### PR TITLE
Modify the date selector to use the session timezone

### PR DESCRIPTION
**Pull request by eskyuu**
Change the date selector to use the timezone defined in the session.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by eskyuu** [comment]
I need to alter submitCustomRange() in html/js/librenms.js to also be timezone aware.

**Comment by eskyuu** [comment]
This version works for me

**Comment by dlangille** [comment]
I'll test this. I started that yesterday, but hit problems with patching - those problem are not for @eskyuu to resolve.

**Comment by dlangille** [comment]
See #15781

**Comment by dlangille** [comment]
I finally got the patch to build here (not the fault of your patch) - by "Modify the date selector to use the session timezone" - should I be seeing local time (based on my laptop) or the Timezone specified in `/preferences` (which I have set to UTC)? I ask because I'm seeing local time in the date picker and on the graph legends.

**Comment by eskyuu** [comment]
Hi Dan,You should see the same timezone in both.  Before this patch the date selector would always be browser local time.I have noticed that new sessions can sometimes revert to the server time.  I need to have a look at why the JavaScript isn't detecting this and updating.  Can you please go into the user settings and change your timezone to anything else, then back to UTC and see if that fixes the timezone for your session.RegardsSteveOn 2 Feb 2024 22:08, Dan Langille ***@***.***> wrote:
I finally got the patch to build here (not the fault of your patch) - by "Modify the date selector to use the session timezone" - should I be seeing local time (based on my laptop) or the Timezone specified in /preferences (which I have set to UTC)? I ask because I'm seeing local time in the date picker and on the graph legends.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/librenms/librenms/pull/15783#issuecomment-1923932612",
"url": "https://github.com/librenms/librenms/pull/15783#issuecomment-1923932612",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dlangille** [comment]
Success! This is great, thank you.

After changing to local time and back to UTC and reloading the page with the graphs, I have UTC in the date picker and on the graph legends.

NOTE: When I select a date range via the date picker and click on `Update`:

* the graph starts at the time the select
* the graph ends at current time
* the `To` field of the date picker is current time

**Comment by laf** [comment]
Thanks @eskyuu, looks and works great.

Would you mind just fixing the style issues (I know you didn't change that part of the code) then we can merge

**Comment by eskyuu** [comment]
No worries - the style should be fixed now.

**Review by electrocret — APPROVED** [review]
LGTM

**Pull request merged**
