### PR TITLE
discovery - LLDPv2 support extension, and discovery-protocols tests

### PR DESCRIPTION
**Pull request by PipoCanaja**
Basically, if LLDP does not give any result, we check LLDPv2 MIB. And if successful, we map the values back to LLDP OIDs so LLDP code continues.

And this PR also adds tests JSON computation for discovery-protocols module.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
I'll try to forge tests based on PaloAlto firewalls. They are using LLDPv2 only.

**Comment by PipoCanaja** [comment]
> I'll try to forge tests based on PaloAlto firewalls. They are using LLDPv2 only.

Test data collected, but as we do not compute discovery-protocols, no json to update.

**Comment by murrant** [comment]
@PipoCanaja might need to add the ability to save json for the module.  For legacy modules, that is set here: https://github.com/librenms/librenms/blob/master/tests/module_tables.yaml

**Comment by PipoCanaja** [comment]
> @PipoCanaja might need to add the ability to save json for the module. For legacy modules, that is set here: https://github.com/librenms/librenms/blob/master/tests/module_tables.yaml

Trying this right now. Looks like it works.

**Comment by PipoCanaja** [comment]
And with LLDPv1 test data from VRP os as well

**Comment by PipoCanaja** [comment]
Hi @murrant 
Seems that it is finally all green here. Ready for review !

**Comment by PipoCanaja** [comment]
Thx @murrant. For some reason tests were stuck.

**Review by murrant — APPROVED** [review]

**Pull request merged**
