### PR TITLE
fix: improve poller validation

### PR DESCRIPTION
**Pull request by murrant**
remove failures when there are duplicate poller entries
add warning that there are duplicate poller entries
link to the poller log in the webui
small fix to getBaseURL() to avoid exception when run from cli.
extract poller validations to private methods for better readability

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Worth applying 212.sql again as another schema update?

**Comment by murrant** [comment]
@laf I dunno maybe, I think it was a timing issue.  This at least reports the correct issues even if there are duplicates.

**Comment by laf** [comment]
I think we should, no harm in doing so and it will save the expected questions we will get asked or at least stop users having to manually fix.

**Comment by murrant** [comment]
Want it in this PR or a separate one?

**Comment by laf** [comment]
This one makes the most sense. Happy to merge straight after that.

**Pull request merged**
