### PR TITLE
Fix all devices menu when no device types exist

### LINKED ISSUE #16167: Issue with Devices Menu Shortcut
### The problem

If you only create ping monitors then the devices page shortcut in the menu is broken and instead sends to the home page.

Unless you manually to go to at least one device and set its type then the devices shortcut will work properly.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.6.0-27-g5ab2f685b (2024-06-28T13:45:50+00:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.1.2-1ubuntu2.18
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.6.0-27-g5ab2f685b - Fri Jun 28 2024 13:45:50 GMT+0000

### Anything in the logs that might be useful for us?

_No response_

### PR DESCRIPTION
**Pull request by jiannelli**
This PR fixes #16167 by improving the Devices Menu:
- Ensuring the "All devices" submenu is always visible.
- Maintaining a consistent label to enhance clarity and user understanding.
- Removing the "No devices" submenu
- Allowing access to the device list when all the devices lacks of device types. 

**Without Devices**
no devices

**Devices without type**
device without type

**Devices with type**
device with type

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I think this is the wrong fix.  The right fix is to fix the actual bug where it shows "no devices" incorrectly.

**Comment by jiannelli** [comment]
> I think this is the wrong fix. The right fix is to fix the actual bug where it shows "no devices" incorrectly.

Could you please clarify what you believe the correct behavior should be in this case? 
For example, when there are devices with no type, what should ideally be displayed?

The behaviour now is:
No devices (no types) -> "All devices" (keeps consistency and if clicked it shows the empty list)
Devices with type -> "All Devices" showing submenu with types as usual
Devices with no type -> "All devices" without submenu becase there are no types to show.

**Comment by murrant** [comment]
The correct behavior:
Devices with no types: All devices shows with no sub menu (This is the case with the bug)
Devices with types: All Devices + sub menu
No devices: No devices

**Comment by laf** [comment]
I've been meaning to fix this, this is my take on it: https://github.com/librenms/librenms/pull/16532

**Comment by jiannelli** [comment]
Improvements after comparing and sharing with @laf and implementing the specified behaviour.
The Screenshot shows the behaviour with no devices, a device without type and a device with type.
devices menu

**Review by laf — DISMISSED** [review]
LGTM. @murrant?

**Review by murrant — APPROVED** [review]

**Pull request merged**
