### PR TITLE
Avoid state collisions between 'dell' and 'drac' OSes

### PR DESCRIPTION
**Pull request by PipoCanaja**
https://community.librenms.org/t/bug-idrac-sensor-discovery/8470

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10539 `
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
LGTM, but will lose historical data.

**Comment by PipoCanaja** [comment]
> LGTM, but will lose historical data.

Should not lose any historical data here. The RRD is not touched, only the state mapping, which does not impact any data.

**Comment by laf** [comment]
> Should not lose any historical data here. The RRD is not touched, only the state mapping, which does not impact any data.

Are you sure? The sensor_type field from the DB is what is used to create the filename and it changes with this.

**Comment by PipoCanaja** [comment]
For me, the RRD file name is created out of the discover_sensor parameters only. And discover_parameter does not have the new modified name. Only the table with the state mapping knows about the new name of the state. 
BUT: 
Seems that it does not create the match properly if both RRD name and state name are not equal :D  so I suspect it does not work. 

I'll do some tests via snmpsim to findout, cause I don't have a DRAC :)

**Comment by PipoCanaja** [comment]
@murrant @laf I need to choose which of the 2 OSes will have state history broken ... Any clue except random :) ?

**Comment by murrant** [comment]
I feel like DRAC is slightly more popular, we could check the stats...

**Comment by PipoCanaja** [comment]
OK. This time, the '$type' part of the discover data is modified, so supposingly the historical data is lost. 
That being said, I don't have any test data for this ...

**Comment by murrant** [comment]
I'm fine with merging without test data for this, but probably needs notification.

**Comment by PipoCanaja** [comment]
Yep, it does. More than test data, I need testers ... I would like to be sure of the behaviour before merging ... IE we need this code to be working, and loose historical data cause RRD is not named the same :)

**Comment by PipoCanaja** [comment]
Hi @murrant 
Been a little bit overloaded lately. In order to close that one, the notification would be : 
" Due to a duplicate name in different Dell MIBs, devices recognised as "dell" os in LibreNMS will loose historical data for the following OIDs : processorDeviceStatusStatus, memoryDeviceStatus, powerSupplyStatus, intrusionStatus, controllerState, arrayDiskState, virtualDiskState, batteryState. ". 
If ok, I'll issue the notification so we can merge this.
Bye

**Comment by murrant** [comment]
Looks ok, maybe mention that it is possible to rename rrds or something.

**Comment by laf** [comment]
@PipoCanaja Any news on the notification so we can get this out?

**Comment by PipoCanaja** [comment]
Hi @laf 
PR for notification created. I'll merge it during the WE unless somebody asks not. Feel free to merge it right away if it LGTY. 
The actual PR #10539 would then be merged Sunday Nov 3rd. 
Bye

**Comment by mikecentola** [comment]
Should we add the latest Dell MIB for OMSA while doing this as well, or do you think it's unrelated?

**Comment by PipoCanaja** [comment]
Hi @mikecentola 
Let's create a dedicated PR for a new device support. This one is "just" targetting an issue between objets in 2 mibs that share the same name, and collision. 
Thanx

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
