### PR TITLE
feature: apps versioning

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

this would imply small changes to snmp extend scripts and polling scripts.
test was done using modified os-updates script.

screen shot 2018-01-07 at 11 51 58 pm

### CODE REVIEW

**Comment by murrant** [comment]
Wouldn't it be better to do this with an alert?  It wouldn't require any custom code.

**Comment by kkrumm1** [comment]
We have alert for this in the Alerts Collection - 
image

**Comment by crcro** [comment]
@kkrumm1 .... it's not about the values returned by apps but about the scripts version itself ... ie: os-updates is now v1, you change it now and add new detection or fix something in script and make it v1.1, the user doesn't know about this change unless let's say he is constantly monitoring librenms-agent repo

**Comment by murrant** [comment]
Oh, interesting idea.

**Comment by crcro** [comment]
i think that this could be the inform part, but still struggling with travis and db change :|

**Comment by laf** [comment]
Not sure why you've tagged me in that :)

I'm not a fan of the applications at all, they are flaky most of the time so I'm not going to get in the way of this PR as I'm in the position that I won't do any work on it anyway.

Having said that I'm not sure this is the right way to go :)

**Comment by crcro** [comment]
Besides your view of apps part :) you have something against maintaining db tables ... if i recall well from past :)

**Comment by laf** [comment]
> you have something against maintaining db tables ... if i recall well from past :)

You don't recall well (or I don't). I can't ever remember this discussion before. However:

  - Easily forgotten about and the table not kept up to date.
  - It gives me the impression that apps are changeable which will most likely lead to loss in data for people. Like the core code we have, it should be done right the first time.
  - Logging that apps are out of date every 5 minutes seems excessive.
  - What do you do about people who have installed a newer version of the app but is running old code (even down to them using the stable release of LibreNMS).

**Comment by murrant** [comment]
I'm not a fan of storing application data in the database.  If this table gets corrupted or changed there is no easy way to fix and if a user changes it, we do not know about that.  Say the table gets truncated, it is just empty forever then.

**Comment by crcro** [comment]
event entries a little more detailed, maybe something to docs should be added also to address a case of outdated app

screen shot 2018-01-09 at 12 34 58 pm

**Comment by laf** [comment]
Personally, this is a no from me.

**Comment by murrant** [comment]
I'm fine with a no too.

As I expressed in the past, we should really be using external solutions for this, such as collectd, but I don't have enough motivation to push that.

**Pull request closed without merging**
