### PR TITLE
Custom Map device images

### PR DESCRIPTION
**Pull request by eskyuu**
This adds a new page where custom map images can be managed, and then alters the custom map editor and viewers to support this new type of image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Tested and works fine, great work as always.

Is it worth now having a sub menu for things like this under Maps?

**Comment by murrant** [comment]
Need to take extra security care when allowing users to upload things. I haven't reviewed this.

**Comment by eskyuu** [comment]
The upload part should be very similar to the background image upload code if that helps.

**Comment by eskyuu** [comment]
Is there any chance of getting an approval for this before the next release, given that the image upload logic is the same as the background images.

**Review by laf — APPROVED** [review]
LGTM.

From a security perspective I can see that a new library is used to sanitise svg files and we at least validate the mime type of the file being uploaded so it seems ok.

I'd still like @murrant to pass his thoughts on.

**Comment by eskyuu** [comment]
I will merge tomorrow if there are no further comments.  It uses the same validation as the background image, so both will need updating if we have a problem.

**Pull request merged**
