### PR TITLE
Add multiples servers into the ldap auth

### PR DESCRIPTION
**Pull request by thunder0666**
Add multiples servers into the ldap auth
example in config.php:
$config['auth_ldap_server'] = ["ldaps://ldap1.example.net","ldaps://ldap2.example.net","ldap://ldap3.example.net"];
the auth ldap chek the uri or not in server name.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7274)

### CODE REVIEW

**Comment by murrant** [comment]
Can't you just use `$config['auth_ldap_server'] = "ldaps://ldap1.example.net daps://ldap2.example.net";`?

**Comment by thunder0666** [comment]
actually i test if the $config['auth_ldap_server'] is a array or not. and i test the server into a loop to find how is alive.
if i use a char like a separator ( usualy coma or space or ???? ) it's a bit more complicated to split a string with a char and create them into a array .
but i you absolutly need that :) .....

**Comment by laf** [comment]
@thunder0666 @murrant is referring to that `ldap_connect()` accepts multiple servers separated by strings so you don't need to do this. I think he does the same in the active_directory auth module:

`You can also provide multiple LDAP-URIs separated by a space as one string`

**Comment by laf** [comment]
@thunder0666 Any comment?

**Comment by laf** [comment]
Feel free to reply here and we can re-open this.

**Comment by thunder0666** [comment]
laf your rigth i delete my repo.
thanks for your attention.

**Pull request closed without merging**
