### PR TITLE
ArubaOS-CX Identification

### PR DESCRIPTION
**Pull request by XxPatrickxX**
Added in definitions for initial ArubaOS-CX detection.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @XxPatrickxX 
Seems that you have a "space" issue in your JSON file. Could you run again the save-test-data and update the json ? 
Thanx

**Comment by PipoCanaja** [comment]
(in order to check that, look at the Travis CI Test. That one must succeed for the PR to be valid. )

**Comment by PipoCanaja** [comment]
Hello @XxPatrickxX 
Looks good to me, thanks !

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
