### PR TITLE
device: more zywall-usg support

### PR DESCRIPTION
**Pull request by tomarch**
Need for new USG device (USG20, USG20W, USG40, USG110, ...)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7405)

### CODE REVIEW

**Comment by laf** [comment]
Thanks @tomarch. Can you add the required unit test please: https://docs.librenms.org/Developing/os/Test-Units/

Preferably one for each of the new devices you are adding support for.

**Comment by tomarch** [comment]
Sure i can.
There's one zywall_1.snmprec for USG300 and one zywall_2.snmprec for USG60
Do i continue with this syntax (zywall_3.snmprec for USG110, etc...) or may i have to rename it (like zywall_usg110.snmprec) ?

**Comment by laf** [comment]
You can use _usg110 and variations of models, that's fine.

**Comment by tomarch** [comment]
I add the files (excuse me for the multiple commit, i'm a git noob).

**Comment by murrant** [comment]
Thanks for the updates @tomarch this was written before we had exclusions, can you updates it to:
```
discovery:
    -
      sysObjectId:
          - .1.3.6.1.4.1.890.1.6
          - .1.3.6.1.4.1.890.1.15
      sysDescr_regex_except:
          - '/^NWA/'
```

That should be a better fix :)

**Pull request merged**
