### PR TITLE
Network map fix Css/img

### PR DESCRIPTION
**Pull request by balkandude**
These are icons for navigation in network map generated by vis-network.js
They are not visible right now because they are missing from LibreNMS

vis.min.css is pointing to img/network/icon.png but url is not present

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
thanks for your PR.
Could you please add a before/after Screenshot, so it's easier to see what you're fixing

**Comment by balkandude** [comment]
The green navigation buttons are invisible on a network map generated by vis-network.js. There is thread on community site
https://community.librenms.org/t/network-map-legend-usage/14694

image

**Review by SourceDoctor — APPROVED** [review]
LGTM

**Comment by murrant** [comment]
@dejantep did not even know those buttons existed :)  Thanks for the fix.

**Pull request merged**
