### PR TITLE
Fixed displaying hostname in create bill when port is passed

### PR DESCRIPTION
**Pull request by laf**
Fixes: https://community.librenms.org/t/cant-create-bill-from-newly-added-device-ports/18286

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jozefrebjak** [comment]
@laf this patch fixed creating new Bill from Port view. It will find interfaces for specified device, but it don't work for creating bill in `Ports->Bills->Crate Bill`. There is no interfaces for the same device as we tried to add via Port view. 

There is also different problem.

This is from Port view creating bill. After patch it works as expected.

Snímka obrazovky 2022-03-07 o 9 42 50

If we just try to specify in dropdown menu different device and then choose previous device interfaces are gone and we can't choose.

Snímka obrazovky 2022-03-07 o 9 45 09

If we try to create bill from `Ports->Bills->Crate Bill` it the same as on the second image.

**Comment by laf** [comment]
I'm sorry but I don't understand what your issue is. This patch fixes only the issue around creating a bill from a specific port. Unless it's introducing a bug then this fix is doing what it's intended.

**Comment by jozefrebjak** [comment]
Ok, so it's better to fix only partial of a problem ? Why to not fix problem with choosing port in bill in one PR ? Is better to make  multiple PR's to fix one problem ?   

If yes, then ok. I'm just tried to describe a whole problem. Maybe on wrong place, sorry.

**Comment by laf** [comment]
I don't understand what your other issue is.

However I only have limited time to work on code for LibreNMS and in this instance, that's all I could do.

**Pull request merged**
