### PR TITLE
Implement an autoloader

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

When cleaning up classes for psr2, things got a bit unwieldy, so I implemented a class autoloader.
I created a PSR-0 compliant LibreNMS directory and moved all classes there that made sense.
Implemented LibreNMS\ClassLoader which supports adding manual class mappings

This reduces the file includes needed and only loads classes when needed.

### CODE REVIEW

**Comment by laf** [comment]
Testing

**Comment by laf** [comment]
500 errors on /devices/ - Hover over any device.

Let me know when resolved and I'll test further.

**Comment by laf** [comment]
https://scrutinizer-ci.com/g/librenms/librenms/inspections/fb8bcf18-a3c8-4efe-90c5-7f9725fe8bd4/issues/files/includes/discovery/functions.inc.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by laf** [comment]
Aside from the scrut issue all good with me. Does it need anything in the docs on using it in development?

**Comment by murrant** [comment]
It only affects class loading.  I'm not sure,  there honestly isn't a lot of classes here.

**Pull request merged**
