### PR TITLE
Enable CSRF protection

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by twelch24** [comment]
I've been running this patch for about 24 hours, no issues so far.

**Comment by murrant** [comment]
Thanks for testing @twelch24

**Comment by twelch24** [comment]
Might have spoken too soon. Ports menu is broken (returns header with empty page). Commenting out line 90 of  includes/html/pages/ports.inc.php restores functionality. ($output .= csrf_field();)

**Comment by murrant** [comment]
Fixed now.  Commenting that makes it so the filtering won't work anymore ;)
The correct fix was to wrap with addslashes()

**Comment by rasssta** [comment]
I have been having some issues on one of my installs that seem to be related to this patch. I have been tracking the issue together with @f0o and when uncommenting https://github.com/murrant/librenms/blob/5166f1254aa4e785f2745aaf317beedf145483c1/app/Http/Middleware/VerifyCsrfToken.php#L22 everything finally works again.

With CSRF security enabled I did not have any widgets on the dash working, nor did eventlog/syslog/devices overview work. Pretty much everything else seem to work though.

Some debugging info from my browser:

**Comment by murrant** [comment]
I can't reproduce that.  Have you ./validate.php on your install?  Also, this is the worst place to discus bugs.

**Comment by rasssta** [comment]
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.54
DB Schema | 2019_07_03_132417_create_mpls_saps_table (139)
PHP       | 7.3.4-2
MySQL     | 10.1.38-MariaDB-0+deb9u1
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.9.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 app/Http/Middleware/VerifyCsrfToken.php

```

**Comment by murrant** [comment]
@rasssta after some googling it seems likely your web server doesn't have write access to the storage folder. Can you check the permissions?

**Comment by rasssta** [comment]
```
# grep librenms /etc/group
librenms:x:999:www-data
```
```
# ls -la storage/
total 24
drwxrwxr-x  6 librenms librenms 4096 Aug  1 10:55 .
drwxrwx--- 30 librenms librenms 4096 Aug  5 22:04 ..
drwxrwxr-x  3 librenms librenms 4096 Aug  1 14:14 app
drwxrwxr-x  2 librenms librenms 4096 Aug  1 14:14 debugbar
drwxrwxr-x  6 librenms librenms 4096 Aug  1 10:55 framework
drwxrwxr-x  2 librenms librenms 4096 Aug  1 14:14 logs
```

As it should be, right?

**Comment by murrant** [comment]
@rasssta yeah, probably selinux or something getting you

**Comment by rgkrw** [comment]
> I have been having some issues on one of my installs that seem to be related to this patch. I have been tracking the issue together with @f0o and when uncommenting https://github.com/murrant/librenms/blob/5166f1254aa4e785f2745aaf317beedf145483c1/app/Http/Middleware/VerifyCsrfToken.php#L22 everything finally works again.
> 
> With CSRF security enabled I did not have any widgets on the dash working, nor did eventlog/syslog/devices overview work. Pretty much everything else seem to work though.
> 
> Some debugging info from my browser:
> 
> 
> 
> 
> 
> 

i have same issue and solved by commenting verifycsrftoken
@murrant

**Comment by murrant** [comment]
@rgkrw this means your install is broken.  Please check that sessions are working. It could be another issue.

**Pull request merged**
