### PR TITLE
webui: Improve sensor graph legend alignment

### PR DESCRIPTION
**Pull request by murrant**
Still not the best ...

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Have you got a before and after?

**Comment by murrant** [comment]
Before:
image

After:
image

**Comment by laf** [comment]
I did:

image

That's on master.

**Comment by murrant** [comment]
@laf that is the wrong place  You have to look at the graph that puts them all together in one graph ;)

This url: `/device/device=2/tab=health/`

**Comment by laf** [comment]
@murrant Yeah but there was no mention of that without looking at which file uses that include :p

**Pull request merged**
