### PR TITLE
Update Table UI

### PR DESCRIPTION
**Pull request by arjitc**
Please give a short description what your pull request is for

Updated up the table UI to match the others in the "Edit" menu

Before,

chrome_2020-05-02_04-46-20

After,

chrome_2020-05-02_05-02-36

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by arjitc** [comment]
ps please ignore the other 3 commits, I had committed a missing image from my repo and then reversed them

**Comment by murrant** [comment]
@arjitc looks good to me.

I'm working to port these pages to Laravel (https://laravel.com/docs/5.8)
See the Latency tab for an example.

**Comment by arjitc** [comment]
@murrant -- can you tell me where the larvel files are located? I did see the app/models folder but couldn't find the Latency tab in there :/

**Comment by murrant** [comment]
app/Http/Controllers/Device/Tabs/LatencyController.php (for code)
resources/views/device/tabs/latency.blade.php (for presentation)

**Comment by murrant** [comment]
Actually, you have been focusing on the settings pages a lot, which require a little additional work to set up the structure (since it has "sub-tabs")

I'll send a PR for that at some point.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
