### PR TITLE
Adding linux_config_files application support

### PR DESCRIPTION
**Pull request by bnerickson**
Adding rpmconf application support.  Associated script PR: https://github.com/librenms/librenms-agent/pull/453

This application executes the rpmconf command and is only relevant for Fedora-based systems that use RPM packages.  Rpmconf knows about rpm configuration file updates when a new (usually major) version of an application is installed and is an administrators method of diff'ing the new configuration file with the old.  It's usually a manual process after that to determine how the new configuration file changes should be merged into the existing configuration file.

This application simply graphs the count of configuration files that are out-of-sync.  An example alert is included that alerts if the number of configs out-of-sync is greater than 0.  Here's a screenshot of the graph:

rpmconf

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by VVelox** [comment]
Hey. Just took a quick look and it looks like you have bits for wireless_ap merged in with this as well. :)

**Comment by bnerickson** [comment]
@VVelox Yeah, this is in draft mode with those changes added assuming they're merged in the future :)

I'll publish this PR at a later date because I need to do a little testing first.

**Comment by bnerickson** [comment]
Stripped out the wireless_ap changes and am publishing this PR after finishing my testing of the rpmconf script.  Should be ready for review now.

**Comment by murrant** [comment]
Other package systems can output a number of config files that need to be updated, perhaps this should be a more generic name?

**Comment by bnerickson** [comment]
> Other package systems can output a number of config files that need to be updated, perhaps this should be a more generic name?

@murrant Sure, how does naming it "linux_config_files" sound?  I'll update the documentation to state that the script only supports Fedora/RPM-based systems for now.  It looks like Debian does things differently (at update you are forced to choose which configs to use).  Gentoo/Portage might have an analogue to rpmconf, but don't know much about it.

**Comment by bnerickson** [comment]
@murrant Updated application name to linux_config_files.  Corresponding script PR updated as well: https://github.com/librenms/librenms-agent/pull/453

**Pull request merged**
