### PR TITLE
Cisco NXOS Bugfix for 16544 (and migration to SnmpQuery)

### PR DESCRIPTION
**Pull request by rudybroersma**
This patch fixes issue [16544](https://github.com/librenms/librenms/issues/16544) for Cisco NXOS. The previous code didn't set a value when calling discover_sensor.
Also migrated the code to SnmpQuery

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by rudybroersma** [comment]
Tests seem to fail on the new transceiver code? I think this is not related to this PR?

**Comment by laf** [comment]
> Tests seem to fail on the new transceiver code? I think this is not related to this PR?

You've regenerated the test data which then doesn't match with the output from the snmprec file, if I generate the json test data using this PR it looks a lot different than what you've got so I'd suggest running it again `./scripts/save-test-data.php -o nxos -v n3k_3064pq`. You also need to save the json test data for the 2 new snmprec files you've added although, you probably don't need the new snmprec files if the existing ones we have cover this test data.

**Comment by rudybroersma** [comment]
I did a reinstall of my LibreNMS instance, I now get the same test result (missing ntp app).
Not sure what to do next

**Comment by PipoCanaja** [comment]
@rudybroersma You should try to rebase your PR to current master. You may be running the tests against a too old code.

**Comment by murrant** [comment]
There is some issue with the NTP app on cisco.
You can remove the "applications" section from your json file for now.  Sorry about the confusion.

**Comment by rudybroersma** [comment]
> There is some issue with the NTP app on cisco. You can remove the "applications" section from your json file for now. Sorry about the confusion.

I removed the NTP app section and the new test data. It passes now

**Review by PipoCanaja — APPROVED** [review]
Looks good, thanx @rudybroersma

**Comment by zagosch** [comment]
I see there are a lot of people having the same issues in different devies. If i look at the NXOS one, this is now solved if i read if correctly? Im not seeing a merge yet, but my guess that this would be available into the next version?

**Comment by rudybroersma** [comment]
> I see there are a lot of people having the same issues in different devies. If i look at the NXOS one, this is now solved if i read if correctly? Im not seeing a merge yet, but my guess that this would be available into the next version?

Someone still has to merge this PR with master. We have to wait for someone with write access to hit the button :)

**Pull request merged**
