### PR TITLE
Transport API - Doc for placeholders

### PR DESCRIPTION
**Pull request by PipoCanaja**
The available placeholders are the same as the Templates documentation but the syntax is not exactly identical.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
@laf Here is a proposal to improve the doc. I would like to avoid writing the complete list of options (verbose) but what do you think ?

**Comment by laf** [comment]
> @laf Here is a proposal to improve the doc. I would like to avoid writing the complete list of options (verbose) but what do you think ?

@PipoCanaja How many are there? It would be good to indicate the list or where to find it.

**Comment by PipoCanaja** [comment]
> > @laf Here is a proposal to improve the doc. I would like to avoid writing the complete list of options (verbose) but what do you think ?
> 
> @PipoCanaja How many are there? It would be good to indicate the list or where to find it.

All the ones that are already defined in the existing doc for Blades templates, except that instead of $alert->xxxxx , you get them with $xxxxx. And the exact list might even depends on the alerts ... I'll check and I'll export a list, we'll see what we get.

**Comment by PipoCanaja** [comment]
@laf More details are now added. A limitation is that there is no way to parse the fault array, contact array, etc etc. Unless we decide to rewrite the blades completely. 
- Should I explicitly write that as well ?
- Should I add more examples ?

**Pull request merged**
