### PR TITLE
Added Additional support for Dell CMC 

### PR DESCRIPTION
**Pull request by takenalias**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by takenalias** [comment]
Sorry, I was unable to run the test data. There is something not quite right with my install. So sorry but hoping someone can run that for me. My apologies there. 

I have added extra support, for CMC controllers. HDD state should now be displayed also the HDD controller state and slot state within the chassis.

I also updated the MIB as the existing one was old.

**Comment by PipoCanaja** [comment]
Hi @takenalias 
We can indeed do it. If you are not in a hurry to get this merged, we would like to solve this issue first : 
https://github.com/librenms/librenms/pull/10539
It could impact this PR.

**Comment by takenalias** [comment]
@PipoCanaja. That's fine with me. Thanks for the heads up and your hard work.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
