### PR TITLE
Added support for excluding devices from Oxidized api

### LINKED ISSUE #2018: Add oxidized ignore flag to devices
It would be very nice if we can add ignore flag to non supported devices by oxidized, for example to all Ubiquiti devices. Right now if we have 1000+ devices, where 800+ of them are Ubiquitis radios and only 200 are Cisco switches it take a long, long time to create a config file for Cisco`s.
If would be awesome to add ignore by default to non-supported devices or maybe opposite - ignore all exept Cisco devices (and other vendors/models from Oxidized site)

### PR DESCRIPTION
**Pull request by laf**
Fix #2018 

This introduces another page into the edit device section called misc. The reason I've not used the device page is because that uses a normal post form, this is now done via AJAX so wanted to ensure no confusion for people.

I've made a generic function that (at present only does checkboxes) you can call to take care of the code for dynamically updating devices_attribs. The function can be expanded out to do other types of input as we get to them.

Users can now select to exclude devices from oxidized via the webui so the api will no longer feed those to Oxidized.

### CODE REVIEW

**Comment by f0o** [comment]
:+1:

**Comment by paszczus** [comment]
yeah!!!! :) thank you @laf

**Comment by masonke** [comment]
That will be great!

**Comment by paszczus** [comment]
@laf maybe there also could be an option to auto add override_Oxidized_disable false for all devices with os = ios and other supported by oxidized?

**Comment by laf** [comment]
@paszczus I'll be doing a PR which will by default exclude certain device types and vendors but allowing it to be user configurable - however we need the notification system to go live as it will mean a change to default behaviour.

**Comment by paszczus** [comment]
@laf ok, thank you.
For now i`ve done:

INSERT INTO devices_attribs (device_id, attrib_type, attrib_value, updated)
select device_id, 'override_Oxidized_disable', 'true', NOW() from devices where os != 'ios';

maybe it will be useful for someone

**Pull request merged**
