### PR TITLE
webui: alerts cleanup / refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

before:
screen shot 2018-01-07 at 5 12 57 am
screen shot 2018-01-07 at 5 13 04 am
screen shot 2018-01-07 at 5 13 13 am
screen shot 2018-01-07 at 5 13 23 am
screen shot 2018-01-07 at 5 13 32 am
screen shot 2018-01-07 at 5 13 39 am

after:
screen shot 2018-01-07 at 5 10 47 am
screen shot 2018-01-07 at 5 11 01 am
screen shot 2018-01-07 at 5 11 17 am
screen shot 2018-01-07 at 5 11 32 am
screen shot 2018-01-07 at 5 11 41 am
screen shot 2018-01-07 at 5 11 50 am

### CODE REVIEW

**Comment by murrant** [comment]
@crcro I know we've already merged this for the devices page, but after you merged the status and name fields, how do you sort by status?

**Comment by crcro** [comment]
@murrant for devices i pushed a PR for enabling sort for status but at this time other pages sort doesn't work properly due to how data is being processed (i may be mistaken)

**Comment by laf** [comment]
I really really don't like the actions menu. It's boring and no longer obvious to create alert rues.

**Comment by crcro** [comment]
You don't like the whole action menu ideea? or it would be ok if instead of simple "links" there were buttons for actions?

**Comment by laf** [comment]
I like the idea of a common place for actions but I don't like the text links. It removes the emphasis on creating alert rules from what we currently have.

**Comment by laf** [comment]
@crcro Feel free to respond to this when you can but for now we are closing down this PR.

**Pull request closed without merging**
