### PR TITLE
Add Cisco Business Wirless to ciscowlc.yaml

### PR DESCRIPTION
**Pull request by nsn-amagruder**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Hi,
would you mind generating test data for this one?

**Comment by nsn-amagruder** [comment]
I added it and changed some of the values to private.  Test failed so not sure if this gives you what is needed or not.

**Comment by Jellyfrog** [comment]
You have removed your other changes, that's why it fails now

**Comment by nsn-amagruder** [comment]
I reran the test data.  How can I safely remove the private information such as Serial Number, IP Addresses, and SSID's before I recommit?

**Comment by Jellyfrog** [comment]
Edit the snmprec (be aware of the format of the data, Ie numbers have to be numbers)
Then rerun the second command of the test data generation, to generate a new json file based on your editedfile

**Review by Jellyfrog — APPROVED** [review]

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
