### PR TITLE
Added discovery for ups-nut status

### PR DESCRIPTION
**Pull request by yon2004**
Added discovery for ups status data works in conjunction with updated client script librenms/librenms-agent#298

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by yon2004** [comment]
Is there anything that I need to do to get this merged ?

**Comment by yon2004** [comment]
I made some alert rules do these seem sane?

| Alert |                                                                                                                                                                                 |
|-------|-------|
|UPS-NUT on battery 										|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSOnBattery" AND macros.state_sensor_warning = 1          |
|UPS-NUT low battery 									|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSLowBattery" AND macros.state_sensor_critical = 1            |
|UPS-NUT high battery									|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSHighBattery" AND macros.state_sensor_warning = 1            |
|UPS-NUT battery needs to be replaced					|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSBatteryReplace" AND macros.state_sensor_warning = 1         |
|UPS-NUT battery is charging								|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSBatteryCharging" AND macros.state_sensor_warning = 1    |
|UPS-NUT battery is discharging							|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSBatteryDischarging" AND macros.state_sensor_warning = 1     |
|UPS-NUT bypass circuit is active						|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSUPSBypass" AND macros.state_sensor_warning = 1              |
|UPS-NUT performing runtime calibration					|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSRuntimeCalibration" AND macros.state_sensor_warning = 1     |
|UPS-NUT offline and is not supplying power to the load	|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSOffline" AND macros.state_sensor_critical = 1               |
|UPS-NUT overloaded										|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSUPSOverloaded" AND macros.state_sensor_critical = 1         |
|UPS-NUT trimming incoming voltage						|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSUPSBuck" AND macros.state_sensor_warning = 1                |
|UPS-NUT boosting incoming voltage						|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSUPSBoost" AND macros.state_sensor_warning = 1               |
|UPS-NUT forced shutdown									|applications.app_type = "ups-nut" AND state_indexes.state_name = "UPSForcedShutdown" AND macros.state_sensor_critical = 1    |

**Comment by SourceDoctor** [comment]
Alert Rules looks good,
please add them to alert_rules.json

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
