### PR TITLE
webui: added opensuse svg logo

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
This looks like it should be in /logos and it needs to be minimized.
http://docs.librenms.org/Developing/Support-New-OS/#icon-and-logo

**Comment by crcro** [comment]
correct, missed that docs part, my bad ...
added logo and icon, minified them also, thanks!

**Comment by laf** [comment]
You need to undelete the os png :)

**Comment by crcro** [comment]
why is that needed if we have the svg?

**Comment by laf** [comment]
We have to areas for logos as per the link murrant added.

html/images/os/ is for the logo we use in the device list, html/images/logos/ are the ones we use for the device page itself.

**Comment by crcro** [comment]
i've added both of them as svg in the second push

**Pull request merged**
