### PR TITLE
api: Added support for wireless sensors

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7742

### CODE REVIEW

**Comment by murrant** [comment]
Nice @laf.   I shouldn't have named the primary key sensor_id, it should have been wireless_sensor_id... oh well.

**Comment by laf** [comment]
> Nice @laf. I shouldn't have named the primary key sensor_id, it should have been wireless_sensor_id... oh well.

No big deal

**Comment by murrant** [comment]
@laf tested.  Add docs and this is ready to merge.

**Comment by laf** [comment]
Thought I had :( Will do.

**Comment by laf** [comment]
Docs done

**Pull request merged**
