### PR TITLE
Center bill graphs

### PR DESCRIPTION
**Pull request by CirnoT**
They do look weird left-aligned since divs they are contained within are full page width.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Can you add a before and after screenshot?

**Comment by CirnoT** [comment]
Before:
before1
before2
before3
before4

After:
after1
after2
after3
after4

**Comment by laf** [comment]
imho I think center aligned looks more odd. I prefer the left aligned one.

**Comment by murrant** [comment]
Maybe if the box around them didn't take up the whole page that would be a better situation.  Not sure it looks better centered either.

**Comment by CirnoT** [comment]
Not really sure making box smaller would make it look better.

**Comment by laf** [comment]
We appreciate the work you put in to the change, UX is really subjective and you'll always get differing opinions I'm afraid.

I'll close this down if no further changes are to be made.

**Pull request closed without merging**
