### PR TITLE
Issued alerts add to the eventlog

### PR DESCRIPTION
**Pull request by neokjames**
Added code to ExtTransports() function to also write an entry to the eventlog to indicate that an external transport has been used to send a notification.

### CODE REVIEW

**Comment by neokjames** [comment]
Example of Eventlog entry:
Issued critical alert for rule 'Pushover Test' to transport 'pushover'

Also associates with the device (via device_id)

**Comment by laf** [comment]
tagging @f0o for thoughts.

**Comment by paulgear** [comment]
I think this is a really good idea - it gives people diagnostic information that their alerting is configured correctly.

**Comment by laf** [comment]
Go for it then :)

**Pull request merged**
