### PR TITLE
fix: top widget multiple instances

### LINKED ISSUE #4739: top devices widget enhancement
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [ ] Please provide as much detail as possible.

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

fix #4739

### CODE REVIEW

**Comment by laf** [comment]
Seems to cause empty widgets for me (for the top devices one that is). Tested on two installs

**Comment by crcro** [comment]
Did you input the number of devices and polling time? (there are no default values)

**Comment by laf** [comment]
No I didn't we need to have defaults in the display prt of the code. We shouldn't make users set the options they don't need.

**Comment by crcro** [comment]
sure, i'll make some default values, would 5 devices with 5 minutes be a good default?

**Comment by laf** [comment]
I'd say 5 devices and 15 mins.

**Comment by laf** [comment]
image

**Pull request merged**
