### PR TITLE
Added basic state details for Infoblox NIOS

### PR DESCRIPTION
**Pull request by FTBZ**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

-------------

Basic sensors for Infoblox NIOS :

- Grid Status
- HA Status

Screenshot 2019-08-30 at 13 50 51
Screenshot 2019-08-30 at 13 50 20

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @FTBZ 
How are you doing ? Any change you can gather some test data for these ? 
++

**Comment by FTBZ** [comment]
Not sure if it's correct, but … done 😃

**Comment by PipoCanaja** [comment]
Looks good for the snmpsim data. Any chance you can run the ./script/save-test-data.php as well ?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
