### PR TITLE
Smokeping folders patch

### PR DESCRIPTION
**Pull request by Negatifff**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Negatifff** [comment]
very strange.
In LibreNMS/Util/Smokeping.php original code has 'else' operand, but codeclimate says - that's incorrect, says that the structure is too complicated - you need to be simpler. Ok, I fix it, but how can this be?

**Comment by Jellyfrog** [comment]
You can ignore that rule, and most other things it says. See it as a helper

**Comment by Negatifff** [comment]
I already corrected the code :). but thanks anyway.

**Comment by Negatifff** [comment]
Prior to this patch, all devices stacked in the root of the rrd folder for smokeping. Because of this, there are very big delays when opening smokeping web ui, when monitoring many devices. This patch improves the structure of the smokeping config by adding folders and web ui process can handle much faster.

Folders are added according to the following logic: 
- if the hostname is not ip, then only the hostname folder will be added, into which the rrd will be added. 
- if the hostname is ip, then the folder will look like this: octet1_octet2 / octet1_octet2_octet3 / ip, into which the rrd will be added.

Such a configuration greatly improves the work of smokeping web ui, adding both speed and orderliness when displaying.
Also, such a structure is supported when displaying charts in the latency tab of the device.
Also added setting to global settings.

**Comment by Negatifff** [comment]
I don't know what codeclimate wants from me.

**Comment by murrant** [comment]
Codeclimate is optional to help detect issues.  Try to minimize it but it isn't expected to get to 0.

Several smokeping patches pending, I can't give much feedback as I don't use Smokeping.  Some look like they conflict.

#11585 #11548 #11651

**Comment by Negatifff** [comment]
Yes you are right. patches will conflict. tell me what is required of me - to close my request and participate in that request? or something else?

**Comment by murrant** [comment]
@Negatifff yep, just give feedback and test on the other PR.  BTW, thanks for all your PRs sorry I haven't been around to help out more.

**Comment by murrant** [comment]
New command merged, closing this.  Reopen if appropriate.

**Pull request closed without merging**
