### PR TITLE
Ircbot fix

### PR DESCRIPTION
**Pull request by robje**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Are you sure this isn't already fixed in master?  Because there was a bug in the 1.68 release.

**Comment by robje** [comment]
> Are you sure this isn't already fixed in master? Because there was a bug in the 1.68 release.

Nope, this was still borken after 1.68 release.

A better solution might be to use sendMessage instead of ircRaw. Though this solves the problem for me (tm)

**Comment by murrant** [comment]
@Olen thoughts?

**Comment by Olen** [comment]
He is right.  I just have not used a key on my channel, so it has never been an issue here.
But as the channel + key is stored as a single, space seperated entry in the config:
`irc_alert_chan = [ '#channel key', '#channel_wouthout_key']` it makes sense to splt on the space and use only the first part as the channel name in the alerts. An irc-channel can never have a space in its name anyway.

Another option would be to restructure the config to so the key can be stored as a seperate entity.  Something along the lines of
`irc_alert_chan_keys['#channel'] = 'key'` 
And then add a check on join to see if there is a key defined, but I don't think it gains much value.

**Review by Jellyfrog — APPROVED** [review]
@robje Tips, next time explain what it actually fixes, belive it or not, we don't know every single thing about the code :)

**Comment by robje** [comment]
> @robje Tips, next time explain what it actually fixes, belive it or not, we don't know every single thing about the code :)

sure, looking back I see I missed adding some explanation. Somehow I skipped reading the first sentence.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1

**Pull request merged**
