### PR TITLE
refactor: Tidy up mibs V-Z

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

I'm pretty certain this won't lead to breaking changes.

For all the mibs I've moved I've grepped the names of them through the entire install dir to make sure:

1. They aren't imported by other mibs in sub directories already.

2. Any OS' that rely on them I faked the os name to localhost and ran pollers to make sure the snmp commands built up the calls with the correct dirs.

This PR adds eatonups definitions, we had code for detection, unit testing and sensors but no definition. It's here because it's part of the mib move.

I've deleted numerous unused mibs, again confirmed by grepping the names of them through the entire install dir which includes check they aren't imported from other mibs.

Added the code back in that allows specifying mib dirs as part of the os definition as we had different vendors share the same mibs so couldn't use groups (UPS mib).

### CODE REVIEW

**Comment by murrant** [comment]
This looks good to me, but I'm not really sure how to test it :(

**Comment by laf** [comment]
Ditto.

I've tried to be as careful as possible by checking the mibs themselves. This one is a bit easier as we don't have to worry about dependencies on another MIB that may be in a different sub dir already.

Tried to limit the damage to sticking with a small number of mibs to start with.

**Comment by murrant** [comment]
Nothing broken on my setup.  Merging.  @librenms/reviewers Keep an eye for reports.

**Comment by laf** [comment]
Thanks, will hit some more in the morning

**Pull request merged**
