### PR TITLE
Discovery YAML: do not implicitly append $index

### PR DESCRIPTION
**Pull request by murrant**
Require it explicitly. Makes it easier to understand and matches the style of other values

Questionable YAML changes (either broken before or now broken):
secureplatform: haStatCode
ptp600: receiveModulationMode

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Out of interest why do you prefer to have to specify `{{ $index }}`. It's just more to write in the file which means it's more error prone for things like spelling mistakes, missing brackets etc.

**Comment by murrant** [comment]
Often people don't understand that the index is appended to the end.  Also, many other places require {{ $index }} to be specified, this is the only place that adds it.

**We gain a lot of clarity and consistency for just a little extra verbosity.**

**Comment by laf** [comment]
> Also, many other places require {{ $index }} to be specified, this is the only place that adds it without that.

In yaml this came first. You added {{ $index }} in processors :p Needs a rebase anyway. I've personally never come across a PR that has added it by my mistake.

**Comment by murrant** [comment]
I can think of at leaat four people asking in chat why discovery worked and polling didn't, with the cause being an incorrect oid because they didn't know index is appended.

I'd like to remove that friction.  I think this is the best way.

**Pull request merged**
