### PR TITLE
add AIX detection running std snmpd or net-snmp

### PR DESCRIPTION
**Pull request by fbourqui**
fix issue #10199

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10569`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by fbourqui** [comment]
Travis CI, is complaining about :
OS dell-os10: Discovered storage data does not match that found in tests/data/dell-os10.json

Can I disable this dell storage sub-module from storage module in my aix.yaml ?
AIX will never be installed on a Dell or HP server.

**Comment by PipoCanaja** [comment]
Hi @fbourqui 
Thanx for your PR ! 
The storage test will be solved via #10574 . Then we'll be able to run tests on this one. After a quick look, it looks good. 
Stay tuned.

**Comment by PipoCanaja** [comment]
Hi @fbourqui 
Thanx for your PR, and sorry for the delay with the Travis tests. 
Happy monitoring :) !

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-55-release-changelog-august-2019/9428/1

**Pull request merged**
