### PR TITLE
OS support for Cisco/Tandberg Video Conferencing Endpoints

### PR DESCRIPTION
**Pull request by adaniels21487**
- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

- OS support for Cisco/Tandberg Video Conferencing Endpoints

### CODE REVIEW

**Comment by adaniels21487** [comment]
resolves #4062

**Comment by murrant** [comment]
Needs merge.

**Comment by laf** [comment]
Merge? Presume you mean rebase? @adaniels21487 bump

**Comment by adaniels21487** [comment]
rebased.

**Pull request merged**
