### PR TITLE
refactor: small function cleanups

### PR DESCRIPTION
**Pull request by murrant**
found while working on my snmp refactor
mac_clean_to_readable is about 33% improvement
hex2str is a moderate improvement

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
I'm never sure if we should be test all functions but this one seems like we should as we rely on the output. If you agree then:

```
diff --git a/tests/CommonFunctionsTest.php b/tests/CommonFunctionsTest.php
index 9041d43..70da2e9 100644
--- a/tests/CommonFunctionsTest.php
+++ b/tests/CommonFunctionsTest.php
@@ -83,4 +83,10 @@ class CommonFunctionsTest extends \PHPUnit_Framework_TestCase
         $data = 'Toner, S/N:CR_UM-16021314488.';
         $this->assertEquals('Toner, S/N CR_UM-16021314488.', safedescr($data));
     }
+
+    public function testCleanMac()
+    {
+        $this->assertEquals('00:00:0c:9f:f1:f8', mac_clean_to_readable('00000c9ff1f8'));
+    }
+
 }

```

If not just merge it as I've tested the mac_clean_to_readable() function which works as expected.

hex2str() isn't used anywhere so we could just bin it off......

**Comment by murrant** [comment]
I actually used these in my snmp rewrite, Instead of committing there, I pushed it upstream.  I can add tests.

**Comment by laf** [comment]
It was more a question of should we have tests for things like this? I've included a working test above unless you want to extend it further.

Either way feel free to merge this :)

**Comment by murrant** [comment]
The amount of refactoring for functions like this is likely small, but also the amount of time added by the test is extremely minimal.

**Comment by murrant** [comment]
Huh, I thought I pushed tests to this...

**Pull request merged**
