### PR TITLE
Support for Huawei SMU11B

### PR DESCRIPTION
**Pull request by sunblade**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Congratulations on your first PR!

Does "SMU11B" Really needs to be it's own OS? Could we maybe create a more generic OS name?

**Comment by sunblade** [comment]
> Congratulations on your first PR!
> 
> Does "SMU11B" Really needs to be it's own OS? Could we maybe create a more generic OS name?

**Comment by PipoCanaja** [comment]
Hi @sunblade 
As @Jellyfrog already asked, could you check if a more generic name could be used ? Something that would fit multiple models of rectifiers for instance ? 
"huawei-smu" would allow more devices, and exact devices type can be loaded in the hardware and variant fields of the device.

**Comment by jozefrebjak** [comment]
@sunblade I agree with @PipoCanaja & @Jellyfrog. We already have os for SMU devices. We just need to add new `sysObjectID` to an existing discovery and add new device type snmprec for tests. What I saw it's almost a copy of my original discovery of Huawei SMU. I will try to test what you added in discovery and make a new PR for support of SMU11B if it's ok

**Pull request closed without merging**
