### PR TITLE
fix: Cleanup printing ifAlias

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #2666
Fixes: #2703

Not sure this is the best way to do this.

Updated display() function to use stripslashes twice. Reason for this is when ifAlias returns \"something\" we store \\something\\ (we strip " in snmp_walk() function. So we are then left with \something\ where as now we should just have something.

Other options to deal with this are:
1. Update ports poller to strip out \ as well. We have the same issue anywhere else though.
2. Strip out \ in snmp_walk response but does this have a negative impact anywhere else?

This option is the safest way but welcome to suggestions.

### CODE REVIEW

**Comment by laf** [comment]
Yes, if you have a " in the description for cisco devices it comes back with \" which then turns into \\\" so a single strip still ends up in \"

**Comment by f0o** [comment]
Wouldn't a preg_replace on '//+' be more efficient?

**Comment by laf** [comment]
Possibly

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
You'd still need to run stripslashes as well as doing a preg_replace so I'm not sure I see the savings with doing that.

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
Rebased

**Comment by laf** [comment]
rebased, display() function was updated in another PR so this should no longer be a concern with double stripslashes().

**Pull request merged**
