### PR TITLE
Fix errors for some devices loading components

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/error-when-viewing-f5-device-pages/11896/8

**Comment by zoeloe** [comment]
Is it me or is there something wrong here ?:
(AM I specifying the wrong pr_id ?)

librenms@librenms:/opt/librenms$ ./scripts/github-apply 11527

Checking patch LibreNMS/Component.php...
Checking patch app/Http/Controllers/Widgets/TopDevicesController.php...
error: while searching for:
    protected $defaults = [
        'title' => null,
        'top_query' => 'traffic',
        'sort_order' => 'asc',
        'device_count' => 5,
        'time_interval' => 15,
        'device_group' => null,

error: patch failed: app/Http/Controllers/Widgets/TopDevicesController.php:47
error: app/Http/Controllers/Widgets/TopDevicesController.php: patch does not apply
Checking patch app/Models/Component.php...
Checking patch app/Models/ComponentPref.php...
Checking patch app/Models/ComponentStatusLog.php...
Checking patch app/Models/DeviceAttrib.php...
Checking patch database/factories/ModelFactory.php...
Checking patch tests/Unit/ComponentTest.php...

librenms@librenms:/opt/librenms$ ./daily.sh 
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updated from 25330646f to c1c95ffda                OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK

librenms@librenms:/opt/librenms$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.63-42-gc1c95ffda
DB Schema | 2020_04_13_150500_add_last_error_fields_to_bgp_peers (164)
PHP       | 7.2.24-0ubuntu0.18.04.3
Python    | 3.6.9
MySQL     | 5.7.29-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.10.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by murrant** [comment]
@zoeloe rebased, patch will apply now.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
