### PR TITLE
Use the new locks for schema updates

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

No code changes inside the block (try ?w=1 on the github url)

Thanks @keeperofdakeys

### CODE REVIEW

**Comment by laf** [comment]
@keeperofdakeys  @murrant I've removed the discovery one as it's not needed as we already do the check in sql-schema/update.php

**Comment by murrant** [comment]
@laf I don't think that is what the discovery lock was for.  I remember someone having long running new device discovery.

On this PR, do you think we should make it wait before continuing or just continue straight away like it is now?

Also, will this work for distributed pollers?

**Comment by laf** [comment]
@murrant The long running issue was multiple stacked new discoveries which https://github.com/murrant/librenms/blob/c8c6bd0f1f410b1a5c75d81f34071f24080f2da8/discovery.php#L36 fixes.

I don't think waiting is the best option really

**Comment by keeperofdakeys** [comment]
If you're concerned about distributed pollers, you could use mysql named locks (`GET_LOCK()`) for schema updates.

**Comment by murrant** [comment]
@laf Oh, I didn't even know that was there.  Read your comment on mobile and didn't notice the change. 👍 

@keeperofdakeys That's what we would have to do, but the question is are we concerned about distributed pollers?

**Comment by murrant** [comment]
As for the waiting, I don't think it is the best thing either.  But do realize I mean wait with a timeout and periodically while waiting check the lock.

**Comment by laf** [comment]
I guess we have 4:59m to play with before a new discovery process is kicked off so go for it. 30 seconds maybe?

**Comment by murrant** [comment]
@laf we could use this to do per-device discovery/polling locking like the python poller service does.

**Comment by laf** [comment]
@murrant The mysql locking here, how does that work for replicated mysql or mysql clusters?

**Comment by murrant** [comment]
@laf From the MySQL docs:
```
This function is unsafe for statement-based replication. A warning is logged if you use this function when binlog_format is set to STATEMENT.
```
So, assuming that is not the case, things should work.  I don't have access to either of those setups at this time.

**Comment by laf** [comment]
@f0o Any thoughts?

**Comment by keeperofdakeys** [comment]
For flock, I'd remove the `LOCK_NB` bitmask if you wanted to wait forever.

**Comment by laf** [comment]
@murrant Ready for another test?

**Comment by murrant** [comment]
Yeah, passed my tests.  With the 30s wait they all run, but not concurrently.  I set it to 0 to check that again.

**Comment by laf** [comment]
@f0o Any comments on this?

@murrant Is the MySQL lock actually used here?

**Comment by murrant** [comment]
@laf not anymore

**Comment by laf** [comment]
What's the need for `LibreNMS/MysqlLock.php` then?

**Comment by murrant** [comment]
None, I can dump it but it works fine as long as there is not statement based replication or galera

**Comment by laf** [comment]
Testing overnight.

Just needs the mysqllock stuff removing from test unit. I can do that tomorrow if you don't get round to it.

**Comment by murrant** [comment]
Thanks @laf

**Pull request merged**
