### PR TITLE
Fix smartos-dcp-m.yaml

### PR DESCRIPTION
**Pull request by electrocret**
Appears to have been a typo

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Can you add skip_value: -99 (or -990 whatever it is)?  This many sensors for ports without modules is ridiculous :D

**Comment by electrocret** [comment]
I'm actually done with this PR now. 

Thought I'd do some prettying up since I was tinkering with it.

**Comment by electrocret** [comment]
Alrighty, _now_ I'm done. (And if I'm not, I'll open another PR 😄 )

**Comment by electrocret** [comment]
Alrighty, this commit is ready. Someone please approve and merge before I find something else to nit pick about it. @murrant @Jellyfrog @VVelox 😄

**Review by VVelox — APPROVED** [review]
Hmm, looks good to me. I am not seeing anything that looks crazy or the like off hand, but I'm by far not the most familiar with this area of discovery.

So likely would be good to have some one take a second peak at it.

**Review by PipoCanaja — APPROVED** [review]
LGTM indeed, as far as I can tell without owning a device :)

**Pull request merged**
