### PR TITLE
adding/updating Nokia SR OS R23.3 MIBs

### PR DESCRIPTION
**Pull request by eimann**
Updating Nokia SR OS MIBs to R23.3

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
We try to avoid adding mibs we don't use

**Review by laf — COMMENTED** [review]
Any reason you have deleted TIMETRA-SYSTEM-MIB as that's being used by the timos discovery.

**Comment by peelman** [comment]
As soon as 23.10 drops i'll get updated MIBs and revised tests in for this.

**Comment by murrant** [comment]
Closing for now.  Please send MIB updates when you are ready.

**Pull request closed without merging**
