### PR TITLE
webui: Improve device header layout

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
If this PR is acceptable, I'd like to merge it before the release.

**Comment by laf** [comment]
I'm fine with this. It has moved the location info back next to the logo - does this not mean that jumps around again when the logo size changes? We've only just moved it that's all.

**Comment by murrant** [comment]
@laf No, they stay put once there isn't enough room, the graphs bump down.  If there isn't enough room for the text next to the logo, it goes underneath the logo.  You can check that pretty easily on the CI site.

The only odd thing is the graphs are on right side when they are underneath the logos.

**Comment by murrant** [comment]
The space between the logo and the text bothered me.  The responsive behavior was poor.

**Pull request merged**
