### PR TITLE
Docs: Add instructions for PHP 8.1 and Ubuntu 22.04

### PR DESCRIPTION
**Pull request by Jellyfrog**
Also removes composer package, it's too old in most distros anyway

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ottorei** [comment]
Testing an uppgrade path from 20.04 -> 22.04 on existing installation. So far upgrading pollers seems to be quite straightforward:
1. Stop and disable librenms-service
2. Issue the do-release-upgrade -d
3. Install the required packages. 
4. Change PHP cli php.ini as docs suggest
5. Reboot, enable and start the librenms-service.

The DB server which hosts the SQL and RRDCached "should" not require anything special but I have not tested this yet.

**Comment by ottorei** [comment]
@Jellyfrog Are there any notable changes in PHP8.1 OPcache settings?

**Review by VVelox — APPROVED** [review]
Looks good to me.

That said we likely probably want to pull CentOS 6 entirely as well as some of those older Ubuntu ones given as it currently stands outside of lots of custom repo or compiling stuff, it will be impossible to meet the current dependency requirement.

**Comment by VVelox** [comment]
Also not CentOS 6 is EOL now as well.

**Comment by murrant** [comment]
Might be worth adding AlmaLinux/Rock Linux in place of CentOS

**Comment by murrant** [comment]
How long are we going to keep Ubuntu 20.04 on there?  When the minimum php version increases, we could either add instructions for installing 8.1 on 20.04 or just remove it.

**Comment by Jellyfrog** [comment]
> How long are we going to keep Ubuntu 20.04 on there? When the minimum php version increases, we could either add instructions for installing 8.1 on 20.04 or just remove it.

I did add 8.1 for 20.04, and it gets support until middle 2024, so we can keep it for a while, packages are new enough in it

**Review by murrant — APPROVED** [review]

**Pull request merged**
