### PR TITLE
Added Clickatell and PlaySMS Transports

### PR DESCRIPTION
**Pull request by f0o**
#2089 

Putting a blocker here, It's untested.
@starnetwork please test these two transports if you can.
I try to get a throwaway phone next week or so and do some tests as well.

### CODE REVIEW

**Comment by starnetwork** [comment]
Hi,
just upload both transport.playsms.php transport.clickatell.php
files to includes/alerts
should I see it now under Global Settings -> Alerting settings?
asking since I don't see it there...

**Comment by starnetwork** [comment]
also, the test PR is not working at https://2104.ci.librenms.org or with http://

**Comment by laf** [comment]
@starnetwork You won't see it in Webui as additional code needs to be done, you would need to configure this within config.php.

**Comment by starnetwork** [comment]
Hi,
I added that, but I didn't get any notifications after device went down
I set the following alert, attached as screenshot
http://postimg.org/image/9xrqb0e6p/full/
but maybe I did something wrong since the overview -> alerts -> notifications is clean
and also the historical logs is clean...

Regards,

**Comment by laf** [comment]
%devices.status = 0 

That will trigger down :)

**Comment by starnetwork** [comment]
thanks @laf , I did it but still same
2015-10-18 16:40:15	Device status changed to Down	
2015-10-18 16:10:03	Device status changed to Up	
2015-10-18 16:05:11	Device status changed to Down	
2015-10-18 14:15:02	Device status changed to Up	
2015-10-18 14:10:12	Device status changed to Down
still overview -> alerts -> notifications is clean
and also the historical logs is clean...

**Comment by laf** [comment]
What's the full rule as that looks like it's still not matching that device.

**Comment by starnetwork** [comment]
here is the full img: http://postimg.org/image/9kkq0fqc3/full/

**Comment by f0o** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

You have set 5 minutes delay so an alert is triggered on the 6th minute.

Looking at your log from earlier you havent given it enough time to meet your delay constraint.

```
2015-10-18 16:10:03 Device status changed to Up 
2015-10-18 16:05:11 Device status changed to Down
```



On October 19, 2015 6:00:03 AM GMT+02:00, starnetwork <notifications@github.com> wrote:
>here is the full img: http://postimg.org/image/9kkq0fqc3/full/
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/pull/2104#issuecomment-149092775
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5MhxEYW5pZWwgUHJldXNza2VyIChNb2JpbGVLZXkjMikgPGYwb0Bs
aWJyZW5tcy5vcmc+BQJWJJJRAAoJEJMZKtVWOFzBM3MQAIO+N3dxRryTBwj9nEcl
m5j4KOtUfQrEH2gpjO8c24cl0JgB4lItMCRgzJcSITYybuUyAfZlFzmwZjHCIjey
ATHGfkgSgffDVSgWSaakO5In7huVD0gFj8pr7d0lqIJBYN7pWkHjgzrGMQr22+jx
eW3MNQGFnXT5O7doh//I4MWBhkfruLx4SszpMpFGrDqBxbucMme0kkGSGH8Koo53
0JWBdanNe5sk5ZFHqaB3t7koT46Ml/Z3yXXiBLt3Rb7dM9OoYQvCmDIEfOU2v7QQ
fK5TVeI9RiQjxD8uFOkP+WkUJLYUTx2nLmAVpnu/g9uFOGMFCv+qXeJ8xiaCFCJD
h4lPdoJ+dUqxgwXUBAR2FBMFNlJguDYq3NLzj9MJSA37XeekZVLd/SBtbuD38p1F
/sMcerRCuKwZAEI6dDHKGyLKXnwc1okXC0sXU/15PZSoWb18YXyEk+KqkQTP6vTd
0/MdnvTJOpfHkdzB+3PdwG4yrQHTKws+TxvLKPRqpT03W9DSRj1gonbE4bEWFzcx
P2KFRIRwTEwueVu5y5P7F0U91ac/qXVwuIjivTXL+EcgzvDnPi4v2ghHE+MGV+Hj
CKEBpj6Ns0omYWk04FaJ0Tkx24x93HvGgVwlRwAO4om37ROglyGyv54imyFYLxnM
bBJ7u9uW8nz8qdPMiRDxmD6I
=uVts
-----END PGP SIGNATURE-----

**Comment by starnetwork** [comment]
thanks!
now I see it under  Historical Log, but not under notifications, and I didn't get any notification
added the config files to config.php

**Comment by f0o** [comment]
@starnetwork any chance you could swing by IRC to coordinate this a bit better?
we're at Freenode on ##librenms :)

**Comment by starnetwork** [comment]
Hi, tested and work for both gateways
thanks for all your support!

**Comment by f0o** [comment]
Only UI left :)

**Comment by f0o** [comment]
bump for UI help :)

**Comment by laf** [comment]
:+1: from me. If someone can check WebUI PR so we can merge at the same time that would be awesome.

**Comment by laf** [comment]
Just a reminder to add the VictorOps code to this branch @f0o

**Comment by laf** [comment]
https://github.com/laf/librenms/blob/441ac6db9463935cba39bea72bc1de91b948cdcd/includes/alerts/transport.victorops.php

**Pull request merged**
