### PR TITLE
Extra VLAN mapping in AOS specific FDB module

### PR DESCRIPTION
**Pull request by joseUPV**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
I'm working to support get vlan from aos devices.
This is based in PR #11132.

**Comment by joseUPV** [comment]
AOS6 Works vlan but fails port, working on port_id dictionary.
AOS7+ Works vlan and port but there is not vlans in database because module vlans is not working.

**Comment by joseUPV** [comment]
Ready to merge.
Added FDB script for AOS devices (AOS6 and AOS7+)
Added vlan script for AOS7+ devices (AOS6 uses qbridge)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
