### PR TITLE
Adding support for Cisco SB SG350X-24 switch

### PR DESCRIPTION
**Pull request by eimann**
This PR adds support for sysObjectID .1.3.6.1.4.1.9.6.1.94 to properly detect Cisco SG350X-24 in the ciscosb discovery module. It does not yet detect fan and stack status nor temperature.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7305)

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR, can you add a unit test as well so we can ensure future changes don't break detection: https://docs.librenms.org/Developing/os/Test-Units/

**Comment by doc-nl** [comment]
Shouldn't this be 1.3.6.1.4.1.9.6.1.91 ?

(according to: https://www.cisco.com/c/dam/en/us/td/docs/net_mgmt/prime/infrastructure/3-2/supported/devices/PI32-Supported-Device-List.xlsx )

**Comment by eimann** [comment]
I do not see SG350X in this list?

**Comment by doc-nl** [comment]
You are right, I deleted my comment, I found another list on the support site which is more complete

https://sbkb.cisco.com/CiscoSB/GetArticle.aspx?docid=ee0088b38ca048ca8435ab7ea460e325_h_5512.xml&pid=2&converted=0&offline=0

which gives .91 for the sg350xg and .94 for the sg350x 

in #7250 I made a list of all OID's which should be added

**Comment by laf** [comment]
@eimann Are you able to update this PR?

**Comment by laf** [comment]
Merged in with #7353

**Pull request closed without merging**
