### PR TITLE
Fix dbm calculation to return -60 instead of 0

### PR DESCRIPTION
**Pull request by electrocret**
0 dbm is the wrong value to replace 0 mw with. 1mw = 0 dbm. It should be -60 since that's where most vendors have their low/no light to. Which equates to .000001mw, which is past the margin of error for all equipment I'm aware of.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by electrocret** [comment]
Fix's PR #14771

**Comment by Jellyfrog** [comment]
You need to fix the failing tests manually.
you can ignore the ones diffing like this:
```diff
-            'sensor_prev' => 0
+            'sensor_prev' => 0.0
```

**Comment by electrocret** [comment]
@Jellyfrog , I finally fixed all of the tests.

**Review by Jellyfrog — DISMISSED** [review]
this changes way to many unrelated things in the test data.

**Comment by electrocret** [comment]
Ah, yep. Looks like the changes got away from me. The Github tests weren't helpful cause they didn't provide enough info on which OID was the issue, so I was blindly making changes. I ended up just applying the patch to my dev Libre, then regenerating test data.

**Comment by electrocret** [comment]
I just reverted the files back to what they currently are in the project, then replaced all the values that changed to -60 in order to pass the test from the last time you reviewed this PR to -60 in the current project test data. It's now failing again. Something is off. Maybe the snmprec doesn't match the json data file?

**Comment by electrocret** [comment]
I've now changed everywhere that has the user_func of mw_to_dbm and a sensor_current value of 0 to -60, and we're still failing....

**Comment by murrant** [comment]
The code is no longer working?

**Comment by electrocret** [comment]
> The code is no longer working?

Code is working, Tests are failing.

**Comment by murrant** [comment]
> > The code is no longer working?
> 
> Code is working, Tests are failing cause calculation is returning a different 0 mw to dbm value, and errors don't provide enough data to identify which data point is the issue.

The value will be 0 during discovery, then your expected value during polling.

**Comment by electrocret** [comment]
Finally got the tests working.

**Review by murrant — APPROVED** [review]

**Pull request merged**
