### PR TITLE
detect OpenBSD sensors

### PR DESCRIPTION
**Pull request by sthen**
This adds the MIBs for OpenBSD's snmpd, and code to detect sensors exported via OPENBSD-SENSORS-MIB. (The standard kernel supports many sensor types - on-board, USB, onewire, IPMI - and exports via a standard sysctl interface which is picked up by snmpd).

### CODE REVIEW

**Comment by f0o** [comment]
Could you please split up all the sensors in the existing structures?
`/includes/discovery/{current,fanspeeds,frequencies,humidity,power,temperatures,voltages}/__os__.inc.php`

**Comment by sthen** [comment]
Is that really preferable? I took the same approach as the existing sensors-netscaler.inc.php and entity-sensor.inc.php files, which deal with the same situation (SNMP server exporting a single table of sensors with all different types together).

Looking at existing discovery code from the type-specific subdirectories, these seem to be for devices which has a separate table per sensor type, e.g. lm-sensors has lmTempSensorsDevice and lmFanSensorsDevice, mikrotik has mtxrHlActiveFan, mtxrHlTemperature and mtxrHlVoltage, etc.

If it were split into subdirectories we'd need to loop through the table multiple times, once to pull out temperature sensors, once for voltages, etc. It's possible of course, but seems much less efficient.

**Comment by f0o** [comment]
kk makes sense :+1: 

Could you just post the link/s to the MIBs here so we have them `for the log`?

**Comment by sthen** [comment]
Certainly - they're mainly distributed as part of OpenBSD, so probably the best link is to the source repo so if they're updated you can pick up newer versions - http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/share/snmp/

**Comment by sthen** [comment]
nice, thanks :)

**Comment by f0o** [comment]
thank <you> for contributing :)

**Pull request merged**
