### PR TITLE
Delete skip_values in yaml for Panduit vendor

### PR DESCRIPTION
**Pull request by kruczek8989**
Delete skip_values in yaml for Panduit vendor

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Why do we no longer need to skip these sensors?

**Comment by kruczek8989** [comment]
> Why do we no longer need to skip these sensors?

Because this causes problems with reading data from the device regarding the power supply voltage sensor. There are several sensors in the device and the one that shows the actual value is skipped by the "skip_values" parameter, I didn't notice it before when I added this vendor :)

**Comment by laf** [comment]
So I generated some updated test data with what we have and the descriptions no longer work as the OID that was used to skip things previously mustn't return data all the time:

`Group . Voltage`

Can you generate some test data from your device for us to see please: `./scripts/collect-snmp-data.php -h HOSTNAME -v '2'

**Comment by kruczek8989** [comment]
@laf I uploaded generated data from device ;)

**Comment by laf** [comment]
So the skip_value is in place because the sensor with no name aren't valid.

You need to change:

```
                             op: 'not_contains'
                             value: 'B'
```

To

```
                             op: '='
                             value: '.'
```

So that we still skip invalid names but the names starting with L in your test data will be discovered.

Can you please make that change in the 3 areas of the discovery file please.

**Comment by laf** [comment]
I've made the changes, just waiting on tests now.

**Review by laf — APPROVED** [review]
LGTM and thanks for the contributions.

**Pull request merged**
