### PR TITLE
Add alert_details script for easier toubleshooting

### PR DESCRIPTION
**Pull request by theochita**
This script will make alert troubleshooting easier by providing a simple way to output alert specific details.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
This should be built as an artisan command, https://laravel.com/docs/8.x/artisan#writing-commands

**Comment by murrant** [comment]
Also, why a script and not just something in the webui?

**Comment by theochita** [comment]
@murrant Hi,
I was unsure what it would look like so it was easier to make a script for it, thinking i could add the webui at a later point.
Would love to hear suggestions though :)

**Comment by murrant** [comment]
Just a button/clickable icon on the alert that says details.  Brings up a modal with the json data.

**Comment by theochita** [comment]
I will take a look at doing something like murrant suggested.

**Pull request closed without merging**
