### PR TITLE
New os ray

### PR DESCRIPTION
**Pull request by erotel**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR.

The two sensors need to be moved to yaml (see our docs). If you need help with this then let me know.

**Comment by erotel** [comment]
Move sensor to yaml not work.

**Comment by laf** [comment]
Why?

**Comment by erotel** [comment]
Ray have broken snmp.Not return oid index. return etc. sysuptime =X not sysuptime.0 = X.

**Comment by laf** [comment]
At some stage we won't be using php to do discovery so you will need to raise this to the vendor to get fixed,

**Comment by murrant** [comment]
@erotel laf means the temperature and voltage sensors.

**Pull request merged**
