### PR TITLE
limit perf array index length to 19 characters due to limitation in ds-name rrdtool

### PR DESCRIPTION
**Pull request by infotek**
limit perf array index length to 19 characters due to limitation in ds-name rrdtool. nagios plugin check_mysql has performance counters that exceed a 19 character limit found in rrdtool.

### CODE REVIEW

**Comment by laf** [comment]
This needs a little more safety checks in. This at the moment has the chance that two DS' will have the same name if we just strip additional chars off. The new 19 char long name should be compared to the array to see if it exists and if it does, it will need changing again.

**Comment by laf** [comment]
p.s some code formatting issues are flagged by Travis, these will also need fixing.

**Comment by infotek** [comment]
I thin I have address the issues concerning name collisions and style.

**Comment by infotek** [comment]
https://github.com/librenms/librenms/issues/4729

**Comment by laf** [comment]
I was trying to figure out how best to deal with this and the approach is right but I think it could be simplified in just using the service_id from the DB table. It's available as `$service['service_id']` as the 19th char. It's always going to be unique so we avoid clashes. The only time this causes an issue is if someone removes a service and re-adds (but only if the name was > 19 chars anyway).

That would reduce the loops down and make things a bit cleaner - @librenms/reviewers ?

**Comment by infotek** [comment]
After some discussion on irc. service id can be greater than 9 and does not offer sequential numbering to differentiate multiple performance counters per a single service.

**Comment by murrant** [comment]
Remember that the number and order of datasets in an rrd basically needs to be fixed.  The only time the dsname is used is when generating graphs.

dsnames not only need to be unique, but they need to be stable and deterministic.

**Comment by laf** [comment]
I've just rebased this ready for merge but then did realise - we have no way to actually view the data in graph format as services doesn't seem to have that support or am I missing something.

**Comment by infotek** [comment]
I would like to try and solve this in a slightly different manner.  I think there is a chance that the array order will be rearranged.  The problem with that is, during the update cycle the order numbers applied would go to the wrong field. example the following service oerf names:

short,reallylonglonglonglong,other

the rrdcreate command will be run with a field order of

short,other,reallylonglonglong0

But the rrdupdate commands will continue to place values in the original order.
I and going to add another value to the array when dealing with the length to avoid the ordering issue.

**Comment by infotek** [comment]
My mistake.  That is the fixed version... You can check functionality with the following code:

`<?php

$perf = array
(
    Qcache_free_memory => array
        (
            value => 15848240,
            uom => ''
        ),
    Qcache_inserts => array
        (
            value => 42685,
            uom => c
        ),
    Qcache_lowmem_prunes => array
        (
            value => 0,
            uom => c
        ),
    "Qcache_qu@eries_in_cachepurple" => array
        (
            value => 5390,
            uom => c
        ),
    "Qcache_qu@eries_in_cache" => array
        (
            value => 1,
            uom => ''
        ),
    "Qcache_qu@eries_in_cac4e" => array
        (
            value => 2,
            uom => ''
        ),
    "Qcache_qu@eries_in_cac3e" => array
        (
            value => 3,
            uom => ''
        ),
    "Qcache_qu@eries_in_cac2e" => array
        (
            value => 4,
            uom => ''
        ),
);

print_r($perf);

        foreach ($perf as $k => $v) {
            $ds_name = preg_replace('/[^a-zA-Z0-9_]/', '', $k);
            if ( strlen($ds_name) >= 19 ) {
                $ds_name = substr($ds_name,0,19);
                echo( $k . " exceeds 19 characters, renaming to " . $ds_name . "\n");
            }
            if ($ds_name != $k) {
                // ds_name has changed. check if ds_name is already in the array
                echo("ds_name = " . $ds_name . "\n");
                while(isset($perf[$ds_name])){
                    echo($ds_name . " isset\n");
                    for( $i = 0; $i<2; $i++ ){
                        echo("i = " . $i . "\n");
                        $ds_name = substr($ds_name,0,18) . $i;
                        if (!isset($perf[$ds_name])){
                            echo("setting\n");
                            $perf[$ds_name] = $v;
                            unset($perf[$k]);
                        }
                    }
                }
            }
        }

print_r($perf);

?>
`

**Comment by infotek** [comment]
php script that emulates changes to includes/services.inc.php for testing 

https://gist.github.com/infotek/afca555ae101168bf91877efb32644ec

**Comment by infotek** [comment]
1) during the nagios check check_service() in 'includes/services.inc.php' make sure ds_name does not exceed 19 characters while preserving the ds_name ordering.
2) check_mysql performance output is normally ~351 characters worth of performance output.  This data is placed into the database, table service, field service_ds.  Alter database so that service_ds can accommodate a larger VARCHAR(400).
3) make performance metrics with the string uptime and Uptime have the rrd type GAUGE.
4) for check_mysql group similar data together in the same graph

**Comment by laf** [comment]
All good with me. @librenms/reviewers anyone else?

**Pull request merged**
