### PR TITLE
Dont set mempool percent to null

### PR DESCRIPTION
**Pull request by Jellyfrog**
`normalizePercent()` can return null, `setMempoolPercAttribute()` applies `round()` and throws deprecation warning 

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
> Hmm, I remember some very specific semantics around null here. I fixed this further up (in the model) I think.

The only difference is in the scenario:
if the input `$percent` is null, and `mempool_total` is not set,
then the models `mempool_perc` will not be set, compared to old behaviour where it sets it = round(null) = 0.0

**Comment by murrant** [comment]
We can't always calculate mempool_perc.  Sometimes we only have used amount and not total.

**Comment by murrant** [comment]
That should fix it.

**Review by murrant — APPROVED** [review]

**Comment by Jellyfrog** [comment]
No, because the error is caused by line 67, that sends null to :
```php
    public function setMempoolPercAttribute($percent)
    {
        $this->attributes['mempool_perc'] = round($percent);
    }
```

**Comment by murrant** [comment]
> No, because the error is caused by line 67, that sends null to :
> 
> ```
>     public function setMempoolPercAttribute($percent)
>     {
>         $this->attributes['mempool_perc'] = round($percent);
>     }
> ```

That is not the current code, this is:
    public function setMempoolPercAttribute($percent)
    {
        $this->attributes['mempool_perc'] = is_numeric($percent) ? round($percent) : null;
    }

**Comment by Jellyfrog** [comment]
hmm im not sure that commit was the best, schema doesnt allow null

**Comment by murrant** [comment]
I noticed that, feel free to revert.

**Pull request closed without merging**
