### PR TITLE
Added dnos to this, does not seem worth duplicating the code for another os

### LINKED ISSUE #1779: Sensor discovery on DNOS (previously FTOS) devices
I have some Dell S4810 switches (previously Force10), that aren't getting temperature sensors discovered/polled. They're detecting as 'dnos' based devices now, but the ftos S series temperature sensor discovery section only looks at devices in the 'ftos' OS category.

snmpwalks of one of the switches:

`# snmpwalk switch sysObjectId`
`.1.3.6.1.2.1.1.2.0 = .1.3.6.1.4.1.6027.1.3.14`
`# snmpwalk switch .1.3.6.1.4.1.6027.3.10.1.2.2.1.14`
`.1.3.6.1.4.1.6027.3.10.1.2.2.1.14.1 = 37`

I think the "correct" way to do this would be to have the ftos S series temperature discovery simply check these on any device with a sysObjectId starting with 1.3.6.1.4.1.6027, since there are also 'dnos' devices that are PowerConnect based and expose temperature sensors differently.

### PR DESCRIPTION
**Pull request by laf**
Fix #1779

### CODE REVIEW

**Comment by f0o** [comment]
Could we rename the file to indicate that it's no longer ftos-centric?

**Comment by laf** [comment]
It's not dnos specific either, it's dnos + ftos-s-series, any suggestions?

**Comment by f0o** [comment]
how about `dnos_ftos-s-series.inc.php` ?

**Comment by laf** [comment]
Pushed update.

**Pull request merged**
