### PR TITLE
Install docs, note proxy config

### PR DESCRIPTION
**Pull request by mhzgh**
As discussed here:
https://github.com/librenms/librenms/issues/9709

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
How do you ensure that?

**Comment by mhzgh** [comment]
I thought about it a moment but decided not to give a specifc example. In the most cases this should be possible by preceding the actual command with a source invocation in the cron job. E.g. . "~/.profile; daily.sh;" But this assumes the users personals files were "skel-created" during the user creation. This could be blocked, when the home directory already existed before the users was created. Or maybe there are other mechanism which inject http_proxy variable. Also settings could reside in profile.d folder, but are not sourced and so on... Was not too sure how to give an most-case-true example here... IMO once there is a hint to keep that in mind, users could review the place their settings come from and act accordingly - what do you think?

**Comment by murrant** [comment]
for http_proxy, you can set it in config.php and I think it is exported for git commands, not sure though.  If it is not, it could be done.

**Comment by murrant** [comment]
Yeah, I can't think of a silver bullet to solve the env in cron.  That is why I asked ;)

**Comment by mhzgh** [comment]
> 
> 
> for http_proxy, you can set it in config.php and I think it is exported for git commands, not sure though. If it is not, it could be done.

That does sound even better to me, right. Daily.sh hands over to php anyways, and the whole application is php - so it doesnt need to be the cron-only solution.

Maybe a hint to review/set these variables during the Web-UI setup makes more sense in that case? Maybe even a lookup-check for validate.php?

Oh and https_proxy should be hitting here, to be precise - at least was in my case.

**Comment by murrant** [comment]
A note about setting the proxy in config.php to ensure it works during cron or setting the env for cron would be good. You can link to https://docs.librenms.org/Support/Configuration/#proxy-support

That gives a concrete way forward, while also giving a hint for people that want to solve it outside config.php.

**Comment by mhzgh** [comment]
Uhm, didn't even notice the Configuration Docs/Environment pages before to be honest...
Sure, can do.

> A note about setting the proxy in config.php to ensure it works during cron or setting the env for cron would be good. You can link to https://docs.librenms.org/Support/Configuration/#proxy-support
Could you give a bit more detail on what you mean by that? Not sure "where" to do modifications now :)

From our discussion I understand that adding a hint nearby the "cron copy" command is not the most optimal location. It should be mentioned in a more general scope nearby config.php.
Since the Install docs hand over that config.php creation part to the WebUI, I am not sure if the Chapter "Web Installer" would be a good place to add further config.php modification hints.

**Comment by mhzgh** [comment]
So you mean e.g. adding an additional step/page in between the "Create user" and "Generate config.php" of the web UI installation wizard, that prompts to configure a http(s) proxy and mentions/refers to the things we discussed?

**Comment by murrant** [comment]
@mhzgh don't worry about that, just thinking out loud.

Add a line return before your note and duplicate it to all the install docs and we can merge this.

**Comment by mhzgh** [comment]
Oh, ok. Wouldn't feel too confident to extend the web-ui installer without further knowledge :)
Reworked the NOTE a bit to include the ENV or "config.php" references, will update it to the other OS descriptions too

**Comment by murrant** [comment]
You can do it in the same PR.  If you want to do it from the github web interface, what I usually do is go to the changes tab, click the edit button (just an easy way to get to the right branch).  Then click on the path breadcrumb at the top to go to a different file and click edit on that file.

**Comment by mhzgh** [comment]
Great, thanks for the guidance :)

Changed all the install docs I could find.

**Comment by murrant** [comment]
Heh, we usually only update the current install docs... So you were a bit of an over-achiever there.

Thanks :)

**Pull request merged**
