### PR TITLE
feature : add link one hour for display  metrics 

### PR DESCRIPTION
**Pull request by yac01**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by yac01** [comment]
I added this link because I think users of librenms when they have an incidents or just to see the status of their devices they look more the last moment than the last 2 years that's what I think with this Links users will win more time

**Comment by laf** [comment]
This is my opinion. As is, I don't think we should merge this. We already have 9 graphs at the top adding another one as well just makes it more excessive and will slow page load speeds slightly.

Whilst I'm not a fan of config options for the sake of them, I do think it fits here nicely. Should be a relatively minor change and will give users complete flexibility over the number of mini graphs for time frames.

**Comment by network-guy** [comment]
@yac01 @laf I agree with Laf. It's too cluttered. Personally I would like to remove the 48 hour and 2 week graphs as I rarely use them. If there's a config option to specify graph time defaults, or just enable/disable a list of them, that should be beneficial to everyone.

**Comment by laf** [comment]
@network-guy I've pushed an update to here to allow you to specify the graphs you want + documentation. Fancy giving it a try?

**Comment by laf** [comment]
@yac01 You've added a commit with the name "YACINE BENAMSILI" which isn't in your github account so the CLA isn't showing as signed. Please either remove that commit or squash it out.

**Comment by network-guy** [comment]
@laf Sure. I'll try it out later today.

**Comment by network-guy** [comment]
@laf Seems to work as expected. You may want to add the available options to the documentation though, since you can't use arbitrary time values.

What's the intended difference between ['mini']['widescreen'] and ['row']['normal']?

**Comment by yac01** [comment]
lose

**Pull request closed without merging**
