### PR TITLE
Updated menubar to try and shrink space down

### PR DESCRIPTION
**Pull request by laf**
Updated the menu bar to remove the caret drop down icons, move settings to the right next to the search bar and removed the 'System' text from it:

http://snag.gy/L5FjL.jpg

On my install the min width for the browser has gone from 1300 to 1170px.

Thoughts?

### CODE REVIEW

**Comment by f0o** [comment]
I think we shoukd go for side-bar in near future as the topbar is getting very populated

**Comment by laf** [comment]
We'd need to see it working like that, at present things like the Locations, Devices and Alerts menus may not work very well.

I'd like to see another visual update anyway to take us away from observium more. I tried sb-admin2 but I don't think it works that well :(

**Comment by f0o** [comment]
I agree, sb-admin2 looked fair though.. Not top-notch but not terribly bad either. Obviously needs a lot of redisgning and restructuring in the html-templates.

For our install at voodoo.systems we have a draft running the default bootstrap sidebar. Its far from complete and bugs but it helps a lot for crowded navigations (plugins, packages, apps, munin, ...)

**Comment by laf** [comment]
Got a screenshot @f0o ?

I've put a screenshot up of my 10 mins testing sb-admin2, wasn't that difficult to convert.

http://snag.gy/pGJMY.jpg

**Comment by f0o** [comment]
Will post one here when I get home again

**Comment by paulgear** [comment]
I like the horizontal menu bar a *lot* better than the side menu bar.  I wouldn't want to see a patch to switch it without a config option that allows reverting to the horizontal one.

**Comment by laf** [comment]
@paulgear to be fair, the sb-admin2 is kind of a side thing from this PR anyway. This is just to gain a little extra space for those with small monitor syndrome :)

**Comment by paulgear** [comment]
I'd definitely like to make the menu usable on lower-res displays, but after line 484 it looks like we've lost the global search...

**Comment by laf** [comment]
Just search for gsearch in the file and you will see it's there.

**Pull request merged**
