### PR TITLE
Added bgpPeerDescr for Arista OS

### PR DESCRIPTION
**Pull request by damonreed**
This PR adds a mib reference in the BGP poller for Arista devices to populate 'bgpPeerDescr' from 'aristaBgp4V2PeerDescription' 

Description is set in the device config under:

```
router bgp {{AS}}
 neighbor {{IP}} description {{description}}
```

This will populate the description on the device page under the routing tab:
image

Also accessible in alert templates:

```
@if ($alert->faults) Faults:
@foreach ($alert->faults as $key => $value)
  #{{ $key }}: Peer Desc: {{ $value['bgpPeerDescr'] }} {{ $value['astext'] }}
```

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by damonreed** [comment]
bgpPeerDescr is present in the arista data JSON, set to a blank value:

https://github.com/librenms/librenms/blob/055abcf443e2e1f5bafeaa898bb29a05f4991f24/tests/data/arista_eos.json#L5112-L5136

The OID for aristaBgp4V2PeerDescription is .1.3.6.1.4.1.30065.4.1.1.2.1.14 

```
[dreed@nms ~]$ snmptranslate -On ARISTA-BGP4V2-MIB::aristaBgp4V2PeerDescription
.1.3.6.1.4.1.30065.4.1.1.2.1.14

```

 This is not currently in the snmpsim for arista_eos.

I will add in a patch to set this to a configured value for one of the two sample peers and leave the other one blank to test the unconfigured state.

**Comment by damonreed** [comment]
Branch updated with snmpsim and data entries.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Comment by ryanmerolle** [comment]
@damonreed I assume adding this to the alerts section for BGP would be a new feature request.  Or is that on your roadmap?

**Comment by damonreed** [comment]
@ryanmerolle With this PR merged, the example use cases should be working for everyone.  Most of the backend support for this was already in place from #9165, there just wasn't any Arista support to populate the DB from the poller. 

It might be a good idea to add this as another BGP alert template like "BGP Sessions Detail."  

Another use case for this is to do description-based alerting control, such as not firing the alert if #NOALERT is in the description.  Then if you have a flappy neighbor you just put the tag in the description and it won't alert.

 I already do this for interface descriptions and I am wondering where the best place would be in the docs to document this pattern and how it is implemented.

**Pull request merged**
