### PR TITLE
Add edit and delete options for lapsed maintenance windows

### PR DESCRIPTION
**Pull request by geordish**
Fix for #3714

### CODE REVIEW

**Comment by laf** [comment]
I always worry with things like this in that we merge it in and others are like, why have you added that, I don't want people to delete or edit lapsed maintenance windows as they are a record.

We could then add a config option but we have more config options than code it seems like.

@librenms/reviewers thoughts?

**Comment by murrant** [comment]
I agree, there is more argument to leave them there as a record than having the ability to edit or delete them and "change history".

**Comment by laf** [comment]
@librenms/reviewers anyone else?

**Comment by Rosiak** [comment]
I would be OK with the delete ability, but not with a edit - But in general, one should not be able to mingle with lapsed maintenance windows, that's just my opinion. We could have some retention(30 days etc.) however.

**Comment by laf** [comment]
Closing, please feel to carry on the discussion in the original issue

**Pull request closed without merging**
