### PR TITLE
Added full discovery and polling support for brocade VDX devices. 

### PR DESCRIPTION
**Pull request by vizay**
Added full discovery and polling for Brocade VDX devices

Removed an obsolete value and check for ifAlias (in definitions and ports) since VDX now days report correct from ifAlias. 

Removed printing of interface numbers for vdx devices in the interface list since VDX devices do not report the expected ifIndex value like other switches do (i.e it doesn't print if1 as 1, but instead uses a huge number making no sense at all....what so ever :P )

### CODE REVIEW

**Comment by laf** [comment]
Thanks @vizay. Whilst we take a look at this can you fix the syntax error in: includes/polling/ports.inc.php

See scrutinizer output for further info.

**Comment by laf** [comment]
Ok couple of comments from me @vizay:

1. includes/discovery/os/nos.inc.php - I'd suggest still including the old checks in this and just add your new one. Just to be sure we maintain backwards compatibility for those on older firmware.

2. Some formatting in the files uses two spaces instead of four when indenting. We have standardised on four spaces - can you update please.

After that, good for a merge from my perspective.

**Comment by laf** [comment]
:+1: from me.

@librenms/reviewers Thoughts?

**Comment by Rosiak** [comment]
:+1:

**Comment by paulgear** [comment]
Without having any other equipment to test on, it seems to me we should merge this, but perhaps send out a notification asking people to add a note to this PR if they notice any problems with Brocade gear.

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
Who's sending the notification out then?

**Comment by vizay** [comment]
Hi,

Just a question, is this standard procedure when adding new devices? Feels like it should be a standard thing that people are staying more aware when support for devices is added that hasn't been there before? :)

**Comment by Rosiak** [comment]
Hi @vizay,
This is not standard procedure as the device support was already partially there.
This is sent out because there is a risk of breaking working installations.

I do not think that we should send out notifications every time new device support is added.

That's just my opinion.

**Comment by ekoyle** [comment]
It appears to be working correctly on the handful of VDXes we have.  The devices are a little bit older (NOS 4.1, I think), so I can't attest to the latest versions.

**Comment by vizay** [comment]
We're running NOS 4, 5 and 6  in our environment and all seem to be working fine so far :)

**Pull request merged**
