### PR TITLE
Change Dell iDrac from Server to Appliance

### PR DESCRIPTION
**Pull request by theherodied**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by theherodied** [comment]
@laf wasn't sure if we needed test data for this?

Thinking this should have an advance warning before being merged in case people had the appliance category in a rule.

Also, I wasn't sure if iLO should be server or if iDrac should be appliance. I went with server for both.

**Comment by Rosiak** [comment]
I'm fine with either.
@librenms/reviewers ?

**Comment by kkrumm1** [comment]
Sounds good to me.

**Comment by murrant** [comment]
IMHO, ILO and iDRAC are appliances but supply server data.  I'm fine with either, but I agree it should be consistent.

**Comment by theherodied** [comment]
Agreed. Will change iDrac instead and update PR.

**Pull request merged**
