### PR TITLE
Fix maps display only one link if multiple links are present between …

### PR DESCRIPTION
**Pull request by louis-oui**
…devices.

Recreate pull request for https://github.com/librenms/librenms/pull/10687

If mac is selected, to graph, only graph one link to avoid unreadable map that was noticed on this post : https://community.librenms.org/t/network-map-w-port-channels-or-multiple-links/2467/3

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/network-map-w-port-channels-or-multiple-links/2467/22

**Comment by murrant** [comment]
Thanks for resending @louis-oui 

Does this fix the issue where there are too many links when using ARP?

**Comment by louis-oui** [comment]
Now it does. Tested

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Comment by jpanzer1** [comment]
I have been following this feature, however, after the latest update today, I am still not seeing maps drawn with both links showing up.. I am only seeing 1 link even though I have a port-channel with multiple links between devices. Should I expect an instantaneous change in showing multiple links on the maps or will this come with the next few polls?

**Comment by murrant** [comment]
@jpanzer1 does your device report the multiple links via lldp?  You can check the links table to see what info is there too.

**Comment by jpanzer1** [comment]
> @jpanzer1 does your device report the multiple links via lldp? You can check the links table to see what info is there too.

It does actually. I am seeing the multiple links via LLDP if I go to the list, however, I am only seeing one of the actual interfaces being mapped out. There are not multiple lines between them.

I am only using xDP for drawing out maps, as I only want to know the physical path between switches.. what I am trying to do is map out my buildings via LLDP and then ultimately, be able to alert on if one of the physical links of a port-channel goes down.

**Comment by louis-oui** [comment]
Could you send us on our librenms dir
`grep map config.php`

**Comment by jpanzer1** [comment]
Here you go>>

-bash-4.2$ grep map config.php
$config['network_map_items'] = array('xdp');

**Comment by louis-oui** [comment]
no idea what is going on for you.  Play with print-map.inc.php to debug

**Comment by jpanzer1** [comment]
Interesting thing is, I have it happen across multiple LibreNMS instances (personal test lab and production at my work). Both are only using XDP. I've found some ares in the print-map where it only wants 1 association between two devices.. To me this seems to be the relevant area that I'm going to try and modify some...

    // If mac is choosen to graph, ensure only one link exists between any two ports, or any two devices.
    // else ensure only one link exists between any two ports
    if (!array_key_exists($link_id1, $link_assoc_seen) &&
        !array_key_exists($link_id2, $link_assoc_seen) &&
        (!in_array('mac', Config::get('network_map_items')) ||
        (!array_key_exists($device_id1, $device_assoc_seen) &&
        !array_key_exists($device_id2, $device_assoc_seen)))) {
        $local_port = cleanPort($local_port);
        $remote_port = cleanPort($remote_port);
        $links[] = array_merge(
            array(
                'from'=>$items['local_device_id'],
                'to'=>$items['remote_device_id'],
                'label'=>shorten_interface_type($local_port['ifName']) . ' > ' . shorten_interface_type($remote_port['ifName']),
                'title' => generate_port_link($local_port, "\n", '', 0, 1),
                'width'=>$width,
            ),
            $link_style
        );
    }
    $link_assoc_seen[$link_id1] = 1;
    $link_assoc_seen[$link_id2] = 1;
    $device_assoc_seen[$device_id1] = 1;
    $device_assoc_seen[$device_id2] = 1;
}

$nodes = json_encode(array_values($devices_by_id));
$edges = json_encode($links);

if (count($devices_by_id) > 1 && count($links) > 0) {
?>

**Comment by rkandilarov** [comment]
Just also to confirm that on our LibreNMS installation with is using only 'xdp' for the map, still only one link between two devices hardly interconnected ( more that 5 links).

**Comment by louis-oui** [comment]
@jpanzer1 @rkandilarov It still works on my side

**Comment by kedare** [comment]
On my setup I see only 1 link between my device where there are aggregate (and all visible on the neighbor list tab)

(running on master)

Screenshot 2019-12-18 at 11 18 04

**Comment by louis-oui** [comment]
Solution is here https://community.librenms.org/t/network-map-w-port-channels-or-multiple-links/2467/30

**Pull request merged**
