### PR TITLE
Output image for graphs with no data

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
doesn't this PR include "not existing RRDs"?
e.G.
image

**Comment by murrant** [comment]
It actually only supports port bits, processors, and storage.  Others would need to be added on a case by case basis.

**Comment by Jellyfrog** [comment]
The text is quite big and it doesn't create any spacing between the graphs, which doesn't look so good:
image

**Comment by SourceDoctor** [comment]
what about not overlib link if RRD doesn't exist and in "little image" the "no <whatever>" show's up ?

**Comment by murrant** [comment]
Can't control the spacing here, because it only outputs a PNG.
You could update the overlib popup to add padding if you like.

**Comment by murrant** [comment]
Let me cover some more graphs in this PR.  Again, I cannot do anything with the overlib output here.

**Comment by murrant** [comment]
Fix norrd image, try to detect norrd.
image

**Pull request merged**
