### PR TITLE
update tripplite divisor for certain versions #5364

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #5364

### CODE REVIEW

**Comment by murrant** [comment]
BTW, I think the UPS attached to the SNMPcard determines the value.

UPS-MIB:upsIdentModel.0 (.1.3.6.1.2.1.33.1.1.2.0) seems show the UPS model maybe we can correlate that with the divisor?

**Comment by laf** [comment]
Yeah it's a bit silly this way. This is standard rfc mib so these guys have just chosen to ignore the mib specs :(

**Comment by FTBZ** [comment]
As mentioned in the IRC channel, a ticket was opened with Generex. Perhaps it's better to wait for the final response before trying to create a workaround.

**Comment by laf** [comment]
I think it is.

**Comment by FTBZ** [comment]
Issue #5634 was updated and this PR is no longer needed.

**Comment by laf** [comment]
That's the wrong issue number, this fixes #5364 and the device is powerlite.

**Pull request merged**
