### PR TITLE
New graph design for health sensors

### PR DESCRIPTION
**Pull request by mpikzink**
**OLD:**
Screenshot from 2024-11-18 20-47-22

For the graphs, I have tried to scale the plots of all sensors not only on the basis of the measured minima and maxima, but instead to use the range of the defined warning thresholds as a basis. 

The orientation towards warning thresholds thus creates a standardised scale across all time intervals, enabling both experts and non-experts to interpret the data clearly and intuitively. Since the scale is no longer determined by the specific extreme values of a single data set, similar sensors can be analysed and compared more easily. Furthermore, the plot can be directly referenced to the threshold value defined by the manufacturer or administrator. 

# Testers are welcome to give feedback

**NEW:**
Screenshot from 2024-11-18 20-49-13
In summary, I am convinced that the decision to scale plots based on defined warning thresholds is not only an aesthetic improvement, but also leads to a significant increase in practical applicability and efficiency in data analysis. It allows for a more targeted use of visualisations and supports both communication and decision-making in data-driven processes. 

**I am sure that not everyone will like the change, which is why it is more of a proposal that the community should decide on. I look forward to your feedback and a discussion!**

Additional small changes I like to add to all sensor graphs:

- [x] all alert tresholds to graph
- [x] all tresholds to legend
- [x] Min, Avg, Max to legend
- [x] SI Unit to Y-Axis
- [x] Label to Y-Axis
- [x] Linear trend line for the future

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
The main problems I see are when thresholds suck or are non-existent.  Like a threshold could be 9999999999

**Comment by mpikzink** [comment]
BTW: I think there is a Bug in rrdtool If you try to add SI units to Y-Axis.

I asked the maintainers:
https://github.com/oetiker/rrdtool-1.x/issues/1271#issue-2672374722

**Comment by mpikzink** [comment]
> The main problems I see are when thresholds suck or are non-existent. Like a threshold could be 9999999999

Thank you for your comment. You pointed Out tree cases I Like to explain seperatly:

If no threshold values are set, the old behavior is implicitly reverted to, as the sensor values then define the minimum and maximum.

If the tresholds are suck and the sensors minimum and maximum are higher the graph will automaticly scale. This I already tested. 

If the threshold values are set very high, this indicates that you should consider whether they generally make sense. We do it in such a way that threshold values that do not make sense for us are removed in the health settings.

Maybe I'm being very idealistic here, but if my fluctuations are far from any pre defined thresholds, then from the system administrator's point of view I can relax and go for a coffee and think about new improvements to lnms :-)

**Comment by murrant** [comment]
I like the idea, I tried to do the same thing with ifSpeed.  But may have to adapt it a bit after merge to cover corner cases and other's use cases.

**Comment by mpikzink** [comment]
@murrant Just to be clear, my plan is only to adjust the health sensors in this PR, as these are currently very simple. I personally think that sensors that have already had a lot of work put into them, such as the ifSpeed, memory and so on, are quite perfect the way they are.

**Comment by murrant** [comment]
Looks good overall.

Graphing code could really use a redesign :/

**Comment by mpikzink** [comment]
I've already thought about an RrdBuilder class, but that seems to be quite time-consuming and takes up too much of my free time.

**Review by laf — APPROVED** [review]
LGTM and thanks for contributing.

**Comment by laf** [comment]
@mpikzink We had to revert this as it broke the graphs. `$sensor->unit()` is being called but `unit()` isn't a function for the Sensor model.

**Comment by mpikzink** [comment]
@laf oh sorry this I have done in #16743

**Pull request merged**
