### PR TITLE
refactor: Update APC discovery

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

I'm unsure if different $types are needed.  I noticed some code uses $index tricks

WARNING, this probably breaks something since it is basically a rewrite.  It will need testing.

### CODE REVIEW

**Comment by crcro** [comment]
checked it against ups and pdu:
on pdu side: the load is no longer reported
on ups side: the output freq output is discovered as 0 and the alert threshold is auto set to 0.15, on polling time is ok, but alarm is generated due to threshold

**Comment by murrant** [comment]
@crcro , I fixed the frequency discovery issue, copy past error.

Can you send the discovery debug output for the pdu current:
`./discovery.php -h HOSTNAME -m sensors/current -d`

**Comment by laf** [comment]
Also needs a rebase.

**Comment by crcro** [comment]
@murrat http://pastebin.com/mqaTnbK5

**Comment by murrant** [comment]
@crcro thanks, but this shows rPDULoadDevNumBanks.0 returns 0, so it says there is no PDU banks.  Can you send the same discovery output without this branch applied?

**Comment by crcro** [comment]
@murrant  ... this is with old current sensor of apc: http://pastebin.com/86zE6j51

**Comment by murrant** [comment]
Thanks for testing @crcro I have both those issues resolved now.

**Comment by crcro** [comment]
@murrant ... i can confirm that everything looks alright with the latest push! congrats!

**Comment by murrant** [comment]
@librenms/reviewers Is it better to leave sensor $type roughly = $device['os'] and make $index longer (so it is unique) or vary $type per sensor type as I have done here?

I might need to change things closer to what they were (there was some collisions before) to minimize loss of historical data.

**Comment by laf** [comment]
Changing type means data loss doesn't it as that changes the rrd filename?

**Comment by murrant** [comment]
Yes, but so does changing index.
```
array('sensor', $sensor['sensor_class'], $sensor['sensor_type'], $sensor['sensor_index'])
```

**Comment by laf** [comment]
That doesn't make it any better then :)

We should be avoiding changing rrd files unless code is put in place to rename them - not sure how this would work with full remote rrdcached nowadays.

**Comment by laf** [comment]
What are we doing with this pr? I've got not way to test it other than against the snmpsimd stuff. If it causes rrd filename changes then we can't merge as is.

**Comment by crcro** [comment]
on my test everything worked without renaming anything.

**Comment by murrant** [comment]
@crco, did you lose historical data though?

**Comment by crcro** [comment]
i'm not 100% sure but i think that i lost the historical data for runtime, load and current sensors on ups. the frequency, temperature and voltage sensors have their old data.

**Comment by murrant** [comment]
FYI, this is pending the rrd rename PR I have been working on.

**Pull request closed without merging**
