### PR TITLE
Add support for ADVA AOS os, with FSP3000 Cloud Connect (with Teraflex)

### PR DESCRIPTION
**Pull request by beufanet**
Add support for ADVA FSP 3000 Cloud Connect

- tshX => Teraflex boxes
- shX => FSP3000C boxes

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by beufanet** [comment]
I'm unable to generate the test JSON files using snmpsim. Please help me to do so:

```
librenms@librenms-dev:~$ ./scripts/save-test-data.php -o adva_fsp3000c -v tsh1r2 -d
Waiting for snmpsim to initialize...

OS: adva_fsp3000c
Module: all
Variant: tsh1r2

Updating os_def.cache
SQL[select * from `devices` where `hostname` = ? limit 1 ["127.1.6.1"] 0.67ms]

SQL[select * from `devices` where `device_id` = ? limit 1 [0] 0.33ms]

SQL[select exists(select * from `devices` where `hostname` = ?) as `exists` ["127.1.6.1"] 0.27ms]

SQL[insert into `devices` (`hostname`, `version`, `community`, `port`, `disabled`, `transport`, `poller_group`, `os`, `status_reason`, `sysName`, `port_association_mode`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ["127.1.6.1","v2c","adva_fsp3000c_tsh1r2",1161,1,"udp",0,"generic","","127.1.6.1",1] 3.31ms]

SQL[insert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (?, ?, ?, ?, ?, ?, ?) [null,"system","2024-12-02 10:39:56",3,"Device 127.1.6.1 has been created","",31] 2.43ms]

adva_fsp3000c_tsh1r2: cURL error 7: Failed to connect to 127.0.0.1 port 8888 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8888/reload.json
```

I don't know how to use it to provides your the JSON file.

**Comment by laf** [comment]
We can help with the test data, however what's the reason for the new OS?

We already have quote a few adva based devices and it would be better not to add a new one, OS's are based on the firmware/software a device runs so what is this device running?

**Comment by beufanet** [comment]
> We can help with the test data, however what's the reason for the new OS?

I think I succeed, but still have some bugs to fix to pass the tests

> 
> We already have quote a few adva based devices and it would be better not to add a new one, OS's are based on the firmware/software a device runs so what is this device running?

ADVA FSP3000 Cloud Connect are new devices and slighlty different regarding OID than the FSP3KR7 and FSP150. That's the reason I proposed this addition.

**Comment by laf** [comment]
> ADVA FSP3000 Cloud Connect are new devices and slighlty different regarding OID than the FSP3KR7 and FSP150. That's the reason I proposed this addition.

Different in what way though? If they have different OIDs that the others don't respond to then add them to the other OS.

**Comment by beufanet** [comment]
> Different in what way though? If they have different OIDs that the others don't respond to then add them to the other OS.

Those have different MIBs and so different OIDs. They are not same. As you can see, the MIB needs also an update https://github.com/librenms/librenms/pull/16788/commits/b2c5d902e607a7d56500475d97d82e94a89c385b

(Still trying to find the reasons tests failed)

**Comment by laf** [comment]
> Those have different MIBs and so different OIDs. They are not same. As you can see, the MIB needs also an update [b2c5d90](https://github.com/librenms/librenms/commit/b2c5d902e607a7d56500475d97d82e94a89c385b)

They can be added to an existing OS then, discovery will work out which OIDs are responding correctly then poller will just obtain data from those. We do this across a range of OS's already.

**Comment by beufanet** [comment]
But existing ADVA OS have nothing related to these devices FSP3000CC ....

**Comment by beufanet** [comment]
As you can see this is a totally new devices, and does not work because OIDs are different, that's why I also pushed the MIBs update. 

Please let me know:
- if this PR will be rejected, as it's for the community ;) 
- how can I fix test failing, I've no ideas who's going wrong in the above tests (`8.3, Unit, 1, mariadb:10.5` & `8.2, Unit, 1, mysql:8.0`)

**Comment by PipoCanaja** [comment]
@laf I don't know this precise device, but I know that ADVA uses a lot of different OSes on their devices, even sometimes the same family runs completely different OSes ... So when a new PR comes with ADVA in the name, I am a lot more ready to consider it a new OS than other vendors :) 

But that being said, again, I have no clue about this precise one.

**Comment by PipoCanaja** [comment]
> * how can I fix test failing, I've no ideas who's going wrong in the above tests (`8.3, Unit, 1, mariadb:10.5` & `8.2, Unit, 1, mysql:8.0`)

It seems that the JSON file wasn't correctly created somehow. Did you face any issue/error while generating it ? Could you generate it again?

**Comment by beufanet** [comment]
> > * how can I fix test failing, I've no ideas who's going wrong in the above tests (`8.3, Unit, 1, mariadb:10.5` & `8.2, Unit, 1, mysql:8.0`)
> 
> It seems that the JSON file wasn't correctly created somehow. Did you face any issue/error while generating it ? Could you generate it again?

I generated again, but seems I still have issues.

**Comment by PipoCanaja** [comment]
Bonjour @beufanet 
Will generate the file on my side and see how it goes.

**Comment by PipoCanaja** [comment]
@beufanet Should we name the os `adva-fsp3000` instead of `adva_fsp3000c`? The device family seems to be fsp3000 (which includes a bunch of devices) and `-` would be better than `_` in the OS name (I know, most of the adva names are wrong indeed :D )

**Comment by beufanet** [comment]
> @beufanet We should probably name the os `adva-fsp3000` instead of `adva_fsp3000c`:
> 
> * The device family seems to be fsp3000 (which includes a bunch of devices). And we want to cover all of them as they should hopefully run all the same fsp3000 OS (never sure of that with ADVA, but we can hope)
> * `-` would be better than `_` in the OS name (I know, most of the adva names are wrong indeed :D )

you want me rename all from adva_fsp3000c to adva-fsp3000 ?

seems to be legit since the MIB is saying : 
`fsp3000               OBJECT IDENTIFIER ::= { products 4 }`

will do it tomorrow morning if it's ok for you, you already helped me a lot fixing tests !

**Comment by PipoCanaja** [comment]
Hi @beufanet 
In fact, the best name candidate I see, looking again at the MIB, could be adva-aos.
For the moment, you match  
`fsp3000c              OBJECT IDENTIFIER ::= { aosProducts 1 }`

But any of the other AOS products are probably supported :
`
fspxg480              OBJECT IDENTIFIER ::= { aosProducts 2 }
fspxg404              OBJECT IDENTIFIER ::= { aosProducts 3 }
fspxg418              OBJECT IDENTIFIER ::= { aosProducts 4 }
fspxg480-25g-100g              OBJECT IDENTIFIER ::= { aosProducts 5 }
fspxg480-100g                  OBJECT IDENTIFIER ::= { aosProducts 6 }
fspxg480-100gcfp2              OBJECT IDENTIFIER ::= { aosProducts 7 }
fspxg404-100g                  OBJECT IDENTIFIER ::= { aosProducts 8 }
fspxg404-100gcfp2              OBJECT IDENTIFIER ::= { aosProducts 9 }
fspxg418-100g                  OBJECT IDENTIFIER ::= { aosProducts 10 }
fspxg418-100gcfp2              OBJECT IDENTIFIER ::= { aosProducts 11 }
fspxg118pro-cshac              OBJECT IDENTIFIER ::= { aosProducts 12 }
fspxg118pro-cshdc              OBJECT IDENTIFIER ::= { aosProducts 13 }
fspxg118pro-cshac-g            OBJECT IDENTIFIER ::= { aosProducts 14 }
fspxg118pro-cshdc-g            OBJECT IDENTIFIER ::= { aosProducts 15 }
`

**Comment by PipoCanaja** [comment]
As you can see, creating the YAML is sometimes not the most difficult part. Understanding what OSes are run on devices and how to group them is ! And unfortunately, renaming an OS is a difficult thing later (because all graphs are then lost).

**Comment by beufanet** [comment]
Ok trying to get some information from ADVA to check if it's running the same AOS

**Comment by beufanet** [comment]
I had the confirmation it's the same OS. Will rework the PR and will submit minor changes in the next couple of days.

**Comment by beufanet** [comment]
Renamed  OS adva_fsp3000c to adva-aos 

Still work on this MR (please do not merge or review) to map correctly LibreNMS state sensors and ADVA troubleshooting guide  alarms reference (ok(0), warning(1), critical(2), unknown(3). 

Should be ready next week.

**Comment by beufanet** [comment]
So i renamed everything to be more generic with adva-aos, fix the sensors states values (ok/warn/critical/unknown) following the ADVA documentation, but one test is still failing, and I'm unable to understand why :( 

https://github.com/librenms/librenms/actions/runs/12200919366/job/34038151657?pr=16788

How can I fix this ?

**Comment by PipoCanaja** [comment]
@beufanet 
Thanx for your first PR ! Seems that we are about to merge this. Waiting for the tests to complete.

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by beufanet** [comment]
Thanks @PipoCanaja for the help and the merge !

**Pull request merged**
