### PR TITLE
Restructured daily.sh

### LINKED ISSUE #2485: rework update script, allow staged update for submodules
I will rewrite the daily.sh to allow post-update operations in order to stage migration from subtree to submodules and also solve #2484

### PR DESCRIPTION
**Pull request by f0o**
Added staged update and check for distributed poller setups
Added release update channel

Fixes #2485 #2484

### CODE REVIEW

**Comment by laf** [comment]
:+1: Tested (limited as no schema updates or logs to clear) but the code looks like it's ok.

@librenms/reviewers Can we get some more testing done please as if this isn't right then it will break auto updates which we've seen before :(

**Comment by f0o** [comment]
Test test test :)
Also test the new config option to update between tags!
And check the new log's output!

I did test it all before submitting but you never know if some setup causes a bug or not ;)

**Comment by Rosiak** [comment]
Issues could appear when messing this new daily.log and .git/ directory (Permissions).
```

bash-4.1$ ./daily.sh 
Updating to latest codebase                       ./daily.sh: line 25: logs/daily.log: Permission denied
./daily.sh: line 26: logs/daily.log: Permission denied

error: cannot open .git/FETCH_HEAD: Permission denied

Updating to latest codebase
You are not currently on a branch, so I cannot use any
'branch.<branchname>.merge' in your configuration file.
Please specify which remote branch you want to use on the command
line and try again (e.g. 'git pull <repository> <refspec>').
See git-pull(1) for details.
Returned: 1
```

I'm very well aware that these issues are caused by myself, but we still do need to be aware of the possibility. I'm a bit worried about this one, we need to be very careful as this could break installs.

Other than that I didn't have any issues after fixing permissions and git stuff! :+1:

**Comment by f0o** [comment]
The .git perms would've always caused an issue fyi

**Comment by laf** [comment]
:+1: proposing to merge.

**Comment by f0o** [comment]
bump @librenms/reviewers

**Comment by SaaldjorMike** [comment]
As mentioned on IRC I've tested this on my installs, looks good. As for the .git permissions, I guess we could add extra checks in another PR to check if permissions are correct.

**Comment by f0o** [comment]
@SaaldjorMike that's likely best done in the validate.php

**Comment by SaaldjorMike** [comment]
@f0o Might be. I was just thinking of a way to notify people if they mess up permissions after installing, as this would be output from cron running.

**Comment by f0o** [comment]
@SaaldjorMike still this perms issue is not part of the PR and isnt related to this PR either :S

**Comment by SaaldjorMike** [comment]
@f0o Agreed. As for this PR :+1:

**Comment by laf** [comment]
./validate already takes care of permission checks if the user has provided the user they run cron as (default for a while now).

We've had 3 +1's for merges so I'll propose we merge in the next 12 hours

**Comment by f0o** [comment]
Bump :)

**Comment by laf** [comment]
Sorry fella. Will merge tomorrow when I'm around in case of issues

**Pull request merged**
