### PR TITLE
Network map updates

### PR DESCRIPTION
**Pull request by laf**
Ok, this should take us a little closer to a stable network map. The map is now re-drawn in the same place each time, links are no longer duplicated and some of the font options have been changed.

Also you can now enable xdp / mac support within the map so if you only care about one then you only have to have it.

### CODE REVIEW

**Comment by f0o** [comment]
In the CI's build the map now only shows 1 link/interface instead of both. Is this intended?

**Comment by laf** [comment]
Yup, the two links were basically the same connection but taken from device A -> B and then B -> A so in essence duplicated.

**Comment by slm4996** [comment]
Thanks for listening, and the very quick work! Sorry if I was harsh. I make use of LibreNMS daily, and contribute to many other projects. 

It is a testament to your quality and flexibility, +listening to your community, that I have yet needed to contribute to this project.

**Comment by laf** [comment]
You've not tried it yet, still might not be quite right :)

**Pull request merged**
