### PR TITLE
fix: Remove the default date from the maintenance form when editing

### PR DESCRIPTION
**Pull request by FTBZ**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

- Removing the default value of 1970 for this field to prevent to lapse from maintenance when editing.

### CODE REVIEW

**Comment by FTBZ** [comment]
Credit to @schubling

**Comment by laf** [comment]
I'll have to test but I doubt this will work for MySQL with sql_mode on

**Comment by laf** [comment]
Unfortunately this doesn't work:

`Incorrect date value: '' for column 'end_recurring_dt' at row 1`

`1970-01-01 00:00:01` is the minimum default for MySQL with `NO_ZERO_IN_DATE,NO_ZERO_DATE` set for sql_mode which we are trying to strive to achieve support for.

**Comment by FTBZ** [comment]
Thanks for the tests. And can we use a date in the future? If no, this PR can be closed but it's not very friendly when editing.

**Comment by laf** [comment]
Explain the issue you are having.

**Comment by FTBZ** [comment]
We're using this maintenance window during the backup session to be not annoyed with false-positive alerts. So we need to edit regularly the maintenance rule to add new service and remove old.

But when editing, the field "End maintenance date" will always be filed with the 1970-01-01 00:00:01. So if you don't take care and validate. The maintenance will be lapsed and you need to create a new one will all your service.

When writing this, I think that the best method isn't to leaving the field blank when creating the maintenance rule. I can change to a date far far far away...

**Comment by laf** [comment]
So we just need to blank out the fields with the default value in then?

**Comment by FTBZ** [comment]
Yes, mostly in the edit form.

**Pull request closed without merging**
