### PR TITLE
webui: Single Server Details widget

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
You're going to open a can of worms with this :) People will be asking for these all over!

So couple of things, can you download the min version of this library and use that instead. As it's only usable for dashboards then you should include the min.js file within the widget to stop it being needed elsewhere.

We already have raphael included which is the same version. `html/js/raphael-min.js` so you can drop yours.

Looks ace btw :)

**Comment by aldemira** [comment]
@laf Yeah ok but, I couldn't find the min version. There are old versions of it on different CDNs but I wanted to use the official one.

**Comment by laf** [comment]
> @laf Yeah ok but, I couldn't find the min version. There are old versions of it on different CDNs but I wanted to use the official one.

Yeah actually can't see it myself. We might need to min it ourselves (as we should with some others). It does raise the question, is this library supported and do we need to pick another one if it's not?

**Comment by aldemira** [comment]
I'm open to suggestions. This project hasn't been touched for a year. There's gauge.js which a not very well documented and not as nice as this, but I can give it a try if you want to.

**Comment by laf** [comment]
Don't want to cause additional work so let's leave it for now. If we start to use it in anger more then I think we should take a look at the best one.

**Comment by aldemira** [comment]
Now I know why there isn't a minified version of the library. I've used a few different sites to compress it, and minified file always breaks the output. I'm attaching the screenshots.
screen shot 2017-12-21 at 09 50 01
screen shot 2017-12-21 at 09 54 07

**Comment by laf** [comment]
I've rebased this and also fixed the sql queries to stop the device list being shown to people who don't have access. The widget will also not load now if the user doesn't have access and display an error message.

Will merge once checks complete.

**Comment by kkrumm1** [comment]
Found a small issue :( When you try to use another Single Server Widget in the same dashboard it adds the info to the first Single server widget, not the second server widget.

image

**Comment by aldemira** [comment]
Thanks @kkrumm1 ! Just sent another PR to fix this.

**Pull request merged**
