### PR TITLE
Mistake in ddmDiagnosisRXPower OID

### PR DESCRIPTION
**Pull request by n-lyakhovoy**
Mistake in ddmDiagnosisRXPower OID (its same as ddmDiagnosisBias)
Right OID is .1.3.6.1.4.1.40418.7.100.30.1.1.17

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by n-lyakhovoy** [comment]
Attached snr.snmprec with module sensors

**Comment by n-lyakhovoy** [comment]
Attached snmp data
[snr.snmprec.zip](https://github.com/librenms/librenms/files/5259890/snr.snmprec.zip)

**Comment by Jellyfrog** [comment]
You need to do both steps https://docs.librenms.org/Developing/os/Test-Units/#capturing-test-data and commit the files to your "patch-1" branch

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
