### PR TITLE
🔧 Enable for using HTTP_X_FORWARDED_PROTO

### PR DESCRIPTION
**Pull request by ah9828**
It's needed when application is behind a SSL loadbalancer or Application Gateway firewall for url generation
Ref: https://docs.microsoft.com/en-us/azure/application-gateway/how-application-gateway-works#modifications-to-the-request

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This is already supported except for legacy links.  Is that what this code does is fix legacy links?

**Comment by ah9828** [comment]
> This is already supported except for legacy links. Is that what this code does is fix legacy links?

I have some problem with /login that redirects me to http://hostname:443/login (plain http protocol) when i access https://hostname even that app_url is set to https://hostname. 

I use https://github.com/librenms/docker in a k8s env. that is behind an application firewall that terminate the ssl certificate.

**Comment by murrant** [comment]
When using nginx, this works for me:
`proxy_set_header X-Forwarded-Proto https;`

**Comment by ah9828** [comment]
I found out the problem. It's seems that the load balancer did not send the correct value. Closing PR

**Comment by murrant** [comment]
@ah9828 glad to hear you got it working.

**Pull request closed without merging**
