### PR TITLE
System Temperature correction if multiple disks

### PR DESCRIPTION
**Pull request by Calvario**

### CODE REVIEW

**Comment by laf** [comment]
@Calvario Can you clarify why you've changed this? The rrd files would now have a different name meaning that people who this has worked for for a while will lose data.

**Comment by Calvario** [comment]
Because if you have more than 2 disks the 3 disk will get the same sensor_index then the System Status. Now with this change disk will have sensor_index = "DiskTemperatureX" and System Temperature will get sensor_index = SystemTemperature and don't have more conflict.

**Comment by laf** [comment]
What I'll suggest is that we look at updating function discover_sensor(), when it does it's first SELECT, update it to check the oid as well. The check is done at present to find sensors with the same index for the same class type, I can't see why this is the only requirement as it really should be based on the oid as well as you can have the same index in multiple OIDs.

@paulgear / @f0o Thoughts?

**Comment by paulgear** [comment]
This definitely needs some more investigation in my opinion.

**Comment by laf** [comment]
So I propose we do this, change:

```sql
SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= ? AND `sensor_class` = ? AND `device_id` = ? AND sensor_type = ? AND `sensor_index` = ?
```

to:

```sql
SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= ? AND `sensor_class` = ? AND `device_id` = ? AND sensor_type = ? AND `sensor_index` = ? AND `sensor_oid` = ?
```

**Comment by Calvario** [comment]
I think that's better with this change ;) Good job
But what's the real usage of "sensor_index" ? It's only for check or for another thing ?

**Comment by laf** [comment]
It looks to be mainly used for duplication checking but imho is too restrictive on it's own.

**Comment by paulgear** [comment]
Two out of the three commits in this PR are related to load, not temperature.  Can we get them split out?  Give us a yell in IRC if you need a bit of help with the git side of things.

**Comment by Calvario** [comment]
Sorry about thant #paulgear, i will correct this imediatly.
I will create a new virtual machine to work properly and create branch for each issue.

**Pull request closed without merging**
