### PR TITLE
Canon printer support

### PR DESCRIPTION
**Pull request by mightea**
Added support for canon MF-Series printers

### CODE REVIEW

**Comment by f0o** [comment]
No polling code required?

**Comment by mightea** [comment]
No, the current printer snmp presets work fine for toner levels, detection was the main problem.

**Comment by mightea** [comment]
added polling for firmware-version serial number and hardware

**Comment by laf** [comment]
Can you rename includes/discovery/os/canon-printer.inc.php to includes/discovery/os/canonprinter.inc.php so it's consistent with the rest of the naming convention then we can merge.

**Pull request merged**
