### PR TITLE
Support for creating custom aggregate graphs, including any list of h…

### PR DESCRIPTION
**Pull request by craized**
…osts and ports

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for submitting this, I've not really looked at the code in too much detail but if we were to merge this then I think it will definitely need some tidying up.

This overall strikes me as what the current port parsing does, or at least where the ability to run a custom script fits in.

What does this look like?

**Comment by craized** [comment]
I don't disagree about it being tidier-- the formatting came from the copied iftype page, and thus inherits all of it's formatting. Any modified or new code has been cleaned up.

Unless I have completely misunderstood the capabilities of description parsing, the functionality is completely different. What this provides, is the ability to create an additional ports menu providing links to aggregate graphs similar to the iftype graphs, but consisting of collections of ports that have been statically configured in config.php. This allows collecting 

As far as what it looks like, nfortunately this is only deployed in a production LibreNMS populated with data that is not mine to share, so I don't have screenshots available. My time working on this (as of now at least) is limited to business hours so I am unable to spend the extra time necessary to spin up a new instance for examples.

If you get a chance to look it over, thank you, otherwise, I understand that there's already plenty of work to be done on the project and my inability to put more time into this addition can't be helping my case

**Comment by laf** [comment]
> Unless I have completely misunderstood the capabilities of description parsing, the functionality is completely different. What this provides, is the ability to create an additional ports menu providing links to aggregate graphs similar to the iftype graphs, but consisting of collections of ports that have been statically configured in config.php. This allows collecting

That's what the port parser does and most likely the code you've done here would be useable in that regards.

I see this as more of a custom requirement than something that should be part of the core code base.

@librenms/reviewers might have a different opinion.

**Comment by laf** [comment]
@craized Any update on this?

**Comment by laf** [comment]
@craized Feel free to respond to this PR and we can re-open it.

**Pull request closed without merging**
