### PR TITLE
Add application xmrig

### PR DESCRIPTION
**Pull request by yrebrac**
LibreNMS application for XMRig (monero miner) 
Accompanied by python snmp extend script in https://github.com/librenms/librenms-agent/pull/347
Tested on live installation
Style checks applied
Example of each graph below
xmrig_hashrate_example
xmrig_jobtime_example
xmrig_shares_example
xmrig_threads_example

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by yrebrac** [comment]
It's easy enough to write a unit test but I don't see any existing unit tests to base off:
`for prefix in `ls includes/polling/applications | cut -d. -f1`; do find tests/ -iname '$prefix*'; done`
Is it actually a requirement for applications? If so, the results should simply match what the comments for function json_app_get() say, so actually a generic test might do. Some applications seems to optionally use this or a legacy method though, so it seems like a generic test would need some more thought how it would be called, and that's getting outside the scope of this PR. What do you recommend?

**Comment by Jellyfrog** [comment]
No need to write anything, did you read https://docs.librenms.org/Developing/os/Test-Units

**Comment by yrebrac** [comment]
Ok figured it out I think. added the .snmprec

**Comment by yrebrac** [comment]
The pending CLA problem is back. How to fix permanently? Looks like there is one commit I keep trying to amend with the wrong author.

**Comment by yrebrac** [comment]
commit email problems, rebranching and will open new PR

**Comment by murrant** [comment]
@yrebrac rebase -i and squash the commits with the bad email (or all of them)

**Pull request closed without merging**
