### PR TITLE
Update MIBs for AlteonOS

### PR DESCRIPTION
**Pull request by NightowlKr**
(Oct 3, 2021) MIB for Alteon Application Switch Software Version 32.4.8.0
- Download MIB ZIP File
  : https://portals.radware.com/getattachment/488a8f78-1c6f-4a80-8f34-77730fb13aa7

(June 27, 2021) Alteon Recommended OIDs 32.x
- Download Document File
  : https://support.radware.com/ci/okcsFattach/getFile/16176/Alteon%20Recommended%20OIDs%2032.x%20June%2021.doc

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Looks like you still have some test data not matching the expect result.  Possible fixes:
1. The new value is correct! Update the test data to match
2. The new value is wrong!  Fix whatever produced the wrong value.

**Review by NightowlKr — COMMENTED** [review]
There is a problem in bringing in the serial number OID of old device.

- Old device
   > ALTEON-CHEETAH-SWITCH-MIB::hwChassisSerialNumber.0
   > .1.3.6.1.4.1.1872.2.5.1.3.1.10.0

- Lately device
   > ALTEON-CHEETAH-SWITCH-MIB::hwSerialNumber.0
   > .1.3.6.1.4.1.1872.2.5.1.3.1.18.0

**Comment by murrant** [comment]
Oops, alteonos_as3408e.json has a syntax error now.

**Comment by laf** [comment]
Just one issue in tests that needs fixing:

```
-            'inetCidrRoutePfxLen' => 2
73
+            'inetCidrRoutePfxLen' => 3
```

Also, can you sign the CLA please?

**Comment by laf** [comment]
@NightowlKr Same as the other PR :(

**Pull request closed without merging**
