### PR TITLE
New Device: Bluecat Networks appliances

### PR DESCRIPTION
**Pull request by ipptac**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

**Bluecat Networks IPAM Appliance Support**
Default Linux detection already in LibreNMS for CPU/Memory/Disk. Have added OS detection for appliance logos along with DNS, DHCP, NTP sensor monitoring for alerting integration when the following - 

- bcnHaServiceStatus
- bcnDhcpv4SerOperState
- bcnDnsSerOperState
- bcnNtpSerOperState

This is useful when the platform is deployed in an XHA environment for DHCP failover. 

bcn-sensors

Pre-commit checks out. 

`andy@libredev00:/opt/librenms# ./scripts/pre-commit.php 
Only checking os: bluecatnetworks
Running unit tests... 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

......                                                              6 / 6 (100%)

Time: 1.71 seconds, Memory: 28.00MB

OK (6 tests, 1181 assertions)
Style check skipped.
Lint check skipped.
Tests ok, submit away :) 
`

### CODE REVIEW

**Comment by murrant** [comment]
git magic: https://stackoverflow.com/questions/12481639/remove-files-from-git-commit
Or, you could close this PR and try again :)

**Comment by TheGreatDoc** [comment]
@ipptac I've converted it to yaml. Also added the replication status.

Please, test it.

**Comment by ipptac** [comment]
@TheGreatDoc Thanks. LGTM. Removed the PHP and added the YAML file. It checks out on all four of our lab boxes.

**Comment by ipptac** [comment]
@TheGreatDoc Not queryable, despite being in the MIB - 

root@libredev00:/opt/librenms# snmpwalk -v 2c -c bcnCommunityV2C labbdds01.lab.ipperf.local .1.3.6.1.4.1.13315.3.1.5.2.1.2
iso.3.6.1.4.1.13315.3.1.5.2.1.2 = No Such Object available on this agent at this OID

We're also following up with the vendor about the HA status (failed(8)) on the running Virtual IP of the XHA cluster, as it shouldn't be returning that, however this doesn't invalidate the submission.

**Pull request merged**
