### PR TITLE
Run CI on ubuntu 22.04

### PR DESCRIPTION
**Pull request by Jellyfrog**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
This fails due to ubuntu 20.04 got a newer net-snmp that handles weird test data different

**Comment by murrant** [comment]
@Jellyfrog at least it would be consistent with most of our dev machines then.

**Comment by murrant** [comment]
I updated all test data.  This had the consequence of adding many modules to tested data (where data existed in the snmprec already).

Should I leave it?

**Comment by Jellyfrog** [comment]
It's better we collect changes here than In some device pr  we're a bit unsure about.

**Pull request merged**
