### PR TITLE
PSR2 Cleanup: /html edition

### PR DESCRIPTION
**Pull request by murrant**
[x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
[x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Testing should focus on authentication, plugins, and collectd
Several libraries were moved to html/lib.
Several changes to some classes (namespace, visibility, function names)
Travis tests for code conformance.
Fixed all errors, left most warnings.
Disabled warnings in phpcs, most are line-length.

### CODE REVIEW

**Comment by murrant** [comment]
Didn't see any other regressions in this patch during testing.
Note that I picked `LibreNMS` as the default namespace for classes.

**Comment by murrant** [comment]
FYI, I suggest squashing this whoever merges.

**Comment by laf** [comment]
`env: PHPL=1` - The reason I separated out the checks was php5.3 isn't supported by InfluxDB-PHP so I only excluded that rather than all of lib/. If we exclude all of lib/ we won't know if any of that breaks version compatibility if we upgraded a sub module.

`html/includes/PasswordHash.php` was a 3rd party library, not sure if we want to change those as it might make it harder to see the difference if we upgrade.

Aside from that - all good.

**Comment by murrant** [comment]
PHPL: I had both split out at some point, but removed it, I can restore it for the lint check.

PasswordHash.php is 3rd party, but I believe it will never be updated.  But, it might be a good idea to move that to libs too and ignore the style check.

**Comment by murrant** [comment]
I'm going to close this and split it up into more PRs..

**Pull request closed without merging**
