### PR TITLE
missing mix-manifest update for settings

### PR DESCRIPTION
**Pull request by SourceDoctor**
missed to upload mix-manifest.json ...

### CODE REVIEW

**Comment by SourceDoctor** [comment]
@PipoCanaja 
is oversees this file, which is also needed for settings language update

**Comment by PipoCanaja** [comment]
Right. I'm holding this one for the moment, as I have a french translation PR waiting to be merged, which includes an updated mix-manifest file. (PR #10763)

**Comment by SourceDoctor** [comment]
@PipoCanaja 
when merging french language into master updating mix-manifest file is again needed for my thoughts.
hash values referencing to app.js and vendor.js will again change ;)
So my Pull Request is obsolete?

**Comment by Jellyfrog** [comment]
Will be fixed in another PR.

**Comment by PipoCanaja** [comment]
One PR can fix both. And if we merge this one, then I need to rebase the 2nd one :)

**Pull request closed without merging**
