### PR TITLE
Cleaned up Trango Apex Lynx OS code and added wireless sensors

### PR DESCRIPTION
**Pull request by metavrs**
I removed an incorrect mib and added the correct one.  Changed initial detection to use mib instead of numeric oid. Removed trim function.  Added wireless sensor class.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Looks great.  There are several instances where you mess up the plurality of $sensors that should be fixed and this is ready.  I'm uploading the test json for you.

**Comment by murrant** [comment]
Hmm, looks like the MIB is kinda broken. Underscores (_) are not allowed in oid names.  So, this made the os version not work.  If the vendor doesn't have an updated and fixed MIB, you can either revert numeric oid or change underscores to dashes in the MIB.

**Comment by metavrs** [comment]
Hey murrant, any idea why this is failing?  I couldn't tell from looking at the details

**Comment by laf** [comment]
I've just re-run `./scripts/save-data.php -o apex-lynx` to regenerate the data.

**Comment by metavrs** [comment]
Thank you, I'll watch out for that next time

**Pull request merged**
