### PR TITLE
Update Bootstrap

### LINKED ISSUE #1890: update Boostrap version
Hello,
From what I see in the current boostrap shipped with Librenms we're at 3.1.1 (http://i.imgur.com/4qs0sIw.png) while the actual bootstrap is at v3.3.5

### PR DESCRIPTION
**Pull request by Rosiak**
- Bump bootstrap to latest 3.3.5

Fix #1890

@f0o @laf @paulgear

### CODE REVIEW

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Bootgrid tables now have a horizontal scrollbar for me and the remember me button is dis-aligned :/

**Comment by SaaldjorMike** [comment]
trigger ci

**Comment by laf** [comment]
@Rosiak 

If you can apply these two patches - fixes both login and devices pages to work with new bootstrap.

https://gist.github.com/laf/dd1cab05bd1102112990

https://gist.github.com/laf/940db869cdfd59656cf0

**Pull request merged**
