### PR TITLE
VRP: add fan description to hwEntityFanState

### PR DESCRIPTION
**Pull request by PipoCanaja**
Very short addon to #9838 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
but I cannot generate the testdata for the device @jozefrebjak used, so Travis won't be happy. 
@jozefrebjak : could you rerun collect_snmp_data and save_test_data with this patch applied and commit the new files to this PR ? 

Thanx

**Comment by jozefrebjak** [comment]
@PipoCanaja yes i can but on monday, because my testing install is running on my work computer as a vm.

**Comment by PipoCanaja** [comment]
Hi @jozefrebjak ,
Would you have time to get the testdata ? 
Thx
PipoCanaja

**Comment by jozefrebjak** [comment]
@PipoCanaja  i got them, how i can add them to your PR ?

**Comment by PipoCanaja** [comment]
@jozefrebjak Please attach the file to this PR as a attachement to a comment. That's the easiest. I'll grab it and push it. 
Thanx

**Comment by jozefrebjak** [comment]
@PipoCanaja 

snmprec
https://p.libren.ms/view/72a7e1eb

data
https://p.libren.ms/view/5b4a4295

**Comment by PipoCanaja** [comment]
Travis CI is happy now. Thanx for your help @jozefrebjak !
@librenms/reviewers : ready for merge.

**Pull request merged**
