### PR TITLE
Added Etherlike counters to the DB.

### PR DESCRIPTION
**Pull request by garryshtern**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Just an FYI that the schema files need to be on one line.

However, I'd say that this belongs in it's own table. The ports_statistics table is already pretty big so this should be ports_dot3 maybe - @librenms/reviewers ?

**Comment by paulgear** [comment]
I agree with @laf - this seems worth having in its own table.

**Comment by laf** [comment]
@garryshtern Are you splitting this out into it's own DB?

**Comment by laf** [comment]
@garryshtern bump

**Comment by laf** [comment]
Closing, feel free to re-open when you've split this out to another table.

**Pull request closed without merging**
