### PR TITLE
Add support for a maintenance boolean in API results.

### PR DESCRIPTION
**Pull request by xorrkaz**
If a device is under maintenance, it would be nice to see that from the API. This can help drive other automation workflows where LibreNMS forms a cornerstone in the management source of truth.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Review by murrant — CHANGES_REQUESTED** [review]
Adds extra database calls when they are not needed.

You shouldn't add this to common code.

**Comment by xorrkaz** [comment]
Thanks @murrant .  I assume you're requesting an additional API endpoint such as, `/api/v0/devices/{device}/maintenance`?

**Comment by xorrkaz** [comment]
@murrant , so I have built the endpoint.  I could use some advice or a pointer with how to regen the bootstrap on a package-installed system so I can test this?  Thanks.

**Comment by xorrkaz** [comment]
Nevermind.  I deleted the cache and tested it.  I hope this meets the requirement.  It certainly meets my needs.

**Review by murrant — APPROVED** [review]
LGTM, it seems a little use case specific, but I think that is ok.

**Pull request merged**
