### PR TITLE
Run git diff as librenms configured user

### PR DESCRIPTION
**Pull request by paulgear**
Proposed fix for issue discovered in #3672

### CODE REVIEW

**Comment by murrant** [comment]
Looks good except when ran as a non-root user (which isn't recommended but people do it anyway).

You get a password prompt without any context.
1. check the user and change or avoid the commands appropriately
2. add context to the password prompt

**Comment by paulgear** [comment]
I'm not sure why we would be running validate from the poller, but if people don't follow the instructions about how to run validate, we should put a check in there to stop it from running when run as non-root.  I'll have a look at that when I've got a minute.

**Comment by laf** [comment]
poller doesn't run validate but it does run the version check function to get all the versions for debug displaying.

Could just exclude .git/index from the file validate.

**Comment by murrant** [comment]
Thanks Paul, got the ball rolling on this fix.

**Pull request closed without merging**
