### PR TITLE
bgp-peers update

### PR DESCRIPTION
**Pull request by murrant**
Use IP parsing library more effectively.
Fix issue with improperly formatted data from some OS.
Fix update issue where some data was not correctly updated in the database.
Include comware bgp-peers test data

May require: #7971 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
I would still like to have JunOS test data for this.

**Comment by zombah** [comment]
Manually tested with discovery of 3 Junos devices of various bgp peers capacity from 5 to 100. bgpLocalAs detected fine, peer statuses and data looks correct.

**Comment by murrant** [comment]
Depends on #8050

**Comment by laf** [comment]
#8050 is now merged, does this need more code or anything before it's ready or it was just waiting on that PR?

**Comment by murrant** [comment]
It's ready.

**Comment by zombah** [comment]
Tested pr this night, for some reason there is now alot of wrong parsed session with first octet of peer ip-address lost, like i have 192.168.99.0 neighbor and it is parsed into 168.99.0 and all other peers same way. Noticed on cisco ios boxes, others seems fine.
```
SNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -Oq -m BGP4-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/cisco udp:HOSTNAME:161 bgpPeerRemoteAs]
BGP4-MIB::bgpPeerRemoteAs.* 8359
BGP4-MIB::bgpPeerRemoteAs.* 8359
BGP4-MIB::bgpPeerRemoteAs.* 64513
BGP4-MIB::bgpPeerRemoteAs.* 64513

Peers : BGP4-MIB::bgpPeerRemoteAs.192.168.99.0 8359
BGP4-MIB::bgpPeerRemoteAs.192.168.99.2 8359
BGP4-MIB::bgpPeerRemoteAs.192.168.99.21 64513
BGP4-MIB::bgpPeerRemoteAs.192.168.99.25 64513
Found peer 168.99.0 (AS8359)
Found peer 168.99.2 (AS8359)
Found peer 168.99.21 (AS64513)
Found peer 168.99.25 (AS64513)
```

**Comment by murrant** [comment]
@zombah Hmm, I don't have any ios test data yet... 

I don't remember there being anything to account for a different index in the previous code.

**Comment by murrant** [comment]
Found the issue, it thought it was using cbgp2.

Fixed that, thanks for the test data.

**Comment by laf** [comment]
@murrant I can get you iosxe test data if you need?

**Comment by zombah** [comment]
Now discovery and polling works fine, tested in enviroment with ios,iosxe and junos devices.

**Pull request merged**
