### PR TITLE
Change axiscam to type camera from

### PR DESCRIPTION
**Pull request by sorano**
Change axiscam to type camera from appliance.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @sorano 
Camera is not an official type currently. This must be discussed before anything else

**Comment by Jellyfrog** [comment]
Yes we should device on device categories. Any suggestions and/or lists or standards we could follow?

**Comment by murrant** [comment]
@PipoCanaja what makes a type an official type?  Are they defined somewhere?

**Comment by sorano** [comment]
Well,
I was actually not aware that a camera type existed until I added some ipolis cameras and they defaulted to camera type. 
https://github.com/librenms/librenms/blob/e864ed7795d80fe46c62bafbbb52f9b0e129d7a6/includes/definitions/ipolis.yaml#L3

Vivotek also has the same:
https://github.com/librenms/librenms/blob/e864ed7795d80fe46c62bafbbb52f9b0e129d7a6/includes/definitions/vivotek.yaml#L3

Then I manually tried to change my Axis cameras to the same but Camera is not a visible type in the drop-down. Maybe the drop-down is what defines "official type" ?
image

**Comment by murrant** [comment]
I think you are correct.  You can set any type in is yaml, but users can only set predefined types...  Which seems kind of silly.

**Pull request closed without merging**
