### PR TITLE
feat:add links for librenms graph

### PR DESCRIPTION
**Pull request by yac01**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by yac01** [comment]
@laf excuse me because This is the second time I have committed the same thing 
i think i have problems in my count  git ub because in each time when i make some modification in github i have the probleme that don't stop "ontinuous-integration/travis-ci/pr" but now I would not make any other changes on github i would do it only in the terminal

**Comment by murrant** [comment]
The docs doesn't seem to mention `$config['graphs']['mini']['widescreen']` and I'm not sure how the three fit together.

**Comment by laf** [comment]
`$config['graphs']['mini']['widescreen']` = Widescreen setup for the pages like a direct port page.

`$config['graphs']['mini']['normal']` = Normal screen size of the above.

`$config['graphs']['row']['normal']` = The row of graphs you use to select the time period for a graph you want to see.

We can't use mini normal and row normal as this would change the number of graphs people see by default so this setup replicates the existing setup with the ability to custom either of those above scenarios.

**Comment by murrant** [comment]
Thanks, @laf we just need that in the docs and I think this is ready.

**Comment by laf** [comment]
@murrant doc update pushed.

**Pull request merged**
