### PR TITLE
Allow stack index other than '1.' for CiscoSB

### PR DESCRIPTION
**Pull request by dennypage**
When in a stack configuration, the index for each port is based on the unit number in the stack. The first unit in the stack uses index '1.', the second uses index '2.', the third '3.' and so on.

The prior code had a hard coded index of '1.' which prevented get_port_by_index_cache() lookup from finding the correct port for any port not on the first stack unit.

This resulted in the port description being missing from tables and graphs like so:

port_desc_missing

This change allows for stack indexes values other than '1.', which corrects the missing port description:

port_desc_present

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by mpikzink** [comment]
With the number of sensors it would make sense to group them by stackunit. (Via the group field)

**Comment by dennypage** [comment]
> With the number of sensors it would make sense to group them by stackunit. (Via the group field)

More words please...

**Comment by mpikzink** [comment]
Have a try and fill the $group variable with the Stackunit index. In the discoverSensor function. It might give us a better overview.

**Comment by dennypage** [comment]
> Have a try and fill the $group variable with the Stackunit index. In the discoverSensor function. It might give us a better overview.

Taking a quick look at that, it seems to me that grouping would more appropriate as a different PR. That appears to be more of a feature enhancement, vs the index issue which is a simple defect. This PR only addresses the index defect.

**Comment by mpikzink** [comment]
Yes, you we do that, it just popped into my head when I saw your screenshot... Go ahead :)

**Comment by Jellyfrog** [comment]
> Please add test data so we can ensure your change is not broken in the future.
> 
> Read the docs to find out how: https://docs.librenms.org/Developing/os/Test-Units

Would you mind generating some test data for this?

**Comment by dennypage** [comment]
> Would you mind generating some test data for this?

I don't have snmpsim, but I can give you an snmprec file. Do you want just the sensors module, or do you want the whole nut? Either way, it will take a bit of work to redact.

**Comment by dennypage** [comment]
Here is the snmprec file generated by scripts/collect-snmp-data.php:

[ciscosb_ciscosb.snmprec.zip](https://github.com/librenms/librenms/files/6911998/ciscosb_ciscosb.snmprec.zip)

**Comment by dennypage** [comment]
Thank you @murrant

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
