### PR TITLE
Support for Ubiquiti UISP Fiber OLT XGS

### LINKED ISSUE #15741: UISP Fiber OLT XGS is being "discovered" as "Inteno GW"
### The problem

The UISP Fiber OLT XGS is being "discovered" as "Inteno GW".   It uses the same OIDs.  The ~/includes/definitions/inteno.yaml has some odd logic as it matches everything except...
`
discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.4413
        sysDescr_regex_except:
            - '/VxWorks/'
            - '/quanta/i'
            - '/FASTPATH (Switching|Routing)/'
`

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0-16-g060775b00 (2024-01-12T20:04:32+00:00)
DB Schema | 2023_12_08_184652_mpls_addrtype_fix (276)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================
```

### What was the last working version of LibreNMS?

_No response_

### Device info

Ubiquiti UISP Fiber OLT XGS

### Discovery output

```txt
LibreNMS Discovery
SQL[[1;33mselect `migration` from `migrations` order by `id` desc limit 1 [0;33m[][0m 0.63ms] 
  
SQL[[1;33mselect count(*) as aggregate from `migrations` [0;33m[][0m 0.51ms] 
  
SQL[[1;33mselect version() [0;33m[][0m 0.45ms] 
  
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0-16-g060775b00 (2024-01-12T20:04:32+00:00)
DB Schema | 2023_12_08_184652_mpls_addrtype_fix (276)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================
DEBUG!
Updating os_def.cache  
SQL[[1;33mSELECT * FROM `devices` WHERE disabled = 0 AND `hostname` LIKE '172.16.254.85' ORDER BY device_id DESC [0;33m[][0m 0.96ms] 
  
172.16.254.85 190 inteno SQL[[1;33mselect * from `devices` where `device_id` = ? limit 1 [0;33m[190][0m 1.55ms] 
  
SQL[[1;33mselect * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [0;33m[190][0m 0.63ms] 
  
[FPING] '/usr/bin/fping' '-e' '-q' '-c' '3' '-p' '500' '-t' '500' '-O' '0' '172.16.254.85'
  
response: xmt/rcv/%loss = 3/3/0%, min/avg/max = 0.308/0.378/0.426  
SNMP[[0;36m'/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/inteno' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0'[0m]  
SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.4413
  
  
Modules status: Global+  
OS  
Device  

#### Load disco module core ####
Attempting to initialize OS: inteno  
OS initialized as Generic (inteno)  
SNMP[[0;36m'/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/inteno' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-On' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0' 'SNMPv2-MIB::sysDescr.0' 'SNMPv2-MIB::sysName.0'[0m]  
.*.*.0 = .*.4.1.4413
.*.*.0 = UISP Fiber OLT XGS, *209, Linux 4.4.302
.*.*.0 = olt02-SantaClaraSt415-val
  
  
| UISP Fiber OLT XGS, 4.6.1.28209, Linux 4.4.302 | .1.3.6.1.4.1.4413 | 
  
OS: Inteno GW (inteno)

Attempting to initialize OS: inteno  
OS initialized as Generic (inteno)  


[...]
```

### Poller output

```txt
Override poller modules: unix-agent, core, os, availability, ipmi, sensors, processors, mempools, storage, netstats, hr-mib, ucd-mib, ipSystemStats, ports, xdsl, customoid, bgp-peers, junose-atm-vp, printer-supplies, ucd-diskio, vminfo, wifi, wireless, ospf, isis, cisco-ipsec-flow-monitor, cisco-remote-access-monitor, cisco-cef, slas, cisco-mac-accounting, cipsec-tunnels, cisco-ace-loadbalancer, cisco-ace-serverfarms, cisco-asa-firewall, cisco-voice, cisco-cbqos, cisco-otv, cisco-qfp, cisco-vpdn, nac, netscaler-vsvr, aruba-controller, entity-physical, entity-state, applications, stp, ntp, loadbalancers, mef, mpls  
SQL[[1;33mselect `migration` from `migrations` order by `id` desc limit 1 [0;33m[][0m 0.54ms] 
  
SQL[[1;33mselect count(*) as aggregate from `migrations` [0;33m[][0m 0.38ms] 
  
SQL[[1;33mselect version() [0;33m[][0m 0.44ms] 
  
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0-16-g060775b00 (2024-01-12T20:04:32+00:00)
DB Schema | 2023_12_08_184652_mpls_addrtype_fix (276)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================
  
Updating os_def.cache  
Starting polling run:
  
SQL[[1;33mselect `device_id` from `devices` where `hostname` = ? [0;33m["172.16.254.85"][0m 0.6ms] 
  
SQL[[1;33mselect * from `devices` where `device_id` = ? limit 1 [0;33m[190][0m 0.59ms] 
  
Hostname:  172.16.254.85 
ID:        190
OS:        inteno
IP:        172.16.254.85
  
Attempting to initialize OS: inteno  
OS initialized as Generic (inteno)  
SQL[[1;33mselect * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [0;33m[190][0m 0.64ms] 
  
[FPING] '/usr/bin/fping' '-e' '-q' '-c' '3' '-p' '500' '-t' '500' '-O' '0' '172.16.254.85'
  
response: xmt/rcv/%loss = 3/3/0%, min/avg/max = 0.293/0.341/0.367  
SNMP[[0;36m'/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/inteno' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysObjectID.0'[0m]  
SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.4413
  
  
SQL[[1;33minsert into `device_perf` (`min`, `max`, `avg`, `xmt`, `rcv`, `loss`, `debug`, `device_id`, `timestamp`) values (?, ?, ?, ?, ?, ?, ?, ?, ?) [0;33m[0.293,0.367,0.341,3,3,0,"{\"poller_name\":\"librenms\"}",190,"2024-01-13 22:29:19"][0m 10.75ms] 
  
SQL[[1;33mupdate `devices` set `last_ping` = ?, `last_ping_timetaken` = ? where `device_id` = ? [0;33m["2024-01-13 22:29:19",0.341,190][0m 3.14ms] 
  
SQL[[1;33mselect * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` is null order by `going_down` desc limit 1 [0;33m[190][0m 0.67ms] 
  
#### Load poller module core ####
  
Module enabled: Global + | OS   | Device   | Manual    
SNMP[[0;36m'/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/inteno' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-On' 'udp:HOSTNAME:161' 'SNMPv2-MIB::sysUpTime.0'[0m]  
.*.*.0 = 16700900
  
  
SNMP[[0;36m'/usr/bin/snmpget' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/inteno' '-m' 'SNMPv2-TC:SNMPv2-MIB:IF-MIB:IP-MIB:TCP-MIB:UDP-MIB:NET-SNMP-VACM-MIB' '-v2c' '-c' 'COMMUNITY' '-OQXUte' 'udp:HOSTNAME:161' 'SNMP-FRAMEWORK-MIB::snmpEngineTime.0' 'HOST-RESOURCES-MIB::hrSystemUptime.0'[0m]  
SNMP-FRAMEWORK-MIB::snmpEngineTime.0 = 166982
HOST-RESOURCES-MIB::hrSystemUptime.0 = No Such Object available on this agent at this OID
  
  
Uptime seconds: 167009
  
Uptime: 1 day 22 hours 23 minutes 29 seconds  
SQL[[1;33mupdate `devices` set `uptime` = ? where `device_id` = ? [0;33m[167009,190][0m 2.64ms] 
  
  
>> [0;36mSNMP[0m: [3/0.07s] [1;33mMySQL[0m: [5/0.18s]   
>> Runtime for poller module 'core': 0.0554 seconds with 195968 bytes  
#### Unload poller module core ####
  
#### Load poller module os ####
  
Module enabled: Global + | OS   | Device   | Manual    
Location: 
Hardware: 
OS Version: 
OS Features: 
Serial: 
  
>> [0;36mSNMP[0m: [0/0.00s] [1;33mMySQL[0m: [0/0.00s]   
>> Runtime for poller module 'os': 0.0030 seconds with 120416 bytes  
#### Unload poller module os ####
  
#### Load poller module availability ####
  
Module enabled: Global + | OS   | Device   | Manual    
SQL[[1;33mselect * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` >= ? order by `going_down` asc [0;33m[190,1705098559][0m 0.55ms] 
  
SQL[[1;33mselect * from `availability` where (`device_id` = ? and `duration` = ?) limit 1 [0;33m[190,86400][0m 0.4ms] 
  
SQL[[1;33mupdate `availability` set `availability_perc` = ? where `availability_id` = ? [0;33m[100,749][0m 0.29ms] 
  
1 day   : 100%  
SQL[[1;33mselect * from `device_outages` where `device_outages`.`device_id` = ? and `device_outages`.`device_id` is not null and `up_again` >= ? order by `going_down` asc [0;33m[190,1704580159][0m 0.5ms] 
  
SQL[[1;33mselect * from `availability` where (`device_id` = ? and `duration` = ?) limit 1 [0;33m[190,604800][0m 0.37ms] 
  
SQL[[1;33mupdate `availability` set `availability_perc` = ? where `availability_id` = ? [0;33m[100,750][0m 0.27ms] 
  
[...]
>>> Polled olt02-santaclarast415-val (190) in 1.956 seconds <<<  

[0;36mSNMP[0m [33/0.75s]: Snmpget[16/0.36s] Snmpwalk[17/0.39s]  
[1;33mSQL[0m [111/1.15s]: Select[75/0.42s] Insert[1/0.11s] Update[33/0.61s] Delete[2/0.01s]
```

### PR DESCRIPTION
**Pull request by pozar**
fixes #15741

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by pozar** [comment]
A fix for https://github.com/librenms/librenms/issues/15741

**Comment by PipoCanaja** [comment]
Hi @pozar 
Welcome in the project and thank you for your PR. Could you please have a look at the tests and let us know if you have issues ? 
Thanx

**Comment by pozar** [comment]
I tried running the tests but at step 2, I get this error...
`librenms@librenms:~$ ./scripts/save-test-data.php -o edgeosolt -v edgeosolt
Starting snmpsim listening on 127.1.6.1:1161... 
Traceback (most recent call last):
  File "/usr/bin/snmpsimd", line 576, in <module>
    '|'.join(log.gMap),
AttributeError: module 'snmpsim.log' has no attribute 'gMap'

Failed to start Snmpsim. Scroll up for error.
librenms@librenms:~$ 
`

**Comment by pozar** [comment]
Running lnms dev:check with this PR patched I get the attached output
[tests.txt](https://github.com/librenms/librenms/files/13933051/tests.txt)

It seems to be testing OSs that are not part of this PR.

**Comment by pozar** [comment]
Will try.  Tnx

**Comment by pozar** [comment]
The output of 
`./scripts/collect-snmp-data.php  -h <yourDeviceId> -v 'uisp-fiber'`
Is attached.
[os_defs.cache.gz](https://github.com/librenms/librenms/files/13996116/os_defs.cache.gz)

**Comment by laf** [comment]
> The output of
> `./scripts/collect-snmp-data.php -h <yourDeviceId> -v 'uisp-fiber'`
> Is attached.
> [os_defs.cache.gz](https://github.com/librenms/librenms/files/13996116/os_defs.cache.gz)

We don't need the os_defs.cache file, it's the output from the collect-snmp-data.php script we need.

**Comment by pozar** [comment]
Here you go...
`librenms@librenms:~$ ./scripts/collect-snmp-data.php -h 190 -v 'uisp-fiber'
OS: edgeosolt
Module(s): all
Variant: uisp-fiber

Capturing Data:  sysDescr.0 sysObjectID.0 SNMPv2-MIB::sysLocation.0 sysContact.0 UBNT-UFIBER-MIB::ubntModel.0 UBNT-UFIBER-MIB::ubntVersion.0 UBNT-UFIBER-MIB::ubntSerialNumber.0 hrSWRunParameters ifDescr ifName ifAlias ifType ifOperStatus ubntSfpsTable ifStackStatus hrStorageTable hrMemorySize.0 memTotalSwap.0 memAvailSwap.0 memTotalReal.0 memAvailReal.0 memBuffer.0 memCached.0 memSysAvail.0 ipAdEntIfIndex ipv6AddrPfxLength ubntOnusTable ubntOnusCount ubntThermsTable ubntFansTable fileSystemSpaceTable hrProcessorTable hrDeviceTable dot1dBasePortIfIndex diskIOEntry dot1qTpFdbPort dot1qVlanFdbId .1.3.6.1.4.1.41112.1.5.6.1.0 .1.3.6.1.4.1.41112.1.5.6.2.1.9.12.85.66.78.84.56.51.101.57.50.51.97.101 .1.3.6.1.4.1.41112.1.5.6.2.1.8.12.85.66.78.84.56.51.101.57.50.51.97.101 .1.3.6.1.4.1.41112.1.5.5.2.1.3.1 .1.3.6.1.4.1.41112.1.5.5.2.1.3.2 .1.3.6.1.4.1.41112.1.5.5.2.1.3.3 .1.3.6.1.4.1.41112.1.5.6.2.1.3.12.85.66.78.84.56.51.101.57.50.51.97.101 .1.3.6.1.4.1.41112.1.5.7.2.1.3.0 .1.3.6.1.4.1.41112.1.5.7.2.1.3.1 .1.3.6.1.4.1.41112.1.5.7.2.1.3.2 .1.3.6.1.4.1.41112.1.5.7.2.1.3.3 .1.3.6.1.4.1.41112.1.5.7.2.1.3.4 .1.3.6.1.4.1.41112.1.5.7.2.1.3.5 .1.3.6.1.4.1.41112.1.5.7.2.1.3.6 .1.3.6.1.4.1.41112.1.5.7.2.1.3.7 .1.3.6.1.4.1.41112.1.5.7.2.1.3.8 .1.3.6.1.4.1.41112.1.5.7.2.1.3.9 .1.3.6.1.4.1.41112.1.5.7.2.1.3.10 .1.3.6.1.4.1.41112.1.5.7.2.1.3.11 .1.3.6.1.4.1.41112.1.5.4.2.1.3.1 .1.3.6.1.4.1.41112.1.5.4.2.1.3.2 .1.3.6.1.4.1.41112.1.5.4.2.1.3.3 .1.3.6.1.4.1.41112.1.5.4.2.1.3.4 .1.3.6.1.4.1.41112.1.5.4.2.1.3.5 hrSystemMaxProcesses.0 hrSystemProcesses.0 hrSystemNumUsers.0 systemStats laLoadInt.1 laLoadInt.2 laLoadInt.3 ipSystemStats dot1qPvid
Saved snmprec data /opt/librenms/tests/snmpsim/edgeosolt_uisp-fiber.snmprec

Verify these file(s) do not contain any private data before sharing!
librenms@librenms:~$ 
`

**Comment by pozar** [comment]
Are you looking for the edgeosolt_uisp-fiber.snmprec file (attached)?
[edgeosolt_uisp-fiber.snmprec.gz](https://github.com/librenms/librenms/files/14016573/edgeosolt_uisp-fiber.snmprec.gz)

**Comment by PipoCanaja** [comment]
> Are you looking for the edgeosolt_uisp-fiber.snmprec file (attached)? [edgeosolt_uisp-fiber.snmprec.gz](https://github.com/librenms/librenms/files/14016573/edgeosolt_uisp-fiber.snmprec.gz)

Yes, exactly. Please put it in the PR at its location.

**Comment by PipoCanaja** [comment]
@pozar JSON is now generated. Tests should be OK. Anything else to add on your side ?

**Review by PipoCanaja — APPROVED** [review]
Looks good !

**Comment by makriska** [comment]
@PipoCanaja 
has this change broken automated testing?

I can see tests fail for these PRs when triggered after this merge
https://github.com/librenms/librenms/pull/16890
https://github.com/librenms/librenms/pull/16904

Tests in my PR https://github.com/librenms/librenms/pull/16890 were passing yesterday and now they fail though I did not make any code changes on my side

and both of them report:
OS edgeosolt: Discovered ports data does not match that found in tests/data/edgeosolt_uisp-fiber.json

**Comment by PipoCanaja** [comment]
@makriska Yes it seems. Next PR merged will include the fix and all PR will then be fixed (as soon as they pull master).

**Pull request merged**
