### PR TITLE
F5 LTM - Take 2

### PR DESCRIPTION
**Pull request by adaniels21487**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

This is the second attempt at the F5 LTM module.
It has been modified to make the poller module fetch only the necessary OID's, not round up to a common point in the tree.

It works fine on my installations, but these are too small to exhibit the problem seen in the first attempt. I would appreciate some testing on larger LTM installations.

Thanks,
Aaron

### CODE REVIEW

**Comment by laf** [comment]
@librenms/reviewers will merge tomorrow unless anyway objects

**Comment by laf** [comment]
Blocking as issues reported in https://github.com/librenms/librenms/pull/5149#issuecomment-268467046

**Comment by rucarrol** [comment]
Hey! 

I've been trialling this PR (LTM Virtual Servers (346) | LTM Pools (332)) internally, and it seems to work beautifully! 

I see that since we have quite a few VIPs, we run out of colours in the multi-graph. 

I was thinking, is it possible to sort the data in the graph from most used to least used? This would really help with running out of colours/70% of our graphs being red :)

/Ruairi

**Comment by adaniels21487** [comment]
Hi @rucarrol 
Thanks for the feedback.

Have you had any issues?
@awlx has had intermittent zend_mm_heap corrupted errors which may be related to PHP bugs, have you seen this (#5149) ?

Re: Running out of colors. if you add /debug=yes to the graph url it will tell you if you have run out of colors (with that many VIPs/Pools you will have), please confirm this and I will add some more colors to the array.

I also have many unused VIPs/Pools and am looking at excluding these from graphs in a future PR. The problem is there is no run-time way (that I can find) of excluding them. The best I can do is pre-calculate which ones are used and build the graph with those. The problem with this approach is that if you were to select an alternate time period those items may or may not have any utilization.
I believe to v2 webUI may be able to handle this better.

**Comment by awlx** [comment]
I did the Select mentioned in #5149.

> mysql> SELECT `type` as `name`, count(*) as count FROM `component` WHERE `device_id` = 6 GROUP BY `type`;
> +-------------------+-------+
> | name              | count |
> +-------------------+-------+
> | f5-ltm-pool       |   759 |
> | f5-ltm-poolmember |  1270 |
> | f5-ltm-vs         |  1247 |
> +-------------------+-------+
> 3 rows in set (0.01 sec)
>

**Comment by rucarrol** [comment]
Hey @adaniels21487

Adding /debug=Yes/ causes the graph to stop rendering (!). While the graphs do render correctly, it's a fundamental issue with the F5's here - too many VIPs. 

I dont think it's a major issue tbh, just wondering if possible. 

I've deployed this PR to my entire LB fleet now, will report back in ~24hrs and see how it is working.

/Ruairi

**Comment by awlx** [comment]
I just upgraded to PHP 5.6. Let's see if that helps.

**Comment by rucarrol** [comment]
Since I dont have perms to push to this repo, I found a small correction on table sorting:

```
index 4671dc3..d44f10e 100644
--- a/html/pages/device/loadbalancer/ltm_pool_all.inc.php
+++ b/html/pages/device/loadbalancer/ltm_pool_all.inc.php
@@ -17,8 +17,8 @@
     <tr>
         <th data-column-id="poolid" data-type="numeric" data-visible="false">poolid</th>
         <th data-column-id="name">Name</th>
-        <th data-column-id="minup">Minimum Members</th>
-        <th data-column-id="currentup">Current Members</th>
+        <th data-column-id="minup" data-type="numeric">Minimum Members</th>
+        <th data-column-id="currentup" data-type="numeric">Current Members</th>
         <th data-column-id="status" data-visible="false">Status</th>
         <th data-column-id="message">Status</th>
     </tr>
```

/Ruairi

**Comment by awlx** [comment]
With the new PHP version (PHP 5.6.14 (cli) (built: Oct  2 2015 08:48:49)) it seems to be stable. Another good thing would be, to add the VIPs to the IPv4 table of LibreNMS to make them searchable.

**Comment by awlx** [comment]
And for sure I run out of colors.

http://i.imgur.com/VZO5elN.png

**Comment by awlx** [comment]
And the pool members are not displayed in the Pool overview.
http://i.imgur.com/48RNnTQ.png

**Comment by adaniels21487** [comment]
Hi @awlx 
Can you please let me know the graph type (in the querystring. eg: type=device_bigip_ltm_allvs_conns) and send a screenshot with the legend enabled (ok to blank out names if they are sensitive).
Pool member issue should be fixed now.

**Comment by awlx** [comment]
> type=device_bigip_ltm_allvs_conns
> type=device_bigip_ltm_allvs_bytesin
> type=device_bigip_ltm_allvs_bytesout
> type=device_bigip_ltm_allvs_pktsin
> type=device_bigip_ltm_allvs_pktsout

Those graphs are affected.

Screenshot of the whole graph is not so easy ;). I don't have a screen which is able to display the whole legend. And if I save the graph as picture, I cannot pixelate it because all programs crash (graph size 355MB uncompressed).

Maybe this still helps: 
http://i.imgur.com/Sx2AGAR.png

**Comment by awlx** [comment]
And I can acknowledge, pool-members work now.

**Comment by awlx** [comment]
Btw is the format of the IP address supposed to look like this? Or is it a bug? :)

http://i.imgur.com/BvoUuzv.png

**Comment by adaniels21487** [comment]
@awlx 
Re Graphs: The code loops through an array of color codes. The change made the other day was to go back to the start when the array ended. Mine looks like: http://i.imgur.com/WoSFveD.png
At line 35 of html/includes/graphs/device/bigip_ltm_allvs_conns.inc.php you should have a block of code that looks like this, please confirm.

        // Grab a colour from the array.
        if (isset($colours[$colcount])) {
            $colour = $colours[$colcount];
        } else {
            $colcount = 0;
            $colour = $colours[$colcount];
        }

Re IP Address: We just pull from SNMP so I assume this is the format your F5 is returning the data in. Please snmpwalk 1.3.6.1.4.1.3375.2.2.10.1.2.1.3 it will return a HEX value, we convert this to the IP. 
Mine looks like: http://i.imgur.com/YNUvNIU.png

Aaron

**Comment by adaniels21487** [comment]
@rucarrol are you seeing the same color issues with the allvs graphs as @awlx?

**Comment by rucarrol** [comment]
Hey,

So after a certain amount of colours in the graph, I end up with this: http://imgur.com/a/md4Jo 

It repeats down for another few hundred servers.

**Comment by awlx** [comment]
Output of snmpwalk http://i.imgur.com/Y0BzMWS.png

I have the codeline you mentioned.

**Comment by adaniels21487** [comment]
@awlx @rucarrol 
Hmm, I dont know whats going on..
Is one of you available on IRC to do some interactive troubleshooting?
can you send me the rrd command

**Comment by rucarrol** [comment]
Hey @adaniels21487 ,

We're both in the EU timezones, is that ok? I'll ping you in the LibreNMS channel. 

/Ruairi

**Comment by adaniels21487** [comment]
So I have taken a look at the RRD command from @awlx and it all looks good.
I have PM'd him the img and the colours are rotating through the array when rendered on my system.

Perhaps it is a RRD issue. I am running 1.4.8:
```
adaniels@dev:~$ rrdtool -v
RRDtool 1.4.8  Copyright 1997-2013 by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Nov 16 2014 14:30:06
```

I can't find anything relevant in the RRDtool github. What version of rrdtool do you run?

**Comment by awlx** [comment]
> RRDtool 1.3.8  Copyright 1997-2009 by Tobias Oetiker <tobi@oetiker.ch>
>                Compiled Apr  3 2014 13:07:03
> 

But somehow it started to work since yesterday. But I deleted all the rrd files (because of diskspace issues).

**Comment by rucarrol** [comment]
```
# rrdtool --version
RRDtool 1.5.5  Copyright by Tobias Oetiker <tobi@oetiker.ch>
```

So I'm on a newer version, so not 100% sure it's related to rrdtool. 

I did a: 
```
find /path/to/rra/directory -name "*f5-ltm*" -exec rm {} \;
```

To see if this will change anything in the same way it did for @awlx, however I still see the same cycle of reds :(

I'll poke about a bit more and see if I can spot anything more obvious.

**Comment by rucarrol** [comment]
Ok,

After a bit of looking (thanks, @awlx ), noticed I was not on the right branch. Corrected, and it looks good now! 

Thank you so much!

**Comment by adaniels21487** [comment]
Awesome, thanks team.
if there are no further issues, I think this is ready for a merge.

**Comment by laf** [comment]
Brilliant. Thanks everyone. Will take a look over the next day or so again just to be sure.

**Comment by laf** [comment]
image

**Pull request merged**
