### PR TITLE
Added support for additional Edge-Core ECS devices

### PR DESCRIPTION
**Pull request by kamils85**
Added support for additional Edge-Core ECS devices  
  
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
If you have access to these devices, would you mind generating some test files for us?

**Comment by kamils85** [comment]
I have access to ecs2100-28P (which is not added yet) and ecs4120-28F (already in).
I am new to git and this was my first commit. Not sure how to amend or add more to this thread so I am going to attach the test file here.   
Apologies for making it harder but I spent half a day trying to figure it out how to link another commit to this PR but I had to give up.

[edgecos_2100-28p.zip](https://github.com/librenms/librenms/files/3950700/edgecos_2100-28p.zip)

**Comment by Jellyfrog** [comment]
@kamils85 you add more commits to the same branch to include them here

**Comment by PipoCanaja** [comment]
Hi @kamils85 
I added the tests files from your zip capture. You can in fact do it directly from the github web gui. I also generated the json. Will see how it goes with the automated tests.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
