### PR TITLE
enable override of \$config[] values set in includes/definitions.inc.php

### PR DESCRIPTION
**Pull request by barryodonovan**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by barryodonovan** [comment]
I'd also like to edit the docs to reflect this but am uncertain where it might fit...

**Comment by Gorian** [comment]
does overriding them in config.php not work? That seems like a bug if config.php variables don't take priority...

**Comment by laf** [comment]
My personal opinion is no to this.

This could increase support burden as users can now edit two different config files. It also means that everything in definitions is now changeable so when someone is talking about (as an example) the small overview graphs not working, we expect to see the ones in definitions but now the user could have changed them all to three other graphs. So overall this means we can no longer trust what we expect to see.

The reason this was needed was to change the device type of an OS. This is possible (per device) in the WebUI. Whilst not the perfect solution for this, it is a solution and one that doesn't come at a cost to the potential burden this could bring. We will never be everything to everyone and this strikes me as one of those areas where a specific need shouldn't be reason to merge something in.

**Comment by barryodonovan** [comment]
since the refactor to use includes/init.php, there is no longer the same error with calling includes/definitions.inc.php before config.php
I have edited my patch to do this instead and removed the local_definitions file

**Comment by laf** [comment]
Running on my home install for a bit to test.

**Comment by laf** [comment]
All good with me.

**Comment by laf** [comment]
@librenms/reviewers 

Merginging 24 hours.

**Pull request merged**
