### PR TITLE
Adding support for Brocade NOS sensors (Temperature and fanspeed)

### PR DESCRIPTION
**Pull request by Linutux42**
#### Please note

> Please read this information carefully.

[x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)

[x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
When you created this pull request a template was there for you to complete, please do so.

**Comment by laf** [comment]
Needs a rebase.

Out of interest, how much other data is in the tree: 1.3.6.1.4.1.1588.2.1.1.1.1.22.1.?

**Comment by Linutux42** [comment]
Hi laf,

What rebase do you want me to do about the code ?

And the only other sensor in this tree is the power supply, which I planned to implement later.

**Comment by laf** [comment]
You need to rebase this branch as files have changed in upstream master to cause conflicts.

If their is only one other value in the tree then I'd probably say you should walk the root of that oid and then grab what you need rather than having to run 3 snmp queries - or at least benchmark to see which is quicker.

**Comment by Linutux42** [comment]
Ok I will rebase the branch.

After reading again the doc from Brocade, I can not implement the power state because the returned value is "unknown" from brocade ...
I will update the code and use the snmpwalk cache.

Thank you,

**Pull request merged**
