### PR TITLE
Maintenance Windows: recurring now works overnight

### PR DESCRIPTION
**Pull request by murrant**
Store dates in UTC, simplify storage.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Like you already said, this changes from database time(zone) to webbserver time(zone).                 Of course this is not librenms problem but it could end up causing confusion. 
Maybe a new validation check should be added that checks time difference between pho and database

**Comment by murrant** [comment]
That validation already exists :)  Also, "timestamp" fields are already in UTC

**Comment by murrant** [comment]
Not even close to ready :(

**Comment by murrant** [comment]
Got it sorted.

**Comment by murrant** [comment]
This code only deals with UTC time, except when displaying to the user.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
