### PR TITLE
rules: default alert rules, updated the name for

### PR DESCRIPTION
**Pull request by kkrumm1**
Sensor Over/Under to help users understand where this alert is coming from. :)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Possibly, not the best place for this.  Will not update existing rules for example.

What about detecting if there are multiple eventlog entries and then adding a custom message to the next eventlog? or something like that.

**Comment by kkrumm1** [comment]
@murrant that sounds like a way better idea. :)

**Comment by murrant** [comment]
How about an edit link in the eventlog, I wonder if it is reasonable to do that.

**Comment by kkrumm1** [comment]
Seems reasonable and helpful. idk about the coding part. :-)

**Comment by laf** [comment]
> Possibly not the best place for this. Will not update existing rules for example.

I'm not sure we should bother about old rules people have created. If users want to update existing rules then they can.

I'm fine with this as is, adding links in to eventlogs is over complicating this PR but could be good idea.

**Pull request merged**
