### PR TITLE
Improve getFullDn() to retrieve RDN

### PR DESCRIPTION
**Pull request by a084ed22**
The previous instance of getFullDn() naively composed the RDN that is then used in the user bind attempt by prefixing and suffixing the attributes defined in config.php.

It may be desirable to allow login with an arbitrary attribute (i.e. mail address), or, as it is the case for me, when the LDAP server does not store the username as the primary key for the entity, and therefore a typical login based on uid would fail.

I believe this change should not impact existing installations as it would still compose the same DN. My testing on this has however been limited. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I'm pretty sure fullDn was written that way to avoid LDAP queries to generate it.  Did you check how many additional queries this generates?

**Comment by murrant** [comment]
There is a chance this will break some installs.  I'm tempted to mark the ldap auth module as deprecated and suggest people use https://ldaprecord.com/docs/laravel/v2/

**Comment by murrant** [comment]
It was written with memberOf before and that didn't work with some user's setups as not all ldap servers implement memberof.

**Comment by murrant** [comment]
Hmm, I was just glancing at the Ldap code and saw almost a duplicate of what you have written here, related to the setting `auth_ldap_wildcard_ou`  Does that do what you want?  If it does, perhaps we just need a documentation update.

**Comment by a084ed22** [comment]
Unfortunately that is not sufficient. Even with `auth_ldap_wildcard_ou`, the code uses the naive uid=... DN when attempting to bind the logging in user to validate its credentials, and in my case it fails due to the LDAP being keyed on cn.

**Comment by murrant** [comment]
So, set auth_ldap_wildcard_ou and set auth_ldap_prefix to ''?

**Comment by laf** [comment]
@a084ed22 Does currants suggestion work for you?

**Comment by a084ed22** [comment]
Apologies for the late reply, I've not had the chance to run tests.

enabling auth_ldap_wildcard_ou and setting auth_ldap_prefix to "" is not sufficient for logins to pass, it'll report invalid credentials from the web interface due to AuthenticationException being thrown (as tested with the auth_test.php script).

**Comment by a084ed22** [comment]
Unfortunately, this appears to have broken again, beyond what my skills with php allow me to fix.

My approach seems to also not be compatible with the new changes of the php-ldap module for php >=8.x

As a result, we've migrated away from LDAP and to AD-based authentication for librenms.

I still believe it is erroneous, or at least naive, to construct the dn by composing it as a string, whereas it would be more correct to search for a specific user-unique attribute and derive the dn with ldap_get_dn()

**Pull request closed without merging**
