### PR TITLE
display device header/mini graphs

### PR DESCRIPTION
**Pull request by arjitc**
http://i.imgur.com/P5CNi8q.png
and normalise font above mini graphs to match scheme of page

### CODE REVIEW

**Comment by laf** [comment]
Not sure I like this personally (it actually looks great), it now takes up more screen estate and means you have to scroll to see the main image on a lot of resolutions.

**Comment by Rosiak** [comment]
Same with me, but I like the change of the font colours!

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Uhm no idea why but this breaks the dropdown selector of graph-types.
Compare these two:
https://1973.ci.librenms.org/graphs/to=1443342300/device=1/type=device_storage/from=1443255900/legend=yes/
http://master.ci.librenms.org/graphs/to=1443342300/device=1/type=device_storage/from=1443255900/legend=yes/

On the `master` you still have a valid dropdown with all the graph types, on `1973` you have an empty dropdown.

Generally I prefer `1973` under the condition that the dropdown is fixed.

**Comment by arjitc** [comment]
We can close this now, I've added the font change and the css fix to https://github.com/librenms/librenms/pull/2031

**Pull request closed without merging**
