### PR TITLE
Hide token, keys and passwords in Transports

### PR DESCRIPTION
**Pull request by LoveSkylark**
I've gone over all the Transporters adn changed all 'text' fields for token, keys and passwords to 'password' so the no longer show up as clear text in the GUI

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
You missed a spot, they all show in the transports window.

**Comment by LoveSkylark** [comment]
> You missed a spot, they all show in the transports window.

Not sure I understand what is the "Transports Windows"?
password is hidden in "/alert-transports" and in the edit of individual transports.

**Comment by murrant** [comment]
I didn't realize there was already code to handle password fields there.  Odd that these didn't use password.

Only question I have is do you consider urls that have token embeded to be secret too?

**Review by murrant — APPROVED** [review]

**Comment by LoveSkylark** [comment]
> 

I supposes I do, but I wasn't trying to harden code security here, I just saw the passwords where sometimes in cleartext and sometimes not so I am just making it a little cleaner and safer.

**Pull request merged**
