### PR TITLE
Add a warning about the cookie configuration

### PR DESCRIPTION
**Pull request by mikeSimonson**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7255)

### CODE REVIEW

**Comment by laf** [comment]
What's the reason for this? We actually setting as part of the authentication cookies. It's not used in install.php though.

**Comment by mikeSimonson** [comment]
If the httponly setting is set to on in the php configuration the ajax request made in the step of the install where the database is updated brakes.

**Comment by murrant** [comment]
@mikeSimonson Interesting, could setting that explicitly in install.php fix the issue too?

**Comment by laf** [comment]
@mikeSimonson Any comment?

**Comment by mikeSimonson** [comment]
@murrant Maybe it could, I am not really sure that you can taught.

**Comment by laf** [comment]
@mikeSimonson We set it in https://github.com/librenms/librenms/blob/master/html/includes/authenticate.inc.php#L7 already so seems possible to toggle it on / off in php. Not sure if that overwrites what the user sets in php.ini but it's worth a test.

**Comment by laf** [comment]
@mikeSimonson bump

**Comment by laf** [comment]
@mikeSimonson Feel free to comment on this still and we can re-open.

**Pull request closed without merging**
