### PR TITLE
Added ability to set a custom SQL query for alert rules.

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This would provide the flexibility some people need without us trying to shoe horn lots of things in to the Alert builder interface.

Also fixed the api for adding/editing rules.

### CODE REVIEW

**Comment by murrant** [comment]
Tested adding via the api this:
```
{"rule_id":1333,"device_id":"-1", "name": "apitest", "builder":"{\"condition\":\"AND\",\"rules\":[{\"id\":\"devices.hostname\",\"field\":\"devices.hostname\",\"type\":\"string\",\"input\":\"text\",\"operator\":\"equal\",\"value\":\"localhost\"}],\"valid\":true}","severity": "critical","count":15,"delay":"5 m","mute":false}
```

It tried to update non-existent rule and didn't fail.
It didn't give a specific error when I tried to send old format alert rule, or json was invalid.
QueryBuilder was not converted to sql (missing toSql call)

**Comment by laf** [comment]
@murrant Those issues should now be sorted.

**Comment by laf** [comment]
Rebased again, should be good to go.

**Comment by trs80** [comment]
This appears to have removed the transport restriction box in html/includes/modal/new_alert_rule.inc.php

Also I don't know if the recovery alerts checkbox is correctly hoooked up.

**Pull request merged**
