### PR TITLE
Add OS version to asuswrt-merlin

### PR DESCRIPTION
**Pull request by arrmo**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Just one change - add version as well to asuswrt-merlin. Confirmed that if the returned string is unchanged ... no change to OS Version. But if it's there, then it's taken into use.

Thanks!

### CODE REVIEW

**Comment by murrant** [comment]
@arrmo version is not set in your json file.

**Comment by arrmo** [comment]
> version is not set in your json file

Yep, see that too (good catch). But very odd. I say that because if I run snmpwalk, I get (as expected),
`UCD-SNMP-MIB::ucdavis.7890.1.101.1 = STRING: "ASUSWRT-Merlin RT-AC68U 384.16_0"
`

And from the Recent Events in LibreNMS,
`OS Version -> 384.16_0
`

So all seems to be working ... but not showing up in the tests for some reason? Thoughts?

Thanks!

**Comment by murrant** [comment]
The snmprec file does not contain that info for `1.3.6.1.4.1.2021.7890.1.101.1`

**Comment by arrmo** [comment]
OK, pulling my hair out ... LOL. You are absolutely right, but does this make sense to you?
1) Manually check,
`snmpwalk -O n -v2c -c public wap-livingroom 1.3.6.1.4.1.2021.7890.1.101.1
`
`.1.3.6.1.4.1.2021.7890.1.101.1 = STRING: "ASUSWRT-Merlin RT-AC68U 384.16_0"`
=> Yep, exactly as expected!

2) Collect Test Data,
`sudo -u librenms ./scripts/collect-snmp-data.php -h wap-livingroom
`
And then, in /opt/librenms/tests/snmpsim/asuswrt-merlin.snmprec
`1.3.6.1.4.1.2021.7890.1.101.1|4|ASUSWRT-Merlin RT-AC68U
`
=> Huh? Why only part of the string above? 

3) OK, tried deleting the test data, run again (in case it's just not overwriting),
`sudo -u librenms ./scripts/collect-snmp-data.php -h wap-livingroom
`
=> That's it! Not sure why, but I had to delete ... now it's there,
`1.3.6.1.4.1.2021.7890.1.101.1|4|ASUSWRT-Merlin RT-AC68U 384.16_0
`
OK, trying the PR again ... 😆. Thanks!

**Comment by murrant** [comment]
collect-snmp-data.php will not overwrite existing oids if I recall correctly.  just removing that one oid would have done the trick :D  But you got it.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Pull request merged**
