### PR TITLE
RFC1628 - Force cast on some values before doing arithmetic

### PR DESCRIPTION
**Pull request by fufroma**
Some devices (like Delta InsightPower G3 Mini SNMP Card) return STRING instead of numerical value.

A few lines after, when doing a division on it, everything go bad ( / $divisor).

I added force casting, no more crash and the values are OK.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
There is a helper funtion for that. Number::cast I think.

**Comment by fufroma** [comment]
> There is a helper function for that. Number::cast I think.

Thank you, I found `cast_number()` in `includes/helpers.php`, look like the wrapper I should have used.

**Comment by PipoCanaja** [comment]
Hi @fufroma 
Could you by chance provide test data (from any device you like) that now behaves correctly thanx to this PR ? The idea is to ensure that if this code is changed later and this cast is removed, tests will catch it (and the code will then be adapted to avoid any regression)
Thanx

**Comment by murrant** [comment]
I would prefer that you use the actual function call cast_number() is just a compatibility function:
```php
function cast_number($number)
{
    return \LibreNMS\Util\Number::cast($number);
}
```

**Comment by fufroma** [comment]
@murrant OK, I'll fix it :). It may be useful to add a _deprecated_ tag on the "old" function.

**Comment by murrant** [comment]
@fufroma good suggestion, but I'll probably just remove it because it is an internal function.

However, in your test data I don't see anything that would require this change.  Are you sure it is included in the snmprec?  What is the string output that you are getting from the device?  (technically all data returned from snmp is php string)

**Comment by fufroma** [comment]
I don't have access to the equipment until monday.

If my memory is right, it's the NULL data that require to be cast as 0.

Example: 
`1.3.6.1.2.1.33.1.3.3.1.2.2|5|`

**Comment by fufroma** [comment]
I checked: the crash are on the NULL lines.

Example:
```
$ ./discovery.php -h 269 -m sensors -ddd

[...]

Stack trace:
#0 /opt/librenms/includes/discovery/functions.inc.php(1011): include()
#1 /opt/librenms/includes/discovery/sensors.inc.php(84): sensors()
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(106): discover_device()
#4 {main}  
SQL[insert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (?, ?, ?, ?, ?, ?, ?) [null,"discovery","2022-11-14 07:49:17",5,"Error discovering sensors module. Check log file for more details.","",269] 0.56ms] 
  
Unsupported operand types: string / int {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string / int at /opt/librenms/includes/discovery/sensors/voltage/rfc1628.inc.php:58)"} 
```

OID for this crash : .1.3.6.1.2.1.33.1.4.4.1.2.2

snmprec for this OID : 1.3.6.1.2.1.33.1.4.4.1.2.2|5|

```
$ snmpget -v 2c -c REDACTED  HOST .1.3.6.1.2.1.33.1.4.4.1.2.2
iso.3.6.1.2.1.33.1.4.4.1.2.2 = NULL
```

@murrant does it look OK to you?

**Comment by fufroma** [comment]
I there something else I can provide?

**Comment by murrant** [comment]
@fufroma sorry, no, I still have a question.  If the response is NULL, that means the sensor should not be discovered right?

**Comment by fufroma** [comment]
This choice of implementation is entirely yours, I don't know if you rather have an empty sensor line for an existing sensor, or no sensor.

In my case, I chose to have a _minimal invasive surgery_ for the Librenms code as I'm not an expert :wink:

**Comment by murrant** [comment]
I will probably merge this, so it is less broken for those devices.  But, yeah, we should not discover those.

**Comment by fufroma** [comment]
Hello there,

Any news regarding this patch?

**Review by electrocret — APPROVED** [review]

**Review by murrant — APPROVED** [review]

**Pull request merged**
