### PR TITLE
Revert ironware BGP-peers changes from PR #10941

### PR DESCRIPTION
**Pull request by martijn-schmidt**
After deploying the BGP-peers code from PR #10941 on our production LibreNMS instance, it turned out that there are severe scaling issues with the BGP4V2-MIB on the NetIron platform if there are large amounts of sessions (in our case >1000 BGP peers): this results in heightened MP-CPU when polling, think a 25% overall increase.

Moreover, it appears that the router does a `show ip bgp summary` on the CLI to retrieve the data for BGP4V2-MIB and then only displays the output from the first "page". This means the output from all subsequent "pages" is missed.

Unfortunately these two issues weren't uncovered during my tests in the lab. My apologies for that.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Please re-generate the test-data as well. @martijn-schmidt

**Comment by martijn-schmidt** [comment]
Yep, working on that @PipoCanaja - hence the WIP :wink:

**Comment by martijn-schmidt** [comment]
@PipoCanaja should be good to merge now, although I'm still waiting to see if Travis has any complaints.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/brocade-bgp-broken/10830/4

**Comment by martijn-schmidt** [comment]
Tagging @PipoCanaja and @laf since both of you were talking about the revert - it should be ready now, Travis also seems to be happy.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
