### PR TITLE
More sensor data on inventory page

### PR DESCRIPTION
**Pull request by PipoCanaja**
Not all sensors have an entPhysical entry dedicated. Current code only display those. This patch checks every entPhysical and if they are matched to a sensor, displays it. 

Cisco Before and after:
Capture d’écran 2021-07-19 à 11 49 33
Capture d’écran 2021-07-19 à 11 49 17

Huawei Before and After:
Capture d’écran 2021-07-19 à 11 47 30
Capture d’écran 2021-07-19 à 11 46 42

Adva Before and After:
Capture d’écran 2021-07-19 à 11 47 57
Capture d’écran 2021-07-19 à 11 48 21

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by mpikzink** [comment]
Very cool! I see in your pictures there little +-. symbols which are not shown I my live and test env (Apache with alias). I didn't even notice the buttons until now, even though I used Inventory regularly :-) . Isn't it possible to convert this symbols to fas? Fas works very well. It's just the gifs which makes this problems.

**Comment by PipoCanaja** [comment]
> Very cool! I see in your pictures there little +-. symbols which are not shown I my live and test env (Apache with alias). I didn't even notice the buttons until now, even though I used Inventory regularly :-) . Isn't it possible to convert this symbols to fas? Fas works very well. It's just the gifs which makes this problems.

Hi @mpikzink 
Sorry I don't get it. Could you post a capture ? may be into the community forum more than here by the way.

**Comment by rhinoau** [comment]
👍  Works well for me on Cisco and Cisco Industrial.

I note it doesn't work for my recently merged Scalance OS - which has a parent/child entPhysical bug pending with the vendor: https://github.com/librenms/librenms/pull/12938#issuecomment-857481866 A quick look at the code suggests that may be why, or maybe I'll have more work to do after this gets merged :smirk:

**Review by Jellyfrog — APPROVED** [review]
You should convert it to blade next :)

**Pull request merged**
