### PR TITLE
ns-bsd updated for SNS LTSB 3.7.19

### PR DESCRIPTION
**Pull request by Mar974**
Since the LTSB version of the stromshield OS in 3.7.19 (and also in last version in 3.7.20) the stormshield firewall are seen as a generic device.

The objectID in the MIB as change from ".1.3.6.1.4.1.8072.3.2.8" to ".1.3.6.1.4.1.11256.2.0" 

see https://github.com/librenms/librenms/issues/12915

Tested on SNS 3.11.10

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Now it won't work for older firmwares, you need to add both of them.
Could you also post the sysdesc of the device?

**Comment by Mar974** [comment]
OK i added a table so the old and the new one will match.
The sysDescr contain the serial number, exemple NS-BSD SN510XXXXXXXX amd64 so we need to keep the regex

**Comment by murrant** [comment]
Need to add a little test data.
I do think the multi-line array that was already there was a little more readable, just need to add another line `- .1.3.6.1.4.1.11256.2.0`

**Comment by Mar974** [comment]
Ok i Changed the array to multiligne and collected some test data, where should i upload the test data ?

**Review by murrant — DISMISSED** [review]

**Review by murrant — APPROVED** [review]

**Pull request merged**
