### PR TITLE
fix: Strip " and / from snmpwalk_cache_oid()

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #6993 

I've not done any other snmp functions yet but they probably should be done to save trim() being used everywhere.

### CODE REVIEW

**Comment by murrant** [comment]
@laf you could also just modify the previous trim.

snmpwalk_group() trims quotes, but not / why is that needed?

**Comment by laf** [comment]
@murrant I left the old trim in place as that trims the defaults off, if you specify what to trim that doesn't happen anymore does it? I thought it didn't hence adding the new trim.

The / is in the snmpwalk output so seems to be sent back by the device. I've seen this in other walks as well.

**Comment by murrant** [comment]
You can include the defaults.

This is what I have snmpwalk_group()
```
trim($value, "\" \n\r")
```

**Comment by murrant** [comment]
I couldn't find an example of `/` in the linked bug.  I did however see an example of `""/""` where this would cause it to return `""` instead of `"/"`

**Comment by laf** [comment]
The poller output in the bug report shows what is returned now:

`\Core: Raymon[1Gbit](Uplink Raymon) {O000002}\`

Seeing as we also have to trim `"` I've added them both in, I can update and add what you use for `snmpwalk_group` as well.

**Comment by murrant** [comment]
laf: the \" is because the " is in the string inputed by the user and the snmp daemon escapes it...

Look at this one: `\"Cust: Raymon[1Gbit](crs2.dro2.raqxs.net Eth3 - Trunk) {O000002}`

**Comment by laf** [comment]
Which of those are you concerned about as it looks like we should strip them all.

**Comment by murrant** [comment]
laf mostly, the `\` because it should only be trimmed if it precedes `"`

It is likely that particular edge case will never cause us any issues.

**Comment by laf** [comment]
It's a bit of a rabbit whole this.

This is what I've come up with so far but I feel less comfortable about this solution then I do my original:

https://p.libren.ms/view/raw/b6afe033

**Comment by murrant** [comment]
Your paste isn't loading.  What do you think about just trimming: `"\" \\\n\r"` and seeing how it goes?

**Comment by laf** [comment]
Updated

**Pull request merged**
