### PR TITLE
Prevent duplicate schema updates

### LINKED ISSUE #3133: Prevent Duplicate Schema Updates
DB Schema updates are currently performed both from daily.sh and discovery.php.  If a schema update takes long enough (e.g. 106 from #3129) then it's possible for two copies of this to run.  In my case, I was running daily.sh manually when cron ran discovery.php, but if an update takes >5 minutes then discovery.php is going to stack up, running multiple copies.

In the case of 106, the end result is not too harmful - duplicate indexes are added.  Future updates may have a more problematic outcome.

The simplest fix to this is to prevent discovery.php from running DB updates (perhaps it could print a warning saying that a DB update is required).  A more advanced approach would be to detect another update in process and fail.

### PR DESCRIPTION
**Pull request by richardlawley**
This PR uses MySQL's GETLOCK to prevent multiple concurrent schema updates from running at the same time.  If a second one (e.g. discovery) runs while another is running, it will wait 10 seconds for the existing one to finish.  If after that time the lock wasn't obtained, the program exits.

It might be that you'd prefer the program carries on running, skipping the schema update instead of exiting, but I think this is safer (discovery in future may depend on something in the schema update, for example).

Fixes #3133, thanks to @ekoyle for the idea.

This update also fixes the current problem of lots of the initial build-base inserting lots of rows in dbSchema rather than just updating one.

### CODE REVIEW

**Comment by murrant** [comment]
@richardlawley How are you dealing with the lock timeout?  The default for mysql seems to be 50s.  Is this enough time?  Do we run the risk of stalling users dbschema?

**Comment by richardlawley** [comment]
@murrant I wasn't aware of any lock timeout, it's not mentioned in the [MySQL documentation](https://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_get-lock), and in my simple testing with two console sessions, I've held a lock obtained with GET_LOCK for >5 minutes while I investigated.  From what I can see, the lock timeout is on obtaining the lock only - once you've got one, you have it until you release it or your MySQL session ends.

If you have information to the contrary, I'm no MySQL expert - I only discovered this function today!

With my current implementation, the second program trying to obtain the lock will wait 10 seconds, then exit(1) if unsuccessful.  It only tries to obtain the lock if it thinks the DB is out of date (i.e. the first check is performed without a lock).

**Comment by ekoyle** [comment]
I don't know if that timeout is in effect for cooperative locking.  This is not the same as a table lock.

Also note that prior to MySQL version 5.7.5 or mariadb 10.0.2, only a single lock could be held by a connection and a call to get_lock will implicitly release the lock that is held.

One other caveat:

```text
GET_LOCK() is unsafe for statement-based replication. A warning is logged if you use this function when binlog_format is set to STATEMENT. 
```

**Comment by ekoyle** [comment]
@murrant: also, locks are released either explicitly or implicitly when the connection is closed, so theoretically the only way a db update stalls is if something hangs during the schema update process.

**Comment by murrant** [comment]
I'm not a MySQL expert either.  i just want to make sure it fails gracefully.

**Comment by ekoyle** [comment]
Is anyone using statement-based replication for their librenms install? That could be a show-stopper if that is a supported configuration :/ .

**Comment by ekoyle** [comment]
@f0o: Any thoughts on this one?  Do you use binlog_format=STATEMENT in your environment?

It looks like it should(TM) work if binlog_format is either mixed or row-based.

**Comment by laf** [comment]
@f0o how do you feel this would work in your env with the MySQL setup you have?

**Comment by f0o** [comment]
Based on MariaDB Galera setups that I have, it's been fine so far.

The locks of course do NOT traverse through the galera so if any code makes changes to the locked table, it will still be processed and afterwards merged by the SST..

However, I rarely (by that I actually mean never) had the issue that a schema was about to be applied twice.. So I'm not sure my tests are of any use :S

**Comment by ekoyle** [comment]
I was thinking that putting all the schema updates within transactions
could help with this, but apparently mysql does an implicit commit for most
DDL operations (I'm used to postgresql, there are only a couple of
operations like drop database that are not transactional).

https://dev.mysql.com/doc/refman/5.5/en/implicit-commit.html

So, is it reasonable to require that discovery.php and daily.sh always run
against the same database host in a clustered environment?  Is there any
way we could verify that people aren't running against multiple db hosts?

The only other real solution I can see for this would be to find/create
some sort of a (centralized|distributed) lock manager service, which
doesn't sound all that fun...

**Comment by laf** [comment]
I'm not 100% sure we should be changing the way this works at the moment imho. I've not heard of any cases of duplicate schema changes happening. With v2 of the webui underway, this includes a robust schema update mechanism - we should consider trying to use that as the base for schema updates.

**Comment by richardlawley** [comment]
Fair enough, the update I wrote this for has already been released anyway.

**Pull request closed without merging**
