### PR TITLE
Added PowerConnect 3548 support

### PR DESCRIPTION
**Pull request by alangregory**

### CODE REVIEW

**Comment by laf** [comment]
Hi @alangregory 

We've just gone through a big update to fix code formatting so we will be a little stricter now on how files are formatted. Please take a look at: http://docs.librenms.org/Developing/Code-Guidelines/ to help fix some of the issues in this file and if you can update the PR that would be great.

Thanks.

**Comment by alangregory** [comment]
@laf Some code was old, check is it's ok now

**Comment by laf** [comment]
Thanks @alangregory.

Still some not quite right, check the Files changed tab at the top of here but things like:

if ($device['os'] == "powerconnect")
{

foreach (explode("\n",$temps) as $oids)
{

Also you don't need to use " when echoing and not using variables so:

$descr = "Internal Temperature";

Should be:

$descr = 'Internal Temperature';

Thanks.

**Comment by alangregory** [comment]
Ok, i'll fix it, thats the old code part.

**Comment by laf** [comment]
Thanks. It looks like lines (in the old file) 3,4, 13, 41 and 42 are still being updated when they shouldn't be, you don't need a space after snmp_get or before the , in each of the items in the function + if () { needs to be on one line still.

**Pull request merged**
