### PR TITLE
Speedup vlans list in device VLANS tab

### PR DESCRIPTION
**Pull request by Negatifff**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Definitely resulted in a speedup.  Porting the queries to eloquent could make it easier.

Unfortunately, sorting was odd for some reason:
image

**Comment by Negatifff** [comment]
strange, but I didn’t have this. I'll see what it can be and try to fix it after leaving the hospital.

**Comment by murrant** [comment]
Probably orderBy ifIndex for the ports query... odd that it happened as really it looks like the changes you make shouldn't affect order.

**Comment by Negatifff** [comment]
it seems like you just need to add forced sorting by ifindex. but in php, not mysql.

**Comment by murrant** [comment]
oh, yeah.  I was curious about what this would look like if ported to Eloquent:
https://github.com/librenms/librenms/compare/master...murrant:vlans-cleanup

Feel free to copy anything from there if you want.

**Comment by Negatifff** [comment]
thank. I’m not ashamed to copy, but it’s not always easy to understand the whole structure in order to know where to copy :). your code is more elegant - let's leave it.

**Comment by murrant** [comment]
I think my code might be slower too, it is unoptimized.  Care to test it?

**Comment by Negatifff** [comment]
I would like to test, of course. but I'm in the hospital now and I can only do it in a week.

**Comment by murrant** [comment]
@Negatifff sorry to hear.  No rush.

**Comment by Negatifff** [comment]
Very strange, but I see next
Screenshot_20200713_134545

**Review by murrant — APPROVED** [review]
sure, not that excited about the code style here though.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
