### PR TITLE
Allow administrators to edit devices sysName

### PR DESCRIPTION
**Pull request by remyj38**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

-----
- New feature to allow administrators to edit the device sysName from edit page.
- Fixing indentation of html/pages/device/edit/device.inc.php

### CODE REVIEW

**Comment by laf** [comment]
This will just revert back to what's found in polling / discovery.

Why allow this to be changed out of interest?

**Comment by remyj38** [comment]
In my usage of LibreNMS, I have a lot of hosts which don't have SNMP (so don't have sysName).
For this kind of hosts, it's easier to find it if a sysName is set.

**Comment by laf** [comment]
> In my usage of LibreNMS, I have a lot of hosts which don't have SNMP (so don't have sysName).
> For this kind of hosts, it's easier to find it if a sysName is set.

Ok but this change allows it for anyone. For snmp based devices the value will just be overwritten. You need to look at `html/pages/device/edit/snmp.inc.php`, that file allows certain input boxes to be shown when snmp is disabled only which is what you want.

You also shouldn't have the edit pencil button next to the input, just allow it be changed if it's non-snmp based.

Last thing, admin users should be allowed to change this like you have, but also normal users with permission to edit the device. You can use `device_permitted()` to determine this.

**Comment by remyj38** [comment]
c4700d3d1c303d53e7cd4db44ca68dff48f13a90 follows your recommendations

**Comment by murrant** [comment]
Wouldn't mind allowing this for all devices, to allow users to set custom display names on anything.

This is a good start, thanks.

**Pull request merged**
