### PR TITLE
Rewrite smokeping script to be an lnms command

### PR DESCRIPTION
**Pull request by TheMysteriousX**
I started off trying to make the existing smokeping script not kill smokeping if it was unable to resolve the device for any reason, and ended up rewriting it. Still to do is a documentation update, and some tests.

Smokeping's configuration format is... interesting, so I've taken a line-by-line approach to generating the configuration.

It is **not** a drop in replacement for the existing script, as it generates both probe and target blocks to support multi processing and IPv6, but can be invoked as follows to generate a compatible configuration:

```
./lnms smokeping:generate --targets --no-header --single-process
```

I need to update the docs, but all that should be needed to use it for new deployments is to remove the default smokeping probe and target stanza's.

This version will not insert unresolvable devices into the configuration:

```
...
# "junkdevice.example.org" was not resolvable and was omitted from the configuration
...
```

It will also support both IPv4 and IPv6 pollers, with multiple processes:

```
smokeping[4964]: Smokeping version 2.006010 successfully launched.
smokeping[4964]: Entering multiprocess mode.
smokeping[4964]: Child process 5011 started for probe lnmsFPing60.
smokeping[4964]: lnmsFPing60: probing 3 targets with step 60 s and offset 38 s.
smokeping[4964]: Child process 5012 started for probe lnmsFPing0.
smokeping[4964]: Child process 5013 started for probe lnmsFPing61.
smokeping[4964]: lnmsFPing0: probing 41 targets with step 60 s and offset 22 s.
smokeping[4964]: Child process 5014 started for probe lnmsFPing63.
smokeping[4964]: lnmsFPing61: probing 3 targets with step 60 s and offset 10 s.
smokeping[4964]: lnmsFPing63: probing 2 targets with step 60 s and offset 8 s.
smokeping[4964]: Child process 5015 started for probe lnmsFPing3.
smokeping[4964]: No targets defined for probe FPing6, skipping.
smokeping[4964]: No targets defined for probe FPing, skipping.
smokeping[4964]: lnmsFPing3: probing 40 targets with step 60 s and offset 4 s.
smokeping[4964]: Child process 5016 started for probe lnmsFPing2.
smokeping[4964]: lnmsFPing2: probing 40 targets with step 60 s and offset 42 s.
smokeping[4964]: Child process 5017 started for probe lnmsFPing62.
smokeping[4964]: lnmsFPing62: probing 3 targets with step 60 s and offset 49 s.
smokeping[4964]: Child process 5018 started for probe lnmsFPing1.
smokeping[4964]: All probe processes started successfully.
smokeping[4964]: lnmsFPing1: probing 40 targets with step 60 s and offset 49 s.
```

```
# ./lnms smokeping:generate --help
Description:
  Generate a configuration suitable for use with smokeping

Usage:
  smokeping:generate [options]

Options:
      --probes              Generate probe list - used for splitting the smokeping configuration into multiple files. Conflicts with "--targets"
      --targets             Generate the target list - used for splitting the smokeping configuration into multiple files. Conflicts with "--probes"
      --no-header           Don't add the boilerplate comment to the start of the generated file
      --single-process      Only use a single process for smokeping - useful for integrating LibreNMS with an existing smokeping setup
  -h, --help                Display this help message
  -q, --quiet               Do not output any message
  -V, --version             Display this application version
      --ansi                Force ANSI output
      --no-ansi             Disable ANSI output
  -n, --no-interaction      Do not ask any interactive question
      --env[=ENV]           The environment the command should run under
  -v|vv|vvv, --verbose      Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Crash0v3r1de** [comment]
Pulled this PR and followed the guide here: https://github.com/librenms/librenms/pull/11585/files?short_path=5f2529f#diff-5f2529feb08b994fca3f624ae976b0b3

Removed the librenms.conf in the general includes and added the targets and probes files, smokeping is still looking for the old librenms.conf file for some reason. restarted the service a few times with no luck.

target and probe files seem to be bad/not generated at all. They both only contain this:
`Use one of --probes and --targets`

Not sure what to try but I can't do much anyway since the probe and target files aren't usable. I have the PR so if you want me to test anything on this PR just let me know and I can send the outputs from here.

**Comment by TheMysteriousX** [comment]
I've re-written the documentation - they now assume LibreNMS is the only thing generating configuration for smokeping. It should work for most people, unless there's something I've missed.

**Comment by TheMysteriousX** [comment]
Did you get a chance to try the revised version @Crash0v3r1de?

Would be good to get a second pair of eyes over this as the old code lacks tests.

**Comment by TheMysteriousX** [comment]
@Negatifff I'm not certain grouping things by the first two domain components of the device name is the best way to group sytems.

It may be better to look at the hierarchies directive in the *** Presentation *** stanza and do something there, which would be cleaner than deeply nesting the rrd directory.

Also make sure you're using fcgid, and that your fcgid processes are actually sticking around and aren't being reaped due to e.g. memory pressure - I have a lot of devices too, but the render time after the first load is < 2 seconds.

**Comment by Negatifff** [comment]
Good day.

The logic of such a grouping is quite simple - the IP address, in fact, is the only thing that does not change for the device (except for the mac address, of course, but here the mac address does not fit at all). if there is a hostname - it will be used. if not - then only IP.

I plan to monitor ~ 13,000 devices, but only 1,500 have been added now. And now, by going to the smokeping page, a very long list of devices is available. therefore, in my opinion, grouping by IP with host priority is a very good option. firstly it is well and clearly grouped, and secondly - how else to group? leaving without grouping is not an option.

I watched Presentation - this is a regular html, in which smokeping adds the specified hierarchy from own config. the only thing that can be done here is to play with the smokeping config, but there too everything will rest against the location of the files.

**Comment by TheMysteriousX** [comment]
I'm not sure the changes you've made have the effect expected outside your deployment then - are you relying on a certain host naming pattern, or on having a large number of devices added by IP?

I tried your changeset on my production system, and ended up with a longer menu strip with than without it.

**Comment by Negatifff** [comment]
> I'm not sure the changes you've made have the effect expected outside your deployment then - are you relying on a certain host naming pattern, or on having a large number of devices added by IP?
> 
> I tried your changeset on my production system, and ended up with a longer menu strip with it than without it.

Yes, I add devices on IP. But ... if a hostname is used instead of an IP - crushing does not occur as for an IP - the rrd is stored in a folder named as a hostname.

**Comment by mcineran** [comment]
I've implemented smokeping with this method, the graphs are showing nicely in the librenms latency tab.
All appears to be working fine.

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/smokeping-cron-script-outputting-there-are-no-commands-defined-in-the-smokeping-namespace-in-nms-confs/13488/2

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
