### PR TITLE
Ignore HC Broadcast and Multicast Counters for Cisco SB as they're al…

### LINKED ISSUE #2376: Issue with multicast and broadcast counters on Cisco SMB
Looks like we use the HC counters for multicast+broadcast if numeric values are returned, but in my case they are never updated. Non-HC values looks good though. 
https://github.com/librenms/librenms/blob/master/includes/polling/ports.inc.php#L271-L277

snmpwalk grepping for information about a specific port:
```
IF-MIB::ifInMulticastPkts.49 = Counter32: 74015
IF-MIB::ifInBroadcastPkts.49 = Counter32: 275
IF-MIB::ifOutMulticastPkts.49 = Counter32: 3783
IF-MIB::ifOutBroadcastPkts.49 = Counter32: 13
IF-MIB::ifHCInOctets.49 = Counter64: 4413025560
IF-MIB::ifHCInUcastPkts.49 = Counter64: 0
IF-MIB::ifHCInMulticastPkts.49 = Counter64: 0
IF-MIB::ifHCInBroadcastPkts.49 = Counter64: 0
IF-MIB::ifHCOutOctets.49 = Counter64: 89120556513
IF-MIB::ifHCOutUcastPkts.49 = Counter64: 0
IF-MIB::ifHCOutMulticastPkts.49 = Counter64: 0
IF-MIB::ifHCOutBroadcastPkts.49 = Counter64: 0
```

### PR DESCRIPTION
**Pull request by SaaldjorMike**
…ways 0

Fix #2376

### CODE REVIEW

**Comment by paulgear** [comment]
My question to this would be: is it consistent on all models which might match os == 'ciscosb'?

**Comment by SaaldjorMike** [comment]
@paulgear Unfortunately all my devices are of the Cisco Small Business 300 series. It would for sure be nice to test against 200 and 500 series as well before merging, but I dont have any of them myself.

If anyone got Cisco SB 200 series and/or 500 series and want to test it, please do so and report back here. If the switches are publicly available and anyone wants me to test it for them, please send the ip+snmp information to mike@librenms.org

**Comment by f0o** [comment]
bump
@SaaldjorMike maybe reach out to Mailinglist and IRC?

**Comment by paulgear** [comment]
I've just put out a tweet as well.

**Comment by SaaldjorMike** [comment]
I've now sent a message out to the mailinglist.

**Comment by paulgear** [comment]
No response to mailing list message or tweet; merging.

**Pull request merged**
