### PR TITLE
Fix LibreNMS Logo SVG missing i sometimes

### PR DESCRIPTION
**Pull request by YisroelTech**
Corrected an issue with the "i" being invisible in certain scenarios on certain (Chromium version 77) browsers, see https://community.librenms.org/t/librenms-svg-logo-issue-in-some-zooms/9640/4. The issue seems to be that "i" was a separate clip-path from the "L bre".

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/librenms-svg-logo-issue-in-some-zooms/9640/5

**Comment by chasgames** [comment]
Nice, fixes the issue for me.

Tested on 
Windows 10
Chrome 77, Chrome 79
Firefox 69.0.1

Kubuntu
Chrome 77

Can you also make the same fix for the other themed SVGs? :D 
librenms_logo_blue.svg
librenms_logo_dark.svg
librenms_logo_mono.svg

**Comment by YisroelTech** [comment]
Changed all 4 (it is technically two since blue is the same as light and dark is the same as mono...)

Someone (I guess from the team) needs to do it for the one on https://www.librenms.org/

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
