### PR TITLE
Added support for Juniper EX2500 switch

### PR DESCRIPTION
**Pull request by barhom**
This should get the EX2500 Juniper loaded and properly identified.

### CODE REVIEW

**Comment by Rosiak** [comment]
I don't think we should create a separate OS for this device, junos should be plenty.

**Comment by barhom** [comment]
Do you mean by adding
```
+<?php
 +
 +if (!$os) {
 +    if (strstr($sysObjectId, '.1.3.6.1.4.1.1411.102')) {
 +        $os = 'juniperex2500';
 +    }
 +}
```

to discovery/os/junos.inc.php ?

**Comment by laf** [comment]
Nope: `$os = 'junos';` and then adding the check into the junos.inc.php file.

$os _has_ to represent the OS the device runs not the model.

If you haven't done you'll also need to sign the contributors agreement form.

Thanks

**Comment by barhom** [comment]
Sure, I understand that @laf.

Although you should know that the ex2500 does NOT run junos.

**Comment by laf** [comment]
What does it run then?

**Comment by barhom** [comment]
Take a look at the snmpwalk here: https://github.com/librenms/librenms/issues/3140

I dont really know what the [EX2500](https://www.juniper.net/techpubs/en_US/release-independent/junos/information-products/pathway-pages/ex-series/hardware/ex2500.html) runs.

I believe that Juniper purchased the switch from some OEM manufacturer and simply put their name on it. There is no mention of which OS it runs but it definitely does NOT run junos.

What do you suggest we do with this switch if it doesn't run JUNOS?

**Comment by barhom** [comment]
According to [Juniper Wikipedia Page](https://en.wikipedia.org/wiki/Juniper_EX-Series)

The EX2500 is a rebranded OEM product which does not run JunOS. Its technical configuration, performance and physical case style is similar to the Blade Network Technologies RackSwitch G8124.

Although that doesn't give us an answer regarding which OS.

**Comment by barhom** [comment]
Ill make a new pull request once I sign the agreement.

**Pull request closed without merging**
