### PR TITLE
Change alert worse/better wording

### PR DESCRIPTION
**Pull request by eg2965**
Please give a short description what your pull request is for

I've updated the AlertState Syntax in RunAlerts.php -

_got better_ has been updated to _Has Improved_, _got worse_ has been updated to _Has Worsened_, and _acknowledged_ has been updated to _Has Been Acknowledged_. This will make the look and feel of the alerts more professional.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

I've run the ./lnms dev:check command, and am getting the following output:

ERRORS!
Tests: 3275, Assertions: 7691, Errors: 124, Failures: 1, Skipped: 109, Risky: 7.
failed (114.39s)

However, most of the errors seem erroneous, and the single failure is the following:
1) LibreNMS\Tests\Unit\SqliteTest::testMigrationsRunWithoutError
Database file at path [/opt/librenms/database/testing.sqlite] does not exist. Ensure this is an absolute path to the database. (Connection: testing_persistent, SQL: PRAGMA foreign_keys = ON;)

This is my first pull request, so I'm not completely confident in the process yet. Obviously I don't want to cause issues with the main repository. Can you let me know if my request is in order and is good enough for approval? If not, I'd appreciate it if you could let me know what I need to modify in order to for it to go through.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/) **YES**.
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it. **N/A**.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/). **N/A**.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I like it, but I wonder if people have email rules etc that need the specific existing wording?

**Comment by eg2965** [comment]
> I like it, but I wonder if people have email rules etc that need the specific existing wording?

You have a point, however here's my counter argument as to why we should still proceed -

We're not updating anything that will affect the standard alert/recovery process. If an alert triggers and recovers, none of the syntax changes I've made will come into play. What will be affected are the 3 processes surrounding the acknowledgment functionality of LibreNMS. I can't speak for the community at large, but I personally have many gmail rules setup, and none of them relate to acknowledged/got better/got worse. My alert rules trigger on other syntax (i.e. the device name, the alert title, etc.) I'm not sure this will affect all that many people if we were to proceed. Also, to reiterate what I wrote in the original pull request, I think this is worth doing in the long run in order to make Libre's alerts look more professional.

All that being said, you guys have the final say of course. Let me know if you agree with my logic or if this request is getting shut down :)

**Comment by eg2965** [comment]
Hi Tony @murrant - wanted to follow up in case you didn't see my last comment.

**Review by laf — APPROVED** [review]
I made a small change as we shouldn't capitalise each letter but good improvement overall. Thanks @eg2965

**Pull request merged**
