### PR TITLE
refactor - remove unused entPhysicalIndex_measured

### PR DESCRIPTION
**Pull request by PipoCanaja**
These entPhysicalIndex_measured variable are unused and may let the reader imagine they make sense. So cleaning them up here. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
This is used in a couple of places, for example 
https://github.com/librenms/librenms/blob/d90a704fcb65befa5b8869172fbe5bbf6ee2763a/includes/html/pages/device/port.inc.php#L89

https://github.com/librenms/librenms/blob/d90a704fcb65befa5b8869172fbe5bbf6ee2763a/includes/html/pages/device/port/sensors.inc.php#L5

**Comment by PipoCanaja** [comment]
> You should change the yaml schema to only allow the values we support.

Sounds good. Trying to convince myself I succeeded :)

**Comment by PipoCanaja** [comment]
> The yaml validation comes after the os test data step due to how phpunit works

OK so I need to generate the JSON file that is currently failing with the matching data, for the validation of the YAML to occur. Will do.

**Comment by PipoCanaja** [comment]
OK, the tests are now failing as expected : 
```
1) LibreNMS\Tests\YamlSchemaTest::testDiscoveryDefinitionSchema
loop-telecom.yaml does not validate. Violations:
[modules.sensors.temperature.data[1].entPhysicalIndex_measured] Does not have a value in the enumeration ["ports",null]

```

I am now fixing the YAML and the resulting tests and this PR will be good to go.

**Review by murrant — APPROVED** [review]

**Pull request merged**
