### PR TITLE
Ajax forms header additions

### PR DESCRIPTION
**Pull request by pblasquez**
Found more application/json and text/plain header additions necessary to play nice with reverse proxies.

### CODE REVIEW

**Comment by Rosiak** [comment]
html/includes/forms/component.inc.php
html/includes/forms/update-dashboard-config.inc.php
html/includes/forms/update-ports.inc.php

Could just be my tired brain, but why no semicolon?

**Comment by pblasquez** [comment]
You're absolutely right, my brain was the tired one apparently.  Fixed!

**Comment by laf** [comment]
With the amount of files this changes I'd propose one of two things:

 - The PR is separated out so testing can be done and made easier
or
 - We just don't bother fixing this, it's not causing issues afaik and the rewrite will deal with all of this.

**Comment by pblasquez** [comment]
I wouldn't be submitting this if it didn't cause issues.  Set up an environment where you are accessing the LibreNMS site via apache reverse proxy and try to do anything using ajax forms.

**Comment by f0o** [comment]
Instead of setting the header on each include/form/xyz, why not just set it in tge upper layer wrapper (ajax_*) ?

**Comment by pblasquez** [comment]
Because each form has different headers.

**Comment by laf** [comment]
No limit in the PR to the number but if they were grouped logically that would help with testing. I.e all alerting stuff, etc.

**Comment by pblasquez** [comment]
Ok will close this one and re-open multiple PRs with grouped changes.

**Pull request closed without merging**
