### PR TITLE
Added Datacom support and some png permissions fix (664)

### PR DESCRIPTION
**Pull request by alangregory**
Added Datacom devices basic support with snmp Mibs and fixed some permissions of png files .

### CODE REVIEW

**Comment by laf** [comment]
@alangregory That's perfect if you can just drop the images from this pr and do that as a separate one so the history is readable that would be awesome. Feel free to just add another commit to this pr with the permissions changed back and we can merge this one in :)

Aside from that it's good to go :)

**Comment by alangregory** [comment]
I'll do a new. Learning it.

**Comment by laf** [comment]
Thanks for sticking with it @alangregory :) If you need any help jump in our irc channel.

**Comment by paulgear** [comment]
@alangregory - thanks again for the contribution! Another small request: please add the MIBs in a separate commit, and provide the link where you obtained them in the commit text.  This makes it easy for us to track down later.  You can still leave it in the same PR, e.g.

git commit -m'Add datacom MIB from https://example.com' mibs/nameofmibfile
git commit -m'Add basic datacom support' includes/
git push alangregory/datacom-support

Thanks,
Paul

**Comment by alangregory** [comment]
I'll do it on next  PRs, thanks for the tip @paulgear

**Pull request closed without merging**
