### PR TITLE
Allow for port misc config option during add on add device form

### PR DESCRIPTION
**Pull request by jepke**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I'm not sure if it is a good thing to add more options to the device add web page.
I think it might be more appropriate to have an API that can set device attribs.

**Comment by jepke** [comment]
Made it optional and hidden by default to avoid confusion.

Also added a fixed subset of attribs to the api_functions, my skills couldnt come up with a way to have a more dynamic way of setting attribs through the API.

**Comment by PipoCanaja** [comment]
Hi @jepke 
Are you still working on this ?
Thx

**Comment by PipoCanaja** [comment]
Hi @jepke 
As this PR seems to be stalled, we'll close it for now. Whenever you have time to continue it, feel free to re-open.
Thanx

**Pull request closed without merging**
