### PR TITLE
Added sysObjectID for Canon LBP printer series

### PR DESCRIPTION
**Pull request by githubuserx**
I mentioned missing Canon LBP series printers some time ago in issue #5637, but didn't find the time to submit a PR until now. There also seems to be an additional OID (`.1.3.6.1.4.1.1602.4.3`) assigned to Canon printers, but I didn't include it since I don't have matching devices to test with.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by Rosiak** [comment]
Hi there,

Could you please add test data to this PR?(https://docs.librenms.org/#Developing/os/Test-Units/)
Thanks!

**Comment by githubuserx** [comment]
I am not exactly sure whats needed for testing, would the output of `./scripts/collect-snmp-data.php` be sufficient and where would I add it? The script creates a new file `canonprinter.snmprec`, but there are already more specific ones - e.g. `canonprinter-lbp.snmprec`. Since my PR only concerns the LBP series should I just append the output to this one? Thanks!

btw: I only have a LBP 6650 and a LBP 6670 and so far everything seems to work as expected.

**Comment by murrant** [comment]
yes, if you add the .snmprec file from ./scripts/collect-snmp-data.php I can generate the json.

If you've already generated this file you need to add it to this pull request still.

**Comment by githubuserx** [comment]
Sorry for the delay, I've added now the output of the snmprec script with IPs, MAC and serial number redacted. Please let me know if you need anything else.

**Comment by murrant** [comment]
Thanks @githubuserx nice work.

**Pull request merged**
