### PR TITLE
I agree to the conditions of the Contributor Agreement

### PR DESCRIPTION
**Pull request by filippog**

### CODE REVIEW

**Comment by laf** [comment]
Thanks @filippog :)

**Comment by filippog** [comment]
@laf no problem! see also my note re: CONTRIBUTING at https://github.com/librenms/librenms/pull/938#issuecomment-100453753

**Comment by laf** [comment]
I did indeed, going to look at adding one that points back to the docs we have on contributing :)

I noticed this patch went onto the wikimedia install, you guys not fancy updating the version you're running in general :)

**Comment by filippog** [comment]
@laf hehe you are right we're running an old version, upgrading is in the works but we haven't had a chance to do it yet

**Comment by laf** [comment]
@filippog 

When you guys do get chance, feel free to give us a heads up. Just in case you have any issues, we can at least try and make sure someones round on irc to help out.

**Comment by filippog** [comment]
@laf :+1: will do, thanks for your help!

**Pull request merged**
