### PR TITLE
Time limit image for ex. mail

### PR DESCRIPTION
**Pull request by SniperVegeta**
Im not having weatermap installed
but some1 gave me the refferer, and that was own domain as refferer.
so it should not break it.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SniperVegeta** [comment]
afbeelding
So timestamp is on 11:08:xx - its round down to 10:05 minus config = 10 mins
afbeelding
So after the time in config + timestamp = will be closed.

afbeelding

If u go try test the rules whit errors...
NO Valid requests.

**Comment by laf** [comment]
Sorry I'm struggling to understand what you're trying to fix or improve here.

**Comment by SniperVegeta** [comment]
Whenn u attach an image in ex. Mail,
It has a time limit to vieuw, it has an check that the active akkert is active. If its close u cant vieuw the image.

The image gets x min befor and x min after till its closed ( so cant see the image annymore)

So its not an fix, its an enhancement, so a better then " vieuw for all" and u cant easy try to switch port numbers, device id to vieuw other devices images.

**Comment by Jellyfrog** [comment]
Closing due to inactivity, feel free to reopen

**Pull request closed without merging**
