### PR TITLE
Remote monitoring using tinc VPN

### PR DESCRIPTION
**Pull request by florianbeer**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by florianbeer** [comment]
Thanks for your feedback @Gorian

**Comment by laf** [comment]
I've got some small changes which I tried to push to your branch, can you confirm that this option is enabled on the bottom right of this page for you:

image

It will allow me to make the changes directly.

**Comment by florianbeer** [comment]
Yes, I deliberately left that enabled so you could make changes. Strange that it doesn't work.

I've un-checkd and re-checked it. Maybe Roy's tip sometimes really does work (if you've seen the IT crowd you'll get it).

**Comment by laf** [comment]
Sorted, you can see my changes in the commit I pushed.

Basically I removed `#` from commands - we don't do this anywhere else so wanted to standardise it. I renamed the file and added it to the menu bar so people can get to it.

Please check you are happy and if so I'll publish on blog + merge.

**Comment by florianbeer** [comment]
I am happy 👍 

Thank you!

**Pull request merged**
