### PR TITLE
Add procedure management from alerting widget

### PR DESCRIPTION
**Pull request by gcoeugnet**
Hi,

We would like to add a procedure management which allow an user to click on an alert and then have a procedure displayed/downloaded regarding the alert. Here is a proposal (please discuss it before any merge :)) of what could be done.

I added a new column to the widget, which can be hidden/shown from widget settings. The column contains a button "Open" which open a new page refering the URL of a procedure stored in a new ~librenms_website/html/procs directory. The procedure name is given when creating an alert rule. If a name is given, this proc will be downloaded, if none is given, a default one is chosen which contains indication about how to add a custom one. If an error occured, a 404 is returned by the ajax call.

What do you think about that ? This is a try, maybe our needs will evolve, that's why I want to discuss it with you before any merge.

Regards,
Guillaume.

### CODE REVIEW

**Comment by laf** [comment]
Seems like potentially a good feature although I'm not sure about storing procedures as actual files as we have no file upload utility and it will also break git updates potentially without setting the directory to be ignored. Would it make more sense to store these within the DB so users can just create / edit them?

This would need an admin system to manage that though so gets a little more complicated - maybe links to existing company procedures instead?

**Comment by Rosiak** [comment]
I like the idea too, but as Neil I think it would be better to store it in the database as text/html/whatever format.

**Comment by gcoeugnet** [comment]
Hi,

If we decide to store the doc in the DB, how users will be able to edit/create them ? LibreNMS provides no editor either, unless integrating something like [jQuery TE](http://jqueryte.com/) ?

The idea here was to allow user to upload doc files from their browser while creating rules and using the format they want (PDF, TXT, ODT). I think an upload utility doesn't seem to be hard to code in PHP. Maybe links to another website is the best compromise ? Instead of a doc name, we can store an URL in the DB !?

**Comment by laf** [comment]
We would indeed need to add the ability to edit / create items.

I think a link would be the best option imho. Not sure what others think ( @librenms/reviewers ). I know in our company docs go out of date so linking back to one central place would be better than duplicating content.

**Comment by gcoeugnet** [comment]
Ok, then I'll modify the Pull request to take link in charge instead of doc files.
Everyone is ok ? I'll change this in few days.

**Comment by laf** [comment]
That sounds good.

**Comment by gcoeugnet** [comment]
Ok, the pull request is updated. I remove all docfile things and put URLs in place.
Let me know if this is ok for you.

**Comment by laf** [comment]
Ok few comments from me then I'd say we are good for a merge.

SQL file 116.sql is being used so you need to `git mv sql-schema/116.sql sql-schema/117.sql`

The button to open the procedure doesn't show in `/alerts/` only in the widget.

Their was probably a reason why but would it not be easier to just hyperlink to the url in the alerts table rather than invoking it via ajax?

**Comment by gcoeugnet** [comment]
Ok for the 117.sql move. I'll take that in charge asap
Sorry but I don't get the problem with the Open button :) ?! Can you explain a little bit ? At the moment the Open button appears in the alerting widget.
The reason I used ajax is to allow easier evolution of the procedure management, if one day someone wants to manage procedure differently. The second point was to keep the button management like the acknowledge one. This proposal is still open to suggestions !?

**Comment by laf** [comment]
The open button is in the widgets but not in the main alerts page '/alerts/' in your webui.

Understood on the reason why ajax was chosen, I just think it's overkill for basically opening a webpage.

**Comment by gcoeugnet** [comment]
Ok :) Understood too what you means by "/alerts" I don't using this page, so I don't work on it. I'll take that in charge too :)

**Comment by gcoeugnet** [comment]
I made both changes : 
- rename 116.sql to 117.sql
- add procedure button in the /alerts page

Regards.

**Pull request merged**
