### PR TITLE
Discovery rcChasPowerSupplyOperStatus for Extreme/Avaya voss.inc.php stop working

### PR DESCRIPTION
**Pull request by ospfbgp**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ospfbgp** [comment]
Seems that the mibs were not discovered for rcChasFanOperStatus and rcChasPowerSupplyOperStatus when using the oid.  Changed syntax to use actual RAPID-CITY mib name.  Seems to have fixed the issue.

**Comment by PipoCanaja** [comment]
Hi @ospfbgp 
Any chance you could add test-data so that we can catch it next time such an issue comes appears ? I would suggest you create a new variant for your device. 

https://docs.librenms.org/Developing/os/Test-Units/

Thanx
PipoCanaja

**Comment by ospfbgp** [comment]
I have several vsp for testing and could submit that for several models.  I need to add new models anyways.  I have done the testing and all looks good in database now.

|       863 |        85 | .1.3.6.1.4.1.2272.1.4.8.1.1.2.1       | rcChasPowerSupplyOperStatus.1     | rcChasPowerSupplyOperStatus | Power Supply 1             |
|       864 |        84 | .1.3.6.1.4.1.2272.1.4.8.1.1.2.1       | rcChasPowerSupplyOperStatus.1     | rcChasPowerSupplyOperStatus | Power Supply 1             |
|       865 |        83 | .1.3.6.1.4.1.2272.1.4.8.1.1.2.1       | rcChasPowerSupplyOperStatus.1     | rcChasPowerSupplyOperStatus | Power Supply 1             |
|       866 |        83 | .1.3.6.1.4.1.2272.1.4.8.1.1.2.2       | rcChasPowerSupplyOperStatus.2     | rcChasPowerSupplyOperStatus | Power Supply 2             |

screen shot 2019-02-25 at 5 56 33 pm
screen shot 2019-02-25 at 5 55 51 pm

**Comment by PipoCanaja** [comment]
If you have multiple devices, you can Skip some that are too similar. The idea is to have test data that covers most of the situations. Then the regression tests will do a good job as tracking ... régressions ... on all devices ;)

**Comment by ospfbgp** [comment]
I have added the .snmprec and .json files for vsp8608 and vsp9012.  I have tested and they work fine just need to add support.  All vsp platforms are very similar so mibs will be very much alike.

**Comment by ospfbgp** [comment]
Let me know if there is anything else I need to do here.  I think I have everything in order.  I have added 2 new devices and mibs.

**Comment by PipoCanaja** [comment]
We need to have Travis CI happy, until then we cannot merge. 
Issue is with tests/data/voss_8608.json for the moment. 
For some reason Travis does not find the same things as the file you attached to the PR. 
Do you have a clean environnement for tests, matching exactly the PR ?

**Comment by ospfbgp** [comment]
Seems Travis is happy now.  The error I was getting "Discovered ports data does not match that found tests/data/voss_xxx.json".  I had to edit voss_xxxx.snmprec and remove the VLANs, since they are not ports.  I had this issue before.  All should be happy now. :-)

**Comment by PipoCanaja** [comment]
This is weird. More data in snmprec should not have any bad impact. If you run ./scripts/pre-cache -o xxxxxx -v yyyyyy, do you see the same behavior than Travis CI ? 
Aside of this issue, this looks good.

**Pull request merged**
