### PR TITLE
Quickfix for division by zero

### PR DESCRIPTION
**Pull request by Jellyfrog**
In PHP8 this throws an exception

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Not sure if the code is suppose to allow 0, way to messy to follow

**Comment by murrant** [comment]
I think this is the wrong fix.  Will result in some odd values being shown when 0 is expected probably.

Likely check if the value is 0 and then set whatever it is calculating to 0.

**Comment by Jellyfrog** [comment]
Way to many places it's used. Maybe just disallow setting value to 0 for now?

**Comment by murrant** [comment]
Maybe, yeah.  Like you said billing code is a mess and very stale.

**Comment by murrant** [comment]
Feel free to send the ui changes.

**Pull request closed without merging**
