### PR TITLE
Position the buttons in the center on user preferences page

### PR DESCRIPTION
**Pull request by SantiagoSilvaZ**
* Button Change Password 
Before:
image
After:
image

* Button Generate TwoFactor Secret Key
Before:
image
After:
image

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by Jellyfrog — CHANGES_REQUESTED** [review]
`align` is obsolete, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#attributes

**Comment by SantiagoSilvaZ** [comment]
@Jellyfrog, thanks for the information

**Review by SantiagoSilvaZ — COMMENTED** [review]
@Jellyfrog, you can check?

**Comment by SantiagoSilvaZ** [comment]
@laf or @Jellyfrog do you agree now?

**Comment by SantiagoSilvaZ** [comment]
@Jellyfrog or @laf, this PR of mine makes sense, can you check it again please?

**Comment by murrant** [comment]
Ideally, the buttons would line up with the form fields right?

**Comment by SantiagoSilvaZ** [comment]
You're right, it looks so much better, I'll make the change
Thank you!

**Comment by laf** [comment]
@SantiagoSilvaZ Have you tried my suggestion?

**Comment by SantiagoSilvaZ** [comment]
@laf Which would be?

**Comment by laf** [comment]
It's further up in the comments but:

image

**Comment by murrant** [comment]
To align with forms, it would be col-sm-offset-4 instead though :)

**Comment by laf** [comment]
> To align with forms, it would be col-sm-offset-4 instead though :)

I was mimicking the ops screenshot :)

**Comment by SantiagoSilvaZ** [comment]
Result: 
image

**Review by murrant — APPROVED** [review]

**Pull request merged**
