### PR TITLE
device - Add Cisco REP Segment state sensor

### PR DESCRIPTION
**Pull request by rudybroersma**
I have created a small patch to add state sensors for Cisco REP (Resilient Ethernet Protocol) segments. This allows LibreNMS to create alerts for incomplete/broken REP rings. 

This was tested against Cisco IE2000 Industrial Ethernet switches running Cisco IOS 15.2(7)E2 (UNIVERSALK9) 

- I have read the code guidelines. A few of the lines are wider than 120 chars, but they were already wider before my additions.
- My request does not make any changes to the WebUI
- snmprec test file added.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data]([
[ios_cisco.snmprec.txt](https://github.com/librenms/librenms/files/13739083/ios_cisco.snmprec.txt)
](https://docs.librenms.org/Developing/os/Test-Units/)).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by rudybroersma** [comment]
[ios_cisco.snmprec.txt](https://github.com/librenms/librenms/files/13739176/ios_cisco.snmprec.txt)

**Comment by PipoCanaja** [comment]
Hi
- Please add the snmprec file to the PR, in the correct directory
- Please generate the JSON file as well. 
Thanx

**Comment by PipoCanaja** [comment]
You could rename the file `ios_ie2000.snmprec` so that it is clear which device it is. And the matching JSON would be `ios_ie2000.json`.

**Comment by rudybroersma** [comment]
The REP information is not limited to IE2000 only. Should I rename the file to ie2000 regardless?

**Comment by PipoCanaja** [comment]
> The REP information is not limited to IE2000 only. Should I rename the file to ie2000 regardless?

Yep. Cause this test file is taken from this device. Later on, somebody may capture test data from a good old Cisco ME3400 that did (if I remember well) also implement it. 
This data is used for regression tests, and it makes sense to have as much as possible so if one day somebody touches the REP code in LibreNMS, it will be tested against all this data and hopefully regressions will be spotted (and avoided).

**Comment by PipoCanaja** [comment]
Waiting for the checks to go green and this PR will be good to go.

**Review by PipoCanaja — APPROVED** [review]

**Comment by PipoCanaja** [comment]
LGTM

**Pull request merged**
