### PR TITLE
Support for InfluxDB V2 API

### PR DESCRIPTION
**Pull request by Walkablenormal**
Please give a short description what your pull request is for

PR to support InfluxDB v2 API in addition to the currently supported InfluxDB v1 API. 
Support for InfluxDBv2 is built as a separate datastore to not break any setups still running InfluxDBv1.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

(Imgur: https://imgur.com/a/4HiqPXf)

- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Can this not replace the current implementation? Or are they not compatible?

**Comment by rvankomen** [comment]
Version ready for review;

**Comment by Walkablenormal** [comment]
Version ready for review;

**Comment by Jellyfrog** [comment]
Nice work, we want to remove the abandoned v1 package sooner or later, this client is compatible with influxdb 1.8+ anyway

**Comment by Jellyfrog** [comment]
@murrant think this falls on your eyes

**Comment by murrant** [comment]
LGTM overall, nice work.

Only improvement I could think of is a little code sharing between both v1 and v2 to format the data.  This seems to be very similar to the v1 code in that spot.

**Comment by Walkablenormal** [comment]
> LGTM overall, nice work.
> 
> Only improvement I could think of is a little code sharing between both v1 and v2 to format the data. This seems to be very similar to the v1 code in that spot.



> LGTM overall, nice work.
> 
> Only improvement I could think of is a little code sharing between both v1 and v2 to format the data. This seems to be very similar to the v1 code in that spot.

Thanks! I was planning on submitting a PR for the removal of influxDB v1 support in favor of v2, so code sharing won't be needed. As @Jellyfrog stated, the InfluxDB v1 datastore currently uses a abandoned library.

**Review by murrant — DISMISSED** [review]

**Review by murrant — APPROVED** [review]

**Pull request merged**
