### PR TITLE
Fix python config fetch disrupted by stderr output

### PR DESCRIPTION
**Pull request by murrant**
I have no idea how to make command_runner not include debug output, so just use subprocess.check_output

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ottorei** [comment]
@deajan Any ideas on this one?
@murrant Could it work with a different capture mode as documented in https://pypi.org/project/command-runner/

**Comment by deajan** [comment]
@ottorei @murrant Let me check this Real quick this evening, I'm pretty sure there's an easy fix for this that doesn't need a revert to subprocess.
Just a quick question, how can I reproduce the problem ? Some trivial change in config_to_json.php perhaps ?

**Comment by murrant** [comment]
Enable the snmp module in php and set `mibs : BOGUS-MIB` in /etc/snmp/snmp.conf  (at least that is how most people trigger it)

**Comment by murrant** [comment]
@deajan merging this in the meantime.

**Comment by deajan** [comment]
No problem. Will give me more time to investigate. Sorry for the noise again, that PR was a major headache ;)

**Pull request merged**
