### PR TITLE
Convert SSO to handle roles

### PR DESCRIPTION
**Pull request by murrant**
Expose settings in webui
Handle legacy level settings still

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@TheMysteriousX

**Comment by TheMysteriousX** [comment]
This looks ok at first glance - I'll give it a test when I can.

**Comment by murrant** [comment]
@TheMysteriousX I think it should be working, but is missing all the strings for the webui settings. (in en/settings.php)

**Comment by TheMysteriousX** [comment]
Ok, I can provide those - pretty busy the next couple of days but I should be able to get this done over the weekend.

**Comment by TheMysteriousX** [comment]
Can't convince github to open an MR against this, so hopefully a comment is fine.

I'm not precious about the wording, so feel free to wordsmith. I've flagged a couple of fields as deprecated, as they're effectively obsoleted by RBAC.

```
        'sso' => [
            'create_users' => 'Enable to automatically create user accounts on first login',
            'descr_attr' => 'Header or environment variable containing the contents of the user\'s description',
            'email_attr' => 'Header or environment variable containing the contents of the user\'s email address',
            'group_attr' => 'Header or environment variable containing the contents of the user\'s group memebership (deprecated)',
            'group_delimiter' => 'Character seperating groups if group is multi-valued',
            'group_filter' => 'Expression to apply to restrict groups accepted from SSO by LibreNMS',
            'group_role_map' => 'Mapping of groups received from SSO to LibreNMS numeric roles (deprecated)',
            'group_strategy' => 'Method used for selecting a role (see documentation)',
            'mode' => 'Enables either environment variables (supported by mod_php) or headers (supported by everything else) for transferring attributes',
            'realname_attr' => 'Header or environment variable containing the contents of the user\'s given and family names',
            'role_attr' => 'Header or environment variable containing the contents of the user\'s role',
            'static_role' => 'Role to be assigned to all users, ignoring SSO fields',
            'trusted_proxies' => 'Source IP addresses that can provide SSO headers, for use with reverse proxies',
        ],
```

**Pull request closed without merging**
