### PR TITLE
Drop tests for unsupported php versions

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Absolutely fine with this and you can just merge, but should we add `SKIP_UNIT_CHECK` as well along with `SKIP_STYLE_CHECK`.

**Comment by murrant** [comment]
I don't think we should skip unit tests, might as well disable that PHP version all together if we skip unit tests.

That is why I disable PHP 7.0 when I sent that earlier PR.  I didn't think the middle versions were required.

**Comment by laf** [comment]
> I don't think we should skip unit tests, might as well disable that PHP version all together if we skip unit tests.
> 
> That is why I disable PHP 7.0 when I sent that earlier PR. I didn't think the middle versions were required.

Surely between versions only the lint check is needed as we want to test the code works on those versions. phpunit should be the same no matter what the version then.

**Comment by murrant** [comment]
lint checks the code for syntax not functionality.  We honestly only need to run lint on the oldest version because we are stuck with that syntax and cannot use newer language features.

At one point had some code that was fine syntax wise, but failed to run on certain versions of php 5.3.  phpunit would catch this, lint would not.

**Pull request merged**
