### PR TITLE
Install python requirements during daily

### PR DESCRIPTION
**Pull request by murrant**
install python requirements for the default python version.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
nice, i like this.
But documentations should be enhanced so `python-pip` package is installed

**Comment by murrant** [comment]
The main problem right now is our minimum version for redis requires python 3.  If we port the scripts to python 3, we might need the libraries for python 2 also.

**Comment by SourceDoctor** [comment]
mmh... so we need 2 and 3 parallel to keep everything running?

On rewriting stuff to python3 i would ensure python code is PEP8 conform (maybe a test for it), and then rewrite Python Code to be compatible for Python 2 and 3.
After a while (with information/warning), we could switch to Python3 only and use it's full capabilities.
Hoping open PR, which is on it will be ready in near future ;-)

**Comment by murrant** [comment]
true, we could just make sure to install deps for python3

**Comment by murrant** [comment]
Honestly, I think we need to drop python2 support at the same time as php 7.1 @Jellyfrog

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
