### PR TITLE
Removed reference to forking

### PR DESCRIPTION
**Pull request by laf**
Not really necessary now. LibreNMS is standing on it's own two feet with a good identity :)

### CODE REVIEW

**Comment by f0o** [comment]
@paulgear I would merge this unless there is some legal issue with not-mentioning that we're a fork.

**Comment by laf** [comment]
Shouldn't be any issues I hope as we still maintain the license attribution. @Paulgear?

**Comment by paulgear** [comment]
Is it mentioned anywhere else on the web site?  If not, I would leave it in.

**Comment by laf** [comment]
It's still mentioned in the acknowledgements:

"Observium Codebase for fork."

And then attributes copyright to Adam.

You only have to maintain copyright which we already do. I can close this though, it's no biggie just wanted to avoid mentioning O......:)

**Pull request merged**
