### PR TITLE
Pop returned value from snmpwalk_group for lldp on mikrotik routeros

### PR DESCRIPTION
**Pull request by thegreatecheese**
This seems to be an issue on only one vendor, but since they are already an exception I thought making the fix more complex might be too much.

On mikrotik devices the snmpwalk_group function returns 
`array (
  0 =>
  array (
    0 =>
    array (
      182 =>
      array (
      ....
`
instead of:
`array (
  182 =>
  array (
  ...
`
So the fix is pealing out the array.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @thegreatecheese 
What device (and what version) did you check this patch against ? Cause LLDP works all right on my mikrotik routers. And this fix actually breaks it.

**Comment by Jellyfrog** [comment]
This will throw errors when it's not an an multiarray

**Comment by thegreatecheese** [comment]
> What device (and what version) did you check this patch against ? Cause LLDP works all right on my mikrotik routers. And this fix actually breaks it.

I have checked it on:
Hex running 6.48.1, 6.48.2 and 6.49beta
CRS326-24G-2S+ running 6.48 and 6.49beta
RB3011 running 6.48.2
RB960PGS running 6.48.2

I dont have routers running older versions of routeros at hand. Probably its a new feature in routeros causing it.

If I do a ` ./discovery.php -d -vvvvv -h 41 -m discovery-protocols` on one of the hex-es (currently running 6.48.1 and is a neighbor to a CRS running 6.49beta) the array before the patch looks like:
`lldp_array:
array (
  0 =>
  array (
    0 =>
    array (
      316 =>
      array (
        'lldpRemChassisIdSubtype' => '4',
        'lldpRemChassisId' => '64:D1:54::ZZ:YY:XX',
        'lldpRemPortIdSubtype' => '5',
        'lldpRemPortId' => 'bridge/ommited/ether23',
        'lldpRemSysName' => 'anotherommited',
        'lldpRemSysDesc' => 'MikroTik RouterOS 6.49beta22 (testing) CRS326-24G-2S+',
        'lldpRemSysCapSupported' => '28',
        'lldpRemSysCapEnabled' => '28',
      ),
    ),
  ),
)
`
And after the patch:
`array (
  316 =>
  array (
    'lldpRemChassisIdSubtype' => '4',
    'lldpRemChassisId' => '64:D1:54:ZZ:YY:XX',
    'lldpRemPortIdSubtype' => '5',
    'lldpRemPortId' => 'bridge/ommited/ether23',
    'lldpRemSysName' => 'anotherommited',
    'lldpRemSysDesc' => 'MikroTik RouterOS 6.49beta22 (testing) CRS326-24G-2S+',
    'lldpRemSysCapSupported' => '28',
    'lldpRemSysCapEnabled' => '28',
  ),
)
`
And since the following for loop only reaches the first depth and uses its key to get the interface's number from the `$lldp_ports_num` array this will return no actual value.
`lldp_ports_num:
array (
  316 =>
  array (
    'mtxrNeighborInterfaceID' => '5',
  ),
)
`

**Comment by thegreatecheese** [comment]
Sorry for the mess and thank you for your patience!
I've done the modification that the styleci requested.

**Review by murrant — APPROVED** [review]
It would be good to report a bug to MikroTik.

**Comment by PipoCanaja** [comment]
Tested OK on CHR, router OS 6.42.1 L2

**Comment by mctaguma** [comment]
Unsure if my issue matches the change proposed in this PR, but I think it might.
I'm seeing a mismatch between VLAN ID and port, when running disco on a MikroTik CRS326-24S+2Q+ running MikroTik RouterOS 6.47.9.
I think this is due to a mismatch between IfIndex and dot1dBasePortIfIndex.

If this is irrelevant to this PR, my apologies. Please tell me, and I'll open a new issue.

Example:

| Port          | Actual VLAN assignment | VLAN assignment according to LibreNMS after disco |
| ---------- | ------------------------- | ------------------------------------------------------ |
| sfpplus11 | 2651                               | 2652                                                                          |
| sfpplus12 | 2652                               | 2653                                                                          |
| sfpplus13 | 2653                               | 2654                                                                          |
| sfpplus14 | 2654                               | 2655                                                                          |
| sfpplus15 | 2655                               | 2656                                                                          |

Disco output:
```

#### Load disco module vlans ####

SQL[SELECT * FROM `vlans` WHERE `device_id` = ? [195] 0.38ms] 
  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'BRIDGE-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/mikrotik' '-r' '3' 'udp:HOSTNAME:161' 'dot1dBasePortIfIndex']

dot1dBasePortIfIndex.1 = 2
dot1dBasePortIfIndex.6 = 7
dot1dBasePortIfIndex.7 = 8
dot1dBasePortIfIndex.8 = 9
dot1dBasePortIfIndex.9 = 10
dot1dBasePortIfIndex.10 = 11
dot1dBasePortIfIndex.11 = 12
dot1dBasePortIfIndex.12 = 13
dot1dBasePortIfIndex.13 = 14
dot1dBasePortIfIndex.14 = 15
dot1dBasePortIfIndex.16 = 17
dot1dBasePortIfIndex.17 = 18
dot1dBasePortIfIndex.18 = 19
dot1dBasePortIfIndex.19 = 20
dot1dBasePortIfIndex.20 = 21
dot1dBasePortIfIndex.21 = 22
dot1dBasePortIfIndex.22 = 23
dot1dBasePortIfIndex.23 = 24
dot1dBasePortIfIndex.24 = 25
dot1dBasePortIfIndex.25 = 26
```

**Pull request merged**
