### PR TITLE
Issue 1540 - Add support for Cisco Voice Gateways

### LINKED ISSUE #1540: Add support for Cisco Voice Gateways
I would like to add support for Cisco Routers performing Voice Gateway functions:
- Primary Rate ISDN Utilisation
- Transcoder Utilisation
- Media Termination Point (MTP) Utilisation
- Digital Signal Processor (DSP) Utilisation

I will be working on this PR myself.

### PR DESCRIPTION
**Pull request by adaniels21487**
Hi Team,
This PR is working fine for me, can someone with a Cisco voice gateway give it a shot and let me know if it needs any more work?

Fixes #1540

### CODE REVIEW

**Comment by Rosiak** [comment]
Please check the formatiing of the files. 
http://docs.librenms.org/Developing/Code-Guidelines/

**Comment by laf** [comment]
Hi @adaniels21487 

It just needs the formatting updating in line with our standards if you can do that please.

I know you've signed the agreement already but as the formatting of this isn't how ours is at the moment, can you please confirm that you haven't developed this against an Observium installation or using any code from an Observium installation?

**Comment by adaniels21487** [comment]
@laf Confirmed. The poller module was based on cisco-vpdn.inc.php and the device graph pages were based off wifi-clients.inc.php

Re: Formatting. Yes, I reverted to some bad habits in the device pages, can you please advise if they are ok now?

**Comment by laf** [comment]
All the formatting looks good :)

My last and final question I think - why have them all as separate poller modules. Is it not better to have just one cisco-voice (or something similar) poller module that then calls each of those files from a sub directory?

**Comment by adaniels21487** [comment]
We could easily move the poller modules to a cisco-voice directory and have a cisco-voice.inc.php that contains 4 include statements, is this what you are referring to?

But each module still needs to determine if it needs to run on its own as they each perform a separate function and a voice gateway may only implement some of the functions.
For example, I have voice gateways that perform a PSTN role connecting to the telco. These devices respond to cisco-dsp and cisco-pri. Others perform a transcoding role and only respond to cisco-xcode and cisco-dsp, etc.

Happy to take your direction...

**Comment by laf** [comment]
Hi @adaniels21487 Yeah that's what I meant.

It's fine each file doing it's own check it should run but it makes sense to bundle them into one poller module.

**Comment by laf** [comment]
:+1: from me.

**Pull request merged**
