### PR TITLE
Fortinet per-core cpu

### PR DESCRIPTION
**Pull request by murrant**
I have no test data...  probably need someone to contribute test data for this to get merged
fixes: #11570

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by paulierco** [comment]
I can help you with this. Can you walk me how to do it ?

**Comment by murrant** [comment]
@paulierco `git apply 12660` `./scripts/collect-snmp-data.php -h 123 -v somedescr`  Add the snmprec here.

**Comment by paulierco** [comment]
[Here ](https://github.com/paulierco/1/blob/main/fortigate_60f.snmprec)is it. I was not able to commit to this PR.

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Pull request merged**
