### PR TITLE
Removed double Stack Temperature Discovery and Fixed typos in dbm discovery for Dell Switches

### PR DESCRIPTION
**Pull request by evheros**
Fixed typos in dbm discovery for Dell Switches

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by evheros** [comment]
> Please add test data so we can ensure your change is not broken in the future.
> 
> Read the docs to find out how: https://docs.librenms.org/Developing/os/Test-Units

Attached the snmprec

[dnos.zip](https://github.com/librenms/librenms/files/3657630/dnos.zip)

**Comment by murrant** [comment]
Thanks for the test data.
1. I suggest you remove the PHP or maybe it needs to be surrounded in if ($device['os'] !== 'dnos')
2. I noticed sensors are grouped by lanes, but that doesn't make sense to me.  Shouldn't be grouped by port and labeled by lane.
3. Should temperature sensors that = 0.000 be skipped?

I know those were pre-existing, but might as well fix them too :)

**Comment by evheros** [comment]
> Thanks for the test data.
> 
> 1. I suggest you remove the PHP temperature instead of yaml or maybe it needs to be surrounded in if ($device['os'] !== 'dnos')
> 2. I noticed sensors are grouped by lanes, but that doesn't make sense to me.  Shouldn't be grouped by port and labeled by lane.
> 3. Should temperature sensors that = 0.000 be skipped?
> 
> I know those were pre-existing, but might as well fix them too :)

1. Done
2. Indeed this is pre-existing. As there is no Lane in de name/description of the sensor you can't see which lane it is in the interface if you group them by interface. Maybe a good idea to open a Issue for this but I don't include it in this PR.
3. Done

**Comment by murrant** [comment]
Ok, looks good.  Just need to update test data.  Can you run ./scripts/save-test-data.php -o dnos
Then need to go through the test data changes make sure they are what we expect.

**Comment by evheros** [comment]
> Ok, looks good. Just need to update test data. Can you run ./scripts/save-test-data.php -o dnos
> Then need to go through the test data changes make sure they are what we expect.

Can't get it running for unknown reason. it starts snmpsim but I keep getting: "dnos: Could not connect to 127.1.6.1, please check the snmp details and snmp reachability"

**Comment by PipoCanaja** [comment]
@evheros 
Any iptables/firewall running locally on the machine ?

**Comment by murrant** [comment]
You don't need snmpsim to collect the data, just `./scripts/collect-snmp-data.php`

**Comment by evheros** [comment]
> You don't need snmpsim to collect the data, just `./scripts/collect-snmp-data.php`

collect-snmp-data is already uploaded. Please see above

**Comment by evheros** [comment]
> @evheros
> Any iptables/firewall running locally on the machine ?

No firewall enabled on the system

**Comment by murrant** [comment]
Sorry, didn't see it because I expected it in the PR...

**Comment by murrant** [comment]
I added both test files, but you need to review the json file.  I noticed mempools is 0 for example...

**Comment by evheros** [comment]
> I added both test files, but you need to review the json file. I noticed mempools is 0 for example...

Good catch. This never worked for our switches. Pushed a fix for this issue also.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-57-release-changelog-october-2019/9969/1

**Pull request merged**
