### PR TITLE
docs: debian install snmp-mibs

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

by default debian distro won't include any mibs for snmp

### CODE REVIEW

**Comment by murrant** [comment]
Is this actually needed?

**Comment by crcro** [comment]
as per irc chat ... seems so

**Comment by murrant** [comment]
I think it is just a matter of the SNMP options being set incorrectly...

**Comment by murrant** [comment]
I believe this is the correct fix:
https://github.com/librenms/librenms/pull/4600/commits/12cdec80240800a534e64c5f0df227613a823376

**Comment by crcro** [comment]
then maybe we should check every polling script that uses mibs and drop this from docs?

**Comment by murrant** [comment]
crcro: in progress now.

**Comment by crcro** [comment]
closing ... as murrant proposed a cleaner, user independent way ... hats down @murrant

**Pull request closed without merging**
