### PR TITLE
Install docs addition

### PR DESCRIPTION
**Pull request by p4k8**
Added nginx route config for API to make it work right after install.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — CHANGES_REQUESTED** [review]
Why are you adding this?  It is absolutely not needed. `api_v0.php` is not needed and only exists to allow old installs to continue to function.  It is an alias of index.php.

**Comment by p4k8** [comment]
Without this change, API calls on a fresh install get redirected to login page. Problem isn't mine alone, as I also seen mentions of this in Discord.
So some kind of change is still needed, I will research it later and edit PR accordingly.

**Comment by murrant** [comment]
what webserver and webserver layout are you using?

**Comment by murrant** [comment]
I did notice when you fail auth it redirects to login page, it didn't used to do that...

**Pull request closed without merging**
