### PR TITLE
Graphical alerts update (text/icon alignment)

### PR DESCRIPTION
**Pull request by PipoCanaja**
The goal is to have the UserName and the alert number correctly aligned.

Before: 
Capture d’écran 2019-11-20 à 11 18 57

After: 
Capture d’écran 2019-11-20 à 11 19 29

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Think ill prefer the old look

**Comment by Cormoran96** [comment]
I don't like the old style. It gives the impression of a bug

**Comment by SourceDoctor** [comment]
what about making position choosable? up(old look)/middle/down?
in ideal case per user ;-)

**Comment by murrant** [comment]
@SourceDoctor we try to avoid option creep :)

**Comment by murrant** [comment]
How about this?

image

**Comment by Cormoran96** [comment]
And if there is 0 notification the 0 is hidden. And when we are more the number is exponent of icon. 
something like that:
Screenshot 2019-11-22 at 08 45 01

**Comment by PipoCanaja** [comment]
I was thinking of moving the exponent style number back to the icon, and it really makes sense. I'll update the PR in that direction.

**Comment by PipoCanaja** [comment]
As murrant suggested : 
Capture d’écran 2019-11-22 à 19 40 24

**Comment by SourceDoctor** [comment]
@PipoCanaja 
nice :-)
but i personally like the idea from Cormoran96 only to see the Counter if messages are existing.
Maybe change it to this?
What do you think about it @murrant ?

**Comment by PipoCanaja** [comment]
With notifications : 
Capture d’écran 2019-11-23 à 15 06 03

Without unread notifications: 
Capture d’écran 2019-11-23 à 15 06 25

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
