### PR TITLE
Enhance Cumulus Support

### PR DESCRIPTION
**Pull request by theherodied**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by theherodied** [comment]
Not ready to merge yet. I will add test data when I'm done adding more features.

**Comment by murrant** [comment]
You are changing the index here, that might not work on other devices.  Perhaps you want to use `snmp_getnext_multi()`?

**Comment by theherodied** [comment]
@murrant, does that look better?

**Comment by murrant** [comment]
I think so

**Comment by Rosiak** [comment]
@librenms/reviewers 
Should we really include all these mibs, when none of them are used?

**Comment by theherodied** [comment]
I was wondering that myself. I was going to bring it up before any merge.

I think the cumulus-* mibs should be included. Not sure about the rest.

**Comment by murrant** [comment]
Yeah, you can leave out the mibs for now, add them when you are using them ;)  We already ship 160MB of mibs :)

**Comment by theherodied** [comment]
@librenms/reviewers, I think this is good and the blocker can be removed if the Travis check passes. Let me know if it needs anything else.

**Comment by theherodied** [comment]
@laf think we can remove the blocker. I'm done with this for now.

**Pull request merged**
