### PR TITLE
Added the lookup of IP if device hostname is a hostname

### LINKED ISSUE #1698: Add polled IP address to the overview
It would be handy to have the ip address that was polled added to the lists and overview pages. The IP address of the interface is displayed when you drill down, but knowing what address was polled would be great.

### PR DESCRIPTION
**Pull request by laf**
Fix #1698  

This now does a dns lookup on hostnames only for an IP. It stores it as a varbinary(16) which is the correct way to store ipv4/ipv6 by all accounts. At present no mysql functions are used as they only exist in 5.6 and above so this is all done in php.

### CODE REVIEW

**Comment by f0o** [comment]
Dislike the modification to the devices-table's schema, it has always caused some problems. Isn't there a way around with using the devices_attribs? If not, never mind my comment

**Comment by laf** [comment]
The biggest issue with devices_attribs is the column type, as we already know for the IP address tables having them as just varchars means we lose a lot of functionality in converting and searching so we really should be using the correct column type to store this information.

**Comment by f0o** [comment]
Ok, I can live with devices then. Thanks for clarifying :)

**Comment by laf** [comment]
Rebased.

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
heh needs another rebase. CI worked out well though! :)

**Comment by laf** [comment]
Rebased again :)

**Pull request merged**
