### PR TITLE
newdevice: Added support for CTC Union devices

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #5221

### CODE REVIEW

**Comment by murrant** [comment]
Would prefer a svg icon, but not a deal breaker.

**Comment by laf** [comment]
I'll sort that, couldn't find a native one so will convert.

**Comment by laf** [comment]
svg logo in place.

**Comment by murrant** [comment]
That is not an svg logo :( it is a png embedded in an svg.

**Comment by laf** [comment]
Sod it, I'm reverting to png.

**Comment by murrant** [comment]
@laf we'll just leave svg up to others unless an svg is readily available.
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 493.17392 177.05811"><path d="M351.175 122.115c-14.175-3.81-20.6-13.794-20.6-24.403 0-6.332 14.877-74.353 17.523-79.495 2.954-5.738 11.612-11.586 22.486-14.97C378.85.673 383.676 1.114 431.47 1.06c29.438-.033 55.7.344 57.753.376 4.668.264 5.837-1.9-.005 19.9-3.76 14.023-3.49 18.123-9.523 17.184-2.188-.34-3.112-1.028-2.213-6.074l.925-5.507H445.21c-18.258 0-35.66.528-38.672 1.17-3.012.643-7.707 3.075-10.434 5.405-4.425 3.78-5.537 6.563-10.33 25.85-6.33 25.48-6.698 31.555-2.166 35.66 2.978 2.698 6.42 2.98 41.503 3.402l37.5-.862 1.332-6.464c1.05-6.19 3.427-6.314 7.537-5.403 4.225.937 2.177 9.004 1.355 15.463-2.215 17.407-1.722 16.53-5.776 21.392-2.887 3.46-40.67 1.834-72.86 1.83-19.487 0-38.734-1.114-43.025-2.267zM234.49 27.105l-47.29-.154L194.796.478 337.733.325l-7.085 26.805-47.406.203-22.053 96.11H211.28zM56.886 173.32c-9.113-1.21-21.75-5.443-29.638-9.93-9.683-5.508-21.542-15.734-25.424-25.746-4.684-12.08-.202-19.58 11.798-68.357C23.915 27.45 25.66 23.7 29.97 18.99c7.09-7.743 12.825-9.914 23.427-13.615 11.298-3.945 14.36-4.37 67.82-4.914 19.518-.197 33.917-.34 43.538-.45 11.736-.133 14.443.916 14.88 4.374-.183 5.554-8.163 30.315-9.66 32.208-.838 1.06-2.86 1.93-4.49 1.93-2.48 0-2.892-.952-2.514-5.79l.983-5.79h-34.498c-29.94 0-34.58.333-39.122 2.81-6.92 3.776-11.14 13.622-16.993 39.65-13.5 60.022-13.552 60.566-6.43 67.69 6.387 6.385 15.217 7.033 45.265 7.033l24.827-.067.947-4.402c1.3-6.048 2.06-7.703 6.05-7.703 2.51 0 4.665 1.137 4.827 2.894.262 2.86-6.47 29.082-8.09 32.638-.92 2.02-3.763 4.4-6.32 5.29-4.383 1.528-66.812 1.966-77.53.545z" fill="#3fb2e8"/><path d="M234.027 143.038l-6.497 32.422-14.707.268.493-2.936s-7.483 2.502-12.387 3.246c-9.822 1.49-16.407 1.517-20.823-3.533-2.79-3.19-2.534-8.656-1.407-14.198 1.126-5.542 2.575-15.27 2.575-15.27h15.633l-2.24 10.884c-2.66 12.928-.652 15.996 7.293 15.893 7.937-.102 12.09-4.25 14.846-16.355l2.373-10.422zm82.408-4.81l1.436-6.825 15.07.257-1.574 6.8zm88.88 37.415l6.497-32.423 14.707-.267-.494 2.935s7.483-2.502 12.387-3.246c9.82-1.49 16.406-1.517 20.822 3.534 2.79 3.19 2.534 8.655 1.407 14.197-1.126 5.542-2.575 15.272-2.575 15.272h-15.633l2.24-10.886c2.66-12.928.653-15.995-7.293-15.893-7.935.103-12.087 4.25-14.844 16.356l-2.373 10.422zm-96.07-.6l6.176-31.22 14.666.137-5.824 31.685zm-67.598.6l6.498-32.423 14.706-.267-.49 2.935s7.48-2.502 12.386-3.246c9.82-1.49 16.405-1.517 20.822 3.534 2.79 3.19 2.534 8.655 1.407 14.197-1.127 5.542-2.575 15.272-2.575 15.272h-15.634l2.24-10.886c2.66-12.928.653-15.995-7.292-15.893-7.936.103-12.088 4.25-14.845 16.356l-2.375 10.422zm140.346-17.335c.047-5.088-2.526-8.363-12.308-8.345-10.357.02-15.158 5.936-15.475 12.23-.27 5.35 5.51 8.222 14.132 7.607 8.576-.612 13.6-6.076 13.65-11.492zm-22.648 18.487c-7.235-.534-20.705-2.156-20.764-14.425-.05-10.462 13.617-19.504 27.626-20.493 11.955-.844 30.377.865 31.497 14.706-.196 19.696-23.366 21.32-38.358 20.212z" fill="#e6180e"/></svg>
```

**Comment by laf** [comment]
Updated again thanks.

**Pull request merged**
