### PR TITLE
Runtime for APC ups 

### PR DESCRIPTION
**Pull request by boudreau**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Where are the images from?

**Comment by boudreau** [comment]
Reused the Power.png already in the icons directories. Just copied and renamed then.

**Comment by laf** [comment]
Sorry I didn't realise you hadn't actually signed the contributors agreement contrary to you saying you had. Please submit a pull request with this asap otherwise we will have to revert this PR.

**Comment by boudreau** [comment]
Hi,

Where can I find this agreement?

Thanks

**Comment by laf** [comment]
It's linked to in the first tick box you selected:

http://docs.librenms.org/General/Contributing/

**Comment by boudreau** [comment]
Hi,

Sorry about the misunderstanding, I think it’s done.

Yves

**Comment by laf** [comment]
I don't see any new pull requests, you will need to submit a new one with the change.

**Comment by boudreau** [comment]
Hi, do I do the pull from my fork for the AUTHOR file or from the librenms master branch?

I’m still new at this Github stuff.

Thanks.

**Comment by laf** [comment]
The easiest way is to click this: https://github.com/librenms/librenms/edit/master/AUTHORS.md

Add your details as explained and then in the commit changes section paste in:

`I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md.`

If you agree to the terms then follow the instructions on github.

**Comment by boudreau** [comment]
Ok, I think I didn’t go all the way with the pull request the first time.

Hope it works this time.

Thanks for the help

Yves

**Comment by laf** [comment]
All sorted. Thanks :)

image

**Comment by boudreau** [comment]
Thanks, 
But I just notice that in the device>health>overview, the runtime graphic is not working right. All the others that I checked are ok. 

runtime-device-health-overview

Can quite find where I need to update the files? Any ideas?

Thanks

**Pull request merged**
