### PR TITLE
webui: alerts table refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

before:
screen shot 2017-11-19 at 3 23 30 am

after:
screen shot 2017-11-19 at 3 23 02 am

### CODE REVIEW

**Comment by kkrumm1** [comment]
I like it just did a test pull on it. 👍 
idk if users will miss the severity status.

**Comment by crcro** [comment]
it’s not missing, it just doesn’t have the title in table header, the icon is still there at the begining of each row

**Comment by kkrumm1** [comment]
ah, I see. this is very nice.

**Comment by laf** [comment]
Really like the idea behind this. However I have a few comments :)

1) The change to the status indicator goes away from how the devices and services page looks. Same as this PR: https://github.com/librenms/librenms/pull/7628.

2) The status seems like it's no longer relevant. It's not about if notifications are going out it's just an indicator that the alert is active. In essence the status will never be anything other than `alert`.

3) Can you get some colour in the ack icon.

4) Can you change the tooltip messages to be in normal case rather than all UPPERCASE. I.e: Uppercase.

5) The Procedure URL doesn't work for me.

**Comment by crcro** [comment]
Is this better @laf ?

screen shot 2017-11-20 at 3 33 18 am

**Comment by FTBZ** [comment]
My opinion about all the recent PR for the UI is that the paging is always too big in all interface. We lost a lot of place only for ... blank space. Same with the title on the dashboard.

So, everything that can make the interface more readable and tiny is welcome.

**Comment by laf** [comment]
@crcro a lot better.

Now, you just need to work with @Rosiak to decide on the best way to display the left hand side block and then he can update the services and devices page so we can merge them at the same time :)

@FTBZ The table hasn't changed so I think this might be the status block on the left increasing the space between rows.

**Comment by crcro** [comment]
after recent changes:

screen shot 2017-11-20 at 9 48 36 pm

**Comment by laf** [comment]
Looks great.

**Comment by crcro** [comment]
alerts page cleanup
before:
screen shot 2017-11-25 at 10 51 09 pm

after:
screen shot 2017-11-25 at 10 50 10 pm

**Comment by crcro** [comment]
pushed the alert log table

before:
screen shot 2017-12-01 at 1 42 30 am

after:
screen shot 2017-12-01 at 1 42 12 am

**Comment by laf** [comment]
Probably don't need the Status column here, the colours will show the state.

**Comment by daynedrak** [comment]
So just want to leave a comment, as this changed while I was away for the holidays. While I get that you're trying to clean it up and make it more compact, I really hate not being able to see whether or not the alert is muted. Furthermore, the acknowledgement colors threw me. If I remember right, muted showed green. Regardless, the way it is now, seeing red when it's acknowledge and green when it's not acknowledged seems reversed. I see red and my instinct is something is wrong, and in an acknowledgement column, my instinct was that it was unacknowledged. Seeing green for unacknowledged alerts likewise seems backwards

**Comment by laf** [comment]
I'm wondering if we should have orange as muted / acknowledged rather than green anyway.

Will submit a PR now.

**Comment by laf** [comment]
Going for this:

image

**Pull request merged**
