### PR TITLE
Health graph fixes for sub directories

### PR DESCRIPTION
**Pull request by dlehman83**
Fix health graphs when using a sub directory and reverse proxy.  
Currently these graphs give a 404 because the url is not using the sub directory.  
The first draft of this PR  assumes a sub directory of /librenms and has this path coded in.  
I'm looking for help to refine the PR to properly use the app_url or base_url variables.  

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by dlehman83** [comment]
I have two ideas for approaching this, but you folks know the code better.  
1. Create a new var 
```php
$graphurl = Config::get('base_url') . 'graph.php'

```
Then on lines 359 and 399 change replace url(graph.php) with url($graphurl)
I tried this but could not get it to work.  

I also tried adding the Config::get('base_url')  into those lines.  This returned a double url that also gave 404.  


2. The parseLegacyPathVars or some of the other functions that look like they are manipulating the url may need updated.  

What I do not understand is the memory health graph works fine before and after these changes.  The rest do not.  I had started by trying to compare those files to the memory page.  

All the other graphs, dashboards, ports etc work fine.  It is just the health graphs.

I hope all this makes sense.

**Comment by murrant** [comment]
How are the other graphs that work generating their urls?

**Comment by dlehman83** [comment]
> How are the other graphs that work generating their urls?

That is what I'm trying to figure out.  The only health page working is the memory page.  
I noticed today the device link on those pages also goes to a 404.  I was trying to compare but I have not found anything yet.

**Comment by dlehman83** [comment]
The hostname link for example.  
librenms\includes\html\table\toner.inc.php
```php
'hostname' => generate_device_link($toner),
```
librenms\includes\html\table\mempool-edit.inc.php
```php
'hostname' => generate_device_link($drive),
```

These look to be calling the same function so should both be good urls.  However the memory page works and the toner page does not.

**Comment by PipoCanaja** [comment]
Hi @dlehman83 
Do you still have this issue with link generation ?

**Comment by murrant** [comment]
Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.

Please feel free to reopen, I would love to see your changes added to LibreNMS.

**Pull request closed without merging**
