### PR TITLE
Poller tuning

### PR DESCRIPTION
**Pull request by vitalisator**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ x ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [ x ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
I'm assuming these devices don't support those modules rather than it being personal choice?

**Comment by laf** [comment]
@vitalisator bump

**Comment by vitalisator** [comment]
@laf, correct there is no support for deactivated modules.

**Comment by laf** [comment]
@vitalisator  Thanks, it just needs the opposite modules disabling then so for storage both polling and discovery should be disabled (I'm assuming).

**Pull request merged**
