### PR TITLE
snmp exec support

### PR DESCRIPTION
**Pull request by robje**
This pull request adds snmp exec support for dmidecode hardware detection

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR. @robje You need to sign the CLA still, it might be because you need to ensure the user your commit is done as is your github user and the email is in your account.

**Comment by robje** [comment]
I did not know this about the commit email. Added it to my profile later, but can't get it to be reprocessed.

**Comment by laf** [comment]
:( When you click the https://cla-assistant.io/librenms/librenms?pullRequest=7126 link, the email address it shows there, was that the one that this was committed with?

**Comment by robje** [comment]
I don't see an email address on the cla-assistant page.

The initial email I received mentioned:
> **Rob J. Epping** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

I did add the email address but still no go.

**Comment by laf** [comment]
What does this show for you:

```
-bash-4.2$ git config -l|grep -P '^user\.'
user.name=laf
user.email=gh+n@laf.io
```

The name and email are my github details so the CLA maps that back from the commits to GH and I can sign the CLA. If they don't match it can't work out if you've signed it.

**Comment by robje** [comment]
this:

    epping@librenms-dev:/opt/librenms$ git config -l | grep ^user
    user.name=Rob J. Epping
    user.email=epping@renf.us
    user.name=Rob J. Epping
    user.email=librenms@renf.us
    epping@librenms-dev:/opt/librenms$ 

first set is global, second set is from librenms.

Must user.name match the github name?

**Pull request merged**
