### PR TITLE
Update menu.blade.php

### PR DESCRIPTION
**Pull request by TheGracens**
It makes life easier with a scrollable Dashboard selection menu

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Does this actually work?  I tried to test it and can never cause a scrollbar.

Perhaps before and after screenshots would be useful.

**Comment by TheGracens** [comment]
Before

before

After

after

**Comment by TheGracens** [comment]
before

before

After

after

**Comment by TheGracens** [comment]
It is possible that you need some more dashboard entries before the scrollbar appears.  I tried it here on my test-machine

**Review by murrant — APPROVED** [review]
Thanks for the pictures, looks great.

**Pull request merged**
