### PR TITLE
rewrite of availability-map

### PR DESCRIPTION
**Pull request by crcro**
new look and added the missing functionality

am-directpage
am-widget

### CODE REVIEW

**Comment by laf** [comment]
Will comment a little later but looks good :)

**Comment by laf** [comment]
This is ace :) At first I thought the replacement for the small red/green tiles wouldn't work as it was originally designed to be condensed but I like it.

Few design elements to fix, drop down is close to the text:

image

This needs to be in a table or at least formatted differently:

image

It's difficult to read the white text on the orange background in the full availability map.

light.css is only one of the themes, you need to also update dark.css and mono.css.

I'm not sure I like placing each of the html lines on a new line with $output[]. It makes it harder to read and should be as it was before.

You've also got some bad formatting on the if statements, `if(something) {` it should be `if (something) {` - notice the space.

I've not checked through much more of the code yet.

**Comment by crcro** [comment]
@laf could you try it again and tell me if everything is ok? (i think i fixed display issues for safari)

**Comment by laf** [comment]
Certainly better for the boxes :)

I'd say the drop down is a bit crazy in size now though:

image

I still think this seems a bit odd:

image

Maybe put the numbers in the relevant boxes?

I still think you doing `$common_output[] = '<form class="form-horizontal" onsubmit="return widget_settings(this)">';` is wrong and over the top. It's duplicating so much and losing readability.

**Comment by crcro** [comment]
hope this commit will be better @laf :)

**Comment by murrant** [comment]
How about something like this for the counts?

http://codepen.io/anon/pen/vKPgvd

image

**Comment by crcro** [comment]
this looks like v2 styling? :)

**Comment by murrant** [comment]
Just bootstrap, but I would like to import this into v2.  Feel free to submit a v2 PR😀

**Comment by crcro** [comment]
i'm thinking about v2, still getting used to laravel's style :(

**Comment by vitalisator** [comment]
this brokes some settings in availability-map widget for me
- boxes are not scalable more (if you have over 160 devices it took too much place)
- widget settings are broken. It seems that setting from availability page are used instead.

**Comment by laf** [comment]
The pull request is probably not the place to raise this, please open an issue.

**Pull request merged**
