### PR TITLE
Juniper DOM support

### PR DESCRIPTION
**Pull request by bartdebruijn**
Added the correct mib for Juniper DOM support, as well as an upgrade Juniper-SMI mib for dependency issues.

### CODE REVIEW

**Comment by dorkmatt** [comment]
One thing to note is this only covers XFP optics, not SFP optics - see https://github.com/Juniper/junoscriptorium/blob/master/library/juniper/event/snmp/record-optics/record-optics.slax

**Comment by laf** [comment]
Is their no code needed to make this work.+?

**Comment by bartdebruijn** [comment]
@laf yes there is, but I thought I'd push the new mibs first before I start coding.

**Comment by laf** [comment]
Ok no probes, where are the mibs from (url?)

**Comment by bartdebruijn** [comment]
I got them from http://www.oidview.com

**Comment by laf** [comment]
Thanks @bartdebruijn 

Can you double check the ones from Juniper direct as they do publish them, as an example:

https://www.juniper.net/documentation/en_US/junos13.3/topics/concept/mib-digital-optical-monitoring-overview.html

**Comment by bartdebruijn** [comment]
Well, we can download the entire JunOS mib pack and put that into librenms as well: http://contentapps.juniper.net/mib-explorer/download.jsp#product=Junos+OS

I wouldn't be opposed to including the latest mibs. I doubt they'd break something.

**Comment by laf** [comment]
@bartdebruijn Do that, we do it for Cisco regularly.

**Comment by bartdebruijn** [comment]
That's a crapload of mibs though, I'll upload the ones I need for now, otherwise you'll see a pull request for about 140 mibs :)

**Comment by bartdebruijn** [comment]
I think it would make the most sense to get the: ifName, jnxDomCurrentRxLaserPower, jnxDomCurrentTxLaserPower and jnxDomCurrentModuleTemperature oid's from the device, these should all be available through JUNIPER-DOM-MIB (ifName is done through IF-MIB, that that is called through JUNIPER-DOM-MIB)

Currently, the discover script tries to get the information about optics by tying to poll the following oid's from CISCO-ENTITY-SENSOR-MIB.

entPhysicalDescr
entPhysicalName
entPhySensorType
entPhySensorScale
entPhySensorPrecision
entPhySensorValue

This doesn't translate well into JunOS, because it doesn't have those oid's or something comparable. However, we can get the interface name, the RX/TX power levels and the temperature, which should be sufficient.

It would probably be best to make a seperate file for this, juniper-dom-sensors.inc.php and add some logic into sensors.inc.php to exclude juniper interfaces that have been already discovered.

**Comment by laf** [comment]
@bartdebruijn 

Can you update these mibs with the ones from Juniper as the current ones in this PR are older.

**Comment by bartdebruijn** [comment]
@laf they changed the naming scheme of the MIB's, unfortunately. How do you want to proceed?

**Comment by laf** [comment]
@bartdebruijn 

How do you mean changed the name? If it's just the filename this usually doesn't matter.

**Comment by bartdebruijn** [comment]
@laf Well, for instance JUNIPER-SMI is now called mib-jnx-smi.txt.

**Comment by laf** [comment]
That's just a file name, if you take a look in the file I expect the name is the same.

**Comment by laf** [comment]
@bartdebruijn Feel free to re-open this but closing due to inactivity.

**Pull request closed without merging**
