### PR TITLE
Grandstream basic support

### PR DESCRIPTION
**Pull request by PipoCanaja**
Grandstream very basic support (MIB pretty bad).

Had to exclude "Linux HT" from the linux.yaml file to match these devices. If anybody has a better idea ... 

Will close https://github.com/librenms/librenms/issues/8015

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
@murrant Just a note to double check the change on the linux.yaml file ... Hope it does not break anything ... but ... more eyes is always better

**Comment by murrant** [comment]
@PipoCanaja I think linux is treated specially, it is check AFTER all other OS are checked.

**Comment by PipoCanaja** [comment]
I am not so sure cause during my tests, without the change in the linux.yaml, the device was always detected as linux and not grandstream-ht.

**Comment by PipoCanaja** [comment]
Let's WIP this, I'll test again if I can avoid the change in linux.yaml. Will be a little bit less available in the next few days, except if the weather is bad for skiing ...

**Comment by PipoCanaja** [comment]
Works correctly now without touching linux.yaml, so I reverted that.

**Pull request merged**
