### PR TITLE
VRP FDB table correctly parsed on some CE switches

### PR DESCRIPTION
**Pull request by PipoCanaja**
Following https://community.librenms.org/t/fdb-table-missing-interface-info-on-huawei/12334/2

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
@murrant Quick solve here. 3 little seconds added in the sleep and it goes to the end. Not a definitive solution but at least snmpsim can start now. And it will be OK for a few more test files until it timesout again.

**Comment by kafooo** [comment]
Can confirm that this fix my issue (as creator of https://community.librenms.org/t/fdb-table-missing-interface-info-on-huawei/12334 )

**Comment by murrant** [comment]
@PipoCanaja fine with the quick fix for now.

**Comment by murrant** [comment]
But you fixed it in the wrong place, set it in bootstrap.php.  And if that is fixing it, probably the one in .travis.yaml is not working.

**Comment by PipoCanaja** [comment]
@murrant Looks good  with the value (6 seconds, I am now 1 second more generous) in bootstrap :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
