### PR TITLE
Proper hardware and version identification for SAF

### PR DESCRIPTION
**Pull request by noaheroufus**
Fixes Issue #7350 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7378)

### CODE REVIEW

**Comment by murrant** [comment]
I know some of the existing code is like this, but this looks extremely fragile.

Any way you can make it nicer with some regex or something?

**Comment by kmpanilla** [comment]
@murrant which lines are looking fragile?  All of it?

**Comment by murrant** [comment]
Say saf adds a semi-colon at some-point?  Then it is all broken.

**Comment by murrant** [comment]
For example of the sysDescr's listed in the ticket here is a regex that would work:

`radio;(CFIP |SAF )?(.*) v([0-9.]*).*SN: ([0-9]+)`  https://regex101.com/r/33ICT5/3

Then the first group is throw away (CFIP and SAF), the second group is the product name, the third group is the version, and the fourth group is the serial number.

**Pull request merged**
