### PR TITLE
changes needed to run under web server subdirectory

### LINKED ISSUE #285: librenms unable to run in subdirectory
LibreNMS is unable to run in a subdirectory.  

In my case, I need this because I'm attempting to run it in a VM environment, with a nginx proxy, and the subdirectory redirects you to the proper VM.  

The two things I have noticed are broken - the images directory & when you login, it redirects you to the domain name.  

Thanks!

### PR DESCRIPTION
**Pull request by miken32**
These are the changes I've made to run under https://server.internal/librenms. .htaccess also needs to be updated, and should probably be built dynamically as part of the install process. Should resolve #285 but will need testing, as we are just getting started with this project.

### CODE REVIEW

**Comment by laf** [comment]
@f0o Can you update the CI build for this to use a sub directory for testing or is it easier if we test manually?

**Comment by laf** [comment]
@miken32 FYI we will need you to sign the contributors agreement, you can add that to this PR with another commit or a separate one if you like.

Thanks for contributing this - we've been asked about it more recently so we really appreciate this :)

**Comment by laf** [comment]
A quick code review looks good, scrut looks good.

**Comment by f0o** [comment]
Updated, Build is now located at http://1645.ci.librenms.org/librenms/

**Comment by laf** [comment]
@miken32 Could you write a doc about what's needed to be changed for users please. Apache only will be fine, we can extend out later.

**Comment by miken32** [comment]
The only change in the distribution needing to be made, for Apache, is to make the `RewriteBase` directive in `html/.htaccess` reference the path:
`RewriteBase /librenms`
instead of 
`RewriteBase /`

Server setup is fairly obvious to anyone who's set up Apache before; rather than setting up a virtual host, you instead put the commands in the root of the server configuration. I run Scientific Linux (another RHEL variant) so I just put something like this into `/etc/httpd/conf.d/librenms.conf`:
```
AllowEncodedSlashes On
Alias /librenms /opt/librenms/html

<Directory "/opt/librenms">
    AllowOverride All
    Options FollowSymLinks MultiViews
</Directory>
```

**Comment by laf** [comment]
Thanks @miken32 

The contributors agreement needs you to push the commit with the message " I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md."

if you can push another commit with that message that would be great.

The docs can be as you've put above, if you can put that into docs/Extensions/Sub-Directory.md to explain to people how to do it for Apache that would be great.

**Comment by f0o** [comment]
I can provide nginx configs once merged.
I will readjust the CI later today and test it one last time in this final state and if no issues merge it

**Comment by laf** [comment]
@miken32 

We had to revert this PR as it caused issues with Apache.

The code which looks to cause the issue (a lot of pages drop back to the overview page) is in html/includes/vars.inc.php

**Comment by miken32** [comment]
Yes I think I see where the problem is, with sites that don't have a subdirectory. I've pushed a change to my repo, not sure how to reopen a pull request though...

**Comment by laf** [comment]
You can't re-open a PR :( You will need to create a new one. Just push to another branch name.

**Comment by LeslieCarr** [comment]
A belated thank you!!!

**Pull request merged**
