### PR TITLE
Basic ZTE ZXA10 detection

### PR DESCRIPTION
**Pull request by murrant**
and mark snmpEngineTime as bad
fixes: #13576

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by aztec102** [comment]
Thank you very much! I was really looking forward to the support of this device.

**Comment by murrant** [comment]
@aztec102 this really only fixes the uptime and adds an icon.  Take a look at what has been added, it is pretty short.  Maybe next time you can add it :)

**Comment by aztec102** [comment]
@murrant In fact, there is such a piece of hardware, so it is possible :)

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Pull request merged**
