### PR TITLE
Made poller message box a link to /poll-log/

### PR DESCRIPTION
**Pull request by laf**
Rather than just warn users, not takes them to the poll-log page

### CODE REVIEW

**Comment by f0o** [comment]
I'm unsure if the poll-log helps if a device is unpolled.. A link to a (new?) Page with a list of the devices might be better...

**Comment by laf** [comment]
I guess there's two sides to it, if the device has never been polled then yes it wouldn't show up. If the device has been polled but not for over 15 mins then we are fine. I think I'll just update poll-log to include devices that are un-polled completely.

**Comment by laf** [comment]
Just checked @f0o, poll-log pulls out all devices and uses the last_polled_timetaken field so even if a device has never been polled it will show up in this :)

**Comment by f0o** [comment]
All good then :)

**Pull request merged**
