### PR TITLE
Use PDO for MySQL queries

### PR DESCRIPTION
**Pull request by murrant**
Gut dbFacile
mres() now does nothing... could have some vulnerable queries, but most are ok

TODO
- [x] IRC client broke
- [x] Install broke

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Checked out for testing on my dev install, leaving overnight.

**Comment by laf** [comment]
I dont' seem to see DB queries now in debug out with `-v` for poller.php or discovery.php.

I'm not sure I'm getting eventlog data now:

`SQL[INSERT IGNORE INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)  VALUES (:host,:device_id,:reference,:type,NOW(),:severity,:message,:username) {"host":168,"device_id":168,"reference":"NULL","type":"alert","severity":1,"message":"Issued critical alert for rule 'Localhost' to transport 'mail'","username":""} 3.79ms]`

Doesn't show up.

Is using IGNORE a wise thing, means that we won't see the mysql errors in the log file anymore.

**Comment by murrant** [comment]
Ah yes:
```
SQL Error! SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '11-8' for key 'unique_alert' (SQL: INSERT INTO `alerts` (`state`,`device_id`,`rule_id`,`open`,`alerted`)  VALUES (:state,:device_id,:rule_id,:open,:alerted)) in includes/alerts.inc.php:236
```

I guess I need to fix the query...

**Comment by laf** [comment]
Re-tested and seems ok still. Found the issue with the installer and it's because I moved /opt/librenms/ out of the way in one shell whilst staying in it in another. In the one I was already in that dir for, running `ll config.php` showed a file existed when in reality - it didn't.

**Comment by murrant** [comment]
FYI, been using this on my production without issues.

**Comment by murrant** [comment]
FYI, the last commit was to fix travis.   Didn't seem to have an affect on normal use.

**Comment by laf** [comment]
> FYI, the last commit was to fix travis. Didn't seem to have an effect on normal use.

Indeed hence I didn't retest :) Nice work with this.

**Pull request merged**
