### PR TITLE
Hide divider if no plugins available - fixed

### PR DESCRIPTION
**Pull request by SaaldjorMike**

### CODE REVIEW

**Comment by f0o** [comment]
`dbFetchCell("SELECT COUNT(*) from `plugins` WHERE plugin_active = '1'"` should be
`dbFetchCell("SELECT COUNT(*) from `plugins` WHERE plugin_active = '1'")`

**Comment by SaaldjorMike** [comment]
@f0o: You are correct, my bad. Dont know if this PR is still ok. Let me know if I should open a new one.

**Comment by paulgear** [comment]
@SaaldjorMike You don't need to create a new PR for something like this - just push the fix to the same branch and the PR will automatically update.

**Comment by SaaldjorMike** [comment]
@paulgear: Next time I'll make sure to do this. Thanks.

**Pull request closed without merging**
