### PR TITLE
Translation of settings in French

### PR DESCRIPTION
**Pull request by PipoCanaja**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
What's with the changes to the js files?

**Comment by PipoCanaja** [comment]
Cross PR between this one and the German translation when generating the .js ... rebasing was long :) 
But at then end, the js files are the ones generated after the german translation was merged, so they are up to date.

**Comment by PipoCanaja** [comment]
Recreated all this PR by only keeping the french settings.inc.php file, and re-computing the others, starting from current master. So no more rebase, no risk of mistake :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
