### PR TITLE
Added support for Orvaldi UPS

### PR DESCRIPTION
**Pull request by PipoCanaja**
Fixes: #8780 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10021 `
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @jozefrebjak 
Seems that you have a PR to test for these UPS support added to LibreNMS :) 
Let me know if it is OK for merging. 
Bye

**Comment by jozefrebjak** [comment]
Do you have some Orvaldi UPS ? .. because we have a orvaldi ups with different snmp modul, what i added to issues, because lower model was bad,  so i am getting that modul as linux with oid .1.3.6.1.4.1.8072.3.2.10, so i changed discovery to 
 ```
discovery:
     - sysDescr:
         - 'Linux SNMP-System'
```
 and it works great

here is the new snmprec

https://p.libren.ms/view/269641b4

**Comment by jozefrebjak** [comment]
we can also change os polling to 

```
<?php
$orvaldi_data = snmp_get_multi_oid($device, ['upsIdSerialNumber.0', 'upsIdFWVersion.0', 'upsIdModelName.0'], '-OUQs', 'companyMIB');
$version      = $orvaldi_data['upsIdFWVersion.0'];
$serial       = $orvaldi_data['upsIdSerialNumber.0'];
$hardware     = $orvaldi_data['upsIdModelName.0']
```
and add for example do yaml discovery state of the ups, if is online (or we can add it to feautere in os polling) and count of the batteries

```
mib: companyMIB
modules:
     sensors:
         state:
             data:
                -
                     oid: upsIdUPSType
                     num_oid: '.1.3.6.1.4.1.21111.1.1.1.7.{{ $index }}'
                     descr: UPS Type
                     state_name: upsIdUPSType
                     states:
                         - { descr: 'standby', graph: 1, value: 0, generic: 0 }
                         - { descr: 'line-interactive', graph: 1, value: 1, generic: 1 }
                         - { descr: 'on-line', graph: 1, value: 2, generic: 0 }
     count:
              data:
                -
                     oid: upsBatNumberInSeries
                     num_oid: '.1.3.6.1.4.1.21111.1.1.3.14.{{ $index }}'
                     descr: Number of Battery in Series
                     group: Battery
                     index: 'series-{{ $index }}'

                -
                     oid: upsBatNumberInParallel
                     num_oid: '.1.3.6.1.4.1.21111.1.1.3.15.{{ $index }}'
                     descr: Number of Battery in Parallel
                     group: Battery
                     index: 'parallel-{{ $index }}'

```

and maybe is possible to disable procesor info ? because its on 100%

there is also updated snmprec

https://p.libren.ms/view/09eddf38

**Comment by PipoCanaja** [comment]
Hi @jozefrebjak 
Thanx for your feedback, I implemented them and tested using the snmprec. 
- No need to put the linux OID, the current criteria works correctly. Try to remove cache/os_defs.cache before doing a discovery. 
- I have no idea how to disable the processor discovery. 

You can test the current state of the PR and let me know how it goes.

**Comment by jozefrebjak** [comment]
@ its fine, but will be fine to add yaml discovery of sensors for state and count of the batteries

**Comment by PipoCanaja** [comment]
@jozefrebjak 
It is already there. You have to delete os_cache and force a discovery after applying the patch again. 
I'll check the tests with Travis.

**Comment by PipoCanaja** [comment]
My bad, I did not ```git add``` the file ...

**Comment by jozefrebjak** [comment]
@PipoCanaja its ok. Its can be merged. Thank you :)

**Comment by PipoCanaja** [comment]
All right, Thx !

**Pull request merged**
