### PR TITLE
Updated map to now include devices linked by mac

### PR DESCRIPTION
**Pull request by laf**
This now extends the map to show devices that are associated via mac / port.

Removed the check for links in the db to show map link as you can't decide this from a single query for macs so now added link to all installs, if a map doesn't show it will suggest the user isn't running xdp or have devices associated via mac addresses.

### CODE REVIEW

**Comment by laf** [comment]
bump

**Comment by SaaldjorMike** [comment]
@laf: Seems like these changes make it very slow to load the network map page. 
Loading /map/: https://i.imgur.com/WQCQ3It.png
Zooming out a bit: https://i.imgur.com/W1xKZ0o.png
'Developer Tools' enabled while loading: https://i.imgur.com/bobJRbR.png

**Comment by laf** [comment]
I'll see if I can optimise the queries that pull the data out. It's now going through bigger a bigger table.

**Comment by f0o** [comment]
I can reproduce @SaaldjorMike's issues.
bump for fix :)

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
bump ;)

**Comment by f0o** [comment]
:+1:

**Pull request merged**
