### PR TITLE
Cisco: change notKnown status to unknown and not warning

### PR DESCRIPTION
**Pull request by FTBZ**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

------------------------------------

The cRFStatusPeerUnitState is used for the VSS Peer Status, problem is that a lot of devices return a warning because the VSS Peer State is in warning when the status is "notKnown".

But a notKnown status should be categorized as LibreNMS "Unknown" and gray but not as a "Warning" and yellow status.

### CODE REVIEW

**Comment by laf** [comment]
Looks like the updated pre-commit.php hasn't ran unit tests when it should. I'll take a look.

**Comment by murrant** [comment]
Also, because this uses the old style state sensor declaration, it will not update the database.
You need to update to this yaml or the php style here: https://docs.librenms.org/Developing/Sensor-State-Support/

**Comment by murrant** [comment]
@laf it ran 993 tests, which is all of them.

**Comment by laf** [comment]
> @laf it ran 993 tests, which is all of them.

@murrant Ah it's moved to 7.2 now hasn't it. Forgot about that.

**Comment by laf** [comment]
@FTBZ Any response to murrants comment on this?

**Pull request merged**
