### PR TITLE
Added definition for Riello 204

### PR DESCRIPTION
**Pull request by wolfraider**
Added new OID for Riello UPS detection

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Would you mind generating test data for this device?

**Comment by wolfraider** [comment]
I don't have one of these devices for testing. I am requesting the original requester to generate the test data.

https://community.librenms.org/t/riello-netman-204-identified-as-generic-device/11949/5

**Comment by PipoCanaja** [comment]
No Test data available. But I suggest to merge it anyway.

**Review by PipoCanaja — APPROVED** [review]
LGTM, even without tests

**Comment by PipoCanaja** [comment]
Thanx @wolfraider  !

**Pull request merged**
