### PR TITLE
Add Cisco FSM to ios.yaml

### PR DESCRIPTION
**Pull request by pblasquez**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
You will need to add tests too.
Update OSDiscovery and add a new snmprec.

**Comment by laf** [comment]
Does Cisco Firewall Services Module run IOS? For the 6500 it run fwsm: https://software.cisco.com/download/release.html?mdfid=277413409&softwareid=280775068&release=4.1(11)

**Comment by laf** [comment]
@pblasquez Any feedback?

**Comment by murrant** [comment]
Found this: http://www.cisco.com/c/en/us/products/interfaces-modules/catalyst-6500-series-firewall-services-module/index.html

`Based on Cisco PIX Firewall technology, the Cisco FWSM`

So, looks like it should be classified as PIX maybe?

**Comment by pblasquez** [comment]
I looked for an fwsm OS but didn't find one, my short-term goal was to activate polling for CPU/RAM/Disk, which works fine using the IOS profile.

Can we add this PR to address this for the short term so I don't have to maintain my local patch, and open the new FWSM/PIX OS as a feature request discussion on the community site?

@murrant: For the test, do I just add the 'Cisco Firewall Services Module' entry to the correct OS function? Or something more involved than that?

**Comment by laf** [comment]
We already have pix (pixos) as an OS this can be tagged onto. I'm not sure if it does really belong in it's own fwsm as that's what it's referred to as is the firmware you can download from it.

We shouldn't merge this into IOS as a work around, it needs to be done correctly first time.

**Comment by pblasquez** [comment]
ok, didn't see pixos since I wasn't looking in the definitions directory yet.  I will update and add the test as well.

**Comment by laf** [comment]
Does cpu/ram/disk work still now?

**Comment by pblasquez** [comment]
I'm going to close this out and submit a new, rebased, clean patch.

**Pull request closed without merging**
