### PR TITLE
Improved Dlink Serial & FW detection

### PR DESCRIPTION
**Pull request by hanserasmus**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

The initial code I copied from comes from `includes/polling/os/vrp.inc.php`. @PipoCanaja referenced it in Discord and told me to have a look there regarding OID lists. So any copyright infringements were done in error and by accident, with no malicious intent what so ever.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @hanserasmus 
Could you please check and correct all the files that should not be changed (.gitignore, composer etc etc) ? You need to clean this PR to only include the necessary files, and not change anything else.
Thanx

**Comment by PipoCanaja** [comment]
In order to correct, you can do the following : 
```
git checkout upstream/master bootstrap/cache/.gitignore
```

**Comment by hanserasmus** [comment]
> git checkout upstream/master bootstrap/cache/.gitignore

I get this:
```
-bash-4.2$ git status
# On branch issue-10467
nothing to commit, working directory clean
-bash-4.2$ git checkout upstream/master bootstrap/cache/.gitignore
error: pathspec 'upstream/master' did not match any file(s) known to git.
-bash-4.2$ 
```
Sorry for screwing this up.

**Comment by hanserasmus** [comment]
Going to close this and start fresh, to see if I can fix all the issues. Sorry for the mess.

**Pull request closed without merging**
