### PR TITLE
api: Added ability to supports CORS for API

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7322 

Uses https://github.com/palanik/CorsSlim.

Docs done, disabled by default.

We do need to be careful with php 5.3. A commit removes it from travis checks. Composer doesn't indicate a required version.

Edit, actually, looks ok:

```bash
sh-4.1# php -v
PHP 5.3.3 (cli) (built: Mar 22 2017 12:27:09)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
sh-4.1# ./vendor/bin/parallel-lint --exclude lib/influxdb-php/  ./vendor/palanik/
PHP 5.3.3 | 10 parallel jobs
....                                                         4/4 (100 %)


Checked 4 files in 0 seconds
No syntax error found
```

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7357)

### CODE REVIEW

**Comment by Zaxmy** [comment]
XMLHttpRequest cannot load https://librenms.nsa.his.se/api/v0/services/xxx.xxxx.xxx.xxx. Request header field X-Auth-Token is not allowed by Access-Control-Allow-Headers in preflight response.

Include X-Auth-Token in the default example, might be good idee ?

**Comment by laf** [comment]
X-Auth-Token added

**Comment by Zaxmy** [comment]
Reviewed 27 of 28 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Support/Configuration.md, line 621 at r2](https://reviewable.io:443/reviews/librenms/librenms/7357#-KuOKx00ryHzywTNRK-d:-KuOKx00ryHzywTNRK-e:b488tcd) ([raw file](https://github.com/librenms/librenms/blob/847f9c6028c72dd1c3a8c78a3a2a6805a65cc2ed/doc/Support/Configuration.md#L621)):*
> ```Markdown
> $config['api']['cors']['maxage'] = '86400';
> $config['api']['cors']['allowmethods'] = array('POST', 'GET', 'PUT', 'DELETE', 'PATCH');
> $config['api']['cors']['allowheaders'] = array('Origin', 'X-Requested-With', 'Content-Type', 'Accept');
> ```

X-Auth-Token ought to be added here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/librenms/librenms/7357)*

**Comment by Zaxmy** [comment]
X-Auth-Token missing in documentation for doc/Support/Configuration.md

**Comment by laf** [comment]
This should be all up to date now.

**Pull request merged**
