### PR TITLE
Enabling "Random access" lookups fixes "MIB: Could not find all::enterprises.xxx" error

### PR DESCRIPTION
**Pull request by exarv**

### CODE REVIEW

**Comment by laf** [comment]
@paulgear thoughts?

Seems like a logical change with no side effects (other than maybe lookup time within snmptranslate)

**Comment by laf** [comment]
@paulgear

**Comment by paulgear** [comment]
Seems reasonable to me; let me do some testing to confirm.

**Comment by murrant** [comment]
Why not just specify the oid as a number to avoid the translate?

**Comment by f0o** [comment]
Looks fine to me

**Comment by Rosiak** [comment]
Awating Paul's tests.

**Comment by spinza** [comment]
This seems to include all MIB values when MIB polling is active.  At least it does for me.  Is that the intention?
https://github.com/librenms/librenms/blob/master/includes/discovery/functions.inc.php#L134

**Comment by laf** [comment]
I suggest creating an issue for that.

**Pull request merged**
