### PR TITLE
Improved SmartAX OS support. Added CPU&Temperature for each card and …

### PR DESCRIPTION
**Pull request by TheGreatDoc**
…hardware, version and serial detection. Also added processors&traffic minigraphs in definition.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Well. It half work. Discovery works perfect, polling doesnt.
Processors disco: https://p.libren.ms/view/10804891
Processors polling: https://p.libren.ms/view/58dc71d9
Temperature disco: https://p.libren.ms/view/ff2b2fd4
Temperature polling: https://p.libren.ms/view/20aaa3cf

As a gift, in the polling pbins you will see what I think is the issue with escaped gzipped binary data in the alert_log table. That one that only happens 1/100.000 😄

**Comment by murrant** [comment]
@TheGreatDoc The oid passed to discovery needs to be fully numeric.  (replace the enterprises bit with `.1.3.6.1.4.1`)

**Comment by jozefrebjak** [comment]
Thanks for this pull request. I am tested this and there is the result for my huawei olt 5680t for now. When I did manual discovery i got values about temperature but not for all cards.

When i looked at my olt in CLI and when i used comand display temperature i got this values 

```
GPON_MA5680T#display temperature
{ frameid/slotid<S><Length 1-15>|frameid<U><0,32>|protect<K>|threshold<K> }:0

  Command:
          display temperature 0
  SlotID:  1      BoardName: H805GPBD       Temperature:   32C(  89F)
  SlotID:  7      BoardName: H802SCUN       Temperature:   31C(  87F)
  SlotID:  8      BoardName: H802SCUN       Temperature:   32C(  89F)
```

.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.7.0.1 = STRING: "H805GPBD"
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.7.0.2 = STRING: "H805GPBD"
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.7.0.7 = STRING: "H802SCUN"
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.7.0.8 = STRING: "H802SCUN"
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.7.0.17 = STRING: "H801GICF"
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.7.0.18 = STRING: "H801GICF"

.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.10.0.1 = INTEGER: 32
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.10.0.2 = INTEGER: 2147483647
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.10.0.7 = INTEGER: 31
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.10.0.8 = INTEGER: 32
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.10.0.17 = INTEGER: 2147483647
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.10.0.18 = INTEGER: 2147483647

So i think that maybe will be good to exclude that cards which doesnt support temperature.

image

it will be nice to have a support for power consumption. I got this in my nagios install with this OID 

.1.3.6.1.4.1.2011.2.6.7.1.1.1.1.11.0

.1.3.6.1.4.1.2011.2.6.7.1.1.1.1.11.0 = INTEGER: 281

or Rx optical power(dBm)  of onts will be great i believe. 

1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4

here is  list how it is look like in my snmpwalk of my device. This will be perfect. 

0/1/0 ont number 0-4

.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312192.0 = INTEGER: -1640
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312192.1 = INTEGER: -1491
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312192.2 = INTEGER: -1523
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312192.3 = INTEGER: -1567
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312192.4 = INTEGER: -1733

0/1/1 ont number 0-20
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.0 = INTEGER: -2244
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.1 = INTEGER: -2923
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.2 = INTEGER: -3129
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.3 = INTEGER: -2196
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.4 = INTEGER: -2166
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.5 = INTEGER: -2663
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.6 = INTEGER: -2771
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.7 = INTEGER: -2244
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.8 = INTEGER: -2744
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.9 = INTEGER: -2638
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.10 = INTEGER: -2523
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.11 = INTEGER: -2602
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.13 = INTEGER: -2301
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.14 = INTEGER: -2328
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.15 = INTEGER: -2568
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.16 = INTEGER: -2346
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.17 = INTEGER: -2236
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.18 = INTEGER: -2318
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.19 = INTEGER: -2553
.1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4.4194312448.20 = INTEGER: -2602

**Comment by TheGreatDoc** [comment]
@jozefrebjak What can I say? AMAZING feedback. Thank you very much.

I'll code to skip temp values greater than 999. Those guys from huaweis are a jokers with the mibs...

Do you know if that power comsuption (which I have too) is in watts? 

Also, about rx opticals Im not sure if it will be a good thing. I dont know how many ONTs do you have...but believe me when I say that will not work for us with thousands of ONTs.

I can make a try, but I'm pretty sure it will make my install to explode.

I want also to monitor SFP temperatures... I'm almost sure there is an oid with that

**Comment by jozefrebjak** [comment]
@TheGreatDoc perfect, now I am seeing just temperatures for that three cards. And yes that power consumption is in a wats.
 
```
MA5680T#display power 
---------------------------------------------
  Command of privilege Mode:
---------------------------------------------
emu                   Query EMU power
frameid[/slotid]<S><Length 1-255>
                      Parameter: FrameID[/SlotID]

that OID is for whole frame 0
GPON_MA5680T#display power 0
  ------------------------------
  FrameID  Power(unit:Watt)
  ------------------------------
  0        281
  ------------------------------
```

and there is also possibility monitor power per slot separately

```
MA5680T#display power 0/1
  ------------------------------
  SlotID   Power(unit:Watt)
  ------------------------------
  1        54
  ------------------------------
```

.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.11.0.1 = INTEGER: 54
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.11.0.2 = INTEGER: 49
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.11.0.7 = INTEGER: 50
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.11.0.8 = INTEGER: 50
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.11.0.17 = INTEGER: 4
.1.3.6.1.4.1.2011.2.6.7.1.1.2.1.11.0.18 = INTEGER: 4

and about that rx info of ont, i think you are right

**Comment by TheGreatDoc** [comment]
@jozefrebjak Power done. Please, check it

**Comment by laf** [comment]
@TheGreatDoc No mib for this as it looks like you could move those sensors to yaml.

**Comment by TheGreatDoc** [comment]
@laf No mibs :( I tried really hard to find them without luck so I had to make all work manually. Which is a pain in the....

**Comment by murrant** [comment]
I tried to find the MIBs.  From what I can tell these OIDs were extracted from the firmware.....

**Comment by laf** [comment]
That's a shame :(

Sometimes I wonder if it's easier if we created our own! 

Just need to fix the code formatting.

**Comment by TheGreatDoc** [comment]
@jozefrebjak If you dont mind doing a last test...

Now I think you should get your hardware correctly (MA5680T instead of RACK-300), FW Version and Serial.

Also processors and traffic minigraphs

**Comment by jozefrebjak** [comment]
@TheGreatDoc  amazing, for me is everything ok now. Thank you.

**Comment by TheGreatDoc** [comment]
@jozefrebjak Thank you for al the tests. 

@laf @murrant You can merge when you want.

**Pull request merged**
