### PR TITLE
Fix Debian Stretch rrdcached Base_Path

### PR DESCRIPTION
**Pull request by MHammett**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
The journal path below is similar...

**Comment by MHammett** [comment]
I don't know enough to know if that should be changed or not. My system appears to work with the stated journal path, but that doesn't mean it's right.

**Comment by murrant** [comment]
default should probably be under /var/lib or something.  Was there any created at install?  `locate rrdcached`

**Comment by MHammett** [comment]
It looks like there's one in /var/lib.

https://p.libren.ms/view/5bc4d694

**Pull request merged**
