### PR TITLE
Implemented a generic approach for ifHighSpeed values that cannot be …

### PR DESCRIPTION
**Pull request by footstep86**
…stored in the database

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by footstep86** [comment]
Database: `ifHighSpeed` int(11) DEFAULT NULL
SQL Integer: -2^31 (-2,147,483,648) to 2^31-1 (2,147,483,647)

**Comment by spencerryan** [comment]
Whatever editor you were using messed up the single quotes around ifHighSpeed and turned them into "smart quotes"

You have: `‘ifHighSpeed’` which will fail.

**Comment by footstep86** [comment]
I've just checked the RFC2233 and the datatype of the ifHighSpeed is Gauge32. So changing the database column to unsignend int is the correct solution and will eliminate the need for this kind of workaround. Unfortunatly I don't have any experience in that regard.

**Comment by murrant** [comment]
You don't need an os check if you fix the database. (this is much preferred)

You can see how to make a new migration here: https://laravel.com/docs/migrations

**Comment by footstep86** [comment]
I'll take a look into fixing the database at a later time.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
