### PR TITLE
Add an option for ad authentication to have a default level

### PR DESCRIPTION
**Pull request by jonathon-k**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Add a config option to allow modifying the default user level for AD authentication when auth_ad_require_groupmembership == 0.

### CODE REVIEW

**Comment by murrant** [comment]
I am against this change.  Requiring the admin to configure a group to grant higher permissions is not that  difficult and also reduces the change of accidental permission elevation.

**Comment by jonathon-k** [comment]
My rationale is two fold, one I don't see what is accomplished by allowing
people to authenticate with user level 0, and two the case of an amin who
doesn't have control over AD and has to setup the same permission for every
group.

The second one is a thin reason, I know, unless your AD admin thinks that
no common groups should exist...

Thoughts?

**Comment by murrant** [comment]
Once the user is created at level 0, you can grant them access to devices and ports specifically.  So they only see those items.

As for second option, maybe, but it isn't that likely.

**Comment by Gorian** [comment]
I am that admin that doesn't have control over AD.... in large corporations, it happens all the time. You have a small group in charge of AD, and lots of other groups that use it. In this case, the AD I'm trying to authenticate to has not group that everyone is in. Instead, we have groups that all start with "world.gs". For other applications, like Graylog, I can just do a wildcard on the group for "world.gs.*" and it works fine. No such option for LibreNMS. 

In my situation, the AD I'm binding to is not a global AD, therefore I can assume everyone who has been granted access to it can also have read-only access to the monitoring system by default.

**Comment by murrant** [comment]
Btw, I am not the final say here, just offering my opinion.  Others should speak up if they want this feature.

I would feel much better about it if it was limited to global read permission and couldn't grant admin access.

**Comment by jonathon-k** [comment]
Changing it to a flag specifically for giving global read access
permissions, rather than setting a default access level.  Probably makes
more sense -- I can't imagine this type of systems having a lot of admins
in different user groups...

**Comment by breeman1** [comment]
I would love to see this feature implemented as we are in the same predicament as @Gorian.

**Comment by jonathon-k** [comment]
If implemented as a flag, would it make sense to allow specifying groups with more restricted privileges or should this override any level below 5 (global read-only)

**Comment by murrant** [comment]
Any defined group should override the default level, even if it is lower.

**Comment by laf** [comment]
I'm not an ad user so can't offer any comments on this but it does need some style fixes :)

**Pull request merged**
