### PR TITLE
Add Varnish Docs

### LINKED ISSUE #1808: Add Varnish Directions on CentOS

### PR DESCRIPTION
**Pull request by Rosiak**
- Fix #1808

### CODE REVIEW

**Comment by f0o** [comment]
Here the settings we use on the demo, FYI.

```text
# varnishd -V
varnishd (varnish-3.0.2 revision 55e70a4)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2011 Varnish Software AS
```

```text
backend default {
    .host = "127.0.0.1";
    .port = "82";
}

sub vcl_recv {
 if (req.url ~ "\.(png|gif|jpg|swf|css|js)$" || req.url ~ ".*(graph\.php|/fonts/).*") {
  return(lookup);
 }
 if (req.restarts == 0) {
  if (req.http.x-forwarded-for) {
   set req.http.X-Forwarded-For =
   req.http.X-Forwarded-For + ", " + client.ip;
  } else {
   set req.http.X-Forwarded-For = client.ip;
  }
 }
 if (req.request != "GET" &&
     req.request != "HEAD" &&
     req.request != "PUT" &&
     req.request != "POST" &&
     req.request != "TRACE" &&
     req.request != "OPTIONS" &&
     req.request != "DELETE") {
  /* Non-RFC2616 or CONNECT which is weird. */
  return (pipe);
 }
 if (req.request != "GET" && req.request != "HEAD") {
  /* We only deal with GET and HEAD by default */
  return (pass);
 }
 if (req.http.Authorization || req.http.Cookie) {
  /* Not cacheable by default */
  return (pass);
 }
 return (lookup);
}

sub vcl_fetch {
 if (beresp.ttl < 300s) {
  set beresp.ttl = 300s;    
 }
 if (req.url ~ "\.(png|gif|jpg|swf|css|js)$" || req.url ~ ".*(graph\.php|/fonts/).*") {
  unset beresp.http.set-cookie;
 }
 return (deliver);
}
 
sub vcl_deliver {
 remove resp.http.Via;
 remove resp.http.X-Varnish;
 remove resp.http.Server;
 remove resp.http.Age;
 return (deliver);
}
```

**Comment by laf** [comment]
Do we need to get the example config into the doc?

**Comment by masonke** [comment]
If there is an example people can use to start from, that would be a huge help. 
~KEM

**Comment by Rosiak** [comment]
The default config should work, havnen't looking into the 2.x vs 3.x config from @f0o .

**Pull request merged**
