### PR TITLE
Fix for Nokia 7705 SAR

### PR DESCRIPTION
**Pull request by vitalisator**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/new-nokia-mpls-path-visualisation-issue-during-discovery-on-nokia-sar/10582/6

**Comment by craig-nokia** [comment]
Is there anything that I could do to help in this fix?

**Comment by vitalisator** [comment]
we just need to wait someone has merged this

**Comment by kkrumm1** [comment]
Can’t merge until Travis passes

**Comment by vitalisator** [comment]
If I understand this correctly, this error has nothing to do with my
commit. Is there someone with more understanding of what is wrong with
travis?

**Comment by Schouwenburg** [comment]
Would love some new attention to this blocked merge. Waiting for the fix made by vitaliser.

**Comment by craig-nokia** [comment]
The patch works and now mplsLspPathOperMetric allows NULL.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Pull request merged**
