### PR TITLE
Change PlaySMS to send alert message instead of just title

### PR DESCRIPTION
**Pull request by optimdevel**
fixed playsms php transport, that it actually works

fixed message body, so that it is appropriate for SMSes.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — CHANGES_REQUESTED** [review]
As I understand, only sending the title was due to length limitations.  Are you sure this is desired?

Additionally, you no longer send `$obj['title']` effectively breaking alerts for everyone that currently is using PlaySMS.

**Comment by optimdevel** [comment]
Only title means that, title of the rule is sent which tells me nothing and is always the same.
It works for services, should work also fine for others.
Lenght of SMSes does not seem to be a problem for gammu or playsms.

**Comment by murrant** [comment]
I am pretty sure the title has access to all the variables the message body does so you can put whatever you want in there.

**Comment by murrant** [comment]
No response, closing for now.  Comment to reopen or resubmit.

**Pull request closed without merging**
