### PR TITLE
Update Bootstrap

### LINKED ISSUE #1890: update Boostrap version
Hello,
From what I see in the current boostrap shipped with Librenms we're at 3.1.1 (http://i.imgur.com/4qs0sIw.png) while the actual bootstrap is at v3.3.5

### PR DESCRIPTION
**Pull request by Rosiak**
Fixes #1890 
- Bump bootstrap to latest 3.3.5

This should be thoroughly tested before merging, tagging @f0o @laf @paulgear

### CODE REVIEW

**Comment by laf** [comment]
trigger ci

**Comment by laf** [comment]
'trigger ci'

**Comment by laf** [comment]
trigger ci

**Comment by laf** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Perhaps my issue with the remember-me checkbox is connected to #2001

**Comment by laf** [comment]
@Rosiak Can you rebase so that we have the login checkbox fix to see if it's all ok now.

**Comment by Rosiak** [comment]
GitNoob gone rouge.
Closing this one.

**Pull request closed without merging**
