### PR TITLE
Remove Cisco Voice module

### PR DESCRIPTION
**Pull request by murrant**
Broken and unmaintained

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by laf — APPROVED** [review]
LGTM. Can't see much test data being available to look at fixing.

Out of interest, what's broken about it?

**Comment by murrant** [comment]
@laf some of the queries were corrected because they were calling nulls or something, but the correction wasn't right.  So it has been partially broken for months :)

**Comment by murrant** [comment]
I started to re-write this, but it didn't seem to have that much in it and I discovered it was broken previously.

**Comment by PipoCanaja** [comment]
Oups, was using it and missed this PR :D Need to find a way to reimplement that. 
Do you have a base of rewrite already ? Something that could be a start and a PR I could continue ?

**Comment by PipoCanaja** [comment]
(and yes, I applied master on prod, who would do that :D :D :D )

**Comment by murrant** [comment]
I started rewriting it but I realized it could just be count sensors.  So I suggest implementing what you were using as a count sensor.

**Pull request merged**
