### PR TITLE
Added error checking to add alert rule and add device group forms

### PR DESCRIPTION
**Pull request by laf**
This will inform users to click the and / or button in the modal window rather than closing it and doing a generic response.

### CODE REVIEW

**Comment by paulgear** [comment]
I wonder whether we could make and/or a dull red colour until one of them is clicked, then make it bright-ish green once clicked.

**Comment by laf** [comment]
Set them orange with an indicator to click. Also highlights the entity and value boxes if blank.

image

**Comment by f0o** [comment]
Can you add this to the device-rule creation modal as well please?

**Comment by laf** [comment]
Sure, what's mandatory on that one, just Name, pattern, value and and/or?

**Pull request merged**
