### PR TITLE
Added detection of Edge-Core ECS4100

### PR DESCRIPTION
**Pull request by jozefrebjak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

I cant add test data because of edgecos_ecs4100-28t: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from `ipv4_addresses` where `ipv4_address` = 127.1.6.1 limit 1)

I dont know how to solve it. So please add test data for this if you can.

### CODE REVIEW

**Comment by laf** [comment]
Sometimes I hate our test data :)

My run has fixed the initial in the last commit but broken port tests according to travis.

**Comment by PipoCanaja** [comment]
@laf There is something wierd here ... I would suggest to @jozefrebjak to start a new PR out of master, with only those 3 changes (yaml, snmprec and json). I suspect that some file in that PR is not correct one way or the other. I already had this problem once or twice and never got a better explanation unfortunalely.

**Comment by PipoCanaja** [comment]
I did the test. 
@jozefrebjak : if the tests are doing better in my attempt, you could close and reopen you PR out of a clean repository. And if not, I have no clue :D

**Comment by PipoCanaja** [comment]
Better now :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
