### PR TITLE
app: os-updates

### PR DESCRIPTION
**Pull request by crcro**
rewrite of os-updates app using latest librenms functions, thanks to @paulgear and @murrant

### CODE REVIEW

**Comment by laf** [comment]
We're going to be merging a change which removes all files in scripts/agent-local as they belong in  https://github.com/librenms/librenms-agent - please submit that file as a separate pull request there and remove it here.

**Comment by murrant** [comment]
Actually, I just noticed this in an snmpd extend script.  What is preferred @laf, extend or agent?

If it is ok to keep this as extend, I think we should add a new folder in scripts to collect them and probably some documentation too.

**Comment by laf** [comment]
I've no care over which way to be fair. I'm not a big user of the agent.

**Comment by murrant** [comment]
Honestly, agent is a little clunky and I'm not sure of the any advantages over extend.  But, I haven't used extend much.

**Comment by crcro** [comment]
so what should i do? :)

**Comment by murrant** [comment]
I just sent PR #3886, hopefully that will be merged soon.
Then, you'll just need to add some docs in `doc/Extensions/Applications.md`  Or you can add your docs to `doc/Extensions/Agent-Setup.md` now and I'll incorporate them into that PR.

Thanks for working hard on this, I'm really not trying to mess with you :)

**Comment by laf** [comment]
#3886 merged.

**Comment by crcro** [comment]
different PR due to agent/scripts separation and required docs
new PR #3935

**Pull request closed without merging**
