### PR TITLE
VLANs: Ironware workaround for Q-BRIDGE-MIB

### PR DESCRIPTION
**Pull request by avatar4d**
@murrant 

As originally noted in https://github.com/librenms/librenms/pull/14326:

The VLANS tab was populated with incorrect data for my Brocade ICX6450-48P. Specifically, the information coming from Q-BRIDGE-MIB::dot1qVlanCurrentEgressPorts is wrong. It appears to need the data in Q-BRIDGE-MIB::dot1qVlanStaticEgressPorts to be correct. 

This PR modifies q-bridge-mib.inc.php in order to test for ironware version 08.0.30uT313 (which is the last version supported on this device) when polling for vlan data. 

This change fixed the VLANs tab for my switch, but I am not sure if this is an acceptable approach and/or if someone else has a device running this version (or others) that can confirm the issue/fix. The only other thing I can think of would be to compare dot1qVlanCurrentEgressPorts with dot1qVlanStaticEgressPorts and if they differ prefer the latter (possibly again only for version 08.0.30uT313 of the firmware). 

Side note: I'm also having trouble creating testing data in the official docker container. I can create the snmprec in step one, but can't get step two to complete. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by avatar4d** [comment]
This change works to provide the correct data when running Discover from the capture page of the device and discover.php from the CLI. For some reason it reverts to the incorrect data when running rediscover in the device settings. It also reverts on its own periodically, I assume due to an automatic background process being run… I’m just not sure what or how it could possibly get bad data again when this change works when running discover the other two ways.

**Comment by murrant** [comment]
Working inside the docker container can be tricky. You may wish to set up a linux environment for development.

Using the version as detection is the least desirable option.  Preferably, we look carefully at the shape of the data from the first walk.  To decide to walk the other.  Otherwise, walk both and combine them.

**Comment by avatar4d** [comment]
Update: Placed a new ICX7150-12p into operation with the latest firmware that Ruckus recommends and it still returns the wrong vlan info. I don't see how the current code could be right for any ICX switch, unless maybe it was right at some point on a much older release of fastiron.

**Comment by murrant** [comment]
I'm not sure this is still applicable, closing.  Please re-open if approriate.

**Pull request closed without merging**
