### PR TITLE
Add bad_ifoperstatus for filtering interfaces having a status for example 'notPresent'

### PR DESCRIPTION
**Pull request by LEV82**
…mple notPresent

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@LEV82 thanks for your contribution, you need to sign the CLA and check the travis errors

**Comment by LEV82** [comment]
Hello,
I'm in github and programming full zero.
Please tell me where I screwed up.

**Comment by Jellyfrog** [comment]
@LEV82 https://travis-ci.com/librenms/librenms/jobs/270615186  
Since you modified the discovery, the test data is no longer correct, so you need to update it accordingly.

**Comment by LEV82** [comment]
> 
> 
> @LEV82 https://travis-ci.com/librenms/librenms/jobs/270615186
> Since you modified the discovery, the test data is no longer correct, so you need to update it accordingly.

Tell me please how to do this?

**Comment by Jellyfrog** [comment]
> > Since you modified the discovery, the test data is no longer correct, so you need to update it accordingly.
> 
> Tell me please how to do this?

As you can see here; https://travis-ci.com/librenms/librenms/jobs/270615186  
the testdata in `tests/data/3com_4200.json` no longer matches the expected values, since you added support for `ifOperStatus`, the value is no longer null: https://github.com/librenms/librenms/blob/1998b8dd0039ee55edecfd0490a4ee7b57924df9/tests/data/3com_4200.json#L57
So you need to update that file to match the newly discovered values

**Comment by LEV82** [comment]
All done

**Comment by LEV82** [comment]
Hi,
Is there any hope that my pool request will be approved?

**Comment by SourceDoctor** [comment]
@kkrumm1 @PipoCanaja 
seems this PR crashes travis tests ...
am i right?

**Comment by kkrumm1** [comment]
Yeah I don’t understand why though

**Comment by SourceDoctor** [comment]
that's an example of Travis Result on my PR

in this PR Testdata got changed ...

`OS arubaos: Discovered ports data does not match that found in tests/data/arubaos.json
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
             'ifConnectorPresent' => null
             'ifPromiscuousMode' => null
             'ifHighSpeed' => null
-            'ifOperStatus' => null
+            'ifOperStatus' => 'down'`

**Comment by SourceDoctor** [comment]
and this PR has change for example in tests/aruba.json

```
-                   "ifOperStatus": null,
+                   "ifOperStatus": "up",

**Comment by SourceDoctor** [comment]
Travis expects null, but null was changed ;-)

**Comment by LEV82** [comment]
Hi, To pass the travis test, I had to update the files /tests/data/*.json 24 days ago. During these days a lot of devices and *.jsion files were added / changed without taking into account my PR. It is necessary to update the files of devices that do not pass the travis test

**Comment by SourceDoctor** [comment]
@LEV82 
could you update the json files so Travis is running successfully again, please?

**Comment by LEV82** [comment]
I can do this, but my request will need to be accepted quickly, before accepting requests for adding new devices

**Comment by SourceDoctor** [comment]
@LEV82 
i think this should be no problem for @kkrumm1  or another maintainer, if your PR is running travis successfully

**Comment by kkrumm1** [comment]
Yes it shouldn’t be an issue to get it pushed through :) thank you guys 

> On Jan 24, 2020, at 5:50 PM, SourceDoctor <notifications@github.com> wrote:
> 
> ﻿
> @LEV82
> i think this should be no problem for @kkrumm1 or another maintainer, if your PR is running travis successfully
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 










CONFIDENTIALITY NOTICE: This email & attached documents may 
contain confidential information. All information is intended only for the 
use of the named recipient. If you are not the named recipient, you are not 
authorized to read, disclose, copy, distribute or take any action in 
reliance on the information and any action other than immediate delivery to 
the named recipient is strictly prohibited. If you have received this email 
in error, do not read the information and please immediately notify sender 
by telephone to arrange for a return of the original documents. If you are 
the named recipient you are not authorized to reveal any of this 
information to any other unauthorized person. If you did not receive all 
pages listed or if pages are not legible, please immediately notify sender 
by phone.

**Comment by LEV82** [comment]
Оk, now do it

**Comment by LEV82** [comment]
Done, local tests pass.
https://github.com/librenms/librenms/pull/11067

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
