### PR TITLE
feature: Added script to generate config for new OS

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Code is shite but for now, it's helping add new OS'

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7161)

### CODE REVIEW

**Comment by sfini** [comment]
@laf
I'm working in support for radware/apsoluteos ( defense pro hw ).... If you want next week i can test the script with this os.

Simone

**Comment by laf** [comment]
@sfini Go for it :)

**Comment by laf** [comment]
Merging this in, I have a fair few new devices to add and this just simplifies things.

**Comment by sfini** [comment]
@laf  Tested for ApsoluteOs and it work very well...

**Comment by laf** [comment]
> work very well...

very well is an overstatement but thanks for testing :)

**Pull request merged**
