### PR TITLE
CiscoSB: Skip notPresent ports from state sensors

### PR DESCRIPTION
**Pull request by Rosiak**
Cisco SB SG350X series presents all possible ports, including non-existent stack ports.
This results in a lot of unnecessary storage usage.

This is a simple fix to skip those ports from the state sensor discovery.

It's been a while, please let me know if there is anything missing.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @Rosiak 
Could you run the ./save-test-data.php on the snmpsim collected data ? Travis is running right now, we'll see if other test-data will need to be updated. 
Bye

**Comment by Rosiak** [comment]
Yup, will fix that!

**Comment by murrant** [comment]
I'll grab that, but it is best to include it :)

**Comment by Rosiak** [comment]
Thx Tony!

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
