### PR TITLE
Add csv of groups a device belongs to in alert object

### PR DESCRIPTION
**Pull request by VirTechSystems**
Query for the groups being alerted on and build a csv string of groups a device belongs to and add it to the alert object for use in the transports.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @VirTechSystems 
Why would you provide a CSV instead of the data structured in a proper way ? We have loop mecanisms availiable in the templates, so serialisation (to any format, CSV being one) can always be done, if needed, in the template itself.

**Comment by VirTechSystems** [comment]
I thought a CSV would be the easiest format to use.  What other way should it be structured?

**Comment by PipoCanaja** [comment]
I would just provide the array (like the faults array). Then you can loop on the group array to retrieve it and display it.

**Comment by laf** [comment]
Yes definitely as another array within the existing `$obj` array.

**Comment by VirTechSystems** [comment]
Ok.  I'll rework it and do some testing.

**Comment by SourceDoctor** [comment]
@VirTechSystems 
something new here?

**Comment by murrant** [comment]
You don't need this, you can just load the groups in your alert template.

`{{ Device::find($alert->device_id)->groups()->pluck('name')->implode(', ') }}`

Just rolls right of the tongue.

**Pull request closed without merging**
