### PR TITLE
Send default mail when no email destinations found

### PR DESCRIPTION
**Pull request by towster**
When no email destinations are found it simply would log that there were no email destinations.
This change will cause it to send an email to the default mail address if there are no email destinations set.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by towster** [comment]
It does change the "To:" to use the pretty name of "Default". Like this:
`To: Default <librenms@work.com>`
Is that sufficient?

**Comment by laf** [comment]
This is a major change to the way alerts work - this should be it's own toggle switch "Fall back to default contact if no other contacts can be found"

**Comment by laf** [comment]
Thanks @towster - It needs also to be in the webui:

`html/pages/settings/alerting.inc.php`

+ a config entry adding to db, see:

`sql-schema/166.sql` as an example

**Comment by murrant** [comment]
trigger-ci

**Comment by murrant** [comment]
trigger ci

**Comment by laf** [comment]
I've just updated Default to NOC to match other areas - tested though and works fine.

**Pull request merged**
