### PR TITLE
fix issue with new firmware requiring new MIB. Iss#10449

### PR DESCRIPTION
**Pull request by MajesticFalcon**
The new Vertiv Geist Watchdog devices come with firmware version 3.4.0 which requires a new MIB "VERTIV-BB-MIB". I don't have the ability to run snmpsim in my environment, however, since I installed these modules and needed support, I figured I would send the changes upstream. I noticed there was a stale issue regarding the sensor support and this PR happens to address their concerns.

Additionally, I added two dry contact sensors. This is what I am using, but it also gives the user a starting point for adding or changing according to their environment. The documentation around this part isn't very clear, I think this will help future users of geist.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @MajesticFalcon 
Unfortunately, changing the file as you currently does most probably kills the support for devices with the old MIBs. A better option would be: 
- to find out if you have old or new firmware and discover accordingly. 
- add support for both the old and new firmware side to side (if possible) meaning you need to support all sensors of all MIB variants

**Comment by MajesticFalcon** [comment]
> Hi @MajesticFalcon Unfortunately, changing the file as you currently does most probably kills the support for devices with the old MIBs. A better option would be:
> 
> * to find out if you have old or new firmware and discover accordingly.
> * add support for both the old and new firmware side to side (if possible) meaning you need to support all sensors of all MIB variants

So I should discover the os based on the existing parameters + firmware version. If the firmware version is greater than or equal to 3.4 (the latest), then use a different OS. Maybe the os is called geist-watchdog3.4?

**Comment by PipoCanaja** [comment]
> > Hi @MajesticFalcon Unfortunately, changing the file as you currently does most probably kills the support for devices with the old MIBs. A better option would be:
> > 
> > * to find out if you have old or new firmware and discover accordingly.
> > * add support for both the old and new firmware side to side (if possible) meaning you need to support all sensors of all MIB variants
> 
> So I should discover the os based on the existing parameters + firmware version. If the firmware version is greater than or equal to 3.4 (the latest), then use a different OS. Maybe the os is called geist-watchdog3.4?

That's option one indeed. If you can make it with that one, this is probably the cleanest of the 2 variants :) To make it work, you need to exclude from the existing OS any firmware > 3.4, and in the new one accept only if firmware >= 3.4. Cause the OS selecting code should have only one solution.

**Comment by murrant** [comment]
It is probably appropriate to define both sets of sensors and let discovery figure out which ones are valid.

**Comment by MajesticFalcon** [comment]
Since these changes have not been pulled into master, what is the best way to get the daily_update script to skip trying to update these files?

I get the following:
WARN: Your local git contains modified files, this could prevent automatic updates.

includes/definitions/discovery/geist-watchdog.yaml
includes/definitions/geist-watchdog.yaml
includes/discovery/sensors/temperature/geist-watchdog.inc.php
includes/polling/sensors/pre-cache/geist-watchdog.inc.php
includes/polling/sensors/temperature/geist-watchdog.inc.php

**Comment by PipoCanaja** [comment]
> Since these changes have not been pulled into master, what is the best way to get the daily_update script to skip trying to update these files?
> 
> I get the following: WARN: Your local git contains modified files, this could prevent automatic updates.
> 
> includes/definitions/discovery/geist-watchdog.yaml includes/definitions/geist-watchdog.yaml includes/discovery/sensors/temperature/geist-watchdog.inc.php includes/polling/sensors/pre-cache/geist-watchdog.inc.php includes/polling/sensors/temperature/geist-watchdog.inc.php

Unfortunately, not. Either you submit a pull request that does not break the OS for everybody else, or you break you own install which means you may suffer issues with later updates on the same files.

**Comment by murrant** [comment]
The daily script will never overwrite your local changes.  You can safely ignore the warning until this gets merged.

**Comment by murrant** [comment]
@MajesticFalcon I was just going to evaluate your changes, but `VERTIV-BB-MIB` is missing from this PR.

**Comment by MajesticFalcon** [comment]
> This is why we encourage you and help you getting it "mergeable" :)

I just don't quite have the time to devote to wrapping this up at this time.

**Comment by MajesticFalcon** [comment]
> @MajesticFalcon I was just going to evaluate your changes, but `VERTIV-BB-MIB` is missing from this PR.

[mib (1) 2.zip](https://github.com/librenms/librenms/files/9686332/mib.1.2.zip)

Here is the MIB file

**Pull request closed without merging**
