### PR TITLE
Service templates -  fix rules

### PR DESCRIPTION
**Pull request by bofh80**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by bofh80** [comment]
currently, this fixes 'static' selection for both.

When i select dynamic, and hit save, the page refreshes, tells me that 'drules' (for instance) is required when dynamic is selected and it has blanked the rules i put in .

Maybe my fix is a misunderstanding :D

**Comment by Jellyfrog** [comment]
You could ask in the forum if someone wants to test it

**Comment by Jellyfrog** [comment]
Also. Rebase your branch on master to fix the tests

**Review by murrant — APPROVED** [review]
Fix looks correct.  Did not test :)

**Comment by Jellyfrog** [comment]
Seems this fixed it!

**Pull request merged**
