### PR TITLE
Add support for Radius auth

### LINKED ISSUE #1295: Add RADIUS authentication method
Currently LibreNMS supports MySQL & LDAP based authentication. If RADIUS support were to be added that would make my life easier in some scenario's.

### PR DESCRIPTION
**Pull request by laf**
Fix #1295 

So this adds Radius support as an authentication backend. I've only been able to test this using FreeRadius.

This will add users into mysql when someone successfully authenticates as level 1 user. ./adduser.php still works as normal so you can add admins in via the cli then when they auth via radius it will match up.

daily.sh / daily.php have also been updated to purge users that haven't logged in for X. We can extend this out further to other backends if we need to.

### CODE REVIEW

**Comment by Rosiak** [comment]
Perhaps @job can help on testing this one?

**Comment by laf** [comment]
Already posted in the issue.

**Comment by laf** [comment]
Adds support for specifying what the default user level should be when auto creating users.

**Comment by laf** [comment]
bump. Been tested by job.

**Comment by job** [comment]
merge it. looks good to me

**Pull request merged**
