### PR TITLE
Update os icon the handling. Add title to the os image

### PR DESCRIPTION
**Pull request by murrant**
Say goodbye to ?

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by murrant** [comment]
image

**Comment by murrant** [comment]
image

**Comment by laf** [comment]
Still says aws to me :(

**Comment by murrant** [comment]
Open to suggestions.  While checking the code allowed generic.svg, I found a lot of errors...  I can remove the icon and PR the fixes for now.

**Comment by laf** [comment]
Maybe it is just worth swapping to the LibreNMS icon?

**Comment by murrant** [comment]
Do you like the desaturated/faded colors?

**Comment by laf** [comment]
Don't go off what I think, you've got two thumbs up so should go with the majority :)

**Comment by murrant** [comment]
I'll try the librenms icon and see, I'd like to get a lot more feedback than 3 people :grinning:

**Comment by InsaneSplash** [comment]
I think both are great, my only concern is will someone think that the
librenms icon  next to a system is a librenms host?

Anything is better than the current one he he

**Comment by murrant** [comment]
Removed the icon for now.

**Pull request merged**
