### PR TITLE
Updated mysql DATE_FORMAT() and php date() to use $config variables

### PR DESCRIPTION
**Pull request by laf**
Some web ui elements have been kept as is otherwise we would end up with a lot of config options.

This should fix all user displayed information though pretty  much.

### CODE REVIEW

**Comment by laf** [comment]
bump

**Comment by f0o** [comment]
Is scrut dead?

**Comment by laf** [comment]
Scrut has issues occasionally but I remember reading maybe last week they had an issue which could be why this pr hasn't got scrut on it.

**Comment by f0o** [comment]
testing through all files gonna take a while :/

**Comment by laf** [comment]
Just ask @paulgear to kick off a scrut run.

**Comment by laf** [comment]
Pushed an update to kick off a scrut run.

**Comment by laf** [comment]
Bump

**Pull request merged**
