### PR TITLE
Display current process-list from unix-agent

### PR DESCRIPTION
**Pull request by f0o**
#405
Added:
	039.sql: create a new table `processes`
	processes.inc.php: show all processes from given device including sort-options

Changed:
	check_mk_agent: added PID to the output of ps
	unix-agent.inc.php: insert all processes reported by check_mk_agent
	device.inc.php: added tab with link to process-list

Rebased and Squashed version

### CODE REVIEW

**Comment by laf** [comment]
These are just comments btw rather than changes that are needed :)

The check_mk_agent is currently the standard one provided by check_mk, with it being changed it just means we have to track that change on future updates which I don't expect to be a lot. Do we need to store the pid seeing as this could change considerably straight after a poll?

The other one is on the sql file, should we be specifying a drop tablename at the start. My only concern with that would be for people who might have custom installs where they've developed LibreNMS out themselves and added other tables and features. It's probably never going to happen but should we look at not putting a drop in unless we need it?

Like I said, merely comments and I'd like to hear people's thoughts on these.

**Comment by f0o** [comment]
First of all it's not the standard check_mk_agent. The standard one already includes pids. see line 199 http://git.mathias-kettner.de/git/?p=check_mk.git;a=blob;f=agents/check_mk_agent.linux;h=165170e137c1bf85db2706de631ce44d7903b711;hb=HEAD

I'd be happy to swap the check_mk_agent with upstream version and modify the unix-agent.inc.php to support the slight format changes introduced by upstream.

Regarding the changes of PID, that is true and as other monitors (xymon, nagios, check_mk's own brew) I'm bound to dropping all related records and insert the ps-state again. Adding existence checks here would mean more overhead than just a rewrite.

I agree that a drop table statement is not nice.
However in named case where a user has custom tables, my code may cause all sorts of oddities within that table or not work at all if cols are named differently. The update-procedure wouldnt care about the erroed create statement and schema will be incremented. This is potentially hard to debug and support in case named user complains about non-working or malformated process-list display.

I generally dont mind removing the drop statement here and add a 2nd PR to update check_mk_agent to upstream version.

**Comment by laf** [comment]
Thanks @f0o. I didn't check the git repo, just gone off the latest available tgz release on the main website. Looks like they release more recent versions on github though. Unless that single line is the only change it would be nice and worthwhile giving the latest git version a test and uploading that to this PR but if that's a chunk of work just I'd say we could just merge with the update you've proposed.

@paulgear What do you think about the drop table name statements, leave or keep? I see benefits / issues with both ways so it's probably just worthwhile standardising one way or the other.

**Comment by f0o** [comment]
I'll split this PR into two PRs:
1.  Check_MK update + php-parse adjustments if required.
2.  Add processlist

Re: SQL drop statement - I'll remove it but as @laf said, a standard would be nice :)

**Pull request closed without merging**
