### PR TITLE
Clarified validate is run as root/fixed hyperlinks

### PR DESCRIPTION
**Pull request by joeywas**
Clarified that the validate.php file is run as root and fixed the reference hyperlinks so they are hyperlinked

### CODE REVIEW

**Comment by Rosiak** [comment]
Can you fix this in the other installation docs aswell(Ubuntu)?

**Comment by joeywas** [comment]
Fixed in the Ubuntu install documents

**Comment by laf** [comment]
:( This needs a rebase because of another PR.

I'm not sure how you'd resolve that on github.com so if you go back to the AUTHORS.md file, copy everything from https://raw.githubusercontent.com/librenms/librenms/master/AUTHORS.md into it and re-add your name it should be good.

**Comment by laf** [comment]
It's still not worked :(

I think you'll need to do this via the command line :(

**Comment by joeywas** [comment]
I'm going to close this pull request and set up my environment appropriately (http://docs.librenms.org/Developing/Using-Git/) then resubmit the pull request.

**Pull request closed without merging**
