### PR TITLE
Equallogic fix typo on os name in the storage module

### LINKED ISSUE #13578: storage module not call for Dell Equallogic device
### The problem

When I try to discover a Dell Equllogic diskarray, I can't get my active storage. Te discovery module is not used.

### Output of ./validate.php

```txt
librenms@{{HOST-SATINIZED}}:/{{PATH-SATINIZED}}/librenms$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP       | 7.3.31-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.31-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[FAIL]  APP_KEY does not match key used to encrypt data. APP_KEY must be the same on all nodes.
	[FIX]: 
	If you rotated APP_KEY, run lnms key:rotate to resolve.
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2021_11_12_123037_change_cpwVcID_to_unsignedInteger). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[FAIL]  Database: incorrect column (notifications/datetime)
[FAIL]  Database: incorrect column (pseudowires/cpwVcID)
[FAIL]  Database: incorrect column (users/created_at)
[FAIL]  We have detected that your database schema may be wrong
	[FIX]: 
	Run the following SQL statements to fix it
	SQL Statements:
	 SET TIME_ZONE='+00:00';
	 ALTER TABLE `notifications` CHANGE `datetime` `datetime` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ;
	 ALTER TABLE `pseudowires` CHANGE `cpwVcID` `cpwVcID` int NOT NULL ;
	 ALTER TABLE `users` CHANGE `created_at` `created_at` timestamp NOT NULL DEFAULT '1970-01-02 00:00:01' ;
[INFO]  Detected Python Wrapper
[OK]    Connection to memcached is ok
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 includes/definitions/equallogic.yaml
	 includes/discovery/storage/eql-storage.inc.php
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
	[FIX]: 
	sudo chown -R librenms:librenms /{{PATH-SATINIZED}}/librenms
	sudo setfacl -d -m g::rwx /{{PATH-SATINIZED}}/librenms/rrd /{{PATH-SATINIZED}}/librenms/logs /{{PATH-SATINIZED}}/librenms/bootstrap/cache/ /{{PATH-SATINIZED}}/librenms/storage/
	sudo chmod -R ug=rwX /{{PATH-SATINIZED}}/librenms/rrd /{{PATH-SATINIZED}}/librenms/logs /{{PATH-SATINIZED}}/librenms/bootstrap/cache/ /{{PATH-SATINIZED}}/librenms/storage/
	Files:
	 /{{PATH-SATINIZED}}/librenms/includes/snmp.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/applications/ntp-server.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/ospf.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/pbn.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/acsw.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/sgos.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/ptp500.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/ciscowap.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/speedtouch.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/jwos.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/samsungprinter.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/elg-ipecs-es.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/vyatta.inc.php
	 /{{PATH-SATINIZED}}/librenms/includes/polling/os/ruckuswireless.inc.php
	  and 313 more...
```

### What was the last working version of LibreNMS?

21.11.0

### Device info

Equallogic PS4110X

### Discovery output

```txt
librenms@{{HOST-SATINIZED}}:/{{PATH-SATINIZED}}/librenms$ ./discovery.php -d -v -m storage -h foo.bar.fr
LibreNMS Discovery
SQL[select `migration` from `migrations` order by `id` desc limit 1 [] 14.67ms] 
  
SQL[select count(*) as aggregate from `migrations` limit 1 [] 14.1ms] 
  
SQL[select version() [] 14.31ms] 
  
===================================
Version info:
Commit SHA: 6b41c29f5f7a8cec104c17737df0a6e50755f66c
Commit Date: 1636736619
DB Schema: 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP: 7.3.31-1~deb10u1
MySQL: 10.3.31-MariaDB-0+deb10u1
RRDTool: 1.7.1
SNMP: NET-SNMP 5.7.3
==================================DEBUG!
Updating os_def.cache  
Override discovery modules: storage  
SQL[SELECT * FROM `devices` WHERE disabled = 0 AND `hostname` LIKE 'foo.bar.fr' AND poller_group IN(1) ORDER BY device_id DESC [] 16.13ms] 
  
SQL[select * from `devices` where `device_id` = ? limit 1 [473] 14.98ms] 
  
SQL[select * from `devices_attribs` where `devices_attribs`.`device_id` = ? and `devices_attribs`.`device_id` is not null [473] 14.51ms] 
  
foo.bar.fr 473 equallogic [FPING] '/usr/bin/fping' '-e' '-q' '-c' '3' '-p' '500' '-t' '500' '-O' '0' 'foo.bar.fr'
  
response: xmt/rcv/%loss = 3/3/0%, min/avg/max = 0.28/0.32/0.39  
SNMP['/usr/bin/snmpget' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/dell' '-v2c' '-c' 'my_community_snmp' '-OQXUte' 'udp:foo.bar.fr:161' 'SNMPv2-MIB::sysObjectID.0']  
SNMPv2-MIB::sysObjectID.0 = SNMPv2-SMI::enterprises.12740.17.1
  
  
Modules status: Global+  
OS  
Device  

#### Load disco module core ####
Attempting to initialize OS: equallogic  
OS initialized as Generic  
SNMP['/usr/bin/snmpget' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/dell' '-v2c' '-c' 'my_community_snmp' '-OQXUte' '-On' 'udp:foo.bar.fr:161' 'SNMPv2-MIB::sysObjectID.0' 'SNMPv2-MIB::sysDescr.0' 'SNMPv2-MIB::sysName.0']  
.1.3.6.1.2.1.1.2.0 = .1.3.6.1.4.1.12740.17.1
.1.3.6.1.2.1.1.1.0 = 
.1.3.6.1.2.1.1.5.0 = foo.bar.fr
  
  
|  | .1.3.6.1.4.1.12740.17.1 | 
  
OS: Dell EqualLogic (equallogic)

Attempting to initialize OS: equallogic  
OS initialized as Generic  

>> Runtime for discovery module 'core': 0.0630 seconds with 257456 bytes
>> SNMP: [1/0.05s] MySQL: [0/0.00s] RRD: [0/0.00s]
#### Unload disco module core ####

Modules status: Global+  
OS  
Device  

#### Load disco module storage ####
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'my_community_snmp' '-OQUs' '-m' 'IBM-AIX-MIB' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell' 'udp:foo.bar.fr:161' 'aixFsTableEntry']
Exitcode: 1  
MIB search path: /{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell
Cannot find module (IBM-AIX-MIB): At line 1 in (none)
aixFsTableEntry: Unknown Object Identifier (Sub-id not found: (top) -> aixFsTableEntry)  
  
MIB search path: /{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell
Cannot find module (IBM-AIX-MIB): At line 1 in (none)
aixFsTableEntry: Unknown Object Identifier (Sub-id not found: (top) -> aixFsTableEntry)  
aix_filesystem : SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'my_community_snmp' '-OQUs' '-m' 'DATA-DOMAIN-MIB' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell:/{{PATH-SATINIZED}}/librenms/mibs/datadomain' 'udp:foo.bar.fr:161' 'fileSystemSpaceTable']
fileSystemSpaceTable = No Such Object available on this agent at this OID  
  
Invalid snmp_walk() data = fileSystemSpaceTable = No Such Object available on this agent at this OID  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'my_community_snmp' '-OQUs' '-m' 'FREENAS-MIB' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell' 'udp:foo.bar.fr:161' 'datasetTable']
Exitcode: 1  
MIB search path: /{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell
Cannot find module (FREENAS-MIB): At line 1 in (none)
datasetTable: Unknown Object Identifier (Sub-id not found: (top) -> datasetTable)  
  
MIB search path: /{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell
Cannot find module (FREENAS-MIB): At line 1 in (none)
datasetTable: Unknown Object Identifier (Sub-id not found: (top) -> datasetTable)  
SQL[SELECT `storage_descr` FROM `storage` WHERE `device_id`  = '473' AND `storage_type` != 'dataset' [] 14.84ms] 
  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'my_community_snmp' '-OQUs' '-m' 'FREENAS-MIB' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell' 'udp:foo.bar.fr:161' 'zpoolTable']
Exitcode: 1  
MIB search path: /{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell
Cannot find module (FREENAS-MIB): At line 1 in (none)
zpoolTable: Unknown Object Identifier (Sub-id not found: (top) -> zpoolTable)  
  
MIB search path: /{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell
Cannot find module (FREENAS-MIB): At line 1 in (none)
zpoolTable: Unknown Object Identifier (Sub-id not found: (top) -> zpoolTable)  
SQL[SELECT `storage_descr` FROM `storage` WHERE `device_id`  = '473' AND `storage_type` != 'zpool' [] 14.65ms] 
  
communityStringIndexing  
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'my_community_snmp' '-OQUsetX' '-m' 'HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell' 'udp:foo.bar.fr:161' 'hrStorageTable']
hrStorageTable = No Such Object available on this agent at this OID  
  
hrStorage : SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'my_community_snmp' '-OQUs' '-m' 'UCD-SNMP-MIB' '-M' '/{{PATH-SATINIZED}}/librenms/mibs:/{{PATH-SATINIZED}}/librenms/mibs/equallogic:/{{PATH-SATINIZED}}/librenms/mibs/dell' 'udp:foo.bar.fr:161' 'dskTable']
dskTable = No Such Object available on this agent at this OID  
  
Invalid snmp_walk() data = dskTable = No Such Object available on this agent at this OID  
SQL[SELECT `storage_descr` FROM `storage` WHERE `device_id`  = '473' AND `storage_type` != 'dsk' [] 14.68ms] 
  
  
SQL[SELECT * FROM `storage` WHERE `device_id`  = '473' [] 14.42ms] 
  


>> Runtime for discovery module 'storage': 0.3800 seconds with 16808 bytes
>> SNMP: [5/0.26s] MySQL: [4/0.59s] RRD: [0/0.00s]
#### Unload disco module storage ####

SQL[UPDATE `devices` set `last_discovered`=NOW(),`last_discovered_timetaken`=? WHERE `device_id` = ? [1.546,473] 14.33ms] 
  
Discovered in 1.546 seconds

./discovery.php foo.bar.fr 2021-11-29 15:48:58 - 1 devices discovered in 2.484 secs  

SNMP [7/0.36s]: Snmpget[2/0.10s] Snmpwalk[5/0.26s]
SQL [14/2.77s]: Select[13/2.62s] Update[1/0.14s]
RRD [0/0.00s]:
librenms@{{HOST-SATINIZED}}:/{{PATH-SATINIZED}}/librenms$
```

### Poller output

```txt
n/a
```

### PR DESCRIPTION
**Pull request by iopsthecloud**
fixes #13578

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Fun, this has been broken since 2018 :)

**Comment by murrant** [comment]
@iopsthecloud It would be really great if you could add test data for this.  I plan to re-write the storage module soonish and that will prevent me from breaking anything :)

**Comment by laf** [comment]
@iopsthecloud Any chance you can get the test data as asked?

**Review by laf — APPROVED** [review]
LGTM. Ideally we could do with test data but we should fix the bug at least by merging.

@murrant?

**Comment by murrant** [comment]
Yeah, that would be fine, just less than ideal.

**Pull request merged**
