### PR TITLE
Add functionality to use snmp-scan.py to addto specific poller group

### PR DESCRIPTION
**Pull request by nathanshiaulam**
Please give a short description what your pull request is for

I'm adding functionality to specify what poller group snmp-scan.py will add devices to. If a user calls `snmp-scan.py` with `-g {POLLER_GROUP}`, all devices will be added to the specified poller group. Otherwise, all devices will be added to the first poller group specified under `distributed_poller_group`, and 0 of neither are provided.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Lint check failed... other than that looks ok.

**Comment by daichaoyang** [comment]
Got it



发自我的iPhone


------------------ Original ------------------

**Comment by nathanshiaulam** [comment]
Sounds good. Not sure why the build is breaking- looked at the stack trace and doesn't seem related, but I might've missed something

**Comment by nathanshiaulam** [comment]
@murrant any clue on how to resolve the lint failure? been poking around but still not sure how it's related/how to resolve

**Comment by murrant** [comment]
The testing error seems unrelated :(

But when I tested I got this:
```
./snmp-scan.py 
Traceback (most recent call last):
  File "./snmp-scan.py", line 178, in <module>
    POLLER_GROUP = args.group or CONFIG.get('distributed_poller_group').split(',')[0]
AttributeError: 'int' object has no attribute 'split'
```

**Comment by nathanshiaulam** [comment]
That's weird, it works just fine for me. Did you set `distributed_poller_group` in your config.php as a string or an int?

**Comment by nathanshiaulam** [comment]
Double checked/confirmed that it does work when `distributed_poller_group` is set to a string/fails if it's an int.

@murrant should I cast the value to a string in case someone inputs an int? Not sure if that's an edge-case I should handle since the value should be a string

**Comment by nathanshiaulam** [comment]
@murrant just casted the input to a string in case the user inputs an int

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
