### PR TITLE
Center the graph displayed.

### PR DESCRIPTION
**Pull request by arjitc**

### CODE REVIEW

**Comment by arjitc** [comment]
Screenshot: http://i.imgur.com/lwHCJcZ.png

**Comment by laf** [comment]
As this is just a visual change and down to preference, let's see what others say on it.

I'm not fussed either way, happy to :+1: it.

**Comment by Calvario** [comment]
I like it.

**Comment by masonke** [comment]
Looks nice

**Comment by f0o** [comment]
:+1:

**Pull request merged**
