### PR TITLE
Raise version size in db to 70 char 

### PR DESCRIPTION
**Pull request by xbeaudouin**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Some version numbers are sometimes more that 64 chars (for example : zimbra-cluebringer 2.1.0.0.cf484f1b93cf9965886cc89d33bdeee9c26426cb-1zimbra8.7b1.14.04).

### CODE REVIEW

**Comment by laf** [comment]
We can go up to 255 chars for varchar without using additional space in mysql so I propose we increase this to 120 or 160 to cover us further. @librenms/reviewers

**Comment by laf** [comment]
@librenms/reviewers thoughts on upping this to something like 120 - 160?

**Comment by paulgear** [comment]
If we can go up to 255 chars for varchar without using additional space in mysql, I can't see any reason we wouldn't make it 255.

**Comment by f0o** [comment]
:+1: to 255

**Comment by laf** [comment]
@xbeaudouin bump

**Comment by xbeaudouin** [comment]
Just updated :D

**Pull request merged**
