### PR TITLE
Updated test data for arubaos, fs-switch, ifotec, lcos, siklu and trendnet, to pass Travis tests

### PR DESCRIPTION
**Pull request by LEV82**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
Waiting for Travis to finish can’t merge unit finish

**Comment by LEV82** [comment]
Strange, in the details of the travis test everything is fine, but the general state is 'created' and 'queued'

**Comment by kkrumm1** [comment]
I have seen this fixed pushing a dummy comment

**Comment by LEV82** [comment]
> 
> 
> I have seen this fixed pushing a dummy comment

I'm sorry, I didn’t understand what you mean?

**Comment by SourceDoctor** [comment]
@LEV82 
@kkrumm1 means to do some "changes" like adding a comment or so, and push stuff again.

Travis seems to hang sometimes, and a "restart" fixes it

**Comment by LEV82** [comment]
Sorry, but I'm new to github, tell me what should I do? And most importantly, how to do it right.

**Comment by LEV82** [comment]
done

**Comment by kkrumm1** [comment]
LGTM

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
