### PR TITLE
Clean up syslog integration

### PR DESCRIPTION
**Pull request by florianbeer**
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Cleans up syslog integration

### CODE REVIEW

**Comment by florianbeer** [comment]
I know re-writing tests is very controversial, but now the the program is just `CRON` which I prefer to the former `PAM_UNIX(CRON:SESSION)`, so I think it's ok to alter the test.

**Comment by laf** [comment]
Isn't `$entry['program']` always empty at that point anyway so I don't see what difference this makes.

As for the tests, unless they needed to be updated for this PR to work then they should be changed in a separate PR. But again what's the reason to change them?

**Comment by murrant** [comment]
Isn't the program pam?

**Comment by Ultra2D** [comment]
I don't use LibreNMS for syslog of Linux servers, so I don't really have a say in this, but is it wise to change the default behavior if there is no real error in it? Isn't this more of a personal preference?

**Comment by florianbeer** [comment]
@laf No it is not always empty, we are in the "linux" branch of `if (in_array($os, array('ios', 'iosxe', 'catos')))`, so this is for Linux servers that haven't figured out the program name properly at that point. So I'm only using `preg_match()` if the program name is empty. Otherwise it can stay the way it is, or be changed out with the facility name by the `elseif` below.

@murrant PAM is a module and not a binary. Cron, sudo etc. are the programs that kick off the action being logged and the original information is still visible in the message. So nothings lost, but the program dropdown and column become a lot tidier.

@Ultra2D Then I would urge you to test it with and without this patch. I have this change running almost for half a year now with multiple different devices monitored by LibreNMS and all of them sending their syslog to the monitoring server.

- Linux Servers (Debian, Ubuntu)
- Ubiquiti Wireless Bridges, Access Points, Switches and Routers
- macOS Computers
- Apple Wireless Routers
- Custom Embedded Linux Radio Streaming Boxes
- Teltonika Industrial LTE Routers

Never did I experience any problem with this change, but without it it will produce wrong/empty program names for syslog messages. That's the whole point of the PR and not personal preference.

**Comment by Ultra2D** [comment]
Well, I do not monitor any of those OSes (except the LibreNMS host itself). Furthermore, this should only affect Linux, as @laf was hinting at.

After another look I seem to understand. The program is already defined in the test (end of the line), but was being changed in the code. This commit will stop that behaviour. In https://github.com/florianbeer/librenms/commit/fb9224d507d88635452470255095e2b11e28daa4 I called it the 'original behaviour', which probably means that it has worked this way since the creation of the LibreNMS fork.

You are changing a test, so you are changing the expected output, which could be considered a (personal) preference, as you yourself actually said in https://github.com/librenms/librenms/pull/5942#issuecomment-280941192 . Anyway, I don't mind either way, just wanted to point it out so someone else could pick up on that, if needed(!). 
For instance, you could say that a longer program description is more informative.

**Comment by laf** [comment]
@florianbeer Actually we aren't in the `if (in_array($os, array('ios', 'iosxe', 'catos'))` we are in the elseif of that. However I see from syslog.php that program is defined there first so if weren't able to split on it originally then we process it here.

I'm ok with that but not sure I'm ok with adjusting the tests in the same PR. Does it fail with the current test units?

**Comment by florianbeer** [comment]
I'd love if somebody could chime in that actually has syslog enabled for Linux devices within LibreNMS. Right now we are just debating about unit tests, which don't reflect the original problem.

I have now just rolled back this change on my server to give you a few examples:

- php-fpm error messages get their pool PID appended to the program name. So it is WWW[19065] instead of PHP or WWW. So this slowly fills up the "program" dropdown with _a lot_ of items.
- Dovecot login messages have the user's email address embedded in the program name, so suddenly I'd have one "program" per mail user, instead of one program "dovecot" which shows all of the IMAP processes' log messages.

Those are just two instances where the "original" way is confusing and over complicated from a user interface standpoint. I want to be able to select one program in the dropdown and see all of it's associated messages from all of my hosts. My PR provides that for Linux systems.

@laf I can split the test changes to a new PR if you want to. If you look at the diffs, you can see exactly what has changed in terms of "program" and "message" output because of my change in `includes/syslog.php`.

**Comment by Ultra2D** [comment]
Did you mention the original problem somewhere before? I might have missed that.

**Comment by florianbeer** [comment]
August 1st, 2016: #3924

**Comment by laf** [comment]
@florianbeer don't take offence that people are asking you questions, you're asking to change the default behavior of something and as such could break people's installs.

You can either wait for someone else to test this which could take a while, or work with us in getting this merged.

So the question again is, does this change not pass the current test units for syslog?

**Comment by Ultra2D** [comment]
@florianbeer thanks for the link, that helps a lot. The issues you have encountered might be prevented, but that list of issues will not be exhaustive. It would indeed be safer to only change the program if absolutely needed, so your change to the code should be merged IMHO.

I would suggest changing the tests in a different way: remove the program from the end of the line to test the regex, and add a couple of lines that lead to the issues you encountered before changing the code.

**Comment by florianbeer** [comment]
Sorry, I didn't want to come across offended or angry. I'll use the fact that it is Monday as an excuse, is that acceptable?

Yes, the original unit tests fail, because they expect different "program" and "message" values.
So before my change it had `PAM_UNIX(CRON:SESSION)` or `PAM_KRB5(SSHD:AUTH)` as "program". After my change it is `CRON` and `SSH` in those two instances and the rest of the information (e.g. `pam_unix(cron:session)` in the first example), will be pre-pended to the "message" value so nothing is lost.

That's why I changed the tests on these 4 lines:
https://github.com/librenms/librenms/pull/5942/files#diff-f3b2bc058140c489246314235be9f988L159
https://github.com/librenms/librenms/pull/5942/files#diff-f3b2bc058140c489246314235be9f988L163
https://github.com/librenms/librenms/pull/5942/files#diff-f3b2bc058140c489246314235be9f988L167
https://github.com/librenms/librenms/pull/5942/files#diff-f3b2bc058140c489246314235be9f988L171

As stated above those unit tests might not reflect the real problem as they are fairly "fixed" values. Where it gets confusing is when "program" gets set to a value that includes "dynamic" information, like email addresses or process id's, because in those instances it fills up the "program" dropdown with a multitude of very similar items over time, that really should all be grouped together under the process name.

**Comment by florianbeer** [comment]
@Ultra2D I'm not exactly sure how you want me to change the tests, I'm afraid. Could you give me an example? I'd be happe to rewrite and/or add test cases that more closely reflect the encountered problem.

**Comment by laf** [comment]
@florianbeer thanks for the info, we just want to be sure we don't break stuff - well as sure as can be.. I'm happy to approve this, not being a syslog user I can't test but I do recall when I last did my programs was full of crud.

Thanks for contributing

**Comment by Ultra2D** [comment]
@florianbeer I mean something like https://github.com/Ultra2D/librenms/commit/263ce2d94c938bda3983c558bcb8f8bfe4ceb3ce . 
Four lines for PAM under "No program" might be overkill though, since they are no longer based on real world examples. One test with ```()``` and another with ```[]``` should probably be good enough.

**Comment by florianbeer** [comment]
@Ultra2D Thanks, I'll take a closer look at it tonight and try to come up with 2 or 3 meaningful tests for my change. But the 4 tests I already altered would have to be deleted or changed still, because at the moment they all fail.

**Comment by nerdalertdk** [comment]
Hi

I use the Syslog feature with a lot of devices
You can se my Program dropdown below, let me know if you want more info

The BACKUP.SH.* is ESXI doing it own wierd thing

```
%%10IFNET/3/LINK_UPDOWN(L)
%%10IFNET/4/INTERFACE
%%10LLDP/6/LLDP_CREATE_NEIGHBOR(
%%10LLDP/6/LLDP_DELETE_NEIGHBOR(
( CD / && RUN-PARTS --REPORT /ET
* : OFFSET
------
/USR/SBIN/CRON
BACKUP.SH.1000883
BACKUP.SH.1001913
BACKUP.SH.1002953
BACKUP.SH.1004043
BACKUP.SH.1005077
BACKUP.SH.1006198
BACKUP.SH.1007692
BACKUP.SH.1008729
BACKUP.SH.1009763
BACKUP.SH.1010799
BACKUP.SH.1011838
BACKUP.SH.1012871
BACKUP.SH.1013902
BACKUP.SH.1014930
BACKUP.SH.1016111
BACKUP.SH.1017362
BACKUP.SH.1018522
BACKUP.SH.1019598
BACKUP.SH.1020640
BACKUP.SH.1021675
BACKUP.SH.1022711
BACKUP.SH.1023745
BACKUP.SH.1024780
BACKUP.SH.1025816
BACKUP.SH.1026853
BACKUP.SH.1027886
BACKUP.SH.1028922
BACKUP.SH.1029959
BACKUP.SH.1030988
BACKUP.SH.1032101
BACKUP.SH.1033527
BACKUP.SH.1034570
BACKUP.SH.1035602
BACKUP.SH.1036693
BACKUP.SH.1037732
BACKUP.SH.1038763
BACKUP.SH.1039793
BACKUP.SH.1040833
BACKUP.SH.1041884
BACKUP.SH.1042907
BACKUP.SH.1043927
BACKUP.SH.1044956
BACKUP.SH.1045977
BACKUP.SH.1046997
BACKUP.SH.1048033
BACKUP.SH.1049401
BACKUP.SH.1050493
BACKUP.SH.1052724
BACKUP.SH.1053750
BACKUP.SH.1054798
BACKUP.SH.1055828
BACKUP.SH.1056862
BACKUP.SH.1057977
BACKUP.SH.1059460
BACKUP.SH.1060510
BACKUP.SH.1061544
BACKUP.SH.1062576
BACKUP.SH.1063609
BACKUP.SH.1064640
BACKUP.SH.1065670
BACKUP.SH.1066707
BACKUP.SH.1067745
BACKUP.SH.1068765
BACKUP.SH.1069844
BACKUP.SH.1070873
BACKUP.SH.1071900
BACKUP.SH.1072929
BACKUP.SH.1073963
BACKUP.SH.1074998
BACKUP.SH.1076031
BACKUP.SH.1077064
BACKUP.SH.1078093
BACKUP.SH.1079123
BACKUP.SH.1080174
BACKUP.SH.1081214
BACKUP.SH.1083879
BACKUP.SH.1085226
BACKUP.SH.1086288
BACKUP.SH.1087322
BACKUP.SH.1088352
BACKUP.SH.1089388
BACKUP.SH.1090418
BACKUP.SH.1091452
BACKUP.SH.1092503
BACKUP.SH.1093541
BACKUP.SH.1094572
BACKUP.SH.1095599
BACKUP.SH.1096626
BACKUP.SH.1097656
BACKUP.SH.1098688
BACKUP.SH.1099718
BACKUP.SH.1100753
BACKUP.SH.1101776
BACKUP.SH.1102849
BACKUP.SH.1103899
BACKUP.SH.1104928
BACKUP.SH.1105969
BACKUP.SH.1106998
BACKUP.SH.1108029
BACKUP.SH.1109061
BACKUP.SH.1110093
BACKUP.SH.1111123
BACKUP.SH.1112159
BACKUP.SH.1113176
BACKUP.SH.1114343
BACKUP.SH.1115611
BACKUP.SH.1116784
BACKUP.SH.1117869
BACKUP.SH.1118910
BACKUP.SH.1119942
BACKUP.SH.1120974
BACKUP.SH.1122004
BACKUP.SH.1123035
BACKUP.SH.1124063
BACKUP.SH.1125102
BACKUP.SH.1126131
BACKUP.SH.1127162
BACKUP.SH.1128191
BACKUP.SH.1129224
BACKUP.SH.1130251
BACKUP.SH.1131286
BACKUP.SH.1132325
BACKUP.SH.1133355
BACKUP.SH.1134388
BACKUP.SH.1135478
BACKUP.SH.1136511
BACKUP.SH.1137541
BACKUP.SH.1138573
BACKUP.SH.1139605
BACKUP.SH.1140647
BACKUP.SH.1141677
BACKUP.SH.1142711
BACKUP.SH.1143745
BACKUP.SH.1144776
BACKUP.SH.1145804
BACKUP.SH.1146833
BACKUP.SH.1148227
BACKUP.SH.1149391
BACKUP.SH.1150482
BACKUP.SH.1151513
BACKUP.SH.1152549
BACKUP.SH.1153577
BACKUP.SH.1154612
BACKUP.SH.1155643
BACKUP.SH.1156680
BACKUP.SH.1157725
BACKUP.SH.1158757
BACKUP.SH.1159786
BACKUP.SH.1160817
BACKUP.SH.1161851
BACKUP.SH.1162881
BACKUP.SH.1163912
BACKUP.SH.1164947
BACKUP.SH.1165977
BACKUP.SH.1167010
BACKUP.SH.1168098
BACKUP.SH.1169127
BACKUP.SH.1170164
BACKUP.SH.1171192
BACKUP.SH.1172223
BACKUP.SH.1173255
BACKUP.SH.1174288
BACKUP.SH.1175313
BACKUP.SH.1176340
BACKUP.SH.1177350
BACKUP.SH.1178382
BACKUP.SH.1179413
BACKUP.SH.1180818
BACKUP.SH.1181963
BACKUP.SH.1183079
BACKUP.SH.1184160
BACKUP.SH.1185193
BACKUP.SH.1186224
BACKUP.SH.1187257
BACKUP.SH.443526
BACKUP.SH.444622
BACKUP.SH.445695
BACKUP.SH.446792
BACKUP.SH.449536
BACKUP.SH.466240
BACKUP.SH.467281
BACKUP.SH.468324
BACKUP.SH.469499
BACKUP.SH.470692
BACKUP.SH.471737
BACKUP.SH.472803
BACKUP.SH.473840
BACKUP.SH.474879
BACKUP.SH.475919
BACKUP.SH.476959
BACKUP.SH.478002
BACKUP.SH.479024
BACKUP.SH.480045
BACKUP.SH.481077
BACKUP.SH.482113
BACKUP.SH.483154
BACKUP.SH.484191
BACKUP.SH.485246
BACKUP.SH.486284
BACKUP.SH.487327
BACKUP.SH.488396
BACKUP.SH.489867
BACKUP.SH.490930
BACKUP.SH.492539
BACKUP.SH.493725
BACKUP.SH.494868
BACKUP.SH.495930
BACKUP.SH.496973
BACKUP.SH.498010
BACKUP.SH.499081
BACKUP.SH.500124
BACKUP.SH.501156
BACKUP.SH.502179
BACKUP.SH.503206
BACKUP.SH.504244
BACKUP.SH.505282
BACKUP.SH.506325
BACKUP.SH.507362
BACKUP.SH.508401
BACKUP.SH.509446
BACKUP.SH.510480
BACKUP.SH.511529
BACKUP.SH.512568
BACKUP.SH.513605
BACKUP.SH.514664
BACKUP.SH.516103
BACKUP.SH.517169
BACKUP.SH.518284
BACKUP.SH.519335
BACKUP.SH.520394
BACKUP.SH.521441
BACKUP.SH.522487
BACKUP.SH.523538
BACKUP.SH.524897
BACKUP.SH.526065
BACKUP.SH.527305
BACKUP.SH.528401
BACKUP.SH.529459
BACKUP.SH.530511
BACKUP.SH.531556
BACKUP.SH.532609
BACKUP.SH.533668
BACKUP.SH.534733
BACKUP.SH.535786
BACKUP.SH.536828
BACKUP.SH.537892
BACKUP.SH.538944
BACKUP.SH.539998
BACKUP.SH.541059
BACKUP.SH.542562
BACKUP.SH.543632
BACKUP.SH.545079
BACKUP.SH.546316
BACKUP.SH.547351
BACKUP.SH.548378
BACKUP.SH.549412
BACKUP.SH.550450
BACKUP.SH.551485
BACKUP.SH.552519
BACKUP.SH.553553
BACKUP.SH.554584
BACKUP.SH.555624
BACKUP.SH.556657
BACKUP.SH.558049
BACKUP.SH.559168
BACKUP.SH.560307
BACKUP.SH.561368
BACKUP.SH.562401
BACKUP.SH.563430
BACKUP.SH.564475
BACKUP.SH.565503
BACKUP.SH.566533
BACKUP.SH.567633
BACKUP.SH.569033
BACKUP.SH.570084
BACKUP.SH.571121
BACKUP.SH.572154
BACKUP.SH.573196
BACKUP.SH.574226
BACKUP.SH.575254
BACKUP.SH.576279
BACKUP.SH.577315
BACKUP.SH.578409
BACKUP.SH.579443
BACKUP.SH.580474
BACKUP.SH.581511
BACKUP.SH.582544
BACKUP.SH.583580
BACKUP.SH.584618
BACKUP.SH.585650
BACKUP.SH.586684
BACKUP.SH.587717
BACKUP.SH.588749
BACKUP.SH.589794
BACKUP.SH.591200
BACKUP.SH.592363
BACKUP.SH.592891
BACKUP.SH.593513
BACKUP.SH.595038
BACKUP.SH.596088
BACKUP.SH.597175
BACKUP.SH.598214
BACKUP.SH.599252
BACKUP.SH.600291
BACKUP.SH.601329
BACKUP.SH.602359
BACKUP.SH.603386
BACKUP.SH.604420
BACKUP.SH.605450
BACKUP.SH.606485
BACKUP.SH.607527
BACKUP.SH.608548
BACKUP.SH.609579
BACKUP.SH.610665
BACKUP.SH.611704
BACKUP.SH.612743
BACKUP.SH.613779
BACKUP.SH.614811
BACKUP.SH.615867
BACKUP.SH.616897
BACKUP.SH.617932
BACKUP.SH.619034
BACKUP.SH.620478
BACKUP.SH.621520
BACKUP.SH.622559
BACKUP.SH.623877
BACKUP.SH.623962
BACKUP.SH.625125
BACKUP.SH.626216
BACKUP.SH.627258
BACKUP.SH.628298
BACKUP.SH.629338
BACKUP.SH.630369
BACKUP.SH.631405
BACKUP.SH.632420
BACKUP.SH.633452
BACKUP.SH.634489
BACKUP.SH.635525
BACKUP.SH.636556
BACKUP.SH.637601
BACKUP.SH.638633
BACKUP.SH.639669
BACKUP.SH.640697
BACKUP.SH.641744
BACKUP.SH.642772
BACKUP.SH.643860
BACKUP.SH.644964
BACKUP.SH.646407
BACKUP.SH.647462
BACKUP.SH.648516
BACKUP.SH.649550
BACKUP.SH.650579
BACKUP.SH.651623
BACKUP.SH.652653
BACKUP.SH.653685
BACKUP.SH.654717
BACKUP.SH.656061
BACKUP.SH.657138
BACKUP.SH.658300
BACKUP.SH.659380
BACKUP.SH.660416
BACKUP.SH.661451
BACKUP.SH.662485
BACKUP.SH.663525
BACKUP.SH.664560
BACKUP.SH.665591
BACKUP.SH.666631
BACKUP.SH.667674
BACKUP.SH.668700
BACKUP.SH.669729
BACKUP.SH.670815
BACKUP.SH.672225
BACKUP.SH.673264
BACKUP.SH.674313
BACKUP.SH.675347
BACKUP.SH.676447
BACKUP.SH.677486
BACKUP.SH.678518
BACKUP.SH.679553
BACKUP.SH.680592
BACKUP.SH.681627
BACKUP.SH.682658
BACKUP.SH.683672
BACKUP.SH.684700
BACKUP.SH.685728
BACKUP.SH.686757
BACKUP.SH.687780
BACKUP.SH.689168
BACKUP.SH.690293
BACKUP.SH.691416
BACKUP.SH.692479
BACKUP.SH.693551
BACKUP.SH.694584
BACKUP.SH.695616
BACKUP.SH.696720
BACKUP.SH.698123
BACKUP.SH.699168
BACKUP.SH.700208
BACKUP.SH.701243
BACKUP.SH.702285
BACKUP.SH.703319
BACKUP.SH.704349
BACKUP.SH.705381
BACKUP.SH.706418
BACKUP.SH.707441
BACKUP.SH.708474
BACKUP.SH.709558
BACKUP.SH.710590
BACKUP.SH.711616
BACKUP.SH.712642
BACKUP.SH.713663
BACKUP.SH.714693
BACKUP.SH.715727
BACKUP.SH.716757
BACKUP.SH.717785
BACKUP.SH.718830
BACKUP.SH.719909
BACKUP.SH.721057
BACKUP.SH.722465
BACKUP.SH.724062
BACKUP.SH.725142
BACKUP.SH.726199
BACKUP.SH.727234
BACKUP.SH.728265
BACKUP.SH.729299
BACKUP.SH.730331
BACKUP.SH.731372
BACKUP.SH.732408
BACKUP.SH.733442
BACKUP.SH.734473
BACKUP.SH.735491
BACKUP.SH.736520
BACKUP.SH.737533
BACKUP.SH.738561
BACKUP.SH.739590
BACKUP.SH.740611
BACKUP.SH.741726
BACKUP.SH.742753
BACKUP.SH.743783
BACKUP.SH.744820
BACKUP.SH.745852
BACKUP.SH.746882
BACKUP.SH.747997
BACKUP.SH.749533
BACKUP.SH.750581
BACKUP.SH.751627
BACKUP.SH.752667
BACKUP.SH.753807
BACKUP.SH.755096
BACKUP.SH.756263
BACKUP.SH.757357
BACKUP.SH.758393
BACKUP.SH.759419
BACKUP.SH.760442
BACKUP.SH.761465
BACKUP.SH.762496
BACKUP.SH.763522
BACKUP.SH.764556
BACKUP.SH.765586
BACKUP.SH.766615
BACKUP.SH.767641
BACKUP.SH.768665
BACKUP.SH.769692
BACKUP.SH.770733
BACKUP.SH.771770
BACKUP.SH.772801
BACKUP.SH.773890
BACKUP.SH.775446
BACKUP.SH.776485
BACKUP.SH.777513
BACKUP.SH.778547
BACKUP.SH.779584
BACKUP.SH.780616
BACKUP.SH.781646
BACKUP.SH.782679
BACKUP.SH.783702
BACKUP.SH.784115
BACKUP.SH.784730
BACKUP.SH.785771
BACKUP.SH.787099
BACKUP.SH.788216
BACKUP.SH.789379
BACKUP.SH.790455
BACKUP.SH.791482
BACKUP.SH.792516
BACKUP.SH.793540
BACKUP.SH.794569
BACKUP.SH.795602
BACKUP.SH.796644
BACKUP.SH.797682
BACKUP.SH.798715
BACKUP.SH.799806
BACKUP.SH.801336
BACKUP.SH.802373
BACKUP.SH.803406
BACKUP.SH.804441
BACKUP.SH.805475
BACKUP.SH.806506
BACKUP.SH.807593
BACKUP.SH.808684
BACKUP.SH.809719
BACKUP.SH.810741
BACKUP.SH.811754
BACKUP.SH.812772
BACKUP.SH.813804
BACKUP.SH.814833
BACKUP.SH.815865
BACKUP.SH.817903
BACKUP.SH.818935
BACKUP.SH.820329
BACKUP.SH.821468
BACKUP.SH.822605
BACKUP.SH.823648
BACKUP.SH.824683
BACKUP.SH.825795
BACKUP.SH.827216
BACKUP.SH.828262
BACKUP.SH.829296
BACKUP.SH.830339
BACKUP.SH.831379
BACKUP.SH.832404
BACKUP.SH.833435
BACKUP.SH.834482
BACKUP.SH.835521
BACKUP.SH.836555
BACKUP.SH.837589
BACKUP.SH.838619
BACKUP.SH.839663
BACKUP.SH.840744
BACKUP.SH.841769
BACKUP.SH.842801
BACKUP.SH.843831
BACKUP.SH.844858
BACKUP.SH.845891
BACKUP.SH.846926
BACKUP.SH.847967
BACKUP.SH.849003
BACKUP.SH.850045
BACKUP.SH.851211
BACKUP.SH.852986
BACKUP.SH.854112
BACKUP.SH.855236
BACKUP.SH.856301
BACKUP.SH.857304
BACKUP.SH.858336
BACKUP.SH.859401
BACKUP.SH.860440
BACKUP.SH.861477
BACKUP.SH.862523
BACKUP.SH.863560
BACKUP.SH.864591
BACKUP.SH.865624
BACKUP.SH.866652
BACKUP.SH.867682
BACKUP.SH.868708
BACKUP.SH.869738
BACKUP.SH.870768
BACKUP.SH.871807
BACKUP.SH.872889
BACKUP.SH.873944
BACKUP.SH.874976
BACKUP.SH.876008
BACKUP.SH.877164
BACKUP.SH.878619
BACKUP.SH.879658
BACKUP.SH.880693
BACKUP.SH.881730
BACKUP.SH.882762
BACKUP.SH.883795
BACKUP.SH.884956
BACKUP.SH.886229
BACKUP.SH.887400
BACKUP.SH.888486
BACKUP.SH.889518
BACKUP.SH.890550
BACKUP.SH.891580
BACKUP.SH.892615
BACKUP.SH.894545
BACKUP.SH.895588
BACKUP.SH.896613
BACKUP.SH.897642
BACKUP.SH.898670
BACKUP.SH.899710
BACKUP.SH.900743
BACKUP.SH.901775
BACKUP.SH.902905
BACKUP.SH.904484
BACKUP.SH.905578
BACKUP.SH.906617
BACKUP.SH.907649
BACKUP.SH.908681
BACKUP.SH.909710
BACKUP.SH.910745
BACKUP.SH.911777
BACKUP.SH.912810
BACKUP.SH.913847
BACKUP.SH.914873
BACKUP.SH.915903
BACKUP.SH.916934
BACKUP.SH.918287
BACKUP.SH.919389
BACKUP.SH.920536
BACKUP.SH.921613
BACKUP.SH.922645
BACKUP.SH.923672
BACKUP.SH.924705
BACKUP.SH.925745
BACKUP.SH.926777
BACKUP.SH.927807
BACKUP.SH.928930
BACKUP.SH.930433
BACKUP.SH.931467
BACKUP.SH.932505
BACKUP.SH.933537
BACKUP.SH.934569
BACKUP.SH.935600
BACKUP.SH.936633
BACKUP.SH.937668
BACKUP.SH.938760
BACKUP.SH.939788
BACKUP.SH.940821
BACKUP.SH.941851
BACKUP.SH.942885
BACKUP.SH.943912
BACKUP.SH.944944
BACKUP.SH.945969
BACKUP.SH.947001
BACKUP.SH.948027
BACKUP.SH.949062
BACKUP.SH.950097
BACKUP.SH.951503
BACKUP.SH.952657
BACKUP.SH.953775
BACKUP.SH.954896
BACKUP.SH.956355
BACKUP.SH.957393
BACKUP.SH.958425
BACKUP.SH.959456
BACKUP.SH.960490
BACKUP.SH.961528
BACKUP.SH.962556
BACKUP.SH.963594
BACKUP.SH.964629
BACKUP.SH.965658
BACKUP.SH.966686
BACKUP.SH.967710
BACKUP.SH.968739
BACKUP.SH.969764
BACKUP.SH.970800
BACKUP.SH.971874
BACKUP.SH.972906
BACKUP.SH.973933
BACKUP.SH.974963
BACKUP.SH.976003
BACKUP.SH.977042
BACKUP.SH.978078
BACKUP.SH.979111
BACKUP.SH.980231
BACKUP.SH.981721
BACKUP.SH.982761
BACKUP.SH.984159
BACKUP.SH.985290
BACKUP.SH.986409
BACKUP.SH.987459
BACKUP.SH.988493
BACKUP.SH.989530
BACKUP.SH.990562
BACKUP.SH.991593
BACKUP.SH.992613
BACKUP.SH.993654
BACKUP.SH.994686
BACKUP.SH.995722
BACKUP.SH.996753
BACKUP.SH.997789
BACKUP.SH.998820
BACKUP.SH.999850
CHAGE
CHECK_RELOAD_STATUS
CHFN
CREATE-STATSSTORE
CRON
CROND
CRONTAB
DBUS
DHCLIENT
DHCPLEASES
DNSMASQ
DPINGER
EXT4-FS (SDA2)
FAT-FS (SDA2)
FILTERLOG
GROUPADD
GROUPMOD
HEARTBEAT
HOSTD
HOSTD-ICM
HOSTD-PROBE
HOSTD-UPGRADE-CONFIG
HPSSACLI
IGMPPROXY
IMAGECONFIGMANAGER
ISCSID
KERNEL
LIBAPACHE2-MOD-PHP5
NGINX
NTPDATE
OS-PROBER
PAM_SYSTEMD(SU:SESSION)
PAM_UNIX(CRON:SESSION)
PAM_UNIX(SSHD:SESSION)
PAM_UNIX(SU:SESSION)
PAM_UNIX(SUDO:SESSION)
PAM_UNIX(SYSTEMD-USER:SESSION)
PFSCTL
PHP
PHP-CGI
PHP-FPM
PHP5-CLI
PHP5-READLINE
PHP7.0-CURL
PHP7.0-SNMP
POLKITD(AUTHORITY=LOCAL)
POLLER-SERVICE
PYVMOMISERVER
RHTTPPROXY
RHTTPPROXY-UPGRADE-CONFIG
ROOT
RPCBIND
RRDCACHED
RTSOLD
SFCB-CIMXML-PROCESSOR
SFCB-VMWARE_BASE
SHELL
SMARTD
SMOKEPING
SNMPD
SSHD
SSHLOCKOUT
SU
SUDO
SYSLOG
SYSLOG-NG
SYSLOGD
SYSTEMD
SYSTEMD-LOGIND
SYSTEMD-TMPFILES
TMPWATCH
UNKNOWN
UPS
USBARB
USERADD
USERMOD
VMAUTHD
VMKERNEL
VMKWARNING
VOBD
VSANSYSTEM
VVOLD
WATCHDOG-HOSTD
WATCHDOG-RHTTPPROXY
WATCHDOG-SNMPD
X
XFS (SDA2)
XINETD</option>
```

**Comment by florianbeer** [comment]
Thanks @nerdalertdk 
I'm pretty sure my patch should clear up your dropown. If you want, you could empty your syslog table, add the change from the patch and restart rsyslogd on your LibreNMS server to test it out.

**Comment by murrant** [comment]
It's fine to have "too many tests" imho they only take ms to complete.

@nerdalertdk You can probably open a ticket for that if this patch doesn't clear it up.  Provide some example syslog entries for testing.

**Pull request merged**
