### PR TITLE
fix: add html line breaks for html emails

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I'm not sure about this change, this will add additional line breaks for users who've already used `<br />` but also formatted the templates for readability by using newlines.

Imho, users should format the template as expected for html rather than rely on us working out what should be formatted and what shouldn't.

**Comment by aldemira** [comment]
I see your point, sure. Default template looks even uglier with html turned on, that was my starting point.

**Comment by laf** [comment]
@aldemira That makes sense. You can fix that in https://github.com/librenms/librenms/blob/master/includes/alerts.inc.php#L449

Do the check for html enabled emails after that and if enabled run through `nl2br()`. That will get you the same result without breaking anything.

**Comment by aldemira** [comment]
What about putting the default template in alert templates page, obviously non-deletable and non-attachable?

**Comment by laf** [comment]
You're more than welcome to :) You'll need to also ensure it can be reverted to default if/when someone makes breaking changes as well.

imho, a simple nl2br() in the code seems the easier and less problematic approach.

**Pull request closed without merging**
