### PR TITLE
Make UBNT Airos type: wireless

### PR DESCRIPTION
**Pull request by trs80**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Because it is. Also airos-af is type: wireless

### CODE REVIEW

**Comment by murrant** [comment]
Go ahead and change airos-af in this PR as well and create a notification like this: https://github.com/librenms/librenms.github.io/pull/90

Thanks.

**Comment by trs80** [comment]
Ah, my point was that airos-af was already type: wireless, to support my change of airos from type: network to type: wireless. Anyway, notification created.

**Comment by laf** [comment]
@trs80 I can't see the pull request for the notification :(

**Comment by trs80** [comment]
It helps when I make a pull request https://github.com/librenms/librenms.github.io/pull/92

**Comment by laf** [comment]
blocker in place. please merge on the 10th of July.

**Pull request merged**
