### PR TITLE
malaysia map - malaysia.js

### PR DESCRIPTION
**Pull request by marcodc**
Hi,
here 1 of 2 maps 
malaysia & south east asia
kindly check and if deem ok please add.

cheers
marco
[malaysia.zip](https://github.com/librenms/librenms/files/150045/malaysia.zip)
[sout_east_asia.zip](https://github.com/librenms/librenms/files/150046/sout_east_asia.zip)

### CODE REVIEW

**Comment by f0o** [comment]
Hi, do you happen to know the licencing terms of those?

**Comment by marcodc** [comment]
Hi Daniel,

i actually made them and converted them myself
even the base image was a free to use for commercial and non commercial without attribution

so actually you can use any license on them as they would be my property and i would like to pass them on as free to use without attribution for you guys.

i use librenms as main part for my infrastructure management appliance called opscontrol.
will need once someone from your team to look at as i change the look and feel a bit and i dont want to go against any of your licensing terms as i change the logos and so on to create a more unified look over mulitple apps (librenms & GLPI & OCS-NG & more = opscontrol virtual appliance)

if you need any graphics for librenms i gladly help and contribute, im not a professional graphics designer but many years of marketing have made me pickup some skills with AI and photoshop as well web and graphic design.

happy to contribute 

best regards
Marco


On 2/29/2016 3:07:00 AM, Daniel Preussker <notifications@github.com> wrote:
Hi, do you happen to know the licencing terms of those?

**Comment by laf** [comment]
@marcodc 

Can you please sign the contributors agreement as per http://docs.librenms.org/General/Contributing/

Can you also update: https://github.com/librenms/librenms/blob/master/doc/General/Acknowledgement.md including a link to the original map please.

**Comment by marcodc** [comment]
@laf 
All Done as per your request.
have a great Day.

**Comment by marcodc** [comment]
.

**Pull request merged**
