### PR TITLE
Update to use DataTables instead of BootGrid

### PR DESCRIPTION
**Pull request by geordish**
As mentioned on a previous issue, bootgrid is no longer maintained. I've taken a look to switching to DataTables instead.

This patch just moves the ports page over as a test.
Before:
image

After:
image

Currently column sorting isn't working, but the rest of it is functional.

If the consensus is that this is worthwhile, I will continue to change all places where bootgrid is used is switched over.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7313)

### CODE REVIEW

**Comment by laf** [comment]
No issues from me :)

What's needed to get column sorting fixed?

**Comment by murrant** [comment]
There is a bootstrap plugin for datatables,  would be best to use that.

**Comment by geordish** [comment]
@murrant: bootstrap plugin:
image

@laf Shouldn't take much. Just didn't want to invest too much time up front.

**Comment by geordish** [comment]
This should now be working exactly the same as before, but with DataTables.

**Comment by florianbeer** [comment]
In my opinion the visual aspect is quite important too and the bootgrid version was nicer to look at in my eyes. Less clutter and generally more styled.

Great job on replacing the outdated library though, thanks!

**Comment by geordish** [comment]
Reopened on #7318

**Pull request closed without merging**
