### PR TITLE
Update dnos.yaml file to include newer switches

### PR DESCRIPTION
**Pull request by kslawrence**
add an additional sysobject ID to detect OS10 Dell (previously Forceten) switches

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kslawrence** [comment]
Hi laf,

Yes the switches are Dell EMC. 

The full sysobjectid I am seeing for our switches is .1.3.6.1.4.1.674.11000.5000.100.2.1.7

**Comment by laf** [comment]
Ok thanks, can you add tests please.

**Comment by kslawrence** [comment]
Not entirely sure if this test method is correct but here is the output:

librenms@librenms:/opt/librenms/scripts$ sudo ./pre-commit.php --db        
Only checking os: dnos
Running unit tests... 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.....SSSS..                                                       11 / 11 (100%)

Time: 24.84 seconds, Memory: 30.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 11, Assertions: 567, Skipped: 4.
Cleaning database...
Style check skipped.
Lint check skipped.
Tests ok, submit away :)

**Comment by laf** [comment]
@kslawrence Any news on this?

**Pull request closed without merging**
