### PR TITLE
Added support for Avaya VSP

### LINKED ISSUE #3982: Add hardware Avaya Virtual Services Platform
Discovery:  http://pastebin.com/ZNtg5Kqy
Poller:  http://pastebin.com/Wz9ym1X7
SNMP Walk:  http://pastebin.com/yqKdcLbh

OIDs of importance:

CPU Utilization %:  1.3.6.1.4.1.2272.1.85.10.1.1.2.1  (rcKhiSlotCpuCurrentUtil)
Memory Utilization %:  1.3.6.1.4.1.2272.1.85.10.1.1.8.1  (rcKhiSlotMemUtil)

Some OIDs are from an updated version of rapid_city.mib.  Older versions with just the old Nortel OIDs may not contain the KHI OIDs.

Relevant: https://github.com/librenms/librenms/pull/3258
rapid_city.mib:  http://pastebin.com/7XczB3e2

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fix #3982

### CODE REVIEW

**Comment by ospfbgp** [comment]
I am actively working on adding support for Avaya VSP
I have am currently beta testings CPU, Memory(total, free, used, percent utilization), and temperature.  I have these working in my lab.  I will be doing power supply and fan as I get time.

**Comment by laf** [comment]
bump

**Comment by ospfbgp** [comment]
I am here.  Just busy. I have the vsp close to working in librenms. 

Daniel Cox
danielcoxman@gmail.com
859-552-8091

**Comment by laf** [comment]
The bump wasn't for you @ospfbgp :)

**Comment by laf** [comment]
ty @f0o.

@ospfbgp - feel free to build on top of this.

**Pull request merged**
