### PR TITLE
Tweak multi_bits_separated graph rendering

### PR DESCRIPTION
**Pull request by peelman**
* remove extra backslashes that were getting rendered
* Aline aggregate in/out text with interface in/out text
* Adjust description length for graphs with widths > 500

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Before:

image


After:

image

imho this adds far too much whitespace after the interface description.

**Comment by peelman** [comment]
graph php

That's fine until you cross devices.  Then it tries to put the hostname in that field with the interface on teh second line.  That can make it problematic to read.  It should be dynamic or wide enough to be halfway accommodating.  18 Characters isn't wide enough.  40 Might be too much. I'd be willing to compromise there.

**Comment by murrant** [comment]
Hmm, perhaps we pre-measure the description length, then we don't have extra padding when we don't need it.

**Comment by peelman** [comment]
i was going to take a swing at looping through for the longest description (or 40chars) and set it; but i kept getting too distracted yesterday. i can try to find some time later this week maybe, unless @murrant beats me to it.

**Comment by laf** [comment]
Ok what about this. @murrant will probably rewrite it but it seems to be ok :)

```
php > $init_modules = ['web'];
php > require 'includes/init.php';
php > var_dump(set_length(['Agg Indsadsdfdf something more made up but too long', 'Agg Out'], 40));
array(2) {
  [0]=>
  string(40) "Agg Indsadsdfdf something more made up b"
  [1]=>
  string(40) "Agg Out                                 "
}

php > var_dump(set_length(['Agg In', 'Agg Out'], 40));
array(2) {
  [0]=>
  string(7) "Agg In "
  [1]=>
  string(7) "Agg Out"
}
```
Code:
https://p.libren.ms/view/raw/9d5abd26

**Comment by laf** [comment]
We can set a few more spaces in as a default so the limit will be $len + 2 for example.

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
Closing for now, feel free to respond to my previous comments.

**Pull request closed without merging**
