### PR TITLE
Ban legacy dbFacile functions

### PR DESCRIPTION
**Pull request by murrant**
Have CI fail when code changes add usage of dbFacile functions.  Users need to be using Eloquent and Fluent so we can add multiple database server capability.

There will likely be changes we don't care about this for... but it is good to tell the contributor early.

Includes changes that will fail, will remove after feedback.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by Jellyfrog — APPROVED** [review]
I'm all for it if we want the project to move forward

**Comment by Jellyfrog** [comment]
Maybe we should merge some low hanging fruit before merging this

**Comment by Jellyfrog** [comment]
No I like this :(

**Comment by murrant** [comment]
We are not ready.

**Pull request closed without merging**
