### PR TITLE
Add support for Vsol v1600d EPON OLT

### PR DESCRIPTION
**Pull request by guipoletto**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by ottorei — APPROVED** [review]

**Comment by kaustubh6199** [comment]
I have added the Vsol EPON olt but facing some issue with rx power of the ONU the value is not correct 
Screenshot from 2023-03-07 20-20-45

**Comment by guipoletto** [comment]
Yes, i'm aware. 

this is due to V-solution returning  very weird things in the snmpget:

-- as far as i know, there is no way to parse that correctly without messing in code that's common to all other platforms.
I have opened a ticket with the V-sol engineers, but their position is #wontfix /not broken (from their perspective, it's the NMS responsibility to parse arbitrarilly weird strings received from their products)


SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-OUQntea' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/vsolution' 'udp:HOSTNAME:161' '.1.3.6.1.4.1.37950.1.1.5.10.13.1.1.5.1' '.1.3.6.1.4.1.37950.1.1.5.10.13.1.1.5.2' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.3' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.5' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.10' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.15' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.1' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.2' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.9' '.1.3.6.1.4.1.37950.1.1.5.12.2.1.8.1.7.1.16']

.*.4.1.379*.*.5.1 = "6.56 dbm"
.*.4.1.379*.*.5.2 = "6.69 dbm"
.*.4.1.379*.*.* = "0.03 mW (-14.60 dBm)"
.*.4.1.379*.*.* = "0.01 mW (-20.00 dBm)"
.*.4.1.379*.*.* = "0.01 mW (-21.55 dBm)"
.*.4.1.379*.*.* = "0.00 mW (-23.28 dBm)"
.*.4.1.379*.*.* = "0.03 mW (-14.63 dBm)"
.*.4.1.379*.*.* = "0.03 mW (-15.97 dBm)"
.*.4.1.379*.*.* = "0.02 mW (-18.12 dBm)"
.*.4.1.379*.*.* = "0.00 mW (-27.70 dBm)"  

< this is the output from the actual GET
the first two entries are from the SFP|EPON interfaces
those are reported in the usual manner for an optical interface

the others are the ONT (uplink) signal levels, that contain the useless "mW" values, and the actual interesting values between parentheses

I didn't know how to make LibreNMS understand that without breaking stuff, so i left it as-is(it's actually V-Solution's fault)

if they fix it, then nothing has to be changed in LibreNMS :)

**Comment by kaustubh6199** [comment]
yup i notice that also while doing snmp pull . i have also tried to add custom oid for that but its unable to notice the oid changes . Still thanks for trying, any ways i am chaning my OLT to CDATA anyways. I will let you know if i found some solutions

**Comment by kaustubh6199** [comment]
i am attaching the my snmp data
[Sy-GOPON-4OLT-L3_20191204.zip](https://github.com/librenms/librenms/files/10918243/Sy-GOPON-4OLT-L3_20191204.zip)

**Comment by jowelvjoy** [comment]
I got a new mib file for Vsol 
[V1600G-MIB.zip](https://github.com/user-attachments/files/15874852/V1600G-MIB.zip)

**Pull request merged**
