### PR TITLE
netscaler new counter metrics

### PR DESCRIPTION
**Pull request by mzacchi**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by mzacchi** [comment]
> Please add test data so we can ensure your change is not broken in the future.
> 
> Read the docs to find out how: https://docs.librenms.org/Developing/os/Test-Units
Content of `tests/snmpsim/netscaler_netscaler.snmprec`
`1.3.6.1.2.1.1.1.0|4|FreeBSD <sysname> 8.4-NETSCALER-11.1 FreeBSD 8.4-NETSCALER-11.1 #0: Fri Apr  7 23:35:57 PDT 2017     root@sjcdbld84-116:/usr/obj/home/build/rs_111_53_5_RTM/usr.src/sys/NSSVM amd64
1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.5951.6
1.3.6.1.2.1.1.3.0|67|885878826
1.3.6.1.2.1.1.4.0|4|<private>
1.3.6.1.2.1.1.5.0|4|<private>
1.3.6.1.2.1.1.6.0|4|<private>
1.3.6.1.2.1.11.1.0|65|15904778
1.3.6.1.2.1.11.2.0|65|15417614
1.3.6.1.2.1.11.3.0|65|0
1.3.6.1.2.1.11.4.0|65|1027
1.3.6.1.2.1.11.5.0|65|0
1.3.6.1.2.1.11.6.0|65|410
1.3.6.1.2.1.11.8.0|65|0
1.3.6.1.2.1.11.9.0|65|0
1.3.6.1.2.1.11.10.0|65|0
1.3.6.1.2.1.11.11.0|65|0
1.3.6.1.2.1.11.12.0|65|0
1.3.6.1.2.1.11.13.0|65|28273913
1.3.6.1.2.1.11.14.0|65|0
1.3.6.1.2.1.11.15.0|65|2185544
1.3.6.1.2.1.11.16.0|65|12995008
1.3.6.1.2.1.11.17.0|65|0
1.3.6.1.2.1.11.18.0|65|0
1.3.6.1.2.1.11.19.0|65|0
1.3.6.1.2.1.11.20.0|65|0
1.3.6.1.2.1.11.21.0|65|0
1.3.6.1.2.1.11.22.0|65|0
1.3.6.1.2.1.11.24.0|65|388332
1.3.6.1.2.1.11.25.0|65|0
1.3.6.1.2.1.11.26.0|65|0
1.3.6.1.2.1.11.27.0|65|0
1.3.6.1.2.1.11.28.0|65|15417616
1.3.6.1.2.1.11.29.0|65|0
1.3.6.1.2.1.11.30.0|2|2
1.3.6.1.2.1.11.31.0|65|0
1.3.6.1.2.1.11.32.0|65|0
1.3.6.1.6.3.10.2.1.3.0|2|51808460`

**Comment by Jellyfrog** [comment]
Hi @mzacchi
Will you look into adding test data?

**Comment by mzacchi** [comment]
Hi Jellyfrog,
Yes, sorry, I needed root access to install some of the testing
requirements and that took a while.
Will update soon.

**Comment by mzacchi** [comment]
@Jellyfrog,
I could not run `lnms dev:check unit --db --snmpsim` as it kept throwing dependency errors and I really don't want to mess with my production environment. Unfortunately, we don
[netscaler_netscaler.json.txt](https://github.com/librenms/librenms/files/7465868/netscaler_netscaler.json.txt)
[netscaler_netscaler.snmprec.txt](https://github.com/librenms/librenms/files/7465869/netscaler_netscaler.snmprec.txt)
't have Netscalers in lab just yet.
This is what I have so far. Is it enough?

**Comment by Jellyfrog** [comment]
Hi yes you need to commit them them here tho.

**Comment by mzacchi** [comment]
> Hi yes you need to commit them them here tho.

OK, how do I do that now? I thought I had alrady commited.

**Comment by Jellyfrog** [comment]
You have only added this changes: https://github.com/librenms/librenms/pull/13323/files

You need to add them to the branch and run git add / commit / push.
Or try a graphical git client like https://desktop.github.com

**Comment by mzacchi** [comment]
> You have only added this changes: https://github.com/librenms/librenms/pull/13323/files
> 
> You need to add them to the branch and run git add / commit / push. Or try a graphical git client like https://desktop.github.com

Almost there :) What is the syntax for git push?

**Review by murrant — APPROVED** [review]
Just had to fix it up a bit ;)

**Pull request merged**
