### PR TITLE
Syslog

### PR DESCRIPTION
**Pull request by vitalisator**
I'm trying to update to syslog new type, but i don't know how to fill the widget with data.
has anyone a hint for me?

have used eventlog as template.
reference to #1712

### CODE REVIEW

**Comment by laf** [comment]
You pretty much just want to take the contents of:

html/pages/syslog.inc.php

**Comment by vitalisator** [comment]
@laf then it just show me, Problem with backend

**Comment by laf** [comment]
You still need to wrap all of the output in $common_output[]; so that it can be output where needed, you can't output directly from the common files.

**Comment by vitalisator** [comment]
@laf, can you please review this?
still the same error.
And i think this line is not sane too:
       $("#dtpickerto").data("DateTimePicker").maxDate("'.mres($config['dateformat']['byminute']) .')";

**Comment by vitalisator** [comment]
@laf, I think it my be the wrong way at all, if I see into html/includes/common/eventlog.inc.php for reference there is on wrapping table data at all, only table header. But for me it is unclear where the table data is coming from.

**Comment by vitalisator** [comment]
I think it's more like my last commit. It's working for me.
Can anyone review an perhaps merge this code?

It would be nice to highlight the warning an critical messages, but i don't know how to do this.

**Comment by laf** [comment]
Sorry I wasn't around to help with this much but yeah - you've got it ;)

**Pull request merged**
