### PR TITLE
Add systemd unit file for the python poller service.

### PR DESCRIPTION
**Pull request by murrant**
Add systemd unit file for the python poller service.

### CODE REVIEW

**Comment by f0o** [comment]
I dislike having it in the top directory, it's already rather messy...
Can you move it to scripts?

**Comment by paulgear** [comment]
@f0o If we're going to say that, we probably need to say that for a bunch of other things too.

**Comment by laf** [comment]
Your both right but there's no reason to add more cruft to the / dir so +1 to move to another directory.

We also need a doc explaining how to use this.

**Comment by murrant** [comment]
I agree as well, If I get some time I'll move them into the scripts directory and update the documentation.

**Comment by murrant** [comment]
Moving the scripts will cause issues for users that have followed the documentation and made a link to the files.

**Comment by laf** [comment]
Can't believe we merged it in (probably me :/), we stopped symlinking stuff last time we had this issue with the cron file.

imho we send notices out about this and set a date to merge.

@murrant Can you update the docs to do cp X Y rather than ln -s (across the whole doc not just the new bit).

**Comment by murrant** [comment]
@laf will do

**Comment by murrant** [comment]
Perhaps we should send a notification about the service files moving so we don't break users that used ln -s.  I'm not sure how many users use the poller-service and might have linked the service files.

**Pull request merged**
