### PR TITLE
Daemonize

### PR DESCRIPTION
**Pull request by f0o**
#1068 
Query me on IRC for access to a test setup using this daemon as of <now> 23.05.2015/22:20 UTC including Syslog and auto-detection of service- and bill-jobs.

Docs to be updated later.

Please hold this PR on wait until tested thoroughly

### CODE REVIEW

**Comment by f0o** [comment]
Explanation of scruts errors:

`It is not recommended to output anything before PHP's opening tag in non-template files.`: This is an executable, it requires the interpreter tag.

`The variable $out does not seem to be defined for all execution paths leading up to this point.`: The variable is defined in both conditions of the if, Although if type is neither 'exec' nor 'include' then it's uninitialized. I can fix this if requested.

`The parameter $sig is not used and could be removed.`: It is used by the PHP internal callback from the signal-handler.

`It seems like you are loosely comparing two booleans. Considering using the strict comparison === instead.`: In case an interrupt occurs it will return an integer.

**Comment by laf** [comment]
I've been running this at home for a couple of days now and it's been perfect. I'm not doing alerting or billing from that install though. If you don't expect any more updates other than bug fixes then I'd be happy to push this out to works install to test in a bigger environment.

**Comment by f0o** [comment]
I will push one small update to enable time-sync, so that the 5m-interval jobs will happen at 0,5,10,... and same for the other jobs.

It's to make it more 'understandable' or 'predictable' when a job fires.

**Comment by laf** [comment]
Let me know when it's pushed and I'll test on a bigger scale.

**Comment by f0o** [comment]
Dont merge this in just yet, I still got a couple of things that got in afterwards. (apart from docs)
   Init-script for CentOS
   Jobs run at <60s intervals (alerts for instance)

**Comment by laf** [comment]
Give me a shout when you've updated.

**Comment by f0o** [comment]
Squashed the commits into a big snapshot.

Only Docs missing to prevent it from merge :)

**Comment by f0o** [comment]
@laf guess what's done :)

**Comment by laf** [comment]
Seeing as your commented on this then the daemon :)

**Comment by f0o** [comment]
collides with #1220 - Rebasing to depend on it.

**Pull request closed without merging**
