### PR TITLE
Rename JiraServiceManagement.php to Jiraservicemanagement.php

### PR DESCRIPTION
**Pull request by gil-obradors**
Quick fix to #15716. Filenames at "LibreNMS\Alert\Transport\" must not be PascalCase, only the first letter can be uppercase.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Seems that it improves but does not solve completely the issue. Is it enough on your setup ?

**Comment by gil-obradors** [comment]
Yes, I have edited and saved Alert transports and rules just now.

**Comment by gil-obradors** [comment]
ah Ok, I see, the PHP Class name must following this name rules.

**Comment by gil-obradors** [comment]
ah Ok, I see, the PHP Class name must following this name rules.

**Review by murrant — APPROVED** [review]

**Pull request merged**
