### PR TITLE
docker stat support

### PR DESCRIPTION
**Pull request by 0xbad0c0d3**
With this "simple" changes LibreNMS will have "docker application" to monitor docker containers with docker stat command
https://github.com/librenms/librenms-agent/pull/307

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Awesome! Thanks for your contribution

Do you mind pushing the extend script to https://github.com/librenms/librenms-agent ?

Nice work. Im going to test this asap!

**Comment by 0xbad0c0d3** [comment]
> Awesome! Thanks for your contribution
> 
> Do you mind pushing the extend script to https://github.com/librenms/librenms-agent ?
> 
> Nice work. Im going to test this asap!

done: https://github.com/librenms/librenms-agent/pull/307

**Comment by murrant** [comment]
Needs the docs to be updated with instructions for the agent.

**Comment by Cormoran96** [comment]
@0xbad0c0d3, I create the doc for you:
https://github.com/0xbad0c0d3/librenms/pull/1

**Comment by SourceDoctor** [comment]
@0xbad0c0d3 please update Applications Docs and resolve merge conflicts. Thx

**Comment by murrant** [comment]
Closing due to lack of response.  Feel free to reopen.

**Pull request closed without merging**
