### PR TITLE
Add device OS detection support for Accedian MetroNODE AEN-1000-* Gig…

### PR DESCRIPTION
**Pull request by nwautomator**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

…abit NIDs and AMO-10000-* 10 Gig NIDs. fixes: #5018

### CODE REVIEW

**Comment by laf** [comment]
str_contains accepts arrays so you can do `str_contains($sysDescr, array('one', 'two'))`

Also needs unit tests as per the other pull request.

**Comment by laf** [comment]
Are they the full sysDescr values returned that you've put in the test units?

Can you also add the output of sysObjectId for the test units.

**Comment by laf** [comment]
@nwautomator any update?

**Comment by nwautomator** [comment]
The output of sysDescr:

For AEN devices:  .1.3.6.1.2.1.1.1.0 = STRING: "AEN-1000-GE"
For AMO devices: .1.3.6.1.2.1.1.1.0 = STRING: "AMO-10000-LT-S"

The output of sysObjectID is the same for both devices: 

.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.22420.1.1

It looks like I should use .1.3.6.1.4.1.22420.1.1 in both unit test files, correct?

**Pull request merged**
