### PR TITLE
Add memory readings for Draytek OS

### PR DESCRIPTION
**Pull request by Sweeny42**
Draytek use a custom OID to define their devices memory usage, defined here: https://www.draytek.com/support/knowledge-base/5517

This commit includes a mempool definition with the new memory OID `1.3.6.1.4.1.7367.3.7` and relevant LibreNMS tests

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @Sweeny42 
Thanx for you PR. Tests need to be updated now. Could you try to do it ? if not, I'll help you.

**Comment by PipoCanaja** [comment]
> Hi @PipoCanaja, I've added the requested tests and rebased the changes, hopefully everything should now be there for your review. Please do let me know if there's anything further I need to commit.

Hi @Sweeny42 
Almost all good, only the JSON from `draytek_vigor2962.snmprec` is missing.

**Comment by Sweeny42** [comment]
Hi @PipoCanaja,
Ahh yes, my apologies! That should now be included.

Thank you for the info, I will remember for next time, it's a force of habit and as you say can be dangerous.

**Comment by PipoCanaja** [comment]
Hi @Sweeny42 
Looks good to me ! Thanx and congrats for your first PR in LibreNMS repo :)

**Review by PipoCanaja — APPROVED** [review]

**Pull request merged**
