### PR TITLE
Tidy up tripplite os polling.

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
How come the MIB names have been moved to he oid? I'm not a fan of that way personally

**Comment by murrant** [comment]
Oh, I am, allows for easy mixing of MIBs, but can change it back.  I was looking into my poweralert devices to see why they didn't have platform info.  Turns out they just suck and don't answer on any of these oids...

**Comment by laf** [comment]
You can just pass multiple mibs with IF-MIB:SNMPv2-MIB

**Comment by murrant** [comment]
True, but I like the full OID name, it probably saves NetSNMP from searching for the oid.

**Pull request closed without merging**
