### PR TITLE
INSERT SELECT to fix async polling duplicates in locations table

### PR DESCRIPTION
**Pull request by drakej**
This also includes my agreement to the contributor agreement

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
Yes
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
Yes

Fixes: #4930

### CODE REVIEW

**Comment by laf** [comment]
Thanks for contributing. All looks good aside from the issue flagged in travis:

https://travis-ci.org/librenms/librenms/jobs/173090191

You can run ./scripts/pre-commit.php to test locally (take a look at our docs).

**Comment by laf** [comment]
It's also worth submitting pull requests from new branches, we can then help fix issues like this - doing it from master can lead to a bit of git pain on your side

**Comment by drakej** [comment]
Hi Laf. I did run the pre-commit.php script but it was spitting out a bunch of unrelated warnings about snmp values. I figured I was missing some dependency but that it wasn't an issue given the code doesn't affect snmp in any way. I'll make sure in the future to satsify all dependencies for it, but I don't know what tripped up the failure on a tab since I did initially commit with a tab but I double checked and removed it. Maybe I missed another.

**Comment by laf** [comment]
Travis tells you the issue (pre-commit should as well- the things for snmp might be that you need dependencies - see http://docs.librenms.org/Developing/Validating-Code/ for setup info.

```
FILE: ...ravis/build/librenms/librenms/includes/polling/functions.inc.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 508 | ERROR | [x] Spaces must be used to indent lines; tabs are not
     |       |     allowed
```

**Comment by laf** [comment]
@drakej We can't merge this until Travis is fixed not because we don't want to but because we have it set so that travis has to pass before github allows the merge.

**Comment by murrant** [comment]
This is fine, but I prefer to fix this at the database schema level, disallowing duplicates there.

**Pull request closed without merging**
