### PR TITLE
Minor alerting addons

### PR DESCRIPTION
**Pull request by f0o**

### CODE REVIEW

**Comment by Mattz0r** [comment]
Thanks for sorting this out :) hopefully will get my installation up to where I need it (mostly) once this has been merged <3

**Comment by laf** [comment]
Testing on local install

**Comment by laf** [comment]
A scrut issue needs to be checked.

Also, is it worth changing else if to elseif. We use elseif pretty much everywhere else and I think last time we checked there was a difference.

**Comment by f0o** [comment]
Not sure about the `else if` vs `elseif` to be honest.
@Mattz0r can you test this please to see if `{calc}` works like expected?

**Comment by Mattz0r** [comment]
Sure, will do some testing and let you know how it goes.

**Comment by Mattz0r** [comment]
https://imgur.com/4Wm2dam - Looking good!!

**Comment by f0o** [comment]
badass alert mail template :+1:

**Comment by Mattz0r** [comment]
The Recovery part of it doesn't work:

https://imgur.com/vBF1ENT

**Comment by Mattz0r** [comment]
OK, the aspect of what is described, does work. Recovery is something different. Will raise issue for it.

**Comment by laf** [comment]
The majority of our code (looks like over 90%) uses elseif so it would be good to standardise on that still.

**Comment by f0o** [comment]
No problem :)

**Comment by Mattz0r** [comment]
I'm not quite sure the %diff section works though. I've also realised that upon the hourly re-alert, the information is as per the original graph attachments, it doesn't seem to update the graph timestamp, even though I'm using: 
 src="http://domain.tld/graph.php?to=%value.poll_time&from=end-6h&id=%value.port_id&type=port_bits&legend=no&height=150&width=500" for the image include.

**Comment by laf** [comment]
That url should provide a dynamic graph so if within your mail client you refresh the email then the graph should update.

**Comment by laf** [comment]
Been running this with basic rule all day. No issues from me so :+1:

**Comment by f0o** [comment]
@Mattz0r `%value.poll_time` wont change the entire %faults object is a static snapshot of the tables.
it's only updated when a condition worsen/betters, so on followup-messages.

`%diff` is also only populated if a condition worsens, this does not mean that a port is 'more over threshold' but that a 2nd port became 'over threshold' as well

**Comment by ekoyle** [comment]
I agree that it makes sense to use elseif for consistency, however there is
no technical reason for doing so.

According to the PHP docs (
http://php.net/manual/en/control-structures.elseif.php ), they are
identical unless you use:

```php
...
elseif (condition):
   statement;
...
```
syntax (ie. no curly braces), in which case `else if` will cause a parse
error.

-- 
Eldon Koyle

**Comment by laf** [comment]
Over 90% of our code uses elseif and is in our standards doc so no point in introducing code that doesn't meet that or not changing code touched by a PR.

**Comment by f0o** [comment]
@Mattz0r reviving this thread with regards to the call for examples on the mailing list, do you mind publishing your templates on our mailing list with the goal to have them as reference in our docs?

**Comment by Mattz0r** [comment]
Oh hey, yeah - Where would I publish them too? - I'm still awaiting the code to show the differences in alerts upon recover, etc.. but the templates are pretty much good to go I think.

**Comment by f0o** [comment]
Best would be to post them to the mailinglist on the thread, if you arent on the ML I can proxy it for you too

**Comment by Mattz0r** [comment]
@f0o - Yeah, I'm not on the ML - I'll pastie them and send you the links via IRC.

**Comment by Mattz0r** [comment]
@f0o  - Posted here: https://groups.google.com/forum/#!topic/librenms-project/sklwLu3arK0

**Pull request merged**
