### PR TITLE
Add HipChat v2 support

### LINKED ISSUE #1688: Update Hipchat transport to use API 2.0 by default
Update hipchat transport to support their new 2.0 API by default and update the documentation for it too.

### PR DESCRIPTION
**Pull request by jcbailey2**
Modified the HipChat transport to use the v2 API (and resolve #1688).

Atlassian is deprecating the v1 API, so I have not retained backwards compatibility.

### CODE REVIEW

**Comment by paulgear** [comment]
Seriously?  They called their API endpoint "bork"?

**Comment by jcbailey2** [comment]
The subdomain for the API endpoint is actually specific to my HipChat account, so I substituted that piece of personal information.

If someone registered the company ID "bork" with HipChat, they'd actually have that as an API endpoint..

**Comment by laf** [comment]
Will this not stop v1 working for those who have it setup?

We may need to think a bit more about how to do this.

**Comment by jcbailey2** [comment]
It will cause v1 to stop working. The v2 API is just different enough.

I could either request an API version (or try to auto detect it from the URL), but then there would be things such as the room ID that would no longer be required and need to be removed from the UI in this case. The backend would be straightforward, but that seems like a fair bit of UI complexity for a deprecated API.

What about splitting the v2 API into a different transport (ie. "hipchatv2") and leave the v1 API alone/deprecate it. This could work fine as long as the old transport is eventually sunset.

Thoughts?

**Comment by Rosiak** [comment]
We need it to be compatible with v1 since a lot of people are still using it.

**Comment by paulgear** [comment]
@jcbailey2 I think "hipchatv2" makes good sense.  Then at some point we can deprecate hipchat v1 support.

**Comment by laf** [comment]
Indeed, :+1: for hipchatv2. If you need any help with that then let me know.

**Comment by jcbailey2** [comment]
I'll fork to another transport. Might not be until the weekend before I can have a new commit ready.

**Comment by f0o** [comment]
Cant we have either a config option or a transport option switching between v1 and v2 with default in v1 ?

On 10 December 2015 23:18:44 CET, Jonathan Bailey <notifications@github.com> wrote:
>I'll fork to another transport. Might not be until the weekend before I
>can have a new commit ready.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms/pull/2587#issuecomment-163765810

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laf** [comment]
@f0o it's going to be a new transport as some options are no longer compatible / relevant between the two.

**Comment by f0o** [comment]
oki

**Comment by f0o** [comment]
Closing and awaiting new PR for the new transport :)

**Comment by shimamizu** [comment]
Did v2 support ever get rolled out?

**Comment by shimamizu** [comment]
And if not, can I easily pull this branch into mine so we can use v2?

**Pull request closed without merging**
