### PR TITLE
Fix duplication of processor entries & limit length of type

### PR DESCRIPTION
**Pull request by EinGlasVollKakao**
Hello,

while adding support for a new device i stumbled upon a bug: in LibreNMS my device displayed two processors, even though it only has one.

So I looked at the code and found the following foreach loop, which I suppose should only limit the length of the description to 64, but after it the $processors array had an additional processor-entry.
image image

But when I also saw these duplicate entries with a device that reports the correct number of CPUs, I thought this couldn't be the problem...

After a little digging, I think I found out why this affected me, but not other OSes: Before saving the processor to the database, it checks for an existing entry with the same values but this check didn't work for my processor, as the type of it was longer than 16 characters and was therefore truncated in the database, but not in the model itself.

So this bug only occurs if the processor type is to long.

This PR fixes the duplication of processor entries (I'm not that good at PHP, but I think the `$processors[] = $processor` assignment isn't needed and causes the duplicate entries) and also limits the type property to 16 characters.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by EinGlasVollKakao** [comment]
I think tests failed because the test data has this problem with duplicate CPU entries.

**Comment by murrant** [comment]
How could this only affect one device? Something seems fishy here.

**Comment by murrant** [comment]
It might be good to add `"maxLength": 16` to the type field in discovery_schema.json

**Comment by EinGlasVollKakao** [comment]
> How could this only affect one device? Something seems fishy here.
Probably because the processor type does not have more than 16 characters anywhere else.

**Review by murrant — APPROVED** [review]
Nice work, lgtm

**Pull request merged**
