### PR TITLE
fix: ePMP gps state

### PR DESCRIPTION
**Pull request by pheinrichs**
fixes: #8567

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by pheinrichs** [comment]
Any idea why this would have stopped working? The above does resolve, just curious is all.

**Comment by laf** [comment]
The `{{ $index }}` at the end isn't needed (never has and I'm not sure if it would have done anything or caused issues).

Specifying the index of 0 shouldn't be needed and `{{ $index }}` should work fine there - are you sure you needed to change that?

**Comment by murrant** [comment]
@laf `{{ $index }}` isn't needed here, I allowed it in the new processors stuff.  I'll try to make it all consistent sometime.

**Comment by pheinrichs** [comment]
Gotcha, so it was probably running 21.1.1.7.{{$index}}.{{$index}}'. So it should be okay like this?

**Comment by laf** [comment]
Yes that should be fine although I think you should do `index: {{ $index }}` instead of `index: 0`

**Comment by laf** [comment]
> @laf {{ $index }} isn't needed here, I allowed it in the new processors stuff. I'll try to make it all consistent sometime.

@murrant Would be good to standardise them although I don't think processors supports not having the `{{ $index }}` right now - didn't work for me earlier at least.

**Comment by laf** [comment]
@pheinrichs Does that change to index still work for you so we can merge?

**Comment by pheinrichs** [comment]
@laf Rediscovered and polled were a success. Good to go.

**Pull request merged**
