### PR TITLE
Cisco sensor discovery fixes

### PR DESCRIPTION
**Pull request by robwilkes**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Severity and Relation varies between devices.
We have in our environment IOS, IOS-XE, NX-OS, ASA.

NX-OS dbm thresholds not being set as the Relation is greaterThan and lessThan, not greaterOrEqual and lessOrEqual.

IOS-XE dbm high thresholds not being set as the Severity is critical, not major.

Most sensors do not have low temperature thresholds via SNMP, therefore LibreNMS arbitrarily guesses them. In our environment these low thresholds were too high and frequently triggering alarms as system loads change.

SFPs return low thresholds of 0 and -5 degrees, from an electrical engineering point of view these seem practical. So where no low threshold is detected using these values. LibreNMS seems to interpret 0 as null however, so using -1 instead of 0.

### CODE REVIEW

**Comment by robwilkes** [comment]
The codeclimate 'deeply nested control flow statements' is pre-existing. I'm not rewriting the entire module. Hopefully everything else is ok. Thanks.

**Comment by PipoCanaja** [comment]
Hi @robwilkes 
Could you please have a look at https://github.com/librenms/librenms/pull/11077/checks?check_run_id=412033579 and ensure that Travis is validated ? We can't merge until Travis is happy. CodeClimate is only giving advices but is not mandatory). 

Basically, you need to re-run some of the tests cause they still have the old value, and they don't validate anymore. 

Thanx

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Comment by dsgagi** [comment]
Hello,
it seems that this PR introduced a little bug when HIGH threshold value is empty. High threshold gets assigned the same value as LOW threshold after discovery.

Screenshot at 2020-04-29 18-52-58

```
Discover sensor: .1.3.6.1.4.1.9.9.91.1.1.1.1.4.3205403, 3205403, cisco-entity-sensor, Module 0/0/CPU0 - 0/0/CPU0, snmp, 10, 1, 3205403, 29.7, (limits: LL: -5, LW: -1, W: , H: )  

SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= ? AND `sensor_class` = ? AND `device_id` = ? AND sensor_type = ? AND `sensor_index` = ? ["snmp","temperature",875,"cisco-entity-sensor","3205403"] 1.26ms] 
  

SQL[SELECT * FROM `sensors` WHERE `sensor_class` = ? AND `device_id` = ? AND `sensor_type` = ? AND `sensor_index` = ? ["temperature",875,"cisco-entity-sensor","3205403"] 1.37ms] 
  

SQL[UPDATE `sensors` set `sensor_limit`=? WHERE `sensor_id` = ? [-5,14048] 0.34ms] 
  

H
( 1 updated )  

SQL[insert into `eventlog` (`device_id`, `reference`, `type`, `datetime`, `severity`, `message`, `username`) values (?, ?, ?, ?, ?, ?, ?) [875,null,"sensor","2020-04-29 15:48:05",3,"Sensor High Limit Updated: temperature cisco-entity-sensor 3205403 Module 0\/0\/CPU0 - 0\/0\/CPU0 (-5)",""] 0.3ms] 
```

I think that the culprit is the part of code below, from `includes/discovery/functions.inc.php`.
```
        // Fix high/low thresholds (i.e. on negative numbers)
        if ($low_limit > $high_limit) {
            list($high_limit, $low_limit) = array($low_limit, $high_limit);
        }
```

Cheers

**Comment by robwilkes** [comment]
Which device is this? I didn't see it with any of the devices on our
environment

**Comment by dsgagi** [comment]
This happened on our three ASR 9k (IOS XR 6.4.2) and three ASR 1006 (IOS XE 15.5(3)S7b).

**Comment by murrant** [comment]
@dsgagi can you send a pull request for the fix?

**Pull request merged**
