### PR TITLE
Improved sensors for the Panduit PDU device.

### PR DESCRIPTION
**Pull request by kruczek8989**
Adding temperature and humidity sensors for the Panduit PDU device.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kruczek8989** [comment]
Adding support for Huawei switches with YunShan software - is another version of the same VRP.

**Comment by kruczek8989** [comment]
> Please add test data so we can ensure your change is not broken in the future. Read the docs to find out how: https://docs.librenms.org/Developing/os/Test-Units

Which specific files from the performed tests should I attach?

**Comment by murrant** [comment]
You are missing either an updated snmprec or additional snmprec.

**Comment by PipoCanaja** [comment]
Hi @kruczek8989 
We need to fix these tests for this PR to be ready. 
Could you please : 
- revert to original those 2 files: 
`tests/snmpsim/panduit.snmprec` and `tests/data/panduit.json`
- create a new variant 
`tests/snmpsim/panduit_improved.snmprec` and `tests/data/panduit_improved.json`

And starting from here, we'll see if something else is needed.

**Comment by PipoCanaja** [comment]
Hi @kruczek8989 
Do you have difficulties to revert the files `tests/snmpsim/panduit.snmprec` and `tests/data/panduit.json` ? 
From CLI, you can do `git checkout master tests/snmpsim/panduit.snmprec tests/data/panduit.json` and `git commit -m "revert" tests/snmpsim/panduit.snmprec tests/data/panduit.json` to get that step done.

**Pull request closed without merging**
