### PR TITLE
[transceivers] Eltex MES23xx Transceiver support

### PR DESCRIPTION
**Pull request by Npeca75**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
I'm assuming you couldn't convert any more of the sensors to yaml @Npeca75?

**Comment by Npeca75** [comment]
> I'm assuming you couldn't convert any more of the sensors to yaml @Npeca75?

hi @laf 
problem with RADLAN is that indexes are not at last position, for example:
`'.1.3.6.1.4.1.89.90.1.2.1.3.' . $ifIndex . '.6';`
this will not work in YAML

**Comment by PipoCanaja** [comment]
You should be able to still use YAML with https://docs.librenms.org/Developing/os/Health-Information/#simple-health-discovery (search the subindex part). You can see a few examples in other YAML files.

**Comment by Npeca75** [comment]
> You should be able to still use YAML with https://docs.librenms.org/Developing/os/Health-Information/#simple-health-discovery (search the subindex part). You can see a few examples in other YAML files.

hi @PipoCanaja 

i tried simple state LOS sensor

```
                -
                    oid: rlPhyTestGetResult
                    value: rlPhyTestTableLOS
                    num_oid: '.1.3.6.1.4.1.89.90.1.2.1.3.{{ $index }}.11'
                    group: 'SFP'
                    descr: 'SFP #{{ $index }} LOS'
                    index: 'rlPhyTestTableLOS.{{ $index }}'
                    states:
                        - { value: 0, descr: False, graph: 1, generic: 0 }
                        - { value: 1, descr: True, graph: 1, generic: 2 }

```

and the debug output is

```
  '108.rlPhyTestTableDataReady' => 
  array (
    'rlPhyTestGetResult' => '1',
  ),
  '108.rlPhyTestTableLOS' => 
  array (
    'rlPhyTestGetResult' => '1',
  ),
```

so, no, it is not working

**Comment by PipoCanaja** [comment]
As I mentionned, you need to use the subindex logic as described. Something like this : 
```
                -
                    oid: rlPhyTestGetResult
                    value: rlPhyTestTableLOS
                    num_oid: '.1.3.6.1.4.1.89.90.1.2.1.3.{{ $index }}'
                    group: 'SFP'
                    descr: 'SFP #{{ $subindex0 }} LOS'
                    index: 'rlPhyTestTableLOS.{{ $subindex0 }}'
                    states:
                        - { value: 0, descr: False, graph: 1, generic: 0 }
                        - { value: 1, descr: True, graph: 1, generic: 2 }
```

What does the debug says with this ?

**Comment by Npeca75** [comment]
> What does the debug says with this ?

same as prev
sensor is not detected

**Comment by murrant** [comment]
@Npeca75 I believe this works:
```yaml
                -
                    oid: rlPhyTestGetTable
                    value: rlPhyTestGetResult
                    num_oid: '.1.3.6.1.4.1.89.90.1.2.1.3.{{ $subindex0 }}.11'
                    group: 'SFP'
                    descr: 'SFP #{{ $subindex0 }} LOS'
                    states:
                        - { value: 0, descr: False, graph: 1, generic: 0 }
                        - { value: 1, descr: True, graph: 1, generic: 2 }
                    skip_values:
                        -
                            oid: index
                            op: not_regex
                            value: '/^\d+\.rlPhyTestTableLOS$/'
```

**Comment by Npeca75** [comment]
hi @murrant 
ok, it is working, sort of ...
```
                -
                    oid: rlPhyTestGetTable
                    value: rlPhyTestGetResult
                    num_oid: '.1.3.6.1.4.1.89.90.1.2.1.3.{{ $subindex0 }}.11'
                    group: 'transceiver'
                    index: 'SfpLOS{{ $subindex0 }}'
                    descr: 'SfpLOS-{{ $entPhysicalName }}'
                    entPhysicalIndex: '{{ $subindex0 }}'
                    entPhysicalIndex_measured: port
                    states:
                        - { value: 0, descr: False, graph: 1, generic: 0 }
                        - { value: 1, descr: True, graph: 1, generic: 2 }
                    skip_values:
                        -
                            oid: index
                            op: not_regex
                            value: '/^\d+\.rlPhyTestTableLOS$/'
```

but
i could not extract PORT NAME
ifName, ifAlias, ifDescr, entPhysicalName
none of these work

debug output:

```
  '105.rlPhyTestTableLOS' => 
  array (
    'rlPhyTestGetType' => '11',
    'rlPhyTestGetStatus' => '2',
    'rlPhyTestGetResult' => '0',
    'rlPhyTestGetUnits' => '2',
    'rlPhyTestGetAlarm' => '1',
    'rlPhyTestGetTimeStamp' => '22-Oct-2024 07:08:37',
```
....
```
YamlDiscovery: No variable available to replace entPhysicalName index: 105.rlPhyTestTableLOS  
```

**Comment by Npeca75** [comment]
ok @murrant 

got it
```
descr: 'SfpLOS-{{ $ifName:0 }}'
```

**Comment by Npeca75** [comment]
@murrant , @PipoCanaja 

could someone point me in right direction ?

```
1) LibreNMS\Tests\YamlSchemaTest::testDiscoveryDefinitionSchema
eltex-mes23xx.yaml does not validate. Violations:
[modules.sensors.state.data[5].num_oid] Does not match the regex pattern ^(\.\d+)+(\.?\{\{ \$(index|str_index_as_numeric) \}\})?(\.\d+)*$
[modules.sensors.state.data[5].states[0].descr] Boolean value found, but a string is required
[modules.sensors.state.data[5].states[1].descr] Boolean value found, but a string is required
```

first time to see this kind of error

**Comment by PipoCanaja** [comment]
You need to correct num_oid as so : 
`num_oid: '.1.3.6.1.4.1.89.90.1.2.1.3.{{ $index }}'`

And states with simple quotes : 
```
                    states:
                        - { value: 0, descr: 'False', graph: 1, generic: 0 }
                        - { value: 1, descr: 'True', graph: 1, generic: 2 }
```

And it should be better.

**Comment by Npeca75** [comment]
ok @PipoCanaja , @murrant 

lets suppose that LOS -> state sensor is OK in YAML

now, next is volt/temp etc
fetching value is working, following @murrant example
but ...
threesholds does not
```
ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.107.temperature = 80
ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.107.supply = 3600000
ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.107.txBias = 80000
ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.107.txOutput = 2000
ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.107.rxOpticalPower = -1001
```

as you could see, $index is in the middle of OID

i tried variations
```
                    low_limit: '.1.3.6.1.4.1.35265.1.23.53.1.2.1.6.{{ $subindex0 }}.0'
                    low_warn_limit: 'ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdLowWarning.{{ $index }}'
                    warn_limit: ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.0
                    high_limit: 'ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighAlarm.{{ $subindex0 }}.0'
```

but no, there is no threeshold value
```
Sensor fetched value: 48  
Discovered Sensor: .1.3.6.1.4.1.89.90.1.2.1.3.107.5, SfpTemp107, eltex-mes23xx, SfpTemp-te1/0/3, snmp, 1, 1, 107, 48, (limits: LL: , LW: , W: , H: ), rrd_type = GAUGE 
```

any idea ?

**Comment by laf** [comment]
When I added support for something recently, I found I had to add the high/low OIDs and MIBs to the pre-cache section

**Comment by murrant** [comment]
@laf correct, thresholds are in a different table. you need to fetch that data to be able to pull it in.

**Comment by Npeca75** [comment]
sorry @murrant @laf 
but no, it is NOT working because $index in the middle of OID

`ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.107.temperature = 80`

yaml:
```
        pre-cache:
            data:
                -
                    oid:
                        - ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdLowWarning
                        - ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning
```

```
                -
                    oid: rlPhyTestGetTable
                    value: rlPhyTestGetResult
                    num_oid: '.1.3.6.1.4.1.89.90.1.2.1.3.{{ $subindex0 }}.5'
                    group: 'transceiver'
                    index: 'SfpTemp{{ $subindex0 }}'
                    descr: 'SfpTemp-{{ $ifName:0 }}'
                    low_limit: '.1.3.6.1.4.1.35265.1.23.53.1.2.1.6.{{ $subindex0 }}.0'
                    low_warn_limit: 'ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdLowWarning.{{ $subindex0 }}.0'
                    warn_limit: 'ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighWarning.0'
                    high_limit: 'ELTEX-MES-PHYSICAL-DESCRIPTION-MIB::eltPhdTransceiverThresholdHighAlarm.{{ $subindex0 }}.temperature'
                    entPhysicalIndex: '{{ $subindex0 }}'
                    entPhysicalIndex_measured: ports
                    skip_values:
                        -
                            oid: index
                            op: not_regex
                            value: '/^\d+\.rlPhyTestTableTransceiverTemp$/'
```

as you see, i tried
$subindex0.0 (.0 is temperature)
$subindex0.temperature

for thresholds, but no

```
Sensor fetched value: 45  
Discovered Sensor: .1.3.6.1.4.1.89.90.1.2.1.3.107.5, SfpTemp107, eltex-mes23xx, SfpTemp-te1/0/3, snmp, 1, 1, 107, 45, (limits: LL: , LW: , W: , H: ), rrd_type = GAUGE  
```

limits are NULL


could we please stop demanding YAML in this case ?

**Comment by PipoCanaja** [comment]
Hi @Npeca75 
I can understand you feel a little bit frustrated, but so are we. 
If you look at the debug data, you will see what the code is trying to fetch, and you may find if we face a bug, or if (most probably) a patch should be written to fix this. 
And at the end of the day, it will be simpler for you to add support for devices, and to all the community to maintain LibreNMS. 
Thx

**Comment by Npeca75** [comment]
> I can understand you feel a little bit frustrated, but so are we.

from my point of view ...
new PHP code, dropped 'pre-cache' and 'modern' snmp functions is enough for this round to be merged and eltex could have SFP support

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
Definitely an improvement, thanks @Npeca75

**Pull request merged**
