### PR TITLE
Asterisk app: add IAX2 peer graphs

### PR DESCRIPTION
**Pull request by josephtingiris**
* It's an entirely new graph and will not break existing graphs.
* The asterisk extend script must be updated to provide the appropriate poller data.
* The PR for librenms-agent/snmp/asterisk is here: 

https://github.com/librenms/librenms-agent/pull/274

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Before merge, I have a question on the agent ( https://github.com/librenms/librenms-agent/pull/274/files )

**Comment by Jellyfrog** [comment]
Could you also generate test data for this? I \*think* you do the same way as described above ^

**Comment by PipoCanaja** [comment]
In fact, there is no test data for apps as far as I can tell. At least I don't see how we could do ...

**Comment by josephtingiris** [comment]
I think I've got it figured out ... it's working locally, for me.  freeradius is a good example.

**Comment by josephtingiris** [comment]
Getting this test data (or any test data with 1.3.6.1.4.1.8072) to pass pre-commit requires https://github.com/librenms/librenms/pull/11085

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
