### PR TITLE
Support of "disable alerting" in availability map and device summary widget

### PR DESCRIPTION
**Pull request by louis-oui**
image

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by louis-oui** [comment]
ready to merge

**Comment by louis-oui** [comment]
Thank you @kkrumm1

**Comment by kkrumm1** [comment]
this still needs some testing we are having users report that normal users none admins cant see certain parts of the dashboard and widgets. I'm starting to wonder if this has anything to do with these recent commits.

**Comment by louis-oui** [comment]
> this still needs some testing we are having users report that normal users none admins cant see certain parts of the dashboard and widgets. I'm starting to wonder if this has anything to do with these recent commits.

Is there any other issue apart from the alerts one ? Alerts issue was not due my change.

**Comment by kkrumm1** [comment]
> > this still needs some testing we are having users report that normal users none admins cant see certain parts of the dashboard and widgets. I'm starting to wonder if this has anything to do with these recent commits.
> 
> Is there any other issue apart from the alerts one ? Alerts issue was not due my change.

That's all I have seen is from community forums. It would help us out if you can help troubleshoot that one. 
This PR I cant merge seems Travis is stuck I'm not sure how to fix that atm.

**Comment by louis-oui** [comment]
@kkrumm1 thank you for merging

**Comment by kkrumm1** [comment]
> @kkrumm1 thank you for merging

Thank you for all your commits, this is what makes librenms possible.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
