### PR TITLE
Modify Menubar

### LINKED ISSUE #2168: Enhancement: Global menu makeover
Perhaps remove the text from the logo so only the square is visible?
Perhaps remove the font-awesome icons in the menubar

menubar23
menutest2

### PR DESCRIPTION
**Pull request by adaniels21487**
- Small Screens - Icon only - Wrap the label in a span with hidden-sm
- Medium Screen - Text only - add hidden-md to the icon
- Large Devices - shrink the left/right padding on .nav>li>a to 10px.

Resolves #2168.

### CODE REVIEW

**Comment by Rosiak** [comment]
For some reason the text from the "plugins" icon is removed, so only the icon is displayed(No matter the screen size).
screen shot 2015-11-18 at 09 56 52


Other than that, I think we should keep the LibreNMS icon, when resizing the screen.
screen shot 2015-11-18 at 09 56 09

But I like the work that has been done!

**Comment by adaniels21487** [comment]
Hi @Rosiak,
Are you suggesting to break the current image into 2 (Icon and Text) and always keep the icon and display the text only if the user is on a large screen?
Currently, this image is user configurable via `$config['title_image']`. Is the intention to have our icon fixed and our text or the users image configurable?

Also, the menubar has the following test: `if ($config['title_image'])`, but definitions.inc.php has the following:
```
if (!isset($config['title_image'])) {
    $config['title_image'] = 'images/librenms_logo_'.$config['site_style'].'.png';
}
```
I can't see any way `$config['title_image']` could be unset?
any objections to me removing the test?

Thanks,
Aaron

**Comment by laf** [comment]
I've not had a proper look at the PR so I'll just comment on this last bit.

You can unset($config['title_image']); in config.php. But you are right, we don't necessarily know what logo is used (plus we have a couple for different style navbars).

**Comment by laf** [comment]
@adaniels21487 - Thanks for giving the Webui some love :)

Had a proper look now. I'm a :+1: for this.

We probably should re-introduce the Plugins text as @Rosiak has mentioned.

**Comment by adaniels21487** [comment]
Plugins returns :)
Let me know if you want me to change/break up the icon.

Thanks,
Aaron

**Comment by laf** [comment]
You have my :+1: when you remove the config setting you added :)

**Comment by Rosiak** [comment]
:+1:  From here!

**Pull request merged**
