### PR TITLE
Updated XOS (Extreme) processor data to use correct OID

### PR DESCRIPTION
**Pull request by laf**
Please give a short description what your pull request is for

Updated the OID used for processor info on XOS devices, closes issue #12094

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
Oops, need to update the test data.

Reminder `./script/save-test-data.php -o xos -m processors`  should do the trick

**Comment by laf** [comment]
I'm guessing we should do a notification to let people know they will lose existing CPU data?

**Comment by Jellyfrog** [comment]
If the current data is wrong there is not much point :)

**Comment by laf** [comment]
Ok, I'll leave it unto you guys to approve/merge if you think this is the right approach.

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
