### PR TITLE
Added support for EDFA

### LINKED ISSUE #9826: New Device : EDFA SNMP Agent V2.0
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

https://p.libren.ms/view/2e858157#L16
https://p.libren.ms/view/9cd7b23e#L5
https://p.libren.ms/view/1218d526

EDFA SNMP Agent V2.0
https://p.libren.ms/view/886d01c3

Thanks,

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

### PR DESCRIPTION
**Pull request by jozefrebjak**
fixes #9826

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
@jozefrebjak check https://github.com/librenms/librenms/pull/9125

**Comment by jozefrebjak** [comment]
@TheGreatDoc  ok i will try to add oid of my edfa to this discovery and i will see what happen.

**Comment by jozefrebjak** [comment]
@TheGreatDoc  ok its almost the same, but you are using low and high limits, and it all done with php, but i am not getting all of the information i believe with #9125 here it is how its look like when i deleted .1 from discovery and used only .1.3.6.1.4.1.17409.1
image

and this how its look like with my PR

image


We dont have anything connected for now, it is in a testing stage. So i dont know if i need to remove this PR and use what is done or we rebuild it little bit.

**Comment by romsworld** [comment]
Hi,

Thanks a lot, I will test next week.

**Comment by romsworld** [comment]
Hi,

For OutputOpticalPower, could you change descr : Total Output Optical Power > Output Optical Power

For BIAS 1, I have 8600A, but i think the real value is 86mA.

Is ti possible to have green or red value for dbm ?

**Comment by TheGreatDoc** [comment]
> Is ti possible to have green or red value for dbm ?

You set this up in Device -> Edit -> Health. Set the high/low values.

**Comment by romsworld** [comment]
Hi,
Everything seems okay to me.
Is it necessary to do another test before going into production?

Thank you.

**Pull request merged**
