### PR TITLE
Implement OS specific information discovery

### PR DESCRIPTION
**Pull request by murrant**
That way it doesn't have to be fetched during polling
Also improve discovery process, os is only detected once, in the core module.
EXA is the test os, a couple improvements there.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@librenms/reviewers  I plan to merge this any thoughts/testing?

**Comment by SourceDoctor** [comment]
@murrant 
with this PR OS specific overlib on Devicelinks in Widgets doesn't work anymore.
Recognized on: Eventlog Widget and Top Interfaces Widget ... maybe more

**Comment by murrant** [comment]
@SourceDoctor how is it related?

**Comment by SourceDoctor** [comment]
@murrant  default overlib image is shown and not OS specific as it should
do a mouseover on a devicename of a switch and then mousover on a devicename of a server ...
you'll see same overlib, which shouldn't be

**Comment by murrant** [comment]
sure, but what causes that is my question ;)

**Comment by SourceDoctor** [comment]
therefore i have to take a deeper look into the code.
At moment i only limited it down to this PR :o) Just wondering also why this happens ...

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
