### PR TITLE
Added detection for CoreOS devices

### PR DESCRIPTION
**Pull request by crazy-max**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by crazy-max** [comment]
Oups i forgot to include tests, will be added asap

**Comment by laf** [comment]
Thanks for this. The tests require a json file as well, I've generated this for you if you could upload it to this PR:

https://p.libren.ms/view/raw/94c0f324

**Comment by crazy-max** [comment]
@laf I have added the json file

**Comment by crazy-max** [comment]
:tada::tada:

image

image

**Pull request merged**
