### PR TITLE
Add more Vigor series device support

### PR DESCRIPTION
**Pull request by jasoncheng7115**
Add more model support, For example Vigor 300b, 2960, 3900, AP903... Etc.

Vigor 3900 screenshots:

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jasoncheng7115** [comment]
Ho, there's something wrong with this modification. I'm going to fix it.

**Comment by jasoncheng7115** [comment]
Ok, have attached the test data (tests/snmpsim/draytek.snmprec)

**Comment by murrant** [comment]
If just adding additional os detection patterns, all we need is an snmprec with sysObjectID and sysDescr

**Comment by jasoncheng7115** [comment]
> If just adding additional os detection patterns, all we need is an snmprec with sysObjectID and sysDescr

Ok, I've learned it. Thanks for telling me how to do it.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
