### PR TITLE
Updated github apply/remove to clear route and view cache

### PR DESCRIPTION
**Pull request by laf**
When running apply or remove, we now clear the view and route cache via artisan command.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
‎optimize:clear‎ Will clear all caches instead

**Comment by laf** [comment]
That does more than just the routes and views, is that what we want?

```
  events .................................................................................................................................. 8ms DONE
  views ................................................................................................................................... 5ms DONE
  cache .................................................................................................................................. 32ms DONE
  route ................................................................................................................................... 2ms DONE
  config .................................................................................................................................. 1ms DONE
  compiled ................................................................................................................................ 2ms DONE

```

**Comment by murrant** [comment]
Yeah, if you are applying test code, you probably want to clear all caches.

**Comment by laf** [comment]
Updated now :)

**Pull request merged**
