### PR TITLE
Lazyload

### PR DESCRIPTION
**Pull request by travishegner**
This is a first stab at converting all graphs to be loaded lazily as they enter (just before actually) the view-port of the browser. I'm not completely satisfied with it yet, but it's a start. This is necessary to reduce web server load when viewing pages with many dozens of graphs.

A couple of quick notes:
 - The lazy loading library I'm using requires the img width and height attributes to be set. Unfortunately those are not known before hand as the dimensions passed to RRD tool are for the canvas, and not the overall image. Currently, I am setting the attributes to the dimensions requested for the canvas, and then removing the attributes after the image is loaded to prevent the browser from scaling it down.
 - I am doing some (hacky) work-arounds for the overlib calls because I don't think it's necessary or appropriate to lazily load the graph that appears on mouseover (it's already loaded lazily, and wrapping it with the JS library creates an annoying delay).

*What could be better?*
RRD tool has a command line option for "--full-size-mode", with which the dimensions specified are those for the final output image, and not only the canvas, the canvas is re-sized with whatever room is left. This would allow the interface to behave a little better (prevents the kind of jumping and re-scrolling as the page loads), but in most of the graphs makes the canvas almost illegible.

I like the way the graphs on the apps pages do not show legends except on 'zoom'. I believe the most appropriate way to fix the minor issues above, and to make the whole tool a bit more consistent, is to have the same behavior across the board. Doing so would allow the use of --full-size-mode, while keeping consistent canvas sizes, but to use --full-size-mode would require that every instance of graph size which overrides the default would have to be manually updated to prevent the final image size from being different than what it is today. These are design decisions that I will leave up to the project leaders to make.

Lastly, another version of generate_graph_tag() could/should be implemented to set up a lazily loaded graph (or the inverse) rather than forcing that to be default, but every call to that function would possible have to be touched. This would prevent the need for some of the hacky overlib workarounds I'm doing, and is probably the way to go, but I don't want to touch that much code on my first submission. If any of the other suggestions above are implemented, then that may be a good time to separate the lazy images into a separate function.

### CODE REVIEW

**Comment by laf** [comment]
trigger ci

**Comment by f0o** [comment]
On phone here so sry for brevity

I'd like seeing "--full-size-mode" being used. It's nonsense that we arent yet. It will also allow us to retry tackling zoomable graphs.

More comments to come when time allows it ;)

**Comment by f0o** [comment]
trigger ci

**Comment by laf** [comment]
Tested on desktop and mobile with no apparent side effects. Gets a :+1: from me as I've got a good number of devices with 200+ ports that are just a pain.

**Comment by laf** [comment]
Ok tested this on a larger install and one of the drawbacks is on the device specific page, the CPU / Memory and Traffic graphs at the top right only load when the rest of the page has so it makes it look like an issue.

This is more apparent on devices with a large number of ports but can be seen on the demo as well.

@travishegner Is this behavious something that can be altered so it doesn't appear like the page hasn't loaded?

**Comment by travishegner** [comment]
@laf, I see what you mean. Perhaps it would be wise to scale this back a bit, and explicitly choose which graphs get loaded lazily by implementing a separate function to do that. We can still make a giant performance impact where it counts, without altering /normal/ behavior too much. I'll try and get that implemented today.

**Comment by travishegner** [comment]
Alright, the latest commit removes some of the overlib hacks that I was doing to circumvent the forced lazy loading. Basically, now lazy loading is optional by calling "generate_lazy_graph_tag()" rather than "generate_graph_tag()", but non-lazy loading is still available via the latter function. I went through as much of the code as I could to change over to calling the lazy version of the function where it made sense.

Generally, you don't want lazy loading on anything inside of the overlib popup, as that is already lazy anyway and adds an unnecessary delay. There are a handful of graphs that are generated by other means... I switched a few of them, but I can guarantee that I did not get them all, nor do I have the ability to test them all. It will likely be an ongoing effort to convert many of the graphs to be lazily loaded where it makes sense, but at least I have some of the heaviest hitting pages done.

The framework is in place to lazily load *any* image. To do so only requires that your  tag have a class of 'lazy', and the 'width' and 'height' attributes be defined. For it to work optimally, the width and height attributes should match that of the final image dimensions as mentioned in the initial PR comments.

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Works well on the CI.
:+1:

**Comment by laf** [comment]
@travishegner Sorry this is going to need rebasing from the big update we've done.

If you like, I can do that and provide you a patch so you can just resubmit this?

**Comment by travishegner** [comment]
@laf, I heard...

That would be fantastic!

**Comment by laf** [comment]
https://dpaste.de/QOFn

I've left out the actual JS files - these need adding via subtree anyway: https://readthedocs.org/docs/librenms/General/Contributing/index.html?highlight=subtree#integrating-other-code

Once you've resubmitted this I'll give it another whirl.

**Comment by travishegner** [comment]
Thanks to @clinta for taking care of the patch and rebasing.

**Comment by f0o** [comment]
:+1:

**Pull request merged**
