### PR TITLE
tests: Tests for errors in mib files

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
@laf didn't make an attempt to fix any of the issues.  What do you think?

**Comment by murrant** [comment]
@laf `phpunit --group mibs`

**Comment by laf** [comment]
You've got that excluded though in phpunit.xml?

**Comment by murrant** [comment]
Yes, it takes awhile to run and has lots of failures.

I was thinking of it more as an optional tool, we could remove it from excluded if it is ever all cleaned up.

**Comment by murrant** [comment]
@laf  I changed my mind.  Removing duplicates is not safe.  I spot checked pbn + bdcom :(

**Comment by laf** [comment]
@murrant how come?

**Comment by murrant** [comment]
NMS-PROCESS-MIB might not be found  and it can't find a module it is importing because it is in a subdirctory.  Which isn't defined in all calls.  I'm just a little unsure.

**Comment by laf** [comment]
That mib only imports NMS-TC and NMS-SMI which are both in the root as well.

**Comment by murrant** [comment]
NMS-SMI imports PBN-ROOT, which is in pbn folder.

**Comment by laf** [comment]
Ok. How useful is this then :(

I'd really like to tidy it up. Maybe if we just do the rename for now?

**Comment by murrant** [comment]
I would like to merge the cleanup, just in a separate PR.

This is basically a tool to check mins for us, maybe we enabled it by default.

**Comment by murrant** [comment]
But I have some ideas to clean this up a little more.

**Comment by laf** [comment]
OK, merge away when you're ready.

**Pull request merged**
