### PR TITLE
Feature: Collect VRP Entity details in the Huawei MIB

### PR DESCRIPTION
**Pull request by PipoCanaja**
Hello

We collect 2 OIDs in the Huawei MIB to get part number in the Entity inventory. 

Bye
PipoCanaja
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi guys,

Refactoring the code according to CodeClimate suggestions may be a good idea but is beyond the scope of this change. It would need to be done for all OSes and not only VRP. 
That being said, if you have an idea on how you would like this to be done, let me know, and I can try to do something. 

Bye
PipoCanaja

**Comment by PipoCanaja** [comment]
Hello @laf 

Tried to add new data as well as updating vrp-5720 file. Seems that updating a file is not as easy as it looked like. Let me know if you prefer me to create a new one instead for 5720 or if I have a way to correct. 

Bye

**Comment by laf** [comment]
A new file will work ok as well.

**Comment by PipoCanaja** [comment]
All done this time. Both this PR and https://github.com/librenms/librenms/pull/8879 look OK

**Comment by laf** [comment]
At present I'm not sure why test data is having issues. We need to generate json data off the back of the snmprec but so far, they are all showing issues with ports :(

**Comment by murrant** [comment]
processor and mempool descriptions strings are too long for the database (and the webui)

**Comment by laf** [comment]
Well spotted.

I'm not sure what to do here, we don't want everything converting to text fields. We could limit the descr in the code to 64 chars but then if the column ever gets updated it is then out of sync.

I'd probably go for limiting the descr value that could be inserted. What do you think @murrant / @PipoCanaja

**Comment by PipoCanaja** [comment]
Hello,

I would suggest to put this PR in WIP while I unbox other VRP devices. I received then but did not start the tests. That will give me an idea if the other switch families are behaving the same, and will come back with hopefully with a way to shorten the string while keeping the interesting information.
 
So if you agree, I turn to WIP.

**Comment by laf** [comment]
@PipoCanaja It's your PR :)

Just edit the title to have WIP in it.

**Comment by PipoCanaja** [comment]
All right. I'll wait until I have all the different devices in test in the lab, and check how I can shorten the field. 

It will take another 1 to 2 months I suppose.

Bye

**Comment by murrant** [comment]
@PipoCanaja before calling discover_xxxxx()   just do `$descr = substr($descr, 0, 60);` or whatever length you deem appropriate/fits in the DB.

**Comment by laf** [comment]
> @PipoCanaja before calling discover_xxxxx() just do $descr = substr($descr, 0, 60); or whatever length you deem appropriate/fits in the DB.

We should just do that in discover_* so it doesn't rely on people knowing about this caveat.

**Comment by murrant** [comment]
@laf sounds good.

**Comment by laf** [comment]
@PipoCanaja Can this be merged now?

**Comment by laf** [comment]
Moved to 1.44.
@PipoCanaja Any news?

**Comment by PipoCanaja** [comment]
Waiting for a few more devices to be tested, so let's keep it for 1.44. I expect to receive new VRP devices and I'll check if there is a better way than just "cutting" the string ...

**Comment by murrant** [comment]
I would like to merge this.  @PipoCanaja If you find a better way to shorten the descriptions, you can send a new PR.

**Pull request merged**
