### PR TITLE
fix polling os cdata

### PR DESCRIPTION
**Pull request by hrtrd**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by hrtrd** [comment]
@PipoCanaja fix for cdata os

**Comment by PipoCanaja** [comment]
OIDs are not the same in this PR. Is this one correct (and the previous one wrong ? ). If yes, you need to resubmit the snmprec and the matching json. @hrtrd

**Comment by PipoCanaja** [comment]
This code does poll both OIDs. Now please check it and let me know what we should do.

**Comment by hrtrd** [comment]
> This code does poll both OIDs. Now please check it and let me know what we should do.

its work fine! i need upload snmsim and test data json?

**Comment by PipoCanaja** [comment]
Then let's keep this one.

**Pull request merged**
