### PR TITLE
Add cisco wireless controller detection

### PR DESCRIPTION
**Pull request by tuomari**

### CODE REVIEW

**Comment by laf** [comment]
Hi @tuomari, many thanks for the PR's.

One of us will get to this pretty soon, in the meantime can you submit a PR following the doc: https://github.com/librenms/librenms/blob/master/doc/General/Contributing.md to confirm that you have the right to submit this code. An example PR is below if you want to look at a previous one, please note that AUTHORS.md is now in the main LibreNMS directory rather than docs:

https://github.com/librenms/librenms/pull/250

Thanks.

**Comment by laf** [comment]
One quick comment, is wlc the correct / best name for the OS description?

**Comment by tuomari** [comment]
Thanks for the comments

I will post a Contributing.pm PR shortly.

Would ciscowlc be a better name? Other suggestions?

What is current practice for including MIB:s. They are convinient, but pose a licencing problem, as discussed in #28.

**Comment by laf** [comment]
Thanks for responding @tuomari.

ciscowlc seems a better fit.

For the MIB, it's fine to include them so long as they don't contain a license saying you can't. An update to that discussion has resulted in: https://github.com/librenms/librenms/blob/master/doc/General/Contributing.md

"We consider inclusion of files such as MIBs in the LibreNMS repository to be merely aggregation in a distribution medium as per the last paragraph of the GPLv3 section 5 ("Conveying Modified Source Versions"), and because they are not combined with LibreNMS to form a larger program, the GPLv3 does not apply to them. This is not a legal ruling - it is simply a statement of our intent and current interpretation."

**Comment by laf** [comment]
Hi @tuomari, any news on the update and the contributing PR so we can get this merged in.

**Comment by tuomari** [comment]
Rebased against master and changed os key from "wlc" to "ciscowlc"
Also created contributing agreement PR #447

**Comment by paulgear** [comment]
Thanks @tuomari.  Those wlc.* files will need to be renamed to ciscowlc.* in order for this to work, though.  I would also suggest adding your own copyright notice to the top of them - you can see a sample in doc/General/Contributing.md.

**Pull request merged**
