### PR TITLE
docs: new SELinux docs

### PR DESCRIPTION
**Pull request by murrant**
I am not feeling the best about this doc's location/integration.

What do we think about splitting apart the install docs?  We could share some docs between the different docs...
Also would show up on the left toc and have the prev/next buttons.  I just don't want too many sections.

However it would would probably be nice to have the option to show the install docs all on one page too.  Not sure if we can do that.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Not sure I like directing users away from the install page to somewhere else just to get some lines for a copy and paste.

**Comment by murrant** [comment]
I agree.  That is why I thought about splitting the install pages up.  Then it would be just part of the flow

**Comment by murrant** [comment]
I'm fine with just embedding this in the install docs for now. Sound good?

**Comment by laf** [comment]
Yup

**Comment by laf** [comment]
Actually, I'm wondering if this should be a script that people run to set SELinux perms up.

**Comment by murrant** [comment]
@laf not a bad thought.  But perhaps merge this first to get the info out there.

**Pull request merged**
