### PR TITLE
Add Meraki support

### PR DESCRIPTION
**Pull request by willjones**
Added logo under new commit.

Logo sourced from Meraki Partner Portal from their marketing collateral section and resized to 32x32px.

### CODE REVIEW

**Comment by laf** [comment]
@willjones - looks like you've left part of a conflict in: https://scrutinizer-ci.com/g/librenms/librenms/inspections/29a919d9-270f-4eaf-b61c-aebf49150f7f/issues/files/includes/definitions.inc.php?status=new&orderField=path&order=asc

**Comment by laf** [comment]
Code looks good.

@paulgear can you confirm if you're happy with this PR. It replaces the one I've done with no code passed across and all done by @willjones

**Comment by paulgear** [comment]
Seems straightforward to me - what was the issue with yours, @laf ?

**Comment by laf** [comment]
I used the blog post from routed logic @paulgear

**Comment by f0o** [comment]
:+1:

**Pull request merged**
