### PR TITLE
Global search by IP address

### PR DESCRIPTION
**Pull request by josephtingiris**
* If a valid IP address is typed into the global search then search ip, overwrite_ip, and hostname for a match and sort the matches by IP address.
* Added IP address to all global search results, whether it's an IP address search or not.
* Cleaned up Handlebars.compile and only display data elements if they have a non-empty value.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by josephtingiris** [comment]
image

**Comment by kkrumm1** [comment]
Yeah, this seems to break Global search completely for me. Using the search by IP address.

**Comment by josephtingiris** [comment]
Does a non-address search work?

Do you still see the ports, or no results at all?

Any sql errors in the librenms.log?

________________________________

**Comment by kkrumm1** [comment]
Cant search by IP address and name. Nothing comes up at all.

**Comment by josephtingiris** [comment]
Any sql errors in the librenms.log?

________________________________

**Comment by josephtingiris** [comment]
The only thing added to the name search was the use of inet6_ntoa().   I’m thinking maybe this ...


https://mariadb.com/kb/en/mysql-56-function/

... are you using mariadb and if so, exactly which version??

________________________________

**Comment by kkrumm1** [comment]
5.5.60-MariaDB
--

**Comment by josephtingiris** [comment]
Thanks.  That explains it.  Older versions of mariadb don’t support the inet6_ntoa function.  

PHP has similar functions.  Is it safe to assume that all LibreNMS installs are using at least PHP 7?

**Comment by kkrumm1** [comment]
For the DB we need to maintain backward compatibility since we have not made a specific version of Maria db and above. 

For PHP the minimum is. 7.1.3

**Comment by josephtingiris** [comment]
Ok,  My mistake.  I'll keep that in mind going forward.

For reference, MariaDB doesn't start supporting inet6_ntoa() until 10.0.12 .. https://mariadb.com/kb/en/inet6_ntoa/

I can do the same thing with PHP.  Should I commit the changes to this branch, or submit a separate PR?

**Comment by kkrumm1** [comment]
I would make a new PR>

**Comment by SourceDoctor** [comment]
@josephtingiris 
in new PR i would use ipv4_addresses table and ipv6_addresses table to search for IP Addresses. Otherwise you'll get only the DNS resolved one's and the overwritten one's.

**Comment by josephtingiris** [comment]
@SourceDoctor Ok, I'll open another PR.  Yes, but the problem with the address tables is they don't have the addresses for ping only devices.  The device ip search works well enough, especially if inet6_aton() is available.  Maybe I'll combine them and see what it looks like.

Do you think it would be acceptable to add a config option to support newer versions of mariadb (with inet6_aton())?  Similar to the $config['rrdtool_version'] setting for rrdcached?

**Comment by SourceDoctor** [comment]
This tables doesn't have them, that's correct. but if you search for a device by ip addresse you should also be able to search for IP Addresses which are not used for polling.
Especially if you want to know to which Device has this IP Addresse.
So please do the complete, but not such easy way, otherwise someone has to fix it to this.
All maintainers are open to help you on problems, optimizing code and questions.

Maybe later, i'd prefer the classical, all versions running, way instead of using a version switch for only this.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/global-search-by-ip-address/11191/2

**Pull request merged**
