### PR TITLE
Issue #5077 - Treat Ubiquiti EdgePoint Switch models the same as EdgeSwitch

### PR DESCRIPTION
**Pull request by twilley**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Treat Ubiquiti EdgePoint Switch models the same as EdgeSwitch and UnifiSwitch models when polling.

### CODE REVIEW

**Comment by laf** [comment]
I'm assuming that edgepoint switches run the same OS as edgeswitch?

We also need OS Test units adding please: http://docs.librenms.org/Developing/Support-New-OS/#os-test-units

**Comment by twilley** [comment]
Yeah, they run the same OS. The EdgePoint Switch 16-Port and the EdgeSwitch 24-Port 250W use the same firmware image file too. I'll look at the OS Test units and get back to you on that.

**Comment by twilley** [comment]
It looks like the OS Unit Test is already in place for Edgeswitch OS:

from the tests/OSDiscoveryTest.php file:

```php
    public function testEdgeswitch()
    {
        $this->checkOS('edgeswitch');
    }
```

When **discovered**, the Edgepoint Switch is correctly classified as running the edgeswitch OS (EdgePoint is just the branding Ubiquiti chose for their outdoor EdgeSwitches and EdgeRouters - Thanks for that, Ubiquiti), but when **polled**, the Hardware, Version, and Serial [Number] info was not being populated into the database.

When I run the pre-commit.php script, everything seems to be in order:

```ShellSession
librenms@librenms:~$ ./scripts/pre-commit.php -u
Running unit tests... success
librenms@librenms:~$
```

This is my second time contributing, so if I'm missing anything else, I'm hoping you'll point me in the right direction.

I have the output from running addhost.php, discovery.php and poller.php as well as mysql data for the following query: `select hardware,version,serial from librenms.devices where device_id=<ID of the Edgepoint>`. For the poller output and mysql query, I have pre-patched and post-patched examples. I haven't included this info here yet, because it's quite verbose, and I'm not sure you even want it.

**Comment by laf** [comment]
You can have more than one test unit per OS type, look at some of the others which list files like X1, X2, X3, etc.

Just add:

```
$this->checkOS('edgeswitch', 'edgeswitch1');
```

Then create a new file called edgeswitch1.snmprec and populate it with the required info.

**Comment by twilley** [comment]
OK, it's making more sense now.

I've added two tests: one for the EdgePoint 16-port Switch, and one for the EdgeSwitch 24-Port 250W.

Is it preferable to keep the version info, etc in the snmprec file, or to remove it? I see varying levels of specificity in the other snmprec files.

For now, I have included all the info for the `1.3.6.1.2.1.1.1.0` OID:

```
1.3.6.1.2.1.1.1.0|4|EdgePoint Switch 16-Port, 1.6.0.4900860, Linux 3.6.5-f4a26ed5, 1.0.0.4857129
```

**Comment by laf** [comment]
image

**Pull request merged**
