### PR TITLE
Refactored and added support for $config['log_dir']

### PR DESCRIPTION
**Pull request by Gorian**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Works for me.

Would be good for at least one other to review and test as if this breaks anything then it will stop updates.

**Comment by Gorian** [comment]
I have tested this with log_dir defined and undefined in config.php, however that was all I tested. Install is in default /opt/librenms, and I haven't tested any other scenarios. Would there be any reason that 'install_dir' would unset, or that config.php wouldn't be in the same directory as config.php? If needed, I can change from a php -r command to actually use a heredoc to input a full php script with more conditionals, if it's required, but it wouldn't be quite as clean.

**Comment by laf** [comment]
I'm fine with how it is, we just need to ensure it's thoroughly tested

**Comment by Gorian** [comment]
No problem. If you approve it, I'll work on some more refactoring and submit later. Let me know if you encounter any bugs or issues, I'll fix. :)

**Comment by laf** [comment]
@librenms/reviewers ?

**Comment by laf** [comment]
@Gorian can you rebase and resolve the conflict please.

**Pull request merged**
