### PR TITLE
Updated hardware detection for VRP

### PR DESCRIPTION
**Pull request by jozefrebjak**
Please test this, my device os version Huawei VRP 5.170 (S5720 V200R010C00SPC600)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello,

This is probably not a good idea, this OID looks very specific to a particular device. 

Bye

**Comment by murrant** [comment]
Sometimes it is appropriate to check $device['sysObjectID'], then snmpget the right value.

**Comment by PipoCanaja** [comment]
Hi @murrant, @jozefrebjak 
It seems that there is absolutely no unified way to solve this. I have now 3 different families (switches, CloudEngines, AccessRouters), and 7 different devices types, and none reply their HW name to the same OID. 
Entity mib is not even a solution, some families are including some kind of virtual chassis in the Entity tree making it difficult to find the real HW you are speaking to. 
Even sysObjectID is not a flat list. 
Only option seems to identify a few recurring OIDs and poll them until one gives a non empty reply. I'll try to come with a PR in this direction.
PipoCanaja

**Comment by murrant** [comment]
@PipoCanaja yes, laf and I have discussed moving os details (version, hw, etc) to discovery, but neither of us have gotten around to it.  Again, I would suggest a sysobjectid map so you only have to call snmpget once.

**Comment by PipoCanaja** [comment]
I tried another approach with sysDescr. Works in the devices I tried. But I kept the OID variant for all devices I don't have that may only support it. 

https://github.com/librenms/librenms/pull/9167

PipoCanaja

**Comment by laf** [comment]
@PipoCanaja It actually is probably better to do all of those as one single multi get rather than loop through an array.

**Comment by murrant** [comment]
Closing this in favor of #9167

**Pull request closed without merging**
