### PR TITLE
UI changes, use of labels

### PR DESCRIPTION
**Pull request by arjitc**
Screenshot: http://i.imgur.com/L5YKZVG.png

### CODE REVIEW

**Comment by laf** [comment]
From IRC:

I think we need to pad these out so they are always the same size - maybe pad to max size of one of the up / down values, i.e if one shows 1000 up then pad all other values to 4 digits.

**Comment by arjitc** [comment]
hmm not sure if there's a padding option for bootstrap labels(?)

**Comment by laf** [comment]
You'll need to find another way then, I think it looks messy as is I'm afraid :)

**Comment by arjitc** [comment]
Hmm could you get me a screenshot @laf ? I have around 200 ports so it doesn't spread into the 4 digit

**Comment by f0o** [comment]
share @laf's thoughs, screenshot looks messy.

**Comment by arjitc** [comment]
I'll think over this one, closing it for now.

**Comment by paulgear** [comment]
As an aside, if you want to center text, it should be done with styles, not hard-coded center tags.

**Pull request closed without merging**
