### PR TITLE
Fixed apc powerbar phase limit discovery for AP7852 firmware: 2.7.3

### PR DESCRIPTION
**Pull request by zarya**

### CODE REVIEW

**Comment by laf** [comment]
@paulgear / @f0o 

Would one of you mind taking a quick look over this.

I'm more happy with how this patch is now, I initially thought this might cause data loss but it appears not as the rrd filenames are the same. It does an if check against the limits returned, according to the MIB for the APC units, -1 means no banks exist so this looks like we should be doing it this way.

the initial commit isn't the best way to approach this imho so I asked @zarya to change it.

Thoughts?

**Comment by f0o** [comment]
Looks good to me.

**Comment by paulgear** [comment]
It looks OK, and is likely to only have a very limited effect.  I'm guessing @zarya the only one running these particular devices?  (Can we find that out from stats.librenms.org?)

**Comment by laf** [comment]
We should have been able to but alas it's not been logging that for some reason :/

**Pull request merged**
