### PR TITLE
Added SQL procedure for fixing validation errors.

### PR DESCRIPTION
**Pull request by cron410**
If you see any issues here, we will need to work together to fix them.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
We've actually avoided telling people to run these queries themselves or automating to prevent the code recommending something it shouldn't. I'm happy with it though - @murrant ?

**Comment by cron410** [comment]
Maybe we should add a huge DANGER DRAGONS AHEAD disclaimer?

**Comment by murrant** [comment]
I'd rather add a way to apply the fixes after user input rather than docs instructing them to run the sql.

**Comment by murrant** [comment]
I think it is good to hear the feedback and the reports should die down over time.

**Comment by murrant** [comment]
We could probably do something here, but I don't think the documentation is the right place.  Also, perhaps not the right time yet.  Closing for now.

**Pull request closed without merging**
