### PR TITLE
webui: Expose pollers link to show total poll time for all devices per poller

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
@laf The groups tab is exposed once you go into the pollers section.  That gave me a thought.

Instead of requiring `distributed_poller` be set on the main node, perhaps we just count the number of poller groups before exposing the poller group setting in the add and edit device dialogs?

**Comment by laf** [comment]
> @laf The groups tab is exposed once you go into the pollers section. That gave me a thought.

Sorry I don't know what you mean here.

> Instead of requiring distributed_poller be set on the main node, perhaps we just count the number of poller groups before exposing the poller group setting in the add and edit device dialogs?

Up to you but an additional sql query to show the link, worth it?

**Comment by murrant** [comment]
Creating poller groups is only relevant for people using distributed polling.

The sql query would be very quick, counting the rows on a table with probably single digit entries.

**Comment by murrant** [comment]
After some looking at the poller-wrapper problem, I vote for 1

**Pull request merged**
