### PR TITLE
webui: routing lineup

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Needs testing, i only have BGP available for testing :(

screen shot 2018-01-01 at 5 59 29 am

### CODE REVIEW

**Comment by kkrumm1** [comment]
OSPF looks good 
image

**Comment by murrant** [comment]
@crcro actually on OSPF the entire area is grey instead of just the header.

**Comment by kkrumm1** [comment]
@murrant if you look the BGP screenshot it looks the same too... I thought that it was supposed to look like that.

**Comment by murrant** [comment]
For bgp the lines alternate grey and white, but he only has one ;)

**Comment by laf** [comment]
Yeah not sure this looks consistent across all the routing.

I did put a comment in the applications PR I merged, I'm not sure I'm a fan of panels in panels. They look odd and 'broken'. Won't hold me back merging once the various pages are fixed but thought I'd mention it.

**Comment by murrant** [comment]
@crcro cef is broken.

You can simulate these by adding rows to the tables in the database.

**Comment by laf** [comment]
@crcro Any update on this?

**Comment by laf** [comment]
@crcro I'm closing this down for now. Feel free to comment back when you've resolved the issue and we can re-open.

**Pull request closed without merging**
