### PR TITLE
Added support for Protelevision DVB-T Transmitter

### PR DESCRIPTION
**Pull request by jozefrebjak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

I added os protelevision-t1 because i will add another os protelevision-t2, because when i switched to T2 then there is diferent sysObjectID and different sensors with different OIDs

### CODE REVIEW

**Comment by murrant** [comment]
@jozefrebjak looks like you forgot to add `includes/poller/os/protelevision-t1.inc.php`.
You using the github webui to create these?  It is a lot easer to use the git cli once you learn how to use it :)

**Comment by jozefrebjak** [comment]
@murrant  Yes, I forgot and yes I am adding it with web :D I know i must to learn, how use cli.

**Comment by jozefrebjak** [comment]
@murrant  so i made some tuning, how that group sensors works ?

**Comment by murrant** [comment]
@jozefrebjak an option way to visually group sensors in the webui.  You might want to use it for your state sensors here actually.

**Comment by murrant** [comment]
Screenshot here: https://github.com/librenms/librenms/pull/9606

**Comment by jozefrebjak** [comment]
@murrant  I am happy with it, you can merge when it will be everything ok.

**Comment by PipoCanaja** [comment]
Hi @jozefrebjak 
After a very quick look, it seems that your groups are not correctly set in the test file. You should probably regenerate them in order to pass the build tests. Basically, Travis must end up green ;) 
PipoCanaja

**Comment by jozefrebjak** [comment]
@murrant  when will be possible to merge this ?

**Comment by murrant** [comment]
Sorry, @jozefrebjak sometimes I don't get back to a PR after waiting for tests to finish.

Thanks for the PR 😃

**Pull request merged**
