### PR TITLE
Lists of CTCU MIBs and yaml

### PR DESCRIPTION
**Pull request by guoming218**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@guoming218 This isn't how mib polling works, you can specify each of the OIDs in a single yaml file.

From the discussions on irc and this PR I'll assume you've not managed to actually get it working anyway. We won't be able to accept a PR without a screenshot showing the data that is collected.

**Comment by guoming218** [comment]
@laf Is there any example online to guide me thru?

**Comment by laf** [comment]
@guoming218 Just the docs we have I'm afraid.

**Comment by guoming218** [comment]
Or maybe u can help me with this? what did i actually miss out, i can go do it and test it out

**Comment by laf** [comment]
Unfortunately I don't know the mib based polling past what we have in the docs. If you follow it exactly and it doesn't work then most likely the MIB isn't compatible and it won't work.

**Comment by laf** [comment]
Feel free to comment back when you've got things working and we can re-open this pull request.

**Pull request closed without merging**
