### PR TITLE
Use displayname instead of hostname for Device Maintenance Modal Title

### PR DESCRIPTION
**Pull request by electrocret**
Device maintenance modal currently uses only hostname instead of displayname.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Is $device a model or an array here?

**Comment by electrocret** [comment]
It's likely an array and not a model since it's in the html section. Updated.

**Comment by murrant** [comment]
That won't work.  The display field is just part of what is needed to correctly display it in all cases.

I suggest this snippet:
`DeviceCache::get($device['device_id'])->display()`

**Comment by electrocret** [comment]
I have it working now.

**Review by SourceDoctor — APPROVED** [review]
LGTM

**Pull request merged**
