### PR TITLE
Fixed missing FW and Serials in Dlink

### LINKED ISSUE #10467: Support for new Dlink models
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.
- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x ] Please provide as much detail as possible.
- [x]  Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Thanks to @laf for updating support for Dlink's newer devices in [this pr](https://github.com/librenms/librenms/pull/9464). However, the  data regarding firmware and serials for these devices aren't displaying. I have attached all the necessary pastebin files. I need to add that I have tried changing the code myself several times, but that just breaks everything regarding the Dlinks. So I humbly ask for any help.

**Dlink DGS-1510-28X/ME**

`./discovery.php -h HOSTNAME -d | ./pbin.sh`
https://p.libren.ms/view/ebf2fd31
`./poller.php -h HOSTNAME -r -f -d | ./pbin.sh`
https://p.libren.ms/view/e1ff56f0
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh`
*Paste too large and errors in command, please see attached txt file*
[dlink1510.txt](https://github.com/librenms/librenms/files/3440584/dlink1510.txt)

**Dlink DGS-3000-28X**

`./discovery.php -h HOSTNAME -d | ./pbin.sh`
https://p.libren.ms/view/e408ffda
`./poller.php -h HOSTNAME -r -f -d | ./pbin.sh`
https://p.libren.ms/view/764e325e
`snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh`
*Paste too large and errors in command, please see attached txt file*
[dlink3000x.txt](https://github.com/librenms/librenms/files/3440643/dlink3000x.txt)

Currently it shows up as follows:
image

And an example of a working device is:

image

So anyone willing to help will have my endless gratitude.

### PR DESCRIPTION
**Pull request by hanserasmus**
closes #10467 
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

*Note*: The original OIDList code can be found in `/includes/polling/os/vrp.inc.php`. I was told to have a look at that file for the idea by @PipoCanaja in discord. Any copyright infringement was done by mistake and not by malicious intent.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @hanserasmus 
Looks good. Could you also add test data to this PR, so we can improve regression tests ?

**Comment by hanserasmus** [comment]
@PipoCanaja unfortunately this is a problem. I have tried on 4 occasions to install all the necessary stuff to run the tests, but `./scripts/composer_wrapper.php install` results in a failed install. See [this](https://media.discordapp.net/attachments/327529583601647617/605867733308932116/unknown.png?width=794&height=568) screenshot I posted in Discord general channel. So I had to revert back to the install with the `--no-dev` switch.

**Comment by hanserasmus** [comment]
Had troubles with the test data generation. Sorry for the multiple commits. Hopefully all is there now.

**Comment by PipoCanaja** [comment]
Hi @hanserasmus 
Thanx for your PR. And the good amount of test material you provided :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-55-release-changelog-august-2019/9428/1

**Pull request merged**
