### PR TITLE
water sensor support for sentry 3/4 pdus

### PR DESCRIPTION
**Pull request by sjtarik**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by sjtarik** [comment]
@laf @murrant I need little help fixing the Travis CI tests. Tests expects the OS version and serial number of PDU to be exactly same in tests/data/sentry3.json and tests/data/sentry4.json. Should I just delete these fields null or is there a way to make them optional?

**Comment by murrant** [comment]
You changed the data in the snmprec file, without updating the json file (which you need to do anyway since you have added sensors)

**Comment by PipoCanaja** [comment]
@sjtarik 
The best solution in your case would be to leave the existing snmprec as they are (so revert them), and create new ones as variants (use  "./collect_snmp_data.php -h <device> -v myModel" to create sentry3_mymodel.snmprec , if the device is a sentry3). That way, we extend our test base instead of replacing it.

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen

**Pull request closed without merging**
