### PR TITLE
Added support for Meraki devices

### PR DESCRIPTION
**Pull request by laf**
Big thanks to https://blog.routedlogic.net/?p=881 for most of the files / code. Some small changes needed to get it working 100%.

### CODE REVIEW

**Comment by laf** [comment]
Scrut issues are false positives or un-related to this PR

**Comment by laf** [comment]
Can we consider merging this, the code is extremely simple and in keeping with the rest of the code base so their should be no concerns over it really.

**Comment by f0o** [comment]
:+1: 
(resolve merge-conflict before would be nice hehe)

**Comment by paulgear** [comment]
I'm reaching out to Colin Stubbs to find out about the licensing on this code.

**Comment by f0o** [comment]
@paulgear any update on the licensing?

**Comment by paulgear** [comment]
No contact yet; I'll try again.  Please do not merge until we have confirmed that we are allowed to use the code.  I thought there was also another PR based on Colin Stubbs' blog, but it appears to be closed now (I'll have a longer look later).

**Comment by laf** [comment]
We talked about Riverbed support from him as well: https://blog.routedlogic.net/?p=903

No one's ever done a PR for that though.

**Comment by paulgear** [comment]
I got in touch with Colin today; he confirmed that this code has already been accepted into Observium, so unfortunately we can't use it.

**Pull request closed without merging**
