### PR TITLE
refactor: Move more state sensors to yaml

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Will try to go through more the next coming days.

Disclaimer:
I have not tested this, this is just converted manually.

### CODE REVIEW

**Comment by laf** [comment]
Wahoo the @Rosiak is back :)

I've not compared the yaml to the php but do any of these change the state name or index so historic data is lost?

**Comment by murrant** [comment]
@Rosiak If you have access to the devices, you could generate test data from before this PR then test it after.  

https://docs.librenms.org/Developing/os/Test-Units/

**Comment by Rosiak** [comment]
I'll see what I can figure out, sorry for the delay, but time..

**Comment by laf** [comment]
I've added test data for 3 of 5 of these devices. @Rosiak would you have time to add the other two if you have data?

If not, I think we just merge in for now.

**Comment by murrant** [comment]
Remove the arp-data section from the json files. That module doesn't work right for testing yet.

**Comment by murrant** [comment]
arp-tables fixed in #8119

**Pull request merged**
