### PR TITLE
Update datacom.yaml

### PR DESCRIPTION
**Pull request by lhwolfarth**
Including specific OIDs for each plataform related to the OS "datacom" (actually DmSwitch). The generic OID  ".1.3.6.1.4.1.3709" include other platforms that uses different OSs (eg. DmOS) with different SNMP architecture that I will implement on the next commits.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by lhwolfarth** [comment]
> You've probably over compensated. Likely you want `.1.3.6.1.4.1.3709.1.2`

Would be good, but unfortunately it is not possible. 
For example, the specific ID bellow is for other platform which uses a different OS with other SNMP tree:
.1.3.6.1.4.1.3709.1.2.137 (DmOS)
In this case it would still be classified on this yaml, so I need to restrict to all specific OIDs in this datacom.yaml in order to don't overlap with the other platforms (OSs) that I will include on the next pull requests that I am planning.
The spefic OIDs for the datacom.yaml I retrieve from the file datacom_reg.mib (https://download.datacom.com.br/ftp/eng-aplicacao/LuisWolfarth/MIBs/datacom_reg.mib). so there is no risk of forgetting a platform and breaking what is already working.

**Comment by murrant** [comment]
Could you perhaps do the more generic sysObjectID and make exceptions for the other oids?  Do whichever manually lists less oids ;)

**Comment by lhwolfarth** [comment]
> Could you perhaps do the more generic sysObjectID and make exceptions for the other oids? Do whichever manually lists less oids ;)

Yes. I tested filtering the new platforms with new OS by using its specific OID plus the "sysDescr" and worked fine.

So no problem using sysObjectID .1.3.6.1.4.1.3709.1.2 or even remaining with the original sysObjectID .1.3.6.1.4.1.3709.

Thanks.

**Comment by murrant** [comment]
I just don't like seeing new pull requests every time a new product is released :)  I like it less when a product isn't detected.

**Comment by murrant** [comment]
Closing in favor of #15436

**Pull request closed without merging**
