### PR TITLE
Added more .gitignore entries

### PR DESCRIPTION
**Pull request by MindTooth**
.bash_history
.vimfiles

### CODE REVIEW

**Comment by tobiasa1** [comment]
Wouldn't it be better to just ignore all dotfiles?
Since we have librenms deployed in the home directory for the librenms user, I get a lot of untracked files with git status.

For example:
```
librenms@nms:~$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .bash_history
        .nano_history

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by MindTooth** [comment]
Would be more applicable.  If it don't break anything ;-)

**Comment by laf** [comment]
We don't have any files other than those listed which are needed and start with . so I think that would be ok to exclude all .* files.

@librenms/reviewers ?

**Comment by f0o** [comment]
:+1: on ignoring all dotfiles

**Comment by MindTooth** [comment]
Now?

**Comment by tobiasa1** [comment]
Hi,

I think .scrutinizer.yml and .editorconfig should be be excepted from the wildcard rule.

Also, I think it's safe to remove the other dotfiles that's already in the file. :)

**Comment by MindTooth** [comment]
Third attempt :-)

**Comment by f0o** [comment]
I've no idea about it but how about the .git directory? Should that be excluded as well or is git smart enough for that?

**Comment by paulgear** [comment]
There's no need to put .git in .gitignore.  It knows about that.

**Pull request merged**
