### PR TITLE
Add Netbotz-V5 Support

### PR DESCRIPTION
**Pull request by mxhob1**
Adding support for current-generation Netbotz units as the entire MIB structure has been changed. This has been tested against NetBotz 750 units for accuracy.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @mxhob1 
Your sensor definition is incomplete. See the Travis error message : 
```
1) LibreNMS\Tests\YamlTest::testDiscoveryDefinitionSchema
netbotz-v5.yaml does not validate. Violations:
[modules.sensors.state.data[0].states] The property states is required

```

**Comment by murrant** [comment]
The MIB should be named NetBotz50-MIB and should be in the netbotz directory (update mibdir in your os definition).

Also,glancing at the MIB, I saw this `BotzWare`  It seems like that is the name of the OS.

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen

**Comment by mxhob1** [comment]
Hi @Jellyfrog, I'm available to get this refactored and committed-- can this PR be re-opened or would you like to have it referenced in a new PR?

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen

**Pull request closed without merging**
