### PR TITLE
Update netscaler with new Health/count metrics

### PR DESCRIPTION
**Pull request by mzacchi**
Counters for sslTotTransactionsRate, httpTotRequestsRate, tcpCurClientConnEstablished and tcpCurServerConnEstablished

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by mzacchi** [comment]
librenms@librevm:~$ ./scripts/pre-commit.php -p -o netscaler
Use ./lnms dev:check
librenms@librevm:~$ ./lnms dev:check
Test output:
Running PHP lint check...
PHP 7.2.27 | 10 parallel jobs
............................................................   60/4002 (1 %)
............................................................  120/4002 (2 %)
............................................................  180/4002 (4 %)
............................................................  240/4002 (5 %)
............................................................  300/4002 (7 %)
............................................................  360/4002 (8 %)
............................................................  420/4002 (10 %)
............................................................  480/4002 (11 %)
............................................................  540/4002 (13 %)
............................................................  600/4002 (14 %)
............................................................  660/4002 (16 %)
............................................................  720/4002 (17 %)
............................................................  780/4002 (19 %)
............................................................  840/4002 (20 %)
............................................................  900/4002 (22 %)
............................................................  960/4002 (23 %)
............................................................ 1020/4002 (25 %)
............................................................ 1080/4002 (26 %)
............................................................ 1140/4002 (28 %)
............................................................ 1200/4002 (29 %)
............................................................ 1260/4002 (31 %)
............................................................ 1320/4002 (32 %)
............................................................ 1380/4002 (34 %)
............................................................ 1440/4002 (35 %)
............................................................ 1500/4002 (37 %)
............................................................ 1560/4002 (38 %)
............................................................ 1620/4002 (40 %)
............................................................ 1680/4002 (41 %)
............................................................ 1740/4002 (43 %)
............................................................ 1800/4002 (44 %)
............................................................ 1860/4002 (46 %)
............................................................ 1920/4002 (47 %)
............................................................ 1980/4002 (49 %)
............................................................ 2040/4002 (50 %)
............................................................ 2100/4002 (52 %)
............................................................ 2160/4002 (53 %)
............................................................ 2220/4002 (55 %)
............................................................ 2280/4002 (56 %)
............................................................ 2340/4002 (58 %)
............................................................ 2400/4002 (59 %)
............................................................ 2460/4002 (61 %)
............................................................ 2520/4002 (62 %)
............................................................ 2580/4002 (64 %)
............................................................ 2640/4002 (65 %)
............................................................ 2700/4002 (67 %)
............................................................ 2760/4002 (68 %)
............................................................ 2820/4002 (70 %)
............................................................ 2880/4002 (71 %)
............................................................ 2940/4002 (73 %)
............................................................ 3000/4002 (74 %)
............................................................ 3060/4002 (76 %)
............................................................ 3120/4002 (77 %)
............................................................ 3180/4002 (79 %)
............................................................ 3240/4002 (80 %)
............................................................ 3300/4002 (82 %)
............................................................ 3360/4002 (83 %)
............................................................ 3420/4002 (85 %)
............................................................ 3480/4002 (86 %)
............................................................ 3540/4002 (88 %)
............................................................ 3600/4002 (89 %)
............................................................ 3660/4002 (91 %)
............................................................ 3720/4002 (92 %)
............................................................ 3780/4002 (94 %)
............................................................ 3840/4002 (95 %)
............................................................ 3900/4002 (97 %)
............................................................ 3960/4002 (98 %)
..........................................                   4002/4002 (100 %)


Checked 4002 files in 8.4 seconds
No syntax error found
success (8.69s)
Running pip3 install to install developer dependencies.
Requirement already satisfied: pylint in ./.local/lib/python3.6/site-packages
Requirement already satisfied: toml>=0.7.1 in ./.local/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: isort<5,>=4.2.5 in ./.local/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: astroid<=2.5,>=2.4.0 in ./.local/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: mccabe<0.7,>=0.6 in ./.local/lib/python3.6/site-packages (from pylint)
Requirement already satisfied: six~=1.12 in ./.local/lib/python3.6/site-packages (from astroid<=2.5,>=2.4.0->pylint)
Requirement already satisfied: lazy-object-proxy==1.4.* in ./.local/lib/python3.6/site-packages (from astroid<=2.5,>=2.4.0->pylint)
Requirement already satisfied: wrapt~=1.11 in ./.local/lib/python3.6/site-packages (from astroid<=2.5,>=2.4.0->pylint)
Requirement already satisfied: typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" in ./.local/lib/python3.6/site-packages (from astroid<=2.5,>=2.4.0->pylint)

Running installing deps with pip3 failed.
 You should try running 'pip3 install -r requirements.txt' by hand
You can find more info at http://docs.librenms.org/Developing/Validating-Code/

**Comment by murrant** [comment]
`./lnms dev:check unit --os netscalar` is how you can check

You'll need to generate new test data with `./scripts/save-test-data.php` and maybe `./scripts/collect-snmp-data.php`  See docs linked by the bot for more info.

**Comment by mzacchi** [comment]
Hi Murrant,

Please find attached the save-test-data.php output.
The other one might contain some sensitive data and I'd rather not going through all of it unless really needed, could you please confirm?

Regards,
Marcelo

[netscaler_json.zip](https://github.com/librenms/librenms/files/4901778/netscaler_json.zip)

**Comment by murrant** [comment]
We try to have test data for everything so it isn't broken in the future.  Without the test data it is very hard to confirm changes to the code won't break it because usually no one has access to the device.

If you are concerned about private data, I suggest you collect data from a non-production unit or go through it and remove any data you consider sensitive.  You need to add both the snmprec and json to this pull request (not attached, the actual code changes)

**Comment by Jellyfrog** [comment]
Thank you for your contribution but we're closing this due to inactivity.  
Feel free to reopen if you plan on finishing it!

**Pull request closed without merging**
