### PR TITLE
docs: Refresh for RRDCached steps

### PR DESCRIPTION
**Pull request by kkrumm1**
Update the steps and streamline them easy for users to set up. 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by kkrumm1** [comment]
I'm 100% sure need to test but had users in the forums who using Ubuntu and followed documentation but never set the permissions or started the service due the doc not including it for that OS.

**Comment by murrant** [comment]
I'll be testing Ubuntu when I can.  But, chown wasn't required on CentOS 7.

**Comment by kkrumm1** [comment]
@murrant on the Centos 7 you saying to remove this chown librenms:librenms /var/run/rrdcached right?

**Comment by murrant** [comment]
Correct, I took these 3 steps to get working rrdcached:


1. Create `/etc/systemd/system/rrdcached.service` with this content:
```
[Unit]
Description=Data caching daemon for rrdtool
After=network.service

[Service]
Type=forking
PIDFile=/run/rrdcached.pid
ExecStart=/usr/bin/rrdcached -w 1800 -z 1800 -f 3600 -s librenms -U librenms -G librenms -B -R -j /var/tmp -l unix:/run/rrdcached.sock -t 4 -F -b /opt/librenms/rrd/

[Install]
WantedBy=default.target
```

2. Start rrdcached
    systemctl enable --now rrdcached.service

3. Edit /opt/librenms/config.php to include:
    $config['rrdcached'] = "unix:/run/rrdcached.sock";

**Comment by kkrumm1** [comment]
New PR was sent in.. this one no longer needed. KK

**Pull request closed without merging**
