### PR TITLE
Fiberhome - Cpu and Mempools support

### PR DESCRIPTION
**Pull request by alangregory**
Added support for sensors

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR @alangregory 

Only one comment, the processor discovery where you use "GEPON-OLT-COMMON-MIB::mgrCardCpuUtil.10" as the oid should really be the numerical OID. This way, the mib isn't needed which is currently how the processors polling is designed.

If you can update that then we can merge.

**Comment by alangregory** [comment]
Changed, should i use Numeric ID in all  processor sensors ?

**Comment by laf** [comment]
You can do the initial lookup in disco with the name but the numerical oid needs to be saved.

**Comment by laf** [comment]
@alangregory Just gone to check this one out again and it looks like you've got a load of the commits we've recently merged bundled into your PR.

It's probably best you creating a new branch from the master and picking out the updates to create a clean PR.

**Comment by alangregory** [comment]
ok, did it.

**Pull request closed without merging**
