### PR TITLE
Created add, edit, remove location and edit, remove services to the v…

### PR DESCRIPTION
**Pull request by gabrielRojasNew**
…0 API and added their corresponding routes

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
good work!

**Comment by gabrielRojasNew** [comment]
Thanks !

**Comment by jozefrebjak** [comment]
@gabrielRojasNew Will be nice to have an option to create a service via API to Group. Will be someting like this possible ? Even better will be that option integrate to WEB. For example I have custom script to check some parameter, but I wan to add that service to some group, this is not possible what I know or yes ? Thank you

**Comment by gabrielRojasNew** [comment]
Hmm caught me off guard there. We can get the ids of the devices belonging to a group so if you create the group first and then add a service to that group, there can be an easy way to just replicate that service to each device that forms part of that group. The issue there is that if you later remove that device from the group the service must be removed too from that device. So it would involve creating a function to add service to group and changing the functions that adds to groups and deletes from groups to check for this. It could be done. I haven't touched the web interface yet; right now i want to add a couple of things to the API (i'm thinking about bringing parent child relationships to it).

**Comment by kkrumm1** [comment]
Looks good we just need a tester and confirm all is good then We can merge it.

**Comment by kkrumm1** [comment]
Any word in this guys, can we merge?

**Comment by gabrielRojasNew** [comment]
Here are some examples. Let's see if someone wants to test them:

Add location
curl -X POST -d '{"location":"Google", "lat":"37.4220041","lng":"-122.0862462"}' -H 'X-Auth-Token:YOUR-API-TOKEN' https://librenms.org/api/v0/locations

Delete location
curl -X DELETE -H 'X-Auth-Token:YOUR-API-TOKEN' https://librenms.org/api/v0/locations/Google

Edit location
curl -X PATCH -d '{"lng":"100.0862462"}' -H 'X-Auth-Token:YOUR-API-TOKEN'  hhttps://librenms.org/api/v0/locations/Google

Delete service from host
curl -X DELETE -H 'X-Auth-Token:YOUR-API-TOKEN' https://librenms.org/api/v0//services/service_id

Edit service from host
curl -X PATCH -d '{"service_disabled":"1"}' 'X-Auth-Token:YOUR-API-TOKEN' https://librenms.org/api/v0/services/service_id

**Comment by PipoCanaja** [comment]
Hi @gabrielRojasNew 
Could you put some details in the doc concerning the new features ? 
https://docs.librenms.org/API/
And we'll merge this. 
Thanx

**Comment by gabrielRojasNew** [comment]
> Hi @gabrielRojasNew
> Could you put some details in the doc concerning the new features ?
> https://docs.librenms.org/API/
> And we'll merge this.
> Thanx

Of course, on it.

**Comment by PipoCanaja** [comment]
Could you do it in the same PR instead of opening one for each change please ?

**Comment by gabrielRojasNew** [comment]
Edited index.md, Services.md and added Locations.md to the API section with the description of these new features.

**Comment by gabrielRojasNew** [comment]
> Could you do it in the same PR instead of opening one for each change please ?

Ok, i'll do it.-

**Comment by gabrielRojasNew** [comment]
Done, this is the PR with all the changes in the documentation https://github.com/librenms/librenms/pull/11193. Sorry

**Comment by gabrielRojasNew** [comment]
The documentation is already merged to master.

**Comment by PipoCanaja** [comment]
@gabrielRojasNew That's why the doc should be in the same PR as the code :D :D

**Comment by gabrielRojasNew** [comment]
XD sorry, next time i create a new pull request i'll include the documentation at first so this doesn't happens again. Let's archive this PR as an example of what not to do XD XD XD.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
