### PR TITLE
webui: device page refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

screen shot 2017-12-27 at 5 05 22 pm
screen shot 2017-12-27 at 6 00 43 pm
screen shot 2017-12-27 at 6 01 25 pm

and more ... like performance and alerts tab

### CODE REVIEW

**Comment by murrant** [comment]
Hmm, I feel like this should be in the December release for consistency, but it is rather large and a little late in the cycle.

**Comment by kkrumm1** [comment]
@murrant I will do some more testing but this fixed the gray icons that show up on the device page under Recent Events. 
#7962

**Comment by kkrumm1** [comment]
Performance calendar doesn't seem to load right 
image

**Comment by crcro** [comment]
strange, didn’t change anything to that part of code, and looks ok on my phone atm ...

**Comment by Rosiak** [comment]
LGTM.
Tested it yesterday, looked fine. I do not see the same issues as @kkrumm1 .

**Comment by Zmegolaz** [comment]
LGTM, I don't see the calendar issues either.

**Comment by kkrumm1** [comment]
Figured it out the calendar window issue only happens when you have site style set to mono.

**Pull request merged**
