### PR TITLE
Store discover/polled time in whole seconds

### PR DESCRIPTION
**Pull request by Jellyfrog**
Fixes 
```
[2023-05-11T09:36:00.864994+02:00] production.ERROR: SQLSTATE[22003]: Numeric value out of range:
1264 Out of range value for column 'last_discovered_timetaken' at row 1 (SQL: UPDATE `devices` set `last_discovered`=NOW(),`last_discovered_timetaken`=1831.653 WHERE `device_id` = 6788) (SQL: UPDATE `devices` set `last_discovered`=NOW(),`last_discovered_timetaken`=1831.653 WHERE `device_id` = 6788)
#0 /opt/librenms/includes/discovery/functions.inc.php(184): dbUpdate()
```

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I don't think we want it stored as whole seconds

**Comment by Jellyfrog** [comment]
Why not? Nobody is interested in millisecond resolution of time taken, it's not a stable number you can compare between runs anyway, too many external factors.

**Comment by murrant** [comment]
Polling can take less than one second.  And this number is aggregated, so losing fractions of a second across a thousand devices can add up.

**Comment by murrant** [comment]
For example:

```
Poller_0-2(INFO):Completed poller run for 2641 in 0.75s
Poller_0-13(INFO):Completed poller run for 58 in 0.84s
```

**Pull request closed without merging**
