### PR TITLE
Freeswitch support

### PR DESCRIPTION
**Pull request by Tatermen**
Support for pulling statistics from freeswitch via check_mk. See https://github.com/librenms/librenms-agent/pull/53 for check_mk plugin.

> Please read this information carefully.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Awesome, thanks for the contribution.

I'd say it's just formatting fixes that need to be done, if you rebase against master you can run ./scripts/pre-commit.php to see what needs updating.

**Comment by Tatermen** [comment]
Unfortunately I just get errors when I try to run that.

```
Running lint check...
success
Checking PSR-2 style... sh: ./vendor/bin/phpcs: No such file or directory
failed

Running unit tests... sh: ./vendor/bin/phpunit: No such file or directory
failed
```

**Comment by laf** [comment]
Sorry you need to install a few things - should have said:

https://github.com/librenms/librenms/blob/master/doc/Developing/Validating-Code.md

**Comment by Tatermen** [comment]
That worked. I know you've already merged it, but here's the results for the record:

```Running lint check...
success
Checking PSR-2 style... success
Running unit tests... success
Tests ok, submit away :)
```

**Pull request merged**
