### PR TITLE
Map Management: Show Groups

### PR DESCRIPTION
**Pull request by murrant**
image

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by santiag0z** [comment]
I liked it!, but I think the position of the buttons would be better aligned more to the right.

image

**Comment by murrant** [comment]
@santiag0z That isn't right, Seems like you didn't run `npm run prod` afterwards so some tailwind CSS isn't generated.

**Comment by santiag0z** [comment]
@murrant In the documentation I don't see mention of npm, is npm necessary?

**Comment by murrant** [comment]
@santiag0z npm is run during daily.sh

**Comment by murrant** [comment]
Wait, no it isn't :D  But I just checked on my prod and the CSS is showing correctly and a compiled app.css is included in this PR.

**Comment by santiag0z** [comment]
@murrant, Thank you for explaining. 

My test box, It seems to work, but I think it would look better aligned to the right instead of centered

image

image

**Comment by murrant** [comment]
Right is too far over on some screens.  Feel free to add a middle responsive state that puts it to the right.

**Pull request merged**
