### PR TITLE
cleanup2

### PR DESCRIPTION
**Pull request by xxorde**
As mentioned in https://github.com/librenms/librenms/pull/850 I did some permission cleanup.

* set direct execute scripts to 755
  * *.py *.sh *.pl
* set most .php to 0644
  * *.php in the root (/) untouched
  * * left /scripts/ and  /upgrade-scripts/ untouched 
* set images, html, txt and MIBs to 644
* removed  html/images/16/Thumbs.db

I tested it (only) on my own setup.

### CODE REVIEW

**Comment by paulgear** [comment]
Looks good to me; no new Scrutinizer issues introduced.

**Comment by laf** [comment]
@paulgear Unless you're planning to merge this I can run it on my test install overnight tonight and merge tomorrow if you like?

**Comment by paulgear** [comment]
@xxorde, I found a few files that shouldn't have been changed: daily.sh, html/js/makemini.pl, mibs/process.pl, scripts/removespikes.pl, scripts/watchmaillog/watchmaillog.pl - if you change these back to 755 and push to your branch, this PR will update automatically.

**Comment by xxorde** [comment]
@paulgear  you mean I should change them back to 0644, right?
I made them 755 on my branch.

**Comment by paulgear** [comment]
Apologies, @xxorde - I was reading the diff the wrong way around.  In that case, these files could use a chmod 644:
mibs/ATM-FORUM-ADDR-REG
mibs/CABLETRON-TRAPS
mibs/CABLETRON-TRAPS-IRM
mibs/CISCOSB-AAA
mibs/CISCOSB-BRIDGE-SECURITY
mibs/CISCOSB-File
mibs/CISCOSB-HWENVIROMENT
mibs/CISCOSB-IP
mibs/CISCOSB-IPv6
mibs/CISCOSB-IpRouter
mibs/CISCOSB-MAC-BASE-PRIO
mibs/CISCOSB-RMON
mibs/CISCOSB-SECURITY-SUITE
mibs/CISCOSB-SSL
mibs/CISCOSB-TCPSESSIONS
mibs/CISCOSB-Tuning
mibs/CISCOSB-UDP
mibs/CISCOSB-rlFft
mibs/CISCOSB-rlInterfaces
mibs/CISCOSB-rndApplications
mibs/CISCOSB-rndMng
mibs/IRM-OIDS
mibs/NETWORK-DIAGS
mibs/RBTWS-AP-TC
mibs/RBTWS-CLIENT-SESSION-TC
mibs/REPEATER-MIB-2
mibs/ROUTER-OIDS

**Comment by xxorde** [comment]
@paulgear you are right, I forgot to change these MIBs to 0644.

**Pull request merged**
