### PR TITLE
WIP: Juniper Firewall counters

### PR DESCRIPTION
**Pull request by jerji**
This change was needed in our move from observium. It adds the Juniper firewall counters to the Health tab. We tried using YAML but could not get it to work because of the weird text strings.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jerji** [comment]
Is there a way to make this into a rate of change instead of a  constant increasing count on the rrd ?

**Comment by jerji** [comment]
Can anyone tell me why my tests are failing?

**Comment by murrant** [comment]
Says right here:
```
Cannot redeclare genOID() (previously declared in /home/runner/work/librenm  
  s/librenms/includes/discovery/sensors/count/junos.inc.php:62)   
```

**Comment by murrant** [comment]
@jerji thanks for updating it now that the COUNTER code landed.  I am pretty sure this could be done in yaml (which is preferred).

You would need to set this to make the string index be collected as a numeric oid:
`snmp_flags: '-OQUsbe'`

**Comment by jerji** [comment]
Alot of things are not in the docs xD

**Comment by murrant** [comment]
I took a look at this, and this and decided it shouldn't be crammed into "sensors"  Feel free to add a custom module for it (make sure you use the modern style like Netstats or Vminfo.

**Comment by jerji** [comment]
@murrant Is there documentation on how to do this?

**Pull request closed without merging**
