### PR TITLE
Changed icon size to match other ubnt icons

### PR DESCRIPTION
**Pull request by MLWALK3R**

### CODE REVIEW

**Comment by f0o** [comment]
Do you happen to know whether it's ok with their license to resize the logo?

**Comment by f0o** [comment]
Also, please dont develop on your master branch.
See the docs on the preferred branch naming schema.
http://docs.librenms.org/Developing/Using-Git/#workflow-guide

**Comment by MLWALK3R** [comment]
@f0o I just rename ubiquiti.png to edgeos, laf added the original32x32 so I guess its ok?

**Comment by f0o** [comment]
legit

**Pull request merged**
