### PR TITLE
Alert schedule refactor

### PR DESCRIPTION
**Pull request by murrant**
Allow maintenance schedule check in Laravel code.
Fixes to the schedule editor
Change the target selection to select2 like the alert rule editor.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Initial testing looks ok, need to wait for maintenance window to finish now and see if alerts are ok then test reoccurring + groups.

**Comment by laf** [comment]
Not sure if this is an issue from how it was before but you can't set any date in the future. The default seems to stop at the current date time but if you set a future date then you're still restricted on the hours you can set it for.

**Comment by murrant** [comment]
@laf I ran into that during testing and tried to fix it.  Perhaps I didn't fix all the cases...

**Comment by murrant** [comment]
@laf ok, I think I have all the cases covered now for limiting the datetime picker...

**Comment by laf** [comment]
Now still seems wrong.

If you pick reoccuring and set the start date to tomorrow, you won't be able to pick any hour, it will limit you.

Non-reoccuring ones also don't allow you to set a future date and time past the current time - date itself works just not the time.

**Comment by murrant** [comment]
@librenms/reviewers anything holding this up?  I'd like to consider merging the migrations PR this month and having this merged would make it easier.

**Comment by laf** [comment]
Re-occuring schedules still don't allow you to set a time later than the current time even if you select a later date.

**Comment by murrant** [comment]
@laf I can't reproduce that.  In recurring start hour cannot be after end hour and end hour cannot be before start hour.  Recurring must hour/min must be contained in a single day.

**Comment by laf** [comment]
> @laf I can't reproduce that. In recurring start hour cannot be after end hour and end hour cannot be before start hour. Recurring must hour/min must be contained in a single day.
> 
> Something like this might be more appropriate.
> [codepen.io/caseymhunt/pen/kertA](https://codepen.io/caseymhunt/pen/kertA)

Makes sense.

Probably not worth merging this late hour for 1.47.

**Pull request merged**
