### PR TITLE
Adds tripplight snmpwebcard support

### PR DESCRIPTION
**Pull request by nkringle**
Please give a short description what your pull request is for

I am adding the MIB for older TrippLight SNMPWEBCARD based UPS and adding sensor data it reports (specifically ambient temp, ambient humidity, and battery age). I also strengthened the pre-exisitng tripplight power alert testing data that was missing for `poweralert.snmprec` and `poweralert_1.snmprec`. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it. (N/A)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
> Please add test data so we can ensure your change is not broken in the future.
> 
> Read the docs to find out how: https://docs.librenms.org/Developing/os/Test-Units

Missing step 2 of the test data

**Comment by nkringle** [comment]
> > Please add test data so we can ensure your change is not broken in the future.
> > Read the docs to find out how: [docs.librenms.org/Developing/os/Test-Units](https://docs.librenms.org/Developing/os/Test-Units)
> 
> Missing step 2 of the test data

I was having a hard time getting that step to work for me (running macos big sur). I got stuck at the script not being able to ping snmpsim. Any suggestions on what that could be? I did get snmpsim to start up via the test script.

**Comment by Jellyfrog** [comment]
Try changing:
https://github.com/librenms/librenms/blob/488cc2b2c436f83419402e45ac172f29a7626112/scripts/save-test-data.php#L105
To:
```php
 $snmpsim = new Snmpsim('127.0.0.1'); 
```

Also check what `./scripts/save-test-data.php --snmpsim` says

**Comment by nkringle** [comment]
> Try changing:
> 
> https://github.com/librenms/librenms/blob/488cc2b2c436f83419402e45ac172f29a7626112/scripts/save-test-data.php#L105
> 
> 
> To:
> ```
>  $snmpsim = new Snmpsim('127.0.0.1'); 
> ```
> 
> Also check what `./scripts/save-test-data.php --snmpsim` says

That helped. For some reason I also had a problem where FPing wasn't installed. I was feeling generous and generated test json data for the other two (already existing) variants in addition to my new variant.

**Comment by nkringle** [comment]
The `license/cla` check hasn't completed but has been running for days. Not sure on that, but I do believe this PR is ready for review/merge.

**Comment by Jellyfrog** [comment]
Isn't there some serial/hardware/software info to add also?

**Comment by nkringle** [comment]
> Isn't there some serial/hardware/software info to add also?

I didn’t think there was. It’s working on my development system. I’d be happy to add it, I just don’t know exactly what you’re referring to.

**Comment by nkringle** [comment]
> Isn't there some serial/hardware/software info to add also?

Do you mean the [discovery file](https://github.com/librenms/librenms/blob/master/includes/definitions/poweralert.yaml)?

**Comment by Jellyfrog** [comment]
I mean adding more data from the snmp, https://docs.librenms.org/Developing/os/Initial-Detection/#yaml-based-os-discovery
so it collects what hardware it is, and if it has a serial number, etc etc.

**Comment by nkringle** [comment]
Yeah I can flush it out. It seems like a lot of its data is coming from `rfc1628_compat = true`. Maybe that is a bad assumption?

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
