### PR TITLE
webui: health pages refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

tried to give the health pages consistent look.

before:
screen shot 2017-12-01 at 5 12 41 am

after:
screen shot 2017-12-01 at 5 11 58 am

### CODE REVIEW

**Comment by breeman1** [comment]
Hi @crcro, Shouldn't the title name called "Used" be aligned with the actual bar graphs. Looks to be offset to the left.

**Comment by crcro** [comment]
@breeman1 ... this should be better?

screen shot 2017-12-01 at 4 02 40 pm

**Comment by murrant** [comment]
@crcro you also lost the navigation here.

**Comment by crcro** [comment]
@murrant  ... didn't loose it, removed it intentionally, same for wireless

**Comment by laf** [comment]
> didn't loose it, removed it intentionally, same for wireless

Any reason why, that's handy set of links to move between the health sensors?

**Comment by crcro** [comment]
@murrant, @laf ... integrated in page navbar, is this ok?

screen shot 2017-12-04 at 8 37 00 am

**Comment by laf** [comment]
@crcro looks good.

**Comment by murrant** [comment]
The header Health::Memory looks a little redundant.  Is there a reason you didn't put navigation in the header.  Think of them as tabs.

**Comment by crcro** [comment]
@murrant ... i think that this new version is more organized:

screen shot 2017-12-04 at 11 21 46 pm

**Comment by murrant** [comment]
Thanks, now just to update the others.

**Comment by crcro** [comment]
already pushed an update for others (device, wireless)

**Comment by kkrumm1** [comment]
Worked for me and looks good.

**Pull request merged**
