### PR TITLE
fix: bgp-peers fails when ip parsing fails

### PR DESCRIPTION
**Pull request by murrant**
Don't try to call ->getFamily() if we didn't parse an IP
Stops the discovery after this is encountered.

We have a junos device returning '&hT' for a peer, tracking down the source, but fixing this is advised in the meantime.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Doesn't cause issues on Arista.

However should the lack of IP being returned not be handled in IP::fromHexString otherwise this check will have to be repeated anywhere else this is used.

**Comment by murrant** [comment]
Most of the time we just convert it to a string afterwards.  So, null -> ''.  This tries to call a method on the object, which is null when it fails.  

Try catch is much better, otherwise you have to add in if not null else.

**Comment by murrant** [comment]
Test by user that reported the issue.

**Comment by murrant** [comment]
@laf there is a check inside IP::fromHexString, it throws an invalid IP exception.  However, we had enabled the ignore errors parameter on this call previously.

**Comment by laf** [comment]
Maybe we shouldn't return null then and instead an empty string?

Ignoring errors is correct though, we should never break polling or discovery from completing.

**Comment by murrant** [comment]
`''->addressFamily()` would still cause a fatal error ;)

**Comment by BradHooper** [comment]
This fixed the lack of BGP prefix graphs on Juniper devices. Thank you.

**Pull request merged**
