### PR TITLE
Greatly reduces application JavaScript memory leak

### PR DESCRIPTION
**Pull request by rmedlyn**
Removed clone statement from jquery-bootgrid destroy function that was causing anything in a bootgrid table to persist and not get garbage collected. Also added some code to make sure a table is emptied of elements and event listeners on widget refresh. If those are too much, calling destroy on its own after the fix still significantly reduced the leak. I also realize that my minification might be a bit different than the original. I can take a look at that if it's a concern.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7215)

### CODE REVIEW

**Comment by murrant** [comment]
I see there is a PR for this upstream.  Perhaps it is best to get it fixed there as someone may just update the bootgrid files later, removing your fix.

At least you should comment on that PR to help it get merged.

https://github.com/rstaib/jquery-bootgrid/issues/216

**Comment by laf** [comment]
This library hasn't had an update in 2 years. We could just fork it and maintain this patch locally or merge in expect that no further updates are to be provided upstream.

**Comment by rmedlyn** [comment]
At this point, I think that maintaining a fork seems to be the best long-term option short of porting to a more up-to-date library like DataTables.

**Comment by murrant** [comment]
Yeah, unfortunate, bootgrid does look unmaintained.

Looks good after you fix the conflict.  It looks like your branch might be out of date with master or something.

**Comment by laf** [comment]
@rmedlyn Are you able to fix the conflict?

**Comment by rmedlyn** [comment]
Should be fixed now. Sorry for the delay.

**Comment by rmedlyn** [comment]
@laf Does everything look okay now?

**Comment by laf** [comment]
Testing

**Pull request merged**
