### PR TITLE
refactor: OS Discovery cleanup (Part 1)

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Convert linux.inc.php to use new string functions
Create OS discovery tests
Use glob instead of readdir in os discovery (could change discovery order)
Stop discovering once $os is set

### CODE REVIEW

**Comment by crcro** [comment]
in tests/mocks/mock.snmp.inc.php you have added the starting comment block twice

**Comment by laf** [comment]
Running at home.

needs a rebase + you've got `function register_mibs()` in the test file, is that supposed to be there?

**Comment by laf** [comment]
No issues for me on existing install.

**Comment by murrant** [comment]
laf, yeah, otherwise I get function undefined when register_mibs() is called.  I didn't need any other functions stubbed yet for discovery in the linux file.

**Comment by laf** [comment]
Probably only https://scrutinizer-ci.com/g/librenms/librenms/inspections/6b1527d7-8e0c-4cdf-bc3e-93c92d39a2d6/issues/files/tests/OSDiscoveryTest.php?status=new&orderField=path&order=asc&honorSelectedPaths=0 worth fixing in scrut.

Good to go after that.

**Pull request merged**
