### PR TITLE
webui: Added Oxidized config validator

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

I'm happy for this not to be part of LibreNMS and I'll just chuck it on my site for people to use

### CODE REVIEW

**Comment by murrant** [comment]
Interesting, I'll take a peak sometime.

**Comment by murrant** [comment]
Works :)

Needs positive feedback when the config is ok.
The textarea is too tall, I have to scroll a lot to get do the submit button.

**Comment by murrant** [comment]
Any thoughts of putting a button under the oxidized page instead of the menu?
I'm not convinced one is better than the other, just a thought.

**Comment by laf** [comment]
Just pushing a commit that will reduce the box height and also adds feedback when the config is ok.

I'm not fussed either way on where the link actually is, possibly would be more hidden if it was within the other page though.

**Comment by laf** [comment]
That's a good point. I'll move it tomorrow.

**Comment by laf** [comment]
Slight rejig of location for the link.

image

Also added small bit of blurb in docs for it.

**Pull request merged**
