### PR TITLE
[WebUI] Custom OID - Removing the colon symbol

### PR DESCRIPTION
**Pull request by ilGino**
In order to make the "Custom OID" >> "Add New OID" modal page more visually consistent with other pages in the system, removed the colon simbol ":" to the very right of each control description, where present.

Regards
GG

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
if you plan on fixing more pages, could you please add them to the same pull request

**Comment by ilGino** [comment]
> if you plan on fixing more pages, could you please add them to the same pull request

Sure, I'll follow your indications.
Sorry for flooding with small Pull Requests, my understanding was that small changes on single files were somehow easier to track.

Thank you again and regards
GG

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by ilGino** [comment]
This Pull Request is being retired in favor of a new larger Pull Request proposing the same visual cleanup on more files and more web pages (found until now: Custom OID, New Alert Transport, New Alert Rule, New Scheduled Maintenance, New Alert Template).

Regards
GG

**Pull request closed without merging**
