### PR TITLE
Update to add acl on list of necessary package

### PR DESCRIPTION
**Pull request by Cormoran96**
Add acl package for the installation of Librenms

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Thanks can you update the nginx install too and keep the package list alphabetical (put acl first)

**Comment by Cormoran96** [comment]
I added !

**Comment by murrant** [comment]
@Cormoran96 I just checked and acl is installed by the base system in Ubuntu 16.04.  Why do we need to add it?

**Comment by Cormoran96** [comment]
I just check on minimal install.

**Pull request merged**
