### PR TITLE
Create qnap.inc.php

### PR DESCRIPTION
**Pull request by GeorgesDick**
Get QNAP Turbo NAS Fans speeds

### CODE REVIEW

**Comment by laf** [comment]
Just as an FYI, you can submit things like this in one PR for future. Multiple commits showing each is fine but not necessary for small commits.

**Comment by GeorgesDick** [comment]
Di you mean that I can add (or edit) multiple files, and then submit only
one PR at the end?

Thank you for your help,
Georges

2016-02-25 10:34 GMT+01:00 Neil Lathwood <notifications@github.com>:

> Just as an FYI, you can submit things like this in one PR for future.
> Multiple commits showing each is fine but not necessary for small commits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/3088#issuecomment-188691953>.
>



-- 
Cordialement,

Georges DICK
email georges@monaco.net
http://georgesdick.com

**Comment by laf** [comment]
Yes that's correct. Let's take these two as an example:

Edit includes/discovery/sensors/fanspeeds/qnap.inc.php and do what you need.
git add includes/discovery/sensors/fanspeeds/qnap.inc.php (only needed when first creating the file).
git commit -a -m 'Added fanspeeds support to qnap devices'
Edit includes/discovery/sensors/temperatures/qnap.inc.php
git add includes/discovery/sensors/temperatures/qnap.inc.php
git commit -a -m 'Added temperature support to qnap devices'
git push

**Comment by GeorgesDick** [comment]
Tahnks !

And when using Github website?
- "Propose new file" (or ("Propose file change")
- "Propose new file" (or ("Propose file change")
(etc.)
- "New Pull Request"

Am I correct?

2016-02-25 12:22 GMT+01:00 Neil Lathwood <notifications@github.com>:

> Yes that's correct. Let's take these two as an example:
>
> Edit includes/discovery/sensors/fanspeeds/qnap.inc.php and do what you
> need.
> git add includes/discovery/sensors/fanspeeds/qnap.inc.php (only needed
> when first creating the file).
> git commit -a -m 'Added fanspeeds support to qnap devices'
> Edit includes/discovery/sensors/temperatures/qnap.inc.php
> git add includes/discovery/sensors/temperatures/qnap.inc.php
> git commit -a -m 'Added temperature support to qnap devices'
> git push
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/3088#issuecomment-188737744>.
>



-- 
Cordialement,

Georges DICK
email georges@monaco.net
http://georgesdick.com

**Comment by murrant** [comment]
Github allows you to select the branch when doing things in the webui.  Make sure you use the same branch as the first, rather than creating a new branch.  This will allow you to create a PR from that branch when you are done.

**Comment by GeorgesDick** [comment]
I created a new file, edited a second one, but can't find how to submit
this in only one pull request: I can see two "Compare & pull request"
buttons, but no way to merge...


2016-02-25 17:20 GMT+01:00 Tony Murray <notifications@github.com>:

> Github allows you to select the branch when doing things in the webui.
> Make sure you use the same branch as the first, rather than creating a new
> branch. This will allow you to create a PR from that branch when you are
> done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/3088#issuecomment-188860933>.
>



-- 
Cordialement,

Georges DICK
email georges@monaco.net
http://georgesdick.com

**Comment by GeorgesDick** [comment]
Hello,

Second try: I cloned librenms on my Linux box, edited/added three files,
but at the last step (git pull), after entering username/password I have an
error message:
remote: Permission to librenms/librenms.git denied to GeorgesDick.
fatal: unable to access 'https://github.com/librenms/librenms.git/': The
requested URL returned error: 403

Sorry to bother you but, although I'm writing code since more than 20
years, and I already contributed to a couple of Open Source projects, I'm
really new to github.

KR,
Georges

2016-02-25 17:20 GMT+01:00 Tony Murray <notifications@github.com>:

> Github allows you to select the branch when doing things in the webui.
> Make sure you use the same branch as the first, rather than creating a new
> branch. This will allow you to create a PR from that branch when you are
> done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/3088#issuecomment-188860933>.
>



-- 
Cordialement,

Georges DICK
email georges@monaco.net
http://georgesdick.com

**Comment by laf** [comment]
It's no problem. The issue there is you are trying to upload straight to our repo. You need to do this to your own.

We have a doc that goes in to how best to manage the repo: http://docs.librenms.org/Developing/Using-Git/

For now, we'll merge these ones it's more just an fyi.

**Pull request merged**
