### PR TITLE
adding serial number discovery to aruba os poller

### PR DESCRIPTION
**Pull request by sjtarik**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Please just upload what it generates, its a new device, so it will be full output

**Comment by Jellyfrog** [comment]
Also, your snmprec file looks rather small?

**Comment by sjtarik** [comment]
> Please just upload what it generates, its a new device, so it will be full output

This change is only to add serial number field to existing aruba WL. I added as a new model to avoid conflict with existing test cases.

**Comment by sjtarik** [comment]
> Also, your snmprec file looks rather small?

only added the part necessary for serial number field, my problem is collect-snmp-data.php respects the modules parameter so I can limit the snmp info returned for privacy. however save-test-data.php does not respect the modules parameter so it fails the test because snmp data and json data does not match. privacy needed here for me to hide wireless client info and some sensitive port info descriptions.

**Comment by Jellyfrog** [comment]
you could manually replace sensitive data with `<private>` or so, we do that automatically for a couple of OIDs if its not too much hassle?

**Comment by sjtarik** [comment]
due to sensitive information I am not able to share a lot of test data and to be honest it is not relevant to the feature since it will only add serial number data a single OID and existing tests are already covering the rest. I will do my best and update this diff.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
