### PR TITLE
Clarify non-x86 hardware info sources for snmpd

### PR DESCRIPTION
**Pull request by dorkmatt**
Follow-up to #12195, this PR gives examples for ARM-based metadata (model, serial number, etc). In particular this is geared for Raspberry Pi 4 hosts.

image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by dorkmatt** [comment]
While here, also suggest that https://github.com/librenms/librenms-agent/blob/master/snmp/snmpd.conf.example get removed from the librenms-agent repo - as that is a duplicate and isn't in sync with the master librenms repo version.

**Comment by Jellyfrog** [comment]
You could fix this place also, https://docs.librenms.org/Support/SNMP-Configuration-Examples/#linux-snmpd-v2

**Comment by dorkmatt** [comment]
@Jellyfrog Sure, good catch - I proposed some additional wording, will update the commit with the complete file once this is approved.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1

**Pull request merged**
