### PR TITLE
Improved Latency graph

### PR DESCRIPTION
**Pull request by murrant**
Store loss+jitter info in rrd instead of database
New graph icmp_perf (legacy ping_perf still valid referencing part of the newer data)
Delete device_perf table
Drops traceroute info for alerts because it was tied to the device_perf table.

CAUTION!  this will cause issues if you run mismatched code on pollers/webui/etc.

image

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Wondering if some alerting will break?

**Comment by murrant** [comment]
> Wondering if some alerting will break? Maybe needs some news post about it

Good thought, upon review, if you tried to use device_perf in an alert rule it could return EVERY ping response on the device.  It would take some careful rule creation to not explode your LibreNMS install referencing that table.

Interestingly enough, because I added Rrd::lastUpdate() in this PR, it could potentially be used to do limited alerting based of rrd data.

**Review by Jellyfrog — APPROVED** [review]

**Comment by freeball155** [comment]
> Wondering if some alerting will break? Maybe needs some news post about it

It's definitely break packet_loss_5m macro.
Please look https://community.librenms.org/t/multiple-device-perf-doesnt-exist-error/24159/2

**Comment by peejaychilds** [comment]
nice work - bit sad to loose traceroute option?

I wonder if something similar could be done with the alert templates?

Have the template execute traceroute() from LibreNMS/Polling/ConnectivityHelper.php and include the output?

It would be interesting to have some persistence abilities via Alert Templates as well ... ie can I store 'stuff' against the alert and/or the device which is visible via the UI so you could store the output of the traceroute have have visible on the UI (similar to prior behaviour), but that you could use in more generic ways.

For example on a JunOS red/yellow alarm alert (a sensor based alert) I could execute a gNMI get on system/alarms and include that in my alert raise, but also on the UI screen ... or parse and add to EventLog etc.

I have a funny feeling using @php and @endphp in templates most of this is probably doable currently?

**Comment by murrant** [comment]
@peejaychilds it is sad, but it was a bit silly to store those in that location in the first place.  Would be happy to have a rework, all alert data is stored in the database.  But the tricky part is the device generating the alert may not be able to properly run a traceroute, it needs to be run by the poller.

**Pull request merged**
