### PR TITLE
Bug - VRP - fix OutOfRange QueryException + missing key

### PR DESCRIPTION
**Pull request by PipoCanaja**
TINYINT overflow.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Running this into my prod to validate it a few days.

**Comment by murrant** [comment]
Fix looks good to me, but it would probably be better to fix it higher up.

**Comment by PipoCanaja** [comment]
> Fix looks good to me, but it would probably be better to fix it higher up.

In fact, the value 255 is replied by the device in case `radioutil` cannot be provided (like if radio is off for instance). That's why I turn it to -1 (so it is not range 0-100, and still in -127/+128 TINYINT range).
We could indeed make the column nullable if that's what you mean. But extending TINYINT to next bigger size seems unnecessary.

**Comment by PipoCanaja** [comment]
Got your point, will do !

**Review by murrant — APPROVED** [review]

**Pull request merged**
