### PR TITLE
 Added peer context/vrf to the devices bgp peers page, added getting of vrf from vrf table instead of only vrflites

### PR DESCRIPTION
**Pull request by Senetus**
Please give a short description what your pull request is for

Added peer context/vrf to the devices bgp peers page

image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Senetus** [comment]
Thanks @murrant for the vrf code!

**Comment by murrant** [comment]
The one question I have is should this always include the default context?

**Comment by Senetus** [comment]
> The one question I have is should this always include the default context?

At least when concerning aristas, yes I would say.

Since there the deafult is the default vrf too and that can't be changed. So all the context polling should be in addition of the default.

**Comment by Senetus** [comment]
Well, bgp peers of course should only be polled with their own context, but discovery should loop though all. Eg. the routes module should first run on the default, and then on any additional context.

**Comment by PipoCanaja** [comment]
Hum, matching between peers and context does not return correct results on other devices (Huawei VRP currently in my tests). Will also test Cisco and see how it goes

**Comment by PipoCanaja** [comment]
@Senetus Contexts, VRF, VRF Lite, all these elements are mixed in LibreNMS but they are not used the same way by all vendors. 
Setting a context for a Device may change the way bgp-discovery and OSPF discovery is done. Which is not what you expect. In fact the context is like a kind of "view" for some mibs. 

What would probably make sense is fetch in which VRF the peer is connected, and store it during BGP discovery in the DB to display it later on.

**Comment by Senetus** [comment]
That's corrext. In arista world a vrf is a namespace and thus also a context. Routes and bgp peers need to be polled/discovered within this context.

**Comment by PipoCanaja** [comment]
> That's correct. In arista world a vrf is a namespace and thus also a context. Routes and bgp peers need to be polled/discovered within this context.

Then you have to enable this context setting only for an Arista device, and keep the new column hidden by default. (which means rewrite this table so that columns can be displayed/hidden).

**Comment by PipoCanaja** [comment]
In fact, context is used for context polling, and context polling may be used for VRFs or other polled data, but this is completely vendor-specific. For most of the devices, this column is not used at all. 
Displaying it unconditionnally is probably not a good idea. And changing [app/Models/Device.php](https://github.com/librenms/librenms/pull/13804/files?show-viewed-files=true&file-filters%5B%5D=#diff-56d0c99da95b2d1d1621c1b694577893589ba6560b344eab93142ccad8c49ff6) is probably not a good idea as it breaks a lot of regression tests. 

So if you can make a proper use of this column for Arista devices, you are very welcome to do so, and adapt the test data as well.
But you'll have to avoid any side effect on other devices.

**Comment by Senetus** [comment]
Yeah, would make sense to display it only if there is something to display. Regarding the broken tests, I adjusted with help of murrant the getvrf's function, since it was only getting vrf lites instead of also data from the vrfs table, like the name would suggest. He did mention probably merging those tables together, so that wouldn't fix the tests most likely.  I don't really know what to do about that.

**Pull request closed without merging**
