### PR TITLE
Additional Open Sense detection

### PR DESCRIPTION
**Pull request by FingerlessGlov3s**
Update opnsense.yaml for new OPNsense OID called version.
This will help with detection after the user turns on "Display Verion in OID" within OPNsense.
Currently detection won't work unless you have OPNsense in the hostname

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/opnsense-os-detection-issues/10222/7

**Comment by murrant** [comment]
No better way to detect these?  snmpget is pretty bad and the more we have the worse.  So we try to minimize them.

**Comment by FingerlessGlov3s** [comment]
@murrant, I did a SNMP walk and this is the only good way I can make it detect. As the sysdescr doesn't contain opnsense if you change the hostname to say fw1-north

**Comment by murrant** [comment]
Ok, but you should qualify it so it only does the snmpget if the sysObjectID is `1.3.6.1.4.1.12325.1.1.2.1.1`

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Comment by FingerlessGlov3s** [comment]
This new detection didn't work for my OPNsense install, the SysObjectID isn't what you put '1.3.6.1.4.1.12325.1.1.2.1.1' mines reporting as '.1.3.6.1.4.1.8072.3.2.8' which is the same for both my 19.7 install and 20.1.

I should of checked this before you approved the change, my mistake.

**Comment by FingerlessGlov3s** [comment]
Created new PR, to fix this bug.
https://github.com/librenms/librenms/pull/11251

**Pull request merged**
