### PR TITLE
Convert OS discovery to new style

### PR DESCRIPTION
**Pull request by murrant**
Convert all OS that have test data to Yaml and Class based OS Discovery.

Attempted to preserve the format, but some changed for consistency, additional data and other issues.

Here is the yaml example from the docs:
```yaml
modules:
    os:
        sysDescr_regex: '/(?<hardware>MSM\S+) .* Serial number (?<serial>\S+) - Firmware version (?<version>\S+)/'
        features: UPS-MIB::upsIdentAttachedDevices.0
        hardware:
            - ENTITY-MIB::entPhysicalName.1
            - ENTITY-MIB::entPhysicalHardwareRev.1
        hardware_template: '{{ ENTITY-MIB::entPhysicalName.1 }} {{ ENTITY-MIB::entPhysicalHardwareRev.1 }}'
        serial: ENTITY-MIB::entPhysicalSerialNum.1
        version: ENTITY-MIB::entPhysicalSoftwareRev.1
        version_regex: '/V(?<version>.*)/'
```

Still 171 legacy os polling files exist.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
You're a beast

**Comment by PipoCanaja** [comment]
> You're a beast

I don't find any other way to say it :D

**Comment by murrant** [comment]
Ok, tests are passing for this now. Docs updated, it is ready to merge.

**Review by Jellyfrog — APPROVED** [review]

**Comment by PipoCanaja** [comment]
Huge and impressive change. I reviewed the OSes I have most and I haven't seen anything to frighten me. But I can't call it a "review". :) Let see it live :D

**Comment by brockcj** [comment]
Looks like this broke OS version and hardware detection for some Dell FTOS/OS9 devices. Our OS9 devices all dropped the OS version and hardware information when our system auto-updated Saturday morning. OS6 based devices are working fine though.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
