### PR TITLE
Fix LDAP slow login

### PR DESCRIPTION
**Pull request by louis-oui**
Related to https://community.librenms.org/t/authentification-with-the-ldab-very-slow/1836/4

Do not parse all user if fallback of memberof

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/authentification-with-the-ldab-very-slow/1836/6

**Comment by deajan** [comment]
Could be further optimized by using ldap_search with a restrictive filter which returns only one user so the whole foreach isn't necessay:

Example filter:
```
$filter = '(&(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(|((samaccountname=$this->userloginname)(cn=$this->userloginname)(uid=$this->userloginname)(userPrincipalName=$this->userloginname))))';
```

**Comment by deajan** [comment]
Since we know the user DN via `$this->getFullDn($username)`, you can litterally write a filter using solely the DN as filter, making the request way more speedy and easy to read.

**Comment by louis-oui** [comment]
@deajan please test the patch

**Comment by louis-oui** [comment]
**My tests with are OK**

Test of the patch : Variable $pass contains my password and $badpass an incorrect password

Correct password : login OK => expected
```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ echo $pass  | ./auth_test.php -d -v -u toto | more
Copied deprecated config fping_options.millisec to fping_options.interval
Authentication Method: ldap
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Password: 
Authenticate user toto: 
**AUTH SUCCESS**

User (74513):
  username => toto
  realname => TATA toto
  user_id => 74513
  email => toto.tata@domain.com
  **level => 10**
Groups: ; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr
; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr
```
Incorrect password : login KO=> expected

```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ echo $badpass  | ./auth_test.php -d -v -u toto | more
Copied deprecated config fping_options.millisec to fping_options.interval
Authentication Method: ldap
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Password: 
Authenticate user toto: 
Error: LibreNMS\Exceptions\AuthenticationException thrown!
**Invalid credentials**
```
Comment out line the in config.php that match group of wich user toto is member
// $config['auth_ldap_groups']['XXX']['level'] = 10;

```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ vi ../config.php
```
Incorrect password without group in config.php : login KO=> expected

```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ echo $badpass  | ./auth_test.php -d -v -u toto | more
Copied deprecated config fping_options.millisec to fping_options.interval
Authentication Method: ldap
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Password: 
Authenticate user toto: 
Error: LibreNMS\Exceptions\AuthenticationException thrown!
**Invalid credentials**
```
Correct password without group in config.php : login KO=> expected

```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ echo $pass  | ./auth_test.php -d -v -u toto | more
Copied deprecated config fping_options.millisec to fping_options.interval
Authentication Method: ldap
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Password: 
Authenticate user toto: 
Error: LibreNMS\Exceptions\AuthenticationException thrown!
**Compare False**
```
Uncomment line of group in config.php. Change level of group from 10 to 5.

```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ vi ../config.php
```
Correct password with group level 5 in config.php : login OK=> expected

```
[root@librenms-prod-dc1 /appl/librenms/scripts]$ echo $pass  | ./auth_test.php -d -v -u toto | more
Copied deprecated config fping_options.millisec to fping_options.interval
Authentication Method: ldap
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Password: 
Authenticate user toto: 
AUTH SUCCESS

User (74513):
  username => toto
  realname => TATA toto
  user_id => 74513
  email => toto.tata@domain.com
  level => 5
Groups: ; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr
; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr; cn=XXXX,ou=Groups,dc=company,dc=titi,dc=fr
```

**Comment by louis-oui** [comment]
@PipoCanaja please review my patch

**Comment by deajan** [comment]
@louis-oui Didn't get a chance to test the PR itself, but from what I've read, it looks correct to me and should definitly speedup LDAP lookups by an order of magnitude using the user DN as search base.
Nice work man ;)

(ps: u French ?)

**Comment by louis-oui** [comment]
@deajan  yes I am French . but alors you are french :-)

**Comment by PipoCanaja** [comment]
Mais alors, we can switch to french in this PR ?  :) I don't have much of a lab for this LDAP auth module, so I can only do a 'paper' review. Let see the results of other tests first.

**Comment by louis-oui** [comment]
Hello,

I have tested my fix successfully but I need somebody else to test the fix.

In order to test the code, assuming app is in /opt/librenms :
cp -p /opt/librenms/LibreNMS/Authentication/LdapAuthorizer.php /opt/librenms/LibreNMS/Authentication/LdapAuthorizer.php.old
wget https://raw.githubusercontent.com/louis-oui/librenms/ldap/LibreNMS/Authentication/LdapAuthorizer.php -O /opt/librenms/LibreNMS/Authentication/LdapAuthorizer.php

To revert change :
cp -p /opt/librenms/LibreNMS/Authentication/LdapAuthorizer.php.old /opt/librenms/LibreNMS/Authentication/LdapAuthorizer.php

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/modify-the-getuserlist-fonction-to-use-ldap-filter/8781/4

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ldap-with-jumpcloud/6883/5

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ldap-tls-negotiation-error/1576/8

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/feature-request-full-dn-as-group-member-attibute-in-ldap-auth/4805/8

**Comment by louis-oui** [comment]
Bonjour @PipoCanaja, no one else is testing this fix.
Please review my tests

**Comment by PipoCanaja** [comment]
Hello @louis-oui 
I suggest that you keep an eye in community.librenms.org in the next few days in order to control that nothing bad happens there. 
Bye

**Comment by louis-oui** [comment]
OK I check the community

**Comment by louis-oui** [comment]
Issue here https://community.librenms.org/t/ldap-authentication-problem-with-webui/6115/3

**Comment by remydb** [comment]
Also running into issues after this was merged. Users authenticate, but attributes don't seem to be passed along properly, as shown by the following auth test:
```
$ ./scripts/auth_test.php -v -d -u testuser
Authentication Method: ldap
Password:
Authenticate user testuser:
AUTH SUCCESS

User ():
  username =>
  realname =>
  user_id => 0
  email =>
  level => 0
Groups: ; cn=NMSAdmin,ou=Groups,dc=testorg,dc=com
```

**Comment by louis-oui** [comment]
Hello @remydb 

https://community.librenms.org/t/ldap-authentication-problem-with-webui/6115/3

Could send send us content of command “grep auth_ config.php” so that we can debug. Hide confidential infos!

In the meantime, you can revert the change on your setup only using this line :
./script/github-apply 10855

**Comment by louis-oui** [comment]
@remydb In order to debug, could you also send me result of command. Replace $config[X] and $username with real values :

ldapsearch -H "$config['auth_ldap_server']" -x -b "$config['auth_ldap_prefix']$username$config['auth_ldap_suffix']" "(uid=*)"

remove comma at begginning $config[‘auth_ldap_suffix’]"
ldapsearch -H "$config['auth_ldap_server']" -x -b "$config['auth_ldap_suffix']" "(uid=$username)"

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/active-directory-ldap-authentication-not-working/10179/4

**Comment by louis-oui** [comment]
@remydb kindly reply to my message so that I can see what was not working on this change

**Pull request merged**
