### PR TITLE
Oxidized add more fields for map

### PR DESCRIPTION
**Pull request by Negatifff**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Negatifff** [comment]
add 2 fields for "Creating overrides" for oxidized: type and oid.

**Comment by Negatifff** [comment]
no problems. you can take my changes if necessary.

**Comment by Negatifff** [comment]
> I would rather see #11567 implemented then expand the existing code.

Look, I'm sorry, but I'm newbie in github. Please explain - you requesting changes, what should I do? Or just wait?

**Comment by murrant** [comment]
I'm saying your changes would be just fine, if it were not for some other pending changes that do the same thing only better.  That other PR does need a little help though.

**Comment by Negatifff** [comment]
yes, but no;). I agree that the solution in that PR is more interesting. but it lacks the ability to use the type in the case when the device does not participate in any group or participates in a group that will not be transferred to oxidized.

**Comment by murrant** [comment]
I just looked at this again and it seems like you are trying to remap the os.  It would better if you just did that here: https://github.com/librenms/librenms/blob/master/includes/html/api_functions.inc.php#L1348

**Comment by murrant** [comment]
Closing this for now. Feel free to reopen.

**Pull request closed without merging**
