### PR TITLE
fix: Update applications poller to use numeric oid instead of nsExtendOutputFull

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #5197 

Seen a few issues now where nsExtendOutputFull doesn't work but the OID does. I don't know why so switched the applications around to use numerical oid.

### CODE REVIEW

**Comment by murrant** [comment]
@laf Not sure about this.
nsExtendOutLine.* = each line at a different oid
nsExtendOutputFull = all lines at one OID

I think you glazed over that a bit in these changes.

If you change all of them to nsExtendOutputFull  ".1.3.6.1.4.1.8072.1.3.2.3.1.2", then it should just be snmp_get(), not snmp_walk();

**Comment by laf** [comment]
Sorry I'm not sure what you mean by the comment in the code block.

As for _get instead of _walk, this change shouldn't alter us looking up a table, the lookup is the same as before but we aren't using the named oid.

**Comment by murrant** [comment]
I'm saying there is confusion of nsExtendOutputFull and nsExtendOutLine all over the applications.

You've replaced them all with nsExtendOutputFull (numeric).   Which is a single OID so all of the SNMP calls should just be snmp_get.

**Comment by laf** [comment]
Rebased

**Comment by murrant** [comment]
Odd that this is needed.  But no issues with it.

**Pull request merged**
