### PR TITLE
fix: AD auth stop alerts being generated

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Was causing alerts to fail as html/includes/functions.inc.php isn't included for these functions to work.

### CODE REVIEW

**Comment by murrant** [comment]
I'll try to test this tonight.

**Comment by nathanthorpe** [comment]
Works for me

**Comment by laf** [comment]
This was tested by someone in irc - as it's breaking alerts we need to get it in the codebase so merging.

**Comment by ekoyle** [comment]
Alerts are probably failing anyway since we aren't using a separate bind user for AD/LDAP; therefore we can't look up an email address.

It seems like _really_ bad form to include something from html/ in the backend code...

**Pull request merged**
