### PR TITLE
feat: ADD co field for Opentsdb

### PR DESCRIPTION
**Pull request by yac01**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Now, what does this `co` field do and why is it on the device table?

**Comment by yac01** [comment]
@murrant  I am updating the doc and  I explain what the field co do

**Comment by yac01** [comment]
hello @laf  @murrant  the field co is for the cutomer identité for who wante to suffix her metrics by this.
and you can to add for eche device her customer identité because when you use grafana Librenms genérate metrics with long queries and it is a problem in some cases because grafana loses time to look for the metric in the database opentsdb and sometimes it put error request so to avoid it is better to suffix by an object code Or the name of customer like this we win the speed and avoid error request

**Comment by murrant** [comment]
As mentioned on IRC, this needs a way to modify the value from the webui.

Would also be good if it applied to other data stores, but that is not required. ;)

**Comment by yac01** [comment]
for the moment i can't do this but when i will have time i will  do it

**Comment by laf** [comment]
@yac01 Any update to this?

**Comment by yac01** [comment]
hello @laf  yes i have started one page that by what you can modify all database but i have not finishe this page because I was obliged to work on the migration from observium to librenms and because that as like all igration i had to resolve some probleme for some device and réhabilitated somme plugin of observium to librenms but i think i will continue that this week

**Pull request closed without merging**
