### PR TITLE
Update PHP dependencies

### PR DESCRIPTION
**Pull request by murrant**
Fix PSR-4 violations

symfony/polyfill-ctype v1.12.0 => v1.15.0
phpoption/phpoption 1.5.2 => 1.7.3
vlucas/phpdotenv v3.6.0 => v3.6.2
symfony/css-selector v4.4.0 => v4.4.7
symfony/polyfill-php72 v1.12.0 => v1.15.0
symfony/polyfill-mbstring v1.12.0 => v1.15.0
symfony/var-dumper v4.4.0 => v4.4.7
symfony/routing v4.4.0 => v4.4.7
symfony/process v4.4.0 => v4.4.7
symfony/polyfill-php73 v1.12.0 => v1.15.0
symfony/polyfill-intl-idn v1.12.0 => v1.15.0
symfony/mime v4.4.0 => v5.0.7
symfony/http-foundation v4.4.0 => v4.4.7
symfony/event-dispatcher v4.4.0 => v4.4.7
psr/log 1.1.2 => 1.1.3
symfony/debug v4.4.0 => v4.4.7
symfony/error-handler v4.4.0 => v4.4.7
symfony/http-kernel v4.4.0 => v4.4.7
symfony/finder v4.4.0 => v4.4.7
symfony/console v4.4.0 => v4.4.7
symfony/polyfill-iconv v1.12.0 => v1.15.0
egulias/email-validator 2.1.11 => 2.1.17
ramsey/uuid 3.8.0 => 3.9.3
opis/closure 3.4.1 => 3.5.1
symfony/translation v4.4.0 => v4.4.7
nesbot/carbon 2.27.0 => 2.32.2
monolog/monolog 1.25.2 => 1.25.3
league/flysystem 1.0.57 => 1.0.66
erusev/parsedown 1.7.3 => 1.7.4
laravel/framework v5.8.35 => v5.8.37
guzzlehttp/guzzle 6.4.1 => 6.5.2
fico7489/laravel-pivot 3.0.3 => 3.0.4
martinlindhe/laravel-vue-i18n-generator 0.1.42 => 0.1.46
php-amqplib/php-amqplib v2.0.2 => v2.11.1
phpmailer/phpmailer v6.1.3 => v6.1.5
symfony/yaml v4.4.0 => v4.4.7
fideloper/proxy 4.2.1 => 4.3.0
maximebf/debugbar v1.15.1 => v1.16.1
barryvdh/laravel-debugbar v3.2.8 => v3.2.9
doctrine/cache 1.9.1 => 1.10.0
seld/phar-utils 1.0.1 => 1.1.0
composer/xdebug-handler 1.4.0 => 1.4.1
composer/spdx-licenses 1.5.2 => 1.5.3
composer/semver 1.5.0 => 1.5.1
composer/ca-bundle 1.2.4 => 1.2.6
symfony/filesystem v4.4.0 => v4.4.7
composer/composer 1.9.1 => 1.10.1
barryvdh/laravel-ide-helper v2.6.5 => v2.6.6
filp/whoops 2.5.0 => 2.7.1
fzaninotto/faker v1.9.0 => v1.9.1
laravel/dusk v5.6.1 => v5.11.0
mockery/mockery 1.2.4 => 1.3.1
webmozart/assert 1.5.0 => 1.7.0
phpdocumentor/reflection-docblock 4.3.2 => 4.3.4
phpspec/prophecy 1.9.0 => v1.10.3
myclabs/deep-copy 1.9.3 => 1.9.5
phpunit/phpunit 7.5.17 => 7.5.20
squizlabs/php_codesniffer 2.9.2 => 3.5.4
symfony/dotenv v3.4.35 => v3.4.39
psy/psysh v0.9.9 => v0.9.12
  
+phpseclib/phpseclib 2.0.26
+dnoegel/php-xdg-base-dir 0.1 => v0.1.1
-facebook/webdriver 1.7.1
+php-webdriver/webdriver 1.8.2
-jakub-onderka/php-parallel-lint 1.0.0
+php-parallel-lint/php-parallel-lint 1.1.0
  

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Either we drop support for PHP 7.1 or you need to run composer update with 7.1

**Comment by murrant** [comment]
hmm, I did run it with php7.1... maybe I missed something

**Comment by murrant** [comment]
haha, used composer_wrapper.php which launches the phar with "php"

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Pull request merged**
