### PR TITLE
Added named/bind9 Application, Graphs, Check_MK-script

### PR DESCRIPTION
**Pull request by f0o**
#411
#412

Added named/bind9 Application, Graphs, Check_MK-script.

Configuration for Bind9:
```text
options {
   ...
   statistics-file "/etc/bind/named.stats";
   zone-statistics yes;
   ...
};
```
`Permission denied` resolve: `touch /etc/bind/named.stats && chown bind:bind /etc/bind/named.stats`
(Substitute `bind:bind` with the user and group that runs your bind)

### CODE REVIEW

**Comment by laf** [comment]
Couple of things on this (I can't get it working as is).

In includes/polling/applications/bind.inc.php I had to change:

-if( !empty($agent_data['app']['bind']) && $app['app_id'] > 0 ) {
+if( !empty($agent_data['app']['bind'])) {

As $app['app_id'] isn't set and I can't actually see where this should be set. Not sure what you're thoughts are on this but out of the box it doesn't work for me :(

3 not defined variables in scrut output probably just need to be addressed and finally....

On the actual BIND graph page I would change:

bind - Queries

to

BIND - Queries

Just because BIND is supposed to be in caps.

**Comment by f0o** [comment]
the app_id is set when you add the application under the device settings. I added the check to avoid having a file named 'app-bind-.rrd' being created and fed.

Scrut fixes and text rewrite incomming :)

**Comment by laf** [comment]
God I must have been blind last night. All working again this morning!!

One thing to add before the merge is to put the config options you need into the Agent.md doc for people to be able to set this up.

**Comment by f0o** [comment]
Updated :)

**Pull request merged**
