### PR TITLE
Update Installation-Ubuntu-1604-Apache.md

### PR DESCRIPTION
**Pull request by daylicron**
Added Troubleshooting for Apache2 + PHP-FPM

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Thanks.  This feels like the wrong spot for this as we are not telling the user to install apache with php-fpm here.  Perhaps a new Advanced Web Server config doc?

To hold this, https://docs.librenms.org/#Extensions/Sub-Directory/ and https://docs.librenms.org/#Support/SSL-Configuration/

**Comment by daylicron** [comment]
Sry for the delay, was quite busy at work:

> Thanks. This feels like the wrong spot for this as we are not telling the user to install apache with php-fpm here. Perhaps a new Advanced Web Server config doc?

Sure, I could provide a new section providing running LibreNMS with Apache2 + php-fpm. Would you like me to do that?

**Comment by laf** [comment]
Yes that would be good please.

**Comment by laf** [comment]
Closing this PR down. Feel free to open another one with the updates or push them to this PR and we can re-open it.

**Pull request closed without merging**
