### PR TITLE
Added average packet size graph on interfaces.

### PR DESCRIPTION
**Pull request by xbeaudouin**
This pull request create average packet size graph on the network interfaces.

### CODE REVIEW

**Comment by xbeaudouin** [comment]
Thanks.

**Comment by xbeaudouin** [comment]
Please remove *all* my previous contribution.

**Comment by f0o** [comment]
@xbeaudouin on this particular PR we cant assert that it has been written without looking at Obs code like you mentioned in #2111. The Feature will make it into upstream eventually, however due to #2111 none of the team nor yourself are eligable to do so without potentially conflicting with the contribution's agreement.

We have to ensure and, if needs be, enforce this agreement to avoid any further issues with adam.

Sorry for the harsh closure.

**Comment by xbeaudouin** [comment]
I understand and also make this angry, how can we code another thing than c/(a+b) ?
So I don't care I have now my own fork, if you'd like to use my code, feel free.
Maybe I will have another patches, but you'll have to look at my fork ... sorry but I don't like to loose 3 hours to have my work trashed.
Regards.

**Comment by laf** [comment]
@xbeaudouin We're sorry you feel that way. We did explain to you in the issue that we wouldn't be able to accept the PR from you before you started working on it and I thought we were quite clear on that. You are correct there is only so many ways to write this but all that was needed was a little patience whilst someone else contributed it and everything would have been good.

Good luck with your fork.

**Pull request closed without merging**
