### PR TITLE
Update Install-LibreNMS.md SELinux configuration for bootstrap

### PR DESCRIPTION
**Pull request by fbouynot**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
What process writes to these files from the webui?

As far as I know only ./daily.sh should write to them, which doesn't run under the httpd context.

**Comment by fbouynot** [comment]
I don't know for sure. About once a day, I had LibreNMS with an error 500, and I could fix it sometimes with ./daily.sh, sometimes not, and I had to remove the content of bootstrap/cache.
For the first time today I did check the full stack trace of a request (not the short one in nginx error.log), here it is:
```
[2023-04-19T09:28:38.912876+02:00] production.ERROR: The /opt/librenms/bootstrap/cache directory must be present and writable. {"exception":"[object] (Exception(code: 0): The /opt/librenms/bootstrap/cache directory must be present and writable. at /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178)"}
[2023-04-19T09:28:38.913285+02:00] production.ERROR: Target class [files] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [files] does not exist. at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:891)
[previous exception] [object] (ReflectionException(code: -1): Class \"files\" does not exist at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:889)"}
[2023-04-19T09:28:38.913528+02:00] production.ERROR: Uncaught ReflectionException: Class "files" does not exist in /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:889
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(889): ReflectionClass->__construct()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\Foundation\Application->make()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(84): Illuminate\Container\Container->offsetGet()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\Foundation\Application->make()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(44): Illuminate\Container\Container->offsetGet()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\Foundation\Application->make()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Container\Container->offsetGet()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\Support\Facades\Facade::getFacadeRoot()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(642): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(623): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse()
#29 /opt/librenms/app/Exceptions/Handler.php(62): Illuminate\Foundation\Exceptions\Handler->render()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\Exceptions\Handler->render()
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#32 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#33 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#34 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [files] does not exist. in /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:891
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\Foundation\Application->make()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(84): Illuminate\Container\Container->offsetGet()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\Foundation\Application->make()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(44): Illuminate\Container\Container->offsetGet()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->build()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->resolve()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Foundation\Application->resolve()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->make()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\Foundation\Application->make()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\Container\Container->offsetGet()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\Support\Facades\Facade::getFacadeRoot()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(642): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(623): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse()
#28 /opt/librenms/app/Exceptions/Handler.php(62): Illuminate\Foundation\Exceptions\Handler->render()
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\Exceptions\Handler->render()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#32 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#33 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ReflectionException: Class \"files\" does not exist in /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:889
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(889): ReflectionClass->__construct()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\\Foundation\\Application->make()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(84): Illuminate\\Container\\Container->offsetGet()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\\Foundation\\Application->make()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(44): Illuminate\\Container\\Container->offsetGet()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\\Foundation\\Application->make()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\\Container\\Container->offsetGet()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(642): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(623): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#28 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#29 /opt/librenms/app/Exceptions/Handler.php(62): Illuminate\\Foundation\\Exceptions\\Handler->render()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\\Exceptions\\Handler->render()
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#32 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#33 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#34 {main}

Next Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [files] does not exist. in /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:891
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\\Foundation\\Application->make()
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(84): Illuminate\\Container\\Container->offsetGet()
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\\Foundation\\Application->make()
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(44): Illuminate\\Container\\Container->offsetGet()
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->resolve()
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->make()
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1431): Illuminate\\Foundation\\Application->make()
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(222): Illuminate\\Container\\Container->offsetGet()
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(193): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(332): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\\Support\\Facades\\Facade::__callStatic()
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(642): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#24 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(623): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#25 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#26 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#27 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#28 /opt/librenms/app/Exceptions/Handler.php(62): Illuminate\\Foundation\\Exceptions\\Handler->render()
#29 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\\Exceptions\\Handler->render()
#30 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#31 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#32 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#33 {main}
  thrown at /opt/librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php:891)"}
```

It says `production.ERROR: The /opt/librenms/bootstrap/cache directory must be present and writable.` so I did add the selinux rw type for context httpd and it started working again.

**Comment by murrant** [comment]
How is your web server set up? What user does php-fpm run as?

**Comment by murrant** [comment]
I did a little research and this seems to be the only way to reach the error you got:
```php
if (! is_file($this->manifestPath)) {
    $this->build();
}
```

So was the is_file() check failing?

**Comment by fbouynot** [comment]
> So was the is_file() check failing?
I think so, I don't know why though.

I have this at the moment:
```
# ls -lahZ /opt/librenms/bootstrap/
total 20K
drwxr-xr-x.  4 librenms librenms system_u:object_r:usr_t:s0                    51 Mar 15 10:19 .
drwxrwx--x. 30 librenms librenms system_u:object_r:usr_t:s0                  4.0K Apr 20 12:19 ..
-rw-rw-r--.  1 librenms librenms unconfined_u:object_r:usr_t:s0              1.6K Aug 29  2022 app.php
drwxr-xr-x+  2 librenms librenms system_u:object_r:httpd_sys_rw_content_t:s0   85 Apr 20 12:19 cache
drwxrwxr-x+  2 librenms librenms system_u:object_r:usr_t:s0                  4.0K Mar 22 10:00 cache-old

# ls -lahZ /opt/librenms/bootstrap/cache
total 404K
drwxr-xr-x+ 2 librenms librenms system_u:object_r:httpd_sys_rw_content_t:s0   85 Apr 20 12:19 .
drwxr-xr-x. 4 librenms librenms system_u:object_r:usr_t:s0                    51 Mar 15 10:19 ..
-rw-rw-r--. 1 librenms librenms system_u:object_r:httpd_sys_rw_content_t:s0   14 Mar 22 10:00 .gitignore
-rwxr-xr-x. 1 librenms librenms system_u:object_r:httpd_sys_rw_content_t:s0 2.0K Apr 20 12:19 packages.php
-rw-rw-r--. 1 librenms librenms system_u:object_r:httpd_sys_rw_content_t:s0 375K Apr 20 12:19 routes-v7.php
-rwxr-xr-x. 1 librenms librenms system_u:object_r:httpd_sys_rw_content_t:s0  20K Apr 20 12:19 services.php

# grep "^user" /etc/nginx/nginx.conf
user nginx;

# grep "^user" /etc/php-fpm.d/librenms.conf
user = librenms

# cat /etc/selinux/targeted/contexts/files/file_contexts.local
# This file is auto-generated by libsemanage
# Do not edit directly.

/opt/librenms/html(/.*)?    system_u:object_r:httpd_sys_content_t:s0
/opt/librenms/librenms-service.py    system_u:object_r:bin_t:s0
/opt/librenms/logs(/.*)?    system_u:object_r:httpd_log_t:s0
/opt/librenms/html/plugins/Weathermap/(configs|output)(/.*)?    system_u:object_r:httpd_sys_rw_content_t:s0
/opt/librenms/(rrd|storage|bootstrap/cache)(/.*)?    system_u:object_r:httpd_sys_rw_content_t:s0
```

You are right, there is no reason for php-fpm to write in this folder.
I did revert, now I have this: 
```
# cat /etc/selinux/targeted/contexts/files/file_contexts.local
# This file is auto-generated by libsemanage
# Do not edit directly.

/opt/librenms/html(/.*)?    system_u:object_r:httpd_sys_content_t:s0
/opt/librenms/librenms-service.py    system_u:object_r:bin_t:s0
/opt/librenms/logs(/.*)?    system_u:object_r:httpd_log_t:s0
/opt/librenms/html/plugins/Weathermap/(configs|output)(/.*)?    system_u:object_r:httpd_sys_rw_content_t:s0
/opt/librenms/(rrd|storage)(/.*)?    system_u:object_r:httpd_sys_rw_content_t:s0

# ls -lahZ /opt/librenms/bootstrap/cache
total 404K
drwxr-xr-x+ 2 librenms librenms system_u:object_r:usr_t:s0   85 Apr 20 13:27 .
drwxr-xr-x. 4 librenms librenms system_u:object_r:usr_t:s0   51 Mar 15 10:19 ..
-rw-rw-r--. 1 librenms librenms system_u:object_r:usr_t:s0   14 Mar 22 10:00 .gitignore
-rwxr-xr-x. 1 librenms librenms system_u:object_r:usr_t:s0 2.0K Apr 20 13:27 packages.php
-rw-rw-r--. 1 librenms librenms system_u:object_r:usr_t:s0 375K Apr 20 13:27 routes-v7.php
-rwxr-xr-x. 1 librenms librenms system_u:object_r:usr_t:s0  20K Apr 20 13:27 services.php
```
I'll try to find something else at the next crash if there is one.
You can deny and close the pull request I think.

Thanks, and sorry for the wrong PR.

**Comment by murrant** [comment]
No worries, just trying to get to the bottom of things.

**Comment by fbouynot** [comment]
The root cause seems to be, something is rewriting these files with the wrong user and context:
```
root@SRV01996:~# ls -lahZ /opt/librenms/bootstrap/cache
total 404K
drwxr-xr-x+ 2 librenms librenms system_u:object_r:usr_t:s0             85 Apr 21 00:19 .
drwxr-xr-x. 4 librenms librenms system_u:object_r:usr_t:s0             51 Mar 15 10:19 ..
-rw-rw-r--. 1 librenms librenms system_u:object_r:usr_t:s0             14 Mar 22 10:00 .gitignore
-rwxr-xr-x. 1 root     root     system_u:object_r:snmpd_var_lib_t:s0 2.0K Apr 21 00:19 packages.php
-rw-rw-r--. 1 librenms librenms system_u:object_r:usr_t:s0           375K Apr 21 00:19 routes-v7.php
-rwxr-xr-x. 1 root     root     system_u:object_r:snmpd_var_lib_t:s0  20K Apr 21 00:19 services.php
```
So I need to restore the permission and file type to get LibreNMS working.
Now I just need to understand what is the script launched as root by snmpd doing this.

**Comment by murrant** [comment]
Bizarre, good progress though.

**Comment by murrant** [comment]
snmptrapd does make sense.  You can definitely make it change user to librenms, but I don't think you can change the context.  Maybe the best you could do is make it not able to overwrite the existing file.

> I couldn't find why yet, but sometimes it does rewrite 
That it is somewhere in the Laravel code.

**Comment by fbouynot** [comment]
I'm trying to get a clean fix, here I am:
```bash
find /opt/librenms -type d -exec chmod 2770 {} \;
find /opt/librenms/bootstrap/cache -type f -exec chmod 2660 {} \;
````
This is to apply the group suid, so the new files are always created with the folder group, and not root.
Here I did not apply the chmod on files on all /opt/librenms to not remove the execution permissions to files that need it.

```bash
dnf install policycoreutils-restorecond -qy
echo "/opt/librenms/bootstrap/cache/*" >> cat /etc/selinux/restorecond.conf
systemctl restart restorecond
```
This is to restore the file context after the creation.

This morning I can see it worked, theowner is root so it has been rewritten by snmpd, but the group is librenms so lnms / php-fpm have access : 
```
~# ls -lahZ /opt/librenms/bootstrap/cache
total 428K
drwxrws---+ 2 librenms librenms system_u:object_r:usr_t:s0  111 May  4 00:19 .
drwxrws---. 4 librenms librenms system_u:object_r:usr_t:s0   51 Mar 15 10:19 ..
-rw-rwS---. 1 librenms librenms system_u:object_r:usr_t:s0   14 Mar 22 10:00 .gitignore
-rwxr-xr-x. 1 root     librenms system_u:object_r:usr_t:s0 2.0K May  4 00:19 packages.php
-rw-rw-r--. 1 librenms librenms system_u:object_r:usr_t:s0 380K May  4 00:19 routes-v7.php
-rwxr-xr-x. 1 root     librenms system_u:object_r:usr_t:s0  20K May  4 00:19 services.php
```

Now before I make a new pull request to change the documentation: 
- should we apply the group suid on all folders in /opt/librenms? (I think we should)
- should we use restorecond? (I see no other option, unless we find and remove or supersed the file transition for snmpd_t usr_t  snmpd_var_lib_t (see. [here](https://serverfault.com/questions/531431/selinux-canonical-way-of-automatically-applying-a-context-on-file-creation)))
- wouldn't it be better to run snmpd as librenms user? or another user? (I didn't succeed doing this, but running a php script as root is not the most secure thing, I should persevere) And if so should we user the group suid anyway?

**Pull request closed without merging**
