### PR TITLE
[webui] sort ports in VLANs blade

### PR DESCRIPTION
**Pull request by Npeca75**
sort ports in VLANs blade

before:
gi1/0/1,gi1/0/10,gi1/0/2,gi1/0/23,gi1/0/24,gi1/0/3,gi1/0/4,gi1/0/5,gi1/0/6,gi1/0/7,gi1/0/8,gi1/0/9,Po1,te1/0/2,te1/0/3,te1/0/4

after:
gi1/0/1,gi1/0/2,gi1/0/3,gi1/0/4,gi1/0/5,gi1/0/6,gi1/0/7,gi1/0/8,gi1/0/9,gi1/0/10,gi1/0/23,gi1/0/24,te1/0/2,te1/0/3,te1/0/4,Po1

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Npeca75** [comment]
before:
lnms1

after:
lnms2

**Review by murrant — APPROVED** [review]

**Review by murrant — CHANGES_REQUESTED** [review]
Sort should be done in the controller.

**Comment by Npeca75** [comment]
> Sort should be done in the controller.

hmm, something is wrong
if i sort this way, port names are sorted correctly, but ... order of vlan id's are messed
1,100,2,22,3,4 etc

any idea ?

**Comment by PipoCanaja** [comment]
> > Sort should be done in the controller.
> 
> hmm, something is wrong if i sort this way, port names are sorted correctly, but ... order of vlan id's are messed 1,100,2,22,3,4 etc
> 
> any idea ?

Does not look messed to me, only lexicographic and not numeric. 

Could you try this option : 
`->sortBy('vlanid', SORT_NUMERIC);`

https://www.php.net/manual/en/array.constants.php

**Comment by Npeca75** [comment]
> 
> Could you try this option : `->sortBy('vlanid', SORT_NUMERIC);`

hmmm
`$data = $portVlan->sortBy(['vlan', 'asc'], ['port', 'asc'])->groupBy('vlan');`
this will sort vlan ids correctly, but ports are messed up (back to square one :slightly_frowning_face: )
for some strange reason, sortBy does not honor second param in array
`[gi1/0/1] (U), [gi1/0/2] (U), [gi1/0/24], [gi1/0/3] (U)`

`$data = $portVlan->sortBy('port')->groupBy('vlan');`
this will place ports in correct order, but vlan ids are messed up

since MySQL could not do natural sorting on ifName, ifDescr, i tried every possible trick, like
`ORDER BY LENGTH(alphanumeric), alphanumeric`
but in mixed environment (gi1/0/10, te1/0/1) it will produce strange result ...

my only idea is to:
1. do sort in blade (you rejected this approach)
2. do sorting in controller with PHP 
` array_multisort(array_column($portsDB, 'ifName'), SORT_ASC, SORT_NATURAL, array_column($portsDB, 'ifDescr'), SORT_ASC, SORT_NATURAL, $portsDB);` 
this line is tested and working as expected
then create collection from array and pass to blade

Maybe my logic/knowledge is limited, so you have better idea

**Comment by murrant** [comment]
@Npeca75 to sort the sub arrays use map like this `$ports->map->sort('vlan')`

**Comment by Npeca75** [comment]
> @Npeca75 to sort the sub arrays use map like this `$portVlan->groupBy('vlan')->map->sort('ifIndex')`

hi @murrant , @PipoCanaja 
sorry for late reply
this did the trick
```
->get()->sortBy(['vlan', 'port']);
```

lnms2

**Review by murrant — APPROVED** [review]

**Pull request merged**
