### PR TITLE
Update Himoinsa Genset discovery

### PR DESCRIPTION
**Pull request by TheGreatDoc**
Please give a short description what your pull request is for

This updates the Himoinsa Gensets discovery to the v14 MIB version

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
And they completey change Oids between firmware versions?

**Comment by murrant** [comment]
@TheGreatDoc are you deleting the old sensors because there is no chance of them existing in the wild?

**Comment by TheGreatDoc** [comment]
> @TheGreatDoc are you deleting the old sensors because there is no chance of them existing in the wild?

Tbh, I dont know. The current yaml works with DISMUNTELv00-MIB and in the current firmware works with HIMOINSAv14-MIB which totally change oids. 

Is there any change of devices with very, VERY old firmware? Yes, there is. As for https://stats.librenms.org there is none, but not everybody allow sending statistics.

I can do three things:
- Send a notification telling to update the firmware.
- Keep both group of oids
- Remove old and set new ones (the one I did)

**Comment by TheGreatDoc** [comment]
Anything else I could do to have this merged?

**Pull request merged**
