### PR TITLE
APC new sensors

### PR DESCRIPTION
**Pull request by jepke**
APC dry input contacts.
APC energy sensor
APC older PDU power sensors

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ottorei** [comment]
Could you also provide the test json-file? Thanks.

**Comment by jepke** [comment]
> Could you also provide the test json-file? Thanks.

I ran these https://docs.librenms.org/Developing/os/Test-Units/ from what i recall from previous pull requests it did output more files.

Not sure what im missing as i just ran it again but it doesnt output that json file

**Comment by jepke** [comment]
i cant get it figure out why my tests wont work

```
~$ lnms dev:check unit -o apc_emu


Only checking os: apc_emu
Running unit check...
Starting snmpsim listening on 127.1.6.2:1162...
Refreshing database...done
PHPUnit 9.6.8 by Sebastian Bergmann and contributors.

FFFFFFFFFFFFFFFFFFF
   Symfony\Component\Process\Exception\ProcessTimedOutException

  The process "'vendor/bin/phpunit' '--colors=always' '--group' 'os' '--filter' '/::test[A-Za-z]+$|::testOSDetection|::test[A-Za-z]+ with data set "apc_emu.*"$/'" exceeded the timeout of 3600 seconds.

  at vendor/symfony/process/Process.php:1160
    1156▕
    1157▕         if (null !== $this->idleTimeout && $this->idleTimeout < microtime(true) - $this->lastOutputTime) {
    1158▕             $this->stop(0);
    1159▕
  ➜ 1160▕             throw new ProcessTimedOutException($this, ProcessTimedOutException::TYPE_IDLE);
    1161▕         }
    1162▕     }
    1163▕
    1164▕     /**

      +2 vendor frames

  3   LibreNMS/Util/CiHelper.php:397
      Symfony\Component\Process\Process::run()

  4   LibreNMS/Util/CiHelper.php:210
      LibreNMS\Util\CiHelper::execute()
```

**Comment by jepke** [comment]
if anyone ever finds this PR looking for a solution to my problem `pyasn1-0.5.0 -> pyasn1-0.4.8` downgrade fixed it

**Review by ottorei — APPROVED** [review]

**Review by murrant — APPROVED** [review]

**Pull request merged**
