### PR TITLE
Use 'counter' RRD type for some TrueNAS sensors

### PR DESCRIPTION
**Pull request by TheMysteriousX**
Like #14529, TrueNAS presents some counters that are best graphed discretely rather than continuously.
Also fix a typo, and give ARC P / ARC C better values (derived from arcstats:c / arcstats:p).

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheMysteriousX** [comment]
This works, but only for new hosts - the type of the RRD appears to be baked in at creation time.

**Comment by PipoCanaja** [comment]
> This works, but only for new hosts - the type of the RRD appears to be baked in at creation time.

Hi
Yes. If you want to generate new graphs, the best is to change the index definition:
`index: zfsArcHits.{{ $index }}`
to
`index: zfsArcHits_Count.{{ $index }}`

That will force the creation of a new RRD. And the old one will be autocleaned after a while (depends on the config of the user).

**Comment by TheMysteriousX** [comment]
Thanks, I'll take a look at that - is '_Count' a magic value? My memory of how the sensor indexes work is a little fuzzy.

**Comment by PipoCanaja** [comment]
> Thanks, I'll take a look at that - is '_Count' a magic value? My memory of how the sensor indexes work is a little fuzzy.

Nop, not magic at all :) The sensor index in YAML is a pure arbitrary value that must be unique between sensors ... And the RRD file contains it in its name :) 
Unicity is achieved in 2 way : 
- The first part is common to all sensors extracted from the same table
- The 2nd part is the index which is by definition unique in the table 

So here, the only magic is to change the 1st part to something else. 

I could have said : 
`index: zfsArcHits.{{ $index }}`
to
`index: dJwuDIsg.{{ $index }}`

Result would have been exactly the same :)

**Comment by murrant** [comment]
Seems like a good change, but I think _rate would be a better suffix.  (because you are taking a counter data type and storing it as a rate)

**Comment by TheMysteriousX** [comment]
Switched over to _rate as suggested.

**Review by ottorei — APPROVED** [review]

**Pull request merged**
