### PR TITLE
Switch to testdox output for phpunit

### PR DESCRIPTION
**Pull request by Jellyfrog**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Seems we need https://github.com/sebastianbergmann/phpunit/pull/4346 for this to work

**Comment by murrant** [comment]
Doesn't seem to work since the os module takes so long.

**Comment by Jellyfrog** [comment]
> Doesn't seem to work since the os module takes so long.

Yes, because the output is buffered it didn't give the output I was looking for, hoping https://github.com/sebastianbergmann/phpunit/pull/4346 will fix that :)

**Comment by Jellyfrog** [comment]
One day maybe

**Pull request closed without merging**
