### PR TITLE
Removed vlan test

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Originally the functions were in a new file but then moved centrally, that means they aren't available for the tests so removed this test for now.

### CODE REVIEW

**Comment by ekoyle** [comment]
Seems a little shortsighted to just remove the test... Seems like something that will be forgotten and never added back in.

**Comment by laf** [comment]
It was causing all tests to fail. I did try and fix it but it's not trivial so the only option was to remove for now

**Comment by ekoyle** [comment]
A trivial fix would be to move them to a different file.

A more permanent fix might be to separate the SNMP functions from non-snmp
functions.

**Comment by laf** [comment]
But the trivial fix is not the path we should go down, we'd end up with countless 'include' files over what we already have.

snmp functions are already in there own file: includes/snmp.inc.php

**Pull request merged**
