### PR TITLE
Update to planetos.inc.php for ISG-* models

### PR DESCRIPTION
**Pull request by kmpanilla**
Gets the proper hardware model# and version of the planet IGS-* series.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Same as previous PR. You don't need to put the tests in both of course. I suggest that the YAML file gets merged first and you include the test data in this PR.

**Comment by kmpanilla** [comment]
This what we need?

[planetos.json](https://github.com/librenms/librenms/files/3124141/planetos.json.txt)

**Comment by PipoCanaja** [comment]
This is one of them. We need both the snmprec and the json generated with it.

During the non regression tests, the snmprec files are all processed again and the json files are compared to the generated ones, to validate nothing is broken.

**Comment by kmpanilla** [comment]
Here you go.
[planetos.snmprec](https://github.com/librenms/librenms/files/3124541/planetos.snmprec.txt)

**Comment by PipoCanaja** [comment]
Hi @kmpanilla 
Could you please 'git add' those 2 files in their corresponding location (~/tests/captures for snmprec, and ~/tests/data for the json) so we have them ready for merge?  

Thanx

**Pull request merged**
