### PR TITLE
fix restricted application access for normal user

### PR DESCRIPTION
**Pull request by SourceDoctor**
normal user with no read access to a device should also have no access to it's application.
This is the fix for this.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Please use Permission class to get user devices, you can find a lot of examples here https://github.com/librenms/librenms/pull/10568

**Comment by SourceDoctor** [comment]
@Jellyfrog Permissions class now used  :-)

but on using "Permissions::devicesForUser()" i'd expect for user with global read a list of all device_ids not an empty array.
devices_perms table has only access list for normal users. :-)

**Comment by Jellyfrog** [comment]
Yeah, the real fix is ofc to use Eloquent model :)  
`Device::canAccess()` etc.

**Comment by SourceDoctor** [comment]
this way works also fine ;-) don't panic :beers:

**Comment by vicomte** [comment]
Just ran into this. Thanks for taking a look! Works for me.

**Comment by murrant** [comment]
I rewrote this with Eloquent, want me to update this PR?

**Comment by SourceDoctor** [comment]
@murrant if you like do so :-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
