### PR TITLE
Updating RAPID-CITY mib for Extreme VSP

### PR DESCRIPTION
**Pull request by ospfbgp**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ospfbgp** [comment]
Extreme VOSS added a new mibs for fans(rcVossSystemFanInfoOperStatus) for 7.x.x and above.  Older code versions still use rcChasFanOperStatus.  I also added VOSS as part of the description for process or and state.  I have included screenshots of where I have tested pull request on v6, v7 and v8 code.  All appers to working as expected.
Screen Shot 2019-07-03 at 7 01 39 AM
Screen Shot 2019-07-03 at 7 01 02 AM

**Comment by ospfbgp** [comment]
Code climate is complaining about "Similar blocks of code found in 2 locations".  The code used to discover rcChasFanOperStatus was copied and changed to add support rcVossSystemFanInfoOperStatus.  The new mib added support for trays with more fans.  The previous mib did not have support for trays.

**Comment by PipoCanaja** [comment]
Hi @ospfbgp 
You have some issues about existing devices test data. (tests/data/voss_7432cq.json). Could you check TravisCI results and validate if the new value is better than the existing value ? If yes, you would have to re-run the tests on the specific test snmprec files to correct them

**Comment by ospfbgp** [comment]
I have updated processor_descr and sensor_descr in the voss_*.json files so it will now pass Travis.  I also ran collect-snmp-data.php and save-test-data.php on voss_7432cq.  All files that needed fixing have been fixed.

**Comment by PipoCanaja** [comment]
Thanx @ospfbgp !

**Pull request merged**
