### PR TITLE
Update allied.yaml

### PR DESCRIPTION
**Pull request by mattie47**
"1.3.6.1.4.1.207.1.4.128" is currently reporting as allied, when it should be reporting as radlan.

Refer to https://community.librenms.org/t/allied-telesis-discovery/6189/8

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Does this not need removing from the adlan device then?

**Comment by Karim77000** [comment]
Need to add this two OID 

1.3.6.1.4.1.207.1.4.125
1.3.6.1.4.1.207.1.4.143

it's for 8000S and 8000GS

**Comment by mattie47** [comment]
@laf 

I don't believe so.

allied.yaml is a "catch all" for the Allied Telesis OIDs, and then lists the exceptions of AW+ (for awplus.yaml) and then specific OIDs related to Radlan.

So while `1.3.6.1.4.1.207.1.4.128` was already listed as "include" within Radlan, it seemed the catch all (`sysObjectID: .1.3.6.1.4.1.207.`) for allied.yaml was grabbing it instead.

So really - It seems I just missed `1.3.6.1.4.1.207.1.4.128` when I originally did changes a year ago.


@Karim77000 re `1.3.6.1.4.1.207.1.4.125` and `1.3.6.1.4.1.207.1.4.143`, can you confirm you actually have devices with these OIDs and have tested they actually should be Radlan instead?

I ask because I think Allied Telesis had several hardware revisions of the 8000 series where the actual operating system might have changed at one point, so in other words some devices should correctly be allied.yaml, and others as radlan.yaml. Confusing stuff!

E.g. 8100S is running Alliedware Plus Version 2.

I'll do another commit once you confirm.


Thanks,

Matt

**Comment by Karim77000** [comment]
Yes i confirm 

1.3.6.1.4.1.207.1.4.125 for 8000S/16
1.3.6.1.4.1.207.1.4.143 for 8000GS/24

**Comment by mattie47** [comment]
@Karim77000  Have updated.

Would you mind testing the changes work for you?

See the "Testers" section in the first comment above.

Thanks,

Matt

**Comment by laf** [comment]
Thanks @mattie47 as always.

**Comment by Karim77000** [comment]
Perfect
Thanks Mattie

**Pull request merged**
