### PR TITLE
newdevice: Added support for Linksys Smart Switch devices #5754

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #5754 
Couldn't see a better os name :(

### CODE REVIEW

**Comment by arrmo** [comment]
Hi,

Does this support the LGS-308 also, not just 308P? The only difference is PoE.

Thanks!

**Comment by laf** [comment]
It's just basic detection and I've kept the sysObjectId quite loose,: .1.3.6.1.4.1.3955.1000

**Comment by arrmo** [comment]
OK, cool - thanks! Model number is slightly different, but that's no biggie.

**Comment by laf** [comment]
The model number used is just for testing. If your device returns that sysObjectId then all is good.

**Comment by dbbestdave** [comment]
Confirmed; Detects as Linksys Smart Switch, now! Thanks!

**Pull request merged**
