### PR TITLE
Feature: F5 LTM bandwidth controller

### PR DESCRIPTION
**Pull request by yac01**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/f5-ltm-bandwidth-controller/12259/1

**Comment by yac01** [comment]
Modification on the WebGui 

F5


F5_1

**Comment by murrant** [comment]
try this, but I probably made a mistake, I don't have any test data:
tests/module_tables.yaml
```yaml
loadbalancers:
    component:
        excluded_fields: [id, device_id]
    component_prefs:
        excluded_fields: [id, component]
        joins:
            - { custom: 'INNER JOIN (SELECT `type`, `label` FROM `component` WHERE `device_id`=?) I ON component_prefs.component = component.id', select: ['type', 'label'] }
        custom_where: ''
        order_by: I.type, component_prefs.attribute
```

**Comment by yac01** [comment]
Hello @murrant 

i retrieve  DATA Test with the following commande :  
 ./scripts/collect-snmp-data.php -h F5_devices  -o f5 -m loadbalancers

you find them in the file attached to this comment in f5.snmprec.txt

i wish it would be good now to merge :)

[f5.snmprec.txt](https://github.com/librenms/librenms/files/4773641/f5.snmprec.txt)

thank you

**Comment by Jellyfrog** [comment]
can you commit the test files ?

**Comment by yac01** [comment]
@Jellyfrog  is it ok ok foy you now ?

**Comment by Jellyfrog** [comment]
Missing json part of the test data, check the docs linked above

**Comment by yac01** [comment]
@murrant : as requested on discord i replaced **** by service 1 and project 1 ... 

you can see it on the followinf file
[f5.snmprec.txt](https://github.com/librenms/librenms/files/4793679/f5.snmprec.txt)

**Comment by yac01** [comment]
@murrant   you can find the last version of DATA captured after correction on the snmprec :
[f5.snmprec.txt](https://github.com/librenms/librenms/files/4798586/f5.snmprec.txt)

**Comment by murrant** [comment]
@yac01 the snmprec is already in the PR, you should update it in your branch...
https://github.com/librenms/librenms/pull/11728/files#diff-ead0213f9b9abd98ae4ede9a5b49a492

**Comment by yac01** [comment]
@murrant : thank you very much for the merge it's very nice  :) .

**Comment by murrant** [comment]
@yac01 thanks for your contribution... which reminds me, I still need to get the test data merged for this.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
