### PR TITLE
Always test all OS detection.

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Yes! I've been thinking about this one from time to time :)

**Comment by Jellyfrog** [comment]
Only thing is that this takes the test from a few minutes to... 15? But do we care? Better with complete tests

**Comment by murrant** [comment]
+12m seems a little long hmm.  Definitely should do this.  It only takes 1m 50s with snmp mock and 6m 40s with snmpsim.

**Comment by Jellyfrog** [comment]
> +12m seems a little long hmm. Definitely should do this. It only takes 1m 50s with snmp mock and 6m 40s with snmpsim on my system to do all 599.

I was only guessing how much it adds :) let's go!

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
