### PR TITLE
Updated OS Support: Dragonwave Horizon

### PR DESCRIPTION
**Pull request by noaheroufus**
Removed the lacking, existing Horizon Compact definition and created new ones, via YAML, to support the following Horizon devices:
- Compact
- Duo
- Compact Plus

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Good job
What about the wireless support you removed?

**Comment by noaheroufus** [comment]
All 3 new definitions should have wireless sensors. RSL, SNR, and Tx Power.

**Comment by murrant** [comment]
FYI, there are non-wireless SNR,dBm, sensors. You have used those instead of the wireless ones.
The wireless ones don't support yaml at this time.

Using the other ones means these won't show up in the places people expect.

**Comment by noaheroufus** [comment]
Moved those to wireless sensors and fixed an error with the Duo's EnetPort2RxCRCErrors sensor I noticed.

**Review by murrant — APPROVED** [review]
Thanks for the quick update!  Looks good.

**Pull request merged**
