### PR TITLE
Add info for ip-based security using nginx

### PR DESCRIPTION
**Pull request by Gorian**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
I'm wondering if it's best to put this in another document. People might think this is needed as part of the setup.

**Comment by murrant** [comment]
I think a separate document would be appropriate.

**Comment by paulgear** [comment]
Yeah, I'd say go for another document.

**Comment by Rosiak** [comment]
Obsolete due to #5093.
Closing.

**Pull request closed without merging**
