### PR TITLE
Update Installation-Ubuntu-1604-Nginx.md

### PR DESCRIPTION
**Pull request by mattie47**
Added extra steps I was required to complete when running this on vanilla Ubuntu 16.04

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by bdg-robert** [comment]
@mattie47 - not sure if you saw or not on Discord, but @murrant mentioned that all of the pear usage was removed a while ago.

**Comment by laf** [comment]
Actually php-pear is needed for weathermap iirc so we possibly should have this in.

If we do, it will need all 4 current install docs updating rather than just this one.

**Comment by murrant** [comment]
Please add php-pear to the weathermap docs then.

**Comment by kkrumm1** [comment]
@murrant I can the php-pear to the weather doc if you want? Or we adding it to the install docs?

**Comment by murrant** [comment]
I would prefer to not add it to the install docs as most users do not use weathermap.

**Comment by mattie47** [comment]
Hi @murrant  @kkrumm1,

I have no issues with this not being added to the install instructions, however ensure the bug telling users to install php-pear gets removed. Otherwise this is just confusing...

Thanks,

Matt

**Comment by laf** [comment]
> I have no issues with this not being added to the install instructions, however ensure the bug telling users to install php-pear gets removed. Otherwise this is just confusing...

Where does that show up? I've grepped install.php and validate and don't see it.

**Comment by mattie47** [comment]
Hi @laf 

I happened to do a snapshot on the VM I'm running for Libre and was able to go back to around the time I was seeing the issue.

See attached:

image


Ahh, well this is interesting...

```
localadmin@librenms:/opt/librenms$ cat html/install.php | grep pear
            $msg = "It appears that the database is already setup so have moved onto stage $stage";
    // Check for pear install
        <td>pear</td>
    echo("<td>apt-get install php-pear / yum install php-pear</td>");

localadmin@librenms:/opt/librenms$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

ocaladmin@librenms:/opt/librenms$ sudo git pull
[sudo] password for localadmin:
remote: Counting objects: 3176, done.
remote: Total 3176 (delta 1728), reused 1728 (delta 1728), pack-reused 1448
Receiving objects: 100% (3176/3176), 3.60 MiB | 471.00 KiB/s, done.
Resolving deltas: 100% (2202/2202), completed with 510 local objects.
From https://github.com/mattie47/librenms
   63ce295..62d5fc4  master     -> origin/master
 * [new branch]      patch-1    -> origin/patch-1
 * [new branch]      patch-2    -> origin/patch-2
```

I updated my fork a day ago to upstream/master, however I only forked Libre initially a few days ago. Hence the confusion.


In short - Ignore my problem. It seems to be fixed after the rebase:

image


Thanks,

Matt

**Comment by murrant** [comment]
Glad you got it working.

**Pull request closed without merging**
