### PR TITLE
Fortimail-Support

### PR DESCRIPTION
**Pull request by darkfritz2**
Wanted to add support for the fortimail because it's missing.

what doesn't work so far:
top right corner - CPU Usage - it writes only "device*fortimail_cpu (my guess is because of definitions/fortimail.yaml)
-are functions are missing, example:
Log Disk Usage ( fmlSysLogDiskUsage 1.3.6.1.4.1.12356.105.1.8 )
Mailbox Disk Usage ( fmlSysMailDiskUsage 1.3.6.1.4.1.12356.105.1.9 )
Deferred Queue ( fmlMailOptionsDeferQueue 1.3.6.1.4.1.12356.105.1.103.1 )
Detected Virus ( i don’t know which is the MIB for that )
Detected Spam ( this one either)

my thought about deferred queue, virus and spam - maybe to put it in /includes/definitions/discovery/fortimail.yaml ?

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/help-fortimail-mib/11777/4

**Comment by darkfritz2** [comment]
i solved the issue with CPU USAGE top right corner.

**Comment by murrant** [comment]
Did you see #10895

**Comment by darkfritz2** [comment]
> Did you see #10895

no i didn't. but considering that the creator didn't continue, i've done it myself. i added the other stuff that weren't working as well. needs testing now. my fortimail isn't in production so i can't see the disk usage (on the equipment is 0% on both). but i hope it'll change in the next few days. if someone could test it properly, then that would be great.

**Comment by darkfritz2** [comment]
*update* log disk usage and mailbox disk usage show exactly what they should. module works on my end.

**Pull request closed without merging**
