### PR TITLE
No longer show disabled ports on main ports page

### LINKED ISSUE #1141: Hide Disabled Ports in /Overview and Device/Ports
User story:
I have a network device with 12 ports. Only first 8 ports would be ever used and are connected at the moment. There seems like no way to disable the unused ports completely. If I set them as "Disabled" or/and "Ignored" I can still see them in /Overview
http://fii.cz/qqvbjxjg
Also they are bothering in Device/Ports
http://fii.cz/vumjc
Question how to handle this classification ?
http://fii.cz/djdat

Also for discussion if this should have been handled by the Disabled flag, which is "maybe" used for disable the polling of the iface. Maybe new flag named "Hide" would be more useful. This is up to you.

### PR DESCRIPTION
**Pull request by laf**
This fixes #1141 

In the issue it's shown that ports disabled are showing in eventlog, I can't see that this is possible in the code so that bit hasn't been touched.

However we now no longer show ports marked as disabled in the Webui for all ports or the devices ports. This makes sense as the option is there for the users to control and isn't what we poll / discover.

### CODE REVIEW

**Comment by paulgear** [comment]
I can understand not showing disabled ports on the global ports table, but taking it out of the device table without any way to override it seems a little counter-intuitive to me.  If they were hidden by default but there was an AJAX button to show them, that would make a lot more sense to me.

**Comment by laf** [comment]
I don't agree personally. But I'll remove that part and update the pr for now.

**Comment by SaaldjorMike** [comment]
:+1: for leaving a button that would show the disabled ports on a device.

**Comment by laf** [comment]
Pushed a new update that keeps disabled ports back in. Someone can look at extending it further another time. This now just fixes the disabled bit of the main ports list.

**Pull request merged**
