### PR TITLE
QNAP QTS: Moved to yaml discovery

### PR DESCRIPTION
**Pull request by TheGreatDoc**
Sadly historical data will be lost as now index is dynamic and not hardwritted.

I've also grouped them so its easy to read

I dont have any QNAP with extension, but with this discovery it should now discover everything.

TODO in other PR: A way to know the raid status. QNAP decided to return it as STRING... And I dont know all possible states.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
index can be dictated in yaml (to some degree)
Ouch all these devices that don't support bulk request.  That REALLY slows down polling.

**Comment by TheGreatDoc** [comment]
> index can be dictated in yaml (to some degree)

I know, and maybe I could save one or two, but will break a sanitized way to name the rrd sensors. So I though it will be better to _restart_ even with the historical data lost. 
After all, no storage/mem/cpu/interface data is lost, only state/temp/fan sensors.

>Ouch all these devices that don't support bulk request. That REALLY slows down polling.
Funny thing: I have 2 QNAP, one at home TS-253A and one at work TS-877XU-RP. 
The TS-253A doesnt respond to bulk but TS-877XU-RP does... Maybe split to two different definitions?

**Comment by murrant** [comment]
@TheGreatDoc one way to disable bulk from the user perspective is to use SNMPv1

**Comment by jozefrebjak** [comment]
@TheGreatDoc I will test it on Turbo NAS TS-469L & Turbo NAS TS-469 Pro

**Comment by TheGreatDoc** [comment]
> @TheGreatDoc one way to disable bulk from the user perspective is to use SNMPv1

Yeah, but from user perspective what you will see is your device not being _fully_ supported.

I'm going to check discovery/poller times with the nobulk option and compare results.

**Comment by jozefrebjak** [comment]
@TheGreatDoc It's much better now. I can see wrong disk finnaly which I know that is wrong some time with HD SMART state. Thank you. I am waiting for merge to master.

**Comment by TheGreatDoc** [comment]
@murrant could be that only one var is allowed for `index:` ?

I just noticed this:

```
Sensor Added: temperature qnap diskTemperture-{{ $diskEnclosureID }}.1 Enclosure 0 Disk 1 Seagate ST4000VN008-2DR166 (SATA). 
```

**Comment by murrant** [comment]
@TheGreatDoc possibly diskEnclosureID was not found.

**Comment by TheGreatDoc** [comment]
@murrant It is. 
Is used in descr: `Enclosure ` **0** `Disk` 1

**Comment by PipoCanaja** [comment]
Right @TheGreatDoc , could be that not all the variables are parsed in `index`, only $index and co.

**Comment by TheGreatDoc** [comment]
@jozefrebjak Do you have a QNAP with extension enclosure?

I dont and I want to check how is the snmp reply with it.

**Comment by TheGreatDoc** [comment]
Oh... I think I totally fucked up....

**Comment by murrant** [comment]
@TheGreatDoc no worries, there is always a way back :D

**Comment by TheGreatDoc** [comment]
Closed. Check https://github.com/librenms/librenms/pull/11882

**Pull request closed without merging**
