### PR TITLE
Fix location missing from API device list

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by fluiddmotion** [comment]
This has not fixed the issue..

Any API experts on here?
If I run 
curl -H 'X-Auth-Token: xxxxxxxxxxxx' http://localhost/api/v0/devices    --- It returns 401 Devices

curl -H 'X-Auth-Token: xxxxxxxxxxxx' http://localhost/api/v0/devices?type=location  --- It returns 358 Device (These all have locations)

curl -H 'X-Auth-Token: xxxxxxxxxxxx' http://localhost/api/v0/devices?type=location&query=538  ---- It still returns 358 Devices (It should only return 5)
Have i got the query correct?

**Comment by murrant** [comment]
No, please read the docs.  https://docs.librenms.org/API/Devices/#list_devices

**Comment by fluiddmotion** [comment]
I have, there is no location example.. The example to query by mac is shown as 

curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.org/api/v0/devices?type=mac&query=00000c9ff013

So based on the documentation how am i wrong? Can you give me the correct way?

**Comment by murrant** [comment]
Make sure you put quotes around your url `&` is a special character in the shell

**Comment by fluiddmotion** [comment]
Ok thank you for that Ive worked it out now..

**Comment by murrant** [comment]
Sure, click the edit button on the page.  Yeah, it was never updated to support location_id.

**Pull request merged**
