### PR TITLE
Fix queries RRD graph.

### PR DESCRIPTION
**Pull request by hugalafutro**
Currently this produces nan values for the queries graph of unbound application.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/rrd-update-issue-with-unbound-module/11481/11

**Comment by Jellyfrog** [comment]
So did you verify it solves your problem?

**Comment by hugalafutro** [comment]
Yes I removed the previous changes to the 2 files from my test install with ./scripts/github-remove -d, then did ./daily.sh and ./validate.php which came up all green. Then I changed just the 16 lines as in this PR, and after few polling cycles the queries graph started showing values instead of nan.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Comment by diegocanton** [comment]
Problem persists after updating to 1.68

image


Stats - Unbound 1.11.0
image

I believe that always make "lower case" still in FOREACH

image
image


This solution would require that all code be changed from:
`$ unbound ['num.query.type.A']`
For
`$ unbound ['num.query.type.a']`
image

What do you think about that?

**Comment by hugalafutro** [comment]
Hi, this is not my experience for me 1.68 in docker install, although my unbound does not report that many queries - it runs on openwrt with 1.1.1.1 over tls as upstream.

from my router's /etc/snmp/unbound all num.query.* entries:
```
num.query.type.A=63728
num.query.type.AAAA=54420
num.query.type.NAPTR=30
num.query.class.IN=118178
num.query.opcode.QUERY=118178
num.query.tcp=11
num.query.tcpout=53435
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=0
num.query.flags.TC=0
num.query.flags.RD=118178
num.query.flags.RA=0
num.query.flags.Z=0
num.query.flags.AD=121
num.query.flags.CD=0
num.query.edns.present=658
num.query.edns.DO=0
```
graph in librenms:
[screenshot on my nextcloud](https://turbomrak.o5.ddns.net/f/29991)

For me the issue of the the graph not drawing anything was fixed as pre-1.68 it would display Error drawing graph. If you are able to fix even more issues please open new PR as I have to say for me even this simple change involved lot more effort to submit than I previously anticipated and I'm not really looking for more challenges :)

**Comment by diegocanton** [comment]
Applied in https://github.com/librenms/librenms/pull/12178

**Pull request merged**
