### PR TITLE
Fixing memory scale for datacom-dmos devices

### PR DESCRIPTION
**Pull request by lhwolfarth**
Fixing memory scale for datacom-dmos devices

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
According to the tests, it seems that it is not working. Moreover, you fixed the index to '1'. Better to use the index provided by the device in the MIB (that would allow the device to provide more than one value).
Does this code work in your environnement ? If yes, then you probably need to upgrade the SNMPREC file (and match the JSON file to it of course)

**Comment by lhwolfarth** [comment]
@PipoCanaja, in my tests it was working. I also tested now without using the index 1 and it changed from the scale of MiB to GiB but still consistent (right values).
I will update the yaml removing the "index 1" and the upload the new test data.
Thank you!

**Comment by PipoCanaja** [comment]
Seems that the tests went somehow wrong (all empty). Fixing that for you

**Comment by PipoCanaja** [comment]
LGTM, so let's control the tests and it will be ready for merge

**Review by PipoCanaja — APPROVED** [review]

**Pull request merged**
