### PR TITLE
[widget] Top Devices

### PR DESCRIPTION
**Pull request by Npeca75**
calculate bitrate only from ports which are UP

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Npeca75** [comment]
hi @PipoCanaja 
i stumbled in this bug when i shut down one of high bitrate port
so, device was still on top of list, because TopDevices widget does not consider which ports are up or down, simply SUM all ports.
Expected behavior is, if device was on top, and you shut down a port, widget need to reflect these changes

**Comment by Npeca75** [comment]
@PipoCanaja 

to be more specific, ports which are DOWN are left "as is" in DB with last data, so they are never zeroed out

**Comment by PipoCanaja** [comment]
> hi @PipoCanaja i stumbled in this bug when i shut down one of high bitrate port so, device was still on top of list, because TopDevices widget does not consider which ports are up or down, simply SUM all ports. Expected behavior is, if device was on top, and you shut down a port, widget need to reflect these changes

Do you use "per port polling" by any chance ?

**Comment by Npeca75** [comment]
> "per port polling"

no, nothing like that :)

**Comment by ottorei** [comment]
@PipoCanaja After looking at the code it seems that the widget just sums ingress and egress bits from all available interfaces. If there was a port with massive amounts of data transferred and that port went down for any reason, looking at the sum itself would skew the result if other ports would not compensate, right? The device would still be listed as the top device even when it would not pass much traffic at all. I think the calculation should only sum the ports that were up during the last poll or were up during the last n-minutes. This is for the real time view.

**Comment by Npeca75** [comment]
hi @ottorei 

we discussed this case with @murrant on discord
there is 2 solution, one to constant fill port counters with zero, for ports which are down (very ugly solution)
or
as @murrant  suggested, to skip counting "down" ports in widget
so i made this modification

**Review by ottorei — APPROVED** [review]

**Pull request merged**
