### PR TITLE
Added more DELL switches in order to get proper CPU stats

### PR DESCRIPTION
**Pull request by rdezavalia**
More DELL switches supported:

* N4032
* N2048
* N2024
* N3048
* N2048P
* N4064F
* 54XX

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @rdezavalia 
Thanx for your pull request ! Looks good !
Could you please add test data for devices that this PR is adding, in order to improve the regression tests set ? 
Thanx

**Comment by rdezavalia** [comment]
Thanks @PipoCanaja. Is there a way to get the test data from my switches ? Are there any guidelines in order build the test data? Hopefully I'll be able do this next week. If you have any pointer it will be very useful.

**Comment by rdezavalia** [comment]
Sorry @PipoCanaja I've just saw this link https://docs.librenms.org/Developing/os/Test-Units ... I should have an update in a few days. Thanks!

**Comment by rdezavalia** [comment]
@PipoCanaja I've just added test data for N4064F. Could you please validated it is correct ? If it is, I will generate data for the other devices.

**Comment by rdezavalia** [comment]
Also I was thinking about refactoring this code, so we don't need to add every switch by hand, does this code make sense to you ? I have been testing it with our hardware and it is working ok:
```

public function discoverProcessors()
    {
        $device = $this->getDevice();

	$device_id = array_pop(explode('.',$device['sysObjectID']));

	if ($device_id > 3019 && $device_id < 3040) {
            d_echo("Dell Powerconnect 55xx");
            return array(
                Processor::discover(
                    'powerconnect-nv',
                    $this->getDeviceId(),
                    '.1.3.6.1.4.1.89.1.7.0',
                    0
                )
            );
	} elseif ($device_id > 3039 && $device_id < 3070) {
            return $this->discoverVxworksProcessors('.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.9.0');
        }

        return $this->discoverVxworksProcessors('.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.4.0');
    }

```

**Comment by murrant** [comment]
I reorganized the code a bit and it looks nicer to read now. I'll merge this as-is.  Feel free to submit further changes if you like.  With the extra test data, it will be easy to tell if it is correct.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-55-release-changelog-august-2019/9428/1

**Pull request merged**
