### PR TITLE
Allow all models of Asentria SiteBoss

### PR DESCRIPTION
**Pull request by willhseitz**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10746`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by willhseitz** [comment]
.1.3.6.1.4.1.3052 belongs to all of Asentria Corp

[http://oid-info.com/get/1.3.6.1.4.1.3052](http://oid-info.com/get/1.3.6.1.4.1.3052)

**Comment by PipoCanaja** [comment]
Hi @willhseitz 
Thanx for your PR. Could you add some test data as well for such a device ? 
Bye

**Comment by willhseitz** [comment]
Hi @PipoCanaja,

I have set up a dev environment, but I am having difficulty with snmpsim. When I try to run `./scripts/save-test-data.php -o siteboss`, I receive this error:


```
Starting snmpsim listening on 127.1.6.1:1161...
sh: 1: snmpsimd.py: not found

Could not find snmpsim, you can install it with 'pip install snmpsim'.  If it is already installed, make sure snmpsimd or snmpsimd.py is in PATH
```

I still receive that error after running `pip install snmpsim `and `pip3 install snmpsim`. I also tried installing snmpsim via U18 APT (apt install snmpsim), and this is the error I get then:

```
Starting snmpsim listening on 127.1.6.1:1161...
Traceback (most recent call last):
  File "/usr/bin/snmpsimd", line 549, in <module>
    '|'.join([ x for x in pyasn1_debug.flagMap.keys() ]),
AttributeError: 'module' object has no attribute 'flagMap'

Failed to start Snmpsim. Scroll up for error.
```

I am running both as librenms user. I did not find much information regarding these types of snmpsim  errors on the community forum :(
If you can point me toward any resources to help with this, I would appreciate it!

**Comment by Jellyfrog** [comment]
> ```
> Could not find snmpsim, you can install it with 'pip install snmpsim'.  If it is already installed, make sure snmpsimd or snmpsimd.py is in PATH
> ```


> make sure snmpsimd or snmpsimd.py is in PATH

You need to make sure snmpsim.py is in your PATH, or modify the script to point to the file directly.

**Comment by willhseitz** [comment]
Thanks, I updated librenms user PATH and was able to export snmpsim data.
I followed [these instructions ](https://docs.librenms.org/Developing/os/Test-Units/#additional-module-support-or-test-data) to get the attached [siteboss.json.txt](https://github.com/librenms/librenms/files/3780994/siteboss.json.txt) file.

**Comment by PipoCanaja** [comment]
Hi @willhseitz 

Thanx for the test data. I added the snmprec file and the JSON matching file (you can compute it yourself using ./script/save-test-data.php -o siteboss -v 2).

For next time, you can directly add the files to the PR. 

We'll see how the tests are going, review and merge your PR

Thanx for your contribution !

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
