### PR TITLE
Move install to php53 branch if running an unsupported version of PHP

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Ok, I've tested this:

 * no updates
 * php 5.5 switch to php53
 * php 5.5 update in php53 branch
 * php 7.2 update switch to master
 * php 7.2 update in master branch

For the release version, I propose we create a new lightweight tag that way we can re-point the tag if we need to push an update.  Otherwise it will be stuck on the hardcoded sha until PHP is updated.

**Comment by murrant** [comment]
We also need to decide a branch point for php53.  Right now it is at 1.35.

**Comment by laf** [comment]
Can we not just move to a branch rather than a tag?

**Comment by murrant** [comment]
I guess it would be the same thing effectively, no reason we need to use tags even if they are on the "release" train.  Thanks for clearing that up @laf.

**Comment by murrant** [comment]
Both release and master will end up in the same php53 branch.  Seems pretty good.

This is pretty hard to test, but I have tested all the ones I could think of.

**Comment by murrant** [comment]
https://youtu.be/jrA-1cG_wq4?t=24

**Pull request merged**
