### PR TITLE
Added CPU temperature discovery/polling for DNOS

### PR DESCRIPTION
**Pull request by cschoonover91**
Issue #3394

### CODE REVIEW

**Comment by laf** [comment]
Looks like the polling file is the same as the discovery file :)

**Comment by cschoonover91** [comment]
I'm going to try and rewrite the poller

**Comment by cschoonover91** [comment]
I apparently misunderstood sensor polling entirely. Looks like a new polling script is unnecessary, even for stacked switches. The single file 'includes/discovery/sensors/temperatures/dnos.inc.php' plus the existing sensor polling successfully adds temperature data to DNOS devices.

**Comment by murrant** [comment]
Yeah, there is a generic poller for most health sensors that does the right thing.

**Pull request merged**
