### PR TITLE
Moved Device Groups menu 

### PR DESCRIPTION
**Pull request by alangregory**
Better Visualization

Before: 
rsz_old

After:
rsz_after

### CODE REVIEW

**Comment by laf** [comment]
What are your thoughts on putting it in both places? Good to have it in the new position but if you're looking for a device and you're already in the devices menu then it just means having to go to another sub-menu.

Probably also worth calling it Device Groups?

**Comment by alangregory** [comment]
It'll only apear on main menu, not inside "All Devices". I'll change name.

**Comment by f0o** [comment]
Can you make the hover-effect of the Groups entry to be a pointer and not a marker cursor?
I think there is just a class missing in your `<a>`-tag

**Comment by alangregory** [comment]
Missing href kkk

**Comment by f0o** [comment]
:+1:

**Pull request merged**
