### PR TITLE
Location based Alert Rule

### PR DESCRIPTION
**Pull request by SourceDoctor**
Alert Rule for a complete location

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
LGTM?

**Comment by josephtingiris** [comment]
Good idea.

The labels are a bit misleading.  `Devices, Group or Location` implies Devices or Groups or Locations.  When I select a location, devices and groups go away.  Was that intentional?

Maybe "Devices and Groups OR Location"?

**Comment by SourceDoctor** [comment]
@josephtingiris 
i see what you mean. Label was overseen by me.

`or` can be seen as `only this`, or as binary `or` which means at least one of them.
This was the text before also, and is handled this way in the complete system.

**Comment by josephtingiris** [comment]
I understand.  The part that got me was that I wasn't expecting it to completely remove the devices and groups and replace it with only the location.

**Comment by SourceDoctor** [comment]
@josephtingiris 
no no don't panic
the label will be fixed by me, thx for the hint

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
