### PR TITLE
fix: yaml files for edgeos and edgeswitch

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

1) discovery based only on sysdescr is not relevant in case of edgeos because that value can be changed via cli: set service snmp description command so i've added the sysObjectID match (which is already added in the tests files).

2) edgeswitch yaml file was malformed

### CODE REVIEW

**Comment by murrant** [comment]
What are you trying to fix here?
Both these devices share the same sysObjectID which is why they are problematic.

**Comment by murrant** [comment]
What are you trying to fix here?

Both of these have generic sysObjectIDs so using sysObjectID alone is problematic.

**Comment by crcro** [comment]
on edgeswitch is just alignment issue.
on edgeos i've added sysObjectID.

**Comment by murrant** [comment]
Do we need a new test to validate these changes?

**Comment by crcro** [comment]
no, the sysobjectid is already added in the edgeos.snmprec

**Comment by murrant** [comment]
Looks good.  Thanks!

**Pull request merged**
