### PR TITLE
Clarify disable, ignore and disable all alerts in device edit section

### PR DESCRIPTION
**Pull request by louis-oui**
Clarify disable, ignore and disable all alerts in device edit section

Reason for this PR: PR https://github.com/librenms/librenms/pull/10809/files introduces wording change. But this change is same than https://github.com/librenms/librenms/pull/8900/files that was rejected with laf's comment: https://github.com/librenms/librenms/pull/8900#issuecomment-405308064 
>IMHO I think the clarification of this belongs in the docs really. Disable doesn't just disable polling so it's a bit misleading if we say it does. Same for ignore.

Removed section "alert settings" and moved their settings "device settings" section.
Changed "Disable Polling" to "Disable polling and alerting":
Changed "Ignore Alerts:" to "Ignore alert tag:"
Changed "Disable all alerting for this host" to "Disable alerting".

Current implementation:
image
image

With the PR:
image

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/disable-ignore/1097/7

**Comment by kkrumm1** [comment]
Looks good to me but have some issues with the checks.

**Comment by louis-oui** [comment]
@kkrumm1 PR is ready
I will do some code cleaning in a seperate PR

**Comment by louis-oui** [comment]
Changed to WIP as so called "Disable all alerting for this host" / "Disable alerting" feature was broken (even without this PR)

**Comment by louis-oui** [comment]
@kkrumm1 OK to merge . I can do the fix of the broken "Disable all alerting for this host" / "Disable alerting" feature. Not broken because of this PR.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
