### PR TITLE
Update Api.php to include Options variable in the Body for POST requests

### PR DESCRIPTION
**Pull request by mzacchi**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @mzacchi 
The syntax for replacement is not correct. I'll update your patch to a more standard way.

**Comment by mzacchi** [comment]
OK, it seems to work fine in my environment. Looking forward to your correction.

**Comment by PipoCanaja** [comment]
> OK, it seems to work fine in my environment. Looking forward to your correction.

Done. Please try it now using `{{ $variable }}` syntax.

**Comment by mzacchi** [comment]
Yep, it worked perfectly.

**Comment by mzacchi** [comment]
> > OK, it seems to work fine in my environment. Looking forward to your correction.
> 
> Done. Please try it now using `{{ $variable }}` syntax.

It worked for me with the other syntax because I was using the "$variable" notation in the Body. After I updated the code, I had to change it to "{{ $variable }}".

**Pull request merged**
