### PR TITLE
Added option to disable footer in web interface

### PR DESCRIPTION
**Pull request by laf**
$config['enable_footer'] = 0 will disable the footer across the web interface.

I don't believe this will be an issue with copyright in anyway as the code is still licensed correctly but this provides users the ability to remove the footer easily.

### CODE REVIEW

**Comment by laf** [comment]
Scrut issues are not related to this PR at all!

**Comment by paulgear** [comment]
Personally, I think we should make 0 the default.  Or just delete the footer.

**Comment by laf** [comment]
I'm happy to delete / default to 0. Let me know which way you want this to go and I'll update.

**Comment by paulgear** [comment]
My feeling is cut it down to a single left-justified line "Powered by LibreNMS", which would be a link to /about/.  Looks like we need to update the /about/ page as well. :-)

**Comment by laf** [comment]
I'll update the text to just that and leave the ability to disable it in then :)

**Comment by laf** [comment]
All done.

**Pull request merged**
