### PR TITLE
Merge launch, SSH, telnet and settings into 1 dropdown

### PR DESCRIPTION
**Pull request by arjitc**
Screenshot: http://i.imgur.com/vV30EKQ.png

### CODE REVIEW

**Comment by laf** [comment]
:+1: from me. That's how it was done in the first place :)

**Comment by Rosiak** [comment]
:+1:

**Comment by laf** [comment]
@librenms/reviewers or anyone else - comments on this would be good?

**Comment by SaaldjorMike** [comment]
I've generally disliked the many buttons we had before, so :+1: from me

**Comment by masonke** [comment]
~KEM

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
Enough :+1: 's so merging.

**Pull request merged**
