### PR TITLE
fix: Fix Generex voltage sensor divisor

### PR DESCRIPTION
**Pull request by FTBZ**
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

screen shot 2017-03-09 at 15 03 30

- Fixed the sensor divisors for voltages (issue confirmed by many members)
- Added an option to exclude a specific sensor because Generex card use different divisors for the same sensor type

Details: #5977

### CODE REVIEW

**Comment by murrant** [comment]
FTBZ: this won't work this way.

get_device_divisor() gets called by the poller which doesn't have the "exclude" variable set.

Also, if you modify the function definition for get_device_divisor(), you need to update all calls to it.

Did you try using OID as I suggested  on IRC?

**Comment by FTBZ** [comment]
Not sure to understand why you say that won't work, because I tested et re-rested and its working fine?

For the calls to get_device_divisor(), I noticed a lot of other functions that wasn't complete, this is why I dared do that.

I didn't find an easy way with the OID, if you've an idea?

Thanks for the feedback.

**Comment by murrant** [comment]
You can only leave off arguments if there is  a default value for that argument :)

Did you test `./poller.php -h HOSTNAME -d -r -f -m voltage`?

I assume it works fine in the discovery, but the poller will still have the wrong divisor.

**Comment by murrant** [comment]
@FTBZ I got the logic switched around.  That should do it.

**Comment by FTBZ** [comment]
unknown

Don't understand how, but it's working fine!

**Pull request merged**
