### PR TITLE
Fix coding style in old (pre-2014) files

### PR DESCRIPTION
**Pull request by job**
Used the `Squiz` standard, with manual editing where the phpcbf made a mess

```
for i in $(cat list_of_old_files); do phpcbf --standard=Squiz $i; vim $i; echo $i; git diff; read; git commit -a ; read; done
```

### CODE REVIEW

**Comment by f0o** [comment]
:+1:

**Comment by f0o** [comment]
Running the patch on an install with several device types and it works. :+1:

**Comment by laf** [comment]
@f0o Also looks good on my install.

I don't want to merge right now as I won't be around so if you can merge in the morning and that way any systems auto updating in the day can shout for help if anything does break :)

**Comment by paulgear** [comment]
Some comments:
1. There's no point in removing the .exe file; it's in a subtree which is used to pull upstream, and it will only get put back, or worse, cause merge conflicts.
2. The addition of 'set -e' to scripts/*.sh is non-transparent and could cause problems.  I would recommend backing that out until we've checked over the component scripts.

**Comment by job** [comment]
@paulgear Unsure what you mean with non-transparent, would you prefer `set -ev` ? Currently those scripts have a yolo approach :-)

**Comment by job** [comment]
I removed the shellscript and .exe related commits from this PR

**Comment by f0o** [comment]
:+1:

**Comment by f0o** [comment]
Ok this needs a rebase now, sorry

**Comment by job** [comment]
@f0o rebase done, solved merge conflicts & pushed

**Comment by paulgear** [comment]
Looks good to me!

**Pull request merged**
