### PR TITLE
Add lint Github Action

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
I think this will be too much.
Larastan we should prepare for tho.

**Comment by murrant** [comment]
Larastan only check PHP code.  We need to lint python and bash code, too.   I tried to run against all files, but apparently, this means run all check against all files... way too much.

**Comment by Jellyfrog** [comment]
I'm aware what Larastan does and I still think the rest is almost unnecessary for this.

>I tried to run against all files, but apparently, this means run all check against all files... way too much.

It doesnt mean run all against all, it means run against all files not not just changed;

>Will parse the entire repository and find all files to validate across all types. NOTE: When set to false, only new or edited files will be parsed for validation.

And without disabling a lot of checks it will just be a mess, https://github.com/librenms/librenms-agent/blob/master/.github/workflows/linter.yml#L27-L32

**Comment by murrant** [comment]
It wasn't that bad, mostly just bash scripts we never touch with issues: https://github.com/librenms/librenms/runs/2206789857?check_suite_focus=true
Also, the whitelist is better than blacklist, as we only want a few validations.

**Comment by Jellyfrog** [comment]
I think you should enable black also

**Comment by murrant** [comment]
Black looked a little aggressive with its style enforcement, not sure I care about style in python.

**Comment by Jellyfrog** [comment]
It got built in fixer, so we don't need to care really, but i can submit a PR with that after this.

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
