### PR TITLE
Fix datepicker timezone issue(s) #1374, #1239, #1241

### PR DESCRIPTION
**Pull request by travishegner**
Basically, passing the unix timestamp straight from PHP without a format, and then using javascript to format the date on page load. With this, javascript automatically converts the format to browser time.

On form submission, changed the parsing to be done by moment.js since we already have it loaded and it seems to do better with cross browser compatibility, and again auto handles the browser's time conversion.

Also fixed a missing semicolon in the same code block.

Fixes: #1374, #1239, #1241

### CODE REVIEW

**Comment by clinta** [comment]
Curious, what's the login info for the CI builds? admin/admin doesn't seem to work.

**Comment by laf** [comment]
root
toor

Super secret :)

**Comment by travishegner** [comment]
It looks like the only issue left is that the RRD graph's timeline is that of the server's timezone. If the browser is in the same timezone as the server, then you won't notice obviously, but in any case I think this is still an improvement over how it works currently.

**Comment by laf** [comment]
Awesome work @travishegner :)

**Pull request merged**
