### PR TITLE
changed screenos test data and snmprec to remove internal data.

### PR DESCRIPTION
**Pull request by leandrojmp**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Whem submitting the screenos.snmprec for some tests, some internal ip range and mac addresses where not changed and sent by mistake.

I've regenerated the screenos.snmprec and the screenos.json files to remove this information from the master branch.

### CODE REVIEW

**Comment by laf** [comment]
Did you edit the json file direct? If so, you only need to run `./scripts/save-test-data.php -o example-os -m <module>`

**Comment by leandrojmp** [comment]
@laf I edited the snmprec file and ran the save-test-data.php with the parameters -o screenos -m processors,ports,arp-table to create the json file.

I will try to run it again.

**Comment by leandrojmp** [comment]
well, i don't know why it is failing, i regenerated the screen.json using the script and the same snmprec file.

**Comment by murrant** [comment]
There is no order by for the capture for the ports module.  Something on your system is creating the ports in a different order than Travis...

Maybe we need this:
```
diff --git a/tests/module_tables.yaml b/tests/module_tables.yaml
index c67a37305..07017749c 100644
--- a/tests/module_tables.yaml
+++ b/tests/module_tables.yaml
@@ -25,6 +25,7 @@ ports:
         excluded_fields: [device_id, port_id, poll_time, poll_period]
         joins:
             - { left: ports.port_id, right: ports_statistics.port_id }
+        order_by: ports.ifIndex, ports.ifDescr, ports.ifName
 os:
     devices:
         included_fields: [sysName, sysObjectID, sysDescr, sysContact, version, hardware, features, location, os, type, serial, icon]

```

**Comment by leandrojmp** [comment]
I temporarily changed my local modules_tables.yaml and ran the save-test-data.php again, but the generated json was the same.

**Comment by murrant** [comment]
I re-captured the data, but can't push to your master branch so sent pull request here #8410.

Sorry this took so long to get straight.

**Comment by leandrojmp** [comment]
oh, no problem! i will comment on the new pull request to see if it speeds up the merge.

**Pull request closed without merging**
