### PR TITLE
Smartoptics dcp m 40 zr

### PR DESCRIPTION
**Pull request by avermeer-tc**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
You are trying to match the sysObjectId of `.1.3.6.1.4.1.30826` which is already used for `smartos`. Looking at the only test data we have, smartos is .1.3.6.1.4.1.30826.1 and your new one is .1.3.6.1.4.1.30826.2 but that may not be 100% accurate so you should look into that some more.

**Comment by avermeer-tc** [comment]
I've added the correct test data now and updated the sensors.

**Comment by avermeer-tc** [comment]
@laf can you review this PR when you get the time? Thanks.

**Review by murrant — APPROVED** [review]
Looks good @avermeer-tc Thanks!

**Pull request merged**
