### PR TITLE
Disable all ports for large installs

### PR DESCRIPTION
**Pull request by mzac**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by murrant** [comment]
Needs rebase to fix travis-ci build, thanks.

**Comment by murrant** [comment]
@mzac I'd like to see this fixed to use pagination (bootgrid) instead of hidden.  This would fix the issue with it taking forever on large installs.
#2705

**Comment by f0o** [comment]
Agreeing with @murrant. Considering this as a blocker

**Comment by mzac** [comment]
Yes, I agree that pagination would be a good option also!  We can close these pull requests

**Pull request closed without merging**
