### PR TITLE
Add the ability to include an LDAP filter for users/groups in AD

### PR DESCRIPTION
**Pull request by ekoyle**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Allow users to set a filter to be ANDed with existing filters for AD authentication/authorization.

I have not tested the ad-authorization, since I'm not entirely sure how it works (I wonder if the two should be merged and add a config option like `auth_ad_authorization_only` to make the subtle changes to what it does?).

### CODE REVIEW

**Comment by murrant** [comment]
Nice change!  I haven't had a chance to test yet though.

Unrelated note: we need to add a bind user for ad/ldap sometime...

**Comment by ekoyle** [comment]
We should probably start from scratch on the LDAP foo with AD-compatibility and the ability to use LDAP for authorization-only in mind.

**Comment by FTBZ** [comment]
With this change, it's possible to use nested group with 1.2.840.113556.1.4.1941?

**Comment by ekoyle** [comment]
You should be able to filter by a nested group, but you wouldn't be able to
assign user levels to nested groups.

**Pull request merged**
