### PR TITLE
AOS-EMU2 add support for APC AP9320, fix humidity sensors

### PR DESCRIPTION
**Pull request by axemann**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for fixing this :)

Would you mind adding test data, especially for the new sysObjectID. It ensures we don't break things for the future.

https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

**Comment by axemann** [comment]
@laf Glad to help out! :-)

I've just added the snmprec and json files for this device as a variant, and squashed (hopefully) the commits.  Let me know if I need to add/change anything else.

**Comment by laf** [comment]
Awesome. Thanks very much :) If at some stage you could submit sensor test data that would be ace as well but we'll take this for now :D

**Comment by axemann** [comment]
Quite welcome :-)

I'll be working on the contact and outlet states next, so I'll try to include all the sensor test data when I submit that PR.

**Pull request merged**
