### PR TITLE
devices: Add Phybridge OS support

### PR DESCRIPTION
**Pull request by vivia11**
Hello,
Adding support for NVT Phybridge.
Tested with a Flex Switch.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
You need to minimize your svg files and the icon should be inverted I think.
https://jakearchibald.github.io/svgomg/

**Comment by laf** [comment]
I've just pushed the json test data needed for this.

however, the OS name is just the company name when it should be named after the firmware of the device. What is that name? If it doesn't have one then it should closely resemble the product name.

**Comment by vivia11** [comment]
@laf 
From what I can gather the software version is: "SYS 3.1.9 PKG 7.0.0". Not sure if SYS or PKG is the name...
The model name is Flex Switch - 24 Port.

Should I rename the files/os to sys | pkg | flex?

**Comment by laf** [comment]
Looks like it might be better as phybridge-flex

**Comment by vivia11** [comment]
Okay I renamed the OS to phybridge-flex. Let me know if I'm missing something or if I should rename anything else.

**Pull request merged**
