### PR TITLE
Added support for Canon printer model TM TX series

### PR DESCRIPTION
**Pull request by Wooboy**
ADD support printer model TM TX series

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@Wooboy could you please look into adding test data?

**Comment by Wooboy** [comment]
UPDATE, upload canon printer TM series snmpsim file

please help me check this commit 
I'm not a programmer, I just use Librenms to manage our company asset

thant you

**Comment by Jellyfrog** [comment]
Hello

You also need to add the json file, described in the test docs. 

The rest looks fine!

**Review by murrant — APPROVED** [review]
Thanks @Wooboy  and  @PipoCanaja

**Comment by Wooboy** [comment]
I've no time study how to generate json for test.
Thanks @PipoCanaja help

**Pull request merged**
