### PR TITLE
Refactor datastores to classes

### PR DESCRIPTION
**Pull request by murrant**
Initial unit tests.  (some may be false positive)
Old functions shimmed to classes
Added Config::forget so I could use it for tests

This requires php-sockets for many non-rrd based data stores.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I've just tested this on my dev env against one single localhost instance and I don't think it's working. Tested with `./scripts/github-apply`

With patch:

```
28% InfluxDB data:  {"measurement":"storage","tags":{"hostname":"localhost","mib":"hrstorage","descr":"/"},"fields":{"used":23914377216,"free":60245131264}}
RRD[update /opt/librenms/rrd/localhost/storage.rrd N:23914377216:60245131264]
RRDtool Output: OK u:0.00 s:0.00 r:1.36
```

Without patch:

```
28% RRD[update /opt/librenms/rrd/localhost/storage-hrstorage-_.rrd N:23914303488:60245204992]
```

**Comment by murrant** [comment]
I can't reproduce what you are seeing @laf can you try disabling influxdb?  I still need to re-test those after all the refactors/updates.

**Comment by murrant** [comment]
Tested: Rrd, InfluxDB, OpenTSDB, Graphite, and Prometheus.

**Comment by laf** [comment]
@murrant Disabling influxes support shows it working, that means if influxdb is not available rrd updates will fail so I'd consider that a blocker.

I can also see duplicate red updates being run:

```
RRD[update /opt/librenms/rrd/localhost/ping-perf.rrd N:0.08]
RRDtool Output: OK u:0.00 s:0.01 r:1.31
RRD[update /opt/librenms/rrd/localhost/ping-perf.rrd N:0.08]
RRDtool Output: OK u:0.00 s:0.01 r:1.33
RRD[update /opt/librenms/rrd/localhost/poller-perf.rrd N:1.339]
RRDtool Output: OK u:0.00 s:0.01 r:1.33
RRD[update /opt/librenms/rrd/localhost/poller-perf.rrd N:1.339]
RRDtool Output: OK u:0.00 s:0.01 r:1.33
``

**Pull request merged**
