### PR TITLE
More appropriate state colours for MS Teams alerts

### PR DESCRIPTION
**Pull request by cjwbath**
Currently the alerting into MS Teams uses only two accent colours on the messages - green for OK (recovery) and red for everything else. I think it would be more appropriate to use something neutral (like blue) for acknowledgements, and something less bad (like yellow) for "got better" alerts.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
nice
could be interesting for other transports with Colors too.
Slack for example :-)

**Comment by cjwbath** [comment]
> could be interesting for other transports with Colors too.
> Slack for example :-)

Yeah I considered generalising but couldn't spot an appropriate place for a common getColor function. LibreNMS\Alert\Transport maybe, although that doesn't feel quite right somehow.

**Comment by PipoCanaja** [comment]
Ths for testing @louis-oui

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
