### PR TITLE
Remove the virtual images from the docs

### PR DESCRIPTION
**Pull request by laf**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Why?

**Comment by laf** [comment]
I just don't see the benefit of them anymore, they are out of date, not just from being ubuntu 22.04 but also from the perspective that none of the software is up to date. That's a risk for people as they will expect things to be fairly recent.

LibreNMS won't update to the latest version without PHP 8.3 either because it's running 8.1 right now.

It generates queries from people which whilst few right now will probably increase especially with the lack of updates being applied.

From a security perspective, they run a set of known credentials, that hasn't changed in a while but I bet a lot of people don't  change the default creds.

**Comment by murrant** [comment]
I do like that it is easy to try LibreNMS with these images, but really it is not good for people to use as their production install.

**Review by Jellyfrog — APPROVED** [review]

**Comment by Jellyfrog** [comment]
We could offer a docker compose or what not for testing. Vm images are old school.

**Pull request merged**
