### PR TITLE
thecityofguanyu/add-calix-e5-support

### PR DESCRIPTION
**Pull request by thecityofguanyu**
On branch thecityofguanyu/add-calix-e5-support

 Changes to be committed:
	modified:   includes/definitions.inc.php
	modified:   includes/discovery/os/calix.inc.php
	new file:   includes/discovery/sensors/temperatures/calix-e5.inc.php
	new file:   includes/polling/os/calix-e5.inc.php
        new file(s):   mibs/a bunch of mibs

### CODE REVIEW

**Comment by Rosiak** [comment]
A lot of the MIBS included already exist in the mibs dir, hence being redundant.

**Comment by thecityofguanyu** [comment]
@Rosiak 

Deleted all of the MIBs that appeared to be redundant in 8d09c3e.

**Comment by laf** [comment]
Thanks, I don't see the point in creating a new OS definition for this.

Just deal with the differences in the calix.inc.php files.

**Comment by thecityofguanyu** [comment]
@laf 

Consolidated the E5 support into the pre-existing 'calix' OS definition.

**Comment by laf** [comment]
You still have includes/polling/os/calix-e5.inc.php in this

**Comment by laf** [comment]
bump @thecityofguanyu

**Comment by thecityofguanyu** [comment]
@laf 

Removed `includes/polling/os/calix-e5.inc.php` in latest commit

**Comment by laf** [comment]
Didn't notice this the first time round but you've got 4 .xls files in here, can you remove them pls.

Whilst you're at it you may as well remove .mib from the end of the file extensions.

**Comment by thecityofguanyu** [comment]
@laf 

>Didn't notice this the first time round but you've got 4 .xls files in here, can you remove them pls.
>
>Whilst you're at it you may as well remove .mib from the end of the file extensions.

This is done.

**Pull request merged**
