### PR TITLE
Converted alerts table to use bootgrid

### PR DESCRIPTION
**Pull request by laf**
The only thing missing at the moment is the colored rows as I've not worked out how to do this in bootgrid yet :(

### CODE REVIEW

**Comment by laf** [comment]
Rather than color each row (which appears to be difficult in bootgrid) I've taken to add a status column to indicate the alerts status:

http://pasteboard.co/2dKd5v8D.png

If people are happy with this then it's good to go.

**Comment by f0o** [comment]
Good for me. Shall I merge?

**Comment by laf** [comment]
I'm happy if others are.....no idea what's gone on with scrut on this one. Pretty sure it's not accurate.

**Comment by f0o** [comment]
Yeah no worries about scrut. It seemsbto have forgotten about all the old issues heh

**Pull request merged**
