### PR TITLE
RRD Cleanup: centralize rrd_exists check, utilize data_update() and rrd_name()

### PR DESCRIPTION
**Pull request by murrant**
Remove is_file(rrd) checks from poller and discovery.
Use data_update instead of rrd_update/rrd_create and influx_update
Centralize rrd file check so we can check against a remote rrdcached server too
Use rrd_name() to generate rrd file names
Allow read-only rrdtool commands when norrd is set
We should be able to do distributed polling without NFS with this patch, but I haven't tested it.

Tested on a couple installs for me.

### CODE REVIEW

**Comment by laf** [comment]
I'll throw this on at home and test, once we think we've ironed out the big flaws I'm happy to throw this onto works install.

I've been waiting to setup a new remote poller in our office so it makes sense to give it a whirl on that - in fact I can test this just on that one poller to start with.

**Comment by laf** [comment]
No issues at home here.

Will move it to work and see how that goes.

**Comment by laf** [comment]
`https://scrutinizer-ci.com/g/librenms/librenms/inspections/abae7c65-126d-43e1-ba8c-1d74f11c3461/issues/files/includes/rrdtool.inc.php?status=new&selectedLabels%5B0%5D=9&orderField=path&order=asc&honorSelectedPaths=0`

Only thing labelled as a bug.

**Comment by murrant** [comment]
I think that is a parsing bug, as it isn't expected to pass variables that way since they will be out of scope.  But we don't care about these variables and only pass them because they are required.  I could break them out into separate lines, but that would be much messier and increase the scope of the variables.

**Comment by paulgear** [comment]
@murrant, I haven't had a chance to try this yet, but just wanted to say thanks for doing it.  It was always my intent to go through bit by bit and fix up the code to consistently use data_update().

**Comment by laf** [comment]
As per IRC, 2) Seems to be the best option.

**Comment by laf** [comment]
Tagged to merge in 24 hours.

@librenms/reviewers speak up now.

**Comment by tuxis-ie** [comment]
This broke the Proxmox and Ceph plugins (again).

**Pull request merged**
