### PR TITLE
Add timeout on unix agent execution after connect.

### PR DESCRIPTION
**Pull request by spinza**
I was seeing agent execution getting stuck but without time-out occurring.  I.e. the poller was connecting to the port but not streaming data which should result in timeout.  

This adds a stream time-out to fix that.

### CODE REVIEW

**Comment by spinza** [comment]
One question that's  whether to continue processing the data if the agent had timed out during fetch.  Means we have partial data.  At the moment it is processing whatever data has been fetched. So if it's usable it will be used.

**Comment by laf** [comment]
I'd say grab what data we can. 

Prob worth setting this to be a user controlled variable so people can increase / decrease the timeout.

**Comment by spinza** [comment]
The existing connection time-out is 10s hard coded.  Just stuck with that, but can change if you want.

**Comment by spinza** [comment]
OK, I've added config settings for both time-outs.

**Pull request merged**
