### PR TITLE
Updated map to support some new features

### PR DESCRIPTION
**Pull request by laf**
1. You can hover over devices to see normal overview graphs

2. You can hover over a link to see it's bandwidth usage.

3. Better placement of nodes

4. Nodes are now box shaped rather than oval.

5. Links will now change color based on the throughput on that connection.

### CODE REVIEW

**Comment by paulgear** [comment]
Not sure what's going on with Scrutinizer, but one thing I'd like to see changed is "no_overlib" - this would be much better expressed as "overlib", with a default of 1 instead of 0.  Any time when we see an option to disable something, we should turn it into an option to enable it instead.  Different defaults are easy to understand; negated logic isn't.

**Comment by paulgear** [comment]
Also, I'd love to see a screenshot of your setup on this - sounds like a good improvement.

**Comment by laf** [comment]
Updated no_overlib to overlib.

Screenshot: http://pasteboard.co/2DHpQkCj.png

**Comment by paulgear** [comment]
Looks good!

**Pull request merged**
