### PR TITLE
NAC - Improve search in WebUI - Keep Historical data

### PR DESCRIPTION
**Pull request by PipoCanaja**
PR plans: 

- [x] Extend search in NAC pages to most fields, including vendor (strongly inspired from FDP Table code)
- [x] Add timestamps for entries in the ports_nac table
- [x] Adapt DB calls to keep historical entries instead of deleting
- [x] Adapt cleaning code in daily to clean this table
- [x] Define the entries that will be kept in historical data (for instance, a device going from auth to unauth should be kept in historical data)
- [x] Add proper option in config menus to configure duration of historical NAC data (default 10 days)
- [x] Add option to display historical data in existing pages
- [x] Add a webui in 'Port' pages to show all NAC historical data associated with it

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Device NAC page : 
cap1

**Comment by PipoCanaja** [comment]
Global NAC page, with all historical entries displayed as well : 
Capture d’écran 2023-12-17 à 20 00 58

**Comment by PipoCanaja** [comment]
And tab in port page : 
cap2

**Review by laf — APPROVED** [review]
LGTM

**Pull request merged**
