### PR TITLE
Fortimail add mail queues message count

### PR DESCRIPTION
**Pull request by cwispy**
Added mail queues message count
Displays the name of the message queue and how many messages are currently in each queue.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I think you might want to set the type of this sensor to a gauge.  (Search in the existing yaml for gauge for an example)

**Comment by murrant** [comment]
Also, it would be good to add some test data.  Since this only uses a single oid, we could probably insert it into one of the existing snmprecs.

**Comment by cwispy** [comment]
> I think you might want to set the type of this sensor to a gauge. (Search in the existing yaml for gauge for an example)

I did not see a gauge type listed in the docs or in any of the other yaml files, or are you referring to using a file in the polling/applications dir to create a gauge from the data?

**Comment by murrant** [comment]
I looked it up and rrd_type is GAUGE by default, so all good :)

**Review by murrant — APPROVED** [review]

**Pull request merged**
