### PR TITLE
Remove legacy function calls

### PR DESCRIPTION
**Pull request by murrant**
Use current methods.
This is not exhaustive, but as you can see, quite a bit.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by Jellyfrog — APPROVED** [review]

**Comment by Jellyfrog** [comment]
🥳

**Comment by murrant** [comment]
Need to watch out that PRs that might reference legacy functions.

**Comment by Jellyfrog** [comment]
This broke some stuff here and there;
https://github.com/librenms/librenms/pull/12672
Also broke "add device" and someone on discord said they had troubles with discovery

**Comment by murrant** [comment]
How could url generation be related to discovery?

**Comment by base-zero** [comment]
I can confirm that I'm seeing the same error as reported above by @Jellyfrog when adding devices, however the device is added correctly and just show the error.

**Pull request merged**
