### PR TITLE
Adding support for SiteBoss360 appliance

### PR DESCRIPTION
**Pull request by Pyrrotech**
Includes YAML files for OS as well as MIBS.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This seems to be a duplicate of other SiteBoss operating systems (which may already be duplciates).

What makes this a distinct OS a part from the others?

**Comment by murrant** [comment]
This still needs test data before it can be merged.

**Comment by Pyrrotech** [comment]
Still working on this. Had to put it down to build the new environment for
our LibreNMS.

**Comment by Phoenhax** [comment]
[Siteboss360 test data.txt](https://github.com/librenms/librenms/files/13954262/Siteboss360.test.data.txt)

Here is the test data requested. If anything else is needed or missing let me or Pyrrotech know.

**Comment by PipoCanaja** [comment]
Was re-submitted in #16422 and merged. This PR can be closed

**Pull request closed without merging**
