### PR TITLE
Menubar Change

### LINKED ISSUE #1575: Suggestion: Menubar Change
A minor change.
Thoughts/ideas?
http://imgur.com/lLrBcuj,jfz6KH1#0
http://imgur.com/lLrBcuj,jfz6KH1#1

### PR DESCRIPTION
**Pull request by Rosiak**
Fix #1575

screen shot 2015-12-09 at 23 32 22

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
Suggestion: Change it to grey instead of red when there are no unread messages.

**Comment by paulgear** [comment]
:+1: to @SaaldjorMike's suggestion

**Comment by laf** [comment]
I do like it but......for 0-9 messages it 'just' about works - it looked better on your mock up.

Can you move the bubble slightly to the left so that it doesn't overlap with the next dropdown?

I'd also say :+1: to grey on 0 messages. Could you also add the number next to the notifications text in the actual drop down?

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by laf** [comment]
Hate to be picky :/ Is the fix for the overlap on the badge shrinking the font-size? If so it's now really illegible.

**Comment by laf** [comment]
:+1: from me.

@librenms/reviewers

**Pull request merged**
