### PR TITLE
Include install scripts to help to install librenms on environment

### PR DESCRIPTION
**Pull request by joubertredrat**
Include install scripts to help users to deploy default LibreNMS on environment.

For more information, see https://github.com/joubertredrat/librenms-faststart

### CODE REVIEW

**Comment by f0o** [comment]
Please add some error-catching, your script is currently just running through and wont halt if an error occurs

**Comment by joubertredrat** [comment]
@f0o 
I can put a validation in all functions or check usual errors, but is impossible to catch all error that can be occur in environment.

I can test as example if mysql is running, but I can't test if mysql broken because InnoDB isn't supported as example.

**Comment by f0o** [comment]
actually just a log and &&-operations are enough, just so it wont continue execution if some part fails

**Comment by joubertredrat** [comment]
I will rewrite script

**Comment by paulgear** [comment]
@joubertredrat I don't think there's any need to rewrite completely.  Just check the obvious things and add set -e; set -u at the start.

**Pull request closed without merging**
