### PR TITLE
Custom Maps: geo map and color backgrounds

### PR DESCRIPTION
**Pull request by murrant**
- set background as a live map
- set background color
- convert a map to an image for performance and offline access

image

tabs blade component
geo-map blade component and related script enhancements

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by electrocret** [comment]
I put this on my dev instance -
When trying to save the background as a map, it returns a server error.

I found this in the librenms logs:

array_merge(): Argument #1 must be of type array, null given {"userId":7,"exception":"[object] (TypeError(code: 0): array_merge(): Argument #1 must be of type array, null given at /opt/librenms/app/Http/Controllers/Maps/CustomMapBackgroundController.php:66)"}

**Comment by murrant** [comment]
@electrocret good catch, was a hold-over while I was deciding the schema.  I changed background_data to not nullable and set the default to empty array.  This should prevent the error.  You'll have to roll-back and re-apply the migrations.

Thanks for testing!

**Comment by murrant** [comment]
Nevermind :)  just handle the nulls apparently text can't have a default.  No need to roll back the migrations.

**Comment by electrocret** [comment]
Tested again - We made it further this time! :D  

If you adjust map, then set the image and save, it gives a Entity too large error message. (Nothing in the Logs)

image

**Comment by murrant** [comment]
@electrocret this is due to web server and php upload limits.  I'm not sure how to better communicate that.

Somewhat related, perhaps we could increase the compression on the captured image of a map...

**Pull request merged**
