### PR TITLE
Maintenance Mode for a complete Location

### PR DESCRIPTION
**Pull request by SourceDoctor**
Scheduled Maintenance now possible for a complete location

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/feature-request-maintenance-by-geo-location/1083/3

**Comment by kkrumm1** [comment]
That’s awesome thank you!

**Comment by SourceDoctor** [comment]
@kkrumm1 
n.p. :-)

**Comment by kkrumm1** [comment]
Do you want to keep this WIP? If you do that stops merged

**Comment by SourceDoctor** [comment]
@kkrumm1 
yes, i changed it to WIP.
Because i recoginzed $this->location detection doesn't work as it should.

I expected location id as return value for handled device on location method,
but it stays empty for all devices.
Seem's to be an bug on line 627,
but i'm not such good in eloquent database handling to find the issue.

Do you have an idea?

**Comment by SourceDoctor** [comment]
@kkrumm1 
problem detected and fixed.

ready to merge now ;-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
