### PR TITLE
Use high precision OIDs for APC UPS sensors

### PR DESCRIPTION
**Pull request by CirnoT**
Use high precision OIDs for APC UPS sensors.

I have looked at the git history to understand why low precision OIDs were used, but in the end I have traced them being unchanged ever since initial code was written before the fork, with no comments or description as to why.

Note that the divisor for these is 10, which is still lower than what UPS reports internally (divisor 100), but it is way better (especially concerning battery voltage) than 1V precision we had before. There doesn't seem to be any other OID on PowerNET-MIB that would provide higher precision sadly.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @CirnoT 
Can we be sure that all APC devices support both the Low and the High prec OIDs ? If yes, then we are clear to remove the Low. If no, then we'd need to try the high prec, and if they are not available, fall back to low prec.

**Comment by CirnoT** [comment]
I do not have any other units to test with.

I'd say we can be reasonably sure that all units should support it, as internally the UPS does report 10mV precision for battery voltage (it is requirement for UPS to even work properly), and that can be traced back to even ones as old as 1996 where PowerChute plus over RS232 was used to report that data.

**Comment by murrant** [comment]
@CirnoT how would you feel about changing these to yaml?

**Comment by CirnoT** [comment]
Not familiar or up-to-date with all the recent changes in LibreNMS

**Comment by murrant** [comment]
basically all the fields in the discover_sensor have 1-1 mappings.  You also tell it what table to walk and what the numeric oid will be.

**Comment by CirnoT** [comment]
The code seems to also loop over some OIDs for multi phase UPSes and also try to do similar things with PDUs, can this also be achieved somehow with YAML?

**Comment by murrant** [comment]
so, what it seems to do is if there are multiple phases, use one oid, otherwise use another.  You can do this via the skip_values field checking upsPhaseNumInputPhases.1

**Comment by Jellyfrog** [comment]
Thank you for your contribution but we're closing this due to inactivity.  
Feel free to reopen if you plan on finishing it!

**Comment by CirnoT** [comment]
The code is very much ready, I don't exactly have time to rework it for YAML because I believe that it is outside of scope of what this PR wants to achieve.

**Comment by Jellyfrog** [comment]
@CirnoT could you rebase this to fix merge conflicts?

**Review by Jellyfrog — APPROVED** [review]

**Comment by PipoCanaja** [comment]
@CirnoT Seems that we already have issues here. We definitely need to keep existing sensors for existing users and add new sensors in //.

**Comment by murrant** [comment]
We should probably revert this until it is fixed...

**Pull request merged**
