### PR TITLE
Better services graphing support

### PR DESCRIPTION
**Pull request by CirnoT**
- This moves services graph code from `device/` to `service/` and removes unused code (`service/availability.inc.php`). This has no real changes to end-user except ensuring that when viewing graph, proper title is shown:

After:
chrome_2019-05-03_17-35-12
Before:
chrome_2019-05-03_17-35-49

- Second commit adds proper support for services in dashboard graph widget. Previously it was piggy-backing on generic device graph, which made it impossible to select specific service for device (first service would be always used). This adds same level of support for services as present with Munin Plugins, where you can select service to be graphed.

chrome_2019-05-03_17-38-27

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Looks good but.  I think it could cause some issues if people are linking to existing graphs called device_service.  Either find a way to redirect that or we can just send a user notification probably.

**Comment by CirnoT** [comment]
I think sending notification would be preferred over adding additional logic for redirecting (which may cause issues later on if we decide to have service graph under device for something else than Nagios services).

**Comment by murrant** [comment]
Could you create a notification on https://github.com/librenms/librenms.github.io ?

**Comment by CirnoT** [comment]
Done at https://github.com/librenms/librenms.github.io/pull/116

**Pull request merged**
