### PR TITLE
Discover box cameras models

### PR DESCRIPTION
**Pull request by luigirosa**
Please give a short description what your pull request is for

Box camera models are identified by "Box Camera":

SNMPv2-MIB::sysDescr.0 = STRING: ; AXIS Q1656; Box Camera; 10.12.240; Jun 03 2024 14:13; 900; 1

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data]([axiscam_box.snmprec.txt](https://github.com/user-attachments/files/17965760/axiscam_box.snmprec.txt)).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by luigirosa** [comment]
[axiscam_box.snmprec.txt](https://github.com/user-attachments/files/17965761/axiscam_box.snmprec.txt)

**Comment by Jellyfrog** [comment]
@luigirosa you need to commit the snmprec file and the json test data file

**Comment by luigirosa** [comment]
> @luigirosa you need to commit the snmprec file and the json test data file

The snmprec is attached in the thread, I am attaching again here

I modified the yaml file and Box model camera is recognized as AXIS again then run 

 `./scripts/collect-snmp-data.php -h 59 -v 'box'`
 
 to collect the file (had to ad TXT extension)
[axiscam_box.snmprec.txt](https://github.com/user-attachments/files/17968429/axiscam_box.snmprec.txt)

But when I run 

`./scripts/save-test-data.php -o axiscam  -v 'box'`

I get some messages of dependencies already satisfied then 

```
Failed to start snmpsim, make sure it is installed, working, and there are no bad snmprec files.
Run ./scripts/save-test-data.php --snmpsim to see the log output
```

But if I run the command I have no log output, only the usage of the command.

In the end Axis added Box model cameras, you only need to add **Box** to the regex in yaml script to have the box cameras recognized as Axis instead of generic dvice

**Comment by PipoCanaja** [comment]
Hi @luigirosa 
Please put the SNMPREC directly in the PR in the correct directory.

**Comment by luigirosa** [comment]
> Hi @luigirosa Please put the SNMPREC directly in the PR in the correct directory.

Uh... Sorry for the lack of familiarity, can you please expand _PR_ ?

SNMPREC file is now in /opt/librenms/tests/snmpsim/axiscam_box.snmprec

Thank you

**Comment by laf** [comment]
This is a pull request (PR) you've done :)

If you upload that snmprec file to this folder: https://github.com/luigirosa/librenms/tree/patch-1/tests/snmpsim

Someone else will generate the json data.

**Comment by laf** [comment]
I've added both files for you.

**Review by laf — APPROVED** [review]
LGTM

**Pull request merged**
