### PR TITLE
Re-Added SQL rule generation

### PR DESCRIPTION
**Pull request by f0o**
solves #795

### CODE REVIEW

**Comment by laf** [comment]
GetDevicesFromGroup in another file now (html/includes/tables/devices.inc.php)

I'll take a look why the device graphs can't be used.

**Comment by laf** [comment]
Merging for now. I'll come back to this so we can clean up the sql code generation.

**Comment by f0o** [comment]
Is there a way to make bootgrid load the graphs?

**Comment by laf** [comment]
Only if it was done as a table :(

The queries are just duplicated so we just need to move those to another file and they can then be included when needed.

**Pull request merged**
