### PR TITLE
Rewrite the docs for OS discovery

### PR DESCRIPTION
**Pull request by Jellyfrog**
To reflect it's now part of discovery instead of polling,
Hopefully helps contributors a bit.

image

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-67-release-changelog-august-2020/13285/1

**Comment by murrant** [comment]
Thanks for this @Jellyfrog I was planning on including that when I update more of the existing OS.  (also adding yaml support)

**Comment by arrmo** [comment]
Hi,

Funny timing - I was just adding a new OS last night (still WIP, but for BeagleBoard). And adding (temperature) sensors as part of it - so somewhat related. It seems like I can't use a string OID, rather only numeric based, or polling after that fails. Is that a known, or should it work?

Thanks!

**Comment by murrant** [comment]
@arrmo textual oids are encouraged, are you sure you have included the mib?

**Comment by arrmo** [comment]
Actually, that answers my question 😆 - thanks! It's extend, trying to use text as part of the extend string ... that won't be in an MIB (agreed?).

**Pull request merged**
