### PR TITLE
TP-Link Jetstream DDM and PoE Support

### PR DESCRIPTION
**Pull request by jbronn**
This PR adds the following support for TP-Link Jetstream switches:
* DDM sensors, including module-specific limit values (why PHP was used instead of YAML).
* PoE, including overall consumption sensors.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Which limit values are not supported by yaml?

**Comment by jbronn** [comment]
@Jellyfrog

Originally I only had the state sensors in PHP because YAML discovery wouldn't accept the string `True`/`False` as numeric and refuse to discover.  I tried doing the DDM sensors and limits in YAML with something like:
```yaml
    sensors:
        pre-cache:
            data:
                -
                    oid:
                        - ddmStatusEntry
                        - ddmTempThresholdEntry
        temperature:
            data:
                -
                    oid: ddmStatusEntry
                    num_oid: '.1.3.6.1.4.1.11863.6.96.1.7.1.1.2.{{ $index }}'
                    value: ddmStatusTemperature
                    descr: 'DDM Temperature {{ $ddmStatusPort }}'
                    entPhysicalIndex: '{{ $index }}'
                    entPhysicalIndex_measured: ports
                    group: SFPs
                    index: 'ddmStatusTemperature.{{ $index }}'
                    skip_values: N/A
                    low_limit: ddmTempThresholdLowAlarm
                    low_warn_limit: ddmTempThresholdLowWarn
                    high_limit: ddmTempThresholdHighAlarm
                    warn_limit: ddmTempThresholdHighWarn
```
However, all limit values were ignored -- I'm assuming this was because the limits in `ddmTempThreshold*` are members of the `ddmTempThresholdEntry` (from `TPLINK-DDMTEMPTHRESHOLD-MIB`) and not the `ddmStatusEntry` OID (from `TPLINK-DDMSTATUS-MIB`).  I'll gladly ditch the code for YAML if possible!

**Comment by SirMaple** [comment]
Thank you!

This appears to have done the trick for my TP-Link T1600G-28PS 3.0. I now have PoE details on the Overview tab and under each ports detailed graphs.

**Comment by Jellyfrog** [comment]
> @Jellyfrog
> 
> Originally I only had the state sensors in PHP because YAML discovery wouldn't accept the string `True`/`False` as numeric and refuse to discover. I tried doing the DDM sensors and limits in YAML with something like:
> 
> ```yaml
> mib: TPLINK-SYSINFO-MIB:TPLINK-SYSMONITOR-MIB:TPLINK-DDMSTATUS-MIB:TPLINK-DDMTEMPTHRESHOLD-MIB:TPLINK-POWER-OVER-ETHERNET-MIB
> ...
>     sensors:
>         pre-cache:
>             data:
>                 -
>                     oid:
>                         - ddmStatusEntry
>                         - ddmTempThresholdEntry
>         temperature:
>             data:
>                 -
>                     oid: ddmStatusEntry
>                     num_oid: '.1.3.6.1.4.1.11863.6.96.1.7.1.1.2.{{ $index }}'
>                     value: ddmStatusTemperature
>                     descr: 'DDM Temperature {{ $ddmStatusPort }}'
>                     entPhysicalIndex: '{{ $index }}'
>                     entPhysicalIndex_measured: ports
>                     group: SFPs
>                     index: 'ddmStatusTemperature.{{ $index }}'
>                     skip_values: N/A
>                     low_limit: ddmTempThresholdLowAlarm
>                     low_warn_limit: ddmTempThresholdLowWarn
>                     high_limit: ddmTempThresholdHighAlarm
>                     warn_limit: ddmTempThresholdHighWarn
> ```
> 
> However, all limit values were ignored -- I'm assuming this was because the limits in `ddmTempThreshold*` are members of the `ddmTempThresholdEntry` (from `TPLINK-DDMTEMPTHRESHOLD-MIB`) and not the `ddmStatusEntry` OID (from `TPLINK-DDMSTATUS-MIB`). I'll gladly ditch the code for YAML if possible!

I think @murrant might know the secrets of this :)

**Comment by PipoCanaja** [comment]
@jbronn  : 
Seems that:
- you don't need to precache `ddmStatusEntry` cause you'll load it anyway in the sensor. 
- `skip_values` is not mandatory, and most importantly, `skip_values: N/A` is not a valid syntax. Just remove the line if you have nothing to skip. 

> However, all limit values were ignored -- I'm assuming this was because the limits in `ddmTempThreshold*` are members of the `ddmTempThresholdEntry` (from `TPLINK-DDMTEMPTHRESHOLD-MIB`) and not the `ddmStatusEntry` OID (from `TPLINK-DDMSTATUS-MIB`). I'll gladly ditch the code for YAML if possible!

It is necessary to precache the OIDs that are not in the table the sensor is using. So you took the right direction. Let's try if the above remarks will help solve the issue. 

Bye

> ```yaml
> mib: TPLINK-SYSINFO-MIB:TPLINK-SYSMONITOR-MIB:TPLINK-DDMSTATUS-MIB:TPLINK-DDMTEMPTHRESHOLD-MIB:TPLINK-POWER-OVER-ETHERNET-MIB
> ...
>     sensors:
>         pre-cache:
>             data:
>                 -
>                     oid:
>                         - ddmTempThresholdEntry
>         temperature:
>             data:
>                 -
>                     oid: ddmStatusEntry
>                     num_oid: '.1.3.6.1.4.1.11863.6.96.1.7.1.1.2.{{ $index }}'
>                     value: ddmStatusTemperature
>                     descr: 'DDM Temperature {{ $ddmStatusPort }}'
>                     entPhysicalIndex: '{{ $index }}'
>                     entPhysicalIndex_measured: ports
>                     group: SFPs
>                     index: 'ddmStatusTemperature.{{ $index }}'
>                     low_limit: ddmTempThresholdLowAlarm
>                     low_warn_limit: ddmTempThresholdLowWarn
>                     high_limit: ddmTempThresholdHighAlarm
>                     warn_limit: ddmTempThresholdHighWarn
> ```

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by PipoCanaja** [comment]
Hi @jbronn 
Looks good to me like this. If it is OK with your tests, just let me know and it will be merged.

**Comment by jbronn** [comment]
@PipoCanaja the YAML conversion and test updates were all done in 8a154ae; it's ready to merge.  Thanks for the help!

**Pull request merged**
