### PR TITLE
added functionality to set sysLocation override in $os.inc.php files

### PR DESCRIPTION
**Pull request by willhseitz**
Copied code to set/update device location_id from `./includes/polling/core.inc.php` to new function set_device_location() in `./includes/polling/functions.inc.php`. Added function in `./includes/polling/os.inc.php` to use with variable `$location`

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by willhseitz** [comment]
I don't understand the error from Travis CI. 
I updated the definition for the enexus OS, but it is reporting that enexus_smartpack is also changed. Are there multiple test data files for a single OS type?

When I tried to save test data for the enexus_smartpack OS, I get this error:

```
 ./scripts/save-test-data.php -o enexus_smartpacks
Starting snmpsim listening on 127.1.6.1:1161...
OS: enexus_smartpacks
Module: all

enexus_smartpacks: Already have host 127.1.6.1 (<private>) due to duplicate sysName
```

**Comment by murrant** [comment]
You have the setting enabled that prevents duplicate sysName's  either disable that or remove the duplicated sysName device from your system. (or set up a separate testing DB)

The Travis ran tests error at:
-            'location' => '<private>'
+            'location' => 'Site'

Which means the data does not match the recorded data.  You can just edit the json by hand for this small change.

Incidentally, we use enexus and we use sysLocation for ours, I'm not sure they even provide "site".  I'll have to check it out.

**Comment by willhseitz** [comment]
The Eltek devices (at least the ones we use) dont report standard sysLocation.0, so this is to customize where location can come from

**Comment by willhseitz** [comment]
I don't understand why there are both enexus.json and enexus_smartpacks.json files. Both show os:"enexus", so they are both using the same definition. Why are there separate test files?

**Comment by willhseitz** [comment]
I removed the enexus_smartpack2.json test data, because I wasnt sure if copying the location data from [this build ](https://travis-ci.com/librenms/librenms/jobs/260272702) is correct. 
However, that may be stepping on Issue #10282

**Comment by PipoCanaja** [comment]
Hi @willhseitz 
Looks pretty good overall. Could you restore the 2 files smartpacks2 ? The data provided by Travis is the correct one you should put in the Location fieled.

**Comment by kkrumm1** [comment]
> I removed the enexus_smartpack2.json test data, because I wasnt sure if copying the location data from [this build ](https://travis-ci.com/librenms/librenms/jobs/260272702) is correct.
> However, that may be stepping on Issue #10282

Any update to this?

**Comment by kkrumm1** [comment]
Going to close this for now. Feel free to re open when you are ready

**Pull request closed without merging**
