### PR TITLE
Add Ericsson IPOS SSR8020 support

### PR DESCRIPTION
**Pull request by rudybroersma**
This is a PR to implement preliminary support for Ericsson IPOS SSR 8020 router per community request:
https://community.librenms.org/t/please-add-new-os-ericsson-ipos-device-ssr-8010-ssr-8020/22300

- Add sysObject ID to discovery
- Add various sensors
- Add MIBs

I have yet to work on stuff like ARP/FDB/VLAN information, but I couldn't find developer documentation for those features.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Could you please rename the MIB files to match their exact internal name (so remove any extension etc etc) ?

**Comment by rudybroersma** [comment]
Sure, I'll do that tomorrow.

**Comment by PipoCanaja** [comment]
And concerning the use of PHP instead of YAML, I did not have time to review in detail yet, but please do your best to use as much YAML as possible, and only use PHP when this is impossible in YAML. That's a lot easier for maintenance than PHP code. 
If you have no choice, please add a short note explaining why, that will help the reviewers of your PR.

**Comment by rudybroersma** [comment]
Yaml is not possible I think, but ifyou feel I'm wrong please say so. The reason for this is as following:

This device has it's index not as the last column. It's index.rxpower, index.txpower, etc, etc.


```
ERICSSON-ROUTER-OPTICAL-TRANSCEIVER-MIB::eriRouterOpticalTransceiverMinAlarmValue.21.txpower = INTEGER: -7.999
ERICSSON-ROUTER-OPTICAL-TRANSCEIVER-MIB::eriRouterOpticalTransceiverMinAlarmValue.21.rxpower = INTEGER: -20.000
ERICSSON-ROUTER-OPTICAL-TRANSCEIVER-MIB::eriRouterOpticalTransceiverMinAlarmValue.21.temperature = INTEGER: -13.000
ERICSSON-ROUTER-OPTICAL-TRANSCEIVER-MIB::eriRouterOpticalTransceiverMinAlarmValue.21.laserBiasCurrent = INTEGER: 15.000
ERICSSON-ROUTER-OPTICAL-TRANSCEIVER-MIB::eriRouterOpticalTransceiverMinAlarmValue.21.vcc = INTEGER: 2.900

```

Fixed the MIBs as well

**Comment by PipoCanaja** [comment]
I'll have a look, I think it may be possible to load the table, and then use the subindexes to keep the one you want and skip the others.

**Comment by rudybroersma** [comment]
Alright, if you can give me an example please let me know, and I'll transform this to YAML.
There's some added complexity though.. I am combining data from two tables, and those 2 have a different layout.

The table eriRouterOpticalTransceiverPortTable contains information like slot number and port number, however, this is a 'normal' table with the index at the end. eg. eriRouterOpticalTransceiverCardSlot.22 = STRING: "6".

But then eriRouterOpticalTransceiverParamTable is the table with the index that's not at the end.

**Comment by PipoCanaja** [comment]
Could you provide me a complete snmprec file. The one you attached for the test does not seem to contain everything to validate the mecanism you describe above :
```
                {
                    "sensor_deleted": 0,
                    "sensor_class": "dbm",
                    "poller_type": "snmp",
                    "sensor_oid": ".1.3.6.1.4.1.193.218.2.50.1.2.1.3.10.2",
                    "sensor_index": "eriRouterOpticalTransceiverCurrentValueRxpower.10",
                    "sensor_type": "ericsson-ipos",
                    "sensor_descr": "Slot 6 / Port 8",
                    "group": "Optic Rx Power",
                    "sensor_divisor": 1000,
                    "sensor_multiplier": 1,
                    "sensor_current": -2.973,
                    "sensor_limit": null,
                    "sensor_limit_warn": null,
                    "sensor_limit_low": null,
                    "sensor_limit_low_warn": null,
                    "sensor_alert": 1,
                    "sensor_custom": "No",
                    "entPhysicalIndex": null,
                    "entPhysicalIndex_measured": null,
                    "sensor_prev": null,
                    "user_func": null,
                    "rrd_type": "GAUGE",
                    "state_name": null
                },
```

**Comment by rudybroersma** [comment]
[ericssonipos.snmpwalk.txt](https://github.com/librenms/librenms/files/14157980/ericssonipos.snmpwalk.txt)

Here it is

**Comment by PipoCanaja** [comment]
I can replicate your device indeed. Will see if I find a way to simplify and YAMLize it.

**Comment by PipoCanaja** [comment]
Managed to YAMLize the Temperature : 
image

```
mib: ERICSSON-ROUTER-ENVMON-MIB:ERICSSON-ROUTER-CPU-METER-MIB:ERICSSON-ROUTER-OPTICAL-TRANSCEIVER-MIB
modules:
    os:
        version: SNMPv2-MIB::sysDescr.0
    processors:
        data:
            -
                oid: eriRouterCpuMeterMIBObjects
                value: eriRouterCpuMeterFiveMinuteAvg
                num_oid: '.1.3.6.1.4.1.193.218.2.6.1.3.{{ $index }}'
                descr: '5 minute average'
            -
                oid: eriRouterCpuMeterMIBObjects
                value: eriRouterCpuMeterFiveMinutePeak
                num_oid: '.1.3.6.1.4.1.193.218.2.6.1.6.{{ $index }}'
                descr: '5 minute peak'
    sensors:
        pre-cache:
            data:
                -
                    snmp_flags: '-OQUsbe'
                    oid:
                        - eriRouterOpticalTransceiverPortTable
                        - eriRouterOpticalTransceiverCardSlot
                        - eriRouterOpticalTransceiverPort
        state:
            data:
                -
                    oid: eriRouterFanStatusTable
                    num_oid: '.1.3.6.1.4.1.193.218.2.4.1.1.1.4.{{ $index }}'
                    descr: eriRouterFanDescr
                    value: eriRouterFanStatus
                    states:
                        - { value: 1, descr: Normal,  graph: 1, generic: 0 }
                        - { value: 2, descr: Failed,  graph: 1, generic: 2 }
                        - { value: 3, descr: Absent,  graph: 1, generic: 0 }
                        - { value: 4, descr: Unknown, graph: 1, generic: 3 }
                -
                    oid: eriRouterPowerStatusTable
                    num_oid: '.1.3.6.1.4.1.193.218.2.4.1.2.1.4.{{ $index }}'
                    descr: eriRouterPowerDescr
                    value: eriRouterPowerStatus
                    states:
                        - { value: 1, descr: Normal,  graph: 1, generic: 0 }
                        - { value: 2, descr: Failed,  graph: 1, generic: 2 }
                        - { value: 3, descr: Absent,  graph: 1, generic: 0 }
                        - { value: 4, descr: Unknown, graph: 1, generic: 3 }
        fanspeed:
            data:
                -
                    oid: EriRouterFanSpeed
                    value: eriRouterFanSpeedCurrent
                    num_oid: '.1.3.6.1.4.1.193.218.2.4.1.5.1.3.{{ $index }}'
                    descr: eriRouterFanUnitDescr
        temperature:
            data:
                -
                    oid: eriRouterEntityTempSensorTable
                    value: eriRouterEntityTempCurrent
                    num_oid: '.1.3.6.1.4.1.193.218.2.4.1.6.1.3.{{ $index }}'
                    descr: eriRouterEntityTempDescr
                -
                    oid: eriRouterOpticalTransceiverParamTable
                    value: eriRouterOpticalTransceiverCurrentValue
                    high_limit: eriRouterOpticalTransceiverMaxAlarmValue
                    warn_limit: eriRouterOpticalTransceiverMaxWarningValue
                    low_limit: eriRouterOpticalTransceiverMinAlarmValue
                    low_warn_limit: eriRouterOpticalTransceiverMinWarningValue
                    snmp_flags: '-OQUsbe'
                    num_oid: '.1.3.6.1.4.1.193.218.2.50.1.2.1.3.{{ $index }}'
                    index: 'opt{{ $index }}'
                    user_func: intval
                    group: 'Test Optic Temperature'
                    divisor: 1000
                    descr: 'Slot {{ $eriRouterOpticalTransceiverCardSlot:0 }} / Port {{ $eriRouterOpticalTransceiverPort:0 }}'
                    skip_values:
                        -
                            oid: eriRouterOpticalTransceiverParamType
                            op: '!='
                            value: 3
```

Please test it in your environnement, and starting from this, you should be able to do a few more using the same tricks.

**Comment by PipoCanaja** [comment]
The key elements : 
- `snmp_flags: '-OQUsbe'` to force the index to be purely numeric
- `{{ $eriRouterOpticalTransceiverCardSlot:0 }}` : Using the `:0` to use only the 1st number of the index to search eriRouterOpticalTransceiverCardSlot (which means, remove the '3' of 'temperature' in the original index)
- skip the entry if eriRouterOpticalTransceiverParamType is different from '3' of 'temperature'

**Comment by rudybroersma** [comment]
Awesome, thank you very much. I'll work on this!
I'll close this PR.

**Comment by rudybroersma** [comment]
@PipoCanaja For some reason your example doesn't fully work on my system. Did a copy/paste of your YAML file. The sensors are detected, but the description is missing the card and slot number (just says  'Slot / Port'). I also get this error when running discovery:

Slot  / Port: Cur 30, Low: -13, Low Warn: -8, Warn: 85, High: 88
.YamlDiscovery: No variable available to replace eriRouterOpticalTransceiverCardSlot:0 index: 22.3  
YamlDiscovery: No variable available to replace eriRouterOpticalTransceiverPort:0 index: 22.3 

I was able to fix this by adding eriRouterOpticalTransceiverCardSlot and eriRouterOpticalTransceiverPort to pre-cache OIDs, but it's weird to me that this worked on your system but not on mine.

**Comment by PipoCanaja** [comment]
Interesting. I'll doublecheck. The goal to avoid the variables in precache is to speed things up. The table is supposed to be already loaded.

**Pull request closed without merging**
