### PR TITLE
Updated the map for showing connected devices

### PR DESCRIPTION
**Pull request by laf**
This uses the links table which I've updated to support device_ids so that you can click the devices on the map to be taken to the relevant screen.

Adds a global map to show all connected devices broken down by location and has varying link sizes based on link speeds.

Currently running on work install so give it 12 hours for it to update all the links to use device_ids and I can then test it properly on a bigger scale.

### CODE REVIEW

**Comment by laf** [comment]
I'm not happy with this at the moment. Existing links in the database aren't re-discovered so the new device_id columns only work for new devices - I believe this is fixable.

Don't merge just yet.

**Comment by laf** [comment]
This is now all done and tested :) Can't show the map as I'd have to blank out the hostnames so it would then be a mess!

**Comment by f0o** [comment]
Testing it on my install today

**Comment by laf** [comment]
All updated so map only shows if links exist. Also converted to use subtree now that lib/ directory is in place.

**Pull request closed without merging**
