### PR TITLE
changed check_mk service from xinetd to systemd

### PR DESCRIPTION
**Pull request by lwillek**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by lwillek** [comment]
Please add Label "Documentation"

Proxmox changed from inetd using systemd now, so I adapted the documentation

**Comment by laf** [comment]
Thanks for this.

Would you be able to put the systemd docs in as well as the xinetd so both exist and just indicate which version of proxmox uses which.

**Comment by lwillek** [comment]
puh, systemd is out for a while now, but I understand the intention of your question. Let me rewrite the doc, ie. by adding a "xinetd section" for older proxmox systems, or for people using xinetd.

**Comment by laf** [comment]
Thank you, it's to cover older installs as well so that would be awesome if you can.

**Comment by laf** [comment]
image

**Pull request merged**
