### PR TITLE
Protocol filter for Routing Table View

### PR DESCRIPTION
**Pull request by SourceDoctor**
Protocol filter for Routing Table View ...

image

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @SourceDoctor 
I find it a little confusing with the checkboxes all in a row. 
May be just 3 links like this : 
```
v4 | v6 | both
```
what do you think ?

**Comment by SourceDoctor** [comment]
@PipoCanaja  what about a selection Box?

- all Protocols
- only IPv4
- only IPv6

**Comment by PipoCanaja** [comment]
I would say yes for the dropdown menu. Let see how it comes into place.

**Comment by SourceDoctor** [comment]
@PipoCanaja 
design changed
image

**Comment by SourceDoctor** [comment]
ok Travis fails, but it's the same failure like on master. So not my fault ;-)
For details take a look here: [https://github.com/librenms/librenms/commit/20bcbfd5915c1d508581b790e14fc53788513687](https://github.com/librenms/librenms/commit/20bcbfd5915c1d508581b790e14fc53788513687)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
