### PR TITLE
Update Windows Icon

### PR DESCRIPTION
**Pull request by RobsanInc**
Update windows icon.

### CODE REVIEW

**Comment by f0o** [comment]
What's the license on the picture?

**Comment by RobsanInc** [comment]
There isn't a license, I made the logo specifically for LibreNMS.

**Comment by SaaldjorMike** [comment]
Just a thought: shouldn't this be the blue logo instead of the multi color logo?
Seems like they use the multi color logo as a general Microsoft logo and the blue one as a Windows logo.

**Comment by laf** [comment]
Closing this down. If the license gets sorted then please submit a new PR.

**Pull request closed without merging**
