### PR TITLE
thecityofguanyu/add telco systems os

### PR DESCRIPTION
**Pull request by thecityofguanyu**
Add support for Telco Systems BiNOS and BiNOX OSs, including copious MIB files.

### CODE REVIEW

**Comment by laf** [comment]
I can see quite a few of these mibs are standard ones of ours. Unless you actively use the mibs I'd remove them imho.

**Comment by thecityofguanyu** [comment]
@laf 

>I can see quite a few of these mibs are standard ones of ours. Unless you actively use the mibs I'd remove them imho.

Removed the MIBs.

Also fixed a line in `includes/discovery/sensors/temperatures/binos.inc.php`

**Comment by laf** [comment]
You've got some blank } else {, any reason why:

```php
+    else {
 +
 +    }
```

**Comment by thecityofguanyu** [comment]
@laf 

>You've got some blank } else {, any reason why:

This was originally built as one OS rather than two, so that's probably where those came from. I must have just missed those empty elses when cleaning up after splitting into two OSs.

This is fixed.

**Pull request merged**
