### PR TITLE
Add Icon / Image for dd-wrt (32x32)

### PR DESCRIPTION
**Pull request by arrmo**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [ X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Where would this be used, I don't see an os definition for it nor does distro return dd-wrt.

**Comment by arrmo** [comment]
Ahhh - gotcha. I updated distro locally, can push/pull that also. 

Thanks!

**Comment by arrmo** [comment]
BTW, here is my addition to distro,
`  if [ "`uname -a | awk '{print $(NF)}'`" = "DD-WRT" ] ; then
    DIST="dd-wrt"
  fi
`

Arrgh ... why do line endings not work inside "code"?!?! Pasted below, not in code,
  if [ "`uname -a | awk '{print $(NF)}'`" = "DD-WRT" ] ; then
    DIST="dd-wrt"
  fi

**Comment by laf** [comment]
Yeah we would need the pull request to librenms/librenms-agent before we can merge this.

**Comment by arrmo** [comment]
OK, will send that one - NP! Just wasn't sure how to do it, given it's a different repository.

Thanks!

**Comment by arrmo** [comment]
Added PR to librenms-agent, yell if any issues. Thanks!

**Pull request merged**
