### PR TITLE
Option to filter Oxidized groups

### PR DESCRIPTION
**Pull request by martinberg**
Currently not possible to filter what is sent to Oxidized, either something is tagged with a group, sent with a default group or no group at all. This adds devices to Oxidized that shouldn't be there.
Can add to the docs if you think this is something that somebody else would find useful.

To test this add 
`$config['oxidized']['ignore_groups'] = array('default','fallback','whatevergroupname');` 
to 
`config.php`

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Seems reasonable, but you will need to define the setting in config_definitions.json.  You can add it to the web ui here too.  You will also need to add translations in resources/lang/en/settings.php

**Comment by martinberg** [comment]
Regarding the conflict I have detached at 21.6.0 and therefore don't have https://github.com/librenms/librenms/commit/50dd6c1685c6725309d0558a841c294baf103aa2 for `mix-manifest.json`. Not sure how to handle the conflict. 
Advice accepted happily :)

**Comment by Jellyfrog** [comment]
Neeed to rebase on master

**Review by murrant — APPROVED** [review]
LGTM, nice work

**Review by murrant — APPROVED** [review]
LGTM, nice work :)

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
