### PR TITLE
Add php-fpm graphs to application overview (#5912)

### PR DESCRIPTION
**Pull request by florianbeer**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by florianbeer** [comment]
Just found out that the mouseover graphs don't show up correctly. No clue why.
@laf help, please?

**Comment by VVelox** [comment]
The mouse over does not work as from what I can tell that page does not like the way it is named.

Was just mucking around with that here with fail2ban and it looks like the graph would best be renamed to php-fpm_stats then just include 'stats' in the array instead of ''.

**Comment by florianbeer** [comment]
Great! Makes sense.
How/where do I rename the graph?

**Comment by laf** [comment]
That does indeed seem to the best approach.

**Comment by VVelox** [comment]
mv html/includes/graphs/application/php-fpm.inc.php html/includes/graphs/application/php-fpm_stats.inc.php

Then update html/pages/device/apps/php-fpm.inc.php and html/pages/apps.inc.php to reflect that the graph has been renamed from php-fpm to php-fpm_stats.

Just did that here and it fixes the issue.

**Comment by florianbeer** [comment]
Done. Thanks for the assistance!

**Comment by VVelox** [comment]
Null sheen!

**Comment by florianbeer** [comment]
Thanks for creating this whole php-fpm thing, chummer!

**Pull request merged**
