### PR TITLE
Fix discovery and pooling Racom Ray2

### PR DESCRIPTION
**Pull request by Martin22**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 13553`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Ray2's discovery and pooling haven't been working for almost a year. Old data is no longer displayed, so there is nothing to lose.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
So they fixed this in newer firmware?

**Comment by Jellyfrog** [comment]
Still will drop support for older firmware(?) versions in that case, which is why I ask.
But newer versions won't work without it, so it's a bit 50/50

**Comment by Martin22** [comment]
> Still will drop support for older firmware(?) versions in that case, which is why I ask. But newer versions won't work without it, so it's a bit 50/50

I haven't tested the older firmware, we don't use old firmware, we don't want to have buggy versions on the network. I'll try it and possibly edit the code.

**Comment by Martin22** [comment]
The current version of LibreNMS does not detect Racom Ray2 with older firmware. The change will not affect older firmware versions as it does not work anyway.

Please approve and I will try to fix the detection of older firmware.

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
