### PR TITLE
Fix junos rpm probes

### PR DESCRIPTION
**Pull request by dagbdagb**
When discovering a Juniper SRX with an RPM probe configured, I end up with the following sensors in the database:

```
MariaDB [librenms]> select sensor_class,sensor_oid,sensor_descr,`group`,entPhysicalIndex,entPhysicalIndex_measured from sensors where sensor_id > 1270;

+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+------------+------------------+---------------------------+

| sensor_class | sensor_oid                                                                                                                                       | sensor_descr                              | group      | entPhysicalIndex | entPhysicalIndex_measured |

+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+------------+------------------+---------------------------+

| state        | .1.3.6.1.4.1.2636.3.1.15.1.8.8.1.1.0                                                                                                             | PIC: 8xGE,8xGE SFP Base PIC @ 0/0/*       | NULL       | NULL             | NULL                      |

| state        | .1.3.6.1.4.1.2636.3.1.15.1.8.9.1.0.0                                                                                                             | Routing Engine                            | NULL       | NULL             | NULL                      |

| count        | .1.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.0                                                                                                            | Node 0 FPC 0 SPU 0 Flow Count             | Sessions   | NULL             | NULL                      |

| temperature  | .1.3.6.1.4.1.2636.3.1.13.1.7.9.1.0.0                                                                                                             | Routing Engine                            | NULL       | NULL             | NULL                      |

| temperature  | .1.3.6.1.4.1.2636.3.60.1.1.1.1.8.526                                                                                                             | ge-0/0/15 Temperature                     | NULL       | 526              | ports                     |

| loss         | .1.3.6.1.4.1.2636.3.50.1.2.1.24.100.97.103.98.46.117.100.112.116.101.115.116.46.99.117.114.114.101.110.116.84.101.115.116                        | dagb.udptest.currentTest Probe Loss       | RPM Probes | dagb.udptest.cur | probes                    |

| loss         | .1.3.6.1.4.1.2636.3.50.1.2.1.30.100.97.103.98.46.117.100.112.116.101.115.116.46.108.97.115.116.67.111.109.112.108.101.116.101.100.84.101.115.116 | dagb.udptest.lastCompletedTest Probe Loss | RPM Probes | dagb.udptest.las | probes                    |

| loss         | .1.3.6.1.4.1.2636.3.50.1.2.1.21.100.97.103.98.46.117.100.112.116.101.115.116.46.97.108.108.84.101.115.116.115                                    | dagb.udptest.allTests Probe Loss          | RPM Probes | dagb.udptest.all | probes                    |

+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+------------+------------------+---------------------------+

8 rows in set (0.000 sec)
```

The first 5 OIDs are pollable, the last three are not. The issue appears to be that there is some mixup during discovery with what constitutes the probe OID and the probe description.

The pollable OIDs are:

```
JUNIPER-SMI::jnxRpmMibRoot.1.2.1.4.4.100.97.103.98.7.117.100.112.116.101.115.116
JUNIPER-SMI::jnxRpmMibRoot.1.2.1.4.4.100.97.103.98.7.117.100.112.116.101.115.116.1 = Gauge32: 100000000
JUNIPER-SMI::jnxRpmMibRoot.1.2.1.4.4.100.97.103.98.7.117.100.112.116.101.115.116.2 = Gauge32: 100000000
JUNIPER-SMI::jnxRpmMibRoot.1.2.1.4.4.100.97.103.98.7.117.100.112.116.101.115.116.4 = Gauge32: 78706199
```

The yaml in question (includes/definitions/discovery/junos.yaml) states:
```
       loss:
            data:
                -
                    oid: jnxRpmResultsSummaryTable
                    value: jnxRpmResSumPercentLost
                    num_oid: '.1.3.6.1.4.1.2636.3.50.1.2.1.{{ $index_string }}'
                    entPhysicalIndex: '{{ $index }}'
                    group: RPM Probes
                    entPhysicalIndex_measured: 'probes'
                    descr: '{{ $index }} Probe Loss'
                    index: 'jnxRpmResSumPercentLost.{{ $index }}'
```

With my SRX 340, running Junos 20.4R3-S4.8, I need to modify num_oid to append $index, not $index_string. With this change, my RPM probes return actual probe data.

Also see [this](https://community.librenms.org/t/juniper-loss-not-polling-correctly/16628) for another report regarding this issue.

I need to create a sanitized environment before I can provide test data. Unsure when I can allocate time for this.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [N/A ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I wonder if this is an issue with loaded MIBs...

**Comment by murrant** [comment]
@dagbdagb looks like you need to update your fork and rebase.

**Comment by dagbdagb** [comment]
> @dagbdagb looks like you need to update your fork and rebase.

Will do.

**Comment by dagbdagb** [comment]
Closing this. Needs rework. See ticket #14666

**Pull request closed without merging**
