### PR TITLE
Oxidized GUI tweaks

### PR DESCRIPTION
**Pull request by cjwbath**
Improve the Oxidized web interface:
- Add device links from the results of a config search
- Use a bootgrid for the nodes list

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
Nice work it’s appreciated

**Comment by kkrumm1** [comment]
Can you post a screenshot of the changes?

**Comment by cjwbath** [comment]
Screenshots as requested:
image

image

**Comment by PipoCanaja** [comment]
@kkrumm1 if it is OK with you, you can merge it anytime.

**Comment by kkrumm1** [comment]
Thank you LGTM

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
