### PR TITLE
Initial Release, wireless sensor support for Openwrt

### PR DESCRIPTION
**Pull request by arrmo**
This is a first release of Wireless Sensor support for Openwrt - supporting clients and frequency (Type, as defined in LibreNMS documentation). Scripts on the client (Openwrt) side set up the needed information, of the format (textual OID),
`NET-SNMP-EXTEND-MIB::nsExtendOutputFull."Type-interface"
`

The php code here detect this, and creates the Wireless Sensors. 

Will add more Sensors, but want to make sure this is all looking OK before I go too far 😆.

BTW, is there some place that it would make sense to store the client scripts (just to share with others)? I have them working for OpenWrt, and also Asuswrt-Merlin (separate PR, as a different OS).

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@arrmo the script would go on https://github.com/librenms/librenms-agent

**Comment by murrant** [comment]
You'll need some docs somewhere too.

**Comment by arrmo** [comment]
Hi,

Sure, no issues adding the scripts (to agents), and as well docs - that makes complete sense. BTW, to explain, here is what I added - by doing it this way, it makes the php code in LibreNMS quite small, and a generic approach that makes adding new sensors straightforward.

On the client, here is a snapshot from my snmp.conf file,
```
exec .1.3.6.1.4.1.2021.7890.1 distro /etc/librenms/distro
exec .1.3.6.1.4.1.2021.7890.2 hardware /etc/librenms/hardware
extend  interfaces /bin/cat /etc/librenms/wlInterfaces.txt
extend  clients-wlan0 /etc/librenms/wlClients.sh wlan0
extend  clients-wlan1 /etc/librenms/wlClients.sh wlan1
extend  clients-wlan /etc/librenms/wlClients.sh
extend  frequency-wlan0 /etc/librenms/wlFrequency.sh wlan0
extend  frequency-wlan1 /etc/librenms/wlFrequency.sh wlan1
extend  rate-tx-wlan0-min /etc/librenms/wlRate.sh wlan0 tx min
extend  rate-tx-wlan0-avg /etc/librenms/wlRate.sh wlan0 tx avg
extend  rate-tx-wlan0-max /etc/librenms/wlRate.sh wlan0 tx max
extend  rate-tx-wlan1-min /etc/librenms/wlRate.sh wlan1 tx min
extend  rate-tx-wlan1-avg /etc/librenms/wlRate.sh wlan1 tx avg
extend  rate-tx-wlan1-max /etc/librenms/wlRate.sh wlan1 tx max
extend  rate-rx-wlan0-min /etc/librenms/wlRate.sh wlan0 rx min
extend  rate-rx-wlan0-avg /etc/librenms/wlRate.sh wlan0 rx avg
extend  rate-rx-wlan0-max /etc/librenms/wlRate.sh wlan0 rx max
extend  rate-rx-wlan1-min /etc/librenms/wlRate.sh wlan1 rx min
extend  rate-rx-wlan1-avg /etc/librenms/wlRate.sh wlan1 rx avg
extend  rate-rx-wlan1-max /etc/librenms/wlRate.sh wlan1 rx max
extend  noise-floor-wlan0 /etc/librenms/wlNoiseFloor.sh wlan0
extend  noise-floor-wlan1 /etc/librenms/wlNoiseFloor.sh wlan1
extend  snr-wlan0-min /etc/librenms/wlSNR.sh wlan0 min
extend  snr-wlan0-avg /etc/librenms/wlSNR.sh wlan0 avg
extend  snr-wlan0-max /etc/librenms/wlSNR.sh wlan0 max
extend  snr-wlan1-min /etc/librenms/wlSNR.sh wlan1 min
extend  snr-wlan1-avg /etc/librenms/wlSNR.sh wlan1 avg
extend  snr-wlan1-max /etc/librenms/wlSNR.sh wlan1 max
```

So the name used is always of the format Type-Direction-Interface-Metric,
- Type, matches to LibreNMS type names (exactly)
- Direction, if applicable, for Tx/Rx for example
- Interface, matching to the interface on the client (and "interfaces" returns a mapping from interface to a desired name in LibreNMS). BTW, if just "wlan" ... that is summed across all interfaces, like clients for example
- Metric, for items that are per-station type (e.g. SNR ... give a min, max and avg).

Clear as mud? The agent really just adds the Wireless Sensor capability to devices that don't have it built in, so it can be used across a range of devices. Oh, and BTW, by using extend (vs. exec), the php code doesn't have to include hard-coded OID numbers ... rather, it can just build the text string (making for less code as well).

Thanks! And do yell if you see things to improve.

**Comment by arrmo** [comment]
Hi,

Do you want the scripts added to https://github.com/librenms/librenms-agent/tree/master/snmp? And as there are a few of them, put them inside a subdirectory (e.g. Openwrt)?

On the documentation, where / how to capture this?

Thanks!

**Comment by arrmo** [comment]
FYI, added a PR for the scripts,
https://github.com/librenms/librenms-agent/pull/309

Just not sure how you would like the documentation captured - just let me know if you would.

Thanks!

**Comment by murrant** [comment]
In the docs folder.

**Comment by arrmo** [comment]
Documentation added to the commit. Thanks!

**Comment by arrmo** [comment]
OK, I think all the pieces are in place - I just have a missing email on one commit to librenms-agent, can't figure out how to fix that (so think it thinks the CLA is not signed ... but it is!).

Thanks!

**Comment by arrmo** [comment]
OK, cleaned up 😆. Docs and LibreNMS code updates attached here, and scripts stored in librenms-agent (https://github.com/librenms/librenms-agent/pull/314).

Thanks!

**Comment by pentium90** [comment]
Thanks a lot! It's really working. Some additional steps were needed here:

Openwrt device was not discovered correctly:

Create this script and make it executable, also extend /etc/config/snmpd: 
[https://community.librenms.org/t/distro-script-for-openwrt/5079/2](https://community.librenms.org/t/distro-script-for-openwrt/5079/2)
 
Librenms machine running Debian, snmpwalk example from doc didn't work:

Add add contrib non-free to /etc/apt/sources.list:
[https://wiki.debian.org/SourcesList#sources.list_format](https://wiki.debian.org/SourcesList#sources.list_format)

run apt-get update & apt-get install snmp-mibs-downloader

**Comment by arrmo** [comment]
> Thanks a lot! It's really working.

NP! And glad it's working for you. I do find it very handy / nice. Copying my same code also to Asuswrt-Merlin, once this one gets in to GitHub.

> Openwrt device was not discovered correctly:

Yes, agreed! Distro needs to be there, for Openwrt to work in general. I didn't include that part, as distro is documented elsewhere - rather, I was just trying to add the Wireless Sensors on top here. But you are correct, make sure Openwrt / distro is working first 😄.

> run apt-get update & apt-get install snmp-mibs-downloader

Yes, I had to have this in place already for general debugging (i.e. was already part of my base install, but needed as you say). Also, this is only for looking at things in snmpwalk, as you note.

**Comment by arrmo** [comment]
Hi,

Not sure if anything is still open here? No issues if not, just not sure if this is waiting on something from me 😄.

Thanks!

**Comment by murrant** [comment]
Thanks, the docs look good, but they should probably be under doc/Support/Device-Notes/

**Comment by arrmo** [comment]
> Thanks, the docs look good, but they should probably be under doc/Support/Device-Notes/

Moved!

**Comment by murrant** [comment]
@arrmo you have some code style issues that need to be resolved.  I updated the json for you.

**Comment by arrmo** [comment]
> @arrmo you have some code style issues that need to be resolved. I updated the json for you.

Thanks - appreciate it!

**Comment by arrmo** [comment]
Hi,

Sorry, I may have misunderstood 😆. I saw you updated this, figured the code was fine then ... or am I supposed to do something with it now? My apologies if this is sitting, waiting for me - I may have gotten your comment wrong.

Thanks!

**Comment by murrant** [comment]
Travis CI is failing because your code style is not correct.  You need reformat your code to be correct.
You can see the issues by running `./lnms dev:check style`

**Comment by arrmo** [comment]
> You can see the issues by running `./lnms dev:check style`

Will do, thanks! Just ran it, it's all True/False => true/false, and tab vs. spaces. Will correct and update the push. Appreciate it!

**Comment by arrmo** [comment]
Updated, cleaned up code style - at least it says success now on my side 😄.

Thanks!

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-66-release-changelog-july-2020/12953/1

**Pull request merged**
