### PR TITLE
Device dell idrac Add dicovery for disk status

### PR DESCRIPTION
**Pull request by tocks53**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by tocks53** [comment]
[drac.json.txt](https://github.com/librenms/librenms/files/4601073/drac.json.txt)

**Comment by murrant** [comment]
@tocks53 we need both the snmprec and json (preferably added to the pull request)

**Comment by murrant** [comment]
Also, the reason you have a failure is because you have indented with tabs instead of spaces.

**Comment by tocks53** [comment]
Thanks for your reply @murrant .
But it's my first pr in giuhub, and i understand nothing in github

When i clic en file changed and search tabs instead, i don't find, there are only space

when i can generate snmprec  ?

I execute  ./scripts/save-test-data.php -o drac
this generate a file in Saved to /opt/librenms/tests/data/drac.json

after this i run : ./scripts/pre-commit.php --db --snmpsim

but i have error :


Starting snmpsim listening on 127.1.6.2:1162...

In bootstrap.php line 62:

  SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'


Style check skipped.
Lint check skipped.
Tests ok, submit away :)
$

but no new file in tests/snmpsim/

**Comment by tocks53** [comment]
[drac.snmprec.txt](https://github.com/librenms/librenms/files/4605695/drac.snmprec.txt)

**Comment by PipoCanaja** [comment]
@tocks53 Please add the file directly to the PR, and check the indentation of the YAML file. Currently we cannot edit this PR for you.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/dell-idrac-sensors-physical-disks-state/12452/3

**Comment by Jellyfrog** [comment]
Closing due to inactivity, feel free to reopen!

**Pull request closed without merging**
