### PR TITLE
Basic recurring maintenance

### PR DESCRIPTION
**Pull request by FTBZ**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

# Basic recurring maintenance

You can add a daily maintenance or a weekly based on specific day (no monthly/yearly support at this time). It's using the same popup and extend the database schema, so it's needing deep tests.

The code was made by a colleague and not by me, special thanks.

screen shot 2016-12-21 at 15 04 06

screen shot 2016-12-21 at 15 03 53

Fixes: #4480

### CODE REVIEW

**Comment by laf** [comment]
Before we look at the code, what's the reason to keep dates and times separate? Can we not keep it together so we ask users for yyyy-mm-dd hh:mm?

How does alerts know this is a repeat maintenance? I'd have thought includes/alerts.inc.php would need updating as well.

**Comment by schubling** [comment]
Hello @laf
we've separated date and time because the end date of a recurring maintenance could be empty so we can imagine to have a reccuring maintenance set from today until no end done from and to a specific time (end time must mandatory be set).
New columns have been added on database to the "alert_scheduling" table (recurring => bool,  tinyint(1) unsigned NOT NULL DEFAULT '0', `start_recurring_dt` date NOT NULL DEFAULT '0000-00-00', `end_recurring_dt` date DEFAULT NULL, `start_recurring_hr` time NOT NULL DEFAULT '00:00:00', `end_recurring_hr` time NOT NULL DEFAULT '00:00:00', `recurring_day` varchar(15) DEFAULT NULL) so we do not alter how it works actually, we only add new features.

Yes we've also modified the alert.inc.php file in order to check also the recurring maintenance (only the SQL request).

**Comment by laf** [comment]
Ok, let us know when the alerts file is uploaded :)

**Comment by laf** [comment]
Any new news on the missing file?

**Comment by FTBZ** [comment]
Sorry, I was in holidays. I'm testing it now.

**Comment by laf** [comment]
Will test this in a couple of days unless someone else does.

I've got some patches locally already though as an FYI.

**Comment by laf** [comment]
Ok, made some updates including fixing the sql schema files.

Once it's gone through checks I'll merge it.

image

**Comment by schubling** [comment]
Great ! Thanks for the updates and the validation ;-)

**Pull request merged**
