### PR TITLE
correct divisor in discovery definition vertiv-pdu.yaml

### PR DESCRIPTION
**Pull request by woidi**
VERTIV-V5-MIB states UNITS "decivolts (rms)" for pduPhaseVoltage

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @woidi 
Seems that you need to re-run the test-data computation, to correct the errors we have now in the non-regression tests. 
Bye

**Comment by laf** [comment]
@woidi I've fixed the test data in your branch (hopefully :D), we need you to sign the CLA as per the comment further up the page.

**Review by laf — APPROVED** [review]
LGTM

**Comment by laf** [comment]
Boom, merged in. Thanks @woidi for contributing this fix.

**Pull request merged**
