### PR TITLE
Teleste Luminato ports & qam/asi output sensors & yaml

### PR DESCRIPTION
**Pull request by Npeca75**
Teleste Luminato

added bitrate sensor for Luminato Transfer values
added discovery for output modules (QAM/AsiOut). Hopefully should work for IP MUX module.
fixed ethernet port state & speed
added CPU graph in overview
fixed yaml for zero temperature readout (lumnato 4x4 sw20.x)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.
- [x] Bitrate sensor for Luminato Transfer
- [x] Luminato port discovery/polling, done
- [x] Luminato YAML
- [x]  test on v5.2.34, v9.2.8, v10.4.14, v20.8.23
- [x] Test in Main CATV headend
- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Npeca75** [comment]
wrong port speed and status
lnms1
lnms2

**Comment by Npeca75** [comment]
working sensors
LQM-C & LDM-C
lnms1

**Comment by Npeca75** [comment]
LAS-D card
lnms2

**Comment by Npeca75** [comment]
correct port speed & status
lnms3

**Comment by Npeca75** [comment]
propper sensors naming
lnms1
lnms2

**Review by laf — APPROVED** [review]
I've been away for a while so team, take my review with a pinch of salt but LGTM

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Pull request merged**
