### PR TITLE
Icecast, Opensips and Voip monitor Application

### PR DESCRIPTION
**Pull request by avinash403**
# Icecast, Opensips and VoIP Monitor Applications

Icecast: CPU Load, Used Memory and Open Files graphs
Opensips: Load Average, total vs used memory, and Open Files graphs
VoIP Monitor: CPU Load, Used Memory and Open Files  graphs

Agent 
https://github.com/librenms/librenms-agent/pull/331

DO NOT DELETE THE UNDERLYING TEXT
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by avinash403** [comment]
Test data for icecast and opensips of the applications have added. I am unable to get any data for voipmon using the instructions given in the doc

Scenario:
machine 1 has Icecast as application - it works well with no issue
machine 2 has mysql, opensips and voipmon as application - using the instructions given in the doc, it only extracts test data for mysql and opensips but not for voipmon. I have trying disabling mysql on the UI but it gets turned ON automatically

Any guidance will be appreciated

**Comment by avinash403** [comment]
maintainers, any update?

**Review by Jellyfrog — APPROVED** [review]

**Comment by SourceDoctor** [comment]
Travis fails through this ...

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
