### PR TITLE
Laravel 8.x Shift

### PR DESCRIPTION
**Pull request by Jellyfrog**
This pull request includes the changes for upgrading to Laravel 8.x. Feel free to commit any additional changes to the `shift-32411` branch.

**Before merging**, you need to:

- Checkout the `shift-32411` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 8
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 streamlined the _Exception Handler_ into a single `register` method to make it easier to add custom logic around rendering or reporting errors within your application.

While this change is not required, Shift recommends comparing yours against the [Laravel 8.x version](https://github.com/laravel-shift/laravel-8.x/blob/master/app/Exceptions/Handler.php) as an opportunity to reduce code and be fully up-to-date.

**Comment by Jellyfrog** [comment]
:warning: The `RouteServiceProvider` no longer prefixes the controller namespace by default in Laravel 8. While you may still set this property, you are encouraged to register your routes using static `::class` references.

You may automate the conversion to static class references using the [Shift Workbench](https://laravelshift.com/workbench).

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 introduced class based factories. Shift [automated this change](https://github.com/librenms/librenms/pull/12073/commits/0897c7621154c0968c98c4e270638e3745c9dc0f?w=1). However, if you were using a community package for factories or other custom code, you should review your factories for additional changes.

If you encounter an issue, you may revert this commit and temporarily install the [laravel/legacy-factories](https://github.com/laravel/legacy-factories) package. You may then automate the conversion to class based factories using the [Shift Workbench](https://laravelshift.com/workbench).

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 added a `uuid` column to the `failed_jobs` table to support the new [job batching](https://laravel.com/docs/8.x/queues#job-batching) features.

If your application is currently using the `failed_jobs` table, you may generate a custom migration for this command by running:

```sh
php artisan make:migration AddUuidToFailedJobsTable
```

Then copy and paste the contents from [Shift's `AddUuidToFailedJobsTable` class](https://github.com/laravel-shift/laravel-8.x/blob/master/database/migrations/2020_09_08_000000_add_uuid_to_failed_jobs_table.php).

**Comment by Jellyfrog** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables. This is an effort to make [maintaining your config files easier](https://jasonmccreary.me/articles/maintaining-laravel-config-files/).

You should [review this commit](https://github.com/librenms/librenms/pull/12073/commits/d9d8ce284225808b73d58a7ac70bf8dc142d6916?w=1) for any additional customizations. If you have a lot of customizations, you may wish to undo this commit with `git revert` and make these [config file changes](https://github.com/laravel/laravel/compare/6.x...master#diff-ea70a5765dbab9fd8032c1d439521db8) manually.

**Comment by Jellyfrog** [comment]
:information_source: Shift [updated your dependencies](https://github.com/librenms/librenms/pull/12073/commits/b46af4604c76e3e168d670451581c9ecca1a3935?w=1) for Laravel 8. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 8.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling package incompatibilities.

**Comment by Jellyfrog** [comment]
:warning: The paginator now uses [Tailwind](https://tailwindcss.com/) for its default styling in Laravel 8. If you wish to continue using Bootstrap, you should add the following snippet to the `boot` method of your `AppServiceProvider`:

```php
\Illuminate\Pagination\Paginator::useBootstrap();
```

**Comment by Jellyfrog** [comment]
:tada: Congratulations, you're now running the latest version of Laravel.

The following _Shifts_ may be used ensure your application is fully upgraded and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automates many of the suggestions found by the [_Laravel Linter_](https://laravelshift.com/opinionated-laravel-way-shift) and other _Shifts_.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and unit tests for your application to give you a head start on testing.

You may run these _Shifts_ and stay upgraded forever as well by subscribing to a [Shifty Plans](https://laravelshift.com/shifty-plans).

**Comment by Jellyfrog** [comment]
Blocked by; https://github.com/influxdata/influxdb-php/pull/149

**Comment by murrant** [comment]
@Jellyfrog can you re-start this shift?

**Comment by Jellyfrog** [comment]
Yeah I'll try to work on it next week

**Pull request closed without merging**
