### PR TITLE
Convert Config to a singleton

### PR DESCRIPTION
**Pull request by murrant**
Continuation of https://github.com/librenms/librenms/pull/14364 by @Jellyfrog
This time, make the old class a shim for the facade. Will update references in a separate PR.

resubmit of #16349 
requires #16385 

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Blocked by https://github.com/librenms/librenms/pull/16385

**Review by Jellyfrog — DISMISSED** [review]

**Comment by laf** [comment]
@murrant Let me know when you want this checking.

**Comment by murrant** [comment]
@laf I think we should merge this sometime soon.

**Comment by laf** [comment]
Let me get on with testing this tomorrow.

**Review by laf — APPROVED** [review]
Code looks good, tested large amounts of the webui and polling/discovery/alerting.

**Pull request merged**
