### PR TITLE
Added support for searching for arp entry

### PR DESCRIPTION
**Pull request by laf**
Using this at work. Feel free to merge or not.

### CODE REVIEW

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
bump

**Comment by Rosiak** [comment]
Not working for me:
```
curl -H 'X-Auth-Token: 58917966815378f4ac20eaeac01a3a23' http://127.0.0.1/api/v0/resources/ip/arp/192.168.169.129
{
    "status": "ok",
    "err-msg": "",
    "count": 0,
    "arp": []
}
```

**Comment by laf** [comment]
Works for me:

```bash
curl -H 'X-Auth-Token: DSADASDSAD' http://url/api/v0/resources/ip/arp/192.168.10.2
{
    "status": "ok",
    "err-msg": "",
    "count": 6,
    "arp": [
        {
            "port_id": "1632",
            "mac_address": "363666636430",
            "ipv4_address": "192.168.10.2",
            "context_name": null
        },
        {
            "port_id": "21587",
            "mac_address": "363666636430",
            "ipv4_address": "192.168.10.2",
            "context_name": ""
        },
        {
            "port_id": "21528",
            "mac_address": "363666636430",
            "ipv4_address": "192.168.10.2",
            "context_name": ""
        },
        {
            "port_id": "21530",
            "mac_address": "363666636430",
            "ipv4_address": "192.168.10.2",
            "context_name": ""
        },
        {
            "port_id": "21586",
            "mac_address": "363666636430",
            "ipv4_address": "192.168.10.2",
            "context_name": ""
        },
        {
            "port_id": "24230",
            "mac_address": "363666636430",
            "ipv4_address": "192.168.10.2",
            "context_name": ""
        }
    ]
}
```

**Comment by Rosiak** [comment]
Well turns out that I actually just had to ask for some valid data from the ipv4_mac table.
Works fine.

**Comment by laf** [comment]
bump

**Pull request merged**
