### PR TITLE
New Device: ATS - Automatic Transfer Switch

### PR DESCRIPTION
**Pull request by TheGreatDoc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
I cant get the High/Low limit work for the temperature sensor.

It snmpget the value but set it as Array when discovering sensor

```
Caching data: sensors SNMP['/usr/bin/snmpwalk' '-v2c' '-c' 'COMMUNITY' '-OteQUs' '-Ih' '-m' 'ATS-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ats' 'udp:HOSTNAME:161' 'emdConfigTempHighSetPoint.0']
emdConfigTempHighSetPoint.0 = 40

SNMP['/usr/bin/snmpwalk' '-v2c' '-c' 'COMMUNITY' '-OteQUs' '-Ih' '-m' 'ATS-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ats' 'udp:HOSTNAME:161' 'emdConfigTempLowSetPoint.0']
emdConfigTempLowSetPoint.0 = 5
```
And then:
```
Final sensor value: 29
Cur 29, Low: Array, Low Warn: null, Warn: null, High: Array
```

**Comment by murrant** [comment]
probably because the code expects tables.  If you dump out the data after pre-cache, you should see it as an array.


FYI, the logo seems to be a copy of the icon. (icon is used if the logo doesn't exist)

**Comment by TheGreatDoc** [comment]
yes, its a "copy". 

About pre-cache, it worked for the other limits and walk/return are exactly the same.

**Comment by murrant** [comment]
You are looking at the raw snmpwalk output, not the data after it is returned by the snmp function.  It is in an array that doesn't track with what you expect.

**Comment by TheGreatDoc** [comment]
I do understand what you mean. What I say is: why it works for the other limits?

What pre-cache does is snmpwalk and all limits returns the same in the walk. Just 1 oid with 1 value.

**Comment by murrant** [comment]
because it is grouping the data by the index.  If you remove the extra index, it strips a level of arrays.

**Comment by TheGreatDoc** [comment]
@murrant totally forgot about this.

So, how should I proceed? Just remove the temp limits from yaml?

**Comment by murrant** [comment]
Probably need to move that part to php

**Pull request merged**
