### PR TITLE
Fix Ruckus Unleashed product ID for OS detection

### PR DESCRIPTION
**Pull request by Cougar**
Please give a short description what your pull request is for

Fix for Ruckus Unleashed OS detection. It could be that the previous `sysObjectID` worked with older firmware but most probably it is just a typo and untested with real hardware.

Ruckus MIB lists .15 as `ruckusZD1200` and .20 as `ruckusUnleashed`. This is based on [unleashed-mibs-20230626.zip](https://support.ruckuswireless.com/software/4093-ruckus-unleashed-ap-200-15-mr-refresh-snmp-mibs) which is the latest MIB bundle for Unleashed products.

```
RUCKUS-PRODUCTS-MIB.txt:ruckusZD1200 OBJECT IDENTIFIER  ::= { ruckusWirelessControllerProducts 15 }
RUCKUS-PRODUCTS-MIB.txt:ruckusUnleashed OBJECT IDENTIFIER  ::= { ruckusWirelessControllerProducts 20 }
```
This change has been tested with latest `200.15.6.112 build 54`.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

I couldn't run tests myself but hope that this change is straightforward and don't break any existing tests.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — CHANGES_REQUESTED** [review]
.1.3.6.1.4.1.25053.3.1.5.15 is no longer a valid sysObjectID? that doesn't seem right

**Comment by Cougar** [comment]
> .1.3.6.1.4.1.25053.3.1.5.15 is no longer a valid sysObjectID? that doesn't seem right

ID is valid of course but not for Unleashed platform :) In [latest](https://support.ruckuswireless.com/software_downloads/4093-ruckus-unleashed-ap-200-15-mr-refresh-snmp-mibs) MIB these IDs are:

```
-- ZD1200 - Access Controller, 2 Ethernet ports, 2048MB Flash, 2048MB DRAM
ruckusZD1200 OBJECT IDENTIFIER  ::= { ruckusWirelessControllerProducts 15 }

-- Unleashed 
ruckusUnleashed OBJECT IDENTIFIER  ::= { ruckusWirelessControllerProducts 20 }
```

I can confirm that Unleashed returns this OID right now:

```
SNMPv2-MIB::sysDescr.0 = STRING: Ruckus Wireless R710
SNMPv2-MIB::sysObjectID.0 = OID: RUCKUS-ROOT-MIB::ruckusRootMIB.3.1.5.20
…
RUCKUS-UNLEASHED-SYSTEM-MIB::ruckusUnleashedSystemVersion.0 = STRING: 200.15.6.112 build 54
```

**Comment by murrant** [comment]
What does the device return for sysObjectID?  I trust that way more than MIBs.

**Comment by Cougar** [comment]
> What does the device return for sysObjectID? I trust that way more than MIBs.

Scroll up my previous [comment](https://github.com/librenms/librenms/pull/16067#issuecomment-2133841799) :)

**Review by Jellyfrog — APPROVED** [review]

**Comment by Jellyfrog** [comment]
Let's try.

**Pull request merged**
