### PR TITLE
Wrap header in panel

### PR DESCRIPTION
**Pull request by arjitc**
http://i.imgur.com/vObwD4w.png

### CODE REVIEW

**Comment by laf** [comment]
I can't make my mind up on this, it's not made me go nice when I first viewed it.

Anyone else got thoughts on this?

@paulgear / @f0o / @Rosiak / @SaaldjorMike

**Comment by Rosiak** [comment]
Hrm, something should be done with the device-menu panel before moving further with this.

**Comment by SaaldjorMike** [comment]
Personally I don't fancy the look of the panel. I got somewhat the same feeling like @laf 
On a side note, the indentation needs to be fixed if still want to merge this.

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Indent looks good for me, if you mean the border of the panel to the first tab's border.

I like the panel but I leave it up to the rest to decide whether it's worth merging or not.
I dont think it's really required, from a objective PoV it just pads down all the info by 10px without doing anything other than eye-candy.

**Comment by laf** [comment]
Yeah I think it looks good but my biggest issue is that this page serves one main purpose which is to show a graph, that graph now isn't totally on the screen by default meaning people have to scroll.

**Comment by f0o** [comment]
@laf this isnt #1973 - this just puts a border around the device's overview header

**Comment by laf** [comment]
lol, indeed. Replying on the phone earlier :(

**Pull request merged**
