### PR TITLE
Puppet Agent Monitoring

### PR DESCRIPTION
**Pull request by SourceDoctor**
# monitoring puppet Agents

## About Puppet:
Puppet is a mighty continuous delivery System to keep all your Servers up to date and in sync.
Also reinstallation/configuration will be massivly speeded up.

### A good description/example what puppet is and can do:
[https://www.guru99.com/puppet-tutorial.html](https://www.guru99.com/puppet-tutorial.html)

Official Page:
[https://puppet.com/docs/](https://puppet.com/docs/)

matching librenms-agent:
[https://github.com/librenms/librenms-agent/pull/258](https://github.com/librenms/librenms-agent/pull/258)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10827`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
@SourceDoctor Please keep the PR structure :)

**Comment by SourceDoctor** [comment]
@PipoCanaja 
i think you mean the text you edited in?

**Comment by PipoCanaja** [comment]
Absolutely, Whatever is after `DO NOT DELETE THIS TEXT`

**Comment by SourceDoctor** [comment]
ok :)

**Comment by SourceDoctor** [comment]
added Device Overview Panel
image

**Comment by SourceDoctor** [comment]
@maintainer
is someone using Puppet to check and verify this PR? :-)

**Comment by SourceDoctor** [comment]
@PipoCanaja still not labeled after 2 month?
unusual for you ;-)

**Comment by PipoCanaja** [comment]
Hi @SourceDoctor 
Absolutely no idea about puppet, no way to test this. @librenms/testers, anybody using puppet ?

**Comment by SourceDoctor** [comment]
@PipoCanaja 

You'll love Puppet if running a lot of Linux Systems.
Especially when many of them are similiar.
Even if you only have to keep SSH Keys in sync on all of this Systems.

Similar continuous delivery System are Chef, Ansible and Saltstack.

**Comment by PipoCanaja** [comment]
I am a poor network engineer :) not in charge of the systems :p But I'll have a look at some time. Until then, we need to find out a tester for this :D

**Comment by SourceDoctor** [comment]
@PipoCanaja 
on my System for Tests and Development it's running fine, but i believe that's not enough ;)

**Comment by PipoCanaja** [comment]
> @PipoCanaja
> on my System for Tests and Development it's running fine, but i believe that's not enough ;)

That's a very good beginning indeed :)

**Comment by Jellyfrog** [comment]
@SourceDoctor ah, crap. Forgot to ask you to generate testdata. Could you open a pr with that?

**Comment by SourceDoctor** [comment]
@Jellyfrog 
i'll do. 
n.p. :-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
