### PR TITLE
Add db schema for ups-nut alerting

### PR DESCRIPTION
**Pull request by erotel**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for submitting this. Be interested to hear what others say on this but imho table specific data is something we should be avoiding. Components could be a fit here but I'm not a fan of that personally.

My approach would be to cache the data from applications to re-use in sensors in someway and if the data doesn't exist when running sensors than obtain it again and cache it. A lot of the data you are storing is already done in the sensors model and has alerting and webui support.

**Comment by erotel** [comment]
If I understand this, then the data from /include/polling/applications/ups-nut.inc.php are only written to the graph.
If this is not the case, then I do not understand the alert system at all.

**Comment by laf** [comment]
Yes data in applications is typically only written to graphs and not the database.

**Comment by erotel** [comment]
In that case, if I understand well, I can not have an alert for ups-nut, since the alert function compares alert rules stored in db with data stored in db.
Is it right?
Sorry my English is bad, I use google translator

**Comment by laf** [comment]
That's correct.

Hence my suggestion that this should be part of the sensors code to do this. It's probably unlikely to be possible to be done in yaml but php would be fine.

**Comment by erotel** [comment]
If I understand it well, should I try to write data from ups-nut.inc.php into the db table of sensors and not use my own ups-nut table?

**Comment by erotel** [comment]
I'm not sure it will save the data from /include/polling/applications/ups-nut.inc.php into db table sensors. In table sensors, each sensor has a unique oid, but ups-down under one oid returns several sensors.

**Comment by laf** [comment]
show an snmpwalk output of the data so we can see what we're dealing with.

**Comment by erotel** [comment]
I have already found an oid for individual sensors

**Comment by laf** [comment]
Better :)

However I would say this doesn't need calling from applications and instead should just be a native sensor for the OS type (I'm guessing it's only linux this works on).

Looks like this would be fine for conversion to yaml as well (see our docs).

**Comment by erotel** [comment]
I also thought to place the discovery into linux, but above all what if someone writes an application for another system?
I'll look at the yaml format.

**Comment by laf** [comment]
What other systems though? all *nix based are discovered as linux.

**Comment by erotel** [comment]
When it's hard for you  ;)
Ok to remake it.

**Comment by erotel** [comment]
Hmm yaml config not work

```
root@speedtest:/opt/librenms/includes/definitions/discovery# snmpwalk -c public -v1 -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs/ 10.133.139.17 nsExtendOutLine
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".1 = STRING: 100.0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".2 = STRING: 120
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".3 = STRING: 16020
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".4 = STRING: 54.81
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".5 = STRING: 048
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".6 = STRING: Unknown
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".7 = STRING: 243.3
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".8 = STRING: 030.5

root@speedtest:/opt/librenms/includes/definitions/discovery# snmpwalk -c public -v1 -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs/ 10.133.139.17 nsExtendOutLine."ups-nut".1
nsExtendOutLine.ups-nut.1: Unknown Object Identifier (Index out of range: ups-nut (nsExtendToken))

```

**Comment by laf** [comment]
Show the yaml as it should work fine.

**Comment by erotel** [comment]
Im test only one sensor

```
mib: NET-SNMP-EXTEND-MIB
modules:
    sensors:
        charge:
            data:
                -
                    oid:  nsExtendOutLine
                    num_oid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.
                    descr: Batery Charge
                    index: 'nsExtendOutLine.{{ $index }}'

```

 [output](https://pastebin.com/GcHnip2v)

**Comment by laf** [comment]
Try changing `oid:  nsExtendOutLine` to `oid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116`

**Comment by erotel** [comment]
```
Dynamic Discovery (charge): Array
(
    [data] => Array
        (
            [0] => Array
                (
                    [oid] => .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116
                    [num_oid] => .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.
                    [descr] => Batery Charge
                    [index] => nsExtendOutLine.{{ $index }}
                )

        )

)
Data .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116: Array
(
    [ups-nut.1] => Array
        (
            [nsExtendOutLine] => 100.0
        )

    [ups-nut.2] => Array
        (
            [nsExtendOutLine] => 120
        )

    [ups-nut.3] => Array
        (
            [nsExtendOutLine] => 16500
        )

    [ups-nut.4] => Array
        (
            [nsExtendOutLine] => 54.81
        )

    [ups-nut.5] => Array
        (
            [nsExtendOutLine] => 048
        )

    [ups-nut.6] => Array
        (
            [nsExtendOutLine] => Unknown
        )

    [ups-nut.7] => Array
        (
            [nsExtendOutLine] => 247.6
        )

    [ups-nut.8] => Array
        (
            [nsExtendOutLine] => 029.9
        )

)
Final sensor value:
Final sensor value:
Final sensor value:
Final sensor value:
Final sensor value:
Final sensor value:
Final sensor value:
Final sensor value:
```

**Comment by laf** [comment]
Can you provide an snmpwalk as per https://docs.librenms.org/#Support/FAQ/#faq8

**Comment by erotel** [comment]
if use snmpbulkwalk -OUneb -v2c -c public 10.133.139.17 oid ups-nut not in tree.
Only if use 
```
root@speedtest:~# snmpbulkwalk -On -c public -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs/ -v2c 10.133.139.17 nsExtendOutLine
.1.3.6.1.4.1.8072.1.3.2.4.1.2.4.116.101.115.116.1 = STRING: uname: No such file or directory
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1 = STRING: 100.0
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.2 = STRING: 120
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.3 = STRING: 16020
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.4 = STRING: 54.81
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.5 = STRING: 048
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.6 = STRING: Unknown
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.7 = STRING: 244.8
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.8 = STRING: 031.2

root@speedtest:~# snmpbulkwalk -c public -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs/ -v2c 10.133.139.17 nsExtendOutLine
NET-SNMP-EXTEND-MIB::nsExtendOutLine."test".1 = STRING: uname: No such file or directory
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".1 = STRING: 100.0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".2 = STRING: 120
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".3 = STRING: 16500
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".4 = STRING: 54.81
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".5 = STRING: 048
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".6 = STRING: Unknown
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".7 = STRING: 246.2
NET-SNMP-EXTEND-MIB::nsExtendOutLine."ups-nut".8 = STRING: 030.5
```

**Comment by laf** [comment]
@erotel it needs to be the full walk as per the FAQ I linked to so that I can use it to simulate the device.

**Comment by erotel** [comment]
[here](https://pastebin.com/p5iY380A),but im delete routing info,file is very big

**Comment by laf** [comment]
That output doesn't contain the values from .`1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116` Can you re-run it with that oid on the end instead of the `.`

**Comment by erotel** [comment]
```
root@speedtest:~# snmpbulkwalk -OUneb -v2c -c public 10.133.139.17 .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1 = STRING: "100.0"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.2 = STRING: "120"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.3 = STRING: "16500"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.4 = STRING: "54.81"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.5 = STRING: "048"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.6 = STRING: "Unknown"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.7 = STRING: "247.6"
.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.8 = STRING: "029.9"
```

**Comment by laf** [comment]
Ok, here's what works for me (yaml file + php patch):

```yaml
modules:
    sensors:
        charge:
            data:
                -
                    oid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1
                    num_oid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.
                    value: 1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1
                    snmp_flags: '-OneQU'
                    descr: Batery Charge
                    index: 'nsExtendOutLine.1'
```

Notice the oid has the index on, this is because you don't care about the full table here and just a single OID per sensor type.

```php
diff --git a/includes/discovery/functions.inc.php b/includes/discovery/functions.inc.php
index f785d8c4b..f684341ec 100644
--- a/includes/discovery/functions.inc.php
+++ b/includes/discovery/functions.inc.php
@@ -984,7 +984,13 @@ function discovery_process(&$valid, $device, $sensor_type, $pre_cache)
                 // get the value for this sensor, check 'value' and 'oid', if state string, translate to a number
                 $data_name = isset($data['value']) ? $data['value'] : $data['oid'];  // fallback to oid if value is not set

-                $tmp_value = $snmp_data[$data_name];
+                if (is_array($snmp_data)) {
+                    $array_values = array_values($snmp_data);
+                    $tmp_value = $array_values[0];
+                    unset($array_values);
+                } else {
+                    $tmp_value = $snmp_data[$data_name];
+                }
                 if (!is_numeric($tmp_value)) {
                     preg_match('/-?\d*\.?\d+/', $tmp_value, $temp_response);
                     if (!empty($temp_response[0])) {

```

**Comment by erotel** [comment]
I'm not sure if I have your patch well applied but if you look at the line find sensor there is an oid there twice. This is stored in db and poller.php then reports a non-oid.
```
Dynamic Discovery (charge): Array
(
    [data] => Array
        (
            [0] => Array
                (
                    [oid] => .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1
                    [num_oid] => .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.
                    [value] => 1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1
                    [snmp_flags] => -OneQU
                    [descr] => Batery Charge
                    [index] => nsExtendOutLine.1
                )

        )

)
Data .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1: Array
(
    [1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1] => Array
        (
            [] => 100.0
        )

)
Final sensor value: 100.0
Discover sensor: .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1, nsExtendOutLine.1, linux, Batery Charge, snmp, 1, 1, , 100
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'charge' AND `device_id` = '31' AND sensor_type = 'linux' AND `sensor_index` = 'nsExtendOutLine.1']
SQL[INSERT INTO `sensors` (`poller_type`,`sensor_class`,`device_id`,`sensor_oid`,`sensor_index`,`sensor_type`,`sensor_descr`,`sensor_divisor`,`sensor_multiplier`,`sensor_current`)  VALUES ('snmp','charge','31','.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1','nsExtendOutLine.1','linux','Batery Charge','1','1','100')]
( 321 inserted )


SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OUQnt -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:HOSTNAME:161 .1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1.3.6.1.4.1.8072.1.3.2.4.1.2.7.117.112.115.45.110.117.116.1]
.*.4.1.8*.*.*.*.*.1.8*.*.*.* = No Such Instance currently exists at this OID

Checking (snmp) charge Batery Charge...
0
RRD[update /opt/librenms/rrd/10.133.139.17/sensor-charge-linux-nsExtendOutLine.1.rrd N:0]

```

**Comment by laf** [comment]
Thanks for giving it a shot, I think we'll just have to go with the php version for now - thanks for all the feedback and nice work on the PR :)

**Pull request merged**
