### PR TITLE
Updating the mibs file from vmware

### PR DESCRIPTION
**Pull request by mikeSimonson**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
You've added a whole heap of new MIBs which are already in the mibs folder. Please remove those from the vmware folder and only have vmware specific mibs there.

**Comment by tracernz** [comment]
Can you put the source these were retrieved from etc. in the commit message please? It would help a bit for anyone trying to look at how they came to be in future.

**Comment by mikeSimonson** [comment]
How do you spot those that are vmware specific ?
Those only come from the vmware archive.

**Comment by tracernz** [comment]
> How do you spot those that are vmware specific ?

VMWARE-*

> Those only come from the vmware archive.

Yeah, they included all the generic MIBs their products use too.

**Comment by murrant** [comment]
You can check this by running: 
`composer install` (to install development dependencies
`./vendor/bin/phpunit tests/MibTest.php --group mibs --filter=vmware` to check for problems in the vmware mib directory.

**Pull request merged**
