### PR TITLE
Battery charge monitoring for APC UPS.

### PR DESCRIPTION
**Pull request by mchasteen**
This just added a sensor type called "charge" which tracks the charge on a APC UPS in commit c1852719c5e12ce40f0a4899efc43df2cf7c3cb3 (Yes, I still cant figure out this pull/whatever stuff).  Looks pretty.  Tested with smartUPS 1000 and 3000.

### CODE REVIEW

**Comment by laf** [comment]
:)

We're going to have to get you  upto scrach on using git @mchasteen.

What git client are you using?

**Comment by mchasteen** [comment]
git commandline.

**Comment by laf** [comment]
Ok, first thing is to set git to auto rebase, in the librenms directory and run:

git config --global branch.autosetuprebase always

Then add a new remote (if you don't already have one):

git remote add upstream https://github.com/librenms/librenms.git
git remote update

Now create a new branch from the main master:
git push upstream master:apc
git checkout apc

Now grab the commits specifically for this PR:
git cherry-pick c185271
git cherry-pick 670b749

Now you should be able to commit that and do:

git push origin apc

Then submit a new PR for just that branch.

**Comment by mchasteen** [comment]
Ah, many thanks!  Also thanks for patience!

**Comment by mchasteen** [comment]
git push upstream master:apc

do you mean:
git push origin master:apc

**Comment by laf** [comment]
No, with using upstream it means you are taking a full upto date copy of the main librenms branch, we know that way it will be clean :)

I've got to head to bed soon but feel free to comment here

**Comment by laf** [comment]
@mchasteen hope you don't mind but I pulled out the relevant commits from this PR and created #519.

**Pull request closed without merging**
