### PR TITLE
Fiberstore Switch add sensors for 52652 switches

### PR DESCRIPTION
**Pull request by murrant**
Because of conflicting MIB names, I had to rename "SWITCH" to FS-SWITCH-V1-MIB and FS-SWITCH-V2-MIB

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by freddy36** [comment]
Is there a typo in the PR subject? I'm not aware of a 52652 switch model.
Based on the MIB file and the OIDs it looks like you mean the S5850 series.

FS doesn't actually develop any of their switches themself.
The S5850 Seris is just a rebranded version of the Centec switches (https://www.centec.com/solution?category=V-Series-Ethernet-Switch).

I'm currently also working on a PR for the S5850 switches which will add temperature/fans/power/transceiver sensors.
But my approach is to move everything to a new OS (fs-cnos), just like in https://github.com/librenms/librenms/pull/16162.
Trying to support all the various OEM switches in a single FS OS won't work very well. Some of the SNMP OIDs are overlapping.

**Comment by murrant** [comment]
Refers to the enterprise id.  FS model numbers seem pretty meaningless as S5850 applies to devices that seeming use one of three different sets of MIBs.

**Comment by freddy36** [comment]
Yes, as I mentioned they simply do a search/replace for the original manufacturer enterprise ID with the fiberstore ID. That sometimes leads to overlapping OIDs. That's why I would recommend moving it to a separate OS. I'll publish my version without transceiver support next week.

**Comment by murrant** [comment]
Superceded

**Pull request closed without merging**
