### PR TITLE
Add AS Text string to BGP Log Event messages

### PR DESCRIPTION
**Pull request by mjclancyau**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7344)

### CODE REVIEW

**Comment by laf** [comment]
How come you closed this?

**Comment by mjclancyau** [comment]
Oops, sorry, I'm a Github newb and accidentally deleted the branch.

Is it recoverable now?

Regards,
Matt

**Comment by laf** [comment]
Yeah that's brought it back :)

> I guess the only other change that might make sense here is checking whether "AS Text" for a particular AS actually contains anything before appending it to the message?

That definitely would be worthwhile. Also we have astext stored in the DB so you can use `$peer['astext']` instead of the function which will perform a dns lookup each time.

**Comment by laf** [comment]
@mjclancyau Any feedback on my comment?

**Comment by laf** [comment]
@mjclancyau Any update on this?

**Comment by laf** [comment]
@mjclancyau feel free to comment when you're ready and we can re-open.

**Pull request closed without merging**
