### PR TITLE
New Device: PowerTek/BladeShelter PDU support

### PR DESCRIPTION
**Pull request by mattosem**
My first pull request in my life. I've added with the help of @TheGreatDoc the support of this PDU.
If I must do something better, let me know :-D

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Awesome work. Thank you very much for your contribution.

You can check that the Travis CI has failed. Take a look to the error and fix it.

Also, we need the test units.

**Comment by mattosem** [comment]
Test unit added!

**Comment by TheGreatDoc** [comment]
Wait, why you closed this?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
