### PR TITLE
added missing wifi module to poller modules

### PR DESCRIPTION
**Pull request by barryodonovan**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by barryodonovan** [comment]
The wifi module, which has been changed to '0' by default is required for ceraos.

**Comment by murrant** [comment]
@barryodonovan if you can give me an snmpwalk from one of these devices, I will remove the need for the wifi module.   We are trying to delete the wifi module from our code and port everything over to wireless.

**Comment by barryodonovan** [comment]
@murrant Thanks, I have been hoping to find a window to do this but to no avail yet.

There is an issue with the current setup, whereby it 'discovers' the number of radios and polls based on this number.

An approach may be to break the discovery out to multiple definitions, using a default expected number of radios per definition and then create a new device with extra radios if someone requires it.


eg IP10 has one radio, IP10q may have from 1-4 radios (usually 2), the multiple radios are for either extra bandwidth or redundancy, dependent on configuration options.


Where can I send you the SNMP walks? I'll send from some of the various radios I have access to later.



________________________________

**Comment by murrant** [comment]
You can DM me on Discord.

**Comment by Rosiak** [comment]
I'll close this PR, then you guys can sort the details out.

**Comment by murrant** [comment]
I have support written, but I have no idea if it works as I don't have a device.

**Comment by laf** [comment]
@murrant I'll post a pastebin link for an snmpwalk

**Comment by barryodonovan** [comment]
@murrant could you send me what you have and I could test it. Unfortunately Librenms keeps getting submerged under my to-do list... I was unable to get any snmpwalk to complete last week  and haven't been able to try again this week yet

**Pull request closed without merging**
