### PR TITLE
add app for getting status of TCP connections for specified services

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This requires https://github.com/librenms/librenms-agent/pull/159

### CODE REVIEW

**Comment by VVelox** [comment]
From matrix on one server of mine...

Pics! https://imgur.com/a/aKYEv
From Server: https://i.imgur.com/u1y4IK1.png
To Server: https://i.imgur.com/pqpDWkV.png
Totals: https://i.imgur.com/sXIsF36.png
Total Details: https://i.imgur.com/pSQ5Hbu.png

**Comment by laf** [comment]
Any reason this is saving to the components table? We have another table for applications now where you can store more data so that might be more appropriate? `application_metrics`

**Comment by VVelox** [comment]
@laf Hey, just looking around and I am not seeing any documentation or any functions for talking to this. Has it been fully implemented yet outside of just being a table? If not, starting to use that sort of bothers me as it does not seem stable as it means starting to use it will mean any code to talk to it will be sitting around in multiple places, making any future updates more problematic as they all have to be tracked down. Currently the components table is nice and documented and we have a means to talking to it properly.

**Comment by laf** [comment]
If your install is up to date then you should find reference to this in includes/polling.

It doesn't have any docs or functions as it's just inserting / reading data into a table so doesn't need anything like that.

**Comment by VVelox** [comment]
@laf  Howdy! Just had a great conversation with @murrant and found that the applications_metrics is being used for alerting and not storing RRD config stuff. Sorry, though you were saying I should use that for starting what RRDs exist.

Sure. I'll sit down and work on getting it all shoved into there via update_application like some of the others. :)

**Comment by laf** [comment]
@VVelox any update on this one?

**Comment by VVelox** [comment]
@laf Hey, sorry. Been a busy last month and all my projects sorta got disrailed for a bit.

But yeah just looking at this more and does this need to be flat or can it be a hash of hashes?

**Comment by VVelox** [comment]
@laf Ahh! Just looking at the smart one. Yeah, does not have to be flat. Doing it like that one. :)

**Comment by VVelox** [comment]
@laf All fixed!

**Comment by laf** [comment]
I'm not a fan of applications and I feel that this is leading us into more of a mess that we will have to do a lot of work to get out (using components). However the code looks fine, I think it needs some example alert rules creating in misc/alert_rules.json so people know how to make use of it.

@murrant what do you think?

**Comment by VVelox** [comment]
@laf The problem is we have nothing else like components for storing data like this.

How would you prefer it to work? Check for the extend of the extend and graph it if it is there?

What is wrong with using components? It allows data to be stored and access in a sane way. Outside of the interface is a bit clunky, it seems to be fine to me.

Personally I love the application as with out it LibreNMS as it is literally the only thing open source that is not garbage for this sort of stats tracking when it.

As to alerting on this, honestly I have no clue how any of the alerting stuff works for apps. Was just looking and I am not seeing that as being documented on any of them.

**Comment by VVelox** [comment]
This has now been converted over to use json_app_get, requiring https://github.com/librenms/librenms/pull/8571 .

**Comment by laf** [comment]
Can you rebase this please.

**Comment by VVelox** [comment]
@laf Done. :)

Now I should really go and make sure this is using json_app_get properly as well as create some test data.

**Comment by VVelox** [comment]
Updated to the current json_app_get and the extend as well.

Just need to finish a bit more documentation and get test data added.

**Comment by VVelox** [comment]
Test data and snmprec added. :)

**Pull request merged**
