### PR TITLE
Add Juniper Inventory support

### PR DESCRIPTION
**Pull request by nwautomator**
Added support for Juniper inventory gathering on Junos devices in a separate discovery module.

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the pr @nwautomator 

Are you sure things like  jnxContentsChassisId can't be used instead of parentrelpos?

Is it worth checking the $device['os'] to see if it's junos before running this and maybe check the $device['os'] isn't junos in the standard entity-physical.inc.php files?

**Comment by nwautomator** [comment]
@laf: my latest commit does an OS check for Junos in the two entity discovery modules and acts accordingly.

**Comment by f0o** [comment]
I wonder, cant this be part of entity-physical.inc.php like the cisco part rather than adding another os-centric module

**Comment by nwautomator** [comment]
@f0o: that's my preference too. If you guys want to merge the code into entity-physical.inc.php, I'm all for it.  :+1:

**Comment by nwautomator** [comment]
@laf, @f0o: my code is merged into the main entity-physical.inc.php module.

**Comment by nwautomator** [comment]
Closing this pull request in order to do it correctly.

**Pull request closed without merging**
