### PR TITLE
alert rules: added Dell iDRAC alert rules

### PR DESCRIPTION
**Pull request by kkrumm1**
to the alerts collection.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by Rosiak** [comment]
Awesome stuff!
My OCD hits me, could you please change idrac to iDRAC? :D

**Comment by kkrumm1** [comment]
@Rosiak Sure will do. :)

**Comment by murrant** [comment]
@kkrumm1 are these types of rules needed anymore now that we can alert on state sensor generic values?

**Comment by kkrumm1** [comment]
@murrant Yes, some users and I still like to use the specific rules instead of the state sensor generic values

**Comment by murrant** [comment]
@kkrumm1 what could be improved so you can use the generic one?  a specific template built in?

**Comment by kkrumm1** [comment]
The generic alert works it's just when you receive the alert you have scroll down just to see what sensor is broken and read the details in the alert. I like to use the sensor specific alerts so I can see right away what the issue is.

**Comment by laf** [comment]
I don't have an issues with more specific alert rules as they cover all bases and are unlikely to change.

**Pull request merged**
