### PR TITLE
Create CONTROLLER-MIB

### PR DESCRIPTION
**Pull request by on3svb**
MIB File for Ucopia Captive Portal (Wifi/LAN) Controller

For request see: https://community.librenms.org/t/mib-oid-for-ucopia-controller-wifi-wired-lan-captive-portal/1673/4

OID Description:
Ucopia Database status
.1.3.6.1.4.1.31218.4.2.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the user/password database
Ucopia Disconnection service
.1.3.6.1.4.1.31218.4.6.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the auto disconnection service that kicks users out when they are not transmitting data within a certain amount of time

Ucopia Splash pages availability webServerService
.1.3.6.1.4.1.31218.4.1.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the (? apache/nginx ?) web service

Ucopia Splash pages availability portalService
.1.3.6.1.4.1.31218.4.4.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the availability of webpages created for each captive portal.

Ucopia URL logging
.1.3.6.1.4.1.31218.4.3.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the URL logging service.

Ucopia Web proxy
.1.3.6.1.4.1.31218.4.5.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the proxy service if enabled by the administrator for the users.

Ucopia concurrent users
.1.3.6.1.4.1.31218.3.1.0
——> Return a value regarding the quantity of users who are connected with the same user&password.

Ucopia cpuTemperature
.1.3.6.1.4.1.31218.3.3.0
—> returns cpu temp

Ucopia dhcpServerService
.1.3.6.1.4.1.31218.4.8.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the dhcp service on the controller

Ucopia diskTemperature
.1.3.6.1.4.1.31218.3.4.0
——> Returns the cpu temp

Ucopia dnsServerService
.1.3.6.1.4.1.31218.4.9.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the internal dns service

Ucopia highAvailabilityService
.1.3.6.1.4.1.31218.4.11.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding a H.A. environment.

Ucopia ldapDirectoryService
.1.3.6.1.4.1.31218.4.12.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the internal ldap service used for storing user & passwords

Ucopia ldapReplicationManagerService
.1.3.6.1.4.1.31218.4.13.0
—> this I don’t know what’s for but I guess it’s for checking status in a H.A. environment.

Ucopia syslogService
.1.3.6.1.4.1.31218.4.18.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding the internal syslog service of the controller.

Ucopia usersLogService
.1.3.6.1.4.1.31218.4.19.0
——> Return a status code (ok/not ok/ok but not master in ha config) regarding regarding the event log of the users (connected/disconnected/end-of-life passsword/mac addresses & user ip’s)

Hope this will help.

Regards,

Sébastien Vandenbussche

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by FTBZ** [comment]
MIB file alone does nothing? This is a new device request?

**Comment by on3svb** [comment]
Hello,

Yes MIB alone is not recognised and I'm not able to create a inc.php related to it.

Yes, if possible.

**Comment by FTBZ** [comment]
Wait for a response from @laf on the Community forum, because this file does nothing alone. Specific code is needed.

**Comment by on3svb** [comment]
Ok. Thanks. Will wait then. I've access to their FAQ/API with their agreement. I'll update then the tread on the Community based forum.

**Comment by laf** [comment]
Those all seem ok for us to add so create an issue and provide all the info we ask for.

**Pull request closed without merging**
