### PR TITLE
Add Fan Support to Alcatel Switches

### PR DESCRIPTION
**Pull request by joseUPV**
Follows up https://github.com/librenms/librenms/pull/10650

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
It's the PR #10650 corrected, I had problems with my local git.

**Comment by joseUPV** [comment]
Added mibs for Alcatel AOS 7 switches.
AOS 6 mibs and AOS 7 mibs have the same filenames but diferent oids numbers.
I changed to relative path in aos 7 fan script.

**Comment by PipoCanaja** [comment]
Hi @joseUPV 
Almost good :) except that the mib files are already located in "nokia" folder, so you don't need to add a new directory with same files. 
You can update the files (if you have newer versions) and add the missing files (like ALCATEL-IND1-OPENFLOW-MIB ).
The only reason to create a new directory, would be if you have conflicting versions that must be kept in nokia and this aos directory. 
Thanx

**Comment by joseUPV** [comment]
All mibs in aos7 folder are diferent or aren't in nokia subfolder.
In fact we have various families of alcatel switches, but it wil be another PR:
     -Enterprise Alcatel-Lucent Omniswitch Switches
          -AOS6 models, like OS6350-P24 (Alcatel-Lucent OS 6.7.1.108.R04): mibs/nokia/ALCATEL-IND1-BASE: REVISION "200704020008Z”
          -AOS7+ models, like OS6900-T40 (Alcatel-Lucent OS
8.5.255.R02): mibs/aos7/ALCATEL-IND1-BASE: REVISION “201003010008Z”
     - Alcatel-Lucent Oministack Swtches:
          -LS models, like LS 6212P (Alcatel-Lucent OS 1.7.0.13): RADLAN-Physicaldescription-MIB
We don't have Alcatel Timetra family swithes.

**Comment by joseUPV** [comment]
Included in #PR 10672

**Pull request closed without merging**
