### PR TITLE
Synology DSM: Moved to yaml discovery

### PR DESCRIPTION
**Pull request by TheGreatDoc**
Moved Synology DSM to dynamic yaml discovery and grouped by type

There are 3 sensors (voltage/load/power) that still in php as I have no way to test them.

**NOTE:** Temperature historical data will be lost as sensor indexes are going to change. If you want to keep them you have to move the rrds to the new file name.

From sensor-temperature-**snmp**-N.rrd to sensor-temperature-**dsm**-N.rrd

Screenshots.
Before:
image
image

After:
image
image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Im unsure on how to fix the tests for the 2 variants (dsm_ds214 and dsm_ds916)

**Comment by TheGreatDoc** [comment]
@Jellyfrog Test files are already in the PR. If you read my last comment, there are 2 variants json files (dsm_ds216 y dsm_ds916) that doesnt contain any sensor info.

**Comment by PipoCanaja** [comment]
> Im unsure on how to fix the tests for the 2 variants (dsm_ds214 and dsm_ds916)

I have a ds214 here I can use to collect new test data after this PR is merged. You can remove DS214 test data for now and ping me when the PR is is merged.

**Comment by Jellyfrog** [comment]
@PipoCanaja If you can check out this branch and attach the result here that would be nice

**Comment by PipoCanaja** [comment]
Hi @TheGreatDoc 
Long but here they are. I think we can remove redundant but incomplete test-data. 
Let see how Travis likes it ...

**Review by PipoCanaja — APPROVED** [review]
LGTM now

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
