### PR TITLE
add OS detection support for the Alcatel-Lucent (Nokia) XRS 7950 per issue #3557

### PR DESCRIPTION
**Pull request by nwautomator**
This resolves Issue #3557

### CODE REVIEW

**Comment by laf** [comment]
Also needs a rebase, I'd suggest just merging this pr with #3555

**Comment by nwautomator** [comment]
Rebased. Please check and let me know if any further issues arise. Thanks!

**Comment by laf** [comment]
Same with this :( 52 commits and 28 changed files, needs tidying up before we can merge.

**Comment by Rosiak** [comment]
Any news @nwautomator ?

**Comment by murrant** [comment]
Added in PR #3698

**Pull request closed without merging**
