### PR TITLE
ZTE ZXA10 Update (Added dBm graphs)

### PR DESCRIPTION
**Pull request by aztec102**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by aztec102** [comment]
@Jellyfrog Hello! Help me, it's not entirely clear why in some checks an error occurs, although the data is normal

**Review by aztec102 — COMMENTED** [review]
Review and comment

**Review by murrant — CHANGES_REQUESTED** [review]
1. Don't use pre-cache it can make things slower
2. Why do you use hardcoded values?
3. Polling files are not needed if you set the numeric oid correctly during discovery
4. Why aren't you using yaml?
5. Don't overwrite existing test data, create a new variant with -v

**Review by aztec102 — COMMENTED** [review]
@murrant Please check

**Review by murrant — APPROVED** [review]

**Comment by fcqpl** [comment]
How to disable this commit? Now we have problems with ZTE OLT mgmt cards.
We need some settings variable to disable reading signals from ONT.

**Comment by aztec102** [comment]
@fcqpl You have ZTE C300. You need using snmp timeout set 90 seconds.
My colleague and I tested the ZTE C300. And there were problems when working with dBm signals. As part of my testing, it was necessary to update the entire OLT to the v210_034.spat patch. Then more or less started working with a timeout of 90 seconds

**Comment by fcqpl** [comment]
@murrant Why this pull request was merged? This feature is killing OLT CPU. We have issues with our ZTE network since Saturday. ONU should not be polled every 5 minutes, there is a bug in ZTE OLT software.

Again, @aztec102 please  add option to disable this functionality or revert this merge from LibreNMS.

**Comment by aztec102** [comment]
@fcqpl Listen, I'm telling you. Graphs are not written because there is a polling error. I say try to set the timeout to 90 seconds.
I can prepare a version without these charts for you by mail. Pour yourself.

**Comment by aztec102** [comment]
Waiting for @murrant
Previously I used subindex because the interface name came out right it didn't work. Then murrant made the final changes to $ifname. In fact, the names work correctly for me only on one device out of three.
As I understand it, the problem is mainly seen on OLT C300 with high CPU usage.

Not work device
изображение
Work device
изображение

**Pull request merged**
