### PR TITLE
Global VLAN ports page

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
I tested this on a test VM, and I like it, it will certainly be useful in LibreNMS instances I run. 
May be on bigger one, other filtering capacities (I think of locations for instance)  would make sense, as VLANs tend to be "local" to locations in a routed L3 network. Thx @murrant

**Comment by PipoCanaja** [comment]
A question : do you know how would the dropdown menu behave with 4094 VLANs ? (I don't have this test setup available to check ...)

**Review by laf — APPROVED** [review]
Tested as well and works well.

**Comment by murrant** [comment]
@PipoCanaja this PR was very basic.  It could use a lot of extra things.  I wanted to add a map as well, but that depends on #15567

**Pull request merged**
