### PR TITLE
Add support for Fiberstore branded BDCOM switches

### PR DESCRIPTION
**Pull request by freddy36**
Adds better support for Fiberstore branded BDCOM switches.

E.g. the S3900-R Series switch from fiberstore are just rebranded versions of the BDCOM S2900 series.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @freddy36 
Are the FS-BDCOM MIBs the same as the standard BDCOM ones ? If yes, please avoid duplicating them.

**Comment by freddy36** [comment]
> Hi @freddy36 
> Are the FS-BDCOM MIBs the same as the standard BDCOM ones ? If yes, please avoid duplicating them. 
> 

Actually only one is different (different enterprise ID s). Is it possible to use multiple MIB dirs in this case?

**Comment by freddy36** [comment]
> Please add test data so we can ensure your change is not broken in the future.
> Read the docs to find out how: https://docs.librenms.org/Developing/os/Test-Units

Test data is already included.

**Comment by murrant** [comment]
If they are the same, this should use the bdcom os.

**Comment by freddy36** [comment]
> If they are the same, this should use the bdcom os.

Hardware-wise they are the same. On the software side Fiberstore simply replaced all BDCOM references (Strings, logos, MAC addresses, SNMP enterprise OID) with Fiberstore. What is the prefered way of handling this? If it would show up as BDCOM in the GUI, it might be confusion for some people who through that they bought a fiebrstore switch.

**Comment by murrant** [comment]
If they changed the enterprise number, it is fine as a separate OS or merged with fs-switch.  FS's whole switch line is very difficult to figure out how to handle.

**Review by murrant — APPROVED** [review]

**Pull request merged**
