### PR TITLE
alphabetic order of app overview

### PR DESCRIPTION
**Pull request by SourceDoctor**
sort applications alphabetic on overview page

### CODE REVIEW

**Comment by Jellyfrog** [comment]
you should put sortBy() Before get(), so it's happens in sql instead of the collection

**Comment by SourceDoctor** [comment]
@Jellyfrog 
i tried before doing pull request and got a crash ... this is the way it works ;-)

**Comment by murrant** [comment]
It needs to be ->orderBy('app_type') if you do it in the SQL query (which you should)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
