### PR TITLE
Update dark theme panel headings

### PR DESCRIPTION
**Pull request by florianbeer**
...to be consistent with navbar.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
I'll be honest and say I can't tell a difference :)

**Comment by florianbeer** [comment]
Trust me there is. It was far to dark and "in your face". This is much nicer!  
...at least on my monitors.

**Comment by laf** [comment]
I'll take your word for it :D

**Comment by florianbeer** [comment]
Thank you, oh great merger 🤴

**Pull request merged**
