### PR TITLE
Remove int width from db schema (MySQL 8)

### PR DESCRIPTION
**Pull request by arrmo**
Please give a short description what your pull request is for
As discussed here, this is the correction to remove the width,
https://github.com/librenms/librenms/pull/11533#issuecomment-635131161

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
it is only integer width that is affected right?

**Comment by arrmo** [comment]
> it is only integer width that is affected right?

No, at least here it looks like I see issues with int, tinyint, varchar, smallint ... OK, I'm not keeping on looking. LOL.

**Comment by arrmo** [comment]
BTW, a thought (dumb question?) here. The code I added works, removes the '(number)', which then lets the schema check pass, but ... I dumped the schema then from my database, and afterwards validate.php checks against that ... right? So I'm sort of checking against myself 😆. Is that what should happen? Or is the dump a one time thing, to get back in sync?

Sorry, just trying to understand.

Thanks!

**Comment by murrant** [comment]
dump creates a record of the current schema.
Validate runs dump and compares the saved one against the one it just dumped.

**Comment by arrmo** [comment]
OK, makes sense, thanks! Should I also add that dump (i.e. latest misc/db_schema.yaml) to this PR?

**Comment by arrmo** [comment]
Found it! :-). Bit of code below, it's in LibreNMS/Validations/Database.php, inside private function checkSchema(Validator $validator),

```
                    // MySQL 8 fix, remove DEFAULT_GENERATED from timestamp extra columns
                    if ($cdata['Type'] == 'timestamp') {
                         $current_columns[$column]['Extra'] = preg_replace("/DEFAULT_GENERATED[ ]*/", '', $current_columns[$column]['Extra']);
                    }
```

I'm not sure why this is used / needed, but due to this the check removes DEFAULT_GENERATED! As this is not removed on the generation / dumping side ... the check fails, for timestamps (as I have been seeing). So, adding the code below to includes/functions.php, and then re-generating the schema ... it passes now!

```
            // MySQL 8 fix, remove DEFAULT_GENERATED from timestamp extra columns
            if ($def['Type'] == 'timestamp') {
                 $def['Extra'] = preg_replace("/DEFAULT_GENERATED[ ]*/", '', $def['Extra']);
            }
```

Do I go ahead and add this matching code to includes/functions.php, and then add this file (along with the new schema) to this PR?

Thanks!

**Comment by arrmo** [comment]
OK, found where this was added! https://github.com/librenms/librenms/pull/9923/

Seems recent mysql updates added this, so the noted PR removed it ... but then after re-generating the schema (which didn't remove it) ... the timestamp issue I saw. I think I need to add this then (as above), and also update the schema file. Please just let me know - if you agree, I'll add the two of them to this PR. Then old and new schema files will both work.

**Comment by murrant** [comment]
Yeah, add them, you don't need my permission to update the PR :)

Could you try changing your regex to `preg_replace('/int\([0-9]+\)/', 'int', $data->COLUMN_TYPE)`?

**Comment by arrmo** [comment]
> Yeah, add them, you don't need my permission to update the PR :)

LOL. Just didn't know what files you want in the repository, vs. local. That's why I asked. Will do though!

> Could you try changing your regex to `preg_replace('/int\([0-9]+\)/', 'int', $data->COLUMN_TYPE)`?

I can, but not all the items being replaced are int ... still want to do this?

**Comment by murrant** [comment]
@arrmo  your production DB has some oddities :)
I did a fresh db migration and dump and uploaded it after setting it to only scrub length from integer types.
For future you might use DB_TEST_DATABASE to specify an alternate database to for tests.  Then you can `./lnms migrate:fresh --database=testing` and `DBTEST=1 ./scripts/build-schema.php`  (note migrate:fresh erases all db data, don't do it on your prod :D)

**Comment by arrmo** [comment]
> your production DB has some oddities :)

OK, odd, but one of those things I guess ... LOL. No biggie, thanks for explaining! To understand ... it looks like you updated the files (thanks!) - so do I just wait for the merge, then get back on master, and will have your changes in place?

But also, do I need to do anything to my (production) DB, or will this all get cleaned up with your updates?

Thanks again.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
