### PR TITLE
CyberPower UPS Updates

### PR DESCRIPTION
**Pull request by arrmo**
1) Update to latest MIB (v2.2 => v2.9)
2) Correct scaling factors (matching updated info in MIB)
3) Add Load - confirmed to work

NOTE: Tried running script to collect data - but it's failing. Not sure why ... it seems to think the host doesn't exist, but poller.php works just fine with it.
NOTE: If Current is not supported (some UPS's) ... calculate it from Load (percentage, rated) and Voltage?

Thanks!

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by arrmo** [comment]
OK, I think the issue with the scripts not working is because this is not on a standard port (i.e. not on port 161). Can the scripts handle that? Not seeing a parameter to set that, but it may be me.

Thanks!

**Comment by arrmo** [comment]
Yes, trying to (add tests)! But as above, the test script is failing 😞. Thinking it's because the UPS is not on port 161 ... is there a way to get the script to work on another port?

Thanks!

**Comment by Jellyfrog** [comment]
What does it say? as far as I know the testing should work exactly the same as normal regarding ports

**Comment by arrmo** [comment]
> What does it say? as far as I know the testing should work exactly the same as normal regarding ports

It's rather odd - could be me ... LOL. So if I poll the device,
```
./poller.php -h ups-winserver
LibreNMS Poller
Starting polling run:

Hostname:    ups-winserver
Device ID:   105
OS:          cyberpower
Assigned IP: winServer
```

Proceeds from there, no issues at all - data all valid and good. But, if I try to run the tests,
```
./scripts/collect-snmp-data.php -h ups-winserver -o cyberpower
Script to collect snmp data from devices to be used for testing.
Snmp data is saved in tests/snmpsim.

Usage:
  You must specify an existing device to collect data from.
```

Huh? I did specify an existing device (as poller.php confirms). Thoughts?

Thanks!

**Comment by Jellyfrog** [comment]
You didn't specify variant, it's a required argument

**Comment by arrmo** [comment]
> You didn't specify variant, it's a required argument

I think that's new, no? I don't ever recall doing that in the past ... LOL.

Sorry, but - what is a "variant"? It's not the OS or hostname, not quite sure what it is (and what to use in this case). Thanks!

**Comment by Jellyfrog** [comment]
It's the model/variant. So in your case the model name of your cyberpower ups

**Comment by arrmo** [comment]
> It's the model/variant. So in your case the model name of your cyberpower ups

That was it, thanks! OK, I know I didn't do that in the past ... LOL! But I do like it, good improvement. FYI, I had to use the "variant" that was reported as Hardware, from discovery.

Test Data added now, let's see if all the tests are happy 🤣.

Thanks again.

**Comment by arrmo** [comment]
OK, on the test failures - I have seen that one before 😜. It's because I changed (corrected) the scaling factor. Do I need to remove the older cyberpower.json file?

Thanks!

**Comment by arrmo** [comment]
Yep, that was it! Had to remove the older test data, with the old / incorrect scaling factor.

Thanks for the help!

**Comment by murrant** [comment]
@arrmo it is better to correct the expected data (aka the json file) than to delete it.

**Comment by arrmo** [comment]
OK, NP. It seemed like the naming has changed now - I can re-run / re-capture, then re-name the output files. Make sense?

Thanks!

**Comment by murrant** [comment]
You need to specify variant with -v,  for ones without a variant, just put `-v ''`

**Comment by arrmo** [comment]
> You need to specify variant with -v, for ones without a variant, just put `-v ''`

Thought that was the secret! 😄. But no joy, still only get the following from `collect-snmp-data.php`,
```
1.3.6.1.2.1.1.1.0|4|UPS Local
1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.3808
```

But it's working fine with the poller. For example, the same device,
```
#### Load poller module sensors ####
Checking (snmp) charge Battery Capacity...
100 %
Checking (snmp) frequency Output...
0 Hz
Checking (snmp) load Load...
24 %
Checking (snmp) runtime Battery Runtime...
20.5 Min
Checking (snmp) state Battery Status...
Checking (snmp) state Battery Replace Indicator...
Checking (snmp) state Input Line Cause...
Checking (snmp) state Input Status...
Checking (snmp) state Output Status...
2 #
2 #
1 #
1 #
2 #
Checking (snmp) voltage Battery Voltage...
Checking (snmp) voltage Input Line Voltage...
Checking (snmp) voltage Output Voltage...
24 V
123 V
123 V
```

Thoughts? Very odd that the tests aren't working - with or without a blank variant.

Thanks!

**Comment by murrant** [comment]
collect-snmp-data.php is currently broken :upside_down_face: #12837

**Comment by arrmo** [comment]
LOL! C'mon man, I don't have much hair left to pull out 🤣.

NP, will wait for that fix, then update the test files here. Actually glad to hear this, thought I was losing my mind.

Thanks!

**Comment by arrmo** [comment]
> collect-snmp-data.php is currently broken 🙃 #12837

OK, that helped - thanks! Rebased off of master (after your merge for this correction) ... now data looks better. Not quite sure why the data is failing in some cases now - I looked at the results, but not seeing the issue 😞.

Appreciate it!

**Comment by arrmo** [comment]
Never mind 😜. That was me being stupid - dang it ... missed one old file hanging around (before updating test runs). Tests all clean now!

**Comment by Jellyfrog** [comment]
Since the current test data is from another device, please  don't overwrite it and fix the tests files  manually if possible

**Comment by arrmo** [comment]
> Since the current test data is from another device, please don't overwrite it and fix the tests files manually if possible

I can put the older files back, add a variant name to this one - NP. I admit, wasn't thinking I should do that, but I can 😄.

The issue is that the older file has incorrect scaling factors => when I tried this, then the tests fail. And I'm not sure I see a real way to fix that. Thoughts?

Thanks!

**Comment by arrmo** [comment]
> Since the current test data is from another device, please don't overwrite it and fix the tests files manually if possible

OK, put the old data back in place, set mine up as a variant. Hopefully that's the intention 😄.

As I saw before, some of the legacy data fails - because the scaling factor was incorrect. This is one of the changes, to correct this, as outlined in the MIB (and also here, https://community.librenms.org/t/cyberpower-v2-9-mib/12546/3)

Thoughts?

**Comment by murrant** [comment]
You have to change the specific test data.

The way we capture test data can capture both correct and incorrect values.  So if the code is wrong when the test data is captured, we need to update existing test data.  We should always manually review the data and make sure it looks righ.

**Comment by arrmo** [comment]
> We should always manually review the data and make sure it looks righ.

Gotcha! Modified the single measurement (scaling factor, and corresponding result). All seems OK now.

Thanks!

**Review by murrant — APPROVED** [review]
Nice work!

**Pull request merged**
