### PR TITLE
Fix Junos CPU Discovery

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

- 1st commit add's a proper description to the polled SRX processors, instead of the generic "CPU".
- 2nd commit add's changes the way invalid sensors are skipped, as CPU usage on some elements could return 0 during inactive periods, which would cause the sensor to be removed upon discovery. Tested on MX,SRX,EX. It's a bit hacky but works.

Indexes remains unchanged.

### CODE REVIEW

**Comment by murrant** [comment]
You'll need to add some updated test data because our test data didn't capture that oid...

**Comment by Rosiak** [comment]
Will do.

**Comment by evheros** [comment]
Any update on this one? I see the problem on one of my installs with processor beeing removed so would be nice if we can proceed with this PR.
I tried to get the testdata but my Juniper (QFX) doesn't provide this OID.

**Comment by Rosiak** [comment]
I'll see if I get time to supply the test data, sorry for the wait-time.

**Comment by sjohnson1980** [comment]
Here is some sample data from 4 different platforms, limited to everything under `jnxOperatingTable`, to show relevant data and limit possibly sensitive information.

Let me know if you need the output of more OIDs.

Thanks.

[snmprec_jnxOperatingTable_srx1500.txt](https://github.com/librenms/librenms/files/2812915/snmprec_jnxOperatingTable_srx1500.txt)
[snmprec_jnxOperatingTable_qfx5100.txt](https://github.com/librenms/librenms/files/2812916/snmprec_jnxOperatingTable_qfx5100.txt)
[snmprec_jnxOperatingTable_qfx10k.txt](https://github.com/librenms/librenms/files/2812917/snmprec_jnxOperatingTable_qfx10k.txt)
[snmprec_jnxOperatingTable_ex3400.txt](https://github.com/librenms/librenms/files/2812918/snmprec_jnxOperatingTable_ex3400.txt)

**Comment by murrant** [comment]
@sjohnson1980 thanks, but none of these contain `1.3.6.1.4.1.2636.3.39.1.12.1.1.1.4` or `.1.3.6.1.4.1.2636.3.1.13.1.11`...

If you concerned about the amount of data, it is easy to limit it.

1. First, apply this PR `./scripts/github-apply 9467`
2. Then capture minimum data `./scripts/collect-snmp-data.php -h HOSTNAME -m processors`

**Comment by sjohnson1980** [comment]
`1.3.6.1.4.1.2636.3.1.13.1.11` was there for all of them, but indeed, none of them had `1.3.6.1.4.1.2636.3.39.1.12.1.1.1.4`.

Here's the data with only the `-m processors`
[junos_mx104.snmprec.txt](https://github.com/librenms/librenms/files/2817365/junos_mx104.snmprec.txt)
[junos_srx1500.snmprec.txt](https://github.com/librenms/librenms/files/2817366/junos_srx1500.snmprec.txt)
[junos_qfx5100.snmprec.txt](https://github.com/librenms/librenms/files/2817367/junos_qfx5100.snmprec.txt)
[junos_qfx10k.snmprec.txt](https://github.com/librenms/librenms/files/2817368/junos_qfx10k.snmprec.txt)
[junos_ex3400.snmprec.txt](https://github.com/librenms/librenms/files/2817369/junos_ex3400.snmprec.txt)

Thanks!

**Pull request merged**
