### PR TITLE
New os RAy

### PR DESCRIPTION
**Pull request by erotel**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Nice work @erotel.  Can you explain your core changes?  I'm a bit skeptical since it could increase polling times.

**Comment by erotel** [comment]
since the ray device returns when snmp_get_multi "sysUpTime" was queried and not "sysUpTime.0" I had to modify the loading of these queries



`root@speedtest:/opt/librenms/includes/polling# /opt/librenms/poller.php -h 10.133.7.252 -d -m os
LibreNMS Poller
===================================
Version info:
Commit SHA: 0830a5386409d769b152ac75a521433839654b84
Commit Date: 1507556567
DB Schema: 210
PHP: 7.0.19-1
MySQL: 10.1.26-MariaDB-0+deb9u1
RRDTool: 1.6.0
SNMP: NET-SNMP 5.7.3
==================================DEBUG!
Starting polling run:

SQL[SELECT * FROM `devices` WHERE `disabled` = 0 AND `hostname` = '10.133.7.252' ORDER BY `device_id` ASC]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '11']
Hostname: 10.133.7.252
Device ID: 11
OS: ray

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','1.41','1.99','1.73','11',NOW())]
SNMP Check response code: 0
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:HOSTNAME:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: sysContact.0

sysUpTime = 4192614
sysLocation =
sysName = RAY10_H
sysObjectID = enterprises.33555.1.1

Array
(
)
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:HOSTNAME:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: sysContact.0

sysUpTime = 4192655
sysLocation =
sysName = RAY10_H
sysObjectID = enterprises.33555.1.1

Array
(
    [sysUpTime] => 4192655
    [sysLocation] =>
    [sysName] => RAY10_H
    [sysObjectID] => enterprises.33555.1.1
)
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OvQ -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:HOSTNAME:161 sysDescr.0]
RAy - Microwave link

SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:HOSTNAME:161 snmpEngineTime.0 hrSystemUptime.0]
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: snmpEngineTime.0

hrSystemUptime = 4192685

Uptime seconds: 41927
RRD[update /opt/librenms/rrd/10.133.7.252/uptime.rrd N:41927]
Uptime: 11h 38m 47s
Modules status: Global+ OS  Device
#### Load poller module os ####
SNMP[/usr/bin/snmpget -v1 -c COMMUNITY -OQs -m RAY-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:HOSTNAME:161 deviceName swVer serialNumber]
deviceName = "RAY10_H"
swVer = "*"
serialNumber = 10348114

Hardware: RAY10_H
Version: 4.1.51.0
Features:
Serial: 10348114
`

**Comment by murrant** [comment]
Seems like a bug in the snmp functions to me. Let me take a look.

**Comment by erotel** [comment]
I think there is an error in implementation on a ray device

ray:
`root@speedtest:/opt/librenms# /usr/bin/snmpget -v1 -c public -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:10.133.7.252:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: sysContact.0

sysUpTime = 4509296
sysLocation =
sysName = RAY10_H
sysObjectID = enterprises.33555.1.1
`

linux machine:

`root@speedtest:/opt/librenms# /usr/bin/snmpget -v1 -c public -OQnUst -m SNMPv2-MIB:HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/ray:/opt/librenms/mibs/ray udp:10.133.255.69:161 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0
sysUpTime.0 = 420645588
sysLocation.0 = Sitting on the Dock of the Bay
sysContact.0 = Me <me@example.org>
sysName.0 = R1
sysObjectID.0 = enterprises.8072.3.2.10
`

**Comment by murrant** [comment]
@librenms/reviewers  Right now snmp_get_multi() discards all entries not containing a `.`

Two ways to fix when index is missing:

1. insert at 0, $array[0][$oid]
2. just insert at oid, $array[$oid]

1 fixes this bug more easily
2 seems more correct

How should we fix it?  I lean towards 2.

**Comment by erotel** [comment]
I leave it to you, I'm not a good programmer

**Comment by murrant** [comment]
@erotel It certainly is an error in the device to return a different oid than what was requested, but it is also an error in LibreNMS code to discard the data that was actually returned.

**Comment by murrant** [comment]
@erotel Also, your code looks pretty good to me, nice and clean :)

**Comment by erotel** [comment]
How to proceed? Please correct LibreNMS and I will return the changes in include / polling / core.inc.php?

**Comment by murrant** [comment]
I've tagged the reviewers for input, just wait for now.  Thanks.

**Comment by laf** [comment]
I'd say show the proposed changes to the snmp_get_multi() function.

However I'd also say that @erotel should report this to the vendor. They seem to be breaking the snmp response.

**Comment by erotel** [comment]
Yes, I contact the manufacturer and I will request a snmp repair

**Pull request closed without merging**
