### PR TITLE
newdevice: Added support for Toshiba RemotEye4 devices

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7258

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7312)

### CODE REVIEW

**Comment by kate66** [comment]
I have deployed this and so far it looks great. The values match the webgui for the RemoteEye itself.

**Comment by laf** [comment]
That's all your device reported for batter :(

**Comment by kate66** [comment]
This is still good, please merge!

**Comment by murrant** [comment]
@laf I'm assuming you decided to walk individual oids instead of upsInput and upsOutput?  Or just happened to write it that way?

**Comment by laf** [comment]
@murrant upsInput and Output aren't tables so I default to using the individual values.

**Pull request merged**
