### PR TITLE
feature: Add error checking/exceptions for AD auth group lookups

### PR DESCRIPTION
**Pull request by ekoyle**
NB: this could break existing installations if they are using bad group names (either non-existent or non-unique)

Use `ldap_get_entries` instead of `ldap_get_first_entry` to be able to tell the difference between no matches and an LDAP query failure.  Also check for a non-unique match, as this could be extremely hard to debug otherwise and may lead to unexpected results.

`ldap_get_first_entry` has the same return value (`false`) when there is an error or when there are no results

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
@ekoyle Do you mind if I merge this into PR #7254?

**Comment by ekoyle** [comment]
@murrant: Feel free.

**Comment by murrant** [comment]
Merged.  Thanks.

**Comment by laf** [comment]
I don't use AD but as we've just had issues with changes here in the past, are we sure none of this is going to break existing users installs?

**Comment by murrant** [comment]
@laf this is just more specific error messages.  Should have been in the original nested groups PR.

I did make a comment of the removal of some of the message detail, but didn't think about emitting those in  user_in_group() function.

We might need to check where get_userlevel is called so we don't have uncaught exceptions.

**Comment by ekoyle** [comment]
@murrant: it may change behavior in the case of a non-unique group name or an invalid group name among other valid group names (ie. both bad, but they may currently work anyway)

**Comment by laf** [comment]
I think we should have asked for testers on this and other auth changes, it seems no setups are quite the same.

**Pull request closed without merging**
