### PR TITLE
Add support for ZyXEL IES4206/5206/5212/6217 MSANs

### PR DESCRIPTION
**Pull request by vitalisator**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @vitalisator 
Seems that you have some tests issues, dixit Travis. Let us know when this is ready for review
Bye

**Comment by vitalisator** [comment]
@PipoCanaja LGTM

**Comment by tomarch** [comment]
All my zyxel USG(zywall USG 20, 50 and 100) have lost their processor graph with this PR.
event of one device after the daily update : 
2019-11-13 02:11:37 |   | Processor Removed: zywall 0 Processor

**Comment by PipoCanaja** [comment]
@tomarch it seems that the culprit could be the updated mib file. I'll have a look.

**Comment by PipoCanaja** [comment]
@tomarch The issues seems to be the broken definition for :
zywallZLDCommon		OBJECT IDENTIFIER ::= { zywall 22 }

I added it back in #10824 

Could you please try it doing : 
./scripts/github-apply 10824

Then, you should run a discovery again of the device (or wait 24 hours). 

Let me know

**Comment by tomarch** [comment]
The fix works fine, cpu graph are coming back.
Thanks.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
