### PR TITLE
fix: Allow line returns in snmprec files with the 4x data type

### PR DESCRIPTION
**Pull request by murrant**
Fill in IOS data files
IOS-XE discovery fails, fix that

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

issue: #6434

### CODE REVIEW

**Comment by murrant** [comment]
trigger ci

**Comment by laf** [comment]
No better way to do this to leave the test units human readable? Is it the detection that breaks or the test units that break without this?

**Comment by murrant** [comment]
Tests are incorrect without this, which allowed the incorrect detection to slip through this weekend.  Unfortunately, no way to keep it human readable and stay compatible with snmpsim.

I did change it so it will print out the decoded string if tests fail.

**Comment by laf** [comment]
:(

**Pull request merged**
