### PR TITLE
Updated clusters to show red if at least one host is down

### LINKED ISSUE #2567: red marker on map issue
Hello,

I have a issue with a red marker :
- On the first picture, we can see more devices down
- On don't see the red market on the map.

librenms

When  I zoom on the map, I can see the red marker when device is down.

librenms2

I woold like see the red market on the map , not when I don't zoom the map.

Is it possible ?

André

### PR DESCRIPTION
**Pull request by laf**
Fix #2567 

If a single host in the cluster is down then the icon will now be red to indicate this.

### CODE REVIEW

**Comment by Rosiak** [comment]
Tested, works on my dev install.
:+1:

**Comment by f0o** [comment]
Can it be a gradient?

**Comment by laf** [comment]
It's already slightly translucent: rgba(0,255,0,0.7);

If you have some css in mind then I'm all for it.

**Comment by f0o** [comment]
I'm really spoiled by my worldmap where the marker turns gradually from greem to yellow and finally to red depending on the % of down hosts or ports. It would be awesome if we can do that

**Comment by laf** [comment]
I can do the JS for that I'm sure if someone can do the css.

**Comment by SaaldjorMike** [comment]
Works here as well. If we want to do yellow/red based on % of devices that are down, then I'd suggest making it user definable as I'm sure that there are different views regarding when it should change colour.

**Comment by f0o** [comment]
bump :)

**Comment by aauvinet** [comment]
Hi, 

It's Ok for me.
Thank's a lot,

**Pull request merged**
