### PR TITLE
Update top-devices.inc.php

### PR DESCRIPTION
**Pull request by DreadnaughtSec**
Added text input to exclude a device type from top-devices:
traffic, uptime, ping, cpu, ram

This can be changed later to allow for multiple exclusions. Possibly use a loop to iterate through and build a string and merge it into the SQL query. I just don't know PHP well enough to do it yet.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
You should definitely just use device groups.  Will allow a lot more flexibility.

**Comment by laf** [comment]
@DreadnaughtSec Any response to the last comment?

**Comment by laf** [comment]
Closed due to no feedback. Feel free to reply and we can re-open this.

**Comment by DreadnaughtSec** [comment]
I will come back to this at some point. I have too many projects going on
currently at work. I am just keeping the additions I made since they do the
trick. If I get the chance, I will rework this addition and resubmit,
unless someone beats me to it.

**Pull request closed without merging**
