### PR TITLE
Agent mysql-php7

### PR DESCRIPTION
**Pull request by nerdalertdk**
After upgrading my Mysql server to ubuntu 16.04 and PHP7 the old mysql script did not work
this is a eddited version of Cacti.

### CODE REVIEW

**Comment by f0o** [comment]
this script looks overly complicated, isnt it easier just to port the current one to 7?
I guess it's just minor things that fail...

**Comment by f0o** [comment]
!trigger

**Comment by nerdalertdk** [comment]
@f0o could be poissible, but had to fix the issue fast at my end :) and changeing cacti that allready used mysqli was faster :)

**Comment by Rosiak** [comment]
I agree with @f0o .

**Comment by laf** [comment]
Someone else is going to update the current script to use mysqli so closing this down.

**Pull request closed without merging**
