### PR TITLE
Allow individual devices to be enabled for MIB polling

### PR DESCRIPTION
**Pull request by paulgear**

### CODE REVIEW

**Comment by paulgear** [comment]
Actually, I'm not convinced this will be enough.  Let me dig in a little more.

**Comment by paulgear** [comment]
I tested this today and it works as expected for me.

**Comment by f0o** [comment]
How about exclusion?

The code only handles when the module is enabled but if it's disabled for a host and enabled globally it will just return true, or am I wrong?

**Comment by paulgear** [comment]
I did test that combination, but I think you're right, and that my test wasn't comprehensive enough.

**Comment by paulgear** [comment]
OK - pushed a new version; I don't know why I didn't do it this way in the first place...

**Pull request merged**
