### PR TITLE
ict-pdu os: Fixed polling for state sensor.

### PR DESCRIPTION
**Pull request by vivia11**
Removed if/else statement. Code was reading an index that was out of bounds (for sensor_index greater than 0) resulting in sensor_value of 0 which did not map to any state.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Any context around why this needs changing?

**Comment by vivia11** [comment]
image

The if/else structure was causing the odd behaviour seen above. The first fuse port was correctly assigned a sensor_value, but all other fuse ports (due to the else structure) was given a sensor_value of 0 which does not map to anything.

The code was attempting to append '.0' to the oid and read the snmp value - but no such index exists. Not sure why the if/else structure was originally necessary, as the polling works fine without the if/else as seen below.

image

**Comment by laf** [comment]
Luckily the chap who added this support used our pastebin service and posted his walk in the issue. I used it to test and you are correct this does fix it - however, removing the file also seems to. Can you check that and if so just remove the file please.

**Comment by vivia11** [comment]
Removing the file also works for me.

**Comment by murrant** [comment]
Any chance you could add test data for this device?

https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

**Comment by laf** [comment]
I've added test data.

**Pull request merged**
