### PR TITLE
Dynamic config

### PR DESCRIPTION
**Pull request by laf**
This is the initial dynamic config PR.

### CODE REVIEW

**Comment by laf** [comment]
This PR has been updated to fix the merge conflicts.

**Comment by laf** [comment]
I'll have to update this again due to recent merges. @paulgear any idea on when we can review this / merge as I'm reluctant to fix this branch again only to have to keep fixing it as time goes on :/

**Comment by paulgear** [comment]
I had a version of this branch almost ready to merge and then time got away from me.  If you're happy to resolve the conflicts I'll set some time aside tonight to look at it.

One thing which we need to consider is how much this is going to impact existing users.  I haven't read the migration logic carefully yet.

**Comment by f0o** [comment]
The sqlschema seems to have escapechars on 2nd line.
Currently on phone so cant really tell which but i can see them as black blobs.

**Comment by laf** [comment]
The 2nd line is a lock table and contains back ticks (`)

Is that what you're seeing?

**Comment by f0o** [comment]
Hrm seems to be a bug in the android chrome
I got the insert statement and about every 30chars a black blob that smoothly scrolls with the bar hahaha

**Comment by laf** [comment]
Submitted a new one.

**Pull request closed without merging**
