### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by arjitc**
Depends on #2160

Add the CSS files to index.php

### CODE REVIEW

**Comment by arjitc** [comment]
This is a global UI change/the CSS affects the global UI/style. It adds in rounded edges, shadows etc

**Comment by laf** [comment]
trigger ci

**Comment by laf** [comment]
Proposing we ask everyone to vote on this.

I'm a :+1: :-1: but more a :-1:

**Comment by paulgear** [comment]
Can we see some before & after screenshots? I'm struggling to see the difference.  The main one is gradients on the menus, which I'm fairly :-1: about, but that doesn't seem to be part of this PR.

**Comment by laf** [comment]
As we've had no other feedback on this, I'm proposing we close the PR.

Will close within the next 24 hours, can be re-opened for further discussion if we need to.

**Pull request closed without merging**
