### PR TITLE
docs: create doc for IP-MAC-Address-Search-Feature

### PR DESCRIPTION
**Pull request by kkrumm1**
I know some of this common networking knowledge, I just thought it would nice to have a doc on it. :)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I'm wondering how best to do things like this, we've got a lot of links already and personally I was hoping we'd reduce those rather than add to them.

The doc itself is possibly useful.

**Comment by kkrumm1** [comment]
I was thinking of a Feature Section?

**Comment by laf** [comment]
I'm still not overly happy with our docs and the layout so I'm not sure how to approach this right now. Leave it open for people to have a think.

**Comment by murrant** [comment]
How about a blog?

**Comment by murrant** [comment]
I am pretty certain things like this should be a blog post.  Would be much appreciated if you could convert it to one @kkrumm1. :)

**Pull request closed without merging**
