### PR TITLE
docs: Intro for developing new modules

### PR DESCRIPTION
**Pull request by pobradovic08**
This is (a high level) intro to help getting started with writing a new module. Getting familiar with the location of stuff and what you need to do in order to complete the module can be hard first time you do it. This is basically expanded versions of notes i took while going through this the first few times.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Thanks for writing this @pobradovic08 it is greatly appreciated.  However, new modules should follow the format of the NAC module.

**Comment by pobradovic08** [comment]
@murrant, thanks for the reply. I'll check out the NAC module as soon as I can. Since i didn't go much into details about the code, do you think this is salvageable or is it completely wrong :) ?

**Comment by murrant** [comment]
Definitely salvageable, there is a lot of good info here.

**Comment by kkrumm1** [comment]
Closing for now feel free to reopen when ready

**Pull request closed without merging**
