### PR TITLE
newdevice: Added support for Gude ETS devices

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7116

### CODE REVIEW

**Comment by laf** [comment]
This has vendor junk because I switched from murrant/composer-install and had to run composer install.

All the updates seem safe so I'm leaving them here as I have no idea how to revert this as those files don't show changed in my local install.

**Comment by kristoferus75** [comment]
Hi !

I have added one ats device but i see no states -> which modules i need to activate ? -> sensors activated !

also the sysname seems wrong value !

kind regards

**Comment by laf** [comment]
Works for me

image


sysName is sent from the device so if it's wrong in LibreNMS then it's wrong on the device.

Can you please stop replying to closed pull requests, if you need help please use irc or community forum.

**Comment by kristoferus75** [comment]
the hostname is set on the device  ok i will use the irc or community forum

**Comment by kristoferus75** [comment]
Hi !

The primary power shows not the icon available it shows in red 1100# and the secondary power icon is ok !

Recent Events:
State sensor Primary power has changed from (1200) to (1100)

thanks
kristoferus75

**Pull request merged**
