### PR TITLE
WebUI - Search results for ports

### PR DESCRIPTION
**Pull request by PipoCanaja**
My NOC is complaining that searchs in LibreNMS gives less details on the port descriptions. Which is true for ports with parsed descriptions, following #13143

This PR restores the behaviour for Parsed Descriptions in Search results as well as PortURL, both using $port->getDescription();
It also removes the code in function.php for `generate_port_link()`, thx @murrant .

And a setting could be added to enable shorter display in case necessary (@fbourqui )

Before
Capture d’écran 2022-02-14 à 17 16 42

After
Capture d’écran 2022-02-14 à 17 16 12

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I believe I was simply trying to match the existing behavior.  I would love to see getDescription() deleted.

**Comment by PipoCanaja** [comment]
Right. I only started my researches and hurried up to try to catch next release. 
`generate_port_link()` is also part of the game here. 

I come with a rather simple patch : restore the full ifAlias. 

Will try to dig where this change came from. Should have done it earlier, my colleagues are complaining for a long time :)

**Comment by fbourqui** [comment]
@PipoCanaja
I sent a pull request to your repo that fix the original minigraph display error, https://github.com/PipoCanaja/librenms/pull/2
Added some screenshot so you can see the display error occurring in iftype page (Ports tab).
Could you merge it, it should then update this pull request

**Comment by PipoCanaja** [comment]
Bonsoir @fbourqui 
You can check if it works as expected for you now. 
Thanx for the patch !

**Comment by fbourqui** [comment]
Salut @PipoCanaja 
It looks good to me like that, no complain.

**Review by laf — APPROVED** [review]
LGTM

**Pull request merged**
