### PR TITLE
fix: fping6 validation when fping6 doesn't support IPv6

### PR DESCRIPTION
**Pull request by murrant**
Is the warning appropriate or should I remove it?

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Is it certain versions of fping6 that don't support it and if so, maybe list those in the warning?

**Comment by murrant** [comment]
It was a centos 6 package on rpmforge.  Just a bad package.  But could be others out there or self-complied fping.

These two for sure:
https://centos.pkgs.org/6/repoforge-x86_64/fping-3.9-1.el6.rf.x86_64.rpm.html
https://centos.pkgs.org/6/repoforge-x86_64/fping-3.10-1.el6.rf.x86_64.rpm.html

**Comment by laf** [comment]
Leave the message for now and let's see what people say in reaction to it.

**Comment by murrant** [comment]
@setiseta update the validation to show warning only when IPv6 is disabled.  Then send a pull request so we can merge it for everyone.

**Pull request merged**
