### PR TITLE
Specify radius attributes for auth roles

### PR DESCRIPTION
**Pull request by barryodonovan**
Add back to documentation the accepted radius attribute vales for each role.

I implemented this yesterday and could only find the appropriate values by reading back through the commit logs to their removal.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Hi, the reason they were removed is because there are no fixed roles.  It could be anything.   It might make sense to add them back with context that they are the built in roles and any role name can be set.

**Comment by barryodonovan** [comment]
I've added a clarification that these are the built-in roles but that any role name can be passed. I'm on monthly so haven't seen full RBAC implementation, I will update docs again if required once I've used the feature.

**Review by murrant — APPROVED** [review]
Looks great, thanks!

**Comment by murrant** [comment]
RBAC is implemented, but no management ui exists yet :)

**Comment by barryodonovan** [comment]
I'll look at using what's there but don't think UI is in my skillset!

**Comment by murrant** [comment]
The items:

1. figure out how collect a list of all permissions (probably just in a json file)
2. add a ui to create roles and assign permissions to roles
3. possibly allow permissions added directly to users, (unsure)

**Pull request merged**
