### PR TITLE
add SMART support

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Depends on https://github.com/librenms/librenms-agent/pull/101 .

### CODE REVIEW

**Comment by laf** [comment]
imho the script either needs to auto detect disks (df?) or the disks to poll data for needs to be in a separate config file.

**Comment by VVelox** [comment]
There is sadly no good way to choose what devices too poll automatically. Especially once you begin factoring things in like how Linux and FreeBSD display USB mass storage devices, which don't no SMART.

If we are going to extract the disk config, from script, we should should really just do it with the entire config.

**Comment by laf** [comment]
Sorry I should have been clear, I was talking about the perl script (conversations are just easier here).

**Comment by murrant** [comment]
The poller module could be shortened quite a bit: 
```php
<?php

use LibreNMS\RRD\RrdDefinition;

echo('S.M.A.R.T.');

$name = 'smart';
$app_id = $app['app_id'];

$oid = 'nsExtendOutputFull.5.115.109.97.114.116';
$output = snmp_walk($device, $oid, '-Oqv', 'NET-SNMP-EXTEND-MIB');

$data_points = array(
    'id5',
    'id10',
    'id173',
    'id177',
    'id183',
    'id184',
    'id187',
    'id188',
    'id190',
    'id194',
    'id196',
    'id197',
    'id198',
    'id199',
    'id231',
    'id233',
    'completed',
    'interrupted',
    'readfailure',
    'unknownfail',
    'extended',
    'short',
    'conveyance',
    'selective',
);

foreach (explode("\n", $output) as $line) {
    $full_data = explode(',', $line);
    $disk = array_shift($full_data);  // remove the first item from the array
    $rrd_name = array('app', $name, $app_id, $disk);
    
    $data = array_combine($data_points, $full_data);
    $fields = array();
    $rrd_def = new RrdDefinition();
    foreach ($data as $ds => $value) {
        $rrd_def->addDataset($ds, 'GAUGE', 0);
        $fields[$ds] = is_int($value) ? $value : null;
    }

    $tags = compact('name', 'app_id', 'rrd_def, 'rrd_name');
    data_update($device, 'app', $tags, $fields);
}
```

**Comment by VVelox** [comment]
Updated it to use a separate con fig file now and documented it in the script. Still need to update the docs.

**Comment by VVelox** [comment]
@murrant Tested out your suggestion there and that is breaking polling for me, even after replacing the $tags line with the normal one. Replacing that causes the polling to work, but it stops updating the RRDs.

**Comment by VVelox** [comment]
Updated the extend again it now has a -g option that will guess and test and print out what is most likely a good config for most common disk devices.

**Comment by VVelox** [comment]
Wooho! This is now done.

**Comment by laf** [comment]
Need to use update_application(); now in the poller file + needs a rebase.

**Comment by VVelox** [comment]
rebased and seems to of not gone well

**Comment by VVelox** [comment]
Replaced by https://github.com/librenms/librenms/pull/6181 .

**Pull request closed without merging**
