### PR TITLE
adding opengear hardware model discovery to poller

### PR DESCRIPTION
**Pull request by sjtarik**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by sjtarik** [comment]
@Jellyfrog @murrant sorry to bother but I have an issue submitting this diff. Basically I added a feature (a single oid) for poller to discover hardware model. But the previous feature tests expect that field to be null as opposed to proper value. I tried to modify the previous test data (.json) file but it did not fly. Could you help me to fix the test data? Again this is just for hardware version and a single OID so it is pretty safe for other fields. Thanks.

**Review by TheGreatDoc — CHANGES_REQUESTED** [review]
Please, can you move `includes/polling/os/opengear.inc.php` to the new `LibreNMS/OS/Opengear.php` format?

Also, those snmp_get should be converted to snmp_multi_get.

About the test files, you did a little mess ;) creating the `_hw` variant. Remove both _hw.snmprec and _hw.json and just collect-snmp-data.php without the `--variant hw` then save-test-data.php again.

**Comment by sjtarik** [comment]
working on comments, will send another diff.

**Comment by murrant** [comment]
@sjtarik LibreNMS now supports yaml for this, add:
```yaml
        hardware_mib: OG-PRODUCTS-MIB
        hardware_regex: '/og(?<hardware>\S+)/'
```
to `includes/definitions/discovery/opengear.yaml` and that should get this going.

**Comment by murrant** [comment]
Actually, I'm just going to send a PR with this, thanks @sjtarik

**Pull request closed without merging**
