### PR TITLE
fix: Add device status reason to up messages.

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Isn't that what already happens?

**Comment by murrant** [comment]
No, $response['status_reason'] is empty when the check succeeds.

**Comment by laf** [comment]
If it's empty and you aren't setting it to something non-empty then why is it now going to contain something.

**Comment by murrant** [comment]
@laf I am using $device['status_reason'], which will be the previous status reason ;)

**Pull request merged**
