### PR TITLE
New overview page and new map

### PR DESCRIPTION
**Pull request by laf**
** for those who tested the other one, you will need to run the following command: **
```bash
ALTER TABLE `devices`   DROP `lat`,   DROP `lng`,   DROP `latlng_update`;
```

1 .This will now perform lookups of sysLocation to work out coords (disabled by default whilst people test). Lookups are limited by checking if a device with the same sysLocation has done a lookup within the last 24 hours and use that.
2 .lat / lng coords then stored in the DB.
3. Map is then available by setting the new frontpage to be map.php. Varying options supported to get a map of the area you want. See docs for details.

Would be great for people to test this functionality.

Things to do:

1. Allow users to override the lat/lng coords in web ui.
2. Add a central DB where we can store some common address to lat/lng lookups (maybe data centres, IX's, etc).
3. more depending on feedback.

We will be able to add more geocoding services quite easily.
We will be able to add more map vendors quite easily.

image

### CODE REVIEW

**Comment by laf** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by Rosiak** [comment]
Gogogogogo :)

**Comment by f0o** [comment]
@spinza has a point (perhaps even with both :P)

**Comment by laf** [comment]
Yeah I'll sort those out don't worry :)

**Comment by spinza** [comment]
Sorry :)

**Comment by laf** [comment]
Ok, table name changed along with code to: locations.

At the moment I don't think using the location column as a unique index. The code does a duplication check so unless someone is adding locations manually then for now I'll not do this.

**Pull request merged**
