### PR TITLE
webui: devices table refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

webui unification, in progress, started from @Rosiak PR #7628 and @laf suggestion.
notes: uses css class and js function from PR #7765

before:
screen shot 2017-11-28 at 12 51 08 am

after:
screen shot 2017-11-28 at 12 50 18 am

### CODE REVIEW

**Comment by murrant** [comment]
You also disabled the links to the graphs view here.  I don't think there is another way to get to that view.

**Comment by crcro** [comment]
@murrant ... it was there but not in the screen capture, nonetheless i've updated the layout atm:

screen shot 2017-12-05 at 12 45 52 am

**Comment by laf** [comment]
The layout was a bit 'rubbish' before because of what we tried to fit on. That doesn't work quite so well now:

image

Have to say though, overall it looks a lot cleaner. Something needs to be done about the up / down / icmp / ping status column. That doesn't look nice now. I'm not sure what to suggest other than dropping the up / down and only having it say if it's icmp or ping (i.e if it is down) or wrap the text in something that makes it look a little slicker.

**Comment by murrant** [comment]
Maybe putting up/down in a label like it was before (but not as big)

**Pull request merged**
