### PR TITLE
device: update hwg-ste and add hwg-ste-plus support

### PR DESCRIPTION
**Pull request by tomarch**
Update HWG-STE support:
-disable bulk
-disable discovery and poller that don't work (the poller time goes from 50s to 2sec now)
-remove bits over graph
-add temperature over graph
-update STE-MIB
-remove php file for temperature and sensors (replace by yaml)

Add HWG-STE-PLUS (Same as HWG-STE but with 2 Dry Contacts)
-use same definition as HWG-STE
-dry contact value (open or closed)
-dry contact alarm status (normal or alarm)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I'm assuming people lose the old data with this update?

**Comment by tomarch** [comment]
I suppose nobody have data unless they have disable bulkwalk manually (this device doesn't support bulk).
How to not lose old data (except by create a new os) ?

**Comment by laf** [comment]
The only way to not lose old data would be to match up the indexes.

Are you 100% all of these devices don't work with bulkwalk or just some do some don't?

**Comment by tomarch** [comment]
Sure the hwg-ste-plus don't work with bulkwalk.
For the hwg-ste it's seem to be the same (as seen in #3606) and it's the same os.

**Pull request merged**
