### PR TITLE
Add alert rule option to invert devices and groups "map to" list

### PR DESCRIPTION
**Pull request by louis-oui**
Fix previous PR https://github.com/librenms/librenms/pull/10954 that worked for group in alert rules "map to" but did not with devices

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
looks like the Travis build got stuck again.

**Comment by PipoCanaja** [comment]
This PR is currently being tested a VM that showed the issue of the 1st PR. So far so good.

**Comment by PipoCanaja** [comment]
Merging this.

**Comment by trs80** [comment]
All my alerts got cleared and retriggered after the daily update with this patch, so all my mutes got cleared too.

**Comment by PipoCanaja** [comment]
@louis-oui : any idea about the alerts being cleared and triggered again when applying this patch ?

**Comment by louis-oui** [comment]
@trs80 what do you mean by mutes ? Do you mean acknownledge ?

**Comment by PipoCanaja** [comment]
All alerts get a new created timestamp. And acknowledged alerts get un-acknowledged indeed.

**Comment by louis-oui** [comment]
The problem you mention here is un-acknowledged alert, I am trying to replicate the issue.

Timestamp is a side effect of un-acknowledgment. When alerts are un-acknowledged or ackwowledged, the timestamp changes becauses of "on update CURRENT_TIMESTAMP" on alerts table. This behaviour is misleading : that is the reason for  https://github.com/librenms/librenms/pull/10907

**Comment by louis-oui** [comment]
@PipoCanaja Can you tell me how to replicate the issue ? Tried
 
Reset code to last friday master version
`git reset --hard 25677e5edc2f21408c0691b8baf99ae3da3d4103`

wait for next polling

`git pull`

wait for next polling => no change to acknowledged alerts

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
