### PR TITLE
WIP Fix fping output parsing with duplicates

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
hmm, I wonder if it is breaking tests...

**Comment by laf** [comment]
I've hit retry on one of them to see.

**Comment by laf** [comment]
Still failing :(

**Comment by murrant** [comment]
No feed back from user with issue and I cannot reproduce.

**Comment by laf** [comment]
@murrant Propose we close for now until someone else mentions it

**Pull request closed without merging**
