### PR TITLE
Add phase2 name to fortigate IPSEC sensor.

### PR DESCRIPTION
**Pull request by VirTechSystems**
For VPN tunnels with more than one phase2, the sensor is confusing. 

Using the phase2 value provides a more complete sensor.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jozefrebjak** [comment]
@VirTechSystems we are using same name for phase1 and phase2, so for me its ok, i this help you. Maybe will be good to use P1 NAME P2 NAME (REMOTE IP) in desc, what you think ?

**Comment by VirTechSystems** [comment]
> 
> 
> @VirTechSystems we are using same name for phase1 and phase2, so for me its ok, if this help you. Maybe will be good to use P1 NAME P2 NAME (REMOTE IP) in desc, what you think ?

We use <phase1>-{name} as the phase2 name to keep it unique across the hundreds of tunnels we have.   

How about something like phase1\phase2 (ip) ?

**Comment by jozefrebjak** [comment]
@VirTechSystems I am open to edit it, you need to get test data to get Travis Ok.

You need to run 

`cd /opt/librenms
`
`su librenms -c "./scripts/collect-snmp-data.php -h HOSTNAME or ID of device"
`
and

`su librenms -c "./scripts/save-test-data.php -o fortigate"
`
if you are using different model than is in tests then you need to specify varian with -v

for example like 

`su librenms -c "./scripts/collect-snmp-data.php -h HOSTNAME or ID of device -v 100e" 
`
and so on after changes.

**Comment by VirTechSystems** [comment]
OK, cool.  It looks like I'll have to dust off my development server to get the test data since we don't manage any 100e's .

**Comment by VirTechSystems** [comment]
Err, there's way too much personal info in that data.  The device SN plus the SN of all FAPs. The name and MAC of everything in the device table......

Is there any way to pass without providing all that?

**Comment by jozefrebjak** [comment]
You can collect the snmprec and before save data put <private> to snmprec where you need to and then run save data

**Comment by VirTechSystems** [comment]
Any ideas why it's not passing?  The details make no sense as I can't imagine anything php version specific in what I changed.

**Comment by fbourqui** [comment]
My change request is more clean.
https://github.com/librenms/librenms/pull/10438
VPN sensors Fortigate name: phase1 - phase2 (remote_ip)

As you can have more than one VPN and each of those can have several phase2. All phase 2 of a given VPN will be displayed together due to phase1 name.

**Comment by PipoCanaja** [comment]
Hi @VirTechSystems 
You need to update all tests for the fortigate OS using save-test-data.php on them. And attach the resulting json to this PR. 
You can read the Travis test results in order to find out which are failing.
Thanx

**Comment by PipoCanaja** [comment]
@fbourqui Only one of the 2 PR can be merged, as you imagine. If this one is fine with you, you can probably close your PR.

**Comment by VirTechSystems** [comment]
What do you mean attach it to the PR?  I committed the json and the result to the branch.

And as far as the php version errors, I don't see anything to suggest why two small changes wouldn't be compliant with all versions of php.

**Comment by PipoCanaja** [comment]
You only committed one result, not all of them (fortigate*.json. You need to run save-test-results.php on all tests json that are impacted by the change. If not, Travis will not pass. You can click on the travis failed tests to find out the exact failure it found. In your case, nothing to do with the code, only with the tests. (and the PHP version in the middle,  7.2, is the only one OK because it does not run the JSON tests to save time and CPU)

**Comment by PipoCanaja** [comment]
Travis fails on the 1st issue, so now it fails with tabs instead of spaces.

**Comment by VirTechSystems** [comment]
The only whitespace issue I found was missing two lines on the bottom.  Everything is a space, not a tab.

**Comment by PipoCanaja** [comment]
I suspect that you have "wireless" module enabled which is not the default. So Travis is not happy now. 
https://travis-ci.com/librenms/librenms/jobs/216193594
Could you disable wireless module in your developpement server and re-run the fortigate_fwf60d ?

**Comment by murrant** [comment]
I'm guessing they had local code adding wireless sensors or something.

**Comment by PipoCanaja** [comment]
Thx @VirTechSystems, and @murrant for the tests cleaned

**Pull request merged**
