### PR TITLE
Update mib SNR-ERD

### PR DESCRIPTION
**Pull request by walday**
Update from 2018 ro 2021 year version

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
This doesn't seem to be the same mib?
SNR-ERD vs SNR-ERD-4

**Comment by walday** [comment]
> This doesn't seem to be the same mib? SNR-ERD vs SNR-ERD-4
SNR-ERD-4 - new mib from manufacturer
https://data.nag.ru/SNR%20ERD/SNR-ERD-4/MIB/

**Comment by murrant** [comment]
MIB file names should be named the same as the MIB in LibreNMS to avoid confusion and increase organization.

**Comment by Jellyfrog** [comment]
First of all, thank you for your contribution!

We're closing this due to inactivity, feel free to reopen if you find the time to continue on this!

**Pull request closed without merging**
