### PR TITLE
Mult graphs bits spacing

### PR DESCRIPTION
**Pull request by peelman**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

Before:
Screen Shot 2020-07-06 at 9 43 09 AM

After:
Screen Shot 2020-07-06 at 10 47 59 AM

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by peelman** [comment]
If these changes are received well, I'd be willing to spread similar love to the other includes in this family of files that share similar renderings.

**Comment by murrant** [comment]
Are there any issues with smaller graphs?

**Comment by peelman** [comment]
the original code is still present that handles graphs under 500px wide. i tested from 450px up through 2k.  i added a tier in for >1500px for large screen / NOC display graphs.

the padding is capped, but still scales and follows a similar scaling as the tiny graphs up to its limit (which was arbitrary and picked after some experimentation on my part for what provided space for long interface names or descriptions, vs keeping things close enough to follow the table lines without too much trouble.

**Comment by Jellyfrog** [comment]
Could you also right-align the headers for current/average/maximum? 
And Maybe a space between number and unit, `1.51Gbps` -> `1.51 Gbps`

**Comment by peelman** [comment]
in theory, if if i were to have cleaned up the legends and alignment on device_bits as well...would that be something to add into this PR, or would you rather it be in a seperate one?

**Comment by murrant** [comment]
Your discretion, but this one looks good to go, so might as well merge it and start a new one.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-66-release-changelog-july-2020/12953/1

**Pull request merged**
