### PR TITLE
Convert Config to a facade

### PR DESCRIPTION
**Pull request by Jellyfrog**
TODO:
- [ ] Logging, See https://github.com/librenms/librenms/pull/14364/commits/7505cb8894b7650d3a9f489d192c9dbe0194ddca
- [ ] Fix loading of configs

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@murrant I might have screwed up the logic with Config::load() since it now requires it for linting, help :)

**Comment by murrant** [comment]
Looks like it is getting initialized during the registration stack. (choking in the process config step)

Could either handle the failure there or try to find what calls the facade during register.

**Comment by Jellyfrog** [comment]
First one is:

```
#0 librenms/LibreNMS/Config.php(44): LibreNMS\Config->load()
#1 [internal function]: LibreNMS\Config->__construct()
#2 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(917): ReflectionClass->newInstanceArgs(Array)
#3 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build('...')
#4 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve('...', Array, true)
#5 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve('...', Array)
#6 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make('...', Array)
#7 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\Foundation\Application->make('...')
#8 librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\Container\Container->offsetGet('...')
#9 librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\Support\Facades\Facade::resolveFacadeInstance('...')
#10 librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\Support\Facades\Facade::getFacadeRoot()
#11 librenms/app/Providers/SocialiteListenersServiceProvider.php(27): Illuminate\Support\Facades\Facade::__callStatic('...', Array)
#12 librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\SocialiteListenersServiceProvider->boot()
#13 librenms/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 librenms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(App\Application), Array, Object(Closure))
#16 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(App\Application), Array, Array, NULL)
#17 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\Container\Container->call(Array)
#18 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\SocialiteListenersServiceProvider))
#19 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\SocialiteListenersServiceProvider), 33)
#20 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk(Array, Object(Closure))
#21 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#22 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(App\Application))
#23 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#24 librenms/vendor/nunomaduro/larastan/bootstrap.php(24): Illuminate\Foundation\Console\Kernel->bootstrap()
#25 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(399): require_once('...')
#26 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(400): PHPStan\Command\CommandHelper::PHPStan\Command\{closure}('...')
#27 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(311): PHPStan\Command\CommandHelper::executeBootstrapFile('...', Object(PHPStan\DependencyInjection\MemoizingContainer), Object(PHPStan\Command\Symfony\SymfonyOutput), false)
#28 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(108): PHPStan\Command\CommandHelper::begin(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput), Array, NULL, NULL, Array, '...', NULL, '...', false, false)
#29 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#30 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_98a3b0791\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#31 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_98a3b0791\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#32 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_98a3b0791\Symfony\Component\Console\Application->doRun(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#33 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(127): _PHPStan_98a3b0791\Symfony\Component\Console\Application->run()
#34 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(128): _PHPStan_98a3b0791\{closure}()
#35 librenms/vendor/phpstan/phpstan/phpstan(8): require('...')
#36 librenms/vendor/bin/phpstan(120): include('...')
```

Patching away that gives:

```
Child process error (exit code 1): #0 librenms/LibreNMS/Config.php(44): LibreNMS\Config->load()
#1 [internal function]: LibreNMS\Config->__construct()
#2 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(917): ReflectionClass->newInstanceArgs(Array)
#3 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build('...')
#4 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve('...', Array, true)
#5 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve('...', Array)
#6 librenms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make('...', Array)
#7 librenms/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\Foundation\Application->make('...')
#8 librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\Container\Container->offsetGet('...')
#9 librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\Support\Facades\Facade::resolveFacadeInstance('...')
#10 librenms/vendor/nunomaduro/larastan/src/Methods/Pipes/Facades.php(30): Illuminate\Support\Facades\Facade::getFacadeRoot()
#11 librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167):
NunoMaduro\Larastan\Methods\Pipes\Facades->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
#12 librenms/vendor/nunomaduro/larastan/src/Methods/Pipes/Contracts.php(36):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
#13 librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167):
NunoMaduro\Larastan\Methods\Pipes\Contracts->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
#14 librenms/vendor/nunomaduro/larastan/src/Methods/Pipes/Macros.php(93):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
#15 librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): NunoMaduro\Larastan\Methods\Pipes\Macros->handle(Object(NunoMaduro\Larastan\Methods\Passable),
Object(Closure))
#16 librenms/vendor/nunomaduro/larastan/src/Methods/Pipes/SelfClass.php(25):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
#17 librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167):
NunoMaduro\Larastan\Methods\Pipes\SelfClass->handle(Object(NunoMaduro\Larastan\Methods\Passable), Object(Closure))
#18 librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(NunoMaduro\Larastan\Methods\Passable))
#19 librenms/vendor/nunomaduro/larastan/src/Methods/Kernel.php(67): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 librenms/vendor/nunomaduro/larastan/src/Methods/Extension.php(42): NunoMaduro\Larastan\Methods\Kernel->handle(Object(PHPStan\Reflection\ClassReflection), '...')
#21 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(386):
NunoMaduro\Larastan\Methods\Extension->hasMethod(Object(PHPStan\Reflection\ClassReflection), '...')
#22 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(458): PHPStan\Reflection\ClassReflection->hasMethod('...')
#23 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3416): PHPStan\Type\ObjectType->hasMethod('...')
#24 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/TypeSpecifier.php(440):
PHPStan\Analyser\MutatingScope->getMethodReflection(Object(PHPStan\Type\ObjectType), '...')
#25 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Comparison/ImpossibleCheckTypeHelper.php(156):
PHPStan\Analyser\TypeSpecifier->specifyTypesInCondition(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\TypeSpecifierContext))
#26 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Comparison/ConstantConditionRuleHelper.php(37):
PHPStan\Rules\Comparison\ImpossibleCheckTypeHelper->findSpecifiedType(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\StaticCall))
#27 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Comparison/ConstantConditionRuleHelper.php(46):
PHPStan\Rules\Comparison\ConstantConditionRuleHelper->shouldSkip(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\StaticCall))
#28 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Comparison/IfConstantConditionRule.php(36):
PHPStan\Rules\Comparison\ConstantConditionRuleHelper->getBooleanType(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\StaticCall))
#29 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(102):
PHPStan\Rules\Comparison\IfConstantConditionRule->processNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope))
#30 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(95):
PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope))
#31 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(460):
PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope))
#32 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(380):
PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope))
#33 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(325):
PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#34 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(475):
PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#35 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(325):
PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#36 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(553):
PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#37 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(325):
PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#38 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(525):
PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#39 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(296):
PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#40 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(189): PHPStan\Analyser\NodeScopeResolver->processNodes(Array,
Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#41 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(143): PHPStan\Analyser\FileAnalyser->analyseFile('...', Array,
Object(PHPStan\Rules\Registry), NULL)
#42 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
#43 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110): _PHPStan_98a3b0791\Evenement\EventEmitter->emit('...', Array)
#44 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
_PHPStan_98a3b0791\Clue\React\NDJson\Decoder->handleData(Array)
#45 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_98a3b0791\Evenement\EventEmitter->emit('...', Array)
#46 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
_PHPStan_98a3b0791\React\Stream\Util::_PHPStan_98a3b0791\React\Stream\{closure}('...')
#47 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_98a3b0791\Evenement\EventEmitter->emit('...', Array)
#48 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):
_PHPStan_98a3b0791\React\Stream\DuplexResourceStream->handleData(Resource id #4709)
#49 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):
_PHPStan_98a3b0791\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#50 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(106): _PHPStan_98a3b0791\React\EventLoop\StreamSelectLoop->run()
#51 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259):
PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#52 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856):
_PHPStan_98a3b0791\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#53 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259):
_PHPStan_98a3b0791\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand), Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#54 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
_PHPStan_98a3b0791\Symfony\Component\Console\Application->doRun(Object(_PHPStan_98a3b0791\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_98a3b0791\Symfony\Component\Console\Output\ConsoleOutput))
#55 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(127): _PHPStan_98a3b0791\Symfony\Component\Console\Application->run()
#56 phar://librenms/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(128): _PHPStan_98a3b0791\{closure}()
#57 librenms/vendor/phpstan/phpstan/phpstan(8): require('...')
#58 librenms/vendor/bin/phpstan(120): include('...')
```

**Comment by Jellyfrog** [comment]
The problem is that load is called in the construct I suppose, not sure where else we could put it

**Comment by murrant** [comment]
#
Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.

Please feel free to reopen, I would love to see your changes added to LibreNMS.

**Pull request closed without merging**
