### PR TITLE
allow displaying special character in description

### PR DESCRIPTION
**Pull request by tomarch**
I need to put some html link in this description field

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7386)

### CODE REVIEW

**Comment by murrant** [comment]
Could you use the procedure field?

**Comment by tomarch** [comment]
No, procedure url is not what i'm looking.
I have one wiki page for all my device, and i need a link to it.

**Comment by murrant** [comment]
Oh yeah, procedures are for alert rules.

I'm very cautious when it comes to displaying user editable data as html, for security reasons.  I'm not sure of how safe this would be.

**Comment by laf** [comment]
Unfortunately this allows for xss:

image

As an example of how to allow certain html code see: `html/includes/common/notes.inc.php`

**Pull request closed without merging**
