### PR TITLE
Updated Nginx Install Doc

### PR DESCRIPTION
**Pull request by vectr0n**
Updated the nginx vhost to switch from including fastcgi.conf to fastcgi_params due to ubuntu not having a fastcgi.conf like debian. Also removed two mentions of Apache.

### CODE REVIEW

**Comment by laf** [comment]
Sorry this needs a rebase, not sure why but it is showing as the whole file being new for some reason.

**Comment by vectr0n** [comment]
How would one go about doing that? This is my first time ever using github.

**Comment by laf** [comment]
Depends on how you've got things setup but: 'git pull upstream master' should pull in the latest changes from the master branch, it will most likely complain and that's where you have to figure our what conflict is there.

**Comment by vectr0n** [comment]
I have done everything from the website, so no idea. I guess it would just be easier to delete the whole doc as none of this makes any sense to me.

**Pull request closed without merging**
