### PR TITLE
fix json-app-tool

### PR DESCRIPTION
**Pull request by VVelox**
- `string_to_oid` is a local function in the script. No require needed.
- Now also adds in the  `deleted_at` as well.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by laf — APPROVED** [review]
LGTM

**Comment by VVelox** [comment]
> I'm going to send a PR to remove string_to_oid, we don't need to duplicate code.

@murrant  The purpose of this PR was to unbreak this. I wrote it intentionally that way originally so it did not require depending on the rest of the source tree. As it was previously it would break if used outside the source tree with all the other php stuff installed.

**Comment by murrant** [comment]
why is it being used outside the source tree?  I just looked at it and considered porting it to an lnms command.

**Comment by VVelox** [comment]
> why is it being used outside the source tree? I just looked at it and considered porting it to an lnms command.

@murrant  It is a dev tool.  I keep a copy of it in `~/bin/`, which is why I did not notice this breakage sooner.

Using it on a checkout from git would not work with how it was or with it being tied to lnms.

**Comment by murrant** [comment]
@VVelox why not just keep a symlink to it in ~/bin?

**Comment by VVelox** [comment]
> @VVelox why not just keep a symlink to it in ~/bin?

@murrant Even then it has the issue of not working just out of a git checkout. Keeping the function where it is keeps everything nice and simple for something that is meant to be a stand along tool. The functionality of this code is not going to change for what it is created for.

**Comment by murrant** [comment]
@VVelox hmm, perhaps it shouldn't be part of the LibreNMS repo then.  Like a separate repo.

**Comment by VVelox** [comment]
> @VVelox hmm, perhaps it shouldn't be part of the LibreNMS repo then. Like a separate repo.

@murrant Hmm... that definitely sounds like an idea. Create one with a bunch of tooling disconnected to poke at stuff like that. :3

Think I found my next weekend project. <3

**Pull request merged**
