### PR TITLE
Fix Temperature Sensor for AirOS 8.7.4+

### PR DESCRIPTION
**Pull request by JKJameson**
https://github.com/librenms/librenms/issues/13647

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
This doesn't look correct according to the test data we got

**Comment by JKJameson** [comment]
I can't seem to get the tests to pass. Could someone share some insight as to why this is failing? This whole process is a bit convoluted for a simple number change which fixes things on my side.

**Comment by Jellyfrog** [comment]
> I can't seem to get the tests to pass. Could someone share some insight as to why this is failing? This whole process is a bit convoluted for a simple number change which fixes things on my side.

Because according to our test data your fix does not seem valid.
You're trying to divide 66 with 10000000.
Maybe it something that changed in newer firmwares? I'd recommend you find the latest MIB and check if there is some clue there

**Comment by JKJameson** [comment]
LibreNMS was recording the temperature as 450 Million degrees Celsius before. Here's the graph with my patch applied.  Good luck trying to get any updated MIB from Ubiquity themselves. If I can contribute anything from the devices please let me know.

Hopefully I'm not the only person monitoring AirOS devices and someone else can chime in with their findings too. Clearly whatever test data you have is no longer valid.

image

image

**Comment by murrant** [comment]
Stupid stuff.  Almost all my airos devices show normal temperatures, except 5.  I think it is airos 8.7,  setting this for all airos would probably break more than it fixes.

**Comment by murrant** [comment]
After looking closely, only 8.7.4 has this issue.  (We don't have any at 8.7.5)   Can you confirm if it reports these bad values on 8.7.5?

**Comment by bile0026** [comment]
I can confirm 8.7.5 reports bad values. Just updated our radios a couple weeks ago and got slammed with temp alerts. Had to shut off temp alerting for now.

**Review by murrant — APPROVED** [review]

**Comment by bile0026** [comment]
Looks like ubiquiti noticed their oops and possibly fixed it in 8.7.7. Going to find a time to upgrade one of my test radios and see. So this might either need logic for the affected versions only. 

image

**Comment by bile0026** [comment]
> What a joke. My next network will be Mikrotik powered. A big thanks to @murrant for the effort regardless.

Generally I'm a fan of their Airmax gear but UniFi and edge switch/route is less than desirable. They have been slipping though. MikroTik all the way for route/switch and I'm starting to like their wireless more and more. They might not have the latest Wi-Fi 700 but it's pretty darn solid. 

I also echo the thanks to @murrant

**Comment by murrant** [comment]
HAHA, I suspected that would happen.  I can easily update the code to only do 8.7.4 to 8.7.6

**Comment by bile0026** [comment]
Confirmed, airos 8.7.7 fixes the snmp issue. LibreNMS version 22.1.0.

**Pull request merged**
