### PR TITLE
Wireless support for Asuswrt-Merlin (the same as Openwrt)

### PR DESCRIPTION
**Pull request by arrmo**
Wireless sensor support, for Asuswrt-Merlin (modeled off of / identical to Openwrt).

I did try to run `./scripts/save-test-data.php -o asuswrt-merlin`, but it's failing in the latest LibreNMS code?

Thanks!

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by arrmo** [comment]
Yes, did try to run and add the test data - it wasn't clear (my bad!), but had noted this above. It seems that the tests are failing in the latest LibreNMS code?
`I did try to run ./scripts/save-test-data.php -o asuswrt-merlin, but it's failing in the latest LibreNMS code?`

Thoughts?

Thanks!

**Comment by arrmo** [comment]
OK, figured out the "fun" 🤣. A mix of pip and pip3 => got it working!

Update coming, with data added.

Thanks!

**Comment by Jellyfrog** [comment]
You should remove `includes/polling/os/asuswrt-merlin.inc.php` and implement those functions is your new fancy OS class :)

**Comment by arrmo** [comment]
Sorry, you lost me there 😆. Are you saying that Polling (not just Discovery) moves to the new file (LibreNMS/OS/AsuswrtMerlin.php)? Sorry, didn't do this in OpenWrt, so not quite sure what you're after.

Thanks!

**Comment by TheGreatDoc** [comment]
@arrmo the info that is retrieved in `includes/polling/os/asuswrt-merlin.inc.php` shouldnt never been in polling but in discovery. You dont have to refresh the version, hardware, serial fields every poll cycle, its OK every discovery cycle, so it is now done in the OS class.

Take a look to other OS class and prepend to your actual class and remove the old file.

**Comment by arrmo** [comment]
Yep, I see what you're talking about - you bet, will update this.

Thanks!

**Comment by arrmo** [comment]
Thanks for pointing out the discoverOS item - much appreciated. Updated (and removed the older poller file, as you noted).

**Comment by TheGreatDoc** [comment]
Rebuild the test data and commit it to make it work (Travis CI failed)

**Comment by arrmo** [comment]
> Rebuild the test data and commit it to make it work (Travis CI failed)

Done - thanks! I was wondering about that. I get fooled sometimes, as one of the scripts doesn't seem to overwrite old data (happened to me before).

**Comment by paulierco** [comment]
@arrmo Is this the same as [this](https://docs.librenms.org/Support/Device-Notes/Openwrt/) ?

Yesterday i tested this and i had some issues that were not mentioned in the documentation.
1. You should specify that package "snmp-mibs-downloader" is installed. Or (sudo apt-get install snmp-mibs-downloader).
2. "Extend" SNMP feature is missing on the OpenWrt version 18.06.5. I had to edit the file (/etc/init.d/snmpd)  that generate the config to fix this. I don't know if this has been fixed to version 19.07.3.
3. In order to work, i had to make sure that the OpenWrt is really discovered as OpenWrt, otherwise script will not work. The [default librenms-distro](https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro) does not work.  This [one](https://community.librenms.org/t/distro-script-for-openwrt/5079) works. I think you should add this in the documentation.
4. Please specify permision, all script files does not work if permision is not fixed.

**Comment by arrmo** [comment]
> @arrmo Is this the same as [this](https://docs.librenms.org/Support/Device-Notes/Openwrt/) ?

Yes, it is!

> Yesterday i tested [this](https://docs.librenms.org/Support/Device-Notes/Openwrt/) and i had some issues that were not mentioned in the documentation.
> 1. You should specify that package "snmp-mibs-downloader" is installed. Or (sudo apt-get install snmp-mibs-downloader).

Sure, I can add that. I admit, that's been on my machine for a long time (and for a lot of other devices) ... LOL. But good to capture, agree with you.

> 2. "Extend" SNMP feature is missing on the OpenWrt version 18.06.5. I had to edit the file (/etc/init.d/snmpd)  that generate the config to fix this. I don't know if this has been fixed to version 19.07.3.

You've got me there, that's a more generic OpenWrt issue - extend has been in SNMP for a long time now.

> 3. In order to work, i had to make sure that the OpenWrt is really discovered as OpenWrt, otherwise script will not work. The [default librenms-distro](https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro) does not work.  This [one](https://community.librenms.org/t/distro-script-for-openwrt/5079) works. I think you should add this in the documentation.

Agreed! Will do. And you are right, the OS has to be detected correctly of course for this to work.

> 4. Please specify permision, all script files does not work if permision is not fixed.

Meaning they need to be executable? Yes, I can add that.

**Comment by arrmo** [comment]
Updated - thanks!

**Comment by arrmo** [comment]
Hi,

Just checking in, in case this is waiting on me (and I don't know it ... 😆). Anything needed here? NP if not, just wanted to make sure if I should be doing something.

Thanks!

**Comment by SourceDoctor** [comment]
This PR seems to break Travis tests:

`There was 1 failure:

1) LibreNMS\Tests\DocsTest::testDocExist

The doc Support/Device-Notes/AsuswrtMerlin.md doesn't exist in mkdocs.yml, please add it to the relevant section
`

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-67-release-changelog-august-2020/13285/1

**Pull request merged**
