### PR TITLE
Fix SQL injection vulnerability in MAC Accounting graph

### PR DESCRIPTION
**Pull request by murrant**
SQL injection vulnerabilities in mishandled user input for the mac_acc_total graph.

Thanks to @hodorsec for the vulnerability report https://twitter.com/hodor_sec

I didn't have any real test data, so tried to keep the changes minimal.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by SourceDoctor — APPROVED** [review]
LGTM
nethertheless i personally would use [filter_input](https://www.php.net/manual/de/function.filter-input.php) instead of `GET` to have a type validation

**Comment by murrant** [comment]
I prefer to use full input validation, but these are legacy files :D

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-october-2020-info/13838/1

**Pull request merged**
