### PR TITLE
Adding active directory authentication to librenms

### PR DESCRIPTION
**Pull request by fstern**
This adds Microsoft Active Directory authentication to librenms. 

This makes it easier than using the already existing LDAP authentication plugin. Adding Active Directory authentication to the existing LDAP plugin would have required a nearly complete rewrite. 
Also sticking to just Active Directory let me make some assumptions of attributes being in place already. 

This plugin has been in use for about a month now without any apparent problems.

### CODE REVIEW

**Comment by laf** [comment]
This is awesome @fstern 

Scrutinizer has picked up on some small issues, the only things of any worth changing is the functions that just return 0, you can remove the variables that are passed to them. I.e:

```php
function reauthenticate($sess_id, $token) {

to

function reauthenticate() {
```

**Comment by laf** [comment]
Actually one other thing, where you have:

```php
} else {
or
} elseif {
```

Can you change these to:

```php
}
else {
or

}
elseif {
```

**Comment by fstern** [comment]
@laf Changes are incorporated, thanks for looking over it.

**Comment by paulgear** [comment]
Hi @fstern - thanks for this.  I know it's already been merged, but would you mind changing the 'auth_ad_dont_check_certificates' option to be 'auth_ad_check_certificates'?  Options should consistently be used for turning features on, not off.  You can keep the same semantics by changing the default value to the opposite.

**Pull request merged**
