### PR TITLE
feature: Added ability to whitelist ifDescr values from being ignored with good_if

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #6581 

I'm not 100% sure this is the best approach but it will also solve the issue we've had before where users want to remove an item from bad_if so have to unset the whole array and add the others back in.

### CODE REVIEW

**Comment by murrant** [comment]
@laf what do you think about removing the global bad_if and moving it into yaml/per is?

**Comment by laf** [comment]
I don't think we will know which devices do / don't have interfaces we will ignore and it's going to duplicate a lot of config in yaml (imho)

**Comment by murrant** [comment]
Probably, but I feel like we could remove some from the global that only make sense on one OS.  However, tracking those down may not be feasible.

... If you can't tell, I'm not a fan of bad_if :D

**Comment by laf** [comment]
It's the tracking down that would be hard, we could obviously just remove them, add the ones we have in our installs to the correct OS and then see what is reported to us, however.....

  - it's a lot of duplication imho hence why bad_if isn't actually that bad
  - it will generate more 'support' noise which I don't particularly want :)

This approach is blacklist bulk, whitelist specific which seems to be a more logical approach no?

**Comment by murrant** [comment]
@laf  Ok, sounds good, but can you please add a good_if for this:  https://github.com/librenms/librenms/issues/3263

**Comment by laf** [comment]
Sure thing. Will do it later on.

**Comment by laf** [comment]
Done

**Pull request merged**
