### PR TITLE
Rocketchat no message

### PR DESCRIPTION
**Pull request by svennd**
If some people also face this issue : the transport works in rocket.chat, but contains no message. This is the script "required" for the webhook integration : 

```
class Script {
  process_incoming_request({ request }) {
    console.log(request.content);

    return {
      content:{
        text: request.content.text
       }
    };

    return {
       error: {
         success: false,
         message: 'Error example'
       }
     };
  }
}
```
Once this change has been done, it works for me. (nothing fancy as coloring) 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I'm not a rocket.chat user but the original looks like it should work ok, I'd prefer to fix it if needed rather than change how it works.

**Comment by svennd** [comment]
@laf I searched the rocket.chat for a solution why it did not work (as described in the docs), but they all pointed towards this solution. So I kinda wanted to share it. However the current code is just a copy of slack, which might have worked before (?) but for the latest version for sure does not work.

For sure, close it, if someone ever has a similar problem you can pick it up later. :) no bad feelings.

**Comment by laf** [comment]
Do you have any links to show that this is the way it should be done? Sending text= is also fine but so is sending as attachments.

**Comment by svennd** [comment]
https://rocket.chat/docs/administrator-guides/integrations/

Both methods seem fine, but I did not get the attachment method working. Perhaps @ToeiRei can pitch in ? Perhaps its just documenting it better on how to use it ?

**Comment by ToeiRei** [comment]
In my case, notifications look like that:

> 
> LibreNMS @rocket.cat BOT 23:56:02 
> Device 10.0.0.8 recovered from Device rebooted 
> Device 10.0.0.8 recovered from Device rebooted 
> Severity: critical 
> Time elapsed: 5m 
> Timestamp: 2017-03-28 21:55:05 
> Unique-ID: 1885 
> Rule: Device rebooted 
> Faults: 
> #1: sysObjectID => enterprises.8072.3.2.8; sysDescr => Hardware: amd64; 
> Alert sent to: NOC

That's all I need. Not sure what the problem really is.

**Comment by svennd** [comment]
Ah well, then I guess its a problem on my end. Closing this :) thx all !

**Comment by laf** [comment]
@svennd you can run alerts.php with -d to get more debug output, you will only get it if an alert is due to be sent which means if the cron job gets to it before you do then you won't see anything. Could be worth just disabling the alerts.php in cron before testing.

**Comment by ToeiRei** [comment]
@svennd what did you do at the rocket.chat config side?

**Pull request closed without merging**
