### PR TITLE
Make new dashboard the default

### PR DESCRIPTION
**Pull request by laf**
Proposing to set the default dashboard to the new tiles one.

Merge or close, no big deal but as this provides more flexibility on a per user basis then we should seriously consider it.

### CODE REVIEW

**Comment by f0o** [comment]
:+1: under the condition of providing a default set of widgets so people can start right away :)

**Comment by laf** [comment]
@f0o no user is created by default so can't do this for new installs, yes we could do it for existing installs - thoughts on this?

**Comment by Rosiak** [comment]
It's OK with me. 
Perhaps we should make a notification box of some kind, to address the issue raised by @f0o ?

**Comment by laf** [comment]
A notification exists on the tiles page when you go to it telling you to add a widget.

**Comment by f0o** [comment]
@laf how about adding that to the add-user functions?
like a skeleton

**Comment by laf** [comment]
@f0o 

Feel free :)

**Comment by vitalisator** [comment]
good idea, I like the new tiles page.
@f0o, I think that will be the right way with add-user function.

**Comment by paulgear** [comment]
I'm getting a little corruption - see screenshot: http://libertysys.com.au/imagebin/1wY9uD31.png
Maybe it's not that big a deal; don't know.  I feel like the tiles page is not quite as smooth as it could be, but happy to go with whatever the majority thinks is right for the default.  I certainly will use it as my front page.

**Comment by laf** [comment]
That's because the tile isn't big enough for the data, we can look to see if you can resize automatically or something else. Codes open for others to look at :)

**Comment by paulgear** [comment]
Since a resize fixes this, and it's definitely superior to the default, let's do it.

**Pull request merged**
