### PR TITLE
Added basic detection for Mellanox devices

### PR DESCRIPTION
**Pull request by laf**
Should provide what is needed in #1328

### CODE REVIEW

**Comment by f0o** [comment]
Is there any licensing information on the logo?

**Comment by laf** [comment]
Logo taken from www.mellanox.com/page/media_kit

**Comment by f0o** [comment]
From the license linked in the media-kit it sounds like they want a line as: 'Logo courtesy of Mellanox' - Do you think you could squeeze that in? Or did I just misread that?

**Comment by paulgear** [comment]
If they have license requirements, we should do our best to comply.

**Comment by paulgear** [comment]
I wonder whether this is going to break NX-OS discovery on some devices.

**Comment by laf** [comment]
?

**Comment by paulgear** [comment]
@laf We've got a change to NX-OS detection in includes/discovery/os/nxos.inc.php that may have unanticipated consequences.

**Comment by laf** [comment]
Yeah now I see what you mean - moved to sysObjectID so should be good now.

**Comment by paulgear** [comment]
@laf We probably should revert to the old NX-OS detect string as well.  Although, I did check two different versions of NX-OS we have at work, and they both contained the "(tm)" part.

**Comment by laf** [comment]
@paulgear If we put NX-OS detection back to just NX-OS then nxos.inc.php will pick up Mellanox devices wouldn't it. Cisco IOS detection also uses (tm) so I doubt this will be any different and something Cisco will drop.

**Comment by laf** [comment]
Thanks @ernstae .

PR updated.

**Pull request merged**
