### PR TITLE
Add Radwin OS Wireless Sensors

### PR DESCRIPTION
**Pull request by vivia11**
Hello,

Adding wireless discovery for distance, tx/rx power and RSSI.
I've tested with Radwin 5000 base and subscription units.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by MrMaus13** [comment]
Works great; 
Tested with RW-2250-B350, RW-5200-2250, RW-5520-2150, RW-5050-2250, RW-5550-2150.

**Comment by tracernz** [comment]
It would be nice to include some test data to ensure this doesn't get broken in future. Info at https://docs.librenms.org/#Developing/os/Test-Units/

**Comment by laf** [comment]
Yes please, test data needed :)

**Comment by MrMaus13** [comment]
Not sure how this works, but why the general failure?
```
./scripts/collect-snmp-data.php -h 1322 -m os
OS: radwin
Module(s): os

Capturing Data: Error in packet
Reason: (genError) A general failure occured
Failed object: SNMPv2-SMI::enterprises.12148.10.2.6.0

Error in packet
Reason: (genError) A general failure occured
Failed object: snmpEngineTime.0

Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: hrSystemUptime.0

 sysDescr.0 sysObjectID.0 sysName.0 SNMPv2-MIB::sysDescr.0 SNMPv2-MIB::sysObjectID.0 .1.3.6.1.4.1.12148.10.2.6.0 sysUpTime.0 sysLocation.0 sysContact.0 snmpEngineTime.0 hrSystemUptime.0 1.3.6.1.4.1.4458.1000.1.1.30.0 1.3.6.1.4.1.4458.1000.1.1.3.0 1.3.6.1.4.1.4458.1000.1.1.2.0 1.3.6.1.4.1.4458.1000.1.1.29.0

Updated snmprec data /opt/librenms/tests/snmpsim/radwin.snmprec

Verify this file does not contain any private data before submitting!
```

**Comment by laf** [comment]
Those are just because the OIDs we are asking for don't exist. Ignore them, if it's created the file then that's all you need.

**Comment by vivia11** [comment]
Added in test data for the three different versions I have access to.

**Comment by tracernz** [comment]
Looks good. :+1: If you run `./scripts/save-test-data.php -o example-os -m <module>` it should do a discovery and poll with that test data, and save the discovery and polling results into `/tests/data/` . As I understand it that completes the loop so your discovery/polling will always be tested in CI to ensure the results don't change.

**Comment by vivia11** [comment]
@tracernz 
I'm having trouble with snmpsim on my machine, so I can't generate the json. Is it possible for the json to be generated by someone else from my snmprec files?

**Comment by laf** [comment]
Ok, i've generated the json files. Hopefully travis passes then we can merge in.

**Comment by tracernz** [comment]
I wonder if something is missing from tests/module_tables.yaml because those files are all empty.

**Comment by tracernz** [comment]
I gave this a try... the data appears to be discovered/polled correctly and inserted into the DB... but nothing comes out.. https://gist.github.com/tracernz/e0b8d23655e6323b7e958da6b9a8a784

And so I tried a different device/module on this branch... and it gave an empty array also. So I checked out master from a few days ago(bbd16dd2d) and it worked with that device/module... Then I checked out current master (69bedd01) and no test data! It's the master branch that's broken and it broke within the last 5 days.

**Comment by tracernz** [comment]
With #8399 merged on top of this branch I captured the data. Can't push to your branch though so here's the data: https://gist.github.com/tracernz/d5467c050e2f779921458966628c25b4

**Comment by laf** [comment]
Thanks @vivia11 (and @tracernz)

**Pull request merged**
