### PR TITLE
Python dispatcher service v2

### PR DESCRIPTION
**Pull request by murrant**
Ping support and a lot of refactoring.
Most code for each queue is in a specific queue manager class now.
Now uses queue that restrict duplicate entries, making things simpler

Will need notification, as it requires Redis 5.x and  3.x of the Redis plugin to support ordered sets.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@laf in my testing it ran better.  This is complete.  I'm 80% sure there are no bugs.

A newer version of redis and redis-py is required, so caution.  I still need to update the docs and this needs notification before merging.

**Comment by laf** [comment]
> A newer version of redis and redis-py is required, so caution. I still need to update the docs and this needs notification before merging.

What versions?

**Comment by murrant** [comment]
redis 5.x and redis-py  3.x

**Comment by murrant** [comment]
@laf fixed one thing I wasn't sure about (discovery not running on timer)

**Comment by murrant** [comment]
@laf I'm confident of this.  It is also a decent bit more efficient than the old code.

**Comment by murrant** [comment]
Hmm, seeing a little gapping with this on my testing

**Comment by laf** [comment]
> Hmm, seeing a little gapping with this on my testing

Ok let me know when you think you've fixed it. Like I said I'd be testing in prod so I really don't want to lose data.

**Comment by murrant** [comment]
@laf false alarm.  Those gaps are due to device not responding during times of high cpu usage.  Unrelated to this I just hadn't noticed it before because it isn't on the main devices I look at.  Consolidation hides the missing data after a week.  So I had to check specific data to see that it was occurring before switching.

**Comment by murrant** [comment]
Now handles db failures "gracefully" so it will keep trying instead of just stopping.
If too many db failures happen, it will attempt to release the master dispatcher to another node.

Fixes #10138 in an integrated way

**Comment by laf** [comment]
Testing on my dev install before I try on our live.

**Comment by twelch24** [comment]
I've been running this service on a 3-node distributed poller setup for a couple of hours now. I'm seeing a significant drop in cpu usage on all three, and no issues to report.

**Comment by adammmmm** [comment]
Seems to run fine here too, with distributed pollers but getting loads of exceptions in the journal:

Traceback (most recent call last):
  File "/opt/librenms/LibreNMS/queuemanager.py", line 54, in _service_worker
    device_id = self.get_queue(queue_id).get(True, 10)
  File "/opt/librenms/LibreNMS/__init__.py", line 307, in get
    item = self._redis.bzpopmin(self.key, timeout=timeout)
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/client.py", line 2409, in bzpopmin
    return self.execute_command('BZPOPMIN', *keys)
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
Poller_0-2(ERROR):Poller poller exception! Error while reading from socket: ('Connection closed by server.',)
Traceback (most recent call last):
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/librenms/LibreNMS/queuemanager.py", line 54, in _service_worker
    device_id = self.get_queue(queue_id).get(True, 10)
  File "/opt/librenms/LibreNMS/__init__.py", line 307, in get
    item = self._redis.bzpopmin(self.key, timeout=timeout)
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/client.py", line 2409, in bzpopmin
    return self.execute_command('BZPOPMIN', *keys)
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
Discovery_0-4(ERROR):Discovery poller exception! Error while reading from socket: ('Connection closed by server.',)
Traceback (most recent call last):
  File "/opt/librenms/.local/lib/python3.6/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

**Comment by murrant** [comment]
Update your redis python library as you have been notified.
`pip install -r requirements.txt`

**Pull request merged**
