### PR TITLE
Remove high limit on UPS charge sensors

### PR DESCRIPTION
**Pull request by mpikzink**
A fully charged UPS should not require any maintenance. 100% charge is the default state when the device is online.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by mpikzink** [comment]
What do the experts think about this PR?
I also see that the "low" and "low_warn" states are hard-coded, but differ. I think at less than 50% there could be a warning and below 15% it is critical. My experience is that if you are below 10% UPS charge, older devices often crash.

**Comment by laf** [comment]
What harm does having the limit set to 100 do?

**Comment by mpikzink** [comment]
Screenshot from 2024-12-10 07-11-35
Screenshot from 2024-12-11 08-27-55
As you can see, the health sensor goes into alert when the battery is full. For example, I also have a rule that is triggered every time a sensor goes into alert. That's what I generally want to avoid with PR.

**Review by laf — APPROVED** [review]
LGTM

**Comment by mpikzink** [comment]
@laf THANKS for your help with the tests.

**Pull request merged**
