### PR TITLE
Add VLAN Discovery for arubaos-cx

### PR DESCRIPTION
**Pull request by slashdoom**
Add VLAN Discovery for arubaos-cx.  

ArubaOS-CX doesn't response to IEEE8021-Q-BRIDGE-MIB::dot1qVlanVersionNumber and uses IEEE8021-Q-BRIDGE-MIB instead of Q-BRIDGE-MIB.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by VVelox — CHANGES_REQUESTED** [review]
Unless I am missing something, there does not appear to be a matching tests file for `arubaos-cx_10.10.snmprec`.

**Comment by slashdoom** [comment]
Yeah, I'm not sure what I'm doing wrong.  Maybe it's because I'm using the Docker image?  But after I've run ./scripts/collect-snmp-data.php and gotten my .snmprc file, when I run ./scripts/save-test-data.php I just get a test json that just contains the word "null".

**Comment by PipoCanaja** [comment]
@slashdoom I added the JSON file, let see how the tests are going with it.

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by PipoCanaja** [comment]
If it is all OK on your side @slashdoom , we should be able to merge this PR soon.

**Pull request merged**
