### PR TITLE
WIP - adding support for Juniper BTI 7000

### LINKED ISSUE #9964: New Device: BTI 7000
**Please do not post bugs or ask questions**

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

### PR DESCRIPTION
**Pull request by spencerbutler**
Very much a work in progress at the moment. The MIB structure for this device is non-standard, and proving to be quite a challenge to integrate into the lnms ecosystem. Any constructive feedback welcome.

Fixes #9964
https://github.com/librenms/librenms/issues/9964

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by czilian** [comment]
Thx guys for helping. Got stuck for the same reasons.

**Comment by czilian** [comment]
Regarding OS name: I have another BTI device in the making with totally different OS. Hence, maybe you could call it "juniper-bti7xxx" because the other would be then "juniper-bti8xxx" (BTI-SA-805 is model I am testing it against).

**Comment by laf** [comment]
Unless a huge difference exists between the 7k and 8k series then try and keep it in one.

@spencerbutler Anything you need from us?

**Comment by spencerbutler** [comment]
FWIW, I have code almost ready to push that adds lots of sensors. When I return in a week or two I will commit it.

**Comment by eyanulis** [comment]
@spencerbutler Out of curiosity, how's this coming along? We've recently deployed LNMS and I have six BTI7800 chassis I'd love to be able to add.

Happy to throw some device data or code work your way if it'd help, although my PHP is rusty at best.

**Comment by spencerbutler** [comment]
@eyanulis I got sidetracked, and I haven't had much time to work on this lately.

**Comment by eyanulis** [comment]
@spencerbutler Got it, totally understood! I'll keep an eye on this for now; I might take a whack at picking up from where the branch currently is if I get some free time.

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen!

**Pull request closed without merging**
