### PR TITLE
Check PHP dependencies in daily.sh

### PR DESCRIPTION
**Pull request by Jellyfrog**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
For example;
```
$ ./daily.sh
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.2.5". You are running 7.1.33-17+ubuntu18.04.1+deb.sury.org+1.Checking PHP dependencies                          FAIL
ext-ctype      7.1.33                                                  success
ext-curl       7.1.33                                                  success
ext-dom        20031129                                                success
ext-fileinfo   1.0.5                                                   success
ext-filter     7.1.33                                                  success
ext-gd         7.1.33                                                  success
ext-json       1.5.0                                                   success
ext-libxml     7.1.33                                                  success
ext-mbstring   7.1.33                                                  success
ext-openssl    7.1.33                                                  success
ext-pcre       7.1.33                                                  success
ext-pdo        7.1.33                                                  success
ext-session    7.1.33                                                  success
ext-sockets    7.1.33                                                  success
ext-tokenizer  7.1.33                                                  success
ext-xml        7.1.33                                                  success
php            7.1.33    darkghosthunter/larapoke requires php (^7.2)  failed
```

**Comment by murrant** [comment]
How does this notify users that don't watch the cli updates?

This seems to check before a new composer.json is pulled.

**Comment by Jellyfrog** [comment]
> How does this notify users that don't watch the cli updates

`status_run()` tries to send a notification on failure

> This seems to check before a new composer.json is pulled.

It tries after in the post function.

**Review by murrant — APPROVED** [review]
sometimes I hate the github diff snippets...  It is inside the check_dependencies() function, ok, LGTM

**Pull request merged**
