### PR TITLE
Add Total Wireless Client and AP count for Ruckus Wireless OS Type

### PR DESCRIPTION
**Pull request by djamp42**
Add Total Authorized Clients and Total AP Connected to Ruckus Wireless OS.  Tested on Zone Director 1200 & 1100.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this. Can you add test data as well so we can ensure nothing breaks in the future: https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

**Comment by djamp42** [comment]
I ran  the following, but it keeps generating the same filename with the same data for all my zone directors. i'm assuming i can't really add any more test data then what is already provided. 

`./scripts/collect-snmp-data.php -h #.#.#.# -m os -v `

```
 Module(s): os

Capturing Data:  sysDescr.0 sysObjectID.0 sysName.0 SNMPv2-MIB::sysDescr.0 SNMPv2-MIB::sysObjectID.0 .1.3.6.1.4.1.12148.10.2.6.0 sysUpTime.0 sysLocation.0 sysContact.0 snmpEngineTime.0 hrSystemUptime.0 .1.3.6.1.4.1.25053.3.1.5.15.5.0 .1.3.6.1.4.1.25053.3.1.5.15.8.0 .1.3.6.1.4.1.25053.3.1.5.15.7.0 .1.3.6.1.4.1.25053.3.1.5.15.9.0

Updated snmprec data /opt/librenms/tests/snmpsim/ruckuswireless.snmprec

Verify this file does not contain any private data before submitting!
```

**Comment by laf** [comment]
Yeah just add `-v model_name` to that command, you can then create a new file per model.

1 is fine though.

**Comment by djamp42** [comment]
Created, also added the AP Count /Client over graphs for the ruckuswireless os type. Let me know if anything else is needed.

**Comment by murrant** [comment]
@djamp42 That's correct, but I think it would be good to add other data besides just os.

Run collect-snmp-data.php again without `-m os` Thanks.

**Comment by djamp42** [comment]
Okay no problem updated the files.

**Pull request merged**
