### PR TITLE
Create Laravel Sessions Table

### PR DESCRIPTION
**Pull request by djamp42**
Laravel supports using the database to hold session information. This is creating the table to hold that information, simply migrate in. then set **SESSION_DRIVER=database** in .env

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Probably no harm in having the table exist.  You just need to update the db_schema.yaml file for verification.

**Comment by djamp42** [comment]
> Probably no harm in having the table exist. You just need to update the db_schema.yaml file for verification.

Yes i thought the same, this really has no major benefit unless you do database clustering as in my other pull request, with both this and clustering enabled.. Enabling Nginx on two librenms installations and load balancing between them seem to work perfectly when session data is in the database. Session data was getting lost when the server went offline that has the session data in a file.

**Comment by murrant** [comment]
FYI, I consider redis session driver better, but depends on your infrastructure.

**Comment by djamp42** [comment]
> 
> 
> FYI, I consider redis session driver better, but depends on your infrastructure.

Yes i originally had this, but i didn't have a redis cluster setup, so for what i was doing it was failing, i will eventually move back to this. 

Because it was just a table missing that was preventing the database from being used, i decided we might as well add this as i don't see the harm in it.

**Review by murrant — APPROVED** [review]

**Pull request merged**
