### PR TITLE
bug - Fix CISCO-BGP4-MIB logic

### PR DESCRIPTION
**Pull request by PipoCanaja**
Cisco BGP4 MIB provides:
```
cbgpPeer2AdvertisedPrefixes
This counter is incremented when a route prefix, which belongs to an address family is advertised on this connection. It is initialized to zero when the connection is undergone a hard reset.
````
and 
```
cbgpPeer2WithdrawnPrefixes
This counter is incremented when a route prefix, which belongs to an address family, is withdrawn on this connection. It is initialized to zero when the connection is undergone a hard reset.
```

But both are counters, and will grow forever. Only the difference makes sense and will show the number of routes that are currently advertised.

Which means that storing `WithdrawnPrefixes` in the DB or in RRDs currently makes no sense. And no page, graph, or OS makes use of it currently.

Shouldn't we remove it from DB in this PR ? 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
A new PR will come for the Cisco-PW module fix (`cpwVcMplsPeerLdpID` when in IP-address form must be converted to long before being sent to the DB `int(11)` column)

**Comment by murrant** [comment]
Should cbgpPeerSuppressedPrefixes be in the calculation too?

**Comment by PipoCanaja** [comment]
> Should cbgpPeerSuppressedPrefixes be in the calculation too?

I did not find any element clearly explaining if yes or no, and I don't have any counter currently to prove it wrong or right (all my suppressedPrefixes counters are at 0). So I don't know :)

**Review by murrant — APPROVED** [review]
I'm going to assume suppressed prefixes do not count as advertised.  It can be corrected later if that is proved to be wrong.

It might make sense to store both in rrd for graphing over time, but yes, only the current advertised prefix count makes sense in the database.

BGP is one of the module due for a rewrite, but it is 2nd scariest module imo, right behind ports :)

**Pull request merged**
