### PR TITLE
fix: Stop loading all oses when we have no db connection

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Stop trying to load all oses if we have no db connection (install process).

Fixes: #7001

### CODE REVIEW

**Comment by murrant** [comment]
@laf you sure this won't have any side effects?

We could force it to load all os (which doesn't require the db) if nodb is specified.

**Comment by laf** [comment]
Not 100% no but we call it with $existing = true so the DB is attempted to be used. 

I can change it to pass false if nodb is set?

**Comment by murrant** [comment]
@laf Yeah, that is what I was thinking, take a performance penalty, but might cause less unexpected edge cases...

**Comment by laf** [comment]
@murrant Updated, tested and it now shows the module not being installed in install.php if mysqli isn't available.

**Pull request merged**
