### PR TITLE
BUG - test-template.php upgrade after #8803 PR, following test-alert.php code

### PR DESCRIPTION
**Pull request by PipoCanaja**
Hello

Following this post, ( https://community.librenms.org/t/bug-test-template-php-not-running-after-laravel-upgrade/4639/9 ), here is the PR.

PipoCanaja

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for taking a look and fixing :)

**Comment by PipoCanaja** [comment]
You are welcome. 

But it seems that you removed a little bit too much code in fact : 

>    [msg] => Severity: severity is not a valid  data name
>  Time elapsed: elapsed is not a valid  data name Timestamp: timestamp is not a valid  data name
> Unique-ID: uid is not a valid  data name
> Rule:  name is not a valid  data name  Faults:
> 
> Warning: Invalid argument supplied for foreach() in /opt/librenms/storage/framework/views/5ad8479defaffcd0ff08c15642789b88 on line 10
> Alert sent to:
> 
> Warning: Invalid argument supplied for foreach() in /opt/librenms/storage/framework/views/5ad8479defaffcd0ff08c15642789b88 on line 28
> 

I would say that "$obj['alert']     = collect($obj);" is needed as well to display all the variables in the template. 

diff --git a/scripts/test-template.php b/scripts/test-template.php
index 3c1a8be9b..c9f6ef8a8 100755
--- a/scripts/test-template.php
+++ b/scripts/test-template.php
@@ -26,6 +26,7 @@ if (isset($options['t']) && isset($options['h']) && isset($options['r'])) {
         $obj['transport'] = $options['p'];
     }
     $type  = new Template;
+    $obj['alert']     = collect($obj);
     $obj['title']     = $type->getTitle($obj);

Can you correct it or should I open a new PR ?

**Comment by laf** [comment]
> collect($obj)

Where have you got this from?

**Comment by PipoCanaja** [comment]
From ./includes/alerts.inc.php I would say.

**Comment by laf** [comment]
Pop another PR in. Not sure I'll be around to merge tonight though

**Comment by PipoCanaja** [comment]
All right, done in https://github.com/librenms/librenms/pull/8910

**Pull request merged**
