### PR TITLE
Make Global Search Limit Configurable

### PR DESCRIPTION
**Pull request by Rosiak**
#2557

### CODE REVIEW

**Comment by laf** [comment]
It would be good to make this a WebUI config option. You can use html/pages/settings/external.inc.php as an example of doing something like html/pages/settings/webui.inc.php

**Comment by laf** [comment]
Commit to add db config support you can use (forgot to remove includes/defaults.inc.php option so ensure you do that).

https://github.com/librenms/librenms/commit/9fcb93b8d2be1f7e0d414d5661fe02778283631a

**Comment by Rosiak** [comment]
Thanks Neil.
Suggested changes has been merged in.

!!!! Notice the SQL schema, DO NOT MERGE until we are at that point !!!!

**Comment by f0o** [comment]
Propose moving the schema down to `102` for immediate merging

**Comment by laf** [comment]
@Rosiak move to 102.sql? We can merge if so.

**Comment by Rosiak** [comment]
Moved.

**Pull request merged**
