### PR TITLE
Discovery: Allow filtering by device groups

### PR DESCRIPTION
**Pull request by mwobst**
The discovery supports filtering by stuff like module, os and type, but not by device group. This pull request enables filtering either by name or by ID.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [-] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [-] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — CHANGES_REQUESTED** [review]
This is not the correct way to filter devices.  Use poller groups.

**Comment by mwobst** [comment]
> This is not the correct way to filter devices. Use poller groups.

Okay, sorry, I should explain this one a bit more.

First: Would a feature request a better idea, for the sake of discussion?

Now the motivation:
We need to discover some modules quite regularly, but there is no distributed discovery (and we don’t want to use a single “behemoth” VM) and not all modules should be fired on all devices on a regular basis.

Also: We don’t want to mix up the distributed polling mode with the discovery. We use a single poller group id to let (right now) 6 pollers do the “loadbalancing”. Using those groups for some static filtering would be complicated. Using device-groups would make things a lot more flexible.

Some examples:
- several nexus device want regular bgp session discovery, but it would be pointless to run the module for every device (as the core module is also called)
- to retrieve the mac addresses at the ports, we want to call the fdb-table module every 5 minutes, using a pool of device groups to distribute all devices.

**Comment by murrant** [comment]
I think this is the wrong approach to fix your problems.

Suggested options:
1. run this code in your local instances (might be a pain for you)
2. add polling for the modules you require (disabled by default)

Curious as to why you specifically need BGP discovery?

**Comment by murrant** [comment]
Closing as this needs a bit more thought and is incompatible with some other work.  Thanks for the PR!

**Pull request closed without merging**
