### PR TITLE
newdevice: Add support for Moxa #4733

### PR DESCRIPTION
**Pull request by Zaxmy**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Looks good :)

Is moxa the right name for the os? I see dsu mentioned here: http://www.moxa.com/support/sarch_result.aspx?prod_id=57&type_id=5&type=soft

We try and avoid labelling the os after the manufacturers name as it can lead to confusion if more products are added.

**Comment by Zaxmy** [comment]
dsu is a windows software to manage the console switches. You can upgrade the firmware, if you want.  Moxa also makes industrial network switches, with "proper" snmp support for which they have MIB's. But their console switches only support snmp via RFC1213-MIB .  http://www.moxa.com/support/faq/faq_detail.aspx?id=645

**Comment by laf** [comment]
Ok well from that then moxa isn't the right os name as if we add support for the switches we can't show them differently based on it being moxa. If they really don't have an OS name for the firmware than we need a unique name here first. We're open to suggestions.

**Comment by laf** [comment]
image

**Pull request merged**
