### PR TITLE
S.M.A.R.T visualization improvements

### PR DESCRIPTION
**Pull request by enilfodne**
This PR follows the changes merged in librenms/librenms-agent#164 and does as follows:

* Change `get_disks_with_smart` to enum drives from rrd files instead of the Database.

While this seems some-what hackish, all the changes are limited to only one function and allows to cleanly transition from disk id to disk sn without rewrite/changes to polling.

* Increase description length in graphs

The new changes introduced longer descriptions and since there was enough space, the length was increased where applicable.

* Add SMART attr177, previously recorded, but not displayed

This is another variant of attr173, but it wasn't displayed and some SSDs use this instead of 173.

* Change the multi-graph titles to better reflect their content

Some titles were extremely long and titles like `Big 5` weren't exactly informative. I'm not sure these changes are good, hopefully someone might come up with a better version.

* Change SMART attr numbers to a more human-friendly description

Accessibility changes to make graphs more readable

* Minor text corrections

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@enilfodne You might need to open a new one of these. I'm not sure why travis isn't starting here :(

**Comment by enilfodne** [comment]
I've noticed that Travis flagged this PR and commits as `Abuse detected` (more info [here](https://travis-ci.org/librenms/librenms/requests), but no details.

**Comment by zapotah** [comment]
I tested the patch yesterday since this is something that ive wanted to have since long ago due to the very reasons you submitted the patch. It works flawlessly and is exactly what is needed.

**Comment by laf** [comment]
I've mailed travis-ci so they can take a look.

**Comment by laf** [comment]
Travis have said "log into travis-ci.org and click the "Sync account" button"

Can you do that please @enilfodne and I'll message them back when done.

**Comment by enilfodne** [comment]
Done, but i must say this is one of the most unpleasant workarounds I've ever seen. Having to register for a service i have no use for, just to send a PR? I think there are better CI systems out there.

**Comment by laf** [comment]
> Done, but i must say this is one of the most unpleasant workarounds I've ever seen. Having to register for a service i have no use for, just to send a PR? I think there are better CI systems out there.

You normally don't have to. They normally auto create the user in there system by default but in this case it's not happened.

**Comment by enilfodne** [comment]
Triggered a rebuild and as far as i can see, there is one [failing](https://travis-ci.org/librenms/librenms/builds/350256626) job, but i don't think its related to the changes in the PR.

**Comment by enilfodne** [comment]
Is there another issue with this PR? Should i rebase?

**Comment by laf** [comment]
The last few PRs going through are now ok so I suggest you rebase this from our master and push the changes.

I'd highly recommend not submitting pull requests from your master branch by the way for future reference.

**Comment by enilfodne** [comment]
Bump!

**Pull request merged**
