### PR TITLE
Enexus system output current fix

### PR DESCRIPTION
**Pull request by loopodoopo**
System output current is not represented correctly, there was a divisor  by 10 which is not needed: 

Before the change:
image

Usage on the rectifier (load changed a fraction to 73A between screenshots....): 
image

After the change: 
image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
you need to run `save-test-data.php -o enexus -v ''` to also upgrade the tests JSON `enexus.json`

**Review by PipoCanaja — CHANGES_REQUESTED** [review]
`./scripts/save-test-data.php -o enexus -v ''` to run

**Comment by loopodoopo** [comment]
I think I tried all options including new variant (which I believe is not neccesery). 

Please advise.

**Comment by PipoCanaja** [comment]
Hi @loopodoopo 
The answer is in the test results : 
```
1) LibreNMS\Tests\OSModulesTest::testOS with data set "enexus_eltek-smartpack2-syst" ('enexus', 'eltek-smartpack2-syst', array('os', 'sensors'))
OS enexus: Discovered sensors data does not match that found in tests/data/enexus_eltek-smartpack2-syst.json
```

That means that the variant `eltek-smartpack2-syst` must be "save-test-data.php" again. 

Something like `./scripts/save-test-data.php -o enexus -v 'eltek-smartpack2-syst' `. 

That being said, looking at the folter with the tests : 
```
librenms@librenms:~$ ls -altr tests/data/enexus*
-rw-rw-r-- 1 librenms librenms 74616 Sep  8 14:08 tests/data/enexus.json
-rw-rw-r-- 1 librenms librenms 64042 Sep  8 14:08 tests/data/enexus_smartpacks.json
-rw-rw-r-- 1 librenms librenms 72477 Sep  8 14:08 tests/data/enexus_eltek-smartpack2-syst.json
-rw-rw-r-- 1 librenms librenms 59707 Sep  8 14:08 tests/data/enexus_sp2touch.json
-rw-rw-r-- 1 librenms librenms 63997 Sep  8 14:08 tests/data/enexus_smartpacks2.json 
```
So you should probably do it on all variants here, to be on the safe side.

**Comment by murrant** [comment]
@loopodoopo Hmm, can you check if there is a firmware setting that can affect output?

**Comment by loopodoopo** [comment]
@PipoCanaja  I learned something. Thank you!

**Comment by loopodoopo** [comment]
@barryodonovan I see you initially created Eltek Enexus support. Could you please have a look at this PR and let me know if the divisor 10 for "System Output Current" was intentional? 

Perhaps you can check your systems, do you have the same problem, I'm having?

**Comment by loopodoopo** [comment]
Can we get this change merged?

**Pull request merged**
