### PR TITLE
bug: fail isPingable if fping errors

### PR DESCRIPTION
**Pull request by f0o**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This will respect the exitcode of fping and fail in situations where hostname is not reachable or if other issues while execution appear.

### CODE REVIEW

**Comment by laf** [comment]
Can someone else test this on an install. It stops my poller processes completing:

image

**Comment by murrant** [comment]
I just tested this and didn't see any problems.  Are you seeing that happen consistently laf?

**Comment by laf** [comment]
Checked out twice and it then just builds up old processes. This is my dev env so it heavily relies on snmpsimd which is where the issue could be.

**Comment by laf** [comment]
I've removed most of my devices and this runs ok now.

**Pull request merged**
