### PR TITLE
refactor: Allow _perc and _current columns to be string for alert rules

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: https://community.librenms.org/t/trouble-with-storage-in-new-alert-rules-format/3724

### CODE REVIEW

**Comment by murrant** [comment]
Why are you making this change?  I'd prefer you make the change in the other part of the code, like where enum is handled.

**Comment by laf** [comment]
It’s not for enum. It’s because currently these columns are restricted to integers but you need to also compare them to other columns.

**Comment by murrant** [comment]
I don't understand "It’s not for enum".   I meant we need a standard way/place to define specific filter items.  That we way we can customize them and make it extra nice.  Right now there is only one custom thing, that is the enum one.  I expect we will add more...

**Comment by murrant** [comment]
Yes, I feel better with it in that place.  But I do feel like we need a better way to handle "special cases".

I'd say put that here for now and we can maybe come up with something later if/when we add more.

**Pull request merged**
