### PR TITLE
Add Port Notes Field

### PR DESCRIPTION
**Pull request by Rosiak**
Add a “Notes” field for ports to accommodate #1897

### CODE REVIEW

**Comment by laf** [comment]
Rather than add another column is it not just worth using the device override table?

**Comment by Rosiak** [comment]
Well, I honestly don't care.
If that's a more pretty way, I'll try that.

**Comment by laf** [comment]
You should only need to replace the dbUpdate calls to use something like set_dev_attr() and get_dev_attr() - names might be wrong :)

**Comment by laf** [comment]
The only outstanding issue (and we have this with device notes) is that multi lines get converted to \n to be stored but not on the output so you end up with something\ntesting

**Pull request merged**
