### PR TITLE
Highlight table on hover, added column names for status and brand

### PR DESCRIPTION
**Pull request by arjitc**
Screenshot: http://i.imgur.com/Si0gisd.png

### CODE REVIEW

**Comment by f0o** [comment]
table-condensed can be used together with table-hover afaik - or is there any reason why you removed it?

**Comment by laf** [comment]
I think brand should be vendor as well.

**Comment by arjitc** [comment]
Changed brand to vendor and added back table-condensed :)

**Comment by laf** [comment]
Thanks, merging this in now. 

We do have a new contributors agreement which we could do with you signing. It's ok for this pr as its specific to us but if you could submit an updated agreement that would be ace.

**Comment by arjitc** [comment]
> We do have a new contributors agreement which we could do with you signing. It's ok for this pr as its specific to us but if you could submit an updated agreement that would be ace.

I had signed one a few months ago when I did my initial UI related commits, I then had to leave to go to another city for a while, back home now so not sure if it has changed, let me know if it has changed and I'll re-sign it :)

**Pull request merged**
