### PR TITLE
feature: Add services-wrapper.py to enable support for distributed setups with service checks

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #4658 

@Gorian please test this.

### CODE REVIEW

**Comment by laf** [comment]
@Gorian any news on testing this?

**Comment by Gorian** [comment]
@laf not yet :( It's on my todo, I WILL keep you update, hopefully soon. I need to wait on the deployment of some more servers from the server team so I can deploy a remote poller. I am waiting on network security before I can test with remote poller in AWS. Apologies for delay.

**Comment by laf** [comment]
With such a small change to check-services.php, I think if people are happy with that change then this can be merged.

**Comment by laf** [comment]
@librenms/reviewers ?

**Comment by murrant** [comment]
I'd be fine with merging this.

**Comment by Gorian** [comment]
bah. I need a way to like things like "laf merged commit blah blah blah"

+1

**Pull request merged**
