### PR TITLE
Improved support for DNOS/FTOS M-Series

### PR DESCRIPTION
**Pull request by skoef**
Current implementation for Force10 series doesn't support the switch-blade M-Series model. This PR adds support for mempools and temperature. In my test environment (still 1.31) I have processors utilization support as well, but I have to test that in the new way processors are handled since 1.37

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@skoef Any update on this?

**Comment by skoef** [comment]
I've executed all the steps in the example workflow. I did have some failed tests unrelated to my change, but I'm not sure why this error is popping up.

**Comment by laf** [comment]
Looks like you had some mibs locally you haven't uploaded here. I've added those and re-ran the test. Should be ok now.

**Comment by skoef** [comment]
Cool thanks!

**Pull request merged**
