### PR TITLE
device: Allied Telesis inventory support

### PR DESCRIPTION
**Pull request by mattie47**
Ignore any commits below. I have not done anything here yet. 

As per screenshot from iReasoning mib browser, Allied Telesis awplus products do not [unfortunately] use the entity-mib, however most information is still available in the private enterprise mibs.

rscBoardTable (oid: .1.3.6.1.4.1.207.8.4.4.3.21.1.1) provides this in a table view.

image

My question is, how can lilbrenms import SNMP table information, since it's slightly different to doing an snmpget on individual OIDs?

Any assistance with what might help here would be much appreciated. 

Thanks,

Matt
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Add support to includes/discovery/entity-physical.inc.php and includes/polling/entity-physical.inc.php - well not directly in those files. You can see cimc has custom support within them, follow that.

**Comment by mattie47** [comment]
Thanks @laf.

Will have a look into this.

**Comment by laf** [comment]
Any update on this @mattie47?

**Comment by mattie47** [comment]
@laf  Haven't had time. Will probably be a few weeks before I can have a look at it again (busy at work/life again). 

For now - feel free to close it. Once I start having a look at it again I'll probably request it gets re-opened.

Thanks,

Matt

**Comment by laf** [comment]
We can leave it open for a bit longer see how you get on or feel free to close this yourself.

**Comment by laf** [comment]
Feel free to comment when this is ready and we can re-open.

**Pull request closed without merging**
