### PR TITLE
newdevice: Eaton/MGE UPS reorganization

### PR DESCRIPTION
**Pull request by murrant**
MGE split Galaxy (and Upsilon) to apc-mgeups
All others to eaton-mgeups
Remove mge ups from eatonups os.
Remove powerware it is a duplicate of eatonups

Not ready for commit!  No changes to sensor discovery/polling, other than powerware removal.
I need feed back to know if I have categorized these UPS correctly.

mgepdu.snmprec and mgeups-galaxy.snmprec are updated from user stats.  The rest are guessed.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Replaces #6279 and #6267

**Comment by laf** [comment]
Needs a notification for users explaining the OS changes + loss in data.

**Comment by murrant** [comment]
@FTBZ and anyone else, does this look ok?

If it doesn't I'll post a notification so we can merge it.

**Comment by FTBZ** [comment]
Just to be sure, it's replacing #6279?

**Comment by laf** [comment]
I believe that's correct.

**Comment by murrant** [comment]
Yes, I've covered the changes from #6279 and #6267,  so they can be closed.

**Pull request merged**
