### PR TITLE
newdevice: Added support for routeros to pull UPS info

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #1011
Replaces: #7331

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7352)

### CODE REVIEW

**Comment by murrant** [comment]
Wasn't there a quirk for runtime?

```
    } elseif ($device['os'] == 'routeros') {
        if ($sensor_type == 'runtime') {
            return 60;
        }
```

**Comment by laf** [comment]
I thought you fixed that in your rfc fix?

**Comment by murrant** [comment]
I fixed the ability for that particular piece of code to work.  Before it wouldn't work as the runtime/rfc1628.inc.php did not call get_device_divisor()

**Comment by laf** [comment]
So `get_device_divisor()` already returns 60 for runtime when the OID starts with `.1.3.6.1.2.1.33.1.2.2` which one of the runtimes does, the other is `.1.3.6.1.2.1.33.1.2.3` and that returns divisor 1.

I don't have access to data to test if we still need to return 60 for `.1.3.6.1.2.1.33.1.2.3`

**Comment by murrant** [comment]
Yeah, I thought they were both 60...

**Pull request merged**
