### PR TITLE
Fix cisco sensor thresholds

### PR DESCRIPTION
**Pull request by dsgagi**
- Skips setting invalid value "-32768" for sensor thresholds on discovery.
- Skips overwriting high limit threshold with low limit threshold value, if high limit is empty/null. Started happening on some Cisco ASR devices after PR #11077 was merged.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
LGTM, it doesn't look like there is any test data that covers this behavior.  Would you care to add some?

**Comment by dsgagi** [comment]
Had no success in creating a json dump of test data.

I successfully generated a `snmprec` file by running `/opt/librenms/scripts/collect-snmp-data.php -h 875 -m os,ports,ports-stack,entity-physical,processors,mempools,cisco-pw,vrf,cisco-cef,cisco-sla,sensors,storage,ntp -v asr9010`. I excluded modules which didn't work for IOSXR and which returned mostly sensitive data (discovery protocols data, ip and mac addresses, etc.).

I then tried executing `./scripts/save-test-data.php -o iosxr -v asr9010`, and this is the output.
```
Starting snmpsim listening on 127.1.6.1:1161... 
OS: iosxr
Module: all
Variant: asr9010

iosxr_asr9010: Could not connect to 127.1.6.1, please check the snmp details and snmp reachability
```

I also tried executing `./scripts/save-test-data.php -o iosxr -v asr9010 --snmpsim`.
```
Index /tmp/snmpsim/_opt_librenms_tests_snmpsim__arrayos.dbm does not exist for data file /opt/librenms/tests/snmpsim//arrayos.snmprec
Traceback (most recent call last):
  File "/usr/bin/snmpsimd.py", line 1247, in <module>
    snmpContext
  File "/usr/bin/snmpsimd.py", line 883, in configureManagedObjects
    dataFile = DataFile(fullPath, textParser).indexText(forceIndexBuild)
  File "/usr/bin/snmpsimd.py", line 241, in indexText
    self.__recordIndex.create(forceIndexBuild, validateData)
  File "/usr/lib/python2.7/site-packages/snmpsim/record/search/database.py", line 93, in create
    raise error.SnmpsimError('Failed to create %s for data file %s: %s' % (self.__dbFile, self.__textFile, sys.exc_info()[1]))
snmpsim.error.SnmpsimError: Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__arrayos.dbm for data file /opt/librenms/tests/snmpsim//arrayos.snmprec: (17, 'File exists -- BDB0002 __fop_file_setup:  Retry limit (100) exceeded')
```

I'm probably doing something wrong, but I am not sure what :)

**Comment by murrant** [comment]
Odd tmp file permissions?

If you put the snmprec here, I can generate the json file.

**Comment by dsgagi** [comment]
Doesn't seem like that is the issue. All files in `/tmp` folder get created with librenms user as owner.

I will attach the snmprec file shortly.

**Comment by PipoCanaja** [comment]
@murrant Even with a rebase, and re-computing the test-data, there is still a funcky mismatch with some sensor data.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
