### PR TITLE
Improvements to "old RRD" updating process

### PR DESCRIPTION
**Pull request by pblasquez**
When you are migrating a device into LibreNMS for which you have old RRDs, there is already code that takes care of the renaming of certain files.  This update both fixes a typo in discovery of ports with old RRD files and allows the user to configure a source directory so they do not have to mix the old files with the new.

### CODE REVIEW

**Comment by laf** [comment]
Does this affect users in anyway?

**Comment by pblasquez** [comment]
It affects users that are onboarding RRDs from an observium instance.

**Comment by laf** [comment]
In what way does it affect them? We don't want cause adverse problems for users.

**Comment by pblasquez** [comment]
In a positive way.

The discovery.php change fixes a bug in the $device array call where $device['id'] was being used instead of $device['device_id']. this was causing old RRDs to not be imported until the poller run. The poller code has the same call and the bug does not exist there.  This bug is never visible unless you are expecting discovery.php to import your RRDs and you aren't running the poller cronjob yet.

The new $config['old_rrd_dir'] setting allows users to deploy librenms on the same server as their observium instance, and use the observium RRD directory as the RRD source without having to copy or move the files over.  If the instances are on different serves, the old RRD files can be copied to a separate directory instead of requiring that they be mixed in with the librenms RRD files.  This helps with cleanup of files that were not matched by the algorithms.

There should be no conflict with existing users as RRD import is a one-time thing, and $config['old_rrd_dir'] has been initialized in the same way as $config['rrd_dir'].

There are two cases where someone might be affected:

1) If a user is **continuously and on a regular basis** importing RRDs and they have $config['rrd_dir'] set to something besides the default.  This user would need to set $config['old_rrd_dir'] to their custom location after this change.

2) Users who modify $config['rrd_dir'] and then attempt to copy old RRDs to their new, custom RRD directory will find that import does not work until they update $config['old_rrd_dir'] to the new custom location.

I could add some instructions to the "Migrating from Observium" docs and give a heads up to Dan Brown for his blog post.  Would that cover things?

**Comment by laf** [comment]
I've not really had chance to digest a lot of that but my initial thoughts is we need to be careful with this.

The initial goal of the rename rrd code was to support changing file names in an install, for instance when we moved from id based port names to varying ifindex, ifname port names. Using it to rename rrd files for other directories as you've pointed out already could lead to issues (moving files rather than copy).

@librenms/reviewers

**Comment by paulgear** [comment]
With the exception of includes/discovery/ports.inc.php, includes/polling/ports.inc.php, and  includes/discovery/storage/hrstorage.inc.php, all of the references to old RRDs pre-date the fork.  Additionally, all of the references (whether before or after the fork) are concerned with changes in the way files are referenced *within a running installation*, not with conversion from an old installation (whether Observium or LibreNMS).  So I agree with @laf, and I don't think we should merge this.

However, pointing to an old installation from which RRDs could be copied *is* a useful feature, and I think it would be great if we could support it.  Even better if we could integrate dump & restore for architecture changes...

**Pull request closed without merging**
