### PR TITLE
Remove from, to text and replace with fontawesome <->

### PR DESCRIPTION
**Pull request by arjitc**
Remove from, to text and replace with fontawesome <->

Screenshot  http://i.imgur.com/kgfOrn6.png

### CODE REVIEW

**Comment by arjitc** [comment]
Maybe someone can help/addon a "on.change.submit" to this form and then we can drop the submit button as well to clean up the area a bit more :)

**Comment by arjitc** [comment]
Hmm, i'm running the same code in production without errors (screenshot).

**Comment by laf** [comment]
I'm not personally convinced this is better, for those who know what the boxes do fine but for new users this may not be so clear.

**Comment by arjitc** [comment]
Hmm how about the second idea? to remove the submit button and make it auto-submit on change of values in the form? Just to clean up the overall area a bit more.

**Comment by laf** [comment]
Personally I'd have to see it in action to make sure it wasn't one of those annoying it submitted by accident jobs.

**Comment by arjitc** [comment]
I'll work on this today and see where it goes with the auto-submit :)

**Pull request closed without merging**
