### PR TITLE
Ubiquiti Airfiber60

### PR DESCRIPTION
**Pull request by jepke**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'airos-af60'
> +'airos'
> 
> /home/runner/work/librenms/librenms/tests/OSDiscoveryTest.php:125
> /home/runner/work/librenms/librenms/tests/OSDiscoveryTest.php:87

This means that the OS "airos" matches the same device, so you need to modify `includes/definitions/airos.yaml` accordingly

**Comment by jepke** [comment]
Ubiquiti uses the same sysobjectid for Airos and Airfiber AF60 devices which is probably causing this. Not sure what the best approach is on this.

**Comment by murrant** [comment]
@jepke first thing to do is to figure out how to uniquely identify the AF60.  Ubiquiti does not make this easy.

**Comment by jepke** [comment]
> @jepke first thing to do is to figure out how to uniquely identify the AF60. Ubiquiti does not make this easy.

.1.3.6.1.4.1.41112.1.11 this is unique to the new AF-60. The Airfiber LTU's have 1.10 as unique oid set.
So if im correct i have to somehow tell `airos.yaml` to skip AF-60 devices. Please correct me if im wrong.

I changed it to WIP as overnight newly added metrics went back to 0 all those come from the wierd OIDs ubiquiti uses that have a mac address encoded. I had this exact same issue with my AF LTU PR have to go back and read it again to see how i fixed that. Its like discovery pulls the correct value but further polling seems to be unable.

**Comment by murrant** [comment]
You need to set sysObjectID_exclude: .1.3.6.1.4.1.41112.1.11  (or something like that) on the airos definition

**Comment by jepke** [comment]
> You need to set sysObjectID_exclude: .1.3.6.1.4.1.41112.1.11 (or something like that) on the airos definition

that unfortunatly doesnt work.
also tried
```
        snmpget_except:
          oid: .1.3.6.1.4.1.41112.1.11.1.2.2.1
          op: 'contains'
          value: 'AF60'
```

**Comment by jepke** [comment]
@murrant it looks like i finally did it but im unsure if this is the most practical.

`.1.3.6.1.4.1.41112.1.11` is unique to the Airfiber 60 ghz product line atleast for now im not sure about ubiquiti's 60ghz wave products as i dont have one.

**Comment by murrant** [comment]
@jepke looks good, but I would prefer the state sensors be done in yaml, it is less likely to break in the future. Any reason you have done them in PHP?

**Comment by jepke** [comment]
> @jepke looks good, but I would prefer the state sensors be done in yaml, it is less likely to break in the future. Any reason you have done them in PHP?

Those oids have the mac address in decimal encoded. 
`1.3.6.1.4.1.41112.1.11.1.3.1.2.{244.146.191.226.158.141}.1`  {macaddress}
I recall i did them in yaml when i did the airfiber LTUs but had a lot of issues getting them to work. So looking back at that PR i noticed another PR was made which made a lot more sense to me #11844.
Thing i encountered was it works in yaml for discovery but then polling fails not being able to find the OID. Assume a difference between doing a snmpwalk and snmpget.

**Review by murrant — APPROVED** [review]
Sounds good for now, thanks @jepke

**Pull request merged**
