### PR TITLE
Added support for drac power and current polling

### PR DESCRIPTION
**Pull request by theister-xan**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Any reason you didn't use yaml for these?

**Comment by theister-xan** [comment]
Is there any way to apply logic to the yaml mechanism?

For the drac data for current and power is in the same tree ( amperageProbeReading ) with current being e.g. .1 and .2 while power is .3

The only way to check which sensor type it should be is to query another tree (amperageProbeType ) and check the type per index.

So if the yaml mechanism can do if then logic we could use it here, I could not find any hint how to do that and asked in discord. After not getting an answer I implemented it this way.

**Comment by murrant** [comment]
Yeah, this is actually pretty easy to do.
amperageProbeType tells you what type of probe so, you just check that in the skip_values

So, for current:

```yaml
skip_values:
                        -
                            oid: amperageProbeType
                            op: '!='
                            value: 23
```

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-57-release-changelog-october-2019/9969/1

**Pull request merged**
