### PR TITLE
Feature: Add elasticsearch transport and docs

### PR DESCRIPTION
**Pull request by pblasquez**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
@pblasquez the test is failing because the test is a little to simplistic.  You can either not use librenms or we can fix the test.  Sorry about that :/

**Comment by laf** [comment]
@murrant 

```
diff --git a/tests/DBSetupTest.php b/tests/DBSetupTest.php
index fed6c2f..f5ebf05 100644
--- a/tests/DBSetupTest.php
+++ b/tests/DBSetupTest.php
@@ -60,7 +60,7 @@ class DBSetupTest extends DBTestCase
                 }

                 // cannot assume user use the librenms database name
-                if (str_contains($line, 'librenms')) {
+                if (str_contains($line, 'librenms.')) {
                     throw new PHPUnitException("Do not include the database name in schema files\n$file: $line");
                 }
             }

```
?

**Comment by pblasquez** [comment]
@murrant np, the default value was only there for completeness.  Also the delay helped me catch that my state switch was incomplete. :)

**Comment by murrant** [comment]
@laf yeah, that would be good, but possibly `librenms`.

**Comment by pblasquez** [comment]
@murrant: sorry, just noticed I left an unused variable that isn't in the SQL config, might cause issues on the UI.

**Comment by pblasquez** [comment]
@murrant @laf I've had this working stable in production for 6 days now, anything else needed for merge?

**Comment by laf** [comment]
@pblasquez all good with me except you need to rename the schema file to 193.sql.

**Pull request merged**
