### PR TITLE
fix: qnap fanspeed sensor

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Again looks ok to me but looking for a second opinion ( @librenms/reviewers )

**Comment by murrant** [comment]
I'm not sure I like this going from one snmpwalk to many snmpget calls.
Btw, what does this PR achieve?

**Comment by crcro** [comment]
qnap guys choose to change the oid names at version 4.2.0 (i think) from HdTemperature to hdTemperatureEX (all of them this was of top of my mind). so instead of poll based on oid names i poll based on numeric oid

**Comment by paulgear** [comment]
I too wonder what this would do from a performance and backwards compatibility perspective, but I don't have any of these devices to test against.  Perhaps we could put the word out on Twitter/community/mailing list to get more feedback?  There are only 3 qnap devices in https://stats.librenms.org at the moment, so it's not like we'd be breaking a lot of people's installs...

**Comment by crcro** [comment]
the backward compatibility exists (i've tested on qnap with different os versions), they are the oid from their NAS-MIB, they only change the name values, numerical oid stayed the same

**Comment by laf** [comment]
Could we just walk the relevant tree instead so we get everything in one go?

**Comment by murrant** [comment]
I actually much prefer the previous code.

**Comment by laf** [comment]
What's the score with this one?

**Comment by crcro** [comment]
Yes, they have their own oid that it's incremented (one oid for descr and one for speed).

**Comment by laf** [comment]
Can we not then walk the OIDs rather than doing single gets?

**Comment by zamolxe** [comment]
I think we missed a dot in the code, causing the oid concatenation with indexes to fail.
```
Including: /data/web/librenms/includes/discovery/sensors/fanspeeds/qnap.inc.php
QNAP: SNMP[ESC[0;36m/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -M /data/web/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.15.1.2ESC[0m]
enterprises.246*.1.2.1 = "System FAN 1"
enterprises.246*.1.2.2 = "System FAN 2"

SNMP[ESC[0;36m/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs -M /data/web/librenms/mibs udp:HOSTNAME:161 .1.3.6.1.4.1.24681.1.2.15.1.3ESC[0m]
enterprises.246*.1.3.1 = "1298 RPM"
enterprises.246*.1.3.2 = "1318 RPM"

Discover sensor: .1.3.6.1.4.1.24681.1.2.15.1.31, 1, snmp, System FAN 1, snmp, ,
SQL[ESC[0;33mSELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'fanspeed' AND `device_id` = '12' AND sensor_type = 'snmp' AND `sensor_index` = '1'ESC[0m]
SQL[ESC[0;33mSELECT * FROM `sensors` WHERE `sensor_class` = 'fanspeed' AND `device_id` = '12' AND `sensor_type` = 'snmp' AND `sensor_index` = '1'ESC[0m]
.Discover sensor: .1.3.6.1.4.1.24681.1.2.15.1.32, 2, snmp, System FAN 2, snmp, ,
SQL[ESC[0;33mSELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= 'snmp' AND `sensor_class` = 'fanspeed' AND `device_id` = '12' AND sensor_type = 'snmp' AND `sensor_index` = '2'ESC[0m]
SQL[ESC[0;33mSELECT * FROM `sensors` WHERE `sensor_class` = 'fanspeed' AND `device_id` = '12' AND `sensor_type` = 'snmp' AND `sensor_index` = '2'ESC[0m]
```

**Pull request merged**
