### PR TITLE
feature: migration of apps to collectd

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

just an ideea, with webui lineup and osupdates script test.

the test design was:
- host with collectd that reports data to server via network plugin (client)
- librenms host with collectd (server) and listening to collectd network clients and output to rrd in  /opt/librenms/collectd/

screen shot 2018-01-17 at 9 56 54 pm
screen shot 2018-01-17 at 9 57 04 pm

### CODE REVIEW

**Comment by laf** [comment]
> librenms host with collectd (server) and listening to collectd network clients and output to rrd in /opt/librenms/collectd/

Can we not get it to store data in /opt/librenms/rrd/$hostname/ like normal?

**Comment by murrant** [comment]
@laf CollectD puts the RRDs there, not LibreNMS...

@crcro I like the general direction, but it needs to be better developed.  I'm not particularly fond of the pretty_x() functions, they would be very long and a little nonsensical after adding all our apps.

**Comment by laf** [comment]
> @laf CollectD puts the RRDs there, not LibreNMS...

I know, the question still stands though.

**Comment by murrant** [comment]
The default according to the docs is 
```
$config['collectd_dir']  = '/var/lib/collectd/rrd';
```
https://docs.librenms.org/Support/Configuration/#collectd

**Comment by crcro** [comment]
it could be done:
- changed the collectd_dir to /opt/librenms/rrd/ 
- collectd creates dirs under each host

the issue after this is that there are wrights issues and collectd cannot write data to rrd files.
still searching for a way to manage this ..

**Comment by murrant** [comment]
Yeah, would require a re-write of the existing apps.  My experience is it will stay in the temporary state.  I actually don't care about apps that much, so I'm fine with that ;)

**Comment by laf** [comment]
No further conversations have been had on this so I'm closing it down.

**Comment by laf** [comment]
Proposing we close this down. Thanks for the work you put in @crcro but at present it's uncertain this is the way to go. @librenms/reviewers?

**Comment by theherodied** [comment]
@laf, I use collectd for some things but I'm not positive it's the way to go either. I've looked into other projects like Prometheus to replace collectd.

**Comment by laf** [comment]
Closing for now. Feel free to continue discussion.

**Pull request closed without merging**
