### PR TITLE
BDCOM add new discovery (CPU,memory,temperature,humidity,fans,voltage,states,count cpe(for olt))

### PR DESCRIPTION
**Pull request by hrtrd**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by hrtrd** [comment]
Wait, i need add some

**Review by murrant — APPROVED** [review]
Odd that you remove the current processor, are you sure you aren't breaking some older device or something?  Other than that, looks good, nice work.

**Comment by hrtrd** [comment]
bdcom is currently trying to update all oid. Just yesterday I got new mibs from their support. From year 20, the firmware versions will be similar to each other. If something breaks somewhere, I will either advise you to update the software version at least to the intermediate one, or I will fix it myself by adding the correct oids.

> Odd that you remove the current processor, are you sure you aren't breaking some older device or something? Other than that, looks good, nice work.

bdcom is currently trying to update all oid. Just yesterday I got new mibs from their support. From year 20, the firmware versions will be similar to each other. If something breaks somewhere, I will either advise you to update the software version at least to the intermediate one, or I will fix it myself by adding the correct oids.

**Comment by hrtrd** [comment]
How possible add to Count several groups? Im trying   this,  and see only last group, like "PON Inactive Onu Num", and Active group not displayed

        count:
            data:
                -
                    oid: gponOltPonPortPortActiveOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.10.2.1.1.4.{{ $index }}'
                    group: "GPON Active Onu Num"
                    descr: "{{ $gponOltPonPortPortIndex }}"
                    low_limit: 0
                    warn_limit: 120
                    high_limit: 128
                -
                    oid: gponOltPonPortPortInactiveOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.10.2.1.1.5.{{ $index }}'
                    group: "GPON Inactive Onu Num"
                    descr: "{{ $gponOltPonPortPortIndex }}"
                -
                    oid: activeOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.101.6.1.1.21.{{ $index }}'
                    group: "EPON Active Onu Num"
                    descr: "{{ $ponIfIndex }}"
                    low_limit: 0
                    warn_limit: 60
                    high_limit: 64
		-
		    oid: inactiveOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.101.6.1.1.22.{{ $index }}'
                    group: "EPON Inactive Onu Num"
                    descr: "{{ $ponIfIndex }}"
                    low_limit: 0
                    warn_limit: 60
                    high_limit: 64

**Comment by murrant** [comment]
> How possible add to Count several groups? Im trying this, and see only last group, like "PON Inactive Onu Num", and Active group not displayed

Are all the sensors being displayed?  Is the group set in the database?

**Comment by hrtrd** [comment]
> > How possible add to Count several groups? Im trying this, and see only last group, like "PON Inactive Onu Num", and Active group not displayed
> 
> Are all the sensors being displayed? Is the group set in the database?

No, of the two available for the same gpon, only the bottom group is displayed. The epon is the same. How can I check a group in the database?

**Comment by murrant** [comment]
Look at the sensors table, there is a "group" column. (or in the json which does not have group set for any of the sensors)

Maybe you need quotes around them? although it shouldn't be required.

**Comment by hrtrd** [comment]
> Look at the sensors table, there is a "group" column. (or in the json which does not have group set for any of the sensors)
> 
> Maybe you need quotes around them? although it shouldn't be required.

https://github.com/librenms/librenms/pull/12433#issuecomment-759498453

**Comment by murrant** [comment]
You need to load the full table or pre-cache the other values you want.
Here is full table:
```yaml
        count:
            data:
                -
                    oid: gponOltPonPortConfigTable
                    value: gponOltPonPortPortActiveOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.10.2.1.1.4.{{ $index }}'
                    group: "GPON Active Onu Num"
                    descr: "{{ $gponOltPonPortPortIndex }}"
                    low_limit: 0
                    warn_limit: 120
                    high_limit: 128
                -
                    oid: gponOltPonPortConfigTable
                    value: gponOltPonPortPortInactiveOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.10.2.1.1.5.{{ $index }}'
                    group: "GPON Inactive Onu Num"
                    descr: "{{ $gponOltPonPortPortIndex }}"
                -
                    oid: nmseponoltponTable
                    value: activeOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.101.6.1.1.21.{{ $index }}'
                    group: "EPON Active Onu Num"
                    descr: "{{ $ponIfIndex }}"
                    low_limit: 0
                    warn_limit: 60
                    high_limit: 64
                -
                    oid: nmseponoltponTable
                    value: inactiveOnuNum
                    num_oid: '.1.3.6.1.4.1.3320.101.6.1.1.22.{{ $index }}'
                    group: "EPON Inactive Onu Num"
                    descr: "{{ $ponIfIndex }}"
```

**Comment by hrtrd** [comment]
> You need to load the full table or pre-cache the other values you want.
> Here is full table:
> 
> ```yaml
>         count:
>             data:
>                 -
>                     oid: gponOltPonPortConfigTable
>                     value: gponOltPonPortPortActiveOnuNum
>                     num_oid: '.1.3.6.1.4.1.3320.10.2.1.1.4.{{ $index }}'
>                     group: "GPON Active Onu Num"
>                     descr: "{{ $gponOltPonPortPortIndex }}"
>                     low_limit: 0
>                     warn_limit: 120
>                     high_limit: 128
>                 -
>                     oid: gponOltPonPortConfigTable
>                     value: gponOltPonPortPortInactiveOnuNum
>                     num_oid: '.1.3.6.1.4.1.3320.10.2.1.1.5.{{ $index }}'
>                     group: "GPON Inactive Onu Num"
>                     descr: "{{ $gponOltPonPortPortIndex }}"
>                 -
>                     oid: nmseponoltponTable
>                     value: activeOnuNum
>                     num_oid: '.1.3.6.1.4.1.3320.101.6.1.1.21.{{ $index }}'
>                     group: "EPON Active Onu Num"
>                     descr: "{{ $ponIfIndex }}"
>                     low_limit: 0
>                     warn_limit: 60
>                     high_limit: 64
>                 -
>                     oid: nmseponoltponTable
>                     value: inactiveOnuNum
>                     num_oid: '.1.3.6.1.4.1.3320.101.6.1.1.22.{{ $index }}'
>                     group: "EPON Inactive Onu Num"
>                     descr: "{{ $ponIfIndex }}"
> ```

oh, try it rn

**Comment by hrtrd** [comment]
nope, same. Added first    group: "GPON Active Onu Num"     discovery, work fine, then add group: "GPON Inactive Onu Num"   discovery, and see only group: "GPON Inactive Onu Num"
Screenshot_319

**Comment by murrant** [comment]
This is because the index matches, so they look like the same sensors.  Set 'index' to differentiate them.

**Comment by hrtrd** [comment]
> This is because the index matches, so they look like the same sensors. Set 'index' to differentiate them.

Hm, I'm not sure what I understand. Sorry. What u mean?

**Comment by murrant** [comment]
Add `index: 'ontActive.{{ $index }}'` to each count sensor (using different names for each)

**Comment by hrtrd** [comment]
> Add `index: 'ontActive.{{ $index }}'` to each count sensor (using different names for each)

oh, yeah, thats work!! thx!! he only thing left is to replace the port index with their real name. when debugging port discovery, ifname and ifdescr output the normal port name. 
Screenshot_299
Screenshot_296

**Comment by Jellyfrog** [comment]
`"hardware": "A"`  doesn't look right

**Comment by hrtrd** [comment]
> `"hardware": "A"` doesn't look right

Screenshot_342

**Comment by Jellyfrog** [comment]
Yes but that's just some hardware revision not your actual model

**Comment by hrtrd** [comment]
> Yes but that's just some hardware revision not your actual model

alright, u right.

**Comment by hrtrd** [comment]
and now, how to change change ports codes to - ofName/ifDescr ?

**Comment by hrtrd** [comment]
alright, no one care. Merge this, and i go rewrite over OS.

**Comment by murrant** [comment]
I think test data needs a small update...

**Comment by hrtrd** [comment]
> I think test data needs a small update...

 ./scripts/collect-snmp-data.php   - broken? ) options do not work. when you specify -h, it just displays possible use cases and nothing else

**Comment by Jellyfrog** [comment]
It is not broken, It tells you the required and optional parameters. I suggest you read it again since it changed recently

**Comment by murrant** [comment]
@hrtrd any reason this was closed?  To update data without a variant use the `-v ''` on collect-snmp-data.php

**Pull request closed without merging**
