### PR TITLE
Fix for issue #5525

### PR DESCRIPTION
**Pull request by towster**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
PR looks good 👍 

You do need to sign the contributors agreement correctly though, please see the doc linked at the top in point 1. You can add another commit to this PR by just editing AUTHORS.md again and put a space after your name then sign the commit as per the doc.

**Comment by towster** [comment]
Some links may be broken if the device name is actually the IP

**Comment by towster** [comment]
Excluded adding devices that already exist when discovery_by_ip used

**Comment by laf** [comment]
You still haven't signed the contributors agreement properly, please read the information in the link at the top.

**Comment by towster** [comment]
Any way to get this looked at again?

**Pull request merged**
