### PR TITLE
add dbal so users can update the database

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
The version numbers are not the same as the ones that came when I added it to my dev machine. Just an information, I have no clue if that is important or not ... 

capture d ecran 2019-01-16 a 17 12 17

**Comment by murrant** [comment]
@PipoCanaja that is because you don't have php 5.6 on your machine :)

**Comment by PipoCanaja** [comment]
All right ;) Then I like it ;)

**Comment by murrant** [comment]
@PipoCanaja go ahead an approve and merge :)

I run composer with php 5.6 when modifying our dependencies.  That way we pull in the versions that still support 5.6.

**Pull request merged**
