### PR TITLE
adding human readable version of /api/v0/fdb/{mac}/detail

### PR DESCRIPTION
**Pull request by sjtarik**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ottorei** [comment]
In my opinion the idea for reducing API-calls and providing a single output with this kind of approach works for this particular use case but there are lots of other models and API-routes where this same problem would occur.

So the basic issue here is that each model has it's own API and if one wishes to have all the related data, multiple API-calls would be needed. I wonder if there is an elegant generic solution to produce single output with all or selected fields from any related models, basically a data API where queries could be made in a similar fashion than normal Eloquent queries that use relations. @Jellyfrog @murrant what do you think about this kind of data API idea?

**Comment by tkaraoglu** [comment]
@Jellyfrog @murrant @ottorei folks, any chance we can land this? in our company we rely on this API. Other ways of pulling this data with existing APIs  times out (getting 500s) since mac and interface table is large, takes up large memory and existing APIs don't use any limit for the queries.

**Comment by electrocret** [comment]
@sjtarik, can you add to the docs how to use this new API endpoint?

**Review by electrocret — APPROVED** [review]
LGTM

**Comment by ottorei** [comment]
> @sjtarik, can you add to the docs how to use this new API endpoint?
> 
> @ottorei , I agree that the Libre API needs a major overhaul (v1 perhaps?).The current API is largely a carry over from pre-Libre. However this is what we currently have.

That's right. I don't see a problem adding additional "recursive" API-routes that resolve IDs and other data from different models into plain string representations. But if we are doing this, then we should probably do it in a unified way for all routes where this kind of behaviour is needed.

**Comment by tkaraoglu** [comment]
@electrocret @ottorei thank you for your comments and reviews. Please let me know if I can contribute to larger effort for APIs in the future.

**Pull request merged**
