### PR TITLE
Alertlog stats dashboard widget

### PR DESCRIPTION
**Pull request by louis-oui**
image

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
Can you post a screenshot please?

**Comment by louis-oui** [comment]
> Can you post a screenshot please?

done

**Comment by louis-oui** [comment]
https://github.com/librenms/librenms/pull/10967

**Comment by louis-oui** [comment]
Needs to add filter by last X days

**Comment by louis-oui** [comment]
Code climate errors can be bypassed

**Comment by kkrumm1** [comment]
Any update on this one?

**Comment by kkrumm1** [comment]
@louis-oui are you still up to this one too?

**Comment by louis-oui** [comment]
@kkrumm1 this PR is working properly. @Jellyfrog asked me for rewriting it to laravel. 
Unfortunately, I have no time to do it right now. If Laravel is not mandatory, this PR could be merged without modification

**Comment by kkrumm1** [comment]
alright LGTM

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
