### PR TITLE
docs: Update Test-Units.md

### PR DESCRIPTION
**Pull request by mattie47**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Seems to be a conflict there.  one line says to install the system wide composer, the other executes ./composer.phar which is downloaded by the `./scripts/composer_wrapper.php` script.

**Comment by laf** [comment]
I'd prefer to get rid of suggesting to install composer by yum/apt.

**Comment by mattie47** [comment]
>Seems to be a conflict there. one line says to install the system wide composer, the other executes ./composer.phar which is downloaded by the ./scripts/composer_wrapper.php script.

OK so I've gone off and done some googling...

In short:
- composer is a package manager for php, similar to npm for node. It differs from things such as apt, or YUM in that packages can be installed on a per project basis. 
- `apt install composer` would globally install composer, which isn't necessarily needed...because: 
-- we can install `composer.phar` in the project folder instead. This is the binary file for per project managed dependencies. 

**In terms of LibreNMS**
- ./composer.json contains the list of requirements/dependencies for LibreNMS. 
- The reason we don't necessarily need composer installed globally, is because we have ./scripts/composer-wrapper.php
- Composer-wrapper will attempt to download composer.phar into the libreNMS install directory 
- If Composer-wrapper can't download composer.phar, it will attempt to use a globally installed composer (if it is installed).
- If all else fails, it'll tell the user to install composer. 

What I don't understand is how composer-wrapper gets called in the first place? I thought perhaps through daily.sh, but this just seems to reference an already defined ${COMPOSER}... 

I see from the LibreNMS install instructions one of the required packages **is** composer, which then uses `composer --create-project` to initially set the libreNMS project up. But beyond that, I'm not sure...

**Comment by laf** [comment]
Forget what composer is or isn't outside of LibreNMS. The composer_wrapper script handles installing composer into /opt/librenms/ as composer.phar so we avoid older versions installed by the distro in the bin path, they've caused us problems before.

Once composer is available as /opt/librenms/composer.phar then composer_wrapper handles invoking it to install the dependancies we need.

**Comment by mattie47** [comment]
@laf,

OK - What do you actually want the docs here to say? 

`./scripts/composer_wrapper.php install` ?

**Comment by laf** [comment]
Correct.

**Pull request merged**
