### PR TITLE
Fix: Update pi-hole app for new API

### PR DESCRIPTION
**Pull request by slashdoom**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by slashdoom** [comment]
Agent changes:
https://github.com/librenms/librenms-agent/pull/178
Info on community forum:
https://community.librenms.org/t/pi-hole-stats-not-pushed-to-influxdb/4155/8

**Comment by laf** [comment]
This will break for those people using the old api.

Our app stuff doesn't do versioning right now until it's moved to passing data via json. Someone else is working on that so I'm not sure that we can merge this right now.

**Comment by slashdoom** [comment]
Unfortunately, the old agent doesn't have a key/value format.  It just spit out numbers and the poller used the order of those number to decide what they were.  So I could probably make these able to work for either API version but I probably can't make it work with both the old and new agent.  Not sure if that would be good enough?

**Comment by laf** [comment]
I do think that it needs to maintain backwards compatibility otherwise we just break things for everyone. Maybe @VVelox could chip in here as he's refactoring the apps to json.

**Comment by slashdoom** [comment]
Yeah, that would be great.  I've looked at some of the app to json PR's and it looks cool but doesn't seem like it is currently written to work with the app agent.  Just snmp extends because the snmpget is written into the json parser unless I'm missing something.

**Comment by laf** [comment]
For us to merge this you'd have to send a notification out to people to say wha they will need to do make this work for them. I'd suggest create a thread on the community site then posting a notification: https://github.com/librenms/librenms.github.io/pull/102/files

**Comment by murrant** [comment]
@slashdoom why not allow snmp extend?

**Comment by slashdoom** [comment]
Hey @murrant, this was written to do both agent and snmp extend.  My point above was just that the new apps to json functions don't appear to be written to work with the agent.  So if I wanted to use whatever version control features are built into the apps to json functions I would either have to figure out how to rework them work with the agent data or give up agent support altogether.

**Comment by murrant** [comment]
Extremely psuedo code, but yes, converting them.

if (snmp_extend_data) {
  standard_data_format = convert_extend(snmp_extend_data)
} else {
  standard_data_format = convert_agen(agent_data)
}

Usually the simplest is just to have a key->value for each item.

**Comment by murrant** [comment]
You could definitely adapt the json_app_get to check for agent data.

**Comment by VVelox** [comment]
I would be happy to begin looking at helping with this. Sorry, been a bit here and there lately.

**Comment by VVelox** [comment]
@murrant @slashdoom I can't get github to see slashdooms repo for submitting a patch to in the drop down. It will show me other repos but not theirs.

Any ways if this gets commited, I can easily throw together some JSON stuff for this.

Just been looking this over a bit more tonight and it will be easy.

**Comment by murrant** [comment]
@VVelox you can just create a separate PR with your changes for now.

**Comment by kkrumm1** [comment]
Been a year now closing for now. Feel free to reopen

**Pull request closed without merging**
