### PR TITLE
remove apc-ats os and merge sensors into apc

### PR DESCRIPTION
**Pull request by tomarch**
Thanks @FTBZ for the #9221 !
But i think we don't need a new os "apc-ats" because:
-it need to add exception in "apc" os definition  (ATS use same firmware and so the same Sysdesc)
-ATS have other sensor which is already present in "apc" discovery

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
@FTBZ Any comments?

**Comment by FTBZ** [comment]
On my side the metrics are returning errors and are not working. The problem is that to fix these metrics, we risk breaking things for PDU users. That's why I created the new OS. 

After if the metrics do not work for me, it does not matter as long as I have the state sensors.

**Comment by FTBZ** [comment]
Nice to know, seems better now with the new firmware. The MIB file was updated too, can you add the new version to the commit?

**Comment by murrant** [comment]
Instead of deleting the test data, rename it to APC (and update it if necessary)

**Comment by tomarch** [comment]
I've add the test data.
thanks.

**Comment by murrant** [comment]
You need the snmprec too.  I would suggest the name apc_ats.snmprec and apc_ats.json for the files.

**Comment by tomarch** [comment]
We want to remove apc-ats OS as we don't need it.
There's already a apc.snmprec, so i only remove apc-ats.snmprec

**Comment by murrant** [comment]
yeah the  underscore separates the os and the variant, a dash means it is part of the os name.

apc-ats  (OS is apc-ats)
apc_ats (OS is apc, variant is ats)

We use variant to allow multiple test datas per os.

**Comment by tomarch** [comment]
OK. thanks for this information.

**Comment by laf** [comment]
Updated tests.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-45-release-changelog-october-2018/6016/1

**Pull request merged**
