### PR TITLE
Alert map location fix

### PR DESCRIPTION
**Pull request by KayckMatias**
Fixed location filter in alert rules

This PR fixes issues #14246 and #12921

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — APPROVED** [review]
Looks good, thanks.  I started to convert the query to Fluent/Eloquent, but it was to complex without some more analysis.

**Comment by murrant** [comment]
Generally it is better to have separate PRs for things, both look good.

**Comment by ottorei** [comment]
I think this broke the filtering on the device page itself (device -> alerts -> alert history). The Ajax-query which loads the table to the page does not have any device_id associated on the device page but the query works when done from the alerts -> alert history page.

I managed to get my installation working with this dirty and quick "fix" (includes/html/common/alert-log.inc.php, L151): 
`device_id: \'' . htmlspecialchars($_POST['device_id'] ?? $device_id) . '\'`

**Comment by murrant** [comment]
Send a fix @ottorei ?

**Comment by ottorei** [comment]
> Send a fix @ottorei ?

Sure. Not the most elegant way to fix it but at least on my setup it seems to be working. #14460

**Comment by KayckMatias** [comment]
In case what I sent doesn't work correctly? But after your PR worked again and with the location fix?

**Pull request merged**
