### PR TITLE
Added a custom sensor oid option to LibreNMS

### PR DESCRIPTION
**Pull request by erotel**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Interesting idea, but I'm unsure about this.  It only supports sensors, which are pretty easy to add and I think should always be added upstream so users don't have to add manually.

**Comment by erotel** [comment]
On the contrary, I think it's a good thing. If I want to add eg the temperature sensor that I use only, so why do it to PR. If I admit that it can be beneficial for others, then I will do a PR.
I need to use arduino to monitor temperature in a rack, but arduino has little memory, so I have to use nonstandard snmp.
In librenms, it appears to me as a generic device (I do not mind), I add customized thermometers and alerting.

**Comment by kkrumm1** [comment]
I think this would be helpful for custom SNMP OID's.

**Comment by laf** [comment]
I think this is partly the way forward. I've always thought we should have a 'custom' section where users can query single OIDs and this along with the codebase from Wireless looks like a good way forward.

I'd like to leave this open into the new year to discuss further if that's ok with everyone.

**Comment by tlkhorses** [comment]
I would like to see this. I just came from another product where I could add them in packs for a product. For instance I would add EVM, PER, PHY etc for Mimosa products or FCS errors for Mikrotiks.

**Comment by BradHooper** [comment]
I think this is a great idea as well. I have a lot of single values I'd like to monitor however don't believe it would be beneficial to all LibreNMS users to have them merged into LibreNMS as a feature.

It would be ideal if devices self discovered these custom OIDs once entered globally.

**Comment by murrant** [comment]
BTW, this doesn't allow random custom OIDs.  They need to be a sensor type that we already support.
https://docs.librenms.org/Developing/os/Health-Information/

It is already possible to add via yaml and even config.php. (Don't make local edits to yaml unless you intend to contribute upstream)

**Comment by erotel** [comment]
My test arduino snmp in rack.

```root@speedtest:~# snmpwalk -c public -v1 10.133.67.100
iso.3.6.1.2.1.1.1.0 = STRING: "Agentuino, a light-weight SNMP Agent."
iso.3.6.1.2.1.1.2.0 = STRING: "1.3.6.1.3.2009.0"
iso.3.6.1.2.1.1.3.0 = Timeticks: (530000) 1:28:20.00
iso.3.6.1.2.1.1.4.0 = STRING: "slezi2"
iso.3.6.1.2.1.1.5.0 = STRING: "serverovna"
iso.3.6.1.2.1.1.6.0 = STRING: "Italska"
iso.3.6.1.2.1.1.7.0 = INTEGER: 6
End of MIB


root@speedtest:~# snmpwalk -c public -v1 10.133.67.100 1.3.6.1.4.1.36582.0.1.1
iso.3.6.1.4.1.36582.0.1.1 = INTEGER: 180
Error: OID not increasing: iso.3.6.1.4.1.36582.0.1.1
 >= iso.3.6.1.4.1.36582.0.1.1

root@speedtest:~# snmpwalk -c public -v1 10.133.67.100 1.3.6.1.4.1.36582.0.1.2
iso.3.6.1.4.1.36582.0.1.2 = INTEGER: 170
Error: OID not increasing: iso.3.6.1.4.1.36582.0.1.2
 >= iso.3.6.1.4.1.36582.0.1.2

```

arduino


arduino1

**Comment by murrant** [comment]
A good use for this @erotel.  I think the use of this needs to be very clear in the webui.  If that is satisfied I'm fine with this.

I can think of a couple of devices that have modular sensors (using fixed oids of course) where this would be useful.

**Comment by murrant** [comment]
@erotel Just getting back to this.

I think move this to a button under the health settings tab.  (You'll have to make the tab always show up).
Have a modal pop up showing the settings you have on the "Custom OID" tab.

**Comment by laf** [comment]
I'd like to approach this slightly different but I've had no time to put my thoughts down. I'll try and get to it soon.

**Comment by laf** [comment]
Sorry for the delay on this. So here's my thoughts:

I don't think adding it to the sensors table is the overall right approach purely because someone will ask next week that it's done for wireless, processors, etc, etc.

What I think we should do is have a generic table that is similar to the way wireless or sensors work which allows people to add arbitrary OIDs in, set things like a high / low, what type of data should be returned, the section it should appear under (not to have it appear in say processors but as a processor section within 'Custom graphs' or similar.

This way people can just throw stuff into here. Allow it so people can import/export those as well to share with others as the natural concern for us is that people don't share what they've done and so people duplicate the effort all over the show.

It would take a bit of work as I think it would mean standardising the graphing library all over to make it re-usable.

What do people think to that?

**Comment by k-y** [comment]
+1 to the generic table idea

**Comment by kalamchi75** [comment]
Hi Guys, 

Thank you for the effort made to add this feature. I have tested it with a couple of custom OID and it seems to poll and graph properly. 
However, I wonder if this script can be made more generalized and customized. For instance, the drop down menu to select the sensor class, can be more general to include things like BPS (bits per second), or a field can be added to input a sensor class.  
Also, I noticed that the dbm sensor can only be added once. i.e. if I have more than one sensor in the device that reads dBm values, I cannot add them all. I can only add one, and if i try to add more, it will only update one that was added the first time. Any chance this can be modified to accept multiple dBm sensors ?
What i'm trying to achieve is to add some Mikrotik wireless sensors that are not being discovered/added automatically.

**Comment by murrant** [comment]
@kalamchi75 That kind of is not what LibreNMS is.  It is actually very easy to add those sensors (you don't even need to write code) and then share with everyone.  LibreNMS shy's away from forcing everyone to manually configure everything.  Why have 1000 people configure something when 1 person can configure it and 1000 get it without doing anything.

The reason the PR exists is some devices have attachable sensors and don't indicate what kind of sensor is attached via snmp.  I suspect the reason it hasn't been merged is there is a lot of confusion that is for general use.

**Comment by murrant** [comment]
Closing in favor of #8738

**Pull request closed without merging**
