### PR TITLE
fix: Validate email addresses used in alerting

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7814

### CODE REVIEW

**Comment by kkrumm1** [comment]
We put Asset Tags into the sys contact on our switches. This shouldn't break anything?

**Comment by laf** [comment]
As in for the email address or the name?

We only check the something@domain.com part so if you have something@domain.com <asset tag> then it's fine.

If the asset tag is the email address but it's not a genuine email address then this will no longer attempt to send emails to that address (which is good) but if you have the correct options set, we fall back to the default contact you have defined.

**Comment by kkrumm1** [comment]
okay it's just a string of numbers. Should be okay then. 👍 

image

**Comment by laf** [comment]
So that would never have sent an email before anyway. This will mean that you still have a chance to fall back to a valid email so it's a good thing :)

**Pull request merged**
