### PR TITLE
Add OS detection for macOS Sierra

### PR DESCRIPTION
**Pull request by florianbeer**
- [x ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Darwin Kernel Version 16

### CODE REVIEW

**Comment by florianbeer** [comment]
**sysDescr:** `Darwin hostname.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 201     6; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64`

How do I get the sysObjectID? `snmpwalk` only gives me the following string, but I guess that's not what's needed here: `SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.255`

**Comment by florianbeer** [comment]
I think I've got it now:

`system.sysObjectID.0` = `.1.3.6.1.4.1.8072.3.2.255`

**Comment by Rosiak** [comment]
Just a quick question @murrant, is it valid to use 1.3.6.1.4.1.8072.3.2.255, since this is documented as "unknown"?

**Comment by murrant** [comment]
@rosiak for tests yes!  but we do not want to use it in solely in our detection code.  Having the full sysObjectID in tests will help identify when we make mistakes like that.

**Pull request merged**
