### PR TITLE
Proper State Monitoring

### PR DESCRIPTION
**Pull request by Rosiak**
#2694, #1365, #1236

First attempt of making a more useable state monitoring system.
Many thanks to @vpsman for the initial code ( https://github.com/vpsman/librenms/commits/issue-2694 ), I hacked my way through the last bits & bobs.

screen shot 2016-02-26 at 23 24 59

screen shot 2016-02-26 at 23 48 51

ToDo:

- Add more states(Only for Cisco power supply atm.)
- Create a state overview page(Current empty)
- Convert old state values, this implementation breaks the overlib stuff(But I have yet to hear anyone actively using /states...)
- Be able to not draw a graph

### CODE REVIEW

**Comment by laf** [comment]
Got it on my local install testing away.

1. I think we need some docs to help people write state sensor modules.

2. Going to: /health/metric=state/ from the Main navbar leads to a blank page where as going to /device/device=18/tab=health/metric=state/ shows the single state I have for my switch.

Let me know if I can help.

**Comment by Rosiak** [comment]
Added more sensors, here's output from a 4500X
screen shot 2016-02-27 at 01 56 27

**Comment by Rosiak** [comment]
@laf 
1. Yeah agree.
2. Yup, as stated in the PR text(Top), the current page is empty. I imagine using the template from temps etc. should be fairly easy.

**Comment by laf** [comment]
Brill :)

Also, needs high / low limits in function sensor_limit(). Maybe use the state_translations table.

**Pull request merged**
