### PR TITLE
Revert "Mattermost Alert Transport"

### PR DESCRIPTION
**Pull request by TheGreatDoc**
Reverts librenms/librenms#9711

Due to that PR removing .htaccess files and making unable to load webui

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
@gpant if you dont mind doing a new PR but without removing the .htaccess files ;)

Also, the PR removes html/includes/collectd/config.php and resources/views/alerts/templates/default.blade.php 

Im pretty sure that shouldnt be there

**Comment by gpant** [comment]
@TheGreatDoc I will re submit the PR using git directly, I didn't notice vscode did that in the second commit I am really sorry.

**Comment by zombah** [comment]
@TheGreatDoc and why you reverted #9673? It seems it is different PR

**Comment by zombah** [comment]
Yes revert commit is empty, didn't noticed, sorry for the noise

**Pull request merged**
