### PR TITLE
Check the sysObjectID before trying to detect ILO temp sensors.

### PR DESCRIPTION
**Pull request by murrant**
What do you think of this fix?  To simple or just incorrect?

issue #3107

### CODE REVIEW

**Comment by Rosiak** [comment]
:+1:

**Comment by laf** [comment]
If 1.3.6.1.4.1.232 is a relevant oid then yeah looks good.

**Comment by murrant** [comment]
TIL: adding `?w=1` to the github url makes the diff ignore whitespace.

After some more checks, I think this is good to merge.
:+1:

**Comment by laf** [comment]
Handy tip :)

**Pull request merged**
