### PR TITLE
feature: Add more Dell iDrac state sensors

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Any chance of test data :)?

**Comment by Rosiak** [comment]
Will add when I'm back from vacation :)

**Comment by murrant** [comment]
@Rosiak you need to add the json file `tests/data/drac.json` too :) If you haven't generated that yet, run `./scripts/save-test-data.php -o drac -m sensors`

**Comment by laf** [comment]
I've pushed the json file so this can be merged once it's passed tests.

**Comment by laf** [comment]
Or not. I love our tests but sometimes, I hate our tests :(

**Comment by murrant** [comment]
I think we need better feedback when things fail, but I have no idea how to do that as sometimes it is something esoteric.

**Comment by murrant** [comment]
I get this output everytime I add it.  The reason you couldn't find the test bug is because it is a code bug:
image

**Comment by murrant** [comment]
Oh and looking at it more closely, the bug is in the old state code.........

**Comment by laf** [comment]
Thanks for taking a look at this @murrant

**Comment by murrant** [comment]
No problem.  The fix was `-e` ;-)

**Pull request merged**
