### PR TITLE
refactor: rewrite arp-table discovery

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Now uses many, many less sql queries
Checks both ipNetToPhysicalPhysAddress and ipNetToMediaPhysAddress for data
Should support vrf better
Remove unused, broken function port_by_id_cache()
Fixes: #4559

### CODE REVIEW

**Comment by laf** [comment]
Works ok for me. Actual slight increase in discovery time from 1m09 to 1m22.

However the formatting with debug on is a bit, erm awful:

```
...SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126514']
...SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126515']
...SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126520']
.......................................................................................................................................................SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126521']
.....................................................................................................................................................................................................................................................SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126522']
........SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126526']
......................................................SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126529']
....................SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126531']
...SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126538']
............SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126540']
.............SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126542']
............SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126548']
.................SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126549']
...SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126550']
............SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126558']
.............................................SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126559']
...SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126561']
....SQL[SELECT * FROM `ports` WHERE `device_id` = '3006' AND `ifIndex` = '151126562']
..........SQL[SELECT * FROM `ports` WHERE `device_id` =
```

**Comment by murrant** [comment]
@laf, I agree, how can I make it better, skip the dots during debug?

**Comment by murrant** [comment]
Reason for the time increase is we fetch both SNMP oids every time now :-(.  The reason is as I posted in the other PR, sometimes one doesn't contain all the data.

**Comment by laf** [comment]
Will take a look at the code that does the output and see. We do the same in other modules so wonder how it is there.

**Pull request merged**
