### PR TITLE
Added Palo Alto Networks Firewall SNMP trap handling.

### PR DESCRIPTION
**Pull request by fidotas**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by fidotas** [comment]
We're using this internally for monitoring and responding to PAN firewall SNMP traps. Thought it may be useful for others.

**Comment by Jellyfrog** [comment]
Would you mind adding tests for this?

**Comment by fidotas** [comment]
> Would you mind adding tests for this? You can find inspiration here; https://github.com/librenms/librenms/tree/master/tests/Feature/SnmpTraps

Will do. Thanks.

**Comment by Jellyfrog** [comment]
@fidotas if you commit your new changes in the same branch they will show up here!

**Comment by laf** [comment]
@fidotas how are you getting on with the test data? Need any help?

**Comment by Jellyfrog** [comment]
@fidotas Closing this due to inactivity, please feel free to reopen if you continue working on it!

**Pull request closed without merging**
