### PR TITLE
Add support for Forcepoint NGFW 6.10 and older

### PR DESCRIPTION
**Pull request by vhuk**
Add support for Forcepoint NGFW 6.10

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @vhuk 
Did you try to implement the storage support using the YAML form ? did you encounter any issue ? We prefer to use this method instead of the PHP code, easier to maintain longterm.

Thx

**Comment by vhuk** [comment]
@PipoCanaja, I couldn't find any cases where YAML was used for storage, so I assumed it isn't possible. That said, I'm more than happy to refactor if you can point me to right direction!

**Comment by PipoCanaja** [comment]
> @PipoCanaja, I couldn't find any cases where YAML was used for storage, so I assumed it isn't possible. That said, I'm more than happy to refactor if you can point me to right direction!

Of course you couldn't because storage is not yet supported in YAML ... my bad ... should get more sleep I guess :) 
So that PR looks pretty good. 
Last thing you can try to do, is generate the JSON test file as it will be posted just below. If you have issue doing that, I'll do it for you.

**Comment by vhuk** [comment]
Added the json. Please let me know if I missed anything else.

**Comment by PipoCanaja** [comment]
Thanx @vhuk ! For some reason the JSON file was not including all the modules. I added them, so let's wait for the automated tests to complete.

**Comment by PipoCanaja** [comment]
I'll send a quick fix, to properly get the version, and also fix the description for processors (get an ID for each of them).

**Review by PipoCanaja — APPROVED** [review]
LGTM, thanx for your first PR in the project !

**Pull request merged**
