### PR TITLE
Add date to git version info

### PR DESCRIPTION
**Pull request by murrant**
valdiate: local tz, rfc2822
poller: iso 8601
about: iso 8601 -> browser local
Also, do not fetch github info on about page, it isn't used.

Fixes: #3775

### CODE REVIEW

**Comment by Rosiak** [comment]
👍

**Comment by laf** [comment]
```bash
Version info:
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (%cI) at position 0 (%): Unexpected character' in /opt/librenms/validate.php:79
Stack trace:
#0 /opt/librenms/validate.php(79): DateTime->__construct('%cI')
#1 {main}
  thrown in /opt/librenms/validate.php on line 79
```

**Comment by laf** [comment]
```
git show --pretty='%H|%cI' -s HEAD
846c5ab0c9b8b098f56e91df41a819ecefb51fc5|%cI
git version 1.8.3.1
```

**Comment by murrant** [comment]
Dang, I'll come up with something for old versions of git.  Thanks @laf

**Pull request merged**
