### PR TITLE
Change strikethrough for recovered alerts

### PR DESCRIPTION
**Pull request by Olen**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by Olen** [comment]
Seems like I probably don't use this correctly, as all changes I make in my fork now automatically shows up here as part of the PR.

**Comment by laf** [comment]
Thanks for this, however the pull request contains more than just strike through changes - did you mean to submit all of that?

**Comment by Olen** [comment]
No, sorry. I am just not experienced enough in github magic.
I should probably have made several branches and submitted them as different PRs

**Comment by Olen** [comment]
Closing this to start over with branches...

**Pull request closed without merging**
