### PR TITLE
Added support for UIO monitoring on APC NMUs

### PR DESCRIPTION
**Pull request by Jimmy-Cl**
Please give a short description what your pull request is for

Added support for temperature and contact switch monitoring for APC NMUs.

image

This is used with UPS Network Management Card 2 & 3 which are installed in a standalone unit without a UPS. When they are used without a UPS they report UIO data on different OIDs. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@Jimmy-Cl Thanks for the contribution.  There are a couple of issues with your PHP.  But can you change these to yaml instead?
Let me know if you need any help.

**Comment by Jimmy-Cl** [comment]
@murrant Cheers for the feedback. I did try to use YAML originally however I found it wouldn't handle the IF statements. Just for some context on why I'm am using the below, 
`$device_type = snmp_get($device, '.1.3.6.1.2.1.1.2.0', '-OqvnU', 'PowerNet-MIB');` 
`&& $device_type == '.1.3.6.1.4.1.318'`
One of our other UPS's an APC SMX750i will show the above temperature and state sensors twice without the IF statement as they are already monitored with different OIDs, I added the Device OID check to make sure it can only be used for the standalone environmental monitoring units. I will try again with YAML if you are still not happy or let me know what your issues were with the PHP and I will try it improve that.

**Comment by murrant** [comment]
@Jimmy-Cl You would do that like this:

pre-fetch it because the value is not already fetch
```yaml
        pre-cache:
            data:
                -
                    oid: SNMPv2-MIB::sysObjectID.0
                    snmp_flags: '-On'
```

then in your sensors:
```yaml
                    skip_values:
                        -
                            oid: SNMPv2-MIB::sysObjectID.0
                            op: '!='
                            value: '.1.3.6.1.4.1.318'
```

(this may not be exactly correct as I didn't test it)

**Comment by murrant** [comment]
Actually, It is even easier than that (you don't need the pre-fetch):
                    skip_values:
                        -
                            device: sysObjectID
                            op: '!='
                            value: '.1.3.6.1.4.1.318'

**Pull request closed without merging**
