### PR TITLE
Add support for Teltonika TRB500

### PR DESCRIPTION
**Pull request by Martin22**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 16327`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @Martin22 
Could you please fix the permissions on the files (.gitignore) that you changed by mistake ? 
Thx

**Comment by PipoCanaja** [comment]
close to re-run the tests

**Comment by Martin22** [comment]
Hello. Why wasn't the request merged? Is something missing? Do I need to do something else?

**Comment by laf** [comment]
We already have 3 rutos* definitions, why do we need this one? The idea behind the OS is it's not device specific and will cover a range of devices.

**Comment by laf** [comment]
> > We already have 3 rutos* definitions, why do we need this one? The idea behind the OS is it's not device specific and will cover a range of devices.
> 
> This is a completely different device. This one is a gateway, while the other devices are routers. There are also modems. It also uses a completely different MIB than the ones currently in use.

It's not about the device though, it's about the OS they run unless it's the same OS for completely different device types. You have this down as a wireless device in discovery but it's classed as a gateway so probably means it should just be a network type. Having different MIBS is also fine and can be handled in yaml.

@librenms/reviewers Any thoughts?

**Comment by Martin22** [comment]
@librenms/reviewers @laf 

I understand that having multiple definitions for one OS is wrong. Theoretically, I can modify rutos-rutx, which is the most similar and has the most matching OID, but even these devices have different MIBs. In one, there are OIDs for latitude and longitude, and in the other, they are missing. This is not the only difference; there are several others. Therefore, the fault lies with Teltonika for not unifying the MIB and OID. Additionally, I had to translate string values into numeric values, which breaks existing graphs, which is undesirable as well. So, please approve or let me know how else to proceed. Thank you.

**Comment by Martin22** [comment]
@laf, @PipoCanaja, @murrant 

I have to say that I am very disappointed with this approach. Another two months have passed without anyone responding or merging the PR. Could someone please comment on this?

Thank you.

**Comment by laf** [comment]
@Martin22 This is purely a community run project and whilst we 100% appreciate you helping to improve it, the maintainer's time is also given for free and it can be difficult for us to get through everything promptly. GitHub also doesn't make it easy to keep track of things.

You should leave your PR open until someone has time to get to it.

**Comment by Martin22** [comment]
I disagree with PR https://github.com/librenms/librenms/pull/16556, as the RUTX series is not the TRB series, they have completely different MIBs. Not to mention the very poor implementation for RUTX. While it is possible that RUTX SNMP returns numeric values (I cannot confirm as I do not have such a device), for TRB, SNMP unfortunately returns strings, requiring remapping. I kindly ask the maintainers to reconsider this, revert the merged PR, and merge my PR instead.

**Pull request closed without merging**
