### PR TITLE
Clean up old cambium code / migrate more data to wireless sensors

### PR DESCRIPTION
**Pull request by pheinrichs**
I would very much prefer testers for this PR. I bit of old code so I want to verifiy nothing funny is happening for anyone. On my local dev machine it looks all okay after a week of testing.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Looks ok to me but we'll have to notify users that they will lose historical data (I realise the graph will still show the old data but we should still tell people).

Any reason the OS polling files have been removed?

**Comment by pheinrichs** [comment]
The Cambium / Canopy OS's don't exist anymore. They were split into pmp, ptp, cmm, etc. So those polling files weren't really doing anything, along with there corresponding sensor files.

**Comment by laf** [comment]
If you can chuck a notice up like you did here https://github.com/librenms/librenms.github.io/pull/99/files just explaining that the data is going to move elsewhere then we can merge this in.

**Comment by pheinrichs** [comment]
Notification PR sent: https://github.com/librenms/librenms.github.io/pull/101

**Comment by laf** [comment]
Notification merged.

/remind me to merge this on Monday the 4th July 2018

**Comment by laf** [comment]
Was very late merging this in :(

**Pull request merged**
