### PR TITLE
[app] mysql-stats rewrite

### PR DESCRIPTION
**Pull request by crcro**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

requires: https://github.com/librenms/librenms-agent/pull/291

screen_01

screen_02

### CODE REVIEW

**Comment by SourceDoctor** [comment]
@librenms/reviewers 
someone uses MySQL Monitoring and could verify rewrite doesn't break something?

**Comment by paulierco** [comment]
I still have the problems with mysql app - stats when rrdcache is enabled. This is a old story that was marked as fixed. Issue have been reported here. https://github.com/librenms/librenms/issues/6223.

I have distributed polling, tried to disable rrdcache and app recovered. Enable it again, app-graphs  broken.

**Comment by paulierco** [comment]
Doesn't work for me. I'm doing something wrong?

**Comment by crcro** [comment]
@paulierco ... did you use the new mysql-stats from librenms-agent? what is the output of script if run in console?

**Comment by paulierco** [comment]
Just checked and i'm using SNMP extend. It should work in the same way, right ? 
poller -> [https://p.libren.ms/view/c882fb6d](https://p.libren.ms/view/c882fb6d)
discovery -> [https://p.libren.ms/view/f130003a](https://p.libren.ms/view/f130003a)

**Comment by crcro** [comment]
i see "mysql:-3:Invalid JSON" response during polling, can you run the mysql-stats script locally and see the output?

**Comment by paulierco** [comment]
`paulierco@mysql:~$ sudo /etc/snmp/mysql-stats
Traceback (most recent call last):
  File "/etc/snmp/mysql-stats", line 24, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'
paulierco@mysql:~$
`

**Comment by SourceDoctor** [comment]
there should be a configfile to overwrite login credentials to database for getting data

**Comment by crcro** [comment]
> `paulierco@mysql:~$ sudo /etc/snmp/mysql-stats Traceback (most recent call last): File "/etc/snmp/mysql-stats", line 24, in <module> import MySQLdb ModuleNotFoundError: No module named 'MySQLdb' paulierco@mysql:~$ `

seems like that your are missing the python3 mysqldb package, please install it via your OS package manager or pip

**Comment by paulierco** [comment]
Scripts run fine but when i checked SNMP:

`snmpwalk -v2c -c public 127.0.0.1 .1.3.6.1.4.1.8072.1.3.2.3.1.2.5.109.121
iso.3.6.1.4.1.8072.1.3.2.3.1.2.5.109.121.115.113.108 = STRING: "Traceback (most recent call last):
  File \"/etc/snmp/mysql-stats\", line 185, in <module>
    with open(temp_file, 'w') as file:
PermissionError: [Errno 13] Permission denied: '/tmp/mysql-stats.old'"
`
I fixed now the permision (it works after) and waiting for graphs.

**Comment by paulierco** [comment]
Still not working.
Discovery -> https://p.libren.ms/view/6183a5f2
Polling -> https://p.libren.ms/view/8d45fe24

From poller to mysql using snmp:

`librenms@librenms5:~$ snmpwalk -v2c -c public librenms-mysql.local .1.3.6.1.4.1.8072.1.3.2.3.1.2.5.109.121
iso.3.6.1.4.1.8072.1.3.2.3.1.2.5.109.121.115.113.108 = STRING: "{\"data\":{\"com_delete\":0,\"com_insert\":28,\"com_insert_select\":0,\"com_load\":0,\"com_replace\":0,\"com_replace_select\":0,\"com_select\":508,\"com_update\":128,\"com_update_multi\":0,\"max_connections\":0,\"max_used_connections\":0,\"aborted_clients\":0,\"aborted_connects\":0,\"threads_connected\":-2,\"connections\":10,\"table_open_cache\":0,\"open_files\":0,\"open_tables\":0,\"opened_tables\":0,\"ib_bpool_size\":0,\"ib_bpool_dbpages\":-438,\"ib_bpool_free\":89,\"ib_bpool_modpages\":-23,\"ib_bpool_read\":113109,\"ib_bpool_created\":3,\"ib_bpool_written\":599,\"ib_merged_ops_insert\":29,\"ib_merged_ops_delete\":0,\"ib_discarded_ops_insert\":0,\"ib_discarded_ops_delete\":0,\"ib_search_cache\":-30207,\"ib_search_non_cache\":-15211,\"ib_io_read\":113046,\"ib_io_write\":840,\"ib_io_log\":175,\"ib_io_fsync\":350,\"ib_iop_log\":0,\"ib_iop_sync\":0,\"ib_iop_flush_log\":0,\"ib_iop_flush_bpool\":0,\"ib_iop_ibuf_aio\":0,\"ib_iop_aioread\":-63,\"ib_iop_aiowrite\":0,\"innodb_log_buffer_size\":0,\"ib_log_flush\":71631,\"ib_log_written\":71631,\"innodb_rows_deleted\":0,\"innodb_rows_inserted\":21,\"innodb_rows_read\":423377,\"innodb_rows_updated\":130,\"ib_spin_rounds\":23554,\"ib_spin_waits\":4048,\"ib_os_waits\":230,\"ib_tnx\":552,\"key_read_requests\":0,\"key_reads\":0,\"key_write_requests\":0,\"key_writes\":0,\"bytes_received\":212796,\"bytes_sent\":2167152,\"qcache_queries_in_cache\":-30,\"qcache_hits\":238,\"qcache_inserts\":184,\"qcache_not_cached\":50,\"qcache_lowmem_prunes\":0,\"query_cache_size\":0,\"qcache_free_memory\":22408,\"select_full_join\":17,\"select_full_range_join\":0,\"select_range\":22,\"select_range_check\":0,\"select_scan\":81,\"slow_queries\":0,\"sort_rows\":388,\"sort_range\":2,\"sort_merge_passes\":0,\"sort_scan\":48,\"table_locks_immediate\":669,\"table_locks_waited\":0,\"created_tmp_disk_tables\":10,\"created_tmp_tables\":47,\"created_tmp_files\":0},\"error\":\"0\",\"errorString\":\"\",\"version\":\"1\"}"
librenms@librenms5:~$
`

**Comment by crcro** [comment]
if you have an old rrd (from the previous script version) you should rename it and let the poller create a new one with the current datasets.

**Comment by paulierco** [comment]
Still the same. Might be something from me, i don't know. 
Anything you would like to try?

**Comment by crcro** [comment]
> 
> 
> Still the same. Might be something from me, i don't know.
> Anything you would like to try?

can you please provide an output of the following (on librenms server):
./poller.php -h <<your mysql host id>> -d -m applications

**Comment by paulierco** [comment]
link -> https://p.libren.ms/view/7588cde2

**Comment by crcro** [comment]
from the output data is pushed into the RRD.
when you click on the **Show RRD Command** on the failed graph what is the output?

**Comment by paulierco** [comment]
RRDTool command -> https://p.libren.ms/view/7169c4b3

RRDTool Output

ERROR: rrdc_fetch: Unable to parse header `DSName'

**Comment by crcro** [comment]
this result is using rrdcache enabled?

**Comment by paulierco** [comment]
Yes, this is with rrdcache enabled.

**Comment by murrant** [comment]
@crcro looking good, but you need a better migration plan for users.

**Comment by crcro** [comment]
@murrant ... i don't think that earlier version worked anymore, i couldn't make it work on my systems
@librenms/reviewers ... can someone confirm/infirm working of existing mysql-stats app?

**Comment by murrant** [comment]
Seems to be working:
image

**Comment by paulierco** [comment]
Works without rrdcached. 
@murrant any idea how to fix this? (i'm currently using version RRDCacheD 1.5.5).

**Comment by crcro** [comment]
from the original bug filled by @murrant on rrdtool (https://github.com/oetiker/rrdtool-1.x/issues/782) it looks like you need to recompile rrdcache with RRD_CMD_MAX set to a higher value

**Comment by paulierco** [comment]
This is very likely to break some other things. He did some workaround at that moment that looks like doesn't work anymore.

**Comment by paulierco** [comment]
For me it's fixed. Spend some time and figured out how to compile rrdtool and rrdcached on ubuntu 16.04. I changed RRD_CMD_MAX to 8192. 

> librenms@librenms:~$ rrdtool -v
> RRDtool 1.7.2  Copyright by Tobias Oetiker <tobi@oetiker.ch>
>                Compiled May  3 2020 16:23:48

> librenms@librenms:~$ rrdcached -v
> invalid option -- 'v'
> RRDCacheD 1.7.2
> Copyright (C) 2008,2009 Florian octo Forster and Kevin Brintnall

**Comment by SourceDoctor** [comment]
@crcro @paulierco something new here?

**Comment by paulierco** [comment]
Looks good to me. Current users have to migrate to the new script, right ?

**Comment by SourceDoctor** [comment]
@crcro could you please resolve conflicts?

also as @murrant said:
> @crcro looking good, but you need a better migration plan for users.

for compatibility with old agent scripts use agent script versioning.
As Example take a look here: https://github.com/librenms/librenms/pull/11661
LibreNMS will inform users about a new existing Agent Script Version

**Comment by paulierco** [comment]
@crcro, any update here?

**Comment by murrant** [comment]
@crcro this pull request has gone stale.  Closing it. Feel free to re-open if you update it.  Thanks.

**Comment by murrant** [comment]
@paulierco if you want to update and submit, you are more than welcome to.

**Comment by paulierco** [comment]
Hi @crcro, can we restart this?

**Pull request closed without merging**
