### PR TITLE
Remove legacy db config

### PR DESCRIPTION
**Pull request by murrant**
Should be configured via the environment or .env.

Note: dotenv imports .env in LibreNMS.get_config_data()

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by f0o — APPROVED** [review]

**Review by f0o — APPROVED** [review]

**Comment by laf** [comment]
This requires #16386 as well because without it you get:

```
librenms@utils:~$ php config_to_json.php 

In config_to_json.php line 17:
                                                                           
  Call to undefined method LibreNMS\Config::populateLegacyDbCredentials()  
                                                                           
```

**Comment by f0o** [comment]
@laf I think that was implied as this was the fix to the issue created by #16349

Maybe we can just staple them all together since #16349 was reverted and a new PR was opened - Depends if you want to revert the revert or just re-merge

**Comment by Jellyfrog** [comment]
Maybe someone should test it before we merge it

**Review by f0o — APPROVED** [review]
poller-wrapper.py and discovery-wrapper.py run fine after applying the PR

**Pull request merged**
