### PR TITLE
Added rittal-cmc (LCP Plus)

### PR DESCRIPTION
**Pull request by mpikzink**
skip_values opperand 'not_in_array' returns an error in pre-commit but in principal it's running. Can someone help?

1) LibreNMS\Tests\YamlTest::testDiscoveryDefinitionSchema
rittal-cmc.yaml does not validate. Violations:
[modules.sensors.fanspeed.data[0].skip_values[0].value] Array value found, but an integer or a string is required
[modules.sensors.temperature.data[0].skip_values[0].value] Array value found, but an integer or a string is required
[modules.sensors.temperature.data[1].skip_values[0].value] Array value found, but an integer or a string is required
[modules.sensors.temperature.data[2].skip_values[0].value] Array value found, but an integer or a string is required
[modules.sensors.temperature.data[3].skip_values[0].value] Array value found, but an integer or a string is required

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @mpikzink ,
On the validation issue. Will update the PR.

**Comment by PipoCanaja** [comment]
Hi @mpikzink 
Not very familiar with the YAML validation but I am probably on the right tracks now. We'll see how Travis enjoys the changes in the schema, and we'll continue from there. 
Thanx for your PR, and we'll help to to get it passed the test and merge it !

**Comment by PipoCanaja** [comment]
Hi @mpikzink 
I have a question : Is there a way (other than statically writing the array) to find out which sensor does what type of measurement (water, air) ?
And for the fans, for instance, you only poll unit 2 ? 
Do all sets come with 2 units ? 

If any of this is dynamic, then we need to support it (or the next user that has the same device will update this file and break your device ... )

**Comment by mpikzink** [comment]
> Hi @mpikzink
> I have a question : Is there a way (other than statically writing the array) to find out which sensor does what type of measurement (water, air) ?
I didn't find a way to do I dynamic. I just found this UnitNumbers in the MIB. For me there is no structure get it only the Comments in the MIB.
> And for the fans, for instance, you only poll unit 2 ?
Oh, I missed to poll unit 1 (In my setup there will not be a FAN) 
> Do all sets come with 2 units ?
In my Setup (16 simular Rittal Racks LPCs) the sensors are mapped to sensor 2. There is just a Door sensor on unit1 but in the mib the Types of Unit1&2 are the same. I think this Sensors can be modified my the manufacturer for diffentent use cases.
> If any of this is dynamic, then we need to support it (or the next user that has the same device will update this file and break your device ... )

**Comment by PipoCanaja** [comment]
OK, then we have good chances that this template would be good. Please update the YAML file for the fans in unit 1 (should not impact the test files as you don't have any fans in unit 1) and we should be good to go. (meaning tomorrow for me :) )
Bye

**Comment by PipoCanaja** [comment]
All right @mpikzink 
Thanx for the PR, ready for merge now.

**Comment by mpikzink** [comment]
> All right @mpikzink
> Thanx for the PR, ready for merge now.

Thanks for your Support @PipoCanaja so I prepare for the next PR, tomorrow or so... ;-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
