### PR TITLE
Update  Allow discovery of IAP radios on Aruba Virtual Controller - Arubaos.php

### PR DESCRIPTION
**Pull request by kkrumm1**
Allow discovery of IAP radios on Aruba Virtual Controller -

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
@kkrumm1 looks like you pasted the diff in instead of applying it :)

**Comment by murrant** [comment]
@kkrumm1 I fixed up your changes I think , please check it

Honestly when you get into submitting code changes, it is just easier to use the command line (to me at least).  I suggest you give this a read: http://docs.librenms.org/Developing/Using-Git/

:)   We're happy to answer questions.

**Comment by kkrumm1** [comment]
Thanks murrant, will do..i got some reading to do. 
I just did pull test and got this message "<stdin>:44: trailing whitespace."  not sure if something to be concerned about or not. 
The Pull request did work tho.  👍

**Comment by murrant** [comment]
If you want to for practice, you can discard this and try again :)

**Comment by kkrumm1** [comment]
so if i wanted to add the ability to see how many wireless clients are connected.... looking the Aurba SNMP mib guide it says it should be this OID. 1.3.6.1.4.1.14823.2.3.3.1.2.4. 

Could i edit it here like this?

**Comment by laf** [comment]
The file already has a `discoverWirelessClients()`. Is this not doing what you need?

**Comment by kkrumm1** [comment]
It's not pulling that data. :(

**Comment by laf** [comment]
The current one looks valid as well. The one you've mentioned, I don't see that in our MIB, do you have an up to date MIB?

**Comment by kkrumm1** [comment]
i think they are both vailed one is for the normal AP and mine is for IAP. 
here is the Aurba IAP mib updated this month. https://gist.github.com/kkrumm1/df47e0869969194843c0de2df70dab86#file-arubaiapmib

i can also get you the updated Aurba OS mib.

**Comment by laf** [comment]
Ah ok, I guess that can be added. We can merge this for now and then add further support in another PR.

**Comment by kkrumm1** [comment]
ok sounds good 👍

**Pull request merged**
