### PR TITLE
[UI] Change alert style for eventlog short

### PR DESCRIPTION
**Pull request by arjitc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

Before,

chrome_2020-04-15_00-26-14

After,

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
why hardcode colours, instead using labels, which are global equal?

**Comment by arjitc** [comment]
Good point about that, I'll check into that.

Otherwise, is the (slight) change in the UI good to look at?

**Comment by SourceDoctor** [comment]
you remove variable definition for $icon, and later $icon is used.

i prefer the before look. You can see, that's a single event with it's severity.
New look could be missunderstood as events grouped by severity, so i'm not sure if it should be implemented.

**Comment by kkrumm1** [comment]
First, thank you for your work. But I have to agree with source doc on this.

**Comment by arjitc** [comment]
Ah okay -- no worries, I'll close this one :+1: :)

**Pull request closed without merging**
