### PR TITLE
Initial support for Moxa EDS-4000 Series switches

### PR DESCRIPTION
**Pull request by kmodzel**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @kmodzel 
Looks good for the snmprec file. Could you also generate the JSON and add it to the PR please? 
Thanx

**Comment by kmodzel** [comment]
> Hi @kmodzel Looks good for the snmprec file. Could you also generate the JSON and add it to the PR please? Thanx

Hi, unfortunately the generated file contains "null"

more /opt/librenms/tests/data/Moxa-EDS-4000-Series_eds-4012-4gc.json
null

**Comment by PipoCanaja** [comment]
any error during the file generation ?

**Comment by kmodzel** [comment]
> Can you move the MIBs into the moxa mib directory? It looks like they are finally sharing mibs across more than one model. Do you think the OS name will be appropriate long term?

This is a new model series of switches and they provided completely new set of mibs for them.

https://www.moxa.com/getmedia/05f990f8-bf8c-452e-b381-3a4483382b4d/moxa-eds-4000-g4000-series-mib-software-package-v3.2.zip

**Comment by murrant** [comment]
Sure, but there seems to be no conflicts and we try to group the mibs by vendor.

**Comment by kmodzel** [comment]
> Sure, but there seems to be no conflicts and we try to group the mibs by vendor.

It makes sense. Done.

**Review by murrant — APPROVED** [review]

**Pull request merged**
