### PR TITLE
Copy existing Alert Rule

### PR DESCRIPTION
**Pull request by SourceDoctor**
copies existing/used Alert Rule for easier/faster writing equal Alert Rule with similar values

image

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ability-to-duplicate-alert-rule/1698/4

**Comment by murrant** [comment]
Hmm, interesting.  I would have just added a duplicate button and then created a copy in the backend with a different name.

**Comment by SourceDoctor** [comment]
my thought was, to have an existing rule as 'Template', so it's copied but directly open for changing parameters similar to Collections

**Comment by SourceDoctor** [comment]
@laf 
i added " - Copy" to it as you've seen ...
Thinking result will be the same.
counting with #1 expects another copy will be #2 if no renaming happens ;-)

**Comment by laf** [comment]
> i added " - Copy" to it as you've seen ...

That's fine as the window is open to edit it already.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
