### PR TITLE
Added conntrack support

### PR DESCRIPTION
**Pull request by angryp**
This commit adds visualization and installation instructions of Netfilter Conntrack application that has been pulled recently: https://github.com/librenms/librenms-agent/pull/200

Visual representation of data as an example: 
librenms_conntrack

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jozefrebjak** [comment]
Hi, this app will be very useful, but I can't get this to working, when I try to run conntrack.pl I am getting errors.

```
/etc/snmp# ./conntrack.pl 
Can't read data from [ conntrack ] tools, error: Adresár alebo súbor neexistuje at ./conntrack.pl line 173.
```

There is a line about ipv6. I am don't using ipv6. There is also a comment ` conntrack-tools can't shows ipv4+ipv6 both..`

please what this means ? How can I run this script without ipv6.

**Comment by angryp** [comment]
Hello @jozefrebjak!

Let's debug this, had not stumbled upon this issue: 
1. Have you followed the steps described in the docs of this commit? 
2. What OS are you running? 
3. Do you see any IPv6-related entries when you run `conntrack -L` in CLI?
4. Do you see any IPv6-related output when you run `ifconfig`/`ip a`, `lsmod | grep ipv6` in CLI?

**Comment by jozefrebjak** [comment]
I am running Linux 3.0.0-21-server on Ubuntu 11.10. When I ran conntrack -L i a have 89311 connections, but I dont using ipv6 on our network.

**Comment by jozefrebjak** [comment]
@angryp It is working perfectly. This need to be merged. Thank you

**Comment by murrant** [comment]
This is waiting to be converted to json.  That way it won't have to handle legacy format.

**Comment by angryp** [comment]
> 
> 
> This is waiting to be converted to json. That way it won't have to handle legacy format.

Hello @murrant!

Can you please tell the requirements and/or show sample reference code?

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen!

**Comment by angryp** [comment]
> 
> 
> Closing due to inactivity. Feel free to reopen!

Hello @Jellyfrog!

Yes, I would like to reopen. Can you please tell the requirements and/or show sample reference code to convert this feature to json?

**Comment by Jellyfrog** [comment]
@angryp here is one example:
https://github.com/librenms/librenms-agent/pull/218 + https://github.com/librenms/librenms/pull/9680

**Comment by Jellyfrog** [comment]
@angryp Closing this due to inactivity, please feel free to reopen if you continue working on it!

**Pull request closed without merging**
