### PR TITLE
feature: RRD rename operations

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] TODO: call the rename operation at the right times from the right places

Template rename operations and only run them once

### CODE REVIEW

**Comment by laf** [comment]
I've not looked at the code much or tested but is it not worth moving this above the sql schema updates (I realise not as is), some schema changes can take a while to run, in those situations polling may happen and new files could be created before they are renamed.

Also I know this wasn't set out to address it but we still have the issue for rrdcached users without shared fs where renames won't work.

**Comment by murrant** [comment]
Is polling allowed to happen during an SQL update?

I could move this above the schema update, but I thought there was a chance the rename operation could require a newer schema.  No reason not to for now, rename should be quick.

I did think of distributed setups, but that needs work.  Perhaps a check if we have write access to a file or folder.  I'm open to ideas.

**Comment by laf** [comment]
Easiest thing was to just test it:

```bash
 ORDER BY ports.port_id]
LibreNMS\ClassLoader [[ LibreNMS\RrdRenamer > /opt/librenms/LibreNMS/RrdRenamer.php ]]
Found 1 files.
SQL[SELECT `device_id` FROM `devices` WHERE `hostname` = 'localhost']
SQL[SELECT * FROM `devices` WHERE `device_id` = '1']
SQL[SELECT * FROM `vrf_lite_cisco` WHERE `device_id` = '1']
SQL[SELECT * FROM `ports` WHERE `device_id` = 1 AND `ifIndex` = '2']
 localhost: /opt/librenms/rrd/localhost/port-2.rrd > /opt/librenms/rrd/localhost/port-id24425.rrd
SQL[INSERT INTO `eventlog` (`host`,`device_id`,`reference`,`type`,`datetime`,`message`)  VALUES ('1','1','NULL','rrd_rename',NOW(),'Renamed /opt/librenms/rrd/localhost/port-2.rrd to /opt/librenms/rrd/localhost/port-id24425.rrd')]
validvalid


-bash-4.2$ php includes/rrd_rename.php
Rename operation 001: ifIndex labeled ports
Rename operation 002: hrProcessor rename
 localhost: /opt/librenms/rrd/localhost/hrProcessor-196608.rrd > /opt/librenms/rrd/localhost/processor-hr-196608.rrd
Rename operation 003: Cisco cpmCPU rename


-bash-4.2$ php includes/rrd_rename.php
Rename operation 001: ifIndex labeled ports
Rename operation 002: hrProcessor rename
Rename operation 003: Cisco cpmCPU rename
 ciscoasa: /opt/librenms/rrd/ciscoasa/cpmCPU-1.rrd > /opt/librenms/rrd/ciscoasa/processor-cpm-1.rrd
```

Would it be beneficial to adding some unit tests?

**Comment by murrant** [comment]
Maybe, I don't see any of them changing after they are initially written, so maybe some generic tests.

I still need to figure out distributed polling.

**Comment by murrant** [comment]
Closed for renovations.

**Pull request closed without merging**
