### PR TITLE
Convert LastSync date for oxidized config info

### PR DESCRIPTION
**Pull request by Negatifff**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Why is this an option and not just done for all?

**Comment by Negatifff** [comment]
I did not dare to take such responsibility. provided the user with a choice.

**Comment by murrant** [comment]
Not making a choice increases future maintenance costs, and increases the burden on the user to configure.

This should probably follow the user's timezone setting.

**Comment by Negatifff** [comment]
this setting already looks into the user's timezone settings. optionally done because I don’t know if it will be fixed in oxidized or not. Now the author says that he will not correct it, but after some time he can change his mind. and the format is set by the user for his own convenience - for example, the Y-m-d format is unusual for me to read. I am more comfortable d.m.Y. therefore, the option suggested itself :).

**Comment by murrant** [comment]
I'm not trying to be difficult I promise, but I need you to think about some things.

How many time format/zone settings should we have?

**Comment by Negatifff** [comment]
maybe I did not quite understand the question. we have a date that needs to be transferred from the UTC timezone to the user's timezone. The user's timezone is specified in his php.ini. from there we will recognize her. but how to set the date and time format? in php.ini it is not. maybe the question is not to indicate the format of the date and time, but it seems inconvenient to me.

**Comment by samotelf** [comment]
@Negatifff are you talking about when you go to the device config the Last Sync is in UTC? I also would like this.
To clarify the Last Sync should be the system time:

@murrant not sure if this an oxidized issue or not, but do you think you can please change it?


image

**Comment by murrant** [comment]
Please use the timezone from `\config('app.timezone')`  instead of making a new setting.

**Comment by Negatifff** [comment]
to be honest, it turned out to be the most mysterious patch. I added the ability to adjust the time zone and the format of the time output, but for some reason this does not work. yes, in pkhp there is a default timezone in the config - no question, this is used. but where to get the default date and time output format? I personally find it unusual to use Y-m-d - what should I do?

**Comment by murrant** [comment]
Right now app.timezone follows the php setting, but in the future, it will allow user and/or browser to set the value.
As for time format, we try to use ISO 8601 for the most part, but for dateformats, we have them defined in the config as dateformat.compact or dateformat.long for example.

**Comment by samotelf** [comment]
> Right now app.timezone follows the php setting, but in the future, it will allow user and/or browser to set the value.
> As for time format, we try to use ISO 8601 for the most part, but for system defined formats, we have them defined in the config as dateformat.compact or dateformat.long for example.

Thank you Murrant for your reply.   
I believe I'll wait for the future release, any idea when will it be available?
Let me also take the opportunity to appreciate all your effort.

**Comment by Negatifff** [comment]
no more configs

**Comment by murrant** [comment]
@samotelf LibreNMS is a community project it will be added when ever anyone deems it worth there time to add and contributes it.  I'm just trying to keep us from kicking ourselves later if/when it is added.

**Comment by Negatifff** [comment]
@murrant thanks

**Comment by murrant** [comment]
Thank you @Negatifff  :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-67-release-changelog-august-2020/13285/1

**Pull request merged**
