### PR TITLE
Add Sensatronic E4-16 support

### PR DESCRIPTION
**Pull request by q7joey**
This adds support for 4-16 channel Sensatronics sensors. I only have the 4 channel unit to confirm.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Cant they share OS?

**Comment by murrant** [comment]
> Cant they share OS?

I asked this on Discord, it seems no. But honestly, the could be combined without much issue.

**Comment by murrant** [comment]
@q7joey make sure you generate test data so we can get this added.

**Comment by q7joey** [comment]
Yes, i'll try to get to that over the weekend.

**Comment by q7joey** [comment]
I think I have created the test data and added it to my branch. It looks 
like my pull request now shows the new files. Let me know if I did 
things correctly.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
