### PR TITLE
add discovery of mempool percent warning limit

### PR DESCRIPTION
**Pull request by vitalisator**
- Remove hardcoded mempool_perc_warn (75%) from the database
- rise a default value up to 90% (maybe need to discus that)
- add possibility to individual warn limits in mempools discover module
- set Linux and vmware limits to: Physical mem: 99%, Virtual mem: 95%, Swap mem: 10%

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Not sure setting 75% on all devices is a good idea.  All Linux servers will essentially report 100% all the time.

**Comment by vitalisator** [comment]
> Not sure setting 75% on all devices is a good idea. All Linux servers will essentially report 100% all the time.

That is because we have already this value per default in the database table

**Comment by PipoCanaja** [comment]
LGTM but not tested

**Comment by tomarch** [comment]
There's an issue with this PR, the custom %warm is always reset to the default.
Step to reproduce :
-change the %warm for a device (test with windows device).
-wait for the discovery
-the %warm come back to the default.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-57-release-changelog-october-2019/9969/1

**Pull request merged**
