### PR TITLE
SQL Schema and update restructure

### PR DESCRIPTION
**Pull request by f0o**
This PR introduces a new versioning system.

It still uses incremental numeric sql files but allows categorization of components.
This way we can introduce new components without having to bump the core schema and allow more frequent SQL-Schema updates.
It also allows 3rd parties to introduce features without conflicting with upstream SQL-Schemas.

The new file-structure is: `/sql-schema/<component>/<version>.sql`
So the last version for LibreNMS Core would be `/sql-schema/core/073.sql`.

It contains migration code.

It was tested against:
- installation from cli
- installation from http
 - including slow database (responsive check)
- migration from `73` to new schema
 - including simultaneous bumping to `74`

### CODE REVIEW

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Blocking: Upstream-Schemas got ahead, need to re-add them and solve a conflict.

**Comment by laf** [comment]
What's the reason for dropping a lot of the alter statements? Some appear to be removed and the table not updated elsewhere potentially? As an example:

```bash
-ALTER TABLE `storage` ADD `storage_free` INT NOT NULL AFTER `storage_used`;
-ALTER TABLE `storage` CHANGE `storage_size` `storage_size` BIGINT NOT NULL ,CHANGE `storage_used` `storage_used` BIGINT NOT NULL ,CHANGE `storage_free` `storage_free` BIGINT NOT NULL;
```

These changes are removed but don't appear to be put back in anywhere. I'm sure you've covered this and those changes aren't needed but I'm a bit concerned that the DB built against this won't be the same as one built before this change?

**Comment by laf** [comment]
@f0o 

Done a patch for this to make it MySQL STRICT compliant.

https://gist.github.com/laf/c6bfc95ecfaa8c75b478

Updated one php file to add a space before it starts with the .... or OK so you don't end up with 001 => 002OK

Tested both web ui and cli installs, works fine.

**Comment by f0o** [comment]
Regarding
```bash
-ALTER TABLE `storage` ADD `storage_free` INT NOT NULL AFTER `storage_used`;
-ALTER TABLE `storage` CHANGE `storage_size` `storage_size` BIGINT NOT NULL ,CHANGE `storage_used` `storage_used` BIGINT NOT NULL ,CHANGE `storage_free` `storage_free` BIGINT NOT NULL;
```

These are covered by the `build.sql` and were causing SQL errors previously, so I removed them as the new code is very strict on errors.

here the excerpt of `build.sql`:
```SQL
CREATE TABLE IF NOT EXISTS `storage` (
  `storage_id`        int(11)     NOT NULL AUTO_INCREMENT,
  `device_id`         int(11)     NOT NULL,
  `storage_mib`       varchar(16) NOT NULL,
  `storage_index`     int(11)     NOT NULL,
  `storage_type`      varchar(32) DEFAULT NULL,
  `storage_descr`     text        NOT NULL,
  `storage_size`      bigint(20)  NOT NULL,
  `storage_units`     int(11)     NOT NULL,
  `storage_used`      bigint(20)  NOT NULL,
  `storage_free`      bigint(20)  NOT NULL,
  `storage_perc`      text        NOT NULL,
  `storage_perc_warn` int(11)     DEFAULT '60',
  PRIMARY KEY (`storage_id`),
  KEY `device_id` (`device_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
```

And here an old install's SQL table:
```SQL
MariaDB [librenms]> desc storage;
+-------------------+-------------+------+-----+---------+----------------+
| Field             | Type        | Null | Key | Default | Extra          |
+-------------------+-------------+------+-----+---------+----------------+
| storage_id        | int(11)     | NO   | PRI | NULL    | auto_increment |
| device_id         | int(11)     | NO   | MUL | NULL    |                |
| storage_mib       | varchar(16) | NO   |     | NULL    |                |
| storage_index     | int(11)     | NO   |     | NULL    |                |
| storage_type      | varchar(32) | YES  |     | NULL    |                |
| storage_descr     | text        | NO   |     | NULL    |                |
| storage_size      | bigint(20)  | NO   |     | NULL    |                |
| storage_units     | int(11)     | NO   |     | NULL    |                |
| storage_used      | bigint(20)  | NO   |     | 0       |                |
| storage_free      | bigint(20)  | NO   |     | 0       |                |
| storage_perc      | int(11)     | NO   |     | 0       |                |
| storage_perc_warn | int(11)     | YES  |     | 60      |                |
| storage_deleted   | tinyint(1)  | NO   |     | 0       |                |
+-------------------+-------------+------+-----+---------+----------------+
13 rows in set (0.00 sec)
```

**Comment by f0o** [comment]
This is now updated to current schema (072.sql at the time of writing)
Docs are going to follow, going for lunch now

**Comment by f0o** [comment]
I'm gonna put a blocker here, docs and component naming schema is up for discussion.
Tagging the entire team @librenms/core-team @librenms/reviewers

**Comment by laf** [comment]
@f0o 

My only concern with this is the doc, it doesn't seem clear enough (imho) for people to follow, I'm struggling to understand how it works - but that's a low benchmark.

If you explain to me, I can tweak the docs if you like?

**Comment by laf** [comment]
IMHO remove doc/Extensions/Database-Schema-Updates.md and leave doc/Developing/Schema-Updates.md. Get's my +1 after that.

**Comment by laf** [comment]
I believe this is now good for a merge. Both myself and @f0o have tested this to get it all correct.

@paulgear - comments?

**Comment by f0o** [comment]
yay conflicts, will rebase

**Comment by laf** [comment]
@paulgear Any input to this so when @f0o rebases we can merge.

**Comment by f0o** [comment]
Rebased :)

**Comment by paulgear** [comment]
I'm still really uncomfortable with this approach; I think we're only reducing the likelihood of clashes by a small amount, and adding complexity that doesn't gain us very much.  If we're going to add complexity (and I think we must), we should do so in a way that gains us a lot of value for the future.

I think we need to create a simple command-line tool that takes an SQL schema file and puts it in a directory that is guaranteed unique, and appropriately date-ordered, then change the schema update process to track those files and run the ones which haven't been done.  That will keep us in a position where it's easy for people who haven't done a lot of coding to contribute, but get us the protection against requiring constant rebasing that we need.

**Comment by f0o** [comment]
Closing, To be discussed further

**Pull request closed without merging**
