### PR TITLE
Added plugin hook to create a custom container under device->overview.

### PR DESCRIPTION
**Pull request by runborg**
Container appears over "Overall traffic" in the left pane

Example usage code added to the Test plugin

### CODE REVIEW

**Comment by f0o** [comment]
:+1:

**Comment by laf** [comment]
I'd probably suggest removing the info from the Test plugin as people will possibly activate that and no disable it.

**Comment by laf** [comment]
'trigger ci'

**Comment by runborg** [comment]
Updated with disabling the code in Test plugin, user have to manually enable the Example code.

**Comment by f0o** [comment]
trigger ci

**Pull request merged**
