### PR TITLE
Mcc mibs valere

### PR DESCRIPTION
**Pull request by metrojworthington**
Changed MIB file for Eltek Valere BC2000 units to the most recent one. Updated .yaml and .php discovery files for this suite as well. Included test results as well. Removed old file as well since no longer referenced.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by metrojworthington** [comment]
Forgot to grab the .json test data. Adding and re-opening PR.

**Comment by metrojworthington** [comment]
Re-opening with updated test data.

**Comment by metrojworthington** [comment]
[librenms local test.txt](https://github.com/librenms/librenms/files/10261179/librenms.local.test.txt)

Uploaded local copy of results from running `lnms dev:check -o valere` which seems to be failing on an arista_eos record on my side which shouldn't be affected by this since this OS set is different.

**Comment by Jellyfrog** [comment]
I don't think it can start snmpsim properly.

tests/snmpsim/valere_bc2000.snmprec is missing its json counterpart
and the changes to valere.json looks wrong (and shouldnt need to be updated at all)

**Comment by metrojworthington** [comment]
[Valere.zip](https://github.com/librenms/librenms/files/10261378/Valere.zip)

Attached are the results from tests/data/valere.json and tests/snmpsim/valere_bc2000.snmprec that were used. Also included in commits/pushes.

**Comment by metrojworthington** [comment]
@Jellyfrog it wouldn't let me run the tests without specifying a variant so I gave it the bc2000 model info on that. I can re-supply the information once I figure out why it's not letting me do that.

**Comment by metrojworthington** [comment]
Spun up new development environment and local test are fully passing.

**Comment by metrojworthington** [comment]
[Eltek Valere Test Results 11-19-22.txt](https://github.com/librenms/librenms/files/10262563/Eltek.Valere.Test.Results.11-19-22.txt)

Local tests pass with the updated MIB files in this PR along with updated .snmprec and valere.json files.

**Comment by metrojworthington** [comment]
[valere.json.txt](https://github.com/librenms/librenms/files/10262698/valere.json.txt)
[valere_bc2000.snmprec.txt](https://github.com/librenms/librenms/files/10262699/valere_bc2000.snmprec.txt)

Here are the most recent test data files as well, they should be in the latest commit too.

**Comment by Jellyfrog** [comment]
You have updated `valere.json` when you should add `valere_bc2000.json`

**Comment by metrojworthington** [comment]
Sorry, didn't realize there was a -v option for the test data. I'll reupload that as well. Give me a few minutes.

**Pull request closed without merging**
