### PR TITLE
Sonus became Ribbon Communications - update logos

### PR DESCRIPTION
**Pull request by cjwbath**
Sonus became Ribbon Communications and has a new logo. Added it. Have not changed the underlying short name "sonus" for the OS - hopefully that is the correct way to do it.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @cjwbath 
Looks good. I only minified the SVG file. Let see how the tests are going.

**Comment by murrant** [comment]
actually, that is pretty wide for an OS image, lets split it out into icon and logo.

**Comment by cjwbath** [comment]
@murrant Yeah I was thinking that but they said [not to do that](https://ribboncommunications.com/logos-guidelines). We still could though.

**Comment by murrant** [comment]
@cjwbath the icon isn't technically a logo.  Look at the favicon for their website.  Thank you for looking into the brand guidlines :)

**Comment by cjwbath** [comment]
Yeah I just noticed that, so I think we're good. Thanks for doing the work!

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-62-release-changelog-march-2020/11423/1

**Pull request merged**
