### PR TITLE
Add Support for OS/Mem/Proc for Radware-Alteon

### PR DESCRIPTION
**Pull request by sfini**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by sfini** [comment]
@laf 
I'm sorry Neil , with the pull request from the patch 1 , also already merged files were pushed.
I've done some mistakes
Simone

**Comment by sfini** [comment]
I'll reopen it correctly

**Comment by murrant** [comment]
Let us know if you need help.

**Comment by sfini** [comment]
Opened Added Support for Radware / AlteonOS OS/Mem/Proc #7220

I think it's ok 😀

**Pull request closed without merging**
