### PR TITLE
BUG - test-template.php upgrade after #8803 +  #8908 PR

### PR DESCRIPTION
**Pull request by PipoCanaja**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Close, but it should actually be AlertData instead of a collection.

**Comment by PipoCanaja** [comment]
Probably something like this then.

**Comment by PipoCanaja** [comment]
Looks pretty good to me, as you would say 👍

**Comment by laf** [comment]
Thanks again @PipoCanaja

**Pull request merged**
