### PR TITLE
Fix escaped chars for graphs legends

### LINKED ISSUE #12838: Device sensor value alignment issue in the graph page
Some sensor alignment problems in the device graph page.  A screenshot is attached here. 
Align

### LINKED ISSUE #12843: Graph legend broken
Between:
librenms@librenms:~$ git reset --hard 33c71517630e7d2303d89d8d07726ea687d308b5
HEAD is now at 33c715176 Additional data collection for GAIA (#12713)

and

librenms@librenms:~$ git reset --hard 2833d935e0a8734b7f304b8cb652e27a7597b20f
HEAD is now at 2833d935e RRD Graph optimization (#12735)

The rrd port graph legends appear on one line.

Screenshot from 2021-05-08 02-33-24
Screenshot from 2021-05-08 02-33-48

### PR DESCRIPTION
**Pull request by PipoCanaja**
fixes #12838 
fixes #12843

(at least partially). Please comment here if you find forgotten graphs

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by twelch24** [comment]
This fixes most of my graphs. Wireless clients seems to still have the issue. URL: https://librenms/graphs/from=1620337800/to=1620424200/type=device_wireless_clients/device=#/. It's a tik with multiple ssid's.

I played with adding/removing escape on lines 36 & 80 of wireless-sensor.inc.php, but didn't seem to make any difference. Do I need to clear cache/views or anything after each change?

**Comment by PipoCanaja** [comment]
> This fixes most of my graphs. Wireless clients seems to still have the issue. URL: https://librenms/graphs/from=1620337800/to=1620424200/type=device_wireless_clients/device=#/. It's a tik with multiple ssid's.

Should be good with the 2 last commits, thx !

**Comment by PipoCanaja** [comment]
@librenms/reviewers Let's go with that batch, and we'll create another PR for the missing ones.

**Comment by TheGracens** [comment]
The text aligment look good to me here in my setup.  Thx for fixing this.  waiting now to put it into my production server.

**Comment by SirMaple** [comment]
Looks like the "Filesystem Usage" graph was missed. librenms/includes/html/graphs/device/storage.inc.php

**Comment by PipoCanaja** [comment]
> librenms/includes/html/graphs/device/storage.inc.php

Could you post the image and exact URL to get it ? Looks good here : 
`http://librenms/graphs/id=101/type=storage_usage/from=1620511200/`
image

**Comment by SirMaple** [comment]
That's not the correct graph. The graph I'm referring to is at the top of a server page in the same box as the hostname. It says "Storage Usage" below it. When you open it it changes to "Filesystem Usage" and shows all the drives in the server in a single graph.

The path I provided above is the location of the file that requires updating not a web address.

http://librenms/graphs/device=54/type=device_storage/from=1620512462/

Screen Shot 2021-05-09 at 4 24 35 PM

**Comment by PipoCanaja** [comment]
Found it now. patch is sent.

**Pull request merged**
