### PR TITLE
Added telnet/ssh/https links to device pages

### PR DESCRIPTION
**Pull request by laf**
This provides basic links to telnet / ssh or open a https connection to the device for admin purposes

Device page:
http://snag.gy/gJbEU.jpg

Device list page:
http://snag.gy/jc758.jpg

### CODE REVIEW

**Comment by f0o** [comment]
:+1: to the Idea

Is it possible to add a configuration directive to toggle all/each of them on a default basis and then use a per-device entry in the `devices_attribs`-table to fine grain the selection?

For example `$config['device_uri']['ssh'] = true` to have SSH link on all devices by default (+ whatever is defined in `devices_attribs`

**Comment by laf** [comment]
The config option is easy enough to add, devices_attribs wouldn't be worth it to write an admin page to manage those options for devices.

I'll add the config options at push the commit.

**Comment by f0o** [comment]
I think we can skip the admin-page for it. I'm having a draft using nmap scans on discovery to feed those values in.

If you dont think it's useful until the autodiscovery of those services is finished, then I will push it along my PR :)

**Comment by f0o** [comment]
@paulgear uhm I think the merge was a bit proactive.. I was still awating the config directive update prior merge.. Nothing important and essentially just cosmetics, but still..

Anyhow, :+1: :)

**Pull request merged**
