### PR TITLE
[DOC] Install LibreNMS: add Icons

### PR DESCRIPTION
**Pull request by santiag0z**
Please give a short description what your pull request is for

Trying to add this PR #15989

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by santiag0z** [comment]
@murrant, Even though the tests were successful, I see the following message in the log under **Build docs**:

  _File "/usr/local/lib/python3.11/site-packages/jinja2/lexer.py", line 389, in __next__
    self.current = next(self._iter)
  File "/usr/local/lib/python3.11/site-packages/jinja2/lexer.py", line 652, in wrap
    .decode("unicode-escape")_
    
   https://github.com/librenms/librenms/actions/runs/8960621946/job/24607334341

**Comment by murrant** [comment]
` DeprecationWarning: invalid escape sequence '\W'`

Seems like a warning in Components.md. (It will break in the future)

**Comment by santiag0z** [comment]
@murrant, Markdown is interpreting the sequence \W as a special character, which is causing the error. To solve this, I needed to use two slashes (\\), this way it reads and displays as a slash (\).

The tests passed and there are no errors, is it safe to merge? @murrant Could you check if something is missing?

**Comment by murrant** [comment]
Running locally seems likes it works fine.  (besides some warnings about bad links)

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
Still doesn't seem to be working correctly.  I hate these kinds of issues :/  Hard to test.

**Comment by murrant** [comment]
Run `./vendor/bin/phpunit tests/DocsTest.php` that is where it is failing.

**Comment by santiag0z** [comment]
I feel sad and frustrated!

**Pull request merged**
