### PR TITLE
Fix OSPF duplicate DB entries

### PR DESCRIPTION
**Pull request by murrant**
Re-write ospf polling using Eloquent

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by DonovanEsterhuizen** [comment]
if I applied this patch how do i roll it back

**Comment by jozefrebjak** [comment]
@DonovanEsterhuizen  this will delete all modified and untracked files go with `cd` for example to `opt/librenms`  and then run `./scripts/github-remove -d`

@murrant it doesnt work for me I am still seeing really wrong numbers 

image

**Comment by murrant** [comment]
I'll check the numbers, thanks for testing.

**Comment by murrant** [comment]
@jozefrebjak did you run build-base.php ?

**Comment by twelch24** [comment]
Cleaned mine up perfectly. 5955 ospf instances went down to 9. Thanks, @murrant

**Comment by jozefrebjak** [comment]
@murrant  This fix helped a lot I think. I am seeing a correct ports and neighbours now.

**Pull request merged**
