### PR TITLE
Solved aos6 problem where Librenms wasn't identifying all vlans

### PR DESCRIPTION
**Pull request by PedroChaps**
Since there was no aos6.inc.php file, a search for vlans was being made using the "Generic"
module core. This caused incorrect SNMP queries that didn't fetch all the device's vlans (The
exact difference between fetched and not-fetched vlans was not found).
Using the new file solved the problem and made every vlan appear.
@filiperfernandes solved the problem.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by paulierco** [comment]
I would like to test this, we have a few thousand devices running aos6.

**Comment by PedroChaps** [comment]
HI! I don't have many experience contributting to open-source projects so sorry for what I did wrong :sweat_smile: !

I have some questions to clear things up:
1. I didn't intend to change the properties to public, I think they were changed when I ran the script that is presented in the Wiki? Should I revert the commit and re-do the steps?
2. Some checks weren't successful, for instance `Error: Call to deprecated function dbUpdate():`. However, this was how the code was before, I didn't change anything. Am I supposed to change it or, if not, how do I pass the checks without changing it?
3. I am required to provide tests (since it's a discovery change). However, how should I proceed to create them?
4. After I have everything set, do I create a new pull request or is there a "reload all checks" on this already created pull request?

Sorry for the trouble!

**Comment by paulierco** [comment]
@PedroChaps [PedroChaps](https://github.com/PedroChaps) Could you please tell me what model of the switches/software version are you using ?

**Comment by PedroChaps** [comment]
> @PedroChaps [PedroChaps](https://github.com/PedroChaps) Could you please tell me what model of the switches/software version are you using ?

We detected the problem in 2 switches (the problem could also be in others but we are not sure).

Both identified switches are 6450 running 6.6.4.177.R01 and 6.7.1.76.R04.

**Comment by murrant** [comment]
> 1. I didn't intend to change the properties to public, I think they were changed when I ran the script that is presented in the Wiki? Should I revert the commit and re-do the steps?
> 2. Some checks weren't successful, for instance `Error: Call to deprecated function dbUpdate():`. However, this was how the code was before, I didn't change anything. Am I supposed to change it or, if not, how do I pass the checks without changing it?
> 3. I am required to provide tests (since it's a discovery change). However, how should I proceed to create them?
> 4. After I have everything set, do I create a new pull request or is there a "reload all checks" on this already created pull request?

1. I think the scripts are a little out of sync right now.  Just avoid the style one for now and follow what style-ci suggests here on github.  To fix it `git reset HEAD~1`  `git add includes/discovery/vlans/aos6.inc.php` `git commit`  `git push --force`.  Now you can just remove all the uncommitted changes.
2. dbUpdate is a deprecated function, no new uses are allowed to be added to the code. For example the first query would be `\App\Models\Vlan::where('vlan_id', $vlan_data['vlan_id'])->update(['vlan_name' => $vlan['vlanDescription']);`  (there are way better ways to handle this, but that is the 1-1 replacement)
3. https://docs.librenms.org/Developing/os/Test-Units/
4. Every time you push a new change to your branch the PR check will be re-run.

**Comment by paulierco** [comment]
@PedroChaps  You're right. If VLANs are only attached to a LACP, they are not visible on LibreNMS.

**Comment by filiperfernandes** [comment]
Hi!

I have additional information regarding the experiments made with @PedroChaps.

Currently, when performing discovery of an `aos6` switch, the `vlan discovery module` uses the `Generic` file, which is `includes/discovery/vlans/q-bridge-mib.inc.php`.

From what we observed, this module correctly discovers the vlans created on the switch (`Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts`) but it is unable  to associate all vlans present on each port (`Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts`).

Creating a specific aos6 vlan discovery file, similar to the aos7 one, seems to solve the issue (it uses `ALCATEL-IND1-VLAN-MGR-MIB` instead).

Current SNMP query used for vlan discovery:
```bash
$ snmpbulkwalk -M /opt/librenms/mibs:/opt/librenms/mibs/nokia -v2c -c COMSTRING -OQXUte udp:DEVICE-FQDN:161 Q-BRIDGE-MIB::dot1qVlanStaticName
Q-BRIDGE-MIB::dot1qVlanStaticName[1] = VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[12] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[14] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[15] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[31] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[50] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[60] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[70] = VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[75] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[80] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[90] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[92] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[132] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[153] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[200] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[222] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[231] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[290] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[311] =  VLAN-NAME
Q-BRIDGE-MIB::dot1qVlanStaticName[1001] =  VLAN-NAME
```

Current SNMP query used to associate each vlan to its belonging ports (lacking vlans 50 and 1001):

```bash
$ snmpbulkwalk -M /opt/librenms/mibs:/opt/librenms/mibs/nokia -v2c -c COMSTRING -OQXUte udp:DEVICE-FQDN:161 Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[9105][1] = "00 00 00 00 00 01 C0 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12053][12] = "00 00 00 00 00 00 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12053][15] = "00 00 00 00 00 00 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12053][70] = "00 00 00 01 FF C0 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12071][80] = "00 00 00 0C 00 00 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12075][90] = "00 00 00 B0 00 00 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12088][132] = "FF FF 1F 42 00 00 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12145][153] = "00 00 00 00 00 3E 00 "
Q-BRIDGE-MIB::dot1qVlanCurrentUntaggedPorts[12153][311] = "00 00 00 00 00 00 00 "
```

**Comment by paulierco** [comment]
@PedroChaps Will you try to update this with the recommandation from Murrant ? @filiperfernandes  Can you support ?

**Review by murrant — APPROVED** [review]

**Pull request merged**
