### PR TITLE
match 'port_descr_type' with LIKE instead of = to allow sql wildcard usage

### PR DESCRIPTION
**Pull request by brandune**
I agree to the conditions of the Contributor Agreement
    contained in doc/General/Contributing.md.

### CODE REVIEW

**Comment by brandune** [comment]
Use case is aggregating a group of port types into a rollup graph. Say we have several custom groups like "transit-provider1" and "transit-provider2". We could add another custom group "transit-%" and show data about all ports in the first two groups.

That said, trying to then load a custom group with a % in it causes problems with the URL parsing. I'm working on another change to build up custom groups a little and fix that problem in the process.

**Comment by laf** [comment]
Yes the % would be an issue in the url. Putting the % in the sql statements would be better but the main issue with this is backwards compatibility.

We use @ in the alerting for wildcard, you could use that here and just s/@/%/ possibly?

**Comment by laf** [comment]
Oh, the contributors agreement needs signing in a commit rather than just a comment in the pull request.

**Comment by brandune** [comment]
Heh, I did something terrible with the git history but I think it's fixed now. Lessons learned, don't use the master branch for PRs.. Speaking of, I think I got the contributors agreement in [this commit message](https://github.com/brandune/librenms/commit/9bc24232d278831b13bbf8755996c1dfd14f1b9f) but I let it sneak in to a PR comment as well.

About @ and %, I've added a translate to handle that in the various places it's necessary. 

Part of that includes removing the 'elseif' block that the dashboard widget uses to handle custom interface group widget configs differently than the standard core/transit/peering configs. As far as I can tell, the 'custom' block only did two things differently. It uses the widget settings for the $type string, and it calls htmlspecialchars on the $type string when building the widget title. The first is handled in a new if block, and the second seems inconsequential to add to the titling for the standard types as well.

The 'custom' block also didn't have the second lookup/parsing of "$type_descr" config objects. By combining the blocks, custom groups can take advantage of that feature in dashboard widgets too.

I've tested this on one of our monitoring instances and it looks to be working as intended.

**Comment by brandune** [comment]
Know what, I got a start on the larger refactor I had in mind and it's going to be needlessly complicated to merge this first. Closing this pr, and I'll resubmit that other refactor soon.

**Pull request closed without merging**
