### PR TITLE
Support rates >17.1gb/s

### PR DESCRIPTION
**Pull request by pblasquez**

### CODE REVIEW

**Comment by f0o** [comment]
Oh boy, this will kill my install again haha.

Just writing a comment so I will be informed of the merge

**Comment by laf** [comment]
I chose to run this as one query which I think this should be updated to do:

```sql
mysql> ALTER TABLE `ports` CHANGE `ifInOctets_rate` `ifInOctets_rate` BIGINT(20) NULL DEFAULT NULL, CHANGE `ifOutOctets_rate` `ifOutOctets_rate` BIGINT(20) NULL DEFAULT NULL ;
Query OK, 69406 rows affected (13.43 sec)
Records: 69406  Duplicates: 0  Warnings: 0
```

+1 from me.

**Comment by f0o** [comment]
Yeah one statement instead of two is better

**Comment by laf** [comment]
@f0o you may not have an issue with this one, the last update took over a minute for me where as this was pretty quick

**Comment by f0o** [comment]
We'll see, at least I'm aware of this schema update so I'll be on alert ;)

**Pull request merged**
