### PR TITLE
Feature: Custom OID polling and graphing

### PR DESCRIPTION
**Pull request by louis-oui**
Re-merge of pull request https://github.com/librenms/librenms/pull/8738
The feature was ready but migration of db schema was missing https://github.com/librenms/librenms/pull/8738#issuecomment-454459743

To test :
./scripts/github-apply 10945
php artisan migrate

To revert : 
php artisan migrate:rollback --step=1
./scripts/github-remove -d

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by louis-oui** [comment]
@PipoCanaja CodeClimate issues are related to Laravel. I can't avoid them

**Comment by PipoCanaja** [comment]
@librenms/testers feel free to play with this 👍

**Comment by PipoCanaja** [comment]
Tested on my side, works well.

**Comment by kkrumm1** [comment]
Worked on my install.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/custom-oid-in-librenms/2857/16

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/custom-oids/4183/5

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/how-to-add-custom-oid/311/9

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/custom-oid-in-librenms-repeat/71/6

**Comment by mrmikelo** [comment]
There seems to be an issue with the graphing of custom OID.  When data type is Gauge, the graph is still displayed as Counter data type.

**Comment by louis-oui** [comment]
> There seems to be an issue with the graphing of custom OID. When data type is Gauge, the graph is still displayed as Counter data type.

works for me as gauge. Tell us the step to reproduce the issue.

To debug the issue, check that both are Gauge in

- rrdtool dump rrd/HOSTNAME/customoid-XXX.rrd | head -n20
- In Database : select * from customoids ;

**Comment by mrmikelo** [comment]
I was able to reproduce this on 3 different devices.
for all 3, I edit the device then click on custom OID link, then I click on Add new OID, then I pasted the OID, added description and choose the Gauge data type. leave the rest as the default/unchanged.
I test the OID and it returns a value then save the OID.  I wait about 10-15 minutes and the outcome is a counter date type graph ..

from what you asked me to run, it does look like the rrd is set to counter but the DB has gauge.. should I clear out the .rrd and start over or is something else causing this mismatch?

_________________________________________________________________

````
[root@netmon]# ls -l customoid-Subscriber_Active_Count.rrd
-rw-rw-r-- 1 librenms librenms 125000 Dec 30 09:53 customoid-Subscriber_Active_Count.rrd

[root@netmon]# rrdtool dump customoid-Subscriber_Active_Count.rrd | head -n20
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rrd SYSTEM "http://oss.oetiker.ch/rrdtool/rrdtool.dtd">
<!-- Round Robin Database Dump -->
<rrd>
        <version>0003</version>
        <step>300</step> <!-- Seconds -->
        <lastupdate>1577717433</lastupdate> <!-- 2019-12-30 09:50:33 EST -->

        <ds>
                <name> oid_value </name>
                <type> COUNTER </type>
                <minimal_heartbeat>600</minimal_heartbeat>
                <min>NaN</min>
                <max>NaN</max>

                <!-- PDP Status -->
                <last_ds>33049</last_ds>
                <value>1.7238805970e+00</value>
                <unknown_sec> 0 </unknown_sec>
        </ds>

---------------------------------------------------------------

MariaDB [librenms]> select * from customoids\G;
*************************** 1. row ***************************
            customoid_id: 7
               device_id: 3
         customoid_descr: Subscriber Active Count
       customoid_deleted: 0
       customoid_current: NULL
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.2.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 0
              lastupdate: 2019-12-20 17:10:36
               user_func: NULL
*************************** 2. row ***************************
            customoid_id: 8
               device_id: 3
         customoid_descr: Subscriber Total Count
       customoid_deleted: 0
       customoid_current: NULL
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.1.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 0
              lastupdate: 2019-12-20 17:10:52
               user_func: NULL
*************************** 3. row ***************************
            customoid_id: 9
               device_id: 88
         customoid_descr: Subscriber Active Count
       customoid_deleted: 0
       customoid_current: 30054
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.2.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 1
              lastupdate: 2019-12-30 10:26:04
               user_func: NULL
*************************** 4. row ***************************
            customoid_id: 10
               device_id: 88
         customoid_descr: Subscriber Total Count
       customoid_deleted: 0
       customoid_current: NULL
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.1.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 0
              lastupdate: 2019-12-20 17:11:49
               user_func: NULL
*************************** 5. row ***************************
            customoid_id: 11
               device_id: 135
         customoid_descr: Subscriber Active Count
       customoid_deleted: 0
       customoid_current: NULL
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.2.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 0
              lastupdate: 2019-12-20 17:13:43
               user_func: NULL
*************************** 6. row ***************************
            customoid_id: 12
               device_id: 135
         customoid_descr: Subscriber Total Count
       customoid_deleted: 0
       customoid_current: NULL
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.1.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 0
              lastupdate: 2019-12-20 17:13:59
               user_func: NULL
*************************** 7. row ***************************
            customoid_id: 13
               device_id: 89
         customoid_descr: Subscriber Active Count
       customoid_deleted: 0
       customoid_current: 30899
          customoid_prev: 30901
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.2.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 1
              lastupdate: 2019-12-30 10:25:40
               user_func: NULL
*************************** 8. row ***************************
            customoid_id: 14
               device_id: 89
         customoid_descr: Subscriber Total Count
       customoid_deleted: 0
       customoid_current: NULL
          customoid_prev: NULL
           customoid_oid: .1.3.6.1.4.1.2636.3.64.1.1.1.1.0
      customoid_datatype: GAUGE
          customoid_unit: NULL
       customoid_divisor: 1
    customoid_multiplier: 1
         customoid_limit: NULL
    customoid_limit_warn: NULL
     customoid_limit_low: NULL
customoid_limit_low_warn: NULL
         customoid_alert: 0
        customoid_passed: 0
              lastupdate: 2019-12-20 17:15:10
               user_func: NULL
8 rows in set (0.00 sec)

**Comment by louis-oui** [comment]
> .1.3.6.1.4.1.2636.3.64.1.1.1.2.0

Try to snmpget on this Oid and check that value type is gauge32

For example with counter :
.1.3.6.1.2.1.2.2.1.15.1181 = Counter32: 0

Also post validate.php output to check rrdtools version

Check ./poller.php -h deviceID -m customoid -d

If bug, it should be in includes/polling/customoid.inc.php

**Comment by mrmikelo** [comment]
I managed to et this to work.
Removing the existing customoid-*.rrd files was not enough, I also had to disable the MIB module, when the module is enabled, Custom OID does not seem to work or display graphs.
With the "old" customoid-*.rrd files removed and MIB module disabled, I re-added the customOIDs and I can now get gauge graphs.

**Comment by mrmikelo** [comment]
as a side note I ran the above commands and have the input:
the manual polling works without issues.

```
RRDTool   | 1.7.1

snmpget -v2c 10.0.1.17 .1.3.6.1.4.1.2636.3.64.1.1.1.2.0
SNMPv2-SMI::enterprises.2636.3.64.1.1.1.2.0 = Counter64: 27201
```

**Comment by louis-oui** [comment]
The problem is the device is replying counter and not gauge

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Comment by Derova** [comment]
Great job! I've been looking forward to this feature for almost a year, thank you so much to all involved for getting this implemented. This is awesome.

**Comment by freedomwarrior** [comment]
Is it possible to use 2 oids on one graph?

**Comment by louis-oui** [comment]
> Is it possible to use 2 oids on one graph?

no

**Comment by penfold1972** [comment]
I added some OIDs, and the system can poll the data and appears to be updating the rrd files. But when I click graphs, i get the titles of the custom graphs I created, but nothing is drawn. All normal graphs are generated fine. So is there something I need to enable somewhere else to get the data graphed?

**Comment by penfold1972** [comment]
After I had added my custom OIDs, I modified the Name of the CustomOID/graph. Looking at the filenames, I noticed that the original name had been created but the new name was being updated. As a test, I created a test which was the same as one of the OIDs that weren't working. 
The only difference was the name began with "TEST_" and it wasn't edited the OID had been created and I came in this morning and there was a graph available. So I wonder if it would be best to generate a filename along the lines of ./rrd/customoid_<DEVICE_ID>_<CUSTOMOID_ID>,rrd so the file never really changes if the name is modified later?

**Comment by penfold1972** [comment]
Can someone test this? Create a customOID graph with an OID that you know is working, and name it "TEST_Interface_ge-0/0/0". Then create a second one called "TEST_Interface_ge-0-0-0" and see if either of them have graphing issues.

**Pull request merged**
