### PR TITLE
Create check_mssql_health.inc.php

### PR DESCRIPTION
**Pull request by premtimibrahimi**
This could be very usefull for the people who want to monitor MS SQL Servers. It is a very cool service check.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
check_mssql_health does not seem to be in the standard nagios/monitoring plugins.  @librenms/reviewers How should we deal with that?  Check for it's existence before listing? Add an note?

**Comment by premtimibrahimi** [comment]
Honestly not sure, but integrating it within librenms would be a good idea. To make this service check work its simple.

**Comment by laf** [comment]
@murrant The list of nagios checks is pulled from the plugin dir for the user so if you add any check_* file it will be listed so this is fine as it's only used when someone selects it.

**Comment by murrant** [comment]
Oh great! Didn't even look at the code 😊

**Pull request merged**
