### PR TITLE
Fix empty output on validation test

### PR DESCRIPTION
**Pull request by hanserasmus**
As per screenshot below, the validate.php has been outputtinga blank line (even with an OK). 

Fixed it for the 'ok' status, **but, I don't know how to handle the output if this validation fails, so I need help with that please!**

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

LibreNMS-validate-before
LibreNMS-validate-after

### CODE REVIEW

**Comment by hanserasmus** [comment]
Please note, as mentioned in the original message, I know handling of validation failures are not part of this original commit, and that is because I am not sure how to do it. Anyone willing to help me with it, and I will keep on working on this PR.

**Comment by hanserasmus** [comment]
I don't understand why styleci fails.

image

**Comment by murrant** [comment]
The failures are all untranslatable strings directly in the code.
If you want to make those translatable, you just move them into the language file and replace them with trans('<string path>')

**Comment by murrant** [comment]
We can merge this as is if you like too.

**Comment by hanserasmus** [comment]
> We can merge this as is if you like too.

If you are happy, I am happy to have this merged as is.

**Review by murrant — APPROVED** [review]

**Pull request merged**
