### PR TITLE
Aprisa support

### PR DESCRIPTION
**Pull request by loopodoopo**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Did the requested changed by LAF.

### CODE REVIEW

**Comment by loopodoopo** [comment]
Made the changes requested in #9424

**Comment by laf** [comment]
Looks good, you've edited defaults.inc.php so you should revert that.

We also need test data: https://docs.librenms.org/Developing/os/Test-Units/#example-workflow

**Comment by murrant** [comment]
@loopodoopo if you can just add the snmprec file created by ./scripts/collect-snmp-data.php, I can generate the json file.  Thanks

**Comment by loopodoopo** [comment]
Please find aprisa.snmprec attached.

**Pull request merged**
