### PR TITLE
nimbleos Changed to bit shift high << 32 and add low. Changed over graphs.

### PR DESCRIPTION
**Pull request by theherodied**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Can you explain this, why would you want to concatenate the two numbers?

**Comment by theherodied** [comment]
When I read the MIB file and saw the High Order Bytes and Low Order Bytes I began researching what they meant. I've seen several different takes on it but this is the one I'm tending to believe. I opened a ticket with Nimble to clarify/confirm.

https://www.zenoss.com/product/zenpacks/nimble
Jane Curry described it like this:
A modeler plugin - NimbleVolumeMap - which gathers id, name, various sizes, online status and number of connections. The three sets of size data are in 2 MIB values - high 32 bits and low 32 bits. The modeler combines these values to present a single value in the NimbleVolume object. We believe that the raw SNMP data is in MB. The modeler divides this by 1024 to present values as GB.

The code Jane used looks like this and can be found at https://github.com/jcurry/ZenPacks.community.Nimble/blob/master/ZenPacks/community/Nimble/modeler/plugins/NimbleVolumeMap.py

# MIB sez vol sizes are bytes.  They are actually MB. We want GB
om.VolSize = (( data['_VolSizeHigh'] << 32 )+ data['_VolSizeLow']) / 1024
om.VolUsage = (( data['_VolUsageHigh'] << 32 )+ data['_VolUsageLow']) / 1024
om.VolReserve = (( data['_VolReserveHigh'] << 32 ) + data['_VolReserveLow']) / 1024

I'm unsure if the 32 bitwise shift is needed.

**Comment by theherodied** [comment]
This might provide some insight. I might need to change the code still.

**Comment by theherodied** [comment]
I actually need to shift the high counter << 32 and add the low. I'll work on that.

**Comment by theherodied** [comment]
I think this is correct now.

**Comment by murrant** [comment]
Also, I **think** it will work like the existing code on 32bit platforms when you `<< 32` the number it should be 0 so, you will only use lowbits.

**Comment by theherodied** [comment]
Is this all set to merge now?

**Pull request merged**
