### PR TITLE
convert NTP to JSON and json_app_get

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Converted this all to use json_app_get. This requires https://github.com/librenms/librenms/pull/8571 .

### CODE REVIEW

**Comment by laf** [comment]
I think I've applied all the PRs required for this but get:

```
ntp-clientSNMP[/usr/bin/snmpget -v2c -c 'librenms' -Oqv -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:localhost:161 nsExtendOutputFull.10.110.116.112.45.99.108.105.101.110.116]
{\"offset\":\"-0.029\",\"frequency\":\"20.601\",\"sys_jitter\":\"0.000\",\"clk_jitter\":\"0.078\",\"clk_wander\":\"0.011\",\"version\":\"1\",\"error\":\"0\",\"errorString\":\"\"}

PHP Fatal error:  Uncaught LibreNMS\Exceptions\JsonAppMissingKeysException: Legacy script or extend error, missing one or more required keys. in /opt/librenms/includes/polling/functions.inc.php:769
Stack trace:
#0 /opt/librenms/includes/polling/applications/ntp-client.inc.php(11): json_app_get(Array, 'ntp-client', 1)
#1 /opt/librenms/includes/polling/applications.inc.php(9): include('/opt/librenms/i...')
#2 /opt/librenms/includes/polling/functions.inc.php(303): include('/opt/librenms/i...')
#3 /opt/librenms/poller.php(159): poll_device(Array, '-O qv')
#4 {main}
  thrown in /opt/librenms/includes/polling/functions.inc.php on line 769

Fatal error: Uncaught LibreNMS\Exceptions\JsonAppMissingKeysException: Legacy script or extend error, missing one or more required keys. in /opt/librenms/includes/polling/functions.inc.php on line 769

LibreNMS\Exceptions\JsonAppMissingKeysException: Legacy script or extend error, missing one or more required keys. in /opt/librenms/includes/polling/functions.inc.php on line 769

Call Stack:
    0.0007     419304   1. {main}() /opt/librenms/poller.php:0
    1.1668    6587528   2. poll_device() /opt/librenms/poller.php:159
    2.3699    6625736   3. include('/opt/librenms/includes/polling/applications.inc.php') /opt/librenms/includes/polling/functions.inc.php:303
    3.3150    6641728   4. include('/opt/librenms/includes/polling/applications/ntp-client.inc.php') /opt/librenms/includes/polling/applications.inc.php:9
    3.3150    6641728   5. json_app_get() /opt/librenms/includes/polling/applications/ntp-client.inc.php:11

```

We shouldn't stop the poller with an exception rather log and carry on.

Is it my setup or is this not working?

**Comment by VVelox** [comment]
Howdy! Sorry, not updated that yet.

To do still involves updating it to the current version of json_app_get and working in handling of the old stuff.

The json_app_get with the fail2ban stuff is done, minus documentation on writing apps. Working on that currently.

**Comment by laf** [comment]
Ok let us know when it's testable.

**Comment by VVelox** [comment]
@laf Testable now. :)

**Comment by VVelox** [comment]
@laf Hey. Sorry, missed your reply there. No, that should not stop. It should just output a warning and continuing.

Unless I am missing something, this should catch anything not specifically mentioned.

     } catch (JsonAppException $e) {

**Comment by VVelox** [comment]
@laf Strange. Just removed a few keys from a machine here and ran the poller and am not seeing that. :/

    fbsd-nfs-server[RRD Disabled]: UUU.UU.UUU...U.U.U..U.....UUU.
    ntp-client
    ntp-client:-5:Legacy script or extend error, missing one or more required keys.
    [RRD Disabled]: .U...............
    portactivity[RRD Disabled][RRD Disabled][RRD Disabled][RRD Disabled][RRD Disabled][RRD Disabled][RRD Disable

**Comment by laf** [comment]
Looks like I'm seeing issues with this one still:

```
ntp-clientSNMP[/usr/bin/snmpget -v2c -c 'librenms' -Oqv -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:localhost:161 nsExtendOutputFull.10.110.116.112.45.99.108.105.101.110.116]
{\"data\":{\"offset\":\"0.037\",\"frequency\":\"19.462\",\"sys_jitter\":\"0.000\",\"clk_jitter\":\"0.062\",\"clk_wander\":\"0.003\"},\"version\":\"1\",\"error\":\"0\",\"errorString\":\"\"}

RRD[update /opt/librenms/rrd/localhost/app-ntp-client-52.rrd N:0.037:19.462:0.000:0.062:0.003]
RRDtool Output: OK u:0.00 s:0.01 r:2.08

Warning: strpos() expects parameter 1 to be string, array given in /opt/librenms/includes/common.php on line 1412

Call Stack:
    0.0007     415048   1. {main}() /opt/librenms/poller.php:0
    0.8741    7083736   2. poll_device() /opt/librenms/poller.php:155
    2.0393    7407992   3. include('/opt/librenms/includes/polling/applications.inc.php') /opt/librenms/includes/polling/functions.inc.php:300
    2.9579    7430688   4. include('/opt/librenms/includes/polling/applications/ntp-client.inc.php') /opt/librenms/includes/polling/applications.inc.php:9
    2.9989    7433488   5. update_application() /opt/librenms/includes/polling/applications/ntp-client.inc.php:47
    2.9989    7433864   6. str_contains() /opt/librenms/includes/polling/functions.inc.php:614
    2.9989    7433864   7. strpos() /opt/librenms/includes/common.php:1412

SQL[UPDATE `applications` set `app_state` ='ERROR',`app_status` ='',`timestamp` =NOW(),`app_state_prev` ='OK' WHERE `app_id` = '52']
```

**Comment by VVelox** [comment]
@laf Found the problem. I forgot where I branched this from did not have the JSON exceptions in it.

Retrying to rebase now.

**Comment by VVelox** [comment]
Replaced with https://github.com/librenms/librenms/pull/9088 as the rebase went majorly FUBAR.

**Pull request closed without merging**
