### PR TITLE
webui: ports table refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

webui unification, in progress, started from @Rosiak PR #7628 and @laf suggestion.

ports page 
before:
screen shot 2017-11-29 at 3 45 03 am

after:
screen shot 2017-11-29 at 3 43 57 am

### CODE REVIEW

**Comment by crcro** [comment]
deleted ports reworks
before:
screen shot 2017-11-30 at 5 37 35 pm

after:
screen shot 2017-11-30 at 6 24 00 pm

**Comment by laf** [comment]
The deleted ports doesn't have a purge all anymore.

The search bar is mis-aligned quite a bit as well:

image

**Comment by kkrumm1** [comment]
Worked for me. Looking good.

**Comment by crcro** [comment]
@laf ... added some limits on name displays to limit the options bar from overflowing, added a port status indicator (please ignore the style, it will match with others if all PR will be merged):

screen shot 2017-12-09 at 6 17 40 pm

**Comment by laf** [comment]
The searchbar still doesn't work for me:

image

No purge all for deleted ports page.

**Comment by laf** [comment]
I can see the the purge all link now but it doesn't do anything, maybe the `===` is too strict for the check?

I know I'm being petty about the search section but it still doesn't line up for me:

image

**Comment by crcro** [comment]
@laf ... what is your display resolution?

**Comment by laf** [comment]
1680x1050.

image

That should be in it's own column.

**Comment by crcro** [comment]
it should be right after options bar but your option bar has a larger width than mine, i’ll try to make some other tweaks

**Comment by murrant** [comment]
Way out of scope for this PR, maybe when we switch out bootgrid...
But I saw a table where you click an icon in the header of filterable columns to filter that column.   Worked decently and took up very little space.  (icon changed to show the column is filtered)

**Comment by laf** [comment]
> it should be right after options bar but your option bar has a larger width than mine, i’ll try to make some other tweaks

If you split the into two columns though then that fixes it. That's how the existing ones were done.

**Comment by laf** [comment]
Thanks for the update @crcro. I think that's me done for requests now so I'm happy to merge all of these.

@librenms/reviewers anyone else got any more thoughts?

**Comment by crcro** [comment]
@laf ... my pleasure, sorry for the delay ... crazy days

**Pull request merged**
