### PR TITLE
Nokia sap graph

### PR DESCRIPTION
**Pull request by loopodoopo**
Added support for SAP graphs under routing > MPLS for Nokia SR/SAR devices. 

image

image

image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by craig-nokia** [comment]
Looks good and works on my test librenms system.

**Comment by murrant** [comment]
It seems like it should show the graph on the MPLS page, otherwise it is kind of hidden.

**Comment by loopodoopo** [comment]
@murrant, they are on the MPLS page under SAP's. Having the graphs in the current location allows us to do SDP graphs under the SDP tab.

**Comment by murrant** [comment]
Ah, I see it is just a link to the device graph page.  I suggest you use `\LibreNMS\Util\Url::graphPopup()` instead of your custom link function.   This will show the graph on hover, then go to it's graph page on click.

**Comment by loopodoopo** [comment]
@murrant that is a very cool solution indeed. Pushed the changes.

**Review by murrant — APPROVED** [review]
I can't test this, but LGTM

**Comment by paunadeu** [comment]
Not working on 7250 IXR-s or 7250 IXR-e Big.

**Pull request merged**
