### PR TITLE
Billing: show all ports except loopback

### PR DESCRIPTION
**Pull request by erdems**
- Modified ifType to include all except software loopback, to cover kernel interfaces like LAG, RETH, bridge.

- Modified / fixed redirection after bill deletion.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Would this make sense to get the ifDescr and os values from the DB and run each port through `is_port_valid()`?

**Comment by erdems** [comment]
ifDescr sounds a good idea, too. I couldn't think of an interface with description / pattern set matching the billing but not carrying traffic.

**Comment by laf** [comment]
Ace, if you update the PR to remove the port checks in the sql query and run each port through `is_port_valid()` then this should be good.

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen!

**Comment by erdems** [comment]
Sorry I hadn't realized this was pending on me.

I would recommend simply going with the initial suggestion which is to include all except software loopback to be able to capture non-Ethernet interfaces with the relevant description that can be parsed.
Does that make sense?

**Comment by Jellyfrog** [comment]
ping @laf

**Comment by laf** [comment]
If you use `is_port_valid()` then users can control what gets excluded.

**Comment by murrant** [comment]
Easiest way is to check deleted=0 for ports.

**Comment by murrant** [comment]
Closing again, pending submitter update

**Pull request closed without merging**
