### PR TITLE
Show when a device was added and last discovered

### PR DESCRIPTION
**Pull request by josephtingiris**
* As an admin or a user, I want to know exactly when a device was added and more easily determine the last time it was discovered.
* Add a new column named 'inserted' to the devices table that automatically updates when a new row is added.
* Updated device overview page to show this information.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
This data is shown in the Device settings page. But it would be nice to have it on the overview page also.

**Comment by josephtingiris** [comment]
Thanks.  I struggled to find it outside of the database.  Creating an alert via the event log didn't go so well either, especially when the event log is large.  The queries were slow.  This patch makes it much easier to find out when a device was added and more efficient to get alerts new devices are added.

**Comment by josephtingiris** [comment]
Should I be concerned about fixing the codeclimate issues related to the database/migrations?

None of the other migrations have a namespace and they all use up() & down() methods.

**Comment by kkrumm1** [comment]
LGTM

**Comment by kkrumm1** [comment]
I didn't catch this but the Device Added seems to be wonky
Screen Shot 2020-02-05 at 2 16 41 PM

**Comment by josephtingiris** [comment]
Wonky is a good word for that.  Was that a device that was added prior to the patch or after?

**Comment by kkrumm1** [comment]
That device has been in librenms for 2 years now. It wasn’t recently added.

Kevin


> On Feb 5, 2020, at 7:02 PM, Joseph Tingiris <notifications@github.com> wrote:
> 
> ﻿
> Wonky is a good word for that. Was that a device that was added prior to the patch or after?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 










CONFIDENTIALITY NOTICE: This email & attached documents may 
contain confidential information. All information is intended only for the 
use of the named recipient. If you are not the named recipient, you are not 
authorized to read, disclose, copy, distribute or take any action in 
reliance on the information and any action other than immediate delivery to 
the named recipient is strictly prohibited. If you have received this email 
in error, do not read the information and please immediately notify sender 
by telephone to arrange for a return of the original documents. If you are 
the named recipient you are not authorized to reveal any of this 
information to any other unauthorized person. If you did not receive all 
pages listed or if pages are not legible, please immediately notify sender 
by phone.

**Comment by josephtingiris** [comment]
Ok, I see and can reproduce those results.  The date in the db is 0000-00-00 00:00:00 and that doesn't translate correctly.  ? is how yours got that way.  :)

I was also thinking that it's impossible to determine when existing devices, like that, were actually added.  The original migration _should_ have set the date to CURRENT_TIMESTAMP (i.e. Now()) when it added the column.  In retrospect, that's not ideal either.

I'll create a new PR to fix both use cases.  Legacy devices prior to today will be set to 0000-00-00 00:00:00 and the Device Added just wont show up for that date.  Only new devices will show their actual timestamp.  Ok?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/device-added-2021-years-ago/10906/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
