### PR TITLE
Allow ping checks to be ran separately from polling

### PR DESCRIPTION
**Pull request by murrant**
Allows ping checks at intervals not tied to the poller.  Pointless if you are not alerting on device status.
I updated the rrdstep.php script to treat ping-perf files separately and made it so it only converts if needed.

Docs here: https://docs.librenms.org/Extensions/Fast-Ping-Check/

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I'm assuming this is to be invoked from cron?

I'm sure it works (haven't tested it) but is php really what we want to use here along with invoking it via cron? Seems like this would be better as part of the new poller service (or written in Go to support < 1 minute checks).

**Comment by murrant** [comment]
Yes, I would add support to the python service too.
I don't know why php isn't ok.   fping does parallel pinging, one fping command pings all hosts.
Using PHP allows us to take advantage of Eloquent so we get nice things like this:
```php
$result = new DevicePerf($captured);
 $device->perf()->save($result);
```

**Comment by cchance27** [comment]
Would be interesting to benchmark this against say a go pinger as i think the latency difference from a well coded go ping vs a php spawn of fping would be decent bit at least when scaled to say a few hundred or thousand devices, could be wrong though

**Comment by murrant** [comment]
Why would a Go pinger be faster than a pinger written in C?

**Comment by cchance27** [comment]
I’m referring to the wrapper+fping vs go-only instead of spawning a fping process

**Comment by murrant** [comment]
@cchance27 feel free to code something up and test it.

**Comment by laf** [comment]
If you can rebase this I'll check it out on a 4.5k+ device install

**Comment by laf** [comment]
Just need docs.

I can only test this on my dev install:

```bash
-bash-4.2$ ./ping.php
Pinged 9 devices in 2.78s
-bash-4.2$ php artisan ping


  Not enough arguments (missing: "groups?* | Optional List of distributed poller groups to poll").
```

I know the artisan command isn't to be used but the code suggests it would return a message indicating that rather than showing missing options.

**Comment by laf** [comment]
Probably just https://github.com/librenms/librenms/tree/master/doc/Extensions as a new file?

**Pull request merged**
