### PR TITLE
OS Icon Updates + Added Info to AUTHORS.md

### PR DESCRIPTION
**Pull request by arrmo**
#### Please note

> Please read this information carefully.

- [ X ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [ X ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by crcro** [comment]
lenovo icon is too large (40x40 instead of 32x32px) and i'm pretty sure that your change is too restrictive (i bet there are more switch with differente sysDescr that are using swos).

also there is @laf PR #4044 which address this swos detection

**Comment by arrmo** [comment]
Agreed on the icon! I did that on purpose, as the text gets very (too?) small at 32x32. I can change it if it's critical, no problem at all! I did check it locally first, and I it seems to fit nicely - but I could be wrong. Just let me know, I can update it - no issue there.

On the SwOS change, it shouldn't just check for numeric - should it? That's why I aligned to their current switch (this is different from RouterOS). Again, just let me know - no problems.

Thanks!

**Comment by laf** [comment]
Yeah icons need to be 32x32 please.

#4044 should fix swos detection properly without resorting to using model numbers.

**Comment by arrmo** [comment]
NP, works for me - will do! To make sure I get it right ... update the file, push it up ... then somehow update this pull request?

Will also remove the SwOS update - didn't know about the other, but that's great by me.

Thanks!

**Comment by laf** [comment]
When you edit what you want in your local branch, commit then push and that's all you need to do :)

**Comment by arrmo** [comment]
OK, done! Icon is now 32x32, and I changed the SwOS item back (so the other change will just go on top of this).

Thanks!

**Comment by laf** [comment]
Sorry @arrmo needs a rebase :(

**Comment by arrmo** [comment]
NP! Should be OK now - but yell if not.

Thanks!

**Comment by laf** [comment]
Sorry only just noticed your agreement isn't as per the docs. You can do another push with just a space after your name but the commit message HAS to appear as described in the contributing doc.

**Comment by laf** [comment]
@arrmo Your contributors agreement isn't correct, please push a commit with the exact message as per our docs.

**Comment by arrmo** [comment]
OK, updated correctly I think (just moved my name in the list, so it's a delta I can commit ... then added the required text to the commit message).

Thanks!

**Comment by laf** [comment]
I hadn't checked up until now but why the new logos, they won't be used from what I can see.

**Comment by arrmo** [comment]
OK, you lost me there - why do you say they won't be used? They are working here, and I see them ... :).

Thanks!

**Comment by arrmo** [comment]
And BTW, the reason for them - to separate out a full-fledged Linux box from a wireless router running a version of Linux -> can clearly see the difference.

**Comment by laf** [comment]
Because we don't have any os definitions for them - are they picked up by the distro script or something?

**Comment by arrmo** [comment]
Works "automatically" - they already return their name (in this case, Tomato or ASUSWRT-Merlin ... from the firmware), and the current code in LibreNMS already checks ... if this name (lowercase) matches the name of the .png file, it gets pulled in. So I just named the file to match, and that's why it happens automatically. Make sense?

Going from memory (don't trust that! ... ;)), the code was already in includes/functions,php (below),
`    // linux specific handling, distro icons
    if ($device['os'] == "linux") {
        $features = strtolower(trim($device['features']));
        list($distro) = explode(" ", $features);
        if (file_exists($config['html_dir'] . "/images/os/$distro" . ".png")) {
            return $distro;
        }
    }
`

Clear as mud?

**Comment by arrmo** [comment]
Crap, that copy formatted poorly - sorry!

**Pull request merged**
