### PR TITLE
Add Duo MFA into LibreNMS

### PR DESCRIPTION
**Pull request by FragmentedPacket**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
I'm looking into implementing Duo MFA into LibreNMS, but having some difficulties and would probably want help with this to make sure the implementation makes sense coding wise within LibreNMS.

So far I think we should add the Duo MFA into the LibreNMS/Authentication/TwoFactor.php into the showForm().

I have some of the code added, but having issues with displaying the iFRAME. I will try and figure out how to add my updated TwoFactor.php so others can review.

**Comment by murrant** [comment]
You can continue coding this as is, but we will want to separate this into two classes.  With an common interface.  We can add a static method to Auth called getTwofactor(). I can help you with that once the time comes.

What kind of issues are you having with the iframe?

**Comment by laf** [comment]
I can probably help test this as well once the code is ready as we run Duo for a few things at work and happy to hook it into LibreNMS.

**Comment by FragmentedPacket** [comment]
Sorry guys, it's picked up at work.

Hopefully I'll be able to spend some time on this next week to answer your questions to help assist me with getting this working.

**Comment by FragmentedPacket** [comment]
Closing pull request. I don't have time to look into this at this point!

**Comment by shepherdjay** [comment]
@FragmentedPacket does this code work or were there some things to tighten up? We're looking to add duo as well and I came across this pull request in a google search.

**Comment by FragmentedPacket** [comment]
@shepherdjay It was just getting started so I didn't really add much. I haven't had time to look into this and probably won't for a while. Hopefully enough people will want the feature and it'll get added at a future date!

**Pull request closed without merging**
