### PR TITLE
Add alert rule option to invert devices and groups "map to" list

### PR DESCRIPTION
**Pull request by louis-oui**
Current implementation :
image

Add this option :
image

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by louis-oui** [comment]
Code climate errors due to laravel and needs to be bypassed

**Comment by louis-oui** [comment]
@PipoCanaja Feature is ready
Before merging, we need to make sur that date in file is last one in list database/migrations/2019_12_17_151314_add_invert_map_to_alert_rules.php 
Otherwise, migration won't work

**Comment by louis-oui** [comment]
Bug invert not accepted at rule creation

**Comment by PipoCanaja** [comment]
> Before merging, we need to make sur that date in file is last one in list database/migrations/2019_12_17_151314_add_invert_map_to_alert_rules.php
> Otherwise, migration won't work

Hi
I don't get why this date would have an impact, unless we have another change touching the same table and the 2 are touching the same columns with one being a prerequisite for the other, I would say.

**Comment by louis-oui** [comment]
> Hi
> I don't get why this date would have an impact, unless we have another change touching the same table and the 2 are touching the same columns with one being a prerequisite for the other, I would say.

From what I have seen, Laravel migration process refuses to update schema if a new schema file is inserted and its date in filename is previous to last update

**Comment by louis-oui** [comment]
> From what I have seen, Laravel migration process refuses to update schema if a new schema file is inserted and its date in filename is previous to last update

Seems my test was wrong for some reason. It is OK

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/add-alert-rule-option-to-invert-devices-and-groups-map-to-list/10635/1

**Comment by SourceDoctor** [comment]
@louis-oui 
this PR results on my production system into false Alerts:
Example Alert Rule:  Port 5 down Switch X

i got Alert for Port 5 down, but on Switch Y

rolling back this PR and everything is fine again

**Comment by vitalisator** [comment]
same problem here. Alert device mapping to Device do not work anymore. Please revert first.

**Comment by louis-oui** [comment]
@vitalisator @SourceDoctor sorry for the issue. It is working on my production environnent. I am checking what is going on my dev.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/device-specific-alerts-applying-to-all-devices-since-jan-15th-update/10649/7

**Comment by louis-oui** [comment]
@vitalisator @SourceDoctor, It seems I have reproduced your issue. Alert rules was bugged when you devices on map to field. My production had only groups.

PR11038 add again the feature and should fix the issue. Could you test it works for you ? 
```
./scripts/github-apply 11038
```
Get an ID of a device not in map to. Do:
`./poller.php -h ID -m ports`

At the bottom of the output, you will have the matching rules. Check that the rules that wrongly match because of the bug does not match again.
```
### Start Alerts ####
Rule #1 (Not 7): Status: NOCHG
Rule #2 (All): Status: NOCHG
Rule #3 (Mapto 5,7,8): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #7 (5): Status: NOCHG
Rule #8 (Not 1): Status: NOCHG
Rule #9 (1): Status: NOCHG
#### End Alerts ####
```
Revert after test:
```
./scripts/github-remove -d
```

**Comment by SourceDoctor** [comment]
@louis-oui 
looks good
`Status: NOCHG` on all rules on all Switches
Thx for fixing :-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
