### PR TITLE
Add HSRP state sensors for Cisco IOS on L3 switches

### PR DESCRIPTION
**Pull request by rudybroersma**
This patch contains an addition to the IOS discovery YAML to add HSRP state sensor support.

eg:
sample 1:
image
sample 2:
image

This allows LibreNMS to detect HSRP changes in the network

My Cisco lab consists of Catalyst 3560 switches. 

**Special thanks to Christiaan de Jonge :)**

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by rudybroersma** [comment]
I believe the test fail because of this one:
https://github.com/librenms/librenms/pull/15629

Do we need to remove all IOS test data and create new ones?

**Comment by rudybroersma** [comment]
Obviously previous test results are now gone. Sorry for that. They failed because ports_nac.x.historical was removed on my machine. My test data:

```
            "ports_nac": [
                {
                    "auth_id": "000000000000000105EF0AFE",
                    "domain": "data",
                    "username": "username1",
                    "mac_address": "788a207f0e96",
                    "ip_address": "120.50.253.35",
                    "host_mode": "multiDomain",
                    "authz_status": "authorizationSuccess",
                    "authz_by": "Authentication Server",
                    "authc_status": "authcSuccess",
                    "method": "other",
                    "timeout": "4",
                    "time_left": "32",
                    "vlan": 0,
                    "time_elapsed": null,
                    "ifIndex": 10001
                },
```

Test data from https://github.com/librenms/librenms/blob/master/tests/data/ios_nac.json
```
            "ports_nac": [
                {
                    "auth_id": "000000000000000105EF0AFE",
                    "domain": "data",
                    "username": "username1",
                    "mac_address": "788a207f0e96",
                    "ip_address": "120.50.253.35",
                    "host_mode": "multiDomain",
                    "authz_status": "authorizationSuccess",
                    "authz_by": "Authentication Server",
                    "authc_status": "authcSuccess",
                    "method": "other",
                    "timeout": "4",
                    "time_left": "32",
                    "vlan": 0,
                    "time_elapsed": null,
                    "historical": 0,
                    "ifIndex": 10001
                },
```

Not sure why my generated test data doesn't have the historical key in the JSON output, but it's unrelated to this PR.
I have therefore restored the ios_nac.json file (kept the one in LibreNMS master repository)

**Comment by rudybroersma** [comment]
@electrocret Tests done!

**Comment by PipoCanaja** [comment]
Hi @rudybroersma 
**Looks good to me**. Might be a little bit verbose on bigger chassis with a lot of Vlan Interfaces but it can be filtered by the users.

That being said, I think it would make sense to go a little bit further and create a dedicated module for HSRP/VRRP/etc that would complement the port page and replace these sensors.

**Comment by rudybroersma** [comment]
> Hi @rudybroersma **Looks good to me**. Might be a little bit verbose on bigger chassis with a lot of Vlan Interfaces but it can be filtered by the users.
> 
> That being said, I think it would make sense to go a little bit further and create a dedicated module for HSRP/VRRP/etc that would complement the port page and replace these sensors.

Alright, just so I get this right.. You mean a new page in the tabs like Overview, Graph, Ports, VLANs, Neighbors, STP and alike?

I'll work on that, but might take me a while. Limited free time and all. If in the meantime this PR can be approved that would be great, I'll remove this sensor when my new code is ready.

**Comment by PipoCanaja** [comment]
> > Hi @rudybroersma **Looks good to me**. Might be a little bit verbose on bigger chassis with a lot of Vlan Interfaces but it can be filtered by the users.
> > That being said, I think it would make sense to go a little bit further and create a dedicated module for HSRP/VRRP/etc that would complement the port page and replace these sensors.
> 
> Alright, just so I get this right.. You mean a new page in the tabs like Overview, Graph, Ports, VLANs, Neighbors, STP and alike?

2 angles: 
- For discovery, polling, creation of a new module, could be named "FHRP" to handle all the 1st hop redundancy protocols. (https://en.wikipedia.org/wiki/First-hop_redundancy_protocol). 
- For GUI, anywhere needed this information could be added, as soon as it is stored in the DB

> I'll work on that, but might take me a while. Limited free time and all. If in the meantime this PR can be approved that would be great, I'll remove this sensor when my new code is ready.

Yep, sounds good.

**Pull request merged**
