### PR TITLE
Correct link for Rule, Location (Alerts, and several other pages)

### PR DESCRIPTION
**Pull request by arrmo**
- wherever generate_url is used
- does not address hostname (device), separate PR for that

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
i didn't catch the problem.
Could you place some before/after example to easier/faster understand what this PR fixes?

**Comment by mpikzink** [comment]
Same Problem in my setup with a apache aliased environment. (base_url=/librenms)
I needed to fix the below part as well:

`public static function deviceUrl($device, $vars = [])
{
-        $routeParams = [is_int($device) ? $device : $device->device_id];
-        if (isset($vars['tab'])) {
-            $routeParams[] = $vars['tab'];
-            unset($vars['tab']);
-        }
-
-        return route('device', $routeParams) . self::urlParams($vars);
+     return self::generate(['page' => 'device', 'device' => is_int($device) ? $device : $device->device_id], $vars);
}`
No Idea if this will create other problems at the moment.

**Comment by arrmo** [comment]
> Same Problem in my setup with a apache aliased environment. (base_url=/librenms)

Exactly! That's my setup as well, same base_url 😄. So this fix works for you as well?

> I needed to fix the below part as well to fix Global Search URLs:

Will try this one! I hadn't found a fix for that yet, it's the part I was missing / trying to find (that I was talking about here, https://community.librenms.org/t/alerts-widget-links-fail/12696/9). This is the same issue I think?

**Comment by SourceDoctor** [comment]
still didn't get where you've find a problem.

please describe where exactly the problem is. Screenshots, URLs ...

also as @murrant wrote in your community post. Have you set base_url -> "Specific URL"?
It can be find here:
image
don't forget a "/" on the end

**Comment by mpikzink** [comment]
I changed my setup as I understood in
https://docs.librenms.org/Extensions/Sub-Directory/

Screenshot_2020-07-16_22-35-05
Screenshot_2020-07-16_22-33-42

It seems, that the baseurl is not considered in LibreNMS\Url.
When I try a test with the route() helperfunction from Laravel via tinker the URL was generated correctly.

**Comment by SourceDoctor** [comment]
`Finally, set APP_URL=/librenms/ in .env and $config["base_url"] = '/librenms/'; in config.php.`

could you show content `.env` file also?

**Comment by arrmo** [comment]
> I needed to fix the below part as well to fix Global Search URLs:

This fixed my hostname links as well (like I mentioned in the community post)! I'd say we check this for a bit, make sure it doesn't break something else => separate PR later if it's working 😄. Thanks!

**Comment by SourceDoctor** [comment]
could you change a space or so and recommit, so Inspector Tests would be restarted. They hang since 3days

**Comment by arrmo** [comment]
Sure, NP. Done!

**Comment by SourceDoctor** [comment]
and now Travis fix please;-)

**Comment by arrmo** [comment]
> and now Travis fix please;-)

Done! It was the space I removed to kick start the check again ... LOL.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-66-release-changelog-july-2020/12953/1

**Comment by arrmo** [comment]
> Same Problem in my setup with a apache aliased environment. (base_url=/librenms)
> I needed to fix the below part as well to fix Global Search URLs:
> 
> ```
> public` static function deviceUrl($device, $vars = [])
> {
> -        $routeParams = [is_int($device) ? $device : $device->device_id];
> -        if (isset($vars['tab'])) {
> -            $routeParams[] = $vars['tab'];
> -            unset($vars['tab']);
> -        }
> -
> -        return route('device', $routeParams) . self::urlParams($vars);
> +     return self::generate(['page' => 'device', 'device' => is_int($device) ? $device : $device->device_id], $vars);
> }
> ```
> 
> No Idea if this will create other problems at the moment.

Any more on this? I still have / see this issue ... you? Is this change safe (i.e. pull it in with a new PR)?

**Comment by mpikzink** [comment]
I have this fix since 1.65 and see no problems in my environment (apache aliased to /librenms).

**Comment by arrmo** [comment]
> I have this fix since 1.65 and see no problems in my environment (apache aliased to /librenms).

Seeing it working here as well! So submit a new PR?

BTW, do you also see an issue with the main page (i.e. link / icon in the top right corner)? Thinking it's an Apache config issue - do you mind sharing your Apache config (just for LibreNMS I mean!).

Thanks!

**Pull request merged**
