### PR TITLE
Enable PHPStan linter

### PR DESCRIPTION
**Pull request by Jellyfrog**
Couldn't add it via super-linter due to some errors with missing php extensions

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Any thoughts on what level to set?

Right now with level 3, its a modest 20 errors on the ignore list, 5 of them actual real bugs(!) 
Level 5 generates only 140 more errors.
Level 6 is all about type hinting, which also might be a good idea to start enforce (2565 more errors tho)

**Comment by Jellyfrog** [comment]
I added a commit to bump it to level 5

**Comment by murrant** [comment]
Level 6 seems too high.  Would be great if we can merge this with almost no blacklist.

**Comment by Jellyfrog** [comment]
Well. Each merge we do contributes to the ignore list :) so I think we should merge this as is. And work on fixes after

**Comment by murrant** [comment]
Should start settling down considering release is in a week.

**Comment by Jellyfrog** [comment]
@murrant I would like to merge this now before too many new errors trickle in :)

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
Going to have errors all over ;)

**Pull request merged**
