### PR TITLE
Added data sensors Vetiv-pdu OS

### PR DESCRIPTION
**Pull request by joseUPV**
Added new sensors
- Total Real Power
- Total Apparent Power
- Total Power Factor
- Total Energy

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
I think it's ready to merge, i don't know why is failing two checks.

**Review by electrocret — DISMISSED** [review]

**Comment by electrocret** [comment]
@joseUPV , can you go over the failed tests and fix the data?

**Comment by joseUPV** [comment]
Tests fails in other device of the same os, i can't regenerate this file because i don't have this device

1) LibreNMS\Tests\OSModulesTest::testOS with data set "vertiv-pdu_mn03edr1" ('vertiv-pdu', 'mn03edr1', array('os', 'ports', 'sensors'))
OS vertiv-pdu: Discovered sensors data does not match that found in tests/data/vertiv-pdu_mn03edr1.json

My device is tests/snmpsim/vertiv-pdu_mg03e4w1.snmprec

**Comment by murrant** [comment]
@joseUPV the snmprec files in LibreNMS include all the data required to regenerate the test data.

**Comment by murrant** [comment]
Already merged due to other PR including test data

**Pull request closed without merging**
