### PR TITLE
Add and extend support for Hirshmann devices

### LINKED ISSUE #15507: Hirschmann PowerMice MS4128-L3E
### The problem

Hi, first thank you for your work

Supervision of my switchs powermice MS4128-L3E ( .1.3.6.1.4.1.248.14.10.10)  don't work, i can't see hardware version , opêrating system version, in Health part i only see power supply 1 and 2, not LED Status : Fault, Standby, Redundancy Manager

Below here is my hirschman.yaml file ( my other switch works mach100, mach4000, rs20)

Thank you for your help

os: hirschmann
text: 'hirschmann'
type: network
icon: hirschmann
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.248.14.10.41
            - .1.3.6.1.4.1.248.14.10.10
            - .1.3.6.1.4.1.248.14.10.130
            - .1.3.6.1.4.1.248.14.10.50
            - .1.3.6.1.4.1.248.14.10.110
            - .1.3.6.1.4.1.248.14.10.40

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.9.1 (2023-09-19T01:59:06+00:00)
DB Schema | 2023_09_01_084057_application_new_defaults (259)
PHP       | 8.1.2-1ubuntu2.14
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         includes/definitions/hirschmann.yaml
```

### What was the last working version of LibreNMS?

_No response_

### Device info

Hirschmann PowerMice MS4128-L3E

### Discovery output

```txt
files joined
```

### Poller output

```txt
files joined
```

### PR DESCRIPTION
**Pull request by cguillaumie**
fixes #15507

History of "Temperature.0" is lost with this PR. The implementation (in PHP) was wrong and did not allow any other sensor to be polled properly. In order to fix it, all is moved to YAML but the index of the sensor cannot be kept, so graphs are lost.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Bonjour Guillaume,

Thanx for your PR. Seems that from the issue and this PR, the OS is now recognised (from generic to hirshmann). Do you confirm this ? 

If yes, then next step is to check if the device is providing the expected data for LED STATUS. Looking at the source files, it seems that the LED STATUS should come from the file `~/discovery/sensors/state/hirshmann.inc.php`.  Can you check that your device is indeed replying to the requests to the OID in that file ? 

To quickly do your checks, you can use `./discovery.php -h <yourDeviceId> -m sensors -v -d`.

**Comment by murrant** [comment]
Can we change the sysObjectID to `- .1.3.6.1.4.1.248.14.10.` so we don't have to add every single device?

**Comment by cguillaumie** [comment]
I confrm that my OS is recognized from generic to hirschmann with the version behind  for railswitch, not for the other one.
MS4128-L3E
image

Can we change the sysObjectID to - .1.3.6.1.4.1.248.14.10. so we don't have to add every single device?
good idea i will do it

[dicovery_105.txt](https://github.com/librenms/librenms/files/13392269/dicovery_105.txt)
[hirschmann_ms4128.snmprec.txt](https://github.com/librenms/librenms/files/13392277/hirschmann_ms4128.snmprec.txt)

**Comment by PipoCanaja** [comment]
Bonsoir Guillaume,
Could you add the snmprec file directly to the correct location : `~/tests/snmpsim/hirschmann_ms4128.snmprec`
PipoCanaja

**Comment by cguillaumie** [comment]
Done

**Comment by PipoCanaja** [comment]
Hi @cguillaumie 
I changed the OID to be generic for the discovery, and created the JSON test data. I will later try to see if the sensor part can be fixed.
Bye

**Comment by PipoCanaja** [comment]
The provided capture files does not contain any SNMP data for the LED part. So it seems that the device does not send it. 

Could you try to snmpwalk it directly and post the result ? 

`'/usr/bin/snmpwalk' '-v2c' '-c' <community> '-m' 'HMPRIV-MGMT-SNMP-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/hirschmann'<IP_address> .1.3.6.1.4.1.248.14.1.1.35`

**Comment by cguillaumie** [comment]
[capture_snmp.txt](https://github.com/librenms/librenms/files/13537432/capture_snmp.txt)

et voilà,

**Comment by PipoCanaja** [comment]
Bonsoir @cguillaumie 
I can confirm that no LED data is provided in the capture you sent me. So the code is probably working as expected, the issue here is the device, which is not providing the data. 
This PR is now OK for merge unless you have other things you would like to add in it. Let me know.

**Comment by cguillaumie** [comment]
Thanks,
 is it possible to have the version of operating system in the overview (hmSysVersion.0) and the platform (hmSysGroupDescription.1), in health, powersupply state and processors info, and the most important for hirschmann switchs is HMPRIV-MGMT-SNMP-MIB::hmRS2OperMode.0  , it says if the switch is redunduncy manager

**Pull request merged**
