### PR TITLE
docs: update world map doc

### PR DESCRIPTION
**Pull request by kkrumm1**
Update the World Map Doc. It was very confusing and had lots of old info. 

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Think it needs more than that. Afaik the doc currently covers two maps we have available.

Worldmap and Globemap are different.

**Comment by kkrumm1** [comment]
I see okay. Maybe should break it down into sections for each map.

**Comment by kkrumm1** [comment]
I know some parts have config but they are already on by default in the default config. Should we keep that info on the doc? It's just going to confuse users thinking they have to add that config.php

**Comment by kkrumm1** [comment]
okay, this going take allot more than i thought. I need to see how each Map works. Right now it's still very confusing.

**Pull request closed without merging**
