### PR TITLE
Added support for interval for alerting for WebUI

### PR DESCRIPTION
**Pull request by laf**
This will need to work in tandem with @f0o's PR so don't merge until then (well you could as it won't break anything).

#1095

### CODE REVIEW

**Comment by paulgear** [comment]
Which one of @f0o's PRs are we waiting on for this?

**Comment by f0o** [comment]
I havent gotten to it yet, shame on me :(

**Comment by paulgear** [comment]
@f0o - no shame required :-)

**Comment by laf** [comment]
I'm merging this as the alerts.php was f0os code I was just testing and putting it as part of this PR. The WebUI is a trivial change and I've tested.

**Comment by f0o** [comment]
:+1:

**Pull request merged**
