### PR TITLE
Update Installation-Ubuntu-1604-Nginx.md

### PR DESCRIPTION
**Pull request by BurntTech**
Remove default site link to avoid conflicts
rm /etc/nginx/sites-enabled/default

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Is this the same for centos? If so can you update that doc as well

**Comment by Gorian** [comment]
@laf last version of CentOS I used, nginx didn't have `/sites-{available,enabled}` by default, and instead used `/etc/nginx/conf.d`, I've always had to add the directory and config lines manually.

**Comment by laf** [comment]
Sorry I don't mean that path specifically more of a default exists like it does for apache.

**Comment by Gorian** [comment]
ah, okay. Yeah, should be able to add `rm /etc/nginx/conf.d/default` for CentOS I think

**Comment by laf** [comment]
@BurntTech bump

**Pull request merged**
