### PR TITLE
Added NOW() to dbUpdate calls to sensors

### PR DESCRIPTION
**Pull request by laf**
Needed for #2493 and #2590

### CODE REVIEW

**Comment by f0o** [comment]
I think that attempts a verbatim update 'NOW()' string, doesnt it?

**Comment by paulgear** [comment]
Yeah - don't think functions can be passed as parameters.  But if it's an autoupdate field, we can just leave it off and MySQL will fill it in.  MIB-based polling does that.

**Comment by f0o** [comment]
Like discussed on IRC, MySQL only updates the auto-update field if the new values are different than the old ones. For a sensor like bat0 voltage thats very stable it will nearly never update and librenms will always assume something is wrong.

Bpaste with test in IRC backlog at about 9pm UTC

**Comment by f0o** [comment]
For the log:
```
MariaDB [librenms]> select sensor_id,lastupdate from sensors;                                                                                                            
+-----------+---------------------+
| sensor_id | lastupdate          |
+-----------+---------------------+
|         1 | 2015-12-09 21:54:03 |
+-----------+---------------------+
1 row in set (0.00 sec)

MariaDB [librenms]> select NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2015-12-09 21:57:16 |
+---------------------+
1 row in set (0.00 sec)

MariaDB [librenms]> update sensors set sensor_id = 1 where sensor_id = 1;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

MariaDB [librenms]> select NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2015-12-09 21:57:21 |
+---------------------+
1 row in set (0.00 sec)

MariaDB [librenms]> select sensor_id,lastupdate from sensors;                                                                                                            
+-----------+---------------------+
| sensor_id | lastupdate          |
+-----------+---------------------+
|         1 | 2015-12-09 21:54:03 |
+-----------+---------------------+
1 row in set (0.00 sec)
```

**Comment by laf** [comment]
We use it in includes/discovery/functions.inc.php:

`dbUpdate(array('last_discovered' => array('NOW()'), 'type' => $device['type'], 'last_discovered_timetaken' => $device_time), 'devices', '`device_id` = ?', array($device['device_id']));`

And that seems to work ok.

**Comment by laf** [comment]
Bump

**Comment by f0o** [comment]
Giving it a whirl at home today

**Comment by Rosiak** [comment]
:+1:

**Comment by laf** [comment]
bump

**Pull request merged**
