### PR TITLE
Fortinet FortiADC detection and basic statistics

### PR DESCRIPTION
**Pull request by westerterp**
This PR adds OS detection for Fortinet FortiADC (Application Delivery Controller)
Also includes collecting basic statistics.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by westerterp** [comment]
I was able to create a SNMPREC file, but was unable to run the commands to convert it to JSON.
Is anyone able to accomplish this based on the provided SNMPREC file?

**Comment by Jellyfrog** [comment]
make sure you can run the command `snmpsimd` or `snmpsimd.py`, then you run `./scripts/save-test-data.php -o fortiadc -v vm`

**Comment by westerterp** [comment]
Thanks for the guidance. Retraced my steps and I'm now able to run snmpsimd, but run into the next error.
This error however seems unrelated to my changes.

<details>
    <summary>librenms@hostname:~$ snmpsimd --version</summary>

    SNMP Simulator version 0.4.5, written by Ilya Etingof <etingof@gmail.com>
    Using foundation libraries: pysnmp 4.4.12, pyasn1 0.4.2.
    Python interpreter: 3.8.10 (default, Jun 22 2022, 20:18:18) 
    [GCC 9.4.0]
    Software documentation and support at http://snmplabs.com/snmpsim
</details>

<details>
    <summary>librenms@hostname:~$ ./scripts/save-test-data.php -o fortiadc -v vm</summary>

    Starting snmpsim listening on 127.1.6.1:1161... 
    Scanning "/opt/librenms/.snmpsim/variation" directory for variation modules...
    Directory "/opt/librenms/.snmpsim/variation" does not exist
    Scanning "/usr/snmpsim/variation" directory for variation modules...
    Directory "/usr/snmpsim/variation" does not exist
    Scanning "/usr/share/snmpsim/variation" directory for variation modules...
    A total of 9 modules found in /usr/share/snmpsim/variation
    Scanning "/usr/lib/python3/dist-packages/snmpsim/variation" directory for variation modules...
    Directory "/usr/lib/python3/dist-packages/snmpsim/variation" does not exist
    Initializing variation modules...
    Variation module "writecache" from "/usr/share/snmpsim/variation/writecache.py" loaded OK
    Variation module "sql" from "/usr/share/snmpsim/variation/sql.py" load FAILED: database type not specified
    Variation module "subprocess" from "/usr/share/snmpsim/variation/subprocess.py" loaded OK
    Variation module "delay" from "/usr/share/snmpsim/variation/delay.py" loaded OK
    Variation module "numeric" from "/usr/share/snmpsim/variation/numeric.py" loaded OK
    Variation module "multiplex" from "/usr/share/snmpsim/variation/multiplex.py" loaded OK
    Variation module "redis" from "/usr/share/snmpsim/variation/redis.py" load FAILED: Redis connect parameters not specified
    Variation module "notification" from "/usr/share/snmpsim/variation/notification.py" loaded OK
    Variation module "error" from "/usr/share/snmpsim/variation/error.py" loaded OK
    --- SNMP Engine configuration
    SNMPv3 EngineID: 0x80004fb80570726c672d6d6f6e2d30312723af40
      --- Data directories configuration
      SNMPv3 Context Engine ID: 0x80004fb80570726c672d6d6f6e2d30312723af40
      Scanning "/opt/librenms/tests/snmpsim/" directory for  *.dump, *.MVC, *.sapwalk, *.snmpwalk, *.snmprec data files...
        Index /tmp/snmpsim/_opt_librenms_tests_snmpsim__adva_xg300_xg304.dbm out of date
    Traceback (most recent call last):
      File "/usr/bin/snmpsimd", line 1222, in <module>
        configureManagedObjects(
      File "/usr/bin/snmpsimd", line 868, in configureManagedObjects
        dataFile = DataFile(fullPath, textParser).indexText(forceIndexBuild)
      File "/usr/bin/snmpsimd", line 237, in indexText
        self.__recordIndex.create(forceIndexBuild, validateData)
      File "/usr/lib/python3/dist-packages/snmpsim/record/search/database.py", line 93, in create
        raise error.SnmpsimError('Failed to create %s for data file %s: %s' % (self.__dbFile, self.__textFile, sys.exc_info()[1]))
    snmpsim.error.SnmpsimError: Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__adva_xg300_xg304.dbm for data file /opt/librenms/tests/snmpsim//adva_xg300_xg304.snmprec: None
    
    Failed to start Snmpsim. Scroll up for error.

</details>

I've re-read the instructions on how to create test data, but could find no relevant info there.
Any more guidance would be much appreciated.

**Comment by Jellyfrog** [comment]
install snmpsim 0.4.7 and try again, else i can generate it for you

**Comment by westerterp** [comment]
Sadly snmpsim release 0.4.5 is the latest version available in the package manager (running Ubuntu 20.04).
Googled a bit to find a .deb file to install for version 0.4.7, but couldn't find anything that was of any use.

If you could generate the JSON test data, that would be great!

**Comment by westerterp** [comment]
I've removed the OS one. The pip one was already installed, but not in $PATH. Fixed that, but I still get that same error.

<details>
<summary>Command output</summary>

```
librenms@hostname:~$ ./scripts/save-test-data.php -o fortiadc -v vm
Starting snmpsim listening on 127.1.6.1:1161... 
Scanning "/opt/librenms/.snmpsim/variation" directory for variation modules... 
Directory "/opt/librenms/.snmpsim/variation" does not exist 
Scanning "/usr/snmpsim/variation" directory for variation modules... 
Directory "/usr/snmpsim/variation" does not exist 
Scanning "/usr/share/snmpsim/variation" directory for variation modules... 
Directory "/usr/share/snmpsim/variation" does not exist 
Scanning "/opt/librenms/.local/lib/python3.8/site-packages/snmpsim/variation" directory for variation modules... 
Directory "/opt/librenms/.local/lib/python3.8/site-packages/snmpsim/variation" does not exist 
--- SNMP Engine configuration 
SNMPv3 EngineID: 0x80004fb80570726c672d6d6f6e2d3031a38b4080 
  --- Data directories configuration 
  SNMPv3 Context Engine ID: 0x80004fb80570726c672d6d6f6e2d3031a38b4080
  Scanning "/opt/librenms/tests/snmpsim/" directory for  *.dump, *.MVC, *.sapwalk, *.snmpwalk, *.snmprec data files... 
    Index /tmp/snmpsim/_opt_librenms_tests_snmpsim__adva_xg300_xg304.dbm out of date
Traceback (most recent call last):
  File "/opt/librenms/.local/bin/snmpsimd.py", line 1243, in <module>
    configureManagedObjects(
  File "/opt/librenms/.local/bin/snmpsimd.py", line 883, in configureManagedObjects
    dataFile = DataFile(fullPath, textParser).indexText(forceIndexBuild)
  File "/opt/librenms/.local/bin/snmpsimd.py", line 241, in indexText
    self.__recordIndex.create(forceIndexBuild, validateData)
  File "/opt/librenms/.local/lib/python3.8/site-packages/snmpsim/record/search/database.py", line 93, in create
    raise error.SnmpsimError('Failed to create %s for data file %s: %s' % (self.__dbFile, self.__textFile, sys.exc_info()[1]))
snmpsim.error.SnmpsimError: Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__adva_xg300_xg304.dbm for data file /opt/librenms/tests/snmpsim//adva_xg300_xg304.snmprec: None

Failed to start Snmpsim. Scroll up for error.



librenms@hostname~$ snmpsimd.py --version
SNMP Simulator version 0.4.7, written by Ilya Etingof <etingof@gmail.com>
Using foundation libraries: pysnmp 4.4.12, pyasn1 0.4.2.
Python interpreter: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
Software documentation and support at http://snmplabs.com/snmpsim
Usage: ...


```

</details>

**Comment by Jellyfrog** [comment]
Maybe this path or owned by root or something. 
Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__adva_xg300_xg304.dbm

**Comment by Jellyfrog** [comment]
I can generate the data for you later

**Comment by westerterp** [comment]
Thanks for the guidance. I guess the folder permissions were messed up indeed because of using the OS package.
I was now able to generate the JSON test data.

Let's see if the tests succeed :heavy_check_mark:

**Comment by westerterp** [comment]
@Jellyfrog tests are successful now. Could you please review this again?

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
