### PR TITLE
fix: Updated ipv4/ipv6 discovery to exclude IPs with invalid port_ids

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

We just check we have a valid port_id before we carry on, this should clear out stale entries if the device still exists in librenms.

Fixes: #6302

### CODE REVIEW

**Comment by murrant** [comment]
What IP address are you removing with this?  Other than that question the code change looks straight forward enough.

**Comment by laf** [comment]
Ones that don't have a valid port id

**Comment by murrant** [comment]
Sorry, I mean I don't understand what kind of ips would not have a valid port id and why I wouldn't want them.

Perhaps ports in badif?

**Comment by laf** [comment]
Probably would have helped if I'd have linked to #6302

**Comment by murrant** [comment]
Sure would have ;)

**Comment by murrant** [comment]
Oh, it was an issue I created :blush: 

I don't think this fixes the problem.  I think the problem is in the $valid cleanup.

**Pull request merged**
