### PR TITLE
Update Install-LibreNMS.md

### PR DESCRIPTION
**Pull request by mjeffin**
Change the symbol for comments from # to ; 
This threw an error for me while following the steps and had to google to fix the issue. Changing to ; might help people like me who are new to php. Not sure if it would affect any older versions.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by SourceDoctor — APPROVED** [review]
good point
thanks

**Comment by murrant** [comment]
Interesting, I didn't consider that people would copy those lines :D

**Comment by mjeffin** [comment]
Haha, people who have absolutely no knowledge of php like me would 😁

**Comment by murrant** [comment]
Anything that makes it easier is appreciated, thanks.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1

**Pull request merged**
