### PR TITLE
Fixing some URLs and Images in /doc/

### PR DESCRIPTION
**Pull request by eimann**
DO NOT DELETE THIS TEXT
I encountered a few broken links in the documentation files, especially for linked images. This has been fixed in this PR.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by kkrumm1** [comment]
Thanks for the PR but those images are loading up. Adding the /doc/ would bring the link to the image?

**Comment by eimann** [comment]
Here's without the fix: https://github.com/librenms/librenms/blob/master/doc/Support/Adding-a-Device.md
Here's with the fix: https://github.com/eimann/librenms/blob/doc-fix/doc/Support/Adding-a-Device.md

**Comment by laf** [comment]
> Here's without the fix: /doc/Support/Adding-a-Device.md@master
> Here's with the fix: eimann/librenms:doc/Support/Adding-a-Device.md@doc-fix

@kkrumm1 is right, this would break it for the docs.librenms.org site which is typically where people will read the docs. The perm fix for both would be to put the images within the dir of each file and reference them relatively.

**Comment by eimann** [comment]
Thanks @laf. I'll give it some more work then and will close it for now.

**Pull request closed without merging**
