### PR TITLE
fix for issue #5585 sanitize location string

### PR DESCRIPTION
**Pull request by InsaneSplash**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [ x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by InsaneSplash** [comment]
I included the removal (by virtual or it not being allowed) the , in a name. I figured that its not required when searching google for a map location as long as each word is separated with a +

**Comment by laf** [comment]
This will cause more location lookups to happen. What about users on non-english characters?

**Comment by InsaneSplash** [comment]
Why would it cause any more than is currently, as its still within the same routine? I might not understand fully so please excuse me. I was looking at that, and have some conversion code we can use, but we would need to do some more testing I just don't have the "right" languages in my computer to do this?

Would it be worse than it is now?

**Comment by laf** [comment]
so the lookups are done on the location string, if that changes another lookup has to be done.

**Comment by InsaneSplash** [comment]
OK, do you think LibreNMS UTF-8 compliant?

**Comment by laf** [comment]
I doubt it :/

**Comment by InsaneSplash** [comment]
:) then we should be OK, and it gives us something to maybe look at moving towards :) ehhe

**Pull request merged**
