### PR TITLE
app: dhcp stats

### PR DESCRIPTION
**Pull request by crcro**

### CODE REVIEW

**Comment by murrant** [comment]
I'm getting this on for the graph
```
RRDTool Output
ERROR: Unused Arguments "" in command : AREA:dhcp_total9#582A7215::
```

**Comment by crcro** [comment]
i cannot reproduce this issue on my instance, weird

**Comment by murrant** [comment]
@crcro Removing the following line from `generic_v3_multiline.inc.php` fixed the issue for me.
```php
$descr = ":";
```

**Comment by crcro** [comment]
maybe something wrong with you generic_v3_multiline.inc.php, i have that line (line 96) and no errors.

**Comment by murrant** [comment]
It could be a difference in rrdtool?  I think I'm running 1.6.

**Comment by crcro** [comment]
i think that upgrading to rrdtool 1.6 will have a lot of changes implied, i tried to update on my server also and no graphs would work after that. i had to go back to v1.4.8 ...

**Comment by murrant** [comment]
I've been running 1.6 without any other issues.  I'll merge this and we can fix the graph separately.

**Comment by murrant** [comment]
You have merge conflicts.

**Pull request closed without merging**
