### PR TITLE
VMWare Guest State Traps and UI

### PR DESCRIPTION
**Pull request by h-barnhart**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

* Snmp trap handlers for on, off, and suspended state
  - Traps update state field in DB in realtime, which is reflected in the UI
* Snmp trap handlers for heartbeat lost.
* UI now shows suspended state
* Added unit tests for handlers and model factory for vminfo

LibreNMS VM Info

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Cool stuff, would be awesome if you could add some docs/example for this.  
Maybe a sub-page to doc/Extensions/SNMP-Trap-Handler.md

**Comment by h-barnhart** [comment]
I can attach some examples of expected outputs in the PR later today.

I'm not seeing what I could add to the documentation, the current documentation is what I used to build the handlers, unless you had something specifically in mind.

**Comment by h-barnhart** [comment]
I uploaded an example of the UI changes. Note that in the example for a suspended VM it says "suspended", but in the code I submitted it says "suspend" to save some real estate. I can add the "ed" back in if desired.

**Comment by Jellyfrog** [comment]
> I can attach some examples of expected outputs in the PR later today.
> 
> I'm not seeing what I could add to the documentation, the current documentation is what I used to build the handlers, unless you had something specifically in mind.

What I mean is an example of how go configure vmware and such, a bit out of scope for the docs but would be nice with some example since there is little written about the traps support in general.

Also the docs starts with:
>Currently, librenms only supports linkUp/linkDown (port up/down), bgpEstablished/bgpBackwardTransition (BGP Sessions Up/Down) and authenticationFailure SNMP traps

**Comment by h-barnhart** [comment]
I'll check on the SNMP Docs, I thought that had already been fixed. I'll probably open a new PR for that.

As for configuring VMWare, couldn't tell you. I asked our SysAdmin to do that as its not obvious where the SNMP settings are on VMWare hosts.

**Comment by Jellyfrog** [comment]
> I'll probably open a new PR for that.

Thanks

> As for configuring VMWare, couldn't tell you. I asked our SysAdmin to do that as its not obvious where the SNMP settings are on VMWare hosts.

Precisely my point :)
Since it's quite tricky to get right sometimes it would be good with some examples

**Comment by Jellyfrog** [comment]
@h-barnhart Would you mind looking into traps for vcenter server also? 🙏
https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.monitoring.doc/GUID-B42AD147-C7AC-48EF-B85B-F6D0F33032F2.html

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/proxmox-virtual-machine-page/10690/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
