### PR TITLE
Alcatel-Lucent Aos7 no bulk fix

### PR DESCRIPTION
**Pull request by paulierco**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @paulierco 
Why did you write a new _nobulk function ? The original is already using "_nobulk" if you configure it in YAML.

**Comment by paulierco** [comment]
Because...that will put everything in nobulk. I discovered that this increased the polling time for some of our core switches from 100s to 500s. 


There is only one state sensor that doesn't work with bulk. Damn Alcatel. 
I copy the other function to create only a nobulk function just for that small sensors. Probably is dirty and ugly.

The other way would be just to drop that state sensor but there is no way to have nobulk globally for OS.

image

**Comment by PipoCanaja** [comment]
Hi @paulierco 
Another nicer option would be to extend YAML syntax to support this nobulk setting on a "per-sensor" basis. This is not currently possible but could be achieved with some changes in `function gen_snmpwalk_cmd` definition in `includes/snmp.inc.php`.

**Comment by PipoCanaja** [comment]
And for next time, you need to explain the change you are suggesting in the Pull Request description. This allows the reviewers to understand what you are trying to achieve (and why)

**Comment by paulierco** [comment]
> 
> 
> Hi @paulierco
> Another nicer option would be to extend YAML syntax to support this nobulk setting on a "per-sensor" basis. This is not currently possible but could be achieved with some changes in `function gen_snmpwalk_cmd` definition in `includes/snmp.inc.php`.

Not sure how to do that. If someone can add this to YAML, i can modify the change and move it back.

**Comment by paulierco** [comment]
> 
> 
> And for next time, you need to explain the change you are suggesting in the Pull Request description. This allows the reviewers to understand what you are trying to achieve (and why)

You're right. My mistake here. I will take care of this next time. Sorry.

**Review by murrant — CHANGES_REQUESTED** [review]
Instead of duplicating code, you should set nobulk temporarily: `Config::set('os.aos7.nobulk', true)`  then `Config::forget('os.aos7.nobulk')`

Also, do not use pre-fetch when it the data is only used in one place.  Pre-fetch makes things less optimal in this case.

This could be added to yaml snmp options if desired.

**Comment by paulierco** [comment]
> Instead of duplicating code, you should set nobulk temporarily: `Config::set('os.aos7.nobulk', true)` then `Config::forget('os.aos7.nobulk')`

This should be done [here ](https://github.com/librenms/librenms/blob/bb39b4ad83f7348a9b51d8cab998f5923ddcfb2f/includes/snmp.inc.php#L132)?

**Comment by paulierco** [comment]
I think i know how to do this, i will try to make the changes in the next two days.

**Comment by paulierco** [comment]
I will reopen this after https://github.com/librenms/librenms/pull/12833 is finished.

**Pull request closed without merging**
