### PR TITLE
Added support for Fiberstore S5800 switch

### PR DESCRIPTION
**Pull request by lennarttd**
Added support for Fiberstore S5800 switch, including CPU, memory, temperature values, fanspeed and PSU states.
As Fiberstore sells multiple switches it might be necessary to create multiple SWITCH-MIBs with different enterprise values and check for compatibility with other switch models.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by lennarttd** [comment]
Test data has been added.

**Comment by murrant** [comment]
Why did you delete the existing detections?

**Comment by lennarttd** [comment]
I have updated the YAML so the existing detections are combined with the new detections.

**Comment by lennarttd** [comment]
I believe the tests are failing as I adapted the MIB and set the enterpise line to match the MIB of the S5800.
The older versions of this switch have a different enterprise ID.

Is there a possibility to merge the two into one single MIB? Besides the enterprise line the MIBs should be identical.

The new model uses `	::= { enterprises 52642 1 }`
and the older model uses `	::= { enterprises 27975 }`

**Comment by murrant** [comment]
@lennarttd I would highly suggest not doing that unless you know it works 100%.  Also, keep in mind that sysObjectID does not specify which oids the device will respond on.   Some bad SNMP implementations change the MIB base OID, which I hope they haven't done.  If they have changed the Base OID, unfortunately, it is basically a different OS and we probably need a seperate OS for it.

**Comment by Jellyfrog** [comment]
First of all, thank you for your contribution!

We're closing this due to inactivity, feel free to reopen if you find the time to continue on this!

**Pull request closed without merging**
