### PR TITLE
Don't run tests on PHP 5.4, 5.5, 7.0.  Add PHP 7.2

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Is this for when we drop < 5.6 support? If so then I think we should hold out until that date.

**Comment by murrant** [comment]
No, it just seems like a waste to test these middle versions.  Definitely open for discussion.

**Comment by laf** [comment]
We're only 8 days away from dropping the support for these anyway so we may as well just wait until then?

**Comment by murrant** [comment]
What about PHP 7.0 and maybe 7.1 after 7.2 is more established? Do we still want to run tests for them?

I'll admit the main reason for this PR is I don't like that we can't run all of the jobs at once in Travis.

**Comment by laf** [comment]
https://docs.travis-ci.com/user/speeding-up-the-build/#PHP-optimizations to help speed things up a little maybe.

The thing with excluding versions is if functions get dropped or are added between them, it means we can break X version because no one can know which functions are always available so for the time difference, I'd prefer to keep them.

It would be good to skip all remaining builds if the first php version we check fails. They also have some other info on parallel builds using matrix, ours look to run sequentially so maybe we could speed things up there.

**Pull request closed without merging**
