### PR TITLE
Eltek eNexus sensor improvements

### PR DESCRIPTION
**Pull request by vitalisator**
- additional sensors
- some cleanup in yaml
- add Current, Runtime, Voltage to device over

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @vitalisator 
Thanx for your PR. Could you let us know why you removed the file  tests/data/enexus_smartpacks2.json ? The goal of the test data is to test regressions and analyse changes between versions. In this case, we need to identify which (if any) sensors will change, loose historical data, etc etc). In this case, I would suggest to update it instead of deleting it. 
Thanx

**Comment by vitalisator** [comment]
@PipoCanaja, I had just problems with pre-commit tests while both files were present.

**Comment by PipoCanaja** [comment]
Hi @vitalisator 
The idea of test files is to check regressions. Or changes that impacts deeply the discovery OR poller. In this case, as you said, pre-commit did warn you that a change occured. Which is expected in your case, cause you are precisely changing discovery and polling. 
You need to update all the existing test-files (so pre-commit does not complain) and we get all the changed test data in the PR (so we have a chance to see if a change in this PR may break historical data, or anything like this). 
So could you please re-add the file, and update it so we can review this PR.
Thanx

**Comment by murrant** [comment]
@vitalisator you are adding new sensors, but you also have removed sensors from other devices.  You need to have both in the yaml.  Only ones that are present will be discovered.

**Comment by vitalisator** [comment]
> @vitalisator you are adding new sensors, but you also have removed sensors from other devices. You need to have both in the yaml. Only ones that are present will be discovered.

if you mean 
oid: load  and oid: battery
that are replaced by more granular oids: loadFuseTable and oid: batteryBankTable
that should not regress other devices.

**Comment by vitalisator** [comment]
after some rework, I think we don't need to inform about changing sensors.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
