### PR TITLE
fix: Apply divisor / multiplier to high/low limits in sensors

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #8163 

If a numeric value is provided for _limits then it's used as is. If not, we apply the divisor / multiplier to those limits. I've been through all the yaml files and the only one which will have an issue with this is the one I've changed to hard coded limits. The devices value requires a divisor but the _limits don't.

Uncommented the _limit values from the yaml that the issue references as it was commented out due to this.

This will fix some high/low limits for yaml files where it should have been applied to but isn't.

### CODE REVIEW

**Comment by murrant** [comment]
What do you think about having a different key for limits that don't need a divisor?
For example `raw_high_limit`?

**Comment by laf** [comment]
We could I guess. This one vendor I've changed is the only one I've seen that doesn't support it as you'd expect so I'd prefer to keep things simple until we do actually need it.

**Comment by murrant** [comment]
@laf, you can update all sensors by running `./scripts/save-test-data.php -m sensors`

**Comment by laf** [comment]
Finally!

**Comment by laf** [comment]
Well spotted @murrant should be fixed now.

**Pull request merged**
