### PR TITLE
Dynamic dashboard

### PR DESCRIPTION
**Pull request by laf**
Should be ready now.

Currently has the following widgets available:

Availability  map
World Map
Alerts
Device summary horizontal
Device summary vertical

### CODE REVIEW

**Comment by Rosiak** [comment]
- World map doesn't scale automatically when size is changing(Only after some time. Perhaps this will be solved with the new map).

**Comment by paulgear** [comment]
OK - couple of questions:
- Is includes/defaults the best place for set_debug()?  I would have thought includes/common would be better.
- Was any of the stuff from html/pages/front/tiles.php based on bootgrid sample code?  If so, we should give credit.
Overall, looks good.

**Comment by laf** [comment]
1. set_debug() needs to be called before as much code as possible as it sets the debug level, includes/defaults.inc.php is the first included file across the code base.

2. Possibly bits, the majority is all from the docs provided for each of functions that are included. I've already added an acknowledgement to docs/General/Acknowledgement.md.

**Comment by paulgear** [comment]
Looks like it this needs a rebase now.  I'm happy to leave set_debug() where it is, but if there are relevant portions of the code in html/pages/front/tiles.php which came from the bootgrid documentation, I'd really like to see links to them in comments.  This will make it easy for us to respond to DMCA takedowns.

**Comment by laf** [comment]
rebased, comment added for the source of one piece of code. The rest are from the documentation.

**Comment by Rosiak** [comment]
Since we're back on track, ready to merge?

**Comment by f0o** [comment]
trigger ci

**Comment by laf** [comment]
:bump:

**Comment by f0o** [comment]
Has my :+1: 
I suppose we should wait until we can make sure everybody has the new daily.sh to avoid MySQL stalling

**Comment by laf** [comment]
Yeah, wait until at least another 10 hours or so for this with daily updates that currently work, anyone else it won't make a difference for.

**Comment by f0o** [comment]
@paulgear / @laf / @Rosiak Are we ready for this one?

**Comment by Rosiak** [comment]
All good, except the world map widget.

I've discovered the following location breaks the globe-map WIDGET.
```
mysql> select location from devices where device_id=326;
+----------+
| location |
+----------+
| Kølegård |
+----------+
```
When i say break, the map widget returns this:
```
{ "status": "ok", "html": null } 
```

I agree that the one who set this snmp location with these characters deservees some ... 
But anyways, this could still happen. 

Fun fact, the globe.php page is able to load the map(no locations tho), which the widget is not.

But yeah, just a heads up.

**Comment by f0o** [comment]
Would an `htmlentities()` or `urlencode` solve it?

**Comment by laf** [comment]
Yeah that's the fix for it. I'd have to close this PR and do another one though as I've re-forked.

I'd much prefer to add the new map anyway when it gets merged.

**Pull request merged**
