### PR TITLE
Create MAS-MIB-SMIV2-MIB

### PR DESCRIPTION
**Pull request by jp-asdf**
This is the SNMP v2 MIB Object Definitions for a Citrix ADM

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @jp-asdf 
Anything you would like to do with this mib ? adding it to LibreNMS mibs does not improve in anyway the discovery. You need to also create/extend the YAML (definition or discovery files)  at least.

**Comment by jp-asdf** [comment]
Hi. We are adding this MIB for SNMP trap definitions (we enabled snmptrapd per the Libre documentation) and figured someone else might be in the same boat and might be able to use it too.

Jeremy Palmer
Neustar, Inc. / Network Architect, UltraDDoS Protect Network Engineering
jeremy.palmer@team.neustar / www.neustar.biz

**Comment by PipoCanaja** [comment]
All right, makes sense. 

Thanx for your contribution.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-62-release-changelog-march-2020/11423/1

**Pull request merged**
