### PR TITLE
Reimplemented filtering of devices under maintenance when displaying …

### PR DESCRIPTION
**Pull request by gdepeyrot**
…only Down devices in the WorldMap

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
You should keep logic in Widgetcontroller

**Comment by gdepeyrot** [comment]
Yes, I later found that the logic is in Widgetcontroller. And the filtering is already implemented. However, there is a bug because the filtering in Widgetcontroller of devices under maintenance when displaying only down devices doesn't work... I haven't figured out what is going wrong yet.

**Comment by Jellyfrog** [comment]
Please test #10778 @gdepeyrot

**Comment by Jellyfrog** [comment]
See https://github.com/librenms/librenms/pull/10778 instead

**Pull request closed without merging**
