### PR TITLE
Added PBN OS Logo

### PR DESCRIPTION
**Pull request by vitalisator**
1st the Logo ;-)

my first GIT step

### CODE REVIEW

**Comment by vitalisator** [comment]
hmm.
on the first pull request i had only add the pbn.png file
on the second pull request i had fix the chmod of the file to 0644, but now i see there are 5 other files changed too. Why this?

after fixing the chmod i run:

git add html/images/os/pbn.png
git commit -a -m 'Added feature to do X, Y and Z'
git checkout master
git pull upstream master
git push origin master
git checkout issue-1140
git pull origin master
git push origin issue-1140

where i have make a mistake?

sorry i am new on git ;-)

**Comment by laf** [comment]
I don't think you've really made a mistake, our docs suggest to do it this way but if I'm honest I'd suggest not bothering to rebase, it's necessary unless your PR would create a conflict.

For future, don't bother with these by default:

git checkout master
git pull upstream master
git push origin master
git checkout issue-1140
git pull origin master

Also, this logo isn't of use without discovery code for this device type. You can submit this in the same PR rather than a separate one.

**Comment by vitalisator** [comment]
i'm done with this pull request.
what happens now? should i close or wait until someone merged this to master?

sorry i'm new here.

**Comment by laf** [comment]
Thanks @vitalisator.

Based on the output from sysDescr you posted you can get hardware and serial support by putting together includes/polling/os/pbn.inc.php as well.

**Comment by vitalisator** [comment]
Maybe i need some help or a template for this, i’m not very familiar with regex and php

**Comment by laf** [comment]
@vitalisator Is the output you posted the other day as it appears from snmp, i.e multi line?

**Comment by vitalisator** [comment]
Yes, I had copied it 1:1 from snmpget command.

**Comment by laf** [comment]
Whilst someone helps you with the polling code can you submit a contributors agreement, an example is: https://github.com/librenms/librenms/pull/1118

**Comment by laf** [comment]
@vitalisator try this:

```php
if (preg_match('/^Pacific Broadband Networks .+\n.+ Version ([^,]+), .+\n.+\n.+\nSerial num:([^,]+), .+/', $poll_device['sysDescr'], $regexp_result)) {
    $version = $regexp_result[1];
    $serial = $regexp_result[2];
}
```

Please don't forget to do the contributors agreement, we need that before we can merge this.

**Comment by vitalisator** [comment]
its working for me fine, now waiting for merge.

**Pull request merged**
