### PR TITLE
Juniper Hardware Inventory Fix (issue 1865)

### PR DESCRIPTION
**Pull request by Tatermen**
Related to issue 1865, this should fix the issue of the hardware inventory being discovered multiple times.

### CODE REVIEW

**Comment by laf** [comment]
Is it not just easier to leave most of the code as is and just remove the '.' (dots) from the juniper results? Changing the entPhysicalIndex means that existing graphs break for everyone rather than just those with juniper which would be more preferred.

**Comment by Tatermen** [comment]
There is already a specific exemption within the code for JunOS devices, so it should only remove the dots for Juniper devices.

    foreach ($entity_array as $entPhysicalIndex => $entry) {
        if ($device['os'] == 'junos') {
             ...
            $entPhysicalIndex = str_replace('.','',$entPhysicalIndex);
        }

**Comment by laf** [comment]
Ah yeah, sorry it was with you commenting out the junos check later I wrong assumed it was now doing it on all.

So just two things now then:

 - We need a contributors agreement from you: http://docs.librenms.org/General/Contributing/

 - Can you remove the code you've commented out. We don't need to keep it as it's all in git so we can pull it back if we need.

**Comment by Tatermen** [comment]
Sorry about the comments - force of habit. I think I've done the contributors thing correctly now?

**Pull request merged**
