### PR TITLE
update Unbound to work with SNMP polling as well

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This requires https://github.com/librenms/librenms-agent/pull/102 .

### CODE REVIEW

**Comment by florianbeer** [comment]
@VVelox could you tell me how you run snmpd and unbound-control? I am getting some problems concerning permissions. snmpd runs as user "snmp" and thus can't execute unbound-control correctly. I also tried with sudo but somehow wasn't successful there either.

**Comment by VVelox** [comment]
@florianbeer if sudo is not working, it means you got a configuration problem with that.

If you are not running snmpd as root, you need to check your config and make sure the user it is running as can read/write to the socket specified in by control-interface in the config.

Alternatively you could look into setting it to like 127.0.0.1 and having the control key be readable by snmpd.

**Comment by laf** [comment]
Needs a rebase but the Unbound SNMP link needs adding in the application menu as well.

**Comment by laf** [comment]
@VVelox bump?

**Comment by VVelox** [comment]
@laf Hey, sorry, been a busy week this week. Shall take a look at it once the weekend begins at 07:00 today.

**Comment by laf** [comment]
No worries - just reminding :)

**Comment by VVelox** [comment]
@laf done :)

**Pull request merged**
