### PR TITLE
newdevice: Added detection for IgniteNet FusionSwitch devices

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7310

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7354)

### CODE REVIEW

**Comment by Rosiak** [comment]
Looks good, just a tiny thing maybe add hardware/firmware info, I see some the info listed under:
.1.3.6.1.4.1.259.6.10.120.1.1.3.1.

**Comment by laf** [comment]
No mibs, I don't like using numerical OIDs.

**Comment by MHammett** [comment]
MIB for switch:  https://www.dropbox.com/s/kw0ig09vgkjyw5z/ES4552BH2.mib?dl=0

MIB (work in progress) for IgniteNet wireless: https://www.dropbox.com/s/eiaixnklv6t25lt/IGNITENET-MIB.mib?dl=0

**Comment by laf** [comment]
@MHammett post the mibs in the relevant issue and I'll re-open

**Pull request merged**
