### PR TITLE
update BIND support

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This requires https://github.com/librenms/librenms-agent/pull/108 .

### CODE REVIEW

**Comment by laf** [comment]
Is this a breaking change to existing setups?

**Comment by VVelox** [comment]
Datawise no, but from a polling standpoint yes. Requires that updated as the existing poller won't feed it useful data.

Regardless though the poller stuff for this needed a massive rewrite as it was just truly awful. It transfers the entire stat file over the wire and assumes that it is the only thing using the stat file.

**Comment by laf** [comment]
If the unix-agent code hasn't changed then surely this should remain backwards compatible?

**Comment by laf** [comment]
@VVelox Any further updates on this?

**Comment by VVelox** [comment]
@f0o Whoops. Sorry, good catch about that bit. Readded for  html/pages/device/apps/bind.inc.php .

Updated. Should be all good now.

**Comment by laf** [comment]
@librenms/reviewers tagging to be merged in 48 hours

**Pull request merged**
