### PR TITLE
Update Dispatcher-Service.md

### PR DESCRIPTION
**Pull request by systeembeheerder**
Removed the CRON part.

Scheduler is handled with a systemd service now. See https://docs.librenms.org/Installation/Install-LibreNMS/#enable-the-scheduler

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by systeembeheerder** [comment]
Added #15706 
remove the "Debian 12 Bookworm is not available".

**Comment by ottorei** [comment]
@Jellyfrog isnt the artisan scheduler supposed to still be in the cron (or possibly systemd timer) to prepare for future Laravel queue based scheduling you suggested a while ago?

**Review by ottorei — DISMISSED** [review]

**Review by electrocret — APPROVED** [review]

**Comment by PipoCanaja** [comment]
test re-run hopefully

**Review by murrant — CHANGES_REQUESTED** [review]
You deleted too much.  Users still need to remove the cron scripts.

**Review by murrant — APPROVED** [review]

**Pull request merged**
