### PR TITLE
add OS detection support for the Alcatel-Lucent (Nokia) 7210 SAS-M 24F 2XFP per issue #3554

### PR DESCRIPTION
**Pull request by nwautomator**
Resolves Issue #3554

### CODE REVIEW

**Comment by murrant** [comment]
Could you perhaps just use `.1.3.6.1.4.1.6527` or is there overlap with other devices?

**Comment by laf** [comment]
6527 is the enterprise number assigned to Alcatel, it might cover too much.

Needs a rebase though :(

**Comment by murrant** [comment]
I was just looking at what is in the discovery and all 6527 enterprise numbers resolve to timos.  arubaos and aos have different numbers.

**Comment by Rosiak** [comment]
@nwautomator Just a rebase and then we'll merge :)

**Comment by nwautomator** [comment]
@Rosiak Rebased. Let me know if any further issues arise. Thanks!

**Comment by laf** [comment]
You've got 80 commits and 28 changed files in this, looks like you've got a load of already merged changes in. Can you please clean this pr up.

**Comment by Rosiak** [comment]
Any news @nwautomator ?

**Comment by murrant** [comment]
Added in PR #3698

**Pull request closed without merging**
