### PR TITLE
update documentation for Centos 7

### PR DESCRIPTION
**Pull request by svennd**
Rewrote the manual to be a bit easier to follow for Centos/RHEL. If this is not oke or some guidelines have been set I have missed, sorry!

Most explicit Centos 6/7 I have removed as they are unneeded, any user of this software probably knows better and can find a solution (like restarting/adding services to boot order) If not it would be easy to find. 

Might be useful if someone proofreads. (I used this document for Centos 7.1 install)

### CODE REVIEW

**Comment by MindTooth** [comment]
Care to take a look at this: https://gist.github.com/MindTooth/1ac31c68baa5f69899bb

Extra steps I needed to add before I could have a fully functional CentOS 7 system.

**Comment by svennd** [comment]
Thx @MindTooth I did not use selinux in this setup so thanks for your addition!

**Comment by laf** [comment]
Thanks for having a crack at the docs @svennd and I'd like comments from @librenms/reviewers as well but my thoughts are:

1. The instructions on using the web installer seem to have been removed.

2. CentOS 6 / 7 instructions have been merged into the old format of chkconfig / service. Imho we should keep them separate as at some stage they will be deprecated anyway. 

3. I personally think it's a good idea to give install instructions for MySQL / Web separately and maintain the option of running mysql / mariadb.

I'd (again personally) say that we can't and shouldn't assume people will be able to work commands out of find them. We deal with a lot of support requests where people don't always follow the install instructions so making them a little more vague seems counter productive and may result in more questions.

Really appreciate you taking a stab at it but I don't think it needs such a rewrite to get it just so. All imho.

**Comment by svennd** [comment]
Thanks for the feedback @laf.

1) I should add that again, I checked the webinstaller just yesterday and I'm not sure why this is not the default way of doing things, its licked.
2) but chkconfig and service is linked in Centos 7 as such its still valid to use these commands, one of the largest issues I had with the docs is the fact that Centos 6/7 are all mixed up and generally make the look & feel more difficult then it should be. Centos 6 is still supported until 2020. By that time I think most users will know that systemctl is now the correct one and we can change them then. For now they work in both Centos 6 and Centos 7.
3) They are still in there I believe, I primary used MariaDB as in Centos 7, its pushed is as replacement, but all commands that don't work for Centos 6 are noted for the users (at least should be).

Thanks, but if you think its more vague, I kinda failed in documenting. I wanted to rewrite them, to make them easier, shorter to follow to get it up and running for both Centos 6/7. Now you get way to much choices where no choice should be in a guide. (MySQL/MariaDB, Webinterface/console, Local DB/ External DB server, Centos 6/7, ...)

Thanks for taking the time to reply.

**Comment by laf** [comment]
Ok agreed on point 2) then :)

On 3). I don't see any commands on how to install MySQL if you don't have MariaDB (or if you don't want to use MariaDB). Without instructions people will struggle (or so we've found).

These are just my thoughts. Would be handy for @librenms/reviewers to chip in as well.

**Comment by paulgear** [comment]
I don't use CentOS, so I'm not the best person to comment, but if any of the changes are applicable to the other install docs, then I'd like to see them added there.

Actually, I'd really like to see the install docs merged with just different sections for the different distros, but that's probably a bit optimistic for right now...

**Comment by svennd** [comment]
I agree, but then you have to test all the distro's at the moment I don't have the time to test all of them , I think I might revisit it in the future, but for now I think its best closed ?

**Comment by laf** [comment]
@svennd you're more than welcome to close and re-open when you come back to it :)

**Pull request closed without merging**
