### PR TITLE
Global Search - IPv4, IPv6

### PR DESCRIPTION
**Pull request by SourceDoctor**
enhanced Global Search field to search for IPv4 and IPv6 also.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
Ping only Devices still not included

**Comment by PipoCanaja** [comment]
We have to be careful with the performances

**Comment by SourceDoctor** [comment]
Thats another reason why it's WIP ;)

**Comment by SourceDoctor** [comment]
Now port and ip address tables will only be joined if a valid ip address is detected in search field.
Also only ipv4 or ipv6 table will be joined, depending on which address type is detected.
This should reduce significant DB load

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/global-search-by-ip-address/11191/2

**Comment by Jellyfrog** [comment]
Bigger changes like this should be converted to eloquent instead.  
@murrant its possible to use eloquent in the old code base also right?

**Comment by SourceDoctor** [comment]
@Jellyfrog 
this is no bigger change, it's a little rewrite for easier seeing and adding IP search ;)

**Comment by Jellyfrog** [comment]
It would be way more readable in eloquent :)

**Comment by SourceDoctor** [comment]
that's valid for all old code ;-)

but if every little change/enhancement in old code everytime ends up in "please rewrite into eloquent before" will demotivate very much

**Comment by Jellyfrog** [comment]
Yes ofc, it has to be judged case to case, this one isn't that small with "+42 −9". 
But it's up to you

**Comment by SourceDoctor** [comment]
i'm totally with you and i'd prefer also to have everything in eloquent and blade,
But i only added a join with another filter. At moment a complete rewrite is to much for myself.

**Comment by PipoCanaja** [comment]
@SourceDoctor @Jellyfrog 1st testing of this PR is very positive in my test AND prod platforms. 

Concerning the rewrite, I'm with @SourceDoctor, this is a "quick" enhancement, IMO, "quick" being calculated against a complete rewrite. So if testing goes as good as it is now, it'll get my approval.

**Comment by PipoCanaja** [comment]
@SourceDoctor So far so good.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-62-release-changelog-march-2020/11423/1

**Pull request merged**
