### PR TITLE
Update of Brocade mibs

### PR DESCRIPTION
**Pull request by xbeaudouin**
Hi,

Some update of Brocade mibs.

Regards

### CODE REVIEW

**Comment by laf** [comment]
Can you confirm where you have got the mibs from please?

**Comment by xbeaudouin** [comment]
Hi!

Sorry for the délay. I got them from brocade ;)
Regards

--
Xavier BEAUDOUIN

**Comment by laf** [comment]
In what way? Are they licensed for open source use?

**Comment by xbeaudouin** [comment]
Hi dunno

There is No licence in the tgz file i got :(

--
Xavier BEAUDOUIN

**Comment by laf** [comment]
@librenms/reviewers everyone happy with this?

**Pull request merged**
