### PR TITLE
Add sysobjectid and hardware fields into oxidized maps

### PR DESCRIPTION
**Pull request by Negatifff**
added hardware and sysObjectID into source fields list in variable mapping for oxidized.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Almost, now, rebase this on current upstream (there were some recent JS changes) and run `npm run prod` and include app.js

**Comment by Negatifff** [comment]
> Almost, now, rebase this on current upstream (there were some recent JS changes) and run `npm install` then `npm run prod` and include app.js

I'm sorry that you have to support this, but I'm stumped: I did 'npm install' and run 'npm run prod'... where? I tried it in librenms directory but get error.

**Comment by murrant** [comment]
That is correct, the error message might be helpful. :) You can also come discuss on Discord it is easier for these kind of discussions.

**Comment by Negatifff** [comment]
I hope now everything is correct :)

**Comment by Negatifff** [comment]
@murrant Tony, something wrong with this request?

**Review by murrant — APPROVED** [review]
Nope,  just waiting for me to have time :)

**Pull request merged**
