### PR TITLE
fix: Change rfc1628 'state' (est. runtime and on battery) to runtime

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by FTBZ** [comment]
Thanks for all your job @murrant. Not sure that this graph is working enough in "runtime" type. Because when you're not on battery it returning nothing.

screen shot 2017-03-10 at 07 27 06

The "seconds on battery" graph a value of 0, but the "minutes remaining" graph isn't working (Error Drawing Graph).

**Comment by murrant** [comment]
Yeah, not sure what the issue is with the graphs.  I'l check it out when I get a chance.

**Comment by laf** [comment]
I thought I'd commented on this last night, I updated #6153 before seeing this.

I can remove that change no problem but the runtime code should just be an snmp_get shouldn't it as it's only one OID.

**Comment by murrant** [comment]
You commented on the application discovery PR, I was confused at first  :-). Let me check the MIB, unless you already did...

**Comment by laf** [comment]
Was pushing my lack of sleep last night :/

image

**Pull request merged**
