### PR TITLE
Add support for description texts in Settings page

### PR DESCRIPTION
**Pull request by Jellyfrog**
By adding a `description` row in the translation like so:
```php
'distributed' => [
  'name' => 'Distributed Poller',
  'description' => 'Distributed Polling allows the workers to be spread across additional servers for horizontal scaling. Distributed polling is not intended for remote polling. Devices can be grouped together into a poller_group to pin these devices to a single or a group of designated pollers.'
]
```

Before:
Screenshot from 2021-08-04 19-04-44
After:
Screenshot from 2021-09-01 17-57-58

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@murrant the vue part is not 100% kosher, could you check?

**Comment by murrant** [comment]
You shouldn't be putting any code in AccordianItem for this... Put it in LibrenmsSettings.  (tip everything inside the according-item tags replaces the <slot></slot> in AccordianItem)

**Comment by Jellyfrog** [comment]
> You shouldn't be putting any code in AccordianItem for this... Put it in LibrenmsSettings. (tip everything inside the according-item tags replaces the in AccordianItem)

I was afraid of this :) I will look into it

**Comment by murrant** [comment]
It is much easier than you think... delete everything in AccordionItem and put this line in:
```javascript
<accordion-item v-for="(items, item) in groups[group]" :key="item" :name="item" :text="$t('settings.sections.' + group + '.' + item + '.name')" :active="item === section">
    <p>{{ $te('settings.sections.' + group + '.' + item + '.description') ? $t('settings.sections.' + group + '.' + item + '.description') : '' }}</p>
    <form class="form-horizontal" @submit.prevent>
```

**Comment by Jellyfrog** [comment]
@murrant like so? Seems2work

**Comment by murrant** [comment]
Yes, add some descriptions at least otherwise no one will know this feature exists :)

Also, the <p> should be better styled, looks like garbage.

**Review by murrant — APPROVED** [review]

**Pull request merged**
