### PR TITLE
Modify ‘discovery-protocols.inc.php’ to fix neighbours problem on Extreme Networks EXOS switch

### PR DESCRIPTION
**Pull request by longchihang**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Please go to the URL for details!
https://community.librenms.org/t/modify-discovery-protocols-inc-php-to-fix-neighbours-problem-on-extreme-networks-exos-switch/7797

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @longchihang 
Thank you for your PR. 
Do you expect this patch to work OK on all EXOS devices ? Could you post the devices you tested this against ? 
Thanx

**Comment by longchihang** [comment]
@PipoCanaja 
I have tested in my company lab environment. Those switches are stack-able switch but not run in stacking mode:
Summit X450a-48t 
Summit x670v-48x
For stacking switch, I have reviewed my company production switch. The LLDP Port Id is "1:1" format.  
The prefix "1" means the stacking member number (slot 1),  the post "1" means the port number.
In xos case, the SNMP always post ifIndex as "1001" format to port id "1" (non-stacking) or "1:1" (stacking), no matter the switch is stacking or non-stacking. My code converts ("1" or "1:1") to "1001" for discovery, by original code, it get what LLDP port id showing to "remote_port" of DB "links" table, no any converting. In the code file, I have seen having case as 'calix' also having converting.

IMG_20190324_123116-1

IMG_20190324_123148-1

IMG_20190324_123200-1

IMG_20190324_123230-1

**Comment by zombah** [comment]
Is it possible to add test data which covers this fix?

**Comment by PipoCanaja** [comment]
Would be awsome but it needs 2 devices in a lab (or anonymizing of the data before submitting. 
@longchihang, could you run : 
```
 ./scripts/collect-snmp-data.php
```
And change any line in the resulting file containing data "private". 

If you want to, you can also send me the file and I'll do the cleaning.

**Comment by longchihang** [comment]
I will run the script later, thanks！

**Comment by longchihang** [comment]
Hi, I have run the script. I attach those lab switches results with <private> mask. thanks!

[xos-10.x.y.31-private.snmprec.log](https://github.com/librenms/librenms/files/3002280/xos-10.x.y.31-private.snmprec.log)
[xos-10.x.y.32-private.snmprec.log](https://github.com/librenms/librenms/files/3002281/xos-10.x.y.32-private.snmprec.log)
[xos-10.x.y.33-private.snmprec.log](https://github.com/librenms/librenms/files/3002282/xos-10.x.y.33-private.snmprec.log)
[xos-10.x.y.34-private.snmprec.log](https://github.com/librenms/librenms/files/3002284/xos-10.x.y.34-private.snmprec.log)
[xos-10.x.y.35-private.snmprec.log](https://github.com/librenms/librenms/files/3002285/xos-10.x.y.35-private.snmprec.log)

**Comment by PipoCanaja** [comment]
Hello,
You have to keep the structure of the data. If you change a mac address for instance, you have to keep a valid mac address. If not, the snmp simulator will fail. 
So please use only "private" in strings, and just change randomly one or 2 characters in mac adresses, 1 or 2 numbers in ip addresses, etc etc

**Comment by PipoCanaja** [comment]
Only one file is necessary (from one device which has at least 1 neighbour).

**Comment by longchihang** [comment]
@PipoCanaja , may I post the EXOS-VM test result instead? Because the lab environment result have much company information.

**Comment by longchihang** [comment]
Those files are my EXOS-VM result. 
[xos-192.168.181.100.snmprec.log](https://github.com/librenms/librenms/files/3014534/xos-192.168.181.100.snmprec.log)
[xos-192.168.181.101.snmprec.log](https://github.com/librenms/librenms/files/3014535/xos-192.168.181.101.snmprec.log)

ScreenShot090
ScreenShot091

**Comment by PipoCanaja** [comment]
Hi @longchihang 
Looks perfect. I'll merge this PR after the release (next week) and add the data right after. 
Thanx !

**Comment by longchihang** [comment]
@PipoCanaja, thank you !

**Comment by PipoCanaja** [comment]
Release done, let's merge this.

**Pull request merged**
