### PR TITLE
refactor: ntp apps

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

updated nicecase function for ntp server and client app

### CODE REVIEW

**Comment by crcro** [comment]
- ntp client app rewrite based on new shell script (agent PR #54):
   - added app in nicecase function
   - rewrite graph scripts to properly work with latest additions to apps.inc.php page
- ntp server app rewrite based on new shell script (agent PR #55, kept agent variant)
   - added app in nicecase function
   - rewrite graph scripts to properly work with latest additions to apps.inc.php page

**Comment by murrant** [comment]
Thanks, overall looks good.
The main concern I have is changing the extend name and rrd file names.  These changes will break existing installations.  Either need to keep the old names or migrate the rrd files to the new name.  You would need to notify users to edit their extend name in snmpd.conf...

**Comment by crcro** [comment]
I don't thing that there are valid graphs using old versions (i have tried the ntp server/client several months ago and they weren't working). Like my first release of nfs-stats i think that the old one should be removed as tehy are obsolete or non-functional.

**Comment by rbax-idx** [comment]
Might be worth making sure the ntpd stats that are built in to the mk_check script have been removed as well as they no longer work.

**Comment by murrant** [comment]
Can you remove https://github.com/librenms/librenms/blob/master/includes/polling/unix-agent.inc.php#L60

Then good to merge.

**Pull request merged**
