### PR TITLE
Laravel 8.x Shift

### PR DESCRIPTION
**Pull request by Jellyfrog**
This pull request includes the changes for upgrading to Laravel 8.x. Feel free to commit any additional changes to the `shift-35189` branch.

**Before merging**, you need to:

- Checkout the `shift-35189` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 8
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 streamlined the _Exception Handler_ into a single `register` method to make it easier to add custom logic around rendering or reporting errors within your application.

While this change is not required, Shift recommends comparing yours against the [Laravel 8.x version](https://github.com/laravel-shift/laravel-8.x/blob/master/app/Exceptions/Handler.php) as an opportunity to reduce code and be fully up-to-date.

**Comment by Jellyfrog** [comment]
:information_source: The `RouteServiceProvider` no longer prefixes the controller namespace by default in Laravel 8. While you may still set this property, you are encouraged to register your routes using static `::class` references.

You may automate the conversion to static class references using the [Shift Workbench](https://laravelshift.com/workbench).

**Comment by Jellyfrog** [comment]
:x: Laravel 8 condenses the `RouteServiceProvider` as well as configured the [new rate limiters](https://laravel.com/docs/8.x/routing#rate-limiting). Shift was unable to automate this change. You should compare yours against the [Laravel 8.x version](https://github.com/laravel-shift/laravel-8.x/blob/master/app/Providers/RouteServiceProvider.php) and merge any changes.

**Comment by Jellyfrog** [comment]
:warning: Shift found multiple model factory definitions in `database/factories/ModelFactory.php` which it may not have properly converted. To receive the full automation you must first split these into individual factories, then request a rerun. You may use the [Shift Workbench](https://laravelshift.com/workbench) to help separate your model factory.

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 introduced class based factories. Shift [automated this change](https://github.com/librenms/librenms/pull/12235/commits/b02efe75b29af27fdaeb41491aa4f2694130ed56?w=1). However, if you were using a community package for factories or other custom code, you should review your factories for additional changes.

If you encounter an issue, you may revert this commit and temporarily install the [laravel/legacy-factories](https://github.com/laravel/legacy-factories) package. You may then automate the conversion to class based factories using the [Shift Workbench](https://laravelshift.com/workbench).

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 added a `uuid` column to the `failed_jobs` table to support the new [job batching](https://laravel.com/docs/8.x/queues#job-batching) features.

If your application is currently using the `failed_jobs` table, you may generate a custom migration for this command by running:

```sh
php artisan make:migration AddUuidToFailedJobsTable
```

Then copy and paste the contents from [Shift's `AddUuidToFailedJobsTable` class](https://github.com/laravel-shift/laravel-8.x/blob/master/database/migrations/2020_09_08_000000_add_uuid_to_failed_jobs_table.php).

**Comment by Jellyfrog** [comment]
:information_source: Laravel 8 added a new ENV variable of `LOG_LEVEL`. While the log level is defaulted in the configuration, you may take this opportunity to set it accordingly in your environments.

**Comment by Jellyfrog** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables. This should make [maintaining your config files easier](https://jasonmccreary.me/articles/maintaining-laravel-config-files/).

You should [review this commit](https://github.com/librenms/librenms/pull/12235/commits/69a5e7a017d4ce25cdfeba7c2ab59437a4486c3b?w=1) for any additional customizations. If you have a lot of customizations, you may wish to undo this commit with `git revert` and make these [config file changes](https://github.com/laravel-shift/laravel-7.x/pull/1/commits/aff49348815635b46f7aa2e5c1d93504f3920bf6) manually.

**Comment by Jellyfrog** [comment]
:information_source: Shift [updated your dependencies](https://github.com/librenms/librenms/pull/12235/commits/0930579c9d1431023e2181959aac3a6a4f3ca59a?w=1) for Laravel 8. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 8.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling package incompatibilities.

**Comment by Jellyfrog** [comment]
:warning: Laravel 8 now requires PHPUnit 9 which made some configuration changes to its config file. You may automate these changes by running `vendor/bin/phpunit --migrate-configuration` or comparing your `phpunit.xml` to the [Laravel 8 version](https://github.com/laravel-shift/laravel-8.x/blob/master/phpunit.xml) and merging any changes.

**Comment by Jellyfrog** [comment]
:warning: The paginator now uses [Tailwind](https://tailwindcss.com/) for its default styling in Laravel 8. If you wish to continue using Bootstrap, you should add the following snippet to the `boot` method of your `AppServiceProvider`:

```php
\Illuminate\Pagination\Paginator::useBootstrap();
```

**Comment by Jellyfrog** [comment]
:tada: Congratulations, you're now running the latest version of Laravel.

The following _Shifts_ may be used ensure your application is fully upgraded and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automates many of the suggestions found by the [_Laravel Linter_](https://laravelshift.com/opinionated-laravel-way-shift) and other _Shifts_.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and unit tests for your application to give you a head start on testing.

You may run these _Shifts_ and stay upgraded forever as well by subscribing to a [Shifty Plans](https://laravelshift.com/shifty-plans).

**Comment by Jellyfrog** [comment]
@librenms/reviewers Need help testing this

**Comment by murrant** [comment]
Testing went fine here.  I'll test the update next.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-november-2020/14124/1

**Pull request merged**
