### PR TITLE
Fix Alert-Test Object.

### PR DESCRIPTION
**Pull request by f0o**
First step in getting the Test-Button to work correctly :)

### CODE REVIEW

**Comment by f0o** [comment]
Well... It doesnt yet work for some reason, I'll push some more commits in a bit

**Comment by f0o** [comment]
Works now.

**Comment by laf** [comment]
@f0o Can you confirm alerts are still issued so I can merge?

**Comment by f0o** [comment]
@laf I think this was your test correct?

```
Aug 27 16:22:46 1772 postfix/pickup[3532]: CC9931163: uid=33 from=<www-data>
Aug 27 16:22:46 1772 postfix/cleanup[4106]: CC9931163: message-id=<499816b2b94a51da56b4da9e247c97e1@1772.ci.librenms.org>
Aug 27 16:22:46 1772 postfix/qmgr[3533]: CC9931163: from=<www-data@ci.librenms.org>, size=543, nrcpt=1 (queue active)
Aug 27 16:22:51 1772 postfix/smtp[4108]: CC9931163: to=<f0o@librenms.org>, relay=mail.libertysys.com.au[118.208.129.235]:25, delay=5, delays=0.08/0.01/3.8/1.1, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 20274920F8)
Aug 27 16:22:51 1772 postfix/qmgr[3533]: CC9931163: removed
```

**Comment by f0o** [comment]
I've tested the test-button & alerts.php and both issue mails correctly to my mailbox.

**Comment by laf** [comment]
Yeah I hit it in the webui but realised it went to you :)

**Comment by anderiv** [comment]
I just updated to the latest commit on master, and verified that the button is indeed working. Thanks!

**Comment by arrmo** [comment]
Hi,

Sorry, this still isn't working for me. I do get alerts every 5 minutes - so all the settings are correct. But if I press the Test Transport button ... nothing happens, no email. But wait 5 minutes, and the alerts are sent as is normal.

Thoughts? BTW, I'm on version 2728bca.

Thanks!

**Pull request merged**
