### PR TITLE
Improved Infinera Groove discovery

### PR DESCRIPTION
**Pull request by nickhilliard**
- add support for 3.0.1 and prior versions

- add support for subports and fibre-channel

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
@nickhilliard Thanx for your PR. 
Could you also collect all test data (including the one covered by your change with interfaces and subinterfaces) so that the tests will be more accurate in the future ? And could you please run save-test-data.php as described in the doc to create the json file ? 
Thanx

**Comment by nickhilliard** [comment]
@PipoCanaja sorry about this, but i have no reliable / useful way of adding this test data at the moment.  The devices which have the subinterfaces are running prerelease software with a slightly messed up snmp implementation and the upgrade procedure is outside my control. The patch to `infinera-groove.snmprec` in this pull request accurately reflects production software from devices which don't have subinterface capability. If the other devices get upgraded at some stage, I'll update `infinera-groove.snmprec` with a more complete config.

**Comment by PipoCanaja** [comment]
OK. We can then proceed this PR. Please submit the tests as soon as you get a chance to.

**Comment by PipoCanaja** [comment]
Quick style upgrade for to make Codeclimate happy again.

**Pull request merged**
