### PR TITLE
Change Cisco UCM category from tele to telephony

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

I think tele doesn't mean much.

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this, to change a type you will need to also submit a notification that this is changing: https://github.com/librenms/librenms.github.io/pull/83

However it will also need more work doing, tele at the moment must be broke but it also needs at least something in includes/definitions.inc.php:

```
$config['device_types'][$i]['text'] = 'Printers';
$config['device_types'][$i]['type'] = 'printer';
$config['device_types'][$i]['icon'] = 'printer.png';
```

As an example.

**Comment by laf** [comment]
Thanks @aldemira. This just needs the notification now adding, let us know when that's been done.

**Comment by aldemira** [comment]
I'm sorry I couldn't get what you mean by notifications?

**Comment by adaniels21487** [comment]
I would prefer this changed to 'collaboration' to be consistent with: Acano, Expressway, VC Endpoints and TPS.

**Comment by laf** [comment]
@aldemira What do you think?

@adaniels21487 If we do stick with that then it needs a group definition like this PR has, that looks to be missed when collaboration was added.

**Comment by aldemira** [comment]
I'm fine with that as long as it's not "Tele". So shall I update the code then?

**Comment by laf** [comment]
@aldemira Yes please, I'll do the notification once you have.

**Comment by laf** [comment]
Ok, the notification has gone out. Will merge Monday 10th.

**Pull request merged**
