### PR TITLE
Fix normal users UI widget AlertLog Stats

### PR DESCRIPTION
**Pull request by Calvario**
Please give a short description what your pull request is for

For a "normal" user, the widget is empty.
The new code use the same logic as implemented on alert & alert log widget for user authorizations on device_id.

Inspiration : https://github.com/librenms/librenms/blob/master/includes/html/table/alertlog.inc.php#L49

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
LGTM, but unfortunately using deprecated methods.

**Comment by Calvario** [comment]
Indeed, it's to maintain the same code logic as the other HTML tables that we have.
In another PR I could check how to change all of them to the new format.

**Comment by murrant** [comment]
You can add an exclusion for this for now.

**Comment by Calvario** [comment]
@murrant exclusion added

**Review by laf — APPROVED** [review]
LGTM

**Pull request merged**
