### PR TITLE
Add detection of additions HP ProCurve units

### PR DESCRIPTION
**Pull request by SaaldjorMike**
#1240

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
@laf Let me know if you want me to remove the old ProCurve check, but as long as I only have access to one HP devices I dont know if this is wise.

**Comment by laf** [comment]
Just one question, do you need to escape the . in [0-9.]? as it is does that not match a charcter?

Leave the current procurve check in thought.

**Comment by SaaldjorMike** [comment]
@laf From a few searches, I found that the dot has no special meaning within the square brackets. Maybe someone else wants to confirm this before merging?

**Comment by paulgear** [comment]
@SaaldjorMike correct - inside [], a . has no special meaning.

**Pull request merged**
