### PR TITLE
Added docs to utilise distro script

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully.

[x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)

[x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by murrant** [comment]
Not exactly where I'd put it but this is fine.

**Comment by laf** [comment]
Do you mean the location of /usr/bin/distro or the location within the docs?

**Comment by murrant** [comment]
location in the docs

**Comment by laf** [comment]
Happy to move it, where do you think it should go?

**Comment by laf** [comment]
bump

**Comment by murrant** [comment]
Couldn't think of a better place for now 😃

**Pull request merged**
