### PR TITLE
Added Perle OS Support for IOLAN SCS

### PR DESCRIPTION
**Pull request by esundberg**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by esundberg** [comment]
Note the snmpsim file is named perle_iolan_scs.snmprec there was already a perle.snmprec for another device

**Comment by esundberg** [comment]
I realize this might of been a mistake to put the snmprec file as perle_iolan_scs.snmprec when the os is call perle

How do you want me to handle this? Create a new device call perle_iolan_scs?

**Comment by PipoCanaja** [comment]
Hi @esundberg 
Thanx for your PR. First step would be to ensure that only the files linked to this perle change are added to the PR. Could you please correct the permissions so that the other files do not get added ? 

In order to get the original files, you can do :
```
git pull upstream bootstrap/cache/.gitignore 
git pull upstream includes/definitions/discovery/perle.yaml
git pull upstream logs/.gitignore
git pull upstream rrd/.gitignore 
git pull upstream storage/app/.gitignore 
git pull upstream storage/app/public/.gitignore 
git pull upstream storage/debugbar/.gitignore 
git pull upstream storage/framework/cache/.gitignore  
git pull upstream storage/framework/cache/data/.gitignore  
git pull upstream storage/framework/sessions/.gitignore  
git pull upstream storage/framework/testing/.gitignore  
git pull upstream storage/framework/views/.gitignore  
git pull upstream storage/logs/.gitignore  
```

For the discovery itself, I would only keep the sysObjectID and get rid of the sysDescr. 1966 includes all Perle devices anyway.

**Comment by esundberg** [comment]
@PipoCanaja 

I am getting a git error when i try to fix the .gitignore issue. 

librenms@librenms-devel:~$ git pull upstream bootstrap/cache/.gitignore
fatal: Invalid refspec 'bootstrap/cache/.gitignore'

----

So the sysdesc was existing, it looks like someone previous added support for the perle MCR MGT:
https://www.perle.com/downloads/software/media-converter/perle-mcr-mgt-unix.mib

The device I am adding is Perle IOLAN SCS
https://www.perle.com/downloads/software/iolan/perle-sds.mib

I am not a MIB expert, but it looks like both use the same SNMP Enterprise object Identifier 1966.
perle OBJECT IDENTIFIER ::= { enterprises 1966 }

I think the we might be able to do this to catch there two different models with the folllow, but I want verify with you guys first.
Remove sysDescr section
- sysObjectID:
- .1.3.6.1.4.1.1966.12  #Perle IOLAN SCS
- .1.3.6.1.4.1.1966.20  #Perle MCR-MGT

**Comment by PipoCanaja** [comment]
Depending on what sensors,etc you add later, you might need to split perle into perle-mcr and perle-iolan if they are too different. 
But for the time being, I would suggest to match ".1.3.6.1.4.1.1966." directly which would identify all perle devices, whatever their model is. From there, the existing test data for perle MCR and the replies from your perle-iolan will help us decide if we have to split or not.

**Comment by PipoCanaja** [comment]
Could you remove the sysDescr part ? That should help Travis with the YAML validity check.

**Comment by PipoCanaja** [comment]
I had to restore the sysDescr check cause the actual Perle MCR testdata relies on it to succeed. Looks better now.

**Pull request merged**
