### PR TITLE
Add MIB for CoolIT's liquid cooling units

### PR DESCRIPTION
**Pull request by cubranic**
Source: https://www.coolitsystems.com/index.php/data-sheets/category/8-software.html?download=10:rack-dclc-mib

### CODE REVIEW

**Comment by laf** [comment]
This mib won't be used, what's the reason for adding it in?

**Comment by cubranic** [comment]
Given the large collection of MIBs in the repo, I thought you'd welcome having this one too. It's for CoolIT cooling units.

**Comment by laf** [comment]
It's not about welcoming it or not, it's about that adding the mib has no benefit, code has to be written to use it so unless you've got some additional features you want adding which make use of the mib then their is no point in adding the file.

**Comment by cubranic** [comment]
closing

**Pull request closed without merging**
