### PR TITLE
Basic support for OpenBSD PF states

### PR DESCRIPTION
**Pull request by dagmartin**
This adds graphs for PF firewall state table on OpenBSD (might apply to FreeBSD as well, have not tested)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ X ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Perhaps you should drop openbsd_ from the graph names?

**Comment by dagmartin** [comment]
I wasn't really sure about the naming convention, most other related graphs I looked at seemed to have the vendor name in the filename (panos, fortios, etc.) and just "pf" might seem a bit generic? Since I've only tested this against OpenBSD I thought it made sense to name the files like that, but I'm happy to change if that is desired.

**Comment by murrant** [comment]
@dagmartin even if the data collection is different, won't the data and graphs be the same?

**Comment by dagmartin** [comment]
That's true. I've removed the openbsd prefix from the files.

**Pull request merged**
