### PR TITLE
Add composer back to the CentOS install docs

### PR DESCRIPTION
**Pull request by murrant**
This is for CentOS 7, not CentOS 6...

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by davama** [comment]
Not to throw a wrench here but `composer` does not install if using php7

CentOS Linux release 7.4.1708 (Core) 


```
 rpm -qa "*php*"
php71w-common-7.1.13-1.w7.x86_64
php71w-mcrypt-7.1.13-1.w7.x86_64
php71w-fpm-7.1.13-1.w7.x86_64
php71w-process-7.1.13-1.w7.x86_64
php71w-xml-7.1.13-1.w7.x86_64
php71w-ldap-7.1.13-1.w7.x86_64
php71w-mysql-7.1.13-1.w7.x86_64
php71w-cli-7.1.13-1.w7.x86_64
mod_php71w-7.1.13-1.w7.x86_64
php71w-pdo-7.1.13-1.w7.x86_64
php71w-gd-7.1.13-1.w7.x86_64
php71w-snmp-7.1.13-1.w7.x86_64
```
```
[root@librenms-lab ~]# yum install composer
Loaded plugins: fastestmirror
extras                                                                                                         | 3.4 kB  00:00:00     
mongodb-org-3.6                                                                                                | 2.4 kB  00:00:00     
updates                                                                                                        | 3.4 kB  00:00:00     
webtatic                                                                                                       | 3.6 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: mirror.umd.edu
 * epel: mirror.cs.princeton.edu
 * extras: mirror.metrocast.net
 * updates: mirror.datto.com
 * webtatic: us-east.repo.webtatic.com
Resolving Dependencies
--> Running transaction check
---> Package composer.noarch 0:1.6.2-1.el7 will be installed
--> Processing Dependency: php-composer(composer/ca-bundle) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(composer/semver) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(composer/spdx-licenses) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(psr/log) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(seld/cli-prompt) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(seld/jsonlint) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(seld/phar-utils) < 2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-PsrLog >= 1.0.0-8 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(composer/ca-bundle) >= 1.0 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(composer/semver) >= 1.0 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(composer/spdx-licenses) >= 1.2 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(psr/log) >= 1.0 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(seld/cli-prompt) >= 1.0 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(seld/jsonlint) >= 1.4 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(seld/phar-utils) >= 1.0 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-seld-cli-prompt >= 1.0.0-3 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-seld-phar-utils >= 1.0.1 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-composer(fedora/autoloader) for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-intl for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-justinrainbow-json-schema5 for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-mbstring for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-symfony-console for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-symfony-filesystem for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-symfony-finder for package: composer-1.6.2-1.el7.noarch
--> Processing Dependency: php-symfony-process for package: composer-1.6.2-1.el7.noarch
--> Running transaction check
---> Package php-PsrLog.noarch 0:1.0.2-2.el7 will be installed
---> Package php-composer-ca-bundle.noarch 0:1.0.2-1.el7 will be installed
--> Processing Dependency: php-composer(symfony/class-loader) for package: php-composer-ca-bundle-1.0.2-1.el7.noarch
---> Package php-composer-semver.noarch 0:1.4.2-1.el7 will be installed
---> Package php-composer-spdx-licenses.noarch 0:1.2.0-1.el7 will be installed
---> Package php-fedora-autoloader.noarch 0:1.0.0-1.el7 will be installed
---> Package php-jsonlint.noarch 0:1.6.1-1.el7 will be installed
---> Package php-justinrainbow-json-schema5.noarch 0:5.2.6-1.el7 will be installed
---> Package php-seld-cli-prompt.noarch 0:1.0.3-1.el7 will be installed
---> Package php-seld-phar-utils.noarch 0:1.0.1-1.el7 will be installed
---> Package php-symfony-console.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/event-dispatcher) = 2.8.12 for package: php-symfony-console-2.8.12-2.el7.noarch
---> Package php-symfony-filesystem.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-symfony-common = 2.8.12-2.el7 for package: php-symfony-filesystem-2.8.12-2.el7.noarch
---> Package php-symfony-finder.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-process.noarch 0:2.8.12-2.el7 will be installed
---> Package php72w-intl.x86_64 0:7.2.1-1.w7 will be installed
--> Processing Dependency: php72w-common(x86-64) = 7.2.1-1.w7 for package: php72w-intl-7.2.1-1.w7.x86_64
--> Processing Dependency: libicuuc.so.50()(64bit) for package: php72w-intl-7.2.1-1.w7.x86_64
--> Processing Dependency: libicuio.so.50()(64bit) for package: php72w-intl-7.2.1-1.w7.x86_64
--> Processing Dependency: libicui18n.so.50()(64bit) for package: php72w-intl-7.2.1-1.w7.x86_64
--> Processing Dependency: libicudata.so.50()(64bit) for package: php72w-intl-7.2.1-1.w7.x86_64
---> Package php72w-mbstring.x86_64 0:7.2.1-1.w7 will be installed
--> Running transaction check
---> Package libicu.x86_64 0:50.1.2-15.el7 will be installed
---> Package php-symfony-class-loader.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-common.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-event-dispatcher.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/dependency-injection) = 2.8.12 for package: php-symfony-event-dispatcher-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/http-kernel) = 2.8.12 for package: php-symfony-event-dispatcher-2.8.12-2.el7.noarch
---> Package php72w-common.x86_64 0:7.2.1-1.w7 will be installed
--> Running transaction check
---> Package php-symfony-dependency-injection.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/config) = 2.8.12 for package: php-symfony-dependency-injection-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/expression-language) = 2.8.12 for package: php-symfony-dependency-injection-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/yaml) = 2.8.12 for package: php-symfony-dependency-injection-2.8.12-2.el7.noarch
---> Package php-symfony-http-kernel.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/browser-kit) = 2.8.12 for package: php-symfony-http-kernel-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/debug) = 2.8.12 for package: php-symfony-http-kernel-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/http-foundation) = 2.8.12 for package: php-symfony-http-kernel-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/var-dumper) = 2.8.12 for package: php-symfony-http-kernel-2.8.12-2.el7.noarch
--> Running transaction check
---> Package php-symfony-browser-kit.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/dom-crawler) = 2.8.12 for package: php-symfony-browser-kit-2.8.12-2.el7.noarch
---> Package php-symfony-config.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-debug.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-expression-language.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-http-foundation.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/polyfill-php54) < 2.0 for package: php-symfony-http-foundation-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/polyfill-php55) < 2.0 for package: php-symfony-http-foundation-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/polyfill-php54) >= 1.0 for package: php-symfony-http-foundation-2.8.12-2.el7.noarch
--> Processing Dependency: php-composer(symfony/polyfill-php55) >= 1.0 for package: php-symfony-http-foundation-2.8.12-2.el7.noarch
---> Package php-symfony-var-dumper.noarch 0:2.8.12-2.el7 will be installed
---> Package php-symfony-yaml.noarch 0:2.8.12-2.el7 will be installed
--> Running transaction check
---> Package php-symfony-dom-crawler.noarch 0:2.8.12-2.el7 will be installed
--> Processing Dependency: php-composer(symfony/css-selector) = 2.8.12 for package: php-symfony-dom-crawler-2.8.12-2.el7.noarch
---> Package php-symfony-polyfill.noarch 0:1.5.0-1.el7 will be installed
--> Processing Dependency: php-composer(ircmaxell/password-compat) < 2.0 for package: php-symfony-polyfill-1.5.0-1.el7.noarch
--> Processing Dependency: php-composer(paragonie/random_compat) < 3.0 for package: php-symfony-polyfill-1.5.0-1.el7.noarch
--> Processing Dependency: php-composer(ircmaxell/password-compat) >= 1.0 for package: php-symfony-polyfill-1.5.0-1.el7.noarch
--> Processing Dependency: php-composer(paragonie/random_compat) >= 1.0 for package: php-symfony-polyfill-1.5.0-1.el7.noarch
--> Running transaction check
---> Package php-paragonie-random-compat.noarch 0:1.4.1-1.el7 will be installed
---> Package php-password-compat.noarch 0:1.0.4-1.el7 will be installed
---> Package php-symfony-css-selector.noarch 0:2.8.12-2.el7 will be installed
--> Processing Conflict: php72w-common-7.2.1-1.w7.x86_64 conflicts php-common < 7.2
--> Finished Dependency Resolution
Error: php72w-common conflicts with php71w-common-7.1.13-1.w7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

How I installed it

```
wget https://getcomposer.org/composer.phar
chmod +x composer.phar
mv composer.phar /usr/local/bin/composer
```
```
./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-32-g913d6dc
DB Schema | 234
PHP       | 7.1.13
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX] You can fix this with ./scripts/github-remove
	Modified Files:
	 html/includes/hostbox-menu.inc.php
	 html/includes/table/devices.inc.php
	 html/pages/device.inc.php
```

**Comment by murrant** [comment]
@davama did you notice I updated the install documents to install PHP 7.2?

**Comment by davama** [comment]
>@davama did you notice I updated the install documents to install PHP 7.2?

....ooh :open_mouth: 

Gonna give it a go with 7.2
Thanks

**Comment by laf** [comment]
Just tested on 7.2, seems good to go to me.

**Pull request merged**
