### PR TITLE
fix: rfc1628 state sensor translations

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7416)

### CODE REVIEW

**Comment by f0o** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librenms/librenms/7416#-:-KvSVDFIg-sbCfWW4HyJ:bnfp4nl)*

**Comment by f0o** [comment]
Still getting used to this reviewable thing

**Comment by murrant** [comment]
no worries, I've barely looked at it ;-)

**Comment by f0o** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/librenms/librenms/7416#-:-KvSVS0ON2F56xVtRUhv:bb6ywmx)*

**Comment by laf** [comment]
Ignore reviewable. I got recommended it but thought it was just a me thing. I'll remove it.

**Comment by murrant** [comment]
@laf it doesn't bother me, I just haven't had the time to give it a look.  If it is useful, keep using it.

**Comment by FTBZ** [comment]
I think it's working, tested on Generex and APC/MGE.

**Pull request merged**
