### PR TITLE
Created a page to show all known VMs

### PR DESCRIPTION
**Pull request by aldemira**
I've created single page which shows all VMs known to LibreNMS. Also I thought not everyone would like to enable this option so it requires $config['show_allvm_list'] = true; in config.php to be enabled as a menu item (under devices)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
I'd suggest counting the entries in the vminfo table instead of adding a config option.

**Comment by aldemira** [comment]
@laf TBH I copied the SQL query from device dependencies ajax call. I'm going to fix that in a separate PR as well. 
screen shot 2018-05-10 at 13 03 29
screen shot 2018-05-10 at 13 28 24

**Comment by laf** [comment]
@aldemira Actually would be good if you could add a license to the new file + update the one you did add using this template; https://docs.librenms.org/#Developing/Licensing/

**Comment by laf** [comment]
@aldemira I've refactored the code a little bit. Can you test this patch and push it to this PR please:

https://p.libren.ms/view/3a29c5c3

**Pull request merged**
