### PR TITLE
Revert "Alert Detail Ping Latency"

### PR DESCRIPTION
**Pull request by PipoCanaja**
Reverts librenms/librenms#11140

### CODE REVIEW

**Comment by PipoCanaja** [comment]
There is no way to define when (and how) to display properly this message. 
A solution could be to generate this "short text", using templates (exactly like the alert transports). 
Each alert rule would include a template and generate the exact needed text.

**Comment by SourceDoctor** [comment]
@PipoCanaja 
i recognized it myself this morning. I'll take a look on it

**Comment by SourceDoctor** [comment]
@PipoCanaja should i approve this for you so it can be removed, till i find a suitable way?

**Comment by PipoCanaja** [comment]
Yep, let's merge this first, and think about a better way. Basically, you have no way to know at this position in the code, what alert the user has configured. And the ping latency is available in every alert structure. 
Only building this alert description based on the alert rule would solve this, and this is a much bigger change.

**Pull request merged**
