### PR TITLE
device: Implement Allied Telesis Environmental Monitoring

### PR DESCRIPTION
**Pull request by mattie47**
Initial patch to monitor:
- fans
- temperature

State:
- fans
- temperature

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by mattie47** [comment]
I'm still working on this.... More to come.

**Comment by laf** [comment]
Let us know when it's done and we can remove the blocker tag and review.

**Comment by mattie47** [comment]
@laf  Ready. 

This implements basic monitoring of:

- Fan Speed and State
- Voltage Speed and State
- Temperature and State
- Power Supply State

I may look at doing things like pluggable monitoring later but the above additions are good in their current state. Have tested on most platforms.

**Comment by murrant** [comment]
@mattie47 Looks good would be great if you added test data for this:
https://docs.librenms.org/Developing/os/Test-Units/#capturing-test-data

**Comment by mattie47** [comment]
@murrant  Thanks. Sorry, I didn't realise I need to do that again. 

I've updated the test data, but I possibly still haven't done it in the desired json format. I'm still having issues with that:

```
librenms@librenmsdev:~$ nano /opt/librenms/tests/snmpsim/awplus.snmprec
librenms@librenmsdev:~$ ./scripts/save-test-data.php -o awplus -m sensors
Starting snmpsim listening on 127.1.6.1:1161... 
OS: awplus
Module: sensors

awplus: Could not connect to 127.1.6.1, please check the snmp details and snmp reachability

librenms@librenmsdev:~$ ./scripts/pre-commit.php -p -u
Running unit tests... 
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_TextUI_Command' not found in /opt/librenms/vendor/phpunit/phpunit/phpunit:52
Stack trace:
#0 {main}
  thrown in /opt/librenms/vendor/phpunit/phpunit/phpunit on line 52
```

**Comment by murrant** [comment]
@mattie47 I've checked the snmprec and it doesn't seem to contain data for the new sensors.

You may have a corrupt snmprec file or something.

Try running `./scripts/collect-snmp-data.php --snmpsim`

**Comment by mattie47** [comment]
@murrant 

Thanks for that. 

I came back today and had a look at this again and realised I'd managed to install an older version of snmpsim (snmpsim-0.2.4) which is why I never got the tests working properly...

Having now installed it via pip I'll get the test data done properly...

**Comment by mattie47** [comment]
@murrant 

Sorry this has taken a while...

I think I've got everything right now, and I've also updated the snmprec data for all the sensors and processors. I think it's all correct :-)

Thanks,

Matt

**Pull request merged**
