### PR TITLE
Fix arp-search search

### PR DESCRIPTION
**Pull request by Jellyfrog**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@murrant you and @laf broke it here actually; https://github.com/librenms/librenms/pull/6288/files#diff-91859f4a89fcb4804d5b1d07912894e6R100 Seems like a copy paste error since the change doesn't make sense.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/production-error-argument-1-passed-to-librenms-cache-device-get/13104/2

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ajax-table-php-throwing-error/12994/8

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
Hmm, definitely didn't break it then, I've used it since then, but sure the code change wasn't right.

**Comment by Jellyfrog** [comment]
> Hmm, definitely didn't break it then, I've used it since then, but sure the code change wasn't right.

it actually broke... you just didnt see it, check the description in https://github.com/librenms/librenms/pull/12076 :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
