### PR TITLE
Run daily.sh as the user set by $config['user']

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

This will give a password prompt when not running as that user or root
Use the full path when re-calling the script
DIR_LIBRENMS > LIBRENMS_DIR

### CODE REVIEW

**Comment by Gorian** [comment]
Looks good, but I would move 

```bash
if [ "$EUID" -ne "$LIBRENMS_USER_ID" -a "$LIBRENMS_USER" != "root" ]; then
     su -l $LIBRENMS_USER -c "$DAILY_SCRIPT $@"
     exit;
fi
```

to be INSIDE main

```bash
main () {
    local arg="$1";

    if [ "$EUID" -ne "$LIBRENMS_USER_ID" -a "$LIBRENMS_USER" != "root" ]; then
        su -l $LIBRENMS_USER -c "$DAILY_SCRIPT $@"
        exit;
    fi
    
    cd ${LIBRENMS_DIR};
...
```

also, I'd say, use MORE quotes, and use [`[[` vs `[`](http://mywiki.wooledge.org/BashFAQ/031), and I think we refactored this script once to change all references of "-ne" to "!=", so we should use that.

Also, it's good to be in the habit of writing your variables in bash in the form of [`${var}`](http://stackoverflow.com/questions/8748831/when-do-we-need-curly-braces-in-variables-using-bash). Any variable operations, from variable next to a string `${i}foo` vs `$ifoo` (the latter of which becomes the variable `$ifoo`, no `$i`), as well as working with array and manipulating variables, `${foo[@]}` for all elements of an array, and `${foo^^} to convert a string to all uppercase

```bash
main () {
    local arg="$1";

    if [[ "${EUID}" != "${LIBRENMS_USER_ID}" ]] &&
       [[ "${LIBRENMS_USER}" != "root" ]]; then
        su -l "${LIBRENMS_USER}" -c "${DAILY_SCRIPT} $@";
        exit;
    fi

    cd ${LIBRENMS_DIR};
 ...
```

**Comment by murrant** [comment]
@Gorian I've always wondered why you put the semi-colin at the end of the line, even though it is only needed when you have multiple statements on the same line.

It feels like saying end of statement end of statement.

**Comment by murrant** [comment]
Made some changes, I think this is in good shape to merge.

**Comment by Gorian** [comment]
@murrant I believe it's usually a style choice. Good practice more than anything. If you make sure to end each line with a semi-colon ala C, then you can avoid some issues in code later where something might continue to a new line or do something you don't want. I just tend to be more explicit than implicit in my coding. But, if you are adding new code to the existing code, better to try and make it all homogeneous :) Also, if you are writing a script, a newline is just a single (or two) characters (\n or \n\r :P ), so there isn't much reason to to generally use multiple statements on a line - I'm not a big fan of code golf.

@laf shouldn't cause any major issues, but [this](http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo) may be useful as to why I chose to use `printf` instead of `echo`

**Pull request merged**
