### PR TITLE
WIP PR8259: Add health sensors for DNOS9

### LINKED ISSUE #8259: DELL S4048-ON/S3048-ON healthstate-sensors missing
discovery:
https://defuse.ca/b/ITa6jJXL
poller:
https://defuse.ca/b/VSmXFh0A
snmpbulkwalk:
https://defuse.ca/b/Qz4NUCIu

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
====================================
Component | Version
--------- | -------
LibreNMS  | 1.36-69-g2a4dd70
DB Schema | 235
PHP       | 7.0.25
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

### PR DESCRIPTION
**Pull request by cloudprodz**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

I've made a template for the sensors but it needs some fixing. snmp-data and debug output uploaded in the issue below.
fixes #8259

### CODE REVIEW

**Comment by murrant** [comment]
@cloudprodz Great, now you need to run ./scripts/collect-snmp-data.php and add the snmprec file to this PR.

https://docs.librenms.org/Developing/os/Test-Units/#capturing-test-data

**Comment by laf** [comment]
@cloudprodz Can you sign the CLA as well please. We can't merge until you've done this.

**Comment by laf** [comment]
I've sorted out all the test files. Just need you to sign the CLA now @cloudprodz

**Comment by cloudprodz** [comment]
Signed it. I was having some problems with the polling as posted in the PR so I'm not sure if it's ready for merging, could someone check it first please? https://github.com/librenms/librenms/issues/8259#issuecomment-401023554

**Comment by laf** [comment]
Judging from your comment and the data, it looks like you might not be able to use the yaml file and will have to port this to php :(

**Comment by laf** [comment]
@cloudprodz Any update on this?

**Comment by laf** [comment]
@cloudprodz Feel free to reply to this with an update and we can re-open.

**Pull request closed without merging**
