### PR TITLE
Added AAA online count polling and graph

### PR DESCRIPTION
**Pull request by alangregory**
Added basic AAA counter for routerOs and graph template for dashboard

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
That polling file won't just run.

However I'm not sure that this should be it's own poller module anyway.

./includes/polling/os/panos.inc.php Does something similar, probably worth following the same process.

**Comment by laf** [comment]
As a side note, the code has failed validation checks, see http://docs.librenms.org/Developing/Validating-Code/

**Comment by alangregory** [comment]
Thank's, this branch is a bit old, i'll check.

**Comment by alangregory** [comment]
And about AAA, I think it could be a poller module, since it's a multi-vendor  feature.

**Comment by laf** [comment]
Tagging @librenms/reviewers 

I don't think AAA warrants a polling module of it's own, it's not big enough to need it. I think the best solution is to do as has been done before for session based support.

**Comment by alangregory** [comment]
Understood. Can you point me a sample to start with ?

**Comment by laf** [comment]
`./includes/polling/os/panos.inc.php` :)

Look for sessions in that, it does the same thing basically.

**Comment by laf** [comment]
@alangregory bump

**Comment by laf** [comment]
Feel free to re-open or open a new PR.

**Comment by alangregory** [comment]
@laf, sorry, was busy last days, i'll open a new PR later when it's ready.

**Pull request closed without merging**
