### PR TITLE
docs: Updated index page to make it look more attractive

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Looks like:

image

### CODE REVIEW

**Comment by laf** [comment]
Yes it's html based rather than markdown but we shouldn't need to change this very often. It's just a nicer way to intro people to some quick win documents without a wall of text.

**Comment by murrant** [comment]
Looks great.  Just a nitpick, the shade of red looks a little off since there is already red on the page.  Don't make it the same shade of red though 😀.

**Comment by laf** [comment]
It's just using bootstrap color, the red in the menu is a little too bright though so wasn't sure it was the best choice.

**Comment by murrant** [comment]
Looks good for now, can tweak later if anyone has a better idea.

**Comment by huegelc** [comment]
Looks good indeed. As you mentioned the red in the navbar:

librenms_docs

looks like if you align both colors.

**Comment by laf** [comment]
The red from the nav is taken from the webui and main website which in turn are taken from the logo as an fyi

**Comment by huegelc** [comment]
OK, but this doesn´t look bad either;):

librenms_docs

```
.text-danger {
    color: #da223a;
}
```

**Comment by laf** [comment]
Just find it a bit bright that's all

**Comment by murrant** [comment]
I agree, to some extent, but like I said, I'm open to a better color :)

**Pull request merged**
