### PR TITLE
Reduce default thread count on small systems

### PR DESCRIPTION
**Pull request by brianegge**
Default script options kills my raspberrypi.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by brianegge** [comment]
It's a "run twice" script. The first time you run it your machine fails, the second time you remember to specify a thread count. 

Agreed that process is not really CPU bound. It's a memory issue more than CPU, but estimating the memory required and memory available is more difficult. A better estimate can be done with:
```mem = psutil.virtual_memory
  free = mem.free + mem.cached
  threads = free / _memory_per_fork```
But you have to know the memory needed per fork. 

The command line switches only help before you have an issue. If you know in advance you are scanning a large network and have the resources, then it's easy to scale up. Otherwise the default would be safer and more stable on most systems.

**Comment by murrant** [comment]
I'm not denying this is a pain.  I just think you need a solution that doesn't punish most of our users with slower runtimes.  Many won't look to see that there is even a tunable and just wait for it to run.

**Comment by PipoCanaja** [comment]
May be you should match the RaspberryPi (or a little bit better, ARM CPUs) directly in the script, and only apply this thread limitation in that case. I cannot see any more "generic" way for a formula that would not punish bigger CPUs by just looking at standard values in cpuinfo.

**Comment by murrant** [comment]
He said the main issue is memory, not cpu actually.

**Comment by laf** [comment]
I'd vote to keep this at a high value to cover the majority of users.

Could add a config.php option to allow users to set a default?

**Comment by brianegge** [comment]
How many cores do most users have? I have 28-32 on my servers but only 4 on my rpi. 

I could change this to estimate based on your available memory. 

-Brian

**Comment by murrant** [comment]
Yes, changing this to check the actual thing that constrains it would help a lot.

**Comment by murrant** [comment]
Feel free to re-open if you can come up with a good way to limit the default thread count.

**Pull request closed without merging**
