### PR TITLE
device: Added state sensor support for HPE MSA devices

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7719 

Untested as the walk in the issue didn't have the data but from the MIB, it _should_ be ok.

### CODE REVIEW

**Comment by kkrumm1** [comment]
i can try the walk again if you like

**Comment by kkrumm1** [comment]
Discovery debug: https://gist.github.com/kkrumm1/cfd12f527d3bc50f22d28579e3d697de
Poller Debug: https://gist.github.com/kkrumm1/63e55d41e3b4e5616c2180edd546bc5a

image
 showing 0#

**Comment by laf** [comment]
`' .....Wz........'` wth!

I'll need the full snmpwalk from this device to test further. Add ` .1.3.6.1.3.94.1.` to the end of the walk command rather than `.`

**Comment by kkrumm1** [comment]
https://gist.github.com/kkrumm1/2bec6658f35d94863e58789336dead19

**Comment by kkrumm1** [comment]
@laf try this one https://gist.github.com/kkrumm1/68b7a88b4c31818dcc81fcd66568f577#file-hp-msa-snmp-walk-take-2

**Comment by murrant** [comment]
I feel like I mentioned this before but connUnitSensorTable -> connUnitSensorEntry
`INDEX { connUnitSensorUnitId, connUnitSensorIndex }`
connUnitSensorUnitId = `FcGlobalId ::= OCTET STRING (SIZE(16))`

So, the index contains a string, maybe the mib is out of date?

**Comment by laf** [comment]
@kkrumm1 do you have access to a newer mib? I can't find one online so not sure one exists.

**Comment by kkrumm1** [comment]
hmm let me check HPE website.

**Comment by kkrumm1** [comment]
@laf https://support.hpe.com/hpsc/swd/public/detail?swItemId=MTX_3f061bd4c08a4dbd977bf4a51d&swEnvOid=2025

https://gist.github.com/kkrumm1/fee7dc0e90e1e60e8fe11ca7773f4c4d#file-fcmgmt-mib-mib

**Comment by laf** [comment]
It's got an older date but seems to have more in it, save it to /opt/librenms/mibs/hp/FCMGMT-MIB with this patch applied and try a discovery again.

**Comment by kkrumm1** [comment]
dang still shows that Wz
debug info below
https://gist.github.com/kkrumm1/f22b6c6b3fb83ce4d6d84b8fed1d0b93
https://gist.github.com/kkrumm1/0894fcd62c0516d8608edc4786ec64f3#file-msa-poller-2

**Comment by murrant** [comment]
I'm pretty sure this is implemented as intended.  You could change the snmpflags.

**Comment by kkrumm1** [comment]
@murrant how do we add SNMPflags?

**Comment by laf** [comment]
> I'm pretty sure this is implemented as intended.

@murrant you mean the PR seems correct?

**Comment by murrant** [comment]
No, I mean the data seems correct, even if it is less than useful.

**Comment by murrant** [comment]
Set the snmp options to `-OQUse`  That should store the whole oid after as the index right?

**Comment by laf** [comment]
@kkrumm1 can you retry this patch please and post the output of `./discovery.php -h HOSTNAME -d -m sensors` if it doesn't work still please.

**Comment by murrant** [comment]
Oopsie, I missed the `-Ob` option above, please try with my correction @kkrumm1.

**Comment by kkrumm1** [comment]
@murrant @laf when i try and apply the patch i get this error on the mib 
image

**Comment by murrant** [comment]
@kkrumm1 you deleted the file?

**Comment by kkrumm1** [comment]
@murrant I think I did back when I was testing the mibs out. Should I add it back? and which directory?

**Comment by kkrumm1** [comment]
Progress yay! 

Looks like it added some 
image

But not all the other sensors show up in the web ui.

@laf @murrant https://p.libren.ms/view/8a82c31a

**Comment by laf** [comment]
Check logs/librenms.log after running it, lots of those sensors are trying to be added so I expect it's a restriction on the db.

**Comment by kkrumm1** [comment]
no errors in the log

**Comment by laf** [comment]
That's got lots of 

```
INSERT INTO `sensors`
```
Which says it's trying to add them. Run a few of those inserts to test.

**Comment by laf** [comment]
Yeah's the index size being too big.

**Comment by kkrumm1** [comment]
> Yeah's the index size being too big.

any way to fix this?

**Comment by laf** [comment]
Run this and see if it works for you:

`ALTER TABLE  `sensors` CHANGE  sensor_index sensor_index VARCHAR( 128 );`

**Comment by kkrumm1** [comment]
@laf that did the trick :) 

image

**Comment by laf** [comment]
Ace. I'm going to move that schema change to PR #7714 so we only deploy one schema change to sensors table.

**Pull request merged**
