### PR TITLE
Adding multi-processor support for Fortigate devices

### PR DESCRIPTION
**Pull request by rucarrol**
This support removes the single CPU graph added to the system hierarchy for Fortigate devices and adds support for discovering all CPUs/NPUs in the system. 

Tested on 60D, 140D, 1000C and 5001B on 5.0.X code train. 

Please let me know if there are any bugs to be ironed out.

### CODE REVIEW

**Comment by laf** [comment]
@rucarrol Thanks for PR.

How come you are dealing with the process in includes/polling/os/fortigate.inc.php? I'd have expected includes/polling/processors.inc.php to take care of that or at least a new file created in includes/polling/processors/.

Also as this is your master branch (bad idea :)) everytime you push commits you're adding them to this PR so we now have F5 MIBs included. Here's some info on a suggested work flow using git: http://docs.librenms.org/Developing/Using-Git/

**Comment by laf** [comment]
Bump

**Comment by rucarrol** [comment]
Hey @laf ! 

Should I nuke this PR and re-create it so that it's just the Fortigate CPU diff (And remove the extra polling code)? 

Cheers
/Ruairi

**Comment by laf** [comment]
Ideally yes but it's not necessary. You can remove the changes that aren't part of this PR then before doing a push you can merge all your commits into one and do a force push.

**Comment by rucarrol** [comment]
Lemme close this PR and make it purdy. Thanks for the tip! 

/Ruairi

**Pull request closed without merging**
