### PR TITLE
Fix bills api output for period=previous

### PR DESCRIPTION
**Pull request by Urth**
Include static fields from the bills table in the previous period output.
Check lowercase(bill_type) because the history table uses CDR and Quota.
Update SQL IF() because the bills table always uses lowercase.

Because of these changes the calculation of the fields allowed, used,
percent and overuse for period=previous is now enabled.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Urth** [comment]
It should be noted that there are still differences between the output for `period=` and `period=previous`.

With `period=`:
-  `bill_type` is `enum(cdr, quota)`

With `period=previous`:
- `bill_type` is `enum(CDR, Quota)`
- Includes the bill_history fields: bill_datefrom, bill_dateto, bill_hist_id, bill_overuse, bill_percent, bill_used, pdf, traf_in, traf_out, traf_total and updated.

I've opted to leave these as they are as these changes would be backwards incompatible. If you'd like to have the same output for both I'll be happy to make the changes accordingly.

**Comment by murrant** [comment]
What is with the SQL query changes?  The reformatting makes it hard to figure out what the change is.

**Comment by Urth** [comment]
With `period=previous` it adds the columns `bills.bill_autoadded, bills.bill_cdr, bills.bill_custid, bills.bill_day, bills.bill_quota, bills.bill_ref and bill_history.updated as bill_last_calc`.

With `period=` it changes formatting according to the guidelines.

**Comment by kzaykov** [comment]
I've got the following trying to call 'bills/?period=previous':
https://pastebin.com/3JQeGa3g

Might be due to 'null' or stale records
bils

**Comment by kzaykov** [comment]
nope, the thing is that we had some bills with CDR = 0

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-62-release-changelog-march-2020/11423/1

**Pull request merged**
