### PR TITLE
Added Nokia timos SFP RX/TX dbm sensors

### PR DESCRIPTION
**Pull request by craig-nokia**
Added the RX and TX dbm values for Fiber SFP's on Nokia Timos routers.

Note: Nokia follows the specifications for Management Interface for SFP+ (SFF-8472). Calculations for external calibration values are supported at this time.

The timos.json has been updated as it was missing quite a few sensors.

dbm
DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Test fails, https://travis-ci.com/github/librenms/librenms/jobs/381650223

**Comment by craig-nokia** [comment]
When I ran "./scripts/save-test-data.php -o timos -m sensors", it did not update the ifName correctly.  Replaced timos.json without using the switch "-m sensors"

**Comment by Jellyfrog** [comment]
you need to omit the `-m` argument

**Comment by craig-nokia** [comment]
The test data timos.snmprec was not changed as the MIB/DATA table was already captured for the interfaces.  I do not know how do I git force load a file that has not changed.

The original problem was when I generated the timos.json file the first time, I only did the sensors.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
