### PR TITLE
Add Universal Input Output support for APC

### PR DESCRIPTION
**Pull request by dennypage**
Circa 2009, with the Network Management Card version 2 (NMC2), APC moved environmental reporting to universalInputOutput (.1.3.6.1.4.1.318.1.1.25), superseding the iemConfig (.1.3.6.1.4.1.318.1.1.10.2.2) and iemStatus (.1.3.6.1.4.1.318.1.1.10.2.3) tables. The legacy iem tables were maintained for backward compatibility. With the introduction of the Network Management Cards version 3, the legacy iem tables are no longer maintained.

This PR adds support for universalInputOutput, covering both the NMC2 and NMC3.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by dennypage** [comment]
Snmp data is in the 2nd commit.

**Comment by Jellyfrog** [comment]
Missing json files

**Comment by dennypage** [comment]
Okay, following this:
```
After you have collected snmp data, run ./scripts/save-test-data.php with the --os (-o)
option to dump the post discovery and post poll database entries to json files. This step requires
snmpsim, if you are having issues, the maintainers may help you generate it from the snmprec
you created in the previous step
```
I've installed snmpsim, but am running into a problem trying to generate the json files.

The command I am using is
`./scripts/save-test-data.php -o apc -v smtl1000-nmc3 -m all`

The output is:
```
Starting snmpsim listening on 127.1.6.1:1161...

...

--- SNMP Engine configuration 
SNMPv3 EngineID: 0x80004fb8056d617276696e2fd66900 
  --- Data directories configuration 
  SNMPv3 Context Engine ID: 0x80004fb8056d617276696e2fd66900
  Scanning "/home/www/librenms.cococafe.com/tests/snmpsim/" directory for  *.dump, *.MVC, *.sapwalk, *.snmpwalk, *.snmprec data files...

...

    Configuring /home/www/librenms/tests/snmpsim/apc_smtl1000-nmc3.snmprec controller
    SNMPv1/2c community name: apc_smtl1000-nmc3 
    SNMPv3 Context Name: a7a88ad6d0391a3768c2d4d348d39b52 or apc_smtl1000-nmc3

...

  --- SNMPv3 USM configuration 
  SNMPv3 USM SecurityName: simulator 
  SNMPv3 USM authentication key: auctoritas, authentication protocol: MD5 
  SNMPv3 USM encryption (privacy) key: privatus, encryption protocol: DES 
  Maximum number of variable bindings in SNMP response: 64
  --- Transport configuration 
  Listening at UDP/IPv4 endpoint 127.1.6.1:1161, transport ID 1.3.6.1.6.1.1.0 
```


At this point the process seems to hang forever. I'm sure I am doing something wrong, it I'm just not seeing it. Can you offer some advice on how to move forward?

**Comment by dennypage** [comment]
Alternatively, would it be possible for someone else to generate the json files?

**Comment by dennypage** [comment]
I found the issue(s). The initial hang was due to a permissions problem. The second issue was that the first snmp query was being attempted before snmpsim had finished scanning and configuring all the snmprec data. This caused the query for SNMPv2-MIB::sysObjectID to time out, and as a result the test system wasn't correctly identified.

I've updated the PR with the generated json test data, and a fix for the save-test-data.php script.

**Comment by dennypage** [comment]
Hey all, I apologize for the stream of conscious nature of this PR. I finally have complete test data which passes all checks.

The issues I encountered were with the process of generating test data, and the operation of the test harness. In the end, I had to create a completely stand-alone instance of librenms (as opposed to using my production librenms instance) with polling disabled to properly create the test data files. I'm not sure why this was required, and would appreciate anyone enlightening me if they know.

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
