### PR TITLE
Removed ping + performance graphs and tab if skip ping check

### LINKED ISSUE #2174: Disable icmp graphs + performance when fping check disabled

### PR DESCRIPTION
**Pull request by laf**
Fix #2174 

This will now remove the icmp graph, performance tab and won't insert new perf data or rrd data for the same.

### CODE REVIEW

**Comment by laf** [comment]
https://scrutinizer-ci.com/g/librenms/librenms/inspections/85be63e6-13e2-4e2a-b1b2-403ac7b7e211/issues/files/includes/polling/functions.inc.php?status=new&orderField=path&order=asc

This array is defined near the start of the function, I'm not sure why scrut is picking it up :/

**Comment by SaaldjorMike** [comment]
@laf If you are referring to the initialisation at line 148, then this is not really the same variable since this is named `$poll_update_array` where the use scrut is complaining about is about `$update_array`.

**Comment by laf** [comment]
Thanks @SaaldjorMike Sorted now :)

**Comment by laf** [comment]
*bump*

**Pull request merged**
