### PR TITLE
Add VRF-Lite logic and adapt all VRF-Lite discovery and polling modules ...

### PR DESCRIPTION
**Pull request by nicearma**
...that depend of context like:

* Discovery: arp-table
* Diccovery: bgp-peers
* Discovery: ipv4-add..
* Discovery: ipv6-add

Fix logic in (i dont really remenber, but  i think the logic was a bit confusing, with some variable used before exist, something like that and not very libreNMS style)
* Poller: bgp-peer
* Poller: ospf

Add two Mibs

And other little change, two important the first line 773 in snmp.inc.php for add SNMPv3 Context to the le logic and one little 2  at line 60 because i had the problem that with context i get the ip in the answer.

### CODE REVIEW

**Comment by f0o** [comment]
Proposing close in 24h

**Comment by laf** [comment]
Proposing to close in 4 minutes. This need lots of work to get right anyway and I've genuinely never had the time to try and lab and test it.

**Comment by f0o** [comment]
`@laf commented 4 minutes ago` expired :)

**Comment by nicearma** [comment]
Well is there if some one need it and if any have any question i can always try to recall what i did and help :)

**Comment by laf** [comment]
Thanks @nicearma. I think we would love to get this support in still but the code base has moved on so much that the patches are they stand will need a lot of work :(

**Comment by at69** [comment]
Hello @laf, based on what was produced for LibreNMS Exports, do you think it would be doable to adapt this work to the current base code?
Also, how long do you think it would take?

**Comment by laf** [comment]
@at69 100% the code can be adapted. Not sure on timeframes but a couple of days maybe of solid coding. Is this something you can do?

**Comment by at69** [comment]
@laf It is needed. I'll need a brief though, I don't know much about LibreNMS.

**Comment by laf** [comment]
First, I think we will need @nicearma to submit a contributors agreement to confirm we are ok to use this code still.

Once he's done that, it will be just a job of taking each file he updated and back porting those changes into the current versions we have. He also had another PR at the same time which had some dependencies on this (or vise versa) so that would need doing as well.

We can help with this on irc if you do fancy getting stuck in.

**Comment by at69** [comment]
What are the IRC info?

**Comment by laf** [comment]
We are on freenode: ##librenms

**Pull request closed without merging**
