### PR TITLE
Fix for issue #5533 (Improve support for TiMOS (Alcatel-Lucent) switches

### PR DESCRIPTION
**Pull request by dorkmatt**
This minor tweak improves the TiMOS support to include additional models that were showing up as generic devices before, I also added a tested regex while I'm here.

| Component | Version |
| --------- | ------- |
| LibreNMS  | 81bde0b8da6c798245a7916ac6e2096a9c4ab1cc |
| DB Schema | 156 |
| PHP       | 7.0.13-0ubuntu0.16.04.1 |
| MySQL     | 5.7.17-0ubuntu0.16.04.1 |
| RRDTool   | 1.5.5 |
| SNMP      | NET-SNMP 5.7.3| 

For reference, example sysDescr's:
`TiMOS-B-4.0.R7 both/mpc ALCATEL SAS-M 24F 2XFP 7210 Copyright (c) 2000-2011 Alcatel-Lucent.`
`TiMOS-B-6.0.R6 both/mpc ALCATEL SAS-M 24F 2XFP 7210 Copyright (c) 2000-2014 Alcatel-Lucent.`
`TiMOS-B-7.0.R3 both/hops ALCATEL SAS-T 12F10T 4XFP 7210 Copyright (c) 2000-2014 Alcatel-Lucent.`
`TiMOS-B-7.0.R5 both/hops ALCATEL SAS-T 12F10T 4XFP 7210 Copyright (c) 2000-2015 Alcatel-Lucent.`
`TiMOS-C-7.0.R5 cpm/hops ALCATEL SAS-R 7210 Copyright (c) 2000-2015 Alcatel-Lucent.`

### CODE REVIEW

**Comment by laf** [comment]
We prefer not to use sysDescr, what's the reason for adding that check in rather than just relying on sysObjectId's?

**Comment by dorkmatt** [comment]
I added a missing objectID too, this was missing for ALU 7210 switches.

**Comment by laf** [comment]
Yeah I can see the sysObjectId but why the sysDescr?

**Comment by dorkmatt** [comment]
I can remove it, the intention was to work for other switches that are
missing the specific objectId.

**Comment by laf** [comment]
Yes please, maybe we need to be a bit more wide matching on the sysObjectId.

This also needs additional unit tests adding that you have the data for and a rebase for AUTHORS.md

**Comment by dorkmatt** [comment]
I'll need a bit more guidance on the unit testing requested, can you point me to a similar PR that has such testing baked in? Thanks.

**Comment by wackychocolatefactory** [comment]
@dorkmatt http://docs.librenms.org/Developing/Support-New-OS/#os-test-units

**Comment by laf** [comment]
@dorkmatt Any update on this?

**Comment by dorkmatt** [comment]
OS unit tested added to branch as requested

**Pull request merged**
