### PR TITLE
Update ports test data to match current data

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Hmm, why does it work on master?

**Comment by murrant** [comment]
@Jellyfrog because it uses lazy comparisons so null == 0 is true.  But when updating the data, it causes a lot of noise.  This is an effort to reduce that noise.

**Comment by Jellyfrog** [comment]
That makes sense. Does it make sense to do strict compares?

**Comment by murrant** [comment]
@Jellyfrog maybe

**Comment by PipoCanaja** [comment]
Is there something we can do with these backslash ?
I searched (without success) where this would come from. Dirty solution : check the snmprec file and remove them, so they don't keep breaking everything later...

**Comment by murrant** [comment]
That is the easy way out, which might be worth it.  I think it has something to do with mibs.

**Pull request merged**
