### PR TITLE
core: rrd values based alert

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

- save last 2 values of rrd ds in db for alerting
- included modification for os-updates, ntp-server, ntp-client apps

### CODE REVIEW

**Comment by f0o** [comment]
I generally support this but i think it's better placed as a call within the rrd/data update routine so it's applicable on all rrds from the start.

**Comment by crcro** [comment]
i think this way there is a more flexible approach.
maybe not all rrd values are required to be stored for alerting rules, just the ones that makes sense for alerting

**Comment by laf** [comment]
1 select + 1 update / insert for every single rrd DS that we record data for. If we think rrdtool is a bottle neck for writing data what's going to happen with this. 

It does duplicate a lot of already existing stored values so I feel this is the wrong way to do it.

**Comment by crcro** [comment]
this is way i didn't make it let's say globally, just add this to needed polling, like apps

**Comment by f0o** [comment]
@laf how about adding a variable and let the user decide which data to store in the SQL?

**Comment by laf** [comment]
Sorry I didn't see it was specific to certain polling modules.

So few comments:

The schema needs to be on one line rather than a block - however is it not possible to use the components system that's in place for this?

Would it not be better to put it in the central update function and have an array of poller modules it works for or something?

**Comment by crcro** [comment]
component table aren't suitable for this approach.

your approach would reduce the coding i think (no more need to add that function to every polling files), maybe is a good ideea

**Comment by laf** [comment]
@f0o I can see that making support a bit more difficult.

Add an alert rule for X, but please make sure you have Y enabled before you do that.

**Comment by murrant** [comment]
This would definitely be a good thing to have, but I don't think the approach is right.
When righting a rule the user would have to know a rrd_values is the right table and the rrd_filename (is this full path or partial (it probably varies).

I think it would be better to code something more specific to applications, most other areas of librenms are already alertable and this wouldn't be usable elsewhere.

**Comment by f0o** [comment]
Using the components would be great. We're already feeding all munin-plugins' output into the components to alert on. However it does miss a delta :/

**Comment by laf** [comment]
I'm with @murrant on this one and think it's better done specifically for the apps.

**Comment by crcro** [comment]
good, i'm thinking of a way to remove the so specific rrd names requirements ...

**Comment by laf** [comment]
What's the score with this - is it something we can close down?

**Comment by murrant** [comment]
I'd vote close it for now, crco can re-pr when it is fixed or he may start a new branch anyway.

**Comment by crcro** [comment]
i'll close this for now, a bit busy, will come back to it

**Pull request closed without merging**
