### PR TITLE
Bugfix and update for manage_bills.php

### PR DESCRIPTION
**Pull request by rucarrol**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Something has gone wrong here. Showing as the entire file is new :(

You should branch of from master rather than making changes direct in there.

**Comment by murrant** [comment]
@rucarrol try this:
```
git remote add upstream https://github.com/librenms/librenms.git
git fetch upstream
git rebase upstream/master
git push --force (use care with this one)
```

**Comment by laf** [comment]
@rucarrol Bump :)

**Comment by rucarrol** [comment]
Sorry, was AFK for few weeks. Shall get to this this week.

**Comment by laf** [comment]
*prods* @rucarrol  :)

**Comment by laf** [comment]
Comment back when you've got this sorted @rucarrol :)

**Pull request closed without merging**
