### PR TITLE
add exclude pattern to snmp-scan.py

### PR DESCRIPTION
**Pull request by slalomsk8er**
Added argument to skip host names matching a regex pattern.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This use case seems extremely niche, I don't think it makes sense to include in upstream.

**Comment by slalomsk8er** [comment]
You don't have testing and production servers, separated by a naming convention?

------- Original Message -------

**Comment by murrant** [comment]
They are in different IP spaces.

**Comment by slalomsk8er** [comment]
I'm not so lucky but at least development separate.

**Comment by murrant** [comment]
Again, thanks a bunch for your contribution.  I hope to see more in the future.

I'm going to close this for now as I don't see it to be generally useful.  Feel free to carry the patch locally.  Also, I suggest not running snmp-scan.py after the initial network scan.  We use netbox for inventory management etc and synchronize that to LibreNMS.

**Pull request closed without merging**
