### PR TITLE
refactor: toner discovery

### LINKED ISSUE #4637: Brother printer shows 150% toner level
> Please read this information carefully.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

This was discussed in #3030, but the fix only works with brother printers that just have an os of "brother". Our multifunction brother printer has an os of "	Brother Printer Firmware Ver.H" which pull request #4526 does not recognize.

We are on Version	dc26f09 - Mon Sep 26 2016 17:34:54 GMT-0400

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

refactored toner discovery
fixes: #4637

### CODE REVIEW

**Comment by murrant** [comment]
Hmm, like the direction, but should we go further?
Breaking this out into os based files too?
```php
include "includes/discovery/toner/$os.inc.php";
```

**Comment by laf** [comment]
We have code that does recursive file inclusion. See things like sensors, processors, memory

**Comment by murrant** [comment]
I'm not a fan of the recursive include.  I would rather include a specific file based on OS and have some fallback code.  So, we would only be required to loop through files for OS discovery...

**Comment by laf** [comment]
The issue with that is a lot of the time the code will be the same so you'd have to check if it's one of X os ' and then include the one file that covers them all.

**Comment by crcro** [comment]
i think that for the moment will be too much overhead for both variants, because there is small number of "custom" implementations, if in future the number will grow we should see at that moment

**Comment by murrant** [comment]
Overhead isn't a concern, the difference is < 0.01s.  I'm just trying to keep things organized and understandable.  I feel it is much easier to discover the toner code for sharp printers under it's own file, then tangled up in a long file with all printers.

**Comment by crcro** [comment]
by overhead i was referring to a refactoring point of view, not computational :)
long run i tend to agree with @murrant ... it's easier to find os discovery code (for example) because of the file structure (also it's easier not to break stuff or repair/change it in such a case)

**Comment by laf** [comment]
pushed phpcs fixes.

I think we'll merge this as is and come back to it later.

**Pull request merged**
