### PR TITLE
webui: wireless pages refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

tried to give the wireless pages consistent look.

before:
screen shot 2017-12-01 at 4 18 24 pm

after:
screen shot 2017-12-01 at 4 17 38 pm

### CODE REVIEW

**Comment by murrant** [comment]
@crcro what happened to the navigation across the top?

**Comment by crcro** [comment]
@murrant ... i removed it, seems redundant as the top menu has the exact same functionality.

**Comment by laf** [comment]
> i removed it, seems redundant as the top menu has the exact same functionality.

If you mean the navbar then that's too far to go to switch between sensors, the old links need to stay imho.

**Comment by murrant** [comment]
There is quite a difference between going through the top menu and having one click.  Please add them back, thanks.

**Comment by crcro** [comment]
added back the in page links, more compact, to match others:

screen shot 2017-12-05 at 1 00 40 am

**Comment by kkrumm1** [comment]
Worked for me and looks good. 👍

**Pull request merged**
