### PR TITLE
fix: Bgp-peers junos empty afi-safi names

### PR DESCRIPTION
**Pull request by zombah**
This fixes os junos part of issue #8051
Test data for this case exist in already pending PR #7972 
as junos_mx

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Blocking until #7972 is merged so we can rebase and test properly.

**Comment by laf** [comment]
Sorry @zombah needs a rebase now :(

**Comment by murrant** [comment]
You will need to update test data, since you are changing the polled data.
Run:
```
./scripts/save-test-data.php -m bgp-peers -o comware
./scripts/save-test-data.php -m bgp-peers -o iosxe
./scripts/save-test-data.php -m bgp-peers -o ios -v 3560g
./scripts/save-test-data.php -m bgp-peers -o junos -v mx
./scripts/save-test-data.php -m bgp-peers -o junos -v ex
./scripts/save-test-data.php -m bgp-peers -o arista_eos
```

Then review the modifications to data to make sure they are desired. 
```
git diff -- tests/data
```

**Comment by zombah** [comment]
@murrant Added test data update but i can't figure myself why it changes wrong sessions inside json, as i mentioned on discord maybe parsing order changed or something

**Comment by murrant** [comment]
Looks some fixes changed other OS data .  I removed that test data.  We'll see if that fixes it.

**Pull request merged**
