### PR TITLE
rework: Cisco SB Switch Temp and Fanspeed fix

### PR DESCRIPTION
**Pull request by Fehler12**
Sorry for the long waiting time. This is an update to #14953, which I cannot update anymore for some reason.

I've made some tests and found that the value 0 should be ignored anyway because some Cisco switches report a non-existing fan/temp-sensor with a speed/temp of 0 which causes several errors when adding e.g. a fanless or desktop switch. Therefore I would like to suggest to keep the skip_value for this case.

I've also seen no more fan flapping with the most recent switch firmware so maybe Cisco has fixed something internally.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Fehler12** [comment]
I have currently no idea why the checks fail. I've recreated the test-data for the cbs250 switch with the following comands:
./scripts/collect-snmp-data.php -h 338 -v cbs250-24p-4x
./scripts/save-test-data.php -o ciscosb -v cbs250-24p-4x

However if I upload these test files the checks fail. Any idea beside manually correcting it?

**Comment by murrant** [comment]
@Fehler12 it is because you generated the test data on an old version of LibreNMS.

**Comment by Fehler12** [comment]
Thx. For some reasaon I had to regenerate the test data several times, now it's working. Hoping for pull :).

**Review by murrant — CHANGES_REQUESTED** [review]
don't delete those snmprec files please (especially without explanation)

**Comment by Fehler12** [comment]
> don't delete those snmprec files please (especially without explanation)

Hi, sorry. I've removed those snmprec data because these files were not used for testing. In addition these files did not contain a full SNMP-walk of these devices and therefore I consider these files as obsolete.

**Comment by murrant** [comment]
Those files are used to test OS Detection (but not any polling modules).

https://github.com/librenms/librenms/blob/master/tests/OSDiscoveryTest.php

Please restore them, thanks.

**Review by murrant — APPROVED** [review]

**Pull request merged**
