### PR TITLE
Oxidized update and Device remove

### PR DESCRIPTION
**Pull request by murrant**
Was just working on oxidized, but then to properly update nodes after delete, updated delete_device()

Thanks to PR #13728 by @Jimmyord 

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Included fix to make sure OS is detected when a device is first added, before oxidized reload nodes is called.  Thanks @laf for making me double check :D

**Comment by murrant** [comment]
Incorporates the changes from #13728

**Comment by Jellyfrog** [comment]
This should have been 2 PRs but I know how it is when you start :)

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
Yeah, they got intertwined and I didn't want to separate them :D

**Pull request merged**
