### PR TITLE
Remove SmartOptics Skip Values

### PR DESCRIPTION
**Pull request by electrocret**
Fiber cuts extending over a discovery period will result in sensor being deleted and historical data lost. (Which average fiber cut does)

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
indeed. But now a lot of new sensors are discovered. Is there some way on these devices to find out if a port is in use (or at least no shut), which would allow to differentiate a port with at spare SFP sleeping from one with a service up and running?

**Comment by electrocret** [comment]
@PipoCanaja , should be better now.

**Comment by PipoCanaja** [comment]
Could you have test data that would trigger this skip value by chance ?

**Comment by electrocret** [comment]
> Could you have test data that would trigger this skip value by chance ?

Unfortunately no, my architecture team doesn't believe in disabling ports on our DWDM gear.

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Pull request merged**
