### PR TITLE
Adding invalid hostnames is no longer fatal.

### PR DESCRIPTION
**Pull request by murrant**
Will still fail if they are unpingable.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
This disables snmp by default so users would add ping only devices.

Not really sure what the difference is, from testing adding some fake devices I don't see what's changed.

**Comment by murrant** [comment]
When I tested snmp was not disabled by default.  I'll retest that.

Before, if the hostname was invalid, it would not try to ping it.

Now, it still shows an error, but it tries to ping/add it anyway.

This was for the user with underscores in his hostnames.

**Comment by laf** [comment]
> This was for the user with underscores in his hostnames.

Is it not easier just to update the validation?

**Comment by murrant** [comment]
The validation is correct in my opinion.

**Pull request merged**
