### PR TITLE
ZXR10-SMI

### PR DESCRIPTION
**Pull request by odooviet**
Add ZTE ZXR10 Ethernet Switch MIB

### CODE REVIEW

**Comment by laf** [comment]
Thanks @odooviet 

Can you confirm where you have got the mib from? 

We'd also need you to do a separate commit to agree to the contributors agreement, an example one is: https://github.com/librenms/librenms/pull/1237

Also, this MIB isn't useful without some additional code - are you also planning to contribute this code?

**Comment by odooviet** [comment]
It's provided by ZTE Corporation.

**Comment by paulgear** [comment]
The MIB seems a little empty, too.

**Comment by laf** [comment]
I've seen small mibs. The Dell EqualLogic are stuff is split into their own mibs.

**Comment by paulgear** [comment]
@odooviet Please reference the exact URL where you found the MIB, or some close equivalent.  We need to be able to attribute its source.

**Comment by odooviet** [comment]
This is link download
http://enterprise.zte.com.cn/us/support/?fwzc=wd
But you must account login and permitted by ZTE. [?]
Have many MIB files. Please see attach. [?]

2015-06-20 16:22 GMT+07:00 Paul Gear <notifications@github.com>:

**Comment by laf** [comment]
We'd also need you to do a separate commit to agree to the contributors agreement, an example one is: #1237

Also, this MIB isn't useful without some additional code - are you also planning to contribute this code?

**Comment by odooviet** [comment]
I will contribute code when I complete tested.

2015-06-25 15:19 GMT+07:00 Neil Lathwood <notifications@github.com>:

**Comment by f0o** [comment]
I suggest putting these MIB PRs on hold until we actually got code to use it.

**Comment by laf** [comment]
Indeed, @odooviet when you've got the code tested, include these mibs as additional commits in your PR and it will be fine.

**Pull request closed without merging**
