### PR TITLE
Basic LigoPTP Discovery

### LINKED ISSUE #2636: New device: Ligowave LigoPTP
I have some Ligowave LigoPTP 5-23 MiMo devices that are being discovered as generic devices.

Here is the discovery output:
[ligoptp_discovery.txt](https://github.com/librenms/librenms/files/64303/ligoptp_discovery.txt)

Here is the output of snmpwalk -Oqn:
[ligoptp_snmpwalk.txt](https://github.com/librenms/librenms/files/64288/ligoptp_snmpwalk.txt)

### PR DESCRIPTION
**Pull request by Rosiak**
fix #2636

### CODE REVIEW

**Comment by laf** [comment]
Missing the ligoos polling os file?

**Comment by Rosiak** [comment]
Not unless someone can do some regex foo with this string: 
.1.3.6.1.2.1.1.1.0 "LigoPTP 5-23 MiMo, v6.78-1.rt2880.LIGO.PTP.en_US.39880.120118.103307"

And that probably won't scale beyond the PTP devices.

**Comment by laf** [comment]
Explain what each part is and I'll pop something up.

**Comment by Rosiak** [comment]
sysDescr returns:
```
LigoPTP 5-23 MiMo, v6.78-1.rt2880.LIGO.PTP.en_US.39880.120118.103307
```

LigoPTP 5-23 MiMo - Model
v6.78-1.rt2880 - Software Version(I suppose)

**Comment by SaaldjorMike** [comment]
Software version is only the part: v6.78-1
Looking at their page it seems like they have these firmwares available for download:
v6.95-1
v6.95
v6.94-7

**Comment by Rosiak** [comment]
@SaaldjorMike 
:+1:

**Comment by laf** [comment]
Something like this.

```php
$sysDescr = "LigoPTP 5-23 MiMo, v6.78-1.rt2880.LIGO.PTP.en_US.39880.120118.103307";

list($hardware,$version) = explode(',', $sysDescr);
preg_match('/(v[0-9\-\.]+)/', $version, $tmp_version);
$version = rtrim($tmp_version[0],'.');
echo "$hardware and $version\n";
```

**Pull request merged**
