### PR TITLE
add a auth module for NSS+PAM

### PR DESCRIPTION
**Pull request by VVelox**
This allows you to use PAM modules to do stuff like LDAP or RADIUS auth while pulling users from LDAP, AD, or the like via NSS.

Admin v. Normal user is determined by group membership.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by VVelox** [comment]
PHP Static Analysis is failling thanks to...
 
 ```
Error: Property LibreNMS\Authentication\NssPamAuthorizer::$HAS_AUTH_USERMANAGEMENT has no type specified.
Error: Property LibreNMS\Authentication\NssPamAuthorizer::$CAN_UPDATE_USER has no type specified.
Error: Property LibreNMS\Authentication\NssPamAuthorizer::$CAN_UPDATE_PASSWORDS has no type specified.
Error: Property LibreNMS\Authentication\NssPamAuthorizer::$AUTH_IS_EXTERNAL has no type specified.
Error: Process completed with exit code 1.
 ```
 
It does not like how we are setting the statics in any of the files. Declared the same in this one the same way as the others.

**Comment by VVelox** [comment]
```
    /**
     * @var bool
     */
```

Above the vars in question fixed it.

**Comment by murrant** [comment]
Please don't add any legacy style authentication.

**Comment by VVelox** [comment]
> Please don't add any legacy style authentication.

Hmm, had note seen this.

So I assume this means reworking it to extend... `app/Providers/LegacyUserProvider.php` and `app/Providers/LegacyUserProvider.php`.

That said I am not seeing any clear way to tell it what to use. Looks like it is always handled by legacy?

**Comment by VVelox** [comment]
> Please don't add any legacy style authentication.

So this appears to be controlled via config/auth.php which says don't edit this file.

Been reading through `https://laravel.com/docs/8.x/authentication` and all of our Laravel stuff seems to wrap back around to this. We don't have a means as of currently to effectively use stuff outside of that config wise, if I am understanding this all.

**Comment by VVelox** [comment]
replaced by https://github.com/librenms/librenms/pull/15550 given various changes to the auth stuff since I originally wrote this

**Pull request closed without merging**
