### PR TITLE
Revert "Fix Device Mouseover View"

### PR DESCRIPTION
**Pull request by PipoCanaja**
In case the issues with  librenms/librenms#10962 are confirmed, this PR will Revert librenms/librenms#10962

### CODE REVIEW

**Comment by PipoCanaja** [comment]
If I am not the only one to have issue with this PR in production (no issue in tests) then the revert PR is ready.

**Comment by louis-oui** [comment]
Same for me 

(1/1) ErrorExceptionArray to string conversion
--
in Device.php line 231
at HandleExceptions->handleError(8, 'Array to string conversion', '/export/appl/librenms/app/Models/Device.php', 231, array('os' => array('os' => 'gaia'), 'install_dir' => '/export/appl/librenms'))in Device.php line 231
at Device::App\Models\{closure}(array('os' => 'gaia'))
at array_map(object(Closure), array(array('os' => 'gaia'), array('os' => 'iosxe'), array('os' => 'junos'), array('os' => 'linux'), array('os' => 'nxos')))in Device.php line 232
at Device::loadAllOs(true)in Device.php line 37

**Comment by SourceDoctor** [comment]
Works on my productive system.
Where do you have this issue and which OS has the system which got a mouseover?
Maybe i took a look not on the right points?

**Comment by louis-oui** [comment]
MariaDB [librenms]> select distinct os from devices;
+-------+
| os    |
+-------+
| gaia  |
| iosxe |
| junos |
| linux |
| nxos  |
+-------+
5 rows in set (0.00 sec)

**Comment by SourceDoctor** [comment]
no Error on my productive System

MariaDB [librenms]> select distinct os from devices;
+---------+
| os      |
+---------+
| apc     |
| linux   |
| netgear |
| ping    |
| unifi   |
| windows |
+---------+
6 rows in set (0.001 sec)

MariaDB [librenms]>

**Comment by PipoCanaja** [comment]
Is it linked to PHP version ? 
-bash-4.2$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.58.1-58-g2953358
DB Schema | 2019_12_16_140000_create_customoids_table (148)
PHP       | 7.2.13
MySQL     | 5.5.64-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.9.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by SourceDoctor** [comment]
@PipoCanaja i pushed a PR which fixes the issue  #10976

**Pull request closed without merging**
