### PR TITLE
Added Vibe OS

### PR DESCRIPTION
**Pull request by caskings**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by caskings** [comment]
I'm having some trouble interpreting the output of the CI test. Is it not matching on the vibe.snmprec file or is it something else?

**Comment by murrant** [comment]
@caskings You did not add includes/defintions/vibe.yaml to your PR ;)

**Comment by laf** [comment]
@caskings Thanks very much for submitting this.

If possible, would you be able to submit more test data following; https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

Please ensure you anonymise any data you need to before submitting it.

**Comment by laf** [comment]
@caskings Any further response on this?

**Comment by caskings** [comment]
@laf I'll get some more test data together over the next week.

**Comment by murrant** [comment]
@caskings I was looking and are you sure ViBE is the right name for this and that that is the right logo?

I did a quick search and ViBE seems to be a technology, not an OS.  Do you have a web link to this product?

**Comment by laf** [comment]
@caskings Feel free to reply to this when you have time and we can re-open but for now we are closing this due to the lack of response.

**Pull request closed without merging**
