### PR TITLE
Update Install-LibreNMS.md

### PR DESCRIPTION
**Pull request by Jarod2801**
Composer missing in Centos 7 and 8 docs

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Composer is not needed, since the docs says `./scripts/composer_wrapper.php install --no-dev`

**Comment by Jarod2801** [comment]
Hm. A user on the community complained about failing to install. After dnf install composer everything went fine. Are there any other dependencies?

**Comment by Jellyfrog** [comment]
Okay I see its actually part of the docs. My bad.

**Comment by murrant** [comment]
I'm not sure this is the correct answer.  It is assumed the device has internet access, if that is the case, it will download the composer.phar.  This is the preferred installation.  The system composer packages are often very stale.

**Comment by bryonadams** [comment]
> 
> 
> I'm not sure this is the correct answer. It is assumed the device has internet access, if that is the case, the wrapper will download the composer.phar. This is the preferred installation. The system composer packages are often very stale.

Should composer be removed from the instructions then?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-67-release-changelog-august-2020/13285/1

**Pull request merged**
