### PR TITLE
Fix ignore alerts has no effect

### PR DESCRIPTION
**Pull request by louis-oui**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Alert ignore is right now done with macros, which gives flexibility (You can still create alerts that triggers on and "ignored" device. I suggest to open a post on the community forum and get some attention on this subject, to see if we go in this direction.

**Comment by louis-oui** [comment]
> Alert ignore is right now done with macros

What do you mean by macros ? Is it ignoring alert rule if "AND devices.ignore = 0" on the rule ?

This behaviour is misleading

**Comment by louis-oui** [comment]
We can rename current label "ignore alerts" to "tag for ignore alerts" and add a new settings "ignore all alerts"

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/ignore-alert-on-device-settings-is-misleading/10501/1

**Comment by louis-oui** [comment]
Hi @PipoCanaja, there is no comment on the community ? What do you think of that ?
We can rename current label "ignore alerts" to "ignore tag" and add a new settings "Disable alerts"

**Comment by PipoCanaja** [comment]
This change has a big impact on the way alerting is done, we cannot just do it between Xmas and NYE without concertation, and without notice. Let's put this on hold for now.

**Comment by louis-oui** [comment]
> This change has a big impact on the way alerting is done, we cannot just do it between Xmas and NYE without concertation, and without notice. Let's put this on hold for now.

Thank you for your response. I understand. That's why I suggest to keep "ignore" behaviour as it is and add a new "disable alert" setting.

Let's keep it in hold for now

**Comment by louis-oui** [comment]
Replaced by https://github.com/librenms/librenms/pull/11011

Just need a wording and section change

**Pull request closed without merging**
