### PR TITLE
 Adding support for ADTRAN AOS, Accedian MetroNID AEN, Telco Systems OS

### PR DESCRIPTION
**Pull request by thecityofguanyu**
On branch thecityofguanyu/add-various-oses

 Changes to be committed:
	new file:   html/images/os/accedian.png
	new file:   html/images/os/adtran.png
	new file:   html/images/os/batm.png
	modified:   includes/definitions.inc.php
	new file:   includes/discovery/mempools/batm.inc.php
	new file:   includes/discovery/os/batm.inc.php
	new file:   includes/discovery/os/metronid.inc.php
	new file:   includes/discovery/os/netvanta.inc.php
	new file:   includes/discovery/processors/batm.inc.php
	new file:   includes/discovery/processors/calix.inc.php
	new file:   includes/discovery/processors/metronid.inc.php
	new file:   includes/discovery/processors/netvanta.inc.php
	new file:   includes/discovery/sensors/temperatures/batm.inc.php
	new file:   includes/discovery/sensors/temperatures/metronid.inc.php
	new file:   includes/polling/mempools/batm.inc.php
	new file:   includes/polling/os/accedian.inc.php
	new file:   includes/polling/os/adtran.inc.php
	new file:   includes/polling/os/batm.inc.php

	also tons of mib files

### CODE REVIEW

**Comment by laf** [comment]
Really appreciate the effort you've put in here.

However you'll need to split things out into different pull requests, mostly to make it easier to review the changes and merge things in but this is too many file changes for one commit alone.

**Comment by thecityofguanyu** [comment]
@laf 

No problem, I understand. Appreciate you bearing with me, as I'm not entire familiar with your best contributing practices.

Just to clarify, is correct method, say, one new OS (including its MIBs) per commit?

**Comment by thecityofguanyu** [comment]
@laf

Opened #3767, which contains one OS from this merge. Let me know if that way works better.

**Comment by laf** [comment]
Yeah one new OS per commit would be best. Will take a look at the new PR's soon.

**Comment by laf** [comment]
Closing this down

**Pull request closed without merging**
