### PR TITLE
Added power metric discovery for rfc1628 UPS (fixes librenms/librenms#1257)

### PR DESCRIPTION
**Pull request by einhirn**
Sorry, still not having got the Github syntax for commit messages right. But I think next one will hopefully be merged to the issue since I read up on how to put the reference in there.

### CODE REVIEW

**Comment by laf** [comment]
@einhirn Thanks for this PR, is the reason to make the sensors unique and be discovered?

**Comment by einhirn** [comment]
Not sure I understand the question. I added this bit because I can read power values from my rfc1628 compliant UPS and wanted them to appear in librenms. "Power" seemed to be the right sensor type.

**Comment by laf** [comment]
Sorry to be more clear, lines like $index      = 100+$i; is this to make the index value unique?

**Comment by einhirn** [comment]
I just copied that from other discovery scripts :grinning:
But yes - since there are up to three lists of Lines (Input, Bypass, Output) each of them usually counting Lines 1,2,3 there's an offset added so the index is unique.

**Comment by f0o** [comment]
Auto-Deploy finished, Test PR at http://1258.librenms.ci.devilcode.org or https://1258.librenms.ci.devilcode.org

**Comment by f0o** [comment]
Auto-Deploy finished, Test PR at http://1258.librenms.ci.devilcode.org or https://1258.librenms.ci.devilcode.org

**Pull request merged**
