### PR TITLE
feature: Added support for setting php memory_limit in config.php

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Users can now change this dynamically rather than having to reload the web service / php-fpm.

### CODE REVIEW

**Comment by murrant** [comment]
Seems reasonable, I would be much happier if we could just display the error to the user.

**Comment by laf** [comment]
> Seems reasonable, I would be much happier if we could just display the error to the user.

Registering our own custom error handler has limitations afaik so we don't get to trap all errors that occur.

**Comment by murrant** [comment]
I mean setting display errors to a different level.  To many errors would be printed at this time :/

**Comment by laf** [comment]
Seems like a different discussion / PR. Regardless of showing this to the user, allowing people to change it in config.php makes it easier for users to fix.

**Comment by murrant** [comment]
I was concerned we might not be able to set that in some situations, but seems ok.  http://php.net/manual/en/ini.list.php

Where you've placed this in the config it doesn't allow the setting to be set via mysql.  Ok with this?

**Comment by laf** [comment]
> Where you've placed this in the init.php it doesn't allow the setting to be set via mysql. Ok with this?

I decided not to bother with the webui ability as most likely you'll want to edit this when you can't access it.

**Pull request merged**
