### PR TITLE
Poller performance improvement

### PR DESCRIPTION
**Pull request by eskyuu**
Hi,

I've just started using librenms and noticed that the poller wrapper forks a new process for every device polled.  I also noticed that the CPU usage is not smooth (the poller gets more CPU bound at the end of the polling cycle as the devices respond quicker).

I was able to get a 2x improvement in the total polling speed after applying these patches and running the poller-wrapper 3 or 4 times.  It is important to do these 3 or 4 poller executions so the wrapper learns the new polling durations and correctly splits the work queues in half.  We are polling around 1,000 devices with a polling duration of between 1 and 140 seconds per device, so I appreciate that my results may differ from other people.

I have tested the code on our system, and it correctly handles the errors that I came across during testing.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by eskyuu** [comment]
I just noticed the bad formatting of the PHP script.  I will fix and re-submit.

**Comment by paulierco** [comment]
Maybe you can have a look to this ? https://github.com/librenms/librenms/pull/13188

**Comment by eskyuu** [comment]
I'll have a look - thanks.

I tracked down my skipped polls issue - I needed to call Config::reload() in between each poll.  Unfortunately this resulted in the poll time increasing back to the previous level.  My patch does appear to reduce CPU usage on our host by about 10%, which I can then compare against the pull request that you've sent after I have confirmed that my newest patch is 100% working.

**Comment by deajan** [comment]
@eskyuu I have written #13188 and would be glad to have your feedback on my PR.
I've refactored most of the wrapped poller code, merging the poller, discovery and service-check codes into a single wrapper, but for other reasons than performance.
Maybe you could try to apply your patch on my fork which has yet to get upstreamed, and see whether it will increase the performance as a whole ?

**Pull request closed without merging**
