### PR TITLE
Added the option to show or hide unreachable devices in the alert widget

### PR DESCRIPTION
**Pull request by eskyuu**
I have added an option on the alerts widget for unreachable hosts (hosts with parent(s) set where all parents have a device status of "0".  It can be used to stop the alert widget from having too much noise from a single site with multiple devices being offline.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ottorei** [comment]
Might be a bit confusing to describe them as unreachable. A device could be unreachable if it is down itself for any reason. Have you considered wording this as something like "Hide alerts when depended devices are down"?

While this might clearly be useful option in some cases, the alerts tab would still list all invidual devices. The widget would probably still list invidual devices for a while if the child was polled before the parent. They would probably also cause any configured alerts / transports to trigger. A more generic approach could probably be to enhance the poller to check the connectivity to one or more parents and changing it's status before polling the child device (maybe several possible options for this like 1) polling order 2) check one or more parents with fastping).

Anyway, I think this PR enhances the functionality of the widget itself just fine and is OK - just pointing out that a more general approach should be implemented at some point to the poller.

**Comment by eskyuu** [comment]
The term unreachable comes from the nagios/icinga monitoring systems 
where devices are down if they are offline but the devices they depend 
on are online, and unreachable if they are offline and the devices they 
depend on are also offline.  I'm happy to change the wording if you 
still think it's clearer, but I'm aware of the limited space in the 
textbox.  I would imagine that an update to the documenation could clear 
up any confusion if you're happy with my explanation of unreachable, as 
well as the use in other monitoring systems.

Yes, this is the same as the "Show acknowledged" option, where the 
alerts tab acts independently of the widget.  I don't think this is an 
issue.

The questions around the polling and alerting are good, but as you've 
noted this PR is not attempting to address any of these, and just builds 
on top of the dependencies used by the alerter.

After reading tbe above do you still think I should change the wording 
on the option?

**Comment by ottorei** [comment]
Well, the wording is fine if it is consistent and usage of the feature is documented.

**Comment by murrant** [comment]
I think unreachable is a bit misleading too.  Perhaps "Hide devices without a parent".

**Comment by eskyuu** [comment]
I've just updated the alert settings page to give a clear description

**Review by murrant — DISMISSED** [review]

**Comment by eskyuu** [comment]
This failed to merge on the final checks because some of the test data has changed.  I've rebased, so can you please re-approve.

**Comment by laf** [comment]
I think I have to agree that this should just be a checkbox to turn on 'Hide alerts for devices with parents that are down' so you only have two options:

option 1) All devices are shown in the alerts
option 2) Only parent devices are show if they are down, or devices that have no parent that is down (it actually would be good to highlight this is a parent device and how many child devices are also down).

**Comment by eskyuu** [comment]
> I think I have to agree that this should just be a checkbox to turn on 'Hide alerts for devices with parents that are down' so you only have two options:
> 
> option 1) All devices are shown in the alerts option 2) Only parent devices are show if they are down, or devices that have no parent that is down (it actually would be good to highlight this is a parent device and how many child devices are also down).

My current use case for this option is to have 2 widgets on the dashboard - one to show all the parents that are offline, and another to show all the children.  The point of having both is to quickly see all the urgent alerts on one widget, while still being able to see the effect.  This means that the tickbox option would not suit my current needs, so I do not agree with the tickbox suggestion.

I agree that adding another column to show how many devices are affected would be very useful.  I can have a look at adding another column with this additional info.

**Comment by eskyuu** [comment]
Having said this, I'm not sure when I will get a chance to look at adding the extra column.  Please let me know how important this additional feature is?

**Comment by eskyuu** [comment]
It looks like this has been merged elsewhere

**Pull request closed without merging**
