### PR TITLE
DOCS, switch to dark or light mode

### PR DESCRIPTION
**Pull request by SantiagoSilvaZ**
light: 
image

dark
image
image

This color palette is automatic according to the user's system preference

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Nifty, the front page is the only custom html.  Might need a bit of css to make it follow the theme.

**Comment by SantiagoSilvaZ** [comment]
@murrant, I've tested it on every page, and the theme seems to work.
libre

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
I was saying the boxes on the front page don't follow the theme.  I don't consider the white to be in the theme.  But it doesn't look too bad.

**Comment by SantiagoSilvaZ** [comment]
Now I understand, I'll take a look later because the boxes didn't follow the theme.
Thanks @murrant!

**Pull request merged**
