### PR TITLE
initial sonus support

### PR DESCRIPTION
**Pull request by crcro**
issue #4135
- tidy on definitions.inc.php
- included all sonus mibs

### CODE REVIEW

**Comment by laf** [comment]
You've got a lot of formatting updates in this PR which is making it noisy, can you please submit just the support for the device.

If all of the included MIBs aren't needed can you reduce it to just those that are.

**Comment by laf** [comment]
Awesome, thanks :)

**Comment by mzac** [comment]
I have some Sonus SBC boxes on my network however the enterprise OID is different

Mine is using SNMPv2-SMI::enterprises.177.15.1.1.1

<pre>
SNMPv2-MIB::sysDescr.0 = STRING: Sonus SBC Portfolio
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.177.15.1.1.1
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1051620595) 121 days, 17:10:05.95
SNMPv2-MIB::sysContact.0 = STRING: root@localhost
SNMPv2-MIB::sysName.0 = STRING: SONUS-SBC1
SNMPv2-MIB::sysLocation.0 = STRING: Unknown
SNMPv2-MIB::sysServices.0 = INTEGER: 15
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (18) 0:00:00.18
</pre>

Anything else I can provide from my side?

**Comment by laf** [comment]
Please create an issue.

**Pull request merged**
