### PR TITLE
Copy redhat.svg to redhatenterpriseserver.svg

### PR DESCRIPTION
**Pull request by rockyluke**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@rockyluke What's the reason for this as I don't see anywhere we would make use of it?

**Comment by rockyluke** [comment]
I see for my RedHat Enterprise : 

> Operating System | Linux 2.6.32-573.18.1.el6.x86_64 (**RedHatEnterpriseServer** 6.7)

**Comment by laf** [comment]
Does it now work as I thought you needed to use the distro script to get specific os logos past the standard Tux one.

**Comment by rockyluke** [comment]
With the distro script I get two more RedHat identifiers that's why I need new svg : 
- RedHatEnterpriseServer
- RedHatEnterpriseES

(sorry it's only a cosmetic issue...)

**Comment by murrant** [comment]
Perhaps change the distro script to return something more consistent?

**Comment by rockyluke** [comment]
I can do that if you prefer :)

**Comment by laf** [comment]
I think it's definitely better to update distro than keep adding logos.

**Comment by laf** [comment]
Closing, if you can update the distro script that would be better.

**Comment by rockyluke** [comment]
It's done : https://github.com/librenms/librenms-agent/pull/145

**Pull request closed without merging**
