### PR TITLE
Add support for snmpsim-lextudio

### PR DESCRIPTION
**Pull request by freddy36**
Ilya Etingof, the author of the original snmpsim/pysnmp projects passed away on 10-Aug-2022.
His snmpsim version doesn't work anymore with the current python version (3.12).
This adds compatibility for the https://github.com/lextudio/snmpsim fork, which works with python 3.12.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by freddy36** [comment]
Please note that the current PyPI release (1.1.0) contains a bug which breaks compatibility with librenms.
The fix (https://github.com/lextudio/snmpsim/pull/2) is already merged and should make it into the next release.

**Comment by murrant** [comment]
Thanks @freddy36 are these the only changes needed?

**Comment by freddy36** [comment]
It works for me with these changes. I'm not sure how I installed it in the first place.

**Comment by freddy36** [comment]
Ok, urrllib3 version >=2 is required now.

**Review by murrant — APPROVED** [review]

**Pull request merged**
