### PR TITLE
Add Laravel to LibreNMS

### PR DESCRIPTION
**Pull request by murrant**
Intercepts all routes and falls back to existing pages/api.

Discovery/Poller should continue to work, if not updating via daily.sh, you will need to run:
```sh
composer install --no-dev
```

.env will be created with some base settings.  Settings in .env are generally settings we need to start the application.  If you can think of anything else that should be in .env, please leave a note so we can add it before we merge this.  When running composer install, we only create .env once, so updating in the future will likely be manual.

If you have permissions issues, you should get a message telling you how to fix it.

Visit any page or **/laravel**.  Test API.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 8318`

### CODE REVIEW

**Comment by laf** [comment]
> composer install --no-dev

This would happen with `./daily.sh` though right?

> setfacl -R -m g::rwx rrd/ logs/ storage/ bootstrap/cache/
> setfacl -d -m g::rwx rrd/ logs/ storage/ bootstrap/cache/

Only needed for webui so at least we don't break polling.

By chance. I get this error:

`[2018-03-19 22:11:11] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: [] operator not supported for strings in /opt/librenms/includes/defaults.inc.php:124`

I had `$config['transit_descr'] = 'boom';` set for testing. This does indicate that config.php can cause the webui to break now if the config values deviate from what we expect.

**Comment by murrant** [comment]
Probably different error settings.  

Thanks for testing.  I'm not sure we can fix the folder permissions without manual intervention.

**Comment by laf** [comment]
> Thanks for testing. I'm not sure we can fix the folder permissions without manual intervention.

Yeah possibly although it doesn't matter too much if it doesn't break poller/discovery and only affects the webui.

**Comment by laf** [comment]
Tag me when this needs testing.

**Comment by murrant** [comment]
@laf I believe you can test it now I've been working on replicating the LibreNMS (v1) layout so we could blend new and old pages.  Mostly that is to see what issues we have.  Right now I am stuck on some database queries, I may just take the easy way out on those for now.

Accessing existing pages and migrating from existing set up.  Is working as good as I can get it for now.  There may still be permissions issues, but we try to avoid those and we should give messages on how to manually fix those.  I can't remember if I tested what happens if git pull is done without composer install --no-dev

**Comment by laf** [comment]
The web pages seem to load ok. I've not tested anything on the API yet.

I did manage to break it but I'm not sure how. You can see the second time I re-ran daily.sh, I ended up with no .env and some errors but it worked after resetting again. Will see if I can replicate it.

```
-bash-4.2$ git checkout laravel
gBranch 'laravel' set up to track remote branch 'laravel' from 'murrant'.
Switched to a new branch 'laravel'
-bash-4.2$ git pull murrant laravel
git From github.com:murrant/librenms
 * branch                laravel    -> FETCH_HEAD
Already up to date.
-bash-4.2$ git reset --hard 97d58cc1214e68253220b1bc06678d7af449fa40
HEAD is now at 97d58cc12 fix:: Fixed display of WD drives for smart application (#8471)
-bash-4.2$ vi config.php
-bash-4.2$ ./daily.sh
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updated from 97d58cc12 to 427c9b291                OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
-bash-4.2$ git checkout^C
-bash-4.2$ vi config.php
-bash-4.2$ vi .env
.env          .env.example
-bash-4.2$ vi .env
-bash-4.2$ rm .env
-bash-4.2$ git reset --hard 97d58cc1214e68253220b1bc06678d7af449fa40
HEAD is now at 97d58cc12 fix:: Fixed display of WD drives for smart application (#8471)
-bash-4.2$ ./daily.sh
PHP Fatal error:  Cannot redeclare array_sort() (previously declared in /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/helpers.php:287) in /opt/librenms/includes/functions.php on line 69
PHP Stack trace:
PHP   1. {main}() /opt/librenms/daily.php:0
PHP   2. require() /opt/librenms/daily.php:14
PHP Fatal error:  Cannot redeclare array_sort() (previously declared in /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/helpers.php:287) in /opt/librenms/includes/functions.php on line 69
PHP Stack trace:
PHP   1. {main}() /opt/librenms/daily.php:0
PHP   2. require() /opt/librenms/daily.php:14
Updating Composer packages                         OK
Updated from unset to                              OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
-bash-4.2$ vi .en
-bash-4.2$ vi .en^C
-bash-4.2$
-bash-4.2$
-bash-4.2$ ll .en^C
-bash-4.2$ ./daily.sh
Updating to latest codebase                       ^C
-bash-4.2$ git reset --hard 97d58cc1214e68253220b1bc06678d7af449fa40
HEAD is now at 97d58cc12 fix:: Fixed display of WD drives for smart application (#8471)
-bash-4.2$ ./daily.sh
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updated from 97d58cc12 to 427c9b291                OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
-bash-4.2$ cat .env

```

**Comment by laf** [comment]
API looks good as well

**Comment by laf** [comment]
So I can reliably replicate the issue with daily.sh but not when starting from a clean, i.e no .env setup so it probably won't impact anyone.

**Comment by laf** [comment]
We will need to update the install docs to install `php72w-mysqlnd` instead of `php72w-mysql` otherwise you get:

```
[2018-04-03 13:40:37] production.ERROR: Error in config.php!
mysqli_connect(): Headers and client library minor version mismatch. Headers:50556 Library:100130
```

**Comment by murrant** [comment]
@laf Odd about the php72w-mysqlnd, not sure why you would need that...

**Comment by murrant** [comment]
@laf After some research are you sure that isn't an OS level issue?  Did LibreNMS without this PR merged work ok?

**Comment by laf** [comment]
> @laf After some research are you sure that isn't an OS level issue? Did LibreNMS without this PR merged work ok?

It works both with and without this PR, it's the warning that gets printed everywhere which drew me to it.

Seems mysqlnd is the recommended approach anyway: https://secure.php.net/manual/en/mysqlnd.overview.php

**Comment by murrant** [comment]
Probably update the install docs then.  We might have to add a FAQ for it.

**Comment by laf** [comment]
So I now get a 500 with this when not running mysqlnd

**Comment by laf** [comment]
Disco and polling is fine. Tested quite a lot of the webui with no issues.

Just need to test the api now.

**Comment by laf** [comment]
API seems good as well.

**Comment by murrant** [comment]
I'm saying it's not a problem with Laravel per-se.  Just that Laravel reports all errors.  You were probably getting an error before and it is suppressed.

**Comment by laf** [comment]
> I'm saying it's not a problem with Laravel per-se. Just that Laravel reports all errors. You were probably getting an error before and it is suppressed.

I know that, however this PR causes a 500 without any other changes which shouldn't happen. Luckily it doesn't affect the poller but still.

**Comment by murrant** [comment]
Once we hand off to index.php librenms sets error handling to the way it is now (except for set_error_handler(), which should be fine)

**Comment by murrant** [comment]
@laf Did a clean VM and installed this.  Found a couple of issues, but I could not recreate your sql issue.

**Comment by laf** [comment]
Ok so I've tracked it down to me having the mariadb repo enabled, removed this and re-installed the relevant rpms and all is fine.

However, it does highlight it could still be an issue for others - not everyone will follow our docs and I know of some big users who get given a DB server to use so they don't have control over some things so imho, this causing a 500 should be stopped.

I've also re-tested from a fresh install this current branch and can't get past:

```
Error: /opt/librenms/bootstrap/cache is not writable! Run these commands to fix:
cd /opt/librenms
chown -R librenms:librenms rrd/ logs/ storage/ bootstrap/cache/
setfacl -R -m g::rwx rrd/ logs/ storage/ bootstrap/cache/
setfacl -d -m g::rwx rrd/ logs/ storage/ bootstrap/cache/
```

Without just disabling SELinux.

**Comment by murrant** [comment]
@laf are you sure it is up to date.  I ran into that issue yesterday and fixed it (i think).  The problem was checking if logs/librenms.log is writable, but it doesn't exist yet.

**Comment by laf** [comment]
> @laf are you sure it is up to date. I ran into that issue yesterday and fixed it (i think). The problem was checking if logs/librenms.log is writable, but it doesn't exist yet.
> 
> Edit: I see yours is complaining about bootstrap/cache

Completely fresh install to test then added your repo as a remote.

**Comment by laf** [comment]
So more reading on this header / client mis-match issue and everything is saying to install php-mysqlnd so we definitely need to update the install docs - I'll do that separately as it won't make a difference if we do it before this.

As for the issue with it here, you could just add `@` before `mysqli_connect` in `includes/dbFacile.php` to suppress this for now.

**Comment by laf** [comment]
Re-running my tests for this.

**Comment by murrant** [comment]
I'd be fine with suppressing warnings in mysqli_connect for now.

**Comment by laf** [comment]
I've not looked into why but potentially the config in the db isn't being at least passed to poller.

```php
diff --git a/includes/polling/functions.inc.php b/includes/polling/functions.inc.php
index 0e79faaa8..0339c41a7 100644
--- a/includes/polling/functions.inc.php
+++ b/includes/polling/functions.inc.php
@@ -390,6 +390,7 @@ function poll_device($device, $options)
         echo "Polled in $device_time seconds\n";

         // check if the poll took to long and log an event
+var_dump($config);
         if ($device_time > $config['rrd']['step']) {
             log_event("Polling took longer than " . round($config['rrd']['step'] / 60, 2) .
                 ' minutes!  This will cause gaps in graphs.', $device, 'system', 5);
```
I was debugging why my eventlog had Polling took longer than 0 and it's because rrd.step isn't being used here. The var_dump shows no db stored config is though.

**Comment by murrant** [comment]
Nice catch @laf.  You should look at the fix, you might get a chuckle.

**Comment by laf** [comment]
> Nice catch @laf. You should look at the fix, you might get a chuckle.

It's always the simple things :)

**Comment by murrant** [comment]
Good to go and I'm up for the day :-)

**Pull request merged**
