### PR TITLE
InfluxDB support

### PR DESCRIPTION
**Pull request by laf**
This is extremely alpha at present - see the doc for more details.

I've not added the library used to Makefile as it needs compiling with composer to create the necessary files used here.

### CODE REVIEW

**Comment by paszczus** [comment]
WOW !!!

**Comment by laf** [comment]
@f0o mind getting me ssh access to this CI or running a poller debug to see why it's stopped running.

**Comment by laf** [comment]
Bump

**Comment by f0o** [comment]
!trigger ci

**Comment by f0o** [comment]
Looking very nice on the CI

**Comment by f0o** [comment]
:+1: from here, Only thing I dislike is the subtree'ing/squashing of the libs :S

**Comment by laf** [comment]
I hate subtreeing in general, 1,000's of files when only a handful are needed :(

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
CI running for 3 days now, all good :+1: 

I'd say merge and tag as Beta feature :)
opinions?

**Comment by laf** [comment]
Bump

**Comment by laf** [comment]
Bump

**Comment by f0o** [comment]
Bump :)

**Comment by SaaldjorMike** [comment]
I briefly tried installing InfluxDB to test it out, but seems like I have some issues which may just be me not setting it up properly.

Running the poller returns the following error:
```
PHP Fatal error:  Uncaught exception 'InfluxDB\Exception' with message 'Error creating resource: [message] fopen(http://127.0.0.1:8086/write?db=librenms&precision=n): failed to open stream: HTTP request failed! 
[file] /opt/librenms/lib/influxdb-php/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 244' in /opt/librenms/lib/influxdb-php/src/InfluxDB/Database.php:149
Stack trace:
#0 /opt/librenms/includes/influxdb.inc.php(70): InfluxDB\Database->writePoints(Array)
#1 /opt/librenms/includes/polling/functions.inc.php(271): influx_update(Array, 'poller-perf', Array, Array)
#2 /opt/librenms/poller.php(122): poll_device(Array, Array)
#3 {main}
  thrown in /opt/librenms/lib/influxdb-php/src/InfluxDB/Database.php on line 149
```

Config.php:
```
$config['influxdb']['enable'] = true;
$config['influxdb']['transport'] = 'http';
$config['influxdb']['host'] = '127.0.0.1';
$config['influxdb']['port'] = '8086';
$config['influxdb']['db'] = 'librenms';
$config['influxdb']['username'] = 'admin';
$config['influxdb']['password'] = 'admin';
```

Opening the CLI to InfluxDB shows me that at least something was inserted:
```
Connected to http://localhost:8086 version 0.9.4.2
InfluxDB shell 0.9.4.2

> use librenms
Using database librenms

> show measurements
name: measurements
------------------
name
poller-perf
processors
uptime

> select * from uptime limit 1
name: uptime
------------
time                            hostname                        uptime
2015-11-12T18:40:02.75397075Z   switch01.example.org  2.497232e+07
```

Any suggestions?

**Comment by laf** [comment]
I've wiped my LibreNMS install and still can't replicate your issue :(

What distro + php version are you on @SaaldjorMike?

**Comment by SaaldjorMike** [comment]
Currently I can't seem to reproduce it. My guess would be that my inexperience with InfluxDB is the issue here. I am currently running the following which is the same system as I tested on previously:
```
[root@ubuntu-librenms librenms (master ✗)]$ php --version     
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
[root@ubuntu-librenms librenms (master ✗)]$ lsb_release -a    
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by laf** [comment]
Still can't replicate the issue @SaaldjorMike. Tested on Ubuntu with the following versions:

```bash
root@ubuntu-librenms:/opt/librenms# php --version
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
root@ubuntu-librenms:/opt/librenms# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

Anyone else care to comment on this @librenms/reviewers

**Comment by Rosiak** [comment]
I *might* have time in the weekend to give this a spin.

**Comment by f0o** [comment]
b..u..m..p..?..

**Comment by laf** [comment]
It's good to go from my side.

**Comment by paulgear** [comment]
We seem to be missing influx from the recently-merged Ceph support.

**Comment by paulgear** [comment]
Sorry - file for the last comment is ./includes/polling/applications/ceph.inc.php; same goes for ./includes/polling/applications/proxmox.inc.php.

**Comment by paulgear** [comment]
./includes/polling/os/fortigate.inc.php has 'fortigate)sessions' - probably should be 'fortigate_sessions'

**Comment by paulgear** [comment]
Other places which seem to be missing influx:
./includes/polling/os/ciscowlc.inc.php
./includes/polling/os/pulse.inc.php
./includes/polling/functions.inc.php (line containing $ping_rrd)
I think this demonstrates why we should be replacing rrdtool_update (and rrd_create_update) with a function that handles both rrdtool and influxdb.  That way we will know that we have 100% coverage of polling data.

**Comment by Rosiak** [comment]
@librenms/core-team 
I really think Influx is the way we need to go, I think we need to discuss the future of this one next time we speak together.

**Comment by laf** [comment]
I've re-opened this with the fix for fortigate_sessions.

The missing influx calls can be added at a later stage. Some of these are missing purely because of the length of time this PR has been open for.

Merging influx and rrd calls I consider outside of the scope of this PR. The core of this PR doesn't tread on the toes of the existing code so should be relatively safe, centralising the code would make this a risky  merge as it could affect existing installs.

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by Rosiak** [comment]
Working fine on my dev machine.
:+1:

**Comment by f0o** [comment]
bump :)

**Comment by laf** [comment]
Needs a rebase again now, will do so when this is going to be merged.

**Comment by Rosiak** [comment]
I suppose we are waiting on @paulgear's go.

**Comment by paulgear** [comment]
I don't think this needs to block on me.  I've given my opinions above.  @laf are you still concerned about the size of the influxdb-php library?  If so, we should work that out before we merge.

**Comment by laf** [comment]
Not the size but more using git subtree but that's now a mute point as trying to tidy up this PR by cherry picking the commits I need just lead to lots of merge conflicts so as it stands then this PR is presented now as is aside from the last rebase that will be needed.

**Comment by f0o** [comment]
With the new daily we can start using submodules, that reduces the size greatly

**Comment by laf** [comment]
The issue is picking this PR apart now to get what I need from it.

**Comment by paulgear** [comment]
If you're happy for me to do it, I'll have a try over the holidays to get just the code we need from influxdb-php.  If we don't really need it, I'd rather not bloat the repository.

**Comment by laf** [comment]
Feel free. Running this at work now so my needs are filled I guess.

**Comment by f0o** [comment]
I'd like to see this merged. It's really useful and in future we can think of a generic feeder function that will multiplex and/or route datasources (influx/mysql/rrd/...)

**Comment by Rosiak** [comment]
I suggest that we set a date, if no objections are made then we merge at that date.

**Comment by laf** [comment]
You have no complaints from me for a merge. Running this currently at work now:

image

**Comment by paulgear** [comment]
Give me until new year's day - I'm going to have a shot at reducing the size of the influxdb-php part.

**Comment by paulgear** [comment]
After looking at this, I don't think it's worthwhile to try to reduce the size of the influxdb-php install.  I did find one other minor issue, which is that tags with spaces are not escaped.  I worked around it like this:
```diff
diff --git a/includes/influxdb.inc.php b/includes/influxdb.inc.php
index 2f844e2..4970d7f 100644
--- a/includes/influxdb.inc.php
+++ b/includes/influxdb.inc.php
@@ -46,6 +46,8 @@ function influx_update($device,$measurement,$tags=array(),$fields) {
     $tmp_fields = array();
     $tmp_tags['hostname'] = $device['hostname'];
     foreach ($tags as $k => $v) {
+        // collapse all whitespace in tags to a single escaped space
+        $v = preg_replace("/(\s+)/", '\\ ', $v);
         $tmp_tags[$k] = $v;
     }
     foreach ($fields as $k => $v) {
```
I'm very keen to 
 1. collapse influxdb & rrd support into a single function
 2. allow graphing from influxdb
 3. include MIB poller data in influxdb

but these can all happen after this is merged.  :+1: from me!

**Comment by f0o** [comment]
Personally I'd like to see a generic data store/get function that then dispatches on the reapective backend. Howeven backends must be multiplexed so they are `AND`.

I'll happily contribute this after merge :)

**Comment by laf** [comment]
You may have checked an older commit, a replace was added in this commit:

https://github.com/laf/librenms/commit/32f5980523f1be4799fcc53d76e01bd12f34e4e9

To take care of the special chars that influx says you can't have in a tag.

**Comment by laf** [comment]
Rebased

**Comment by Rosiak** [comment]
All good here :+1:

**Pull request merged**
