### PR TITLE
PHP dependencies update

### PR DESCRIPTION
**Pull request by murrant**
Removing dnoegel/php-xdg-base-dir (v0.1.1)

barryvdh/laravel-debugbar (v3.5.2 => v3.6.2)
barryvdh/laravel-ide-helper (v2.9.1 => v2.10.0)
composer/ca-bundle (1.2.9 => 1.2.10)
composer/composer (2.0.13 => 2.1.3)
composer/semver (3.2.4 => 3.2.5)
composer/xdebug-handler (1.4.6 => 2.0.1)
dapphp/radius (2.5.4 => 2.5.5)
doctrine/annotations (1.12.1 => 1.13.1)
doctrine/cache (1.10.2 => 2.0.3)
doctrine/dbal (2.13.0 => 2.13.2)
facade/flare-client-php (1.5.0 => 1.8.1)
facade/ignition (2.7.0 => 2.10.2)
fakerphp/faker (v1.14.1 => v1.15.0)
filp/whoops (2.12.0 => 2.13.0)
friendsofphp/php-cs-fixer (v2.18.4 => v2.19.0)
fruitcake/laravel-cors (v2.0.3 => v2.0.4)
guzzlehttp/psr7 (1.8.1 => 2.0.0)
laravel/dusk (v6.15.0 => v6.15.1)
laravel/framework (v8.40.0 => v8.49.2)
laravel/ui (v3.2.0 => v3.3.0)
league/commonmark (1.5.8 => 1.6.5)
league/flysystem (1.1.3 => 1.1.4)
monolog/monolog (2.2.0 => 2.3.0)
nesbot/carbon (2.46.0 => 2.50.0)
nikic/php-parser (v4.10.4 => v4.11.0)
nunomaduro/collision (v5.3.0 => v5.5.0)
nunomaduro/larastan (v0.7.4 => v0.7.10)
php-parallel-lint/php-parallel-lint (v1.2.0 => v1.3.0)
php-webdriver/webdriver (1.10.0 => 1.11.1)
phpseclib/phpseclib (3.0.7 => 3.0.9)
phpstan/phpstan (0.12.83 => 0.12.92)
phpstan/phpstan-mockery (0.12.13 => 0.12.14)
phpunit/phpunit (9.5.4 => 9.5.6)
predis/predis (v1.1.6 => v1.1.7)
psr/cache (1.0.1)
psr/http-factory (1.0.1)
psr/log (1.1.3 => 1.1.4)
psy/psysh (v0.10.7 => v0.10.8)
rmccue/requests (v1.8.0 => v1.8.1)
sebastian/global-state (5.0.2 => 5.0.3)
sebastian/type (2.3.1 => 2.3.4)
symfony/console (v5.2.6 => v5.3.2)
symfony/css-selector (v5.2.4 => v5.3.0)
symfony/debug (v4.4.20 => v4.4.25)
symfony/error-handler (v5.2.6 => v5.3.3)
symfony/event-dispatcher (v5.2.4 => v5.3.0)
symfony/filesystem (v5.2.6 => v5.3.3)
symfony/finder (v5.2.4 => v5.3.0)
symfony/http-foundation (v5.2.4 => v5.3.3)
symfony/http-kernel (v5.2.6 => v5.3.3)
symfony/mime (v5.2.6 => v5.3.2)
symfony/options-resolver (v5.2.4 => v5.3.0)
symfony/polyfill-ctype (v1.22.1 => v1.23.0)
symfony/polyfill-iconv (v1.22.1 => v1.23.0)
symfony/polyfill-intl-grapheme (v1.22.1 => v1.23.0)
symfony/polyfill-intl-idn (v1.22.1 => v1.23.0)
symfony/polyfill-intl-normalizer (v1.22.1 => v1.23.0)
symfony/polyfill-mbstring (v1.22.1 => v1.23.0)
symfony/polyfill-php72 (v1.22.1 => v1.23.0)
symfony/polyfill-php73 (v1.22.1 => v1.23.0)
symfony/polyfill-php80 (v1.22.1 => v1.23.0)
symfony/process (v5.2.4 => v5.3.2)
symfony/routing (v5.2.6 => v5.3.0)
symfony/stopwatch (v5.2.4 => v5.3.0)
symfony/string (v5.2.6 => v5.3.3)
symfony/translation (v5.2.6 => v5.3.3)
symfony/var-dumper (v5.2.6 => v5.3.3)
symfony/yaml (v4.4.21 => v4.4.26)

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Think you broke larastan or phpstan :)

**Comment by murrant** [comment]
Yeah, the update must have introduced new detections...

**Comment by Jellyfrog** [comment]
I'd suggest removing the phpstan/larastan updates for now and we can step thought the updates to see what changed. Support for factories is soon released also

**Comment by murrant** [comment]
I already did that @Jellyfrog however, I could not add the exceptions, because phpstan throws an error when there is not error to ignore, which is nice.

**Pull request merged**
