### PR TITLE
Added FAQ on where to update database credentials if they change

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Question, if credentials are set in .env.  Does anything use the config.php ones?

**Comment by laf** [comment]
> Question, if credentials are set in .env. Does anything use the config.php ones?

I thought polling / discovery did but I'm not managing to keep up with things now.

**Comment by murrant** [comment]
I'm not keeping up with things either.  Doesn't help when I write stuff that isn't merged yet or I throw away :)

**Comment by murrant** [comment]
Yes, credentials are always loaded through the Laravel config now.  Which means .env supercedes config.php

**Comment by murrant** [comment]
Except for the python processes... those use config_to_json.php

**Pull request merged**
