### PR TITLE
Auth AD URL

### PR DESCRIPTION
**Pull request by Munzy**
This adds auth_ad_url setting to the global settings for authentication.

image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Munzy** [comment]
Not sure how I can get the "auth_ad_url" in the web page updated as I set the config variables in settings.php files.

**Comment by murrant** [comment]
FYI, all languages fall back to the English translation.
The mix-manifest.json file should be updated by `lnms translation:generate`  Which will cause your browser to load the new version (you should include that file in the PR too).   Or CTRL-F5

**Comment by Munzy** [comment]
@murrant it asks for me to run composer to install depends, but those depends are being added to the repo? Any suggestions to get around that?

**Comment by murrant** [comment]
yeah, it needs to install development dependencies.  They are only being added to the vendor folder.

**Comment by murrant** [comment]
Afterward you can remove them again if you like by running `./scripts/composer_wrapper.php --no-dev`

**Comment by Munzy** [comment]
image

Removed unneeded translations.
Ran lnms translation:generate

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
