### PR TITLE
Fixed removing transports in alert rules

### PR DESCRIPTION
**Pull request by TheGreatDoc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Don't think that will work.  You will need to use dbGenPlaceholders() like I have in #9048

**Comment by TheGreatDoc** [comment]
It works, I tested it before submitting

**Comment by murrant** [comment]
@TheGreatDoc it shouldn't work, it should delete all.  See #9077.

**Comment by TheGreatDoc** [comment]
You are totally rigth. Closing this in behalf of #9077

**Pull request closed without merging**
