### PR TITLE
Alert template transport

### LINKED ISSUE #3125: Assign alert templates per transport
I think it would be very useful to be able to assign a default alert template per-transport.  This would make it possible to handle the different formats expected by different transports (ie. a template for html emails with links and maybe even inline graphs, a template for transports that only handle text, and a separate template for each transport that have quirky syntax for links).

Any thoughts on the best way to go about this without interfering with the per-rule alert template mappings?

I am considering adding a column for transport (default null), and if null use for all transports, then the same for the rule and using the most specific (use something like 'order by rule, transport nulls last' and take the first result).  Currently, transport would need to be a string since we don't have anything else to map it to.

### PR DESCRIPTION
**Pull request by ekoyle**
Resolves #3125 in a different way.  Gives access to the transport name within the template to allow things such as:

    {if %transport == mail}something email-specific{/if}

### CODE REVIEW

**Comment by ekoyle** [comment]
I have tested this in that it works in my environment, but I would appreciate if @f0o could take a look.

**Comment by f0o** [comment]
Without having validated the regex, :+1:

**Comment by ekoyle** [comment]
Along the same lines as escaping $, users could still use {} to do unexpected things (this was already the case).  Should I not bother with escaping '$'?

Also, is there something handling the template string to prevent SQL injection, since we aren't escaping '?

**Comment by laf** [comment]
Running on my home install to test code against existing alerts.

**Comment by f0o** [comment]
I don't really understand why you removed `addslashes`.
Having single or double quotes which are unescaped is quite dangerous for the template translation.

Besides the code works just well with `addslashes`.

Tested with `{if %transport == dummy}Awesome!{/if}` and indeed I get 'Awesome!' printed on the CLI. The negative test using `{if %transport == IDontExist}Awesome!{/if}` also works as expected (no output)

**Comment by ekoyle** [comment]
@f0o: it was escaping single quotes in the if condition, ie:

`{if %var == 'value'}` was expanded to `if obj['var'] == \'value\'`, which is invalid syntax.  This prevents the example in your docs from working.  Since all the relevant code is using double-quotes, it seemed relatively safe to just not escape single-quotes.

It is still escaping double-quotes, so `{if %var == "value"}` will cause syntax errors.

**Comment by ekoyle** [comment]
@f0o: It could just be a documentation bug, although I thought I tried with `{if %var == value}` syntax without success.

According to docs under Controls:
 
 - if-else (Else can be omitted):
 `{if %placeholder == 'value'}Some Text{else}Other Text{/if}`

**Comment by ekoyle** [comment]
Looks like I must have done something else wrong when I tried without quotes.  Reverted quoting foo.

**Comment by ekoyle** [comment]
I think so, as long as @f0o is okay with it.

**Comment by f0o** [comment]
:+1: merge when re-tested

**Comment by ekoyle** [comment]
We have been running this in production for a couple weeks now, any thoughts on how to test more?

**Comment by ekoyle** [comment]
*Sigh*... I just noticed another quoting issue... I can't create a link in my email template, as `<a href='url'>` gets changed to `<a href=\'url\'>`...  Is there some kind of workaround for that?  Do we need to look at actually parsing the template string instead of doing a bunch of replace()'s?

**Comment by f0o** [comment]
If you have the time for doing that, go ahead.

With v2 approaching I was looking into using twig as template engine..

**Comment by laf** [comment]
I'm sure @Mattz0r has used a href in his templates.

**Comment by Mattz0r** [comment]
Yes, I do use them. 

You have to put 

$config['alert']['transports']['mail'] = array('html'=>true);

In your config.php

This was added in #3138 

Cheers.

**Comment by ekoyle** [comment]
@Mattz0r: have you had issues with quotes (ie. template expanding to `<a href=\'...\'>`)?

Also, it wasn't in the docs, so I submitted #3221, which replaces the config option from #3138 to make it act like the rest of the email config options.  Do we know how many people are using `$config['alert']['transports']['mail'] = array('html'=>true);`, because I didn't take that into account?

**Comment by Mattz0r** [comment]
@ekoyle - Probably just me that uses that config option... As @f0o  was working on that aspect of the alerting module for me specifically, so if you want to make it better in terms of config option, go ahead!

Regarding HTML in the template, I have no issues at all, as it just parses HTML like you would expect.

**Comment by ekoyle** [comment]
Hmm... I must be doing something wrong, because all of my quotes are being
escaped in the output from my templates...

To be clear, I'm not having trouble with html in general, but with
backslashes being added before any quotes in my html.


On Tue, Mar 15, 2016 at 5:08 PM, Mattz0r <notifications@github.com> wrote:

> @ekoyle <https://github.com/ekoyle> - Probably just me that uses that
> config option... As @f0o <https://github.com/f0o> was working on that
> aspect of the alerting module for me specifically, so if you want to make
> it better in terms of config option, go ahead!
>
> Regarding HTML in the template, I have no issues at all, as it just parses
> HTML like you would expect.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/3148#issuecomment-197062861>
>



-- 
Eldon Koyle

**Comment by Mattz0r** [comment]
@ekoyle - I just logged in and checked my template. I'm using "" instead of ''

Here's one of my templates: http://pastie.org/private/o96pufcgklgdcgznvgfy5g

**Comment by ekoyle** [comment]
I should have tried that.  I think the right solution would be to not escape single quotes, but I'll just update the docs for this PR to avoid any unexpected security flaws.

**Pull request merged**
