### PR TITLE
feature: Add PoE support for CiscoSB #1746

### LINKED ISSUE #1746: PoE information from Cisco SB
Running a snmpbulkwalk on CISCOSB-POE-MIB::rlPoe with switchport 23 having a Cisco Access Point connected:
http://paste.ubuntu.com/11282099/

### PR DESCRIPTION
**Pull request by Rosiak**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

fix #1746

### CODE REVIEW

**Comment by laf** [comment]
We already have some poe stuff going on in includes/polling/ports.inc.php and includes/polling/ports/port-poe.inc.php. Sensors doesn't strike me as the place to have this but the stuff in the ports seems incomplete.

**Comment by Rosiak** [comment]
¯\_(ツ)_/¯
I don't see an issue in this. 
We do the same for dBm etc. for ports?

**Comment by laf** [comment]
But we already have poe code so it either all needs moving to sensors or needs putting together with the current poe code.

**Comment by laf** [comment]
@librenms/reviewers anyone else got comments / feedback?

**Comment by murrant** [comment]
Looks good, but the display string feels a little odd. Can I suggest this change?
"23 PoE Power" > "Port 23 PoE"

It is already in the Power section and PoE means power, where as the port number doesn't have enough context for me.

**Comment by Rosiak** [comment]
Anyways to kick travis in the butt?

**Comment by murrant** [comment]
@Rosiak if you log in with your GitHub account, you should be able to tell it to restart the build.

**Pull request merged**
