### PR TITLE
Cable Modem Graphs for TopVision OS

### PR DESCRIPTION
**Pull request by djamp42**
Graphs Total/Registered/Offline Cable modems for the TopVision CMTS.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @djamp42 

Could you add testdata to your PR ? 
https://github.com/librenms/librenms/blob/master/doc/Developing/os/Test-Units.md

Thanx

**Comment by djamp42** [comment]
Yup, updated test data, thanks

**Comment by PipoCanaja** [comment]
Thanx. But you should also run ./scripts/save-test-data.php etc etc. 

Thanx

**Comment by djamp42** [comment]
> Thanx. But you should also run ./scripts/save-test-data.php.

So when i run the following command

`./scripts/save-test-data.php -o topvision -m os -d `

it reads all the snmprec files and then hangs at listening endpoint. First time i've ever used this so it might be something obvious.  It never updates the topvision.json file.

```
  SNMPv3 USM SecurityName: simulator
  SNMPv3 USM authentication key: auctoritas, authentication protocol: MD5
  SNMPv3 USM encryption (privacy) key: privatus, encryption protocol: DES
  Maximum number of variable bindings in SNMP response: 64
  --- Transport configuration
  Listening at UDP/IPv4 endpoint 127.1.6.1:1161, transport ID 1.3.6.1.6.1.1.0
```


  Listening at UDP/IPv4 endpoint 127.1.6.1:1161, transport ID 1.3.6.1.6.1.1.0

**Comment by PipoCanaja** [comment]
It seems that your snmpsim config is not working properly. It could be the iptables / firewall rules on the machine. If you could troubleshoot in that direction, it would probably solve the issue. (look at the address and the port snmpsim uses, it is clearly non standard)

**Comment by djamp42** [comment]
So this is a custom graph and data doesn't get entered into the database.  @murrant in discord said the following. Can you let me know what else needs to be done if any?

> no, test data doesn't test rrd info, only database, so it doesn't make sense.

**Comment by PipoCanaja** [comment]
Right. Only the snmprec file gets data if the DB is not changed. So this looks good. 

@librenms/reviewers Could somebody else have a look ?

**Pull request merged**
