### PR TITLE
Updated BGP discovery code to perform autodiscovery if enabled

### PR DESCRIPTION
**Pull request by laf**
Even though we had a config option to enable discovery via BGP no code existed. Now added.

Fixes issue #1197

### CODE REVIEW

**Comment by f0o** [comment]
trigger ci

**Comment by paulgear** [comment]
The log_event code here feels like it belongs inside discover_new_device, with the discovery method passed in as a string/strings.

**Comment by laf** [comment]
Possibly, that was taken from the discover arp code and mimics how that is done.

**Comment by f0o** [comment]
:+1: from my side

**Comment by paulgear** [comment]
You should never trust that ARP discovery code; the guy who wrote it didn't know what he was doing. :-)

**Comment by laf** [comment]
Updated both ARP and BGP to use discover_new_device() to log.

**Pull request merged**
