### PR TITLE
Send kernel version to stats.librenms.org

### PR DESCRIPTION
**Pull request by crazy-max**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I suggest you try to deduce the environment and send that to stats.  More detections could be added overtime.

**Comment by murrant** [comment]
https://github.com/librenms/librenms-stats/pull/22

**Comment by crazy-max** [comment]
@murrant Ok now I only keep `major.minor` of kernel version to reduce fingerprint. Will look like this:

```
5.3
4.19
4.19-docker
```

**Comment by murrant** [comment]
Still doesn't feel quite right to me.  Why is -docker appended to one kernel version?

**Comment by crazy-max** [comment]
@murrant Sorry don't have time to work on this. You can close this PR if you want.

**Comment by murrant** [comment]
Closing for now.

**Pull request closed without merging**
