### PR TITLE
LibreNMS vrf-lite

### PR DESCRIPTION
**Pull request by nicearma**
New pull request with only 2 commit

Changes made:
* VRF-lite compatible
* Ipv4 SNMPv3 context compatible (VRF-Lite)
* Ipv6 SNMPv3 context compatible (VRF-Lite) (only DB and discovery/poller, not in the html view)
* Bgp SNMPv3 context compatible (VRF-Lite)
* OSPF SNMPv3 context compatible (VRF-Lite)
* HTML VRF-lite compatible (reference made by ipv4* tables)
* Disocovery route module
* HTML visual changes
* Add some MIBs
* Other global changes

### CODE REVIEW

**Comment by laf** [comment]
Hey @nicearma, I'm waiting for one of our 7k VDC's to be setup for me to test the code works. In the meantime I'm starting to review the code and below is my questions / queries. As this is a big PR, this may have quite a few questions :)

1. In html/includes/print-interface-adsl.inc.php and html/includes/print-interface.inc.php you have commented out printing ifIndex in the generate_port function. How come?

2. It looks like a lot of code formatting updates have snook in, especially for sections not related to the code changes. This isn't something that should normally happen in a PR but I'll leave @paulgear to comment on whether this needs clearing up or not as it's a good chunk of the PR :)

3. html/pages/device.inc.php contains code changes to the way smokeping integration works. Not sure if this is to fix a problem but the same applies for this as #2 above.

4. html/pages/device/overview.inc.php You've removed the include for includes/dev-overview-data.inc.php but this file does exist so will need putting back.

5. html/pages/device/overview.inc.php You've moved the location of syslog and eventlog includes which may or may not affect the output on the screen, I've not checked if it does but ideally the includes should stay in the same location unless their is a reason for it.

That's as far as I've got for now, I'll come back to the rest.

**Comment by nicearma** [comment]
Hello @laf, well some visual modification was part of my work.
I will try to explain some of them:
* *html/includes/print-interface-adsl.inc.php* and *html/includes/print-interface.inc.php* i dont really remember, but i think it was because they told me to put that way, only show the text value
* I made some change like '->" and " -> '  because in some part of the php was like echo ("<html value='some' "), for me the  html code have to have value="some" not value='some' and if the echo code have not vars, have to be '', but is not very important at the end
* In the *html/pages/device.inc.php* this is a problem with the space/ format code, this it was my IDE, so i dont know what to do with this, i made changes, but 99% of this change was for the vrf context adaptation (add variables to add  VRF-Lite to the menu, add SQL request for VRF-Lite)
* Yes 4 (html/pages/device/overview.inc.php) was one error of mine, i have to put (includes/dev-overview-data.inc.php) again, i can made changes in the PR?
* The *html/pages/device/overview.inc.php* is because that was "better", i told my company that this kind of changes was not a very good idea, they told me, they (librenms team) can add this changes if they want, if not..... (i really dont know what they will do if not)

If you have any other question i will be happy to answer

**Comment by laf** [comment]
Hi @nicearma Sorry it's took a few days to get back to you on this.

1. If the changes are unrelated to this PR then it would be good to push them out separately.

2. This is more the code formatting updates rather than the value='some' bits, understood the IDE you use has done this.

3. For this one, aside from the code formatting updates it does look like some changes have been made to smokeping integration. If this is needed then ideally this needs to be in a separate PR.

4. You can just revert the change in this branch and push the update, the PR will then update itself :)

5. Again for this ideally it needs to be it's own PR. Anything not related to the VRF work should be separated out to make reviewing the code easier.

I'll try and get to the rest of the code and testing as soon as I can.

**Comment by laf** [comment]
Some more checks into this now.

6. html/pages/device/overview/mempools.inc.php You've removed the div fluid class which should most likely stay.

7. html/pages/device/overview/ports.inc.php ifsep is now disabled and div used instead, unfortunately the columns are limited to 12 so with no checks on if more than 6 results exist from the sql query then the page formatting will break. I also think that cols need wrapping in a div class='row'.

8. html/pages/device/overview/processors.inc.php The fluid class has been removed here as well and most likely is still needed.

9. The PR has the route discovery in it and really should be separated out into a separate PR.

10. includes/defaults.inc.php Some minor formatting issues that need a few tweaks.

11. includes/polling/functions.inc.php Some minor formatting issues.

**Comment by paulgear** [comment]
Hi @nicearma, just wanted to reiterate @laf's comments - we need to break this down into more manageable PRs, each of which has a single purpose.  Please keep any formatting and stylistic changes in separate PRs to functionality.

**Comment by nicearma** [comment]
Well i will try to split the changes, make it 4, one only for the discovery-poller of vrf-lite, other for discovery of route table, and the other 2 with the visual changes, this way you can accept the discovery modules and if the visual you will have the choise to add or made it different (it hard because this was like they wanted). The only problem is i dont have the option to test my code to see if made the good changes.

**Comment by laf** [comment]
hi @nicearma, just wondering how you are getting on with splitting these changes out to different PR's?

**Comment by laf** [comment]
Closing this as it's split out into two separate PRs now.

**Pull request closed without merging**
