### PR TITLE
Eliminate if debug then echo

### PR DESCRIPTION
**Pull request by tuxis-ie**
This should remove all the useless-uses-of if-then-else to do debug output...

### CODE REVIEW

**Comment by laf** [comment]
Hi @tuxis-ie, you will need to rebase this commit before we can merge.

**Comment by laf** [comment]
Also, you need to sign the contributors agreement, see https://github.com/paulgear/librenms/commit/63f367683e15e4c100f47f05060893b8349a4c77 as an example.

**Comment by tuxis-ie** [comment]
Done, both...

**Comment by laf** [comment]
@tuxis-ie checking through the code now, scrutinizer has found two syntax issues which need to be resolved:

https://scrutinizer-ci.com/g/librenms/librenms/inspections/266f4e53-2165-425f-b339-126a1fb42a6a/issues/

**Comment by laf** [comment]
Once the two scrut issues are fixed then I think this is fine for a merge, just checked through all the files and all looks good. No graphing issues on my install for 30+ mins.

**Pull request merged**
