### PR TITLE
Don't call clean() on the inputs to the SNMP settings form

### PR DESCRIPTION
**Pull request by cjwbath**
The device SNMP settings form calls `clean()` on all the data it gets. This in turn calls `strip_tags()` which breaks some values that contain angle brackets. In my case I discovered it because one of my SNMPv3 authentication passwords has angle brackets - perfectly allowable I would say, but the value appeared truncated when updated to the database and then didn't work for SNMP to the device.

Since the database updates/inserts are parameterised anyway, it is inappropriate to "sanitize" this early and I've removed it. If we're worried about HTML tags in data, it's better to use `htmlspecialchars` at the point  where the data is rendered into HTML (which I've added here).

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Looks good, but need to go through and verify we aren't leaking any unsanitized data.

**Comment by murrant** [comment]
@cjwbath You should sanitize all the values displayed on this page, since you remove the incoming protection.  Otherwise it is js injection vulnerability.

**Comment by cjwbath** [comment]
@murrant I think I _have_ sanitized anything that potentially came from user input. Was there something specific you saw?

**Comment by murrant** [comment]
Pretty much all of them came from user or outside input in some way.

**Comment by cjwbath** [comment]
OK I have added some more escaping to cover stuff that should be validated elsewhere (i.e. numbers) and stuff coming from SNMP. But the original `clean()` that I got rid of only covered the form inputs.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
