### PR TITLE
Bootstrapping checkboxes, cont.

### PR DESCRIPTION
**Pull request by SourceDoctor**
Hopefully all checkboxes are bootstrapped now ;-)

The remaining Checkbox in user management "can modify password"
will bootstrapped automatically with merging #10511

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @SourceDoctor 
If you have a few minutes, could you have a look at this post  ? I am wondering if it could be linked. 
https://community.librenms.org/t/can-not-create-recurring-maintenance/10082

Thanx

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/can-not-create-recurring-maintenance/10082/2

**Comment by SourceDoctor** [comment]
should be fixed with #10793

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
