### PR TITLE
Alcatel-Lucent advanced discovery support.

### PR DESCRIPTION
**Pull request by joseUPV**
This contribution is work of paulierco and JoseUPV
Modifies #10672 (split aos os in three, aos, aos6 and aos7)
Modifies #11145 (split aos os in three, aos, aos6 and aos7)

Notification:

    Aos devices will be detected now as aos, aos6 or aos7.
    - Aos OS will be for Omnistack branch (ex. series 6200)
    - Aos6 OS will be for Aos6 branch (ex. series 6350, 6400)
    - Aos7 OS will be for Aos7 branch (ex. series 6800, 6900)

    Added multichassis support (temperature, state, fans)
    Added DDM support
    Changed processor discovery script to yaml discovery (old processor data will be lost)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 11322`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
Alcatel-Lucent (detected as aos) has three branch:
- OmniStack Branch (mibs/radlan): will remain discovered as aos
- AOS6 branch (mibs/nokia): will remain discovered as aos
- AOS7+ branch (mibs/nokia/aos7): will be discovered as aos7

**Comment by murrant** [comment]
Curious as to your reason to split out different versions of aos?  It seems there is some overlap.

**Comment by joseUPV** [comment]
Alcatel-Lucent (detected as aos) has three branch:

    OmniStack Branch (mibs/radlan): will remain discovered as aos
    AOS6 branch (mibs/nokia): will be discovered as aos6
    AOS7+ branch (mibs/nokia/aos7): will be discovered as aos7

Some features added (pulierco contribution):
- DDM discovery support for aos6 (yaml file)
- DDM discovery support for aos7 (discovery scripts)
- Multichassis temperature sensor discovery support for aos6 (yaml file)
- Multichassis temperature sensor discovery support for aos7 (discovery scripts)
- Multichassis state discovery support (yaml file)

**Comment by murrant** [comment]
What a mess they have made. 

Will need to add a notification to users about this change.

Please take care to reduce duplication as much as possible.

**Comment by joseUPV** [comment]
This test files will be remove after testers tried this pull request, they are old test files.
(
    [0] => aos_1
    [1] => aos_aos6 (created by me)
    [2] => aos_aos7 (created by me)
    [3] => aos_ls
    [4] => aos_omnistack (created by me)
)

**Comment by joseUPV** [comment]
Now. It's ready for testers.
Paulierco and me have tested it with:
- Omnistack LS 6212, 6224, 6248 and poe versions
- OmniSwitch 6350 standalone (only one chassis) and virtual-chassis (more than one chassis) and poe versions
- Omniswitch 6400 series
- Omniswitch 6860 series
- Omniswitch 6900 series only one chassis and multichassis.

Test files are from:
- Aos: OmniStack LS 6224P Alcatel-Lucent OS 1.7.0.13
- Aos6: OS6350-P24 6.7.1.108.R04
- Aos7: OS6860E-U28 8.5.255.R02

**Comment by joseUPV** [comment]
I will create new PR

**Pull request closed without merging**
