### PR TITLE
Adva FSP150cc Health Sensors

### PR DESCRIPTION
**Pull request by h-barnhart**
Adds the following health sensors for the Adva FSP150 family of MetroE devices:

- Temperature sensors on line cards.
- Temperature sensors on SFPs and optics
- Transmit and Receive optical power
- Laser Bias Current on optics
- Voltage used by line cards

Optic reading require the optic to provide digital optical monitoring (DOM) capabilities. These changes were tested using the following models from the Adva FSP150CC series of MetroE devices:

- 114Pro
- 206V
- XG116
- XG210

Updated MIBs to provide support for the XG116 model.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @h-barnhart 
Could you please rename all the MIB files using their official name ? (in the files, the name is the text before ```DEFINITIONS ::= BEGIN```
Thanx

**Comment by h-barnhart** [comment]
Can do. It would be cool if the vendor did it....

**Comment by PipoCanaja** [comment]
Almost good for the mib files. You still need to remove the extension to have the exact match between the MIB name and the file name.

**Comment by h-barnhart** [comment]
Fixed

**Comment by h-barnhart** [comment]
Replaced ADVA-MIB with the currently existing version in the master build. I got the "new" file from the latest MIB pack for firmware version, which is why I added it.

**Comment by murrant** [comment]
@h-barnhart I added test data.  Can you please review the json files to make sure they look right.

**Comment by h-barnhart** [comment]
> @h-barnhart I added test data. Can you please review the json files to make sure they look right.

I'll take a look at it. I added snmpsim files, did I miss a step creating for creating test data?

**Comment by murrant** [comment]
./scripts/save-test-data.php will run discovery and poller and dump the database to json files so we can check it for tests.  It does require working snmpsim to do that though.

**Comment by h-barnhart** [comment]
@murrant It looks oks. I'm going to run it on my test server to confirm.

**Comment by h-barnhart** [comment]
@murrant Your test data looks similar to mine. Should be good to go.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
