### PR TITLE
Fix for RouterOS LLDP discovery

### PR DESCRIPTION
**Pull request by mjducharme**
Only the first nine neighbors were correct on RouterOS - missing hexdec() led to the remaining neighbors being linked to the wrong ports. Ex. port 10 in hex was incorrectly linked to port 10 decimal when it should be 16 in decimal

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @mjducharme 
Looks good so far. Could you also generate some test data (new variant for your family of device) with a few LLDP neighbors at least ? The more feature enabled you have the better (meaning the testdata will cover a wider part of the RouterOS code). 
Thx

**Comment by mjducharme** [comment]
Test data submitted

**Comment by PipoCanaja** [comment]
> Test data submitted

I don't see any neighbor data in it ? Could you run a test data collection with at least one or 2 neighbors ?

**Comment by mjducharme** [comment]
That device has 12 neighbors. You can see them in the .snmprec. I was surprised that they do not show up in the .json file but since I've never done this before I thought that might be normal. Are they supposed to appear in the .json file somehow?

**Comment by PipoCanaja** [comment]
Most probably because the neighbors are default disabled. So they are not tested. At least the snmprec is here.

**Pull request merged**
