### PR TITLE
webui: Improve Services Page Look

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Before:
before_r
After:
after_r

### CODE REVIEW

**Comment by laf** [comment]
I like the tidying up of things, however the status check boxes now go away from how the devices page is - imho we should remain consistent as much as possible throughout the webui.

**Comment by FTBZ** [comment]
I've a lot of services, I think that a small refactor to save space will be nice. Now this is a long list to scroll. This PR is not affecting the space, only the readability?

**Comment by florianbeer** [comment]
Actually, I don't really think this does anything to tidy up things or make it more readable. It only moves the status color from the service name background to a strip on the left side and shifts around the other fields (e.g. description to the right, why?). Having the edit/delete buttons on top of each other also looks a bit weird to me, to be honest. At least we should have a bit of padding in between. The width of the "Last Changed" column was intentionally chosen to accommodate everything in one line.

Here's a screenshot of how the current services page looks on my installation:
screen shot 2017-11-06 at 21 10 00

**Comment by FTBZ** [comment]
Didn't notice that the description column was gone. This is important for me too like @florianbeer. This is where I add the detail about the test because sometimes you're using the same plugin for different tests. Like the http for checking https and certificat.

**Comment by Rosiak** [comment]
I believe the screenshots I included was bad, as it was taken on a rather small screen which could cause some confusion. Also I did include the descr column, I just forgot to name it.

Please take a look:
screen shot 2017-11-07 at 08 06 07
screen shot 2017-11-07 at 08 05 37

**Comment by FTBZ** [comment]
Nice shot! Can the green label be reduced to keeping it on one line and save space on the screen?

**Comment by laf** [comment]
I still don't think we should be moving the colour to the side, it's different from the devices page and we really should have some consistency.

**Comment by Rosiak** [comment]
@laf 
Perfectly understand that, I could do the same to the other pages if people think it's OK.
Otherwise I'll just close this PR.

**Comment by laf** [comment]
Well in all honesty and I don't know if this is the same still but that's how obse.... device page looks (or at least similar)

**Comment by Rosiak** [comment]
Ok.
I dunno how obs.. looks, as I got the inspiration from Incinga2.
I guess if people are not up for it, I'll close it.

**Comment by laf** [comment]
It does look nicer, but we would need all tables that do it the other way to be updated.

**Comment by Rosiak** [comment]
So, should I proceed with updating the other ones or just close this PR?

**Comment by laf** [comment]
I'm happy for the other ones to be updated. Just not happy about the disjointed look if we merged this one PR :)

**Comment by FTBZ** [comment]
I think we should start somewhere, no? The padding can be reduce IMHO.

**Comment by laf** [comment]
imho no, if we merged the alerts PR we would have 3 totally separate looks for tables like that. Sometimes our webui is the worst part of the software because it's changed by many people to look how they want, we need some kind of standards / consistency.

**Pull request merged**
