### PR TITLE
Add alert transport restriction to time range and device "map to"

### PR DESCRIPTION
**Pull request by louis-oui**
Feature request https://community.librenms.org/t/time-range-for-alert-transport/11336

Add the following in yellow color:
image
image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/time-range-for-alert-transport/11336/18

**Comment by murrant** [comment]
You might want to review #11389 
Otherwise you will have the same issues.

**Comment by louis-oui** [comment]
> You might want to review #11389
> Otherwise you will have the same issues.

thank you for the info

**Comment by murrant** [comment]
You should be storing time as UTC.  When it is saved, convert to UTC, when it is displayed to the user convert from UTC.

**Comment by louis-oui** [comment]
The problem is that if I store time in UTC, it is difficult to compare time and to manage daylight saving time in some countries. 

Where condition is:

`$where_time = "(at.timerange = 0 OR (at.timerange = 1 AND at.start_hr <= ? AND at.end_hr >= ? AND at.day LIKE ?))";`

For example, in my timezone Paris - France (GMT+2/UTC+2), if I set start hour to 1:00am, it will store start_hr 23:00:00 UTC in database. 

1. My alert is at 1:30 am, start_hr <= ? comparaison is 23:00:00 <= 23:30:00. Where condition matches. OK
2. My alert is at 5:30 am, it will compare 23:00:00 <= 03:30:00. Where condition does not match. NOK

=> We are unable to compare using UTC

My timezone has daylight saving time. UTC+1 in winter and UTC+2 in summer. Storing in UTC will change alert hour time after timeshift. 

https://www.timeanddate.com/time/change/france/paris

**Comment by louis-oui** [comment]
@murrant any comment on this PR ?

**Comment by murrant** [comment]
Yes, but if you don't solve that issue it means you can't have periods from 11pm to 1am for example...

So, the way you solve it is compare start and end.  If start < end then you check that the time is between them.  If the end < start, then you check that the time is outside the given times.

**Comment by murrant** [comment]
See https://github.com/librenms/librenms/blob/master/app/Models/AlertSchedule.php#L176

**Comment by louis-oui** [comment]
Thank you for you review @murrant 

> Yes, but if you don't solve that issue it means you can't have periods from 11pm to 1am for example...

If I am right, purpose of https://github.com/librenms/librenms/pull/11389 was to add the possibility to schedule maintenance overnight (i.e. for time before midnight to time after midnight). Am I correct ?

However, the purpose of this PR is to restrict alert during a period. Basically, the use case is to only alert during business working hours. Use case of only avoid alert overnight is not very common.

> So, the way you solve it is compare start and end. If start < end then you check that the time is between them. If the end < start, then you check that the time is outside the given times.

My implementation would be. Diff is made from last state PR you reviewed. 

```
diff --git a/LibreNMS/Alert/AlertUtil.php b/LibreNMS/Alert/AlertUtil.php
index 9dbc5f4a2..0837ad938 100644
--- a/LibreNMS/Alert/AlertUtil.php
+++ b/LibreNMS/Alert/AlertUtil.php
@@ -110,14 +110,20 @@ class AlertUtil
                 OR (at.invert_map = 1  AND (d.device_id != ? OR d.device_id IS NULL) AND (dg.device_id != ? OR dg.device_id IS NULL))
             )";
 
-        $now = CarbonImmutable::now(config('app.timezone'));
-        $where_time = "(at.timerange = 0 OR (at.timerange = 1 AND at.start_hr <= ? AND at.end_hr >= ? AND at.day LIKE ?))";
+        $local_now = CarbonImmutable::now(config('app.timezone'));
+        $now = CarbonImmutable::now('UTC');
+        $where_time = "(at.timerange = 0 OR
+            (at.timerange = 1 AND ((at.start_hr < at.end_hr AND at.start_hr <= ? AND at.end_hr >= ?)
+            OR (at.start_hr > at.end_hr AND at.start_hr >= ? AND at.end_hr <= ?))
+            AND at.day LIKE ?))";
+
 
         $query = "SELECT transport_id, transport_type, transport_name
             FROM alert_transports as at
             WHERE at.is_default=true AND at.transport_id IN (" . $query_mapto . ") AND " . $where_time;
         $params = [$device_id, $device_id, $device_id, $device_id, $device_id, $device_id, $device_id, $device_id,
-                   $now->toTimeString(), $now->toTimeString(), $now->format('%N%')];
+                   $now->toTimeString(), $now->toTimeString(), $now->toTimeString(), $now->toTimeString(),
+                   $local_now->format('%N%')];
         return dbFetchRows($query, $params);
     }
 
diff --git a/includes/html/forms/alert-transports.inc.php b/includes/html/forms/alert-transports.inc.php
index 7e020a5e2..e91f77552 100644
--- a/includes/html/forms/alert-transports.inc.php
+++ b/includes/html/forms/alert-transports.inc.php
@@ -95,8 +95,8 @@ if (empty($name)) {
         } else {
             $timerange_day = null;
         }
-        $details['start_hr'] = $start_hr;
-        $details['end_hr'] = $end_hr;
+        $details['start_hr'] = gmdate('H:i', strtotime($start_hr));
+        $details['end_hr'] = gmdate('H:i', strtotime($end_hr));
         $details['day'] = $timerange_day;
     }
     if (!is_array($vars['maps']) && $invert_map) {
diff --git a/includes/html/forms/show-alert-transport.inc.php b/includes/html/forms/show-alert-transport.inc.php
index 282b19891..37e4da293 100644
--- a/includes/html/forms/show-alert-transport.inc.php
+++ b/includes/html/forms/show-alert-transport.inc.php
@@ -63,8 +63,8 @@ if (is_array($transport)) {
         'is_default' => $is_default,
         'details' => $details,
         'timerange' => ($transport['timerange'] == true) ? true : false,
-        'end_timerange_hr' => ($transport['end_hr'] == null) ? '' : $transport['end_hr'],
-        'start_timerange_hr' => ($transport['start_hr'] == null) ? '' : $transport['start_hr'],
+        'end_timerange_hr' => ($transport['end_hr'] == null) ? '' : date("H:i", strtotime($transport['end_hr'].' UTC')),
+        'start_timerange_hr' => ($transport['start_hr'] == null) ? '' : date("H:i", strtotime($transport['start_hr'].' UTC')),
         'invert_map' => ($transport['invert_map'] == true) ? true : false,
         'day' => ($transport['day'] == null) ? '' : $transport['day'],
         'maps' => $maps,

```

**Comment by louis-oui** [comment]
> So, the way you solve it is compare start and end. If start < end then you check that the time is between them. If the end < start, then you check that the time is outside the given times.

**It does not work all the times.** 

Let's take an example. Assuming our timezone is GMT+2. This is an overnight case where start>end.

```
|          |    UI   |   DB   |
| start    |   23:00 | 21:00  |
| end      |   03:00 | 01:00  |
```
Example on second line fails.
```
| alert_time GMT |  start > alert_time     |  end < alert_time       | Result |
|   22:17        | (21:00 > 22:17) = True  | (01:00 < 22:17) = True  | Passed |
|   00:17        | (21:00 > 00:17) = True  | (01:00 < 00:17) = False | Failed |
```

My suggestion to implement 

```
if the end < start:
   (start < alert_time && end > (alert_time + 24:00) || (start + 24:00)< alert_time && (end+ 24:00) > (alert_time + 24:00))
```

```
|          |    UI   |   DB   | DB+1d  |
| start    |   23:00 | 21:00  |   --   |
| end      |   03:00 | 01:00  | 25:00  |
```
All tests are successful
```
| alert_time GMT |   start < alert_time    | (end+1d) > alert_time  | start< (alert_time+1d) | (end+1d) > (alert_time+1d)|
|       22:17    | (21:00 < 22:17) = True  | (25:00 > 22:17) = True |           ----         |        ----               | 
|       00:17    | (21:00 < 00:17) = False | (25:00 > 00:17) = True | (21:00 < 24:17) = True | (25:00 > 24:17) = True    |
```

**Comment by louis-oui** [comment]
All tests are OK

First test - not overnight
```
[root@librenms-dev /opt/librenms]$ echo 'select transport_id, transport_name, timerange, start_hr, end_hr from alert_transports;' | mysql -u root librenms
transport_id	transport_name	timerange	start_hr	end_hr
1	Teams	0	NULL	NULL
2	TEAMS HNO	1	01:00:00	04:00:00
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
81.42.14.1	sw-dc2-t01
[root@librenms-dev /opt/librenms]$ date +%T -s "00:13:13" ; date; date --utc
00:13:13
Sat Sep 12 00:13:13 CEST 2020
Fri Sep 11 22:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: OK
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 00:13:14 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #596/0:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 00:13:14 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "02:13:13" ; date; date --utc
02:13:13
Sat Sep 12 02:13:13 CEST 2020
Sat Sep 12 00:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 02:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #597/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 02:13:18 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
81.42.14.1	sw-dc2-t01
[root@librenms-dev /opt/librenms]$ date +%T -s "03:13:13" ; date; date --utc
03:13:13
Sat Sep 12 03:13:13 CEST 2020
Sat Sep 12 01:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: OK
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 03:13:14 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #598/0:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 03:13:14 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "05:13:13" ; date; date --utc
05:13:13
Sat Sep 12 05:13:13 CEST 2020
Sat Sep 12 03:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 05:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #599/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 05:13:19 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
81.42.14.1	sw-dc2-t01
[root@librenms-dev /opt/librenms]$ date +%T -s "06:13:13" ; date; date --utc
06:13:13
Sat Sep 12 06:13:13 CEST 2020
Sat Sep 12 04:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: OK
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 06:13:14 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #600/0:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 06:13:14 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "18:13:13" ; date; date --utc
18:13:13
Sat Sep 12 18:13:13 CEST 2020
Sat Sep 12 16:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 18:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #601/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 18:13:18 +0200
```
Second test - overnight
```
[root@librenms-dev /opt/librenms]$ echo 'select transport_id, transport_name, timerange, start_hr, end_hr from alert_transports;' | mysql -u root librenms
transport_id	transport_name	timerange	start_hr	end_hr
1	Teams	0	NULL	NULL
2	TEAMS HNO	1	21:00:00	01:00:00
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "22:13:13" ; date; date --utc
22:13:13
Sat Sep 12 22:13:13 CEST 2020
Sat Sep 12 20:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"

#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 22:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #589/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 22:13:19 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
81.42.14.1	sw-dc2-t01
[root@librenms-dev /opt/librenms]$ date +%T -s "23:13:13" ; date; date --utc
23:13:13
Sat Sep 12 23:13:13 CEST 2020
Sat Sep 12 21:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: OK
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 23:13:14 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #590/0:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 23:13:14 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "00:13:13" ; date; date --utc
00:13:13
Sat Sep 12 00:13:13 CEST 2020
Fri Sep 11 22:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 00:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #591/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 00:13:19 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
81.42.14.1	sw-dc2-t01
[root@librenms-dev /opt/librenms]$ date +%T -s "01:13:13" ; date; date --utc
01:13:13
Sat Sep 12 01:13:13 CEST 2020
Fri Sep 11 23:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: OK
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 01:13:14 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #592/0:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 01:13:14 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "02:13:13" ; date; date --utc
02:13:13
Sat Sep 12 02:13:13 CEST 2020
Sat Sep 12 00:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 02:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #593/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 02:13:19 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
81.42.14.1	sw-dc2-t01
[root@librenms-dev /opt/librenms]$ date +%T -s "03:13:13" ; date; date --utc
03:13:13
Sat Sep 12 03:13:13 CEST 2020
Sat Sep 12 01:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: OK
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 03:13:14 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #594/0:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 03:13:14 +0200
[root@librenms-dev /opt/librenms]$ grep ^81.42.14.1 /etc/hosts && sed -e 's|^81.42.14.1|#81.42.14.1|g' -i /etc/hosts || sed -e 's|#81.42.14.1|81.42.14.1|g' -i /etc/hosts
[root@librenms-dev /opt/librenms]$ date +%T -s "07:13:13" ; date; date --utc
07:13:13
Sat Sep 12 07:13:13 CEST 2020
Sat Sep 12 05:13:13 UTC 2020
[root@librenms-dev /opt/librenms]$ ./poller.php -h 11 -m ipmi &>/dev/stdout | grep -A100 'Start Alerts' | grep -B100 "End Alerts"
#### Start Alerts ####
Rule #2 (All): Status: NOCHG
Rule #5 (Not all): Status: NOCHG
Rule #9 (1): 
Status: ALERT
#### End Alerts ####
[root@librenms-dev /opt/librenms]$ ./alerts.php
Start: Sat, 12 Sep 2020 07:13:18 +0200
ClearStaleAlerts():
RunFollowUp():
RunAlerts():
Issuing Alert-UID #595/1:
 :: Transport msteams => string(43) "Microsoft Teams returned Error, retry later"
ERROR

RunAcks():
End  : Sat, 12 Sep 2020 07:13:18 +0200
```

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/time-range-for-alert-transport/11336/32

**Comment by PipoCanaja** [comment]
Bonjour @louis-oui 
Any update on this PR ? 
Bye

**Comment by SourceDoctor** [comment]
@louis-oui 
something new on this?
i think this might be a useful feature

**Comment by Jellyfrog** [comment]
First of all, thank you for your contribution!

We're closing this due to inactivity, feel free to reopen if you find the time to continue on this!

**Pull request closed without merging**
