### PR TITLE
Added Huawei MA5600T OIDs

### PR DESCRIPTION
**Pull request by PipoCanaja**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Negatifff** [comment]
Good day. Why request is closed?

**Comment by PipoCanaja** [comment]
Hi
Because you have to click to "create PR" yourself. I cannot create it myself and approve it afterward :)

**Comment by Negatifff** [comment]
Ok. I'm newbie and I don't know all details. But now request is closed and I can't create PR now. What should I do now?

**Comment by PipoCanaja** [comment]
My bad, I should not have clicked the button create :) I did not even know I could do it myself. 
Anyway, there is probably a way for you to re-create one PR, but I reopened this one.

**Comment by Negatifff** [comment]
thanks

**Comment by jozefrebjak** [comment]
@PipoCanaja This PR can be closed because of https://github.com/librenms/librenms/pull/11719

**Pull request closed without merging**
