### PR TITLE
Update Barracuda Spam Firewall product name with the current name (Barracuda Email Security Gateway)

### PR DESCRIPTION
**Pull request by salt-lick**
New product name change confirmed via Barracuda chat on May 9, 2018
I plan on extending this a bit further but I'll submit a pull for that later.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@salt-lick Do you have test data for this?

**Comment by salt-lick** [comment]
['Should be all you need ( Barracuda name change test data ) '](https://gist.github.com/salt-lick/a94869ce91249983310f85cdb173f4a0)
If I need to strip out anything else... let me know please.

**Comment by laf** [comment]
You need to add it to this PR :) If you could rebase it as well that would be good.

**Comment by laf** [comment]
Can you run this:

`./scripts/collect-snmp-data.php -h $hostname -v email_sg`

**Comment by laf** [comment]
Thanks for pushing that. I've added the relevant json test data.

FYI for the future, you can't alter OIDs to be non-numeric so .X.X.X.X isn't valid. I removed those lines.

**Pull request merged**
