### PR TITLE
Fixed widgets from updated dbFacile changes

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by centralscrutiniser** [comment]
This patch fixes Top Devices (CPU in my case), but not Top Interfaces. 

Andy

**Comment by centralscrutiniser** [comment]
Worse this time, I'm afraid - 

`root@librenms00:/opt/librenms# ./scripts/github-apply 9033
Checking patch html/includes/common/top-devices.inc.php...
error: while searching for:

use LibreNMS\Authentication\Auth;

$top_query = $widget_settings['top_query'];
$sort_order = $widget_settings['sort_order'];

$selected_sort_asc = '';

error: patch failed: html/includes/common/top-devices.inc.php:20
error: html/includes/common/top-devices.inc.php: patch does not apply
Checking patch html/includes/common/top-interfaces.inc.php...
Checking patch html/includes/common/worldmap.inc.php...
error: while searching for:
                    WHERE `disabled`=0 AND `ignore`=0 AND ((`lat` != '' AND `lng` != '') OR (`devices`.`location` REGEXP '\[[0-9\.\, ]+\]'))
                      AND `status` IN (".$widget_settings['status'].")
                    ORDER BY `status` ASC, `hostname`";
        } else {
        // Normal user - grab devices that user has permissions to
            $sql = "SELECT DISTINCT(`devices`.`device_id`) as `device_id`,`devices`.`location`,`sysName`,`hostname`,`os`,`status`,`lat`,`lng`

error: patch failed: html/includes/common/worldmap.inc.php:176
error: html/includes/common/worldmap.inc.php: patch does not apply`

Andy

**Comment by laf** [comment]
> Worse this time, I'm afraid -

This is most likely because you didn't remove the previous patch.

**Comment by centralscrutiniser** [comment]
Better now. Thanks. 

Both Interfaces and Devices working.

**Comment by centralscrutiniser** [comment]
Confirmed working on three diff installs.

Andy

**Pull request merged**
