### PR TITLE
device: Enable cisco-vrf discovery for junos os

### PR DESCRIPTION
**Pull request by zombah**
As cisco-vrf now works fine with Junos os it seems fine
to enable it by default

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Bad module name then if it's not cisco specific :(

I think we should update this to be just vrf, that will mean file name changes, doc updates, a check for the old config variable in includes/process_config.inc.php and set the new one to true if the old one was and then `discover_cisco-vrf` updating to `discover_vrf` in the `devices_attribs` table to that db selected modules work.

It's a big ask so if you don't fancy it, let me know and I'll do that.

**Comment by zombah** [comment]
Agree. Sure i'll do. VRF is specific for Cisco and Arista, maybe to choose vendor agnostic name, like mib name, mpls-vpn or mpls-l3vpn?

**Comment by laf** [comment]
You pick, basically it just needs to represent what it does now seeing as it's no longer cisco vrf specific.

**Comment by Zmegolaz** [comment]
I'd say "VRF" is fine, it's not vendor specific and is used in Juniper too. ("set instance-type vrf")

**Comment by zombah** [comment]
Yes i'll keep vrf, i found that it is used alot in webui,docs and etc places so i see no reason to create segmentation with other term variants.

**Comment by murrant** [comment]
Looks good to me too.   (obviously needs the schema to be moved up)

**Comment by zombah** [comment]
Rebased versus current master

**Comment by laf** [comment]
Awesome work @zombah. Thanks for going through all of that :D

**Pull request merged**
