### PR TITLE
fix: Some graphs broke due to stacked graphs, remove that change

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

@crcro can you check this please. I've removed the transparency on this as this doesn't work in rrdtool 1.4. I can't see a difference before and after this patch in 1.6 so not sure what the intention was with it.
If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by crcro** [comment]
@laf ... it should be visible only if using stacked graphs (have no issues with it, but also runnning rrdtool 1.7)

screen shot 2017-12-04 at 7 51 55 am

screen shot 2017-12-04 at 7 52 23 am

**Comment by laf** [comment]
It is only used when stacked graphs are enabled but it's not compatible with rrdtool 1.4.x which we need to support.

**Comment by crcro** [comment]
@laf ... able to reproduce bug, this seems to fix it.

**Comment by laf** [comment]
Thanks @crcro

**Pull request merged**
