### PR TITLE
MikroTik: Add Fan no. 3 and no. 4 to the discovery/routeros.yaml

### PR DESCRIPTION
**Pull request by netravnen**
Some MikroTik models has more than 2 fans installed. This PR is an attempt to solicit feedback on how best to expand the current discovery model to be able to fetch data concerning Fan no. 3 and no. 4.

#### Changes

Add

1. mtxrHlFanSpeed3, mtxrHlFanSpeed4 in `discovery/routeros.yaml`, and
2. custom objects for the same names in the `mikrotik/MIKROTIK-MIB` file.

#### Models

- [CCR2116-12G-4S+](https://mikrotik.com/product/ccr2116_12g_4splus)
- [CCR2216-1G-12XS-2XQ](https://mikrotik.com/product/ccr2216_1g_12xs_2xq)
- [CRS518-16XS-2XQ-RM](https://mikrotik.com/product/crs518_16xs_2xq)
- [CRS326-24S+2Q+RM](https://mikrotik.com/product/crs326_24s_2q_rm)

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] ~~If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.~~
- [ ] ~~If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).~~

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by netravnen** [comment]
The dev check returned 1 failure. Which I _presume_ is leftover from when I had the Fan no. 3 and 4 set to index 2 and 3. In this PR the indexes is set to 7003 and 7004.


```
There was 1 failure:

1) LibreNMS\Tests\YamlSchemaTest::testDiscoveryDefinitionSchema
routeros.yaml does not validate. Violations:
[modules.sensors.fanspeed.data[2].num_oid] Does not match the regex pattern ^(\.\d+)+\.?\{\{ \$index \}\}(\.\d+)*$
[modules.sensors.fanspeed.data[3].num_oid] Does not match the regex pattern ^(\.\d+)+\.?\{\{ \$index \}\}(\.\d+)*$

Failed asserting that false is true.

/opt/librenms/tests/YamlSchemaTest.php:149
/opt/librenms/tests/YamlSchemaTest.php:82
/opt/librenms/tests/YamlSchemaTest.php:76
/opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:174

FAILURES!
Tests: 696, Assertions: 5553, Failures: 1, Skipped: 2.
failed (153.09s)
```

**Comment by netravnen** [comment]
Is it intentional these two Regex statements are not identical... 😕 

https://github.com/librenms/librenms/blob/6d1b1ac1fa802cdd405477d27af5622e71324358/misc/discovery_schema.json#L232

https://github.com/librenms/librenms/blob/6d1b1ac1fa802cdd405477d27af5622e71324358/misc/discovery_schema.json#L416

**Comment by netravnen** [comment]
The CI checks are failing due to `^(\.\d+)+\.?\{\{ \$index \}\}(\.\d+)*$` not matching against `.1.3.6.1.4.1.14988.1.1.3.100.1.3.700[34]`

**Comment by netravnen** [comment]
With the modifications in this PR. I can now monitor fan 3 and fan 4.

**Comment by netravnen** [comment]
Have not changed anything in the original MIB file.

Unsure if it makes sense in the discovery/routeros.yaml file change fan 1 and fan 2 to pull values from the Gauge table, too.

**Comment by murrant** [comment]
@netravnen hah, didn't see this PR and I made #15289 

It will fix your issue in a more flexible way (but lose historical data).  What do you think?

**Comment by netravnen** [comment]
> I am against modifying the MIB.

@murrant Agreed! Modifying the MIB is an ugly workaround I found worked for me short-term. My PR was geared towards getting a discussion started how to best solve what I was trying to archive.

Will trial #15289 over the next couple of days. :-)

**Pull request closed without merging**
