### PR TITLE
Fix coding style old files (part 2)

### PR DESCRIPTION
**Pull request by job**
Ran `phpcbf` over all PHP files that were not touched in the last code style fixing round. I did a manual clean up on every file after phpcbf. Excluded third party libraries. This is my last code style PR.

### CODE REVIEW

**Comment by job** [comment]
I will squash this when you are ready to merge.

**Comment by job** [comment]
trigger ci

**Comment by laf** [comment]
@job 

adduser.php - The copyright has changed in this to 2013, we forked the code from 2012 so copyright needs to stay the same. - That's happened a number of files actually.

Some of the functions have been changed from:

functionname() {

to

functionname()
{

Is it because it then adds // end functionname() or can that behaviour be changed?

Aside from that those, I can't see any issues.

**Comment by laf** [comment]
p.s also needs a rebase.

**Comment by job** [comment]
trigger ci

**Comment by job** [comment]
This can be closed, continuing in #1449

**Pull request merged**
