### PR TITLE
Mikrotik - Updated MIB file and added Wireless Quality

### PR DESCRIPTION
**Pull request by Martin22**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @Martin22 
It seems that you need to compute again the tests. You can check travis here: 
https://travis-ci.com/github/librenms/librenms/jobs/302838035

**Comment by Martin22** [comment]
> Hi @Martin22
> It seems that you need to compute again the tests. You can check travis here:
> https://travis-ci.com/github/librenms/librenms/jobs/302838035

Hi @PipoCanaja 
Sorry, save-test-data.php does not generate a json file. How do I generate a json file from snmprec?

**Comment by PipoCanaja** [comment]
save-test-data is the one to do the job. If you cannot get it to work with the docs, then we'll generate for you.

**Comment by PipoCanaja** [comment]
By the way, please rename your snmprec file to routeros_wq.snmprec and restore the original routeros.snmprec file so we can keep both the old and the new. 
I'll do the JSON for you.

**Comment by PipoCanaja** [comment]
You did the wrong actions here in the last commit. You renamed a JSON file to SNMPREC which is not correct.

We need to restore the original JSON and SNMPREC files, and create a new variant for your data.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Pull request merged**
