### PR TITLE
Add web config option for HTML emails

### PR DESCRIPTION
**Pull request by ekoyle**
Add a config option with all the other alerting options for HTML emails.  I don't think the existing option worked, because $config['transports'][mail] = 1 instead of an array.

### CODE REVIEW

**Comment by laf** [comment]
All good but we need something adding to the docs so people know:

http://docs.librenms.org/Extensions/Alerting/#templates

If you can add something in then we can merge.

**Comment by ekoyle** [comment]
@laf: Documented, rebased, using schema 108 instead of 107.

**Comment by laf** [comment]
@f0o Any thoughts on this. I've tested both on and off and it sets the content-type correctly.

**Comment by ekoyle** [comment]
@Mattz0r: you will need to update your config now that this PR has been merged

**Pull request merged**
