### PR TITLE
Add more device fields to oxidized map configuration

### LINKED ISSUE #13599: Oxidized plugin map rule dropdown missing "hardware"
### The problem

Under `/settings/external/oxidized` there's the possibility to create map rules. New map rule supports a source dropdown containing hostname, os, type and sysOBJECTID. The dropdown item "hardware" is missing here, even though the commandline client does support it.
Example:
lnms config:set oxidized.maps.group.hardware.+ '{"regex": "/1820 24G/", "value": "nobackup"}'

Screenshot 2021-12-06 113235

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-66-g528d8e55b
DB Schema | 2021_11_17_105321_device_add_display_field (226)
PHP       | 7.3.31-1~deb10u1
Python    | 3.7.3
MySQL     | 10.3.31-MariaDB-0+deb10u1
RRDTool   | 1.7.1
SNMP      | 5.7.3
====================================

[OK]    Composer Version: 2.1.14
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
```

### What was the last working version of LibreNMS?

21.11.0

### Anything in the logs that might be useful for us?

```txt
Simple frontend problem, nothing in logs for that.
```

### PR DESCRIPTION
**Pull request by martinberg**
Fixes #13599 and adds missing options for source

oxidized

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by martinberg** [comment]
Note: Not sure if `type` is ever used or can be used

**Comment by murrant** [comment]
I'm also not sure ip will work, I'd have to look at the code.

**Comment by martinberg** [comment]
> I'm also not sure ip will work, I'd have to look at the code.

I think ip will work. It is fetched from the db at least and included in `misc/config_definitions.json` 

https://github.com/librenms/librenms/blob/e803fa57ac0920879cdfea4112545e421286810d/includes/html/api_functions.inc.php#L1455-L1457

https://github.com/librenms/librenms/blob/e803fa57ac0920879cdfea4112545e421286810d/misc/config_definitions.json#L4236-L4245

**Comment by murrant** [comment]
Where is mix-manifest.js?  Without that your new app.js won't be loaded because of browser caches.

**Review by murrant — APPROVED** [review]

**Pull request merged**
