### PR TITLE
WebUI - Display interface errors per second instead of accumulated

### PR DESCRIPTION
**Pull request by antonio-jose-almeida**
Hello,
I had a lot of difficulty in identifying the interfaces that were generating errors in my network because the value that was shown in the table was the accumulated value. I tried to identify a way to change the code to show the delta (I even considered using the rate but I think that to identify errors the delta value is more indicated)

librenms_changes

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Like it but the name is not good.  Delta from what?  Need to be able to convey that in the title.

**Comment by antonio-jose-almeida** [comment]
Hi, 
I've change the name to be more verbose. Now makes more sense?

**Comment by PipoCanaja** [comment]
Hi @antonio-jose-almeida 

Really like the idea. Current display is not very usable. 

I would probably go a little further here. 
- Leave the description as `Errors In` and `Errors Out`
- Display the delta value, but computed in a "per second" (or "per minute") value
- Add a Unit to make it clear

Cause the delta value you display, is taken between 2 polls. By default it is 5 minutes. But some users use different intervals (I use 1 minutes on some servers). In order to compare, dividing this "delta" value with the poller interval would give you "errors per second". Per minute might even be a little bit easier for the user, on interfaces with a low amount of trafic (and errors)

**Comment by antonio-jose-almeida** [comment]
Hello,
I tried to implement it as suggested. I think I never saw the "Eps" reference for errors per second but it was the acronym that occurred to me.

eps

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by PipoCanaja** [comment]
Thanx @antonio-jose-almeida !

**Comment by synnack** [comment]
Is there a button to toggle this behaviour or have the old Errors In/Out columns back as extra columns? It's really difficult to sort by interfaces that have error peaks (but not the current polling interval) with the current behaviour.

**Pull request merged**
