### PR TITLE
apc discovery: Get a count of banks before pulling info

### PR DESCRIPTION
**Pull request by vrillusions**
* On my device (AP7901 / AOS v3.9.0 / App v3.7.4) discovery would keep
  clobbering the bank and current sensor.  Looking in to it the oid
  should be used for current and not bank.  To fix this now it pulls
  a count of banks using the `rPDULoadDevNumBanks.0` oid. Per MIB that
  will return 0 if no banks are found.  In which case skip the bank
  detection.

* Also update PowerNet-MIB to v4.1.7 released 2015-08-05

### CODE REVIEW

**Comment by vrillusions** [comment]
I'd like to see someone that actually has an APC PDU with multiple banks (or even one) to test this out.  Only device I have doesn't have banks so unable to check that part.

**Comment by laf** [comment]
So with this we only poll if the APC unit has 1 or more bank. I'm assuming if no banks exist then this sensor doesn't exist? This could be a breaking change so we'd like to make sure it's good before merging.

**Comment by vrillusions** [comment]
That's correct in how it was setup and :+1: on more testing.  I only have the one AP7901 which doesn't have any power banks.  Even if we got some snmpwalk output it should confirm if this count updates... Hmm that actually wouldn't be a bad idea for testing is ask the community "run <command> against your device" and keep a repository of all them

**Comment by laf** [comment]
I'd be inclined to say we notify users we will be merging this and merge. It's unlikely we'll get anyone to test it otherwise :(

@librenms/reviewers thoughts?

**Comment by paulgear** [comment]
Yeah - let's give people some notice and then merge.  I'll drop a note on Twitter & the mailing list now.

**Comment by murrant** [comment]
Works fine on my APC 7932s with two powerbanks.

**Pull request merged**
