### PR TITLE
Added librenms/librenms-mins as subtree into mibs/

### PR DESCRIPTION
**Pull request by f0o**

### CODE REVIEW

**Comment by paulgear** [comment]
Just like the agent, there's no point in moving MIBs into their own repo if we merge them straight back in with a subtree.  It should be a submodule, or just pulled separately during install/update.

**Comment by f0o** [comment]
will do

**Comment by laf** [comment]
With submodules can you just git pull within the directory of it then git push the main librenms to update mibs? I did a test a while ago and couldn't get it working but that's most likely just me.

If it doesn't work like that then we need a way to keep the mibs upto date.

**Comment by laf** [comment]
Now it does look like it should work:

git submodule update --remote

**Pull request closed without merging**
