### PR TITLE
location map regex replace pattern only 

### PR DESCRIPTION
**Pull request by MrDragon**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by MrDragon** [comment]
I don't know if I did anything right... See https://community.librenms.org/t/location-mapping-regex-substitute/1054/3 - that's my submission, use it as you see fit :)

**Comment by murrant** [comment]
I think this needs some documentation updates and you need to fix the one style issue.

**Comment by laf** [comment]
Docs are definitely needed :)

**Comment by MrDragon** [comment]
Thank you for pointing me at the docs. As to the style issue, I did find two lines with trailing spaces (fixed). If there's another style issue, I may need a bigger hint :(
Thank you for your patience and guidance!

**Comment by laf** [comment]
imho it needs a bit more clarity in the docs, I can't tell from the example what it's doing.

**Pull request merged**
