### PR TITLE
Auto IPv6/IPv4 detection when adding host

### PR DESCRIPTION
**Pull request by murrant**
Fallback to ipv4 if snmpd isn't listening on ipv6 (as our example configures)
Update snmpd.conf example to listen on IPv6
refactor dnslookup() supports auto (ipv6 then ipv4) and hosts file for ipv4 at least.
Improve layout in the device snmp settings page

Tested adding:
ipv4 only
dual ipv4 listen only
dual dual listen

image

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
This changes the default behaviour. Doing nothing more than checking this branch out and trying to add a host via the webui I get:

`Already have host with this IP localhost (127.0.0.1)`

**Comment by murrant** [comment]
@laf good catch, I missed adding the boolean in the if statement when re-arranging.

**Comment by murrant** [comment]
Testing this I discovered something.
When adding a device with dual stack, you can add it via both IPv4 and IPv6 because we only have one "IP" field...

**Comment by murrant** [comment]
Maybe that only works for localhost since there is not an entry in the ipv6_addresses table...

**Comment by laf** [comment]
So here's the next one :)

Trying to add www.google.com as icmp only device and it tries to use fping6 as the binary :) Adding www.intel.com and it works fine as it tries fping.

**Comment by murrant** [comment]
That sounds correct to me, did you expect a different result?

**Comment by laf** [comment]
Yes as I don't have a working ipv6 setup so it failed.

**Comment by murrant** [comment]
Bahhhh, I'm guessing because we are doing a direct DNS lookup, we can't detect if IPv6 is functioning.

I really wish PHPs gethostbyname() supported IPv6

**Comment by MrMaus13** [comment]
Something like this?

```
function check_ipv6_reachable($hostname) {
  $record = dns_get_record($hostname, DNS_AAAA);
  if(IsSet($record[0]["ipv6"])) return exec("/usr/sbin/fping6 -a ".$record[0]["ipv6"]);
}

if(check_ipv6_reachable("www.google.com")) echo "IPV6 Works!";

```

**Comment by murrant** [comment]
unfortunately, we can't guarantee everything is pingable.  Aka some host blocks icmp echos but responds to snmp.

**Comment by MrMaus13** [comment]
Isn't it possible to use isSNMPable for that then?

```
function check_ipv6_reachable($hostname) {
  $record = dns_get_record($hostname, DNS_AAAA);
  if(IsSet($record[0]["ipv6"])) return isSNMPable($record[0]["ipv6"]);
}

if(check_ipv6_reachable("www.google.com")) echo "IPV6 SNMP Works!";
```

I'm just beginning to understand the code, apologies in advance if I'm saying something stupid. ;-)

**Comment by laf** [comment]
@murrant Can we close this or do you want to keep it open to come back to it?

**Comment by murrant** [comment]
Yeah, closing this.  Can't come up with a good solution.

**Pull request closed without merging**
