### PR TITLE
Distributed Polling backend

### PR DESCRIPTION
**Pull request by f0o**
#608 

Tested in large scale by @laf.

### CODE REVIEW

**Comment by laf** [comment]
:+1: 

Been running for 3 weeks now.

1 Web server
1 MySQL server
1 RRDCached / NFS server
6 Pollers.

NFS server isn't actually needed other than for access to create the rrd files however this can be done in other ways I'm sure.

**Comment by f0o** [comment]
Before merging let me update the docs one last time to add an example setup using NFS and rrdcsched :)

**Comment by laf** [comment]
No worries. I'm going to get a diagram done as well so we can reference that.

Won't be merging until @paulgear has a look at both these PRs :)

**Comment by paulgear** [comment]
I think I've mentioned before that I really hate NFS, so I don't plan to use this, but it looks like a nice small change that a lot of people would find really helpful.  Has anyone tested using a non-distributed poller with the distributed poller code?

**Comment by laf** [comment]
I've got it on my librenms.lathwood.co.uk setup - the only thing I might add is to disable the pollers menu option if distributed poller is disabled - or we could update the poller / poller-wrapper code to make use of this and record the same data we do now to show the poller duration.

**Comment by f0o** [comment]
Re: NFS: it's not required. Any distributed FS is fine. In essence, even webdav or sshfs as well as smb is fine.

The alternative would be a daemon that solely creates rrds. I think thats a bit too much tbh.

**Comment by laf** [comment]
My PR has been updated so the poller menu won't show if distributed poller is FALSE.

@f0o When the PR for the actual website is merged it will contain a new image you can use in the docs for show the capabilities of the distributed pollers: http://www.librenms.org/img/librenms-distributed-diagram.png

**Pull request merged**
