### PR TITLE
Initial adds for map group functionality.

### PR DESCRIPTION
**Pull request by jmacul2**
This functionality adds subsets of the network map based upon device groups.

https://librenms.foo/map/group=9  (as an example)

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
Tagging #1108

**Comment by laf** [comment]
Can you add something somewhere so people can select these rather than just going directly to the url?

**Comment by laf** [comment]
Any news @jmacul2 ?

**Comment by laf** [comment]
bump

**Comment by jmacul2** [comment]
Added UI for this issue.

**Comment by laf** [comment]
Thanks for the contribution :)

**Comment by vitalisator** [comment]
here is something that broke my maps, after two last commits the map is empty.

**Comment by laf** [comment]
Can you provide anymore info so that we can try and fix it rather than reverting?

**Comment by vitalisator** [comment]
see only blank page on maps, can I enable some logs there?

**Comment by laf** [comment]
Check your JavaScript developer console and add /debug=true/ to the url and check php debug link at bottom of page

**Comment by vitalisator** [comment]
got it (but no doubt how to put it into master)

diff --git a/html/includes/print-map.inc.php b/html/includes/print-map.inc.php
index 9c28a0b..8470e7a 100644
--- a/html/includes/print-map.inc.php
+++ b/html/includes/print-map.inc.php
@@ -41,11 +41,9 @@ $devices = array();
 
 $where = "";
 if (is_numeric($vars['group'])) {
-    $group = dbFetchRows('SELECT `pattern`, `name`, `description` FROM `device_groups` WHERE id = '.$vars['group']);
-    $group_pattern = rtrim($group['pattern'], '&&');
+    $group_pattern = dbFetchCell('SELECT `pattern` FROM `device_groups` WHERE id = '.$vars['group']);
+    $group_pattern = rtrim($group_pattern, '&&');
     $group_pattern = rtrim($group_pattern, '||');
-    $group_name = $group['name'];
-    $group_description = $group['group_descriptio'];
 
     $device_id_sql = GenGroupSQL($group_pattern);
     if ($device_id_sql) {
@@ -248,5 +246,4 @@ else {
 
 }
 
-if (is_numeric($vars['group'])) {
 $pagetitle[] = "Map";

**Comment by vitalisator** [comment]
#3174 

that helps :)

**Pull request merged**
