### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by xxorde**
I cleaned up unnecessary files and file privileges.
Most of the issues come from the debian analysis tool lintian, fix makes potential packaging easier.

I tested all changes on my instance of librenms.

Bugs look like this:
W: librenms: executable-not-elf-or-script usr/share/librenms/html/images/icons/flags/pk.png
...
W: librenms: windows-thumbnail-database-in-package usr/share/librenms/html/images/16/Thumbs.db

### CODE REVIEW

**Comment by laf** [comment]
Wow, large PR :)

On an initial glance things like images being changed to 644 is a great idea. A lot of php scripts have had perms changed to 755. especially anything in html as they are web executable so we really shouldn't be setting the permissions to be more lax. What's the reason for that?

The lib/vis changes, we just do a git subtree to include those so we shouldn't be removing them out as they will just get pulled back in when we update.

**Comment by xxorde** [comment]
It's my fault, I changed *.php to 0775 and than *.inc.php  to 0644.
I could change all php files to 644 again, if you like (or only the ones in html).

You have a lot of libraries / third party includes, which is nice for installation from source!
I think about building a debian package.
This is much easier when the upstream code does:
* not contain libraries / packets which are already included in other debian packages
* not contain compiled / minimized code (without source)
* not contain unnecessary bloat
* meet certain file permissions

Of course I do not want to remove things like fontawesome or jquery from librenms, its great that it is running out of the box. Especially if you want to use the git uptoupdate feature.  
Just want to make it easy for me to do so, or add the necessary "source code" and license. 

Cool, that you react so fast :+1:

**Comment by laf** [comment]
Thanks @xxorde 

The php files in / are ok to be 755 as they are all callable on their own,
Any other php files should be 644 (I realise some files in html are 755 but this is either a hangup from where we forked or a mistake). They only need 644 to run so should stay that way.

With regards to libraries and packages included in other debian packages. We won't be able to remove these libraries from our repo as without all of the included ones - something would be greak and we really don't want to make it harder to get up and running.

I don't think we have any compiled code, minimised we do but apart from some legacy javascript libraries we include the full source for everything, the non-minified versions may not be in the same place though.

Unnecessary bloat. we decided to live with the additional cruft that a lot of libraries provide even when we only need certain files. It enables us to keep them update easily.

**Comment by paulgear** [comment]
I think we need to have some discussion about this (and make some changes to Scrutinizer config) before we merge.

**Comment by xxorde** [comment]
@laf as mentioned before I do not want to remove any features or make installation and the life of the librenms users harder.
Just my own life easier :)
If I am really going to build a package (I am just evaluation cost / benefit at the moment) every change I have to make, I have to redo for each new release / snapshot.

Lets do a list with things we / I can do without negative side effects:
* set all direct execute scripts to 755
  * *.py *.sh *.pl
  * *.php in the root (/)
* set all images / html to 644
* remove bloat like:  html/images/16/Thumbs.db

If the list is OK for you, I could do the changes  an make a new pull request?




Many changes I have to make will never go upstream here.
Fore example remove things like Font Awesome / jquery and tell librenms where to find these on the system. I will see how to do this best.
In the long run, it would be cool to teach librenms how to find them on it's own, when it can't find the shipped files. But that is not an essential feature.
And of course, I do not want to cause more work for you than needed. :)

**Comment by laf** [comment]
@xxorde 

Those suggested changes seem ok to me :)

@paulgear what do you think?

**Comment by laf** [comment]
@paulgear. Do you have any thoughts on this?

**Comment by paulgear** [comment]
Certainly that list of things without side effects should be no problem.

The 3rd-party libraries issue is a bigger one; I'm happy if we can find a better way of organising it that works for @xxorde and us, but it really needs to be low overhead.

**Comment by laf** [comment]
@xxorde 

If you can update your PR to just include those items we've talked about we can get it merged :)

**Comment by xxorde** [comment]
@paulgear I am open for any idea :) 

@laf I start a new PR for this.

**Pull request closed without merging**
