### PR TITLE
fix: edgeswitch fans

### PR DESCRIPTION
**Pull request by crcro**
fix: fan state 2(operational) should be mapped to 0 (no error)

tested on: EdgeSwitch 24-Port 250W, firmware 1.8.0.5106045  - latest atm

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
I don't like OS checks, perhaps set a flag on the OS or sensor instead.

**Comment by crcro** [comment]
added bad_fanspeed to yaml definition and made checks based on it, hope this is a better approach

**Comment by laf** [comment]
I'm against this really. Such a bodge within the code base to support something all other vendors get right.

**Comment by murrant** [comment]
actually, @laf is right.  Maybe a different sensor type? Fan utilization?

**Comment by crcro** [comment]
@laf is right, reverted fan rpm changes, leaved only the operational mapping

**Comment by murrant** [comment]
@crcro looks like the other state generic values need to be corrected too.

**Comment by murrant** [comment]
@crcro The test files don't have any data for fan state sensors.  Care to capture it with `./scripts/save-test-data.php -h HOSTNAME`

**Comment by crcro** [comment]
@murrant I've runned `./scripts/save-test-data.php -o edgeswitch` after `./scripts/save-test-data.php -m sensors -o edgeswitch` and the resulted json is identical with the already existing one ...

**Comment by murrant** [comment]
@crcro sorry, wrong command.  I meant `./scripts/collect-snmp-data.php -h HOSTNAME`

**Pull request merged**
