### PR TITLE
Add trap-handlers for some Aruba Clearpass traps

### PR DESCRIPTION
**Pull request by dagbdagb**
This enriches process-related traps from Clearpass, such that alerts can identify the exact process being affected.
The relevant MIB-file is also added.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by dagbdagb** [comment]
My email address was set wrong in git when creating this. I do have a CLA in place.

**Comment by Jellyfrog** [comment]
You’ll still need to update the author for your commits before we can merge this

**Comment by laf** [comment]
@dagbdagb Would you mind rebasing this to pick up the fixed checks that are being flagged here. You will also need to update the style/formatting as per https://github.styleci.io/analyses/9bQovP?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

If you can then just edit the author for the commits to match you cla email that would be ace. https://stackoverflow.com/questions/3042437/how-can-i-change-the-commit-author-for-a-single-commit

**Comment by dagbdagb** [comment]
closing, making a fresh one.

**Pull request closed without merging**
