### PR TITLE
Poller service rebase

### PR DESCRIPTION
**Pull request by clinta**
Rebase of PR #1561.

### CODE REVIEW

**Comment by f0o** [comment]
Assigned @paulgear for this one.
This PR still has my :+1: :)

**Comment by laf** [comment]
Also :+1: from me.

We don't have to have users use this as default, it could be available as an alternative to cron until move live feedback can be given.

**Comment by spinza** [comment]
I'll run this as soon as it is out.  On >200 devices.

**Comment by laf** [comment]
Tagging @paulgear for comments. 

I've just put a PR through which adds 061.sql so one of us will end up rebasing and @clinta has had to do that a fair few times so far.

**Comment by spinza** [comment]
Any news guys?

**Comment by laf** [comment]
I believe we need to try and nail down a fix for mysql clusters so that those running multi master or master/slave setups won't be impacted.

And waiting on @paulgear for input.

**Comment by clinta** [comment]
@laf, I think I covered that in f2b45327. Do you think it needs more details? Cause details would all depend on how people are load balancing the connections to their MySQL masters. Since there isn't any specific guidance from the project on multi-master setups, I tried to keep it as a general warning.

**Comment by laf** [comment]
@clinta It's just something @f0o mentioned. 

I think a multi master setup will be unusual but anything else we can do to ensure we can still do locks?

**Comment by clinta** [comment]
@laf, not that I'm aware of. It's a known limitation in MariaDB. I think compared to the alternative of running some other service exclusively for maintaining locks, making sure the pollers use only one mysql server at a time is preferable.

[This](http://www.severalnines.com/blog/avoiding-deadlocks-galera-set-haproxy-single-node-writes-and-multi-node-reads) link describes how to create a listener in harproxy on a different port that uses only one node at a time.

**Comment by f0o** [comment]
@clinta my personal issue is the use of locks within the `*.php` files. So everybody is affected, not only the people who use the distributed setup. I'm happy with wrapping it, like `if($config['use_mysql_locks'] == true)` or else.
Keeping the locks in place reduces the ability to cluster any MySQL (MariaDB or MySQL, doesnt matter. Locks arent replicated eitherways).

But as stated earlier and on IRC: This is not a blocker for me.
If the rest of the team is fine with this, then I will not go on a rampage or anything. I assigned @paulgear because I personally wouldnt feel well merging this knowing of the introduced limitation in the basecode.

**Comment by clinta** [comment]
@f0o, fair point and I can add a config check, though I don't think that config check will change the practical behavior.

If the poll runs without obtaining a lock, you have the possibility of multiple pollers updating the same device at the same time. If two pollers run against different servers in a cluster and do obtain locks, you have the same danger. They won't fail to get a lock, it's just that the other poller won't be aware of its lock.

I can't think of a scenario where obtaining the locks will break anything that wouldn't already break if the poller runs without locking.

**Comment by f0o** [comment]
The issue I ran into was that a Lock was obtained on server A but the release was sent to server B.
Server A remains locked. This doesnt break instantly but it does stack up to a point where to the viewer at random devices cant be polled and debugging this issue turns into a nightmare if you're unaware of the entire lock situation.

Anyways, the suggested config-option is only usefull for those who do not run your poller-service but still use Multi-Master setups.

**Comment by clinta** [comment]
Interesting, I'm trying to figure out how that could happen because locks are always acquired and released in the same MySQL connection, that's why I have a different lock in python than in php. One of the advantages of the locks is that if the MySQL connection is closed or dies, the lock is automatically released.

**Comment by f0o** [comment]
@clinta interesting indeed!
If so this issue is very localized to my install and I've to dig in.

Regardless, I'm fine with a merge at current state

**Comment by paulgear** [comment]
@f0o Any progress on your issue?  I don't have any objections to this (once conflicts are resolved), but I haven't had a chance to run it up myself yet.

**Comment by f0o** [comment]
:+1: Merge after rebase

**Comment by paulgear** [comment]
I've got this activated and running on my system; it seems to work well.  One thing I couldn't find in the code is how it runs 'discovery.php -h new'.  It seems like that might not happen at all.

**Comment by clinta** [comment]
It doesn't, because it orderes queries based on last discovery date, devices that have never been discovered will automatically be at the top fo the queue, so it shouldn't be necessary.

**Comment by paulgear** [comment]
@clinta First, I want to say a big thanks for your work and your patience on this; I've been running it on my server for a day so far without issues, and it seems to have had a positive impact on poll times, which was an unexpected bonus: http://libertysys.com.au/imagebin/Q6ATBFAA.png

I think after a few people have used it, we should consider making this the default poller.  In fact, we may want to make it the default for new installs straight away.

I'd like to see the licensing tidied up.  Here are my suggestions in order of preference:

1. Mark it as GPLv3 licensed.  It will become so anyway by being a part of LibreNMS, and this in no way prevents you as the copyright holder from using it separately from LibreNMS under a different license.

2. Use the Apache 2.0 license as recommended by the FSF for permissive licenses, as it provides protection against patent bullies.

3. Include the full text of the BSD 2-clause license (either in the header or as a separate file), since we don't have a dedicated copy of it in LibreNMS.

**Comment by f0o** [comment]
bump :)

**Comment by paulgear** [comment]
Looks like we've had yet another SQL schema clash.  Please rename the file and I'll get this merged ASAP, @clinta.

**Comment by spinza** [comment]
Happy this is merged.  Will deploy some time this weekend.

**Comment by laf** [comment]
@clinta / @spinza 

Sorry for the short notice but we are just about to revert this PR. It appears to be causing issues for people who don't run the poller-service. So far @f0o's attempts to try and get it working haven't been 100 successful so we've taken the difficult decision to revert this.

I'd highly suggest you disable auto updates asap if you want to retain the current support and jump on irc asap so we can discuss.

**Pull request merged**
