### PR TITLE
Callback system for stats

### PR DESCRIPTION
**Pull request by laf**
Putting here ready for merging. Code should be good but suggestions are welcome.

### CODE REVIEW

**Comment by laf** [comment]
ps. don't merge this until we have a vm online to collect the stats. at which point i need to update the submission urls

**Comment by f0o** [comment]
I'm not 100% happy with uniqid as uuid. I'd prefer seeing RFC 4122, UUID version 4.

I can provide a single function to generate UUIDv4 if needed

**Comment by laf** [comment]
Go for it.

Out of interest what's up with uuid from php?

**Comment by paulgear** [comment]
http://stackoverflow.com/questions/2040240/php-function-to-generate-v4-uuid#15875555 has a small, elegant UUIDv4 function.

**Comment by f0o** [comment]
@paulgear that function fits good. Important is the use of openssl's entropy source over mt_rand, rand, uniqid, ...

**Comment by f0o** [comment]
@lafwood the docs for debian have a wrong patch. The PEAR package is not php5-pear, it's php-pear https://packages.debian.org/wheezy/php-pear :)

**Comment by laf** [comment]
ok, all good to go.

urls updated to point to https://stats.librenms.org (which has been updated with the suggested changes).

data cleared out so no stats in at the moment (I have a large install using it so when daily.sh runs it will create the first lot).

no logging on the web server so we should be good to go.

**Comment by paulgear** [comment]
+1 from me - any other comments?

**Comment by laf** [comment]
Nothing from me - I updated the uuid to use that function from stackoverflow. Credits are in comments within the function for it.

I do want to get the graphs visually looking better but for now it's a starting point.

**Pull request merged**
