### PR TITLE
Update Teltonika Sensors for FW R_00.07.02

### PR DESCRIPTION
**Pull request by hjcday**
Updated MIB file for the RUTX series and RUT360 devices. 
Now able to capture I/O state data and byte transfer totals

Updated snmprec data

Changes does not break monitoring for earlier FW versions.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [N/A] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@hjcday looks like your snmpsim is broken.  I'll try to generate it when you get a chance.

**Comment by murrant** [comment]
Make sure you check the json file to see if the data matches your expectations.

**Comment by hjcday** [comment]
@murrant All data in the json file is as expected. Thank you for helping with this. Tried removing and reinstalling snmpsim (multiple different versions) and even just launching snmpsimd by itself gave the same error. Who knows...
All good to be approved.

**Comment by murrant** [comment]
@hjcday did you install it via distribution packaging or pip?  (Discord might be a better place to discuss that issue)

**Review by murrant — APPROVED** [review]

**Pull request merged**
