### PR TITLE
Adding support for Cisco SB SX550X-24F switch

### PR DESCRIPTION
**Pull request by Pluppo**
This pull request adds support for Cisco Small Business SX550X-24F switch by adding sysObjectID .1.3.6.1.4.1.9.6.1.1001 in the ciscosb discovery module.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Your test-data doesn't match, did you generate it with https://docs.librenms.org/Developing/os/Test-Units/ ?

**Comment by Pluppo** [comment]
Yes, I tried to follow the instructions. I ran the following:
./scripts/collect-snmp-data.php -v sx550x-24f -h nameofhost
./scripts/save-test-data.php -v sx550x-24f -o ciscosb

This generated the files that I added to this PR.

I ran this again now and noticed that there was a slight change in the snmprec file, I have updated it now.

**Comment by PipoCanaja** [comment]
@Pluppo Are you sure that your LibreNMS is uptodate with master ? Could you check your ./validate.php ?

**Comment by Pluppo** [comment]
@PipoCanaja I was collecting these files from a production server, so it was not up to date. I have now installed a new server for development, and managed to collect a new snmprec file.

I was not able to get snmpsim to run however, getting this error message:
ciscosb_sx550x-24f: Could not connect to 127.1.6.1, please check the snmp details and snmp reachability

**Comment by Pluppo** [comment]
I got snmpsim working again, had to delete the /tmp/snmpsim folder. After that I was able to run ./scripts/save-test-data.php --snmpsim. Updated json file committed.

**Comment by PipoCanaja** [comment]
Hello @Pluppo 
Thanx for your contribution. Looks good !

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
