### PR TITLE
Fixing HP Proliant state sensors

### PR DESCRIPTION
**Pull request by mikenowak**
The support to HP Proliant disk discovery was originally introduced at #6124.

However that code contains a few errors that prevent it from doing what it was intended to do.

1) The MIB that contains cpqDaPhyDrvStatus and cpqDaPhyDrvSmartStatus is **CPQIDA-MIB**, not 
CPQSINFO-MIB.

2) The OID in the code that iterates the array in order to find the disk number should drop the last digit (.1) as that indicates the disk in position (1) and we end up missing the Disk # as follows:
```
Sensor Added: state cpqDaPhyDrvSmartStatus 10.0 Disk #
Sensor Added: state cpqDaPhyDrvStatus 00.0 Disk #
```

Having made the changes described herein, the following is seen in the recent events

```
State sensor Disk # has changed from (0) to (2)
State sensor Disk # has changed from (0) to (2)
Sensor Updated: state cpqDaPhyDrvSmartStatus 10.0 Disk #1
Sensor Updated: state cpqDaPhyDrvStatus 00.0 Disk #1
```

The only other issue that I can name is that the states are not expanded properly in the UI, i.e. 2 should equal to OK.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the fix :)

I think if you change:

`create_sensor_to_state_index($device, $state_name, $index);`

to:

`create_sensor_to_state_index($device, $state_name, $x . $index);`

It should fix the display issue, give it a try and update this PR.

**Comment by mikenowak** [comment]
@laf,

thanks for that - I've added the change suggested by you and now the states are represented by nice bootstrap style buttons :)

I've also took this opportunity to extend this code and implement the following:

1) Added support for querying:
* raid ctrl accelerator status
* power supply status
* system fan status

2) Set the labels for the above to `CTRL # Status`, `PSU # Status`,  `FAN # Status`, and I've renamed `Disk #` to `HDD #`. Shall there be a naming convention in place that I am not aware of please let me know.

3) Added checks for PSU and FAN to ensure that they are truly installed `$temp[$index][$tablevalue[5]] == 'present'`, so that we wont alert if the component is not present due to such and such system configuration rather than failure.

4) Set `state_draw_graph` to 0 in all instances as I understand this would prevent the graphs from being created for these states, as these would be meaningless in my opinion. Please correct me if I am missing something here.

5) Last but not least, removed the SMART check as I am not getting anything out of that OID on my test system and based on my experience the SMART errors would result in `cpqDaPhyDrvStatus` becoming `predictiveFailure`.

Please let me know if you need anything else.

**Comment by f0o** [comment]
I think travis died on this one

**Comment by laf** [comment]
> Set state_draw_graph to 0 in all instances as I understand this would prevent the graphs from being created for these states, as these would be meaningless in my opinion. Please correct me if I am missing something here.

Well I'd say graphs are still useful. They show the historic state of the sensors over time which can be useful

> Last but not least, removed the SMART check as I am not getting anything out of that OID on my test system and based on my experience the SMART errors would result in cpqDaPhyDrvStatus becoming predictiveFailure.

I think it might be better to leave them in.

With this amount of changes, can you submit test data as well so we can ensure this code works going forward. https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

**Comment by Rosiak** [comment]
Just want to add in that state_draw_graph to 0 doesn't make any difference right now. Code to enforce this was never implemented, but hopefully will be with time.

**Comment by mikenowak** [comment]
> I think travis died on this one

Wrong number of spaces, should be good now

> Well I'd say graphs are still useful. They show the historic state of the sensors over time which can be useful

>Just want to add in that state_draw_graph to 0 doesn't make any difference right now. Code to enforce this was never implemented, but hopefully will be with time.

OK, thanks for confirming - this is now reverted to original value of 1.

> I think it might be better to leave them in.

OK, I'll try to do something smart here, since both of these come from the same snmp table.

>With this amount of changes, can you submit test data as well so we can ensure this code works going forward. https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

OK, will allocate time to this next week.

**Comment by mikenowak** [comment]
Slight correction regarding the SMART status.

I just checked ILO 3 and 4 on Proliants G7, Gen8 and Gen9 and I dont see this exposed anywhere.

So my current thinking is that it isn't really needed unless somebody can prove otherwise please.

**Comment by laf** [comment]
Here's some test data someone else has previously submitted which has the OID for the smart status:

```
.1.3.6.1.4.1.232.3.2.5.1.1.57.1.0 = INTEGER: 2
.1.3.6.1.4.1.232.3.2.5.1.1.57.1.1 = INTEGER: 2
```

**Comment by murrant** [comment]
Unless you update to the state code to the new format, you can't change existing state translations.

https://docs.librenms.org/Developing/Sensor-State-Support/

**Comment by murrant** [comment]
This currently cannot be tested. We don't discover sensors until the second discovery, because we poll 'hardware' instead of discover it.

**Comment by murrant** [comment]
@mikenowak If they weren't in this, then you will need to open a new pull request.

**Comment by murrant** [comment]
That's odd it works on my system.  Can you please stop by discord or community sometime to troubleshoot.

**Pull request merged**
