### PR TITLE
Disable Gridster after window resize when Gridster is/should be disabled

### PR DESCRIPTION
**Pull request by tim427**
This will fix issue #13611

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This seems to be a 100ms loop that only disables gridster, never enables it... should it ever be enabled?

**Comment by tim427** [comment]
> This seems to be a 100ms loop that only disables gridster, never enables it... should it ever be enabled?

It only triggers when the window is resized (which is problem with gridster); after resize of the browser window, gridster is unwantedly reactivated again

With this addition the preferred state will be checked (`gridster_state`) and disabled again when this state is prefered.

By adding a `console.log('gridster disabled');` before `gridster.disable();` and `gridster.disable_resize();`, you could see/verify this is only executed once, after a window resize event.

I've tested all scenarios;
- Desktop browser; "Edit Dashboard"-enabled -> stays moveable/resizeable after window resize
- Desktop browser; "Edit Dashboard"-disabled -> stays non-moveable/resizeable after window resize (which is a fix)
- Mobile browser; "Edit Dashboard"-enabled -> stays moveable/resizeable (which is a fix)
- Mobile browser; "Edit Dashboard"-disabled -> stays non-moveable/resizeable (which is a fix)

**Comment by murrant** [comment]
Is there any event we can listen for instead of a busy loop?

**Comment by murrant** [comment]
Nevermind, I totally mis-read the code.  I thought it was calling itself in the setTimeout()

**Review by murrant — APPROVED** [review]
Nice work!

**Pull request merged**
