### PR TITLE
Support for TrueNAS-SCALE (merging with existing truenas.yaml)

### LINKED ISSUE #14881: TrueNAS / FreeNAS Storage poller zilstat data pulled into wrong sensor, zpool state sensor updates with storage size value
### The problem

After recent update of Truenas SCALE Bluefin I noticed LibreNMS spams `Error discovering storage module. Check log file for more details.` in Event Log.

librenms.log has this:
```
[2023-03-07T07:16:33.612927+00:00] production.ERROR: Error discovering storage module for turbofreenas.lan. TypeError: Unsupported operand types: string * string in /opt/librenms/includes/discovery/storage/freenas-zpool.inc.php:13
Stack trace:
#0 /opt/librenms/includes/include-dir.inc.php(6): include()
#1 /opt/librenms/includes/discovery/storage.inc.php(7): require('...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(106): discover_device()
#4 {main}
[2023-03-07T07:16:33.679870+00:00] production.ERROR: Unsupported operand types: string * string {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string * string at /opt/librenms/includes/discovery/storage/freenas-zpool.inc.php:13)"}
[2023-03-07T07:16:36.789458+00:00] production.ERROR: No Storage {"userId":2,"exception":"[object] (LibreNMS\\Exceptions\\RrdGraphException(code: 0): No Storage at /opt/librenms/includes/html/graphs/device/storage.inc.php:14)"}
[2023-03-07T07:16:36.807317+00:00] production.ERROR: No Storage {"userId":2,"exception":"[object] (LibreNMS\\Exceptions\\RrdGraphException(code: 0): No Storage at /opt/librenms/includes/html/graphs/device/storage.inc.php:14)"}
[2023-03-07T07:16:36.925426+00:00] production.ERROR: No Storage {"userId":2,"exception":"[object] (LibreNMS\\Exceptions\\RrdGraphException(code: 0): No Storage at /opt/librenms/includes/html/graphs/device/storage.inc.php:14)"}
/opt/librenms/discovery.php 38 2023-03-07 07:16:44 - 1 devices discovered in 27.33 secs
```

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.1.1 (2023-02-09T19:33:37+00:00)
DB Schema | 2022_08_15_084507_add_rrd_type_to_wireless_sensors_table (248)
PHP       | 8.1.15
Python    | 3.10.10
Database  | MariaDB 10.5.19-MariaDB-1:10.5.19+maria~ubu2004
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

### What was the last working version of LibreNMS?

_No response_

### Device info

TrueNAS SCALE 22.12.1

### Discovery output

[https://o.o5.ddns.net/M3iHY](https://o.o5.ddns.net/M3iHY)

### Poller output

[https://o.o5.ddns.net/iyMEX](https://o.o5.ddns.net/iyMEX)

### PR DESCRIPTION
**Pull request by jiannelli**
Includes support for TrueNAS-SCALE (as a merge with truenas.yaml that has suport for Truenas-CORE / FreeNAS).

TrueNAS-SCALE uses TRUENAS-MIB; TrueNAS-CORE uses FREENAS-MIB.
Many OIDs overlap and have different meaning.

Rationale of this approach:
- All the editions are considered the same os wether it is SCALE  or CORE, no matter if there are different products editions with different underlying operative systems (linux / freebsd).
- Much longer and complex truenas.yaml
- Conditionals with skip_values are used on each OID and FREENAS-MIB:: or TRUENAS-MIB:: to avoid overlaps.

Fixes #14881 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
So, those MIBS are basically the same, except someone changed the structure of zpoolTable, datasetTable, and zvolTable...  But the sensors defined here use the same numeric OIDs.  So you can just use TRUENAS-MIB for both OS and remove all your conditionals in this yaml.

The place you need to have conditional code is in the storage code.  Despite the underlying OS changing, these would still be considered the same OS according to LibreNMS.

Don't forget to include test data.  Thanks!

**Review by laf — CHANGES_REQUESTED** [review]
...

**Comment by jiannelli** [comment]
**Differences in MIBs from FREENAS-MIB to TRUENAS-MIB**

- removed ZPoolHealthType (SYNTAX INTEGER).
- changed zpoolHealth type from ZPoolHealthType to DisplayString

- changed AlertLevelType with different integer codes.

- removed dataset OBJECT IDENTIFIER ::= { zfs 2 } causing cascade shift of 1 in OID numbers:
  zvol    OBJECT IDENTIFIER ::= { zfs 3 } to { zfs 2 } overlaps with FREENAS-MIB dataset
  arc     OBJECT IDENTIFIER ::= { zfs 4 } to { zfs 3 } overlaps with FREENAS-MIB zvol
  l2arc   OBJECT IDENTIFIER ::= { zfs 5 } to { zfs 4 } overlaps with FREENAS-MIB arc
  zil     OBJECT IDENTIFIER ::= { zfs 6 } to { zfs 5 } overlaps with FREENAS-MIB l2arc

- renamed zpoolDescr to zpoolName

- removed zpoolAllocationUnits, zpoolSize, zpoolUsed, zpoolAvailable causing cascade shift of 4 in OID numbers:
  zpoolReadOps        { zpoolEntry 8 } to  { zpoolEntry 4 } overlaps with FREENAS-MIB zpoolSize
  zpoolWriteOps       { zpoolEntry 9 } to  { zpoolEntry 5 } overlaps with FREENAS-MIB zpoolUsed
  zpoolReadBytes      { zpoolEntry 10 } to { zpoolEntry 6 } overlaps with FREENAS-MIB zpoolAvailable
  zpoolWriteBytes     { zpoolEntry 11 } to { zpoolEntry 7 } overlaps with FREENAS-MIB zpoolHealth
  zpoolReadOps1sec    { zpoolEntry 12 } to { zpoolEntry 8 } overlaps with FREENAS-MIB zpoolReadOps
  zpoolWriteOps1sec   { zpoolEntry 13 } to { zpoolEntry 9 } overlaps with FREENAS-MIB zpoolWriteOps
  zpoolReadBytes1sec  { zpoolEntry 14 } to { zpoolEntry 10 } overlaps with FREENAS-MIB zpoolReadBytes
  zpoolWriteBytes1sec { zpoolEntry 15 } to { zpoolEntry 11 } overlaps with FREENAS-MIB zpoolWriteBytes

- changed ZvolEntry  ::= SEQUENCE (types, names and entries) causing cascade shift of 1 in OID numbers:
  zvolUsedBytes       { zvolEntry 3 } overlaps with FREENAS-MIB zvolAllocationUnits
  zvolAvailableBytes  { zvolEntry 4 } overlaps with FREENAS-MIB zvolSize
  zvolReferencedBytes { zvolEntry 5 } overlaps with FREENAS-MIB zvolUsed

 - removed zfsArcP OBJECT-TYPE
 
 - Added hddTempTable (hard disk temperature table)

**Comment by murrant** [comment]
So... you agree with me? There is no reason to use the old MIB for the yaml sensors except for zpoolHealth.

**Comment by murrant** [comment]
ixSystems really bungled the MIB update... They could have just added a new zpoolTable at a new oid and marked the old one as deprecated.

**Comment by jiannelli** [comment]
Thanks for reviewing @laf and @murrant!

After putting a lot of focus in this I think I'm missing something. I would love some guidance with an example or something so we are all on the same track. I see no other choice as keeping the yaml as it is, to make core and scale work and for the sake of consistency and readability.

Yes the mibs are basically the same, but the OIDs changed a lot. Al least half of the sensors OIDs overlaps and I think are in need of conditionals, they exist in both MIBs but with different meanings. I think that if librenms just uses TRUENAS-MIB for both editions (removing all conditionals) we would have problems. i.e.: 

### Example in practice
If our device is a TRUENAS-CORE and we use TRUENAS-MIB (made for SCALE) we would discover:
num_oid: .1.3.6.1.4.1.50536.1.4.1.{{ $index }}  oid: TRUENAS-MIB::zfsL2ArcHits  
but we would actually get the incorrect information from
num_oid: .1.3.6.1.4.1.50536.1.4.1.{{ $index }}  oid: FREENAS-MIB::zfsArcSize    

**Correct: Using conditionals and query uses FREENAS-MIB:**
This PR branch
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OteQUSa' '-Ih' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ixsystems' 'udp:HOSTNAME:161' 'FREENAS-MIB::zfsL2ArcHits']
FREENAS-MIB::zfsL2ArcHits.0 = 0  

**Incorrect: Without conditionals only using the new TRUENAS-MIB:**
https://github.com/librenms/librenms/blob/71646d61d2c06c35e4eaa7d5a71cd695c9822981/includes/definitions/discovery/truenas.yaml
SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OteQUsa' '-Ih' '-m' 'TRUENAS-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/ixsystems' 'udp:HOSTNAME:161' 'zfsL2ArcHits']
zfsL2ArcHits.0 = 153623  

**This is similar (but the reverse) librenms behaviour that happens without this PR fix i.e.:**
If our device is TRUENAS-SCALE librenms uses FREENAS-MIB (made for CORE) and it discovers:
oid: FREENAS-MIB::zpoolTable
num_oid: .1.3.6.1.4.1.50536.1.1.1.1.7.{{ $index }}      FREENAS-MIB::zpoolHealth
but actually gets the incorrect information from
num_oid: .1.3.6.1.4.1.50536.1.1.1.1.7.{{ $index }}      zpoolWriteBytes

> The place you need to have conditional code is in the storage code.
I don't quite know where is the storage code (everywhere seems storage related to me), I think most of the sensors in definitions/discovery/truenas.yaml would be in need of conditionals.

**Comment by laf** [comment]
I'm ok with the current PR, it's a bit noisy but seems to make sense from what you describe. @murrant is the guru on these things though so I'll leave it to his judgement on the best path forward.

**Comment by murrant** [comment]
I have  a hard time here too.  Let me try to be more explicit.
Only the numeric oid matters.  If the same data point is at the same numeric oid, you can just use one single sensor entry (preferring using the TRUENAS-MIB name)

If the numeric oid differs, you do need your solution.

My initial look made me think more OIDs matched not that ixSystems had kind of needlessly messed everything up.  If you can can you list which OIDs used in LibreNMS have matching OIDs and which have differing?  Then maybe we can come up with the best solution.

**Comment by jiannelli** [comment]
Great @murrant! I feel we are getting to the same conclusions.

> My initial look made me think more OIDs matched not that ixSystems had kind of needlessly messed everything up. If you can can you list which OIDs used in LibreNMS have matching OIDs and which have differing? Then maybe we can come up with the best solution.

All of the OIDs in discovery/truenas.yaml changed their num_oid, no datapoint used kept the same number:

```
oid: zfsArcSize
- num_oid: .1.3.6.1.4.1.50536.1.4.1.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.1.{{ $index }}
oid: zfsArcMeta
- num_oid: .1.3.6.1.4.1.50536.1.4.2.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.2.{{ $index }}
oid: zfsArcData
- num_oid: .1.3.6.1.4.1.50536.1.4.3.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.3.{{ $index }}
oid: zfsArcHits
- num_oid: .1.3.6.1.4.1.50536.1.4.4.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.4.{{ $index }}
oid: zfsArcMisses
- num_oid: .1.3.6.1.4.1.50536.1.4.5.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.5.{{ $index }}
oid: zfsArcC
- num_oid: .1.3.6.1.4.1.50536.1.4.6.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.6.{{ $index }}
oid: zfsArcP
- num_oid: .1.3.6.1.4.1.50536.1.4.7.{{ $index }}
+ 
oid: zfsArcMissPercent
- num_oid: .1.3.6.1.4.1.50536.1.4.8.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.8.{{ $index }}
oid: zfsArcCacheHitRatio
- num_oid: .1.3.6.1.4.1.50536.1.4.9.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.3.9.{{ $index }}
oid: zfsArcMissRatio
- num_oid: .1.3.6.1.4.1.50536.1.4.10.{{ $index }}
oid: zfsArcCacheMissRatio
+ num_oid: .1.3.6.1.4.1.50536.1.3.10.{{ $index }}
oid: zfsL2ArcHits
- num_oid: .1.3.6.1.4.1.50536.1.5.1.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.4.1.{{ $index }}
oid: zfsL2ArcMisses
- num_oid: .1.3.6.1.4.1.50536.1.5.2.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.4.2.{{ $index }}
oid: zfsL2ArcRead
- num_oid: .1.3.6.1.4.1.50536.1.5.3.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.4.3.{{ $index }}
oid: zfsL2ArcWrite
- num_oid: .1.3.6.1.4.1.50536.1.5.4.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.4.4.{{ $index }}
oid: zfsL2ArcSize
- num_oid: .1.3.6.1.4.1.50536.1.5.5.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.4.5.{{ $index }}
oid: zfsZilstatOps1sec
- num_oid: .1.3.6.1.4.1.50536.1.6.1.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.5.1.{{ $index }}
oid: zfsZilstatOps5sec
- num_oid: .1.3.6.1.4.1.50536.1.6.2.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.5.2.{{ $index }}
oid: zfsZilstatOps10sec
- num_oid: .1.3.6.1.4.1.50536.1.6.3.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.5.3.{{ $index }}
oid: zpoolTable
- num_oid: .1.3.6.1.4.1.50536.1.1.1.1.7.{{ $index }}
+ num_oid: .1.3.6.1.4.1.50536.1.1.1.1.3.{{ $index }}
```

**Comment by jiannelli** [comment]
I'll close this PR because we decided that will continue working with PR 16462 that implements truenas-scale as a different OS for simplicity.

**Pull request closed without merging**
