### PR TITLE
Add apc battery operation time, including display in WebUI

### PR DESCRIPTION
**Pull request by mwobst**
With this feature, the date of last battery change is determined and used for building the difference to today. That difference is stored as minutes and displayed as years + minutes as »Battery Operating Time«. The limits are 4 years (warning/yellow) and 5 years (critical/red) – values from our own experience.
apc_battery_operation_time

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by mwobst** [comment]
I am a little puzzled about the single failed test unit (php8, Unit, 1, mariadb:10.5):

> There was 1 failure:
> 1] LibreNMS\Tests\OSDiscoveryTest::testOSDetection with data set "3com" ('3com')
> OS 3com took longer than 5s to detect
> Failed asserting that 6.779435873031616 is less than 5.
[please note: to avoid list formatting, round bracket after “1” has been substituted)

My test data has nothing to do with 3com at all. Maybe the 5s limit is a little bit too strict? I would have expected, that all three tests would fail for the same reason (it doesn’t seem to be reliant on the PHP or database version). What can I do in this case? Making a meaningless commit for triggering the checks again seems a little bit … dirty.

**Comment by mwobst** [comment]
Update: Now the check has passed … either my eyes are clouded or a nice person triggered them again … in this case: Thank you.

**Comment by dagbdagb** [comment]
Great contribution! Thank you!

**Review by ottorei — APPROVED** [review]

**Comment by PipoCanaja** [comment]
Hi @mwobst 
I created a revert PR because tests are failing. It fails because the date changes every day and of course the result of the operation time increases ... 
@librenms/reviewers  Any idea how this could be handled properly ?

**Comment by murrant** [comment]
@PipoCanaja thanks.

Hmm...   The only way would be to mock a fixed date for tests.
https://laravel.com/docs/mocking#interacting-with-time

**Comment by dagbdagb** [comment]
I'd really like to see this merged again. From the comments above, it sounds as if one or more tests are 'suboptimally implemented', is this correct? Kinda strange that this only shows up now?

**Comment by mwobst** [comment]
@PipoCanaja @murrant Is there any plan right now how to solve this thing? This PR is still marked as resolved, with another PR reverting this one. As I did not found a corresponding issue, I would like to keep this PR as draft until that strange test issue is resolved. Would this be possible?

**Pull request merged**
