### PR TITLE
Check for empty SLA tags so we skip bad entries

### PR DESCRIPTION
**Pull request by laf**
Please give a short description what your pull request is for

Fixes these errors due to bad tag data from Cisco SLAs:

```
Error discovering slas module for x.x.x.x. SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tag' cannot be null (SQL: insert into `slas` (`deleted`, `sla_nr`, `owner`, `tag`, `rtt_type`, `rtt`, `status`, `opstatus`, `device_id`) values (0, 13, , ?, echo, 5, 1, 0, 119))
```

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Is skipping what we want or do we want to write an empty string.  (I don't know what data the tags field holds)

**Comment by ottorei** [comment]
> Is skipping what we want or do we want to write an empty string. (I don't know what data the tags field holds)

Its varchar(255) in the DB. The values in that field are mostly IP-addresses (* tested with some random Cisco gear).

**Comment by murrant** [comment]
> > Is skipping what we want or do we want to write an empty string. (I don't know what data the tags field holds)
> 
> Its varchar(255) in the DB. The values in that field are mostly IP-addresses (* tested with some random Cisco gear).

So, should we discard the ones with empty tags, or keep them?

**Comment by bonzo81** [comment]
Hope I can chip in. We use IP SLA quite a bit. We tend to use the tag like a description. I think it's just free text. Cisco guide explains it as 

> Creates a user-specified identifier for an IP SLAs operation.

We have some configured without the tag so I would think it best to keep those too, as they still produce SLA data.

**Comment by murrant** [comment]
Thanks @bonzo81, if that is the case I suggest we store empty strings.

**Pull request merged**
