### PR TITLE
Fix polling and discovery of FortiGate cluster sensors

### PR DESCRIPTION
**Pull request by mkuurstra**
As discussed [here](https://community.librenms.org/t/name-based-polling-not-working/18567)

All these checks where not working because of an error in the discovery. I also moved 1 sensor from `state` to `count` as it was counting cluster members, so that sensor type seemed more appropriate.

With these changes the customised state polling for Fortigate wasn't needed anymore so I deleted that file as well.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Looks good.

As for the deleted test file, does the new 1500d test file replace it?  what is the difference?

**Comment by mkuurstra** [comment]
I might’ve misinterpreted the 3th checkpoint asking to update test data when making discovery/polling changes.

If I remember correctly the tests threw an error. My interpretation was that the error was caused because by fixing the created test I added sync cluster status for every member in the cluster, which wasn’t already in the captured test data.

**Comment by murrant** [comment]
You are probably correct, but no way for me to tell that without comparing the changes from the previous test data :)

Would be great if you can re-add the snmprec file and generate the json file from it from scratch.

**Comment by mkuurstra** [comment]
Added the test data like you requested. I also noticed that I was the one who added the 1500d data 3 years ago and wanted to update and obscure some of the content.

**Pull request merged**
