### PR TITLE
feature: Add CiscoSB Port Suspended Status Info

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
@Rosiak any reason you didn't use yaml here?

**Comment by laf** [comment]
I'm guessing because of the description.

**Comment by murrant** [comment]
Ah, I see it now

**Comment by Rosiak** [comment]
Yes, for some reason the Cisco Sx series replies with port-channels which are non-existent, it is to mitigate that.

```
IF-MIB::ifDescr.49 = STRING: gigabitethernet1
IF-MIB::ifDescr.50 = STRING: gigabitethernet2
IF-MIB::ifDescr.51 = STRING: gigabitethernet3
IF-MIB::ifDescr.52 = STRING: gigabitethernet4
IF-MIB::ifDescr.53 = STRING: gigabitethernet5
IF-MIB::ifDescr.54 = STRING: gigabitethernet6
IF-MIB::ifDescr.55 = STRING: gigabitethernet7
IF-MIB::ifDescr.56 = STRING: gigabitethernet8
IF-MIB::ifDescr.57 = STRING: gigabitethernet9
IF-MIB::ifDescr.58 = STRING: gigabitethernet10
IF-MIB::ifDescr.59 = STRING: gigabitethernet11
IF-MIB::ifDescr.60 = STRING: gigabitethernet12
IF-MIB::ifDescr.61 = STRING: gigabitethernet13
IF-MIB::ifDescr.62 = STRING: gigabitethernet14
IF-MIB::ifDescr.63 = STRING: gigabitethernet15
IF-MIB::ifDescr.64 = STRING: gigabitethernet16
IF-MIB::ifDescr.65 = STRING: gigabitethernet17
IF-MIB::ifDescr.66 = STRING: gigabitethernet18
IF-MIB::ifDescr.67 = STRING: gigabitethernet19
IF-MIB::ifDescr.68 = STRING: gigabitethernet20
IF-MIB::ifDescr.69 = STRING: gigabitethernet21
IF-MIB::ifDescr.70 = STRING: gigabitethernet22
IF-MIB::ifDescr.71 = STRING: gigabitethernet23
IF-MIB::ifDescr.72 = STRING: gigabitethernet24
IF-MIB::ifDescr.73 = STRING: gigabitethernet25
IF-MIB::ifDescr.74 = STRING: gigabitethernet26
IF-MIB::ifDescr.75 = STRING: gigabitethernet27
IF-MIB::ifDescr.76 = STRING: gigabitethernet28
IF-MIB::ifDescr.1000 = STRING: Po1
IF-MIB::ifDescr.1001 = STRING: Po2
IF-MIB::ifDescr.1002 = STRING: Po3
IF-MIB::ifDescr.1003 = STRING: Po4
IF-MIB::ifDescr.1004 = STRING: Po5
IF-MIB::ifDescr.1005 = STRING: Po6
IF-MIB::ifDescr.1006 = STRING: Po7
IF-MIB::ifDescr.1007 = STRING: Po8


swIfOperSuspendedStatus.49 = false
swIfOperSuspendedStatus.50 = false
swIfOperSuspendedStatus.51 = false
swIfOperSuspendedStatus.52 = false
swIfOperSuspendedStatus.53 = false
swIfOperSuspendedStatus.54 = false
swIfOperSuspendedStatus.55 = false
swIfOperSuspendedStatus.56 = false
swIfOperSuspendedStatus.57 = false
swIfOperSuspendedStatus.58 = false
swIfOperSuspendedStatus.59 = false
swIfOperSuspendedStatus.60 = false
swIfOperSuspendedStatus.61 = false
swIfOperSuspendedStatus.62 = false
swIfOperSuspendedStatus.63 = false
swIfOperSuspendedStatus.64 = false
swIfOperSuspendedStatus.65 = false
swIfOperSuspendedStatus.66 = false
swIfOperSuspendedStatus.67 = false
swIfOperSuspendedStatus.68 = false
swIfOperSuspendedStatus.69 = false
swIfOperSuspendedStatus.70 = false
swIfOperSuspendedStatus.71 = false
swIfOperSuspendedStatus.72 = false
swIfOperSuspendedStatus.73 = false
swIfOperSuspendedStatus.74 = false
swIfOperSuspendedStatus.75 = false
swIfOperSuspendedStatus.76 = false
swIfOperSuspendedStatus.1000 = false
swIfOperSuspendedStatus.1001 = false
swIfOperSuspendedStatus.1002 = false
swIfOperSuspendedStatus.1003 = false
swIfOperSuspendedStatus.1004 = false
swIfOperSuspendedStatus.1005 = false
swIfOperSuspendedStatus.1006 = false
swIfOperSuspendedStatus.1007 = false
```
This specific use case for this is to catch ports that might have violated BPDU-Guard etc.

**Pull request merged**
