### PR TITLE
[DOC] Fix code box warnings in Configuration Docs

### PR DESCRIPTION
**Pull request by santiag0z**
Before:
image

After:
image

Reference:
https://squidfunk.github.io/mkdocs-material/reference/admonitions/

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by electrocret — APPROVED** [review]
LGTM

**Comment by santiag0z** [comment]
Can this PR be merged?

**Review by murrant — CHANGES_REQUESTED** [review]
Something else is wrong.  The setting key is used for functionality that this would break.

**Comment by santiag0z** [comment]
@murrant, I don't understand, where should I look?

**Comment by murrant** [comment]
For dark mode colors, the css in doc/librenms.css needs to be added for dark.

You are also missing the url edit icon on the right side of the box.  Check the oxidized page, it is working there.

**Comment by murrant** [comment]
I do like the gear on the left, maybe that should be added to the css file too.

**Comment by murrant** [comment]
Actually, I'm guessing some javascript failed in your browser.  Did you check the console?

**Comment by murrant** [comment]
@santiag0z Thanks, fixed some of the things in my PR.  If there are any remaining issues, please make a new PR :)

**Pull request closed without merging**
