### PR TITLE
Added temperature support for APC portable AC units.

### PR DESCRIPTION
**Pull request by mchasteen**
Adds support for APC's portable AC units.  Now the intake, exhaust, and ambient temperatures are being polled.

I have it grabbing the setpoint on the AC unit and putting it in the description.  I don't know if there is a better way of doing this.

I could have used MIB things.  That is a possible change.

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this @mchasteen. Does it not need an update to polling/apc.inc.php for it to then be able to grab data?

**Comment by laf** [comment]
Also @mchasteen, take a look at the scrutinizer output, it has a few things that need a little tidying up :)

**Comment by mchasteen** [comment]
It works without modifying any of the polling.  It grabs data and graphs it.

**Comment by laf** [comment]
Thanks for getting back to us @mchasteen.

If you could just take a look at the scrutinizer issues that would be great: https://scrutinizer-ci.com/g/librenms/librenms/inspections/7020d979-5a0b-43aa-a06e-94fe2ed94615/issues/files/includes/discovery/temperatures/apc.inc.php?status=new&orderField=path&order=asc

A lot of the recommendations are just changing things like:

if ($oids)

to

if ($oids !== false)

so should be quite simple :)

**Comment by mchasteen** [comment]
ok, so do I do another commit with the changes?

**Comment by f0o** [comment]
Yep :)

**Comment by laf** [comment]
Thanks for sorting that @mchasteen 

FYI we've published some starting docs on code formatting which whilst aren't show stoppers, is helpful to try and keep consistent standards going forward :)

http://docs.librenms.org/Developing/Code-Guidelines/

**Pull request merged**
