### PR TITLE
Update Cisco Meraki logo

### PR DESCRIPTION
**Pull request by arjitc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

Logo Source: Their home page header (https://meraki.cisco.com/)
https://meraki.cisco.com/img/cisco-meraki-logo.png

Old logo/image in LiberNMS:
chrome_2020-04-09_00-16-16

Updated logo/image:
chrome_2020-04-09_00-16-01

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by arjitc** [comment]
@murrant -- I'm unable to find a proper 32x32 logo for Meraki. The current logo bundled with LibreNMS seems to not be present on their site currently, https://meraki.cisco.com/

**Comment by murrant** [comment]
Then leave the existing icon and set this as the banner logo...

**Comment by murrant** [comment]
usually the favicon on the website is a good indication of what should be set for the icon in LibreNMS.  Also, it isn't 32x32 that is just the smallest size it is usually displayed as. See docs for more info:
https://docs.librenms.org/Developing/os/Initial-Detection/#icon-and-logo

**Comment by arjitc** [comment]
@murrant the reason is, for example, if we see the Mikrotik logo



it's the complete logo which appears in the top-bar -- so similarly, I felt that the existing logo for the Meraki was quite odd (looks really blurred?)

**Comment by murrant** [comment]
This is because MikroTik has two separate files one for icon and one for the full banner display called a logo.  Please read the docs I linked thanks.

**Comment by arjitc** [comment]
Would the logo (SVG) from Wikipedia be fine in this case ?

https://en.wikipedia.org/wiki/Cisco_Meraki#/media/File:Meraki_Logo_2016.svg

For example,

**Comment by murrant** [comment]
No, I liked your original image better.

**Comment by murrant** [comment]
So, you seem to be having trouble here. Let me try to help you out.
Place the new file here: `images/logos/meraki.png`
Restore or find a new different image for the icon here: `images/os/meraki.png`

(if it is an SVG it should have the svg extension)

**Comment by murrant** [comment]
Fixed in #11406

**Pull request closed without merging**
