### PR TITLE
Canceling the creation of graphs for VLAN as for the Eltex MES23xx interface

### PR DESCRIPTION
**Pull request by aztec102**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

I propose to cancel the creation of graphs for VLAN interfaces. They take up a lot of space, provided that a lot of VLANs are created on the switch.

### CODE REVIEW

**Comment by Npeca75** [comment]
@aztec102 
why do you want to remove Vlan interface?

**Comment by aztec102** [comment]
@Npeca75 I propose to cancel the creation of graphs for VLAN interfaces. They take up a lot of space, provided that a lot of VLANs are created on the switch.

**Comment by Npeca75** [comment]
if you delete vlan if, we will lose IP info and how the device is connected to others
lnms1

**Comment by aztec102** [comment]
> if you delete vlanIf, we will lose IP info and how the device is connected to others
Well, then you have to put up with it.

**Pull request closed without merging**
