### PR TITLE
Daemonize (Rebased)

### PR DESCRIPTION
**Pull request by f0o**
Original PR: #1120  
Depends: #1222

### CODE REVIEW

**Comment by laf** [comment]
zero issues with this for me.

@f0o can you add librenmsd.pid to .gitignore.

@paulgear Thoughts on this PR if any?

**Comment by f0o** [comment]
Will do :)

**Comment by paulgear** [comment]
I have to admit I'm a little nervous about this one.  What happens if the daemon dies for some reason?  Is there a check from the GUI or cron to restart it if it drops out?

**Comment by f0o** [comment]
putting it on hold until fixed.
Adding a config to simplify distributed poller setup integration for jobcontrol.

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
bump @laf @paulgear :)

**Comment by laf** [comment]
My only comment would be the docs contain info relevant for other distros i.e in Ubuntu docs it contains info CentOS. Possibly worth just chopping the irrelevant bits out. 

Using cron to start means we shouldn't be concerned on about it failing and people not knowing.

So overall :+1: from me - @paulgear

**Comment by f0o** [comment]
There's also a notification in the UI if the daemon isnt running but a pid-file exists.

**Comment by paulgear** [comment]
If the daemon isn't running but a pid file exists, shouldn't we just delete it and start the daemon?

**Comment by f0o** [comment]
@paulgear I dont think the UI should have the permissions to start the daemon

**Comment by paulgear** [comment]
@f0o I meant from the cron job

**Comment by f0o** [comment]
Resolved merge-conflicts

**Comment by laf** [comment]
@paulgear Think we're waiting on you?

**Comment by f0o** [comment]
Putting it on Hold.

**Comment by f0o** [comment]
Closing this PR.
At the current stage #1405 is likely the better alternative.

The code wont get to waste, my mates and I are going to add poller-to-poller protocols and some sort of result-feedback queue to suit our infrastructure.
When finalized it will be released under GPL3 and re-presented to LibreNMS.

**Pull request closed without merging**
