### PR TITLE
API: Change display query of list_devices to pattern match

### PR DESCRIPTION
**Pull request by hirose003**
Please give a short description what your pull request is for

Changed display query of list_devices from exact match to pattern match.
Because hostname query is a pattern match.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by ottorei — APPROVED** [review]
This makes the display selection work with the same logic as hostname selection so looks good to me.

**Comment by murrant** [comment]
:/  I think we need to cache the generated display name in the database.  Code like this only works if people explicitly set display names, and not if they use a template.

**Comment by ottorei** [comment]
> :/ I think we need to cache the generated display name in the database. Code like this only works if people explicitly set display names, and not if they use a template.

Oh, I forgot it was possible not to explicitly set display names..

**Comment by electrocret** [comment]
Merging. This PR has no effect for those who don't manually set display names, and fixes it for those who do manually set. Putting display name in DB is a separate issue.

**Pull request merged**
