### PR TITLE
Added support for OS detection from NXOS and UCS 

### PR DESCRIPTION
**Pull request by magnuslarsen**
This PR adds support for LibreNMS to differentiate between Cisco UCS and Cisco NXOS type devices.

Currently both UCS server hardware and NXOS network devices gets detected as `NXOS` - which is wrong :-)
If you use Oxidized, this leads to the wrong model configuration being used; and Oxidized fails to load the config.

If someone could help me figure this one out, please help me.
When changing to a the proper UCS os (`ucos`) - the hardware field changes from (the correct) `UCS 6248 Series Fabric Interconnect` to `
ciscoModules.3.1.3.1062` - how is this decided, and where can I change it?

FROM:
image

TO:
image

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
@magnuslarsen thanks for your commit,
please sign CLA.

**Comment by magnuslarsen** [comment]
Hey @SourceDoctor, had some trouble with it, but got it working :-)

**Comment by murrant** [comment]
Tests fail.  Can't you use sysDescr or sysObjectID to differentiate?  Also, seems like UCOS runs NX-OS underneath...

**Comment by magnuslarsen** [comment]
It does seem that way yes. But UCOS _is_ different from NXOS, especially in regards to the CLI

**Comment by murrant** [comment]
You can move this to yaml.  There are some other OS that use the "except" rule.  Might be useful for you to look at them :)

**Comment by magnuslarsen** [comment]
I moved it to YAML. However, i'm not able to test it till tomorrow

**Comment by magnuslarsen** [comment]
Did I do anything wrong with the except rules? This seems like it should work; but it still detects NXOS :shrug:

**Comment by SourceDoctor** [comment]
@magnuslarsen 
take a look into Travis Results, please

**Comment by magnuslarsen** [comment]
It just seems to me, that it is using the wrong snmprec file. If the test would be using `ucos_2.snmprec`  it should work yeah (it is "created" in this PR)?

I just tested this out on my LibreNMS installation, and it does not work either. Are the except rules wrong? When i did the initial commit here, without the YAML, it was working as expected..

**Comment by murrant** [comment]
@magnuslarsen all files need to pass.  So you have broken the detection of some UCOS devices (based on the data in ucs.snmprec)

**Comment by murrant** [comment]
I know it is not obvious, but is how you have grouped your detection statements. Check here: https://docs.librenms.org/Developing/os/Initial-Detection/#discovery-logic

**Comment by murrant** [comment]
Fixed the except grouping while merging upstream changes...

**Comment by murrant** [comment]
heh, the "nxos.yaml" discovery only contained ucos sensors, just renamed it.

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/nxos-model-os-version-detection-broken/13458/3

**Comment by PipoCanaja** [comment]
Hi Guys,
It seems that this PR is breaking Nexus devices : 
https://community.librenms.org/t/nxos-model-os-version-detection-broken/13458

Could you have a look ?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
