### PR TITLE
Update Infoblox/Palo Alto/Red hat logos to SVG file

### PR DESCRIPTION
**Pull request by FTBZ**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

- Change Infoblox/Palo Alto Networks/Redhat to new logo in SVG format

### CODE REVIEW

**Comment by FTBZ** [comment]
Multiple commits because I noticed that the size of 32x32 is no longer needed in SVG file

**Comment by murrant** [comment]
You should remove the copyright from the redhat icon, it is too small for 32x32.
Also, the other icons seem to wide.

@librenms/reviewers Perhaps we need seperate logo and icon images?  I think that would make things look very nice.  And if the logo is missing we can just use the icon...

**Comment by FTBZ** [comment]
@murrant, what's the ideal size for SVG logo?

**Comment by murrant** [comment]
@FTBZ You don't have to add the logos to this PR, but hold on to them for a bit ;)

**Comment by FTBZ** [comment]
The last ones after IRC discussion:

screen shot 2017-01-24 at 07 50 36
screen shot 2017-01-24 at 07 50 26

**Pull request merged**
