### PR TITLE
refactor: Improve sensors polling for performance increase

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Do not merge yet

### CODE REVIEW

**Comment by Rosiak** [comment]
I can test this one.

**Comment by laf** [comment]
Tested on my home install, I only really have a switch where this would benefit but overall no loss of data or increase in poller times.

image

**Comment by Rosiak** [comment]
Tested and have had it running for 24 hrs, no issues seen.

**Comment by paszczus** [comment]
I think that commit has broke my UPS devices Runtime info. I has been merged 15 hours ago and just after midnigh when ./daily.sh is updating librenms to current version i have received a hundreds of notifications that runtime sensor is critical and also we can see this on graph:

upc_runtime

apc_smart

**Comment by MatGit5** [comment]
Confirmed, it broke Runtime on my APC Smart-UPS 2200.

**Comment by paszczus** [comment]
Is anyone going to revert/fix this?

**Comment by murrant** [comment]
PR #4780 contains fixes for these issues, but none of the core developers have equipment to test them.
Feedback would be appreciated so we can get it merged sooner rather than later.

**Comment by Rosiak** [comment]
Merged & tested with a device from the demo.
Please update and retest @MatGit5 @paszczus

**Comment by paszczus** [comment]
Works fine for me now. Thanks!

**Pull request merged**
