### PR TITLE
I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md.

### PR DESCRIPTION
**Pull request by adaniels21487**
I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md.

### CODE REVIEW

**Comment by f0o** [comment]
@adaniels21487 We recently updated our Contribution Guidelines, would you mind reviewing them and either leave the PR open but comment your consent or in case you disagree close the PR?
Thanks!

**Comment by adaniels21487** [comment]
@f0o I agree with the new Contribution Guidelines.
Thanks,
Aaron

**Comment by laf** [comment]
Thanks for confirming @adaniels21487 

Unfortunately you will need to rebase this anyway as another PR Has just been merged that changes the same file.

**Comment by f0o** [comment]
Apparently github didnt bother!

**Comment by laf** [comment]
Oh awesome :) @adaniels21487 Ignore my comment :D

**Pull request merged**
