### PR TITLE
Update supported SwOS Devices

### PR DESCRIPTION
**Pull request by arrmo**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
The original code for this was a bit wrong, we don't need to do snmpget requests.

Use this patch to update this PR and include a test as well:

https://gist.github.com/laf/8fec9f6f57890c79f18c22f4b5d40f52

**Comment by arrmo** [comment]
Sorry, a bit confused by your note above ... :(. We can't just rely on MikroTik, as this will pick up routeros as well - agreed? 

Not quite sure I understand how the files in tests (directory) fit in - can you clarify?

Thanks!

**Comment by laf** [comment]
The patch provided is he same as you submitted but doesn't make three separate snmp calls. It still does the mikrotik check as normal

For os test. We need all new and updated os' to have checks so that things don't get broken as you've seen with swos before.

**Comment by murrant** [comment]
https://github.com/librenms/librenms/compare/master...murrant:fix-swos

**Comment by laf** [comment]
@murrant want to just turn that into a pr?

**Comment by arrmo** [comment]
Thanks guys! Sorry, I missed that change that laf made. I can make the update, or murrant - just let me know.

**Comment by laf** [comment]
Merged in another PR

**Comment by murrant** [comment]
Thanks for the changes arrmo, just have many changing pieces in that part of our code right now.

**Comment by arrmo** [comment]
No worries - glad to try to help out. I think LibreNMS is awesome, want to try to do what I can to replay the effort that has gone in to it. And I admit - it's great trying to help out when the lead folks have such awesome attitudes.

Thanks!

**Comment by arrmo** [comment]
FYI, pulled in these latest updates - broke my SwOS switch (detection) ... :-(. Here is what is in the log,
2016-09-20 19:57:45	Device OS changed swos => generic	
2016-09-20 19:57:45	Device Icon changed swos => generic

Devices is now generic again.

**Comment by laf** [comment]
Can you post the output of `./poller.php -h HOSTNAME -d -r -f -m os`

It's odd as we have unit tests in for OS' now and this hasn't picked it up.

**Comment by murrant** [comment]
laf: the unit tests are based off the code... If the code is wrong...

**Comment by arrmo** [comment]
Hi,

OK, output attached. And also note, I get the following error message (tied to one particular query, I think looking for a non-existent parameter, but I could be wrong!)
Timeout: No Response from udp:mikrotik.home:161.
[poller-check.txt](https://github.com/librenms/librenms/files/485286/poller-check.txt)

Thanks!

**Comment by murrant** [comment]
@arrmo You need to run discovery.php to check if os is right.  Might need to start an issue for this...

**Comment by arrmo** [comment]
Yep, ran both - is there something in particular to check in discovery (output)? It was working before this update, so something is amiss. Just let me know - I admit, just not real familiar with the debug output.

Thanks!

**Comment by laf** [comment]
I submitted a pull request last night. It's purely down to Microtik -> Mikrotik

**Comment by arrmo** [comment]
Yep, that was it - thanks! One last thing ... :). The following update in the log now, after running discovery (this is a good thing!),
2016-09-22 07:23:23	Device Icon changed generic => swos

But the log is also getting filled with the following, seems to be changing ever run of the poller now (or really, with recent changes - not necessarily the typo fix above),
2016-09-22 07:25:18	sfp ifLastChange: 0 -> 0:0:00:00.00	
2016-09-22 07:25:18	port5 ifLastChange: 0 -> 0:0:00:02.12	
2016-09-22 07:25:18	port4 ifLastChange: 0 -> 0:0:00:02.06	
2016-09-22 07:25:18	port3 ifLastChange: 23 -> 23:11:22:34.08	
2016-09-22 07:25:18	port2 ifLastChange: 23 -> 23:11:28:05.01	
2016-09-22 07:25:18	port1 ifLastChange: 7 -> 7:18:44:50.54

Thoughts?

**Comment by arrmo** [comment]
Never mind! Just saw another post on this - seems it's more generic.

Thanks again!

**Pull request closed without merging**
