### PR TITLE
Add stats to db

### PR DESCRIPTION
**Pull request by ekoyle**
Add more values from the last poll to the DB for alerting purposes.

### CODE REVIEW

**Comment by ekoyle** [comment]
I added a config option that defaults to false, is that appropriate?

**Comment by paulgear** [comment]
@ekoyle Adding config options that default to false is fine, and probably preferred in the case of new features.  I'd personally prefer to see the "enable_" removed from the front of the option name.  All boolean flags should be true to enable and false to disable, so having enable is redundant.

You'll need to mangle your schema update so that it's one line per statement, though (an annoying limitation that we hope to fix in future).

**Comment by ekoyle** [comment]
Okay... rebased, updated schema, and changed config option.  Also, laf had me use schema version 081, assuming this would be merged after #2458 and #2536 .

**Comment by laf** [comment]
I'd say that we get rid of the config option for this. I'm not sure I see a people having to turn it on. It just makes documenting / rule suggestions trickier as we won't know who's got it on and who hasn't.

**Comment by ekoyle** [comment]
I went ahead and removed the option.  Since we are already collecting these variables in the poller, it makes sense to always add them to the DB so they can be alerted on, and there doesn't appear to be a use-case for turning them off.

**Comment by laf** [comment]
@f0o would you be able to check the DB to see if the table is being populated ok?

**Comment by f0o** [comment]
Is it supposed to be like this?
```
                 port_id: 3
          ifInNUcastPkts: NULL
     ifInNUcastPkts_prev: NULL
    ifInNUcastPkts_delta: NULL
     ifInNUcastPkts_rate: NULL
         ifOutNUcastPkts: NULL
    ifOutNUcastPkts_prev: NULL
   ifOutNUcastPkts_delta: NULL
    ifOutNUcastPkts_rate: NULL
            ifInDiscards: NULL
       ifInDiscards_prev: NULL
      ifInDiscards_delta: NULL
       ifInDiscards_rate: NULL
           ifOutDiscards: NULL
      ifOutDiscards_prev: NULL
     ifOutDiscards_delta: NULL
      ifOutDiscards_rate: NULL
       ifInUnknownProtos: NULL
  ifInUnknownProtos_prev: NULL
 ifInUnknownProtos_delta: NULL
  ifInUnknownProtos_rate: NULL
       ifInBroadcastPkts: NULL
  ifInBroadcastPkts_prev: NULL
 ifInBroadcastPkts_delta: NULL
  ifInBroadcastPkts_rate: NULL
      ifOutBroadcastPkts: 0
 ifOutBroadcastPkts_prev: 0
ifOutBroadcastPkts_delta: 0
 ifOutBroadcastPkts_rate: 0
       ifInMulticastPkts: 0
  ifInMulticastPkts_prev: 0
 ifInMulticastPkts_delta: 0
  ifInMulticastPkts_rate: 0
      ifOutMulticastPkts: 0
 ifOutMulticastPkts_prev: 0
ifOutMulticastPkts_delta: 0
 ifOutMulticastPkts_rate: 0
```

**Comment by f0o** [comment]
The poller is updating the SQL though.
```
SQL[ESC[0;33mUPDATE `ports_statistics` set `ifOutBroadcastPkts` ='0',`ifOutBroadcastPkts_prev` ='0',`ifOutBroadcastPkts_rate` ='0',`ifOutBroadcastPkts_delta` ='0',`ifInMulticastPkts` ='0',`ifInMulticastPkts_prev` ='0',`ifInMulticastPkts_rate` ='0',`ifInMulticastPkts_delta` ='0',`ifOutMulticastPkts` ='0',`ifOutMulticastPkts_prev` ='0',`ifOutMulticastPkts_rate` ='0',`ifOutMulticastPkts_delta` ='0' WHERE `port_id` = '3'ESC[0m]
```

Just doesnt seem to hold any data

**Comment by ekoyle** [comment]
It is only updating data that is actually being polled, so if it isn't
there it leaves it at the default of NULL.  I figured that would be more
useful than setting to 0.

The odd thing is that the RRDs appear to contain that data, and it looks
like it is using the same variable to get it there, so I'm not entirely
sure why this is happening.  Is there something somewhere else that is also
updating the port rrd files?



On Wed, Dec 9, 2015 at 11:51 AM, Daniel Preussker <notifications@github.com>
wrote:

> The poller is updating the SQL though.
>
> SQL[ESC[0;33mUPDATE `ports_statistics` set `ifOutBroadcastPkts` ='0',`ifOutBroadcastPkts_prev` ='0',`ifOutBroadcastPkts_rate` ='0',`ifOutBroadcastPkts_delta` ='0',`ifInMulticastPkts` ='0',`ifInMulticastPkts_prev` ='0',`ifInMulticastPkts_rate` ='0',`ifInMulticastPkts_delta` ='0',`ifOutMulticastPkts` ='0',`ifOutMulticastPkts_prev` ='0',`ifOutMulticastPkts_rate` ='0',`ifOutMulticastPkts_delta` ='0' WHERE `port_id` = '3'ESC[0m]
>
> Just doesnt seem to hold any data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/2542#issuecomment-163355736>.
>



-- 
Eldon Koyle

**Comment by ekoyle** [comment]
Apparently '+' doesn't do what I thought it would :/ .

includes/polling/ports.inc.php:436 has:
$_stat_oids = $stat_oids_db + $stat_oids_db_extended;

Here is what I see in $_stat_oids after that statement: Array
(
    [0] => ifInOctets
    [1] => ifOutOctets
    [2] => ifInErrors
    [3] => ifOutErrors
    [4] => ifInUcastPkts
    [5] => ifOutUcastPkts
    [6] => ifOutBroadcastPkts
    [7] => ifInMulticastPkts
    [8] => ifOutMulticastPkts
)

Here is what those two arrays are supposed to be:
$stat_oids_db = array(
    'ifInOctets',
    'ifOutOctets',
    'ifInErrors',
    'ifOutErrors',
    'ifInUcastPkts',
    'ifOutUcastPkts',
);

$stat_oids_db_extended = array(
    'ifInNUcastPkts',
    'ifOutNUcastPkts',
    'ifInDiscards',
    'ifOutDiscards',
    'ifInUnknownProtos',
    'ifInBroadcastPkts',
    'ifOutBroadcastPkts',
    'ifInMulticastPkts',
    'ifOutMulticastPkts',
);



On Wed, Dec 9, 2015 at 2:45 PM, Eldon Koyle <ekoyle@gmail.com> wrote:

> It is only updating data that is actually being polled, so if it isn't
> there it leaves it at the default of NULL.  I figured that would be more
> useful than setting to 0.
>
> The odd thing is that the RRDs appear to contain that data, and it looks
> like it is using the same variable to get it there, so I'm not entirely
> sure why this is happening.  Is there something somewhere else that is also
> updating the port rrd files?
>
>
>
> On Wed, Dec 9, 2015 at 11:51 AM, Daniel Preussker <
> notifications@github.com> wrote:
>
>> The poller is updating the SQL though.
>>
>> SQL[ESC[0;33mUPDATE `ports_statistics` set `ifOutBroadcastPkts` ='0',`ifOutBroadcastPkts_prev` ='0',`ifOutBroadcastPkts_rate` ='0',`ifOutBroadcastPkts_delta` ='0',`ifInMulticastPkts` ='0',`ifInMulticastPkts_prev` ='0',`ifInMulticastPkts_rate` ='0',`ifInMulticastPkts_delta` ='0',`ifOutMulticastPkts` ='0',`ifOutMulticastPkts_prev` ='0',`ifOutMulticastPkts_rate` ='0',`ifOutMulticastPkts_delta` ='0' WHERE `port_id` = '3'ESC[0m]
>>
>> Just doesnt seem to hold any data
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/librenms/librenms/pull/2542#issuecomment-163355736>.
>>
>
>
>
> --
> Eldon Koyle
>



-- 
Eldon Koyle

**Comment by ekoyle** [comment]
I found it.  Should be updating all the things now.  I am a python programmer, and made a bad assumption on how array('a') + array('b') would work in PHP.

**Comment by f0o** [comment]
```
                 port_id: 3
          ifInNUcastPkts: 0
     ifInNUcastPkts_prev: 0
    ifInNUcastPkts_delta: 0
     ifInNUcastPkts_rate: 0
         ifOutNUcastPkts: 0
    ifOutNUcastPkts_prev: 0
   ifOutNUcastPkts_delta: 0
    ifOutNUcastPkts_rate: 0
            ifInDiscards: 0
       ifInDiscards_prev: 0
      ifInDiscards_delta: 0
       ifInDiscards_rate: 0
           ifOutDiscards: 0
      ifOutDiscards_prev: 0
     ifOutDiscards_delta: 0
      ifOutDiscards_rate: 0
       ifInUnknownProtos: 0
  ifInUnknownProtos_prev: 0
 ifInUnknownProtos_delta: 0
  ifInUnknownProtos_rate: 0
       ifInBroadcastPkts: 0
  ifInBroadcastPkts_prev: 0
 ifInBroadcastPkts_delta: 0
  ifInBroadcastPkts_rate: 0
      ifOutBroadcastPkts: 0
 ifOutBroadcastPkts_prev: 0
ifOutBroadcastPkts_delta: 0
 ifOutBroadcastPkts_rate: 0
       ifInMulticastPkts: 0
  ifInMulticastPkts_prev: 0
 ifInMulticastPkts_delta: 0
  ifInMulticastPkts_rate: 0
      ifOutMulticastPkts: 0
 ifOutMulticastPkts_prev: 0
ifOutMulticastPkts_delta: 0
 ifOutMulticastPkts_rate: 0
```

supposed to be like this?

**Comment by ekoyle** [comment]
If the port is down I would expect it to look like that.

It depends on whether you have rx/tx any of those kinds of packets on that
port.

On Thu, Dec 10, 2015 at 2:56 AM, Daniel Preussker <notifications@github.com>
wrote:

>                  port_id: 3
>           ifInNUcastPkts: 0
>      ifInNUcastPkts_prev: 0
>     ifInNUcastPkts_delta: 0
>      ifInNUcastPkts_rate: 0
>          ifOutNUcastPkts: 0
>     ifOutNUcastPkts_prev: 0
>    ifOutNUcastPkts_delta: 0
>     ifOutNUcastPkts_rate: 0
>             ifInDiscards: 0
>        ifInDiscards_prev: 0
>       ifInDiscards_delta: 0
>        ifInDiscards_rate: 0
>            ifOutDiscards: 0
>       ifOutDiscards_prev: 0
>      ifOutDiscards_delta: 0
>       ifOutDiscards_rate: 0
>        ifInUnknownProtos: 0
>   ifInUnknownProtos_prev: 0
>  ifInUnknownProtos_delta: 0
>   ifInUnknownProtos_rate: 0
>        ifInBroadcastPkts: 0
>   ifInBroadcastPkts_prev: 0
>  ifInBroadcastPkts_delta: 0
>   ifInBroadcastPkts_rate: 0
>       ifOutBroadcastPkts: 0
>  ifOutBroadcastPkts_prev: 0
> ifOutBroadcastPkts_delta: 0
>  ifOutBroadcastPkts_rate: 0
>        ifInMulticastPkts: 0
>   ifInMulticastPkts_prev: 0
>  ifInMulticastPkts_delta: 0
>   ifInMulticastPkts_rate: 0
>       ifOutMulticastPkts: 0
>  ifOutMulticastPkts_prev: 0
> ifOutMulticastPkts_delta: 0
>  ifOutMulticastPkts_rate: 0
>
> supposed to be like this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/librenms/librenms/pull/2542#issuecomment-163560642>.
>



-- 
Eldon Koyle

**Comment by laf** [comment]
Testing now.

**Pull request merged**
