### PR TITLE
device: Use 5secs cpu interval for Extereme XOS

### PR DESCRIPTION
**Pull request by zombah**
Most network devices use cpu current counter, but
Extreme XOS miss it, use closest one to current
which is 5secs not 5mins and this makes cpu graph 
more granular.

Signed-off-by: Misha Komarovskiy <zombah@gmail.com>

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Out of interest why not use the 5min one. Using the a 5 second one will most likely give inaccurate results as it will spike from our polling code at the time and show high cpu usage all the time.

**Comment by zombah** [comment]
5min flattening cpu graph too much. Maybe then go for 30sec counter? 5sec was first i noticed between other os who also don't have "current cpu".

**Comment by murrant** [comment]
I would like to store multiple cpu usage periods and graph them all.  That way admins have all data available.  I haven't begun to think about this or what it would entail...  not any room for that on my plate right now.

**Comment by murrant** [comment]
@zombah The problem with making the window too short is you add more measurement bias.

When we poll a device, the cpu usage goes up.  If you cut out most of the time where the device was idle, usage whill look higher than it is.

**Comment by laf** [comment]
@zombah Any update on this?

**Comment by laf** [comment]
Closing until we receive an update.

**Comment by zombah** [comment]
Sorry i totally forgot about this. I like @murrant idea about storing multiple cpu vars and ability to graph them all. I tested 5secs counters for couple weeks there, didn't notice any polling impact but not big granularity bonus also, probably this is case specific. So i revoke this PR for now, storing multiple cpu counter sound much better idea than playing with specific one for specific device type.

**Pull request closed without merging**
