### PR TITLE
fix: add semicolons in sql scripts

### PR DESCRIPTION
**Pull request by jarischaefer**
Adds missing semicolons in SQL scripts.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks, good to tidy these up but they aren't strictly needed unless you directly import them into mysql.

**Comment by jarischaefer** [comment]
After I had encountered errors running the build-base script, I tried importing the SQLs manually via MySQL's CLI, which resulted in the errors fixed by this PR.

It seems the build-base script ignores all SQL errors and just keeps going with no visible error messages.

I will probably submit another PR shortly, which fixes some of the "real" errors that forced me to use the CLI directly in the first place.

**Comment by laf** [comment]
@jarischaefer Running build base gives you an error count (we have unit tests against these - slightly broken right now). I've recently been through and fixed all the errors, please ensure you don't have mysql strict mode enabled.

**Comment by jarischaefer** [comment]
I just tested everything with the official MySQL docker image. MySQL 5.7 does not work at all (they removed ALTER IGNORE TABLE in 5.7.4, which breaks 109.sql) and 5.6 still fails at https://github.com/librenms/librenms/pull/6289.

**Pull request merged**
