### PR TITLE
Update VyOS logo

### PR DESCRIPTION
**Pull request by c-po**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

VyOS (https://vyos.io/) switched to a new logo in 2016, also use this new logo in LibreNMS.

### CODE REVIEW

**Comment by murrant** [comment]
Any chance you can get an SVG source? (or other vector and convert it to SVG)

**Comment by c-po** [comment]
I'll try to get the SVG source from the designer. Currently the VyOS team only has the PNG. Yu are right, SVG is always to be preferred!

**Comment by c-po** [comment]
Designer was asked if a SVG version is available. Unfortunately no reply yet.

**Comment by murrant** [comment]
Thanks for the update.

**Comment by murrant** [comment]
@c-po Merging this for now.  Create a new PR if you get a hold of a SVG :)

**Pull request merged**
