### PR TITLE
allow to search a device by its hostname

### PR DESCRIPTION
**Pull request by mmarchand**
search by hostname if ID was not found 
it also permits to add a quick search for a device in most modern browsers ;)  
( http://nmsinstall//device/device=dev-hostname/ )

### CODE REVIEW

**Comment by f0o** [comment]
We already have this with `http://librenms/devices/hostname=.../` - it's a real search and doesnt require the correct hostname but any portion of it will do the job.

**Comment by mmarchand** [comment]
ha indeed, I did not know about this search
however, it still adds a few clicks (for example I use this patch to access ports page directly too)
the idea here is to come directly on the right device on the right page to save from a searching step
so not sure if you find this relevant or not ;)

**Comment by laf** [comment]
I can see why you would want to do this, quick access to the device itself by url. It seems like one of those features few might use. It doesn't take us back in anyway so I'd vote to add it.

**Comment by f0o** [comment]
It probably doesnt do any harm.

I'd like to change the code a little bit however:
```diff
diff --git a/html/pages/device.inc.php b/html/pages/device.inc.php
index 9dcf277..0e2c166 100644
--- a/html/pages/device.inc.php
+++ b/html/pages/device.inc.php
@@ -6,10 +6,8 @@ if ($vars['tab'] == "port" && is_numeric($vars['device']) && port_permitted($var
   $permit_ports = 1;
 }
 
-$device  = device_by_id_cache($vars['device']);
-if (!$device) {
+if (!is_numeric($vars['device'])) {
   $vars['device'] = device_by_name($vars['device']);
-  $device  = device_by_id_cache($vars['device']);
 }
 
 if (device_permitted($vars['device']) || $check_device == $vars['device'])
@@ -25,6 +23,7 @@ if (device_permitted($vars['device']) || $check_device == $vars['device'])
 
   $select[$tab] = "active";
 
+  $device  = device_by_id_cache($vars['device']);
   $attribs = get_dev_attribs($device['device_id']);
 
   $entity_state = get_dev_entity_state($device['device_id']);
```

**Comment by paulgear** [comment]
+1 from me after @f0o's change added

**Pull request merged**
