### PR TITLE
Fixed issue for nagios-receiver where flapjack requires an Unix time…

### PR DESCRIPTION
**Pull request by Nesousx**
…stamp

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@Nesousx Thanks for this. Can you sign the CLA above please.

**Comment by Nesousx** [comment]
Hi laf,

I did, but it doesn't seem to "refresh" it. :(

**Comment by laf** [comment]
Did you use the same email address to sign it as is in your github profile?

**Comment by Nesousx** [comment]
As far as I know, yes. I believe it is because my commits are not linked with my user (grey Octocat logo), but I can't find the blue question mark that it supposed to give more info on why it is not linked (according to help page).

**Comment by laf** [comment]
You need to set your username/email in your git client. Once you've done that it might be easier to submit a new PR - pay attention to the changes I made here though, we don't use tabs for indentation.

**Comment by Nesousx** [comment]
Thanks for the info.
I believe that this is the issue, I didn't set my email in my git client, and pushed with my SSH key. Now, my email is set correctly (I hope), but as far as I understand it is too late for this commit.

Now, should I submit a new PR for this issue, or the fact you committed it yourself makes it "ok" for this PR?

**Comment by laf** [comment]
https://help.github.com/articles/changing-author-info/

or new pull request.

**Pull request closed without merging**
