### PR TITLE
Trust PHP session and remove remember me cookie

### LINKED ISSUE #4127: PHP session contains user login credentials
mneth in IRC reported that ibrenms is storing passwords in the PHP session file.  I think this is an unnecessary security risk.

It looks like every page request will call reauthenticate() with a chained call to authenticate() if there is no cookie.  It looks like this is the only place where the password is used.  Should this be using a local variable instead of $_SESSION? It appears to be set around [html/includes/authenticate.php line 39-47](https://github.com/librenms/librenms/blob/bf2c522c899a41c726830d5bc63f95dc8f6e7a72/html/includes/authenticate.inc.php#L39) and then only used on line 64.
#### Please note

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [ ] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

### PR DESCRIPTION
**Pull request by ekoyle**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] remove 'remember me' remnants from database schema

My rationale: By putting usernames/passwords in the session, we have already extended the ultimate level of trust there.  Reduce our exposure by removing username/password, and eliminate redundant handling caused by 'remember me' cookie.
- mitigate some session fixation concerns
- trust PHP sessions to handle 'remember me' functionality and login functionality
- add some session handling helper functions
- fix some active directory bugs (don't try to set user_id on insert to users table)

FIxes #4127

### CODE REVIEW

**Comment by murrant** [comment]
@ekoyle I'm all for getting this cleaned up to move forward, but how do you resume a session if the browser is closed?  If the answer is you don't, then please remove the "Remember Me" checkbox from the ui.

**Comment by ekoyle** [comment]
I didn't even think about that...  I need to check to see how it behaves...
chances are the session is not cleared on browser close, regardless of the
ceckbox.

-- 
Eldon

**Comment by laf** [comment]
How does this handle if a user is removed from AD/LDAP/RADIUS and they've already authed?

**Comment by ekoyle** [comment]
It doesn't.  We should probably add a method for that which doesn't require
storing every username and password; however I feel that the
username/password in the session is a much greater security risk than users
being able to continue using the service for an extra few hours or days
after deleting from the directory.

**Comment by ekoyle** [comment]
@murrant: the 'remember me' checkbox seems to be working as expected now (when unchecked, the cookie is deleted on browser close; when checked, it is theoretically retained for auth_remember days).

**Comment by laf** [comment]
I've emailed someone who's done some previous work on vulnerability testing LibreNMS asking if they can re-do it against this branch so we can be sure we aren't introducing any vulnerabilities. Will see what they say.

**Comment by laf** [comment]
I've just pushed the rebase for this.

Tested with MySQL auth - if anyone else can test other auth methods that would be great.

@librenms/reviewers

**Comment by ekoyle** [comment]
We have been running this with LDAP auth for quite some time now.  The only issue I have noticed is that sessions are timing out early (especially with 'remember me' checked).  I think this may be caused by something using sessions either before or without including authenticate.inc.php.

Is there a place put the relevant @ini_set() calls to be sure they get called before any other web-related stuff?

**Comment by ekoyle** [comment]
Would librenms/html/index.php be the appropriate place?

**Comment by laf** [comment]
We have things like html_ajax* files which get called so index.php wouldn't allow these to run. authenticate.inc.php should be included in all of those so it shouldn't be possible to not hit the php ini calls.

**Comment by ekoyle** [comment]
Since index.php references the session, we need to set the max session
lifetime before then or the sessions will be cleaned up early.  We do not
need to include authenticate.inc.php there.

**Comment by laf** [comment]
authenticate needs to be included in html/index.php so we can authenticate the user.

If you include php ini settings in html/index.php then they will need to repeating in all of the html/ajax_* calls.

**Comment by jonathon-k** [comment]
authenticate.inc.php is required before the access to the session so shouldn't that mean the settings will take before the session is created?  

Also, @laf did you ever hear anything back from your vulnerability testing contact?

**Comment by laf** [comment]
They didn't do a full check but seemed happy with the changes.

**Comment by laf** [comment]
This needs a rebase.

**Comment by ekoyle** [comment]
I wasn't sure if you were still interested in it.  I have merged the changes from master.

We have been running this on our production instance (with AD auth) for quite some time now and haven't noticed any serious problems.

**Comment by laf** [comment]
@librenms/reviewers Happy to merge?

**Comment by murrant** [comment]
I think so, I haven't tested in a long time.  Does this still remove "remember me"?  It doesn't matter to me personally as that never worked with AD and I always use a password manager, but I'm sure some care.

**Comment by ekoyle** [comment]
It removes the cookie, but leaves the checkbox.  When the box is checked,
it extends the PHP session.

**Comment by laf** [comment]
Merging in 48 hours @librenms/reviewers

**Comment by laf** [comment]
Sorry this has to be reverted as it breaks non-users device, ports and bill permissions.

**Comment by mwen** [comment]
Thankfully it's been reverted. For a few days two-factor authentication via TOTP did not work, where it would keep jumping back to the login screen after entering the authentication code (mysql auth as backend), until I temporarily disabled it in the configuration file.

**Pull request merged**
