### PR TITLE
Add APC Cooler detection

### LINKED ISSUE #11763: APC In-Row cooler not discovered
- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

https://p.libren.ms/view/717f0845
https://p.libren.ms/view/04d6a360
https://p.libren.ms/view/d90b2f0a

These are APC in-row coolers. They are a newer model. They are not detecting as an APC in-row cooler

### PR DESCRIPTION
**Pull request by karrots**
Adds discovery detection for APC InRow DX and Uniflair SP models.

InRow cooler is missing many sensors. May be bugs in the existing sensor detection code. I am testing against fairly new models.

Fixes #11763

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Can you add the Uniflair snmprec like I have added?  Doing this will test the OS detection :)

**Comment by karrots** [comment]
Ok, I think this is done correctly.

**Comment by karrots** [comment]
ok, I think I've found all the issues with the APC discovery in regards to cooling units. If you need me to squash commits or anything like that let me know.

**Comment by Jellyfrog** [comment]
Missing json test data

**Comment by karrots** [comment]
Can you point me in the correct direction to generate the needed JSON? I am not adding a new OS. The instructions for adding tests talk about JSON data being generated but I don't see any new data generated by the steps outlined.

When I run ` ./scripts/save-test-data.php -o apc -m sensors` it sticks at the following.

```--- Transport configuration
  Listening at UDP/IPv4 endpoint 127.1.6.1:1161, transport ID 1.3.6.1.6.1.1.0
```

**Comment by karrots** [comment]
Ok, JSON now included @Jellyfrog

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by karrots** [comment]
@murrant Here is my reply from discord.

**Pull request merged**
