### PR TITLE
fix: availability-map

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

somehow changes between 2 PR remained in the file.

- fix: json_decode -> true vars
- removed: services ignored/disabled (not applicable)
- fix: widget settings for disabled/ignored hosts
- fix: widget settings layout
- fix: direct page header top-bar width to accommodate disable/ignored hosts
- fix: widget tile size accept only numbers

### CODE REVIEW

**Comment by laf** [comment]
All finished @crcro?

**Comment by crcro** [comment]
yes

**Comment by laf** [comment]
Not sure this is right. I now see:

image

Before:

image

**Comment by crcro** [comment]
the show only devices/services/both it is not needed as it got from session
tile width is displayed only when compact view is select (otherwise is useless)
disabled and ignored is a select now (for better webui looks) ... still too big of a text for a small widget size

**Comment by jonathon-k** [comment]
Do you mean it comes from the session because the direct page stores a value in the session variable?
 Would it make more sense for them to be configurable independently?  So when using the widget one makes the settings changes there, and when at the direct page one makes settings changes there.

**Comment by jonathon-k** [comment]
Also, can services not be disabled/ignored?  May have been a poor assumption on my part. (I didn't realize there was a config value that would make them available to me for testing thus a typo occurred that I never new about)

**Comment by crcro** [comment]
@jonathon-k i didn't see any options to ignore/disable services so i removed that part, also i think that widget should reflect the direct page content otherwise it may create confusion (seeing a service down on widget but direct page only showing devices would make an uncorrelated view)

**Comment by laf** [comment]
Let us know when you two have worked out how this should be.

**Comment by crcro** [comment]
@laf ... from my side this can be merged

**Comment by jonathon-k** [comment]
My perspective is probably skewed because I don't use the direct page.  It works for me.  And if it doesn't, I can always diverge from master on my production instance.

**Pull request merged**
