### PR TITLE
Docs: Debian 11 Sury DPA provides PHP 8.2

### PR DESCRIPTION
**Pull request by tim427**
Default PHP version of Debian 11 (following this documentation) is 8.2 currently, instead of 8.1

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by VVelox — APPROVED** [review]

**Comment by VVelox** [comment]
Looks good to me.

**Comment by PipoCanaja** [comment]
PHP 8.2 is not validated yet. A few dependencies were not supporting it properly back in december. So I wound avoid changing this documentation yet. 8.1 seems the safe way right now.

**Comment by tim427** [comment]
> PHP 8.2 is not validated yet. A few dependencies were not supporting it properly back in december. So I wound avoid changing this documentation yet. 8.1 seems the safe way right now.

By following the first steps of the documentation (adding repo `sury.org` for PHP) will actually result in PHP 8.2 though (on Debian 11).

**Comment by murrant** [comment]
Fixed some issues with PHP 8.2 in December release.  Hasn't been much compatibility issues otherwise.

**Pull request merged**
