### PR TITLE
feature: Improve Juniper MSS Support

### PR DESCRIPTION
**Pull request by Rosiak**
Add the following sensors
- Processor
- Mempool
- State

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Would it be possible to change the snmp_gets to multi_gets?

**Comment by Rosiak** [comment]
Will see if I can get it done during the next week, my time is very limited at the moment.

**Comment by Rosiak** [comment]
Should be fixed now.

**Comment by laf** [comment]
Thanks, I've pushed a change to move all mibs to juniper dir (we should move junos + others). Can be merged when checks complete

**Pull request merged**
