### PR TITLE
Always update widget seeds when db update

### PR DESCRIPTION
**Pull request by louis-oui**
Related to https://github.com/librenms/librenms/pull/10901#discussion_r353790598

Avoid doing seeds manually : https://docs.librenms.org/Support/FAQ/#faq31

Script includes/sql-schema/update.php is called by daily.sh (in case of automatic upgrade) or build-base.php (for manual upgrade)

daily.sh
```
        case $arg in
            no-code-update)
                # Updates of the code are disabled, just check for schema updates
                # and clean up the db.
                status_run 'Updating SQL-Schema' 'php includes/sql-schema/update.php'
```

build-base.php
`require __DIR__ . '/includes/sql-schema/update.php';`

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
if the user don’t want to keep the seed data, it will come back each update

**Comment by louis-oui** [comment]
> if the user don’t want to keep the seed data, it will come back each update

you are correct. Fixed

**Comment by louis-oui** [comment]
@Jellyfrog if you agree with this change, please also merge https://github.com/librenms/librenms/pull/10901

**Comment by louis-oui** [comment]
@Jellyfrog please review this PR

**Comment by louis-oui** [comment]
@Jellyfrog @PipoCanaja 
How do you want to proceed with this PR ?
Do you have any other suggestion to update seeds automatically ?

**Comment by Jellyfrog** [comment]
I think we will try to move widget definitions from database and move to config instead

**Comment by louis-oui** [comment]
Could you tell me what is your concern with doing widget definition seeds in daily task ? I do not have your experience in this project, so I do not understand why you want something else. 

> I think we will try to move widget definitions from database and move to config instead

From what I've seen:
 - Currently list of widgets is in database/seeds/DefaultWidgetSeeder.php. It seeds widgets table.
 - users_widgets table is the user configuration. Settings column contains autogenerated info like token. 
=> How could we move users_widgets table info to manual user config (i.e. config.php or equivalent in db) ?
 - widget_id column in users_widgets  refers to widget table. 
=> It seems the only thing we can do is to move move widgets definition to a file and remove the widgets table. Then migrate widget_id column of users_widgets to text key such as availability-map alertlog-stats, alerts... (current widget column of widgets table)

```
MariaDB [librenms]> select * from widgets;
+-----------+---------------------------+----------------------+-----------------+
| widget_id | widget_title              | widget               | base_dimensions |
+-----------+---------------------------+----------------------+-----------------+
|         1 | Availability map          | availability-map     | 6,3             |
|         2 | Device summary horizontal | device-summary-horiz | 6,3             |
|         3 | Alerts                    | alerts               | 6,3             |
|         4 | Device summary vertical   | device-summary-vert  | 6,3             |
|         5 | Globe map                 | globe                | 6,3             |
|         6 | Syslog                    | syslog               | 6,3             |
|         7 | Eventlog                  | eventlog             | 6,3             |
|         8 | World map                 | worldmap             | 6,3             |
|         9 | Graylog                   | graylog              | 6,3             |
|        10 | Graph                     | generic-graph        | 6,3             |
|        11 | Top Devices               | top-devices          | 6,3             |
|        12 | Top Interfaces            | top-interfaces       | 6,3             |
|        13 | Notes                     | notes                | 6,3             |
|        14 | External Images           | generic-image        | 6,3             |
|        15 | Component Status          | component-status     | 6,3             |
|        16 | Server Stats              | server-stats         | 6,3             |
|        17 | Alert History             | alertlog             | 6,3             |
|        18 | Alert History Stats       | alertlog-stats       | 6,3             |
+-----------+---------------------------+----------------------+-----------------+
18 rows in set (0.00 sec)

MariaDB [librenms]> select * from users_widgets;
+----------------+---------+-----------+-----+-----+--------+--------+---------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| user_widget_id | user_id | widget_id | col | row | size_x | size_y | title                     | refresh | settings                                                                                                                                                                                       | dashboard_id |
+----------------+---------+-----------+-----+-----+--------+--------+---------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
|             17 |       3 |         1 |   1 |   1 |      6 |      3 | Availability map          |      60 | {"_token":"l3hlEIaN21GRJtwxxxxeqp9o4qZPOqNMPTLF3UwZcU","title":null,"type":"0","color_only_select":"0","tile_size":"12","show_disabled_and_ignored":"1","mode_select":"0","order_by":"hostname"} |            1 |
|             18 |       3 |         1 |   7 |   1 |      6 |      3 | Availability map          |      60 |                                                                                                                                                                                                |            1 |
|             19 |       3 |         2 |   7 |   4 |      6 |      3 | Device summary horizontal |      60 |                                                                                                                                                                                                |            1 |
|             20 |       3 |         4 |   1 |   4 |      6 |      3 | Device summary vertical   |      60 |                                                                                                                                                                                                |            1 |
+----------------+---------+-----------+-----+-----+--------+--------+---------------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
4 rows in set (0.00 sec)

```

**Comment by louis-oui** [comment]
@Jellyfrog any news on it ?

**Comment by louis-oui** [comment]
@kkrumm1 

This PR works perfectly. May there is a better solution to update widgets list. However, without answer to my questions, there is nothing I can do.

Not merging it blocks https://github.com/librenms/librenms/pull/10901 that would be useful to the community. 

I suggest we merge both PR that are waiting for more than one month. Code refactor will be done later

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
