### PR TITLE
feature: issue warning notification if php version is less than 5.6.4

### PR DESCRIPTION
**Pull request by murrant**
rename set_notification function in daily.sh to set_notifiable_result
print output when a daily.sh process fails

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7418)

### CODE REVIEW

**Comment by laf** [comment]
I can't help but get annoyed by 'notifiable' for some reason!

So this will introduce the min requirement as 5.6.4. When do you think this should be merged as we need to give people enough notice as we had 15% of the survey users say they run < 5.6 and 25% said we should still support < 5.6.

**Comment by murrant** [comment]
I think I'd like to target the December release for the hard minimum date.  Which means I'd like to merge this this release cycle or the next.  Giving people plenty of time to update their infrastructure.  If we have a hard date, we should update the message here to indicate that.

This does not do anything other than issue a warning.  Once we set a date, we can change this to block updates if the PHP version is not new enough.  At that time, more code needs to be added to roll back and issue a critical notification instead of a warning.

**Comment by laf** [comment]
Ok then.

I don't think this should be the first warning we give people. What about a Community post which we can run social media updates on to warn people of the soft date (this PR to be merged) then the hard date?

**Comment by murrant** [comment]
I opened this to start the discussion.

What does everyone think of these dates:
Soft: Oct. 25
Hard: Nov. 25 or Dec. 30

**Comment by murrant** [comment]
As for notifiable.  Still struggling to find an optimal name for that function :D

**Comment by laf** [comment]
Happy with those timelines aside from Dec 30. We should avoid anything that late - or push it into Jan.

**Comment by murrant** [comment]
Yeah, I was dubious about the end of December, too much other stuff going on.  But I wasn't sure if November was too early.

**Comment by laf** [comment]
Maybe we should say that it won't be any earlier than mid November but we will only merge the blocking of < 5.6 when we need to push an update that can no longer supporting it rather than just block updates based on a set date?

**Comment by murrant** [comment]
I don't think that works.  The number of things being held back by the php version will only grow and we can keep holding them back but I don't think that is a healthy thing.

Things I can think of off the top of my head:

- remove array_column library
- update dependencies to current versions instead of the last version that supports php 5.3
- Laravel
- Some sort of ORM, possibly just Eloquent from Laravel.
- Convert array format from awful php 5.3 syntax to 5.4 syntax.

**Comment by laf** [comment]
Fine by me then. Maybe we go with the cut off in the new year then?

**Comment by murrant** [comment]
Ok, January it is. Probably should be enough before the release so we get testing.

**Comment by murrant** [comment]
Added hard cut off date.  This should be merged mid-November.

**Comment by murrant** [comment]
Merge Mid November.

**Comment by laf** [comment]
Only issue I've found @murrant is that if you have auto updates disabled then this check is skipped.

It would need moving lower down in daily.sh to `post-pull` possibly?

**Pull request merged**
