### PR TITLE
Add support for -OX snmpflag to snmpwalk_cache_oid()

### LINKED ISSUE #15739: snmpwalk_cache_oid() failing with binary indexes
### The problem

`snmpwalk_cache_oid()` can't handle binary indexes with non-printable values correctly. Dell, for example, uses MAC address as index for agentAuthMgrClientAuthMethod. This results in the following SNMP walk output when using standard $snmpflags='-OQUs'

```
agentAuthMgrClientAuthMethod.'......' = dot1x
agentAuthMgrClientAuthMethod.'......' = dot1x
```

This causes `snmpwalk_cache_oid()` to return only single item:

```
array:1 [
  "'......'" => array:1 [
    "agentAuthMgrClientAuthMethod" => "dot1x"
  ]
]
```

Passing the '-OX' in $snmpflags to `snmpwalk_cache_oid()` will provide the correct output:

```
agentAuthMgrClientAuthMethod[0a:0a:0a:c9:13:bc] = dot1x
agentAuthMgrClientAuthMethod[0a:0a:0a:c9:17:12] = dot1x
```

but will lead to the following error when parsing the output:

```
ErrorException: Undefined array key 1 in /opt/librenms/includes/snmp.inc.php:436
```

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.1.0-16-g060775b00 (2024-01-12T22:04:32+02:00)
DB Schema | 2023_12_15_105529_access_points_nummonbssid_integer (276)
PHP       | 8.2.7
Python    | 3.11.2
Database  | MariaDB 10.11.4-MariaDB-1~deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================
```

### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

_No response_

### PR DESCRIPTION
**Pull request by vhuk**
Add support for -OX  snmpflag to snmpwalk_cache_oid() to  allow support for binary indexes. 

This fixes #15739.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @vhuk 
The failed test is not linked to your code, it is linked to #15722 .
It will be reverted.

**Comment by rudybroersma** [comment]
> Hi @vhuk The failed test is not linked to your code, it is linked to #15722 . It will be reverted.

Hmm, that would be mine. Looks like the test data is outdated (day difference in expiration). Would new test data fix this? Can I just add that to the original PR or should I create a new one?

**Comment by PipoCanaja** [comment]
force tests to re-run

**Comment by vhuk** [comment]
One should use `SnmpQuery` instead.

**Pull request closed without merging**
