### PR TITLE
Make the Discord transport more formatted for Discord.

### PR DESCRIPTION
**Pull request by nepeat**
Uses an embed object that Discord webhooks can use to better format. Still has some problems with it, so don't merge it yet but I have something that is a good framework for making the embeds more way more readable.

### Before change
image

### After change
IMG_22EFA51CEA7A-1

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Looks nice. Let us know when it's ready

**Comment by nepeat** [comment]
PR is now in a workable state where it shouldn't 400 because of the edge case which I have cleaned up.

Solved that edge case by redoing the embed fields by making a map of the Alert object's fields to the embed's field names. Discord does not like having blank values for the field values so I can easily ignore fields that are empty.

Brought back the normal behaviour of dumping the alert's `msg` because I found that it is acquired from the alert templates so it will be up to the user to make the alert's body better formatted.

Current state of the embed with a real world alert looks like this
image

**Comment by nepeat** [comment]
Dropped the WIP from the title. Been running for a while and a handful of alerts have been pushed through.

**Comment by SourceDoctor** [comment]
@nepeat could you retrigger tests with a dummy commit, please? :-)

**Comment by nepeat** [comment]
Sorry for the late reply! Just made a dummy commit by merging the latest master into the branch!

**Comment by nepeat** [comment]
Hi, any update on this PR? Been a while and hoping to hear some updates on this.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
