### PR TITLE
Update Installation-Ubuntu-1804-Apache.md

### PR DESCRIPTION
**Pull request by Function-10**
Added commands to save /etc/mysql/mariadb.conf.d/50-server.cnf and exit vi editor

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This should probably be a "tip" further up about how to exit VI.  And it should be in all the install docs, not just one.

**Comment by laf** [comment]
We tell people to use vi a few times but imho it's not our place to teach people how to use an editor.

**Comment by Function-10** [comment]
Updated document to only give instructions to exit the text editor.
Removed keyboard input.

**Comment by laf** [comment]
Thanks, this does need updating in all of the install guides though to remain consistent.

**Comment by Function-10** [comment]
> Thanks, this does need updating in all of the install guides though to remain consistent.

Sorry, I thought I had. Do I need to submit a new pull request?

**Comment by laf** [comment]
> Sorry, I thought I had. Do I need to submit a new pull request?

No just make sure you edit the files within the same branch: https://github.com/Function-10/librenms/tree/patch-1

**Comment by murrant** [comment]
I don't think this is adding much and would prefer to keep the install docs as succinct as possible.

**Pull request closed without merging**
