### PR TITLE
python-ipaddress is required by snmp-scan.py

### PR DESCRIPTION
**Pull request by brianegge**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
We should probably just force the script to use python 3 at this point...

**Comment by brianegge** [comment]
My install was using python 3 on a Ubuntu 19 server. 

-Brian

**Comment by murrant** [comment]
python-ipaddres doesn't exist for python 3... it is built in.

**Comment by brianegge** [comment]
I see. I thought the default python would be python3. I see Ubuntu 19 defaults to `Python 2.7.17rc1`. I would be in favor of the scan script using python3 via `#!/usr/bin/env python3`

**Pull request closed without merging**
