### PR TITLE
Fix incorrect eth0 status for Ubiquiti AirFiber 5XHD

### PR DESCRIPTION
**Pull request by nightcore500**
Ubiquiti uses separate OIDs for reading the ethernet port status. When reading out via IF-MIB the device reports that eth0 is down. This leads to eth0 being reported as "down" on every discovery. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Test fails

**Comment by nightcore500** [comment]
I am currently in contact with Ubiquiti because the problem is probably a bit deeper. It seems to be temporarily not possible to read the afLTUethConnected OID.

**Comment by Jellyfrog** [comment]
if youre polling new OIDs you need to generate new snmprec also, else tests wont match

**Comment by nightcore500** [comment]
@Jellyfrog 
But I do not read out a new OID. I read the same OID which is already read at every polling. The OID is also present in both snmprec's.

**Comment by nightcore500** [comment]
@murrant 
I also had this thought. It seems to concern only the 1.4.0 variant. I will take a closer look at it tomorrow.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
