### PR TITLE
Added support for rrdtool 1.5

### PR DESCRIPTION
**Pull request by laf**
This removes the need for a shared FS for distributed polling as rrdtool 1.5 or greater supports creating rrdfiles.

To enable this you just need:

```php
$config['rrdtool_version'] = 1.5;
```

@f0o On CI can you install rrdtool 1.5, run rrdcached and configure the above option please. Also would be good to remove all current rrd files to let it run through re-creating them all.

### CODE REVIEW

**Comment by laf** [comment]
Don't merge this just yet, seems to break some graphs running 1.5

**Comment by f0o** [comment]
Will do.

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Above build runs now with:
```php
$config['rrdtool_version'] = "1.5";
$config['rrdcached']       = "127.0.0.1:42217";
$config['rrd_dir']         = "/opt/librenms/rrd";
$config['rrdcached_dir']   = "";
```

And for rrdcached:
```shell
DISABLE=0
OPTS="-l 0:42217 -j /var/lib/rrdcached/journal/ -F -b /opt/librenms/rrd -B -w 1800 -z 900"
MAXWAIT=30
ENABLE_COREFILES=0
```

**Comment by f0o** [comment]
Need to upgrade the build to Debian Stretch. Hold on.

**Comment by laf** [comment]
Leave it for now, some graphs need the rrd command updating to support 1.5 so I'll be pushing more updates anyway

**Comment by f0o** [comment]
kk, I will see if I can get a patch into the jenkins to accept build-configs from within the PR's comment.

until then, ping me when you need the build upgraded to Debian Stretch to include RRD 1.5.4

**Comment by laf** [comment]
Fixed some network graphs not working. Compatible with both 1.4.x and 1.5.x versions of rrdtool.

**Comment by laf** [comment]
trigger ci

**Comment by laf** [comment]
Rebased

**Comment by Rosiak** [comment]
:+1:

**Pull request merged**
