### PR TITLE
Rework edituser page to allow user selection of a default dashboard

### PR DESCRIPTION
**Pull request by jonathon-k**
Pulls most edit user fields into functions to allow selective construction of the edituser page.
If can_update_users() returns 1 all applicable fields are displayed otherwise only the default dashboard select and twofactor auth sections display.

### CODE REVIEW

**Comment by laf** [comment]
I'm not sure I'm a fan of how this is done to be honest, building pages using functions seems a bit odd.

@librenms/reviewers

**Comment by paulgear** [comment]
I'm not sure how building pages with functions could be worse than doing it with include files or just single monolithic pages.  It certainly gives the opportunity to make things more self-contained.  If the change works, I'm +1 for splitting it up with functions.

**Comment by laf** [comment]
The include files way is the core of how it all works (rightly or wrongly) so changing that is difficult. If we ended up with 1,000 of functions to build all aspects of all our pages then that's just seems crazy to me and if so doing it on only one or a handful of pages is just even worse as it's then inconsistent across the entire code base.

**Comment by jonathon-k** [comment]
I was hoping to make the if blocks more readable, but the same page change could be done with variables that are created and then assigned inside the ifs and combined at the end to create the final output string.

Are you okay with the logic that performs the actual updates to the database and such staying in a function?

**Comment by murrant** [comment]
I would prefer to stick with the same style for consistency.

V2 is the place to make big changes and because we use blade templates there, things are much better.

**Comment by laf** [comment]
I'll be honest I'm still confused over this code, we're building a variable with all the html code to just print it out rather than just echoing as we go along.

**Comment by jonathon-k** [comment]
Yeah, so some of the fields could be interleaved without redundant checks
for being able to update the user.  If the preference is for echo as you
go... I'll do that and do some re-ordering.

**Comment by laf** [comment]
Overall we just want a clean codebase. We don't have that now, a lot because of the original code from the fork but we should be trying to tidy things up rather than (and this is my opinion) make it harder to read. Others might disagree with me so it's worth hearing from others before you go off and do more work on this.

**Comment by laf** [comment]
tagging @librenms/reviewers for comment

**Comment by Rosiak** [comment]
I really appreciate the effort put into this, but I am in the same boat as @murrant .

**Comment by f0o** [comment]
trigger ci

**Pull request merged**
