### PR TITLE
Added SAF Integra-X OS Support

### PR DESCRIPTION
**Pull request by noaheroufus**
Added definitions and MIBs for SAF Integra-X wireless radio support.

Added an additional 'sysDescr' check for Integra-B devices, to prevent Integra-X devices incorrectly discovering as Integra-B; OIDs are very similar and were causing issues.
Integra-B sysObjectID: .1.3.6.1.4.1.7571.100.1.1.7.1
Integra-X sysObjectID: .1.3.6.1.4.1.7571.100.1.1.7.10

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by noaheroufus** [comment]
Interesting. I received no errors when I "./lnms dev:check unit -o saf-integra-x".
Looking at the test data, the processor_usage sensor value differs completely between discovery and poller. I'm not entirely sure why?

**Comment by ottorei** [comment]
> 
> 
> Interesting. I received no errors when I "./lnms dev:check unit -o saf-integra-x".
> Looking at the test data, the processor_usage sensor value differs completely between discovery and poller. I'm not entirely sure why?

Was the snmprec updated after the json-file was made?

**Comment by noaheroufus** [comment]
> > Interesting. I received no errors when I "./lnms dev:check unit -o saf-integra-x".
> > Looking at the test data, the processor_usage sensor value differs completely between discovery and poller. I'm not entirely sure why?
> 
> Was the snmprec updated after the json-file was made?

No. I modified some info in the snmprec prior to generating the json. I've also tried deleting both snmprec and json and regenerated things without modifying either, and still get the differing values.

**Comment by Jellyfrog** [comment]
Weird, could you debug this? Maybe add some echo in here; https://github.com/librenms/librenms/blob/7e26331ab6850896ca49efe0b2e419fecc33fb1c/LibreNMS/Device/Processor.php#L237-L250

too see what it receives

**Comment by noaheroufus** [comment]
Seems that discovery.php is being passed the correct values. poller.php seems to be passed a value that has already been divided by 10.

Debug output on discovery.php for processData():
```
Input $value = '809'
$precision = -10
Idle $value = 100 - (809 / ( -10 * -1 ) = 19.1
Output $value = 19.099999999999994
```

Debug output on poller.php for processData():
```
Input $value = '73.5'
$precision = -10
Idle $value = 100 - (73.5 / ( -10 * -1 ) = 92.65
Output $value = 92.65
```

**Comment by noaheroufus** [comment]
Oh, I see. The MIB applies a display hint which divides the value automagically. Discovery must not use the MIB when polling for values, if I'm understanding correctly.

**Comment by Jellyfrog** [comment]
Opposite. Discovery uses mib, poller uses Oid directly

**Comment by noaheroufus** [comment]
I don't understand why these checks aren't failing on my system, or I wouldn't be pushing these bad changes. I apologize.
```
$ ./lnms dev:check ci
Running PHP lint check... success (0.09s)
Only checking os: saf-integra-x, saf-integra-b
Running unit check... 
Starting snmpsim listening on 127.1.6.2:1162... 
Info: Refusing to reset main database: librenms.  Running migrations.
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 629 ( 10%)
............................................................... 126 / 629 ( 20%)
............................................................... 189 / 629 ( 30%)
............................................................... 252 / 629 ( 40%)
............................................................... 315 / 629 ( 50%)
............................................................... 378 / 629 ( 60%)
............................................................... 441 / 629 ( 70%)
............................................................... 504 / 629 ( 80%)
............................................................... 567 / 629 ( 90%)
.......................................................SNMP['/usr/bin/snmpget' '-v2c' '-c' 'saf-integra-b' '-Ovq' '-M' '/home/nroufus/.projects/librenms/mibs' 'udp:127.1.6.2:1162' 'SNMPv2-MIB::sysDescr.0']
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'saf-integra-b' '-Ovqn' '-M' '/home/nroufus/.projects/librenms/mibs' 'udp:127.1.6.2:1162' 'SNMPv2-MIB::sysObjectID.0']
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'saf-integra-b' '-Oqv' '-m' 'SNMPv2-MIB' '-M' '/home/nroufus/.projects/librenms/mibs' 'udp:127.1.6.2:1162' 'sysName.0']
.SNMP['/usr/bin/snmpget' '-v2c' '-c' 'saf-integra-x' '-Ovq' '-M' '/home/nroufus/.projects/librenms/mibs' 'udp:127.1.6.2:1162' 'SNMPv2-MIB::sysDescr.0']
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'saf-integra-x' '-Ovqn' '-M' '/home/nroufus/.projects/librenms/mibs' 'udp:127.1.6.2:1162' 'SNMPv2-MIB::sysObjectID.0']
SNMP['/usr/bin/snmpget' '-v2c' '-c' 'saf-integra-x' '-Oqv' '-m' 'SNMPv2-MIB' '-M' '/home/nroufus/.projects/librenms/mibs' 'udp:127.1.6.2:1162' 'sysName.0']
......  629 / 629 (100%)

Time: 06:24.347, Memory: 414.50 MB

OK (629 tests, 3653 assertions)
success (393.12s)
```

```
$ git status
On branch new-integrax
Your branch is up to date with 'origin/new-integrax'.

nothing to commit, working tree clean
```

**Comment by murrant** [comment]
> Oh, I see. The MIB applies a display hint which divides the value automagically. Discovery must not use the MIB when polling for values, if I'm understanding correctly.

This means you have the mib loaded in your snmp.conf.  applying the hint to the poller call.

**Comment by noaheroufus** [comment]
> This means you have the mib loaded in your snmp.conf. applying the hint to the poller call.

That was it, thank you!

**Review by murrant — APPROVED** [review]

**Pull request merged**
