### PR TITLE
fix bdcom/pbn neighbour discovery

### PR DESCRIPTION
**Pull request by freddy36**
fix bdcom/pbn neighbour discovery

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by freddy36** [comment]
The current neighbour discovery code doesn't seem to work at all.

he snmpsim file doesn't contain any neighbour discovery realted records, so I can't check if there are any format changes.

@hrtrd @murrant @kakopedreros @vitalisator @Rosiak @laf: you contributed BDCOM/PBN code before, can you check if LLDP neighbour discovery is working with your devices and the current librenms master code?

**Comment by PipoCanaja** [comment]
Hi @freddy36 
Thanx for your contribution. 
Please take a few minutes to sign the CLA. 

And concerning the tests, this code has been changed to use the newer SNMP methods. As you noticed, test data was missing, so it was probably broken during it. So please add test data to you change, and we'll get it merged when ready. If it breaks things, we'll get more test data from other users and improve the code to handle different versions.

**Comment by PipoCanaja** [comment]
Please ignore the current test failures, it is linked to another PR and will be fixed ASAP.

**Comment by PipoCanaja** [comment]
re-run tests

**Comment by freddy36** [comment]
I've added a test.

While the snmprec file contains the relevant OIDs (1.3.6.1.4.1.3320.127.1.4.1.1), the save-test-data.php script apparently doesn't run/care about the results of the discovery-protocols modul (no neighbour informations are included in the json).

Is this the intended behaviour?
I even tried to explicitly run the module via `./scripts/save-test-data.php -o bdcom -v S2900-24S8C4X -m discovery-protocols`

**Comment by PipoCanaja** [comment]
Ok. Let see if we have a few testers for your patch. You are right, JSON does not compute links (including neighbors) right now.

**Comment by freddy36** [comment]
Given that i asked a few people which made BDCOM related commits for feedback in an old comment and no one responded it's proably unlikely that anyone can test it.
The current code calls `SnmpQuery::hideMib()->walk('NMS-LLDP-MIB::lldpRemoteSystemsData')->table();` without any parameter for `table()` which returns ungrouped SNMP data so that the resulting code can't work. It's very unlikely that it will break any existing working setups. We would appreciate it, if the change can be merged (we've another PR ready which depends on this PR).

**Review by murrant — APPROVED** [review]

**Pull request merged**
