### PR TITLE
fixed oxidized groups not being returned

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by mehran-a** [comment]
Hi,

That fixed the grouping by os but grouping by hostname still doesn't work:

`$config['oxidized']['group']['hostname'][] = array('regex' => '/^test-fw/', 'group' =>'testfw');`

**Comment by mehran-a** [comment]
Hi,

That fixed the grouping by os but grouping by hostname still doesn't work:

$config['oxidized']['group']['hostname'][] = array('regex' => '/^test-fw/', 'group' =>'testfw');

**Comment by laf** [comment]
> Hi,
> 
> That fixed the grouping by os but grouping by hostname still doesn't work:
> 
> $config['oxidized']['group']['hostname'][] = array('regex' => '/^test-fw/', 'group' =>'testfw');

Works for me:

`$config['oxidized']['group']['hostname'][] = array('regex' => '/^localhost/', 'group' =>'testfw');`

```
    {
        "hostname": "localhost",
        "os": "linux",
        "ip": "",
        "group": "testfw"
    },
```

**Comment by mehran-a** [comment]
Looks like the matching criteria has been changed now and the last matching rule wins.
Since I had a combination of os grouping and hostname grouping, had to move the hostname ones to the end to get the desired result.
Thank you

**Pull request merged**
