### PR TITLE
Added certificate file validity check for services (#10354)

### PR DESCRIPTION
**Pull request by SourceDoctor**
check for certificates with following attributes
- age in days
- remaining validity in days

### CODE REVIEW

**Comment by SourceDoctor** [comment]
something else to do on this Extension before merging?

**Comment by laf** [comment]
Thanks for this.

Does it not make sense to check a url for the cert rather than a file?

Would also need docs updating to show how to use this.

**Comment by Rosiak** [comment]
Why not just use the Nagios check_ssl_cert?

**Comment by SourceDoctor** [comment]
@laf
i modified librenms-agent so it checks a URL and not more a file.
[https://github.com/librenms/librenms-agent/pull/239](https://github.com/librenms/librenms-agent/pull/239)
I would love to update docs, but don't know where to find this file
@Rosiak
i prefer to do Monitoring stuff via snmp only ;-)

**Comment by SourceDoctor** [comment]
@laf
something else to modify?

**Comment by laf** [comment]
Docs are here for you to edit: https://github.com/SourceDoctor/librenms/blob/certificate_check/doc/Extensions/Applications.md

**Comment by SourceDoctor** [comment]
@laf
Documentation is added

**Comment by PipoCanaja** [comment]
@SourceDoctor There is a conflict with other changes that took place on Applications.md. Could you check it ? 
Thanx

**Comment by SourceDoctor** [comment]
@PipoCanaja 
conflict solved

**Comment by SourceDoctor** [comment]
@PipoCanaja @laf 
something else to change on code?

**Comment by SourceDoctor** [comment]
@laf resolved Merge Conflicts
now everything should be fine for merging :-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
