### PR TITLE
Adding Cisco ME1200 support

### PR DESCRIPTION
**Pull request by aarchijs**
I have created configuration file to add Cisco ME1200 support. 
The information that can be read through SNMP is not much.
Memory and CPU cannot be read thus removed from config file. 

In general with this configuration it is enough to have correct classification and support for this specific device. 

"poller_modules:" and "discovery_modules:" are there from my experience with these devices. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @aarchijs 
Is it really necessary to create a new OS instead of using the existing cisco code. ME switches are already supported with standard IOS.
Thanx

**Comment by aarchijs** [comment]
> Hi @aarchijs
> Thank you for your contribution !
> But is it really necessary to create a new OS instead of using the existing cisco code. ME switches are already supported with standard IOS.
> Thanx

Yes I understand but this "thing" differs quite a lot from Cisco ME36xx and ME38xx. ME1200 is new OS due to fact that it was designed as port extention of Cisco ASR900 series router and not to be used separately. But it can be used independently as a regular switch. ME1200 is not compatible with IOS. I will provide required info.

**Comment by Jellyfrog** [comment]
Missing test json file

**Comment by aarchijs** [comment]
> Missing test json file

I am unable to acquire test json file as snmpsim is unable to start. 

I get this error, but I am not sure why. 

Traceback (most recent call last):
  File "/usr/local/bin/snmpsimd.py", line 1243, in <module>
    configureManagedObjects(
  File "/usr/local/bin/snmpsimd.py", line 883, in configureManagedObjects
    dataFile = DataFile(fullPath, textParser).indexText(forceIndexBuild)
  File "/usr/local/bin/snmpsimd.py", line 241, in indexText
    self.__recordIndex.create(forceIndexBuild, validateData)
  File "/usr/local/lib/python3.8/dist-packages/snmpsim/record/search/database.py", line 93, in create
    raise error.SnmpsimError('Failed to create %s for data file %s: %s' % (self.__dbFile, self.__textFile, sys.exc_info()[1]))
snmpsim.error.SnmpsimError: Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__truenas.dbm for data file /opt/librenms/tests/snmpsim//truenas.snmprec: None

**Comment by PipoCanaja** [comment]
Rights on /tmp  ? Space  ? never had this issue so far, so just guessing. 

snmpsim is "building" a temporary file for each device it will simulate, and this file is stored in /tmp/snmpsim. 

> snmpsim.error.SnmpsimError: Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__truenas.dbm for data file /opt/librenms/tests/snmpsim//truenas.snmprec: None

**Comment by aarchijs** [comment]
> Rights on /tmp ? Space ? never had this issue so far, so just guessing.
> 
> snmpsim is "building" a temporary file for each device it will simulate, and this file is stored in /tmp/snmpsim.
> 
> > snmpsim.error.SnmpsimError: Failed to create /tmp/snmpsim/_opt_librenms_tests_snmpsim__truenas.dbm for data file /opt/librenms/tests/snmpsim//truenas.snmprec: None

Yes, it was rights on /tmp/snmpsim directory. Didn't notice previously. Thanks for tip.

**Comment by PipoCanaja** [comment]
@aarchijs 
Still don't see any added value for this new OS compared to existing one. No specific discovery or polling going on. Just standard Cisco or standard RFC. And the family (only 2 members) is EOS in a few days, replaced by Cisco NCS. 

My suggestion: 
- Remove the new OS
- Add the OID to standard Cisco discovery
- ReGenerate test data

And you'll be good to go. But of course, the OS will be wrongly displayed  as "Cisco IOS" in the LibreNMS view which is not the best, but for simplicity and maintainability, we could live with that I think.

Other option, as this OS is ME1200 named, and specific to this model only, you can rename your new OS to ciscome1200 (I know that's a long one) to avoid any confusion with all the others ME out there which are running plain IOS.

**Comment by PipoCanaja** [comment]
LGTM now. Thanx for your PR @aarchijs

**Review by PipoCanaja — APPROVED** [review]

**Pull request merged**
