### PR TITLE
webui: availability map update 5

### LINKED ISSUE #4275: Feature Request: Availability Map - Filter based on Device Groups, and custom Title
It would be nice if it was possible to filter results in the availability map to match the Device Groups.

It would also be really great if you could give the widget a custom title to match what set of devices it contained.

Thanks in advance.

### LINKED ISSUE #4345: Availability map widget issue
Hi
Availability map widget on the dashboard always shows devices with small icons. Like this:

Even if I change tile width (I tried different values)

But in Overview -> Maps -> Availability it looks like this:

Is it a bug? What is the use of the tile width?

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

update:
 - webui: can select old view widget tile size from global settings -> webui (fix #4345)
 - webui: can select new view direct page box size from global settings -> webui
 - code: added numeric field as input type (used for size input of the new webui changes)
 - db: cleaned webui db config names, enabled all help tips, added clear tips
 - widget: moved tile width to global settings -> webui
 - widget: removed the display option (got from session)
 - widget: added the custome title (fix #4275)

### CODE REVIEW

**Comment by laf** [comment]
Can you consolidate the sql schema file down, you're only just adding the two new settings so should be no need to update them already.

**Comment by crcro** [comment]
actually i'm updating older settings, not the newly 2 added

**Comment by laf** [comment]
You're right.

Leaving a blocker in place still to see where we get to with #4134 to save another rebase.

**Comment by murrant** [comment]
Rebase needed.

**Pull request closed without merging**
