### PR TITLE
feature: Oxidized basic config search

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Hacked this together this eve.

Depending on the progress of https://github.com/ytti/oxidized-web/pull/111

This enables you to leverage the Oxidized's API Config search function, giving you the ability to search through configs stored in Oxidized. Example could be that you want to find all the Cisco devices with "no service password-encryption" command set.

This is VERY basic, code should be refactored and prettified some. 
Output should also be better as it only yields matches for now.
Feel free to take it from here, at least this is a start.

screen shot 2017-01-07 at 00 10 04

### CODE REVIEW

**Comment by laf** [comment]
@Rosiak can you give this small update a test, it's just to use the helper functions to clean and display code.

**Comment by Rosiak** [comment]
@laf Works fine, thanks!

**Comment by DonovanEsterhuizen** [comment]
Where in th ui can I find this?

**Comment by DonovanEsterhuizen** [comment]
Has this been released yet?

**Comment by laf** [comment]
It's already live in the dev / daily branch but relies on an update from oxidized which afaik isn't yet released.

**Pull request merged**
