### PR TITLE
Use Oxidized API client and add support for groups on config get

### PR DESCRIPTION
**Pull request by electrocret**
Code was adapted from the device showconfig.php page.

fixes #14816

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Would you mind updating the docs to reflect your changes?

**Comment by electrocret** [comment]
I don't believe any changes are needed. The change is to Libre's algorithm. Instead of Libre assuming that the device is in Oxidized with the exact same Hostname as it is in Libre, it searches Oxidized's API for what the device's name is in Oxidized then asks for the config at that name.

**Comment by electrocret** [comment]
I just reviewed the Doc, and clarified that it should be the hostname or IP. 
Which is how the API endpoint operated before.

**Comment by westerterp** [comment]
Works like a charm on my environment :+1:

**Review by murrant — APPROVED** [review]

**Pull request merged**
