### PR TITLE
Fix Application Sudo Example

### PR DESCRIPTION
**Pull request by ZoLuSs**
On latest version of Debian (9.1 and later) snmpd run ad Debian-snmp user.
In visudo change snmp to Debian-snmp

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
nice, catch. Not wrong, but your PR only views on Debian, maybe also Ubuntu Systems.
What about the others e.G CentOS?

**Comment by murrant** [comment]
> What about the others e.G CentOS?

This ^^^^

**Comment by SourceDoctor** [comment]
maybe write something like for Debian/Ubuntu:
Debian-snmp ...
CentOS ...
snmp ...

**Comment by ZoLuSs** [comment]
Oh, because Proxmox is made and runs on Debian (to my knowledge, I've never seen Proxmox ported to CentOS, but maybe I'm wrong)

**Comment by SourceDoctor** [comment]
problem is, you want to update a generic explanation for sudo to a Debian Family specific configuration

**Comment by Cormoran96** [comment]
>  CentOS ...

It doesn't make sense. Proxmox doesn't run on Centos
https://forum.proxmox.com/threads/can-we-install-proxmox-on-a-server-running-with-centos.50431/

**Comment by SourceDoctor** [comment]
@Cormoran96 don't look on PR Title, look on the changes

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Pull request merged**
