### PR TITLE
Poller FPM

### PR DESCRIPTION
**Pull request by eskyuu**
This request adds support for using a dedicated PHP-FPM pool for the poller process, which reduce the CPU utilisation required.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by eskyuu** [comment]
I have questions on the following:
 - Is there a better place for the "EchoOutput.php" file
 - The assumption is that the original librenms php script will be in the path for librenms.sh.  Is this OK, or should I get librenms.sh to use an absolute path when running the original php script.
 - I think the presence of librenms, librenms.php and librenms.sh in the same directory could be confusing.  Do you have an idea on a better location for the new scripts
 - The lnms.sh script won't correctly handle arguments with spaces when passing them to the FPM script.  I don't think this is an issue, and I'm pretty sure it will pass arguments with space to the original script
 - The FPM process doesn't have the STDIN constant defined, and if you fopen php://stdin it doesn't work the same as the CLI.  I haven't witnessed this causing any issues with any poller modules, but it did given an error when trying to do other commands (possibly adding or removing a device from memory)
 - The current version has a hard-coded FPM socket defined in lnms.sh.  Would a variable in the .env file be a better option

**Comment by murrant** [comment]
@eskyuu as I mentioned on Discord I have serious concerns about this.  It is just not the correct approach.  fpm is not intended to be used in this way and fpm is not inherently faster than CLI.
I assume the only reason it may be faster is:

1. long running php process (cutting down startup time)
2. opcache saving cpu cycles

opcache can be enabled for php cli
Laravel queue workers can be run as long running processes

**Comment by eskyuu** [comment]
Opcache does not deliver the same savings.  The pull request below was my first attempt at this, and at this time we were running CLI opcache (I disabled it because we were getting corruption in the cache due to the Debian PHP bug), and we still saw a 15% drop in CPU usage with long running PHP processes.
https://github.com/librenms/librenms/pull/13400

Laravel queue workers looks like a good alternative to PHP-FPM for having long running processes.  I'll see how easy it is to get the poller working as a queue worker when I get the chance.

**Comment by eskyuu** [comment]
Closing - https://github.com/librenms/librenms/pull/16297 is the preferred solution using Laravel worker queues.

**Pull request closed without merging**
