### PR TITLE
Added myself to the contributors list and added the ability to list devices by location in the api

### PR DESCRIPTION
**Pull request by gilrim**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by gilrim** [comment]
fixed code style

**Comment by laf** [comment]
How come you closed this?

**Comment by gilrim** [comment]
lack of understanding of git - thought that would mean "I'm all done", not "forget this pr" :)

**Comment by laf** [comment]
All good - just needs docs :)

I've done a patch:

```
diff --git a/doc/API/API-Docs.md b/doc/API/API-Docs.md
index a332e3a..5419450 100644
--- a/doc/API/API-Docs.md
+++ b/doc/API/API-Docs.md
@@ -693,6 +693,7 @@ Input:
     - mac: search by mac address
     - ipv4: search by IPv4 address
     - ipv6: search by IPv6 address (compressed or uncompressed)
+    - location: search by location
   - query: If searching by, then this will be used as the input.
 Example:
 ```curl

```

**Comment by laf** [comment]
@gilrim this needs rebasing for AUTHORS.md

**Comment by laf** [comment]
@gilrim any further update on this?

**Pull request merged**
