### PR TITLE
more test data for junos

### PR DESCRIPTION
**Pull request by Mikeburke14**
More test data to help test against issues raised in #12683

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I think the reason this is failing is because the port data is omitted.

**Comment by Jellyfrog** [comment]
I know he edited the data manually, might be that the json is now out of sync due to removed records or so. 

@Mikeburke14 the easiest way to solve that case is to use snmpsim with your snmprec file and generate a new json. 
Not sure if we have a guide for it..
I'm on phone so bit roughly;

`lnms dev:simulate`
Then add a new device with
Ip: 127.1.6.1
Port: 1161
Community: junos_Mx10003 (same as your file name)

Then run the json step against it

**Comment by Mikeburke14** [comment]
Hey, Yeah I did edit it manually, sorry about that will fix it tomorrow and push the changes!

**Comment by Mikeburke14** [comment]
Hi,

Sorry for the delay I have a few things come up - I am still having trouble making this work.

The only thing I edited manually on this commit was to remove some hostnames from the snmprec file, nothing that actually relates to the errors in the tests

I decided to start from scratch and did the following

```
 $ ./scripts/collect-snmp-data.php -h <routerhostname> --os junos -v mx10003
OS: junos
Module(s): all
Variant: mx10003

<removed spam>

Updated snmprec data /opt/librenms/tests/snmpsim/junos_mx10003.snmprec
```

```$ ./scripts/save-test-data.php --os junos -v mx10003
Starting snmpsim listening on 127.1.6.1:1161... 
OS: junos
Module: all
Variant: mx10003

<removed spam>

Polled in 15.331 seconds
Saved to /opt/librenms/tests/data/junos_mx10003.json
Ready for testing!
```

I then rename the test, setting the export as the CI does to limit it only to those files
```
$ export FILES="tests/data/junos_mx10003.json tests/snmpsim/junos_mx10003.snmprec"
$ export SKIP_WEB_CHECK="1"
```
```
$ php lnms dev:check ci

OS junos: Polled ospf data does not match that found in tests/data/junos_mx10003.json
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
             'ospfIfMetricValue' => 700
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 568
+            'ifIndex' => null
         )
         1 => Array (
             'ospf_port_id' => '109.200.218.155.0'
@@ @@
             'ospfIfMetricValue' => 800
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 557
+            'ifIndex' => null
         )
         2 => Array (
             'ospf_port_id' => '109.200.218.188.0'
@@ @@
             'ospfIfMetricValue' => 6700
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 574
+            'ifIndex' => null
         )
         3 => Array (
             'ospf_port_id' => '109.200.218.229.0'
@@ @@
             'ospfIfMetricValue' => 700
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 550
+            'ifIndex' => null
         )
         4 => Array (
             'ospf_port_id' => '188.122.95.126.0'
@@ @@
             'ospfIfMetricValue' => 0
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 16
+            'ifIndex' => null
         )
     )
     'ospf_instances' => Array (...)

/opt/librenms/tests/OSModulesTest.php:141

FAILURES!
Tests: 17, Assertions: 99, Failures: 1.
failed (269.33s)
```

I get the exact same issue, without making any changes to the files between gathering the data and running the tests.

How should I proceed?

**Comment by murrant** [comment]
That is hard mode to run the test...

`lnms dev:check unit -o junos_mx10003`

**Comment by Mikeburke14** [comment]
Thanks but sadly that didn't help either

```
$ lnms dev:check unit -o junos_mx10003
Only checking os: junos_mx10003
Running unit check... 
Starting snmpsim listening on 127.1.6.2:1162... 
Refreshing database...done
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

.F......                                                            8 / 8 (100%)

Time: 03:51.771, Memory: 104.50 MB

There was 1 failure:

1) LibreNMS\Tests\OSModulesTest::testOS with data set "junos_mx10003" ('junos', 'mx10003', array('bgp-peers', 'os', 'ports', 'processors', 'mempools', 'vrf', 'sensors', 'storage', 'vlans', 'ospf'))
OS junos: Polled ospf data does not match that found in tests/data/junos_mx10003.json
Array
(
)
#### Load poller module ospf ####
 Processes: SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'junos_mx10003' '-OQUs' '-m' 'OSPF-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/junos' 'udp:127.1.6.2:1162' 'OSPF-MIB::ospfGeneralGroup']
1 Areas: SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'junos_mx10003' '-OQUs' '-m' 'OSPF-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/junos' 'udp:127.1.6.2:1162' 'OSPF-MIB::ospfAreaEntry']
1 Ports: SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'junos_mx10003' '-OQUs' '-m' 'OSPF-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/junos' 'udp:127.1.6.2:1162' 'OSPF-MIB::ospfIfEntry']
5 Neighbours: SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'junos_mx10003' '-OQUs' '-m' 'OSPF-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/junos' 'udp:127.1.6.2:1162' 'OSPF-MIB::ospfNbrEntry']
4 TOS Metrics: SNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'junos_mx10003' '-OQUs' '-m' 'OSPF-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/junos' 'udp:127.1.6.2:1162' 'OSPF-MIB::ospfIfMetricEntry']
5

>> Runtime for poller module 'ospf': 0.1198 seconds with 153072 bytes
>> SNMP: [5/0.10s] MySQL: [0/0.00s]
#### Unload poller module ospf ####
OS junos: Polled ospf data does not match that found in tests/data/junos_mx10003.json
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
             'ospfIfMetricValue' => 700
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 568
+            'ifIndex' => null
         )
         1 => Array (
             'ospf_port_id' => '109.200.218.155.0'
@@ @@
             'ospfIfMetricValue' => 800
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 557
+            'ifIndex' => null
         )
         2 => Array (
             'ospf_port_id' => '109.200.218.188.0'
@@ @@
             'ospfIfMetricValue' => 6700
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 574
+            'ifIndex' => null
         )
         3 => Array (
             'ospf_port_id' => '109.200.218.229.0'
@@ @@
             'ospfIfMetricValue' => 700
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 550
+            'ifIndex' => null
         )
         4 => Array (
             'ospf_port_id' => '188.122.95.126.0'
@@ @@
             'ospfIfMetricValue' => 0
             'ospfIfMetricStatus' => 'active'
             'context_name' => null
-            'ifIndex' => 16
+            'ifIndex' => null
         )
     )
     'ospf_instances' => Array (...)

/opt/librenms/tests/OSModulesTest.php:141

FAILURES!
Tests: 8, Assertions: 2289, Failures: 1.
failed (242.06s)
```
This is still with the unmodified files directly from the tools above

**Comment by murrant** [comment]
It is not connecting the ospf port to a port... is the ports module running in the test?

**Comment by Mikeburke14** [comment]
What would be the best way to check/set that? I am running a local install of librenms with default settings so I would have assumed it would have been enabled by default?

**Pull request closed without merging**
