### PR TITLE
Translate settings strings to zh-TW

### PR DESCRIPTION
**Pull request by jasoncheng7115**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jasoncheng7115** [comment]
When I translated a part of this file, I put it into the test environment, and found that the Settings page did not apply the translated traditional Chinese, so I submitted the current version first.

Have you implemented the multilingual part of the settings page?

**Comment by laf** [comment]
I'm not 100% sure, I think not because the text is pulled from the db still at the moment but that can probably be changed.

**Comment by jasoncheng7115** [comment]
Ok.
I will translate all the other parts of  next time PR.

**Comment by murrant** [comment]
Right now the translations need to be converted to json then imported into the app.js file.  I've been working to remedy this so it isn't so involved, but have not been successful yet.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
