### PR TITLE
Remove static footer and make it a simple centered text

### PR DESCRIPTION
**Pull request by arjitc**

### CODE REVIEW

**Comment by f0o** [comment]
Can't you just remove the CSS-class 'navbar-fixed-bottom' from the top element instead of altering the entire HTML-structure?

**Comment by arjitc** [comment]
Hmm, yes that can be done but it leaves a empty padding below it: http://i.imgur.com/XJjDy9H.png Trying to figure out where this padding came in from

**Comment by laf** [comment]
The navbar has a fixed height in bootstrap iirc. We've also got some additional footer padding as recommended by bootstrap:

body {
  font-family: Verdana, Arial, Helvetica, sans-serif;
  margin: 0px;
  padding: 0px;
  padding-bottom: 50px;
  padding-top: 50px;
  background: rgb(255,255,255); /* Old browsers */
  color: #555;
  font-size: 10pt;
  line-height: 20px;
}

html/css/styles.css - remove padding-bottom.

**Comment by laf** [comment]
Also, what happens when you add /debug=yes/, before it put links at the bottom within the footer.

**Comment by arjitc** [comment]
Please keep this open and I will test the debug output and report back as soon as I'm back home this week.

**Comment by laf** [comment]
@arjitc Any further info on this?

Proposing to close in 48 hours if not.

**Pull request closed without merging**
