### PR TITLE
Add discovery for ports errdisabled on Cisco NXOS

### PR DESCRIPTION
**Pull request by fbouynot**
It is not in the yaml file so it can access the interface name 

image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @fbouynot 
If I get it right, err-disabled ports are discovered during the discovery process. What happens when the issue (Err-disabled) is solved ? how does it look like in the WebUI ? And what happens at the following discovery ? 

It is not really the expected way of handling the err-disabled status.

**Comment by fbouynot** [comment]
Hi @PipoCanaja 

> If I get it right, err-disabled ports are discovered during the discovery process.
You get it right.

I came with this because it was (I think) how it was done in https://github.com/librenms/librenms/pull/7064

> What happens when the issue (Err-disabled) is solved ? how does it look like in the WebUI ? And what happens at the following discovery ?

If it is only checked at discovery, either the OID exists, or it doesn't (which is why it is tricky to check).
So if the problem is solved, the sensors disappeared.

> It is not really the expected way of handling the err-disabled status.

Yes I do agree. I was trying to setup something based on existing code, even if suboptimal (can at least catch long time suspended ports).

Although now that I have something working and you ask me how it works, I can understand a little better how I could do.
Would it be OK if I : 
- discover sensor for each existing port instead, and apply a value discovered by snmpget on suspend oid OR 0 if oid doesn't exists
- add a script for polling doing the same except the discovery part

**Comment by fbouynot** [comment]
I fixed the logic: sensors are persistent and can be polled.
image
image
I just need to regenerate test data, it should take two hours, so maybe I'll add it today, or maybe on monday.

**Comment by murrant** [comment]
NACK on this.  It should either be a trap, or an extended port status on the port itself, not a sensor.

**Pull request closed without merging**
