### PR TITLE
refactor: Update alert rules to generate sql query and store in db

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Should remain backwards compatible.

Rather than running GenSQL all the time for both polling and alerting we now do this when a rule is edited / added (and also daily just in case) and then store the query to be used directly. This saves us doing un-indexed queries against information_schema DB.

I've put a blocker on this purely because the schema number i've used is 144 as I already have 143 out for the sensors polling and whilst people test that I don't want to cause any conflicts.

### CODE REVIEW

**Comment by laf** [comment]
Just to give some info on this, it will save 1 MySQL query per alert rule per device. So 10 alert rules on 50 devices = 500 queries per poller run saved.

Will also save 1 MySQL query per alert rule run for alerts.php.

**Comment by murrant** [comment]
Seems reasonable to me, that query to information_schema bothered me when I was working on the device_group stuff as well.

**Comment by laf** [comment]
Update schema file number

**Comment by laf** [comment]
Just as an FYI that we've been running this at work for most of the week.

**Comment by Rosiak** [comment]
Not able to test this properly.

**Comment by murrant** [comment]
I don't use alerting really, so if it works for you :+1:

**Pull request merged**
