### PR TITLE
Added code to map cell RSSI on XE routers

### PR DESCRIPTION
**Pull request by lukeofthetauri**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by lukeofthetauri** [comment]
I see the codeclimate failure - I know its duplicate code, I brought it over from the Ios device. I am just an amateur who used this code in my prod environment to get IOS-XE routers to map their cellular RSSI

**Comment by murrant** [comment]
Yep, it's ok, but we shouldn't do that because if the code gets fixed in one place it doesn't in another.  There is a way to share the code.   It should be in a trait.

**Comment by murrant** [comment]
I can't update your pull request so I pushed to a new branch:  https://github.com/librenms/librenms/compare/master...murrant:cisco-cellular

Feel free to update your branch to match or I can just PR that if you like?

**Comment by lukeofthetauri** [comment]
PR that, I'll learn from what you did. Thank you!

**Comment by murrant** [comment]
Sure

**Pull request closed without merging**
