### PR TITLE
Implement dynamic temperature scale detection and value conversion for siteboss

### PR DESCRIPTION
**Pull request by thecityofguanyu**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Just added comment to the discovery file because I have no idea how to open an empty PR.

### CODE REVIEW

**Comment by murrant** [comment]
Why not use yaml to discover, but have a custom polling file?

**Comment by laf** [comment]
@murrant we don't need to have a custom polling file if we register a user function (i.e f_to_c for temps).

What this needs is a check for the returned value within yaml for the string f or F and if found we add the function. I'll take a look at this.

**Comment by laf** [comment]
@thecityofguanyu please try this patch:

https://p.libren.ms/view/raw/d22581fa

**Comment by laf** [comment]
@thecityofguanyu All work ok for you?

**Comment by thecityofguanyu** [comment]
@laf sorry, responded to you earlier on Discord.

All is good! Definitely being converted to celsius and graphing as such.

**Comment by laf** [comment]
Good shout.

Poller does it before divisor/multiplier runs so we need to do it the same for disco. This means in discovery_process()

@thecityofguanyu Can you add this patch as well please:

```php
diff --git a/includes/discovery/functions.inc.php b/includes/discovery/functions.inc.php
index 0f2eef7a5..db2328377 100644
--- a/includes/discovery/functions.inc.php
+++ b/includes/discovery/functions.inc.php
@@ -1038,6 +1038,11 @@ function discovery_process(&$valid, $device, $sensor_type, $pre_cache)
                     $high_limit = is_numeric($data['high_limit']) ? $data['high_limit'] : dynamic_discovery_get_value('high_limit', $index, $data, $pre_cache, 'null');

                     $sensor_name = $device['os'];
+
+                    if (isset($user_function) && function_exists($user_function)) {
+                        $value = $user_function($value);
+                    }
+
                     if ($sensor_type === 'state') {
                         $sensor_name = $data['state_name'] ?: $data['oid'];
                         create_state_index($sensor_name, $data['states']);

```

**Comment by thecityofguanyu** [comment]
@murrant @laf second patch applied. Re-discovered a node and re-polled sensors -- still looks good to me.

```
SNMP[/usr/bin/snmpget -v1 -c 'public' -OUQnt -M /opt/librenms/mibs:/opt/librenms/mibs/asentria udp:asentria_kel00:161 .1.3.6.1.4.1.3052.12.1.1.1.1.7.16.1.1]
.1.3.6.1.4.1.3052.12.1.1.1.1.7.16.1.1 = "47 F"

Checking (snmp) temperature temp...
8.33
RRD[update asentria_kel00/sensor-temperature-siteboss-16.1.1.rrd N:8.33 --daemon unix:/var/run/rrdcached.sock]
RRDtool Output: OK u:0.00 s:0.00 r:9.15
Sending asentria_kel00.sensor.sensor.temperature.siteboss.16_1_1.sensor 8.33 1511360467
SQL[UPDATE `sensors` set `sensor_current` ='8.33',`sensor_prev` ='7.78',`lastupdate` =NOW() WHERE `sensor_class` = 'Temperature' AND `sensor_id` = '3885']
```

**Pull request merged**
