### PR TITLE
Added API support for working with the Custom OIDs function.

### PR DESCRIPTION
**Pull request by GRMrGecko**
Please give a short description what your pull request is for

Working on automation features for the company I work for, we needed to be able to modify Custom OIDs which were added without API support. I had to add API support so that I can work with the Custom OIDs, and this is the result.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by GRMrGecko** [comment]
Not sure if there are other changes you'd like done to my additions.

**Comment by SourceDoctor** [comment]
i don't understand why CustomOID Graph would change once they are added.
If they are graph from devices, why not writing a PR to have it added the correct way.
Same for missing Graphs on existing OS/Devices.

**Comment by murrant** [comment]
@GRMrGecko Just curious, what are you using custom oids for?

**Comment by murrant** [comment]
Closed for inactivity, feel free to re-open.

**Comment by GRMrGecko** [comment]
@murrant Hey, sorry for delay in response, I had to move on with other projects at work and did not have time to review responses here. I use custom oids for monitoring a custom script I have setup with SNMP on our servers. The custom script graphs out count of PHP processes on our servers.

If you need me to adjust how it is written, let me know and I will be happy to adjust. I just needed an API available to add a custom oid, so wrote an entire API set to work with them.

**Pull request closed without merging**
