### PR TITLE
Docs refactor

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

image

Lots of shuffling around of location of docs. Some updates to the text in various places.

If this gets merged, it SHOULD push it live so be warned.

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7389)

### CODE REVIEW

**Comment by murrant** [comment]
@laf I'm trying to build this on my local machines, but I keep running into issues.  Is the theme_v2 repo fully up-to-date?

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /srv/http/docs 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.15.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mkdocs/__main__.py", line 137, in build_command
    ), clean_site_dir=clean)
  File "/usr/lib64/python2.7/site-packages/mkdocs/commands/build.py", line 289, in build
    build_pages(config)
  File "/usr/lib64/python2.7/site-packages/mkdocs/commands/build.py", line 249, in build_pages
    dump_json)
  File "/usr/lib64/python2.7/site-packages/mkdocs/commands/build.py", line 184, in _build_page
    output_content = template.render(context)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/murrant/projects/librenms/theme_v2/base.html", line 120, in top-level template code
    {%- block content %}
  File "/home/murrant/projects/librenms/theme_v2/base.html", line 129, in block "content"
    {{ page.content }}
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'page' is undefined
```

**Comment by laf** [comment]
@murrant Yes it is. I've just done a git clone in /opt/librenms for the theme and it's started ok again:

```
cd /opt/librenms/
git clone https://github.com/librenms-docs/theme_v2
mkdocs serve -a 0.0.0.0:8443
```

How are you starting it?

**Comment by murrant** [comment]
The title case for the sections needs to be corrected, but the categories look good to me.  We can always refine it later :)

I'm exporting it to a dir served by nginx.  But doing `mkdocs serve` has the same error, I think something is messed up with my mkdocs install.

**Comment by laf** [comment]
If you're happy for me to merge then I'll do it when I've got some spare time to fix any issues that might crop up

**Comment by murrant** [comment]
yeah, merge when ready @laf

**Pull request merged**
