### PR TITLE
F5-Loadbalancer module to support an expiration check of the installed certificates

### PR DESCRIPTION
**Pull request by Ferris-0815**
These patches extend the F5-Loadbalancer module to support an expiration check of the installed certificates.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Ferris-0815** [comment]
Hi,

i'm new to this. Do i have to do anything about the StyleCI complains? Or are their proposals merged automatically?

Thanks

**Comment by rudybroersma** [comment]
> i'm new to this. Do i have to do anything about the StyleCI complains? Or are their proposals merged automatically?

You have to manually apply the fixes and commit them

**Review by electrocret — APPROVED** [review]
LGTM

**Comment by DanielIsakssonTN** [comment]
Hello!

I'm new to this, but I would like clarification. Will the certificate / days left until expiration automatically update every 5 minutes? 
We have f5 loadbalancers polled by librenms, but the certificates do not automatically update after removal of the certs on the loadbalancer. The only way to update the page is by running "Capture " Discovery/Poller/Snmp after i've removed the cert from loadbalancer.

**Comment by Ferris-0815** [comment]
Hi,

The cert-check for F5 Loadbalancers is only performed during discovery. By default (i guess) this is every 6 hours.

While implementing i thought, that certs do not change that often, so i sticked to the discovery and “safed” some unnecessary roundtrips on the network.

Regards

Von: DanielIsakssonTN ***@***.***>
Gesendet: Freitag, 13. Dezember 2024 10:43
An: librenms/librenms ***@***.***>
Cc: Lockenvitz, Jan (ext) (IT ECP CFS DEV) ***@***.***>; Author ***@***.***>
Betreff: Re: [librenms/librenms] F5-Loadbalancer module to support an expiration check of the installed certificates (PR #16217)


Hello!

I'm new to this, but I would like clarification. Will the certificate / days left until expiration automatically update every 5 minutes?
We have f5 loadbalancers polled by librenms, but the certificates do not automatically update after removal of the certs on the loadbalancer. The only way to update the page is by running "Capture " Discovery/Poller/Snmp after i've removed the cert from loadbalancer.

**Pull request merged**
