### PR TITLE
Extend username to varchar(255)

### PR DESCRIPTION
**Pull request by ParthKolekar**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7395)

### CODE REVIEW

**Comment by ParthKolekar** [comment]
I was feeling lazy and opened the PR from my master. Please do let me know if there is anything that needs to be changed.

**Comment by laf** [comment]
Can you also update sessions.session_username to be the same please?

Thanks for submitting this.

**Comment by ParthKolekar** [comment]
@laf 

Please let me know if any more changes are required.

**Comment by laf** [comment]
@ParthKolekar Awesome work. Thanks.

image

**Pull request merged**
