### PR TITLE
Fix memcached always reporting "ERROR" for app_state

### PR DESCRIPTION
**Pull request by willhseitz**
perform json_encode() on memcached app $response data to match update_application() string parameter

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Nothing better to put in that field?  Just a json dump of the full data set (that is already stored in the db) does not seem that interesting.

**Comment by willhseitz** [comment]
On first glance, it seemed the only reason the $response is passed back to update_application() is only to check is there is a PHP warning/error. I figured something like json_encode() would capture all the same data, as it is being passed as an array currently

**Comment by murrant** [comment]
The intent of that field (I think) is just a simple ok/error state for the most part.

**Comment by willhseitz** [comment]
Here is the only code block from update_application() that interacts with the $response parameter:

```
    if ($response != '' && $response !== false) {
        if (str_contains($response, array(
            'Traceback (most recent call last):',
        ))) {
            $data['app_state'] = 'ERROR';
        } else {
            $data['app_state'] = 'OK';
        }
    }
```

I think converting the entire array to string via json_encode() would keep this functionality. Do you think there is a smaller subset of the array that should be JSON encoded and passed instead?

**Comment by murrant** [comment]
What is the contents of $data?
put `dd($data);` right before update_application()   (without your changes)

**Comment by willhseitz** [comment]
here is the $data output: https://p.libren.ms/view/09682872
Looks to be the collected data from the memcached application module. The only difference between this and other application pollers is that $data is still an array when passed to update_application(), which expects a string

**Comment by murrant** [comment]
Yeah you could do something like:
```php
$status = empty($data['uptime']) ? 'ERROR' : 'OK';
```

Then send that to the update_application() call

**Comment by willhseitz** [comment]
I looked over over application modules again, and noticed that most return the raw snmp_get or snmp_walk data as the $response for update_application(). I've updated memcached.inc.php to be consistent with the other application pollers

**Comment by willhseitz** [comment]
This is ready for review

**Comment by danislav** [comment]
Is this how we decide if an application is in good health? - the app_state?
I thought to use the app_state to create alerts but am not convinced that this is the best.

**Comment by willhseitz** [comment]
> Is this how we decide if an application is in good health? - the app_state?
> I thought to use the app_state to create alerts but am not convinced that this is the best.

This PR is more intended to make the memcached check consistent with other application checks, not to change the intention of the checks themselves.

**Comment by SourceDoctor** [comment]
@murrant @laf 
User Pending still actual, or ready for merge?

**Comment by willhseitz** [comment]
Ready for merge please

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Pull request merged**
