### PR TITLE
add hardware and sysObjectID field into oxidized maps

### PR DESCRIPTION
**Pull request by Negatifff**
added hardware and sysObjectID into source fields list in variable mapping for oxidized.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Negatifff** [comment]
I'm not entirely sure I made the correct changes, in particular in misc/config_definitions.json and in html/js/app.js - it is possible that changes are being made to these files in a different way. did it in Librents for the first time. if you did something wrong, please correct me.

**Comment by Negatifff** [comment]
one of the checks seems to be freezed. what to do?

**Comment by murrant** [comment]
Ignore that one it is an optional check.   Why have you included app.js?  Please revert that.

**Comment by Negatifff** [comment]
> Why have you included app.js? Please revert that.

because changes are made there

**Comment by murrant** [comment]
@Negatifff you haven't included the changes in this PR.  So if you made changes, please include them :)

**Comment by Negatifff** [comment]
> @Negatifff you haven't included the changes in this PR. So if you made changes, please include them :)
> 
> And in case you are not aware, app.js is generated by `npm run prod` Direct modification will just get overwritten.

ok, I hope I found how to do it right. I'll redo it now.

**Comment by Negatifff** [comment]
@murrant  I hope now I did everything right 
https://github.com/librenms/librenms/pull/13221

**Pull request closed without merging**
