### PR TITLE
Add missing python3 modules from repo, remove pip

### PR DESCRIPTION
**Pull request by gardar**
Please give a short description what your pull request is for

Added missing python3 modules from official debian repos and thus removing the need for pip, I do believe using the official Debian packages should be the "offical" way and using pip should be up to the user.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
What version is `python3-redis`?  Other OS have not had a sufficient version to do this.

**Comment by gardar** [comment]
It's version 3.2.1-2
https://packages.debian.org/buster/python3-redis

**Comment by murrant** [comment]
Great, can you also set setuptools?

**Comment by gardar** [comment]
Is setuptools needed if you don't use pip?

**Comment by murrant** [comment]
@gardar setuptools is used to validate the packages are available at the required versions.  So if you don't have that, the test will fail.

**Comment by gardar** [comment]
@murrant sure, done!

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
