### PR TITLE
API Call list_alert_rules now returns associated devices

### PR DESCRIPTION
**Pull request by ayyylias**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
nice work, but you have to take also a lookup into following tables:

- alert_group_map  (Alert Rules assigned to Device Groups)
- alert_location_map (Alert Rules assigned to Locations)

and also search for Alert Rules which are not listed in:
- alert_device_map (Alert Rules assigned to Devices)
- alert_group_map  (Alert Rules assigned to Device Groups)
- alert_location_map (Alert Rules assigned to Locations)
this Rules are assigned global (all Devices)

for help take a look into  LibreNMS/Alert/AlertUtil.php
maybe a concentration of sql query is possible

**Comment by SourceDoctor** [comment]
or much better to see in here: includes/html/print-alert-rules.php

**Comment by SourceDoctor** [comment]
not such long lines please :)
[Code Guideline](https://docs.librenms.org/Developing/Code-Guidelines/)

**Comment by ayyylias** [comment]
thanks! (I was going to ask how I should go about the long lines, but I found how queries are splitted elsewhere in the code)

I'll check trying to make it a more re-usable/compatible with the rest of the code tomorrow :)

**Comment by SourceDoctor** [comment]
everything fine
i'll take a look about functionality later.
on questions, don't worry asking

**Comment by SourceDoctor** [comment]
maybe you could reuse code from includes/html/print-alert-rules.php
and integrate it into a centralized function in includes/functions.php,
so API and Alert Rules Web Gui can be handled from there to avoid duplicated code

**Comment by SourceDoctor** [comment]
@ayyylias 
something new?

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen

**Pull request closed without merging**
