### PR TITLE
first and last value where always U since \" wasn't stripped from input

### PR DESCRIPTION
**Pull request by funkestefan**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7111)

### CODE REVIEW

**Comment by laf** [comment]
@murrant. I think we should apply the trim() from the previous PR to `snmp_get()`. We end up just adding `trim('"', $value)` all over the show right now. What do you reckon?

**Comment by murrant** [comment]
@laf, probably.  Again, I'm not that confident about the `\`

**Comment by laf** [comment]
@murrant then we just switch to trim('"')

**Comment by murrant** [comment]
@laf merging this for now, we can address the other change you suggested separately if you like.

**Pull request merged**
