### PR TITLE
put all the stats into the optionbar

### PR DESCRIPTION
**Pull request by arjitc**
Please give a short description what your pull request is for,

To add/list all 3 items within the optionbar

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

Before,

image

After,

image

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
could you show how it looks with all other themes?
If i remember correctly we discussed this in past and it looks not very nice on other themes
(big coloured blocked with nearly no content in it)

**Comment by arjitc** [comment]
Sure, 

Light:
image

Blue:
image

Dark:
image

Mono:
image

**Comment by SourceDoctor** [comment]
@arjitc 
yeah, i remember. We discussed this month ago and decided against, because of the "fat" bar.
Looks not really elegant

**Comment by arjitc** [comment]
@SourceDoctor I believe that was with the eventlog in #11422 

How about all in 1 line? 
chrome_2020-05-01_04-06-18

As currently/default it looks like this, with 1 item in the bar and the rest outside it
chrome_2020-04-30_05-38-48

**Comment by SourceDoctor** [comment]
i'm fine with all in one line.
thinking this would be ok :-)

**Comment by arjitc** [comment]
Also -- Just for reference,

Light:
image

Blue:
image

Dark:
image

Mono:
image

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
