### PR TITLE
Added additional Cisco FirePOWER device ID's for 2100 series

### PR DESCRIPTION
**Pull request by Brickbr1**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @Brickbr1 
Could you please ensure that indentation is done with the right amount of spaces only ? 
Thanx

**Comment by PipoCanaja** [comment]
Thanx @Brickbr1 for your contribution !

**Comment by Brickbr1** [comment]
thanks for pushing me to do it myself.

> Thanx @Brickbr1 for your contribution !

**Comment by PipoCanaja** [comment]
And now that you have seen how easy it is, you'll submit many more PR ;-)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-62-release-changelog-march-2020/11423/1

**Pull request merged**
