### PR TITLE
Add juniper rpm support

### PR DESCRIPTION
**Pull request by geg347**
Hello dear LibreNMS Community,

In this pull request I add support for Juniper RPM the same way it is already working for Cisco SLA.

So I created a discovery module juniper-rpm. It fills the same SQL table slas with a mock sla_nr field for compatibility (the real "key" for searching data is owner + tag). The code is querying the DISMAN-PING-MIB with OID for pingCtlEntry field (1.3.6.1.2.1.80.1.2.1).

I created the poller modules juniper-rpm that querying the DISMAN-PING-MIB with OID for pingCtlEntryfield (to get status), with OID for pingResultsEntry field and the JUNIPER-PING-MIB with OID for jnxPingResultsEntry field.
I did the same as Cisco SLA by creating a first RRD file with only the Round Trip Time. And I added support for IcmpEcho and IcmpTimeStamp Juniper RPM types in RRD file sla-<sla_nr>-<type>. The extra MIB values that I put in this second RRD are MInRttUs, MaxRttUs, StdDevRttUs, ProbeResponses and ProbeLoss. (if needed it is posiblle to add other value).

I adapted the code to display graphs. So I created graph and page files for those 2 RPM types. I am currently displaying 2 simple grapsh for RTT and for PacketLoss in percentage. (here again you can add whatever you want).

I tried to integrate properly this feature by declaring the modules, adding them in junos.yaml device file. I also declared the Juniper RPM types.

If I missed some part like the documentation, maybe the unit test (also not done for Cisco SLA) or if you see errors or possible improvements in those changes feel free to tell me!

I hope this feature will be useful!! I did it to completely migrate fro Observium to LibreNMS in my enterprise.
Have a nice week-end!

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Congratulations on your first pull request (and quite a large one to start with!) 🥳 

You should add test data for this to start with ( as mentioned above)

**Comment by geg347** [comment]
So I am trying to follow the doc for test data but I am not sure if I did the right things..

I first collected data for my device (vmx : virtual Juniper router). There are no sensitive data in it as it is a virtual lab for testing purpose. It generated the file /opt/librenms/tests/snmpsim/junos_vmx.snmprec.

Then I launched 3 different tests : 
    - without any options : lnms dev:check and it crashed with 2 failures (they don't seem to concern my code) :
```
There were 2 failures:

1) LibreNMS\Tests\OSDiscoveryTest::testOS with data set "nxos" ('nxos')
Test file: nxos_n3k-3064pq.snmprec

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'nxos'
+'generic'

/opt/librenms/tests/OSDiscoveryTest.php:113
/opt/librenms/tests/OSDiscoveryTest.php:77

2) LibreNMS\Tests\OSDiscoveryTest::testAllFilesTested
Not all snmprec files were checked: Array
(
    [0] => nxos_n3k-3064pq
)

Failed asserting that an array is empty.

/opt/librenms/tests/OSDiscoveryTest.php:91

FAILURES!
Tests: 2280, Assertions: 4403, Failures: 2, Skipped: 194.
failed (47.79s)
```
    - one for the modules juniper-rpm (I did not add anything so I suppose it is not implemented I got 2 skipped tests)
```
lnms dev:check unit -m juniper-rpm
Running unit check... 
Starting snmpsim listening on 127.1.6.2:1162... 
Refreshing database...done
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

SS                                                                  2 / 2 (100%)

Time: 00:00.007, Memory: 70.65 MB

OK, but incomplete, skipped, or risky tests!
Tests: 2, Assertions: 0, Skipped: 2.
success (14.12s)
```
    - one for OS JunOS and it passed successfully
```
lnms dev:check unit -o junos
Only checking os: junos
Running unit check... 
Starting snmpsim listening on 127.1.6.2:1162... 
Refreshing database...done
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

..........................                                        26 / 26 (100%)

Time: 01:19.854, Memory: 134.50 MB

OK (26 tests, 2405 assertions)
success (94.54s)
```

What should I do then, please? Just commit my new .snmprec test file with some RPM enabled in it.
Do I need to implement tests for the discovery and poller modules juniper-rpm?

Thanks for your reply!

**Comment by Jellyfrog** [comment]
You need both a snmprec and the json file. 

But yes you need to add support for your module to generate test for it. 
However first we would like to ask you to convert your new module to the newer format; 

You can find a complete example here; https://github.com/librenms/librenms/pull/12605/files

And there are other examples in https://github.com/librenms/librenms/tree/master/LibreNMS/Modules

**Comment by PipoCanaja** [comment]
@Jellyfrog
Should'nt we have only one module for SLA and RPM ? both are the same feature, for different vendors ? This could then be extended for other vendors as well (I am looking at this same feature for Huawei, currently).

**Comment by geg347** [comment]
@Jellyfrog 
OK so I should have asked before starting the development. My bad. So I need more time to implement the module the new way.

@PipoCanaja had a good question. Before I start creating a new module could we agree on how to do it, please?

I am agree to implement the Juniper RPM part (and why not the SLA as it is really similar) but to do this the right way I need some help at the beginning... I am more sysadmin than dev. 
How should I process, create a generic module called SLA and put some case for Cisco and Juniper? (@PipoCanaja  can manage the Huawey part if he wants)
Or should I create a module called RPM for only Juniper?

**Comment by geg347** [comment]
So I started to create a SLA module with first the Juniper RPM support by copying my old discovery and polling modules.
I found how to push data in database, it should look like this :
 ```
$this->syncModels($os->getDevice(), 'slas', $data);
```
But how do you replace this line for example, please ?
```
$existing_slas = dbFetchColumn('SELECT `sla_id` FROM `slas` WHERE `device_id` = :device_id AND `deleted` = 0', ['device_id' => $device['device_id']]);
```
And before I managed to put all the code in one file to test it and debug. How can I test the code now with this complex architecture...? Do I need a special software IDE or something?
Have a nice week-end!

**Comment by Jellyfrog** [comment]
> @Jellyfrog
> Should'nt we have only one module for SLA and RPM ? both are the same feature, for different vendors ? This could then be extended for other vendors as well (I am looking at this same feature for Huawei, currently).

Yes that sounds sane :)

**Comment by PipoCanaja** [comment]
@geg347 You can create the new SLA "OS agnostic" module. I can take care of the migration from current Cisco to this new module. And will after try to implement the Huawei support as well. 

To access data (both read and write) you will use this  : 
https://laravel.com/docs/8.x/eloquent-collections

Basically, it will hide the SQL into an object-oriented syntax. You can then alter the data and save it (as you will see in the PrinterSupply module @Jellyfrog sent you above). The Laravel doc above shows you how to do add where() clauses etc etc. Any request can be written using this object oriented syntax.

**Comment by geg347** [comment]
Hello,
Thank you for your help!
I have almost finished to adapt the new SLA module for Juniper RPM support and I also did the Cisco SLA part. 
But I am not sure I did it the right way. I will submit a new pull request tomorrow and we could discuss about improvements.

**Comment by geg347** [comment]
Hello, as the changes was quite big to reimplement this feature the new way LibreNMS manages modules, I did a [new Pull Request here](https://github.com/librenms/librenms/pull/12799) so this one can be close.

**Pull request closed without merging**
