### PR TITLE
Add veya as bad interface for APC

### PR DESCRIPTION
**Pull request by CirnoT**
This seems to be somehow half-broken on AP9606, it never records any actual traffic.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
> This seems to be somehow half-broken on AP9606, it never records any actual traffic.

But does on other models? If it's only one model then you should disable it on your install and leave it for others. If it's broken on all then this change would be fine.

**Comment by CirnoT** [comment]
I am afraid I have no other models to test it against, but you are right - adding it to config seems like better option for now. Anyone here care to chime in and confirm whether other models have same issue/use same interface name?

**Comment by murrant** [comment]
My APC PDUs have "lance" and "LOOPBACK" which all work fine.

**Comment by laf** [comment]
I'll close this down until we get more feedback. I can't see any mention of veya in our test data.

**Pull request closed without merging**
