### PR TITLE
Add config switch for selective polling to force HC Counter usage

### PR DESCRIPTION
**Pull request by cchance27**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
You should change the yaml for the device this is intended to fix.  No reason to merge theoretical code ;)

**Comment by murrant** [comment]
You should also add documentation here https://docs.librenms.org/Developing/os/Settings/

**Comment by laf** [comment]
I worry about things like this having done many work arounds in port polling previously.

What we tend to find is that it's a limited set of devices or even firmware versions that require this and in reality the vendor should fix it.

**Comment by cchance27** [comment]
While I agree the vendor should fix it and I’m working on that with cambium in my instance of the problem, I still think their should be a way for users to force HC to be used as the alternative is broken graphs or being forced to switch the device to full polling which in some cases might mean way more polling on larger port devices.

This just adds a last resort override for those users that are stuck.

**Comment by cchance27** [comment]
will merge documentation changes this weekend as requested. 

Is their an explanation of the device yaml's and how to handle setting config flags?

**Comment by murrant** [comment]
That is the wrong place in the documentation.
It should be documented in these two locations:
https://docs.librenms.org/Support/Configuration/
https://docs.librenms.org/Developing/os/Settings/

First one is for users using in config.php, second one is for developers in yaml files.

**Comment by cchance27** [comment]
i had considered that but as selected_ports isn't part of general documentation (because its marked as experimental) and force_hc only affects selected_ports thats why i added it to that section, adding it to those sections seems odd without those sections having mention of the selected_ports

**Comment by murrant** [comment]
I'm thinking selective port polling is not so experimental any more.

At least add it to this page, it is intended to collect ALL configurable settings for OS.
https://docs.librenms.org/Developing/os/Settings/

**Comment by murrant** [comment]
@laf I find this preferable to also walking ifHCInOctects for selected port polling.  Thoughts?

**Comment by murrant** [comment]
I'm unsure about it too.

**Comment by cchance27** [comment]
So is this a no go ? im still running it to get the cambium stuff to poll correctly :S

**Comment by laf** [comment]
@cchance27 It's not something I would merge personally.

**Pull request closed without merging**
