### PR TITLE
Device: Added basic support for BKtel Optical Amplifier

### PR DESCRIPTION
**Pull request by Torch09**
Added basic support for BKtel Optical Amplifier (KOA).

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Hi

Looks good!

Two things;

1. Did you name the mibs yourself or is that the exakt name from the vendor? Because it looks wrong

2. Could you try find a svg version of the Logo? If not, no problem.

**Comment by Torch09** [comment]
> Hi
> 
> Looks good!
> 
> Two things;
> 
> 1. Did you name the mibs yourself or is that the exakt name from the vendor? Because it looks wrong
> 2. Could you try find a svg version of the Logo? If not, no problem.

Hi,

1.
Yeah, thought the same while working with these mibs.
These were send to us from the manufacturer, so these should be the official ones.

2. 
Tried to find a .svg with google search, but I haven't had any luck.
If I stumble across one, I'll update it.

**Comment by PipoCanaja** [comment]
Hello @Torch09 
Could you rename all the MIB files with their "official" name, which is the one you find inside the file, just before the  "DEFINITIONS ::= BEGIN" at the beginning of the file :
 
`BKTEL-HFC862-BES-V01-MIB DEFINITIONS ::= BEGIN`

This way, the name of the file and the name of the MIB will match. Easier when reading the YAML file, easier when debugging, etc ect.

**Comment by Torch09** [comment]
> Hello @Torch09
> Could you rename all the MIB files with their "official" name, which is the one you find inside the file, just before the "DEFINITIONS ::= BEGIN" at the beginning of the file :
> 
> `BKTEL-HFC862-BES-V01-MIB DEFINITIONS ::= BEGIN`
> 
> This way, the name of the file and the name of the MIB will match. Easier when reading the YAML file, easier when debugging, etc ect.

Yes, no Problem. Updated the pr.

**Comment by PipoCanaja** [comment]
Looks good to me. Thanx @Torch09

**Review by PipoCanaja — APPROVED** [review]
LGTM. @Jellyfrog I leave you the merge.

**Comment by Jellyfrog** [comment]
Got no comments, good job!

**Pull request merged**
