### PR TITLE
Adding wireguard application support

### PR DESCRIPTION
**Pull request by bnerickson**
This PR adds application support for monitoring Wireguard clients' traffic and "minutes since last handshake" on a per-interface basis.  The corresponding script PR is located here: https://github.com/librenms/librenms-agent/pull/432

Below is a screenshot of the changes to the UI:

wireguard

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Npeca75** [comment]
but why python ???

think about OpenWRT devices
they are limited in flash size
LibreNMS have already support for OpenWRT, so it would be shame to left out WG from OpenWRT because interpreter could not fit in limited flash

is there any chance to rewrite this in ASH ?
yes, ASH is default in OpenWRT, and it will run nicely on full Linux bash environment

**Comment by bnerickson** [comment]
> but why python ???
> 
> think about OpenWRT devices they are limited in flash size LibreNMS have already support for OpenWRT, so it would be shame to left out WG from OpenWRT because interpreter could not fit in limited flash
> 
> is there any chance to rewrite this in ASH ? yes, ASH is default in OpenWRT, and it will run nicely on full Linux bash environment

No, this will not be rewritten in ASH.  Anyone interested in writing a version that can run on OpenWRT is welcome to do so using my code as a baseline, however.

**Review by Jellyfrog — APPROVED** [review]

**Comment by arrmo** [comment]
FYI, getting an error with the script (in Ubuntu) - pretty sure it's because `wg` needs to be run as root, but `snmpd` runs as `Debian-snmp`. I have tried adding wg, python, and the script to visudo ... but no joy. Any pointers?

Thanks!

**Comment by arrmo** [comment]
OK, even `visudo` isn't cutting it 😞. Seems you have to be root to access the wg interfaces, not just be able to run sudo. Hmm.

Any pointers appreciated!

**Comment by arrmo** [comment]
Hi,

OK, two issues I found 😄. Let me try to explain,
1) On Linux (Ubuntu), snmpd runs as Debian-snmp ... can't access / run wg. BUT - if you add this user to `visudo`, and allow `bash` to be run, then you can update the row in snmpd.conf to be, `extend wireguard /usr/bin/bash -c "sudo -i /etc/snmp/wireguard.py"`
2) The current script fails to run if any parameters are set for the interface, like (for example), `FwMark` ... the reason is, `wg show all dump` outputs this info as well, which doesn't work with the current logic. I made a small mod (captured below), then it runs correctly. Perhaps update the code?

```
        if len(line.strip().split()) == 9:
            for intf, intf_data in output_parser(line, interface_clients_dict).items():
                if intf not in output_data["data"]:
                    output_data["data"][intf] = {}
                for client, client_data in intf_data.items():
                    output_data["data"][intf][client] = client_data
```
Thanks!

**Pull request merged**
