### PR TITLE
Added instructions for rsyslog version 8

### PR DESCRIPTION
**Pull request by h-barnhart**
Added instructions for rsyslog version 8

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Maybe we could add tabs like https://docs.librenms.org/Installation/Install-LibreNMS/#install-required-packages

**Comment by h-barnhart** [comment]
Not familiar with this markup. I looked at the source file for the page you linked, but either its not correct or Git preview isn't rendering the tabs.

**Comment by Jellyfrog** [comment]
It's not markdown Specific, it's a extension to mkdocs. So it can't be previewed here

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1

**Pull request merged**
