### PR TITLE
(WIP) showing paper levels and health state for printers

### PR DESCRIPTION
**Pull request by sjtarik**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by sjtarik** [comment]
Help wanted. 

- More testing on different vendors, currently only tested on HP JetDirect
   - Typical test would be, remove all papers from a tray, poll the device.
   - Leave the tray open, poll the device.
   - Fix the current issue, poll the device.
- Current issues:
  - Paper tray level graphs are weird, probably due to device capacity and polling logic. Need ideas.
  - On HP printers, after an issue resolved, it takes two polls for device to recover. Investigate.
  - Printer detect state resolution seems to be faulty. Troubleshoot.

**Comment by murrant** [comment]
@sjtarik This is looking good overall.  Hopefully I'll get a chance to test it.

Can you convert array defs to new style? array() to []

**Comment by sjtarik** [comment]
closing and reopening another one since the commit history cluttered a lot.

**Comment by PipoCanaja** [comment]
Hi @sjtarik 
No big deal with the commit history. But now that it is done ;) 
PipoCanaja

**Pull request closed without merging**
