### PR TITLE
Billing: add peak in and out

### PR DESCRIPTION
**Pull request by bennetgallein**
This PR adds the peak in and out values for each billing period to the `bill_history` table. All values previous to the month this update is installed will be `null`.

It now also includes the peak values in the bills historical graphs:
bill_history
 
table-titles are subject to change, I just wasn't able to find the correct naming there.

This feature was requested in the librenms-discourse community here:
https://community.librenms.org/t/max-in-out-in-bills-api/16324

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
What is the benefit of calculating this ahead of time and storing it instead of calculating later?

**Review by murrant — APPROVED** [review]
LGTM, did not test.

**Comment by murrant** [comment]
@bennetgallein I thought about this a bit and it should probably be displayed in the UI.

**Comment by bennet-esyoil** [comment]
> @bennetgallein I thought about this a bit and it should probably be displayed in the UI.

I can do that, no problem.. Give me a day or two to figure things out.

**Comment by bennetgallein** [comment]
Hello @murrant ,

please see the updated PR.

**Comment by murrant** [comment]
Looks good if you plan on changing max to peak, you'll want to change it in the DB, API and UI.  If you decided to keep max, I'm fine with that.
Looks like you have some style issues that need fixing.

**Comment by bennetgallein** [comment]
:wave: @murrant 

I've decided to rename to peak instead of max, so that's changed. Also fixed the style issue there..

**Review by murrant — APPROVED** [review]
Looks good, thanks @bennetgallein

**Pull request merged**
