### PR TITLE
Add new discovery patterns in edgeswitch.yaml

### PR DESCRIPTION
**Pull request by ubnt-tim**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ubnt-tim** [comment]
@murrant Thanks for your help. There are the devices' sysDescr and sysObjectID
```
1.3.6.1.2.1.1.1.0 = STRING: "USW-5-Flex, develop.10723"
1.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.41112


1.3.6.1.2.1.1.1.0 = STRING: "UBNT US48PRO - 48 GE POE + 4 XE, 4.0.19.9951, Linux 3.6.5"
1.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.4413


1.3.6.1.2.1.1.1.0 = STRING: "Linux UBNT 4.9.65 #0 Thu Aug 30 12:10:54 2018 mips"
1.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
```

**Comment by murrant** [comment]
The last one isn't working because of the oid.

**Comment by ubnt-tim** [comment]
So third one is because the OID is incorrect, not missing entry.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-57-release-changelog-october-2019/9969/1

**Pull request merged**
