### PR TITLE
Added and updated icons

### PR DESCRIPTION
**Pull request by RobsanInc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this. Can you compress the SVG images please: https://jakearchibald.github.io/svgomg/

**Comment by RobsanInc** [comment]
SVGs have been compressed using that web app, not much compression for the ClearOS and Microsemi SVGs.

**Comment by laf** [comment]
Are you sure? This is the centos one after it's gone through that compressor: https://gist.githubusercontent.com/laf/de36cb4f4c4940bd3499d17fe85856f4/raw/c18da77e1f0894e9971879ebaf6ec1d98868e5bb/gistfile1.txt

**Comment by RobsanInc** [comment]
I just tested the centos.svg in the compressor from my branch and it shows:

624 bytes - no change

**Comment by laf** [comment]
Running the cli version? Just use the website I linked to.

**Comment by RobsanInc** [comment]
Looks like the same output, but I'm still confused why you think there's still compression available.

I used the web version, after uploading my branch svg to the online version, at the bottom right it says:
624 bytes - no change
Which means no more compression available.

**Pull request closed without merging**
