### PR TITLE
webui: Added support for lat/lng to Globe widget #6147

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #6147

### CODE REVIEW

**Comment by murrant** [comment]
Seems to be all nonsense for me :(   Also, really slow to populate.  Changes the names of things that are just towns to GPS.  Maybe I can take a closer look sometime but I can't really evaluate what is going on here.

Before:
before

After:
screenshot_20170325_143155

**Comment by laf** [comment]
Thanks for checking, I'm not quite sure if you mean that the change is showing issues now of if that's how it was before and now.

This fix was purely to place the markers in the correct place, I'm guessing from your comment about Chicago that's not the case :)

**Comment by murrant** [comment]
I think before was more correct...  They are both quite incorrect.   Some locations are lat,long, others are just town, state.

**Comment by laf** [comment]
Unless I'm reading this wrong, it doesn't seem that geochart doesn't support actual locations and just areas: https://developers.google.com/chart/interactive/docs/gallery/geochart

**Comment by murrant** [comment]
Makes sense, seems to explain the behavior.

**Pull request closed without merging**
