### PR TITLE
Fix cafSessionClientAddress ipv4 HEX to STRING (#16361) WIP

### LINKED ISSUE #16361: NAC Pool - cafSessionClientAddress
### The problem

I have a problem with pool NAC.
Namely, the IP address is not shown for one device, this is the first time I have had a problem with this.
The case is as follows:
```
cafSessionClientAddress.10102.'000000000000001496847D61' = "
$i"
cafSessionClientAddress.10110.'000000000000003696A8FC22' = "0A 0D 24 15"
cafSessionClientAddress.10116.'0000000000000019968487D5' = "0A 0D 24 1C "
cafSessionClientAddress.10118.'000000000000002A9693ADBE' = "
$!”
cafSessionClientAddress.10120.'000000000000001796848000' = "0A 0D 24 19"
cafSessionClientAddress.10128.'000000000000001596847F69' = "
$A"
cafSessionClientAddress.10129.'000000000000002F96A62F60' = "
$:"
```

The problem is with the last item, the others correctly show the IP address of the end device.

Clear SNMP otuput for "cafSessionClientAddress":
```
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10102.48.48.48.48.48.48.48.48.48.48.48.48.48.48.49.52.57.54.56.52.55.68.54.49 = STRING: "

$i"
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10110.48.48.48.48.48.48.48.48.48.48.48.48.48.48.51.55.57.54.67.55.66.53.51.66 = Hex-STRING: 0A 0D 24 15 
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10116.48.48.48.48.48.48.48.48.48.48.48.48.48.48.49.57.57.54.56.52.56.55.68.53 = Hex-STRING: 0A 0D 24 1C 
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10118.48.48.48.48.48.48.48.48.48.48.48.48.48.48.50.65.57.54.57.51.65.68.66.69 = STRING: "

$!"
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10120.48.48.48.48.48.48.48.48.48.48.48.48.48.48.49.55.57.54.56.52.56.48.48.48 = Hex-STRING: 0A 0D 24 19 
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10128.48.48.48.48.48.48.48.48.48.48.48.48.48.48.49.53.57.54.56.52.55.70.54.57 = STRING: "

$A"
.1.3.6.1.4.1.9.9.656.1.4.1.1.4.10129.48.48.48.48.48.48.48.48.48.48.48.48.48.48.50.70.57.54.65.54.50.70.54.48 = STRING: "

$:"
```
In database this recorde cell "ipaddres" is blank, not null and not 0.0.0.0.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.3.0-321-g007925927 (2024-09-04T11:19:08+02:00)
DB Schema | 2024_08_27_182000_ports_statistics_table_rev_length (299)
PHP       | 8.3.11
Python    | 3.10.12
Database  | MariaDB 10.6.18-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.4.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.3.0

### Anything in the logs that might be useful for us?

_No response_

### PR DESCRIPTION
**Pull request by kruczek8989**
Changing a parameter to fix the IP address returned by a Cisco switch in NAC (802.1X) polling code.

fixes #16361 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @kruczek8989 
Thanx for your PR.
Does this change fix the behaviour without any side-effect in your environnement ?h

Currently the test code is a little bit broken in the "master" branch, so we'll have to wait a little bit until we can have your PR reviewed and merged.

**Comment by kruczek8989** [comment]
Hi @PipoCanaja
I didn't notice anything damaged :) everything works fine and as before :)

**Comment by PipoCanaja** [comment]
@kruczek8989 Not clear why this PR has an impact on this other OS. I suspect that the issue was there before your PR. Will try to find out why.

**Comment by kruczek8989** [comment]
What other operating system is affected by my PR?

**Pull request closed without merging**
