### PR TITLE
WIP fix email duplicates

### PR DESCRIPTION
**Pull request by murrant**
add mail_use_bcc setting to put all to addresses in bcc instead
Send one email to the server instead of multiple individual mails

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Just a thought, I'm not sure it makes sense.  I don't see much reason to bcc instead of to.

**Comment by laf** [comment]
> Just a thought, I'm not sure it makes sense. I don't see much reason to bcc instead of to.

The only reason for us not to use it (at work that is) is so you have transparency of who else gets the alerts.

**Comment by SourceDoctor** [comment]
mmh BCC for Mail Transports?
What about a middle way with an option switch between CC and BCC with CC as default?
But by default i would also prefer to see who else get's this mail

**Comment by murrant** [comment]
Needs rebase

**Pull request closed without merging**
