### PR TITLE
Added initial support for teltonika

### PR DESCRIPTION
**Pull request by tomarch**
Hi,

First PR for support TELTONIKA products.
Works for RUT95X which is LTE router.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @tomarch 
Thanx for your contribution. 
Could you please rename the mib files to match the MIB official name ?

**Comment by tomarch** [comment]
This is the name given by Teltonika.
Both file refer to "TELTONIKA-MIB".
Which name can i set ?

**Comment by PipoCanaja** [comment]
Only 1 file can have a name so yes, you need to remove the not necessary one (it won't be used by snmpwalk anyway). 
And for devices using the 2nd one, you have to create a 2nd OS and a 2nd mib directory.

**Comment by tomarch** [comment]
Ok, thanks.

**Comment by PipoCanaja** [comment]
Bonjour ! 
Looks good. Here is the test data. Let's run the tests this and if all good, will be ready to merge. 
++

**Comment by tomarch** [comment]
seems to be all good. 
Thx

**Comment by PipoCanaja** [comment]
rutos.yaml is not good. 

Please rerun ```./script/save-test-data.php -o rutos ``` and commit the resulting file.

**Comment by PipoCanaja** [comment]
Bonjour,
It seems that, for some reason, when you run tests, it does not match the correct OS on the data. Are you running the test in the correct branch of your dev server? 
Basically, you have to fix the json file and check on TravisCI result, which has to pass. 
++

**Comment by spencerbutler** [comment]
@tomarch This can be a tricky one to figure out. I typically run my tests like [this](https://gist.github.com/spencerbutler/01c3d5891d7e2791fb3d3df9cabceb88#file-run-lnms-tests-sh) to avoid the "data doesn't match!" issue. Most of the time, it is cache/os_defs.cache ruining your game. Good luck, and hop on discord with any questions.

**Comment by murrant** [comment]
This happened because the binary png files don't come through in patches...

**Pull request merged**
