### PR TITLE
Use bootstraps own img-responsive class for responsive graphs

### PR DESCRIPTION
**Pull request by arjitc**
Old: http://i.imgur.com/ZKHurbZ.png 
When img-responsive is used: http://i.imgur.com/R6sTtiV.png
Automatically resizes as well when I resize the window: http://i.imgur.com/G5QxZN7.png

### CODE REVIEW

**Comment by laf** [comment]
Does this negate the need for #2537?

**Comment by arjitc** [comment]
@laf Yup, does not need the $w and $h values either.

**Comment by Alucardfh** [comment]
I just tested this PR and it is indeed working very well.

The only downside is that the bootstrap responsive code doesn't upscale image. Which anyway isn't something we want as it would blur graphs. But this means that graphs are still tiny on big resolutions.

So I also tested the changes in the PR on top of the one I have in PR #2537 which looks quite good to me and avoid my ugly workaround to reduce the blur on graphs.

Current master behavior (resolution 2560x1440): 

no-img-responsive-noupscale


With this PR : 

img-responsive-noupscale


With this PR + PR #2537 ;

img-responsive-upscale

**Comment by paulgear** [comment]
I've tested this along with PR#2537 and it looks perfect on my browser.  Big thanks, @arjitc, and :+1: to merge both this & #2537.

**Pull request merged**
