### PR TITLE
Fix nokia(TiMOS) memory

### LINKED ISSUE #12924: Memory read wrong on Nokia/TiMOS devices
From what I can understand in the _includes/definitions/discovery/timos.yaml_ file the Nokia/TiMOS devices gets polled with **sgiMemoryUsed** and **sgiMemoryAvailable** which becomes an issue if the device has more then ~4GB memory.

Instead **sgiKbMemoryUsed** and **sgiKbMemoryAvailable** should be used that reports the values in kibibytes instead of bytes.

I'm not sure what to modify to make this work - I could probably do it as a pull request if I knew what to modify.

### PR DESCRIPTION
**Pull request by paddy01**
Fix Nokia(TiMOS) mempool to use kibibyte instead of bytes to fix issues with routers that has more memory then byte counter can handle

fixes #12924.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by paddy01** [comment]
I have no idea why the test cases are not working.
The are ripped from working real world data.

**Comment by Jellyfrog** [comment]
Guessing Because you didn't update the snmprec so there is no data available for the tests too read

**Comment by Jellyfrog** [comment]
Question is, does this oid exist for all devices?

**Comment by paddy01** [comment]
> 
> 
> Question is, does this oid exist for all devices?

I cannot guarantee more then the devices I have access to and have tested - that being 
Nokia 
 7750: SR-a4,SR-c4,SR-1s,SR-7s,SR-7
 7210: SAS-Mxp, SAS-M
 7250: IXR-e

and this being in the TiMOS SYSTEM MIB this should, I suppose, be supported on all their TiMOS platforms.

**Review by murrant — APPROVED** [review]
Great work.

**Pull request merged**
