### PR TITLE
Light update

### PR DESCRIPTION
**Pull request by laf**
Not sure the red works very well on this theme. If the general consensus is ok then merge, if not, close :)

Old:

http://pasteboard.co/2FvSsDAt.png

New:

http://pasteboard.co/2FvPnCZ3.png

### CODE REVIEW

**Comment by Rosiak** [comment]
:thumbsup:

**Comment by f0o** [comment]
:+1

**Comment by laf** [comment]
@paulgear ?

I'm wary of constantly changing the theme but the red doesn't suite the light theme.

**Comment by paulgear** [comment]
I wasn't a huge fan of the red to start with, but I'd probably go with a slightly darker grey - say the same as the "NMS" in LibreNMS?

**Comment by laf** [comment]
http://pasteboard.co/2KXIvsx3.png

Darkened up :)

**Comment by f0o** [comment]
:+1:

**Pull request merged**
