### PR TITLE
Feature: skip_value can check OID existance

### PR DESCRIPTION
**Pull request by PipoCanaja**
Added a "skip_value" comparison named "exists" which will do "isset" on $a and compare the result to $b. This allows to skip a sensor if another OID exists (or does not exist). 

Use case: VRP AR routers can now display SFP dbm even without breaking other Huawei devices support. 

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Could you split the `exists` feature to its own PR?

**Comment by PipoCanaja** [comment]
I did it that way cause adding this kind of feature without a "real life" example was usually requested to be merged. 
And travis will fail if I split it, cause os_schema will be wrong. 
Are you sure you prefer it split ?

**Comment by Jellyfrog** [comment]
Yeah I get it, but thinking of the changelog, looks better as its own feature :)

**Comment by PipoCanaja** [comment]
Then I turned it the other way around :) The feature is now 1st and the AR patch is in the comments. You are right, the feature is probably more interesting than the AR router family for most of the ChangeLogs readers :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by PipoCanaja** [comment]
Hi,
You are going back in the old files @murrant :D The goal here is to check if an OID is available, whatever the value. I used it as a key to help identify whether Huawei provides value in dbm or mw, considering they don't provide the unit of course :)

https://community.librenms.org/t/libre-reading-incorrect-light-level-values-from-huawei-switchports/17853

**Comment by murrant** [comment]
@PipoCanaja Haha, I didn't check the date.  I was kinda confused about this.

**Pull request merged**
