### PR TITLE
Syslog future entries cleanup (take 2)

### PR DESCRIPTION
**Pull request by deepseth**
When switches reload, often we end up with entries in the database that show timestamps from the future. These entries then remain until the future date gets reached, which is undesirable.

This patch deletes any entries that are more than 7 days into the future. This accounts for the majority of clock skew, where devices can be hours or days ahead "legitimately" while solving for others.

 DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7282)

### CODE REVIEW

**Comment by deepseth** [comment]
I'd actually like to change this to be a configurable setting, rather than forcing an arbitrary 7 day value on everyone. Can be defaulted to 7 days, but should have a $config var. Will update and commit when ready.

**Comment by laf** [comment]
You need to doc this as well.

**Comment by murrant** [comment]
Any reason not to bound incoming syslog entries by the current time instead of allowing times in the future.   I think that approach could hide issues with timezones and incorrect clocks, but is that something we care about?

**Comment by deepseth** [comment]
I personally don't care, and would rather have all timestamps normalised to the host's local time, but that may not be true of everyone. I'm happy to dump this and just make this a simple documentation change where the vars being used by syslog server are altered instead.

**Comment by kkrumm1** [comment]
I agree with both sides I think should have both options. 
One: to have the config options to purge future syslog entries. (this pull request)
Second: Bond syslog entries as they come into the syslog server time.  (also keep in some users may not know how to configure that in syslog) 
But we should give the users the options. 
Just my two cents. 👍

**Comment by murrant** [comment]
I wouldn't mind both options with one config setting.

Like: `$config['future_syslog_handling'] = 'delete';` or 'rewrite' or 'none'.

Variable name could be better.

**Comment by kkrumm1** [comment]
that would be awesome :)

**Comment by laf** [comment]
So where are we up to with this?

**Comment by kkrumm1** [comment]
I think it's gonna be change to the syslog.conf adding and documenting the change to docs.
adding the R_ to force syslog to use the host time when recoved and not the device time recived. 
` program("/opt/librenms/syslog.php" template ("$HOST||$FACILITY||$PRIORITY||$LEVEL||$TAG||$R_YEAR-$R_MONTH-$R_DAY $R_HOUR:$R_MIN:$R_SEC||$MSG||$PROGRAM\n") template-escape(yes));
`

**Comment by deepseth** [comment]
Syslog-ng and rsyslog both now use received time rather than reported time
(rsyslog had conflicting examples to do either, depending on which block of text users opted to copy)
I'm happy to strip out the need for future deleting stuff as that's no longer really necessary

**Comment by laf** [comment]
I just thought, why not just have a config option which stops the syslog entry being processed in the first place if the data is > by X days threshold.

**Comment by laf** [comment]
@deepseth Any thoughts to my last comment?

**Comment by murrant** [comment]
I'd say, just send the doc changes and call it good.  We can point people to update their configs if they have any issues.

**Comment by laf** [comment]
Seems odd that we'd let data be stored that we know should be binned off. I'll leave you to merge if you like but seems more sensible to drop the data first to me.

**Comment by murrant** [comment]
Yeah, but the syslog message did happen, just has the incorrect date.

**Comment by laf** [comment]
I know, but we get rid of them on the next daily run anyway

**Comment by deepseth** [comment]
Sorry, my intention was to remove the 'future delete' stuff, and just use the documentation change to have timestamps replaced on ingress at syslog-ng / rsyslog, since that essentially resolves the problem, and doesn't result in messages getting lost due to timestamp issues.

**Comment by murrant** [comment]
@deepseth Are planning on updating this PR?

**Comment by murrant** [comment]
Resubmitted in #7519

**Pull request closed without merging**
