### PR TITLE
Fix Glue-Expansion on alerts

### PR DESCRIPTION
**Pull request by f0o**

### CODE REVIEW

**Comment by f0o** [comment]
Putting a Blocker here for last fixes

**Comment by f0o** [comment]
Releasing Blocker, Redundant glue is legitimate after all.

**Comment by f0o** [comment]
Please do extensive testing on this. We dont want alerting to explode.

**Comment by laf** [comment]
Testing.....

**Comment by laf** [comment]
:+1: from me. Been running at home for 20+ hours. Alerts still triggering when they should. Using a group mapping as well.

**Pull request merged**
