### PR TITLE
webui: Do not show disabled devices in alerts list as they stale #6213

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #6213 

I've not provided an option to show hidden alerts, we might get asked for that but it adds unnecessary complicates.

### CODE REVIEW

**Comment by murrant** [comment]
Alerts are still visible at the device level, or this affects both?

**Comment by laf** [comment]
Both, I can add it back to the device page itself but the initial issue would still be valid for that page.

**Comment by murrant** [comment]
I would think it would be expected to see all device alerts on the device page even when it is disabled.

**Comment by ekoyle** [comment]
The problem is that the device is not polled and the alert isn't updated
when disabled, so the condition may have cleared in the meantime.  Maybe it
would be better to clear all alerts when a device gets disabled?

**Comment by laf** [comment]
I'm actually of the opinion we shouldn't show these on the device page as they aren't alerts. The alternative is to change the status box for the alert to 'disabled'

**Comment by murrant** [comment]
Sounds good to me.  Just wanted to discus it a bit.

**Pull request merged**
