### PR TITLE
refactor: Convert Hikvision discovery to yaml

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
I'm pretty certain (at least with some older firmware for these) that sysObjectId isn't available.

I have the cameras at home (but now use an NVR so can't snmp directly to them) but in the original PR: https://github.com/librenms/librenms/pull/393/files you can see that I did a specific check that no sysObjectId existed and then did an additional snmp call.

**Comment by murrant** [comment]
Ok, please update or close this if you can check them, thanks :)

**Comment by laf** [comment]
I can't :( It means removing them from my NVR and I'm that lazy right now :D

**Comment by murrant** [comment]
haha, fair enough.  I could possibly change it to support both, not sure how though.

**Comment by laf** [comment]
Sod it, the units are awful enough on snmp so let's just hope it's fixed in newer firmware.

**Pull request merged**
