### PR TITLE
Availability-map

### PR DESCRIPTION
**Pull request by Rosiak**
This PR consists 3 things:
  - A availability/heat map. This is just a VERY basic version. There is room for improvement, but hey gotta start somewhere!
  http://snag.gy/2Eo5g.jpg

  - Introduction of the Maps submenu, the idea is to "move" the maps "links" to here.
  This PR only introduces the availability/heat map entry in the submenu.
http://snag.gy/U4iVI.jpg

  - Removed the old "Network Map" menu shortcut, since it just linked to the overview page.

### CODE REVIEW

**Comment by f0o** [comment]
Awesome work!

Should the Network-Map link from the Devices-dropdown also be moved to the Maps submenu?
Is linking to the device-page rather than the uptime-graph more useful?

Could you use `generate_url()` on line 37 of `html/pages/availability-map.inc.php` please ?

**Comment by Rosiak** [comment]
Thx for input @f0o just made the changes.

**Comment by f0o** [comment]
I'm tagging @laf for a comment.

:+1:, I'd merge this PR :)

**Comment by laf** [comment]
I think if we can change the device map link in print-menubar to be Network Map then all good

**Pull request merged**
