### PR TITLE
Cisco Integrated Management Console

### LINKED ISSUE #4252: Cisco UCS support
Hi
Could somebody add Cisco UCSC-C220-M4S to LibreNMS, please? MIBs can be found here: http://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/mib/c-series/b_UCS_Standalone_C-Series_MIBRef/b_UCS_Standalone_C-Series_MIBRef_chapter_01.html
./discovery.php -h HOSTNAME -d -m os
http://pastebin.com/UZKRSa16
./poller.php -h HOSTNAME -r -f -d -m os
http://pastebin.com/WWhAHJhe
snmpbulkwalk -On -v2c -c COMMUNITY HOSTNAME
http://pastebin.com/SXL0Kc0j

### PR DESCRIPTION
**Pull request by adaniels21487**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Features:

- Pulls all hardware items and stores them in entPhysical and components
- A critical alarm is raised if a component fails
- Creates sensors for all graphable items.

Resolves #4252

### CODE REVIEW

**Comment by laf** [comment]
@adaniels21487 We're following psr2 now, you'll need to resolve all of the formatting issues before we can merge.

**Comment by adaniels21487** [comment]
Thanks @laf PSR-2 issues fixed.
Now I have a couple of scrutiniser issue to look at...

**Comment by laf** [comment]
What's the purpose of the cimc poller/disco modules?

Do you have a screenshot to show the output?

I realise the functions are specific to these modules but they should be moved to includes/functions.inc.php

**Comment by adaniels21487** [comment]
Hi @laf 
The discovery module pulls hardware information from the device.
This is displayed from components as a pane on the overview page for the device:
image
You can see an active PSU fault on this device.

And from entPhysical on the inventory tab:
image

The poller module checks the hardware status every poller cycle. This is for alerting only, graphing is handled by sensors.

Thanks,
Aaron

**Comment by laf** [comment]
Does this not belong in the entity-physical disco / poller module then?

We can't keep adding poller modules for each unique item per vendor, it's going to get too complicated and cause future issues.

**Comment by adaniels21487** [comment]
Hi @laf 
Sorry for the delay. I have no issues with this being in ent-physical. 
I will get on it now.

Aaron

**Comment by laf** [comment]
All good with me with one exception: We probably want to switch the entity-physical to use includes now as that's a big chunk of code :) Feel free to not do this now and I'll sort it out.

@librenms/reviewers anyone else?

**Comment by adaniels21487** [comment]
hi @laf 
Good call on splitting it out. If you're happy to wait a day or so I'll split it out now.
I'd like to investigate the 52 scrutinizer issues as well.

Aaron

**Comment by laf** [comment]
No probs, we have a release due this weekend so I've removed this from the milestone for that as we won't be merging anything except bug fixes or small fixes after today.

**Comment by f0o** [comment]
Any updates to this?

**Comment by adaniels21487** [comment]
Hi @f0o 
Yes, Sorry for the delay. I have split out the code, it all looks good on a couple of installs I run. But I'd like some further testing.
On my installs I can see inventory data from IOS and IOS-XE devices.

If testing is ok, this should be good to go.

Thanks,
Aaron

**Comment by murrant** [comment]
FYI, this code is in danger of being removed, cue to a lack of test data.

**Pull request merged**
