### PR TITLE
Config loading refactor

### PR DESCRIPTION
**Pull request by eskyuu**
- Move the code that loads the YAML files into Config.php
 - Change all code to use Config::get() either directly or indirectly, which will load the YAML files as needed
 - Add a new method for tracking the OS definitions that have been read from YAML to avoid updating the config array
 - Add a new config merge function that will completely overwrite lists

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by eskyuu** [comment]
There was caching code on the original system, but it didn't look like it was used much (except for maybe during testing).  I'm happy to re-implement if needed.

**Comment by murrant** [comment]
This will clash with #16386

**Comment by eskyuu** [comment]
I see the clash.

My point about caching is that the current release doesn't enable the cache unless discovery or poller has debug/verbose enabled.

My other comments about the current code is that it doesn't seem right that each piece of code that wants the OS config needs to explicitly call the OS helper function.

Is it worth combining both changes, or should I wait for the singleton to be merged and re-work this?  On one hand I can see it increases the chance of causing issues, but on the other it avoids having 2 separate core changes in a short timeframe.

**Comment by eskyuu** [comment]
I have create https://github.com/librenms/librenms/pull/16738 as a fork of https://github.com/librenms/librenms/pull/16386 so I can track my changes off your work.

**Pull request closed without merging**
