### PR TITLE
[dlink] added support for dgs1210-20 & dgs1210-28

### PR DESCRIPTION
**Pull request by Npeca75**
initial support for
dgs1210-20
dgs1210-28

CPU, MEM, SFP DDM, SFP Inventory

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Npeca75** [comment]
lnms1
lnms2

**Comment by PipoCanaja** [comment]
Hi @Npeca75 
I would suggest to go with 2 different OSes here. Because you would end up with no PHP code at all, and only 4 YAML files. Makes the maintenance easier for later on.
The vendor is clearly not playing nice here, when using the same textual name but different OID for 2 very similar devices, but that's their choice.

**Comment by Npeca75** [comment]
> 4 YAML files.

hi @PipoCanaja 
i would like to ask your help. How could i translate entity-physycal PHP code into YAML ?
that is first reason why i done this way

**Comment by Npeca75** [comment]
>  4 YAML files.

and, this one ...
maybe i am wrong, but could not find the way how to set limits
oid format is
ddmHighAlarm.ifIndex.alarmType
lnms1

**Comment by laf** [comment]
> i would like to ask your help. How could i translate entity-physycal PHP code into YAML ?
> that is first reason why i done this way

@Npeca75 Nice work on the PR 👍 

entity-physical isn't supported in YAML right now so leave that as is.

**Comment by laf** [comment]
> and, this one ...
> maybe i am wrong, but could not find the way how to set limits in YAML
> oid format is
> ddmHighAlarm.ifIndex.alarmType(temp/bias/dbm)

@Npeca75 in YAML:

```
                   low_limit: -10
                    low_warn_limit: -5
                    warn_limit: 8
                    high_limit: 10
```

see `includes/definitions/discovery/volius.yaml` as an example. These are hard coded but you can use responses from the snmpbulkwalk.

**Comment by Npeca75** [comment]
@laf  @PipoCanaja 
>                    low_limit: -10
>                     low_warn_limit: -5
>                     warn_limit: 8
>                     high_limit: 10

yes, i know how to set hard coded values, but i hate them. There is info in SNMP response so i like to use it
but ...

low_limit: ddmLowAlarm
high_limit: ddmHighAlarm

it is a problem
same name for every sensor

lnms1
lnms2
lnms3

one MIB, same names. It will pick wrong values


for example, in Jetstream, there is different mibs/different names
TPLINK-DDMTXPOWTHRESHOLD-MIB::ddmTxPowThresholdLowAlarm
TPLINK-DDMRXPOWTHRESHOLD-MIB::ddmRxPowThresholdLowAlarm

you see difference ? TX/RX

but there is nothing this DLINK MIB which help to pick up right one

**Comment by Npeca75** [comment]
@laf @PipoCanaja 
to be more clear...

SNMP['/usr/bin/snmpbulkwalk' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/dlink' '-v2c' '-c' 'COMMUNITY' '-OQXUte' '-Os' 'udp:HOSTNAME:5003' 'DGS-1210-28ME-AX::ddmThresholdMgmtEntry']  

ddmHighAlarm[25][temperature] = 95.000
ddmHighAlarm[25][voltage] = 3.80
ddmHighAlarm[25][bias] = 20.0
ddmHighAlarm[25][txPower] = 1.5900
ddmHighAlarm[25][rxPower] = 1.2599
ddmHighAlarm[26][temperature] = 95.000
ddmHighAlarm[26][voltage] = 3.80
ddmHighAlarm[26][bias] = 20.0
ddmHighAlarm[26][txPower] = 1.5900
ddmHighAlarm[26][rxPower] = 1.2599
ddmHighAlarm[27][temperature] = 95.000
ddmHighAlarm[27][voltage] = 3.80
ddmHighAlarm[27][bias] = 20.0
ddmHighAlarm[27][txPower] = 1.5900
ddmHighAlarm[27][rxPower] = 1.2599

i don't see any example in YAML where {{ $index }} is in middle of string :(

**Comment by Npeca75** [comment]
hi @murrant , @PipoCanaja , @laf 

i tried (again) as murrant suggested but failed, seems there is no way (or i could not figure out) how to deal with OIDs which does not end with $index

**Comment by murrant** [comment]
#13861 add support to have arbitrary strings around the sub index.  Like this:
```yaml
    pre-cache:
            data:
                -
                    oid:
                        - DGS-1210-28ME-AX::ddmThresholdMgmtTable
```

```yaml
            high_limit: DGS-1210-28ME-AX::ddmHighAlarm:0.bias
```

Additionally, I suggest always using Table over Entry  (Entry is the sub-structure of a Table)

**Pull request closed without merging**
