### PR TITLE
Improved Logging and Debugging

### PR DESCRIPTION
**Pull request by murrant**
Use Log facility when Laravel is booted.
Update init.php so we can easily boot Laravel for CLI scripts. (and just Eloquent, but that may go away)
Move all debug setup into set_debug() function and use that across all scripts.
Log Laravel database queries.
Send debug output to librenms log file when enabling debug in the webui.
Allow for colorized Log CLI output. (currently will leave % tags in log file output)

** Needs testing and perhaps tweaking still.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
`alerts.php`

```bash
Warning: flock(): supplied resource is not a valid stream resource in /opt/librenms/LibreNMS/Util/FileLock.php on line 67

Call Stack:
    0.0634    4704288   1. LibreNMS\Util\FileLock->__destruct() /opt/librenms/LibreNMS/Util/FileLock.php:0
    0.0634    4704288   2. LibreNMS\Util\FileLock->release() /opt/librenms/LibreNMS/Util/FileLock.php:54
    0.0634    4704288   3. flock() /opt/librenms/LibreNMS/Util/FileLock.php:67


Warning: fclose(): supplied resource is not a valid stream resource in /opt/librenms/LibreNMS/Util/FileLock.php on line 68

Call Stack:
    0.0634    4704288   1. LibreNMS\Util\FileLock->__destruct() /opt/librenms/LibreNMS/Util/FileLock.php:0
    0.0634    4704288   2. LibreNMS\Util\FileLock->release() /opt/librenms/LibreNMS/Util/FileLock.php:54
    0.0635    4704288   3. fclose() /opt/librenms/LibreNMS/Util/FileLock.php:68
```

```
SQL[UPDATE `alert_log` set `details` ='<binary data>'��H�jBĻ��K��`;��\'���u`i�#�b`�\Z�ܒ�M3\\�d�ƚ�m��\n�����9�L&m�4|:���Tr����a��f�ˠ���<Y�i�8~}hu\Z' WHERE id = '28573']
MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '???H?jBĻ??K??`;??\'????u`i?#??b`?\Z?ܒ?M3\\?d?ƚ?m??\n?????9?L&m?4|:???T' at line 1 (UPDATE `alert_log` set `details` ='<binary data>'��H�jBĻ��K��`;��\'���u`i�#�b`�\Z�ܒ�M3\\�d�ƚ�m��\n�����9�L&m�4|:���Tr����a��f�ˠ���<Y�i�8~}hu\Z' WHERE id = '28573')

Warning: QDB - Update failed. in /opt/librenms/includes/dbFacile.php on line 288

Call Stack:
    0.0004     393256   1. {main}() /opt/librenms/alerts.php:0
    0.0892    4709024   2. RunAlerts() /opt/librenms/alerts.php:48
    0.0992    4727904   3. dbUpdate() /opt/librenms/includes/alerts.inc.php:850
    0.1005    4727512   4. trigger_error() /opt/librenms/includes/dbFacile.php:288``
```

```
Warning: gzuncompress(): data error in /opt/librenms/includes/alerts.inc.php on line 764

Call Stack:
    0.0004     393256   1. {main}() /opt/librenms/alerts.php:0
    0.0892    4709024   2. RunAlerts() /opt/librenms/alerts.php:48
    0.0892    4709024   3. loadAlerts() /opt/librenms/includes/alerts.inc.php:779
    0.0945    4723816   4. gzuncompress() /opt/librenms/includes/alerts.inc.php:764
```

**Comment by laf** [comment]
`discovery.php`

```bash
Warning: Invalid argument supplied for foreach() in /opt/librenms/includes/discovery/vmware-vminfo.inc.php on line 25

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    5.3487    7106472   3. include('/opt/librenms/includes/discovery/vmware-vminfo.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
```

```bash
Warning: Invalid argument supplied for foreach() in /opt/librenms/includes/discovery/vlans.inc.php on line 83

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    5.2439    7110456   3. include('/opt/librenms/includes/discovery/vlans.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
```

```bash
Warning: current() expects parameter 1 to be array, null given in /opt/librenms/includes/discovery/sensors/voltage/linux.inc.php on line 23

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    4.1125    6979744   3. include('/opt/librenms/includes/discovery/sensors.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
    4.2147    7032808   4. sensors() /opt/librenms/includes/discovery/sensors.inc.php:61
    4.5512    7065736   5. include('/opt/librenms/includes/discovery/sensors/voltage/linux.inc.php') /opt/librenms/includes/discovery/functions.inc.php:1140
    4.5512    7065736   6. current() /opt/librenms/includes/discovery/sensors/voltage/linux.inc.php:23
```

```bash
Warning: current() expects parameter 1 to be array, null given in /opt/librenms/includes/discovery/sensors/state/linux.inc.php on line 29

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    4.1125    6979744   3. include('/opt/librenms/includes/discovery/sensors.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
    4.2147    7032808   4. sensors() /opt/librenms/includes/discovery/sensors.inc.php:61
    4.4023    7045992   5. include('/opt/librenms/includes/discovery/sensors/state/linux.inc.php') /opt/librenms/includes/discovery/functions.inc.php:1140
    4.4023    7045992   6. current() /opt/librenms/includes/discovery/sensors/state/linux.inc.php:29
```

```bash
Warning: include_once(/opt/librenms/includes/discovery/sensors/fanspeeds/supermicro.inc.php): failed to open stream: No such file or directory in /opt/librenms/includes/discovery/sensors/fanspeed/linux.inc.php on line 5

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    4.1125    6979744   3. include('/opt/librenms/includes/discovery/sensors.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
    4.2147    7032808   4. sensors() /opt/librenms/includes/discovery/sensors.inc.php:61
    4.2974    7035272   5. include('/opt/librenms/includes/discovery/sensors/fanspeed/linux.inc.php') /opt/librenms/includes/discovery/functions.inc.php:1140


Warning: include_once(): Failed opening '/opt/librenms/includes/discovery/sensors/fanspeeds/supermicro.inc.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /opt/librenms/includes/discovery/sensors/fanspeed/linux.inc.php on line 5

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    4.1125    6979744   3. include('/opt/librenms/includes/discovery/sensors.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
    4.2147    7032808   4. sensors() /opt/librenms/includes/discovery/sensors.inc.php:61
    4.2974    7035272   5. include('/opt/librenms/includes/discovery/sensors/fanspeed/linux.inc.php') /opt/librenms/includes/discovery/functions.inc.php:1140

SQL[SELECT * FROM sensors AS S, devices AS D WHERE S.sensor_class='fanspeed' AND S.device_id = D.device_id AND D.device_id = '1472' AND S.poller_type = 'snmp']

Frequency:
Warning: current() expects parameter 1 to be array, null given in /opt/librenms/includes/discovery/sensors/frequency/linux.inc.php on line 18

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    4.1125    6979744   3. include('/opt/librenms/includes/discovery/sensors.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
    4.2147    7032808   4. sensors() /opt/librenms/includes/discovery/sensors.inc.php:61
    4.2997    7038160   5. include('/opt/librenms/includes/discovery/sensors/frequency/linux.inc.php') /opt/librenms/includes/discovery/functions.inc.php:1140
    4.2997    7038160   6. current() /opt/librenms/includes/discovery/sensors/frequency/linux.inc.php:18
```

```bash
Warning: Invalid argument supplied for foreach() in /opt/librenms/includes/discovery/sensors/entity-sensor.inc.php on line 42

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    4.1125    6979744   3. include('/opt/librenms/includes/discovery/sensors.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
    4.1759    7055200   4. require('/opt/librenms/includes/discovery/sensors/entity-sensor.inc.php') /opt/librenms/includes/discovery/sensors.inc.php:13
```

```bash
Warning: Invalid argument supplied for foreach() in /opt/librenms/includes/discovery/ports-stack.inc.php on line 39

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    3.0647    6800256   3. include('/opt/librenms/includes/discovery/ports-stack.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
```

```bash
Warning: Invalid argument supplied for foreach() in /opt/librenms/includes/discovery/ports.inc.php on line 92

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.9356    6806168   3. include('/opt/librenms/includes/discovery/ports.inc.php') /opt/librenms/includes/discovery/functions.inc.php:183
```

```bash
Warning: array_sum() expects parameter 1 to be array, null given in /opt/librenms/includes/functions.php on line 2128

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.1318    6772224   3. printChangedStats() /opt/librenms/includes/discovery/functions.inc.php:188
    2.1318    6772296   4. array_sum() /opt/librenms/includes/functions.php:2128


Warning: array_sum() expects parameter 1 to be array, null given in /opt/librenms/includes/functions.php on line 2129

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.1318    6772224   3. printChangedStats() /opt/librenms/includes/discovery/functions.inc.php:188
    2.1319    6772296   4. array_sum() /opt/librenms/includes/functions.php:2129


Warning: array_sum() expects parameter 1 to be array, null given in /opt/librenms/includes/functions.php on line 2130

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.1318    6772224   3. printChangedStats() /opt/librenms/includes/discovery/functions.inc.php:188
    2.1320    6772296   4. array_sum() /opt/librenms/includes/functions.php:2130


Warning: array_sum() expects parameter 1 to be array, null given in /opt/librenms/includes/functions.php on line 2131

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.1318    6772224   3. printChangedStats() /opt/librenms/includes/discovery/functions.inc.php:188
    2.1320    6772296   4. array_sum() /opt/librenms/includes/functions.php:2131


Warning: array_sum() expects parameter 1 to be array, null given in /opt/librenms/includes/functions.php on line 2132

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.1318    6772224   3. printChangedStats() /opt/librenms/includes/discovery/functions.inc.php:188
    2.1320    6772296   4. array_sum() /opt/librenms/includes/functions.php:2132


Warning: array_sum() expects parameter 1 to be array, null given in /opt/librenms/includes/functions.php on line 2133

Call Stack:
    0.0006     413552   1. {main}() /opt/librenms/discovery.php:0
    1.0178    6651152   2. discover_device() /opt/librenms/discovery.php:117
    2.1318    6772224   3. printChangedStats() /opt/librenms/includes/discovery/functions.inc.php:188
    2.1320    6772296   4. array_sum() /opt/librenms/includes/functions.php:2133
```

**Comment by laf** [comment]
`legacy_index.php`

These aren't errors so will be confusing to people trying to debug things.
```bash
[2018-07-07 14:52:06] production.ERROR: 8 /opt/librenms/html/pages/devices.inc.php:347 Undefined index: type
[2018-07-07 14:52:06] production.ERROR: 8 /opt/librenms/html/pages/devices.inc.php:347 Undefined index: type
[2018-07-07 14:52:06] production.ERROR: 8 /opt/librenms/html/pages/devices.inc.php:347 Undefined index: type
[2018-07-07 14:52:06] production.ERROR: 8 /opt/librenms/html/pages/devices.inc.php:436 Undefined index: searchquery
[2018-07-07 14:52:06] production.ERROR: 8 /opt/librenms/html/pages/devices.inc.php:437 Undefined index: os
```

I do miss the debug being shown in the browser but it's not going to be a show stopper.

**Comment by laf** [comment]
`poller.php`

```bash
SQL[UPDATE `alert_log` set `details` ='<binary data>'�̋_#�Y�z��5�*����1�
                                                                       ��F:Ӳ���GW7�l7E�=�aR�7�m�fp.�Y�jh\\9���f�Q6���Xh�1����ZU��z��aa<�$�8����9��#l?
                                                                                                                                                     ;�9Eu�Pm��kO��PH����e!����dSr�2���1Z���V
                                                                                                                                                                                             -ψ�YTQtȖ��]λ��G�|nT��b#J�q�ζ\r\'�Tn�V��9n�*D��kU��TmT�s�L���{,&�X�V����VCԅ9��ZfIҍ�6���l�rL�	\nQ/<t��\ZHZ�=mcq���V�T:��wP�����jŖc��tٲwH�^�i��q�\r��qɒN�?�����|��O��{��\'��쩧;{�tgO9�ɿ=�7�+1��' WHERE id = '28576']
MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?̋_#?Y?z??5?*????1?
                                                                                                                                                                        ??F:Ӳ???GW7??l7E?=?aR?7?m?fp.?Y?jh\\9???f?Q6????X' at line 1 (UPDATE `alert_log` set `details` ='<binary data>'�̋_#�Y�z��5�*����1�
                                                             ��F:Ӳ���GW7�l7E�=�aR�7�m�fp.�Y�jh\\9���f�Q6���Xh�1����ZU��z��aa<�$�8����9��#l?
                                                                                                                                           ;�9Eu�Pm��kO��PH����e!����dSr�2���1Z���V
                                                                                                                                                                                   -ψ�YTQtȖ��]λ��G�|nT��b#J�q�ζ\r\'�Tn�V��9n�*D��kU��TmT�s�L���{,&�X�V����VCԅ9��ZfIҍ�6���l�rL�	\nQ/<t��\ZHZ�=mcq���V�T:��wP�����jŖc��tٲwH�^�i��q�\r��qɒN�?�����|��O��{��\'��쩧;{�tgO9�ɿ=�7�+1��' WHERE id = '28576')

Warning: QDB - Update failed. in /opt/librenms/includes/dbFacile.php on line 288

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    5.3687    8426928   2. RunRules() /opt/librenms/poller.php:155
    5.3897    8460080   3. dbUpdate() /opt/librenms/includes/alerts.inc.php:217
    5.3911    8460928   4. trigger_error() /opt/librenms/includes/dbFacile.php:288
```

```bash
SQL[UPDATE `alert_log` set `details` ='<binary data>'���BӒ�׈� 9-o_h�ע�h �fńF�A;�Xq*u�$��v��6z��*I�4Vz�D���\nRF��uA	�c�XY�:\0��k.�8t�4{�0�m&[�;����C��9�8ՙ5�����@j��x�<�[���\Z��q�6�row��U�pl�Z�V�9�
                                                                                                                                                                                                        ރzw���k��0 �4���;K�	��8MF�N����s��3y�\"�2N��9$a��\"~��U��)Y^\\���!̒���2��ӂ�� �$��92-��׍�`���~OxǄ�Y�X��\'@�\\Nh���P0�<1�B�qŭ������J�t�s�E��+�$�P$���Hr��ǈ\\k�E�K������:(o{r{v����A�v��^x1�HwFe9s��8���v۪M㚍
                                                                                                                                                                          6,�Ώ�+�\n�vDI�|e��P֣����Yy��Yz����3��0�Wx�g�k��i�̈́�j\r��9����wEdPD�+��O���\Z��&X��n�|oP�-.O�?��Uԃ�5��]���XpI[�V��+�������R���\n7��-ֵ0U�4����\r��|O' WHERE id = '28573']
MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '???BӒ?׈? 9-o_h?ע??h ?fńF?A;?Xq*u?$??v??6z??*I?4Vz?D???\nRF??uA	?c?XY?:\0' at line 1 (UPDATE `alert_log` set `details` ='<binary data>'���BӒ�׈� 9-o_h�ע�h �fńF�A;�Xq*u�$��v��6z��*I�4Vz�D���\nRF��uA	�c�XY�:\0��k.�8t�4{�0�m&[�;����C��9�8ՙ5�����@j��x�<�[���\Z��q�6�row��U�pl�Z�V�9�
                                                                                                                                                                                                        ރzw���k��0 �4���;K�	��8MF�N����s��3y�\"�2N��9$a��\"~��U��)Y^\\���!̒���2��ӂ�� �$��92-��׍�`���~OxǄ�Y�X��\'@�\\Nh���P0�<1�B�qŭ������J�t�s�E��+�$�P$���Hr��ǈ\\k�E�K������:(o{r{v����A�v��^x1�HwFe9s��8���v۪M㚍
                                                                                                                                                                          6,�Ώ�+�\n�vDI�|e��P֣����Yy��Yz����3��0�Wx�g�k��i�̈́�j\r��9����wEdPD�+��O���\Z��&X��n�|oP�-.O�?��Uԃ�5��]���XpI[�V��+�������R���\n7��-ֵ0U�4����\r��|O' WHERE id = '28573')

Warning: QDB - Update failed. in /opt/librenms/includes/dbFacile.php on line 288

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    5.3687    8426928   2. RunRules() /opt/librenms/poller.php:155
    5.3761    8446840   3. dbUpdate() /opt/librenms/includes/alerts.inc.php:217
    5.3831    8450232   4. trigger_error() /opt/librenms/includes/dbFacile.php:288
```

```bash
Warning: krsort() expects parameter 1 to be array, null given in /opt/librenms/includes/device-groups.inc.php on line 267

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    5.3390    8467848   3. UpdateGroupsForDevice() /opt/librenms/includes/polling/functions.inc.php:344
    5.3390    8467848   4. QueryGroupsFromDevice() /opt/librenms/includes/device-groups.inc.php:291
    5.3544    8478896   5. GenGroupSQL() /opt/librenms/includes/device-groups.inc.php:229
    5.3544    8478896   6. RunGroupMacros() /opt/librenms/includes/device-groups.inc.php:82
    5.3544    8478920   7. krsort() /opt/librenms/includes/device-groups.inc.php:267


Warning: Invalid argument supplied for foreach() in /opt/librenms/includes/device-groups.inc.php on line 268

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    5.3390    8467848   3. UpdateGroupsForDevice() /opt/librenms/includes/polling/functions.inc.php:344
    5.3390    8467848   4. QueryGroupsFromDevice() /opt/librenms/includes/device-groups.inc.php:291
    5.3544    8478896   5. GenGroupSQL() /opt/librenms/includes/device-groups.inc.php:229
    5.3544    8478896   6. RunGroupMacros() /opt/librenms/includes/device-groups.inc.php:82
```

```bash
Warning: include(includes/polling/services.inc.php): failed to open stream: No such file or directory in /opt/librenms/includes/polling/functions.inc.php on line 310

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150


Warning: include(): Failed opening 'includes/polling/services.inc.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /opt/librenms/includes/polling/functions.inc.php on line 310

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
```

```bash
Warning: array_merge() expects at least 1 parameter, 0 given in /opt/librenms/LibreNMS/Device/Sensor.php on line 297

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    4.2881    8344864   3. include('/opt/librenms/includes/polling/wireless.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
    4.2898    8461608   4. LibreNMS\Device\Sensor::poll() /opt/librenms/includes/polling/wireless.inc.php:29
    4.2906    8462808   5. call_user_func_array:{/opt/librenms/LibreNMS/Device/Sensor.php:297}() /opt/librenms/LibreNMS/Device/Sensor.php:297
    4.2906    8462872   6. array_merge() /opt/librenms/LibreNMS/Device/Sensor.php:297


Warning: array_reduce() expects parameter 1 to be array, null given in /opt/librenms/LibreNMS/Device/Sensor.php on line 422

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    4.2881    8344864   3. include('/opt/librenms/includes/polling/wireless.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
    4.2898    8461608   4. LibreNMS\Device\Sensor::poll() /opt/librenms/includes/polling/wireless.inc.php:29
    4.2907    8462808   5. LibreNMS\Device\Sensor::fetchSnmpData() /opt/librenms/LibreNMS/Device/Sensor.php:298
    4.2907    8462808   6. LibreNMS\Device\Sensor::getOidsFromSensors() /opt/librenms/LibreNMS/Device/Sensor.php:343
    4.2907    8463128   7. array_reduce() /opt/librenms/LibreNMS/Device/Sensor.php:422


Warning: array_flip() expects parameter 1 to be array, null given in /opt/librenms/LibreNMS/Device/Sensor.php on line 425

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    4.2881    8344864   3. include('/opt/librenms/includes/polling/wireless.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
    4.2898    8461608   4. LibreNMS\Device\Sensor::poll() /opt/librenms/includes/polling/wireless.inc.php:29
    4.2907    8462808   5. LibreNMS\Device\Sensor::fetchSnmpData() /opt/librenms/LibreNMS/Device/Sensor.php:298
    4.2907    8462808   6. LibreNMS\Device\Sensor::getOidsFromSensors() /opt/librenms/LibreNMS/Device/Sensor.php:343
    4.2907    8462808   7. array_flip() /opt/librenms/LibreNMS/Device/Sensor.php:425


Warning: array_keys() expects parameter 1 to be array, null given in /opt/librenms/LibreNMS/Device/Sensor.php on line 425

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    4.2881    8344864   3. include('/opt/librenms/includes/polling/wireless.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
    4.2898    8461608   4. LibreNMS\Device\Sensor::poll() /opt/librenms/includes/polling/wireless.inc.php:29
    4.2907    8462808   5. LibreNMS\Device\Sensor::fetchSnmpData() /opt/librenms/LibreNMS/Device/Sensor.php:298
    4.2907    8462808   6. LibreNMS\Device\Sensor::getOidsFromSensors() /opt/librenms/LibreNMS/Device/Sensor.php:343
    4.2908    8462808   7. array_keys() /opt/librenms/LibreNMS/Device/Sensor.php:425


Warning: array_chunk() expects parameter 1 to be array, null given in /opt/librenms/LibreNMS/Device/Sensor.php on line 425

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    4.2881    8344864   3. include('/opt/librenms/includes/polling/wireless.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
    4.2898    8461608   4. LibreNMS\Device\Sensor::poll() /opt/librenms/includes/polling/wireless.inc.php:29
    4.2907    8462808   5. LibreNMS\Device\Sensor::fetchSnmpData() /opt/librenms/LibreNMS/Device/Sensor.php:298
    4.2907    8462808   6. LibreNMS\Device\Sensor::getOidsFromSensors() /opt/librenms/LibreNMS/Device/Sensor.php:343
    4.2908    8462808   7. array_chunk() /opt/librenms/LibreNMS/Device/Sensor.php:425


Warning: Invalid argument supplied for foreach() in /opt/librenms/LibreNMS/Device/Sensor.php on line 346

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    4.2881    8344864   3. include('/opt/librenms/includes/polling/wireless.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
    4.2898    8461608   4. LibreNMS\Device\Sensor::poll() /opt/librenms/includes/polling/wireless.inc.php:29
    4.2907    8462808   5. LibreNMS\Device\Sensor::fetchSnmpData() /opt/librenms/LibreNMS/Device/Sensor.php:298
```

```bash
Warning: Division by zero in /opt/librenms/includes/polling/ports.inc.php on line 731

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    3.5943    8455856   3. include('/opt/librenms/includes/polling/ports.inc.php') /opt/librenms/includes/polling/functions.inc.php:310


Warning: Division by zero in /opt/librenms/includes/polling/ports.inc.php on line 732

Call Stack:
    0.0006     415000   1. {main}() /opt/librenms/poller.php:0
    1.0220    6908928   2. poll_device() /opt/librenms/poller.php:150
    3.5943    8455856   3. include('/opt/librenms/includes/polling/ports.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
```

```bash
Warning: inet_pton(): Unrecognized address  in /opt/librenms/includes/polling/functions.inc.php on line 247

Call Stack:
    0.0007     415000   1. {main}() /opt/librenms/poller.php:0
    1.0932    6908928   2. poll_device() /opt/librenms/poller.php:150
    1.1272    6909048   3. inet_pton() /opt/librenms/includes/polling/functions.inc.php:247
```

```bash
Warning: Use of undefined constant mempool_index - assumed 'mempool_index' (this will throw an Error in a future version of PHP) in /opt/librenms/includes/polling/mempools/hrstorage.inc.php on line 11

Call Stack:
    0.0007     415000   1. {main}() /opt/librenms/poller.php:0
    1.0932    6908928   2. poll_device() /opt/librenms/poller.php:150
   36.8464    8279416   3. include('/opt/librenms/includes/polling/mempools.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
   36.8488    8289296   4. include('/opt/librenms/includes/polling/mempools/hrstorage.inc.php') /opt/librenms/includes/polling/mempools.inc.php:13
```

```bash
Warning: Use of undefined constant storage_index - assumed 'storage_index' (this will throw an Error in a future version of PHP) in /opt/librenms/includes/polling/storage/hrstorage.inc.php on line 9

Call Stack:
    0.0007     415000   1. {main}() /opt/librenms/poller.php:0
    1.0932    6908928   2. poll_device() /opt/librenms/poller.php:150
   46.1189    8300696   3. include('/opt/librenms/includes/polling/storage.inc.php') /opt/librenms/includes/polling/functions.inc.php:310
   46.1287    8323176   4. include('/opt/librenms/includes/polling/storage/hrstorage.inc.php') /opt/librenms/includes/polling/storage.inc.php:18
```

**Comment by laf** [comment]
I know a lot of these are not because of this code but have been masked previously but it's going to add noise to an already hard to read debug output in poller/discovery imho so they should be fixed - or the noise reduced.

Does poller/discovery now print out more data (I haven't compared, just feels like it) and if so, anyway to reduce that?

**Comment by murrant** [comment]
@laf are those non-fatal at least?  I've tried to hide them in normal output, but not debug output.

Should I fix them in this PR or other PRs?  I encountered several in my testing and backed out the fixes from this PR for now.  (Most were different from the ones you linked)

**Comment by laf** [comment]
> @laf are those non-fatal at least? I've tried to hide them in normal output, but not debug output.

Correct they are non fatal but they add a lot of noise to an already messy debug output.

> Should I fix them in this PR or other PRs? I encountered several in my testing and backed out the fixes from this PR for now. (Most were different from the ones you linked)

imho they should be fixed here or before this PR goes in at least. I'm happy to help work through them but it would have to be after the transport mapping PR is done.

**Comment by murrant** [comment]
Tested for warnings with:
```
./poller.php -h all -d 2>/dev/null | egrep "Warning|Hostname: "
./discovery.php -h all -d 2>/dev/null | egrep 'Warning|device_perf'
```

**Pull request merged**
