### PR TITLE
Eltek ospf poller disable

### PR DESCRIPTION
**Pull request by loopodoopo**
Polling Eltek web power devices hang on OSPF polling even though these devices will never do anything with OSPF. 

Disabled this in the poller. 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
OSPF module doesn't have discovery, that would avoid polling delays.

**Review by laf — APPROVED** [review]
LGTM

**Comment by loopodoopo** [comment]
Are we good to get this one merged for the next release? :)

**Comment by murrant** [comment]
Sure, just never that excited about bandaid fixes ;)

**Comment by loopodoopo** [comment]
I understand. I will keep the proper fix in the back of my head. Unfortunately time is a limited resource for all of us :-)

Thank you for merging!

**Pull request merged**
