### PR TITLE
fix: Allow html but not script, head and html tags in notes widget #4898

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #4898

Strips out html/body and script tags.

### CODE REVIEW

**Comment by laf** [comment]
bump

**Comment by murrant** [comment]
How about whitelist instead of blacklist?

`<p>, <ul>, <ol>, <li>, <strong>, <em>, <pre>, <code>, <blockquote>, <cite>`  or even better something like this: http://htmlpurifier.org/

**Comment by laf** [comment]
Changed now. Using htmlpurifier in the display() function.

I've tested the pages which currently use display().

**Comment by murrant** [comment]
Use the autoloader so it only gets loaded when needed:
```php
require $install_dir . '/lib/htmlpurifier-4.8.0-lite/library/HTMLPurifier.auto.php';
```

Also, it seems to fail badly when iconv isn't present.  The docs said you only need iconv when the string isn't utf-8.  I couldn't figure out how to fix that...

**Comment by laf** [comment]
I'll have to come back to this one as I'm working on something else at the moment.

What fails for you?

**Comment by laf** [comment]
Updated

**Pull request merged**
