### PR TITLE
New lnms command to enable and disable plugins

### PR DESCRIPTION
**Pull request by murrant**
lnms plugin:disable
lnms plugin:enable

plugin name completion

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
This collides name wise with plugin:add  which is not the same type of plugins :)

**Comment by Jellyfrog** [comment]
Also deleting rockylinux logo?

**Comment by murrant** [comment]
That thing sneaking in there...  the rockylinux.svg is in the wrong place, with the wrong name.  Was prepping for a separate PR.

**Comment by Jellyfrog** [comment]
we can change the name of plugin:add to something like.. composer:add or so

**Comment by murrant** [comment]
@Jellyfrog how about package:add

**Comment by murrant** [comment]
Also, v2 plugins should be available via composer

**Comment by ryanmerolle** [comment]
Stupid question, how would I execute this?  I have a docker-compose setup using the official container, and I have weathermap disabled since 22.6.0, but when I run 22.7.0 or 22.8.0, the weathermap issue still pops up.  I want to disable via command line to proceed.

**Pull request merged**
