### PR TITLE
Documentation update for Oxidized integration.

### PR DESCRIPTION
**Pull request by jackson-tim**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by murrant** [comment]
trigger ci

**Comment by murrant** [comment]
Looks good. Thanks!

**Comment by murrant** [comment]
With nginx, it won't be the web server that is connecting, but php-fpm.  So, likely this won't be needed or a different permission would be needed.

**Comment by laf** [comment]
Awesome :)

I guess it's a good idea to cover in the apache one anyway as that's not the only thing we do http lookups for.

**Pull request merged**
