### PR TITLE
Fixed integers fields in alert rules to be string

### PR DESCRIPTION
**Pull request by TheGreatDoc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I'd really like to see the editor allow field selection by dropdown instead of this work-around.

I understand that isn't necessarily an easy task :)

**Comment by TheGreatDoc** [comment]
I know. I want to do field type by operator dropdown.

But! This is going to take way more time than what I did here and I think we need to fix it quick.

**Comment by murrant** [comment]
Yeah, can you add `//TODO implement field selection and change back to integer` comment on that line?

**Comment by TheGreatDoc** [comment]
Done. But... If field selection by operator is implemented, is this function neede anymore?

**Comment by murrant** [comment]
Yes, that would be done in javascript

**Pull request merged**
