### PR TITLE
Basic HP Blade Management Support

### PR DESCRIPTION
**Pull request by Rosiak**
#3631

### CODE REVIEW

**Comment by laf** [comment]
Is this definitely the best $os name?

**Comment by Rosiak** [comment]
Could just call it hp-blm?

**Comment by laf** [comment]
Upto you, just want to make sure it's the right one.

**Comment by Rosiak** [comment]
I could not find a definition when I did a search, however I was having second thoughts of just renaming it to hp-blm.

**Comment by laf** [comment]
Let's just go with that.

**Pull request merged**
