### PR TITLE
device: Added detection for Red Lion Sixnet devices

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #7879

### CODE REVIEW

**Comment by maladd3** [comment]
Do I need to add a MIB?

**Comment by laf** [comment]
If you have a mib and it contains useful info then yes.

**Comment by maladd3** [comment]
Here is what I found on their website. 
[SIXNET-MIB.txt](https://github.com/librenms/librenms/files/1920116/SIXNET-MIB.txt)

**Comment by laf** [comment]
Thanks @maladd3. Your snmpwalk doesn't contain any of this data though so you'll need to re-run the snmpbulkwalk command but replace the `.` with `.1.3.6.1.4.1.20540.2`

**Comment by maladd3** [comment]
@laf this is the output. 
https://p.libren.ms/view/3e33d829

Thank you.

**Comment by laf** [comment]
I've added those sensors now.

**Pull request merged**
