### PR TITLE
Update Ubuntu 16.04 nginx install doc with a better nginx config

### PR DESCRIPTION
**Pull request by ndum**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by f0o** [comment]
Although the API rule is not inherently wrong, we chose namer location for a reason. Our API is versioned and in due time we need to support /v0 /v1 etc. This is why we had a rewrite with named location instead of matching the actual directoryand try_files

**Comment by ndum** [comment]
Hi,

Please correct me, but is v0 actually not hardcoded also?

`rewrite api/v0(.*)$ /api_v0.php/$1 last;`

if u need v0 / v1 just add a second location? (as example)

```
location /api/v0 {
 try_files $uri $uri/ /api_v0.php?$query_string;
}

location /api/v1 {
 try_files $uri $uri/ /api_v1.php?$query_string;
}
```

This named location does not works in all situation, that is why i created this MR. In addition it's actually match both rules every time add this is bad for the performance.

**Comment by laf** [comment]
Does your change support /api/v0 though, it looks like it will pass v0 as a parameter to api_v0.php. Maybe just be explicit with the v0 in the rule?

**Comment by ndum** [comment]
> Does your change support /api/v0 though, it looks like it will pass v0 as a parameter to api_v0.php. Maybe just be explicit with the v0 in the rule?


Yes, if you send a request (example: xxx.xxx.org/api/v0/devices) the "devices" will be passed as a parameter. 

$query_string is just the last input parameter, so it will send "devices" to api_v0.php. 
example: api_v0.php?devices
`
Like i said before, if you want another API location (v1 / v2 or what ever), just add this as a new location.

**Comment by laf** [comment]
Imho I think you should change it to `location /api/v0 {` now so that it's clear.

**Comment by ndum** [comment]
I've changed it now to /api/v0

**Comment by laf** [comment]
Brilliant thanks.

Will fix when we work out what Travis changed :/

**Comment by ndum** [comment]
Perfect Thanks!

**Comment by laf** [comment]
This breaks access to /api-access/ for me.

**Comment by laf** [comment]
@ndum Please see my last comment.

**Comment by ndum** [comment]
Hi, 
I'm looking on it, 
On 2-3 installs at my environment it works fine.Also the  /api-access/
I will check this out.

**Comment by laf** [comment]
Sorry no I didn't see the change.

Works fine. Can you please update the CentOS install docs as well, should be the same changes but we need to ensure uniformed info.

**Comment by laf** [comment]
Oh and please rebase to fix the travis issue.

**Comment by ndum** [comment]
I have updated CentOS documentation now also.

Thanks ;)

**Comment by laf** [comment]
Thanks very much :)

**Pull request merged**
