### PR TITLE
Update services page

### PR DESCRIPTION
**Pull request by florianbeer**
- Bring services overview page in line with the rest of the interface
using bootstrap classes, panels, colors etc.
- Getting rid of most of the tables using bootstrap's grid classes.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Great work - could you change the size of the status box, it's a tad small:

image

**Comment by florianbeer** [comment]
Sure, I could make them the same as the status labels on the `/alerts/` page.

**Comment by florianbeer** [comment]
How's that?

screen shot 2017-02-18 at 18 25 02

I had to make the first column a bit wider, because some of the service names would have been cut off with the bigger font size.

**Comment by laf** [comment]
Looks good to me ( @librenms/reviewers )

**Pull request merged**
