### PR TITLE
Adding application for drone stats

### PR DESCRIPTION
**Pull request by MorrisJobke**
I wanted to write a little integration with Drone CI. There you can read out currently idling workers, running workers and the size of the queued jobs list. This will be reported by an SNMP extend command in following way:

```
33|0|0
```

I can submit the script for this later to the agents repository as well.

Also `snmpwalk` properly shows them:

```
$ snmpwalk -v 2c -c COMMUNITY HOST .1.3.6.1.4.1.8072.1.3.2.3.1
iso.3.6.1.4.1.8072.1.3.2.3.1.1.11.100.114.111.110.101.95.115.116.97.116.115 = STRING: "33|0|0"
iso.3.6.1.4.1.8072.1.3.2.3.1.2.11.100.114.111.110.101.95.115.116.97.116.115 = STRING: "33|0|0"
iso.3.6.1.4.1.8072.1.3.2.3.1.3.11.100.114.111.110.101.95.115.116.97.116.115 = INTEGER: 1
iso.3.6.1.4.1.8072.1.3.2.3.1.4.11.100.114.111.110.101.95.115.116.97.116.115 = INTEGER: 0
```

Any idea why LibreNMS does not show them in the UI? It is simply empty:

bildschirmfoto 2018-05-31 um 00 59 32

Sorry if this all looks totally wrong. I just wanted to have some custom graphs in the monitoring setup and thought that this is the way to handle it. Did I maybe messed up with the OID or did I forgot to register the data somewhere?

Thanks

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Sorry if this all looks totally wrong. I just wanted to have some custom graphs in the monitoring setup and thought that this is the way to handle it. Did I maybe messed up with the OID or did I forgot to register the data somewhere?

Disclaimer: I took #5496 as inspiration 🙈

**Comment by laf** [comment]
If you pastebin the output of `./poller.php -h HOSTNAME -d -m applications,unix-agent` we can see what's going on for data collection.

**Comment by MorrisJobke** [comment]
There you go:

<details>

<summary>poller.php output</summary>

```
LibreNMS Poller
===================================
Version info:
Commit SHA: e45aeff8713b39f2cf4a0998bcffb1e0abe5f1e9
Commit Date: 1527708890
DB Schema: 251
PHP: 7.2.5-0ubuntu0.18.04.1
MySQL: 10.1.29-MariaDB-6
RRDTool: 1.7.0
SNMP: NET-SNMP 5.7.3
==================================DEBUG!
Updating os_def.cache... Done
Starting polling run:

SQL[SELECT * FROM `devices` WHERE `disabled` = 0 AND `hostname` = 'HOSTNAME' ORDER BY `device_id` ASC] 
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '6'] 
Hostname: HOSTNAME
Device ID: 6
OS: linux (unix)

SQL[INSERT INTO `device_perf` (`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`)  VALUES ('3','3','0','0.01','0.02','0.01','6',NOW())] 
SNMP Check response code: 0
Modules status: Global+ OS  Device  
#### Load poller module core ####
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OQnUt -m SNMPv2-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:HOSTNAME:42003 sysUpTime.0 sysLocation.0 sysContact.0 sysName.0 sysObjectID.0 sysDescr.0]
.*.*.0 = 3420356
.*.*.0 = LOCATION
.*.*.0 = USER
.*.*.0 = drone
.*.*.0 = .*.4.1.8*
.*.*.0 = Linux drone 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64

SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -OQnUst -m HOST-RESOURCES-MIB:SNMP-FRAMEWORK-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:HOSTNAME:42003 snmpEngineTime.0 hrSystemUptime.0]
snmpEngineTime.0 = 34204
hrSystemUptime.0 = 15333413

Uptime seconds: 153334
RRD[update /opt/librenms/rrd/HOSTNAME/uptime.rrd N:153334]
Uptime: 1 day, 18h 35m 34s
SQL[SELECT `lat`,`lng` FROM `locations` WHERE `location`='LOCATION' LIMIT 1] 
Using cached lat/lng from other device

>> Runtime for poller module 'core': 0.0200 seconds with 34296 bytes
>> SNMP: [2/0.02s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module core ####

RRD[update /opt/librenms/rrd/HOSTNAME/poller-perf-core.rrd N:0.020041942596436]
Modules status: Global+ OS  Device  
#### Load poller module applications ####
SQL[SELECT * FROM `applications` WHERE `device_id`  = '6'] 
SNMP[/usr/bin/snmpget -v2c -c COMMUNITY -O qv -m NET-SNMP-EXTEND-MIB -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell udp:HOSTNAME:42003 .1.3.6.1.4.1.8072.1.3.2.3.1.2.11.100.114.111.110.101.95.115.116.97.116.115]
33|0|0

 drone-statsRRD[update /opt/librenms/rrd/HOSTNAME/app-drone-stats-3.rrd N:33:0:0]
SQL[UPDATE `applications` set `app_state` ='OK',`app_status` ='',`timestamp` =NOW() WHERE `app_id` = '3'] 
SQL[SELECT * FROM `application_metrics` WHERE app_id='3'] 
: ...


>> Runtime for poller module 'applications': 0.2671 seconds with 7336 bytes
>> SNMP: [1/0.24s] MySQL: [3/0.02s] RRD: [2/0.00s]
#### Unload poller module applications ####

RRD[update /opt/librenms/rrd/HOSTNAME/poller-perf-applications.rrd N:0.26712894439697]
Modules status: Global+ OS  Device  
#### Load poller module unix-agent ####
LibreNMS UNIX Agent: SQL[SELECT attrib_value FROM devices_attribs WHERE `device_id` = '6' AND `attrib_type` = 'override_Unixagent_port' ] 
Connection to UNIX agent failed on port 6556.

>> Runtime for poller module 'unix-agent': 0.0028 seconds with 9560 bytes
>> SNMP: [0/0.00s] MySQL: [1/0.00s] RRD: [1/0.00s]
#### Unload poller module unix-agent ####

RRD[create /opt/librenms/rrd/HOSTNAME/poller-perf-unix-agent.rrd --step 300 DS:poller:GAUGE:600:0:U  RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440 ]
RRD[update /opt/librenms/rrd/HOSTNAME/poller-perf-unix-agent.rrd N:0.0028328895568848]
### Start Device Groups ###
SQL[SELECT * FROM device_groups ORDER BY name] 
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='6'] 
Groups Added: 
Groups Removed: 
### End Device Groups ###
SQL[SELECT `graph` FROM `device_graphs` WHERE `device_id` = '6'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_icmp'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_icmp_info'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_ip'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_ip_frag'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_snmp'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_snmp_pkt'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_tcp'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'netstat_udp'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'hr_processes'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'hr_users'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_cpu'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_swap_io'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_io'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_contexts'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_interrupts'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_memory'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ucd_load'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystemstats_ipv4'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystemstats_ipv4_frag'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystemstats_ipv6'] 
SQL[DELETE FROM `device_graphs` WHERE `device_id` = '6' AND `graph` = 'ipsystemstats_ipv6_frag'] 
uptime 
RRD[update /opt/librenms/rrd/HOSTNAME/ping-perf.rrd N:0.01]
RRD[update /opt/librenms/rrd/HOSTNAME/poller-perf.rrd N:1.974]
Polled in 1.974 seconds
Updating HOSTNAME
SQL[UPDATE `devices` set `uptime` ='153334',`last_ping` =NOW(),`last_ping_timetaken` ='0.01',`last_polled` =NOW(),`last_polled_timetaken` ='1.974' WHERE `device_id` = '6'] 
UPDATED!
#### Start Alerts ####
SQL[SELECT `device_group_id` FROM `device_group_device` WHERE `device_id`='6'] 
SQL[SELECT alert_schedule.schedule_id FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '6' ) && ((alert_schedule.recurring = 0 AND (NOW() BETWEEN alert_schedule.start AND alert_schedule.end)) OR (alert_schedule.recurring = 1 AND (alert_schedule.start_recurring_dt <= date_format(NOW(), '--%d') AND (end_recurring_dt >= date_format(NOW(), '--%d') OR end_recurring_dt is NULL OR end_recurring_dt = '0000-00-00' OR end_recurring_dt = '')) AND (date_format(now(), '%H:%i:%s') BETWEEN `start_recurring_hr` AND end_recurring_hr) AND (recurring_day LIKE CONCAT('%',date_format(now(), ''),'%') OR recurring_day is null or recurring_day = ''))) LIMIT 1] 
SQL[SELECT DISTINCT a.* FROM alert_rules a  LEFT JOIN alert_device_map d ON a.id=d.rule_id  LEFT JOIN alert_group_map g ON a.id=g.rule_id  LEFT JOIN device_group_device dg ON g.group_id=dg.device_group_id  WHERE a.disabled = 0 AND ((d.device_id IS NULL AND g.group_id IS NULL) OR d.device_id='6' OR dg.device_id='6')] 
Rule #1 (Devices up/down): 
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '6') AND (devices.status = 0 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #2 (Device rebooted): 
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices WHERE (devices.device_id = '6') AND devices.uptime < 300 AND (devices.disabled = 0 && devices.ignore = 0) = 1] 
Status: NOCHG
Rule #3 (BGP Session down): 
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,bgpPeers WHERE (devices.device_id = '6' AND devices.device_id = bgpPeers.device_id) AND bgpPeers.bgpPeerState != "established" AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #4 (BGP Session established): 
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,bgpPeers WHERE (devices.device_id = '6' AND devices.device_id = bgpPeers.device_id) AND bgpPeers.bgpPeerFsmEstablishedTime < 300 AND bgpPeers.bgpPeerState = "established" AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #5 (Port status up/down): 
SQL[SELECT state FROM alerts WHERE rule_id = '5' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,ports WHERE (devices.device_id = '6' AND devices.device_id = ports.device_id) AND (ports.ifOperStatus = "down" && ports.ifAdminStatus != "down" && (ports.deleted = 0 && ports.ignore = 0 && ports.disabled = 0)) = 1] 
Status: NOCHG
Rule #6 (Port utilisation over threshold): 
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,ports WHERE (devices.device_id = '6' AND devices.device_id = ports.device_id) AND (((ports.ifInOctets_rate*8) / ports.ifSpeed)*100) >= 80 AND (ports.ifOperStatus = "up" && ports.ifAdminStatus = "up" && (ports.deleted = 0 && ports.ignore = 0 && ports.disabled = 0)) = 1] 
Status: NOCHG
Rule #7 (Sensor over limit - Check Device Health Settings): 
SQL[SELECT state FROM alerts WHERE rule_id = '7' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,sensors WHERE (devices.device_id = '6' AND devices.device_id = sensors.device_id) AND sensors.sensor_current > "sensors.sensor_limit" AND sensors.sensor_alert = 1 AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHGSQL[SELECT alert_log.id, alert_log.details FROM alert_log,alert_rules WHERE alert_log.rule_id = alert_rules.id && alert_log.device_id = '6' && alert_log.rule_id = '7' && alert_rules.disabled = 0 ORDER BY alert_log.id DESC LIMIT 1] 
SQL[UPDATE `alert_log` set `details` ='x??{k#7??ʲ?7^?}??QZr?	䒻????(?:G?VZ?p?
                                                                               ???????!?IƎg4#?F3?C?CXKaHmtX>?a??G?????aC符k` ??? -
                                                  ????F?ޛ?K?D?l?@/??h4??E???A???,@???/w???N?????qwa?wr{5?j?<sb?\r?s??RX???F??c??\\ɵZtF?-??F???S??\Z??2 ?1B	?F??:?tN?Z*?Y?+j?z<]?0M?]C׳?\\ք??1Z???[Z???`?(?r?L?}???8?h??{?k?9?>?S`?&?|2??*V?`<?|????????೥??8-?i?????\'A?p??U???
                                  \0??.?\n????\'??#?4?j?#XC?4???fkyWD5wD?-???	?tr?
   ???X??.??y?\\Rc?yO?????ΐ??0\r?:^
                                   ??D?>??fB?U???o????q9?,I???M??;#N??:?7???e??(ӢL?c??C??8??4GՐ??
                  \rG?b?	a?2?e?G???Vy?$?Ʈcb?a?œe??\\?:?:???c?ˀ?j?\'?0??5V????iEz>?{6?????[??E?XC+(???Q?!!ͦ/\\
                                   UЈ?f?M?ʆ?Δ\n-???Ӎ?????Q.?5??9t?@U_U??V[?&?x?~?\']?G8??~`?h???Ȗ??v??8ġ;??,4?X??m؜?_7#}k?ag?sg?Pm???t=?l?????r????????2??????D yf;m?^???j?gC~?m}?BcZ??9l?Cwk6+?h???s?qפj??fE=L?x?y?y?y?y???(F?Q?ˣx?@???g@??z? Byyyy?Ⴠ(?Q?7????????\0D?A@??(?
                             ?(+?Q\\?? ? ? ? z J?lD?? J^D?M???\r?(? ? ? ? z J?|D?? J?Os?\nDqV???4?A?A?A?jA?D?.???A?????޾e?ވ??????~?A?\'?0P??0q?~?5ӧ' WHERE id = '19'] 

Rule #8 (Sensor under limit - Check Device Health Settings): 
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,sensors WHERE (devices.device_id = '6' AND devices.device_id = sensors.device_id) AND sensors.sensor_current < "sensors.sensor_limit_low" AND sensors.sensor_alert = 1 AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #9 (Service up/down): 
SQL[SELECT state FROM alerts WHERE rule_id = '9' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,services WHERE (devices.device_id = '6' AND devices.device_id = services.device_id) AND services.service_status != 0 AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #10 (Wireless Sensor over limit): 
SQL[SELECT state FROM alerts WHERE rule_id = '10' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,wireless_sensors WHERE (devices.device_id = '6' AND devices.device_id = wireless_sensors.device_id) AND wireless_sensors.sensor_current >= "wireless_sensors.sensor_limit" AND wireless_sensors.sensor_alert = 1 AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #11 (Wireless Sensor under limit): 
SQL[SELECT state FROM alerts WHERE rule_id = '11' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,wireless_sensors WHERE (devices.device_id = '6' AND devices.device_id = wireless_sensors.device_id) AND wireless_sensors.sensor_current <= "wireless_sensors.sensor_limit_low" AND wireless_sensors.sensor_alert = 1 AND (devices.status = 1 && (devices.disabled = 0 && devices.ignore = 0)) = 1] 
Status: NOCHG
Rule #12 (State Sensor Critical): 
SQL[SELECT state FROM alerts WHERE rule_id = '12' && device_id = '6' ORDER BY id DESC LIMIT 1] 
SQL[SELECT * FROM devices,sensors,sensors_to_state_indexes,state_indexes,state_translations WHERE (devices.device_id = '6' AND devices.device_id = sensors.device_id AND sensors.sensor_id = sensors_to_state_indexes.sensor_id AND sensors_to_state_indexes.state_index_id = state_indexes.state_index_id AND state_indexes.state_index_id = state_translations.state_index_id) AND (sensors.sensor_current = state_translations.state_value && state_translations.state_generic_value = 2) = 1] 
Status: NOCHG
#### End Alerts ####
SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','HOSTNAME','1527752857.5382','2.133','1','monitoring')] 
poller.php HOSTNAME 2018-05-31 07:47:39 - 1 devices polled in 2.133 secs
SNMP [4/0.27s]: Get[4/0.27s] Getnext[0/0.00s] Walk[0/0.00s]
MySQL [67/0.79s]: Cell[3/0.00s] Row[15/0.00s] Rows[21/0.02s] Column[2/0.00s] Update[3/0.07s] Insert[2/0.19s] Delete[21/0.50s]
RRD [8/0.00s]: Update[7/0.00s] Create [1/0.00s] Other[0/0.00s]
```
</details>

**Comment by laf** [comment]
Ah all your files are `something.php`, the ones in html should be `something.inc.php`

**Comment by MorrisJobke** [comment]
> Ah all your files are something.php, the ones in html should be something.inc.php

I'm so sorry 🙈 Sorry to wasted your time on this one. 🙇

**Comment by MorrisJobke** [comment]
Works now without problems:

bildschirmfoto 2018-05-31 um 10 37 20


:+1:
 Should I submit the code for the snmp-agent to the other repo as well? Is this even wanted, because I just opened a PR and hoped, that it makes sense.

And the installation guide for the snmp-agent should also be in here, right?

**Comment by laf** [comment]
> Should I submit the code for the snmp-agent to the other repo as well? Is this even wanted, because I just opened a PR and hoped, that it makes sense.

Yes please.

> And the installation guide for the snmp-agent should also be in here, right?

Correct, need to add the docs to this one.

@VVelox is in the process of converting our applications to json so he might have some input on this.

You also need to sign the CLA @MorrisJobke

**Comment by VVelox** [comment]
Howdy!

I would highly suggest converting the backend over to JSON. Been working on getting all of ours converted. 

https://github.com/librenms/librenms/blob/master/includes/polling/functions.inc.php
https://github.com/librenms/librenms/blob/master/includes/polling/applications/fail2ban.inc.php

Those should provide a nice example of how to use it.

If you have any questions, please let me know. Still in the process of getting nice large doc together on it.

**Comment by laf** [comment]
@MorrisJobke Any update on this + the agent script?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Any update on this + the agent script?

Sorry - forgot this one. Let me send in the needed PRs.

**Comment by MorrisJobke** [comment]
I haven't lost track of this - was just busy with other stuff. It is still on my todo list, but a bit further down.

**Comment by laf** [comment]
@MorrisJobke I'm closing this for now, feel free to continue to push commits and comment back when it's ready for a review.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I'm closing this for now, feel free to continue to push commits and comment back when it's ready for a review.

Will do once I find some time.

**Pull request closed without merging**
