### PR TITLE
Improve dell-compellent detection for newer firmwares

### PR DESCRIPTION
**Pull request by saschareichert**
Dell changed the text for sysDescr after the 2017 firmware-release so that the string "COMPELLEN" which was looked after here before, did not appear anymore. The Compellent cuts off the snmp-answer after 255 characters.
I replaced the previous detection to a new snmpget-detection using the oid (DELL-STORAGE-SC-MIB::productIDDisplayName.0) that shouldnt be altered in the future.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by saschareichert** [comment]
[dell-compellent_scv3020.snmprec.TXT](https://github.com/librenms/librenms/files/6794376/dell-compellent_scv3020.snmprec.TXT)

**Comment by saschareichert** [comment]
pls help with the file.

**Comment by PipoCanaja** [comment]
@saschareichert Please commit the file at the right location (tests/snmpsim).

**Comment by PipoCanaja** [comment]
Hi @saschareichert 
I will compute the JSON file later and this will be good to go. 
Thanx

**Comment by PipoCanaja** [comment]
LGTM. Thanx @saschareichert

**Review by PipoCanaja — APPROVED** [review]

**Pull request merged**
