### PR TITLE
First Draft in Per-User default dashboards

### LINKED ISSUE #2216: Feature Request: Set default dashboard for new users
When creating a new shared dashboard, it would be great to be able to set this dashboard as default for new users, so the new user doesn't see the "placeholder-widget" in the dashboard.

I propose that this can either be a setting when editing the user, "set default dashboard" - dropdown and select available shared dashboards.
OR
When creating a shared dashboard, have a checkbox "make this dashboard default for new users"?

I'd prefer the first option because it gives flexibility to create different dashboards, and assigning them to users, i.e management-dashboard, servicedesk-dashboard, etc.

### PR DESCRIPTION
**Pull request by f0o**
Fixes #2216 #1916 

This is not final yet.
What hasn't been bothered with:
 - User can change his own defaults (Only admins can atm)
 - Dashboards permissions aren't revalidated

Help appreciated.

### CODE REVIEW

**Comment by laf** [comment]
So this allows an admin to set what the default dashboard is for a user?

Should the list of dashboards on edit show the current users, that's what I see on my test at the moment but I thought it should be the list of dashboards of the user being edited?

**Comment by f0o** [comment]
The dropdown shows a list of all dashboards the user has access to.
So own, shared(ro) and shared(rw).

**Comment by laf** [comment]
Ok so If I select someone else's shared dashboard then that user should have it as the default? I'm not sure that happened last night but let me test again.

**Comment by f0o** [comment]
Yeah it should unless I did a mistake

**Comment by awlx** [comment]
Hm, it does not seem to work for me. I as a user selected the shared one of another. But everytime I select "overview" it's gone.

**Comment by higante702** [comment]
Not trying to necro this thread, but I am in the same boat as @awlx - I set a dashboard and when we relog on or revisit the overview, it is set to "default"

**Comment by Rosiak** [comment]
Is this the place where you set it?
Cause that works for me.
screen shot 2016-04-29 at 23 43 25

**Comment by higante702** [comment]
image


I thought that it would disappear because we have LDAP auth setup.

**Pull request merged**
