### PR TITLE
Update Docu to fix #6301

### LINKED ISSUE #6301: Update install docs to cover mysql dropping GRANT ability to create users
We need to update to:
https://p.libren.ms/view/cc2a77fd

### PR DESCRIPTION
**Pull request by sorano**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Sorry about the spam, I realised I suck at git ;)

### CODE REVIEW

**Comment by sorano** [comment]
Final fix for #6301

**Comment by Gorian** [comment]
So... I see what you changed, but what is the reason for doing it the way you are proposing vs. the current method?

**Comment by sorano** [comment]
@Gorian I honestly dont know, I just figured that was what @laf wanted since he wrote https://github.com/librenms/librenms/issues/6301#issue-218026304

**Comment by laf** [comment]
I've just pushed a small fix.

And yes, it is because MySQL have deprecated creating users with the GRANT option.

**Comment by Gorian** [comment]
@laf awesome! I didn't know that, thanks for informing me :)

**Pull request merged**
