### PR TITLE
fix: Improve authentication load time and security

### PR DESCRIPTION
**Pull request by murrant**
page/graphs speedup part 2

**Write close the session as soon as we no longer need to write to it. Prevents the session from blocking other requests.**
Do not run through full authentication functions if the session is already authenticated.
Do not bind to AD every request when the session is already authenticated.
Extract login, logout, and remember_me functions.
Use Exceptions for authentication error handling.

Removes password from the session (See #4608)

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

fixes: #4127

### CODE REVIEW

**Comment by laf** [comment]
Still having graph issues with this and also getting kicked frequently.

One of the graph issues is that no width/height are set.

**Comment by murrant** [comment]
@laf OK, I think this is ready for testing.  I didn't find anything obviously wrong.

I also found out calling ldap_bind() on include in ad auth was a huge waste of time if we aren't going to even use it most of the time.

**Comment by rbax82** [comment]
Deployed on my setup. Wow what a difference in page load time.

**Comment by olivierbeytrison** [comment]
Currently in test on our setup with radius auth. There's a clear speed improvement!

**Comment by murrant** [comment]
Thanks for testing!

**Comment by laf** [comment]
lgtm

**Comment by laf** [comment]
@murrant Good for a merge from your perspective? If so, merge away

**Pull request merged**
