### PR TITLE
Add support for VOSS switches VSP-4900-12MXU-12XE, XA1440, and XA1480

### PR DESCRIPTION
**Pull request by ospfbgp**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ospfbgp** [comment]
No need to create Snmprec files because the mibs are the exact same mibs as other VSP models. Nothing new other than a different flavor of VOSS switch with different port configurations. LAB testing with modification have worked fine when polling. All memory, fans, power, cpu and ports look discovered properly.

**Comment by Jellyfrog** [comment]
If you could add one of them at least that would be nice

**Comment by ospfbgp** [comment]
Working on this now.  I am adding VOSS XA1440.

**Comment by ospfbgp** [comment]
This should GTG now... All checks passed 👍

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-68-release-changelog-september-2020/13525/1

**Pull request merged**
