### PR TITLE
remove calls to unavailable {{ $variable }} from YAML discovery

### PR DESCRIPTION
**Pull request by PipoCanaja**
As discussed in Discord, this PR removed unused variables from YAML Files instead of leaving them untouched.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Need to review all the test files now ...

**Comment by murrant** [comment]
Having second thoughts on this one.  Leaving the original code makes it more obvious that the data was not found.

Hopefully, only the developer sees unreplaced data.

Thoughts?

**Comment by PipoCanaja** [comment]
> Having second thoughts on this one. Leaving the original code makes it more obvious that the data was not found.
> 
> Hopefully, only the developer sees unreplaced data.
> Thoughts?

My issue is that sometimes, due to the fact that YAML does not allow conditions, you might want to display a variable if it is available, and nothing if it is not. In that case, it makes sense to have the "remove if not available" condition. 

Exemple : VRP, the OS of Huawei, is theoretically the same on all devices of the vendor (switches, routers, wireless Lan controllers). But they are in fact different flavours, and the SNMP implementation is very unstable between flavours. This current patch would allow to use 2 or 3 variables in one description, considering that only one is available for each flavours of VRP. 

That beeing said, I agree that we should display a warning in debug whenever a variable is not replaced, so that any person running ./discovery.php -v -d would see it (in case it is a mistake). I'll add that.

**Comment by murrant** [comment]
Sounds good to me.

**Pull request merged**
