### PR TITLE
Add case insensitive string helper functions.

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Not sold on the function names here, any better suggestions?

### CODE REVIEW

**Comment by laf** [comment]
Not easier to just pass a true / false to str_contains as a 3rd param?

**Comment by murrant** [comment]
laf, I thought about that but I thought it would be better to be more explicit.  That would fix the silly name issue...

**Comment by laf** [comment]
It would fix the silly name issue :)

**Comment by laf** [comment]
image

**Pull request merged**
