### PR TITLE
Add support fo PBN CPE device"

### LINKED ISSUE #1382: extend support for PBN CPE

### PR DESCRIPTION
**Pull request by vitalisator**
Fixes #1382

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR @vitalisator - would it be possible for you to add the discovery code as an elseif check so that we can ensure we are maintaining backwards compatibility please?

**Comment by vitalisator** [comment]
@laf, we do not need a elseif here.
the discovery based on snmp is much precise to all pbn devices, because all pbn devices have the
 ojectID begins with .1.3.6.1.4.1.11606 but not all have a previous used String in sysDescr.

it is tested by me for backward compatibility and it works fine.

**Comment by Rosiak** [comment]
@laf That was my initial thought too, untill i saaw that @vitalisator was the one who added the support for the PBN initially.

**Comment by laf** [comment]
Sounds good then :)

**Pull request merged**
