### PR TITLE
Changed default disk utilization warning threshold to 95% from 60%

### PR DESCRIPTION
**Pull request by admiralspark**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

----

Hello, 

The default storage alarm threshold is 60%. This is ridiculously low for any sort of servers, and though it can be adjusted on a per-server basis it creates unneeded extra work to manually change it each time. On top of that, validation checks fail if the value is manually changed by the end user. 

This is to open discussion on the subject, and if 95% is considered a good cutoff point then no further work is needed.

### CODE REVIEW

**Comment by laf** [comment]
This just changes the hard coded limit when we should be offering a user configurable value that overwrites the 60 when inserting the data into the table.

Is this something you want to tackle?

**Comment by murrant** [comment]
This would mean updating the function discover_storage() to set storage_perc_warn.

**Comment by admiralspark** [comment]
@laf @murrant Python is my strong suit, so I can take a look but it'll take a bit. 

Do you think it should be set at initial setup? Or have it be a General Setting option? How do you want to handle mariadb validation using the validate script after, just check that the value exists or verify it matches the set value? 

I'm willing to do the work, but not sure what the best end result would be. I think a user configurable option post-installation seems good, and I can update discover_storage() as he said.

**Comment by laf** [comment]
So you can add a webui config option but it does need a new section setting up for this so it's probably better to leave it for now unless you want to try that as well? I can do that part for you.

The main part is to update `discover_storage()` and add `storage_perc_warn` to the insert using `Config::get('discovery.storage.perc_warn')` - Made that up but it seems a logical config name.

@murrant what do you think?

**Comment by murrant** [comment]
Seems good to me, but perhaps we should add default to the name to indicate that changing it's value won't update existing records.

**Comment by admiralspark** [comment]
Hmm. @laf @murrant I can kill this PR and start a new one with a modified discover_storage() function. I like the idea of using discovery.storage.perc_warn_default in the config for it instead of modifying the base 60% warning.

**Pull request closed without merging**
