### PR TITLE
Force explicit full path to mib files.

### PR DESCRIPTION
**Pull request by mjsteckel**
snmpget and snmpwalk where not finding some mibs even though a) they were in the mibs directory and b) all perms were correct.

This patch provides the full path to each mib to be specified (-m) on the snmp[get|walk| cmd line, which takes precedence over the (-M) mib search path.

### CODE REVIEW

**Comment by murrant** [comment]
It looks like you have effectively deleted the AirFiber MIBs, be replacing the contents with the generic UBNT-MIB.

Is that intended?

**Comment by mjsteckel** [comment]
murrant: The only mib updated/changed (or should be) is UBNT-AirFIBER-MIB. The two other UBNT mibs files are (or are supposed to be) unchanged.

Are you seeing something different?

**Comment by laf** [comment]
Yeah I only see updates to the AirFibre mib.

Will take more of a look later tonight.

**Comment by murrant** [comment]
Look at the name of the mib inside the file it is now `UBNT-MIB`, it used to be `UBNT-AirFIBER-MIB`.

I think UBNT has merged their mibs into the same file.  So we will need to adjust the code to adapt if we want to use this new mib.

**Comment by laf** [comment]
Ah, good spot :)

**Comment by murrant** [comment]
Please correct usage of MIB, rather than forcing it to use a different MIB definition, thanks.

**Pull request closed without merging**
