### PR TITLE
Various variables will all be updated if they are blank #5811

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #5811

### CODE REVIEW

**Comment by murrant** [comment]
My only concern is if one of these variables is null or something and the database returns ''.  Causing it to b e updated every poll.

I'll try to test this, but my testing bandwidth has been pretty low of late :(

**Comment by laf** [comment]
```
-bash-4.2$ cat /tmp/n.php
<?php

$t = null;
$s = '';

if ($t != $s) {
    echo 'notequals';
} else {
    echo 'equals';
}
-bash-4.2$ php /tmp/n.php
equals
```

Should be ok

**Comment by murrant** [comment]
Ah yes, you aren't using strict comparison.

**Comment by laf** [comment]
Yeah I only use strict when I know or trust the data

**Pull request merged**
