### PR TITLE
availability map updates

### LINKED ISSUE #4154: Availability Map blanks the screen on empty services selection
Hi,

First of all I would like to mention that the new availability-map is a cool feature, well done:). 
The issue I am experiencing though is that when I select services in its pull-down menu; in my case I do not have any service configured yet, then I just get blank white screen. Even the pull down dissappears meaning I cannot revert back. The only way to get back to the availability map for devices is to logout and login again. The issue affects the dashboard as well when it occurs. See below;

snap35

snap34

snap36

snap37

### PR DESCRIPTION
**Pull request by crcro**
fixes for:
- services visibility if no service available (issue Fixes #4154)
- services not enabled in config (issue Fixes #4154)
- widget view vs full page

### CODE REVIEW

**Comment by crcro** [comment]
added the possibility to switch to the old view (which gives more space to overview) by adding in config.php:

$config['availability-map-newview'] = 0;

**Comment by laf** [comment]
Will comment later but travis has some issues which need to be addressed as well.

**Comment by laf** [comment]
Variable names should follow the traditional method of something_something rather than something-something.

You may as well add the config option to /settings/sub=webui/ in a new category of 'Visual display', adding these values is quite easy.

Here's an example: https://github.com/librenms/librenms/commit/4581366bf487f7d5cce79e819f9d6d9525ae6c71

**Comment by crcro** [comment]
- added settings to /settings/sub=webui/
- fixed travis errors

**Pull request merged**
