### PR TITLE
Update avaya-vsp.yaml

### PR DESCRIPTION
**Pull request by ospfbgp**
Extreme purchased the Avaya networking assets and so I need to rebrand the VSP to be Extreme.  I am changing the icon to be Extreme.  I am also adding support for the 8404c which is  sysObjectID .1.3.6.1.4.1.2272.220

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Looks good can you add test data for .1.3.6.1.4.1.2272.220?

If you don't want to install snmpsim, you can just run this and add the snmprec to this PR.
`./scripts/collect-snmp-data.php -h HOSTNAME`

https://docs.librenms.org/#Developing/os/Test-Units/#example-workflow

**Comment by ospfbgp** [comment]
Hope this is what I need to submit. :-)

[avaya-vsp.snmprec.txt](https://github.com/librenms/librenms/files/1812236/avaya-vsp.snmprec.txt)
librenms@gtb-dashboard:~$ ./scripts/collect-snmp-data.php -h 192.168.0.6
OS: avaya-vsp
Module(s): all

Capturing Data:  sysDescr.0 sysObjectID.0 sysName.0 SNMPv2-MIB::sysDescr.0 SNMPv2-MIB::sysObjectID.0 ifDescr ifName ifAlias ifType entPhysicalEntry entAliasMappingIdentifier rcKhiSlotCpu5MinAve .1.3.6.1.4.1.2272.1.85.10.1.1.8.1 hpLocal hpGlobal hrStorageEntry entPhysicalDescr entPhysicalName entPhySensorType entPhySensorScale entPhySensorPrecision entPhySensorValue .1.3.6.1.4.1.2272.1.4.7.1.1.2 .1.3.6.1.4.1.2272.1.4.8.1.1.2 rcChasFanAmbientTemperature rcSingleCpSystemCpuTemperature.0 rcSingleCpSystemMacTemperature.0 rcSingleCpSystemPhy1Temperature.0 rcSingleCpSystemPhy2Temperature.0 rcSingleCpSystemMac2Temperature.0 ipNetToPhysicalPhysAddress ipNetToMediaPhysAddress dot1dBasePortIfIndex dot1qVlanVersionNumber.0 dot1qVlanStaticName dot1qVlanCurrentEgressPorts dot1qVlanCurrentUntaggedPorts dot1qTpFdbPort sysUpTime.0 sysLocation.0 sysContact.0 snmpEngineTime.0 hrSystemUptime.0 rcSysVersion.0 rcChasSerialNumber.0 .1.3.6.1.4.1.2272.1.4.7.1.1.2.1 .1.3.6.1.4.1.2272.1.4.7.1.1.2.2 .1.3.6.1.4.1.2272.1.4.7.1.1.2.3 .1.3.6.1.4.1.2272.1.4.7.1.1.2.4 .1.3.6.1.4.1.2272.1.4.8.1.1.2.1 .1.3.6.1.4.1.2272.1.4.8.1.1.2.2 .1.3.6.1.4.1.2272.1.212.1.0 .1.3.6.1.4.1.2272.1.212.2.0 .1.3.6.1.4.1.2272.1.212.3.0 .1.3.6.1.4.1.2272.1.212.4.0 .1.3.6.1.4.1.2272.1.85.10.1.1.3.1 1.3.6.1.4.1.2272.1.85.10.1.1.6.1 1.3.6.1.4.1.2272.1.85.10.1.1.7.1 1.3.6.1.4.1.2272.1.85.10.1.1.8.1 IP-MIB::ipForwDatagrams.0 IP-MIB::ipInDelivers.0 IP-MIB::ipInReceives.0 IP-MIB::ipOutRequests.0 IP-MIB::ipInDiscards.0 IP-MIB::ipOutDiscards.0 IP-MIB::ipOutNoRoutes.0 IP-MIB::ipReasmReqds.0 IP-MIB::ipReasmOKs.0 IP-MIB::ipReasmFails.0 IP-MIB::ipFragOKs.0 IP-MIB::ipFragFails.0 IP-MIB::ipFragCreates.0 IP-MIB::ipInUnknownProtos.0 IP-MIB::ipInHdrErrors.0 IP-MIB::ipInAddrErrors.0 TCP-MIB::tcpActiveOpens.0 TCP-MIB::tcpPassiveOpens.0 TCP-MIB::tcpAttemptFails.0 TCP-MIB::tcpEstabResets.0 TCP-MIB::tcpCurrEstab.0 TCP-MIB::tcpInSegs.0 TCP-MIB::tcpOutSegs.0 TCP-MIB::tcpRetransSegs.0 TCP-MIB::tcpInErrs.0 TCP-MIB::tcpOutRsts.0 tcpHCInSegs.0 tcpHCOutSegs.0 UDP-MIB::udpInDatagrams.0 UDP-MIB::udpOutDatagrams.0 UDP-MIB::udpInErrors.0 UDP-MIB::udpNoPorts.0 icmp snmp IP-FORWARD-MIB::ipCidrRouteNumber.0 ipSystemStats ifXEntry ifAdminStatus ifOperStatus ifLastChange ifPhysAddress ifMtu ifInErrors ifOutErrors ifInDiscards ifOutDiscards dot3StatsDuplexStatus dot1qPvid

Updated snmprec data /opt/librenms/tests/snmpsim/avaya-vsp.snmprec

Verify this file does not contain any private data before submitting!

**Comment by laf** [comment]
Looks good. Just check if nothing is sensitive in it and add the file to this PR.

**Comment by laf** [comment]
I forgot the json file, added now.

**Comment by ospfbgp** [comment]
Laf am I all complete here?  I noticed Merging is blocked.  A little confused.  Sorry

**Comment by ospfbgp** [comment]
Laf just want to see if I can get this closed.  If I need to do something else let me know.

**Pull request merged**
