### PR TITLE
Added support for Brocade 200E

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
You need to also add the extra test call into tests/OSDiscoveryTest.php

**Comment by laf** [comment]
Also, whilst you are at it, can you change your github name in AUTHORS.md to aldemira rather than aldemir_a.

It's also worth to mention that you should avoid working in your master branch. We have docs to help you with that :)

**Comment by laf** [comment]
Sorry my head isn't with it :(

Can you add sysDescr to the test unit file, it's not used for discovery but helps with the whole unit testing piece in general.

**Comment by aldemira** [comment]
I would, but sysDescr string says "Fibre Channel Switch."
I think it's a bit too generic, don't you think so?

**Comment by laf** [comment]
Not really, yes it is generic but if someone adds a new device which only matches on Fibre Channel sysDescr and it runs before this one then it will break detection. The more test data we have the better :)

**Pull request merged**
