### PR TITLE
device: "DEVELOP" Support

### PR DESCRIPTION
**Pull request by jasoncheng7115**
DO NOT DELETE THIS TEXT

**Please note**

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
 

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

**Testers**

If you would like to test this pull request then please run:` ./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by kkrumm1** [comment]
@jasoncheng7115 why did you delete everything below "DO NOT DELETE THIS TEXT" ?

**Comment by jasoncheng7115** [comment]
Hooo...... Sorry, it's my mistake, i have fixed it.

**Comment by murrant** [comment]
@jasoncheng7115 your indentation is off, please fix that (tabs instead of spaces maybe?)

**Comment by jasoncheng7115** [comment]
@murrant thank your tip, i fixed it. :-)

**Comment by laf** [comment]
Thanks for submitting this @jasoncheng7115 

We will need test data as well so that we can ensure this change doesn't become broken in the future.

**Comment by murrant** [comment]
https://docs.librenms.org/Developing/os/Test-Units/#example-workflow

**Comment by laf** [comment]
@jasoncheng7115 Any update on this one?

**Comment by jasoncheng7115** [comment]
Hello!

Thanks for the tips, 
run "collect-snmp-data.php", "save-test-data.php" is ok.

`
# ./scripts/collect-snmp-data.php -h 9 -m os
OS: konica
Module(s): os

Capturing Data:  sysDescr.0 sysObjectID.0 sysName.0 SNMPv2-MIB::sysDescr.0 SNMPv2-MIB::sysObjectID.0 .1.3.6.1.4.1.12148.10.2.6.0 sysUpTime.0 sysLocation.0 sysContact.0 snmpEngineTime.0 hrSystemUptime.0 1.3.6.1.4.1.18334.1.1.1.1.6.2.1.0 1.3.6.1.4.1.18334.1.1.1.1.6.1.0

Updated snmprec data /opt/librenms/tests/snmpsim/konica.snmprec

Verify this file does not contain any private data before submitting!

# cat  /opt/librenms/tests/snmpsim/konica.snmprec
1.3.6.1.2.1.1.1.0|4|KONICA MINOLTA bizhub C3110
1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.18334.1.1.1.2.1.117.2.2
1.3.6.1.2.1.1.3.0|67|173664643
1.3.6.1.2.1.1.4.0|4|<private>
1.3.6.1.2.1.1.5.0|4|<private>
1.3.6.1.2.1.1.6.0|4|<private>
1.3.6.1.2.1.25.1.1.0|67|173664647
1.3.6.1.4.1.18334.1.1.1.1.6.1.0|4|1.80
1.3.6.1.4.1.18334.1.1.1.1.6.2.1.0|4|Develop ineo+ 280
`

**Comment by jasoncheng7115** [comment]
But I run "pre-commit.php"This question appears, how can I solve

./scripts/pre-commit.php --db --snmpsim
Running unit tests... Timeout: No Response from udp:127.1.6.2:1161.

I try to modify the file ip = 127.0.0.1, get same output:

./scripts/pre-commit.php --db --snmpsim
Running unit tests... Timeout: No Response from udp:127.0.0.1:1161.

**Comment by laf** [comment]
Don't worry about the pre-commit. Just run `./scripts/save-test-data.php -o konica -m os` add the new files to this pr and we should be good.

**Comment by jasoncheng7115** [comment]
I run   `./scripts/save-test-data.php -o konica -m os`  ,   The results:

> #root@mon:/opt/librenms# ./scripts/save-test-data.php -o konica -m os
>Starting snmpsim listening on 127.1.6.1:1161...
>OS: konica
>Module: os
>
>konica: Could not connect to 127.1.6.1, please check the snmp details and snmp reachability

hoo..

**Comment by laf** [comment]
Sorry for the delay. Please run `./scripts/collect-snmp-data.php -h $HOSTNAME` instead and upload the file to this PR that it produces, we'll take a look after that.

**Comment by jasoncheng7115** [comment]
Thanks for your help. I have uploaded my file here. 
Yeah!

[konica.zip](https://github.com/librenms/librenms/files/1809242/konica.zip)

**Pull request merged**
