### PR TITLE
Added Meraki CS device detection

### PR DESCRIPTION
**Pull request by laf**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
What is the difference between these and Catalyst 9300 switches?  Are they still running IOS-XE?

**Comment by murrant** [comment]
A little research shows it is Meraki on top of IOS-XE.  So, yes this should be "meraki", but it seems like it is exactly the same as merakims.  So, it should be that OS.  (And marketing/branding names biting us in the ass again)

https://community.meraki.com/t5/Switching/MS390-vs-Catalyst-9300-M/m-p/217001

**Comment by laf** [comment]
> A little research shows it is Meraki on top of IOS-XE. So, yes this should be "meraki", but it seems like it is exactly the same as merakims. So, it should be that OS. (And marketing/branding names biting us in the ass again)
> 
> https://community.meraki.com/t5/Switching/MS390-vs-Catalyst-9300-M/m-p/217001

From my research the firmware is known as Meraki MCS :)

https://documentation.meraki.com/Firmware_Features/MS_Firmware_Features_Directory

Happy to merge it into the merakia-ms if that's what we want but it's indicated that ms and cs are different from the vendor.

**Comment by murrant** [comment]
Hmm, according to [this](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/SNMP_Overview_and_Configuration) ALL meraki devices only support standard MIBs + MERAKI-CLOUD-CONTROLLER-MIB

**Comment by laf** [comment]
> Hmm, according to [this](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/SNMP_Overview_and_Configuration) ALL (MX,MS,CS) meraki devices only support standard MIBs + MERAKI-CLOUD-CONTROLLER-MIB

I've updated the PR to use Meraki MS now.

**Comment by murrant** [comment]
Ok, we may have to rename merakims to meraki in the future.

**Review by murrant — APPROVED** [review]

**Pull request merged**
