### PR TITLE
New overview page and new map

### PR DESCRIPTION
**Pull request by laf**
1. This will now perform lookups of sysLocation to work out coords (disabled by default whilst people test). Lookups are limited by checking if a device with the same sysLocation has done a lookup within the last 24 hours and use that.
2. lat / lng coords then stored in the DB.
3. Map is then available by setting the new frontpage to be map.php. Varying options supported to get a map of the area you want. See docs for details.

Would be great for people to test this functionality.

Things to do:

1. Allow users to override the lat/lng coords in web ui.
2. Add a central DB where we can store some common address to lat/lng lookups (maybe data centres, IX's, etc).
3. + more depending on feedback.

We will be able to add more geocoding services quite easily.
We will be able to add more map vendors quite easily.

### CODE REVIEW

**Comment by laf** [comment]
If people want to test this, please ensure you have a clean install and then please ensure you understand git before undertaking this. It's not currently rebased to master so is a few versions old so you may want to create a new branch yourself then merge mine in to test.

**Comment by f0o** [comment]
I'm going to alter the config of the build, keep in mind if you cause a rebuild by commit or via comment, it will overwrite the altered config.

Ping me on IRC to add the map-config again after rebuild.

**Comment by laf** [comment]
Thanks @f0o :)

**Comment by f0o** [comment]
Updated - http://1394.ci.librenms.org or https://1394.ci.librenms.org

**Comment by f0o** [comment]
Updated - http://1394.ci.librenms.org or https://1394.ci.librenms.org

**Comment by travishegner** [comment]
@laf, this looks awesome! @clinta and I were discussing doing something very similar.

**Comment by travishegner** [comment]
@laf, one thing that stands out is that the 24 hour cache seems a bit short for data that is practically static. I can understand why you went with that given that the lat/lng are stored inside of each device record. If the location for a device changes, you don't want the old coordinates to be stuck with it for too long.

IMHO, it wouldn't take too much refactoring to store in a separate table a location<-->coordinate mapping that could really be cached practically indefinitely as addresses almost never change coordinates.

When it comes time to generate the map data, alter the select statement to use an inner join on the 'location' field from the device, with the 'location' field on the new mapping table. You'd only really have to change the query where the coordinates get stored, and adjust the query that reads them back out.

What do you think?

**Comment by laf** [comment]
It's more about looking up the data in the first place I supposed.

Doing it in a table is fine except we still need to do the initial lookup for each address (which is all we do now anyway as we then use the results for devices with the same address). So as an example, if you have 100 devices with the same address, we do the lookup once then for 99 other devices use the coords from the first device.

We need the 24 hour thing in as you can override the sysLocation in the WebUI which wouldn't trigger  an update of the coords. It can be changed from 24 hours to be longer or user configurable?

If I'm missing what you mean just let me know :)

**Comment by Rosiak** [comment]
A few ideas

- Could be nice to have the alertlog/eventlog seperation from the overview page today.
- Perhaps the alert notifications could be kept, either with a lookup in the DB(Is there any active alerts? If so then display the notifications, otherwise hide the notification area). But not sure about this.

midgar31 also posted some ideas on IRC:
- Possibility to adjust the map size(just through config.php options as a start)
- Possibility to open the map in a separate window(For some kind of NOC view)

**Comment by laf** [comment]
@Rosiak 

So remove the alertlog / eventlog? I'm guessing this is personal preference and where we'd want the dynamic dashboard to come into play.

Size adjustment is already in, you set the width (see docs in this PR)

I can do that, have it as a menu option as well so regardless of the dashboard you use you can still have this available.

**Comment by Rosiak** [comment]
@laf 
In the test i saw that only the eventlog was visible on the new page, i would prefer both the alertlog and the eventlog being visible. Like the overview page today.

Perfect!

**Comment by travishegner** [comment]
@laf, I agree with what you are saying, and that is definitely better than doing a lookup many times for the same address.

What I'm trying to explain is that having a simple permanent cache table would allow you to only lookup any given address once for the lifetime of the installation, as opposed to once per day. If a device's location was changed to one already in the lookup table, the change would be instant, and another lookup wouldn't even be required. If not, it could trigger a geo service lookup and cache it in the permanent table itself for any future devices that may be in the same location.

Am I making sense? I feel like I'm struggling to explain it well.

**Comment by laf** [comment]
@Rosiak Yeah that can be done. Got an idea how to make it a little bit more extendable.

@travishegner Totally understand, kind of said we would do that kind of thing with @f0o. We will be populating a list of common addresses so can easily add that support as well.

**Comment by paulgear** [comment]
One question: is a table in the LibreNMS database the right place for geocaching information?  To me it seems like this is something worth outsourcing to a separate service.

**Comment by clinta** [comment]
@paulgear, any specific service in mind? Right now I'd say google maps is a separate service and it proves very slow and inefficient. The advantages of the MySQL database include: the code is aready there, it's easy to interface with, getting location and devices can be done in one query quickly and efficiently.

**Comment by travishegner** [comment]
@paulgear, besides what @clinta mentioned, it should also be noted that the separate service is still the authority for the information. The information changes very rarely, so it is a prime target for any form of caching. In my experience, the google maps and charts are *much* more responsive with raw geographical coordinates, than with addresses that have to be converted.

Also, many third party services impose restrictions on the number of queries per day that can be executed from a given IP or account. The code could also be written to serve data from a *stale* cache in the even that the separate service is down (very rare in this day and age, but it wasn't only 5 years ago).

Besides all of that, it also builds the foundation for being able to switch the map to an interactive or zoom-able map, rather than the static map that exists today. It would be possible to zoom in on the map and issue a bounding box query, and only select the devices/locations that would be visible in the map to be displayed. Many modern databases are equipped with some pretty good geospatial  functions.

**Comment by paulgear** [comment]
@clinta, @travishegner: When I say "outsourcing to a separate service", I don't mean that it shouldn't be part of LibreNMS, I mean that the implementation should be as decoupled and self-contained as possible.  e.g. Given the problem we're having in issue #1345, the more optional features we include in the devices table, the more likely it is to happen.

If we implement it as a separate entity (i.e. not tied to the devices table), we isolate the rest of the code from any changes in data types used by the geocaching provider.  Google are well known for changing and dropping APIs that they don't like, and we don't want to have to update the devices table if this happens.

All this means in practical terms is that I think we should use a function which takes an address and returns coordinates, and that function should cache as it sees fit, in whatever manner seems appropriate, including having its own geocaching table in the database, if necessary.

P.S. @laf, it seems like $api_url is ignored, and every device lives at the same address in Manchester.

**Comment by paulgear** [comment]
P.S. the curl stuff should probably use the same proxy as the stats submitter.

**Comment by travishegner** [comment]
@paulgear, understood and agreed. That would be partially satisfied with the suggestion I made earlier about the separate mapping table.

**Comment by laf** [comment]
Ok, this is now rebased.

$api_url is being used again and proxy for curl is used.

Also pushed an update to sql file to lock tables before hand.

Ok, so now as far as caching / db layer. When people make their minds up on what / how it should be done, let me know and I'll do it.

My take is:

lat/lng belong in the device table (devices_perms is a pain from a query point of view), a separate table to JUST store the lat / lng relationship to the device is overkill and makes no sense.

I'm all up for having  table that stores previously looked up lat / lng values as previously mentioned, they don't chnage often. As it standards at the moment - the additional method used shouldn't do too many lookups - if it does, it means each device has a unique address so at the point looking up in the db table would save on external queries.

**Comment by clinta** [comment]
@laf, not sure if we're on the same page. I wasn't suggesting a separate table to store the relationship between devices and lat, lng. To clarify, a location table shouldn't store device ID's at all. A location table should be used to store the relationship between a location string and a lat, lng, with the location string as the index. Then querying a device and it's lat, lng requires a simple inner join, but the coordinates for each location only need to be stored once and should never need to be changed. And there is never a chance of a device having an updated location string for a device with stale coordinates, which there is when storing all that data in the device table.

**Comment by paulgear** [comment]
trigger ci

**Comment by laf** [comment]
@clinta That makes sense and I'm happy to switch to that.

**Comment by spinza** [comment]
The override lat/long will be useful as I know the co-ordinates of my devices but not their addresses.

**Comment by travishegner** [comment]
@clinta did a much better job explaining it than I did for some reason.

@laf, @spinza, it'd be a complex query, but you can technically keep a set of lat/lng columns in the device table along with the mapping table, and then use a "case...when" in the select to grab the mapping table coordinates only if the device table's coordinates are null. That's the easiest way that I can think of to allow a device override in a single query anyway.

**Comment by clinta** [comment]
@spinza, do you need to override for a single device, or just for a location string (which may not be an address). For example, you don't know the address of "building 3", but if you can associate the snmp location "building 3" with a set of coordinates, would that be sufficient?

**Comment by spinza** [comment]
Sorry I wasn't clear.  I know the lat/long of most of my devices through other means.  I don't know the locations/addresses and the SNMP/syslocation is outside of my control and poor quality data.  I'd like to be able to use this map and it not attempt to geocode my syslocations.  I can update the device table locations via backend query.
I guess that can be done by turning geocoding off but using the map view in any case? Is something of this sort possible by the way it's been implemented here.

**Comment by clinta** [comment]
I think that can be done without the complication of lat/long in the device table. You can override the snmp syslocation per device to any arbitrary string you want, that's already exposed in the GUI. We just need another page to manually adjust the mapping of location strings to lat/long.

**Comment by spinza** [comment]
I think a per device lat/long makes sense.  You could still use a location->lat/long mapping table if needed to derive those lat/longs and cache the lookups.  
My locations look like this: `21.934344,16.404395`
Heck, with device lat/long you could even do reverse lookups to automate the Locations menu for country/province/city type menu structure.

**Comment by travishegner** [comment]
@spinza, there is also nothing in the mapping table enforcing any structure to the "location" string. Assuming your SNMP locations at least don't overlap, you could put the bad *locations* into the mapping table, and the inner join will still return the right coordinates.

Building on @clinta's comment, it would be an easy query ("update devices set location=device_name" or something like that) to copy the device name into the "sysLocation" overridden field, and then manually populate the mapping table with <device_name>, <lat>, <lng> columns. You could do that as often as you needed to in a custom cron job or something. It sounds like you are populating some of that data manually already anyway.

Regardless the possible solutions for your given scenario, the project should move forward with what makes sense for the majority of it's user base, while still leaving it open enough to do a custom solution if necessary, albeit without a bunch of hacks.

**Comment by spinza** [comment]
@travishegner thanks I'm sure I'll find a way to work it either way.  Was just thinking in terms of usefulness. 
One of the possibilities of doing it with a location /mapping table is that we can add some detail down the line:
If we add a location table then we could do a hierarchical fields?  E.g. country/province/city/suburb or whatever?  These could then populate sub-menu's under Devices/Locations/Country/etc.  This could also be something else like company regions, site names/ building names etc.
So location table could be have headers: syslocation, level 1, level 2, level 3, lat, long.

**Comment by laf** [comment]
I'm not sure if anyone has taken a look at how the location / override is done but I don't think (assuming I understand what is being said) this is a case of a simple inner join.

So location in the devices table is pulled from snmp. If you overwrite this then two new entries are stored in devices_attribs so to get just the devices location means you have to do a join with devices_attribs, check that override_sysLocation_bool = 1 meaning the user has specified to overwrite the location. Then, when you have the location either from the devices table or devices_attribs you then need to look up the lat/lng from a coordinates table using the single location we have found but again by joining devices_attribs as we now need to check if the user has overwrote the coordinates to a custom value. This may be possible with a single query but is looking unlikely + add in the complication of user perms that also then need to be checked.

I feel like I'm trying to shoe horn something into here which is made extremely difficult by adams choice in using functions to perform restrictions which should be done in mysql queries.

If anyone wants to help come up with the schema / queries for this (or take over the PR) please jump on irc. I'll make it work but it may not be optimal or what people are expecting.

**Comment by travishegner** [comment]
@spinza, that seems possible and almost opens the issue up to a sense of perhaps there should be a "locations" table that stores all of the given attributes of defined locations.

@laf, obviously you know more about the inner workings of the project, as well as it's current user base, therefore you know better how difficult this stuff may be to actually implement.

At the risk of scope creep, do you think defining locations outright in their own table with the ability to manage/override them from the front end is a way to accomplish even more, given the concerns of your last comment? The location table could be somewhat auto populated based on the SNMP/syslocation (I love the way that happens currently, BTW), but then those locations could be further manageable through a front end. A foreign key from devices to location would be all you need to map them, and the override logic for location fields would be based on that table rather than the device itself... or instead of any overrides, you just define a new location with whatever attributes you need for it, and map the given device to it.

It seems that the more we try to add and do with "locations" the more sense it makes to define them as their own object, rather than as attributes of a device. I can envision a user who's entire equipment list is in one building, and a "location" is defined as "server room", or "third floor wiring closet". I don't know how difficult it would be to consider that as part of this PR, or if it makes more sense as a feature request. I also don't know if it will help with the security/permissions issues you described.

**Comment by clinta** [comment]
That devices_attribs table is certainly a bear to work around. Ideally a future effort should invovle recreating that as a proper table indexed by device ID.

However, in the interum, here is a query which will retrieve the location, either as the override location if overrie_sysLocation_bool = 1 or as just the device location if not.

```SQL
set @dev_id=216;

SELECT
  device_id, 
  IF(
     ( SELECT attrib_value FROM devices_attribs
       WHERE device_id = @dev_id
       AND attrib_type = "override_sysLocation_bool" ) = 1,
      ( SELECT attrib_value FROM devices_attribs
        WHERE device_id = @dev_id
        AND attrib_type = "override_sysLocation_string" ),
      devices.location) AS location
FROM
  devices
WHERE
  device_id = @dev_id;
```

In this query, location could be joined to a location table.

**Comment by clinta** [comment]
This is totally untested, so I'm not opening a PR yet, but I have some preliminary progress on moving the override_syslocation boolean into the devices table as we discussed earlier today in IRC.

057.sql has the schema updates required.

https://github.com/clinta/librenms/tree/location-override

**Comment by laf** [comment]
@clinta how far are you going with this so I know not to duplicate the work? I.e quite a few areas need changing to use the new schema, are you updating those or do you want me to?

**Comment by clinta** [comment]
@laf check the comparison, I believe I've gotten everwhere that the override was called from at least in master as it stands. https://github.com/librenms/librenms/compare/master...clinta:location-override

I was just going to write the schema, but it wasn't to hard to go find and correct the php to use the new schema. Figured that would provide a helpful starting point. I'm not planning to go farther with it though as the next steps are getting into this PR and adding the location table. Since you know the code in this PR best, you can probably do that much better than I.

**Pull request closed without merging**
