### PR TITLE
[UI] Fix last column of table

### PR DESCRIPTION
**Pull request by arjitc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Minor UI fix to add/fix the last column for alert state items

Old,
chrome_2018-12-01_17-10-17

New,
chrome_2018-12-01_17-11-40

### CODE REVIEW

**Comment by murrant** [comment]
Thanks for the fix :)  We can avoid the else by moving the <td> and </td> tags outside the if :)

**Comment by arjitc** [comment]
@murrant when I move it outside of the if , this happens,

chrome_2018-12-01_19-34-44


I assume you meant this (right?)

```
if ($alert_state != '') {
    if ($alert_state == '0') {
        $fa_icon  = 'check';
        $fa_color = 'success';
        $text     = 'Ok';
    } elseif ($alert_state == '1') {
        $fa_icon  = 'remove';
        $fa_color = 'danger';
        $text     = 'Alert';
    } elseif ($alert_state == '2') {
        $fa_icon  = 'info-circle';
        $fa_color = 'muted';
        $text     = 'Ack';
    } elseif ($alert_state == '3') {
        $fa_icon  = 'arrow-down';
        $fa_color = 'warning';
        $text     = 'Worse';
    } elseif ($alert_state == '4') {
        $fa_icon  = 'arrow-up';
        $fa_color = 'info';
        $text     = 'Better';
    }//end if
}
echo "<td><b><i class='fa fa-fw fa-".$fa_icon." text-".$fa_color."'></i> $text</b></td>";
```

**Comment by murrant** [comment]
@arjitc no, remove the td tag only, not the i tag :)

**Comment by arjitc** [comment]
@murrant ah I see, I've made the changes now 👍

**Pull request merged**
