### PR TITLE
fix syslog prune when dbFetchRow() returns array

### PR DESCRIPTION
**Pull request by rj-taylor**
My syslog table was not being pruned.  Troubleshooting revealed that if dbFetchRow() returns an array, dbDelete() won't do its work pruning the syslog table. murrant recommended I try dbFetchCell() instead of dbFetchRow().  This works fine and makes for a much cleaner patch.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by rj-taylor** [comment]
Working on a simpler fix for this, suggested by murrant.

**Comment by rj-taylor** [comment]
This is a much simpler solution than my first patch (thanks murrant).  This takes care of my syslog table pruning problem.

**Comment by PipoCanaja** [comment]
Thanx @rj-taylor !

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
