### PR TITLE
Update with FortiAP

### PR DESCRIPTION
**Pull request by wkamlun**
Add number of connected wireless client and number of connected FortiAP

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by wkamlun** [comment]
I run the command ./scripts/collect-snmp-data.php

OS: fortigate
Module(s): all
Variant: Fortigate

Capturing Data:  sysDescr.0 sysObjectID.0 sysName.0 SNMPv2-MIB::sysLocation.0 sysContact.0 FORTINET-FORTIGATE-MIB::fgSysVersion.0 ENTITY-MIB::entPhysicalSerialNum.1 ENTITY-MIB::entPhysicalModelName.1 ifDescr ifName ifAlias ifType ifOperStatus ifStackStatus entPhysicalEntry entAliasMappingIdentifier fgSysCpuUsage fgProcessorUsage fgVpnTunEntPhase1Name fgVpnTunEntPhase2Name fgVpnTunEntRemGwyIp fgHwSensors fgVpnTunEntStatus fgVpnSslState fgVpnTunnelUpCount fgVpnSslStatsLoginUsers fgVpnSslStatsActiveTunnels FORTINET-FORTIGATE-MIB::fgSysMemCapacity FORTINET-FORTIGATE-MIB::fgSysMemUsage ipAdEntIfIndex ipAdEntNetMask.10.253.16.100 ipAdEntNetMask.172.30.101.1 ipAdEntNetMask.172.30.102.1 ipAdEntNetMask.172.30.113.1 ipAdEntNetMask.192.168.2.99 ipAdEntNetMask.192.168.106.93 ipAdEntNetMask.192.168.107.225 ipAdEntNetMask.220.241.122.1 ipAddressIfIndex.ipv6 ipv6AddrPfxLength entPhysicalDescr entPhysicalName entPhySensorType entPhySensorScale entPhySensorPrecision entPhySensorValue entPhySensorOperStatus fgHaSystemMode.0 fgSysSesRate1 fgSysSesRate10 fgSysSesRate30 fgSysSesRate60 fgSysSesCount aixFsTableEntry fileSystemSpaceTable datasetTable zpoolTable hrStorageTable dskTable hrDeviceEntry hrProcessorEntry cdpCache lldpRemTable ipNetToPhysicalPhysAddress ipNetToMediaPhysAddress bgpLocalAs bgpPeerRemoteAs dot1dBasePortIfIndex dot1qVlanVersionNumber.0 diskIOEntry dot1dStpProtocolSpecification.0 .1.3.6.1.4.1.12356.101.14.2.4.0 .1.3.6.1.4.1.12356.101.14.2.7.0 dot1qTpFdbPort dot1dTpFdbPort sysUpTime.0 snmpEngineTime.0 hrSystemUptime.0 FORTINET-FORTIGATE-MIB::fgSysSesCount.0 FORTINET-FORTIGATE-MIB::fgSysCpuUsage.0 .1.3.6.1.4.1.12356.101.4.1.11.0 .1.3.6.1.4.1.12356.101.4.1.12.0 .1.3.6.1.4.1.12356.101.4.1.13.0 .1.3.6.1.4.1.12356.101.4.1.14.0 .1.3.6.1.4.1.12356.101.4.1.8.0 .1.3.6.1.4.1.12356.101.12.1.1.0 .1.3.6.1.4.1.12356.101.12.2.3.1.2.1 .1.3.6.1.4.1.12356.101.12.2.3.1.6.1 .1.3.6.1.4.1.12356.101.4.3.2.1.4.1 .1.3.6.1.4.1.12356.101.4.3.2.1.4.2 .1.3.6.1.4.1.12356.101.4.3.2.1.4.3 .1.3.6.1.4.1.12356.101.4.3.2.1.4.4 .1.3.6.1.4.1.12356.101.4.3.2.1.4.5 .1.3.6.1.4.1.12356.101.4.3.2.1.4.6 .1.3.6.1.4.1.12356.101.4.3.2.1.4.7 .1.3.6.1.4.1.12356.101.4.3.2.1.4.8 .1.3.6.1.4.1.12356.101.4.3.2.1.4.9 .1.3.6.1.4.1.12356.101.4.3.2.1.4.10 .1.3.6.1.4.1.12356.101.4.3.2.1.4.11 .1.3.6.1.4.1.12356.101.4.3.2.1.4.12 .1.3.6.1.4.1.12356.101.4.3.2.1.4.13 .1.3.6.1.4.1.12356.101.4.3.2.1.4.14 .1.3.6.1.4.1.12356.101.4.3.2.1.4.15 .1.3.6.1.4.1.12356.101.4.3.2.1.4.16 .1.3.6.1.4.1.12356.101.4.3.2.1.4.17 .1.3.6.1.4.1.12356.101.4.3.2.1.4.18 .1.3.6.1.4.1.12356.101.4.3.2.1.4.19 .1.3.6.1.4.1.12356.101.4.3.2.1.4.20 .1.3.6.1.4.1.12356.101.4.3.2.1.4.21 .1.3.6.1.4.1.12356.101.4.3.2.1.4.22 .1.3.6.1.4.1.12356.101.4.3.2.1.4.23 .1.3.6.1.4.1.12356.101.4.3.2.1.4.24 .1.3.6.1.4.1.12356.101.4.3.2.1.4.25 .1.3.6.1.4.1.12356.101.4.3.2.1.4.26 .1.3.6.1.4.1.12356.101.4.3.2.1.4.27 .1.3.6.1.4.1.12356.101.4.3.2.1.4.28 .1.3.6.1.4.1.12356.101.4.3.2.1.4.29 .1.3.6.1.4.1.12356.101.4.3.2.1.4.30 .1.3.6.1.4.1.12356.101.12.2.3.1.1.1 .1.3.6.1.4.1.12356.101.4.1.3.0 .1.3.6.1.4.1.12356.101.4.4.2.1.2.1 .1.3.6.1.4.1.12356.101.4.4.2.1.2.2 .1.3.6.1.4.1.12356.101.4.4.2.1.2.3 .1.3.6.1.4.1.12356.101.4.4.2.1.2.4 .1.3.6.1.4.1.12356.101.4.4.2.1.2.5 .1.3.6.1.4.1.12356.101.4.1.4.0 icmp ipForwDatagrams ipInDelivers ipInReceives ipOutRequests ipInDiscards ipOutDiscards ipOutNoRoutes ipReasmReqds ipReasmOKs ipReasmFails ipFragOKs ipFragFails ipFragCreates ipInUnknownProtos ipInHdrErrors ipInAddrErrors IP-FORWARD-MIB::ipCidrRouteNumber.0 snmp tcpActiveOpens tcpPassiveOpens tcpAttemptFails tcpEstabResets tcpCurrEstab tcpInSegs tcpOutSegs tcpRetransSegs tcpInErrs tcpOutRsts tcpHCInSegs.0 tcpHCOutSegs.0 udpInDatagrams udpOutDatagrams udpInErrors udpNoPorts hrSystemProcesses.0 hrSystemNumUsers.0 systemStats laLoadInt.1 laLoadInt.2 laLoadInt.3 ipSystemStats ifXEntry ifAdminStatus ifLastChange ifPhysAddress ifMtu ifInErrors ifOutErrors ifInDiscards ifOutDiscards dot3StatsDuplexStatus dot1qPvid OSPF-MIB::ospfGeneralGroup OSPF-MIB::ospfAreaEntry OSPF-MIB::ospfIfEntry OSPF-MIB::ospfNbrEntry OSPF-MIB::ospfIfMetricEntry

**Comment by wkamlun** [comment]
[fortigate_fortigate.zip](https://github.com/librenms/librenms/files/6806547/fortigate_fortigate.zip)

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by PipoCanaja** [comment]
@wkamlun 
Thanx for the PR and the test data. 
@murrant Another one of those tests that behave different between  save-test-data and dev:check. I suppose this is linked to the mapping of OSPF interfaces to IfIndexes via DB calls.

**Pull request merged**
