### PR TITLE
Align the buttons (Edit and Delete) to the right in Map Management

### PR DESCRIPTION
**Pull request by santiag0z**
Please give a short description what your pull request is for
Before
image
image

After
image
image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by electrocret — APPROVED** [review]

**Comment by murrant** [comment]
If you want this change, you should limit the width of the panel.

image

**Comment by murrant** [comment]
@santiag0z yes, I set it intentionally like that so the buttons didn't get too far away from the label.

**Comment by murrant** [comment]
My snip was misleading this is what I'm saying:
image

**Comment by murrant** [comment]
maybe a better fix was to change it from sm: to md:

**Pull request merged**
