### PR TITLE
Add support for more Cisco FTD devices

### LINKED ISSUE #16106: Cisco FirePower 3110
### The problem

Firewall is discovered as a generic device

### Output of ./validate.php

```txt
librenms@p-mon-lims01:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.5.0-37-g4f183989c (2024-06-10T03:11:03+02:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.1.2-1ubuntu2.15
Python    | 3.10.12
Database  | MariaDB 10.6.16-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your install is over 24 hours out of date, last update: Mon, 10 Jun 2024 01:11:03 +0000
	[FIX]:
	Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
	[FIX]:
	sudo chown -R librenms:librenms /opt/librenms
	sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
	sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
	Files:
	 /opt/librenms/rrd/smokeping/__sortercache
	 /opt/librenms/rrd/smokeping/__sortercache/data.lnmsFPing-1.storable
	 /opt/librenms/rrd/smokeping/__sortercache/data.lnmsFPing-0.storable
	 /opt/librenms/rrd/smokeping/__sortercache/data.storable
	 /opt/librenms/rrd/smokeping/__sortercache/data.DNS.storable
	 /opt/librenms/rrd/smokeping/__sortercache/data.FPing.storable
	 /opt/librenms/rrd/smokeping/Ungrouped
	 /opt/librenms/rrd/smokeping/Ungrouped/p-fwl-cisc01-pri_neas_local.rrd
	 /opt/librenms/rrd/smokeping/Ungrouped/p-fwl-cisc01-pri_neas_local~p-mon-smpi01.neas.local.rrd
	 /opt/librenms/rrd/smokeping/network
	 /opt/librenms/rrd/smokeping/network/AALX28.rrd
	 /opt/librenms/rrd/smokeping/network/10_227_128_3~p-mon-smpi01.neas.local.rrd
	 /opt/librenms/rrd/smokeping/network/AALN1301.rrd
	 /opt/librenms/rrd/smokeping/network/10_228_32_38~p-mon-smpi01.neas.local.rrd
	 /opt/librenms/rrd/smokeping/network/AALX26~p-mon-smpi01.neas.local.rrd
	  and 358 more...
librenms@p-mon-lims01:~$
```

### What was the last working version of LibreNMS?

24.5.0-37

### Device info

Cisco FirePower 3110

### Discovery output

```txt
https://pastebin.com/Qqrg8yK7
```

### Poller output

```txt
https://pastebin.com/1miu4Y5a
```

### PR DESCRIPTION
**Pull request by normand-hue**
Add sysObjectID definition for Cisco Secure Firewall 3110
Add sysObjectID definition for Cisco Secure Firewall 3120
Add sysObjectID definition for Cisco Secure Firewall 3130

fixes #16106 

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @normand-hue 
Thanx for your PR. I jumped in with @pertoft as he also has the same family of devices (3110 in his case) that is not currently supported. 
Now that the sysObjectIDs are added, next step is to add test data. 
@normand-hue  and @pertoft : Could you please add test data (snmpsim files) for your devices to this PR ? And the matching JSON as well if you can.

Thanx

**Comment by normand-hue** [comment]
[ftd_firewall.snmprec.txt](https://github.com/user-attachments/files/15928971/ftd_firewall.snmprec.txt)

**Comment by PipoCanaja** [comment]
Thx @normand-hue 
@pertsoft, could you submit one as well ?

**Comment by pertoft** [comment]
Hi,

I do not have write access to this pr. So I have forked librenms and committed the files:
https://github.com/pertoft/librenms/commit/65ff6d5ec7907313f5bbbb53ec8f66b2eef25d5e

I hope this is enough, otherwise let me know

**Comment by PipoCanaja** [comment]
Hi,
Yes it is fine. Seems that you both have 3110, both running the same software. So we'll keep only one of the 2 files, will be enough for the PR. 
Thx !

**Review by PipoCanaja — APPROVED** [review]
LGTM !

**Comment by PipoCanaja** [comment]
Hi @normand-hue  and @pertoft 
Thanx to both of you !

**Pull request merged**
