### PR TITLE
refactor: Further speed improvements to port poller

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Improved the selected ports polling section, we don't need to do the full walk as that still causes issues with devices with a lot of ports. It may add a small increase for low port number devices with all enabled and up ports but this feature didn't help with that before.

For me on a device with high latency, ports went from 170~ to 120~.

### CODE REVIEW

**Comment by wriedel** [comment]
Hi Laf, very cool. For a Cat4503/SUP8e with 96ports where I already had disabled all non needed modules I am now down to 25sec from 50sec!  
Question: For Pollers, Poller history, there is a line-item listing for every device. Is there a way to have a graph visualizing all this and also give me an aggregated number for a polling cycle? 
Would make the saving more visual ;-)

**Comment by wriedel** [comment]
Hi Laf, is this by design that ports being identified by that feature gets deleted?

**Comment by laf** [comment]
No

**Comment by wriedel** [comment]
you need more debugs or anything else?

**Comment by laf** [comment]
Full port debug for poller and discovery

**Comment by laf** [comment]
I still think this is ok to merge.

https://community.librenms.org/t/do-not-pool-virtual-interfaces/619/14

**Comment by LoZio** [comment]
Running LibreNMS  | 1.37-40-g6b68d5f
I checked one of the files in your commit and see different code in my setup as of today (Mar 13). There is some special procedure to do to have your patch without switching to a specific PR?
I'm desperately trying to lower my poll times and this coud be very useful.
Do I need to configure something to enable this patch?
Sorry for my dumbness

**Comment by murrant** [comment]
You already have this code.

Please read this https://docs.librenms.org/Support/Performance/

**Comment by LoZio** [comment]
I read that doc and I'm experimenting with all the parameters to find the better setup for my environment.
I supposed to have different code since if I look at the commit in this thread and files on my disk they are different.
Daily.sh says I have the latest code though.

**Comment by murrant** [comment]
@LoZio code changes over time.  There has been improvements/bugfixes since then.
If `./validate.php` says you are all good, you are up to date.

Make sure to pay attention to the per-port polling section of the performance docs that may help you.

**Pull request merged**
