### PR TITLE
deduping type_where code, adding manual types to graph widgets 

### PR DESCRIPTION
**Pull request by brandune**
Follow-up to https://github.com/librenms/librenms/pull/3564

Several places in the code run queries against the 'ports' table to find ports matching a given 'port_descr_type'. There are ever so slight differences in each of these places, but nothing meaningful as far as I can tell. One commit here dedups that code with a function in functions.inc.php.

The new function adds two new behaviors: It substitutes @ for % in the SQL, allowing for the use of wildcards. It also supports querying for arbitrary strings that aren't represented in $config. This is mostly to support the second commit, but also allows for arbitrary queries on the iftype page and the get_graph_by_portgroup api endpoint as well.

The second commit adds a new dropdown selection to the graph dashboard widget called 'Manual Descr'. It provides a text field to manually specify the string that's used to query the ports table. This adds some flexibility in the dashboards you can create by structuring your interface descriptions and using the wildcard behavior added in the first commit.

### CODE REVIEW

**Comment by laf** [comment]
We've had to revert this as it affects the main navigation ports -> transit/peering

**Comment by brandune** [comment]
:( Sorry about that. Do you have any more details about the issue, or what config it hiccups with? 

I'm using the config below and don't notice any issues with the ports dropdown menu -> transit, peering, or transit/peering.

```
$config['transit_descr']   = 'transit@';
$config['peering_descr']   = array('public-@', 'private-@');
```

**Comment by brandune** [comment]
@laf Do you have any other info on the issue caused by this merge?

**Comment by laf** [comment]
@brandune sorry didn't see your initial reply, this basically breaks existing Transit/Peering/Core pages so the old method stopped working.

**Comment by brandune** [comment]
@laf No worries! I'm afraid I still don't understand the real issue though. The main navigation links are links to the iftype page with type=transit, type=peering, or type=transit,peering.  Running this pr in our environment, the iftype page still works for either individual or comma separated lists of 'types', including those main navigation links. I can't reproduce whatever's broken.

The only change in behavior I can see is where '@' is substituted. If someone out there is using the '@' literal in their type strings, this pr might cause extra interfaces to be returned in the db query.

**Comment by laf** [comment]
It's quite easy to replicate for me.

I can switch to your branch, edit a devices port and set it to Transit: Testing. Go to Transit and Peering page and see nothing, change back to master branch, refresh and it appears fine.

**Comment by brandune** [comment]
Ah ha. That's what I get for not testing the default install. So this is because my branch doesn't handle the default value of $config['transit_descr'] being an empty string, and the main branch sort of ignores that.

The main branch has an extra step where it adds the url's 'type' parameter to the db query whether that string has any significance in $config or not. I guess that's to allow arbitrary queries to the iftype page. My branch supports this by checking $config for a matching entry to read, and if there is none it will add the url's 'type' parameter to the query. But if there is a matching entry in $config, the type parameter itself is ignored in favor of whatever's in $config.

The 'glitch' is that config.php.default sets the transit_descr option to an empty string by default. Running my branch with the default config does query the DB for port descriptions matching an empty string, but of course that returns nothing. The main branch ends up querying for descriptions matching 'transit' because that's the url's value, even though the default config explicitly sets this to an empty string.

I think that the best fix is setting the default $config['transit_descr'] to 'transit' instead of an empty string (and do the same for the other default groups). I think that more clearly describes the intended behavior of the default configuration. It's also easy to make my branch follow the main branch's behavior, but I think that behavior is a little implicit/unclear. Do you have any preference?

**Comment by laf** [comment]
That works for me, you'll need to submit a new PR though :/

**Pull request merged**
