### PR TITLE
Ports by device group

### PR DESCRIPTION
**Pull request by electrocret**
Create the URL filter option to filter ports by DeviceGroup.  /ports/devicegroup=##/

image

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
The only problem I see is that no one will know this feature exists.

You could probably improve the efficiency of the query, but that might not be needed.  The best way to test is to use a factory to generate a large amount of ports, devices, and device groups. https://laravel.com/docs/9.x/database-testing#creating-models-using-factories

**Comment by electrocret** [comment]
I added a GUI entry so people will know it exists.

**Comment by PipoCanaja** [comment]
> I added a GUI entry so people will know it exists.

Hi ! Could you please add a screen capture in the PR to show it ? Thanx

**Review by murrant — APPROVED** [review]
LGTM

**Pull request merged**
