### PR TITLE
newdevice: Added additional sensor support for Huawei VRP #4279

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #4279

### CODE REVIEW

**Comment by murrant** [comment]
Needs rebase.  I can't give any feedback on this one.

**Comment by laf** [comment]
This has been rebased.

**Comment by laf** [comment]
This should be good now, the user submitting this and testing in #4279 has confirmed it's working except dBm values but they are correct they just expected to see a different value in uW rather than dBM.

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
Confirmed working in the issue so merging.

**Pull request merged**
