### PR TITLE
Ask people to contribute documentation

### PR DESCRIPTION
**Pull request by trs80**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Good addition, but I'm not sure if the content is right.

**Comment by paulgear** [comment]
Seems reasonable to me; maybe "Some features exist ..." would be better?

**Comment by laf** [comment]
I think something like:

```
Documentation. Documentation can always be improved and every little helps. Not all features are currently documented or documented well, speeling mistakes exist along with additional FAQs.
```

**Comment by laf** [comment]
Thanks :)

**Pull request merged**
