### PR TITLE
Docs: Allow host renames with selinux enforcing

### PR DESCRIPTION
**Pull request by kedearian**
you have to change the fcontext of /opt/librenms/rrd/ to allow read/write.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
This is covered by #6920

**Comment by kedearian** [comment]
Sorry i was going off the docs from http://docs.librenms.org/Installation/Installation-CentOS-7-Nginx/#selinux and didn't see this. I'll close my pull.

**Comment by murrant** [comment]
No, it's good to make this change now.  I was just making a note.

**Comment by laf** [comment]
So @murrant's PR has `semanage fcontext -a -t httpd_sys_content_t '/opt/librenms/rrd(/.*)?'` as well. If you both agree this should be in then I'll add it to this PR and merge.

**Comment by murrant** [comment]
Sounds good @laf that way we get more correct installs while we wait for the other PR to merge.

**Comment by kedearian** [comment]
Sounds good to me as well, thanks.

**Pull request merged**
