### PR TITLE
Added support for Cambium cnMatrix switches

### PR DESCRIPTION
**Pull request by noaheroufus**
Added MIBs and definitions to support Cambium cnMatrix switches.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
You'll need to remove all the duplicate MIBs.  (check in the base mibs directory)

**Comment by noaheroufus** [comment]
Removed all my duplicates.
Also fixed LLDP-EXT-DOT1-MIB and LLDP-EXT-DOT3-MIB having the same DOT3 content in both.  DOT3 contains the newer of the two MIBs, DOT1 file was replaced with the DOT1 definition that I had in `mibs/cambium/cnmatrix/`.

**Comment by Jellyfrog** [comment]
You should remove the unused mibs also. We normally only include the used ones

**Comment by noaheroufus** [comment]
OK, removed any unused/unreferenced MIBs.

**Review by murrant — APPROVED** [review]
Much cleaner, thanks!
Annoying they don't support ifAlias.

**Pull request merged**
