### PR TITLE
Added load and state to device overview

### LINKED ISSUE #1252: Add Load to the device homepage
See https://www.dropbox.com/s/7tn4b0tm8wfg150/Screenshot%202015-06-12%2008.57.46.png?dl=0

### PR DESCRIPTION
**Pull request by laf**
Fixes #1252

### CODE REVIEW

**Comment by laf** [comment]
trigger ci

**Comment by laf** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by laf** [comment]
Not sure it's worth pushing another commit to trigger an update, simple PR this one.

**Comment by f0o** [comment]
It's only scrut that keeps failing

**Pull request merged**
