### PR TITLE
Rename index_string to str_index_as_numeric

### PR DESCRIPTION
**Pull request by PipoCanaja**
Renaming index_string to a more self explanatory index:str2num. Documentation also updated.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — CHANGES_REQUESTED** [review]
you shouldn't use a colin like that as it is already used for other things

**Comment by PipoCanaja** [comment]
> you shouldn't use a colin like that as it is already used for other things

I also thought of `str2num($index)` which would lead to `{{ str2num($index) }}` in the YAML file. It is a little bit long but at least it means "feed current index variable to a str2num function" which is basically what we do here.

What would you suggest ?

**Comment by murrant** [comment]
That makes it look like you can run functions inside {{}}, which we don't want to indicate.

`str_index_as_numeric` ?

Question, should $index always be numeric?

maybe we delete this and always convert strings in an index to numeric for $index?

I think the main trick with this is enum in index.  But those should be displayed differently I think:
.3.enum.0 vs .3."string".0

**Comment by PipoCanaja** [comment]
> That makes it look like you can run functions inside {{}}, which we don't want to indicate.
> 
> `str_index_as_numeric` ?
Why not. I prefered the look of the original one, but clearly this one does not lead to confusion with functions and will (very probably) never collision with a real OID (so many underscores :) ), so good candidate.

> Question, should $index always be numeric?
> maybe we delete this and always convert strings in an index to numeric for $index?
> I think the main trick with this is enum in index. But those should be displayed differently I think: .3.enum.0 vs .3."string".0
There is no way to differentiate an enum from a numerical OID if the enum is only made of digits so it would probably break thinks here.
Basically, if we had a way to get data out of snmpwalk/get in a clean and typed datastructure (like a JSON reply with both row SNMP oid and reply, as well as all the type magic that is taken from the MIB, instead of the text that is not parsable in a safe and reproductible way). But that does not exist ...

I'll go with str_index_as_numeric asap and update here.

**Comment by PipoCanaja** [comment]
@murrant After a very long time, this one should be good to go if tests are successful.

**Review by murrant — APPROVED** [review]

**Pull request merged**
