### PR TITLE
fix: Toner graphs with invalid chars

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.
- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Added a function to do this, it re-uses an existing function for simplicity for now but I expect the two to diverge at some stage.

### CODE REVIEW

**Comment by jquagga** [comment]
I wanted to see if this would fix #4868 for me.  It changes the behavior, but it doesn't seem the colon is escaped so rrdgraph still is unhappy.  

Here's a copy of the rrdtool debug from the webui:
```
RRDTool Command
rrdtool graph /tmp/YBveQO5SYVtYX8hF.png --alt-autoscale-max --rigid -E --start 1477313400 --end 1477399800 --width 1164 --height 300 -c BACK#EEEEEE00 -c SHADEA#EEEEEE00 -c SHADEB#EEEEEE00 -c FONT#000000 -c CANVAS#FFFFFF00 -c GRID#a5a5a5 -c MGRID#FF9999 -c FRAME#5e5e5e -c ARROW#5e5e5e -R normal --font LEGEND:8:DejaVuSansMono --font AXIS:7:DejaVuSansMono --font-render-mode normal -l 0 -E COMMENT:'Toner level Cur Min Max\n' DEF:toner3=/opt/librenms/rrd/scribe.internal/toner-1.rrd:toner:AVERAGE LINE2:toner3#bf5d5b:'Toner S/N:CRUM-1' GPRINT:toner3:LAST:'%5.0lf%%' GPRINT:toner3:MIN:'%5.0lf%%' GPRINT:toner3:MAX:%5.0lf%%\\l

RRDTool Output
ERROR: Unused Arguments "CRUM-1" in command : LINE2:toner3#bf5d5b:Toner S/N:CRUM-1
```

"Toner S/N:CRUM-16021314488" became "Toner S/N:CRUM-1"

**Comment by laf** [comment]
This again now, if it still doesn't work please show the link you are going to to get to that graph.

**Comment by jquagga** [comment]
Good day,

I've applied the second patch and it doesn't seem to change the behavior I'm afraid.  It still comes up with "Toner S/N:CRUM-1".  The link I'm using is by clicking on the toner graph (all red) in the corner of the printer.  The URL is:

https://bes.internal/graphs/type=device_toner/device=10/to=1477402800/from=1477316400/showcommand=yes/

Here's a screenshot with the URL and the rrd output.  
screenshot-fs8

**Comment by laf** [comment]
That's a different graph file than I changed, try now.

**Comment by jquagga** [comment]
Perfect!  It works great now!  It does have the ending \ that I talked about in #4882 but that's another mater.  

There's no graph below because I removed / re-added the device when trying the updates.  So it doesn't have much of a rrd history yet, but it's building.  

screenshot-fs8

**Comment by laf** [comment]
Added phpdoc, feel free to rename the function though.

**Pull request merged**
