### PR TITLE
Added ability to globally disable sending alerts

### LINKED ISSUE #2360: Feature Request - Disable Alert Notifications Globally
Since we don't have any parent/child relationships is an entire site is experiencing issues we have a plethora of alerts coming in via email.  

For example there are some routing issues taking place on the internet today making some of our subnets unreachable so it is constantly flapping and alerting us all day.  Instead of needing to disable manually 20-30 devices I'd like to manually disable the alerts until the problem is done.  

I'd like the option to click a button.  Maybe a widget can be made for this for the dashboard?  A small set of 4-6 buttons each with some form of control that will disable only alerting.  Or have icons for other functions.  Maybe the slider buttons for General alert settings?

### PR DESCRIPTION
**Pull request by laf**
Fix #2360 

It's a good thing to have, people might want to just disable all alerting without disabling cron so I agree it's a good idea. Feel free to merge or not though.

### CODE REVIEW

**Comment by Lonecrowe** [comment]
+1

**Comment by f0o** [comment]
trigger ci

**Comment by paulgear** [comment]
:+1: - I think it would be great if we had a similar button for polling

**Comment by Lonecrowe** [comment]
+1

**Pull request merged**
