### PR TITLE
Do not purge alert_log table entries that have a matching active alert in alerts table

### PR DESCRIPTION
**Pull request by louis-oui**
**Observed behaviour :**
From what I understand, in database, alert_log table contains details of active and previous alert. Information on state (active or not) of alert is in alerts table.

In daily maintenance script, alert_log logs table entries in database older than $config['alert_log_purge'] days are purged. Default value of $config['alert_log_purge'] is 365 days. It possible to decrease the value to a few days for example. Daily process purges details of aged alerts, no matter there are still active or not. If active alerts were older than $config['alert_log_purge'] days, their details are removed in alert_log table. Next polling will recreate a new alert_log entry and alert routine will consider the active alert as a new one. If transport is set for the alert rule, the alert is exported again.

**Consequence :**
In our environment, daily maintenance is done every day during the night at 2 am (time of daily maintenance is choosen by librenms service v2). At that time, people are woken up for an existing alert that there were already aware of.

**Fix :**

This fix changes alert_log purging process in daily.php so that only alert_log table entries that have NO matching active alert in alerts table are removed.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by louis-oui** [comment]
2019-10-18 16:06:02	Cisco/Juniper - interface vlan down (teams)		
n9504XXXXXX
#1: Vlan3103;  network - Vlan3103; 

MariaDB [librenms]> select name from alert_rules where id=52;
+---------------------------------------------+
| name                                        |
+---------------------------------------------+
| Cisco/Juniper - interface vlan down (teams) |
+---------------------------------------------+
1 row in set (0.00 sec)


MariaDB [librenms]> select time_logged, state from alert_log where rule_id=52 and device_id=15;
+---------------------+-------+
| time_logged         | state |
+---------------------+-------+
| 2019-10-18 16:04:15 |     1 |
+---------------------+-------+
1 row in set (0.00 sec)

MariaDB [librenms]> select * from alerts where rule_id=52 and device_id=15;
+-------+-----------+---------+-------+---------+------+------+---------------------+------+
| id    | device_id | rule_id | state | alerted | open | note | timestamp           | info |
+-------+-----------+---------+-------+---------+------+------+---------------------+------+
| 15875 |        15 |      52 |     1 |       1 |    1 | NULL | 2019-10-18 16:06:02 |      |
+-------+-----------+---------+-------+---------+------+------+---------------------+------+
1 row in set (0.00 sec)

# cat decode2.php
<?php
$hostname = "127.0.0.1";
$username = "librenms";
$password = "X";
$dbName = "librenms";

$link = mysqli_connect($hostname,$username,$password,$dbName);

$query = "select * from alert_log where device_id=15 and rule_id=52"; # and time_logged = '2019-10-24 18:25:47' "; #and time_logged = '2019-10-24 02:06:13' ";

if ($res = mysqli_query($link, $query)) { 
    if (mysqli_num_rows($res) > 0) { 
        while ($row = mysqli_fetch_array($res)) { 
          echo $row['device_id']." ".$row['time_logged']."\n";
          $decode = json_decode(gzuncompress($row['details']), true);
          print_r($decode);
        } 
        //mysqli_free_res($res); 
    } 
    else { 
        echo "No matching records are found."; 
    } 
} 
else { 
    echo "ERROR: Could not able to execute $query. "
                                .mysqli_error($link); 
} 
mysqli_close($link); 

?>

[root@librenms-prod-dc1 ~]$ php decode2.php 
15 2019-10-18 16:04:15
Array
(
    [contacts] => Array
        (
        )

    [rule] => Array
        (
            [0] => Array
                (
                    [device_id] => 15
                    [hostname] => XXXXXXXXXXX
                    [sysName] => XXXXXXXXXXX
                    [ip] => 10.0.8.10
                    [community] => 
                    [authlevel] => authNoPriv
                    [authname] => X
                    [authpass] => X
                    [authalgo] => MD5
                    [cryptopass] => 
                    [cryptoalgo] => 
                    [snmpver] => v3
                    [port] => 161
                    [transport] => udp
                    [timeout] => 
                    [retries] => 
                    [snmp_disable] => 0
                    [bgpLocalAs] => 65011
                    [sysObjectID] => .1.3.6.1.4.1.9.12.3.1.3.1507
                    [sysDescr] => Cisco NX-OS(tm) nxos.7.0.3.I5.2.bin, Software (nxos), Version 7.0(3)I5(2), RELEASE SOFTWARE Copyright (c) 2002-2016 by Cisco Systems, Inc. Compiled 2/16/2017 7:00:00
                    [sysContact] => 
                    [version] => 7.0(3)I5(2)
                    [hardware] => N9K-C9504
                    [features] => 
                    [location_id] => 
                    [os] => nxos
                    [status] => 1
                    [status_reason] => 
                    [ignore] => 0
                    [disabled] => 0
                    [uptime] => 13703595
                    [agent_uptime] => 0
                    [last_polled] => 2019-10-28 15:54:21
                    [last_poll_attempted] => 
                    [last_polled_timetaken] => 9.84
                    [last_discovered_timetaken] => 479.92
                    [last_discovered] => 2019-10-28 13:08:00
                    [last_ping] => 2019-10-28 15:54:21
                    [last_ping_timetaken] => 0.48
                    [purpose] => 
                    [type] => network
                    [serial] => FOXXXXXXX
                    [icon] => cisco.svg
                    [poller_group] => 0
                    [override_sysLocation] => 0
                    [notes] => 
                    [port_association_mode] => 1
                    [max_depth] => 0
                    [port_id] => 833
                    [port_descr_type] => 
                    [port_descr_descr] => 
                    [port_descr_circuit] => 
                    [port_descr_speed] => 
                    [port_descr_notes] => 
                    [ifDescr] => Vlan3103
                    [ifName] => Vlan3103
                    [portName] => 
                    [ifIndex] => 151063583
                    [ifSpeed] => 1000000000
                    [ifConnectorPresent] => false
                    [ifPromiscuousMode] => false
                    [ifHighSpeed] => 1000
                    [ifOperStatus] => down
                    [ifOperStatus_prev] => up
                    [ifAdminStatus] => up
                    [ifAdminStatus_prev] => up
                    [ifDuplex] => 
                    [ifMtu] => 1500
                    [ifType] => propVirtual
                    [ifAlias] => Vlan3103
                    [ifPhysAddress] => a0e0afecbdbf
                    [ifHardType] => 
                    [ifLastChange] => 1012848454
                    [ifVlan] => 
                    [ifTrunk] => 
                    [ifVrf] => 0
                    [counter_in] => 
                    [counter_out] => 
                    [detailed] => 0
                    [deleted] => 0
                    [pagpOperationMode] => 
                    [pagpPortState] => 
                    [pagpPartnerDeviceId] => 
                    [pagpPartnerLearnMethod] => 
                    [pagpPartnerIfIndex] => 
                    [pagpPartnerGroupIfIndex] => 
                    [pagpPartnerDeviceName] => 
                    [pagpEthcOperationMode] => 
                    [pagpDeviceId] => 
                    [pagpGroupIfIndex] => 
                    [ifInUcastPkts] => 0
                    [ifInUcastPkts_prev] => 0
                    [ifInUcastPkts_delta] => 0
                    [ifInUcastPkts_rate] => 0
                    [ifOutUcastPkts] => 0
                    [ifOutUcastPkts_prev] => 0
                    [ifOutUcastPkts_delta] => 0
                    [ifOutUcastPkts_rate] => 0
                    [ifInErrors] => 0
                    [ifInErrors_prev] => 0
                    [ifInErrors_delta] => 0
                    [ifInErrors_rate] => 0
                    [ifOutErrors] => 0
                    [ifOutErrors_prev] => 0
                    [ifOutErrors_delta] => 0
                    [ifOutErrors_rate] => 0
                    [ifInOctets] => 0
                    [ifInOctets_prev] => 0
                    [ifInOctets_delta] => 0
                    [ifInOctets_rate] => 0
                    [ifOutOctets] => 0
                    [ifOutOctets_prev] => 0
                    [ifOutOctets_delta] => 0
                    [ifOutOctets_rate] => 0
                    [poll_time] => 1572274457
                    [poll_prev] => 1572274336
                    [poll_period] => 121
                )

        )

    [interval] => 1572258420
)

MariaDB [librenms]> SELECT count(*) FROM alert_log INNER JOIN alerts ON alerts.device_id=alert_log.device_id AND alerts.rule_id=alert_log.rule_id WHERE alerts.state=0 AND alert_log.time_logged < DATE_SUB(NOW(),INTERVAL 7 DAY);
+----------+
| count(*) |
+----------+
|     3544 |
+----------+
1 row in set (0.03 sec)

MariaDB [librenms]> SELECT count(*) FROM alert_log INNER JOIN alerts ON alerts.device_id=alert_log.device_id AND alerts.rule_id=alert_log.rule_id WHERE alerts.state!=0 AND alert_log.time_logged < DATE_SUB(NOW(),INTERVAL 7 DAY);
+----------+
| count(*) |
+----------+
|     1733 |
+----------+
1 row in set (0.01 sec)

[root@librenms-prod-dc1 /appl/librenms]$ grep alert_log_purge config.php
$config['alert_log_purge'] = 7;

[root@librenms-prod-dc1 /appl/librenms]$ php ./daily.php -d -f alert_log
DEBUG
Deleting alert_logs more than 7 days that are not active

MariaDB [librenms]> SELECT COUNT(*) FROM alert_log INNER JOIN alerts ON alerts.device_id=alert_log.device_id AND alerts.rule_id=alert_log.rule_id WHERE alerts.state=0 AND alert_log.time_logged < DATE_SUB(NOW(),INTERVAL 7 DAY);
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.01 sec)

MariaDB [librenms]> SELECT COUNT(*) FROM alert_log INNER JOIN alerts ON alerts.device_id=alert_log.device_id AND alerts.rule_id=alert_log.rule_id WHERE alerts.state!=0 AND alert_log.time_logged < DATE_SUB(NOW(),INTERVAL 7 DAY);
+----------+
| COUNT(*) |
+----------+
|     1733 |
+----------+
1 row in set (0.00 sec)

MariaDB [librenms]> select time_logged, state from alert_log where rule_id=52 and device_id=15;+---------------------+-------+
| time_logged         | state |
+---------------------+-------+
| 2019-10-18 16:04:15 |     1 |
+---------------------+-------+
1 row in set (0.00 sec)

MariaDB [librenms]> select * from alerts where rule_id=52 and device_id=15;+-------+-----------+---------+-------+---------+------+------+---------------------+------+
| id    | device_id | rule_id | state | alerted | open | note | timestamp           | info |
+-------+-----------+---------+-------+---------+------+------+---------------------+------+
| 15875 |        15 |      52 |     1 |       1 |    1 | NULL | 2019-10-18 16:06:02 |      |
+-------+-----------+---------+-------+---------+------+------+---------------------+------+
1 row in set (0.00 sec)

**Comment by louis-oui** [comment]
Add deleting history of active alert_logs more than ? days in code

Before testing

```
MariaDB [librenms]> SELECT alert_log.device_id, alert_log.rule_id, time_logged FROM alert_log INNER JOIN alerts ON alerts.device_id=alert_log.device_id AND alerts.rule_id=alert_log.rule_id WHERE alerts.state!=0 AND alert_log.time_logged < DATE_SUB(NOW(),INTERVAL 7 DAY) ORDER BY alert_log.device_id, alert_log.rule_id;
+-----------+---------+---------------------+
| device_id | rule_id | time_logged         |
+-----------+---------+---------------------+
|        12 |      20 | 2019-10-20 02:06:34 |
|        13 |      20 | 2019-10-20 02:06:35 |
|        14 |      20 | 2019-10-20 02:07:25 |
|        14 |      52 | 2019-10-18 16:04:59 |
|        15 |      20 | 2019-10-20 02:07:36 |
|        15 |      52 | 2019-10-18 16:04:15 |
|        16 |      20 | 2019-10-20 02:07:21 |
|        17 |      20 | 2019-10-20 02:07:20 |
|        25 |      20 | 2019-10-19 02:06:33 |
|        26 |      20 | 2019-10-20 02:06:22 |
|        27 |      20 | 2019-10-20 02:06:08 |
|        28 |      20 | 2019-10-20 02:06:18 |
|        29 |      20 | 2019-10-20 02:06:12 |
|        29 |      48 | 2019-10-18 13:09:49 |
|        30 |      20 | 2019-10-20 02:06:12 |
|        32 |      20 | 2019-10-20 02:06:12 |
|        34 |      20 | 2019-10-20 02:06:12 |
|        35 |      20 | 2019-10-20 02:06:06 |
|        36 |      20 | 2019-10-20 02:06:18 |
|        37 |      20 | 2019-10-20 02:06:18 |
|        38 |      20 | 2019-10-20 02:07:55 |
|        47 |      20 | 2019-10-20 02:07:51 |
|        53 |      20 | 2019-10-20 00:50:32 |
|        53 |      20 | 2019-10-20 00:44:52 |
|        54 |      20 | 2019-10-20 00:44:14 |
|        54 |      20 | 2019-10-20 00:50:59 |
|        55 |      20 | 2019-10-20 02:06:06 |
|        59 |      20 | 2019-10-20 02:07:26 |
|        82 |      20 | 2019-10-20 02:06:53 |
|        83 |       3 | 2019-10-21 14:44:06 |
|        83 |       3 | 2019-10-21 14:42:06 |
|        83 |      20 | 2019-10-20 02:06:53 |
|       110 |      12 | 2019-10-19 02:06:34 |
|       110 |      19 | 2019-10-20 02:06:31 |
|       111 |      19 | 2019-10-20 02:06:31 |
|       118 |      20 | 2019-10-20 02:06:31 |
|       119 |      20 | 2019-10-20 02:06:33 |
|       137 |      16 | 2019-10-19 02:07:50 |
|       138 |      16 | 2019-10-19 02:07:51 |
|       139 |      12 | 2019-10-21 16:05:57 |
|       139 |      12 | 2019-10-21 16:03:50 |
|       139 |      16 | 2019-10-21 16:05:57 |
|       139 |      16 | 2019-10-21 16:03:50 |
+-----------+---------+---------------------+
43 rows in set (0.01 sec)
```
Testing
```
[root@librenms-prod-dc1 /appl/librenms]$ php ./daily.php -d -f alert_log
DEBUG
Deleting alert_logs more than 7 days that are not active
Deleting history of active alert_logs more than 7 days
```
After testing, 

```

MariaDB [librenms]> SELECT alert_log.device_id, alert_log.rule_id, time_logged FROM alert_log INNER JOIN alerts ON alerts.device_id=alert_log.device_id AND alerts.rule_id=alert_log.rule_id WHERE alerts.state!=0 AND alert_log.time_logged < DATE_SUB(NOW(),INTERVAL 7 DAY) ORDER BY alert_log.device_id, alert_log.rule_id;
+-----------+---------+---------------------+
| device_id | rule_id | time_logged         |
+-----------+---------+---------------------+
|        12 |      20 | 2019-10-20 02:06:34 |
|        13 |      20 | 2019-10-20 02:06:35 |
|        14 |      20 | 2019-10-20 02:07:25 |
|        14 |      52 | 2019-10-18 16:04:59 |
|        15 |      20 | 2019-10-20 02:07:36 |
|        15 |      52 | 2019-10-18 16:04:15 |
|        16 |      20 | 2019-10-20 02:07:21 |
|        17 |      20 | 2019-10-20 02:07:20 |
|        25 |      20 | 2019-10-19 02:06:33 |
|        26 |      20 | 2019-10-20 02:06:22 |
|        27 |      20 | 2019-10-20 02:06:08 |
|        28 |      20 | 2019-10-20 02:06:18 |
|        29 |      20 | 2019-10-20 02:06:12 |
|        29 |      48 | 2019-10-18 13:09:49 |
|        30 |      20 | 2019-10-20 02:06:12 |
|        32 |      20 | 2019-10-20 02:06:12 |
|        34 |      20 | 2019-10-20 02:06:12 |
|        35 |      20 | 2019-10-20 02:06:06 |
|        36 |      20 | 2019-10-20 02:06:18 |
|        37 |      20 | 2019-10-20 02:06:18 |
|        38 |      20 | 2019-10-20 02:07:55 |
|        47 |      20 | 2019-10-20 02:07:51 |
|        53 |      20 | 2019-10-20 00:50:32 |
|        54 |      20 | 2019-10-20 00:50:59 |
|        55 |      20 | 2019-10-20 02:06:06 |
|        59 |      20 | 2019-10-20 02:07:26 |
|        82 |      20 | 2019-10-20 02:06:53 |
|        83 |       3 | 2019-10-21 14:44:06 |
|        83 |      20 | 2019-10-20 02:06:53 |
|       110 |      12 | 2019-10-19 02:06:34 |
|       110 |      19 | 2019-10-20 02:06:31 |
|       111 |      19 | 2019-10-20 02:06:31 |
|       118 |      20 | 2019-10-20 02:06:31 |
|       119 |      20 | 2019-10-20 02:06:33 |
|       137 |      16 | 2019-10-19 02:07:50 |
|       138 |      16 | 2019-10-19 02:07:51 |
|       139 |      12 | 2019-10-21 16:05:57 |
|       139 |      16 | 2019-10-21 16:05:57 |
+-----------+---------+---------------------+
38 rows in set (0.00 sec)
```

```
|        83 |       3 | 2019-10-21 14:44:06 |
|        83 |       3 | 2019-10-21 14:42:06 |
```
Some couple of device_id, rule_id had history of alerts. After maintenance, only the last log is kept.
```
|        83 |       3 | 2019-10-21 14:44:06 |
```

**Comment by louis-oui** [comment]
Could someone test the fix please ?
Tested OK on my setup

**Comment by louis-oui** [comment]
@PipoCanaja ?

**Comment by PipoCanaja** [comment]
Hi @louis-oui 
Looks good to me.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
