### PR TITLE
properly track size based rejections($msefl) for Postfix now

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This depends on https://github.com/librenms/librenms-agent/pull/106 .

### CODE REVIEW

**Comment by murrant** [comment]
I don't like this workaround.    Try adding the stat at the end, it will complain about too many values, but should update the first values.   Perhaps I should try again on my "rrd schema" patch...

**Comment by VVelox** [comment]
@murrant where are you seeing that? The code works fine here.

The only option outside of doing this would be to rewrite it so that the old RRD needs removed.

**Comment by murrant** [comment]
No, I said I don't like adding an extra rrd for one stat.  Then, I suggested an alternative.

**Comment by VVelox** [comment]
close this as it is a bit of a dupe

**Pull request closed without merging**
