### PR TITLE
Added librenms/librenms-agent as subtree into scripts/librenms-agent

### PR DESCRIPTION
**Pull request by f0o**

### CODE REVIEW

**Comment by laf** [comment]
PR itself is fine, no issues. @paulgear if you're happy with this then please merge or comment here and I'll do so.

**Comment by paulgear** [comment]
If we're going to split this off into its own repo (which is mostly for GPLv2 compliance), there's no point in merging it back in as a subtree.  We need to have it in a separate repo and only call it as part of the installation process.

**Comment by f0o** [comment]
So back to submodule and refer to `--recursive` cloning?

**Comment by laf** [comment]
For agent is it even needed to include the agent files seeing as they are mostly going to be installed on separate devices and not the LibreNMS instance?

**Comment by paulgear** [comment]
Good point @laf - people will only need it if they are installing the agent on the LibreNMS server.  Although, they may want it there as a convenient distribution point.  But we could always put something in the installer to say "Download agent (Y/N)?" or similar.

**Comment by f0o** [comment]
Closing this PR, refiling one with the files being removed and a note in the install docs + step in the installer.

**Pull request closed without merging**
