### PR TITLE
cleanup of device page

### PR DESCRIPTION
**Pull request by crcro**
A follow-up on an older "task" to cleanup the UI.

screen shot 2019-02-25 at 12 05 05 am
screen shot 2019-02-25 at 12 04 43 am
screen shot 2019-02-25 at 12 04 32 am
screen shot 2019-02-25 at 12 04 21 am
screen shot 2019-02-25 at 12 04 11 am

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @crcro 
I have a doubt concerning the use of inline styles. Makes it difficult to maintain. @librenms/reviewers , any advices on this ?

**Comment by crcro** [comment]
i will put them into css files at the end

**Comment by crcro** [comment]
screen shot 2019-03-03 at 11 22 42 pm
screen shot 2019-03-03 at 11 22 27 pm
screen shot 2019-03-03 at 11 22 21 pm
screen shot 2019-03-03 at 11 22 15 pm
screen shot 2019-03-03 at 11 22 00 pm
screen shot 2019-03-03 at 11 21 53 pm
screen shot 2019-03-03 at 11 21 42 pm
screen shot 2019-03-03 at 11 21 36 pm

**Comment by murrant** [comment]
@crcro is this still WIP?

**Comment by crcro** [comment]
@murrant ... no

**Comment by laf** [comment]
If you can put the styles into the central stylesheets like @PipoCanaja mentioned.

Do you have before / after screenshots side by side or top/bottom so we can see the diffs as it's hard to see what's changed.

**Comment by murrant** [comment]
Web files have been moved to includes/html, you will need to update your PR, sorry for the trouble. Let us know if you need any help.

**Comment by laf** [comment]
I think you've rebased this wrong, lots of changes which were outside the scope of the PR. Still also got some inline style sheet changes with things like bold. You should be using bootstrap to achieve this.

Last thing, I'd prefer to see effort put into converting the webui over to use Laravel views and react rather than fixing bits of the UI all over the show, if you still want to do that then maybe smaller PRs as it makes it difficult to test so many changes in one go.

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen!

**Pull request closed without merging**
