### PR TITLE
Fix handling of zero value for entSensorThresholdValue for dbm cisco sensor

### PR DESCRIPTION
**Pull request by makriska**
This addresses https://github.com/librenms/librenms/issues/16335

It handles a situation where zero value is returned via entSensorThresholdValue and this is "lost somewhere" so LibreNMS shows blank value in WebUI
The approach to set it to a close enough non-zero value already exists for temperature sensor type.
I just expanded it to cover dbm sensor type.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
* [ ]  If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
A better fix IMHO would be to find why the `0` is lost in the path and fix that. Using `null` for "no value" and `0` for the "0" value would make more sense.

**Comment by makriska** [comment]
Yes, I fully agree that your proposal is the best fix.
I believe someone somewhere already faced the challenge of trying to identify why the zero value is lost and for some reason chose this hacky approach for temperature sensor fix rather than fixing properly as you suggest.

**Comment by PipoCanaja** [comment]
Could you check in your DB when the problem occurs : do you have `0` or `null` in the column ?

**Comment by makriska** [comment]
I have NULL in the database after discovery and the WebUI comes blank for that value
Screenshot 2024-09-01 at 17 19 17


```
MariaDB [librenms]> SELECT * FROM sensors WHERE sensor_class='dbm' AND sensor_descr LIKE 'Subslot 0/0 Transceiver 10%';
+-----------+----------------+--------------+-----------+-------------+------------------------------------+--------------+---------------------+-------------------------------------+-------+----------------+-------------------+----------------+--------------+-------------------+------------------+-----------------------+--------------+---------------+------------------+---------------------------+---------------------+-------------+-----------+----------+
| sensor_id | sensor_deleted | sensor_class | device_id | poller_type | sensor_oid                         | sensor_index | sensor_type         | sensor_descr                        | group | sensor_divisor | sensor_multiplier | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn | sensor_alert | sensor_custom | entPhysicalIndex | entPhysicalIndex_measured | lastupdate          | sensor_prev | user_func | rrd_type |
+-----------+----------------+--------------+-----------+-------------+------------------------------------+--------------+---------------------+-------------------------------------+-------+----------------+-------------------+----------------+--------------+-------------------+------------------+-----------------------+--------------+---------------+------------------+---------------------------+---------------------+-------------+-----------+----------+
|     21529 |              0 | dbm          |       178 | snmp        | .1.3.6.1.4.1.9.9.91.1.1.1.1.4.1218 | 1218         | cisco-entity-sensor | Subslot 0/0 Transceiver 10 Tx Power | NULL  |             10 |                 1 |           -5.7 |         NULL |                -3 |            -13.5 |                  -9.5 |            1 | No            | 1218             | 0                         | 2024-09-01 17:10:11 |        NULL | NULL      | GAUGE    |
|     21530 |              0 | dbm          |       178 | snmp        | .1.3.6.1.4.1.9.9.91.1.1.1.1.4.1219 | 1219         | cisco-entity-sensor | Subslot 0/0 Transceiver 10 Rx Power | NULL  |             10 |                 1 |           -6.6 |            3 |                 0 |              -21 |                   -17 |            1 | No            | 1219             | 0                         | 2024-09-01 17:15:03 |        -6.5 | NULL      | GAUGE    |
+-----------+----------------+--------------+-----------+-------------+------------------------------------+--------------+---------------------+-------------------------------------+-------+----------------+-------------------+----------------+--------------+-------------------+------------------+-----------------------+--------------+---------------+------------------+---------------------------+---------------------+-------------+-----------+----------+
2 rows in set (0.004 sec)

MariaDB [librenms]> 

```

**Comment by PipoCanaja** [comment]
Indeed. So this wrong conversion from `0`to `null` takes place in the discovery code indeed. I don't see where this happens. Could you debug the discovery code (in `includes/discovery/sensors/cisco-entity-sensor.inc.php`) up to the `discover_sensors()` call to check if the call is made with `0`or `null`? I am convinced this issue occurs before the call because I have other devices (other vendors) that have the `0` limit without any issues ...

**Comment by murrant** [comment]
Likely this is an isset/empty issue.

**Comment by makriska** [comment]
I ran the discovery.php module in debug mode for this host
and these were the interesting portions I wanted to share

```
Caching OIDs:  entPhysicalDescrSNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'ENTITY-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'entPhysicalDescr'[0m]
...
entPhysicalDescr.1218 = subslot 0/0 transceiver 10 Tx Power Sensor
entPhysicalDescr.1219 = subslot 0/0 transceiver 10 Rx Power Sensor
...
```
```
 entSensorThresholdValueSNMP['/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OQUs' '-m' 'CISCO-ENTITY-SENSOR-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:HOSTNAME:161' 'entSensorThresholdValue'[0m]
...
entSensorThresholdValue.1218.1 = 0
entSensorThresholdValue.1218.2 = -30
entSensorThresholdValue.1218.3 = -95
entSensorThresholdValue.1218.4 = -135
entSensorThresholdValue.1219.1 = 30
entSensorThresholdValue.1219.2 = 0
entSensorThresholdValue.1219.3 = -170
entSensorThresholdValue.1219.4 = -210
...
```

Thresholds are retrieved properly via SNMP

```
.Discover sensor: .1.3.6.1.4.1.9.9.91.1.1.1.1.4.1218, 1218, cisco-entity-sensor, Subslot 0/0 Transceiver 10 Tx Power, snmp, 10, 1, 1218, -5.7, (limits: LL: -13.5, LW: -9.5, W: -3, H: ), rrd_type = GAUGE  
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= ? AND `sensor_class` = ? AND `device_id` = ? AND sensor_type = ? AND `sensor_index` = ? [0;33m["snmp","dbm",178,"cisco-entity-sensor","1218"][0m 0.11ms] 
  
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = ? AND `device_id` = ? AND `sensor_type` = ? AND `sensor_index` = ? [0;33m["dbm",178,"cisco-entity-sensor","1218"][0m 0.12ms] 
  
.Discover sensor: .1.3.6.1.4.1.9.9.91.1.1.1.1.4.1219, 1219, cisco-entity-sensor, Subslot 0/0 Transceiver 10 Rx Power, snmp, 10, 1, 1219, -6.5, (limits: LL: -21, LW: -17, W: 0, H: 3), rrd_type = GAUGE  
SQL[SELECT COUNT(sensor_id) FROM `sensors` WHERE `poller_type`= ? AND `sensor_class` = ? AND `device_id` = ? AND sensor_type = ? AND `sensor_index` = ? [0;33m["snmp","dbm",178,"cisco-entity-sensor","1219"][0m 0.11ms] 
  
SQL[SELECT * FROM `sensors` WHERE `sensor_class` = ? AND `device_id` = ? AND `sensor_type` = ? AND `sensor_index` = ? [0;33m["dbm",178,"cisco-entity-sensor","1219"][0m 0.12ms] 
...
```

however zero value threshold is blank for H but not W limit:
(limits: LL: -13.5, LW: -9.5, W: -3, **H:** )
(limits: LL: -21, LW: -17, **W: 0**, H: 3)

**Comment by makriska** [comment]
I think this is the code that is causing the issue.


```
                // Check thresholds for this entry (bit dirty, but it works!)
                if (isset($t_oids[$index]) && is_array($t_oids[$index])) {
                    foreach ($t_oids[$index] as $t_index => $key) {
                        // Skip invalid treshold values
                        if ($key['entSensorThresholdValue'] == '-32768') {
                            continue;
                        }
                        // Critical Limit
                        if (($key['entSensorThresholdSeverity'] == 'major' || $key['entSensorThresholdSeverity'] == 'critical') && ($key['entSensorThresholdValue'] != 0) && ($key['entSensorThresholdRelation'] == 'greaterOrEqual' || $key['entSensorThresholdRelation'] == 'gre>
                            $limit = ($key['entSensorThresholdValue'] * $multiplier / $divisor);
                        }

                        if (($key['entSensorThresholdSeverity'] == 'major' || $key['entSensorThresholdSeverity'] == 'critical') && ($key['entSensorThresholdValue'] != 0) && ($key['entSensorThresholdRelation'] == 'lessOrEqual' || $key['entSensorThresholdRelation'] == 'lessTh>
                            $limit_low = ($key['entSensorThresholdValue'] * $multiplier / $divisor);
                        }

                        // Warning Limit
                        if ($key['entSensorThresholdSeverity'] == 'minor' && ($key['entSensorThresholdRelation'] == 'greaterOrEqual' || $key['entSensorThresholdRelation'] == 'greaterThan')) {
                            $warn_limit = ($key['entSensorThresholdValue'] * $multiplier / $divisor);
                        }

                        if ($key['entSensorThresholdSeverity'] == 'minor' && ($key['entSensorThresholdRelation'] == 'lessOrEqual' || $key['entSensorThresholdRelation'] == 'lessThan')) {
                            $warn_limit_low = ($key['entSensorThresholdValue'] * $multiplier / $divisor);
                        }
                    }//end foreach
                }//end if
```

From the investigation do so far, I could see that there is High Ciritical Limit and High Warning Limit returning 0 via SNMP
entSensorThresholdValue.1218.1 = 0
entSensorThresholdValue.1219.2 = 0

High Warning Limit gets populated into DB but High Critical Limit does not
(limits: LL: -13.5, LW: -9.5, W: -3, **H:** )
(limits: LL: -21, LW: -17, **W: 0**, H: 3)

The code above has an extra checks Critical limit

($key['entSensorThresholdValue'] != 0)

**Comment by makriska** [comment]
removing ($key['entSensorThresholdValue'] != 0) from the critical limit if the branch allows LibreNMS to display the zero value threshold in DB and in WebUI

```
MariaDB [librenms]> SELECT * FROM sensors WHERE sensor_class='dbm' AND sensor_descr LIKE 'Subslot 0/0 Transceiver 10%';
+-----------+----------------+--------------+-----------+-------------+------------------------------------+--------------+---------------------+-------------------------------------+-------+----------------+-------------------+----------------+--------------+-------------------+------------------+-----------------------+--------------+---------------+------------------+---------------------------+---------------------+-------------+-----------+----------+
| sensor_id | sensor_deleted | sensor_class | device_id | poller_type | sensor_oid                         | sensor_index | sensor_type         | sensor_descr                        | group | sensor_divisor | sensor_multiplier | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn | sensor_alert | sensor_custom | entPhysicalIndex | entPhysicalIndex_measured | lastupdate          | sensor_prev | user_func | rrd_type |
+-----------+----------------+--------------+-----------+-------------+------------------------------------+--------------+---------------------+-------------------------------------+-------+----------------+-------------------+----------------+--------------+-------------------+------------------+-----------------------+--------------+---------------+------------------+---------------------------+---------------------+-------------+-----------+----------+
|     21801 |              0 | dbm          |       180 | snmp        | .1.3.6.1.4.1.9.9.91.1.1.1.1.4.1218 | 1218         | cisco-entity-sensor | Subslot 0/0 Transceiver 10 Tx Power | NULL  |             10 |                 1 |           -5.7 |            0 |                -3 |            -13.5 |                  -9.5 |            1 | No            | 1218             | 0                         | 2024-09-02 11:35:10 |        NULL | NULL      | GAUGE    |
|     21802 |              0 | dbm          |       180 | snmp        | .1.3.6.1.4.1.9.9.91.1.1.1.1.4.1219 | 1219         | cisco-entity-sensor | Subslot 0/0 Transceiver 10 Rx Power | NULL  |             10 |                 1 |           -6.6 |            3 |                 0 |              -21 |                   -17 |            1 | No            | 1219             | 0                         | 2024-09-02 11:35:10 |        NULL | NULL      | GAUGE    |
+-----------+----------------+--------------+-----------+-------------+------------------------------------+--------------+---------------------+-------------------------------------+-------+----------------+-------------------+----------------+--------------+-------------------+------------------+-----------------------+--------------+---------------+------------------+---------------------------+---------------------+-------------+-----------+----------+
2 rows in set (0.004 sec)

MariaDB [librenms]>
``` 

Screenshot 2024-09-02 at 11 42 06


Though it was there for a reason I assume.
I suspect this change might break other things

**Comment by PipoCanaja** [comment]
LGTM, added a check in case $key['entSensorThresholdValue'] would not be set, just to be safe.

**Review by PipoCanaja — COMMENTED** [review]
Looks good to me

**Comment by PipoCanaja** [comment]
Thanx for your fix, @makriska and welcome in the project !

**Review by PipoCanaja — APPROVED** [review]

**Pull request merged**
