### PR TITLE
Updated network to support old style format, docs provided

### LINKED ISSUE #1461: Is it possible to use the old style interconnect maps?
Is there a way to use the old style interconnection maps vs the elastic maps? The older version was a lot easier to read. The new style tends to bunch up in a ball and when pulled about, snaps back.

### PR DESCRIPTION
**Pull request by laf**
Fix #1461 

You can now set:

$config['gui']['network-map']['style'] = 'old';

To get the old style network map for devices.

### CODE REVIEW

**Comment by laf** [comment]
I can see some scrut duplication issues. I've tried to ensure the formatting of network-map.php is upto standards but as this is an old file I'm not spending anytime to fix anything else. This is just so people who don't like the new network map can go back to the old one.

**Comment by laf** [comment]
bump

**Comment by masonke** [comment]
My apologies, I did not see this. Did you need me to test it?

**Comment by laf** [comment]
Nope, just waiting on it being merged :)

**Comment by f0o** [comment]
I wonder if this requires the old `map.php` from the install-dir.
Generally I'd prefer @paulgear doing this merge, I dont fancy re-including old obs stuff ;)

**Comment by laf** [comment]
I've updated the call to use the new map filename so it doesn't need map.php in html/pages/device/map.inc.php

It's the old file from the fork: https://github.com/librenms/librenms/commits/f836c2b5e3704fe788819234615b03e12e9d70a2/html/map.php

**Pull request merged**
