### PR TITLE
Add global view:

### PR DESCRIPTION
**Pull request by nicearma**
Discovery:
*Search all tables route 
View:
* GLOBAL: route see all the table ip get by the discovery module route
* DEVICE VIEW!: route see all the table ip get by the discovery module route but only for the device selected

### CODE REVIEW

**Comment by laf** [comment]
Thanks @nicearma. Just waiting on scrutinizer to come back with the results then I'll check into this one.

In the meantime, could you do a PR to sign the agreement for code contributions please, see this PR as an example: https://github.com/librenms/librenms/pull/486

**Comment by nicearma** [comment]
Yes i'm trying to separed and i will make other PR, i'm working in the VRF discovery-poller and for last another PR for the visual part, and i will make the PR like #486 to. :)

**Comment by laf** [comment]
All looks good apart from, the sql file, would be better to do this as one line (the second line has an error anyway):

CREATE TABLE IF NOT EXISTS `route` (  `device_id` int(11) NOT NULL,  `ipRouteDest` varchar(256) NOT NULL,  `ipRouteIfIndex` varchar(256) DEFAULT NULL,  `ipRouteMetric` varchar(256) NOT NULL,   `ipRouteNextHop` varchar(256) NOT NULL,  `ipRouteType` varchar(256) NOT NULL,  `ipRouteProto` varchar(256) NOT NULL,  `discoveredAt` int(11) NOT NULL,  `ipRouteMask` varchar(256) NOT NULL, KEY `device` (`device_id`,`ipRouteDest`(255),`ipRouteNextHop`(255))) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by nicearma** [comment]
yes is because i deleted the context_name from the insert and  the alter table but i didn't verify the sql syntax sorry,

**Comment by laf** [comment]
If you're able to fix the SQL then I can get this merged @nicearma

**Comment by nicearma** [comment]
sorry i was sick, i do it now

**Comment by laf** [comment]
Hi @nicearma 

Ok, I've had chance to test this now and unfortunately it doesn't work :( I also merged in the other PR you submitted and it looks like both are needed together (still some issues).

I'm going to try and test against Cisco VIRL shortly to see if the code functions as is and I'll get back to you.

**Comment by nicearma** [comment]
Do you have the error? yes the problem is because i dont have where to test my code

**Comment by laf** [comment]
Sorry for the delay @nicearma, no errors as such just things like the wrong pages being included for the route overview and I think some items relying on both PRs.

We've got a Nexus 7k setup on Cisco VIRL, just waiting on spinning up a Linux vm to fully test your patch at the moment. I can provide you access to this if you like so you can see what's going on?

**Comment by f0o** [comment]
So what's up with this PR?
It's been idle for long long time now and requires another rebasing again.
Close It? Keep Open?

**Comment by f0o** [comment]
Proposing close in 24h

**Comment by laf** [comment]
Same again

**Pull request closed without merging**
