### PR TITLE
Updated rrdtool_update() to use new array format

### PR DESCRIPTION
**Pull request by laf**
This is in preparation for moving to other backends than rrd.

Basically we now use only an array for the values being passed to rrdtool_update so we can then pass the same array to other functions. This new array includes key names as well as values so that we can use the keys as well.

It shouldn't affect the way anything currently works assuming I've made no mistakes :)

The first push of this is to kick off a scrut and CI run so I can see if anything needs fixing.

### CODE REVIEW

**Comment by laf** [comment]
Tagging @paulgear @f0o and @Rosiak for quick feedback. I'm going to be working on the next backend support using this as a base so I'd like to hear back sooner rather than later if this isn't how anyone thinks we should do it.

**Comment by f0o** [comment]
Good approach should continue in that direction :+1:

**Comment by paulgear** [comment]
I think syntactically some of it is a bit yucky, but that's fairly minor; +1 from me for getting it ready to support other backends.

**Comment by laf** [comment]
@paulgear What would you like to see updating?

**Comment by paulgear** [comment]
@laf, just as an example, the changes to includes/polling/applications/bind.inc.php and includes/polling/applications/drbd.inc.php would be much better done as loops.  But that's pretty minor.

**Comment by paulgear** [comment]
Scrutinizer has some issues which look worthwhile addressing as well.

**Comment by f0o** [comment]
trigger ci

**Comment by laf** [comment]
trigger ci

**Comment by f0o** [comment]
trigger ci

**Comment by Rosiak** [comment]
:+1: 
Tested, works fine on my dev install.

**Comment by laf** [comment]
bump

**Comment by f0o** [comment]
trigger ci

**Pull request merged**
