### PR TITLE
Add custom Field to Jira Payload

### PR DESCRIPTION
**Pull request by LoveSkylark**
Allmost every Jira setup is diffenerent and requires customise information to be added to the API post.

This change will allow you add a custom fields to the '"fields": {   }' using json format.
Examples: are provided in the TransportUI

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Having fixed data per transport is useful?
Don't wrap {} around the json, it is confusing.

**Comment by LoveSkylark** [comment]
> Having fixed data per transport is useful? Don't wrap {} around the json, it is confusing.

I thought I was being security savy by stripping {} I was limiting the content to stay inside this one filed :)

This is how it looks to the user:
image

**Comment by murrant** [comment]
Accept valid json.  If you want to validate the structure, do so in the code.

**Comment by LoveSkylark** [comment]
Working on adding webhooks as well will finish that and re-submit with valid json

**Pull request closed without merging**
