### PR TITLE
Better Support of Alcatel Switches

### PR DESCRIPTION
**Pull request by joseUPV**
From Issue #10116
Includes PR #10655
Includes PR #10659

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
This PR includes #10659 because it uses same file for model detection
This PR includes #10655 because for it uses same file for FAN discovery
Added Model, Processor, Fan State and Power Supply State of Alcatel OmniStack LS Switches that uses RADLAN mibs.
I couldn't get mempool data, becuause i did'nt find nothing in mibs.
It's not included POE State data, because it is global state of the switch, not the ports.

**Comment by joseUPV** [comment]
Included support of Alcatel Enterprise Fan Speed Sensor.
Included Mibs for Alcatel Enterprise AOS7+ Switches in nokia/aos7

**Comment by joseUPV** [comment]
For all Alcatel Family:
- Added graphs of CPU Usage and Temperature
For Alcatel Enterprise with AOS7+ (.1.3.6.1.4.1.6486.801.):
- Added hardware and version detection
- Added Fan Speed sensor of all chassis
- Added temperature sensor of first chassis
- Added mempools ¿of first chassis?
For Alcatel OmniSwitch (.1.3.6.1.4.1.6486.800.1.1.2.1.):
- Added Fan Status (for ex. 3 fans in 6350, 2 in 6400)
- Added hardware and version detection for 6400 family
For Alcatel OmniStack LS (.1.3.6.1.4.1.6486.800.1.1.2.2.4.):
- Added hardware and version detection
- Added Fan Status
- Added temperature sensor of first chassis
- Added Power Supply Status

**Comment by joseUPV** [comment]
Added Tests for aos family:
- aos6 variant for OmniSwitch Switches (.1.3.6.1.4.1.6486.800.1.1.2.1.)
- aos7 variant for Enterprise AOS7 Ominiswitch Switches (.1.3.6.1.4.1.6486.801.)
- ls variant for Omnistack LS Switches (.1.3.6.1.4.1.6486.800.1.1.2.2.4.)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-57-release-changelog-october-2019/9969/1

**Pull request merged**
