### PR TITLE
BGP API: Add filter by remote ASN

### PR DESCRIPTION
**Pull request by kedare**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kedare** [comment]
Testing it locally, I let you know if everything is fine

**Comment by kedare** [comment]
Fixed typo and force-pushed

**Comment by kedare** [comment]
Fixed sql concat on this API endpoint, working as expected now :)

**Comment by kedare** [comment]
The failing CI test looks related to something else ?

**Comment by PipoCanaja** [comment]
You are right, this is a side effect of another merge. But it must be fixed cause it is blocking the merge now. 
Could you add it in "mkdocs.yml" , just after `      - Logs: API/Logs.md`?
`      - Logs: API/Locations.md`

**Comment by kedare** [comment]
Done

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
