### PR TITLE
Fix nav icons

### PR DESCRIPTION
**Pull request by benwa**
Removes notification overlap and fixes mobile navigation view.

It's more vanilla Bootstrap, but the benefit is it works as expected on all breakpoints.

### CODE REVIEW

**Comment by laf** [comment]
This removes the colour indication showing you have messages so is now always grey. I'm not a fan of that.

Not sure I really like it being next to the user icon either, I realise having just checked that it looks worse on a mobile but maybe we just fix that?

**Comment by benwa** [comment]
Ah you're totally right about the color, I don't like that either.  I believe the mobile part can also be fixed with a media query for smaller breakpoints.  I'll see if I can correct that.




On a separate note, are you guys considering moving to SASS in the future and possibly Bootstrap 4 (when it comes out)?

**Comment by laf** [comment]
What's the score with this one @benwa?

As for SASS, we'd certainly consider it. Not sure any of the current @librenms/reviewers have experience in it so someone would need to kick start the process.

**Comment by benwa** [comment]
Still looking in on it, trying to make it work and run right without being hacky

**Comment by murrant** [comment]
@benwa I ha e a feeling you might be interested in https://github.com/librenms/librenmsv2.  I definitely want to use bootstrap4 there.  I think our adminlte template is already partially ported to bootstrap4.  As for sass, I only have a rough idea what it would be used for,. I'm not really a front-end guy :-).

**Comment by laf** [comment]
A lot better, thanks :)

**Pull request merged**
