### PR TITLE
port_error_perc macro

### PR DESCRIPTION
**Pull request by electrocret**
Adding macro for percent of packets are erroring.

This will allow for a standardized/scalable error metric that can be applied to ports no matter what the speed.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by electrocret** [comment]
The query appears to be correct, however the query builder isn't offering a decimal comparison like port_usage_perc does. Suggestions @murrant ?

**Comment by murrant** [comment]
I would probably sum the two for this calculation.

**Comment by electrocret** [comment]
Alrighty, I put the macros in correctly now (I hope).

They're still showing up as No/Yes instead of allowing me to do a numeric comparison.
image

**Comment by laf** [comment]
@electrocret have you tried:

```
    "port_out_error_perc": "((%ports.ifOutErrors_rate) \/ %ports.ifOutUcastPkts_rate)*100",
    "port_in_error_perc": "((%ports.ifInErrors_rate) \/ %ports.ifInUcastPkts_rate)*100",
```

**Comment by electrocret** [comment]
@laf no change. :(

**Comment by murrant** [comment]
@electrocret somewhere in php filter builder for the js editor there is some code that makes specific macros not yes/no.

**Comment by electrocret** [comment]
Found it https://github.com/librenms/librenms/blob/b655eb7feb3412bf5e46137991bec7e951864bae/LibreNMS/Alerting/QueryBuilderFilter.php#L73C1-L73C1

**Comment by murrant** [comment]
Or rename the macros :)

**Comment by electrocret** [comment]
Just tested, and that did it.
image

Heh, I'm not sure if you meant rename my macros, or rename all macros. My macros wouldn't make sense with '_usage_perc' at the end. However all macros that are comparing a percentage would make sense with '_perc' at the end.

**Comment by electrocret** [comment]
A little poking around in the code, and it looks like all of the macros that use an integer are percentages. So we could hypothetically rename the 'packet_loss_XXm' macros to 'packet_loss_XXm_perc', and remove the startswith test. That'd make identifying which is an integer macro alot cleaner. Let me know if you'd like me to make a PR to accomplish that.

**Comment by electrocret** [comment]
@murrant and @laf . Bump?

Been using this personally for quite a bit with no issue.

**Review by murrant — APPROVED** [review]

**Pull request merged**
