### PR TITLE
Update defaults.inc.php

### PR DESCRIPTION
**Pull request by mzac**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by murrant** [comment]
Needs rebase to fix travis-ci build, thanks.

**Comment by murrant** [comment]
I can't find where `$config['int_all_ports']` is used? did you forget to include some code?

**Comment by mzac** [comment]
Murrant, sorry the rest of the code is in 4313, this was the first time I did a pull request on github so I was a little lost on what I was doing :)

**Comment by murrant** [comment]
No worries, you can add this change to #4313 .

http://docs.librenms.org/Developing/Using-Git/  might help you out a bit.  If you have any questions, irc is a good place to ask.

**Comment by mzac** [comment]
Look at pagination as an alternative

**Pull request closed without merging**
