### PR TITLE
webui: Update Font Awesome to 4.7.0

### PR DESCRIPTION
**Pull request by Rosiak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Are we duplicating files here? Before FA was loaded into lib/ which seems to the case still but all the symlinks from html/* back to lib/fa/* are now replaced with the full files as well.

**Comment by InsaneSplash** [comment]
Do we not just need the 2 CSS files, or do you require the whole package to be part of the repo?

**Comment by Rosiak** [comment]
We briefly had a discussion on IRC regarding this earlier today.
Should we remove the lib completely and just keep the necessary files?

**Comment by InsaneSplash** [comment]
I'd say why include stuff that's not required...it would de-bloat the installation and reduce its size a little if the whole package wasn't included. Also make for easier updating in the future.

**Comment by laf** [comment]
Remove.

**Pull request merged**
