### PR TITLE
feature: Added script to test alerts

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Added a cli script to force send an alert. The alert must be currently active but this gives you a forced cli approach to being able to debug.

### CODE REVIEW

**Comment by murrant** [comment]
Trying to test this in my dev box, which may not have alerting properly set up.

When running the script `./scripts/test-alert.php -r 1 -h 1` I get no output.

**Comment by laf** [comment]
It needs to be an active alert that is triggering right now.

**Comment by murrant** [comment]
Oh, I probably should have read the docs first :)

I made a quick change, seem reasonable?

**Comment by laf** [comment]
Perfectly :)

**Pull request merged**
