### PR TITLE
Added detction for OSX El Capitan

### LINKED ISSUE #3017: Mac OSX
LibreNMS is not sorting OSX El Capitan (10.11.3) as an Apple icon. 

Darwin Sulla.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
Operating System	Generic Device
Object ID	enterprises.8072.3.2.255

### PR DESCRIPTION
**Pull request by laf**
Fix #3017

### CODE REVIEW

**Comment by Rosiak** [comment]
Pretty sure 1.3.6.1.4.1.8072.3.2.255 is a generic one, at least it was when I was looking last time.
Think we should use the sysDescr instead.

**Comment by laf** [comment]
Updated

**Comment by Rosiak** [comment]
Sorry to bother again, but why not strstr?

**Comment by laf** [comment]
Taken from another file, feel free to submit your own pr if you want strstr.

**Comment by Rosiak** [comment]
meh.

**Pull request merged**
