### PR TITLE
option to turn off icmp check for polling while fast-ping check is implemented

### PR DESCRIPTION
**Pull request by DR3EVR8u8c**
While the Fast-Ping Check feature has been implemented, the default ping check during polling is not helpful. And the default ping sometimes cause small gap in the graph due to the fping failure.
Due to the reason above, I would like to add an option to turn off the icmp check in polling while do not stop the fast-ping check.
Thanks and regards,
Roger

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by DR3EVR8u8c** [comment]
don't know why this PR including some past commits from @laf and @murrant. I expected that the PR only includes my last 2 changes. Please let me know if you want me to close this PR and create new one.

**Comment by murrant** [comment]
Seems fine in the diff.

By the way you understand that these two ping checks are not interchangeable.  You will have less data by only using ping.php.

**Comment by DR3EVR8u8c** [comment]
@murrant , May I know what data will be missing if use ping.php only?

**Comment by DR3EVR8u8c** [comment]
Sorry @murrant, I may make mistake. initially I assumed that the config['icmp_check']=false will stop all pings including fast-ping. but that seems not the case. if so, then the option may be not required. I will close the PR now.

**Comment by murrant** [comment]
@DR3EVR8u8c The performance tab data is not populated by ping.php.  ping.php sends 1 ping (if successful), the poller sends a minimum of 3 pings (by default) so it can get average latency, etc.

**Pull request closed without merging**
