### PR TITLE
Copy and modify the syslog transport for sending alerts to Splunk in an easy to parse format

### PR DESCRIPTION
**Pull request by VirTechSystems**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @VirTechSystems 
Could you please provide the documentation along with this PR so we can review it with all the details needed. 
Thanx

**Comment by SourceDoctor** [comment]
@VirTechSystems 
is existing Syslog Transport incompatible for splunk?
default Port in your Code is the same

**Comment by VirTechSystems** [comment]
Splunk lets you use any tcp/udp port you want as an input.  I figured the syslog port was a good default, but I can make it anything.  I'm using something in the 7000 range.

And the syslog format isn't really incompatible.  The amount and format of the data I'm sending is more useful and natural for parsing and exploring the data like Splunk does.

**Comment by SourceDoctor** [comment]
@librenms/reviewers someone uses Splunk so Alert Transport can be tested?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
