### PR TITLE
Various UI changes

### PR DESCRIPTION
**Pull request by arjitc**
Changed to panel like UI 
Screenshot: 
1. http://i.imgur.com/QOpQjlt.png
2. http://i.imgur.com/dd1rafq.png
3. http://i.imgur.com/EiouFCV.png

Few other misc fixes to the UI here and there :)

### CODE REVIEW

**Comment by Rosiak** [comment]
Hrmm, need a few other opinions on this. 
@laf @f0o @paulgear

**Comment by f0o** [comment]
trigger ci

**Comment by f0o** [comment]
Blocker: Please dont file pull-requests from your master branch.
Consult http://docs.librenms.org/Developing/Using-Git/#workflow-guide

**Comment by arjitc** [comment]
Closing this PR and re-trying it with/on a new one.

**Pull request closed without merging**
