### PR TITLE
Optional automatic sensor limits

### PR DESCRIPTION
**Pull request by amigne**
When a device does not give sensor limit values, LibreNMS automatically sets limits, based on the current value measured during the first discovery.

In environments where equipments providing such limit information and others that don't are mixed, it is impossible to determine at first if the limit value is provided by the vendor or by the tool.

In cases where the LibreNMS administrator would trust the vendor values (for instance, to generate alerts) and prefer have no values set at all when the vendor does not return any (these values can be manually set, if needed), a new configuration parameter can be set. If this parameter is true (default value), the discoverer will determine an automatic value; if the parameter is false, LibreNMS does not determine any automatic value when the device does not provide any.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
The name of the config variable doesn't feel quite right.  How about `sensors.guess_limits`?

**Comment by TheGreatDoc** [comment]
Do you mind also documenting this new option in https://docs.librenms.org/Support/Configuration/ ?

**Comment by amigne** [comment]
> Do you mind also documenting this new option in https://docs.librenms.org/Support/Configuration/ ?

@TheGreatDoc I'll do it with the update of my PR.

**Comment by PipoCanaja** [comment]
I guess you can remove the WIP tag in the title to get this merged.

**Comment by murrant** [comment]
@amigne naming might be trivial, but it is the only thing we can't fix trivially ;)

**Pull request merged**
