### PR TITLE
Added transport for Pushover alerting

### PR DESCRIPTION
**Pull request by neokjames**
Added support for Pushover alerts using Pushover's API

Updated documentation to include how to configure it

Added myself to Authors list

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR @neokjames :)

Couple of things before we can merge this.

1. You've put your copyright notice at the top, as this is based on @f0o's code then you will need to include his copyright notice. You can still add yours but you also need to keep the original.

2. If possible, can you squash down some of these commits. 24 is a bit excessive :) http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by neokjames** [comment]
1. It was, but it has been modified to be nothing like any of his transports now, but I've added his copyright notice anyway.

2. I have squashed them, do I need to do another PR? It doesn't seem to have come across to the PR.

**Comment by laf** [comment]
Thanks for updating :)

On 1. I realise quite a bit is different but it's basically derived from f0os work. He'll possibly pick this pr up later anyway as I'm heading to bed now. He might not be bothered about it. 

2. You need to git push again but most likely force it. Just add a + infront of the branch name. Eg git push origin +branchname

**Comment by neokjames** [comment]
All good, I've successfully squashed it, give it a quick review now and feel free to merge. :)

**Pull request merged**
