### PR TITLE
Improve netgear tests

### PR DESCRIPTION
**Pull request by murrant**
Currently this detects Switches, APs, Routers and ReadyNAS devices.
netgear os has little more than an icon and a poor attempt at platform info.
I'm not 100% sure what to do with this, but I do know they have different MIBS.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
Why not just leave it alone until we have the data to add the other specific OS' either from stats or a request from a user?

**Comment by laf** [comment]
bump @murrant

**Comment by murrant** [comment]
We can leave it alone.  I didn't add those other os's because I didn't take the time to research what MIBs, etc Netgear has... and what devices support them.

**Comment by laf** [comment]
Mind if we close then?

**Pull request closed without merging**
