### PR TITLE
Fix Device Mouseover View

### PR DESCRIPTION
**Pull request by SourceDoctor**
Blade/Laravel Code shows on mouseover on a device_Link always 'default' OS.
This Fix repairs config, to show correct OS mouseover View on device_Link.

For better seeing what is meant:
take a mouseover in Dashboard Eventlog on a Server, a Switch and maybe others too.
Now go into Overview->Map->Network and do a mouseover on same Devices to see how it should be.

That's what this PR repairing :-)

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
@kkrumm1 
could you take a look on Travis Failures, please?
I'm a little bit confused about what to do.
thx :-)

**Comment by kkrumm1** [comment]
> @kkrumm1
> could you take a look on Travis Failures, please?
> I'm a little bit confused about what to do.
> thx :-)

Hi did you look in here https://travis-ci.com/librenms/librenms/builds/141728784

**Comment by SourceDoctor** [comment]
@kkrumm1
yes that's what i mean

**Comment by PipoCanaja** [comment]
I tried to force the tests to re-run but it seems that one way or the other, this PR makes travis do something wrong ... And I have no clue so far on how to troubleshoot that kind of issue.

**Comment by PipoCanaja** [comment]
Hi @SourceDoctor 
The fix is not at the right spot here. And that's why Travis is complaining during the test. The DB is not yet initialized when this Config code is called the 1st time, resulting in this test failure. 
You should relocate this code in a later stage during the build of a page. The loadAllOs function could end up aside of the loadOs function, in the ./app/Models/Device.php file.

**Comment by SourceDoctor** [comment]
@PipoCanaja 
ok i moved it to app/Models/Device.php, As you can see, Travis is also crashing.
Now what to do?
For my intention netherless it should be loaded with Config, because it loads all OS specific settings.
Also after this it's in cache for later use.
Some ideas?

**Comment by SourceDoctor** [comment]
@PipoCanaja 
moved to Device Class constructor.
Works now, and without crashing Travis :-)

**Comment by PipoCanaja** [comment]
@SourceDoctor 
It crashes my prod server :) so there is something wrong. If I force         $existing = false; then it goes correct. According to the logs, the issue is in app/Models/Device.php line 231 , array to string conversion. Don't get what's wrong so far. And I don't know if my setup causing this or if the issue is more global.

**Comment by PipoCanaja** [comment]
It could be the "Top Interfaces" that appears to be broken now. And I don't have it on my test machines. Will check.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
