### PR TITLE
Update settings.php translation string

### PR DESCRIPTION
**Pull request by jasoncheng7115**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @jasoncheng7115 
Could you please run 
```
/lnms translation:generate 
```
to re-generate the translation files ? 
Thanx

**Comment by jasoncheng7115** [comment]
> Hi @jasoncheng7115
> Could you please run
> `./lnms translation:generate`
> to re-generate the translation files ?
> Thanx

Executed, is it for this file?
 /opt/librenms/resources/js/vue-i18n-locales.generated.js

thanks.

**Comment by PipoCanaja** [comment]
Just update the PR with all changed files after this command.

**Comment by josephtingiris** [comment]
> Just update the PR with all changed files after this command. This one is clearly one of them.

They wont show up in the repo because `lnms translation:generate` generates javascripts that are ignored by `/opt/librenms/html/js/lang/.gitignore`

I've been trying to explain that over here, too https://github.com/librenms/librenms/pull/11020#issuecomment-586636080

**Comment by josephtingiris** [comment]
I've applied this as a patch and, with #11020 dailiy.sh running `lnms translation:generate`, these translations are working.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
