### PR TITLE
Added support for Ruijie Networks

### PR DESCRIPTION
**Pull request by spencerbutler**
fixes:
https://github.com/librenms/librenms/issues/8021

@hanserasmus Can you give this a try? If so, please submit a new discover, poller, and snmpwalk so I can add sensors and whatever else is missing.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by hanserasmus** [comment]
Hi @spencerbutler Thank you SO much for working on this.

Herewith the three links to pastebin. I will keep my LibreNMS running on this device and see what happens. I will also test on another Ruijie model to see how it behaves.

```
System description      : Ruijie 10G Routing Switch(S6220-48XS4QXS) By Ruijie Networks
System start time       : 2019-02-23 11:1:2
System uptime           : 30:22:28:48
System hardware version : 1.17
System software version : RGOS 10.4(5b2)p2 Release(182500)
System BOOT version     : 10.4(5b2)p2 Release(182500)
```
[Discovery](https://p.libren.ms/view/0a541c3c)
[Poller](https://p.libren.ms/view/9706fd2f)
[SNMPbulkwalk](https://p.libren.ms/view/c76eca34)

Does this help at all?

Thank you again!

**Comment by hanserasmus** [comment]
Here is the output for a Ruijie 5750.

```
System description      : Ruijie 10G Routing Switch(S5750-24SFP/8GT-E) By Ruijie Networks
System start time       : 2017-07-21 5:53:52
System uptime           : 613:12:26:52
System hardware version : 1.06
System software version : RGOS 10.4(3b16)p2 Release(178747)
System BOOT version     : 10.4(3b16)p2 Release(178747)
System CTRL version     : 10.4(3b16)p2 Release(178747)
```
[Discovery](https://p.libren.ms/view/4b2c0175)
[Poller](https://p.libren.ms/view/b9323cd4)
[SNMPbulkwalk](https://p.libren.ms/view/319ad55a)

When running SNMPBulkwalk I still get this error

```
Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.973403460.21.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.8487.26.1

Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.973403460.21.1
 >= .1.0.8802.1.1.2.1.4.1.1.4.559905836.27.1
```

**Comment by spencerbutler** [comment]
> ```
> Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.973403460.21.1
>  >= .1.0.8802.1.1.2.1.4.1.1.4.8487.26.1
> 
> Error: OID not increasing: .1.0.8802.1.1.2.1.4.1.1.4.973403460.21.1
>  >= .1.0.8802.1.1.2.1.4.1.1.4.559905836.27.1

I believe this is because of the old MIBs that are in use. Your particular model isn't listed in the PRODUCT-MIB. If you can contact the vendor and obtain current MIBs for these, it would greatly help the support LibrenNMS can provide.

**Comment by hanserasmus** [comment]
I have sent through the request, so now we hold our breaths to see if they are willing to help. Thank you for the help here!

**Comment by PipoCanaja** [comment]
@spencerbutler You can either put this in WIP or decide to merge this and come back to it later if new MIBs become available. Let me know.

**Comment by spencerbutler** [comment]
> @spencerbutler You can either put this in WIP or decide to merge this and come back to it later if new MIBs become available. Let me know.

Let's merge it in. I'll pick it back up if we get some newer/working MIB files.

**Comment by PipoCanaja** [comment]
I extended to all the RUIJIE products (according to MIB) which includes Switches, Routers and Wireless. The logo and default device discovery will be there.

**Pull request merged**
