### PR TITLE
Increase minimum version to PHP 8.1

### PR DESCRIPTION
**Pull request by murrant**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by Jellyfrog — DISMISSED** [review]

**Comment by Jellyfrog** [comment]
Need to create php73 branch
And post some rss news + forum maybe?

**Comment by murrant** [comment]
Branch is already created.  No posts yet.

**Comment by murrant** [comment]
Post here: https://community.librenms.org/t/php-minimum-version-raised-to-php-8-1/19686

Change it to listed if you merge this.  Feel free to edit it.

**Comment by SourceDoctor** [comment]
@murrant 
is this increasement really needed?
Debian Bullseye (the actual stable release) still has PHP Version 7.4

**Comment by murrant** [comment]
PHP 7.4 will be unsupported in about 2 months.  The install docs cover Debian 11:  https://docs.librenms.org/Installation/Install-LibreNMS

**Pull request merged**
