### PR TITLE
Added support for DGD and BER on newer infinera-groove FW

### PR DESCRIPTION
**Pull request by bergroth**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @bergroth 
Thanx for your PR. Could you check Travis results and correct the test-data after your changes ? 
Thanx

**Comment by bergroth** [comment]
Should look better now

**Comment by PipoCanaja** [comment]
Looks good to me.

**Comment by PipoCanaja** [comment]
Thanx @bergroth !

**Pull request merged**
