### PR TITLE
Add more interface types to bad_iftype array in config_definitions.json

### PR DESCRIPTION
**Pull request by pepperoni-pi**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Actually, we are looking to eliminate all the default entries for this setting.
Instead they should be added to the OS that needs them.

**Comment by pepperoni-pi** [comment]
LibreNMS by default will discover a bunch of "Uncontrolled" and "Controlled" interfaces which do not seem to be useful in any way so I have currently just added them to the array via my config.php, but since they seem to not be useful at all I figured I should just get them added to the config_definitions.json bad_iftype array.

**Comment by murrant** [comment]
The problem is that this applies to ALL OS and it is hard to remove them from the global ignore array defaults.  Please just add them to the OS definition that has the interfaces.  Thanks.

**Comment by PipoCanaja** [comment]
> LibreNMS by default will discover a bunch of "Uncontrolled" and "Controlled" interfaces which do not seem to be useful in any way so I have currently just added them to the array via my config.php, but since they seem to not be useful at all I figured I should just get them added to the config_definitions.json bad_iftype array.

Hi @pepperoni-pi 
You can use this file as a model on how to add these directly to the OS concerned : 
```
librenms@librenms:~/includes/definitions$ cat nokia-isam.yaml
os: nokia-isam
text: 'NOKIA ISAM'
type: network
icon: nokia
group: nokia
bad_ifXEntry:
    - NFXS-E
over:
    - { graph: device_bits, text: 'Device Traffic' }
    - { graph: device_processor, text: 'CPU Usage' }
    - { graph: device_mempool, text: 'Memory Usage' }
discovery:
    -
      sysObjectID:
        - .1.3.6.1.4.1.637.61
mib_dir:
    - nokia
bad_iftype:
    - aluGponOnu
    - bridge
    - ieee8023adLag
    - l2vlan
    - slip
    - softwareLoopback
```

**Comment by pepperoni-pi** [comment]
Sweet! Thanks guys. I'll close this request and create a new one after I do some testing.

**Pull request closed without merging**
