### PR TITLE
Cisco C9800 Wireless Controller AP Count Support

### PR DESCRIPTION
**Pull request by jayceeemperador**
Add AP count support for C9800.
Update Cisco MIBs to gather AP count and AP maximum count.
Provide test data from C9800s

Update: Will use the existing Iosxe OS to detect C9800s.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
What is the difference between this and the ciscowlc  OS?

**Comment by jayceeemperador** [comment]
> What is the difference between this and the ciscowlc OS?

In the System Description:
CiscoWLC OS:          **Cisco WLC** 8.5.140.0
Cisco IOS-XE WLC:   **Cisco IOS-XE** C9800_IOSXE-K9 17.9.4 (Cupertino)             /it matches the Iosxe OS, which is a network type

Cisco IOS-XE WLC needs to get the AP count ap AP radio data from the updated CISCO-LWAPP-TC-MIB and CISCO-LWAPP-AP-MIB

**Comment by murrant** [comment]
So one is IOS-XE based and the other is its own specific OS?

I note that Ciscowlc does use the CISCO-LWAPP-SYS-MIB MIB.  So I'm still confused a bit how it all fits together. (Keep in mind I have no knowledge of Cisco WLC or WLC like devices)

**Comment by jayceeemperador** [comment]
> So one is IOS-XE based and the other is its own specific OS?
> 
> I note that Ciscowlc does use the CISCO-LWAPP-SYS-MIB MIB. So I'm still confused a bit how it all fits together. (Keep in mind I have no knowledge of Cisco WLC or WLC like devices)

Yes, IOS-XE based for the latest Cisco Catalyst WLC (C9800)

The AireOS (own specific OS) is the old generation OS for old Cisco AireOS WLC (3504/2504/5508) which in the near future will have no more hardware/software support

https://blogs.cisco.com/networking/after-15-years-cisco-wireless-aireos-controllers-are-going-away

**Comment by murrant** [comment]
The article highlights why this should not be a separate OS.   The WLC package can be installed on any IOS-XE device.

**Comment by jayceeemperador** [comment]
> The article highlights why this should not be a separate OS. The WLC package can be installed on any IOS-XE device.

The disadvantage that I forseen is that when merging the iosxe and iosxewlc, There will be no immediate Number of clients and Number of APs wireless graphs display for C9800 devices and it will be universal 'network' type.

https://community.librenms.org/t/cisco-cl9800-wireless-controller-support/14357

I'm goods in the merge, since the AP count is the initial intention, I recently recall that a Cisco Catalyst switch can also be a Wireless controller but didn't see/configure it actual.

Will I proceed with my PR edit (merge)?

**Comment by murrant** [comment]
@jayceeemperador after a bit of looking, it looks like you are just reverting this change #13563

Because the wireless code here is run in polling with no discovery checks, it slows down a lot of devices.
Maybe we can add check to make sure the polling code doesn't run all the time, only when a WLC is present.

Delete the pollOS() here and make changes in Ciscowlc.  (It would be much easier to solve this if there was a wireless controller module like the code mentions...)

**Comment by PipoCanaja** [comment]
rerun tests

**Comment by jayceeemperador** [comment]
> @jayceeemperador after a bit of looking, it looks like you are just reverting this change #13563
> 
> Because the wireless code here is run in polling with no discovery checks, it slows down a lot of devices. Maybe we can add check to make sure the polling code doesn't run all the time, only when a WLC is present.
> 
> Delete the pollOS() here and make changes in Ciscowlc. (It would be much easier to solve this if there was a wireless controller module like the code mentions...)

Thanks for the code logic information, will continue on the PR change.

**Comment by LoveSkylark** [comment]
So if I'm understanding this correctly we finally have a way to count APs on C9800.

C9800 is IOSXE based but we need a new OS templates because we don't want start putting up empty AP count graphs on regular cisco switches, and we can't use the old AireOS because that is a completely different OS?

**Comment by PipoCanaja** [comment]
> C9800 is IOSXE based but we need a new OS templates because we don't want start putting up empty AP count graphs on regular cisco switches, and we can't use the old AireOS because that is a completely different OS?

It is a little bit more complicated. The Wireless code that runs on the C9800 runs on other C9x00 switches as well that have the WLC capability. Catalyst 9300, Catalyst 9100 (which are AP with WLC capability as far as I understand), etc etc. 
And all of these are IOSXE based. 

So the only way is to extend IOSXE OS in LibreNMS to support these, but only do the polling if the discovery finds any Wireless counters in the device. This ensures that no WLC enabled devices are left behind.

**Comment by haffi78** [comment]
I think we still should have per template , on dico you can find if its wlc or not.

**Comment by murrant** [comment]
OS proliferation is catastrophic for LibreNMS and causes a lot of user and developer pain, so we need to avoid that at as much as possible.
A lot of people think different hardware = different device.  This is not the case.  LibreNMS would benefit for things like "type" and overview graphs being made a little more dynamic.

**Comment by murrant** [comment]
Try this.

Also, can you please update iosxe_c9800.snmprec to contain more data with `./scripts/collect-snmp-data.php -h <hostname>`  so we can add real tests for this.   The current one is missing and relevant oids. (Make sure to sanitize data without breaking it)

**Comment by jayceeemperador** [comment]
> Try this.
> 
> Also, can you please update iosxe_c9800.snmprec to contain more data with `./scripts/collect-snmp-data.php -h <hostname>` so we can add real tests for this. The current one is missing and relevant oids. (Make sure to sanitize data without breaking it)

Hi @murrant, I have updated the iosxe_c9800.snmprec. I apologize if its not sanitized well but was able to convert private data to <private>

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
@jayceeemperador no worries, just making sure you don't post something you shouldn't publicly.  This LGTM now :)

**Comment by jayceeemperador** [comment]
Hi @murrant, thank you for the approval. 

I would like to know how did you converted the snmprec to json? Or is it the snmpsim?

Thanks

**Comment by PipoCanaja** [comment]
> Hi @murrant, thank you for the approval.
> 
> I would like to know how did you converted the snmprec to json? Or is it the snmpsim?
> 
> Thanks

Hi @jayceeemperador 
The commande is `save-test-data.php`. 

https://docs.librenms.org/Developing/os/Test-Units/

Bye

**Pull request merged**
