### PR TITLE
Fix syslog widget priority filtering

### PR DESCRIPTION
**Pull request by murrant**
syslog stores priority as a string
filter strings, not numbers

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Talkabout** [comment]
Hi @murrant ,

for me the priority filtering is not working any more. In your commit the filter column is still "level" which stores a number, not a string. Only the "priority" column might contain a string, but only if the template part for "syslogpriority" for rsyslog (which I am using) is changed to "syslogpriority-text". From my point of view filtering for numbers is much faster than strings. What is your opinion on this?

**Comment by Talkabout** [comment]
@murrant , Can be easily fixed by doing this:

image

Is this a valid solution for you?

**Comment by murrant** [comment]
@Talkabout AHA, my sample data only contains strings.   We are breaking 1 of 2 groups of people everytime we fix this :D

The only proper fix is to search for the string or the number.

**Comment by murrant** [comment]
Speaking of @Talkabout, Do you know why there is priority and level?  Do they contain the same values? Is one supposed to be numeric?

**Comment by Talkabout** [comment]
Hi @murrant ,

I think it depends on the configuration of the log facility you are using. The rsyslog template I am using is storing numbers for both, priority and level, but this can be easily changed. I tried that also already but the strings that are getting stored are different from the strings that you are using inside your level array. So it not only seems to be a problem whether string/number, but also what kind of string. That is why I think chosing numbers is the best way to go, but I have suggested a solution in the other thread that might allow to handle both cases.

**Comment by murrant** [comment]
So, what are the levels as stored by your rsyslogd?

**Comment by Talkabout** [comment]
rsyslog stores "error", "warning", "notice", "critical" if I use "syslogpriority-text" instead of "syslogpriority" as described here:

https://docs.librenms.org/Extensions/Syslog/#rsyslog

**Comment by murrant** [comment]
There are 8 levels :D

**Comment by Talkabout** [comment]
Hm,

looking here

https://wiki.archlinux.org/title/rsyslog

there is a table, which gives similar values to what you have used. But this means that we need to replace all the syslog templates to use string severity, correct?

**Comment by murrant** [comment]
Probably, I just checked the templates and the version 7 and 8 ones switched from text to number.  The legacy one uses text.

**Comment by Talkabout** [comment]
good catch, I am using librenms since a few months now, wasn't aware of this :)

**Comment by murrant** [comment]
Let's keep discussion on the bug.

**Pull request merged**
