### PR TITLE
Update for Ubuntu 20 RRDCached Permission Errors

### PR DESCRIPTION
**Pull request by hatboxen**
Please give a short description what your pull request is for

While following the available documentation and attempting to install on Ubuntu 20.04 with RRDCached 1.7.2 the instructions as written for Ubuntu 16 did not work for me - I would get RRDCached permissions errors. Never had this happen on older Ubuntu/RRDCached versions. The fix was to change

$config['rrdcached'] = "unix:/run/rrdcached.sock";
to
$config['rrdcached'] = "unix://run/rrdcached.sock";

with everything else being exactly the same. So I'm sharing it.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Are you sure that isn't what it is supposed to be on older versions too and it just happens to work anyway for some reason?

**Comment by hatboxen** [comment]
Honestly, no. That said I did try it on an older Ubuntu16.04/LNMS1.41/RRD1.5.5 install and it seemed to work both ways.

I actually found this on the community site after lots of search trawling - https://community.librenms.org/t/rrdcached-monitoring-custom-rrdcached-sock-dir/11358/13

**Comment by murrant** [comment]
Very odd the rrdcached docs seem to clearly state it should just be unix: + path

**Comment by hatboxen** [comment]
That's.. odd. Questioning my reality a bit now, but may be best to close this out for now. Will try spinning up a new instance in a similar environment to try and replicate and come back with more information (the one is question is on prod gear, where I can't just do what I want haha). What's weird is it was a fresh OS install, just imported existing rrd/database (same arch).

**Comment by hatboxen** [comment]
Couldn't replicate... god only knows what happened here.

**Comment by murrant** [comment]
Odd, stuff.  Thanks for double checking :)

**Pull request closed without merging**
