### PR TITLE
Added OS detection for Cisco Prime Infrastructure

### LINKED ISSUE #4083: OS Support - Cisco Prime Infrastructure
Adding OS Support

### PR DESCRIPTION
**Pull request by adaniels21487**
- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

- Added OS detection for Cisco Prime Infrastructure
- Added $hardware, $version & $serial
- Resolves #4083

### CODE REVIEW

**Comment by laf** [comment]
Needs a rebase @adaniels21487 

Is this the best OS name?

**Comment by adaniels21487** [comment]
Hi @laf 
This is usually referred to as PI but I thought being 2 characters might cause collisions down the track. I'm open to any suggestions.

**Comment by laf** [comment]
I don't really have any, just checking as it's lengthy and specific. Leave as is.

**Comment by crcro** [comment]
@adaniels21487 ... maybe cpios (cisco prime infrastructure os)?

**Comment by adaniels21487** [comment]
@laf @f0o 
There seems to be a backend failure with CI. Can you please take a look when you get a chance:
https://www.ci.librenms.org/job/librenms/4346/console

```
ERROR 1005 (HY000) at line 916: Can't create table `jenkins_librenms_pr4088`.`device_group_device` (errno: 150 "Foreign key constraint is incorrectly formed")
 101KiB 0:00:12
mysqldump: Got errno 32 on write
ERROR: Cannot mirror master's database! MYSQL_USER=jenkins_librenms_pr-4088 MYSQL_DATABASE=jenkins_librenms_pr4088
Build step 'Execute shell' marked build as failure
```

**Pull request merged**
