### PR TITLE
russian language support

### PR DESCRIPTION
**Pull request by rkislov**
Add ru folder in resource
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
:+1: 

Great start :)

**Comment by rkislov** [comment]
Please review the codeclimate issue - it's not a problem

**Comment by murrant** [comment]
Codeclimate is an optional check.

**Comment by murrant** [comment]
@rkislov as you can tell language support is ongoing.  The user management was recently reworked and supports translation.

If you know anything that could help let us know.

**Comment by rkislov** [comment]
Tony my commit is the Russian language support for user management, I will continue translation of librenms to Russian language as quickly as will appear a new language files for translation.

**Comment by murrant** [comment]
Some translations use implicit translation so they won't be explicitly in the language files.

https://laravel.com/docs/5.8/localization#using-translation-strings-as-keys

**Comment by rkislov** [comment]
> Some translations use implicit translation so they won't be explicitly in the language files.
> 
> https://laravel.com/docs/5.8/localization#using-translation-strings-as-keys

Ok. Translation on a way..........

**Comment by murrant** [comment]
Oops, the browser tests assume english.  I'll get that fixed.

**Comment by rkislov** [comment]
Ok, thanks. I’ll continue translation

**Comment by murrant** [comment]
Sorry there isn't more for you to translate.  A lot of the webui needs to be ported to Laravel.

**Comment by rkislov** [comment]
How can I help you in porting?

**Comment by murrant** [comment]
Old pages need to be ported to Laravel.  Pick one and rewrite it using Blade and controller(s).  You can check the user management or locations pages for an example.

**Comment by rkislov** [comment]
Ok, I'll try it

**Comment by murrant** [comment]
@rkislov several more strings to translate here https://p.libren.ms/view/796e4972

**Comment by rkislov** [comment]
Ok i’ll Translate it soon

**Comment by rkislov** [comment]
> @rkislov several more strings to translate here https://p.libren.ms/view/796e4972
I done it
https://p.libren.ms/view/796e4972#L1

**Comment by murrant** [comment]
@rkislov do you want me to merge that for you or are you going to create a pull request?

**Comment by rkislov** [comment]
I’ll make a pull request by my self to night

**Comment by rkislov** [comment]
I'll made a pull request with updated russian language support

**Pull request merged**
