### PR TITLE
Update Font Awesome from 4.4.0 to 4.7.0 and remove unused files

### PR DESCRIPTION
**Pull request by InsaneSplash**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by InsaneSplash** [comment]
Duplicate

**Comment by murrant** [comment]
Why did you close this @InsaneSplash ?

**Comment by InsaneSplash** [comment]
Roasiak beat me to the punch, his PR is being built as I submitted mine.

**Comment by murrant** [comment]
Ah, I didn't see he updated his. :)

**Pull request closed without merging**
