### PR TITLE
Linux syslog processing cleanup

### PR DESCRIPTION
**Pull request by Ultra2D**
Solves issue #3035 for me, but might need some additional testing.

### CODE REVIEW

**Comment by laf** [comment]
Isn't $entry['program'] empty by that point anyway?

**Comment by Ultra2D** [comment]
No, it's not:
> Feb 18 12:41:23 librenms postfix/smtp[20284]: 23298404BA: to=<mail@example.com>, relay=mailserver.example.com[127.0.0.1]:25, delay=0.21, delays=0.01/0/0/0.2, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 265BE3A62E0)

$entry['program'] will be postfix/smtp .

**Comment by laf** [comment]
I can't say if / what this may break for others. @librenms/reviewers ?

**Comment by paulgear** [comment]
It seems to me this could have unintended side-effects; needs more testing before merge, I say.

**Comment by Ultra2D** [comment]
After looking into it some more, it seems like this rule is mainly matching authentication lines (see comments in the original code), for instance:
> Feb 22 10:23:27 librenms su[7154]: pam_unix(su:auth): authentication failure; logname=thatsme uid=1000 euid=0 tty=/dev/pts/0 ruser=thatsme rhost=  user=root
Feb 22 10:35:01 librenms CRON[16503]: pam_unix(cron:session): session closed for user librenms
Feb 22 10:35:08 librenms sshd[17015]: pam_unix(sshd:session): session opened for user root by (uid=0)
Feb 22 10:35:08 librenms systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Feb 22 10:35:52 librenms sudo: pam_unix(sudo:session): session opened for user librenms by root(uid=0)

It is replacing su/CRON/sshd/systemd/sudo with `pam_unix(<program>:session)` as $entry['program']. The regexp is loosely defined, and because it is matching either `(` or `[`, this will also match the postfix line posted earlier.
The question then becomes, is this the desired behaviour?

**Comment by Ultra2D** [comment]
Would it be easier if I just prevented wrong matches and keep the original behaviour?

**Comment by laf** [comment]
The original behaviour would be better, the caution we have with big changes like this is the level of testing we can do :(

#3099 is also dealing with some syslog changes which could conflict as an fyi.

**Comment by Ultra2D** [comment]
This commit should match the two examples in the code, and won't match Postfix lines including something like `[127.0.0.1]:`
> // pam_krb5(sshd:auth): authentication failure; logname=root uid=0 euid=0 tty=ssh ruser= rhost=123.213.132.231
             // pam_krb5[sshd:auth]: authentication failure; logname=root uid=0 euid=0 tty=ssh ruser= rhost=123.213.132.231

Changes:

- The part preceding the brackets cannot include `:`
- The closing bracket should match the opening one, so either `[]` **or** `()`
- The `:` can be preceded and/or follow by a space

**Comment by murrant** [comment]
@Ultra2D we just merged a change that adds unit tests for the syslog parser (tests/SyslogTest.php).  It would be great if you can add some test cases there.  Thanks.

**Comment by Ultra2D** [comment]
Will do, seems easy enough to extend it now the hard work has been done.

**Comment by laf** [comment]
Is this pr still relevant @Ultra2D ?

**Comment by Ultra2D** [comment]
Yes, the current code will still match too match when OS is Linux. As requested, I will try to add some tests.

**Comment by Ultra2D** [comment]
Alright, I'm done. Two bugs got squashed in the process.

**Comment by Ultra2D** [comment]
On second thought, the dovecot-line was added in 2011 (https://github.com/librenms/librenms/blob/2778e4b90d8a0d38f11b9e6fb29332fae57d19f5/includes/syslog.php#L64) and has never worked, I will remove it completely.

**Comment by paulgear** [comment]
Thanks for your efforts on this one everyone - it's great to see all these test cases getting added!

**Pull request merged**
