### PR TITLE
Rewrite detection of ipv6-addresses & ipv6-networks to LibreNMS/Modules

### PR DESCRIPTION
**Pull request by Npeca75**
1. drop all .inc.php files
2. drop all hard coded OIDs
3. drop old DB code
4. detect SpecialOS es (previous .inc.php)
5. drop old discover_process_ipv6() from functions
6. include ipv6-addresses in json test data
7. include ipv6-networks in json test data
8. translated address origin
9. proper handling of multiple IPv6 Addresses
10.  proper handling of IPv4 compatible IPv6 Addresses  (tested on Jetstream and linux derivates)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@Npeca75 does this has the same problem as the other one?

**Comment by Npeca75** [comment]
> @Npeca75 does this has the same problem as the other one?

Hi @Jellyfrog 

i understand your concern :slightly_smiling_face: 
using this patch on 5 distributed poller, cca 220 pcs of unique IPv6 address and 61pcs of IPv6 network
using 3 special OS and bunch of device in "standard OS" category

for now, everything is looks good
mostly /64 and /120 prefixlen

but, to be sure let me test it again with some "strange" prefixes
will drop you a note

**Comment by Npeca75** [comment]
> @Npeca75 does this has the same problem as the other one?

Hi @Jellyfrog 
tested again, everything works fine

lnms1
lnms2
lnms3
lnms4

**Comment by murrant** [comment]
@Npeca75 Thanks for starting work on this!  We need to make some changes to make it align with the over design of the new modules.

You are missing a design pattern that puts all OS specific code in the OS classes within LibreNMS/OS.

We do this by creating an interface for discovery/polling and implementing that on the OS.  These functions return a collection of models. For this module, you would not need to create a polling interface of course.

We can then use the Keyable interface on the model to sync them to the database with `$this->syncModels()`

Check out the Isis.php module and others for an example.

**Comment by Npeca75** [comment]
> You are missing a design pattern that puts all OS specific code in the OS classes within LibreNMS/OS.

done
but ... not as you expected :(
yes, i wrote a separate discovery modules for each special OS, this is OK, but 

>We can then use the Keyable interface 
it is over my head
1. ipv6address discovery use two table, ipv6addresses & ipv6networks
2. if (big if) someone finish this and make "keyable" thing to work, there will be duplicate, triplicate etc code because then, in every specific OS file you need to have complete code for both networks&addresses

so, i did:
specific os have snmp discovery & put in array
main module then do the rest of job

ok, half way you wanted ... but as i said, i will be glad if you rethink your demand or help me with co-authoring

**Comment by Npeca75** [comment]
hi @murrant 
i am unsure if this a way you wanted, anyway, if you have a time to take a look ....

**Comment by murrant** [comment]
Thanks for continuing to work on this.  You are getting closer.
I think this is how it should work:
1. discoverIpv6 should return an array of Ipv6Address models (new and unsaved)
2. The Ipv6Addresses module will extract a list of networks and add them to the database (then update the ids in the address models
3. Then call $this->syncModels() to save the Ipv6Addresses (and delete no longer existing ones)

Not sure if I missed anything there.

**Pull request closed without merging**
