### PR TITLE
Extended 'port previous' graphs

### PR DESCRIPTION
**Pull request by SniperVegeta**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @SniperVegeta 
Tests are not passing right now. A few errors (formatting) are blocking. 
You can check Travis for a list of blocking ones (https://travis-ci.com/librenms/librenms/jobs/215453953) and Codeclimate for the complete list. 
Bye

**Comment by murrant** [comment]
@SniperVegeta I think I'm missing something, but I don't understand what this is supposed to do.  Also clicking previous on the graph page before and after applying this doesn't seem to do anything.

**Comment by SniperVegeta** [comment]
@PipoCanaja for so far its done, 
if i find someting new to do i get a new pull

**Comment by PipoCanaja** [comment]
Hi @SniperVegeta 
I personnally don't use this "Previous" at all. As far as I get it, the idea is to superpose for whatever time interval you draw the RRD, the n-1 interval. 

Any chance that you could attach a 'before' 'after' screen capture of a graph that benefit from this feature ?

**Comment by SniperVegeta** [comment]
Device Poller (not working) now whit stats + line
Poller (not working) + new avg dev
Poller Show Previous Whit line to easy compare
Switch Port Show Previous (after) Better show + stats
Switch Port Show Previous (befor)
Switch overvieuw Show Previous (whit port stats+total)

+ Poller mudules

**Comment by SniperVegeta** [comment]
@PipoCanaja ok?

**Comment by SniperVegeta** [comment]
@PipoCanaja , Added the merged "Simple linear port graph prediction" by @murrant

**Comment by laf** [comment]
Needs rebasing I'm afraid to fix the merge conflict.

**Comment by SniperVegeta** [comment]
@laf , if i try to apply it only whines about:

Checking patch includes/html/graphs/generic_data.inc.php...
error: while searching for:
$rrd_options .= ' LINE1:percentile_in#aa0000';
$rrd_options .= ' LINE1:dpercentile_out#aa0000';

if ($_GET['previous'] == 'yes') {
    $rrd_options .= ' LINE1.25:in' . $format . "X#009900:'Prev In \\\\n'";
    $rrd_options .= ' LINE1.25:dout' . $format . "X#000099:'Prev Out'";
}

unset($stacked);


only the  $rrd_options .= ' LINE1.25:in' . $format . "X#009900:'Prev In \\\\n'" i alrady changed, but somehow i cant edit annymore , my fork is gone :(

but it works....

will redo it soon and get an new PR

**Comment by SniperVegeta** [comment]
New PR cant edit this one annymore ...

**Pull request closed without merging**
