### PR TITLE
add basic f5 support

### PR DESCRIPTION
**Pull request by supertylerc**
This adds the most basic F5 support by:

* Adding an F5 Device Icon
* Determining the Big IP software version
* Defining basic F5 Big IP OS variables

### CODE REVIEW

**Comment by supertylerc** [comment]
I looked at the failed test on Scrutinizer, but I don't see why it failed.  There's no output.

**Comment by f0o** [comment]
Cheers @supertylerc, 

Can you sign the contributor's agreement mentioned at http://docs.librenms.org/General/Contributing/ in a seperate PR please?

Thanks :)

**Comment by laf** [comment]
Hey Tyler 

Scrut on occasions just fails :/ Paul can kick a new test off or you could push a small commit to do the same. I don't see it being an issue on such a small commit.

**Comment by supertylerc** [comment]
@f0o-

Finding a license proved to be a bit of a challenge, so I've e-mailed F5 Networks for more information.  Here is a copy of the email:

> From: Tyler Christiansen <mail@tylerc.me>
> Subject: F5 Icon License?
> Date: March 27, 2015 at 9:42:48 AM PDT
> To: CorporateCommunications@F5.com
> 
> Hello.
> 
> I'd like to use the F5 icon in an open source project, but I can't seem to find licensing information.  The project is called LibreNMS, and you can see it here: librenms.  You can see the specific pull request for adding basic F5 support here: https://github.com/librenms/librenms/pull/670#issuecomment-86849090
> 
> I would like to use the image that is part of that script (https://github.com/supertylerc/librenms/blob/feat/f5-detection/html/images/os/f5.png), which was obtained from Wikipedia here: http://en.wikipedia.org/wiki/F5_Networks.  The licensing details according to Wikipedia for this image are here: http://en.wikipedia.org/wiki/File:F5_Networks_logo.svg.  The image was retrieved and then resized to the required 40x40 pixels.
> 
> Any guidance you could provide would be immensely appreciated.  Thank you.
> 
> --
Tyler Christiansen

**Comment by laf** [comment]
@supertylerc 

https://f5.com/about-us/news/press-kit

No restriction by the looks of it, it does say a minimum for the image height which is bigger than what we use but I can't see that being a huge issue.

**Comment by supertylerc** [comment]
@laf 

I looked through that and some of the associated documentation--much of it seemed it indicate that express permission is required for use.  Better safe than sorry.

**Comment by supertylerc** [comment]
I haven't received a response from F5 Networks.  Do you feel that it is safe enough to merge this change based on their website's information?

**Comment by laf** [comment]
I'd merge it personally. Probably one for @paulgear to comment on. If not, for now remove the image for something else. I did just that on a pr today to save waiting for the vendor to confirm.

**Comment by paulgear** [comment]
This is easy to fix by just removing the file, so let's put it in.

**Pull request merged**
