### PR TITLE
LibreNMS/Alert/Transport/Elasticsearch - Send timestamp with timezone

### PR DESCRIPTION
**Pull request by pobradovic08**
Add timezone to timestamp field, otherwise ES will think it's UTC

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Can we just send a unix_timestamp?
Aka: `'@timestamp' => date(),`

**Comment by pobradovic08** [comment]
We could do:
`'@timestamp' => time()*1000,`

Apparently it's expecting microseconds since epoch and both  `time()` and `microtime(true)` are iterpreted as Jan 18th 1970 by ES

**Comment by pobradovic08** [comment]
Unfortunately if we send just a timestamp then elastics sets the type of the field to `number` by default (instead of `date`). This can be fixed by creating a template on ES side but I think it's easier for everyone to send a timestamp as a string that will automatically be recognized as a date by ES.

**Comment by murrant** [comment]
@pobradovic08 Perhaps instead of sending a timezone (which can bring daylight savings headaches) Just send the UTC time.  `\Carbon\Carbon:now('UTC')->toISOString()`

**Comment by murrant** [comment]
Updated to use ISO 8601 format

**Pull request merged**
