### PR TITLE
WebUI update to support dark / light theme - dark is default

### PR DESCRIPTION
**Pull request by laf**
Dark theme: http://pbrd.co/1yfAGFf

Light theme: http://pbrd.co/1yfAMwz

Use can change this in config.php using: $config['site_style'] = 'light'; // or dark

Moved all icons in the navbar to use font awesome icons. Whilst this is a little restrictive in some ways, the just look a lot cleaner / crisper and can be tied in in many other part os the website.

### CODE REVIEW

**Comment by laf** [comment]
I've done some (crude) page speed tests against the current setup and the dark theme (it will be the same for the light theme).

Load times have dropped by 1/2 - 2/3 so vastly increase the page loading and rendering times.

**Comment by f0o** [comment]
Related: #665

**Comment by laf** [comment]
Updated default theme to light.

Updated navbar main icons to use new colors - menus use the defaults.

**Comment by paulgear** [comment]
We probably should use the project_url config setting instead of manually hard-coding the "powered by" URL, but I'm not going to let that stand in the way of this. :-)

**Comment by laf** [comment]
lol, I'll update that :)

**Comment by laf** [comment]
@paulgear FYI #700. I've created a new config option to support this, reasons why in that PR :)

**Pull request merged**
