### PR TITLE
Disable xdebug on travis-ci

### PR DESCRIPTION
**Pull request by Jellyfrog**
Could probably speed up the tests and avoid a couple of quirks.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This is skipping the unit tests on all builds.

**Comment by Jellyfrog** [comment]
I think thats because of how our pre-commit decides on what to run and not, ie:
```php
// If we have no php files and no OS' found then also skip unit checks.
if (!empty($changed_files) && $map['php'] === 0 && empty($map['os']) && !$os) {
    putenv('SKIP_UNIT_CHECK=1');
}
```
https://travis-ci.com/github/Jellyfrog/librenms/jobs/318404090

**Comment by murrant** [comment]
it should probably run all in this case...

**Comment by Jellyfrog** [comment]
indeed.

**Pull request merged**
