### PR TITLE
WebUI - 'Disabled' and 'Down' state for devices/links rendered on NetworkMap

### PR DESCRIPTION
**Pull request by PipoCanaja**
Hello

Here is a proposal for a dedicated color on disabled devices displayed on the Network Maps. Usecase is that during a migration, we are "disabling" the old devices and we delete them only a few days/weeks later. This change allows to see the productive devices as well as the disabled ones and clearly know which is which. 

Thanx

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Got an example of what this looks like?

**Comment by PipoCanaja** [comment]
Something like this, right now. 

image

Looking at the code, it seems that the color of the links is mapped to the load of the links. We could imagine the the hosts color changes : 
 - host disabled -> host GRAY, links GRAY as well, could be dotted (dotted would mean "not running"
 - host down -> host RED, links dotted RED
 - host up -> host BLUE, links color depending of the speed (like it is now). 

Bye

**Comment by laf** [comment]
@PipoCanaja Looks fine to me. Is this still classed as WIP?

**Comment by laf** [comment]
> Do you suggest me to commit the "try and fails" or to keep it "internal" (and providing you screenshots until then) and when something appears good, then I commit ?

Sorry I'm not sure what you mean by this.

**Comment by PipoCanaja** [comment]
The map as in the screenshot is now committed. In my environnement, it seems good. But it should definitly be tested now in more networks.  

Let me know how it goes.

**Pull request merged**
