### PR TITLE
RFC: RRD Definition object

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Move RrdDefinition to an Object to make it easier to create and remve the possibility of typos.
@laf: Combine this with #5947 ?

This code is not mergable as-is, it requires updating all definitions.

### CODE REVIEW

**Comment by laf** [comment]
@murrant are you looking to merge those two prs and update all the files to make use of this new class at the same time?

**Comment by murrant** [comment]
@laf yes, if it seems like this is something we want.

**Comment by laf** [comment]
Yes indeed, just don't know if I've got the time to go and update all the files to use this straight away :/

**Comment by murrant** [comment]
I can take a shot at it.  A few regex replacements should do it.

**Comment by laf** [comment]
If you do just add it to this PR.

I'll do the webui config and docs if you like.

**Pull request closed without merging**
