### PR TITLE
docs: create Database-Schema doc

### PR DESCRIPTION
**Pull request by kkrumm1**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
For most people this won't be needed. I'd say we should cover this under the developer docs as a new file title Database-Schema.md, can start with some info on how the database schema is published as a json file so we can validate the users DB.

Include the command on how to generate that file if you make changes to the db structure for a PR.

**Comment by kkrumm1** [comment]
Okay, @laf  I will make doc like that.

**Comment by kkrumm1** [comment]
> Include the command on how to generate that file if you make changes to the db structure for a PR.
@laf im not sure what you mean by this or what command? :(

**Comment by laf** [comment]
I'll be honest and say we should close this for now, until someone can get more info in it then it's not really of any use to anyone and it's not an often enough asked question.

**Comment by kkrumm1** [comment]
roger sounds good. closing for now. :)

**Pull request closed without merging**
