### PR TITLE
To allow dots in username

### PR DESCRIPTION
**Pull request by Oirbsiu**
When creating a new user, this change updates the validation rule and permits a dot (period) in the username string

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by electrocret** [comment]
Please delete the .bak files as they're not executed.

**Comment by murrant** [comment]
Instead adding a new custom validation, just set the regex directly on the validation.

**Review by murrant — CHANGES_REQUESTED** [review]
Should not be adding a custom validator for this.

regex is very subjective, possibly this should be  a setting with a sane default.

**Comment by murrant** [comment]
#
Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.

Please feel free to reopen, I would love to see your changes added to LibreNMS.

**Comment by Oirbsiu** [comment]
would this be an acceptable RegEx?
^[a-z0-9]+([._]?[a-z0-9]+)+$

**Pull request closed without merging**
