### PR TITLE
Feature/add t echo

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

DO NOT MERGE

Thought this might be useful to try and tidy up poller/debug output as it's a pain to read through some times. php-cli-tools is a modified version which is within the librenms org, I've added support for outputting the index used for the arrays as we have a lot of data which don't just have 0,1,2,3,etc as indexes but 100, 501, 1501, etc (ifIndex).

We could probably roll our own but this has support for other cli processing + still works when you pipe the data to other programs.

Creating PR for feedback, if it's good I'll try and covert a lot of poller/disco to use it.

### CODE REVIEW

**Comment by laf** [comment]
Example output https://www.irccloud.com/pastebin/MtpEzw0S/

**Comment by murrant** [comment]
I made a change to make headers optional.
I also fixed the autoloader (`composer dump-autoload -o`)

**Comment by laf** [comment]
You happy with it then if I convert some poller files over?

**Comment by murrant** [comment]
If it makes things easier to read, go ahead.  We could also drop our console_color2 dependency, but that doesn't have to be done in this PR.

**Comment by laf** [comment]
Hmm, started on ports polling and because of the size of the columns you get:

https://p.libren.ms/view/3c8c890a

I'm not sure that's actually anymore readable than:

https://p.libren.ms/view/6e750e02

So closing this down :(

**Comment by murrant** [comment]
Hmm, yeah, it is just a lot of data...

**Pull request closed without merging**
