### PR TITLE
newdevice: Updated Arista entity-physical support to use high/low values from device

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Added checks for is_nan and is_infinite as the data returned from the calculations returned either -INF or NAN.

Fixes: #7078

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7156)

### CODE REVIEW

**Comment by shimamizu** [comment]
I went and applied this, got a bunch of whitespace errors that it looks like you need to fix. 

/opt/librenms
me@librenms:  -> sudo ./scripts/github-apply 7156
<stdin>:124: trailing whitespace.
ARISTA-ENTITY-SENSOR-MIB DEFINITIONS ::= BEGIN 
<stdin>:152: trailing whitespace.
        "This MIB module augments the entPhySensorTable of 
<stdin>:153: trailing whitespace.
        ENTITY-SENSOR-MIB to provide threshold information for 
<stdin>:159: trailing whitespace.
        In addition, on systems where it is supported, if the 
<stdin>:168: trailing whitespace.
-- Textual Conventions -- 
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
Checking patch includes/discovery/sensors/misc/arista-eos-limits.inc.php...
Checking patch includes/polling/functions.inc.php...
Checking patch mibs/arista/ARISTA-ENTITY-SENSOR-MIB...
Checking patch includes/common.php...
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
Applied patch includes/discovery/sensors/entity-sensor.inc.php cleanly.
Applied patch includes/discovery/sensors/misc/arista-eos-limits.inc.php cleanly.
Applied patch includes/polling/functions.inc.php cleanly.
Applied patch mibs/arista/ARISTA-ENTITY-SENSOR-MIB cleanly.
Applied patch includes/common.php cleanly.
Applied patch includes/discovery/sensors/entity-sensor.inc.php cleanly.
warning: squelched 14 whitespace errors
warning: 19 lines add whitespace errors.

**Comment by laf** [comment]
Those are just the mibs so nothing to be fixed. The apply has worked ok though so see how you get on after a full discover and some polls.

**Comment by shimamizu** [comment]
K, so I did a discovery and got the new values. However it looks like you're not doing the conversions I mentioned for Tx Power or Rx Power.

My original description mentioned: 

> The outputs we would get would look like this, note the values don't look correct though! we have to convert them. In order to get the correct values, divide by 10,000 and then convert from mw to dBm.
> 
> SNMPv2-SMI::enterprises.30065.3.12.1.1.1.1.103329212 = INTEGER: 4250
> SNMPv2-SMI::enterprises.30065.3.12.1.1.1.2.103329212 = INTEGER: 4575
> SNMPv2-SMI::enterprises.30065.3.12.1.1.1.3.103329212 = INTEGER: 19952
> SNMPv2-SMI::enterprises.30065.3.12.1.1.1.4.103329212 = INTEGER: 22387
> 
> So converting them we get:
> 4250 / 10000 => 0.4250mw => -3.7161106995 dBm ~ -3.72 dBm
> 4575 / 10000 => 0.4575mw => -3.396089016 dBm ~ -3.40 dBm
> 19952 / 10000 => 1.9952mw => 2.9998643613 dBm ~ 3.00 dbm
> 22387 / 10000 => 2.2387mw => 3.4986008219 dBm ~ 3.50 dBm
>

Which looking at the channel sensor readings, I can see there's no conversion being done, all the sensor_limit values need to be converted like mentioned above to get values that can be compared against the sensor_current. 

```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%52/1%';
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                   | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM TX Bias  for Ethernet52/1  |        0.05375 |          0.1 |              0.09 |           0.0002 |                0.0003 |
| DOM TX Power  for Ethernet52/1 |          -0.16 |        22387 |             19952 |             4250 |                  4575 |
| DOM RX Power  for Ethernet52/1 |          2.471 |        28184 |             25119 |              100 |                   199 |
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
3 rows in set (0.00 sec)
```

**Comment by shimamizu** [comment]
One other problem Temperature sensor is grabbing limit and limit_low but getting only NULL for limit_warn and low_warn. 

What it gets now: 

```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%DOM Temp%';
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                    | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM Temperature  for Ethernet49 |           55.4 |           70 |              NULL |               -5 |                  NULL |
| DOM Temperature  for Ethernet50 |           56.2 |           70 |              NULL |               -5 |                  NULL |
| DOM Temperature  for Ethernet51 |           52.6 |           70 |              NULL |               -5 |                  NULL |
| DOM Temperature  for Ethernet52 |           55.1 |           70 |              NULL |               -5 |                  NULL |
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
4 rows in set (0.00 sec)
```

Example of what it should get for the missing values: 
```
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Temperature   Threshold   Threshold   Threshold   Threshold   
Port       (Celsius)     (Celsius)   (Celsius)   (Celsius)   (Celsius)   
-------    ------------  ----------  ----------  ----------  ----------  
Et51/1     52.64         70.00       65.00       -5.00       0.00        
```
We're missing the 65.00 and 0.00 values in the table. They're showing as NULL right now.



The Bias values look funny too, did you divide ALL of those by 10,000 or something? kind of seems that way: 
```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%DOM TX Bias  for Ethernet49/1%';
+-------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                  | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+-------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM TX Bias  for Ethernet49/1 |        0.05159 |          0.1 |              0.09 |           0.0002 |                0.0003 |
+-------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
1 row in set (0.00 sec)
```

What it should look like: 
```
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Current       Threshold   Threshold   Threshold   Threshold   
Port       (mA)          (mA)        (mA)        (mA)        (mA)        
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     51.58         100.00      90.00       0.20        0.30     
```

**Comment by shimamizu** [comment]
Whatever you just changed now caused limit_warn and low_warn to all be NULL. 
Also note it's Tx Power and Rx Power values for sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn that need to be converted. And they must be converted by dividing by 10,000 first and then also converted from mw to dbm in order for them to be the right values.  

```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%52/1%';
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                   | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM TX Bias  for Ethernet52/1  |        0.05375 |          0.1 |              NULL |           0.0002 |                  NULL |
| DOM TX Power  for Ethernet52/1 |          -0.16 |        22387 |              NULL |             4250 |                  NULL |
| DOM RX Power  for Ethernet52/1 |          2.532 |        28184 |              NULL |              100 |                  NULL |
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
3 rows in set (0.00 sec)
```

And these values for Tx Bias still shouldn't be divided. 
```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%DOM TX Bias  for Ethernet49/1%';
+-------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                  | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+-------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM TX Bias  for Ethernet49/1 |        0.05159 |          0.1 |              NULL |           0.0002 |                  NULL |
+-------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
1 row in set (0.00 sec)
```

**Comment by laf** [comment]
I've pushed a change, you'll need to remove the old patch which you can do with `scripts/github-remove` if you don't have any other changes.

However....I don't think it's right still and I'm not in the mood for fighting a shitty snmp implementation from arista so if this doesn't work then I'll close this down for now and either come back to it or hope someone else does.

**Comment by shimamizu** [comment]
Did a git reset --hard (git-remove didn't play nice) and that worked, then re-applied. 

Still seeing the same null values as my last comment. The other values still haven't actually been divided by 10,000 and converted from mw to dbm. I think it's very close to working (and whatever you did on your first pass was slightly closer as I didn't end up with the warn values as NULL until your second pass). Just need to figure out why it's not doing the divide and convert logic you wrote for them.

**Comment by laf** [comment]
The issue with the first one was that all values were being divided by 10000 + then converted not just the power ones.

I've pushed one more update...

The mib doesn't indicate it should vary between different sensor types but obviously it does. Maybe with a fresh pair of eyes some will spot it but I'm done with it for now.

**Comment by shimamizu** [comment]
Well I did another git reset hard and pull. Still getting null values in the warn columns, and then numbers still not looking like they were actually divided by 10,000 or converted to dbm at all. 

BTW for my checks I've been forcing discovery on my test device this way: 
sudo php56 discovery.php -h 122

I assume that's the right way to get the values re-polled?


```
/opt/librenms
me@librenms:  -> sudo git reset --hard
[sudo] password for gurinsky: 
HEAD is now at 1f98bf4 Update Using-Git.md (#7159)
/opt/librenms
me@librenms:  -> sudo git pull
Already up-to-date.
/opt/librenms
me@librenms:  -> sudo ./scripts/github-apply 7156
<stdin>:124: trailing whitespace.
ARISTA-ENTITY-SENSOR-MIB DEFINITIONS ::= BEGIN 
<stdin>:152: trailing whitespace.
        "This MIB module augments the entPhySensorTable of 
<stdin>:153: trailing whitespace.
        ENTITY-SENSOR-MIB to provide threshold information for 
<stdin>:159: trailing whitespace.
        In addition, on systems where it is supported, if the 
<stdin>:168: trailing whitespace.
-- Textual Conventions -- 
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
Checking patch includes/discovery/sensors/misc/arista-eos-limits.inc.php...
error: includes/discovery/sensors/misc/arista-eos-limits.inc.php: already exists in working directory
Checking patch includes/polling/functions.inc.php...
Checking patch mibs/arista/ARISTA-ENTITY-SENSOR-MIB...
error: mibs/arista/ARISTA-ENTITY-SENSOR-MIB: already exists in working directory
Checking patch includes/common.php...
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
Checking patch includes/discovery/sensors/entity-sensor.inc.php...
```

and then I do: 
```
/opt/librenms
me@librenms:  -> sudo php56 discovery.php -h 122
LibreNMS Discovery
```
~rest omitted


The power values still don't look like they've been converted at all, and there's null's in the warn columns (which attempt 1 didn't have, but attempt 2 and onward did have that issue) 
```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%52/1%';
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                   | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM TX Bias  for Ethernet52/1  |        0.05341 |          0.1 |              NULL |           0.0002 |                  NULL |
| DOM TX Power  for Ethernet52/1 |         -0.185 |        22387 |              NULL |             4250 |                  NULL |
| DOM RX Power  for Ethernet52/1 |          2.459 |        28184 |              NULL |              100 |                  NULL |
+--------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
3 rows in set (0.00 sec)
```

**Comment by shimamizu** [comment]
Trying again, realized I forgot to chown after I re-pulled.

**Comment by shimamizu** [comment]
Bummer, no change after that.

**Comment by laf** [comment]
Thanks for testing @shimamizu.

I'm closing this now.

**Comment by shimamizu** [comment]
K, I think the main thing that needed (needs) fixing to make it work is just the conversion to happen on the right values. The Tx Bias value needs to NOT be divided (cuz it looked like it had been?) and the TX Power and Rx Power need to still be converted. In all the iterations, the values were the default SNMP get values and no adjustments (division / conversion) had actually been done to them from what I saw when they ended up in the database. 

We were close! :)

**Comment by laf** [comment]
Give it another shot.

**Comment by shimamizu** [comment]
Much better but it looks like you need to figure out why everything in sensor_limit_warn and sensor_limit_low_warn is showing up NULL. 

Also looks like you are dividing by 10,000 on the ones w/ "DOM TX Bias" but those don't need to be divided.  

So things to fix 
1) Don't have it divide values listed for Tx Bias
2) all values listing as NULL for sensor_limit_warn and sensor_limit_low_warn - fix whatever is causing it to miss grabbing those

but everything else I see looks like the right values :) :) :) 

`MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%Ethernet49%';
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                    | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM Temperature  for Ethernet49 |           54.2 |           70 |              NULL |               -5 |                  NULL |
| DOM Voltage  for Ethernet49     |           3.28 |         3.63 |              NULL |             2.97 |                  NULL |
| DOM TX Bias  for Ethernet49/1   |        0.05145 |          0.1 |              NULL |           0.0002 |                  NULL |
| DOM TX Power  for Ethernet49/1  |          1.344 |        22387 |              NULL |             4250 |                  NULL |
| DOM RX Power  for Ethernet49/1  |          1.604 |        28184 |              NULL |              100 |                  NULL `


`switch#show interfaces ethernet 49/1 transceiver detail 
mA: milliamperes, dBm: decibels (milliwatts), NA or N/A: not applicable.
++ : high alarm, +  : high warning, -  : low warning, -- : low alarm.
A2D readouts (if they differ), are reported in parentheses.
The threshold values are calibrated.
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Temperature   Threshold   Threshold   Threshold   Threshold   
Port       (Celsius)     (Celsius)   (Celsius)   (Celsius)   (Celsius)   
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     54.16         70.00       65.00       -5.00       0.00        
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Voltage       Threshold   Threshold   Threshold   Threshold   
Port       (Volts)       (Volts)     (Volts)     (Volts)     (Volts)     
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     3.28          3.63        3.47        2.97        3.14        
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Current       Threshold   Threshold   Threshold   Threshold   
Port       (mA)          (mA)        (mA)        (mA)        (mA)        
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     51.45         100.00      90.00       0.20        0.30        
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Tx Power      Threshold   Threshold   Threshold   Threshold   
Port       (dBm)         (dBm)       (dBm)       (dBm)       (dBm)       
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     1.35          3.50        3.00        -3.72       -3.40       
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Rx Power      Threshold   Threshold   Threshold   Threshold   
Port       (dBm)         (dBm)       (dBm)       (dBm)       (dBm)       
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     1.58          4.50        4.00        -20.00      -17.01  `

**Comment by shimamizu** [comment]
Trashing my comment, thought it looked right, but now I'm forcing a few more scans to run to verify some things as I think I was misreading the columns I cared about. stand by.

**Comment by shimamizu** [comment]
Ok so I went back to your *first* commit since that was the only one that actually grabbed all the values and didn't have two columns spewing out NULL values for whatever reason. I then did some hacking of my own on the code and was finally able to get it to work. 

To fix the BIAS CURRENT dividing wrong, I put this in after this existing section: 
```
if ($entry['entPhySensorScale'] == 'milli') {
                $divisor    = '1000';
                $multiplier = '1';
            }
```

I added 

```
if ($entry['entPhySensorScale'] == 'milli' &&  $entry['entPhySensorType'] == 'amperes') {
                $divisor    = '1';
                $multiplier = '1';
            }
```

Then for the actual grabbing the sensors section I changed this code: 

```
if ($device['os'] === 'arista_eos') {
                    if ($entry['aristaEntSensorThresholdLowWarning'] != '-1000000000' &&
                    $entry['aristaEntSensorThresholdLowWarning'] != '0') {
                        $low_warn_limit = $entry['aristaEntSensorThresholdLowWarning'] / $divisor;
                    }
                    if ($entry['aristaEntSensorThresholdLowCritical'] != '-1000000000' &&
                    $entry['aristaEntSensorThresholdLowCritical'] != '0') {
                        $low_limit = $entry['aristaEntSensorThresholdLowCritical'] / $divisor;
                    }
                    if ($entry['aristaEntSensorThresholdHighWarning'] != '1000000000' &&
                    $entry['aristaEntSensorThresholdHighWarning'] != '0') {
                        $warn_limit = $entry['aristaEntSensorThresholdHighWarning'] / $divisor;
                    }
                    if ($entry['aristaEntSensorThresholdHighCritical'] != '1000000000' &&
                    $entry['aristaEntSensorThresholdHighCritical'] != '0') {
                        $high_limit = $entry['aristaEntSensorThresholdHighCritical'] / $divisor;
                    }
                }
```


To this: 

```
if ($device['os'] === 'arista_eos') {
                    if ($entry['aristaEntSensorThresholdLowWarning'] != '-1000000000' && $entry['aristaEntSensorThresholdLowWarning'] != '0') {
                        if ($entry['entPhySensorScale'] == 'milli' &&  $entry['entPhySensorType'] == 'watts') {
	                        $temp_low_warn_limit = $entry['aristaEntSensorThresholdLowWarning'] / 10000;
	                        $low_warn_limit = round(10 * log10($temp_low_warn_limit),2);
                        }
                        else {
	                        $low_warn_limit = $entry['aristaEntSensorThresholdLowWarning'] / $divisor;
	                    }
                    }
                    if ($entry['aristaEntSensorThresholdLowCritical'] != '-1000000000' && $entry['aristaEntSensorThresholdLowCritical'] != '0') {
                        if ($entry['entPhySensorScale'] == 'milli' &&  $entry['entPhySensorType'] == 'watts') {
	                        $temp_low_limit = $entry['aristaEntSensorThresholdLowCritical'] / 10000;
	                        $low_limit = round(10 * log10($temp_low_limit),2);
                        }
                        else {
	                        $low_limit = $entry['aristaEntSensorThresholdLowCritical'] / $divisor;
	                    }
                    }
                    if ($entry['aristaEntSensorThresholdHighWarning'] != '1000000000' && $entry['aristaEntSensorThresholdHighWarning'] != '0') {
                        if ($entry['entPhySensorScale'] == 'milli' &&  $entry['entPhySensorType'] == 'watts') {
	                        $temp_warn_limit = $entry['aristaEntSensorThresholdHighWarning'] / 10000;
	                        $warn_limit = round(10 * log10($temp_warn_limit),2);
                        }
                        else {
	                        $warn_limit = $entry['aristaEntSensorThresholdHighWarning'] / $divisor;
	                    }
                    }
                    if ($entry['aristaEntSensorThresholdHighCritical'] != '1000000000' && $entry['aristaEntSensorThresholdHighCritical'] != '0') {
                        if ($entry['entPhySensorScale'] == 'milli' &&  $entry['entPhySensorType'] == 'watts') {
	                        $temp_high_limit = $entry['aristaEntSensorThresholdHighCritical'] / 10000;
	                        $high_limit = round(10 * log10($temp_high_limit),2);
                        }
                        else {
	                        $high_limit = $entry['aristaEntSensorThresholdHighCritical'] / $divisor;
	                    }
                    }
                }
```



After those changes I get the correct outputs for Bias Current thresholds and the correct outputs for Tx and Rx power thresholds. 

Note - one last thing to check, even your first commit gives me NULL values for  DOM Temperature in sensor_limit_warn and sensor_limit_low_warn. Everything else gives me outputs and w/ my adjustments are now the right numbers. 

Also NOTE - for the sensor_current you can change this to round to 2 instead of 3 decimal places, that's what the switch output shows. I couldn't figure out where in your code you were rounding that current sensor value off at. 

After my changes: 

```
MariaDB [librenms]> select sensor_descr,sensor_current,sensor_limit,sensor_limit_warn, sensor_limit_low, sensor_limit_low_warn from sensors where device_id = 122 and sensor_descr like '%Ethernet49%';
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| sensor_descr                    | sensor_current | sensor_limit | sensor_limit_warn | sensor_limit_low | sensor_limit_low_warn |
+---------------------------------+----------------+--------------+-------------------+------------------+-----------------------+
| DOM Temperature  for Ethernet49 |             55 |           70 |              NULL |               -5 |                  NULL |
| DOM Voltage  for Ethernet49     |           3.28 |         3.63 |              3.47 |             2.97 |                  3.14 |
| DOM TX Bias  for Ethernet49/1   |          51.59 |          100 |                90 |              0.2 |                   0.3 |
| DOM TX Power  for Ethernet49/1  |          1.331 |          3.5 |                 3 |            -3.72 |                  -3.4 |
| DOM RX Power  for Ethernet49/1  |          2.474 |          4.5 |                 4 |              -20 |                -17.01 |
```

and compare to the switch: 

```
switch#show interfaces ethernet 49/1 transceiver detail
mA: milliamperes, dBm: decibels (milliwatts), NA or N/A: not applicable.
++ : high alarm, +  : high warning, -  : low warning, -- : low alarm.
A2D readouts (if they differ), are reported in parentheses.
The threshold values are calibrated.
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Temperature   Threshold   Threshold   Threshold   Threshold   
Port       (Celsius)     (Celsius)   (Celsius)   (Celsius)   (Celsius)   
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     55.00         70.00       65.00       -5.00       0.00        
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Voltage       Threshold   Threshold   Threshold   Threshold   
Port       (Volts)       (Volts)     (Volts)     (Volts)     (Volts)     
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     3.28          3.63        3.47        2.97        3.14        
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Current       Threshold   Threshold   Threshold   Threshold   
Port       (mA)          (mA)        (mA)        (mA)        (mA)        
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     51.91         100.00      90.00       0.20        0.30        
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Tx Power      Threshold   Threshold   Threshold   Threshold   
Port       (dBm)         (dBm)       (dBm)       (dBm)       (dBm)       
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     1.33          3.50        3.00        -3.72       -3.40       
                         High Alarm  High Warn   Low Alarm   Low Warn    
           Rx Power      Threshold   Threshold   Threshold   Threshold   
Port       (dBm)         (dBm)       (dBm)       (dBm)       (dBm)       
-------    ------------  ----------  ----------  ----------  ----------  
Et49/1     2.47          4.50        4.00        -20.00      -17.01  
```

**Comment by laf** [comment]
> if ($entry['entPhySensorScale'] == 'milli' &&  $entry['entPhySensorType'] == 'amperes') {
>                 $divisor    = '1';
>                 $multiplier = '1';
>             }

Awesome :)

Can you give me a diff (or submit your own pull request?).

You will need to change the above though as that will change the divisor / multiplier for all devices so it needs doing in the arista_eos section only.

**Comment by shimamizu** [comment]
I paste bin'ed the entire file I have working here: 
https://pastebin.com/2P5YP6pg

Like I mentioned, I had just modified what you had in your first commit for includes/discovery/sensors/entity-sensor.inc.php and updated it to the above pastebin output. 

I moved the one section you asked me to under the Arista section so it shouldn't break other things. Ironically when I move it to there instead, it requires divisor = 100 instead of divisor = 1. Go figure. Not sure what other magic voodoo was effecting that bias current calculation ;)

**Comment by shimamizu** [comment]
Don't forget to see if you can find what is causing NULL values for DOM Temperature in sensor_limit_warn and sensor_limit_low_warn

and if you can get the current sensor values for the arista's to round to 2 decimal places instead of 3

**Comment by laf** [comment]
@shimamizu I've just pushed another update - hopefully not enough to break things again but should fix the last few niggles.

Some sensors will still have NULL but that's because they have values or -1000000000 or 1000000000 so we exclude them.

**Comment by shimamizu** [comment]
K i imported this and tested it just now and the values still appear to look correct :)

**Comment by laf** [comment]
Thanks for testing @shimamizu :)

**Comment by laf** [comment]
Oh - and fixing my code :D

**Pull request merged**
