### PR TITLE
RRDtool dual process (remote creation/check)

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Disabled at this time
Split out rrdtool version checks into rrdtool_create_command()
Tests for rrdtool_create_command()
Fixes a few small issues.

### CODE REVIEW

**Comment by laf** [comment]
Needs a rebase. Will run on dev / home installs to test.

**Comment by murrant** [comment]
To enable dual process, also apply this patch:
```
diff --git a/includes/rrdtool.inc.php b/includes/rrdtool.inc.php
index 6d79b7a..9abdbf8 100644
--- a/includes/rrdtool.inc.php
+++ b/includes/rrdtool.inc.php
@@ -18,7 +18,7 @@
  * @param bool $dual_process start an additional process that's output should be read after every command
  * @return bool the process(s) have been successfully started
  */
-function rrdtool_initialize($dual_process = false)
+function rrdtool_initialize($dual_process = true)
 {
     global $config, $rrd_async_process, $rrd_async_pipes, $rrd_sync_process, $rrd_sync_pipes;
 
@@ -235,7 +235,13 @@ function rrdtool_build_command($command, $filename, $options)
  */
 function rrdtool_check_rrd_exists($filename)
 {
-    return is_file($filename);
+    global $config;
+    if ($config['rrdcached'] && version_compare($config['rrdtool_version'], '1.5', '>=')) {
+        $chk = rrdtool('last', $filename, '');
+        return strpos(implode($chk), "$filename': No such file or directory") === false;
+    } else {
+        return is_file($filename);
+    }
 }
 
 /**
```

**Comment by laf** [comment]
Done.

Why not just put this as part of the PR?

**Comment by murrant** [comment]
Well, I want to separate them because this fixes a bug with rrd tool <1.4.3 and the dual proc has more breaking potential.

**Comment by murrant** [comment]
After some more testing, I fixed an issue where I didn't strip the full path on remote commands.
I also enabled dual process.  Tests went very well on the three systems I tested.

**Comment by laf** [comment]
Updated to continue testing.

**Comment by laf** [comment]
👍  from me.

Works on two installs, one with rrdcached and one without.

**Comment by laf** [comment]
Tagging @librenms/reviewers

**Comment by laf** [comment]
@murrant needs a rebase - if you'd like to leave that until tomorrow just in case feel free.

**Comment by laf** [comment]
Time until @murrant flips tables......3....2....:)

**Pull request merged**
