### PR TITLE
alerting: Added option to enable/disable option for sending alerts to normal users

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #6499 

By default, adding a normal user and assigning them a device means they will get alerts for this and can't disable it. With this you can now enable / disable that ability.

I've chosen to default this off as I think that should be the fresh install option, this will obviously stop alerts for users who now expect the old way is how it should be for which I've put a notification in. Overall I'm not fussed if we default to on or off but just felt that we shouldn't default to what was the old (broken imho) way and we should do it properly.

### CODE REVIEW

**Comment by laf** [comment]
Actually added schema file now!

**Comment by laf** [comment]
Feel free to push the change to my branch

**Comment by laf** [comment]
If you do change it to default on, please remove the update from notifications as that's no longer relevant.

**Comment by murrant** [comment]
How about different defaults for new and existing installs.

**Comment by laf** [comment]
That would require adding it as false to config.php.default and means users can't just use the webui to make changes to the option. 

We should just pick one way or the other.

**Comment by laf** [comment]
bump

**Pull request merged**
