### PR TITLE
Added fan and temp sensor state discovery Avaya ERS 3500 #7117

### PR DESCRIPTION
**Pull request by tslytsly**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by tslytsly** [comment]
Issue: [#7117](https://github.com/librenms/librenms/issues/7117)

**Comment by tslytsly** [comment]
Not sure why it says I have not signed the CLA, cos I have.

**Comment by laf** [comment]
I've made a few tweaks: https://github.com/librenms/librenms/pull/7134/commits/747b8e176c33d38a5593ce5cc19c8f79ea138b80

Can you give it a test?

**Comment by tslytsly** [comment]
yep works fine.

**Pull request merged**
