### PR TITLE
Add Divisors to Eaton Matrix sensors

### PR DESCRIPTION
**Pull request by peelman**
Please give a short description what your pull request is for

Adds divisors to Eaton Matrix Telecom Inverter sensors.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

Screen Shot 2020-07-06 at 9 26 03 AM

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by peelman** [comment]
Test data for this device family already exists...

**Comment by Jellyfrog** [comment]
And you need to fix it, since it no longer matches with you changes

**Comment by peelman** [comment]
Nothing changed for me...the snmprec matches, save for sterilizing the IP address out of it.

**Comment by Jellyfrog** [comment]
You changed the divisor, and now the test data no longer matches, https://travis-ci.com/github/librenms/librenms/jobs/357903421

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-66-release-changelog-july-2020/12953/1

**Pull request merged**
