### PR TITLE
Application Discovery

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

First attempt.
Only supports snmp extend applications.
This may need more fixes where the extend name != application name

### CODE REVIEW

**Comment by laf** [comment]
What's the need for this?

**Comment by murrant** [comment]
This would save a step when setting up snmp extend scripts.

Basically, after you deploy an snmpd script, the next discovery will enable the applications that you set up.

**Comment by laf** [comment]
Rather than enabling them in the webui?

**Comment by murrant** [comment]
Correct

**Comment by laf** [comment]
What about applications that are no longer detected, no clean up?

**Comment by laf** [comment]
Does this continuously add to the applications table?

**Comment by murrant** [comment]
Hmm, yes, if a use disabled an app, it would get re-enabled.
Might have to fix that.

**Comment by laf** [comment]
Was just about to merge this and realised it needs an entry in `defaults.inc.php`

`$config['discovery_modules']['applications']                   = 1;`

Also should be added to `doc/Support/Discovery Support.md`

**Pull request closed without merging**
