### PR TITLE
feature: Add osTicket Alert Transport

### PR DESCRIPTION
**Pull request by Rosiak**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Add osTicket alert transport using the osTicket API.

### CODE REVIEW

**Comment by Rosiak** [comment]
OSTicket text in sql schema needs to be changed to osTicket.
Will do that when I'm off work.

**Comment by laf** [comment]
I've got a PR outstanding which adds support for proxies to transports so this will need that adding in.

Aside from that, tested the webui side fine. No osTicket install to test further.

**Comment by laf** [comment]
Actually just realised my pr was updated so you'll need to make use of that now to add proxy support.

**Comment by laf** [comment]
bump @Rosiak

**Pull request merged**
