### PR TITLE
Show Date from last discovery and last poll

### PR DESCRIPTION
**Pull request by SourceDoctor**
show in small text "last discovered" and "last polled" date on Device edit page

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @SourceDoctor 
Could you post a screen capture for webui changes like this ? Would help us "see" what's going to change without having to run it locally. 
Thx

**Comment by SourceDoctor** [comment]
will look like that:
image

**Comment by PipoCanaja** [comment]
Just for a test, what would it look like if you put that text into the bar just above  ? Like size on 1 line, discovery followed by poll on 2nd line, all same size (no more small tag ) ?

Capture d’écran 2019-11-23 à 19 52 59

**Comment by SourceDoctor** [comment]
i tried it.
But for my i personal intention the bar will look fat and improper
so i decided for the small tag info beside

**Comment by PipoCanaja** [comment]
OK. All right for me. I'll approuve it and leave it ready for merging for the team.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
