### PR TITLE
Adding support for Redis Sentinel password

### PR DESCRIPTION
**Pull request by banachtarski-91**
Please give a short description what your pull request is for

Currently LibreNMS is unable to auth to redis sentinels that require a password. This is a small change that adds that functionality.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
please update the docs also

**Comment by murrant** [comment]
You are adding configuration setting, which needs added to `config_definitions.json` and `resources/lang/en/settings.php`

**Comment by banachtarski-91** [comment]
@murrant  Forgive me if I'm mistaken, but I'm not seeing entries in either file mentioned for any of the redis settings - sentinel or otherwise. Should I add all of them or is that more appropriate for a different pull request

@Jellyfrog  Dumb question from me: would the best place in the docs be under "Using REDIS" in the Requirements For Distributed Polling?

Thanks guys!

**Comment by Jellyfrog** [comment]
in this file there are some example, so please add your changes there also;

https://github.com/librenms/librenms/blob/8f474dd4d4e8d08b69c7dbf19ed4a3a3ba49d867/doc/Extensions/Dispatcher-Service.md#L84

**Comment by banachtarski-91** [comment]
Going to close and recreate this - CLA issue keeps tripping because of a faulty git setup on a new computer. My bad.

**Pull request closed without merging**
