### PR TITLE
Adding MPLS Interface stats to Nokia SROS Router Interfaces.

### PR DESCRIPTION
**Pull request by mabra94**
This PR adds Nokia SROS MPLS Interface Stats.

Nokia SROS devices collect interface stats but differentiate between IP Interface Stats and MPLS Interface Stats. By polling the Interface Stats based on IF-MIB only SROS will provide IP Interface Stats only. For MPLS networks usually most of their traffic is MPLS encapsulated. This traffic is missed when only fetching IF-MIB based Interface stats. Therefor the MPLS Interface Stats were added to the counters. 

The proposed implementation here keeps it simple:
- in LibreNMS UI there is no separation between the different traffic types
- only the timos specific port poller file was edited; no change in the generic port poller definition

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This behavior seems odd, can you add a before and after image of the graphs?

**Comment by peelman** [comment]
For giggles I pulled this into our instance last night; I was unable to see a difference in graphs...perhaps I'm misunderstanding the intent; but all of our traffic is in L3VPNs' over MPLS, and our graphs _look_ correct...again, i could be missing something.

**Comment by mabra94** [comment]
Will follow this up after the Christmas break including some more explanation on the intention of this PR. (+ adding test data)

**Comment by mabra94** [comment]
> This behavior seems odd, can you add a before and after image of the graphs? (and don't forget to add test data)

Any pointer how to collect test data when LibreNMS is running in a docker container? 
The snmpsim is unable to start as reported here: https://github.com/etingof/snmpsim/issues/156

My LibreNMS system is running as a container. I failed in manually excluding the UID check.

**Comment by peelman** [comment]
Good gravy, what a great explanation @mabra94!

So it appears this is specific to SR 7750's; our IXR7250s and SAS7210s do not differentiate between the traffic that way (our 7750s are still in boxes...waiting on CO overhaul).  So unfortunately I am useless to help in testing this at the moment.

**Comment by mabra94** [comment]
> Good gravy, what a great explanation @mabra94!
> 
> So it appears this is specific to SR 7750's; our IXR7250s and SAS7210s do not differentiate between the traffic that way (our 7750s are still in boxes...waiting on CO overhaul). So unfortunately I am useless to help in testing this at the moment.

Yes indeed, that's correct. There is no such traffic differrentiation on 7250s or 7210s

**Comment by mabra94** [comment]
I am able to collect the SNMP data in order to create a test but the "save-test-data.php" fails for me to finally create the test data. I do have the snmprec though. I would need help on that. 

The doc page says:
_This step requires snmpsim, if you are having issues, the maintainers may help you generate it from the snmprec you created in the previous step._

So maybe someone can give me a hand a based on my snmprec create the actual test data. Thanks!

**Comment by FadhliRais** [comment]
Hi there, I have 210wbx switch nokia switch

and the switch is only use local VPLS service, and SAP port didnt graph the traffic, I wonder this PR can work for me sir ?
since your explanation its only for router interface.


image

**Comment by PipoCanaja** [comment]
> I am able to collect the SNMP data in order to create a test but the "save-test-data.php" fails for me to finally create the test data. I do have the snmprec though. I would need help on that.
> 
> The doc page says: _This step requires snmpsim, if you are having issues, the maintainers may help you generate it from the snmprec you created in the previous step._
> 
> So maybe someone can give me a hand a based on my snmprec create the actual test data. Thanks!

Hi @mabra94 
Please add the snmprec file to the PR, I can generate the JSON file for you.

**Comment by mabra94** [comment]
[timos_timos.txt](https://github.com/librenms/librenms/files/14600188/timos_timos.txt)
Had to change to .txt from .snmprec. That should help creating a test.

**Comment by murrant** [comment]
:/  What was the result of your support ticket with Nokia?

**Comment by peelman** [comment]
> :/  What was the result of your support ticket with Nokia?

who are you asking?

**Comment by murrant** [comment]
Anyone.  This seems to be a workaround for a bug as not all models show this behavior.

**Comment by peelman** [comment]
eh...the problem Fadhli has is resulting for those being Nuage boxes; those run a bastard version of SROS similar to the 7210s, but different enough that even they would probably require some special sauce. 

i don't think it's a bug so much as we need to keep up with Nokias MIBs better because they have been on a streak of changing their services MIBs at each release. 

that said, i now have 7750s in the network i can test against, running R23.9R5, so i'll try to set aside some time this week to button this up and get this PR up to master/main so it can be reviewed and merged with at least the 23.9 MIBs.

**Comment by mabra94** [comment]
Thanks @peelman to look into this again. 
I have to admit that I forgot about this. But your explanation is correct, not all Nokia devices support the differentiation between IP and MPLS traffic (which is not a bug but rather caused by different chipsets, system capabilities, etc.) and hence, this PR does not apply to all boxes. 
Nonetheless, as far as I remember, this PR would also not break anything for devices that does not support this differentiation. It should simply show the IP Stats for devices where separated MPLS Stats counters are not available. 
Would love to see this being merged and closed :)

**Comment by murrant** [comment]
#
Thanks for your pull request. You haven't updated this PR in some time. Closing it for now.

Please feel free to reopen, I would love to see your changes added to LibreNMS.

**Pull request closed without merging**
