### PR TITLE
app: mailcow-dockerized postfix stats

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

requires https://github.com/librenms/librenms-agent/pull/270

### CODE REVIEW

**Comment by kkrumm1** [comment]
Can you please add test data?

**Comment by crcro** [comment]
@kkrumm1 ... added test-data, sorry for delay

**Comment by SourceDoctor** [comment]
@crcro 
travis fails because of a missing testfile, could you please take a look on it?

**Comment by crcro** [comment]
@SourceDoctor 
finally figured it out :)

**Comment by SourceDoctor** [comment]
@librenms/reviewers someone here who can verify functionality?

**Comment by crcro** [comment]
mailcow_01
mailcow_02

**Comment by jozefrebjak** [comment]
I am getting error

```
mailcow-postfix  

SNMP['/usr/bin/snmpget' '-v2c' '-c' 'COMMUNITY' '-Oqv' '-m' 'NET-SNMP-EXTEND-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/supermicro:/opt/librenms/mibs/dell' 'udp:HOSTNAME:161' 'nsExtendOutputFull.15.109.97.105.108.99.111.119.45.112.111.115.116.102.105.120']

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?filters=%7B%22name%22%3A%7B%22postfix-mailcow%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Traceback (most recent call last):
  File \"/etc/snmp/mailcow-dockerized-postfix\", line 61, in <module>
    mcd_postfix_data = get_output().split('messages')
  File \"/etc/snmp/mailcow-dockerized-postfix\", line 47, in get_output
    return subprocess.check_output(cli_command(), shell=True).decode('utf8')
  File \"/etc/snmp/mailcow-dockerized-postfix\", line 42, in cli_command
    + \"m \" + cli_get_docker_container() + \"| pflogsumm --smtpd-stats\"
  File \"/etc/snmp/mailcow-dockerized-postfix\", line 37, in cli_get_docker_container
    return subprocess.check_output(\"docker ps -qf name=postfix-mailcow\", shell=True).decode('utf8').strip()
  File \"/usr/lib/python3.5/subprocess.py\", line 626, in check_output
    **kwargs).stdout
  File \"/usr/lib/python3.5/subprocess.py\", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'docker ps -qf name=postfix-mailcow' returned non-zero exit status 1  

  


mailcow-postfix:-3:Invalid JSON

SQL[UPDATE `applications` set `app_state`=?,`app_status`=?,`timestamp`=NOW() WHERE `app_id` = ? ["OK","",54] 0.75ms] 
```

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-62-release-changelog-march-2020/11423/1

**Pull request merged**
