### PR TITLE
add high memory alert templates for Linux

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by ottorei — APPROVED** [review]

**Comment by VVelox** [comment]
now is linux specific

**Review by ottorei — APPROVED** [review]

**Comment by Jellyfrog** [comment]
Does mempool_perc take caching into consideration?

**Comment by VVelox** [comment]
> Does mempool_perc take caching into consideration?

As far as I know this is updated when the device is polled.

So far this has worked well at work for finding places where Suricata needs some more tuning before it causes issues.

**Comment by VVelox** [comment]
I know it alerts go away at next polling period when I tweak Suricata mem settings and give the running instances of it on a machine a kick.

**Comment by Jellyfrog** [comment]
I mean the Linux cached memory. Free vs cached vs available.

**Comment by VVelox** [comment]
As far as I know, no it does not.

That said this is why this alert is Linux only. FreeBSD that stat includes caches, so it is totally unreliable, which is strange as there is also a cache one as well.

**Comment by murrant** [comment]
Not sure this is quite there yet. The sysDescr starts with Linux seems like an error prone heuristic.

Been awhile since I looked at the memory stuff, does mempool_perc include or exclude file cache usage?

**Comment by eskyuu** [comment]
On Linux systems, the mempool_class="system" excludes buffers and cache, so it is an accurate representation of actual memory load.

**Comment by eskyuu** [comment]
> Not sure this is quite there yet. The sysDescr starts with Linux seems like an error prone heuristic.
> 
> Been awhile since I looked at the memory stuff, does mempool_perc include or exclude file cache usage?

Would devices.os == 'linux' be better?

I also think that mempools.mempool_descr == 'Physical Memory' is redundant based on what I see in our database.

**Comment by VVelox** [comment]
@murrant @eskyuu Updates made. :)

**Review by murrant — APPROVED** [review]

**Pull request merged**
