### PR TITLE
Delete Orphaned Dashboards

### PR DESCRIPTION
**Pull request by electrocret**
Delete Orphaned Dashboards when user is deleted.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Wondering if it's kept since it can be shared?

**Comment by murrant** [comment]
I think @Jellyfrog is correct.  We could delete non-shared dashboards.  Probably need a better process to handle shared ones.  Like change the owner when the owner is deleted.

**Comment by Jellyfrog** [comment]
I'd suggest adding a line before this that moves all shared dashboards to the first admin user.

**Comment by electrocret** [comment]
Heh, I originally made this PR when a user made a ton of dashboards and wanted help deleting them. I recognize that deleting them isn't ideal under most conditions. I'll look into adding some logic when I have a chance.

**Comment by electrocret** [comment]
Will resubmit whenever I have time to write the logic y'all described.

**Pull request closed without merging**
