### PR TITLE
Added sensor monitoring for IBM 3584 Tape Library

### PR DESCRIPTION
**Pull request by MelonicOverlord**
Includes some sensor data monitoring for IBM Tape Libraries (in particular the 3584 but may work for others?)

Updated logo to show correctly as IBM, device OS etc and monitoring for Fibre status on drives. 

```
lnms dev:check completed succesfully -- 

Time: 02:58.354, Memory: 939.50 MB

OK (732 tests, 6254 assertions)
```

```
OS: ibmtl
Module(s): all
Variant: IBM Tape Library 7420

Capturing Data:  sysDescr.0 sysObjectID.0 SNMPv2-MIB::sysObjectID.0 SNMPv2-MIB::sysDescr.0 SNMPv2-MIB::sysName.0 .1.3.6.1.4.1.1166.1.621.14.2.0 .1.3.6.1.4.1.8072.1.3.2.3.1.2.6.100.105.115.116.114.111 .1.3.6.1.4.1.12148.10.2.6.0 .1.3.6.1.4.1.39165.1.1.0 SNMPv2-MIB::sysLocation.0 sysContact.0 .1.3.6.1.4.1.14851.3.1.4.2.0 .1.3.6.1.4.1.14851.3.1.3.2.0 .1.3.6.1.4.1.14851.3.1.3.4.0 ifDescr ifName ifAlias ifType ifOperStatus IF-MIB::ifStackStatus ENTITY-MIB::entPhysicalTable hrProcessorLoad .1.3.6.1.4.1.2021.11.11.0 hrStorageTable hrMemorySize.0 memTotalSwap.0 memAvailSwap.0 memTotalReal.0 memAvailReal.0 memBuffer.0 memCached.0 memSysAvail.0 IP-MIB::ipAdEntIfIndex IP-MIB::ipAdEntNetMask.10.32.4.58 IP-MIB::ipAdEntNetMask.127.0.0.1 IP-MIB::ipAddressIfIndex.ipv6 ipv6AddrPfxLength SNIA-SML-MIB::scsiProtocolControllerTable entPhysicalDescr fileSystemSpaceTable ARICENT-ISS-MIB::issSwitchCurrentFlashUsage.0 dskTable hrProcessorTable hrDeviceTable LLDP-MIB::lldpRemTable LLDP-V2-MIB::lldpV2RemTable IP-MIB::ipNetToPhysicalPhysAddress IP-MIB::ipNetToMediaPhysAddress BGP4-MIB::bgpLocalAs.0 dot1dBasePortIfIndex dot1qVlanVersionNumber.0 diskIOEntry BRIDGE-MIB::dot1dStpProtocolSpecification.0 dot1qTpFdbPort dot1dTpFdbPort SNMPv2-MIB::sysUpTime.0 SNMP-FRAMEWORK-MIB::snmpEngineTime.0 HOST-RESOURCES-MIB::hrSystemUptime.0 .1.3.6.1.4.1.14851.3.1.12.2.1.4.1 .1.3.6.1.4.1.14851.3.1.12.2.1.4.2 .1.3.6.1.4.1.14851.3.1.12.2.1.4.3 .1.3.6.1.4.1.14851.3.1.12.2.1.4.4 IP-MIB::icmpInMsgs.0 IP-MIB::icmpOutMsgs.0 IP-MIB::icmpInErrors.0 IP-MIB::icmpOutErrors.0 IP-MIB::icmpInEchos.0 IP-MIB::icmpOutEchos.0 IP-MIB::icmpInEchoReps.0 IP-MIB::icmpOutEchoReps.0 IP-MIB::icmpInDestUnreachs.0 IP-MIB::icmpOutDestUnreachs.0 IP-MIB::icmpInParmProbs.0 IP-MIB::icmpInTimeExcds.0 IP-MIB::icmpInSrcQuenchs.0 IP-MIB::icmpInRedirects.0 IP-MIB::icmpInTimestamps.0 IP-MIB::icmpInTimestampReps.0 IP-MIB::icmpInAddrMasks.0 IP-MIB::icmpInAddrMaskReps.0 IP-MIB::icmpOutTimeExcds.0 IP-MIB::icmpOutParmProbs.0 IP-MIB::icmpOutSrcQuenchs.0 IP-MIB::icmpOutRedirects.0 IP-MIB::icmpOutTimestamps.0 IP-MIB::icmpOutTimestampReps.0 IP-MIB::icmpOutAddrMasks.0 IP-MIB::icmpOutAddrMaskReps.0 IP-MIB::ipForwDatagrams.0 IP-MIB::ipInDelivers.0 IP-MIB::ipInReceives.0 IP-MIB::ipOutRequests.0 IP-MIB::ipInDiscards.0 IP-MIB::ipOutDiscards.0 IP-MIB::ipOutNoRoutes.0 IP-MIB::ipReasmReqds.0 IP-MIB::ipReasmOKs.0 IP-MIB::ipReasmFails.0 IP-MIB::ipFragOKs.0 IP-MIB::ipFragFails.0 IP-MIB::ipFragCreates.0 IP-MIB::ipInUnknownProtos.0 IP-MIB::ipInHdrErrors.0 IP-MIB::ipInAddrErrors.0 IP-FORWARD-MIB::ipCidrRouteNumber.0 SNMPv2-MIB::snmpInPkts.0 SNMPv2-MIB::snmpOutPkts.0 SNMPv2-MIB::snmpInBadVersions.0 SNMPv2-MIB::snmpInBadCommunityNames.0 SNMPv2-MIB::snmpInBadCommunityUses.0 SNMPv2-MIB::snmpInASNParseErrs.0 SNMPv2-MIB::snmpInTooBigs.0 SNMPv2-MIB::snmpInNoSuchNames.0 SNMPv2-MIB::snmpInBadValues.0 SNMPv2-MIB::snmpInReadOnlys.0 SNMPv2-MIB::snmpInGenErrs.0 SNMPv2-MIB::snmpInTotalReqVars.0 SNMPv2-MIB::snmpInTotalSetVars.0 SNMPv2-MIB::snmpInGetRequests.0 SNMPv2-MIB::snmpInGetNexts.0 SNMPv2-MIB::snmpInSetRequests.0 SNMPv2-MIB::snmpInGetResponses.0 SNMPv2-MIB::snmpInTraps.0 SNMPv2-MIB::snmpOutTooBigs.0 SNMPv2-MIB::snmpOutNoSuchNames.0 SNMPv2-MIB::snmpOutBadValues.0 SNMPv2-MIB::snmpOutGenErrs.0 SNMPv2-MIB::snmpOutGetRequests.0 SNMPv2-MIB::snmpOutGetNexts.0 SNMPv2-MIB::snmpOutSetRequests.0 SNMPv2-MIB::snmpOutGetResponses.0 SNMPv2-MIB::snmpOutTraps.0 SNMPv2-MIB::snmpSilentDrops.0 SNMPv2-MIB::snmpProxyDrops.0 UDP-MIB::udpInDatagrams.0 UDP-MIB::udpOutDatagrams.0 UDP-MIB::udpInErrors.0 UDP-MIB::udpNoPorts.0 TCP-MIB::tcpActiveOpens.0 TCP-MIB::tcpPassiveOpens.0 TCP-MIB::tcpAttemptFails.0 TCP-MIB::tcpEstabResets.0 TCP-MIB::tcpCurrEstab.0 TCP-MIB::tcpInSegs.0 TCP-MIB::tcpOutSegs.0 TCP-MIB::tcpRetransSegs.0 TCP-MIB::tcpInErrs.0 TCP-MIB::tcpOutRsts.0 hrSystemMaxProcesses.0 hrSystemProcesses.0 hrSystemNumUsers.0 systemStats laLoadInt.1 laLoadInt.2 laLoadInt.3 ipSystemStats ifXEntry ifEntry dot3StatsDuplexStatus dot1qPvid OSPF-MIB::ospfGeneralGroup
Saved snmprec data /opt/librenms/tests/snmpsim/ibmtl_ibm tape library 7420.snmprec
```

Let me know if any further test data is required. All seems to be working as expected. 

Before

After

**Thanks to @laf for the support, this is my first contribution.**

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Yes @MelonicOverlord, could you please collect test-data (at least the SNMPREC file) and attach it to this PR. If you can also generate and attach the JSON, even better.

**Comment by MelonicOverlord** [comment]
No problem. Will generate this later or tomorrow and get it to you.

**Comment by MelonicOverlord** [comment]
[snmprecoutput.txt](https://github.com/user-attachments/files/18176993/snmprecoutput.txt)
[snmprec.txt](https://github.com/user-attachments/files/18176985/snmprec.txt)

Attached is the SNMPREC

**Comment by PipoCanaja** [comment]
@MelonicOverlord File looks good. Please put it directly into the PR in the `~/tests/snmpsim` directory. And I can generate the JSON file for you.

**Review by laf — APPROVED** [review]
LGTM and thanks for contributing @MelonicOverlord :)

**Review by laf — APPROVED** [review]

**Review by PipoCanaja — APPROVED** [review]

**Comment by PipoCanaja** [comment]
Thanx @MelonicOverlord !

**Pull request merged**
