### PR TITLE
Added description of AD configuration options

### PR DESCRIPTION
**Pull request by awlx**
Stumbled across this description and had to search the code what really needs to be set. So I thought this might be a better description.

### CODE REVIEW

**Comment by laf** [comment]
I think it would be better not to use <> for the names. Maybe even be more explicit what can be customised.

**Comment by awlx** [comment]
Well I used this: http://docs.librenms.org/Installation/Installation-(RHEL-CentOS)/ as an example, they use <> too.

And I thought it will be clear this way. Well at least better then before ;). But maybe it's better to change it to "Replace <ad-admingroup> with your desired Active Directory Admingroup".

**Comment by laf** [comment]
The install docs specifically tell people to replace <ip> with the IP though, if you do that it will be fine but it just needs to be clear.

**Comment by awlx** [comment]
Ok, changed it.

**Comment by laf** [comment]
Thanks :)

**Pull request merged**
