### PR TITLE
Convert blade to panel component

### PR DESCRIPTION
**Pull request by Jellyfrog**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Blocked by #11952

**Comment by Jellyfrog** [comment]
View the diff without whitespaces...

**Comment by murrant** [comment]
Certainly saves a lot of boiler plate

**Comment by murrant** [comment]
@Jellyfrog looks good, my only question is:  Should the component be called card?  (considering panels are renamed to cards in bootstrap 4)

**Comment by Jellyfrog** [comment]
Sure. I named it after thecss class

**Comment by murrant** [comment]
I only mention it if we plan to move to bootstrap 4.  Maybe leaving it on panel makes sense while we are on bootstrap 3 and change it when we change to bootstrap 4.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-66-release-changelog-july-2020/12953/1

**Pull request merged**
