### PR TITLE
Add a deprecated warning to the front pages

### PR DESCRIPTION
**Pull request by Jellyfrog**
This is a preparation for https://github.com/librenms/librenms/pull/10757

Looks like this:
image

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Looks clear and good to me. I don't have a clue how many users are using these. We may add a link to the PR which will deprecate them, to ensure the users have a chance to let us know they are still using it.

**Comment by murrant** [comment]
Yeah, having a little clearer action would be helpful.  Like:

Overview pages will change to a new format, this page will not be converted to the new format and will be removed in the next release.  For more info: <link>

**Comment by laf** [comment]
You can use this link: https://t.libren.ms/overview. Takes you to a community post where we describe what's going on?

**Comment by Jellyfrog** [comment]
Updated

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
