### PR TITLE
Add support for polling Gaia active connections and firewall statistics

### PR DESCRIPTION
**Pull request by martinberg**
Add support for polling Gaia active connections and firewall statistics
Stats being collected: packets accepted/rejected/logged/dropped

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This looks good to me, everything ready?

**Comment by martinberg** [comment]
> 
> 
> This looks good to me, everything ready?

Go ahead :)

**Comment by martinberg** [comment]
@murrant Added support for lograte data to be collected as well. If I should put this in a new PR, let me know.
However, I'm not sure if I got the testdata how you want it. 
The logging server which returns the lograte value doesn't run on a Checkpoint appliance but on a regular server. The naming of the files might not be correct or the hardware type in the snmpsim data might break something down the road. 
Let me know if this is fine or if I should regenerate the snmpsim data.

**Comment by martinberg** [comment]
This PR is no longer up to date and I will make a new one in the coming days with more features added and some cleaned up code.

**Pull request closed without merging**
