### PR TITLE
Add JiraServiceManagement Transport

### PR DESCRIPTION
**Pull request by mhamzak008**
Adding a new transport to work with the alerts in JSM 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
The link from the docs to the JSM docs doesn't work. Do you have the correct link so I can check this?

**Comment by ozlemmcokuk** [comment]
Hi @laf 
Thank you for the update 🙏 Let us update this part

**Comment by laf** [comment]
Thanks both, the only other thing I'd say then is this should be called Jira Service Management rather than just JSM so it's clear what the transport is for.

**Comment by PipoCanaja** [comment]
Hi @mhamzak008,
Thanx for your contribution !

**Comment by murrant** [comment]
Kinda scary that this ties our internal data structure to external functionality.  Likely this will break at some point in the future.

**Pull request merged**
