### PR TITLE
alphabatize doc/Extensions/Applications.md 

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
This doesn't really make sense to me, it's not following the order of the list. I think Agent should be always at the top anyway. Actually this whole section could do with a revamp, maybe one application per file would be best seeing we have quite a few.

**Comment by murrant** [comment]
I don't like the Agent being at the top because then you read from top down and conclude you need to install the agent.  What do you think about moving the agent install to a separate page?

**Comment by laf** [comment]
No ones going to read that entire page and realise they need the agent at the end. Logically you'd assume the first step was to install the agent but yes the doc needs a revamp and the agent install can be one of the first on it's own.

**Comment by murrant** [comment]
Agent Setup broken out to it's own page.

**Pull request merged**
