### PR TITLE
refactor: Use snmp.version config option to allow users to set versions available

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

`$config['snmp']['version']` was unused before. This allows people to disable snmp versions they don't need.

### CODE REVIEW

**Comment by murrant** [comment]
Leave it in defaults, just commented.

**Comment by trcyberoptic** [comment]
initial refector works for me, thanks!

**Comment by laf** [comment]
> @laf Instead of setting in defaults, use the default option of Condig::get(). Put v2c first by default, as we try them in order, and trying other versions slows it down a lot. Plus we don't want to add devices by v1 if we can help it.

Maybe I should just drop the webui support in this PR then I can default this back to just v2c but it at least allows people to customise it.

Why set the defaults in Config::get() as you'd have to do it each time it's called (which would only be once now but probably not in the future?)

**Comment by laf** [comment]
I've removed the addhost.php changes so this now maintains backwards compatibility.

**Pull request merged**
