### PR TITLE
Update JS deps

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
Are the packages automatically updated on instances?
Didn't find anything in Repository referencing to packages.json

**Comment by PipoCanaja** [comment]
@murrant Shouldn't this file be ignored and removed from master ? 
` html/mix-manifest.json `

**Comment by murrant** [comment]
@SourceDoctor app.js contains the updated code.   We don't run npm on client instances at this time.

@PipoCanaja right now we need to update it when we update the JS files, for the js language files that are generated on install, it would make sense to remove it.  It is required for mix() blade directives so it knows when to break the cache.

**Comment by PipoCanaja** [comment]
All right :) this part of the code is completely dark for me, I leave it to you 👍

**Comment by PipoCanaja** [comment]
@murrant Shouldn't we remove it from master (as it is generated by daily anyway) ? That would allow daily to stop failing every night :D

**Comment by murrant** [comment]
it isn't generated by daily, only the lang files are. `@php artisan vue-i18n:generate --multi-locales --format=umd`

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
