### PR TITLE
Update eatonups.yaml

### PR DESCRIPTION
**Pull request by boudreau**
added support for Eaton ups model 9PX 2000 RT

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
This also needs an OS test unit file: http://docs.librenms.org/Developing/Support-New-OS/#os-test-units

**Comment by boudreau** [comment]
I have an error when I try that script, any tips?

./scripts/pre-commit.php -u --snmpsim
Starting snmpsimd...
Running unit tests... PHP Fatal error:  Class 'PHPUnit_TextUI_Command' not found in /var/www/librenms/vendor/phpunit/phpunit/phpunit on line 52
failed

snmpsimd: output at /tmp/snmpsimd.log
-bash-4.2$

**Comment by laf** [comment]
http://docs.librenms.org/Developing/Validating-Code/#validating-code

You need composer to install the dependencies.

**Comment by murrant** [comment]
I think you've installed phpunit 6.0 on your system.  If you install it with composer in the librenms directory, it will fix that.

**Comment by laf** [comment]
@boudreau Any update?

**Comment by boudreau** [comment]
not yet, have to build another librenms server.

**Comment by murrant** [comment]
OK, here we go with these again:
.1.3.6.1.4.1.534.1 = powerware which was bought by eaton and is generally detected as eatonups and has decent support there. Suggestion: remove powerware os
.1.3.6.1.4.1.534.2 = eaton powerxpert fine as eatonups
.1.3.6.1.4.1.534.6 = eatonpdu fine as is

.1.3.6.1.4.1.705. = mgeups which seems to be detected mixed as mgeups and eatonups.  mgeups have multiple lines, was purchased by Eaton, datacenter class ups were sold to APC (Which is owned by Schnieder Electric now)  But Eaton retained the network/server class UPS. 

Suggestion... no clue.  Possibly keep mgeups os and change the icon and text to Eaton


Here is the stats data:
Powerware:
|Total|OS       |sysObjectID           | sysDescr |
|    3|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V3.38 |
|    3|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V4.38 |
|    3|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V4.20 |
|    1|eatonups |.1.3.6.1.4.1.534.2.12 | Linux hostname 2.6.36 #1 Mon Jun 23 15:31:56 EDT 2014 ppc |
|    1|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V3.28 |
|    1|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V4.26 |
|    1|eatonups |.1.3.6.1.4.1.534.2.12 | Linux hostname 3.2.2 #1 PREEMPT Mon Sep 26 12:17:28 CEST 2016 ppc |
|    1|eatonpdu |.1.3.6.1.4.1.534.6.6.7| Eaton ePDU MA 1P IN:L6-30P 24A OUT:20xC13, 4xC19 |
|    1|powerware|.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V4.20 |
|    1|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V4.28 |
|    1|eatonups |.1.3.6.1.4.1.534.1    | ConnectUPS Web/SNMP Card V4.34 |


MGE:
|Total|OS      |sysObjectID         | sysDescr |
|   43|eatonups|.1.3.6.1.4.1.705.1  | Eaton 5PX 2200 |
|   35|eatonups|.1.3.6.1.4.1.705.1  | Eaton 5PX 3000 |
|    9|mgeups  |.1.3.6.1.4.1.705.1  | EX 2200 |
|    4|mgeups  |.1.3.6.1.4.1.705.1  | EX 1000 RT2U |
|    3|eatonups|.1.3.6.1.4.1.705.1  | Eaton 5PX 1500 |
|    3|mgeups  |.1.3.6.1.4.1.705.1  | Powerware 9130 1000 |
|    2|mgeups  |.1.3.6.1.4.1.705.1  | Eaton 9PX 6000 |
|    2|mgeups  |.1.3.6.1.4.1.705.1.2| Galaxy 3000 30 kVA |
|    2|mgepdu  |.1.3.6.1.4.1.705.2  | MGE Switched PDU |
|    1|eatonups|.1.3.6.1.4.1.705.1  | Eaton 5P 3000 |
|    1|mgeups  |.1.3.6.1.4.1.705.1  | Eaton 9PX 8000 |
|    1|mgeups  |.1.3.6.1.4.1.705.1  | UPS |
|    1|mgeups  |.1.3.6.1.4.1.705.1  | IBM 11000VA/10000W Rack HV UPS |
|    1|mgeups  |.1.3.6.1.4.1.705.1.2| EX 3000 |
|    1|mgeups  |.1.3.6.1.4.1.705.1  | Eaton 9PX 5000 |
|    1|mgeups  |.1.3.6.1.4.1.705.1  | 9P 80kW |

**Pull request closed without merging**
