### PR TITLE
Add support for HP Printer

### PR DESCRIPTION
**Pull request by Clete2**
Add support for HP printers in general. This one happens to be a Photosmart 5520 series. Hopefully someone else can come along and add more OIDs.

My printer was being discovered as a generic device, so I copied the canon printer file and changed it to fit my needs.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @Clete2 
Thanx for your contribution. Any chance you could collect real-world data from the printer using the collect-snmp-data script as described here  : 
https://docs.librenms.org/Developing/os/Test-Units/

Thanx

**Comment by murrant** [comment]
There is already an HP printer OS.  jetdirect

**Comment by Clete2** [comment]
> There is already an HP printer OS. jetdirect

This is a home printer, not a print server. I think Jetdirect is a server of sorts. This is a single printer with simple wifi connectivity and is branded differently.

@PipoCanaja I tried that script but getting this error. Do you know why?

```shell
~> sudo -u librenms ./scripts/collect-snmp-data.php -h 192.168.1.204 -o hpprinter -v photosmart -d
OS: hpprinter
Module(s): all
Variant: photosmart

Capturing Data:
   TypeError

  Argument 1 passed to LibreNMS\Cache\Device::setPrimary() must be of the type int, null given, called in /opt/librenms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261

  at LibreNMS/Cache/Device.php:48
     44▕      * This will be fetched by getPrimary()
     45▕      *
     46▕      * @param int $device_id
     47▕      */
  ➜  48▕     public function setPrimary(int $device_id)
     49▕     {
     50▕         $this->primary = $device_id;
     51▕     }
     52▕

      +1 vendor frames
  2   LibreNMS/Util/ModuleTestHelper.php:178
      Illuminate\Support\Facades\Facade::__callStatic("setPrimary")

  3   LibreNMS/Util/ModuleTestHelper.php:145
      LibreNMS\Util\ModuleTestHelper::collectOids()
```

**Comment by PipoCanaja** [comment]
> @PipoCanaja I tried that script but getting this error. Do you know why?
`-h` is expecting a device_id number, not an ip-address of device. In order to find it, just move your mouse over a link to the device, or look at your browser address_bar. 

That being said, as @murrant said, jetdirect is already existing, and jetdirect is the name at HP for any IP connectivity module. Professionnal or home printer does not make a difference here it seems. 

So you should probably give a try, and add you OID to the existing jetdirect yaml instead of creating a new one. And see how it goes from there. 

(don't forget to remove your new YAML file before modifying the existing jetdirect one of course).

**Review by murrant — CHANGES_REQUESTED** [review]
jetdirect = all HP printers with network.  please add to jetdirect

**Comment by Clete2** [comment]
@murrant will do. sorry for delay. Been busy with other work

**Comment by murrant** [comment]
@Clete2 either open a new PR or push and drop a comment here and we will reopen.  Closing this for now.  Thanks.

**Pull request closed without merging**
