### PR TITLE
update fail2ban to have better stat graphs and and fix generic_stats graph.php

### PR DESCRIPTION
**Pull request by VVelox**
Now uses generic_stats.inc.php so one has a far better idea of trends.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
Can you include a before after picture? or are they the same?

**Comment by VVelox** [comment]
@murrant 

Before: https://i.imgur.com/5xi8dnW.png
After: https://i.imgur.com/c3zn0o6.png

Standard generic_stats.inc.php graph, which for a single DS graph is way better than generic_v3_multiline.inc.php as the rest lack lots of meaningful additional detail for viewing trends etc.

**Comment by VVelox** [comment]
newest examples...

general: https://cdn.discordapp.com/attachments/463435361100627988/1072532841063260230/Untitled.png
mini: https://cdn.discordapp.com/attachments/463435361100627988/1072532367689920652/Untitled.png

**Review by ottorei — COMMENTED** [review]
Testing this PR on my system at the moment.

**Comment by VVelox** [comment]
@ottorei How you liking it? :)

**Review by Jellyfrog — DISMISSED** [review]

**Comment by Jellyfrog** [comment]
Ill leave the merging to @murrant tho

**Comment by VVelox** [comment]
This includes a DEF for ds01d being added twice. 

This issue  went unnoticed as some of rrd don't care if it is or not.

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
