### PR TITLE
Escape SNMP & IPMI shell commands

### PR DESCRIPTION
**Pull request by murrant**
hopefully doesn't break anything
Mostly issues with snmp oids and options containing spaces.  Try to remove all of those.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I was using this code for testing which helped me see where the bad command was.
Thoughts on including it?
```php
    if ($proc->getExitCode()) {
        throw new Exception('Snmp failed: ' . $proc->getErrorOutput());
    }
```

**Comment by laf** [comment]
> if ($proc->getExitCode()) { throw new Exception('Snmp failed: ' . $proc->getErrorOutput()); }

If it stops polling / discovery then naturally no but if it's part of debug output to just capture failed calls then yes.

Discovery issues (some may exist in the current codebase I haven't checked).

VLAN discovery
```
sh: line 0: exec: -A: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
SNMP['-a' 'MD5' '-A' 'pass' '-u' 'user' '-OQUsetX' '-m' 'BRIDGE-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:hostname:161' 'dot1dBasePortIfIndex']
```

discovery-arp

```
Warning: Cannot use a scalar value as an array in /opt/librenms/includes/rewrites.php on line 83

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   14.1206    9646672   2. discover_device() /opt/librenms/discovery.php:120
   18.0932   10064824   3. include('/opt/librenms/includes/discovery/discovery-arp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   18.0983   10147888   4. cleanPort() /opt/librenms/includes/discovery/discovery-arp.inc.php:44


Warning: Cannot use a scalar value as an array in /opt/librenms/includes/rewrites.php on line 84

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   14.1206    9646672   2. discover_device() /opt/librenms/discovery.php:120
   18.0932   10064824   3. include('/opt/librenms/includes/discovery/discovery-arp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   18.0983   10147888   4. cleanPort() /opt/librenms/includes/discovery/discovery-arp.inc.php:44


Warning: Cannot use a scalar value as an array in /opt/librenms/includes/rewrites.php on line 85

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   14.1206    9646672   2. discover_device() /opt/librenms/discovery.php:120
   18.0932   10064824   3. include('/opt/librenms/includes/discovery/discovery-arp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   18.0983   10147888   4. cleanPort() /opt/librenms/includes/discovery/discovery-arp.inc.php:44

SQL[SELECT `devices`.*, `location`, `lat`, `lng` FROM `devices` LEFT JOIN locations ON `devices`.location_id=`locations`.`id` WHERE `device_id` = ? [null] 2.25ms]
SQL[SELECT * FROM devices_attribs WHERE `device_id` = ? [null] 0.93ms]
No OS to loadSQL[SELECT * FROM `vrf_lite_cisco` WHERE `device_id` = ? [null] 0.84ms]

Warning: Cannot use a scalar value as an array in /opt/librenms/includes/rewrites.php on line 102

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   14.1206    9646672   2. discover_device() /opt/librenms/discovery.php:120
   18.0932   10064824   3. include('/opt/librenms/includes/discovery/discovery-arp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   18.0983   10147888   4. cleanPort() /opt/librenms/includes/discovery/discovery-arp.inc.php:44


Warning: array_key_exists() expects parameter 2 to be array, null given in /opt/librenms/includes/common.php on line 1034

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   14.1206    9646672   2. discover_device() /opt/librenms/discovery.php:120
   18.0932   10064824   3. include('/opt/librenms/includes/discovery/discovery-arp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   18.1286   11977856   4. object_is_cached() /opt/librenms/includes/discovery/discovery-arp.inc.php:61
   18.1286   11977880   5. array_key_exists() /opt/librenms/includes/common.php:1034
```

cisco-otv

```
Warning: Illegal offset type in /opt/librenms/LibreNMS/Component.php on line 162

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   19.4702   12036408   2. discover_device() /opt/librenms/discovery.php:120
   23.1737   12214688   3. include('/opt/librenms/includes/discovery/cisco-otv.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   23.1745   12271456   4. LibreNMS\Component->getComponents() /opt/librenms/includes/discovery/cisco-otv.inc.php:62


Warning: Illegal offset type in /opt/librenms/LibreNMS/Component.php on line 165

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   19.4702   12036408   2. discover_device() /opt/librenms/discovery.php:120
   23.1737   12214688   3. include('/opt/librenms/includes/discovery/cisco-otv.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   23.1745   12271456   4. LibreNMS\Component->getComponents() /opt/librenms/includes/discovery/cisco-otv.inc.php:62

```

ipv4-addresses
```
sh: line 0: exec: -A: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
SNMP['-a' 'MD5' '-A' 'pass' '-u' 'user' '-Oqv' '-m' 'IP-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:hostname:161' 'ipAdEntNetMask.']
```

ipv6-addresses
```
sh: line 0: exec: -A: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
SNMP['-a' 'MD5' '-A' 'pass' '-u' 'user' '-OsqnU' '-Ln' '-m' 'IPV6-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:hostname:161' 'ipv6AddrPfxLength']
```

arp-table
```
sh: line 0: exec: -A: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
SNMP['-a' 'MD5' '-A' 'pass' '-u' 'user' '-OQUsetX' '-m' 'IP-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:hostname:161' 'ipNetToMediaPhysAddress']
```

ntp
```
Warning: Illegal offset type in /opt/librenms/LibreNMS/Component.php on line 162

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   19.4702   12036408   2. discover_device() /opt/librenms/discovery.php:120
   28.2067   13045880   3. include('/opt/librenms/includes/discovery/ntp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   28.2071   13061224   4. include('/opt/librenms/includes/discovery/ntp/cisco.inc.php') /opt/librenms/includes/discovery/ntp.inc.php:31
   28.2958   13060224   5. LibreNMS\Component->setComponentPrefs() /opt/librenms/includes/discovery/ntp/cisco.inc.php:119
   28.2958   13060224   6. LibreNMS\Component->getComponents() /opt/librenms/LibreNMS/Component.php:299


Warning: Illegal offset type in /opt/librenms/LibreNMS/Component.php on line 165

Call Stack:
    0.0006     414944   1. {main}() /opt/librenms/discovery.php:0
   19.4702   12036408   2. discover_device() /opt/librenms/discovery.php:120
   28.2067   13045880   3. include('/opt/librenms/includes/discovery/ntp.inc.php') /opt/librenms/includes/discovery/functions.inc.php:179
   28.2071   13061224   4. include('/opt/librenms/includes/discovery/ntp/cisco.inc.php') /opt/librenms/includes/discovery/ntp.inc.php:31
   28.2958   13060224   5. LibreNMS\Component->setComponentPrefs() /opt/librenms/includes/discovery/ntp/cisco.inc.php:119
   28.2958   13060224   6. LibreNMS\Component->getComponents() /opt/librenms/LibreNMS/Component.php:299
```

fdb-table
```
sh: line 0: exec: -A: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
SNMP['-a' 'MD5' '-A' 'pass' '-u' 'user' '-OQUsetX' '-m' 'BRIDGE-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/cisco' 'udp:hostname:161' 'dot1dBasePortIfIndex']
```

**Comment by murrant** [comment]
@laf oh, I think it is snmpv3, The tests don't test that.

**Comment by murrant** [comment]
I went through and confirmed all the updates that are included here (not sure if I missed any but I couldn't find any more).

I'm not going to include the Exception, while it makes it easier to pinpoint the issue, other parts of the code aren't ready to handle exceptions from snmp requests.

**Pull request merged**
