### PR TITLE
AOS Advanced Support.

### PR DESCRIPTION
**Pull request by joseUPV**
This contribution is work of paulierco and JoseUPV
Modifies #10672 (split aos os in three, aos, aos6 and aos7)
Modifies #11145 (split aos os in three, aos, aos6 and aos7)
Continues #11322 

Notification:

    **AOS OS discovery reorganize.**
    Due to a duplicate name in different AOS MIBs, devices recognised as "AOS" os in LibreNMS will be detected now as aos, aos6 or aos7. 
    Change will occur on date. Device_processor sensors of aos6 and aos7 will loose historical data (rrd file can be renamed if you want to keep data).
    - Aos OS will be for Omnistack branch (ex. series 6200)
    - Aos6 OS will be for Aos6 branch (ex. series 6350, 6400)
    - Aos7 OS will be for Aos7 branch (ex. series 6800, 6900)
    More info at: https://github.com/librenms/librenms/pull/11500  

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 11500`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
device_processor sensor RRD renaming instructions:
    - New Aos device: processor-aos-0.rrd -> processor-aos-0.rrd (no change)
    - New Aos6 device: processor-aos-system-0.rrd ->processor-aos6-0.rrd
    - New Aos7 device: processor-aos-system-0.rrd ->processor-aos7-0.rrd

**Comment by murrant** [comment]
@joseUPV ok, sorry for the delay.  Please send a PR to https://github.com/librenms/librenms.github.io and set a date to merge this in the message.

**Comment by joseUPV** [comment]
Pull Request https://github.com/librenms/librenms.github.io/pull/128 added to notify users.

**Comment by murrant** [comment]
Thanks @joseUPV great work

**Comment by joseUPV** [comment]
Text Notification says that change will occur next monday, 18.

**Comment by murrant** [comment]
Oops, thanks.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Pull request merged**
