### PR TITLE
Added additional function called good_if_regexp to allow whitelist of…

### PR DESCRIPTION
**Pull request by philr2**
… intefaces using regular expressions.

This should also be used with a wildcard match on all interfaces using bad_if_regexp.

e.g the following will only allow ens interfaces on linux.
$config['os']['linux']['bad_if_regexp']='/.*/'
$config['os']['linux']['good_if_regexp']='/^ens[0-9]+$/'

e.g the following will only allow physical and aggregated interfaces on IOSXR.
$config['os']['iosxr']['bad_if_regexp']='/.*/'
$config['os']['iosxr']['good_if_regexp']='/^TenGigE[0-9].*/'
$config['os']['iosxr']['good_if_regexp']='/^GigabitEthernet[0-9].*/'
$config['os']['iosxr'']['good_if_regexp']='/^FastEthernet[0-9].*/'
$config['os']['iosxr']['good_if_regexp']='/^Bundle-Ether[0-9].*/'

e.g the following will only allow physical and aggregated major interfaces on JUNOS, but not their sub interfaces
$config['os']['junos']['bad_if_regexp']='/.*/'
$config['os']['junos']['good_if_regexp']='/^(gx)e-[0-9]+\/[0-9]+\/[0-9]+$/'
$config['os']['junos']['good_if_regexp']='/^ae[0-9]+$/'

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
:/ piling more complex on this overly complex system does not seem ideal

**Comment by philr2** [comment]
I'm unclear on which part is complex to you?
Do you mean Librenms is overly complex or the functions that parse the discovery of the interface?

I would argue that filtering on interface discovery is a requirement for an NMS. My addition is to allow for more parsing of the interface discovery process. At the moment it allows black listing. Black listing all uninteresting interfaces is not a good practice. White listing is something that makes more sense to me in some circumstances.

**Comment by murrant** [comment]
I agree, filtering is great, but it should not be hard.
Right now LibreNMS has 7 negative filtering options and 2 positive filtering options.

**Comment by philr2** [comment]
Right well where to from here?
My addition should be self explanatory. Its 5 lines of code. Unless I'm missing something very obvious, I honestly can't fathom why you think this is any harder than what already present.

**Comment by philr2** [comment]
OK so I've done a bit more digging around. Would you think the best way to whitelist interfaces is to discover all and then use "Enable selected port polling"? to only poll the interfaces?

**Comment by murrant** [comment]
If I had to throw something out there:
```
if_filter.direction=whitelist|blacklist
if_filter.filters = [
'ifName' => ['/Gigabit/'],
'ifSpeed' => [1000, 1000000]
]
```

**Comment by Jellyfrog** [comment]
@philr2 tests fails

**Comment by philr2** [comment]
OK so I've pushed another commit. This time with some documentation around it. I kept to the existing filtering functions as much as I could while including a new if_filter_mode definition.

**Comment by murrant** [comment]
Getting warmer, we have a way to deprecate variables:
https://github.com/librenms/librenms/blob/master/LibreNMS/Config.php#L432

**Comment by murrant** [comment]
Closing due to inactivity, feel free to reopen

**Pull request closed without merging**
