### PR TITLE
Update services.inc.php

### PR DESCRIPTION
**Pull request by SniperVegeta**
Added clickabel link to Services 
Added hover of the services status

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by kkrumm1** [comment]
Can you post a screenshot of what this change looks like?

**Comment by SniperVegeta** [comment]
afbeelding

**Comment by SniperVegeta** [comment]
i realy sometimes have no cleu what travis is whining about....

do you?

**Comment by PipoCanaja** [comment]
Thanx @SniperVegeta 
Travis is enforcing some rules which may appear annoying sometimes but they also ensure that the coding style remains consistant, and helps to keep a good readability 👍

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-55-release-changelog-august-2019/9428/1

**Pull request merged**
