### PR TITLE
Detection, sensors and zpool/dataset usage for FreeNAS, TrueNAS

### PR DESCRIPTION
**Pull request by TheMysteriousX**
It's also possible to do zpool IO from the MIB, but diskIO on
LibreNMS makes a lot of assumptions about it coming from the UCD
MIB.

This changeset adds detection for FreeNAS and TrueNAS - despite
having their own enterprise number, the snmpd uses the FreeBSD
one.

The naming is a bit all over the place, because this reflects
reality - IXSystems produce FreeNAS and TrueNAS, the product lines
have merged to eliminate FreeNAS, but TrueNAS still calls itself
FreeNAS everywhere except the GUI.

Screenshot_2020-04-23 dk-z dev ja net - LibreNMS(1)

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Missing tests for freenas?

**Comment by TheMysteriousX** [comment]
I don't have access to any un-upgraded systems, so I can only provide the TrueNAS test data.

I'm not expecting there to be any differences in behaviour though - both TrueNAS and FreeNAS have always shared a codebase, just now it's done by build options rather than forking.

**Comment by karlshea** [comment]
Now my FreeNAS box is detected as "Generic Device" instead of FreeBSD.

**Comment by TheMysteriousX** [comment]
Can you capture an snmprec (or post the sysdescr)?

**Comment by karlshea** [comment]
SNMPv2-MIB::sysDescr.0 = STRING: FreeNAS-11.3-U2 (7216401758). Hardware: amd64 Intel(R) Pentium(R) CPU J4205 @ 1.50GHz running at 1497. Software: FreeBSD 11.3-RELEASE-p7 (revision 199506)

**Comment by karlshea** [comment]
In truenas.yml it looks like you're checking for .1.3.6.1.4.1.8072.3.2.8 but that OID doesn't exist when I snmpwalk it.

**Comment by TheMysteriousX** [comment]
I think I see the problem. Are you running the 11.3? Looks like they've changed the SysObjectID in the latest release. Fortunately it's an easy fix.

**Comment by karlshea** [comment]
Yes, 11.3

**Comment by karlshea** [comment]
Also, none of the ZFS OIDs you seem to be checking exist, either. Maybe that's a FreeNAS vs TrueNAS issue?

**Comment by TheMysteriousX** [comment]
#11494 should support the enterprise number change.

**Comment by TheMysteriousX** [comment]
And thank you for testing.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Comment by evanrich** [comment]
just updated to 1.63, Doesn't seem to work on  FreeNAS-11.3-U2.1.  Still says "FREEBSD Generic", and i don't see pool status.  Anything you need from me?

**Comment by TheMysteriousX** [comment]
Have you looked at #11494 ?

**Comment by evanrich** [comment]
@TheMysteriousX  ahh crap did not.  That seems to have fixed it for me as well. thanks!  I thought 11494 had already been merged in before 1.63 was released.

**Comment by TheMysteriousX** [comment]
It missed the cutoff unfortunately; will be in the next release though. Glad it's working for you.

**Pull request merged**
