### PR TITLE
Update zh-TW.json for authlog page

### PR DESCRIPTION
**Pull request by jasoncheng7115**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@jasoncheng7115 let us know if you notice any strings missing for translation on the converted pages :)

**Comment by jasoncheng7115** [comment]
> @jasoncheng7115 let us know if you notice any strings missing for translation on the converted pages :)

 @murrant

No problem!
Or I will submit PR supplement :)

**Comment by murrant** [comment]
Yeah, that one is a priority, but complex.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
