### PR TITLE
Add support for Fiberstore branded Centec switches

### PR DESCRIPTION
**Pull request by freddy36**
Adds better support for Fiberstore branded Centec switches (S5800/S5850 series) running the fiberstore branded CNOS.

Tested with the S5850-48B8C and S5850-48S2Q4C switches.

Supports the following sensors:
* CPU load
* System Memory
* Temperatures
* FAN state
* FAN speed
* PSU alarm

Compared to https://github.com/librenms/librenms/pull/16163 this PR creates a seperate OS to handle the switches.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by freddy36** [comment]
@sp1rr3 you provided SNMP data for S5800 and S5850 switches as part of https://github.com/librenms/librenms/issues/9117
Are you still using these switches? Did you ever update the software on them?
I suspect that in early software versions Fiberstore forgot to update the SNMP enterprise OIDs and still used the original Centec IDs befor they moved the `.1.3.6.1.4.1.27975.1.` Centec tree to their own enterprice ID `.1.3.6.1.4.1.52642.1.`. I've seen this happening on e.g. the S3800 myself.

**Comment by sp1rr3** [comment]
@freddy36 Hi, 
Yes we are still running them and are on software: S5850 software (S5850 48T4Q), Version 7.4.3.r3 
I will attach the snmpwalk also.
[s5850.txt](https://github.com/user-attachments/files/16054324/s5850.txt)

**Comment by freddy36** [comment]
> @freddy36 Hi, Yes we are still running them and are on software: S5850 software (S5850 48T4Q), Version 7.4.3.r3 I will attach the snmpwalk also. [s5850.txt](https://github.com/user-attachments/files/16054324/s5850.txt)

Thank you, unfortunately your walk is short and doesn't contain any enterprise IDs, maybe you can try to walk `.1.3.6.1.4.1.52642` and `.1.3.6.1.4.1.27975.1`. With the 7.4.3 software version I would expect no results for the second OID.
Do you still have the S5800 switch too?

**Comment by sp1rr3** [comment]
Hi, 
Sorry, yes was checking S5850 but they dont have theeese oids. 
Here is from the S5800 and correct one was .1.3.6.1.4.1.27975.1
[s5800.txt](https://github.com/user-attachments/files/16063735/s5800.txt)

**Comment by freddy36** [comment]
@sp1rr3: With this old software release (5.3.11.r3) the switch apparently still uses the original Centec OIDs.
FS released V7.4.8.R for the S5800 Series Switches: https://resource.fs.com/mall/doc/2024020211254236xtfl.zip
It would be interesting to see if with this newer software they also changed the OIDs.
Not sure if it's possible for you to install the update.

**Comment by murrant** [comment]
@freddy36 are you on the Discord? I wouldn't mind going through these FS switches with you.

**Comment by murrant** [comment]
Put the mibs under the fs directory in a sub directory (fs/centec) and set mib_dir in the OS.
Make the OS name shorter, either fs-centec or fs-cnos.

**Comment by freddy36** [comment]
> Put the mibs under the fs directory in a sub directory (fs/centec) and set mib_dir in the OS yaml. Make the OS name shorter, either fs-centec or fs-cnos.

Made the changes, this should be ready to merge.

**Comment by freddy36** [comment]
@sp1rr3 I checked with fiberstore and you're right, the S5800-8TF12S has it's own software packages, you can't use the generic S5800 updates.
Apparently they already fixed the OIDs in v5.3.12.r. Based on your snmpwalk it seems you already installed the udpate but missing a reboot (software version reports 5.3.11.r3/flash file name reports v5.3.12.r)

https://www.fs.com/products_support/search.html?id=69404

**Review by murrant — APPROVED** [review]
LGTM, good work on these.

**Pull request merged**
