### PR TITLE
Updated BGP polling for Cisco to support CISCO-BGP4-MIB better

### PR DESCRIPTION
**Pull request by laf**
Should hopefully fix all in #936.

Adds IPv6 support.
Uses Cisco-BGP4-MIB where possible.
Small WebUI tidy.

### CODE REVIEW

**Comment by laf** [comment]
Running on works install to confirm 100% working.

**Comment by laf** [comment]
Pushed some small updates mainly to force a scrut run as previous one timed out.

**Comment by f0o** [comment]
Works good here,
I cant test the BGP, have no cisco gear.

One small cosmetic change I would suggest is a squashing of all the small fixups :+1:

**Comment by laf** [comment]
Bump.

I believe we discussed squashing commits and that we shouldn't do this in case people are cherry picking or merging branches - unless it's a ridiculous number of commits.

**Pull request merged**
