### PR TITLE
Added support for new OLT Model

### PR DESCRIPTION
**Pull request by alangregory**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7396)

### CODE REVIEW

**Comment by laf** [comment]
Thanks @alangregory. You need to sign the CLA and also can you add a unit test please: https://docs.librenms.org/Developing/os/Test-Units/

**Comment by alangregory** [comment]
@laf Updated and signed.

**Comment by laf** [comment]
@alangregory - Sorry the test units need to have sysObjectID as per the docs. I know the older unit tests don't here but we're trying to make sure new ones are accurate.

**Comment by laf** [comment]
@alangregory Can you push a commit to trigger travis-ci please, seems to have got stuck :(

**Comment by laf** [comment]
@alangregory really sorry but I don't know why travis isn't picking this up. I think you might need to close the pull request and do a new one. Would you mind?

**Comment by alangregory** [comment]
@laf , no problem, i'll do it.

**Pull request closed without merging**
