### PR TITLE
Fixed Device-Groups for multiple entries and glue-expansion

### LINKED ISSUE #3683: Device Groups only allows one rule
This rule returns all devices instead of one device.
`%devices.device_id > "0" && %sensors.sensor_id < "179" &&`

Looking at the SQL:
`SELECT DISTINCT(devices.device_id) FROM devices,sensors WHERE devices.device_id > 0 AND sensors.sensor_id = 179`

Because of DISTINCT(**devices**.device_id), it only selects from that table.

Thoughts @f0o ?

### PR DESCRIPTION
**Pull request by f0o**
Moved `ResolveGlue` function to commons to avoid code duplication.

Device-Groups are now formed in similar fashion as alert rules are evaluated.

Fixes #3683

### CODE REVIEW

**Comment by laf** [comment]
Running at home to test.

**Comment by murrant** [comment]
I haven't looked into it but with a brief test, I was having issues with a simple `devices.hostname = hostname` rule.  Give me a little more time for testing before merging.

**Comment by laf** [comment]
It ran ok for me at home, @murrant what issues have you seen?

**Comment by murrant** [comment]
```
%devices.hostname ~ "temp@" &&
```

results in the sql

```
SELECT DISTINCT(devices.device_id) FROM devices WHERE (devices.device_id = ?) && (devices.hostname REGEXP "temp.*" )
```

`(devices.device_id = ?) &&` causes the issue

**Comment by laf** [comment]
Odd,

`SELECT DISTINCT(devices.device_id) FROM devices WHERE (devices.device_id = 2) && (devices.hostname REGEXP "temp.*" );`

Works for me. What mysql version?

**Comment by murrant** [comment]
I figured out the problem, this assumes we always have a device to run the query against.  Previously, the device_id was specified in $extra.

Here is the actual command run by the poller:
```
pending
```

When getting all devices belonging to a group, we don't have a device_id.  
https://github.com/librenms/librenms/blob/master/includes/device-groups.inc.php#L136

**Comment by f0o** [comment]
I'll fix it sorry must've slipped

**Comment by laf** [comment]
Re-running at home.

**Pull request merged**
