### PR TITLE
webui: New LibreNMS logo assets

### PR DESCRIPTION
**Pull request by murrant**
SVG images where we can.
Updated favicon and app icons.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by murrant** [comment]
An example.

Old:
librenms-header-mono-old

New:
librenms-header-mono

**Comment by InsaneSplash** [comment]
Nice!

**Comment by laf** [comment]
The only thing with this is the export to pdf (used once in alerts log), it doesn't render properly. Really not an issue but we should address.

**Comment by laf** [comment]
btw looks freakin sweet :)

**Pull request merged**
