### PR TITLE
update some devices to disable poller/disco modules by default

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Covers more cisco devices + some juniper.

I expect they may give users the biggest benefit.

### CODE REVIEW

**Comment by murrant** [comment]
What do you think about disabling some of these globally and enabling them per OS?

**Comment by laf** [comment]
Always nervous :)

We can do. Things like cisco-ace-* only are used for os' which are in the cisco group. I'll take another look.

**Comment by laf** [comment]
Set a lot of vendor specific modules to be off in defaults then enabled per os.

**Comment by murrant** [comment]
I'll try to test this sometime this week.

**Comment by Rosiak** [comment]
I'll test this tomorrow.

**Comment by laf** [comment]
bump

**Pull request merged**
