### PR TITLE
Show port speed on port graphs, optionally set scale

### PR DESCRIPTION
**Pull request by murrant**
Global setting: graphs.port_speed_zoom controls this
You can also set it on an individual graph by setting `port_speed_zoom=1` in the url

LINE2:
image

shows scale, downside is tiny amounts of data on a fast port won't even register visually

HRULE:

image

Allows zoomed in graphs, downside is you can't really see the line unless you are very close to the limit.  It is still in the legend though.

**Any color suggestions or leave it black?**

Dump ifHighSpeed db field it is useless.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Maybe an option to turn it on/off and color?

**Comment by peelman** [comment]
it’s a useful tool, but should definitely be optional.

**Comment by pobradovic08** [comment]
+1 for making it optional. There are cases where you have for couple of 10G interfaces in a port-channel with bunch of subinterfaces (each terminating a customer connection for example). Some of them might have just few mbps but the interface speed is still reported as N x 10G.
image

**Comment by murrant** [comment]
Added global setting and per graph setting.  you can set `port_speed_zoom=1` on any graph to scale it to the ifSpeed.

**Comment by murrant** [comment]
should have been two PRs :/

**Comment by pgnuta** [comment]
Hi All,  Firstly i want to say thanks to everyone for your ongoing hard work on this project but i have a slight beef with this feature...  This feature has been badly implemented in some ways.  It should have been made clear in the release notes and it should not have been enabled by default.  It's been a bit of a confusing time tracking down why a bunch of my VMware high speed interfaces were showing no apparent traffic.

**Comment by aldemaroc** [comment]
Is it possible to disable this feature globally? We have some 10G interface with just a few Mbps and now our dashboards are useless. Also, "Zoom to Traffic" link is broken, as it appends `/%3Fport_speed_zoom=0/` to the URL instead of `/port_speed_zoom=0/` as per [includes/html/pages/graphs.inc.php#L158](https://github.com/librenms/librenms/blob/master/includes/html/pages/graphs.inc.php#L158).

**Comment by pgnuta** [comment]
You can set this in your config.php

'''
$config['graphs.port_speed_zoom'] = false;
'''

**Comment by murrant** [comment]
All, this has been set by default initially to get some feedback, it will likely be set to false before the release.

Thanks for all that given useful feedback.  Please switch to the monthly release if you want.  If you like to be able to give feedback on these things, please stay on the daily.

**Comment by bakerds** [comment]
I think you've got a bug in line 158 of includes/html/pages/graphs.inc.php:
`        if ($vars['port_speed_zoom'] ?? Config::get('graphs.port_speed_zoom')) {
            echo generate_link('Zoom to Traffic', $vars, ['page' => 'graphs', '**?**port_speed_zoom' => 0]);
        } else {
            echo generate_link('Zoom to Port Speed', $vars, ['page' => 'graphs', 'port_speed_zoom' => 1]);
        }`

Including the ? seems to break the ability to toggle back and forth.

**Comment by bakerds** [comment]
When "use stacked graphs" is turned off, should this draw a scale line on the negative Y axis as well?

**Comment by murrant** [comment]
@bakerds I saw that and probably, but it makes the graph even smaller and usually traffic is asymmetric. I have no idea how to solve that and am open to suggestions.

Also, sent PR to change the default. Thanks for feedback all.

**Comment by bakerds** [comment]
Maybe break it into two settings — one for input and one for output — and have a toggle for each on the graph display?

**Comment by richardlawley** [comment]
Some feedback on this - removal of the ifHighSpeed caused any API calls which requested it to break in an unfriendly way:

`GET /api/v0/devices/XX/ports?columns=port_id,ifHighSpeed` would previously return the normal JSON output - since this PR it returns "1" (i.e. invalid JSON) while still giving a 200 status.  I suspect this problem (invalid ports requested) was there all along, but taking a field was previously valid has caused this to crop up (also mentioned by someone else at https://community.librenms.org/t/ifhighspeed-no-longer-on-api-call/16719).

Additionally, the [documentation page for ports](https://docs.librenms.org/API/Ports/) still lists it.

Took me a while to find this since it's just lumped in with what looks like an unrelated PR.

**Comment by murrant** [comment]
@richardlawley a notification within LibreNMS was issued.  Thanks for the heads up on the docs.  Probably should have been two separate PRs.

**Comment by richardlawley** [comment]
> a notification within LibreNMS was issued.

I've not seen such a notification, and it's not present in https://www.librenms.org/notifications.rss

**Comment by murrant** [comment]
https://github.com/librenms/librenms/blob/master/misc/notifications.rss

**Comment by christianseitz** [comment]
It's a great feature and it's good that it can be switches on and off globally.

The graph only seems to zoom to the port speed for incoming packets and not for both incoming and outgoing packets. I would have expected the zero line to be in the middle of the graph.

**Pull request merged**
