### PR TITLE
Updated Aruba ClearPass appliance detection for new sysObjectId

### PR DESCRIPTION
**Pull request by cjwbath**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/clearpass-discovery/10254/5

**Comment by cjwbath** [comment]
Sorry what do you mean by a new variant? Another branch? Why? What's the best practice here?

**Comment by cjwbath** [comment]
So now I guess I have to make the OS definition detect both variants rather than just the new one - will get to that.

**Comment by PipoCanaja** [comment]
still not that good :) The goal is to continue to match existing old clearpass setups, as well as new one

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-59-release-changelog-december-2019/10558/1

**Pull request merged**
