### PR TITLE
Show composer status in web validate.

### PR DESCRIPTION
**Pull request by murrant**
Don't duplicate in validate.php

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Code looks good @murrant. Just needs a rebase now.

**Comment by murrant** [comment]
Ended up with a lot of fixes here.
It wasn't working right when DB wasn't running.

whereis -b was returning multiple items on one computer when testing.

**Comment by lewisvive** [comment]
This doesn't work on Ubuntu 16.04 due to composer being 1.0.0~beta2 and the validation requires 0.9. Is there a need for 0.9 or can we change it to allow 1.0?

**Comment by laf** [comment]
That's being fixed separately.

**Comment by HomeServ** [comment]
`mon1:/opt/librenms/scripts$ ./composer_wrapper.php --version
Composer version 1.6.3 2018-01-31 16:28:17`

Validation page gives error message "Fail: No composer available, please install composer"
====================================
Component | Version
--------- | -------
LibreNMS  | 1.37-13-g764abde
DB Schema | 238
PHP       | 7.0.25-0ubuntu0.16.04.1
MySQL     | 5.7.21-0ubuntu0.16.04.1-log
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.6.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Pull request merged**
