### PR TITLE
Add new Edge core switch

### PR DESCRIPTION
**Pull request by erotel**
Add Edge core switch
ECS 4510-28F
ECS 4510-52T
ECS 4210-28T
ES3528MV2

on discovery os.

This is my first commit. I'm sorry if I did something wrong

 On branch edgecore
 Changes to be committed:
	modified:   ../includes/discovery/os/edgecos.inc.php
	modified:   OSDiscoveryTest.php
	new file:   snmpsim/edgecos-ecs4210-28t.snmprec
	new file:   snmpsim/edgecos-ecs4510-28f.snmprec
	new file:   snmpsim/edgecos-ecs4510-52t.snmprec
	new file:   snmpsim/edgecos-es3528mv2.snmprec

### CODE REVIEW

**Comment by laf** [comment]
Checking the code now, in the meantime you need to sign the contributors agreement as per: http://docs.librenms.org/General/Contributing/#contributor-agreement

The commit message MUST be exactly like we say in the doc.

**Comment by laf** [comment]
Ok just two things.

Can you drop the leading . in the OS test (`1.3.6.1.2.1.1.2.0|6|.1.3.6.1.4.1.259.10.1.24.103` to be `1.3.6.1.2.1.1.2.0|6|1.3.6.1.4.1.259.10.1.24.103`) - yes the other tests for edgecos are like this but they should be changed (feel free to do that if you like).

Is the sysDescr the full output? We don't want just the output the discovery code is, we want the full thing so if it's like `ECS4210-28T This is some device` then use the full thing.

**Comment by erotel** [comment]
Excuse me, but my English is terrible and I do not understand procedures on Github.
I would like to ask someone more experienced for implementation of the changes


sysDescr return :

iso.3.6.1.2.1.1.1.0 = STRING: "ECS4210-28T"
iso.3.6.1.2.1.1.1.0 = STRING: "ECS4510-28F"
iso.3.6.1.2.1.1.1.0 = STRING: "ECS4510-52T"
iso.3.6.1.2.1.1.1.0 = STRING: "ES3528MV2"

**Comment by laf** [comment]
You can push more commits to the same branch. I've done that for you with this commit: https://github.com/librenms/librenms/pull/5102/commits/22c84109743e05b51bd36e07d1caed5451ddf7bb

**Comment by laf** [comment]
You need to add your details to AUTHORS.md with the explicit commit message of (so long as you agree to the contributors docs): `I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md`

**Pull request merged**
