### PR TITLE
Fix ifAlias encoding

### PR DESCRIPTION
**Pull request by Calvario**
Please give a short description what your pull request is for

In some cases the ifAlias isn't sanitized as expected and stop all the port polling process for the device.
This solution is not ideal but currently work flawlessly in 300K ports environment.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
It would be better if you modified StringHelpers::inferEncoding() because there are actual tests for that code.  By modifying this one spot inline, you skip tests so I don't have any confidence this won't break anything.

**Comment by Calvario** [comment]
Indeed, I will check how to implement it on StringHelpers::inferEncoding() and add an adicional test with an accent as it was one of the cases that got stuck by MariaDB as not utf-8.

**Comment by Calvario** [comment]
SQL Error with exemple of non-UTF-8
```sql 
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE9-cabl...' for column 'librenms'.'eventlog'.'message' at row 1 (Connection: mysql, SQL: insert into 'eventlog' ('reference', 'type', 'datetime', 'severity', 'message', 'username', 'device_id') values (41743, interface, 2024-08-28 10:29:36, 3, ifAlias: novo Pr?-cableamento -> novo Pr▒-cableamento, , 106)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE9-cabl...' for column 'librenms'.'eventlog'.'message' at row 1 (Connection: mysql, SQL: insert into 'eventlog' ('reference', 'type', 'datetime', 'severity', 'message', 'username', 'device_id') values (41743, interface, 2024-08-28 10:29:36, 3, ifAlias: novo Pr?-cableamento -> novo Pr�-cableamento, , 106)) at /opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)"
```
On the UI
image

**Comment by Calvario** [comment]
I will close this PR as it turns out, it's an issue on the Official LibreNMS Docker image, iconv is not enabled. 
``` bash
# cat test_iconv.php
<?php
echo function_exists('iconv') ? 'iconv function exists' : 'iconv function does not exist';
?>

# php test_iconv.php
iconv function does not exist
```
It would be interesting to add it on the validate.php in another PR.

**Pull request closed without merging**
