### PR TITLE
New Fortinet mibs

### PR DESCRIPTION
**Pull request by xbeaudouin**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This will add latest Fortinet Mibs (Mostly new objects that can be used on FortiOS 5.4.3)

### CODE REVIEW

**Comment by laf** [comment]
Thanks @xbeaudouin. Just needs the new CLA signing.

**Comment by laf** [comment]
It's because you are committing under 'Xavier Beaudouin' where as it should be xbeaudouin.

```
-bash-4.2$ git config user.name
laf
```

**Comment by xbeaudouin** [comment]
Maybe the documentation has to be updated.... :/

**Comment by xbeaudouin** [comment]
CLA breakage make this brain damage. Will redo this PR

**Pull request closed without merging**
