### PR TITLE
webui: syslog table refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

webui unification, in progress, started from @Rosiak PR #7628 and @laf suggestion.
notes: uses css class from PR #7765

dashboard
before:
screen shot 2017-11-26 at 3 15 20 am

after:
screen shot 2017-11-26 at 4 39 27 am

page
before:
screen shot 2017-11-25 at 10 53 51 pm

after:
screen shot 2017-11-26 at 4 39 37 am

### CODE REVIEW

**Comment by laf** [comment]
Thanks @crcro 

Are you doing the devices page and alerts page? If they were all done then it would look standard and I'd say we should merge at that stage.

**Comment by crcro** [comment]
alerts are already done in another PR, i will do everything else also. next is graylog integration tables (after graylog timezone feature)

**Comment by Rosiak** [comment]
Awesome job @crcro, really happy you are doing this!

**Comment by kkrumm1** [comment]
https://i.giphy.com/media/iiS84hOJXh1Pq/giphy.webp

**Pull request merged**
