### PR TITLE
Better detection of old 3Com StackSwitches

### PR DESCRIPTION
**Pull request by joseUPV**
From Issue #10717

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by joseUPV** [comment]
This will work for:

stackSwitch1100                   OBJECT IDENTIFIER ::= {stackSwitch 1}
stackSwitch3300                   OBJECT IDENTIFIER ::= {stackSwitch 2}
stackSwitch3400                   OBJECT IDENTIFIER ::= {stackSwitch 3}
stackSwitch4400                   OBJECT IDENTIFIER ::= {stackSwitch 4}
stackSwitch4900                   OBJECT IDENTIFIER ::= {stackSwitch 5}
stackSwitchBeefy                  OBJECT IDENTIFIER ::= {stackSwitch 6}
stackSwitchBluetooth              OBJECT IDENTIFIER ::= {stackSwitch 7}
stackSwitchVCN2010                OBJECT IDENTIFIER ::= {stackSwitch 8}
stackSwitchVCN2100                OBJECT IDENTIFIER ::= {stackSwitch 9}
stackSwitch40x0                   OBJECT IDENTIFIER ::= {stackSwitch 10}
stackSwitch4200                   OBJECT IDENTIFIER ::= {stackSwitch 11}
stackSwitch4500                   OBJECT IDENTIFIER ::= {stackSwitch 13}

**Comment by joseUPV** [comment]
I'm going to try other ways to get info from 3Com switches with:

A3COM0352-STACK-CONFIG::stackUnitAddress.1 = Hex-STRING: 00 18 6E 64 49 A0
A3COM0352-STACK-CONFIG::stackUnitLastReset.1 = Timeticks: (130280129) 15 days, 1:53:21.29
A3COM0352-STACK-CONFIG::stackUnitType.1 = INTEGER: 67
A3COM0352-STACK-CONFIG::stackUnitDesc.1 = STRING: "Switch 4200"
A3COM0352-STACK-CONFIG::stackUnitName.1 = ""
A3COM0352-STACK-CONFIG::stackUnitState.1 = INTEGER: unitOperational(3)
A3COM0352-STACK-CONFIG::stackUnitManagementType.1 = INTEGER: distributed(2)
A3COM0352-STACK-CONFIG::stackUnitCapabilities.1 = Hex-STRING: 07 09 14 15 17 1A 1B 1C 1E 20 21 22 23 25 26 28 29 2A 38 42 43 44
A3COM0352-STACK-CONFIG::stackUnitPromVersion.1 = STRING: "2.03"
A3COM0352-STACK-CONFIG::stackUnitHWVersion.1 = STRING: "04.01.01"
A3COM0352-STACK-CONFIG::stackUnitSWVersion.1 = STRING: "3.00"
A3COM0352-STACK-CONFIG::stackUnitSerialNumber.1 = STRING: "L3ZV7LJ6449A0"
A3COM0352-STACK-CONFIG::stackUnitAttention.1 = INTEGER: noAttention(1)
A3COM0352-STACK-CONFIG::stackUnitMgmtInterface.1 = INTEGER: 199
A3COM0352-STACK-CONFIG::stackUnitSummary.1 = Hex-STRING: 01 01 03 8B B2 AF 46 01 01 01 02 01 01 43 03 02 01 00 04 02 16 07 09 14 15 17 1A 1B 1C 1E 20 21 22 23 25 26 28 29 2A 38 42 43 44 05 02 0D 31 37 32 2E 33 31 2E 31 36 2E 31 33 00 0D 01 01 02
A3COM0352-STACK-CONFIG::stackUnitSlipMgmtInterface.1 = INTEGER: 198
A3COM0352-STACK-CONFIG::stackUnitNotepad.1 = ""
A3COM0352-STACK-CONFIG::stackUnitProductNumber.1 = STRING: "3C17300A"

And I want to test it with other 3com models that we have retired.

**Comment by joseUPV** [comment]
Added Mibs from [MibDepot]([http://www.mibdepot.com/cgi-bin/vendor_index.cgi?r=a3com&id=132336])

Modified original 3COM0352.MIB in import section with:
line 88:     a3Com FROM A3Com-products-MIB
to avoid :
Unlinked OID in A3COM0352-STACK-CONFIG: a3Com# ::= { a3Com 0 }
Undefined identifier: a3Com near line 677 of /opt/librenms/mibs/3com/A3COM0352-STACK-CONFIG

**Comment by joseUPV** [comment]
I have doubts in using mibs in librenms because they aren't published by HP (company who bought 3com), and i've found [here](https://sites.google.com/site/jrbinks/code/netdisco/snmp-info-3com) a citation that says that this mibs has copyrights restrictions.

**Comment by joseUPV** [comment]
Added unmodified mibs from http://oidref.com/ and http://www.mibdepot.com/

**Comment by PipoCanaja** [comment]
Hi @joseUPV 
Thanx for your contribution!

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
