### PR TITLE
Fixed url to graphs from date selector

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by geoffrey-wolf** [comment]
This has functionally fixed the 404 issue I was hitting. The only thing that's a bit strange is that following the base URL, the tail part of the URL is prepended with a /

Thus the URL gets composed like: http://hostname.domain/librenms//graphs/to=1535662200/id=1800/type=port_bits/from=1535658600/

In my config I have the base URL configured as /librenms/ Removing the trailing / from the base URL breaks just about everything. Perhaps the // is the result of what the Nginx reverse proxy is doing with the URL.

**Comment by laf** [comment]
I assume it's not causing you an issue?

**Comment by geoffrey-wolf** [comment]
No. Despite the // in the URL the page loads fine.

Geoffrey Wolf
Senior Network Engineer
intermedix, an R1 Company
Office: 412.450.6137
Geoffrey.Wolf@intermedix.com<mailto:%0dGeoffrey.Wolf@intermedix.com>  |  www.intermedix.com<http://www.intermedix.com/>

The information contained in this message is confidential and may be privileged and/or protected under law. If you received this message in error, please notify us immediately by forwarding a copy to compliance@intermedix.com<mailto:compliance@intermedix.com> and delete the original message and any attachments.

**Comment by TheGreatDoc** [comment]
Few thoughts about this.
If you have set `$config['base_url']        = "/";` it will not work
And everytime you hit Update button, it will add a / before graphs. So, after 5 updates it is:
`http://your.domain.tld/////graphs/id=....`

**Pull request merged**
