### PR TITLE
feature: Added support to cisco sensors to link them to ports + macro/docs for alerting

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes: #1065

So what this does is it will link cisco entity sensors up to ports where applicable allowing you to alert on the sensor only if the port is up.

### CODE REVIEW

**Comment by laf** [comment]
Rebased.

**Comment by laf** [comment]
@librenms/reviewers anyone able to look at this?

**Comment by laf** [comment]
Unless anyone want to block this, I'll merge later tonight @librenms/reviewers

**Comment by dragans** [comment]
Hi laf,

It seems you have overwritten the PR changes made in functions.inc.php by mistake.

To be more precise, the changes were reverted in https://github.com/librenms/librenms/commit/d8140467aea9c0fea52500a578c52c6703855879#diff-67aaf7dd786395ce4cbd2c3996cf1bdc

I suppose you used an older version of functions.php.inc when you added support for Emerson energy systems.

Cheers,
Dragan

**Pull request merged**
