### PR TITLE
Use more width for rows of graphs

### PR DESCRIPTION
**Pull request by Alucardfh**
Hi,

This is an attempt to allow the php code to size the graphs according the available width and height.
It uses an ajax call to populate the width and height of the browser.

To determine the size of each graph I divide the width by the number of graph to be drawn minus an arbitrary number of pixel to account for both side margins.

I have also decided to make graphs take the whole row if there is less than 800px available.

This is related to issue  #2410. 

Without modification : 
normalwidth

With modification : 

usemorewidth

### CODE REVIEW

**Comment by laf** [comment]
Thanks for tackling this. A few comments for things that need updating:

- We have some code standards we try and stick to: http://docs.librenms.org/Developing/Code-Guidelines/
Things like the way if / elseif / else is structured. You also don't need the closing ?> in the ajax file.

As this fires the ajax call on each page, I'm unsure if this is the best way.Obviously doing it only on login page isn't enough due to sessions. For now is it worth running that call on the single page it's used or at least moving the call outside of librenms.js to index.php where the session for screen size can be checked first and if it doesn't exist called at that stage?

The browser resize would then still then be triggered as expected.

@librenms/reviewers thoughts?

**Comment by Alucardfh** [comment]
@laf, I agree that having the ajax call on every page is a bit ugly. Do you think that having it on the login page/index would be enough ? I think that even with a direct link you either have a valid session or are asked to login.

An other possibility would be to set a cookie when session variable are set so javascript can check for its presence in order to know if it needs to do the ajax call or not.

**Comment by laf** [comment]
@Alucardfh We only display the login if someone isn't authenticated at present!

However, what about just doing:

```php
if(empty($_REQUEST['width']) && empty($_REQUEST['height'])) {
    echo "<script>updateResolution();</script>";
}
```

Rather than running updateResolution(); all the time? That way, if res isn't set you call the function only once. Res is then set with the session and only recalled when browser window changes?

**Comment by Alucardfh** [comment]
Yes, I think that's a good way of doing it.
But I need to check for the session variable and not just the request otherwise it will still trigger each time it is not updated.

**Comment by laf** [comment]
Yeah it was just an example, replace _REQUEST with _SESSION :)

**Comment by laf** [comment]
Nearly there. Happy to merge after this last change, you have some else statements that need splitting:

`}else {`

should be

```php
}
else {
```

**Comment by Alucardfh** [comment]
I added the same kind of modification in html/pages/graphs.inc.php : 

Going from :
grpahpage

To : 

grpahpagemodified


I'll correct the else statementS.

Also I didn't take out the code that dealt with static size of graph, do you want me to remove that before merging ?

**Comment by laf** [comment]
@Alucardfh Sorry not sure what you mean by you didn't take out the code that dealt with static size of graphs?

**Comment by Alucardfh** [comment]
@laf there is still code that try to set the size of the graph according to $_SESSION['widescreen'] value.
This doesn't seem to be relevant any more especially because there is nothing that set this variable.

 grep -Rn "widescreen" html/
html/index.php:82:if (strstr($_SERVER['REQUEST_URI'], 'widescreen=yes')) {
html/index.php:83:    $_SESSION['widescreen'] = 1;
html/index.php:85:if (strstr($_SERVER['REQUEST_URI'], 'widescreen=no')) {
html/index.php:86:    unset($_SESSION['widescreen']);
html/pages/devices.inc.php:230:                if ($_SESSION['widescreen']) {
html/pages/ports/graph.inc.php:29:        if ($_SESSION['widescreen']) {
html/pages/ports/graph.inc.php:36:        if ($_SESSION['widescreen']) {
html/pages/graphs.inc.php:7:if($_SESSION['widescreen']) {
html/includes/print-graphrow.inc.php:5:if ($_SESSION['widescreen']) {

Does it make sense to get rid of all of this unused code ?

**Comment by laf** [comment]
@Alucardfh makes sense. I'd say deal with that in another PR but yes, that does like it can all be changed to use the new session you've no sorted so we truly know how wide a page is.

**Comment by laf** [comment]
Ok so testing this in the browser and it's not quite right :(

 - The graphs don't seem to resize based on a browser window resize. Tried Chrome and FF. When I resize and refresh it's fine.

 - If the browser window is shrunk in height then images become squashed - enabler developer window at the bottom of your browser and refresh or just manually resize.

**Comment by Alucardfh** [comment]
Yes currently you need a refresh for php to regenerate all graphs with the new browser size.
But having it dynamically adjust would require triggering all graph call on the page to re render them.

Workaround could be to hook a refresh on browser resize.

**Comment by laf** [comment]
Makes sense, probably can be left for now as we have the same issue at present.

Just the image size when the windows height is shrunk down.

**Comment by f0o** [comment]
trigger ci

**Comment by Rosiak** [comment]
:+1:

**Comment by f0o** [comment]
:+1: 

when on a small screen the padding is not sufficient so I get a horizontal scrollbar for ~15-20px. I dont consider it as a blocker though.

**Comment by paulgear** [comment]
Personally, I think horizontal scrollbars are a bit of a blocker...

**Comment by Alucardfh** [comment]
@f0o , @paulgear : on which resolutions and pages have you experienced the scrollbar ?

I agree that it shouldn't display any when not needed.

**Comment by laf** [comment]
@Alucardfh If you just pop a min width/height of what we have now then that should be sufficient. The graphs get kind of whacky when you shrink the screen down anyway :)

**Comment by Alucardfh** [comment]
Ok I have looked a bit further into the sizing of the graph on small resolutions.

On 640*960 on the graph page the scrollbar appear because the miniature graphs are not wrapped after the "Two weeks" one.

So I have added a few media queries to resize the graphs thumbnails if the resolution is too small to fit all of them on one line.

I also tweaked the graph sizing to better fit on the screen.

Before : 
scrollbar2

After : 

scrollbar3


I'll look into the same thing for graphow

**Comment by laf** [comment]
Thanks @Alucardfh 

You'll need to rebase :(

**Comment by Alucardfh** [comment]
@laf I'll do it.

I modified graprow.inc.php to avoid having scrollbars, I had to add a class on the device header to change the font size and graphs size according to the resolutions.

I have tested resolutions : 

480*800
640*960
768*1280
800*600
1024*768
1366*768
1280*800
1280*1024
1680*1050
1920*1080
2550*1440

The only thing I am not really happy is in resolutions between 768*1280 and 800*600 the menu doesn't collapse but doesn't have enough space to be on one line.
This result in a slight overlap of the top graph thumbnail and the menu.

But I am waiting for feedback on the size of graphs in different resolutions, as testing small resolutions on a big screen sometimes give a wrong impression.

**Comment by Alucardfh** [comment]
Hum, does the rebase should look like this ?
I am not that confident with my git skills, I might have messed up.

**Comment by laf** [comment]
:) Don't worry about the rebase for now. Let's test some more and see if it's all ok. We can fix the rebase later.

**Comment by Alucardfh** [comment]
Ok.

I have noticed an issue with graphs that have a lot of text in their legends in resolutions between 800x600 and 1024x768.
The legends is not rendered properly and make some graphs of different size.

But to solve this, it would probably require dynamically scale the text font in the graphs legend.

**Comment by laf** [comment]
If you just put a min height / width in at the value we use now then no one is worse off but the people with larger screens will gain.

**Comment by Alucardfh** [comment]
I have added a check to set the minimum size of the graphs if the computation give a value that is smaller than the old value.

This effectively only apply on screens width between 800px and 1024px as I didn't changed having each graph on a line for screens with less than 800px width.

I also tried to understand better why some graphs act weirdly and mess up the layout : 

rrdgraph use the width and height only for the canva and not for the total size of the image.
You can make it do it by using --full-size-mode but this doesn't scale the axis text and legend making some graph ridiculously small.

This is made difficult to overcome as the lazy loading doesn't set the height and width of the  and thus let it use the space it needs.

I'll dig around to see if it would be possible/easy/not ugly to force the width of the image that has been lazy loaded.

This would solve all padding issue due to graphs having slightly different width.

**Comment by Alucardfh** [comment]
Ok actually the lazy loading has been made to remove the height/width in the  tag.

I have modified the lazy loading to just remove the height tag, this way the width of each graph is the width expected and the graphs is not compressed if the legend is long.

This avoid having weird padding to accommodate the unexpected extra width of some graphs.
It also make the page loading smoother as the lazy load only change the height layout.

There is still a default size set to the old value if it tries to render a graphs with smaller value.

Feedback ?

**Comment by laf** [comment]
I get the opposite now without the height. On graphs that looked ok as they are now, they become squashed looking as the height is calculated too big.

The default images are: 215w 100h. I can shrink my browser with this now to get 215w but the height is then 176h which then looks odd :(

**Comment by Alucardfh** [comment]
Ok, I'll think about how to solve that.

But my initial feeling is that it would require conserving the 215/100 ratio or similar to avoid weird looking graphs in resolution were the width x height ratio is reversed.

**Comment by laf** [comment]
Yes that sounds good. Thanks for tackling this :)

**Comment by Alucardfh** [comment]
I have implemented a solution that make the height always width/2.15.
This prevent having weird looking graphs.

I also change the code to only fit two graphs per row on resolution with width between 700px and 1024px. 
I made so as displaying one graph per line made them too large and displaying all of them made them too small.

I also hooked a refresh after the resize event has updated the new browser size.
Its a workaround that avoid having to compute the actual ratio change for each different graph according to the change in browser size.

**Comment by f0o** [comment]
It looks good for me even on tiny screens.

However: I dont want this commit-mess to be merged, if this is the final version I will rebase it for @Alucardfh and re-submit it if that's OK for you

**Comment by Alucardfh** [comment]
I agree, this PR is not good to merged (I possibly tracked my error to a merge I did instead of a rebase).

The only thing that will probably need tuning at this point is the size of the tooltip on large and small screen, but that can be dealt with in another PR.

@f0o : As you wish, I can also put all my changes in another PR if needed.

**Comment by Alucardfh** [comment]
OK I have made another PR #2510 which should be less painful to merge.

**Pull request closed without merging**
