### PR TITLE
fix: Stop sending -CI with snmpbulkwalk commands #5164

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

fixes: #5164

### CODE REVIEW

**Comment by laf** [comment]
Can you be sure that won't break polling? If so then I'll close this. If not then we should merge as an interim fix as this is currently breaking polling.

**Comment by murrant** [comment]
As far as I can tell from the docs `-CI` only affects walks that return 0-1 results.

The only place the option is used in is ports polling.

**Comment by laf** [comment]
http://www.real-world-systems.com/docs/snmpwalk.1.html

People may have data returned with 0-1 results though?

**Comment by murrant** [comment]
See #5166

**Pull request closed without merging**
