### PR TITLE
Add possibility to monitor the php-fpm service with the unix agent

### PR DESCRIPTION
**Pull request by earendilfr**
Currently, the module php-fpm is only available through SNMP.
It could be great to be available too through unix-agent (like nginx or mysql).

The module itself is not modified

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Is there a corresponding agent update? or docs?

**Comment by earendilfr** [comment]
> Is there a corresponding agent update? or docs?

I haven't update the agent because you only need to take the script from snmp to put it in the unix-agent local directory to use it.
Did you prefer I perform also a commit on agent to duplicate the file ```snmp/phpfpmsp``` to ```agent-local```?

**Comment by VVelox** [comment]
> > Is there a corresponding agent update? or docs?
> 
> I haven't update the agent because you only need to take the script from snmp to put it in the unix-agent local directory to use it. Did you prefer I perform also a commit on agent to duplicate the file `snmp/phpfpmsp` to `agent-local`?

Fine where it is. The important bit is updating `doc/Extensions/Applications.md` to reflect the update.

**Review by murrant — APPROVED** [review]

**Comment by earendilfr** [comment]
> > > Is there a corresponding agent update? or docs?
> > 
> > 
> > I haven't update the agent because you only need to take the script from snmp to put it in the unix-agent local directory to use it. Did you prefer I perform also a commit on agent to duplicate the file `snmp/phpfpmsp` to `agent-local`?
> 
> Fine where it is. The important bit is updating `doc/Extensions/Applications.md` to reflect the update.

OK. I have updated the PR and modified also the doc.

**Review by murrant — APPROVED** [review]

**Pull request merged**
