### PR TITLE
Update Install-LibreNMS.md

### PR DESCRIPTION
**Pull request by jult**
Script fails for users having installed python and pip using apt, which is also default for debian 12.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by jult** [comment]
Sorry, I accidentally deleted the systemctl restart php8.2-fpm line, which was not intended to be pushed ;)

**Comment by murrant** [comment]
@jult push a new commit to your branch and it will update this.

**Comment by murrant** [comment]
Maybe we just update the pip3 call in composer.json instead?

**Comment by jult** [comment]
> Maybe we just update the pip3 call in composer.json instead?

Yes, but then users will wonder why you'd be 'breaking' system-packages for librenms.
A better option is probably to get rid of python altogether, I think..

**Review by murrant — CHANGES_REQUESTED** [review]
I think this is the wrong approach.

**Comment by ottorei** [comment]
> I think this is the wrong approach.

You mean the original or the venv? Running the Python inside venv would only need minimal changes to the update script and systemd unit. Running it in a venv could be a universal solution to avoid breaking any Python packages on all platforms.

**Comment by jult** [comment]
A very similar discussion was going on for LetsEncrypt's certbot on their forums. They decided to drop pip/python and switch to use snap (snapcraft, snapd) altogether. And frankly, ever since, so many (mostly user) issues with certbot have disappeared..

**Comment by murrant** [comment]
@jult yeah.  I still wish there was a clean fix for this.  I tried to convert the existing directory into a venv, but I don't know enough about python...

**Comment by murrant** [comment]
Closing, this needs to be fixed another way.  Thanks!

**Pull request closed without merging**
