### PR TITLE
Add AXOS sensor data for PON Transceivers (the only transceivers Cali…

### PR DESCRIPTION
**Pull request by peelman**
Add AXOS sensor data for PON Transceivers (the only transceivers Calix provides SNMP data for); includes temperature, Tx/Rx dBm, and voltage. (the cliffs in the Tx/Rx were a `user_func` error on my part during testing).

image
image
image
image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by peelman** [comment]
🤔 

This is currently passing for me; and passes in one of the three CI checks...any ideas why its failing on the other two?

image

**Comment by Jellyfrog** [comment]
Most of the times when the tests differs against local env. It's because an "unclean" local env. Like setting file and so.

**Comment by peelman** [comment]
@Jellyfrog i'm tempted to just remove the tests for the E5-16F.  That model isn't exactly the core audience of AXOS anyway...

**Comment by murrant** [comment]
getnext can perform oddly on snmpsim sometimes.  Anyway we can avoid that and just do a regular get?

**Comment by peelman** [comment]
> getnext can perform oddly on snmpsim sometimes. Anyway we can avoid that and just do a regular get?

yeah...my bad on that one; was cloning another discovery.  Will fix.

**Comment by peelman** [comment]
@murrant well that didn't have the desired outcome...

**Comment by Jellyfrog** [comment]
You could leave axos.json/snmprec in their original state. Also you added a php file as yaml. And a couple of executable mib files.

**Comment by peelman** [comment]
@Jellyfrog i originally _did_ leave them in their original state, but because of the discovery changes, the tests weren't happy.

**Comment by murrant** [comment]
FYI, Unless you call `parent::discoverOS(Device $device);` in your discoverOS method, YAML will not be run.
I suggest doing that and moving the serial and hardware to yaml.  To convert hardware to yaml would be:
```yaml
modules:
    os:
        sysDescr_regex: '/(?<hardware>.*)/'
 ```

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
