### PR TITLE
[feat] edgeos hardware info

### PR DESCRIPTION
**Pull request by crcro**
* added missing hardware info
* cleanup os version

(tested with v2.0.0 of edgeos and edge router pro)

before:
screen shot 2019-02-24 at 8 46 47 pm

after:
screen shot 2019-02-24 at 8 47 52 pm

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @crcro 
Could you: 
- update your local repo using ``` git pull origin edgeos_hw_info ```
- check that it still works as expected
- run ``` ./scripts/collect-snmp-data.php -h <yourDevice> ```
- run ``` ./scripts/save-test-data.php -o edgeos ```
- run ``` git add tests/data/edgeos.json ```
- run ``` git commit -a -m 'Updated test data' ```
- run ``` git push origin edgeos_hw_info ```
Thanx ;)
PipoCanaja

**Comment by crcro** [comment]
Hi @PipoCanaja,

it works with your changes.
I cannot save test data, the scripts save-test-data.php is freezing with:

 --- Transport configuration
  Listening at UDP/IPv4 endpoint 127.1.6.1:1161, transport ID 1.3.6.1.6.1.1.0

**Comment by PipoCanaja** [comment]
Hi @crcro 
Do you have by chance a Firewall running on your device ? You can confirm this by disabling it temporarily and testing. If the issue is solved, you should probably disable it for any loopback traffic (means 127.0.0.0/8) and not only 127.0.0.1 as most of us always use for loopback ...

**Comment by PipoCanaja** [comment]
What you can do for sure is "git add" the edgeos.snmprec file to this PR.

**Comment by PipoCanaja** [comment]
Hi @crcro 
Did you manage to disable the firewall so you can run save-test-data as well ?

**Pull request merged**
