### PR TITLE
Syslog hooks for Oxidized integration (and more)

### PR DESCRIPTION
**Pull request by deepseth**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by deepseth** [comment]
This is super rough, and before I spend more time tidying it up, want to make sure I'm doing it inline with how it would be liked to be done, or if something needs refactoring (e.g. the oxidized function needs moving to a different file?)

Absolutely do not expect this current version to be accepted as is, as it's terribad, but it does work :-)

**Comment by laf** [comment]
I think it makes more sense to try and abstract this away from being directly in the code and instead allow users to create their own hooks / search strings that are compared.

**Comment by deepseth** [comment]
Example entry in config.php:
`$config['os']['ios']['syslog_hook'][] = Array('regex' => '/%SYS-(SW[0-9]+-)?5-CONFIG_I/', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');
`

**Comment by deepseth** [comment]
Added matches for NXOS and IOSXR as well, running this in prod myself at the moment and it appears to be working well.

**Comment by laf** [comment]
That looks a lot better to me. You need to add docs to cover the use and I'd also have a global `$config[]` option to enable the hooks as well as per OS.

**Comment by deepseth** [comment]
I've updated the docs to cover the use, and added a global $config[] option to enable the hooks.

**Comment by laf** [comment]
@deepseth LGTM.

@murrant - thoughts?

**Comment by laf** [comment]
Oh and @deepseth - You need to sign the CLA.

**Pull request merged**
