### PR TITLE
Added power supply (PSU) sensor state for Checkpoint Gaia

### PR DESCRIPTION
**Pull request by ajsiersema**
Adds missing power supply (PSU) sensor state for Checkpoint Gaia

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
hello is it possible to implement this in yaml instead? we strongly prefer that since it will be way more future proof.

**Review by JohnnyBBravo — APPROVED** [review]
Tested on various Checkpoint platforms (6000-series, 7000-series, 15000-series, 28000-series & Maestro MHO-140) and works as expected.

**Comment by ajsiersema** [comment]
I won't be able to work on this until the first week of September, but I'll definitely will look into the yaml and tests then.
Please keep this PR open until then

**Comment by murrant** [comment]
@JohnnyBBravo can you collect an snmprec with this PR applied and upload it here?  I can generate the test data from that.

**Comment by JohnnyBBravo** [comment]
I'm not in a position where I can continue work on this unfortunately.

@ajsiersema can you please provide the requested data?

**Comment by PipoCanaja** [comment]
This PR can now be closed as this PSU sensor is now added via YAML in PR #15882

**Pull request closed without merging**
