### PR TITLE
Basic discovery of Cyclades ACS 6000

### PR DESCRIPTION
**Pull request by KlaasT**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this, you will need to fix the conflict in AUTHORS.md.

Can you also add unit test for this: http://docs.librenms.org/Developing/Support-New-OS/#os-test-units

**Comment by KlaasT** [comment]
I'll try my very best :-)

**Comment by laf** [comment]
It's easy :D

**Comment by KlaasT** [comment]
I hope these work. Forgive me if I still have to correct something. This is my first work on LibreNMS :-)

**Comment by laf** [comment]
Thanks for contributing :)

I have updated this to use sysObjectId instead of sysObjectDescr as we prefer that where possible.

**Pull request merged**
