### PR TITLE
Graph: Place the Y grid dynamically if there is no scale

### PR DESCRIPTION
**Pull request by mpikzink**
Place the Y grid dynamically based on the graph's Y range. The algorithm ensures that you always have a grid, that there are enough but not too many grid lines, and that the grid is metric. That is the grid lines are placed every 1, 2, 5 or 10 units. This parameter will also ensure that you get enough decimals displayed even if your graph goes from 69.998 to 70.001. 

Plot

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by PipoCanaja** [comment]
Thx @mpikzink !

**Comment by fcqpl** [comment]
Hi @mpikzink,
Your commit broke Y grid on our LibreNMS instance.
Before:
chrome_cmSdxc458E
After:
chrome_wEXBDrDaLp

Could you please check this?

**Comment by PipoCanaja** [comment]
> Hi @mpikzink, Your commit broke Y grid on our LibreNMS instance. Before: chrome_cmSdxc458E After: chrome_wEXBDrDaLp
> 
> Could you please check this?

Hi @fcqpl 
Please let us know exactly which page you have this display ?

**Comment by fcqpl** [comment]
Hi @PipoCanaja,
This is from dashboard graph "Manual ports", which is linked to `/graphs/id=6562585,6562588,6562603,6562606/type=multiport_bits_separate`
Same with "Overall Traffic", "Memory" in Device overview.

**Comment by mpikzink** [comment]
Thanks for your hint, I can also reproduce it. In some cases, the rrdtool option seems to have other grid label count l, which is not configurable. I try to look in the sources of rrdtool. Even I find a better solution which solve both issues. I haven't found some in the red manuals, yet.

**Pull request merged**
