### PR TITLE
Simplify and fix Cisco ios,iosxe,catos syslog processing

### LINKED ISSUE #2205: Syslog-ng is only showing '%' in the program field and no message in the 'msg' field.
Syslog-ng is displaying syslog messages properly from other devices but not from a Cisco 2960G switch.  Here is the output from the database showing what is stored.  I did a tcpdump on the LibreNMS server and can see the full syslog messages coming from the switch but the messages are not making it into the MySQL database.

mysql> select * from syslog where device_id=2;
+-----------+----------+----------+--------+------+---------------------+---------+------+------+
| device_id | facility | priority | level  | tag  | timestamp           | program | msg  | seq  |
+-----------+----------+----------+--------+------+---------------------+---------+------+------+
|         2 | local6   | notice   | notice | b5   | 2015-10-25 20:59:32 | %       |      | 1357 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:11:16 | %       |      | 1422 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:21:32 | %       |      | 1478 |
|         2 | local6   | info     | info   | b6   | 2015-10-25 21:22:10 | %       |      | 1482 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:22:41 | %       |      | 1486 |
|         2 | local6   | err      | err    | b3   | 2015-10-25 21:23:08 | %       |      | 1487 |
|         2 | local6   | info     | info   | b6   | 2015-10-25 21:23:17 | %       |      | 1488 |
|         2 | local6   | err      | err    | b3   | 2015-10-25 21:23:41 | %       |      | 1489 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:25:01 | %       |      | 1501 |
|         2 | local6   | err      | err    | b3   | 2015-10-25 21:25:04 | %       |      | 1502 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 21:40:20 | %       |      | 1579 |
|         2 | local6   | notice   | notice | b5   | 2015-10-25 22:05:46 | %       |      | 1694 |
+-----------+----------+----------+--------+------+---------------------+---------+------+------+
12 rows in set (0.00 sec)

### PR DESCRIPTION
**Pull request by murrant**
This should cover the examples I could find on the web, but we could be missing some corner cases.
If we fail, the entire message is in msg, instead of being lost.

Fixes #2205

### CODE REVIEW

**Comment by Ultra2D** [comment]
First off, I don't manage any devices affected by this, only interested in the syslog parsing (see #3036) and origin of the old code so to speak.
If I understand correctly, the edge cases are:

- messages that do not start with % [1], could be fixed by changing `'/^%` to `'/^%?`
- Message Traceback Reports [2]: `-Process= ` and `-Traceback=  `
- message within a message,  for some unknown reason only the slot message was logged as program [2]: 
"Some messages also indicate the card and slot that are reporting the error. These messages begin with a percent sign (%) and are structured as follows:"
`%CARD-SEVERITY-MSG:SLOT %FACILITY-SEVERITY-MNEMONIC: Message-text`

[1] http://www.cisco.com/c/en/us/support/docs/switches/catalyst-6000-series-switches/29804-186.html
[2] http://www.cisco.com/c/en/us/td/docs/ios/system/messages/guide/consol_smg/sm_cnovr.html

**Comment by murrant** [comment]
Thanks @Ultra2D.  I thought I had %? in there at some point, must have snuck out.  I'll go through these later.

**Comment by murrant** [comment]
@librenms/reviewers Any thoughts on this?

**Comment by laf** [comment]
Still nervous about things like this as we just don't 100% know the impact for people :/

If we were to merge, I'd propose a message out via the notifications.xml to let people know.

**Comment by murrant** [comment]
Maybe, it has been totally broken for my Cisco devices since I set it up on my production server.  All I get is % in the logs.

**Comment by murrant** [comment]
Unit tests would help, but I have no idea how to set that up.

**Comment by laf** [comment]
If you just add a new entry to misc/notifications.xml and add a new entry just saying that we've merged this in and if you use syslogging with cisco kit then keep an eye on it.

**Comment by Ultra2D** [comment]
@murrant There is a single tab character on line 86 of tests/SyslogTest.php. Could you convert it to spaces?

**Comment by laf** [comment]
This pr has been merged so it would need to be a separate pr.

**Pull request merged**
