### PR TITLE
newdevice: Added additional support for Synology DSM devices #2738

### LINKED ISSUE #2738: Device support: Synology rs2212+ and 812rp not properly configured
Hello

Libre doesn't recognise and configure a Synology RS2212+ properly.

This particular unit also have an expansion chassis attached to it. The expected behaviour is to see all disks in main + expansion and graph health and temp of them. Status of all fans, memory, processors and such. 

Also have an 812rp+. There it finds some units but it doesn't store/save graphs for the disks and it feels icomplete. For that unit I couldn't snmpwalk, gives me oid error. Odd. Can send incomplete if ok.

snmpwalk: http://pastebin.com/66DBLeHr

Some of the info libre finds for the 2212+:
screen shot 2016-01-10 at 01 17 58

The 812:
screen shot 2016-01-10 at 01 20 22

### PR DESCRIPTION
**Pull request by laf**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes #2738

### CODE REVIEW

**Comment by murrant** [comment]
I'm not sure I like the approach for this, I might push a different fix.

**Comment by laf** [comment]
Be my guest :)

**Comment by Rosiak** [comment]
Should we wait for Tony's fix or?

**Comment by murrant** [comment]
I couldn't reproduce the issue...

**Comment by murrant** [comment]
Actually, this doesn't work.

**Pull request closed without merging**
