### PR TITLE
Throw exception when mail delivery fails

### PR DESCRIPTION
**Pull request by alwold**
Currently the `Mail` transport returns a string when delivery fails. This doesn't seem to be recognized by the system as an error. You can see this pretty easily by doing the following:

- Go into Global Settings, Alerting tab, and set the Email Options to have slightly misconfigured SMTP settings (e.g. use the wrong port)
- Go into Alerts -> Alert Transports and Create Alert Transport
- Set up a transport using Mail
- Click the Test Transport button
- It will indicate delivery was successful, even though it wasn't

This PR updates the `Mail` util to throw an exception on failure, instead of catching it and returning a string. Then, in the `Mail` transport, it catches exceptions and translates them to `AlertTransportDeliveryException`, since that seems to be the documented way to indicate failure.

With this change, you can repeat the test above and it will tell you that the delivery failed 🎉 

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Validation uses this as well in `LibreNMS/Validations/Mail.php`, have you checked to make sure that's still working ok?

**Comment by murrant** [comment]
Thanks @alwold this does update the mail transport for modern LibreNMS transport error handling.   As @laf mentioned, the mail validation does need to be updated to handle exceptions :)

LibreNMS/Validations/Mail.php

**Comment by alwold** [comment]
> Validation uses this as well in `LibreNMS/Validations/Mail.php`, have you checked to make sure that's still working ok?

I haven't checked, but I'll test it out. Thanks for pointing that out!

**Review by murrant — APPROVED** [review]
Great improvement, thanks! I plan to remove the validation.

**Comment by alwold** [comment]
> Great improvement, thanks! I plan to remove the validation.

Ok, sounds good! I had started looking into it, but it seemed like it might need quite a bit of work. The most recent thing I ran into was it seems like the config property `alert.default_mail` has to be set to something for it to actually attempt to send something, but there doesn't seem to be anywhere in the UI to do actually set that value (other than doing it via config.php).

**Comment by murrant** [comment]
yeah, all that stuff it is testing is deprecated :)
It is recommended to use alert transports for mails instead that myriad of settings.

**Comment by luktr** [comment]
Updating to latest codebase                        FAIL

In Mail.php line 129:
                     
  No contacts found

**Pull request merged**
