### PR TITLE
Allow pre-formatted logon message

### PR DESCRIPTION
**Pull request by murrant**
Either this or allow full html, but that seems dubious security wise.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
nice idea.
Isn't it better for this to change login_message window in global settings to a textarea?

**Comment by Jellyfrog** [comment]
I dont see the problem with allowing server owner to override it to html, they can inject what they want anyway

**Comment by murrant** [comment]
@Jellyfrog here is my thought line.  The setting is settable by the webui/sql.  Once you can set that setting, it is shown on an _unathenticated_ web page, allowing easy embedding.  It is not that it is inherently unsafe, just that it is much riskier than other settings.

**Comment by murrant** [comment]
We could perhaps use html purifier to remove risky tags though...

**Review by Jellyfrog — APPROVED** [review]
Fair enough

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-october-2020/13837/1

**Comment by murrant** [comment]
If I add this to webui settings, I'll change it to html purifier.

**Pull request merged**
