### PR TITLE
Update WATCHGUARD-PRODUCTS-MIB

### PR DESCRIPTION
**Pull request by lferrerfmv**
Updating the MIB file with the latest version from the manufacturer

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @lferrerfmv 
Could you put both changes in the same PR for clarity ? 
Thanx

**Comment by lferrerfmv** [comment]
Sorry, this is the first time I collaborate, I have done it from the web browser and I have not found a way to send it in a single PR

**Comment by electrocret** [comment]
Is this the entire MIB file? 
Usually when there is a revision to a MIB the manufacturer updates the revision date of it.

**Comment by electrocret** [comment]
> @PipoCanaja Sorry, this is the first time I collaborate, I have done it from the web browser and I have not found a way to send it in a single PR

I do most of my PR's via the browser too. 😄  You should have a clone of the librenms repository on your github account. you just need to find the branch on that repo that this PR is under, and edit the files in it.

Looks like this is the branch you created for this PR. https://github.com/lferrerfmv/librenms/tree/patch-2

**Comment by lferrerfmv** [comment]
> Is this the entire MIB file? Usually when there is a revision to a MIB the manufacturer updates the revision date of it.

These are the latest files published by the manufacturer, they are surely updated because one of the OIDs is only available in the firmware released 20 days ago. And they seem to list models that are a few months old.

**Review by laf — APPROVED** [review]
LGTM

**Pull request merged**
