### PR TITLE
bug - TPLink - fix null exception for LLDP discovery WIP

### LINKED ISSUE #15627: LLDP discovery on TP-Link switches fails
### The problem

I’m not able to see any neighbours on tp-link switches dashboard.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.11.0-25-g3a5a64d5c (2023-12-09T14:24:01+01:00)
DB Schema | 2023_11_21_172239_increase_vminfo.vmwvmguestos_column_length (274)
PHP       | 8.2.13
Python    | 3.11.2
Database  | MariaDB 10.11.4-MariaDB-1~deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.6.6
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[FAIL]  Python3 module issue found: 'Required packages: ['PyMySQL!=1.0.0', 'python-dotenv', 'redis>=4.0', 'setuptools', 'psutil>=5.6.0', 'command_runner>=1.3.0']
Package not found: The 'command_runner>=1.3.0' distribution was not found and is required by the application
'
	[FIX]: 
	pip3 install -r /opt/librenms/requirements.txt
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
```

### What was the last working version of LibreNMS?

23.11.0-25-g3a5a64d5c

### Anything in the logs that might be useful for us?

```txt
Discovery log available at:
https://p.libren.ms/view/b179de65

SNMPBULKWALK reads LLDP data but it cannot manage info

Main error line drops:

Error discovering discovery-protocols module for sw3.mozoilo.lan. TypeError: key(): Argument #1 ($array) must be of type array, null given in /opt/librenms/includes/discovery/discovery-protocols.inc.php:206
```

### PR DESCRIPTION
**Pull request by PipoCanaja**
fixes #15627 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by electrocret — APPROVED** [review]
LGTM

**Comment by younity-ENG** [comment]
hi
was this bug resolved?
i still can't see lldp neighbors on my tp-link switches page.
I'm using LibraNMS 24.2.
thanks

**Comment by PipoCanaja** [comment]
Hi
Yes it was. but not sure if LLDP discovery gives any result on all TPLink devices or not, don't own a single one. What was fixed here was a null exception that was crashing the discovery process. 
But you can investigate (check if SNMP gives data in the LLDP MIB, and if it does, good chances we can do something).
Bye

**Comment by younity-ENG** [comment]
dear @PipoCanaja 

Thank you for responding!!
I have conducted tests with two models of TP-Link switches and observed that both provide LLDP information as evidenced by the output from "./discovery.php -v -d -m discovery-protocols", which I will attach below. This output includes details such as the neighbors' system names, MAC addresses, IP addresses, and local and remote ports, among other data.

Additionally, I experimented with two separate instances of Libra. In the first instance, I updated to the latest TP-Link LLDP-MIBs (and lldpinfo), replacing the previous versions, while in the second instance, I made no changes. Despite these differences, the output from discovery.php appears identical in both instances. However, a notable discrepancy exists in the user interface; the first instance displays a "neighbors" page under the TP-Link switch section, though it remains empty. In contrast, this page is absent in the second instance.

Given these observations, could any further information or insights might aid in resolving this issue? If necessary, I can reach out to TP-Link's R&D department for any additional details that might be required.


by the way, I have the same issue with a Mikrotik switch CRS326-24S+2Q+, only the Ruckus switch (I use ruckus, tp-link and MikroTik) provides full neighbor information and has links automatically created.


Thanks,

[TL-SG3452XP.txt](https://github.com/librenms/librenms/files/14634069/TL-SG3452XP.txt)
[SX3016F.txt](https://github.com/librenms/librenms/files/14634074/SX3016F.txt)

**Pull request merged**
