### PR TITLE
Disable used rules in template map for select them

### PR DESCRIPTION
**Pull request by TheGreatDoc**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

If you map 2 templates to the same rule, it will always use the one with lower id.
With this, you wont be able to map a second template to the same rule. It will disable the option and tell you what template is already mapped to that rule.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Thanks @laf. You actually can remove the rule clicking in the upper empty option. 
But what I noticed is, as <option>'s are loaded in /templates/ if you de-select one rule to use in another template, you must reload.

**Comment by laf** [comment]
> Thanks @laf. You actually can remove the rule clicking in the upper empty option.
> But what I noticed is, as <option>'s are loaded in /templates/ if you de-select one rule to use in another template, you must reload.

Probably worth changing the blank one to be `<option>--Clear Rules--</option>`.

To do this properly you'd need to return this data in the json response then it wouldn't need a page reload.

**Comment by TheGreatDoc** [comment]
I think im done. Only needs some debug clean up.

Please, test it now and let me know if you like it.

**Comment by laf** [comment]
Seems that this now allows you to allocate a second template to a rule, says it's ok but doesn't actually do it. Would be much better to warn people that it didn't work or stop people doing it like you did before.

**Comment by TheGreatDoc** [comment]
Reverted.

**Comment by laf** [comment]
I've done a small update when editing a template that the associated rules for that template are selectable again so you can continue to select the existing rule + others.

**Comment by TheGreatDoc** [comment]
@laf you did the same I reverted in [b36d591faf251f00b06080985aed26d330864a85](https://github.com/librenms/librenms/pull/9212/commits/b36d591faf251f00b06080985aed26d330864a85)

And now, as you said before, if you open a mapping (removing the disabled attr from that options), then cancel and open another mapping will have the other mapping options enabled, making it possible to select that alert rules.

I was thinking in making another ajax call on "Cancel" button to disable selected again.

**Comment by laf** [comment]
> To do this properly you'd need to return this data in the json response then it wouldn't need a page reload.

^^ You need to do it that way. At present you've got a combination of loading data into the modal which is loaded on the initial page load then a call to ajax for which ones are already selected.

It really needs all doing over ajax.

**Pull request merged**
