### PR TITLE
VOSS/BOSS memory usage not working after rebranding

### PR DESCRIPTION
**Pull request by ospfbgp**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I think the actual fix is to rename the files in `includes/polling/mempools/` to the old names, should retain historical data then.

**Comment by ospfbgp** [comment]
I just tried renaming the files in includes/polling/mempools/ and that did not seem to work.  I know we could probably find a way to keep historical data but not sure it is worth it.  This would keep it uniform and future maintainers could troubleshoot.  I did a rediscover of devices  after renaming the files and voss/boss devices did not have entries in mempools.  They were not even being discovered.

librenms@cox-home-dashboard:~/includes/polling/mempools$ ls -al avaya*.*
-rw-rw-r-- 1 librenms librenms  316 Apr 22 00:15 avaya-ers.inc.php
-rw-rw-r-- 1 librenms librenms 1075 Apr 22 00:15 avaya-vsp.inc.php

**Comment by laf** [comment]
Did you put the discovery files back as they were though, with this PR + renaming the poller files it won't work.

**Comment by ospfbgp** [comment]
My apologies.   It appears I screwed something up.  I changed the files back to name before rebranding BOSS/VOSS PR.

includes/polling/mempools/boss.inc.php -> avaya-ers.inc.php
includes/polling/mempools/voss.inc.php -> avaya-vsp.inc.php

librenms@cox-home-dashboard:~/includes/polling/mempools$ ls -al avaya*.*
-rw-r--r-- 1 librenms librenms  316 Apr 24 08:47 avaya-ers.inc.php
-rw-r--r-- 1 librenms librenms 1075 Apr 24 08:47 avaya-vsp.inc.php

MariaDB [librenms]> select mempool_type,mempool_descr,mempool_perc from mempools;   
+--------------+-----------------+--------------+
| mempool_type | mempool_descr   | mempool_perc |
+--------------+-----------------+--------------+
| hrstorage    | Physical memory |           35 |
| hrstorage    | Virtual memory  |           17 |
| hrstorage    | Swap space      |            0 |
| avaya-vsp    | VSP Memory      |           35 |
| avaya-vsp    | VSP Memory      |           40 |
| avaya-vsp    | VSP Memory      |           40 |
| avaya-ers    | Unit 1 memory   |           82 |
| avaya-ers    | Unit 1 memory   |           60 |
+--------------+-----------------+--------------+
8 rows in set (0.00 sec)

**Comment by laf** [comment]
Thanks for fixing :)

**Pull request merged**
