### PR TITLE
Added more macros and alert templates

### PR DESCRIPTION
**Pull request by laf**
Updated docs to reflect this.

Big thanks to @kate66 for most of these.

### CODE REVIEW

**Comment by murrant** [comment]
@laf What about an alert template for service down?

**Comment by laf** [comment]
You got one? I don't use services.

**Comment by murrant** [comment]
Yeah, throw this in `html\includes\print-alert-rules.php`
```
    $default_rules[] = array(
        'device_id' => '-1',
        'rule'      => '%services.service_status != "0"',
        'severity'  => 'critical',
        'extra'     => '{"mute":false,"count":"-1","delay":"300"}',
        'disabled'  => 0,
        'name'      => 'Service up/down',
    );
```

**Comment by laf** [comment]
Added that in now.

**Comment by laf** [comment]
bump

**Comment by Rosiak** [comment]
👍

**Comment by laf** [comment]
Updated schema file name so bump

**Pull request merged**
