### PR TITLE
Typo in routeros YAML discovery

### PR DESCRIPTION
**Pull request by PipoCanaja**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
I may be wrong, but this fix (which is good) will delete historical data as the index changed.

**Comment by PipoCanaja** [comment]
Sounds right. We should probably inform the users in that case.

**Comment by PipoCanaja** [comment]
Rebase + notification.css done. Can be merged today.

**Comment by TheGreatDoc** [comment]
Oops. Missed this comment @PipoCanaja. Sorry for that.

Btw, notification in this repo are only read when update. I suggest to use the librenms.github.io one, so ppl will be notified before merge

**Comment by PipoCanaja** [comment]
Hi @TheGreatDoc 

PR is posted on the librenms.github.io side. And the message is also removed from this PR.

I did not tell "when" this PR will be merged in the notification, feel free to change it in order to sync it with your merge plans :)

Bye

**Pull request merged**
