### PR TITLE
Add app xmrig

### PR DESCRIPTION
**Pull request by yrebrac**
Resubmitting this pull request for xmrig application, git commit email being different from github email should be fixed.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Tests fails

**Comment by yrebrac** [comment]
> Tests fails

The test seems to be looking for or referring to a doc that is not required. Extensions.md has been updated as per any other application.

**Comment by Jellyfrog** [comment]
If you want this merged you need to fix what the tests says

**Comment by yrebrac** [comment]
> 
> 
> If you want this merged you need to fix what the tests says

Let me put it another way. The test is wrong.

**Comment by murrant** [comment]
@yrebrac `The doc Extensions/Application-XMRig.md doesn't exist in mkdocs.yml, please add it to the relevant section`
is the error from the tests, seems like the tests are correct to me.

**Comment by murrant** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
