### PR TITLE
Extra VLAN mapping in bridge FDB module to fix ProCurve

### PR DESCRIPTION
**Pull request by cjwbath**
The FDB discovery process cannot currently get the VLANs for FDB entries on ProCurve switches. This is because ProCurve does not use actual VLAN numbers to index the dot1qTpFdbTable, which is what the default code assumes. Instead, the indices must be further looked up against dot1qVlanFdbId in dot1qVlanCurrentTable to map them to an actual VLAN number.

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/vlan-id-missing-in-fdb-tables-for-hp-provurve-or-aruba-switches/10889/3

**Comment by cjwbath** [comment]
Oh, this is issue #11131; I didn't see that before, was just fixing the issue for myself!

**Comment by F47991** [comment]
The update seems to work, I now have VLAN information in the FDB table.
I did get a warning when applying the fix:
```
<stdin>:16: trailing whitespace.
 *
Checking patch includes/discovery/fdb-table/procurve.inc.php...
Applied patch includes/discovery/fdb-table/procurve.inc.php cleanly.
warning: 1 line adds whitespace errors.
```

**Comment by PipoCanaja** [comment]
Hi guys, 
We already have another PR with less code duplication that came: 
https://github.com/librenms/librenms/pull/11131
Could you test it and let us know if it does it well ?

**Comment by cjwbath** [comment]
@PipoCanaja The other PR doesn't seem to work for me at this time. As for code duplication, I thought a separate file specific to the OS was the convention rather than doing if-tests for the OS in the main fdb-table?

**Comment by PipoCanaja** [comment]
@cjwbath You are right in general, but here only 1 line changes so either we add a condition in the main code, or we put all the code into a function and call both functions from the device specific files. 
Concerning the other PR, a typo was removed now. But I have no idea of the code itself.

**Comment by joseUPV** [comment]
Tested in aruba 2930, hp procurve 2520, hp procurve 2530, hp procurve 2510 and works perfect.

**Comment by cjwbath** [comment]
@PipoCanaja Ah but as I understand it, a one-line fix is _not_ sufficient here - I don't see how the other PR can work with just one line when we need to fetch extra information from SNMP for this. However, it may be that this is something we can patch in the main bridge.inc.php rather than special casing for procurve actually.

**Comment by cjwbath** [comment]
Thanks everyone for testing so far. Thinking about this and on the comments about code duplication I've made this patch a little more generic and put it into the main bridge.inc.php, since switches that _were_ using real VLAN IDs as SNMP IDs should not be affected by the extra mapping code, and those that weren't should be fixed.

This does mean we now need to test on a lot more devices besides just ProCurve. I've tested ProCurve/Aruba, HP Comware and Brocade.

**Comment by cjwbath** [comment]
@F47991 Not sure what OS those Cisco switches run but if it's IOS chances are this will be being handled by fdb-table/ios.inc.php rather than bridge.inc.php

**Comment by F47991** [comment]
@cjwbath They are running IOS-XE 16.9.3 (Fuji). I can see the discovery modules sees it as ```iosxe```.

**Comment by cjwbath** [comment]
Aha, we have failed unit tests for edgecos_es3510ma. I will investigate.

**Comment by joseUPV** [comment]
Tested with Alcatel-Lucent aos6 devices, and doesn't solve the same problem. 
Original bridge.inc.php get all macs in vlan 1. Now gets another vlan number but is not the correct.
Tested with Alcatel-Lucent aos7+ devices, and doesn't solve the same problem.
Original bridge.inc.php get all macs without vlan. This patch doen't change anything
I will make new PR for aos devices to solve fdb problems. Issue #11134

**Comment by cjwbath** [comment]
@joseUPV Could you post snmpwalks of dot1qTpFdbTable and dot1qVlanCurrentTable for the AOS devices? Maybe I need to tweak something.

**Comment by joseUPV** [comment]
@joseUPV Could you post snmpwalks of dot1qTpFdbTable and dot1qVlanCurrentTable for the AOS devices? Maybe I need to tweak something.

https://github.com/librenms/librenms/issues/11134#issuecomment-585157515

**Comment by joseUPV** [comment]
Working on:
- Dell PowerConnect 5316M
- Huawei S2751-28TP-PWR-EI-AC (but I think uses vrp script)
- OfficeConnect 1950-24G-2SFP+-2XGT with HPE Comware
No changes (Doesn't have vlan data) in:
- Alcatel-Lucent Family
- Nortel 3510 with Extreme BOSS v4.0.4.00 
- DLink DGS-3100-48 Rev. 

I will continue testing.

**Comment by joseUPV** [comment]
Working in:
- Netgear ProSafe XS716T
No changes in:
Avaya VSP-4450GSX-PWR+

**Comment by kkrumm1** [comment]
Need to check out the Travis error we can't merge until its resolved.

**Comment by cjwbath** [comment]
@kkrumm1 There you go; I added a fallback so we can still potentially get VLANs even if the vlanCurrentTable is missing like in the edgecos_es3510ma test.

**Comment by kkrumm1** [comment]
Ready to merge?

**Comment by cjwbath** [comment]
I am if testers are happy.

**Comment by kkrumm1** [comment]
Ok thank you. Let’s see if any @testers

**Comment by Jellyfrog** [comment]
Don't we need updated test data for this?

**Comment by sajiby3k** [comment]
Getting below warning when applying patch -

./scripts/github-apply 11132
<stdin>:24: trailing whitespace.
    
<stdin>:45: trailing whitespace.
        
Checking patch includes/discovery/fdb-table/bridge.inc.php...
Applied patch includes/discovery/fdb-table/bridge.inc.php cleanly.
warning: 2 lines add whitespace errors.

And For Cisco SG300 switches it just shows empty in VLAN field when the VLAN is 1. The code must be checked more.

Next week I will check HP Comware, Huawei Comware and Procurve.

**Comment by sajiby3k** [comment]
Hi,

Now checked with procurve switches. Works well. VLAN 1 and other vlan information works.

Checked with HP comware, there also works well.

Checked with Huawei comware works well.

I will upload snmp dumps from Cisco SG series switches soon.

**Comment by cjwbath** [comment]
I'm struggling with building tests for this, snmpsim etc. Here's an snmprec of the FDB-table parts of a ProCurve 2520G I have if someone could help with the tests?

[procurve_2520g_fdb_snmprec.txt](https://github.com/librenms/librenms/files/4244431/procurve_2520g_fdb_snmprec.txt)

**Comment by joseUPV** [comment]
I have hp procurve switches 2510,2520,2530 and 2930.
I can create snmprec and json files of each model if you want.

**Comment by cjwbath** [comment]
@joseUPV That would be helpful

**Comment by joseUPV** [comment]
I can't commit it, data is on the issue: https://github.com/librenms/librenms/issues/11121#issuecomment-590341268

**Comment by cjwbath** [comment]
@joseUPV Those don't seem to have the fdb-table data in so aren't so useful for testing this particular feature unfortunately

**Comment by joseUPV** [comment]
I posted the way i make it on the issue.

**Comment by joseUPV** [comment]
Test data files of HP Procurve 2520 POE:
[procurve.zip](https://github.com/librenms/librenms/files/4249084/procurve.zip)

**Comment by laf** [comment]
@cjwbath Can you use the test data from @joseUPV to add to this PR please.

**Comment by cjwbath** [comment]
@laf Sure, but I don't really know how to do it. Do I just commit the .snmprec and .json files into tests directory? What about the existing files? Should the new ones have a different name?

**Comment by laf** [comment]
If you name them different after the `_` part of the filename that should be fine, chuck them in the relevant directories on the same branch this PR is under and you should be good to then commit and push.

**Comment by cjwbath** [comment]
Bah, somehow I've mucked this up. I suck at Git.

**Comment by cjwbath** [comment]
Redone this as PR #11230 since I messed this up so badly, closing this one.

**Pull request closed without merging**
