### PR TITLE
refactor: Add an option to force transport for the snmp auto discovery

### PR DESCRIPTION
**Pull request by FTBZ**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---------------------------

- When TCP scan is running, the auto discovery with snmp scan is really slow
- Add an option to choose to use only tcp, udp or both

Thanks @schubling for the code.

### CODE REVIEW

**Comment by murrant** [comment]
I don't think you need the word force here.  Just call it transport.  -t (Select transport, tcp or udp.  The default is to try udp then tcp)

**Comment by FTBZ** [comment]
OK changed and added information into the documentation.

**Comment by laf** [comment]
What do people think of just defaulting to udp only and people have to set tcp or both? I think it's rare to see people using tcp for snmp so let's not slow things down.

**Comment by murrant** [comment]
@laf tcp is only tried if udp fails and only if a device is pingable.

**Comment by laf** [comment]
I know but people are complaining that snmp scan is slow, if it's because of tcp then why bother trying by default.

**Comment by murrant** [comment]
@laf I'm working on speeding up snmp-scan and I don't think it will matter much.

**Comment by FTBZ** [comment]
#6889

**Pull request closed without merging**
