### PR TITLE
Update AUTHORS.md

### PR DESCRIPTION
**Pull request by ospfbgp**
#### Please note

> Please read this information carefully.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by laf** [comment]
I'm going to have to stop you here, all of these Pull requests need to be done in one rather than separate requests.

**Comment by laf** [comment]
The commit message must be as per the contributors agreement, if you add a space to the end of the line with your name and push the new commit that will be fine.

**Comment by ospfbgp** [comment]
I have added the line  to comments.  Sorry I am new to the Github and doing this.
I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md.

**Comment by laf** [comment]
You're doing a great job :)

image

**Comment by ospfbgp** [comment]
That's funny.  :)

Daniel Cox
danielcoxman@gmail.com
859-552-8091

**Pull request merged**
