### PR TITLE
Fix bad link in Install-LibreNMS.md

### PR DESCRIPTION
**Pull request by arjenz**
Ubuntu 22.04 has PHP 8.2

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Can you include your change from your other PR into this one please: https://github.com/librenms/librenms/pull/15153

**Review by murrant — CHANGES_REQUESTED** [review]
This seems to indicate 22.04 still uses 8.1 https://packages.ubuntu.com/jammy/php8.1

**Comment by arjenz** [comment]
> This seems to indicate 22.04 still uses 8.1 https://packages.ubuntu.com/jammy/php8.1

My bad! I was operating on a Debian 12 machine, and other than the php version the instructions "just worked" (I was doing multiple installs on different platforms), 8.1 is correct indeed.

**Comment by arjenz** [comment]
I dropped that change from this PR and inserted the one from https://github.com/librenms/librenms/pull/15153

**Pull request merged**
