### PR TITLE
Create Volt OS

### PR DESCRIPTION
**Pull request by mrighetti1989**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10518`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @mrighetti1989 
Thanx for your Pull Request. 
Adding the MIB file is only one of the step to add support for a device. 
- Mib can be added and must be named by its official name (in your case, VOLT-MIB). 
- Definition for the new "operating system" should be added in the form of a YAML file located in ``` includes/definitions/ ```. You can have a look at an existing one, to find out how to create yours ``` includes/definitions/riverbed.yaml ```. Basically, you need to help LibreNMS differentiate your device from all others.
- icon should be added
With those steps, you get a basic OS, and no sensors yet. You can update this PR when you reach that point, and we'll help you go further on.

**Comment by mrighetti1989** [comment]
Hi there! Thanks for the reply, I commented that I tried to add the MIB file, but the enterprise-number of VOLT (17095) is being used in LIBRENMS by the serverscheck company, so it does not allow me to add the MIB, is this possible?

thx

**Comment by PipoCanaja** [comment]
Hi
Tricky one. Serverscheck was highjacking the number that is in use by VOLT. We need to move now. I'll have a look at it and see how to solve it. 
Until then, you can proceed like I described, rename the mib file as asked, and create the YAML files. 
I

**Comment by mrighetti1989** [comment]
Hello, I have already created the volt.yaml file, and I have put the
VOLT-MIB files in the repository of the MIBs, and when I run
./discovery.php -d -h 192.168.89.33 (my VOLT device) the following error
appears



 librenms]# ./discovery.php -d -h 192.168.89.33
LibreNMS Discovery
SQL[select `migration` from `migrations` order by `id` desc limit 1 []
0.38ms]

SQL[select count(*) as aggregate from `migrations` limit 1 [] 0.36ms]

SQL[SELECT version() [] 0.26ms]

===================================
Version info:
Commit SHA: 463170583864b823bd58e7537b43ac18929dc2bd
Commit Date: 1565724860
DB Schema: 2019_07_09_150217_update_users_widgets_settings (140)
PHP: 7.2.19
MySQL: 5.5.60-MariaDB
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2
==================================DEBUG!
Updating os_def.cache...
Done
SQL[SELECT * FROM `devices` WHERE disabled = 0 AND snmp_disable = 0 AND
`hostname` LIKE '192.168.89.33' ORDER BY device_id DESC [] 0.97ms]

SQL[SELECT * FROM devices_attribs WHERE `device_id` = ? [4] 0.38ms]

192.168.89.33 4 serverscheck [FPING] /usr/sbin/fping -e -q -c 3 -p 500 -t
500 192.168.89.33
array (
  'xmt' => '3',
  'rcv' => '3',
  'loss' => '0',
  'min' => '1.68',
  'max' => '2.21',
  'avg' => '2.03',
  'exitcode' => 0,
)
SQL[INSERT IGNORE INTO `device_perf`
(`xmt`,`rcv`,`loss`,`min`,`max`,`avg`,`device_id`,`timestamp`,`debug`)
 VALUES (:xmt,:rcv,:loss,:min,:max,:avg,:device_id,NOW(),:debug)
{"xmt":"3","rcv":"3","loss":"0","min":"1.68","max":"2.21","avg":"2.03","device_id":4,"debug":"[]"}
0.96ms]

SNMP Check response code: 0
SQL[INSERT IGNORE INTO `eventlog`
(`device_id`,`reference`,`type`,`datetime`,`severity`,`message`,`username`)
 VALUES
(:device_id,:reference,:type,:datetime,:severity,:message,:username)
{"device_id":4,"reference":null,"type":"system","datetime":"2019-08-14
09:04:09","severity":3,"message":"Device type changed  =>
network","username":""} 0.81ms]

SQL[UPDATE `devices` set `type`=? WHERE device_id=? ["network",4] 1.37ms]

Device type changed to network!
Unable to parse at line 1 (near "mib:SERVERSCHECK-MIB").
{"exception":"[object]
(Symfony\\Component\\Yaml\\Exception\\ParseException(code: 0): Unable to
parse at line 1 (near \"mib:SERVERSCHECK-MIB\"). at
/opt/librenms/vendor/symfony/yaml/Parser.php:391)"}

In Parser.php line 391:

  Unable to parse at line 1 (near "mib:SERVERSCHECK-MIB").



as information, I deleted the MIB file from serverscheck and the yaml file
from the / include / definitions directory since when I issued the same
command, it brought me data from the VOLT device, but as if it were a
serverscheck device

Thanx
MR

**Comment by PipoCanaja** [comment]
Hi @mrighetti1989 
Could you please sign the CLA ? 

You can try the current version of the PR. 
Please remove your os cache with the following command before running discovery again: 
``` rm cache/os_defs.cache ```

You should have the correct 'volt' os name on your volt device. 

When this is OK, we'll continue with discovery of the volt os. 

Bye

**Comment by PipoCanaja** [comment]
Hi @mrighetti1989 
We still need your signature of the CLA in order to merge your Pull Request. 
Thanx

**Comment by murrant** [comment]
@mrighetti1989 would be happy to merge this, but you need to accept the CLA first.  Otherwise I will have to close this.  Let us know if you need any assistance.

**Comment by laf** [comment]
I've added the missing json test file that was needed.

**Comment by PipoCanaja** [comment]
Hi @mrighetti1989 
We really need you to sign the CLA to merge this change. Looks like this is the only missing point now. 
Thanx

**Comment by laf** [comment]
Closing this down. @mrighetti1989 feel free to comment if you can sign the CLA and we'll re-open this.

**Pull request closed without merging**
