### PR TITLE
cyberpower extra sensor values

### PR DESCRIPTION
**Pull request by takenalias**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by takenalias** [comment]
I'm on leave now for a few days. Once I get back, I'll get onto this.

**Comment by takenalias** [comment]
Not sure how to generate a new JSON file, but I have uploaded the snmprec.

**Comment by 07stuntar1** [comment]
Has this been merged into the daily update builds or do i need to do something special?

**Comment by takenalias** [comment]
> Has this been merged into the daily update builds or do i need to do something special?

I think it will be merged into the 1.45 release later this month.

**Comment by 07stuntar1** [comment]
Sweet

**Comment by takenalias** [comment]
Awsome. Glad to hear.

**Comment by 07stuntar1** [comment]
Thank you

**Comment by takenalias** [comment]
I just realised there will be an issue with humidity, I had a divisor on humidity. This should not have been the case. Not sure the best way to get it sorted. Apologies.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-45-release-changelog-october-2018/6016/1

**Pull request merged**
