### PR TITLE
Updated OS (ftd) for Cisco FirePOWER devices

### PR DESCRIPTION
**Pull request by spencerbutler**
Fixes:
#9880 

There is a similar OS named ftd, but most of the modules are disabled. The CISCO-PRODUCTS-MIB lists several Cisco FirePOWER devices in the same OID range -- I don't know if they all need their own OS, or if they can be grouped into the same OS. Please advise.

I would like to get some sensors added to this OS, hence the "WiP" tag.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
ftd should in fact be ciscoftd to be consistant, but renaming an OS is a bit of a problem for the actual users. So I would avoid the rename. 
Now, most probably all Firepower devices should be included in ftd OS, unless you find an incompatibility that would justify not to. 
I would suggest to start this approach first, and only spend time on the new OS if that approach fails.

**Comment by spencerbutler** [comment]
The only incompatibility I found was that the sensors, mempool, and processor modules are disabled. Do you have any idea why it is configured in that manor?

**Comment by PipoCanaja** [comment]
Nope, not at all. I would still suggest to start from that OS, with the snmpwalk data of the issue, try re-enabling the discovery (which any user can disable from config.php if he wants) and see what you discover. There is no definitions/discovery/ftd.yaml file for the moment, so everything that is coming today is completely standard, not at all specific to ftd anyway.

**Comment by spencerbutler** [comment]
I did start with that OS and moved to this one, named from the CISCO-PRODUCTS-MIB definitions (ie ciscoFpr2140td  OBJECT IDENTIFIER ::= { ciscoProducts 2407 }) because the discovery modules are disabled it ftd. There is only one Ftd device listed in the CISCO-PRODUCTS-MIB, and it's OID is not included in the ftd OS, so I'm at a lost for why: a) it's name doesn't match the documentation b) it's modules are disabled.

**Comment by PipoCanaja** [comment]
The OS name in LibreNMS is absolutely arbitrary. Only depends on what name was chosen by the contributor. 
Discovery modules disabled or not is not important. As the FirePower devices are running linux, may be the contributor wanted to avoid the default linux values, it will be difficult to see. But adding new sensors to an existing OS does not harm existing devices that would not have this sensor. It is necessary to split only if devices behave differently enough.

**Comment by spencerbutler** [comment]
> I think you just need to update the ftd os.

That is the plan. I had an unexpected event carry me away from coding for the past 2 weeks. I'll have a new commit for this "soon".

**Comment by spencerbutler** [comment]
Added to OS (ftd).

**Pull request merged**
