### PR TITLE
Moved system polling module to core to centralise some snmpget calls

### PR DESCRIPTION
**Pull request by laf**
With this I've removed the 'system' polling module and moved it to core.inc.php

core.inc.php is now called for all polls regardless of the modules picked. Before hand some os files needed $poll_device data which was only available if you ran system,os. Whilst most of the time this would just be manual polling debugging that it would affect, the data it actually retrieves is used in a few places so it makes sense to grab this data and re-use it where possible.

I've also added some of the additional queries to the initial snmp_multi_get() so this saves at minimum 4 snmp queries but potentially 5-6 depending on the OS. Not a huge saving but every little helps.

### CODE REVIEW

**Comment by Rosiak** [comment]
I don't have any proper install available to test this on at the moment, just to let you know.
But other than that, awesome!

**Comment by laf** [comment]
Bump

**Comment by Rosiak** [comment]
I really don't have a proper install to test this with.

**Comment by paulgear** [comment]
Looks good to me; big :+1: to this sort of cleanup

**Comment by laf** [comment]
Rebased

**Comment by paulgear** [comment]
One Q: is the system -> core change just a straight rename?

**Comment by laf** [comment]
Yup, but I've left system in with a blank file as it's still a poller module.

**Pull request merged**
