### PR TITLE
Added H3C / Comware MIB files

### PR DESCRIPTION
**Pull request by Laplacence**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Laplacence** [comment]
@PipoCanaja Thx for reply! I have no plans to develop for this part for the time being.
I got this part of the file from the h3c, and thought it might be useful for subsequent development, so I uploaded it first.

**Comment by PipoCanaja** [comment]
OK. Could you please proceed with the CLA (Contributor Licence) ?

**Comment by Laplacence** [comment]
OK, done it.:-)

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Pull request merged**
