### PR TITLE
Update notes.inc.php

### PR DESCRIPTION
**Pull request by MrMaus13**
Allow for iframe border removal by allowing frameborder attribute.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Can you explain the results of this a bit more?
Perhaps a screenshot would be helpful too.

**Comment by MrMaus13** [comment]
The notes-widget can be used to add all sorts of things to your dashboard, including iframes. 
This is a handy feature because it allows you to add some content to your dashboard from external sources but also from, for example, the weathermap plugin. 

If you add an iframe like this:
`<iframe src="your_url" width="100%" height = "100%">`

It looks like this:
note_border


Allowing the frameborder attribute you can remove the border, it's just for esthetic purposes;
`<iframe src="your_url" frameBorder="0" width="100%" height = "100%">`

It then looks like this:
note_borderless

**Comment by murrant** [comment]
Thanks, wasn't sure :)

**Comment by kkrumm1** [comment]
Very nice thank you @MrMaus13

**Pull request merged**
