### PR TITLE
Added Support for SAF Integra E Radios

### PR DESCRIPTION
**Pull request by Derova**
Added Support for SAF Integra E Radios

Before:
IntegraE-Before

After:
IntegraE-After

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Missing json test file, and that snmprec looks incomplete :(

**Comment by Derova** [comment]
Hey @Jellyfrog 
Yes, my apologies I was having difficulties with the save-test-data.php script.
I will have another go today and try to fix this.

**Comment by Derova** [comment]
@Jellyfrog I have the snmprec and json files however I'm not able to run the test. Since upgrading to the latest version I'm getting root@localhost SQL auth issues (which also broke some of my legacy pollers).
./scripts/pre-commit.php says to run ./lnms dev:check instead.

```
$ whoami
librenms
$ ./lnms dev:check -o saf-integra-e
Only checking os: saf-integra-e
Running unit check... 
Starting snmpsim listening on 127.1.6.2:1162... 

In bootstrap.php line 60:
                                                                    
  SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'  
                                                                    
success (6.24s)
```

Have tried flushing the grant table and also setting the password again, but no luck.

**Comment by Derova** [comment]
@Jellyfrog I've updated the SNMPREC / JSON files now. Unfortunately I'm having issues running the test.

**Comment by Derova** [comment]
Will resubmit the pull request. I've made a mess of this one and there's a bunch of other commits?

**Pull request closed without merging**
