### PR TITLE
Update Apps overview page

### PR DESCRIPTION
**Pull request by florianbeer**
Bootstrap-ified Apps overview page. It's now much easier on the eyes.

### CODE REVIEW

**Comment by crcro** [comment]
this should fix an older issue opened by me :) thx @florianbeer

**Comment by florianbeer** [comment]
@crcro great could you maybe link to the issue?

**Comment by crcro** [comment]
issue: #3746

**Comment by florianbeer** [comment]
Old 
screen shot 2016-08-04 at 18 59 37

New
screen shot 2016-08-04 at 18 56 59

**Pull request merged**
