### PR TITLE
Increased speed of loading syslog pages.

### PR DESCRIPTION
**Pull request by TimStallard**
When using the syslog functionality with many records (I tested with ~1.5 million), the UI becomes slow in several places:
- Loading the main syslog page or the page for each device is very slow. This is due to the priorities dropdown, which is ordered by level. Adding an index on the levels and priorities combined resolves this.
- Moving around the table for a single device is fairly slow, due to the count at the bottom being updated. A COUNT(timestamp) is currently performed, but there should not be any items with a null timestamp, so changing this to simply count rows using COUNT(*) significantly increases performance.
These issues are still present when using additional filters, but I can't think of a nice way in which this would be resolved without adding many more combined indexes (or maybe one large index for device, program and priority?).

I agree to the conditions of the Contributor Agreement contained in doc/General/Contributing.md.

#### Please note

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@TimStallard How long did this index take to create for you?

**Comment by TimStallard** [comment]
@laf I just ran a test on an instance with 1.76 million records, it took ~22.3 seconds to create. That's running inside an LXC container with two allocated cores and 2GB RAM.

I also ran the same test on a $40/mo digitalocean droplet (just running mariaDB with the database imported) and saw a similar time, ~23.8s.

**Comment by laf** [comment]
Waiting for #6469 then we can rebase and fix this.

@TimStallard We've gone live with a new CLA, can you please sign that one so we are able to merge.

**Comment by laf** [comment]
@TimStallard We're ready to merge this, can you please sign the new CLA please?

**Comment by TimStallard** [comment]
Sorry, I think something weird must have happened last time I tried. Should be signed now.

**Comment by laf** [comment]
Thanks very much for contributing :)

**Pull request merged**
