### PR TITLE
Print runtimes for each individual polling and discovery module.

### PR DESCRIPTION
**Pull request by SaaldjorMike**

### CODE REVIEW

**Comment by f0o** [comment]
Substitute `utime()` with `microtime(true)` please

**Comment by SaaldjorMike** [comment]
@f0o Will do. Should we look at removing the `utime()` function entirely then (in separate PR ofc)?

**Comment by f0o** [comment]
Afaik `utime` isnt even native php. I got no idea what Adam et. al. did in it when getting precision time is as simple as using `microtime(true)`

**Comment by f0o** [comment]
```
function utime() {
    $time = explode(' ', microtime());
    $usec = (double) $time[0];
    $sec  = (double) $time[1];
    return ($sec + $usec);

}
```

That's a lot of code for similar result like `microtime(true)`

**Pull request merged**
