### PR TITLE
Added new sensors for Huawei SmartAX OS

### PR DESCRIPTION
**Pull request by jozefrebjak**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @jozefrebjak 
Something is wrong with the test data. You should probably revert the original test data, create a new variant for your new sensors, and see how it goes from there.

**Comment by jozefrebjak** [comment]
> Hi @jozefrebjak
> Something is wrong with the test data. You should probably revert the original test data, create a new variant for your new sensors, and see how it goes from there.

It's still falling, please check the travis, i don't understand why it is falling.

**Comment by PipoCanaja** [comment]
You removed the sysDescr recognition pattern for smartax. So it is normal that the original smartax.snmprec is not matched anymore. 
Are you sure your list of OIDs is matching all smartax devices ? Why did you remove the sysDescr ?

**Comment by PipoCanaja** [comment]
In term of Processors, you don't discover all of them compared to the existing code. You need to revert the original Processor discovery code and remove the YAML part doing the new processor discovery. 
Let's process step by step to make the original test succeed while you add new sensors.

**Comment by Jellyfrog** [comment]
Closing due to inactivity. Feel free to reopen

**Pull request closed without merging**
