### PR TITLE
feature: Add AKCP dry contact state support

### LINKED ISSUE #7100: NEW AKCP DEVICE missing dry contacts sensorProbe8
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x ] Please include all of the information between the `====================================` 
section of `./validate.php` which you can run from the cli.

Component | Version
--------- | -------
LibreNMS  | 1.30-7-gafa5b6f
DB Schema | 200
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

https://p.libren.ms/view/3cb05dcd
https://p.libren.ms/view/a65f59b4
https://p.libren.ms/view/a3359145#L7

- [x ] Please provide as much detail as possible.

the dry contacts are mssing :+1: 

sensorProbe8 v2.0 SP8406i

It seems the librenms not recocnise the hardware as akcp
so i added this line

- sensorProbe8

to the akcp.yaml !

Now tthe hardware is checked as AKCP but from the 8 sensors the dry contacts are missing and the

Temperature and Humidity are ok !

https://p.libren.ms/view/b45a31c5

- [ x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

### PR DESCRIPTION
**Pull request by Rosiak**
fix #7100

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
This looks like it can be done in yaml

**Comment by Rosiak** [comment]
Sure, but can I exclude sensors like this:
```
+        if ($temp[$index]['hhmsSensorArraySwitchStatus'] != 'noStatus') {
```

**Comment by laf** [comment]
> Sure, but can I exclude sensors like this:
> 
> +        if ($temp[$index]['hhmsSensorArraySwitchStatus'] != 'noStatus') {

Yup, we actually get the numerical value in the yaml code as you need it. So you can do:

`skip_values: 1`

**Comment by laf** [comment]
Switched to yaml:

image

**Comment by kristoferus75** [comment]
Hi !

I dont know if its ok but i see the states now but in double version like this :


USV Carrier 230V ausgefallen		normal
USV Carrier 230V ausgefallen		2#
USV Carrier Stoerung		normal
USV Carrier Stoerung		2#
48V Gleichrichter 230V ausgefallen		normal
48V Gleichrichter 230V ausgefallen		2#
48V Gleichrichter Stoerung		normal
48V Gleichrichter Stoerung		2#
USV Koax Stoerung		normal
USV Koax Stoerung		2#

**Comment by laf** [comment]
I've just deleted all the states for mine and re-run disco:

image

Try run a rediscovery. Also if you ran the patch for this initially then you'll need to revert that as I moved it to yaml which would explain the duplicates.

**Comment by kristoferus75** [comment]
Hi Laf !

hmm rediscovery don't help but after delete and add the device again it looks now good !

but one thing a have noticed that the discovery takes a very long time at the point 

disco module sensors !

kind regrads

kristoferus75

**Comment by laf** [comment]
Discovery times shouldn't be an issue like it is with polling. But you can disable unneeded discovery modules as normal.

**Comment by kristoferus75** [comment]
ok thanks Laf !

**Comment by kristoferus75** [comment]
Sorry again !

I have seen that we also have sensorProbe2 in use !

after adding:
vi includes/definitions/akcp.yaml

- sensorProbe2

the sensorprobe2 work !

Please update this in the git master !

thanks

kind regards 

kristoferus75

**Comment by laf** [comment]
Please submit this yourself, it's an easy fix.

**Pull request merged**
