### PR TITLE
hp 2530 series procurve/aruba detection

### PR DESCRIPTION
**Pull request by crcro**
for issue #4089

### CODE REVIEW

**Comment by murrant** [comment]
Shouldn't this be in the procurve file?

**Comment by crcro** [comment]
first i put it there but on hp site it is marketed as aruba ... didn't want any confusion on user site

**Comment by murrant** [comment]
I looked on the site and it was labeled as both.  I'm guessing it's the same situation as 3com.   But I think because of the sysDescr check you have it would be good to go into the procurve file.  If you were doing sysObjectID check, it might be a different story.

**Comment by crcro** [comment]
@murrant ... reverted back to procurve

**Pull request merged**
