### PR TITLE
Update documentation to reflect matching behaviour

### PR DESCRIPTION
**Pull request by kiwibrew**
Added a note to help users with matching patterns for Oxidized OS matching patterns.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
A good addition, but it is a little more than just lowercase.  It requires the system name for an os such as hpe-msa

**Comment by PipoCanaja** [comment]
> A good addition, but it is a little more than just lowercase. It requires the system name for an os such as hpe-msa

By the way, Is there an easy way to see the os_name other than digging into the YAML file or the DB ?

**Comment by murrant** [comment]
I could not think of one other than the raw yaml, or db.

**Comment by PipoCanaja** [comment]
> I could not think of one other than the raw yaml, or db.

If I think of a place in the GUI that could provide this information, I'll add it.

**Comment by murrant** [comment]
How about adding it in tooltips or something?

**Pull request merged**
