### PR TITLE
update support GWD GFA6900S

### PR DESCRIPTION
**Pull request by hrtrd**
Try fix CPU.  - Cant show cpus only from OLT borad, without CPU's onu
Try add support  display current ONU's per port. Same problem like CPU's

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by hrtrd** [comment]
Any ideas how can fix show all CPU's?  
Debug module : 
Caching data: processors SNMP[[0;36m'/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OeQUs' '-Pu' '-Ih' '-m' 'GW-EPON-DEV-MIB:GWTT-SMI:GW-EPON-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/gwd' 'udp:HOSTNAME:161' 'GW-EPON-MIB::boardCpuUsage'[0m]
boardCpuUsage.1.1 = 3
boardCpuUsage.1.2 = 255
boardCpuUsage.1.3 = 255
boardCpuUsage.1.4 = 255
boardCpuUsage.16844033.1 = 0
boardCpuUsage.16844034.1 = 0
boardCpuUsage.16844035.1 = 0
boardCpuUsage.16844036.1 = 0
boardCpuUsage.16844037.1 = 0
boardCpuUsage.16844038.1 = 0
boardCpuUsage.16844039.1 = 0
boardCpuUsage.16844040.1 = 0
>500 lines (Online ONU)

So first 4 lines its CPU's OLT, my olt have only one CPU (boardCpuUsage.1.1) but same models have 4 CPU's. I think need support that but dont display if =255. Another oids its CPU's onu, that dont needed display. If i have ~7000 ONU and shows all CPU's holy cow...

**Comment by hrtrd** [comment]
Same problem with PON ports, depending on the board alt can have from 2 ports to 64. 

SNMP[[0;36m'/usr/bin/snmpbulkwalk' '-v2c' '-c' 'COMMUNITY' '-OnQUs' '-Pu' '-Ih' '-m' 'GW-EPON-DEV-MIB:GWTT-SMI:GW-EPON-MIB' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/gwd' 'udp:HOSTNAME:161' 'ponPortCurrOnu'[0m]
ponPortCurrOnu.1.1.5 = 30
ponPortCurrOnu.1.1.6 = 63
ponPortCurrOnu.1.1.7 = 32
ponPortCurrOnu.1.1.8 = 39
ponPortCurrOnu.1.1.9 = 33
ponPortCurrOnu.1.1.10 = 61
ponPortCurrOnu.1.1.11 = 26
ponPortCurrOnu.1.1.12 = 52
ponPortCurrOnu.1.1.13 = 45
ponPortCurrOnu.1.1.14 = 16
ponPortCurrOnu.1.1.15 = 30
ponPortCurrOnu.1.1.16 = 49
ponPortCurrOnu.16844033.1.1 = 0
ponPortCurrOnu.16844034.1.1 = 0
ponPortCurrOnu.16844035.1.1 = 0
ponPortCurrOnu.16844036.1.1 = 0
ponPortCurrOnu.16844037.1.1 = 0

First 12 lines thats real pon ports (1.5 - that pon port №5, 1.6 that pon port №6)  another 500+ lines (like ponPortCurrOnu.16844033.1.1 = 0 )  thats ONU pon ports,  taht dont needed display.

**Comment by hrtrd** [comment]
upload full debug module sensors
[output.txt](https://github.com/librenms/librenms/files/4516838/output.txt)

**Comment by hrtrd** [comment]
@Jellyfrog @murrant

**Comment by hrtrd** [comment]
@Jellyfrog collect new test data and uploaded

**Comment by hrtrd** [comment]
Any ideas?

**Comment by murrant** [comment]
Any reason you aren't using the Processor module instead of a generic count?

**Comment by hrtrd** [comment]
@murrant I apologize, you can in more detail

**Comment by hrtrd** [comment]
Unfortunately, I can’t make a custom processor detection method

**Comment by murrant** [comment]
Why can't you?  Check files in LibreNMS/OS for `discoverProcessors()`

**Comment by hrtrd** [comment]
I will repeat later

**Pull request closed without merging**
