### PR TITLE
feature: Configurable 95th percentile

### PR DESCRIPTION
**Pull request by yunchih**
See issue #7406  for detail.  I have run the lint check, but is still not sure if the code is of standard.  

Please help review.  Thanks.

---

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
All good from me with one small exception. As the config `$config['rrdgraph_real_95th']` has been changed to `$config['rrdgraph_real_percentile']` then we should maintain backwards compatibility by adding something like:

```php
if ($config['rrdgraph_real_95th']) {
    $config['rrdgraph_real_percentile'] = $config['rrdgraph_real_95th'];
}
```

To the end of: `includes/process_config.inc.php`

After that, 👍

**Comment by yunchih** [comment]
Thanks, @laf , I have updated as requested.

**Comment by murrant** [comment]
Well, I was going to say something about the config name being changed for rrdgraph_real_95th, but I tested rrdgraph_real_95th and it didn't seem to be any different because max seems to taken per period and we only have one value per 5 minutes.

So, LGTM.

**Comment by laf** [comment]
@yunchih just need you to sign the CLA please.

**Comment by yunchih** [comment]
@laf Thanks!  Done.

**Comment by laf** [comment]
image

**Pull request merged**
