### PR TITLE
Irc host authentication

### PR DESCRIPTION
**Pull request by Olen**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

This patch will allow you to add users/hosts to be pre-authenticated.
$config['irc_auth'][username1][] = "*!*ident@*host.tld"

### CODE REVIEW

**Comment by deutor** [comment]
Actually it pre-authenticates you every time you send a command. 
I think that either moving that feature to _auth (so .auth admin authenticates you without token) or  pre-authenticate only if not $this->isAuthd() would save some CPU ticks, though those "wasted" ticks do not really matter nowadays (pre-authentication on first command if user is not authorized would still require changing _auth so one could refresh user['devices'] and user['ports'] with pre-authentication). 
Overall I like this change as it will save me some work required to authenticate to 20 bots :)

Anyway $this->user['expire']  should honor  config['irc_authtime'] setting so it should be:
`$this->user['expire'] = (time() + ($this->config['irc_authtime'] * 3600));`
instead of:
`$this->user['expire'] = (time() + 3600);`

**Comment by Olen** [comment]
I thought of using _auth, but that means you still need to type ".auth" at leas once, which was something I wanted to avoid.  But I agree that if we move the check to _auth, it makes sense to honor irc_authtime as well.
But I agreee that checking isAuthd() first is a good thing.  I will add that.  I will look into checking devices and ports.
I will also add the same test to external commands.  This might lead to some refactoring of the code.

**Comment by laf** [comment]
@deutor if you're happy with these changes we'll merge in.

**Comment by deutor** [comment]
I'm very happy with these changes :)

**Comment by laf** [comment]
Needs docs adding before I forget: http://docs.librenms.org/Extensions/IRC-Bot/#configuration-defaults

**Pull request merged**
