### PR TITLE
Stp module rewrite

### PR DESCRIPTION
**Pull request by murrant**
Should fix the stp port polling.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by SourceDoctor** [comment]
comes with this also seperation of STP, RSTP and MSTP? :-)

**Comment by murrant** [comment]
@SourceDoctor what do you mean?

**Comment by SourceDoctor** [comment]
STP 802.1d
RSTP 802.1w
MSTP 802.1s

Some switches are making differences about STP mode in SNMP,.
e.G. on Netgear Switches RSTP isn't recognized on LibreNMS.
Do not know which other Switch families are doing this also.

i think Support of all three STP variants would be useful to be supported.
Especially MSTP is being used often in bigger Networks when not using vxlan.

**Comment by murrant** [comment]
STP and RSTP use the same MIB,  only MSTP is different.

**Comment by SourceDoctor** [comment]
I'm not such familar with reading MIBs, but here is a link to them.
Hope this helps to get your question answered.
http://www.downloads.netgear.com/files/GDC/GS716TV3/gs7xxt-v6.3.1.19-mibs.zip

You don't need to implement them, but if you're motivated to it i'll not hold you back ;-)

In my network are running following Netgear Models with RSTP:
G716Tv3
G724Tv3
G108Tv2
So i can test stuff if wanted.
:-)

**Comment by murrant** [comment]
@SourceDoctor BRIDGE-MIB is in there, so should be supported.

**Comment by murrant** [comment]
@glance- 90% of the time when context is involved it is related to VRFs.  Can definitely make the module VRF aware, but hard for me to do so without something to work with.

**Comment by glance-** [comment]
I've just played around some and found that the SG250 and SG300 switches exposes some sanem MST information in CISCOSB-BRIDGEMIBOBJECTS-MIB space. That might be usable for adding more than mst-0 information to librenms.

@murrant If you'd like I could provide you some test data. Just tell me in which format you'd like it.

**Comment by glance-** [comment]
My ios cisco switches have also some kind of MST information in CISCO-STP-EXTENSIONS-MIB.

**Comment by murrant** [comment]
@glance- Ok, I merged #13596.  So, apply this PR, migrate your DB, and capture some MST test data for me :)  Might be a lot of files due to context stuff.

**Comment by glance-** [comment]
Here you go https://www.acc.umu.se/~glance/snmpsim.tar.gz

**Comment by glance-** [comment]
I didn't see any mst information in any of those dumps, but it might be hiding under some other oid?

**Comment by murrant** [comment]
@glance- it is the ones with the @ symbol in the file name. I found some data already for ios and committed it.  But thanks!

**Comment by glance-** [comment]
The @-context in those files was the (r)pvst compability view's, and not the mst views. The mst view's are supposed to be under @mst-<mst-id> but probably due to bugs those view's are empty on the ios firmware i'm running.

The other SG250 and SWR2016/SWR2024 switches there aren't just any views, so I wonder if its all possible to get anything except mst-0 over snmp from them.

**Comment by glance-** [comment]
Some mocking around later I've found some signal surrounding MST.

For ios devices CISCO-STP-EXTENSIONS-MIB actually contains some MST information that might be usefull, and for the SG250 (and probably other cisco small buissness switches) CISCOSB-BRIDGEMIBOBJECTS-MIB also contains relevant information.

**Comment by murrant** [comment]
@glance- This PR already includes MST per-vlan status.

**Comment by vias79** [comment]
This commit seems to make LibreNMS sometimes fail to send SNMP community to the devices.

Jan 31 2022 13:00:20+01:00 my.switchname.huawei %%01SNMP/3/SNMP_AUTHEN_FAILED(s):CID=0x80d50404;Failed to login through SNMP. (Version=v2c, UserName=**, Ip=librenms.ip, VpnName=_public_, RequestID=1310317586, PduType=Get, Reason=Community is incorrect)

**Pull request merged**
