### PR TITLE
Use Laravel authentication

### PR DESCRIPTION
**Pull request by murrant**
Use Laravel for authentication, but call into legacy auth code for now.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply 8702` and run ./build-base.php to update your db schema.

TODO:

- [x] Implement token auth for API
- [x] Remember Me (updated and tested)
- [x] Two Factor Auth
- [x] Unauth status screen
- [x] Remove legacy includes
- [x] API check auth
- [x] Remove unneeded legacy code
- [ ] Test each auth type (simple tests done for mysql, ldap, and active directory)
- [x] General Testing

Auth types tested:
 - [x] Mysql
 - [x] Active Directory
 - [x] LDAP
 - [x] Radius
 - [x] HTTP
 - [ ] HTTP-LDAP
 - [ ] HTTP-AD
 - [x] SSO

What to test:

 - login/logout
 - user management (if applicable)
 - api token creation
 - api access / full usage
 - other auth related things
 - 2FA

### CODE REVIEW

**Comment by laf** [comment]
Ok, first thing from me is using Firefox (not tested on other browsers). Login either with or without remember me. Close the browser and reopen. Both times you will be faced with `Unauthenticated` and nothing more.

Had to delete the `librenms_session` cookie to allow me to get back to the login page. Hitting /logout didn't make a difference.

**Comment by laf** [comment]
Second thing is the API no longer works, Get:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=https://web01.lathwood.uk/login" />

        <title>Redirecting to https://web01.lathwood.uk/login</title>
    </head>
    <body>
        Redirecting to <a href="https://web01.lathwood.uk/login">https://web01.lathwood.uk/login</a>.
    </body>
</html>
```

**Comment by murrant** [comment]
Ready for testing.  Still have some small issues to work out but I think it is all there.

**Comment by theherodied** [comment]
@murrant Using AD auth and getting `Unhandled MySQL Error [42S22] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'auth_type' in 'where clause'

**Comment by theherodied** [comment]
Removed the PR and reapplied it. It's working now.

**Comment by murrant** [comment]
Yeah, you will need to apply the sql schema update to use it.

**Comment by laf** [comment]
I'm not running mysql strict here but I get:

`Unhandled MySQL Error [23000] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'can_modify_passwd' cannot be null`

When trying to edit an existing user.

**Comment by laf** [comment]
I've tried to test sso and not sure it is working. Following the test example from https://github.com/librenms/librenms/pull/7601#issuecomment-341265561 which I used when that auth type landed and it worked fine.

**Comment by laf** [comment]
@TheMysteriousX if you get chance, could you test this PR with SSO?

**Comment by murrant** [comment]
2FA has some issues with adding+removing tokens right now.  I've got it almost worked out, but I'm running into an issue involving the ajax request setResolution.

**Comment by TheMysteriousX** [comment]
Sure, I'll give it a try when I can. Once its merged I'll look at what hooks are available in Laravel itself too - I know it has some support for single sign on.

**Comment by murrant** [comment]
Mysql error on edit fixed.
deleting user works for me, it should not end in .php
restrict polling alert to devices the user can access (or should it only be admins?)  Also, should it be on every page like it is now?
I have not looked into sso or authorizers.

**Comment by laf** [comment]
> deleting user works for me, it should not end in .php

Still doesn't work for me. Redirects me to the dashboard.

> restrict polling alert to devices the user can access (or should it only be admins?) Also, should it be on every page like it is now?

Admins is fine I guess otherwise, yes, restrict to devices the user can access. Every page maybe not, any page yes if we could restrict how often it pops up.

**Comment by TheMysteriousX** [comment]
Just did a quick test of this, breaks SSO in its current form.

As far as I can tell the authoriser isn't being loaded so it could be down to a change in how the configuration is parsed - where do I need to be looking in this changeset to check how the authoriser is loaded.

**Comment by murrant** [comment]
@TheMysteriousX Thanks for checking.
LegacyUserProvider is the main entry point.  First fetchUserByName is called, then validateCredentials.
AuthEventListener handles auth events.

Errors will be in logs/librenms.log

**Comment by TheMysteriousX** [comment]
Ok, I see what's going on. `retrieveByCredentials `/`validateCredentials` aren't called until the user actively clicks the login button.

For modules like SSO that validate users outside of LibreNMS, the login sequence needs to be invoked automatically.

**Comment by TheMysteriousX** [comment]
Little video of the mechanism in action: https://www.dropbox.com/s/lso6w4nzlgdtp7a/LibreNMS.mov?dl=0

LibreNMS bounces me to the gateway, I authenticate to the gateway with 2fa which then sends me back to LibreNMS with all the information needed for the SSO mechanism to log me in.

**Comment by murrant** [comment]
Hmm, auth.basic sounds similar to that.

**Comment by TheMysteriousX** [comment]
There are similarities yes - auth.basic only handles user/password though, and not group assignment etc.

**Comment by murrant** [comment]
@TheMysteriousX I've made a rough guess at making external auth methods work. Can you test it/give feedback?

**Comment by TheMysteriousX** [comment]
Just tried it, got this - does the error make sense to you or do you need me to do some diagnosing?

```
[2018-08-06 15:15:39] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Illuminate\Cookie\Middleware\EncryptCookies::encrypt() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Wpb\String_Blade_Compiler\View given, called in /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php on line 59 in /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:123
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Object(Wpb\String_Blade_Compiler\View))
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#24 /opt/librenms/html/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#25 {main}
```

**Comment by murrant** [comment]
Hmm, seems like a side effect of another PR not related to this.

**Comment by TheMysteriousX** [comment]
You know which, or should I run a bisect?

**Comment by murrant** [comment]
@TheMysteriousX Yeah, we replace view() with string-blade-compilier.  Not sure why that would cause any issues here.

**Comment by laf** [comment]
Testing http-auth and get:

image

**Comment by murrant** [comment]
@laf @TheMysteriousX I don't have setups for those auth methods.  I might try to if I get some time.  But please feel free to try to get them to work.

I've tried to avoid using legacy functions in this PR (that is why you get your error message @laf).  Just need to remove them and replace as appropriate.

**Comment by TheMysteriousX** [comment]
Sure, I'll see if I can find some time to dig in to the problem.

**Comment by murrant** [comment]
@TheMysteriousX I fixed up http-auth, does that help with the others?

**Comment by laf** [comment]
I've moved this to 1.44 as we won't be able to get this out in time.

**Comment by adam-bishop** [comment]
Sure, I'll find some time to give it a test - if its successful with http auth though, should be with single signon.

**Comment by TheMysteriousX** [comment]
I'm still getting the same error - I think it's unrelated to the SSO code.

I switched back to mysql auth, which had no effect.

**Comment by murrant** [comment]
@TheMysteriousX you get the same error? as in the same line in the same file saying clean() doesn't exist?

I'm going to rebase this again today.

**Comment by TheMysteriousX** [comment]
This one:

```
[2018-08-28 13:53:58] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Illuminate\Cookie\Middleware\EncryptCookies::encrypt() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Wpb\String_Blade_Compiler\View given, called in /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php on line 59 in /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:123
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Object(Wpb\String_Blade_Compiler\View))
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#24 /opt/librenms/html/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#25 {main}
```

If I enable SQL auth on 4158615, everything works If I then github-apply this PR, I get the "something went wrong" and then the above log entry.

**Comment by murrant** [comment]
@TheMysteriousX You didn't run composer install

**Comment by TheMysteriousX** [comment]
Is there a dependency that hasn't made it into composer.json?

```====================================
Component | Version
--------- | -------
LibreNMS  | 1.42.01-92-g29549f6
DB Schema | 261
PHP       | 7.1.18
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.7.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git branch is not master, this will prevent automatic updates.
	[FIX] You can switch back to master with git checkout master
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX] You can fix this with ./scripts/github-remove
	Modified Files:
```

**Comment by murrant** [comment]
@TheMysteriousX I think sometimes the autoloader just needs to be bumped.

**Comment by TheMysteriousX** [comment]
Apologies, I was unclear - validation passes and I've run composer install, and this still PR breaks my install regardless of auth method used.

**Comment by murrant** [comment]
@TheMysteriousX I can't reproduces the issue.  Please try `php artisan cache:clear`.

**Comment by TheMysteriousX** [comment]
No change I'm afraid - I might have a theory though. What happens if you set the following cookie manually and try to load LibreNMS with this patchset:

```
Key: _shibsession_6c696272656e6d7368747470733a2f2f6c696272656e6d732e736f632e6a612e6e65742f73686962626f6c657468
Value: _c5e8a4494550f70b2d6dd91d829f61ec
```

**Comment by TheMysteriousX** [comment]
Just reproduced this using the librenms docker image here: https://hub.docker.com/r/jarischaefer/docker-librenms/

```
root@librenms:/opt/librenms# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.42.01-97-ge603fcf
DB Schema | 263
PHP       | 7.2.8-1+ubuntu16.04.1+deb.sury.org+1
MySQL     | 5.6.41
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.7.2
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  You have not added any devices yet.
	[FIX] You can add a device in the webui or with ./addhost.php
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Your local git branch is not master, this will prevent automatic updates.
	[FIX] You can switch back to master with git checkout master
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX] You can fix this with ./scripts/github-remove
	Modified Files:
```

Error is exactly the same - librenms isn't even installed yet:

```
[2018-08-29 16:35:25] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Illuminate\Cookie\Middleware\EncryptCookies::encrypt() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Wpb\String_Blade_Compiler\View given, called in /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php on line 59 in /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:123
Stack trace:
#0 /opt/librenms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Object(Wpb\String_Blade_Compiler\View))
#1 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#4 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#9 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /opt/librenms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /opt/librenms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /opt/librenms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#24 /opt/librenms/html/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#25 {main}
```

**Comment by murrant** [comment]
Thanks found the problem.  When APP_DEBUG is disabled and there is no existing session and you visit a url besides /login, it will trigger.

There was an error in the exception handling, I hooked in at the wrong place and caused the unauthenticated exception to be handle incorrectly. (and once the session was created, it didn't trigger again)

**Comment by murrant** [comment]
@TheMysteriousX 
Thanks found the problem. When APP_DEBUG is disabled and there is no existing session and you visit a url besides /login, it will trigger.

There was an error in the exception handling, I hooked in at the wrong place and caused the unauthenticated exception to be handle incorrectly. (and once the session was created, it didn't trigger again)

**Comment by TheMysteriousX** [comment]
All working with fine for me with the latest changes.

**Comment by murrant** [comment]
@TheMysteriousX what authentication methods did you test?  Also a huge thanks for testing :)

**Comment by paulocoimbrati** [comment]
Authentication using LDAP not working here. 

> Component | Version
> --------- | -------
> LibreNMS  | 1.43-57-g31e931d8e
> DB Schema | 267
> PHP       | 7.0.27-0+deb9u1
> MySQL     | 10.1.26-MariaDB-0+deb9u1
> RRDTool   | 1.6.0
> SNMP      | NET-SNMP 5.7.3

**Comment by titanismo** [comment]
After latest changes I can see following in librenms.log:

[2018-09-13 17:21:48] production.ERROR: 2 /opt/librenms/LibreNMS/Component.php:162 Illegal offset type  
[2018-09-13 17:21:48] production.ERROR: 2 /opt/librenms/LibreNMS/Component.php:162 ksort() expects parameter 1 to be array, null given  
[2018-09-13 17:21:48] production.ERROR: 2 /opt/librenms/LibreNMS/Component.php:163 Illegal offset type  
[2018-09-13 17:21:48] production.ERROR: 2 /opt/librenms/LibreNMS/Component.php:163 ksort() expects parameter 1 to be array, null given  

I am using old auth_method.

**Comment by murrant** [comment]
This PR has been locked as it is not the correct place to ask for help.

For help please use our Discord server or the community site: http://docs.librenms.org/Support/FAQ/#faq3

**Pull request merged**
