### PR TITLE
Improved RARITAN PDU/PDU2 MIB (current, power) and external env. sensors

### PR DESCRIPTION
**Pull request by theister-xan**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by theister-xan** [comment]
test-data was added last week.
Anything else i can/should do?

**Comment by PipoCanaja** [comment]
Hi @theister-xan 
This PR looks good, thanx for contributing ! 
If this PR is done from your side, we'll merge it in the next few days. 
Bye

**Comment by murrant** [comment]
Does this break any existing sensors for other raritan devices?

**Comment by theister-xan** [comment]
From what i have seen it should not break anything. I am running this on my end against PDU and PDU2 MIB devices for quite sime time now.

The changes to the current code is more cosmetic
- changing echo to d_echo
- moved parenthesis to only run code when there is a result of the snmpwalk at the beginning. Before the change only the echo was conditional, but the following code was run regardless of existance of data from SNMP

From my end i am done with this PR

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-57-release-changelog-october-2019/9969/1

**Pull request merged**
