### PR TITLE
Don't use @lang() it doesn't escape the string

### PR DESCRIPTION
**Pull request by murrant**
Found an issue where a string contained a single quote and broke the page.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Fun side-effect of accidently including storage in the paths for phpstan, it finds syntax errors blade renders :)

**Comment by troublestarter** [comment]
After applied patch, error on logon screen

Here the logs :

[2021-11-25T23:09:32.042018+01:00] production.ERROR: syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (ParseError(code: 0): syntax error, unexpected ')', expecting ']' at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)"}
[2021-11-25T23:09:36.740461+01:00] production.ERROR: syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (ParseError(code: 0): syntax error, unexpected ')', expecting ']' at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)"}
[2021-11-25T23:09:50.238158+01:00] production.ERROR: syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (ParseError(code: 0): syntax error, unexpected ')', expecting ']' at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)"}
/opt/librenms/discovery.php new 2021-11-25 23:10:02 - 0 devices discovered in 0.018 secs
/opt/librenms/poller.php 2 2021-11-25 23:10:04 - 1 devices polled in 1.867 secs
/opt/librenms/poller.php 4 2021-11-25 23:10:04 - 1 devices polled in 2.085 secs
/opt/librenms/poller.php 3 2021-11-25 23:10:06 - 1 devices polled in 3.320 secs
[2021-11-25T23:10:08.306405+01:00] production.ERROR: syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected ')', expecting ']' (View: /opt/librenms/resources/views/layouts/menu.blade.php) at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)
[previous exception] [object] (ParseError(code: 0): syntax error, unexpected ')', expecting ']' at /opt/librenms/storage/framework/views/cde89dba324d4a09ffd2ec12c13984db9181ee04.php:627)"}

image

**Comment by murrant** [comment]
@Jellyfrog was actually helpful :D

**Comment by troublestarter** [comment]
Do we must wait for tyhis to be resolve before testing ?
image

**Comment by murrant** [comment]
@troublestarter looks like I'm still missing at least one messed up search/replace

**Comment by troublestarter** [comment]
@murrant  ok 'm waiting your feedback before testing

**Comment by troublestarter** [comment]
All seems working good !

**Review by troublestarter — APPROVED** [review]
All seems working good on testing

**Pull request merged**
