### PR TITLE
enhance smart to show power_on_hours also

### PR DESCRIPTION
**Pull request by SourceDoctor**
Power on hours on smart will be monitored with this patch

### CODE REVIEW

**Comment by SourceDoctor** [comment]
i think it's an useful enhancement for smart application :-)

**Comment by murrant** [comment]
You can't modify the rrd defintion like that.  rrds can't be changed after creation.  The best way is to create a new rrd defintion just for that one data point.

**Comment by SourceDoctor** [comment]
now new rrd for id9 enhancement will be created

**Comment by SourceDoctor** [comment]
@murrant something else to change for merging?

**Pull request merged**
