### PR TITLE
Fix dynamic group membership rule for devices.status equal 0

### PR DESCRIPTION
**Pull request by ajsiersema**
A dynamic group membership rule can be added with “devices.status equal 0”.
This would be very useful for e.g. Maps -> Device Group Dependencies
However, the device group membership is updated by the poller, and the poller code won’t update the device group membership for devices that are down.

This PR runs group membership updates for down and up devices, fixing e.g. network maps with device group dependencies.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
I appreciate you extracting a function instead of just copying the code, but it would be better if you just called the code every time in the same spot.  The way you have done it makes it harder to understand/read the code.

My suggestion, but it right before the code that runs alerts.

**Comment by ajsiersema** [comment]
> My suggestion, but it right before the code that runs alerts.

Hehe, that's exactly what I did in the initial version, but then decided you might like the patch better if it was made explicit that updating the groups is done in both cases.

I'll rework the PR by moving the code out of the function again.

**Comment by murrant** [comment]
No need to squash, we squash when we merge to make nice tidy commits in master.

**Comment by murrant** [comment]
You can see how confusing that is right?
if ($blah) {
wall of code...
do_something()
wall of code.. 
} else {
do_something()
}

**Comment by ajsiersema** [comment]
> You can see how confusing that is right?

The first version I came up with moved the code into a function, in the include, then called that function from poller.php. Kinda how I would have implemented it to begin with.
Which then got me thinking, that although I thought it was very confusing that the device groups weren't always updated (principle of least surprise and all that), I wasn't there when the decision was made to place the code conditionally in the include cod. So there might have been a very good reason, and maybe it was decided to keep the poller.php as small/clean as possible. Hence, I moved all the code (back) info the include.

Anyway, thanks for your assistance and the merging ! (and all the other work on librenms)
Dynamic maps based on dynamic device groups are a nice feature.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-64-release-changelog-may-2020/12290/1

**Comment by murrant** [comment]
@ajsiersema There was likely no decision.  Remember LibreNMS is 100% community supported. Someone probably changed something and didn't realize the rammifications.

**Pull request merged**
