### PR TITLE
Centralised version info + used in output

### PR DESCRIPTION
**Pull request by laf**
This provides a central function to get version info back across the board.

We now print this info in validate,poller and discovery + updated webui. This will enable us to get info back on what versions people have when provide debug output. Saves asking for it all the time.

In validate.php we do a check against the last github commit and the local one to see if it's upto date.

### CODE REVIEW

**Comment by laf** [comment]
Rebased.

**Comment by f0o** [comment]
Can you add HTTPd's name+version to it as well?

**Comment by laf** [comment]
Left it out initially as it's useless in poller/discovery and not everyone uses Apache but I can add it in.

**Comment by f0o** [comment]
fair enough

**Pull request merged**
