### PR TITLE
fix dbm sensor for ios-xr

### PR DESCRIPTION
**Pull request by mmarchand**
Restore dbm sensors for IOS-XR

### CODE REVIEW

**Comment by laf** [comment]
Can you show us the output of an snmpwalk on this so we can see?

Is it possible this varies between ios-xr versions?

**Comment by mmarchand** [comment]
I don't believe it's a change on XR side,
iirc it's a change in librenms, sensor descriptions used to be shortened automatically (things like "current/power/state/temperature/..." were cleaned out)

**Comment by laf** [comment]
Sorry it was more to see what the actual output from snmp was :)

**Comment by mmarchand** [comment]
snmpwalk of OID 1.3.6.1.2.1.47.1.1.1.1 (entPhysical) : 
https://gist.githubusercontent.com/mmarchand/d2615d60acb35cb4fdc898b4a0828de9/raw/5b7d3e9052e7e456d3007a7fb6eac05e0a6e4d9d/gistfile1.txt

**Comment by laf** [comment]
Do we need both checks as that output shows:

power Rx 0/11/CPU0/18

and

Transceiver Tx Power Sensor

?

**Comment by mmarchand** [comment]
hmm actually a sensor entry is like:
```
ENTITY-MIB::entPhysicalDescr.1247 = STRING: Transceiver Tx Power Sensor
ENTITY-MIB::entPhysicalVendorType.1247 = OID: SNMPv2-SMI::enterprises.9.12.3.1.8.47
ENTITY-MIB::entPhysicalContainedIn.1247 = INTEGER: 21556457
ENTITY-MIB::entPhysicalClass.1247 = INTEGER: sensor(8)
ENTITY-MIB::entPhysicalParentRelPos.1247 = INTEGER: 1
ENTITY-MIB::entPhysicalName.1247 = STRING: power Tx 0/13/CPU0/2
ENTITY-MIB::entPhysicalHardwareRev.1247 = STRING:
ENTITY-MIB::entPhysicalFirmwareRev.1247 = STRING:
ENTITY-MIB::entPhysicalSoftwareRev.1247 = STRING:
ENTITY-MIB::entPhysicalSerialNum.1247 = STRING:
ENTITY-MIB::entPhysicalMfgName.1247 = STRING:
ENTITY-MIB::entPhysicalModelName.1247 = STRING:
ENTITY-MIB::entPhysicalAlias.1247 = STRING:
ENTITY-MIB::entPhysicalAssetID.1247 = STRING:
ENTITY-MIB::entPhysicalIsFRU.1247 = INTEGER: false(2)
```

actually the root cause seems to be : 

```
   if ($entity_array[$index]['entPhysicalName'] || $device['os'] == 'iosxr') {
                    $descr = rewrite_entity_descr($entity_array[$index]['entPhysicalName']);
                }

```
from #2767 

Mik

**Comment by laf** [comment]
So before we would have had:

power Tx 0/13/CPU0/2 - Transceiver Tx Power Sensor

but now just show:

power Tx 0/13/CPU0/2

So you are right with this. Merging now.

**Pull request merged**
