### PR TITLE
Traditional Chinese language support

### PR DESCRIPTION
**Pull request by jasoncheng7115**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
@murrant Saw this one merged the other day: https://github.com/librenms/librenms/pull/10137/files does this also need the additional php files updating like that PR?

**Comment by jasoncheng7115** [comment]
> @murrant Saw this one merged the other day: https://github.com/librenms/librenms/pull/10137/files does this also need the additional php files updating like that PR?

By the way,
When I try to change the locale Settings in app.php, the system does use the zh-tw. json language string.

2019-05-03 09_22_59-mRemoteNG - confCons xml - mon1 - 172 16 1 180
2019-05-03 09_23_56-LibreNMS

**Comment by murrant** [comment]
Very few portions of the system support translation.  There is a PR that I hope will be merged soon that will add support for the whole main menu.  (you can preview this menu by visiting /locations)
#10173

**Comment by murrant** [comment]
Any missed translations for things that are done in Laravel Blade can be fixed pretty easily by wrapping them in @lang() or __().  Send a separate PR for those please.

**Comment by murrant** [comment]
This also reminds, me, we should create a .env setting for locale.

**Comment by murrant** [comment]
@jasoncheng7115 you have not translated all those strings (such as "Ignored").  We don't have any guide or assistance on how to find the strings that need translation at this time, language support is still in its infancy in LibreNMS.  You can check the Russian translation files for some things that need to be added.

**Comment by jasoncheng7115** [comment]
> @jasoncheng7115 you have not translated all those strings (such as "Ignored"). We don't have any guide or assistance on how to find the strings that need translation at this time, language support is still in its infancy in LibreNMS. You can check the Russian translation files for some things that need to be added (those are incomplete too).

Yes, I did translate zh-tw. json from ru.json. So the missing part of ru.json, I don't have it here.
Suggest a file I must refer to?

**Comment by murrant** [comment]
@jasoncheng7115 You could use this to find all the translatable strings:  https://github.com/kkomelin/laravel-translatable-string-exporter

I might add it to upstream as a dev dependency, but not atm.  You can add it to your local install and use it.

**Comment by murrant** [comment]
A current list of strings that need translation: https://p.libren.ms/view/796e4972  (New ones are added all the time)

**Comment by jasoncheng7115** [comment]
> A current list of strings that need translation: https://p.libren.ms/view/796e4972 (New ones are added all the time)

No problem. Let me translate traditional Chinese.

**Comment by murrant** [comment]
Yes

**Comment by murrant** [comment]
I've added a new file too to specify the language name in the select screen #10272

**Comment by jasoncheng7115** [comment]
> I've added a new file to specify the language name in the select screen #10272

I have updated this translation file.
This language is "繁體中文 Traditional Chinese"

**Comment by murrant** [comment]
You are still missing the other translation files that should be in the zh-TW directory, see the ru folder for starters.

**Comment by jasoncheng7115** [comment]
> You are still missing the other translation files that should be in the zh-TW directory, see the ru folder for starters.

Thank you for your prompt. Relevant files have been added.

**Pull request merged**
