### PR TITLE
Add support for Cisco IE1000

### PR DESCRIPTION
**Pull request by rudybroersma**
Our Cisco IE1000s were discovered as generic devices. The IOS discovery yaml doesn't use sysObjectIDs but sysDescr matching instead. The IE1000 have 'IE1000 Industrial Ethernet Switch' in their sysDescr, while more recent models such as the IE2000 have a more generic Cisco IOS string:

IE1k: STRING: "IE1000 Industrial Ethernet Switch, Version: 1.8.2#2020-08-13T23:48:09+00:00"
IE2k: STRING: Cisco IOS Software, IES Software (IES-LANBASEK9-M), Version 12.2(58)SE1, RELEASE SOFTWARE (fc1)

I've modified the ios.yaml discovery to include the IE1000 variants' sysObjectIDs. Names taken from CISCO-PRODUCTS-MIB

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Why not add its sysobject id .1.3.6.1.4.1.9.1.2333 instead?

**Comment by rudybroersma** [comment]
> Why not add its sysobject id .1.3.6.1.4.1.9.1.2333 instead?

That was my original plan, but I thought there must be a reason why none of the IOS devices are identified using sysObjectIDs.

Do you prefer adding sysObjectID instead of sysDescr regex? If so, i'll change it.

**Comment by Jellyfrog** [comment]
100%

**Comment by rudybroersma** [comment]
> 100%

Done!

**Review by Jellyfrog — APPROVED** [review]

**Pull request merged**
