### PR TITLE
Change default graph image to SVG

### PR DESCRIPTION
**Pull request by electrocret**
All modern browsers support SVG. It is immensely more efficient than png, so it should be the default.

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by peejaychilds** [comment]
Whilst I don't have any particular issue with this change I do remember we did something similar for a cacti deployment about 100 years ago and found the end user performance was impacted as the size of all the graphs was much higher than the PNGs

Looking at my lab deployment just the processor graph on a host ... so this can add up ?

```
 Downloads$du -sh graph*
 20K	graph.png
1.7M	graph.svg

```

**Comment by murrant** [comment]
Make sure you enable gzip (or better) on your webserver. And compare those sizes.
Note that it is enabled for the default install instructions.

**Comment by electrocret** [comment]
I've been using SVG on all of my Libre instances for months, and it has noticeably improved graph lazy load times.

**Comment by peejaychilds** [comment]
```
$ gzip graph.svg
$ du -sh graph*
 20K	graph.png
352K	graph.svg.gz
```

I guess I should go do some real wire comparisons toggling on/off etc with a bunch of graphs.

As I said I don't think this will cause any issues given it is 2023 ... but binary packed images are pretty compact.

Perhaps switching from png->svg just moves some of the processing to the client, or out of the rrdtool process into the web-server, or probably a bit of all of the above....

**Comment by murrant** [comment]
I guess it depends on the graph:
rw-r--r-- 1 murrant murrant  85K Nov 17 07:40 graph.png
-rw-r--r-- 1 murrant murrant 309K Nov 17 07:27 graph.svg
-rw-r--r-- 1 murrant murrant 42K Nov 17 07:27 graph.svg.gz

**Comment by laf** [comment]
I'd vote for this to be the default.

**Review by murrant — APPROVED** [review]
We can merge it and see

**Pull request merged**
