### PR TITLE
Alert template clean up  "\r\n\n"

### PR DESCRIPTION
**Pull request by bestlong**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
These sql files aren't used anymore.

**Comment by bestlong** [comment]
Ref #10495

**Comment by murrant** [comment]
Can we remove the \r?  It used to be needed for windows email clients I am pretty sure.

**Comment by bestlong** [comment]
@murrant use web ui create new alert template input two line:

```alertTemplate
A
B
```

then use mysqldump get sql:

```sql
INSERT INTO `alert_templates` VALUES (50,'Default Alert Template','{{ $alert->title }}\nSeverity: {{ $alert->severity }}\n@if ($alert->state == 0) Time elapsed: {{ $alert->elapsed }} @endif\nTimestamp: {{ $alert->timestamp }}\nUnique-ID: {{ $alert->uid }}\nRule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule }} @endif\n@if ($alert->faults) Faults:\n@foreach ($alert->faults as $key => $value)\n  #{{ $key }}: {{ $value[\'string\'] }}\n@endforeach\n@endif\nAlert sent to:\n@foreach ($alert->contacts as $key => $value)\n  {{ $value }} <{{ $key }}>\n@endforeach',NULL,NULL),(51,'Test CRLF','A\nB\n','','');
```

only see \n in `(51,'Test CRLF','A\nB\n','','')`, so i cleanup "\r".

**Comment by bestlong** [comment]
Hi @garysteers database/migration script will affect all user,  and difficult to identify data status.

Only four pieces of data can be solved by copying:

Default Alert Template

```blade
{{ $alert->title }}
Severity: {{ $alert->severity }}
@if ($alert->state == 0) Time elapsed: {{ $alert->elapsed }} @endif
Timestamp: {{ $alert->timestamp }}
Unique-ID: {{ $alert->uid }}
Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule }} @endif
@if ($alert->faults) Faults:
@foreach ($alert->faults as $key => $value)
  #{{ $key }}: {{ $value['string'] }}
@endforeach
@endif
Alert sent to:
@foreach ($alert->contacts as $key => $value)
  {{ $value }} <{{ $key }}>
@endforeach
```

BGP Sessions.

```blade
{{ $alert->title }}
Severity: {{ $alert->severity }}
@if ($alert->state == 0) Time elapsed: {{ $alert->elapsed }} @endif
Timestamp: {{ $alert->timestamp }}
Unique-ID: {{ $alert->uid }}
Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule }} @endif
@if ($alert->faults) Faults:
@foreach ($alert->faults as $key => $value)
  #{{ $key }}: {{ $value['string'] }}
  Peer: {{ $value['astext'] }}
  Peer IP: {{ $value['bgpPeerIdentifier'] }}
  Peer AS: {{ $value['bgpPeerRemoteAs'] }}
  Peer EstTime: {{ $value['bgpPeerFsmEstablishedTime'] }}
  Peer State: {{ $value['bgpPeerState'] }}
@endforeach
@endif
```

Ports

```blade
{{ $alert->title }}
Severity: {{ $alert->severity }}
@if ($alert->state == 0) Time elapsed: {{ $alert->elapsed }} @endif
Timestamp: {{ $alert->timestamp }}
Unique-ID: {{ $alert->uid }}
Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule }} @endif
@if ($alert->faults) Faults:
@foreach ($alert->faults as $key => $value)
  #{{ $key }}: {{ $value['string'] }}
  Port: {{ $value['ifName'] }}
  Port Name: {{ $value['ifAlias'] }}
  Port Status: {{ $value['message'] }}
@endforeach
@endif
```

Temperature

```blade
{{ $alert->title }}
Severity: {{ $alert->severity }}
@if ($alert->state == 0) Time elapsed: {{ $alert->elapsed }} @endif
Timestamp: {{ $alert->timestamp }}
Unique-ID: {{ $alert->uid }}
Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule }} @endif
@if ($alert->faults) Faults:
@foreach ($alert->faults as $key => $value)
  #{{ $key }}: {{ $value['string'] }}
  Temperature: {{ $value['sensor_current'] }}
  Previous Measurement: {{ $value['sensor_prev'] }}
@endforeach
@endif
```

or U can clean all alert template then run seed

```bash
root@ubuntu-bionic:~# cd /opt/librenms/
root@ubuntu-bionic:/opt/librenms# php artisan db:seed --class=DefaultAlertTemplateSeeder
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Database seeding completed successfully.
root@ubuntu-bionic:/opt/librenms#
```

**Comment by bestlong** [comment]
Hi @murrant 

Do i need to fix codeclimate issues ?

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/message-alert-mail/9550/3

**Comment by slushi66** [comment]
hello
> @garysteers you can delete all existing templates (not just included ones) with `TRUNCATE TABLE alert_templates;` and then run `./lnms db:seed`

I did TRUNCATE TABLE but when I did this comand: `./lnms db:seed`
I have this error:

There are no commands defined in the "db" namespace.

Do you have an idea ?
My mail alert doesn't work since I did the `TRUNCATE TABLE alert_templates;`

Thank you,
Aki

**Comment by murrant** [comment]
php artisan db:seed

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
