### PR TITLE
easily setting font colors for RRD graphs is now possible

### PR DESCRIPTION
**Pull request by VVelox**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Now make all your font colors green for graph text.

    $config['rrdgraph_def_text_color'] = '00FF00';

Or really any other color. This is handy for those of us who use light on dark schemes as the black on white is hard to read.

https://i.imgur.com/mXdxmC6.png  <--- 00FF00 example graph

### CODE REVIEW

**Comment by kkrumm1** [comment]
Are you going to post the code for the your dark theme? 😀

**Comment by VVelox** [comment]
@kkrumm1 I use Dark Background and Light Text addon with firefox. I don't have a custom theme (Is that even possible with LibreNMS?).

https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/

That said also added a note about the variable and suggested 0000FF as a color that works decent for both dark and light.

**Comment by kkrumm1** [comment]
It is possible another user in the forums made some custom css. I will see if I can find the post. 

Kevin

> On Apr 10, 2019, at 6:20 AM, VVelox <notifications@github.com> wrote:
> 
> @kkrumm1 I use Dark Background and Light Text addon with firefox. I don't have a custom theme (Is that even possible with LibreNMS?).
> 
> https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/
> 
> That said also added a note about the variable and suggested 0000FF as a color that works decent for both dark and light.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 










CONFIDENTIALITY NOTICE: This email & attached documents may 
contain confidential information. All information is intended only for the 
use of the named recipient. If you are not the named recipient, you are not 
authorized to read, disclose, copy, distribute or take any action in 
reliance on the information and any action other than immediate delivery to 
the named recipient is strictly prohibited. If you have received this email 
in error, do not read the information and please immediately notify sender 
by telephone to arrange for a return of the original documents. If you are 
the named recipient you are not authorized to reveal any of this 
information to any other unauthorized person. If you did not receive all 
pages listed or if pages are not legible, please immediately notify sender 
by phone.

**Comment by kkrumm1** [comment]
Check out this post https://community.librenms.org/t/graph-legend-text-color/7748

**Comment by murrant** [comment]
Web files have been moved to includes/html, you will need to update your PR, sorry for the trouble. Let us know if you need any help.

**Comment by VVelox** [comment]
@murrant Updated from master. First time merge has ever worked nicely for me. :)

**Pull request merged**
