### PR TITLE
newdevice: Add Kyocera Mita support

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Kyocera Mita printers have "KYOCERA MITA Printing System" in its sysDescr

### CODE REVIEW

**Comment by laf** [comment]
How come you closed this?

**Comment by aldemira** [comment]
I want to create a new branch, before rebasing my master branch to librenms/master.  I don't like to see all those redundant commit messages here. I'll resubmit it soon.

**Comment by laf** [comment]
We squash and merge anyway so it really doesn't matter.

**Comment by aldemira** [comment]
Any idea why the test is failing?

**Comment by f0o** [comment]
https://travis-ci.org/librenms/librenms/jobs/198763690#L302

**Comment by laf** [comment]
Just realised, you want to use sysDescr_regex rather than sysDescr in that yaml file.

**Comment by laf** [comment]
I've pushed the fix, will merge once travis agrees.

**Pull request merged**
