### PR TITLE
Add support for some UPS that use same card as multimatic

### PR DESCRIPTION
**Pull request by xbeaudouin**
There is some UPS that have same management card as a multimatic that use UPS-MIB.
This pull request add "simple" way to support them.

### CODE REVIEW

**Comment by laf** [comment]
Hi @xbeaudouin 

We will need you to sign the contributors agreement, an example of a commit is here: https://github.com/paszczus/librenms/commit/75119b111c4ee32facfb40e4926f1aaef0dda79b

**Comment by xbeaudouin** [comment]
Do I have to make another pull request for that ?

**Comment by f0o** [comment]
@xbeaudouin preferably yes but you can also attach it to this one as it's quite small.
Can you rebase your branch against upstream/master before pushing again? It's to get rid of the 'merge' commit you got there. (you might need to force-push after rebasing)

**Comment by xbeaudouin** [comment]
Agreement done.

**Pull request merged**
