### PR TITLE
feature: RRD rename operations

### PR DESCRIPTION
**Pull request by murrant**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Template rename operations and only run them once

### CODE REVIEW

**Comment by laf** [comment]
I'm assuming this doesn't work for people not running a shared fs? If not, what would happen in that situation?

**Comment by murrant** [comment]
It is not run if it is is tried on a device that doesn't have access.
The version is updated until after it succeeds.  Right now there are no checks for that version.

You need at least one device running Dail.sh that has access to the files.

**Comment by laf** [comment]
added to my home install, will code review soon as I can

**Comment by laf** [comment]
Didn't bother checking when I deployed at home - it's failing anyway :( Will check why

**Comment by laf** [comment]
```bash
PHP Fatal error:  Call to a member function getPattern() on a non-object in /opt/librenms/includes/polling/ports.inc.php on line 230

Fatal error: Call to a member function getPattern() on a non-object in /opt/librenms/includes/polling/ports.inc.php on line 230
```

**Comment by laf** [comment]
Updated install to carry on testing.

**Comment by laf** [comment]
I've got a number of devices still failing to poll for this:

```
PHP Fatal error:  Uncaught exception 'LibreNMS\Exceptions\FileExistsException' with message 'Destination file /opt/librenms/rrd/dns01/port-id.rrd exists' in /opt/librenms/LibreNMS/RRD/RenameOp.php:133
Stack trace:
#0 /opt/librenms/LibreNMS/RRD/RenameOp.php(94): LibreNMS\RRD\RenameOp->renameFile(Array, 'port-2', 'port-id')
#1 /opt/librenms/includes/polling/ports.inc.php(232): LibreNMS\RRD\RenameOp->run()
#2 /opt/librenms/includes/polling/functions.inc.php(261): include('/opt/librenms/i...')
#3 /opt/librenms/poller.php(134): poll_device(Array, Array)
#4 {main}
  thrown in /opt/librenms/LibreNMS/RRD/RenameOp.php on line 133

Fatal error: Uncaught exception 'LibreNMS\Exceptions\FileExistsException' with message 'Destination file /opt/librenms/rrd/dns01/port-id.rrd exists' in /opt/librenms/LibreNMS/RRD/RenameOp.php:133
Stack trace:
#0 /opt/librenms/LibreNMS/RRD/RenameOp.php(94): LibreNMS\RRD\RenameOp->renameFile(Array, 'port-2', 'port-id')
#1 /opt/librenms/includes/polling/ports.inc.php(232): LibreNMS\RRD\RenameOp->run()
#2 /opt/librenms/includes/polling/functions.inc.php(261): include('/opt/librenms/i...')
#3 /opt/librenms/poller.php(134): poll_device(Array, Array)
#4 {main}
  thrown in /opt/librenms/LibreNMS/RRD/RenameOp.php on line 133
```

**Comment by murrant** [comment]
I'm unsure how much demand there is for this feature...

**Pull request closed without merging**
