### PR TITLE
Configurable Network Map Parameters

### LINKED ISSUE #1536: Configurable Network Map Parameters
Idea is to make the network map paramteres in [html/includes/print-map.inc.php](https://github.com/librenms/librenms/blob/master/html/includes/print-map.inc.php) configurable via ```config.php```.

Current map configuration is not ideal for me so I want to change it.  Thought I'd just make it configurable.  

If no objections I'll start on it.
Useful to this:
http://visjs.org/network_examples.html
http://visjs.org/docs/network/physics.html#
http://visjs.org/docs/network/edges.html#

### PR DESCRIPTION
**Pull request by spinza**
Allows one to change network map options.
Fixes #1536.

### CODE REVIEW

**Comment by f0o** [comment]
Would you mind converting the json object into a native PHP-Array please?
It's much simpler to change a single spec when you dont need to redefine the entire json-chunk.
Thanks! :)

**Comment by laf** [comment]
I said about doing it this way rather than having a big array or loads of config options. 

Not sure that it's the type of thing people will change that much hence just allowing the Json to be changed.

**Comment by f0o** [comment]
Haha ok, if it's been agreed on this format I've nothing to nag :)
Thanks for the contribution :+1:

**Comment by f0o** [comment]
One thing tho, nearly forgot.. @spinza we recently changed our contribution guidelines, would you mind reviewing them and resign your agreement (adding a whitespace behind your line is sufficient)?
Thanks a lot! :)

**Comment by laf** [comment]
Not agreed, it was my suggestion :)

Visjs has a load of physics engines and options, just seemed the easiest way?

**Comment by spinza** [comment]
I'll sign.

**Pull request merged**
