### PR TITLE
Add support for Extreme SLX-OS.

### PR DESCRIPTION
**Pull request by kaniini**
Adds support for Extreme SLX-OS devices. Extreme SLX-OS is a fork of Brocade NetworkOS.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by netmax79** [comment]
I tested this with two SLX 9640 devices. They were not detected.

I added .1.3.6.1.4.1.1916.2.306 sysobject id to slxos.yaml, than it showed up cpu and memory usage.

For temperature and fanspeeds i had to link following files 
includes/discovery/sensors/fanspeed/slxos.inc.php -> nos.inc.php
includes/discovery/sensors/temperature/slxos.inc.php -> nos.inc.php

**Comment by kaniini** [comment]
Thanks for testing @netmax79.  Making those changes appears to still work with the vSLX image I am testing against, so I will do so momentarily.

**Comment by kaniini** [comment]
It would be nice if somebody could test and merge this.

**Comment by Jellyfrog** [comment]
@kaniini please check tests below

**Comment by murrant** [comment]
Would be great if you could implement the sensors in yaml instead of copying the nos php files.

**Comment by kaniini** [comment]
I do not see any documentation for implementing those sensors in YAML, which is why I copied the PHP files.  If somebody can point me at an example YAML file for those kinds of sensors, I can take it from there.

**Comment by murrant** [comment]
https://docs.librenms.org/Developing/os/Health-Information/

**Comment by murrant** [comment]
Any progress on this?

**Comment by murrant** [comment]
Closing due to inactivity, feel free to resubmit or have us reopen this.

**Pull request closed without merging**
