### PR TITLE
Fix invalid dates in the database

### PR DESCRIPTION
**Pull request by Jellyfrog**
Preparing work for #12501

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@librenms/reviewers need people to test this, shouldn't break anything but take a database backup.

**Comment by murrant** [comment]
@Jellyfrog seems fine, but does not prevent new ones to be added. right?

**Comment by Jellyfrog** [comment]
Nope, but the ones I found in my db are not inserted anymore

**Comment by murrant** [comment]
If I remember, the notifications will be inserted for every new user.

**Review by murrant — APPROVED** [review]
Pending merge of #12523

**Pull request merged**
