### PR TITLE
Ports API: Workaround for ifNames with slashes

### PR DESCRIPTION
**Pull request by murrant**
Basically,

/api/v0/devices/3/ports/0%2f4 -> /api/v0/devices/3/ports/ifName?ifName=0/4
/api/v0/devices/3/ports/0%2f4/port_bits -> /api/v0/devices/3/ports/ifName/port_bits?ifName=0/4

Or you can just use port_id. If ifName doesn't contain / it will still work.

Also adds port_id to the default output for the ports list.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/api-issue-url-encoding-issue-with-port-graph/9146/7

**Comment by kate66** [comment]
This is still not working as it was previously, the API call is getting a 404.

`api.ip - - [09/Aug/2019:09:05:29 -0400] "GET /api/v0/devices/19/ports/ge-0%2F0%2F41/port_bits?from=1565269528&to=1565355928&width=1000 HTTP/1.1" 404 254 "-" "-"`

**Comment by laf** [comment]
Is this backwards compatible? If not, I'd say this is a breaking change that shouldn't got in without a version bump of the API

**Comment by murrant** [comment]
@laf it is a breaking change that we can't fix without breaking bc.  Slashes in routes breaks the rfc :(.  Additionally, there is a workaround for the last route segment, but we can't use that because of a collision with the other route...  So bad stuff all around.

**Comment by laf** [comment]
Is this because the api is now going through Laravel I assume?

**Comment by murrant** [comment]
Yes.   I might have another work around, basically subverting the Laravel routing.

**Comment by murrant** [comment]
@laf ok, should restore original functionality.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/api-issue-url-encoding-issue-with-port-graph/9146/14

**Comment by laf** [comment]
Awesome. Thanks for keeping it compatible. Makes it easier at work :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-55-release-changelog-august-2019/9428/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/api-issue-with-search-port/13341/1

**Pull request merged**
