### PR TITLE
Add LINE Notify Alert Transport.

### PR DESCRIPTION
**Pull request by bestlong**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/librenms-can-send-alarm-messages-to-line-notify/4240/6

**Comment by sujunmin** [comment]
Test seems ok, maybe the /r/n (newline and return) need to be handled.

test1
test2
test3

**Comment by bestlong** [comment]
@sujunmin can you provide template code. my notify seems good

IMG_4134

My alert template code:

```php
{{ $alert->title }}
Severity: {{ $alert->severity }}
@if ($alert->state == 0) Time elapsed: {{ $alert->elapsed }} @endif
Timestamp: {{ $alert->timestamp }}
Unique-ID: {{ $alert->uid }}
Rule: @if ($alert->name) {{ $alert->name }} @else {{ $alert->rule }} @endif
@if ($alert->faults) Faults:
@foreach ($alert->faults as $key => $value)
  {{ $key }}: {{ $value['string'] }}
@endforeach
@endif
Alert sent to:
@foreach ($alert->contacts as $key => $value)
  {{ $value }} <{{ $key }}>
@endforeach
```

**Comment by sujunmin** [comment]
@bestlong This is the test for using default Devices up/down from collection
Screenshot_20190807_131602

**Comment by bestlong** [comment]
@sujunmin Your are show alert rule list and layout is different from me.
My LibreNMS version is 1.54-16

Alert template is define notify content, maybe your is old format.

螢幕快照 2019-08-07 13 30 55

螢幕快照 2019-08-07 13 34 40

螢幕快照 2019-08-07 13 35 20

**Comment by sujunmin** [comment]
@bestlong 
```
librenms@librenms:~$ ./validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.54
DB Schema | 2019_07_03_132417_create_mpls_saps_table (139)
PHP       | 7.2.19-0ubuntu0.18.04.1
MySQL     | 10.1.40-MariaDB-0ubuntu0.18.04.1
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================
```

You can test by using default collection from Alert -> Alert Rules -> Create rules from collection -> Select "Devices up/down".

**Comment by bestlong** [comment]
@sujunmin OK, I got it.

**Comment by sujunmin** [comment]
@bestlong Hi, I found the alert collection use "Default Alert Template" in "Alert Template", and it will keep \r\n in the template, This problem should be fixed either use specified (user-defined) template, or modify the default template that removed all \r\n in the default template.

**Comment by bestlong** [comment]
New install alert template:

librenms alert template

About template contain "\r\n\n" problem. is affecting all transports (was test email and telegram).
need manual update alert template after install.

or modify sql-schema 123.sql and 202.sql for new install.

**Comment by wayneleetw** [comment]
Hi, It also works for me. thanks

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-56-release-changelog-september-2019/9671/1

**Pull request merged**
