### PR TITLE
Fix: netstats-udp, tcp and ip rrd's not updating

### PR DESCRIPTION
**Pull request by slashdoom**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by slashdoom** [comment]
Seems to have broken with PR #9537.  Attempt to fix.

**Comment by slashdoom** [comment]
CLA is signed.

**Comment by CirnoT** [comment]
You have to click link to recheck CLA.

**Comment by CirnoT** [comment]
These changes make no sense to me. Does it actually work for you? All it did for me was to generate empty RRD file with no actual data.

**Comment by murrant** [comment]
The fix the the correct approach (LibreNMS now escapes all snmp arguments).  Need to use an array so each oid gets escaped individually instead of all together.

Just the data isn't formatted as expected after the change.  I'll update netstats-ip.inc.php to show what I think is the correct fix.

**Comment by slashdoom** [comment]
Thanks all.  Updates pushed and seems to working/graphing.

**Comment by slashdoom** [comment]
That makes sense.  So I've changed back to checking $data and changed the checks to is_numeric().  I also moved the if statement up so it doesn't run the for loop if the checks fail.

**Comment by murrant** [comment]
Thanks @slashdoom :+1:

**Pull request merged**
