### PR TITLE
Set device ping_perf scale_min to 0

### PR DESCRIPTION
**Pull request by murrant**
And allow scale_min, scale_max, and scale_rigid to be set via url parameter

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by electrocret — APPROVED** [review]

**Comment by fcqpl** [comment]
Hi @murrant,
This commit added some unwanted padding at top of chart. Can you look at this?
Before:
chrome_BaLSOk3CXV
After:
chrome_JaDg92srfv

**Comment by murrant** [comment]
Odd, maybe rigid is set now

**Comment by murrant** [comment]
@fcqpl try this #14992  Please respond there if it fixes your issue.

**Comment by fcqpl** [comment]
@murrant, #14992 fixes this issue. Thanks!

**Pull request merged**
