### PR TITLE
skip creation of "Stack Ring - Redundant" sensor for Cisco StackWise Virtual 

### LINKED ISSUE #16889: [Cisco StackWise Virtual (Virtual Stack)] Stack Ring - Redundant always returns FALSE
### The problem

Cisco Catalyst 9000 Series switches support 3 modes of stacking operation:
- standalone switch [Cat9200/Cat9300/Cat9400/Cat9500/Cat9600]
- backside stacking [BSS] - StackWise [Cat9200/Cat9300]
- frontside stacking [FSS] - StackWise Virtual [Cat9400/Cat9500/Cat9600]

I observe the following behaviors of the "Stack Ring - Redundant" state sensor depending on the mode of operation:

A) The "Stack Ring - Redundant" state sensor always reports FALSE for frontside stacking [FSS] StackWise Virtual pairs.
B) The "Stack Ring - Redundant" state sensor reports the correct values [TRUE or FALSE] for backside stacking [BSS] - StackWise stacks.
C) The "Stack Ring - Redundant" state sensor is not shown for standalone switches

Behaviors B and C are correct, but A is incorrect.

Here is an example of a state sensor as observed on a StackWise Virtual pair consisting of 2x C9500-48Y4C switches running 17.12.04 IOS-XE software.

stack_ring_redundant

The problem is not specific to a particular device model or software version [all StackWise Virtual devices show the same behavior].

I studied the code in https://github.com/librenms/librenms/blob/master/includes/discovery/sensors/state/cisco.inc.php to understand what this sensor means and where it gets data to determine its value.

I understand that this comes from CISCO-STACKWISE-MIB, more specifically from cswRingRedundant OID.

I was in touch with the software development department and internally received confirmation that CISCO-STACKWISE-MIB was originally developed for the backside stacking [BSS] - Stackwise solution and particularly cswRingRedundant is not suitable for monitoring in frontside stacking [FSS] - Stackwise Virtual type of HA clusters.
The specific reason is that cswRingRedundant is used to monitor the status of stack ring that is built via dedicated stacking cables on backside stacking [BSS] - StackWise stacks.
As frontside stacking [FSS] - StackWise Virtual does not use dedicated stacking cables to form a ring (it uses transceivers on front panel network interfaces), the value reported via cswRingRedundant OID is not relevant.

Having Stack Ring - Redundant always return FALSE on frontside stacking [FSS] - StackWise Virtual causes an unnecessary alarm simply because LibreNMS is monitoring OID that does not make sense for a particular stacking solution.

I would propose not creating this state sensor for devices operating in frontside stacking [FSS] - StackWise Virtual model.
LibreNMS already displays "VSS Mode", which obtains value from cRFCfgRedundancyOperMode and reports correct status [most notable nonRedundant//coldStandbyRedundant//warmStandbyRedundant//hotStandbyRedundant] and thus the removal of "Stack Ring - Redundant" should not be an issue.

Please let me know what you think.

I'll raise a PR if you agree with the proposed approach.

### Output of ./validate.php

```txt
librenms@vagrant:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-106-g6bf98b2b7 (2024-12-17T09:57:04+01:00)
DB Schema | 2024_10_24_131715_mpls_sdp_bindings_enum_string (310)
PHP       | 8.3.6
Python    | 3.12.3
Database  | MariaDB 10.11.8-MariaDB-0ubuntu0.24.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.4.pre2
===========================================

[OK]    Composer Version: 2.8.4
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
librenms@vagrant:~$
```

### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

_No response_

### PR DESCRIPTION
**Pull request by makriska**
This fixes #16889
Long story short, Stack Ring - Redundant obtains value from cswRingRedundant OID which has no meaning for StackWise Virtual.
Hence I propose skipping it for StackWise Virtual as cswRingRedundant OID always returns FALSE, which generates an alert.
This is a false positive alert due to monitoring OID that is not relevant to StackWise Virtual.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by makriska** [comment]
I added test data from all StackWise Virtual systems that identify themselves as 'Virtual Stack' in entPhysicalName.1
Cat9400  [C9404R with C9400-SUP-1XL]
Cat9400X [C9407R with C9400X-SUP-2]
Cat9500H [C9500-48Y4C]
Cat9500X [C9500X-60L4D]
Cat9600  [C9606R with C9600-SUP-1]
Cat9600X [C9606R with C9600X-SUP-2]

**Comment by makriska** [comment]
I finished testing in the lab on various StackWise Virtual platforms.
I collected and added test data from these systems.

@PipoCanaja 
The actual code change remains the same as yesterday when you reviewed and approved it.

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by PipoCanaja** [comment]
Thanx @makriska !

**Comment by makriska** [comment]
this is strange
could you please help me get past the "license/cla Expected — Waiting for status to be reported" check?
I have agreed to the CLA for librenms/librenms as shown below
Screenshot 2024-12-20 at 07 01 32

**Comment by makriska** [comment]
force run test

**Pull request merged**
