### PR TITLE
Ubiquiti Edgepower OS definition

### PR DESCRIPTION
**Pull request by jepke**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@jepke Hey, thanks for the Pull Request.  Looking at this, it is actually and EdgeOS device :D  can you move everything to edgeos (by renaming the files)

**Comment by jepke** [comment]
> @jepke Hey, thanks for the Pull Request. Looking at this, it is actually and EdgeOS device :D can you move everything to edgeos

Its odd but its a airos firmware but they used the edgeOS MIB as far as i know. Ubiquiti needs to do some development on those edgepowers as snmp seems a bit buggy sometimes it gives back zero values and the device is fine. Also when the edgepower is running on battery backup the PSU state snmp value has still the charge value.

**Comment by PipoCanaja** [comment]
@jepke If you don't mind, I'll close this PR for now, until you find out exactly where this device belongs. Feel free to repoen it if necessary. You can even continue the discussion on the closed PR.

**Comment by jepke** [comment]
Finally found some time to move everything over to Edgeos. But i cant reopen this one it seems

**Comment by jepke** [comment]
this is a duplicate of #11315 which is already merged. I didn't know how to open a closed PR

**Pull request closed without merging**
