### PR TITLE
Add automated responses for some labels

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Did you set 2 blank lines between phrases on purpose?

**Comment by murrant** [comment]
@TheGreatDoc yes, it will be one blank line in the rendered comment.  Check YAML syntax.

**Comment by TheGreatDoc** [comment]
@murrant call me idiot but only I've found is this: https://github.com/apps/label-actions and dont see anything about that. Of course, I believe you when you say it, just want to know better how it works ;)

**Comment by murrant** [comment]
@TheGreatDoc https://github.com/dessant/label-actions/issues/1  :wink:

**Pull request merged**
