### PR TITLE
Revert to port description on port_link in Ports-Type pages after #13143

### PR DESCRIPTION
**Pull request by fbourqui**
Consistent with Customers pages.
For a port to be in a Ports-Type page, it needs a parsed description PorType : Transit, Peering, Core, Custom, ...

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This looks odd to me, can you include a screenshot?

**Comment by fbourqui** [comment]
Hello, 
You were right, doing the screenshot, made me correct the code to get the same result as before the merged change #13143 

Before-change_#13143
Before-change_#13143

after_change_#13143
after_change_#13143

after_change_#13149-not-good
after_change_#13149-not-good

[after_change_#13149-corrected
after_change_#13149-corrected

**Review by murrant — COMMENTED** [review]
Fix looks more correct now, but it makes me wonder if port_descr_descr should be checked in the generate_port_link code?

**Comment by fbourqui** [comment]
generate_port_link is called from 66 different places, with different expectations.
 
Are you worrying that  port_descr_descr would be undefined, or "" ?
That should not be the case as to set the portType you need a parsed description, and Unless you description to be parsed like:
Core:(just a note)
You should always get something in port_descr_descr.

**Review by murrant — APPROVED** [review]

**Pull request merged**
