### PR TITLE
Allow linked maps to have a device selected

### PR DESCRIPTION
**Pull request by eskyuu**
This PR allows custom maps to have both a device and a linked map selected.  When both are selected, the node title and double-click will show the linked map information.

This is needed if we want to create an overview map where each node is a link to a more detailed map, but also want to show bandwidth between the nodes.

Feature has been requested here:
https://community.librenms.org/t/custom-map-node-with-device-name-and-link-to-map/26111

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
My thoughts on how that should work is to just allow any port to be selected for edges, but if this is easier to keep things consistent from a code perspective, this works.

**Comment by eskyuu** [comment]
I was thinking that the mechanics of how this works isn't as intuitive as it could be.  Having said that, I plan on keeping most of the changes made because I think having the explicit device_id and linked_map_id fields in the node dataset is nicer than overloading the title.

I will add a new drop-down list to select a device in the edge modal for the case where neither node is linked to a device.

**Comment by eskyuu** [comment]
I decided to have both options.  From the tickets that have come through, it looks like many people like using device icons as the node image, so allowing devices to link to another map may be useful.  I have also allowed for a device to be selected to search ports for an edge that is linked to 2 non-device nodes.

**Review by murrant — APPROVED** [review]
LGTM

**Pull request merged**
