### PR TITLE
fix: snmp_get_multi returns no data if the oid doesn't contain a period

### PR DESCRIPTION
**Pull request by murrant**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
The other fix is to simple add:
```
if (is_null($index)) {
    $index = 0;
}
```

**Comment by erotel** [comment]
HI im test and for me work this code:

   

```
if (!str_contains($value, 'at this OID')) { 
           if (is_null($index)) {
                $index = 0;
                if (empty($oid)) {
                    continue; // no index or oid
                }
            }
       $array[$index][$oid] = $value;
}
```

**Comment by laf** [comment]
How does this help when a device is asked for sysUptime.0 and replies with sysUptime = X as in the code we will expect .0 to be there or am I misunderstanding why this patch is proposed?

**Comment by murrant** [comment]
It doesn't work around the device bugs, just makes it possible to.

So, to work around the device bug, something like this is also needed.:
```
if (isset($snmpdata[0])) {
   $poll_device = $snmpdata[0];
} else {
     $poll_device = $snmpdata;
}
```

**Comment by laf** [comment]
But doesn't this still then need custom code in the poller / core module to make use of the returned data that doesn't have the array index of 0?

**Comment by erotel** [comment]
Podle mě není nic víc měnit. Tahle oprava jen přidá k oid index 0,pokud tam není žádný index. Pokud oid index má, nic se nemění.

**Comment by murrant** [comment]
@laf This does NOT fix the issue @erotel is having with his device.  I just fixed a bug that he uncovered.

**Pull request merged**
