### PR TITLE
Added discovery support for Alcatel-Lucent OmniSwitch 6900

### PR DESCRIPTION
**Pull request by einhirn**
I have yet to find out how to add this to #1251 ...

### CODE REVIEW

**Comment by laf** [comment]
Thanks @einhirn 

Can you also submit a commit for signing the contributors agreement, you can do this in this PR but needs to be a new commit:

E.g: https://github.com/librenms/librenms/pull/1237

With this, does the polling of aos still pick up hardware and version or does this need to be updated as well? includes/polling/os/aos.inc.php

**Comment by einhirn** [comment]
It seems like hardware and version info is polled ok without further change:
"Alcatel-Lucent OS6900-X40 7.3.1.682.R01 Service Release, March 18, 2013."

**Comment by laf** [comment]
@einhirn Excellent, if you can submit the extra commit to the contributors then we can get this merged in.

**Comment by einhirn** [comment]
@laf I think I did submit it already. Should be the second commit in this pull request

**Comment by laf** [comment]
Ah, it hadn't refreshed here :) Thanks @einhirn

**Pull request merged**
