### PR TITLE
Added Slack mrkdwn support in alert messages

### PR DESCRIPTION
**Pull request by tslytsly**
Noticed that my Slack alerts were not being formatted, realised it's because we pass the alert as an attachment, which is not formatted by slack by default.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

---
This change is [Reviewable](https://reviewable.io/reviews/librenms/librenms/7202)

### CODE REVIEW

**Comment by laf** [comment]
@pblasquez - Can you take a look at this, you changed it to the attachment style at some stage so I'd like to avoid flip flopping between the two.

**Comment by tslytsly** [comment]
> @laf you changed it to the attachment style at some stage so I'd like to avoid flip flopping between the two.

I haven't changed it from attachment, I've only added an option to enable mrkdwn formatting. 
It's being passed in the same way.

**Comment by laf** [comment]
@tslytsly Ah ok.

Would be good if @pblasquez could review anyway.

**Comment by pblasquez** [comment]
Sure, @laf. Will test as well.

**Comment by laf** [comment]
Thanks 👍

**Comment by tslytsly** [comment]
Hi, @pblasquez 

Did you get chance to test this?

😄

**Comment by pblasquez** [comment]
Did not get a chance to test but I did read the docs on the 'mrkdwn_in' option and this add gets the thumbs-up from me.

**Comment by tslytsly** [comment]
@pblasquez thanks.

**Pull request merged**
