### PR TITLE
docs: Reorganised alerting docs + added some clarifications

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
I'm fine with breaking these into pages, but it  we need better navigation.  Like a link list on the left side.

**Comment by laf** [comment]
I don't think it's possible to have a custom TOC per page. we might be able to fudge it with headings in each doc.

**Comment by murrant** [comment]
I'll give it a look.

**Comment by murrant** [comment]
My main problem with breaking things up into smaller pages is it is difficult to move between the the pages.  Like there is not go to next page.

**Comment by laf** [comment]
That is a problem but is it a worse problem to have than a huge wall of text?

**Comment by murrant** [comment]
Wish we had a little more control...

**Pull request merged**
