### PR TITLE
webui: About align

### PR DESCRIPTION
**Pull request by benwa**
right align is best align

### CODE REVIEW

**Comment by laf** [comment]
New:

image


Old:

image

I'll admit I'm not a fan of the website links in the new format, looks cleaner the old way. Undecided about the version list but I'd say old way looks better again.

**Comment by laf** [comment]
Tagging @librenms/reviewers

**Comment by benwa** [comment]
Oh man the links look weird.  It might be a difference in rendering.  Shouldn't include that commit then.

**Comment by paulgear** [comment]
I don't think right align looks better at all.  I would be happy with an indent on the left, but lining up the beginning of the headings rather than the end makes the table a lot easier to scan. -1 from me.

**Comment by laf** [comment]
bump

**Comment by laf** [comment]
Closing, feel free to re-open when you've addressed the issues.

**Pull request closed without merging**
