### PR TITLE
Add purge-port scipt to allow deleting of ports from the CLI.

### PR DESCRIPTION
**Pull request by BarbarossaTM**
This script allows deleting single ports by their port_id or a list
  of ports read from a file or STDIN.

  LibreNMS Port purge tool
        -p <port_id>    Purge single port by it's port-id
        -f <file>       Purge a list of ports, read port-ids from <file>, one on each line.
                        A filename of - means reading from STDIN.

Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Thought I'd responded to this already.

@BarbarossaTM Can you sign the CLA + Also take a look at travis as you have some code styling issues. https://travis-ci.org/librenms/librenms/builds/291562436?utm_source=github_status&utm_medium=notification

**Comment by BarbarossaTM** [comment]
Hey @laf 

Do I have to accept the CLA again? Did so last year already :-)

I fixed the "null"s as well as the "Space before opening parenthesis of function call prohibited" (which are bad for readability IMHO, but ok, your style guidlines), but I don't get what's wrong with the if/while. Does it complain about a missing block for the follwing single line?

Best
Max

**Comment by laf** [comment]
@BarbarossaTM We switched to a new CLA so yes you'll need to re-sign, just click the link from the bot above.

As for the style guides. We follow psr-2 so `if () {` is required.

**Comment by BarbarossaTM** [comment]
@laf I see. Signed the CLA via the link above and added some {} into the code. This should be according the style guidelines now.

Best
Max

**Comment by laf** [comment]
@BarbarossaTM bump

**Pull request merged**
