### PR TITLE
Added mempool support for Avaya ERS 3500

### PR DESCRIPTION
**Pull request by tslytsly**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Hmm, why are we using a regex against sysDescr here?  Odd.  Also, for polling it should check the DB.

Your PR is fine, but this code is troubling.

**Comment by laf** [comment]
@murrant The regex is already done and looks like it's to limit the devices that this support is for.

**Comment by tslytsly** [comment]
@laf and @murrant 
laf is correct, although I don't see a need to limit it? We use a lot of Avaya products, and as far as I know that is the correct OID for all ERS devices.

**Comment by laf** [comment]
@tslytsly remove the if check then :)

**Comment by tslytsly** [comment]
@laf ok then, I'll close this PR and open a new one then.
The MIBs are from well before Avaya bought Nortel, before Nortel bought Baystack I think.
So I doubt there are many switches out there in the wild that don't support these MIBs.
I'll do the same for CPU and Temp, all part of the same MIBs.

**Pull request closed without merging**
