### PR TITLE
Removed duplicate include

### PR DESCRIPTION
**Pull request by geordish**
Fix for #4353

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

### CODE REVIEW

**Comment by deutor** [comment]
I am not sure whether removing that include is correct.
include 'includes/defaults.inc.php'; <--- that was use to "reload" defaults, and as long as in that file there were only $config[] default values it was working. So I think that probably functions should be removed from defaults.inc.php or defaults values (and only values) should be moved to defaults_config.inc.php (and that file could be included in current defaults.inc.php).

**Comment by geordish** [comment]
includes/defaults.inc.php is included in irc.php. It then gets included again when the reload function is called. This is what is causing your error.

I've tested this, and a reload works fine with the script modified in this way,

**Comment by laf** [comment]
I'm guessing removing that though means any core updates to LibreNMS will no longer reload (if changes were made to defaults.inc.php).

My concern though with having yet another include file (to be able to remove the function) is a bit ott.

My vote would be to keep the PR as is, @librenms/reviewers?

**Comment by geordish** [comment]
Oh, hmm, I see what you were on about. Perhaps moving the set_debug function out elsewhere (includes/functions.php?) makes more sense? I would imagine the class loader stuff would also need to move.

**Comment by laf** [comment]
I think set_debug is needed early on :/

**Comment by geordish** [comment]
A quick grep of the source says not:

```
dave@mars:/opt/librenms$ grep -R set_debug
grep: .viminfo: Permission denied
grep: .bash_history: Permission denied
includes/defaults.inc.php:function set_debug($debug)
includes/defaults.inc.php:}//end set_debug()
html/ajax_table.php:set_debug($_REQUEST['debug']);
html/ajax_search.php:set_debug($_REQUEST['debug']);
html/ajax_dash.php:set_debug($_REQUEST['debug']);
html/ajax_listports.php:set_debug($_REQUEST['debug']);
html/ajax_rulesuggest.php:set_debug($_REQUEST['debug']);
html/ajax_form.php:set_debug($_REQUEST['debug']);
```

**Comment by geordish** [comment]
This seems to work OK for me from my quick testing. Feel free to try it.

**Comment by laf** [comment]
I think it's code that was put in place to make use of, we duplicate the use of setting debug up all over and it should be centralised.

**Comment by deutor** [comment]
reload for bot works, however I get "problem with backend" when I enter WebUI and no devices.
[Wed Sep 07 07:11:58 2016] [error] [client 10.0.100.119] PHP Fatal error:  Uncaught Error: Call to undefined function set_debug() in /opt/librenms/html/ajax_dash.php:16\nStack trace:\n#0 {main}\n  thrown in /opt/librenms/html/ajax_dash.php on line 16, referer: http://10.0.0.11/overview/

I think that is because in ajax_dash.php functions.inc.php are included after set_debug call:
`
require_once '../includes/defaults.inc.php';
set_debug($_REQUEST['debug']);
require_once '../config.php';
require_once '../includes/definitions.inc.php';
require_once 'includes/functions.inc.php';
`

**Pull request merged**
