### PR TITLE
Fixing irrelevant values rpm packetloss

### PR DESCRIPTION
**Pull request by geg347**
DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

Hello again,

After weeks of use, I saw that the values of Juniper RPM packetloss was strangely too high. After debugging I found that the problem comes from the DISMAN Ping MIB values. The values currently queried are the current probe values and if a probe is still pending, we got irrelevant pingResultsProbeResponses and pingResultsSentProbes values so the calculated percentage is wrong.
So to fix this I changed the MIB to Juniper's one (jnxPingLastTestResultTable). And now only the completed RPM probe are queried and the graphs correspond to reality.
I also changed the RTT to the average RTT of the last completed probe.

The same behaviour could occur with Huawei NQA depending on the implementation.

(I also fixed a typo in Cisco pollerSla part)

Thanks for checking and have a nice end of day!

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @geg347 
Thanx for the PR. You need to replace the tests files (cause you are now checking OIDs that are not part of the current test files). 
You can check the test results after this replacement is done. 
I'll check the Huawei part if the same issue is found, and adapt it if necessary.
Bye

**Comment by PipoCanaja** [comment]
@geg347 
Removing snmprec data is not the way to go :) 

- For any test variant existing, you should re-run save-test-data on it, so JSON is computed again with your code.
- For at least one variant (the juniper device you own and on which you tested this current patch) you collect new snmp values (or update existing, but this can be messy) and run save-test-data on those new values. 

Thanx

**Review by PipoCanaja — CHANGES_REQUESTED** [review]
still need test data.

**Comment by geg347** [comment]
OK @PipoCanaja sorry I thought I needed to regenerate both test data and snmprec.
Is it OK like this, please?

**Comment by PipoCanaja** [comment]
Your snmprec (the one that was added in the previous PR) must be updated to comply with current code. Andd then you need to regenerate all JSON that are failing (the one from previous PR as well as all others that fail)

**Review by PipoCanaja — APPROVED** [review]
LGTM

**Comment by geg347** [comment]
OK sorry I am not so familiar with unit tests.
So following the procedure on this page : https://docs.librenms.org/Developing/os/Test-Units/,
I need to rerun `./scripts/collect-snmp-data.php -h <myhostname> -m slas -v vmx`?
And then rerun `./scripts/save-test-data.php -o junos -m slas -v vmx`?
Please.
Not sure so I am asking before submitting a 3rd attempt...

**Pull request merged**
