### PR TITLE
Ensure irc fifo-file is shared between dispatcher and core containers

### PR DESCRIPTION
**Pull request by Olen**
Please give a short description what your pull request is for

When running as docker containers, we need to share the ircbot.alert-file between the core container and the dispather container to send alerts using the irc-transport.

Here, the fifo-file is moved to the shared /data-folder if it exists and is owned by the user "librenms" which is true for the Docker images.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
it uses a fifo, hmm, there has to be a better way.

**Comment by Olen** [comment]
> it uses a fifo, hmm, there has to be a better way.

A better way than using a fifo altogether to communicate with the bot?  
Or a better way to share the fifo between containers?
Or a better way to detect if we are using the containerized install to place the fifo in shared folder?

**Comment by murrant** [comment]
A better way than using a fifo.

**Comment by Olen** [comment]
> A better way than using a fifo.

You may be right*, although a fifo is a pretty simple and reliable way to share data between processes.

But just to be clear. The fifo has been the way to communicate with the ircbot since day one. All this PR do is moving the fifo file to inside a shared volume, so it is reachable from more than one container.

* Other options might be using sql to store and read the alerts, although that would lead to more load on the database (but probably not too much of a problem).
Another option could be to create a new api between the bot and the alerting system, but that would require a larger rewrite, and possibly some new endpoints.
All of this takes time and requires more tests etc. While this PR is just ensuring that the bot can send alerts even if it runs in a different container than the dispatcher.

**Pull request merged**
