### PR TITLE
fixed race conditions in distributed poller setup

### PR DESCRIPTION
**Pull request by vsessink**
Fixed a race condition in the master/slave setup where a pollers would race to become master (get/set instead of add); and another possible (but quite unlikely to trigger) race where a slave would try to memc.incr(nodes_tag) while the master had not yet added this tag to memcache.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This looks sound to me, but I have no real way to test it.

**Comment by vsessink** [comment]
It's been running for 2 weeks now - in a globally distributed network. Does that help?

**Comment by murrant** [comment]
Thanks @vsessink

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-63-release-changelog-april-2020/11828/1

**Pull request merged**
