### PR TITLE
WIP: Overwrite resolved IP with custom IP

### PR DESCRIPTION
**Pull request by SourceDoctor**
Usecases:
- hostnames resolved ip should not be used for SNMP
- specifiy IP to avoid "IP flapping", through loadbalancing or such other technics
- Infrastructure preparement for other Networks/Locations
- ...

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
@SourceDoctor the ipaddress field is not used for polling, the hostname field is.

**Comment by SourceDoctor** [comment]
@murrant 

did i missunderstood the `poll_device` function in `includes/polling/functions.inc.php` ?

As i see it run's all the polling, and before it does a DNS Lookup to get the actual IP Address for working with it

**Comment by murrant** [comment]
But $ip is never used for polling.

**Comment by SourceDoctor** [comment]
OK

so i have to do further changes :-)

for what IP is used, if not for polling?

**Comment by SourceDoctor** [comment]
needed a more complex workover ...

**Pull request closed without merging**
