### PR TITLE
I agree to the conditions of the Contributor Agreement

### PR DESCRIPTION
**Pull request by Calvario**
I agree to the conditions of the Contributor Agreement
contained in doc/General/Contributing.md.

### CODE REVIEW

**Comment by odooviet** [comment]
It's provided by ZTE Corporation.

**Comment by Calvario** [comment]
??????

**Comment by laf** [comment]
This pr has been merged in, what's the query?

**Comment by paulgear** [comment]
I think it was just not understanding @odooviet's comment, which was really about another PR.  I'll delete the irrelevant parts of this shortly.

**Pull request merged**
