### PR TITLE
Faster initial database creation

### PR DESCRIPTION
**Pull request by murrant**
Add db dumps to improve initial db migration
On my test system 13s -> 7s, a 46% reduction.
Should help out a lot on systems like RPi

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by haydenseitz** [comment]
This is cool. Instead of keeping the custom schema dump, what if you use [laravel's schema:dump ](https://laravel.com/docs/8.x/migrations#squashing-migrations) to check against? update the checkSchema to use that schema file when running `./validate.php`

**Comment by Jellyfrog** [comment]
@murrant Guessing the connection is closed, so the in-memory database disappears, not sure its even feasible for us to use for tests.

**Comment by murrant** [comment]
@Jellyfrog unsure, probably not a significant gain for in-memory anyway.

**Comment by murrant** [comment]
@haydenseitz yep, just merging in our build-schema.php to the same command which creates our yaml db schema for validation.  And a little automation to generate it for multiple databases.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-november-2020/14124/1

**Pull request merged**
