### PR TITLE
webui: device-groups refresh

### PR DESCRIPTION
**Pull request by crcro**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

before:
screen shot 2018-01-06 at 8 32 28 pm
screen shot 2018-01-06 at 8 32 52 pm

after:
screen shot 2018-01-06 at 8 31 55 pm
screen shot 2018-01-06 at 8 32 07 pm

### CODE REVIEW

**Comment by laf** [comment]
Not sure about this one, we don't have a similar actions menu anywhere else I don't think so it not looks odd and unnatural.

**Comment by crcro** [comment]
we (maybe) have something like this on ports page -> bulk remove deleted ports

**Comment by laf** [comment]
Yeah that was also only added recently.

**Comment by aldemira** [comment]
What about turning that action link into a button?

**Comment by crcro** [comment]
i tried but looks a bit bigger even with btn-sm in my opinion ...

**Comment by murrant** [comment]
I think it should be a button.  A link makes it seem like it goes somewhere. A button makes it seem like it does something.

If it is too big probably move it out of the header.

**Comment by laf** [comment]
@crcro any update on this one?

**Comment by laf** [comment]
@crcro Feel free to reply to this when you have time but for now we are closing the PR.

**Pull request closed without merging**
