### PR TITLE
Add support for new Extreme VSP/VOSS models

### PR DESCRIPTION
**Pull request by ospfbgp**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ospfbgp** [comment]
Adding support for some legacy VSP models and new VSP4900 and 5520 series.  All of the models use the same kernel so no need to add snmpsim data for these. They all use the same OID for fans, power supplies, cpu, memory, vlans and etc...  There is already many VSP models in the snmpsim.  I do not have access to test all these models but I have verified oids from manufacture.

**Comment by murrant** [comment]
Ok, I looked at the reported stats and:
voss: .1.3.6.1.4.1.2272  /^VSP-/
boss: .1.3.6.1.4.1.2272 /^ERS-/
xos: .1.3.6.1.4.1.1916.2

Why are we calling out specific models? (which requires constant updates)

**Comment by murrant** [comment]
Ok, how about this for generic style detection?

boss
```yaml
discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.45.
            - .1.3.6.1.4.1.2272.
        sysDescr:
            - 'Ethernet Switch'
            - 'Ethernet Routing Switch'
            - 'ERS'
            - 'Virtual Services Platform 7024XLS'
            - 'Virtual Services Platform 7024XT'
```

voss
```yaml
discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.1916.2.337 #XA1440
            - .1.3.6.1.4.1.1916.2.338 #XA1480
            - .1.3.6.1.4.1.2272. # everything not caught by boss OS
    -
        sysObjectID:
            - .1.3.6.1.4.1.1916.2.3
        sysDescr:
            - VSP
            - VOSS
```

xos
```yaml
discovery:
    -
        sysObjectID:
            - .1.3.6.1.4.1.1916.2. # everything not caught by voss OS
```

**Comment by ospfbgp** [comment]
I have have cleaned up the yaml file and took your recommendation.  I do not think that boss.yaml needs to be modified.  No boss switches have the oid .1.3.6.1.4.1.2272 so no change should be needed.  There is a 2 x VSP7024 that was built that has the oid 1.3.6.1.4.1.45.3.79.1 and  1.3.6.1.4.1.45.3.79.1.  I do not believe there is a .1.3.

**Comment by ospfbgp** [comment]
This should be complete.  I delete several BOSS, VSP and EXOS in my lab and added back.  Discovery of the OS was correct for each platform.  Thank you Murrant for the logic.  This will allow future VSP to work without making special exceptions.

**Review by Jellyfrog — APPROVED** [review]

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-69-release-changelog-november-2020/14124/1

**Pull request merged**
