### PR TITLE
validate improvements

### PR DESCRIPTION
**Pull request by murrant**
Always output header (may be missing mysql data)
Improve version display, now looks like '1.28-129-g74e6c3edf' <tag>-<commits since tag>-<shortag>
Add mysqli to the list of required extensions, check extensions before init
Add dbIsConnected() function, used to check if we have db in version_info()
Do not die on IPv4 and IPv6 so validate can print errors.
Move git checks so they are output together
fix rrdtool 1.7.0 reports version as 1.7.01.7.0

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
@murrant `LibreNMS  | 1.28-130-gae4e66999` - what does that even mean :)

**Comment by murrant** [comment]
@laf I put it in the post but it got stripped.   It means tag-commits since tag-short commit hash

**Comment by laf** [comment]
So 1.28 = Tag

1.29 is the latest tag though:

```bash
-bash-4.2$ git describe --tags $(git rev-list --tags --max-count=1)
1.29
-bash-4.2$ ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.28-130-gae4e66999
```

**Comment by murrant** [comment]
I'll check it

**Pull request merged**
