### PR TITLE
Removed unused default variables

### PR DESCRIPTION
**Pull request by SaaldjorMike**
These variables looks only to be referenced from within the includes/defaults.inc.php file as far as I can see.

### CODE REVIEW

**Comment by laf** [comment]
Need to be really careful with this, sometimes you can't just grep the config name as it can get built from other variables. For instance all of the:

$config['transit_descr']   = '';

Options are in includes/port-descr-parser.inc.php but built from other variables. Whilst it won't break anything removing them, it will generate superficial warnings. defaults.inc.php are also a location people can check what options are available.

**Comment by SaaldjorMike** [comment]
Need to be careful for sure! The reason for me wanting to remove those things, is that I initially thought I could enable eigrp polling with enabling the option, but it seems to not be implemented at all, which as far as I've discovered is true for all those options I want to remove. Other people might also try to enable options that seems to be available but are not in fact implemented.

**Comment by laf** [comment]
Yeah that's what I'm saying, the options you've removed - some are still used. You can't just grep for the config name to find out :(

**Comment by paulgear** [comment]
As far as I can tell, $config['timestamp_format'] is the only one still used - $config['*_descr'] are still referenced in the documentation, but not elsewhere.

**Comment by laf** [comment]
$config['*_descr'] are used in a file, search for a PR from me with transit in the description. I wrote the code to enable people to do dynamic lists so whilst you will expect those values to be set in config.php by someone it just means they will no longer be defined and throw up warning notices if removed.

The use of the names is built from another variable.

**Comment by SaaldjorMike** [comment]
Aha, let me just clean this up and leave those things there.

**Comment by SaaldjorMike** [comment]
Let me know if other changes are needed. :)

**Comment by paulgear** [comment]
I think the dot/neato/etc. will likely be required due to the PR restoring old map - is that right @laf ?

**Comment by laf** [comment]
A couple of them look to be yeah.

**Comment by f0o** [comment]
I merged the Map-PR ( #1582 ) - This one needs now a revise about unused vars :)
While at it, Would you mind updating the docs as well?

**Comment by SaaldjorMike** [comment]
I've updated the PR earlier to include the few lines that the old network map uses and removed the documentation references to configuration options that are not implemented. Any further changes needed?

**Pull request merged**
