### PR TITLE
Fix ifSpeed override not being applied

### LINKED ISSUE #15226: ifSpeed Custom Changes Revert Back On Next Poll
### The problem

Custom ifSpeed changes do not save and revert back to the default after the next poll. 
This randomly started on 8-13-2023 for all devices in NMS, after running fine for close to 2 years. 
Luckily there were only a few custom ifSpeed assigned. 
image
image
Reverted back after next poll:
image
Recent event showing it was manually set to 40Gbps and changed back:
image

The only way to fix is updating the interface bandwidth on the device which then causes graphs to not fill out correctly. 
image

### Output of ./validate.php

```txt
librenms@librenms-01:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.7.0-75-g8ee1a2034 (2023-08-14T08:16:45-05:00)
DB Schema | 2023_08_02_120455_vendor_ouis_unique_index (255)
PHP       | 8.1.11
Python    | 3.9.2
Database  | MariaDB 10.5.15-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[FAIL]  We have detected that your database schema may be wrong
Database: extra table (report_high_optical_errors_7_days)
Database: extra table (report_low_optical_power_near_end_7_days)
Database: extra table (report_ont_went_missing)
Database: extra table (report_sdber_errors_7_days)
        [FIX]:
        Run the following SQL statements to fix it
        SQL Statements:
         DROP TABLE `report_high_optical_errors_7_days`;
         DROP TABLE `report_low_optical_power_near_end_7_days`;
         DROP TABLE `report_ont_went_missing`;
         DROP TABLE `report_sdber_errors_7_days`;
Attempt to fix this issue (y or n)?:n
[OK]    MySQl and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         scripts/syslog-notify-oxidized.php
[FAIL]  We have found some files that are owned by a different user than 'librenms', this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX]:
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/Google.rrd
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/Level_3.rrd
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/Cloudflare.rrd
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/BGP_Ping_Test/<OMITTED>
         /opt/librenms/rrd/smokeping/server/Old files
         /opt/librenms/rrd/smokeping/server/<OMMITTED>
          and 45 more...
```

### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

_No response_

### PR DESCRIPTION
**Pull request by murrant**
fixes #15226

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by JvGinkel** [comment]
I'm sorry to say but the issue is not resolved.

All `ifSpeed` are now set to 1 so I have all the alerts going off right now. And when I update a value it will be set back to 1 after a snmp update.


Screenshot 2023-08-21 at 08 46 56

**Comment by TheGracens** [comment]
I have the same problem here. A few ports are on ifSpeed  set to 1.   Not all devices and ports,tho.  I have no clue why this is the case.

**Comment by murrant** [comment]
:/ looks like the variable is set differently in a couple different places.

**Comment by BirdDawg01** [comment]
Looks like as time goes on more and more interfaces are setting themselves to 1bps.
Screenshot 2023-08-22 073232
Screenshot 2023-08-22 073307

**Pull request merged**
