### PR TITLE
Add support for power supply on Extreme BOSS switches

### PR DESCRIPTION
**Pull request by ospfbgp**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by ospfbgp** [comment]
I have added support for power supplies.  I have tested on several different stack sizes.  Looks good.  I did some testing on the patch with variety of stacks.  I have included some screen shots.

screen shot 2019-03-03 at 9 41 25 pm
screen shot 2019-03-03 at 9 38 24 pm

**Comment by ospfbgp** [comment]
I have added BOSS to beginning of sensor so it can be search easily and match on with alert rules.  Here is a snapshot of table sensors.

MariaDB [librenms]> select sensor_index,sensor_type,sensor_descr from sensors where sensor_descr like '%BOSS%';
+---------------------------+--------------------+---------------------------------+
| sensor_index              | sensor_type        | sensor_descr                    |
+---------------------------+--------------------+---------------------------------+
| s5ChasComOperState.5.10.0 | s5ChasComOperState | BOSS Unit 1: Temperature Sensor |
| s5ChasComOperState.6.10.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 1     |
| s5ChasComOperState.6.11.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 2     |
| s5ChasComOperState.6.12.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 3     |
| s5ChasComOperState.6.13.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 4     |
| s5ChasComOperState.5.10.0 | s5ChasComOperState | BOSS Unit 1: Temperature Sensor |
| s5ChasComOperState.6.10.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 1     |
| s5ChasComOperState.6.11.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 2     |
| s5ChasComOperState.6.12.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 3     |
| s5ChasComOperState.6.13.0 | s5ChasComOperState | BOSS Unit 1: Internal Fan 4     |
| s5ChasComOperState.4.10.0 | s5ChasComOperState | BOSS Unit 1: Power Supply 1     |
| s5ChasComOperState.4.11.0 | s5ChasComOperState | BOSS Unit 1: Power Supply 2     |
| s5ChasComOperState.4.10.0 | s5ChasComOperState | BOSS Unit 1: Power Supply 1     |
| s5ChasComOperState.4.11.0 | s5ChasComOperState | BOSS Unit 1: Power Supply 2     |
+---------------------------+--------------------+---------------------------------+
14 rows in set (0.00 sec)

**Comment by ospfbgp** [comment]
Should be in working order now.  Addid test data for BOSS ers4950 and ers3510

**Comment by murrant** [comment]
Nice work

**Pull request merged**
