### PR TITLE
fix: Added primary key to perf_times to improve DELETE performance on replicas using ROW based replication

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Relies on #7446 so travis will fail until that's merged.

Replaces #7368

### CODE REVIEW

**Comment by laf** [comment]
Bump?

**Comment by laf** [comment]
Rebased.

**Comment by murrant** [comment]
@laf your db_schema.yaml seems to re-order some of the fields, which is now taken into account for adding missing fields with the new validate.  Perhaps, you need to start a fresh db.

**Comment by laf** [comment]
Dev install, I'd genuinely prefer not to start again :(

I'll manually fix.

**Pull request merged**
