### PR TITLE
Add Oxidized API URL protocol

### PR DESCRIPTION
**Pull request by Zmegolaz**
file_get_contents() need the protocol ("http://" or similar) when fetching remote files, add it to the oxidized API URL config if the user forgot it.

From: https://www.reddit.com/r/LibreNMS/comments/7mrufq/i_am_a_moron_oxidized_config/

I'm not sure this is the best place to add this check, if you have any suggestion, please let me know.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Maybe just doing https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation for now?

Ideally longer term we'd define the config values that should exist in the db so we can validate they exist. We could also then validate the input.

**Comment by Zmegolaz** [comment]
Something like this?

**Comment by laf** [comment]
Close, config still gets updated.

This patch fixes that: https://p.libren.ms/view/raw/b0206dc8

**Comment by laf** [comment]
Brilliant, thanks for that :) We should go back through at some point and do the same for some of the other inputs.

**Pull request merged**
