### PR TITLE
Dynamic config system

### PR DESCRIPTION
**Pull request by laf**
Had to redo this PR as I couldn't get fix the conflicts on the other one without then having to do a forced push.

#277 was the last attempt at this for reference / notes.

### CODE REVIEW

**Comment by f0o** [comment]
:-1: 

Old-styled config.php entries wont be overwritten by the db's entries, right?

**Comment by laf** [comment]
They won't no, it just means they could actually make changes in the webui rather than editing a config file.

**Comment by f0o** [comment]
So in other words the concerns of @paulgear regarding transition from old styled to db driven are cleared up.
Might be worth to mention in the docs that the db-config values wont overwrite the in-file values. Just to avoid the typical 'I changed xyz but nothing happened'.

I merged your changes in my test-env and it works well for me :)

**Comment by f0o** [comment]
Poke @paulgear :)

**Comment by laf** [comment]
Poking @paulgear again :)

**Pull request closed without merging**
