### PR TITLE
Added new raritan logo

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
Just needs compressing. You can do that with https://jakearchibald.github.io/svgomg/

**Comment by laf** [comment]
Just by pasting and copying out of that service I get:

```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 123.59 58.17"><defs><style>.cls-1{fill:#231f20}.cls-2{fill:#ed1c24}</style></defs><title>LNA.Raritan.Logo.4C</title><path class="cls-1" d="M75.34 47.5v2.1h2.22v5.49h2.01V47.5h-4.23m-.27 2.1v-2.76h-.48v2.76h.48"/><path class="cls-1" d="M76.53 55.09v-2.1h-2.21v-5.48h-2.01v7.58h4.22m.27-2.1v2.77h.49v-2.77h-.49"/><path class="cls-2" d="M83.98 55.48v-8.19h-1.79v8.19h1.79"/><path class="cls-2" d="M96.57 50.27v6h1.91v-3.06c0-1.5 1.7-1.59 1.7-1.59v-1.45a2.85 2.85 0 0 0-1.71.72v-.61h-1.9m7.9-.01v6h1.84v-3.54a.68.68 0 0 1 1.36 0v3.53h1.8v-4.48c0-.9-1.18-2.23-3.17-.94v-.56h-1.84" transform="translate(0 -.79)"/><path class="cls-2" d="M100.62 51.56a3.79 3.79 0 0 1 .85 0c.88 0 .77.75.77.75a2.25 2.25 0 0 0-1-.27 2 2 0 0 0-2 2.18 1.93 1.93 0 0 0 2 2 1.88 1.88 0 0 0 1.14-.35v.38h1.73v-4.07a1.65 1.65 0 0 0-.5-1.41 2.9 2.9 0 0 0-1.7-.6h-1.23v1.4zm.18 2.49a.77.77 0 1 1 .77.77.77.77 0 0 1-.77-.77m11.72.43a1.16 1.16 0 1 1 1.15-1.15 1.15 1.15 0 0 1-1.15 1.15zm0-4a2.68 2.68 0 0 0-2.73 2.84 2.62 2.62 0 0 0 2.71 2.89 1.94 1.94 0 0 0 1-.44v.51h1.85v-8.21h-1.85v2.72a2.34 2.34 0 0 0-1-.33m-19.29 3.97a1.16 1.16 0 1 1 1.16-1.16 1.16 1.16 0 0 1-1.16 1.16zm.13 2.79c-.85 0-1-.58-1-.58h-2.17c.45 3 5.7 3.11 5.94.24v-6.61h-1.78v.62c-1.23-1.25-4.11-.34-4 2.46.09 2.62 2.87 3.41 4 2.4v.7c0 .79-1 .76-1 .76m-7.14-4.7a1 1 0 0 1 2 0zm1-2.46a3 3 0 0 0-2.89 3.09c0 2.13 1.33 3.35 3.08 3.3A2.72 2.72 0 0 0 90 54.36h-1.85a.92.92 0 0 1-.89.41 1 1 0 0 1-1-1h3.87c.22-2.21-1.21-3.71-2.91-3.71" transform="translate(0 -.79)"/><path class="cls-1" d="M116.87 50a.89.89 0 1 1 .89-.89.89.89 0 0 1-.89.89zm0-1.93a1 1 0 1 0 1 1 1 1 0 0 0-1-1" transform="translate(0 -.79)"/><path class="cls-1" d="M116.6 49.05h.34c.11 0 .22 0 .22-.19s-.12-.18-.2-.18h-.37v.37zm0 .6h-.15v-1.1h.5c.18 0 .36.06.36.29a.27.27 0 0 1-.15.26c.06 0 .12.05.13.2v.2c0 .06 0 .08.05.11h-.18a1.32 1.32 0 0 1 0-.27c0-.09 0-.19-.19-.19h-.36v.47M26.8 55.8l-.44-1.31h-2.61l-.45 1.31h-1.5l2.68-7.37h1.13l2.69 7.37zm-1.72-5.2l-.93 2.68H26zm10.41 4.78a1.88 1.88 0 0 1-1.31.49 1.64 1.64 0 0 1-1.35-.57v.51h-1.3v-7.38h1.35v2.45a1.6 1.6 0 0 1 1.31-.54 1.88 1.88 0 0 1 1.31.49 3.2 3.2 0 0 1 .5 2.27 3.22 3.22 0 0 1-.51 2.28zm-1.71-3.82c-.81 0-.91.66-.91 1.54s.1 1.55.91 1.55.91-.67.91-1.55-.1-1.54-.91-1.54zm6.12.32a.9.9 0 0 0-1.58.67v3.25H37v-5.4h1.31v.52a1.83 1.83 0 0 1 1.36-.58 1.63 1.63 0 0 1 1.27.51zm4.17 3.92v-.47a1.64 1.64 0 0 1-1.33.52 1.84 1.84 0 0 1-1.38-.48 1.73 1.73 0 0 1-.45-1.21c0-.86.59-1.56 1.84-1.56H44v-.27c0-.59-.29-.85-1-.85a1.16 1.16 0 0 0-1 .45l-.86-.84a2.27 2.27 0 0 1 1.95-.75c1.51 0 2.3.64 2.3 1.91v3.55zm0-2.28H43c-.49 0-.76.23-.76.61s.25.62.78.62a1.07 1.07 0 0 0 .85-.26.89.89 0 0 0 .2-.68zm5.55 2.28v-3.26a.9.9 0 1 0-1.79 0v3.26h-1.35v-5.4h1.32v.5a1.85 1.85 0 0 1 1.35-.56 1.75 1.75 0 0 1 1.27.48 2 2 0 0 1 .58 1.53v3.45zm5.52 0v-.5a1.62 1.62 0 0 1-1.34.57 1.91 1.91 0 0 1-1.33-.49 3.23 3.23 0 0 1-.55-2.28 3.2 3.2 0 0 1 .55-2.27 1.88 1.88 0 0 1 1.32-.49 1.62 1.62 0 0 1 1.32.54v-2.45h1.35v7.37zm-1-4.25c-.81 0-.91.66-.91 1.54s.1 1.55.91 1.55.92-.67.92-1.55-.06-1.53-.88-1.53zm9.32 3.65a2.24 2.24 0 0 1-1.68.66 2.21 2.21 0 0 1-1.67-.66 2.74 2.74 0 0 1-.61-2.1 2.73 2.73 0 0 1 .62-2.1 2.21 2.21 0 0 1 1.67-.66 2.24 2.24 0 0 1 1.68.66 2.73 2.73 0 0 1 .61 2.09 2.74 2.74 0 0 1-.62 2.11zm-1-3.41a.85.85 0 0 0-.63-.24.83.83 0 0 0-.62.24 1.83 1.83 0 0 0-.31 1.31 1.85 1.85 0 0 0 .31 1.32.83.83 0 0 0 .62.24.85.85 0 0 0 .63-.24 1.85 1.85 0 0 0 .31-1.32 1.82 1.82 0 0 0-.35-1.31zm4.12-.2v4.21h-1.35v-4.21h-.56v-1h.56v-.67a1.47 1.47 0 0 1 1.57-1.54h.77v1.14H67c-.32 0-.47.18-.47.49v.59h1v1zM14.56 39.47L9.51 23.61H6.09v15.86H0V.79h9.78c7.06 0 9.89 3.42 9.89 11.41 0 4.78-1 8.2-4.51 10.11l5.76 17.17zM9.83 6.27H6.09v11.85h3.74c3.26 0 3.75-2.72 3.75-5.92s-.49-5.93-3.75-5.93zm23.26 33.2V37a7.33 7.33 0 0 1-1.74 1.9 5.29 5.29 0 0 1-3.26 1 6.39 6.39 0 0 1-5.38-2.39C21.57 36.16 21 34 21 31.1a8.31 8.31 0 0 1 2.66-6.41c1.41-1.25 3.26-2 6.57-2h2.55v-4c0-2.12-1-3.31-2.77-3.31a2.4 2.4 0 0 0-1.9.82 3.66 3.66 0 0 0-.87 2.66h-5.78a8.34 8.34 0 0 1 2.44-6.19 8.89 8.89 0 0 1 6-2.34 8.26 8.26 0 0 1 6.1 2.19 9 9 0 0 1 2.5 6.74v20.21zm-.33-12.66h-1.9a3.94 3.94 0 0 0-3 .87 4.8 4.8 0 0 0-1.14 3.21c0 2.55 1 4 3 4 1.74 0 3-1.47 3-3.8zM51.88 16a4.61 4.61 0 0 0-4.78 4.94v18.53h-5.76V10.84h5.54v3a8.43 8.43 0 0 1 2.5-2.28 8.52 8.52 0 0 1 4.46-1.19V16zm3.81-12A3.18 3.18 0 0 1 58.87.84 3.18 3.18 0 0 1 62 4a3.18 3.18 0 0 1-3.13 3.2A3.18 3.18 0 0 1 55.69 4zM56 39.47V11.6h5.76v27.87zm13.87-1.74c-1.79-1.41-2.88-3.59-2.88-7V16h-3.7v-4.4H67V3.5h5.76v8.1h4V16h-4v14.45c0 2.66 1.36 3.86 4.07 3.86v5.16c-2.73 0-5.01-.22-6.96-1.74zm20.04 1.74V37a7.34 7.34 0 0 1-1.74 1.9 5.29 5.29 0 0 1-3.26 1 6.39 6.39 0 0 1-5.38-2.39C78.39 36.16 77.8 34 77.8 31.1a8.31 8.31 0 0 1 2.66-6.41c1.41-1.25 3.26-2 6.57-2h2.55v-4c0-2.12-1-3.31-2.77-3.31a2.4 2.4 0 0 0-1.9.82 3.66 3.66 0 0 0-.91 2.73h-5.71a8.34 8.34 0 0 1 2.44-6.19 8.89 8.89 0 0 1 6-2.34 8.26 8.26 0 0 1 6.08 2.12 9 9 0 0 1 2.5 6.74v20.21zm-.33-12.66h-1.9a3.94 3.94 0 0 0-3 .87 4.8 4.8 0 0 0-1.14 3.21c0 2.55 1 4 3 4 1.74 0 3-1.47 3-3.8zm20 12.66V18.88c0-2.23-1.25-3.31-2.83-3.31s-2.82 1.09-2.82 3.31v20.59h-5.76V10.84h5.54V13a6.64 6.64 0 0 1 1.9-1.79 5.7 5.7 0 0 1 2.88-.76 6.27 6.27 0 0 1 5.22 2.23c1.14 1.3 1.63 2.88 1.63 6.19v20.6zm10.86.19a3.15 3.15 0 1 1 3.15-3.15 3.15 3.15 0 0 1-3.15 3.15zm0-5.74a2.59 2.59 0 1 0 2.56 2.59 2.51 2.51 0 0 0-2.56-2.59zm.48 4.31l-.43-1.39h-.3v1.39h-.57V34.8h.91a.88.88 0 0 1 .64.21 1.11 1.11 0 0 1 .23.81 1 1 0 0 1-.22.77.61.61 0 0 1-.17.13l.49 1.51zm-.17-2.82a.29.29 0 0 0-.22-.09h-.34v1h.34a.3.3 0 0 0 .22-.09.58.58 0 0 0 .1-.41.64.64 0 0 0-.1-.41z" transform="translate(0 -.79)"/></svg>
```

**Comment by aldemira** [comment]
Ok, I'll have a look again.

**Comment by murrant** [comment]
Actually, this has too much stuff for a 32x32 icon.  Can you please copy this to logos/raritan.svg and crop out the registered and bottom bit?

**Comment by aldemira** [comment]
@murrant I couldn't edit the svg with inkspace or other online tools. This svg is a bit dodgy. So I found an jpg version, and I scaled and cropped it, is that OK?

**Comment by laf** [comment]
What about this one?

image

**Comment by aldemira** [comment]
@laf Apparently Legrant bought them and changed that logo to the one I've submitted, hence the ugly message and the trademarks on it :(
Would like to go with the old one?

**Comment by laf** [comment]
No we should use a newer one.

What about the square icon part of this logo:

image

**Comment by aldemira** [comment]
You mean the legrand logo's square? That wouldn't be accurate would it?

**Comment by laf** [comment]
We need something 32x32 that looks ok. nothing they have seems to :(

**Comment by salt-lick** [comment]
https://svgshare.com/s/6QM <-- Raritan logo
https://svgshare.com/s/6R1 <-- Legrand square thing
https://svgshare.com/s/6N3 <-- Legrand square thing + Raritan

32x32 SVGs

**Comment by murrant** [comment]
Doesn't need to be 32x32 @laf we scale all graphics.

**Comment by laf** [comment]
> Doesn't need to be 32x32 @laf we scale all graphics. But it helps for perspective on how it will display in LibreNMS.

But we scale them to 32x32 don't we, little point in having anything bigger then.

**Comment by aldemira** [comment]
Thanks @salt-lick but the page gives an error: over quota :(

**Comment by f0o** [comment]
> https://svgshare.com/s/6N3 <-- Legrand square thing + Raritan

This one looks decent. Just the square could be ambiguous (maybe?)

**Comment by aldemira** [comment]
This is how it looks, and I've update the pr with this. Thanks @salt-lick 

screen shot 2018-04-30 at 09 57 47

**Comment by murrant** [comment]
@aldemira almost there, probably would be appropriate to add the svg with "a brand of legrand" as the logo in addition to the icon svg you already have.

**Pull request merged**
