### PR TITLE
Unifi 5.60.1 sysObjectID changed

### PR DESCRIPTION
**Pull request by wolfraider**
Added new OID for Unifi detection

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Which devices is under this sysobject?

**Comment by wolfraider** [comment]
Ubiquiti UniFi access points like the UAP-nanoHD, U6-Lite, UAP-SHD running (roughly) beta firmware 5.53.1 or release candidate firmware 5.60.1 or later

**Comment by murrant** [comment]
You might need a more specific sysObjectID than this, edgeos uses .1.3.6.1.4.1.41112.1.5

**Comment by doktornotor** [comment]
> You might need a more specific sysObjectID than this, edgeos uses .1.3.6.1.4.1.41112.1.5

Well that'd need to be reported by the UniFi devices in the first place - it is not, They report the generic UBNT one instead. Does it still surprise anyone that Ubiquiti cannot implement SNMP properly?

**Review by murrant — APPROVED** [review]

**Comment by Jellyfrog** [comment]
@wolfraider @murrant this was reverted since it kidnaps airos devices, needs some tweaking

**Comment by wolfraider** [comment]
I'll see if I can dig up a unifi device for testing

**Pull request merged**
