### PR TITLE
Eaton UPS - Current Discovery

### PR DESCRIPTION
**Pull request by GeorgesDick**
I added this file in my local LibreNMS installation to get current values from my Eaton 5PX UPS. Another file is also needed :
librenms/includes/discovery/os/eatonups.inc.php

### CODE REVIEW

**Comment by laf** [comment]
Thanks. Can you sign the contributors agreement please as per: http://docs.librenms.org/General/Contributing/

**Comment by GeorgesDick** [comment]
Thank you @laf I added my name in AUTHORS.md, but can't find how to agree to the conditions of the Contributor Agreement in the commit log: where is the commit log and how to edit it? (Sorry, I'm used to Subversion, I'm only a beginner using Git)

**Comment by paulgear** [comment]
@GeorgesDick The commit log is the message you use in committing your change.  So in #3073, instead of saying "Update AUTHORS.md", you should include the text mentioned in the contributor agreement.

**Comment by GeorgesDick** [comment]
OK, done, hope I did it right.

**Pull request merged**
