### PR TITLE
Added comments to several MySQL tables

### PR DESCRIPTION
**Pull request by imcdona**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

I've added comments to several MySQL tables. There are additional tables that I wasn't able to determine their purpose so I left those alone. Please modify this commit with comments on any tables that aren't commented here.

For those not aware, comments are visible in the table properties and also come in handy when you enable the display of table comments in phpMyAdmin. At a glance you can easily determine what a tables purpose is.

### CODE REVIEW

**Comment by murrant** [comment]
We could also use comments in the new alert query builder...

**Comment by imcdona** [comment]
I forgot to add, I think it makes sense to apply all comments in a single schema update (241.sql). I don't mind holding off on this merge until I get a complete list. If you can add descriptions of each table to this push request I'll update the SQL schema and re-submit.

**Comment by imcdona** [comment]
@murrant "new alert query builder"??

**Comment by murrant** [comment]
My quick notes, please go through and make them look nice / make sense :)


Table|Description
--- | ---
access_points|Wifi Controller Access Points
alert_device_map|Alert rule to device map (added in #8293)
alert_group_map|Alert rule to device group map (added in #8293)
alert_log|Log of issued alerts
alert_map| (Removed in #8293)
alert_rules|Alert rules
alert_schedule|Alert maintenance windows
alert_schedule_items|Alert maintenance to device/group map
alert_template_map|Alert to template map
alert_templates|Alert templates
alerts|Log of alert changes
api_tokens|API tokens
application_metrics|Application metrics
applications|Applications
authlog|Log of authentication requests
bgpPeers|BGP Peers
bgpPeers_cbgp|BGP Peers extended data
bill_data|
bill_history|
bill_perms|Bill user permissions
bill_port_counters|
bill_ports|Bill to port map
bills|Bills
callback|Anonymous statistics id
cef_switching|CEF Switching
ciscoASA|Cisco ASA connections
component|Components attached to a device.
component_prefs|AV Pairs for each component
component_statuslog|log of status changes to a component.
config|Librenms configuration table
customers|Customer authentication information
dashboards|User dashboards
dbSchema|Database schema version
device_graphs|Enabled graphs by device_id
device_group_device|Device group to device map
device_groups|Device groups
device_mibs|Device to MIB mappings
device_oids|Per-device MIB data
device_perf|Device ICMP performance
device_relationships|Device dependency map
devices|Devices
devices_attribs|Device preferences
devices_perms|Device permissions
entPhysical|Entity physical inventory
entPhysical_state|Entity physical state
entityState|Entity states
eventlog|Log of events
graph_types|Graph descriptions
graph_types_dead| (This table needs to be removed)
hrDevice|Host Resources data
ipsec_tunnels|VPN tunnels
ipv4_addresses|IPv4 configured on ports
ipv4_mac|ARP tables
ipv4_networks|IPv4 networks
ipv6_addresses|IPv6 configured on ports
ipv6_networks|IPv6 networks
juniAtmVp|Juniper ATM Virtual Paths
links|Discovered device links
loadbalancer_rservers|Load balancer Rservers
loadbalancer_vservers|Load balancer Vservers
locations|Named locations to gps
mac_accounting|MAC accounting
mefinfo|Metro ethernet
mempools|Memory usage
mibdefs|MIB definitions
munin_plugins|Munin plugins
munin_plugins_ds|Munin graphing data
netscaler_vservers|NetScalar Vservers
notifications|Notifications
notifications_attribs|Notifications read/archived
ospf_areas|OSPF areas
ospf_instances|OSPF instances
ospf_nbrs|OSPF neighbors
ospf_ports|OSPF ports
packages|Installed software packages
pdb_ix|PeeringDB cache
pdb_ix_peers|PeeringDB peers
perf_times|Polling times log
plugins|Installed LibreNMS plugins
poller_groups|Distributed poller groups
pollers|Pollers
port_association_mode|List of port association modes (should be removed)
ports|Device ports
ports_adsl|ADSL ports
ports_fdb|Port bridging MAC tables
ports_perms|Port user permissions
ports_stack|Stacking ports
ports_statistics|Additional ports statistics
ports_stp|Port spanning tree info
ports_vlans|Port VLANs
processes|Process list
processors|Processors
proxmox|Proxmox
proxmox_ports|Proxmox ports
pseudowires|Pseudowires
route|Routes
sensors|Sensors
sensors_to_state_indexes|Sensor to state index map
services|Monitoring services
session|Logged in user sessions
slas|Cisco IP SLAs
state_indexes|State sensor types
state_translations|State sensors state translations
storage|Storage usage
stp|Spanning tree instances
syslog|Imported syslog data
tnmsneinfo|Coriant  TNMS NE info
toner|Printer toner status
ucd_diskio|UCD MIB disk IO graph list
users|User authentication information
users_prefs|User preferences
users_widgets|User widget preferences
vlans|VLAN information
vminfo|Virtual Machines
vrf_lite_cisco|Cisco VRF Lite
vrfs|VPN Routing and Forwarding
widgets|User widgets
wireless_sensors|Wireless sensors

**Comment by laf** [comment]
Updated some billing table information.

**Comment by imcdona** [comment]
Thanks for the info! Added additional comments and dropped graph_types_dead & port_association_mode

**Comment by murrant** [comment]
Don't drop port_association_mode, there are code changes needed.  Maybe not drop any in this PR 😀

**Comment by laf** [comment]
You'll also need to move this file to the latest schema version

**Comment by laf** [comment]
@imcdona Any update on this?

**Comment by laf** [comment]
Feel free to rebase this PR and we can re-open and merge.

**Pull request closed without merging**
