### PR TITLE
Use sysName for Application graph titles if not empty

### PR DESCRIPTION
**Pull request by aldemira**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Auto discovered devices with no reverse dns names are shown with IP addresses on graph titles. So I'm proposing to use sysName if not empty. That makes more sense IMHO.

### CODE REVIEW

**Comment by laf** [comment]
I'm not sure on this one personally, seems to be specific. Why the change?

**Comment by aldemira** [comment]
If a device with no reverse dns is auto discovered then the graph titles show IP addresses rather than a friendly name. I must admit I wasn't totally sure when sending this request :), but I am totally ok to delete this or to find another way.

**Comment by florianbeer** [comment]
I would welcome this as well. I often set up large(-ish) networks with a lot of network components that only have IPs and sysNames, there is neither time nor need to set up DNS, rDNS for these.

**Comment by laf** [comment]
Use this badly named function:

`ip_to_sysname($device, $hostname)`

Probably like this:

`shorthost(ip_to_sysname($device, $app_device['hostname']));`

You need to use the config option `$config['force_ip_to_sysname'] = true;` for this to work but basically anywhere an IP is shown for the hostname we switch out to sysName instead. It's not in place all over (just as you've seen here) but slowly it's being fixed.

**Pull request closed without merging**
