### PR TITLE
Arista VRF discovery support

### LINKED ISSUE #10179: Get Arista VRFs from an Arista extra MIB
Arista VRFs are not detected in the currently implemented way but there is a way to read the VRFs out with an Arista specific MIB. (http://www.circitor.fr/Mibs/Html/A/ARISTA-VRF-MIB.php)

One has to parse it out of the response of ARISTA-VRF-MIB::aristaVrfRoutingStatus, which is .1.3.6.1.4.1.30065.3.18.1.1.1.2.

Example:
snmpwalk -v2c -c xxxx 172.29.173.169  .1.3.6.1.4.1.30065.3.18.1.1.1.2
SNMPv2-SMI::enterprises.30065.3.18.1.1.1.2.3.109.103.116 = Hex-STRING: 00

It returns for example 3.18.1.1.1.2.3.109.103.116 where the first byte after the 2 is protocol identifier so 3 in dec is ipv4 and 9 in dec is ipv6 (I think). The rest are ascii codes in dec so in this case the vrf name would be ‘mgt’ (109 103 116).

After that getting the vrf specific route polling can be done with routing-instance@community string requests.

This should allow for BGP sessions within VRFs to be properly monitored.

See also: https://community.librenms.org/t/vrfs-are-not-added-discovered-for-arista-switches/8155/

**For help and support you can use our [Discord server](https://t.libren.ms/discord) or our [community site](https://community.librenms.org).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

(EDIT): 
[snmp.txt](https://github.com/librenms/librenms/files/3151358/snmp.txt)
[discovery.txt](https://github.com/librenms/librenms/files/3140914/discovery.txt)
[poller.txt](https://github.com/librenms/librenms/files/3140915/poller.txt)
(/EDIT)

### PR DESCRIPTION
**Pull request by PipoCanaja**
fixes #10179

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 11421 `
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/get-arista-vrfs-from-an-arista-extra-mib/11618/3

**Comment by PipoCanaja** [comment]
Hi @Senetus @Meh @oroomans @f0rkz 
Please have a look in this PR and let us know how it goes with your devices.
Thanx

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/arista-bgp-sessions-under-vrf/5717/9

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/vrfs-are-not-added-discovered-for-arista-switches/8155/10

**Comment by f0rkz** [comment]
@PipoCanaja thanks a ton for tackling this! I will be bringing up my lab tomorrow to work on this and see if this PR does the needful. Thanks again!

**Comment by oroomans** [comment]
Hello, 

thanks for this !

I just tried and it seems this is not working. 
In the routing tab, I only see the ospf from the default vrf and nothing about my bgp routing bound to vrf instance. 
I don't see any vrf tab neither. Don't know if this should appear as I only have vrfs on my arista devices. 

Tested models: 
DCS-7280SR2-48YC6
DCS-7050TX-72Q
DCS-7020TR-48
DCS-7050SX3-48YC12


EOS version 4.21.7.1M

Let me know if you need any logs

**Comment by PipoCanaja** [comment]
Hi
The goal is only to discover the VRFs (nothing with OSPF or BGP right now). I tested here with the data I have : 
```
HardwareDCS-7150S-24
Operating SystemArista EOS 4.20.12.1M
```

Capture d’écran 2020-04-15 à 09 28 16

Please provide me the data described in this FAQ and attach it here for a few of your devices so I can check.

**Comment by Senetus** [comment]
Works for me, excellent!

**Comment by oroomans** [comment]
Hello,

my bad it nows appears correctly in the interface.
I waited half an hour this morning before giving you feedback and
checked that polling was done, but seems it needed more time.

Thanks a lot for this !

Do you plan as well to integrate the routing tables from routing protocols
bounded to those vrfs ?

On my devices, the bgp peering is done insided a dedicated vrf, so that
would be super helpful to have it.

**Comment by PipoCanaja** [comment]
> Hello, my bad it nows appears correctly in the interface. I waited half an hour this morning before giving you feedback and checked that polling was done, but seems it needed more time. 

This is a discovery module, so you have to force a new discovery to get it. 

> Do you plan as well to integrate the routing tables from routing protocols bounded to those vrfs ? 
If this information is available, yes. But so far I haven't found it when doing a snmpwalk on my test data. If you can provide me some snmpwalk data, then I can check on yours if it is provided.

> On my devices, the bgp peering is done insided a dedicated vrf, so that would be super helpful to have it.

Same here If you give me your snmpwalk data, I can check what I can find.

**Comment by Senetus** [comment]
I think that to get the routing table from a specific vrf you can use the standard MIBs but you have to do community@vrfname for the snmp side of things. So you fetch all the VRF's and after that you have to loop through the routing table per vrf with additional calls.

**Comment by PipoCanaja** [comment]
It seems doable. Will have a look this week but I need your help guys, I don't own the devices : 
> Please provide me the data described in this FAQ(https://docs.librenms.org/Support/FAQ/#faq20) and attach it here for a few of your devices so I can check. Most importantly this one :
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME . | ./pbin.sh

**Comment by Senetus** [comment]
I’ll spin up a couple of virtual aristas and make some routing up, let me know anyhow you might need in addition :)

**Comment by Senetus** [comment]
I made up some configs fast and did snmpwalk on default, libre1 and testy2 vrf's, hereby the results.
[libre1.txt](https://github.com/librenms/librenms/files/4484237/libre1.txt)
[default.txt](https://github.com/librenms/librenms/files/4484238/default.txt)
[testy2.txt](https://github.com/librenms/librenms/files/4484239/testy2.txt)
So it looks like when doing the snmpwalk on a vrf you only get the useful stuff, seems good so far.

**Comment by Senetus** [comment]
Anything else you would need @PipoCanaja ?

**Comment by PipoCanaja** [comment]
@Senetus Only time to see how to implement this community trick in a clean enough way. It is not forgotten :)

**Comment by PipoCanaja** [comment]
@Senetus We'll get this 1st part merged. And I'll start another PR for Routes discovery. It's been a long time.

**Comment by Senetus** [comment]
Great, thanks for the info!

**Comment by murrant** [comment]
@PipoCanaja the VLAN (I think) code does the same thing.  Just set the $device['context'] on the device array before the queries and unset it after.  (We need a better solution than that at some point)

Actually, the collect-snmp-data.php script should collect context data too... hmm.

**Comment by PipoCanaja** [comment]
@murrant Sounds right. I remember that trick. I'll have to figure out how to do this with snmpsim cause I don't have any ARISTA device around me. 
But I'll do this in another PR. This one was for VRF only at first, let's keep it that way.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-65-release-changelog-june-2020/12687/1

**Comment by MennoCB** [comment]
Really appreciate the addition of VRF support, I have a pair of 7280SR2A-48YC6 with BGP inside the VRFs and if anyone wants to try adding support for that (BGP) then I am happy to provide remote access.

**Pull request merged**
