### PR TITLE
Support for SSL/TLS protected connections to MySQL databases

### PR DESCRIPTION
**Pull request by gs-kamnas**
This changeset enables the use of SSL/TLS protected connections to MySQL databases in both the UI/poller as well as the dispatcher service.

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [NA] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [NA] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by murrant — DISMISSED** [review]
LGTM, thanks for following the Laravel ENV variables.
I have not tested.

**Comment by murrant** [comment]
$ ./poller-wrapper.py 10
2022-07-27 10:37:16,335 :: CRITICAL :: ERROR: Could not connect to MySQL database! 'DBConfig' object has no attribute 'db_sslmode'
Traceback (most recent call last):
  File "/home/murrant/projects/librenms/./poller-wrapper.py", line 57, in <module>
    wrapper.wrapper(
  File "/home/murrant/projects/librenms/LibreNMS/wrapper.py", line 463, in wrapper
    db_connection = LibreNMS.DB(sconfig)
  File "/home/murrant/projects/librenms/LibreNMS/__init__.py", line 220, in __init__
    self.connect()
  File "/home/murrant/projects/librenms/LibreNMS/__init__.py", line 251, in connect
    sslmode = self.config.db_sslmode.lower()
AttributeError: 'DBConfig' object has no attribute 'db_sslmode'

**Comment by gs-kamnas** [comment]
@murrant Apologies, this was broken when the poller-wrapper as opposed to the dispatcher service was used as the poller entrypoint.

I _believe_, this is now fixed but need to retest fully (as in with both entrypoints).

**Comment by gs-kamnas** [comment]
Both entrypoints appear to work properly now, would appreciate another review when convenient:

```
librenms@librenms:~$ ./poller-wrapper.py 1
2022-07-27 20:09:10,131 :: INFO :: starting the poller check at 2022-07-27 20:09:10 with 1 threads for 1 devices
2022-07-27 20:09:11,745 :: INFO :: worker Thread-2 finished device 1 in 1 seconds
2022-07-27 20:09:11,745 :: INFO :: poller-wrapper checked 1 devices in 1 seconds with 1 workers with 0 errors
librenms@librenms:~$ ./discovery-wrapper.py 1
2022-07-27 20:09:16,496 :: INFO :: starting the discovery check at 2022-07-27 20:09:16 with 1 threads for 1 devices
2022-07-27 20:09:20,104 :: INFO :: worker Thread-2 finished device 1 in 3 seconds
2022-07-27 20:09:20,105 :: INFO :: discovery-wrapper checked 1 devices in 3 seconds with 1 workers with 0 errors
librenms@librenms:~$ ./librenms-service.py
librenms(INFO):Watchdog is disabled.
librenms(INFO):Entering main LibreNMS service loop on 5165/librenms...
librenms(INFO):LibreNMS Service: librenms-02da6614-0de8-11ed-87bc-3b5092677e04 started!
librenms(INFO):Poller group 0 (default). Using Python 3.8.10 and internal locks and queues
librenms(INFO):Queue Workers: Discovery=16 Poller=4 Services=8 Alerting=enabled Billing=enabled Ping=disabled
librenms(INFO):Maintenance tasks will be run every 1 day, 0:00:00
librenms(INFO):librenms is now the master dispatcher
librenms(INFO):Received signal on thread librenms, handling
librenms(INFO):Dispatch loop terminated
librenms(INFO):Shutting down, waiting for running jobs to complete...
librenms(INFO):Shutdown of 5165/librenms complete
```

**Review by murrant — APPROVED** [review]
Much better, not breaking polling is a good thing :D

**Comment by gs-kamnas** [comment]
Indeed. Apologies again for the near-miss.

**Comment by murrant** [comment]
@gs-kamnas no worries, we should have a test for that.

**Pull request merged**
