### PR TITLE
fix: Changed sql query for state sensors on device overview page to ignore null sensor_id

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Fixes: #5168

### CODE REVIEW

**Comment by murrant** [comment]
I couldn't reproduce the issue, but the change looks good.

**Comment by E-t-z** [comment]
Tested, works.

**Comment by laf** [comment]
The bug is from devices which had existing state sensors before the refactor from rosiak. They don't register the state translations so when the query runs with the left join we end up with two sensor_id values, first is legit, second is NULL because it's from the translation table.

Yes this is a work around

**Comment by Rosiak** [comment]
Hrm, this broke something.
Will try to have a look when I'm back home.
screen shot 2016-12-18 at 13 55 04

**Comment by laf** [comment]
Try #5191

**Pull request merged**
