### PR TITLE
Documentation updates for DMI support and making two links in the FAQ work

### PR DESCRIPTION
**Pull request by trs80**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
I feel like those line should be commented out by default.

Also, you can remove the numeric oids from the extends...

**Comment by laf** [comment]
> I feel like those line should be commented out by default.
Definitely. They don't all work by default but the error will be returned and used then show in the webui.

**Comment by laf** [comment]
@trs80 Any response to the previous comments?

**Comment by murrant** [comment]
@trs80 looks like you need to sign/resign the CLA.  Thanks.

**Pull request merged**
