### PR TITLE
Added Routeros vlans discovery

### PR DESCRIPTION
**Pull request by Npeca75**
It is my attempt to add ability for discovery of Mikrotik Vlans

there is two part needed for this to work
1. this PR (include/discovery/vlans/routeros.inc.php)
2. Script for Mikrotik (librenms-agent/snmp/Routeros/LNMS_vlans.scr)

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@Npeca75 please check the  failing tests below

**Comment by Npeca75** [comment]
> @Npeca75 please check the failing tests below

hi @Jellyfrog 
dbfetch, dbfetchrow is widely used in LNMS core code
i tried to find something similar, but no
so i have no idea what else i could write instead of dbfetch ?

it is valid, and it is working

**Comment by Jellyfrog** [comment]
Hi,
Yes those are deprecated no longer allowed to be used for new code,
 as the error says use Eloquent instead; https://laravel.com/docs/8.x/eloquent 

For example this
` dbFetchRow('select * FROM vlans where `device_id` = ? AND `vlan_vlan` = ?....`

Should be written as 
`Vlan::where('device_id', $device['device_id'])->where('vlan_vlan', $vId)->get()`

**Comment by Npeca75** [comment]
> Vlan::where('device_id', $device['device_id'])->where('vlan_vlan', $vId)->get()

@Jellyfrog 
hi ... well, it is unfair
LNMS have almost no documentatio about core stuff
in past i added vlans for jetstream, and needed to loop trough existing code to learn how to do things
and now, somebody idea is to use new semantic, starting to learn again from beginning
maybe someone from devs could FIRST rewrite old, core code, and after that requesting from volonteurs / hobby users to learn high school php.

**Pull request closed without merging**
