### PR TITLE
Added WUT Humidity and Temperature Sensors

### PR DESCRIPTION
**Pull request by mpikzink**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hello @mpikzink
 
Thanx for your PR ! It seems that you did a little bit too much work here. Only one YAML pair was necessary, the sensors of the 3 models you suggest are the same. 
Could you please :
- Rename the mib file with its official name : "WebGraph-Thermo-Hygro-Barometer-MIB"
- Move it to a directory in the mibs folder, like mibs/wut
- Keep only one YAML file for definitions and discovery, named "wut.yaml"
- Adapt the OID matching for the definition yaml file
- The discovery YAML can be re-generated without specifying the index, so it can discover "any" device
- Re-Generate the test data

I would suggest that you start with the 4 first steps and we can then see how it goes. 

Thanx

**Comment by PipoCanaja** [comment]
MIB files seems very similar. Could you check them, and probably keep only the bigger of them ? IF it includes all the OIDs you need, then you don't even have to load the others. 
I did some cleaning/renaming in the files, to only keep the needed YAML, snmprec etc.

**Comment by PipoCanaja** [comment]
Please extract the textual OIDs and the numerical OIDs of Pressure and Humidity and post them here. With the MIB in which you got them.

**Comment by mpikzink** [comment]
I think this includes the information:

### HOST1 ###
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.5040.1.2.16
snmpwalk -c public -v1 HOST1 -m /opt/librenms/mibs/wut/WebGraph-Thermo-Hygro-Barometer-MIB -On wtWebGraphThermoBaroBinaryTempValue
.1.3.6.1.4.1.5040.1.2.16.1.4.1.1.1 = INTEGER: 221
.1.3.6.1.4.1.5040.1.2.16.1.4.1.1.2 = INTEGER: 256
.1.3.6.1.4.1.5040.1.2.16.1.4.1.1.3 = INTEGER: 9904

### HOST2 ###
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.5040.1.2.9
snmpwalk -c public -v1 HOST2 -m /opt/librenms/mibs/wut/WebGraph-Thermo-Hygrometer-MIB -On wtWebGraphThermHygroBinaryTempValue
.1.3.6.1.4.1.5040.1.2.9.1.4.1.1.1 = INTEGER: 216
.1.3.6.1.4.1.5040.1.2.9.1.4.1.1.2 = INTEGER: 371

### HOST3 ###
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.5040.1.2.42
Actually not in my test Setup

**Comment by PipoCanaja** [comment]
So the 1st OID seems to be a temp sensor in both, and the 2nd the humidity sensor. It there an OID that could help us dynamically find which sensor is where ?

**Comment by PipoCanaja** [comment]
Hi @mpikzink 
Looks much better now. Do you get the expected result ? 
If yes, could you run ./scripts/save-test-data.php for each of those 3 variants to make the JSON files and add them to the PR?

**Comment by mpikzink** [comment]
Now it works fine in my environment. I don't unterstand how to create the JSON files with ./scripts/save-test-data.php

**Comment by Jellyfrog** [comment]
> Now it works fine in my environment. I don't unterstand how to create the JSON files with ./scripts/save-test-data.php

`./scripts/save-test-data.php --os wut`

**Comment by mpikzink** [comment]
> > Now it works fine in my environment. I don't unterstand how to create the JSON files with ./scripts/save-test-data.php
> 
> `./scripts/save-test-data.php --os wut`

Yes, I did, but it doesn't finish. And I don't know what to do ?!

```
./scripts/save-test-data.php --os wut

...
  --- Transport configuration
  Listening at UDP/IPv4 endpoint 127.1.6.1:1161, transport ID 1.3.6.1.6.1.1.0
```

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
