### PR TITLE
Update queuemanager.py: Single element args tuple breaks alerts.php running

### PR DESCRIPTION
**Pull request by r-duran**
Single element args tuple breaks alerts.php

I have disabled all cron jobs and using dispatcher service. On my installation "./alerts.php" does not run without "-f" parameter:

`librenms@nms:~$ ./alerts.php -d
DEBUG!
Alerts are not enabled for cron scheduling.  Add the -f command argument if you want to force this command to run.`

In "queuemanager.py" file, "alerts.php" arguments needs to be in tuple format but according to pyhton docs, you need to add traling comma if you need to define single element tuple: https://www.w3schools.com/python/gloss_python_tuple_one_item.asp#:~:text=To%20create%20a%20tuple%20with,the%20variable%20as%20a%20tuple.

So email alert transports does not work with dispacther service. This patch requests fixes this,

`librenms@nms:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.11.0-98-g446e05c97 (2024-12-12T02:38:58+03:00)
DB Schema | 2024_10_20_154356_create_qos_table (310)
PHP       | 8.2.26
Python    | 3.11.2
Database  | MariaDB 10.11.6-MariaDB-0+deb12u1
RRDTool   | 1.7.2
SNMP      | 5.9.3
===========================================

[OK]    Composer Version: 2.8.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
[WARN]  Your local git contains modified files, this could prevent automatic updates.
        [FIX]:
        You can fix this with ./scripts/github-remove
        Modified Files:
         LibreNMS/queuemanager.py`

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the submission. Can you please sign the CLA.

I'm intrigued by your setup though as I run the dispatcher service with alerts and it works fine out of the box.

**Comment by ottorei** [comment]
Im also using the dispatcher (running a few months old release) and the alerts do work. However, the alerting module is enabled on only one server because only that server can actually send emails using smtp on my environment. Other servers are just pollers. The same goes for other transports too - only the "master" server can make connections to external systems.

**Comment by r-duran** [comment]
> Thanks for the submission. Can you please sign the CLA.
> 
> I'm intrigued by your setup though as I run the dispatcher service with alerts and it works fine out of the box.

You are welcome. If your setup can run ./alerts.php  without -f parameter then it seems you are not affected. I am happy to test why my alerts.php does not run without -f parameter, if you can suggest where to look, what to test.

This is a 2-3 years old setup, single server, installed on debian 11, upgraded to debian 12. Until last 2 months it was using cron jobs. The i disabled them and start to use dispatcher service as validate.php suggested.

**Comment by r-duran** [comment]
> Im also using the dispatcher (running a few months old release) and the alerts do work. However, the alerting module is enabled on only one server because only that server can actually send emails using smtp on my environment. Other servers are just pollers. The same goes for other transports too - only the "master" server can make connections to external systems.

Mine is a songle server setup without distibuted poller.

**Comment by SuPeRMiNoR2** [comment]
This same issue is happening to me. I tested the fix in this PR by manually applying it, and it fixed the issue for me.

**Review by murrant — APPROVED** [review]

**Comment by laf** [comment]
@r-duran or @SuPeRMiNoR2 Out of interest, what did you have schedule_type.alerting set to? `lnms config:get schedule_type.alerting`

**Comment by SuPeRMiNoR2** [comment]
> @r-duran or @SuPeRMiNoR2 Out of interest, what did you have schedule_type.alerting set to? `lnms config:get schedule_type.alerting`

dispatcher

**Comment by laf** [comment]
> > @r-duran or @SuPeRMiNoR2 Out of interest, what did you have schedule_type.alerting set to? `lnms config:get schedule_type.alerting`
> 
> dispatcher

Ace. Thanks.

**Pull request merged**
