### PR TITLE
Improvements to distro script: Arch Linux support, only use lsb-release as a fallback

### PR DESCRIPTION
**Pull request by n-st**

### CODE REVIEW

**Comment by laf** [comment]
@f0o you may be better at checking this as I don't really poll servers. Looks ok from my perspective.

**Comment by paulgear** [comment]
Not sure why we would want to remove the LSB stuff...

**Comment by n-st** [comment]
@paulgear We're not removing anything, just preferring the distribution-specific version detection code over the generic one.
Right now, the script detects and parses files like `/etc/debian_version`, but discards those results if `/etc/lsb_release` exists.
I really can't think of a reason why we would want to do that. In fact, this looks suspiciously like an oversight (accidental `if` instead of `elif`) to me...

**Comment by paulgear** [comment]
@n-st OK - I'll look more closely at the full script when I get a sec.  From the diff it looked like it was discarding the LSB stuff needlessly.

**Comment by f0o** [comment]
:+1:

**Pull request merged**
