### PR TITLE
Added basic Ubiquoss PON support

### LINKED ISSUE #10601: Adtran/Ubiquoss/Commscope C9500 OLT New Device Support
[NEW-OS-SUPPORT-COMMANDS.txt](https://github.com/librenms/librenms/files/3606498/NEW-OS-SUPPORT-COMMANDS.txt)
Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [X] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [X] Please provide as much detail as possible.
- [X] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Attached is the output of the following commands -

./discovery.php -h HOSTNAME -d | ./pbin.sh
./poller.php -h HOSTNAME -r -f -d | ./pbin.sh
snmpbulkwalk -OUneb -v2c -c COMMUNITY HOSTNAME .  | ./pbin.sh

Also attached is the 2 different sets of MIBs from Ubiquoss and also the Ubiquoss Logo

Detail -
Adtran has the North American Distribution Rights to Ubiquoss.  Adtran acquired Commscope, which Commscope is the North American branding/version of Ubiquoss.

OS Name is Ubiquoss

C9500 OLT is EPON

Hopefully, a new OS template can be created.

If possible, please try to get the following -

Tpon Interface Optical Light Readings

PON ONU bridging-entries -

 1/4-1.2     0024.4508.3bf9
 1/4-1.3     0003.e637.4006
 1/4-1.4     0024.4508.3bf8

PON ONU Light Readings -

  PON NETWORK ONU DDM FOR 10G-OLT(1/4) INFORMATION
================================================================================
 INDEX       RX POWER   TX POWER        VCC       BIAS   TEMPERATURE
--------------------------------------------------------------------------------
 1/4-1           0.17       1.83       3.26       9.75      31.89
================================================================================

  -- ONU 1/4-1 DDM Information --
 RX Laser Power                 :                  0.15 dBm

 TX Laser Power                 :                  1.88 dBm
 Laser VCC                      :                 3.260 volt
 Laser Bias                     :                 9.950 mAmp
 Laser temperature              :                32.562 Celsius

ubiquoss
[Ubiquoss-mibs.zip](https://github.com/librenms/librenms/files/3606421/Ubiquoss-mibs.zip)
[9500_mib_r320c.zip](https://github.com/librenms/librenms/files/3606423/9500_mib_r320c.zip)

### PR DESCRIPTION
**Pull request by PipoCanaja**
fixes #10601 

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
ready for review

**Comment by jerrydao** [comment]
how about the ubiquoss yaml file inside definition/discovery?

**Comment by PipoCanaja** [comment]
Hi @jerrydao 
This PR is only adding basic support for the moment. I don't own a device and don't know which metrics are interesting or not on them.
But you can add the definition/discovery/ yaml file of course, and submit it as a PR when done. 
Bye

**Comment by jerrydao** [comment]
Thank you for your reply, but I still don't get your points. I added all ur files to Librenms and it showed no different.

**Comment by PipoCanaja** [comment]
> Thank you for your reply, but I still don't get your points. I added all ur files to Librenms and it showed no different.

You can apply this patch with ```./scripts/github-apply 10828 ``` and ``` rm cache/os_defs.cache ```. That will add the basic discovery : serial number, logo, etc etc. 

++ Philippe

**Comment by jerrydao** [comment]
Thanks, I had done it. My point is I don't see any much difference.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
