### PR TITLE
refactor: Switch to using discovery-wrapper.py by default

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Seems sensible to run like this now. Won't effect new installs.

### CODE REVIEW

**Comment by murrant** [comment]
Great, but I think the default thread count should be 2 or 4 instead of 1.

**Comment by laf** [comment]
1 means it’s a direct replacement for the php version and should guarantee that we don’t overload installs, changing it to another value won’t guarantee that :(

**Comment by Zmegolaz** [comment]
I've been running this with 4 threads for a day now and tried adding/removing devices, seems to work.

But this will _only_ affect new installs, won't it? In that case nothing will break for existing users if it's set to more threads.

**Comment by laf** [comment]
> But this will only affect new installs, won't it? In that case nothing will break for existing users if it's set to more threads.

Correct but we've had no feedback so imho, I'd prefer to start out with how it is now and as people start reporting positive changes then we start increasing the limit.

I actually plan to remove the thread argument and allow people to just set in config.

**Pull request merged**
