### PR TITLE
Update zynos to support XGS device detection

### PR DESCRIPTION
**Pull request by MrMaus13**
Update to support XGS device detection. (10Gig variant of GS type).

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
You'll need to add new test data for this.  Thanks.

**Comment by laf** [comment]
@MrMaus13 Any response to the last comment?

**Comment by MrMaus13** [comment]
I will add testdata, overlooked the reply, apologies

Verstuurd vanaf mijn iPhone

Op 21 apr. 2018 om 12:59 heeft Neil Lathwood <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@MrMaus13<https://github.com/MrMaus13> Any response to the last comment?

**Comment by laf** [comment]
@MrMaus13 Let us know when you've got the test data together and we can re-open.

**Pull request closed without merging**
