### PR TITLE
Hide link to syslog for device if syslog is not enabled.

### PR DESCRIPTION
**Pull request by SaaldjorMike**

### CODE REVIEW

**Comment by paulgear** [comment]
I don't think we want to redirect to / in the case of html/pages/device/logs/syslog.inc.php - that would redirect someone to the overview page for just clicking on the wrong tab in the device menu.

**Comment by SaaldjorMike** [comment]
@paulgear: Not sure I'm getting what you're saying. The link for syslog for a given device will not be shown since the changes to html/pages/device/logs.inc.php will remove the link shown for syslog, thus making it impossible for some user to press the link.

The menu for /device/device=ID/tab=logs/ with enable_syslog=0:
Before: https://i.imgur.com/rmL1VLH.png
After: https://i.imgur.com/eqGaPSA.png

With enable_syslog=1, it will appear exactly like the 'after' screendump from above.

**Comment by Rosiak** [comment]
Seems like a great idea.

**Comment by paulgear** [comment]
@SaaldjorMike True, the link won't be there, but any bookmarks would break and be redirected to somewhere surprising.  Not a big deal either way, though...

**Comment by SaaldjorMike** [comment]
@paulgear: True, but since syslog is not really enabled I just assumed that one should not be able to go to the pages. Let me know if you want me to change anything.

**Comment by laf** [comment]
Can see why the redirects are in place but personally I'd remove them as you can actually run syslog without it being enabled in the menu system. So hide the link but don't redirect the user. You might also have had syslog running but now it's disabled yet you still want to see legacy data.

**Comment by SaaldjorMike** [comment]
@paulgear @laf: I've now only included the commit that hides the link in the branch.

**Pull request merged**
