### PR TITLE
Added HTTPS config instructions

### PR DESCRIPTION
**Pull request by tslytsly**
Added new section explaining how to enable SSL on Ubuntu and Nginx using a LetsEncrypt SSL cert.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I think these belong somewhere else. I'll have a think.

**Comment by tslytsly** [comment]
Yea, I wasn't sure either.
I thought about as a sub-heading of http://docs.librenms.org/Installation/Installation-Ubuntu-1604-Nginx/#web-server, but then I thought that SSL is not an install requirement. (Even if it is a good idea)

**Comment by murrant** [comment]
I think I would prefer to have the certbot renew cron in it's own file.  This way if someone copies the standard cron from our repo over the one they have they don't delete it.
Also, any reason you run certbot as librenms, but then have it sudo?

**Comment by tslytsly** [comment]
> I think I would prefer to have the certbot renew cron in it's own file. This way if someone copies the standard cron from our repo over the one they have they don't delete it.

Yea, good point. I can change and test that on my system.

> Also, any reason you run certbot as librenms, but then have it sudo?

I originally ran it as root without sudo, but then I was getting ownership warnings for my Nginx access and error logs when I ran validate.php.
So I switched it to run as librenms with sudo and, so far, I've not got the same error.

**Comment by laf** [comment]
I think the best place for this is under Support -> SSL Configuration

This requires creating a new page which is more than just a new file so please ensure you read: http://docs.librenms.org/Developing/Creating-Documentation/

As for the permissions on the logs, this is fixed in validate.php now so you can just drop the sudo from librenms in cron and split that cron entry out into it's own.

**Pull request closed without merging**
