### PR TITLE
changed default param max_rows to increase widget count on dashboard

### PR DESCRIPTION
**Pull request by alakiza**
In a large network, there is a need to create large dashboards, so the limit of 15 lines is not enough.

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Can't you set max_rows where we use it instead?

**Comment by murrant** [comment]
Yes, very welcome change, but can we do it without modifying the source?  Someone might upgrade it and overwrite your change.

**Comment by alakiza** [comment]
Reasonable. I will try to make it possible to edit this parameter via config.php

**Comment by murrant** [comment]
It doesn't need to be a config.php setting.  Just set `max_rows` here:
https://github.com/librenms/librenms/blob/6d2a8867dc7a2efe92fdf8773b320308e12bf3e9/resources/views/overview/default.blade.php#L183

**Review by murrant — APPROVED** [review]
;)

**Pull request merged**
