### PR TITLE
make login form more mobile-friendly

### PR DESCRIPTION
**Pull request by peelman**
Disable autocomplete, autocorrect, autocapitalize, and spellcheck on username and password input forms.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
What's wrong with autocomplete on the username field?

Also, does this stop browser saved logins working at all?

**Comment by peelman** [comment]
In my case, on iOS, the input field defaults to capitalizing the first character.  So you end up with `Npeelman` instead of `npeelman`.  If you have a username that is spelled like a common word, it may autocorrect it every time (which mine will do occasionally on systems where my username is just 'peelman').

AFAIK, it doesn't affect saved browser logins.  It only affects how browsers treat the keyboard entry on those inputs.

**Comment by laf** [comment]
I'm fine with all the others (like auto capital, etc), just wondering if the actual auto-complete should be left on for usernames?

**Comment by murrant** [comment]
Also, I don't think those attributes are needed when `type="password"` so you can remove them all there.

**Comment by laf** [comment]
murrant summed up what I was trying to say :)

**Comment by murrant** [comment]
Thanks!

**Pull request merged**
