### PR TITLE
Add Dlink DCS model identification

### PR DESCRIPTION
**Pull request by pblasquez**
Also consolidated to a single preg_match statement for DCS-, DES-, DGS- models

### CODE REVIEW

**Comment by murrant** [comment]
The only problem I have with this is all the others are switches, DCS- are cameras.  But I'm not sure if it should be handled any differently.

**Comment by laf** [comment]
I added Hikvision support a while ago which was labelled as network at the time.

Should we switch them out to be camera?

**Comment by murrant** [comment]
Yeah, it would make sense.

**Comment by laf** [comment]
@pblasquez any comments?

**Comment by murrant** [comment]
Yep, I'd like this separated from the networking devices.  With a device type of Camera, which might require a separate os...

**Comment by laf** [comment]
@pblasquez Feel free to re-open or comment to discuss further.

**Pull request closed without merging**
