### PR TITLE
Added 'Video' device group and moved Axis cameras to this group'

### PR DESCRIPTION
**Pull request by EnzoZafra**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/) - please do NOT submit a pull request unless you have (signing the agreement in the same pull request is fine). Your commit message for signing the agreement must appear as per the docs.
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by laf** [comment]
I'm not a fan of video, from the sysDescr this could be a variety of things so appliance may be a better fit but overall I'm not sure we should change it.

**Comment by EnzoZafra** [comment]
@laf Is it possible to at least move the network cameras to a separate group? Something like 'Surveillance' or 'Cameras'? The video encoders and video servers could stay in the 'Network' group.

**Comment by laf** [comment]
That would mean splitting out this OS discovery into 3 separate OS'.

You are more than welcome to submit a pull request to do this but my opinion (not the projects) is that this should be kept simple - basically as it is with the appropriate type, appliance potentially fits better here.

**Comment by EnzoZafra** [comment]
Okay, that makes sense. The important part for us is to separate the Axis cameras from the network group as we have hundreds of cameras and the switches are getting pushed back to the last few pages - so this will solve our problem

**Comment by laf** [comment]
Needs a rebase and also a notification adding:

https://github.com/librenms/librenms.github.io/blob/master/notifications.rss

Use 'Change to Cisco UCM type from tele to collaboration' as an example, needs to give around 4 days notice.

**Comment by laf** [comment]
I've merged the notification.

This should be merged on the 17th.

**Pull request merged**
