### PR TITLE
Poller service

### PR DESCRIPTION
**Pull request by clinta**
This replaces PR #1405 which was broken by the Github takedown and restore.

### CODE REVIEW

**Comment by spinza** [comment]
Great thanks! I had not realised that my problem was a general one!

**Comment by laf** [comment]
:bump:

I'd like us to look at moving this forward for merging. It can be done so it's a secondary choice on how to run poller until we get more live feedback or it's perfect time for us to look at a dev branch.

@paulgear / @f0o

**Comment by f0o** [comment]
I'm pro Dev/Master branches eventhough this contradicts the rolling-release @paulgear seems to prefer.

The poller-service has my :+1: - Against all odds we should mention in the docs that people running MultiMaster MySQL setups are going to revert this commit on thier own setup due to the lock-usage in discovery.php and poller.php. I'm not aware of anybody but me doing this but silence doesnt mean that nobody does it :)

**Comment by clinta** [comment]
I can add some documentation about considerations for multi-master MySQL.

**Comment by f0o** [comment]
That'd be awesome @clinta :)

**Comment by paulgear** [comment]
With a PR as long-running as this, I'd really prefer to see it fully rebased to get rid of those merge commits.

**Comment by clinta** [comment]
Rebased in #1584

**Comment by clinta** [comment]
Apparently a new PR was unnecessary, I read that rebasing an open PR wouldn't update the PR in github, but it looks like that is not correct.

**Pull request closed without merging**
