### PR TITLE
Remove agent scripts

### PR DESCRIPTION
**Pull request by murrant**
Leave a note that they have been moved to https://github.com/librenms/librenms-agent
The goal is to prevent divergence.

### CODE REVIEW

**Comment by f0o** [comment]
We should use submodules like we planned to a long time ago haha

**Comment by f0o** [comment]
(same applies for mibs)

**Comment by laf** [comment]
Doesn't this need additional commands to be run after to get the files?

Checking this branch out results in no files in scripts/agent.

My opinion, especially for this is we should just have the README pointing people to the agent repo. Most of the time these scripts aren't going to be used on the LibreNMS box direct.

**Comment by murrant** [comment]
The scripts are in daily.sh already.
But that seems valid to me and simpler.  I can revert the last commit.

**Comment by laf** [comment]
I'd be interested in what the rest of @librenms/reviewers think.

Keep in mind that the scripts directory will then only get populated the day after an initial install unless we also update install docs to get people to run daily.sh manually on install time.

**Comment by laf** [comment]
@librenms/reviewers bump otherwise merging in 48 hours.

**Pull request merged**
