### PR TITLE
Change ups-nut sensors

### PR DESCRIPTION
**Pull request by mpikzink**
I had to adjust the dd-wrt files, otherwise there were problems with the pre commit script.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @mpikzink 
You probably have a mib issue here, for the dd-wrt part. Are you sure of your test environnement ? I am also not really getting why you change the ups-nut thing alltogether. Could you let us know your initial issue ?

**Comment by mpikzink** [comment]
OK, sorry for the trubble and thank you for help.
This is my error with an old baseline.
`
# ./scripts/pre-commit.php 
Only checking os: linux
Running unit tests... 
PHPUnit 7.5.17 by Sebastian Bergmann and contributors.

Unknown object identifier: NET-SNMP-EXTEND-MIB::nsExtendOutput1Line.distro
ESS.....

Time: 5.83 seconds, Memory: 46.00 MB

There was 1 error:

1) LibreNMS\Tests\OSDiscoveryTest::testOS with data set "linux" ('linux')
Exception: Could not translate oid: NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."distro"
Tried: snmptranslate -IR -On NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."distro" -M /opt/librenms/mibs

/opt/librenms/tests/mocks/mock.snmp.inc.php:150
/opt/librenms/tests/mocks/mock.snmp.inc.php:209
/opt/librenms/includes/functions.php:256
/opt/librenms/includes/functions.php:182
/opt/librenms/tests/OSDiscoveryTest.php:107
/opt/librenms/tests/OSDiscoveryTest.php:75
`

Today I updated it to the new baseline and get a different error:

`
There was 1 error:

1) LibreNMS\Tests\Unit\PermissionsTest::testUserCanAccessDevice
Illuminate\Database\QueryException: SQLSTATE[HY000] [1049] Unknown database 'librenms_phpunit_78hunjuybybh' (SQL: select distinct `os` from `devices`)

/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2130
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2118
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2604
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2119
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:521
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:505
/opt/librenms/app/Models/Device.php:250
/opt/librenms/app/Models/Device.php:38
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:186
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:165
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:292
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php:122
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:300
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:219
/opt/librenms/tests/Unit/PermissionsTest.php:67

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1049] Unknown database 'librenms_phpunit_78hunjuybybh'

/opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:46
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:182
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:919
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:944
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:399
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:325
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2130
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2118
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2604
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2119
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:521
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:505
/opt/librenms/app/Models/Device.php:250
/opt/librenms/app/Models/Device.php:38
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:186
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:165
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:292
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php:122
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:300
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:219
/opt/librenms/tests/Unit/PermissionsTest.php:67

Caused by
PDOException: SQLSTATE[HY000] [1049] Unknown database 'librenms_phpunit_78hunjuybybh'

/opt/librenms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:67
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:46
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:182
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:919
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:944
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:399
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:325
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2130
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2118
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2604
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2119
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:521
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:505
/opt/librenms/app/Models/Device.php:250
/opt/librenms/app/Models/Device.php:38
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:186
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:165
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:292
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php:122
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:300
/opt/librenms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:219
/opt/librenms/tests/Unit/PermissionsTest.php:67

ERRORS!
Tests: 1697, Assertions: 3031, Errors: 1, Skipped: 130.
`

**Comment by PipoCanaja** [comment]
The error is in the pre-commit script itself, that does not have access to the test database. But the device model does work OK (or should at least). 

So, I would suggest to start over now. 
Let us know what's wrong with ups-nut, and then only correct what you feel is wrong there. And we'll help you if needed.

**Comment by mpikzink** [comment]
OK, the senors of ups-nut are seperatet from the others and it's not possible to access it via the menue. In my opinion, the several sensors are already defindes so it's not nessesary to have this seperate ups-nut sensor.
Screenshot_20200207_090259

**Comment by PipoCanaja** [comment]
Ah clear! That is clearly a bug here ... 👍

**Comment by PipoCanaja** [comment]
Should be ready to merge after #11116 is merged to fix travis.

**Comment by PipoCanaja** [comment]
Hi @mpikzink 
You need to rebase your PR to master to get it ready for merge. I cannot edit it.

**Comment by mpikzink** [comment]
I deleted my fork by tests and I am not able to rebase my PR. The main problem is because I am new with git and PRs. I am testing arround  :-(

**Comment by PipoCanaja** [comment]
I have no way to merge it as it is now unfortunately. How did you delete the fork ? Was it in your own repository on your machine ? 
If no other option, I would suggest to start over with a new PR, same files, and should be ready to merge right away.

**Comment by PipoCanaja** [comment]
Could be possible to workaround this. Hold on for the moment.

**Comment by mpikzink** [comment]
I deleted on my fork after the last merge. I just wanted to delete the branch and then I did this mistake - Anyway. Of course it's no big deal to make a new PR except of this little changes, but I want to learn how to fix this, in case of bigger PR requests in the future.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-61-release-changelog-february-2020/11145/1

**Pull request merged**
