### PR TITLE
refactor of daily.sh

### PR DESCRIPTION
**Pull request by Gorian**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

Refactored code of daily.sh. Replaced -ne with "!=", "[" with "[[", enforced better quotes usage, moved daily.php calls to a dedicated function, added support for using $config['log_dir'] from config.php for setting the log directory. Defaults to the value of $config['install_dir'] . '/logs' if $config['log_dir'] is not set. Properly moved all code not in a dedicated function to main().

### CODE REVIEW

**Comment by laf** [comment]
Tested and works for me. CentOS 7.

What have you tested against @Gorian ?

**Comment by Gorian** [comment]
@laf also CentOS7, same bash version.

**Comment by jonathon-k** [comment]
Works for me as far as I can tell.  Debian Jessie
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

**Comment by laf** [comment]
I think we need some older distros to test this on.

**Comment by murrant** [comment]
Tested on `GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)` too (although I didn't have a fully installed librenms there)

**Comment by laf** [comment]
Tagged to merge in 48 hours.

**Pull request merged**
