### PR TITLE
Update composer_wrapper to use http links

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Ref: https://github.com/librenms/librenms/pull/6920#issuecomment-368911038

### CODE REVIEW

**Comment by murrant** [comment]
What about users that only set http proxy?

**Comment by murrant** [comment]
Also, I started something similar here.  But I wasn't sure it was needed.  What do you think?
https://github.com/librenms/librenms/compare/master...murrant:https-composer

**Comment by laf** [comment]
I'd go with yours then? Can you add the composer version check fix and submit your branch?

**Comment by murrant** [comment]
Sure

**Pull request closed without merging**
