### PR TITLE
Cisco OTV

### PR DESCRIPTION
**Pull request by adaniels21487**
Implements the CISCO-OTV-MIB to retrieve OTV counters from Cisco devices.
This collects information on the configured Overlays and Adjacencies

Statistics are collected for the amount of VLAN's on each overlay and the amount of MAC addresses available over each OTV endpoint.
OTV alerts are collected and generated if the appropriate alerting rules exist.

Data is displayed under routing at both the global and device level.

Includes function snmpwalk_array_num, which performs a numeric SNMPWalk and returns an array containing $count indexes
One Index:
 From: 1.3.6.1.4.1.9.9.166.1.15.1.1.27.18.655360 = 0
 To: $array['1.3.6.1.4.1.9.9.166.1.15.1.1.27.18']['655360'] = 0
Two Indexes:
 From: 1.3.6.1.4.1.9.9.166.1.15.1.1.27.18.655360 = 0
 To: $array['1.3.6.1.4.1.9.9.166.1.15.1.1.27']['18']['655360'] = 0
And so on...

Have a play and let me know what you think.

Thanks,
Aaron

### CODE REVIEW

**Comment by laf** [comment]
:+1: from me again.

Although the same comment about uppercase variables as per the other PR.

**Comment by laf** [comment]
rrd updates seem to fail:

found extra data on update argument: U:0:57

So graphs don't show any data. This is via rrdcached.

**Comment by adaniels21487** [comment]
Hi @laf,
Thats not cool. Can you please unicast me the debug poller output for this module (lists@daniels.id.au).

Thanks,
Aaron

**Comment by adaniels21487** [comment]
Hi @laf,
I have pushed the lower case variable commit as well as adding some new debugging code.
Please send me the output of this and I will take a look.

Thanks,
Aaron

**Comment by laf** [comment]
Disco: https://gist.github.com/laf/a154c582705ba1472035

Poll: https://gist.github.com/laf/ef9850ada25e2b8877d4

**Comment by laf** [comment]
Updated gists, hadn't pulled in your changes :/

**Comment by laf** [comment]
Gentle nudge :)

**Comment by adaniels21487** [comment]
Hi @laf,
Sorry mate, I assumed that not pulling in my changes was the source of the problem..

Taking a look at the Gists, things look ok.
Discovery is creating the components, Polling is finding data.

The RRD lines look fine:

		VLAN Count: 8
	[RRD Disabled]RRD[update ././HOSTNAME/cisco-otv-Overlay0-vlan.rrd N:8 --daemon 192.168.100.154:42217]

		MAC Count: 0
	[RRD Disabled]RRD[update ././HOSTNAME/cisco-otv-FOUND-mac.rrd N:0 --daemon 192.168.100.154:42217]

		MAC Count: 48
	[RRD Disabled]RRD[update ././HOSTNAME/cisco-otv-FOUND-mac.rrd N:48 --daemon 192.168.100.154:42217]

		MAC Count: 55
	[RRD Disabled]RRD[update ././HOSTNAME/cisco-otv-FOUND-mac.rrd N:55 --daemon 192.168.100.154:42217]

I cant see the message you mentioned in the logs, does this only happen without -r ?

Aaron

**Comment by laf** [comment]
No we get that on rrdcached logs. I'll take another look next week when I'm back in work.

Thanks for getting back to me though.

**Comment by laf** [comment]
I have no idea wtf was going on when I first tried - graphs are working and did on that same day. I blame rrdcached :)

**Comment by laf** [comment]
Thanks for this pr @adaniels21487. Appreciate the help and support.

**Comment by adaniels21487** [comment]
no worries @laf, happy to help.

**Pull request merged**
