### PR TITLE
Timos yaml updates

### PR DESCRIPTION
**Pull request by peelman**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Review by craig-nokia — COMMENTED** [review]
Patch looks good, but we need to update the test data.

**Comment by peelman** [comment]
@craig @murrant Added test data from one of our largest 7750 SR-12's.  I sterilized it quite a bit, but should have all the testing bits for these changes in it.

**Comment by murrant** [comment]
@peelman looks like current test data contains current oids, so you need to update those.

**Comment by peelman** [comment]
> @peelman looks like current test data contains current oids, so you need to update those.

i don't follow...

**Comment by craig-nokia** [comment]
I think it is safe to delete the old tests/data/timos.json and maybe timos_7705.json.

**Comment by Jellyfrog** [comment]
First of all, thank you for your contribution!

We're closing this due to inactivity, feel free to reopen if you find the time to continue on this!

**Pull request closed without merging**
