### PR TITLE
Update Sensors for ADVA FSP150CC + discovery fix

### PR DESCRIPTION
**Pull request by keryazmi**
Hi,

Please refer summary below:

**State Sensors**
- ERP State
- Alarm Condition State

**Temperature Sensors**
- Add more devices/modules

**Voltage**
- Add more devices/modules

**Pre-Cache Sensors**
- Add for model XG116ProH, XG120Pro and EG-X

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by keryazmi** [comment]
Hi,

I am still get the following error.

```
>> SNMP: [29/2.12s] MySQL: [38/0.03s]
#### Unload disco module sensors ####
OS adva_fsp150: Discovered sensors data does not match that found in tests/data/adva_fsp150_xg116pro.json
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         1 => Array (...)
         2 => Array (...)
         3 => Array (...)
+        4 => Array (...)
     )
     'state_indexes' => Array ()
 )

/home/runner/work/librenms/librenms/tests/OSModulesTest.php:122

FAILURES!
Tests: 617, Assertions: 1266, Failures: 1.


Error: Process completed with exit code 1.
```

Since I create new test data with new variant should it compare with new data test instead existing one.

Appreciate your kind assistance.

**Comment by Jellyfrog** [comment]
You need to update existing test data also yes. 
Run the second command (that generates the json) but target the already existing device

**Comment by keryazmi** [comment]
Tried multiple times and compare between the snmprec and json file. 
Even the snmprec capture the data with single digit but the checks mention it capture decimal value.

Refer below:

```
Run php lnms dev:check ci
Running PHP lint check... success (0.17s)
Only checking os: adva_fsp150
Running unit check... 
failed (82.28s)
Starting snmpsim listening on 127.1.6.2:1162... 
Info: Refusing to reset main database: librenms_phpunit_78hunjuybybh.  Running migrations.
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

>> Runtime for discovery module 'sensors': 2.6750 seconds with 719104 bytes
>> SNMP: [33/2.56s] MySQL: [85/0.05s]
#### Unload disco module sensors ####
OS adva_fsp150: Discovered sensors data does not match that found in tests/data/adva_fsp150_xg116proh.json
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.1.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsLBC.1.1.1.1'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-1 BIAS'
+            'sensor_descr' => ' BIAS'
             'group' => null
             'sensor_divisor' => 1000
             'sensor_multiplier' => 1
-            'sensor_current' => 8
+            'sensor_current' => 8.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.7.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsLBC.1.1.1.7'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-7 BIAS'
+            'sensor_descr' => ' BIAS'
             'group' => null
             'sensor_divisor' => 1000
             'sensor_multiplier' => 1
-            'sensor_current' => 60
+            'sensor_current' => 60.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.8.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsLBC.1.1.1.8'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-8 BIAS'
+            'sensor_descr' => ' BIAS'
             'group' => null
             'sensor_divisor' => 1000
             'sensor_multiplier' => 1
-            'sensor_current' => 86
+            'sensor_current' => 86.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.1.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsOPR.1.1.1.1'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-1 Rx Power'
+            'sensor_descr' => ' Rx Power'
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => -5
+            'sensor_current' => -5.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.7.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsOPR.1.1.1.7'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-7 Rx Power'
+            'sensor_descr' => ' Rx Power'
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => -4
+            'sensor_current' => -4.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.8.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsOPR.1.1.1.8'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-8 Rx Power'
+            'sensor_descr' => ' Rx Power'
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => -15
+            'sensor_current' => -15.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.1.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsOPT.1.1.1.1'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-1 Tx Power'
+            'sensor_descr' => ' Tx Power'
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => -5
+            'sensor_current' => -5.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.7.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsOPT.1.1.1.7'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-7 Tx Power'
+            'sensor_descr' => ' Tx Power'
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => 1
+            'sensor_current' => 1.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.8.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsOPT.1.1.1.8'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-8 Tx Power'
+            'sensor_descr' => ' Tx Power'
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => 1
+            'sensor_current' => 1.0
             'sensor_limit' => null
             'sensor_limit_warn' => null
             'sensor_limit_low' => null
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.1.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsTemp.1.1.1.1'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-1'
+            'sensor_descr' => null
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => 33
-            'sensor_limit' => 53
+            'sensor_current' => 33.0
+            'sensor_limit' => 53.0
             'sensor_limit_warn' => null
-            'sensor_limit_low' => 23
+            'sensor_limit_low' => 23.0
             'sensor_limit_low_warn' => null
             'sensor_alert' => 1
             'sensor_custom' => 'No'
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.7.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsTemp.1.1.1.7'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-7'
+            'sensor_descr' => null
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => 32
-            'sensor_limit' => 52
+            'sensor_current' => 32.0
+            'sensor_limit' => 52.0
             'sensor_limit_warn' => null
-            'sensor_limit_low' => 22
+            'sensor_limit_low' => 22.0
             'sensor_limit_low_warn' => null
             'sensor_alert' => 1
             'sensor_custom' => 'No'
@@ @@
             'sensor_oid' => '.1.3.6.1.4.1.2544.1.12.5.1.21....1.8.3'
             'sensor_index' => 'cmEthernetTrafficPortStatsTemp.1.1.1.8'
             'sensor_type' => 'adva_fsp150'
-            'sensor_descr' => 'ETH PORT-1-1-1-8'
+            'sensor_descr' => null
             'group' => null
             'sensor_divisor' => 1
             'sensor_multiplier' => 1
-            'sensor_current' => 38
-            'sensor_limit' => 58
+            'sensor_current' => 38.0
+            'sensor_limit' => 58.0
             'sensor_limit_warn' => null
-            'sensor_limit_low' => 28
+            'sensor_limit_low' => 28.0
             'sensor_limit_low_warn' => null
             'sensor_alert' => 1
             'sensor_custom' => 'No'

/home/runner/work/librenms/librenms/tests/OSModulesTest.php:122

FAILURES!
Tests: 618, Assertions: 1274, Failures: 1.
```

**Comment by PipoCanaja** [comment]
Hi @keryazmi 
I have the same issue you have, save-test-data seems to do it right, but the regression test (even when I run it on my machine) finds other results. I can't explain it for hte moment. I'll keep searching and let you know. 
Bye

**Comment by PipoCanaja** [comment]
Hi @keryazmi 
The existing ADVA discovery code was somehow "dirty". And one of those dirty pieces was killing the regression test (race condition issue). 
This should be fixed now (even if the code would need more cleaning).

**Review by PipoCanaja — APPROVED** [review]
LGTM. Thanx @keryazmi !

**Comment by keryazmi** [comment]
Hi @PipoCanaja,
I've tested it with my machine and it run perfectly.
I never thought the snmp and db call function require to replace and use the pre cache function to centralized it.
I'm glad you help it before the new release soon.

Many thanks and really appreciate for your assistance. 👍

**Review by keryazmi — COMMENTED** [review]
Hi @PipoCanaja,

I'm just find out on line 72 should be `cmEthernetNetPortIfIndex` instead of `cmEthernetTrafficPortIfIndex`.

**Comment by PipoCanaja** [comment]
> Hi @PipoCanaja,
> 
> I'm just find out on line 72 should be `cmEthernetNetPortIfIndex` instead of `cmEthernetTrafficPortIfIndex`.

OK. Please just open a new PR for this, I'll review it right away and merge it.

**Comment by PipoCanaja** [comment]
All good @keryazmi 
Thanx

**Pull request merged**
