### PR TITLE
Add initial OS detection for LoadBalancer.org

### PR DESCRIPTION
**Pull request by cjwbath**
Add initial OS detection for Loadbalancer.org OS, formerly detected as Linux

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [X] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [X] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [X] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by cjwbath** [comment]
Sorry, I committed as the wrong author. Now amended but don't know if that will clear the CLA whinge.

**Comment by Jellyfrog** [comment]
They are not amended yet

**Comment by cjwbath** [comment]
How do I get out of this mess? My git skills aren't good enough. Is adding a second email address to my Github account and accepting the CLA again the only way?

**Comment by cjwbath** [comment]
I fixed all the authors and (I think) accepted the CLA under the erroneous author email but that check still won't pass. Please just review this on its technical merits and accept anyway if OK - there are tests now.

**Comment by murrant** [comment]
Author on one of the commits is different than your github id.  I'll just merge this as you have signed the cla with your github account.

**Pull request merged**
