### PR TITLE
Added option to always update value and value_prev in Applications

### PR DESCRIPTION
**Pull request by TheGreatDoc**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)
- [] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
Its hard to determine... I could do it by application instead.

**Comment by TheGreatDoc** [comment]
I'm unsure on how to rebase. Any tip?

**Comment by murrant** [comment]
```bash
git fetch upstream
git checkout app-always-update-prev
git rebase upstream/master
```
edit html/mix-manifest.json and resolve conflict
`git rebase --continue`

**Comment by murrant** [comment]
You should just add _prev values on a per-value basis I think.  minimal is better.

**Comment by TheGreatDoc** [comment]
New PR https://github.com/librenms/librenms/pull/11941 so I dont have to rebase ;)

**Pull request closed without merging**
