### PR TITLE
Update IronWare sensors & bgp-peers discovery, allow skip_values to target a specific index appended to the OID

### PR DESCRIPTION
**Pull request by martijn-schmidt**
This PR updates the sensors and bgp-peers discovery for ironware.

- Migrated pre-cache/dbm sensors from PHP to YAML, output from a user's perspective is identical.
- Added support for Tx Bias Current detection in transceivers. This appears to be supported in the NetIron platform but not on the ICX series.
- Migrated state sensors from PHP to YAML:
-- Power Supply output from a user's perspective is identical.
-- Added support for Fan status detection.
-- For the ICX platform we now also have Stacking Config detection, and if that is enabled then also Stacking Unit and Stacking Port detection.
- Migrated temperature sensors from PHP to YAML:
-- Module Temperature behaviour is slightly different from a user's perspective since I can't replicate all the `descr` rewrites from PHP.
-- Added support for Tx Laser temperature detection in transceivers. This appears to be supported in the NetIron platform but not on the ICX series.
- Rewrote bgp-peers to correct the discovery process for BGP sessions with 32-bit ASNs and/or IPv6 neighbors using the BGP4V2-MIB, which is based on draft-ietf-idr-bgp4-mibv2-11. I copied most of the code from PR #8877 by @Mikeburke14, cleaned up the code a little bit to match the normal LibreNMS style, and fixed bgpPeers_cbgp discovery.
- Also started polling for IPv4 unicast received routes in bgpPeers_cbgp through the FOUNDRY-SN-BGP4-GROUP-MIB.
- Note that older Brocade IronWare firmware versions are known to have multiple defects relating to the BGP4V2-MIB which might result in certain missing non-established neighbors. Related vendor defect numbers are DEFECT000550309, DEFECT000583319, DEFECT000633962 and can be found in the vendor's release notes.

In all cases where a sensor was migrated from PHP to YAML I have kept the old index so users don't lose their historical data during the rediscovery process. As a result the index naming might not be fully compliant with the instructions from the documentation for some sensors, but I think it's the lesser evil.

The duplicate function `dynamic_discovery_get_value()` was removed in favour of `YamlDiscovery::getValueFromData`. I added another match condition in `YamlDiscovery::getValueFromData()` and corrected `@param string $index` since that variable may contain periods. There's a new if clause in `YamlDiscovery::canSkipItem()` to allow for skip_values to target a specific index that is manually appended to the OID, of course it still defaults to the index of the sensor which is being discovered. The documentation has been updated to reflect this new YAML discovery feature.

Finally, I have removed the now-obsoleted function `return_num()` which was only used for the PHP-based ironware dbm sensor discovery. YAML discovery deals with this automatically so the PHP function was no longer needed.

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 10941`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by PipoCanaja** [comment]
Hi @martijn-schmidt 
Nice evolution of the skip_value syntax. That does extend possibilities without adding too much complexity in the code and in the yaml file. 
Waiting for test data and some feedbacks from testers as well.

**Comment by martijn-schmidt** [comment]
Ok @PipoCanaja - the test data is available and as such the PR should be ready for review now. Since I went through the trouble of building a lab with a CER router I also incorporated most of the code changes from my colleague @Mikeburke14's PR #8877 relating to Brocade-specific BGP discovery and polling.

**Comment by Jellyfrog** [comment]
@martijn-schmidt it would be great if we can keep the old test data also

**Comment by martijn-schmidt** [comment]
Hello @Jellyfrog - the old test data pretty much consisted of one CPU sensor from an ICX7250-24 besides the standard generic OIDs like sysDescr, sysObjectID, sysUpTime which all came from a NetIron MLXe. The new test data contains multiple CPU sensors from a NetIron CER, and data about those CPU sensors lives at the same OID regardless of whether one is polling a NetIron or ICX series device.

So overall I think nothing has been lost, I've only replaced some things with new data so that everything consistently comes from the NetIron platform, with the exception of the `sensors` module for which I've also collected test data from the ICX platform related to the stack-link monitoring sensors that don't exist on the NetIron platform.

**Comment by PipoCanaja** [comment]
Hi @martijn-schmidt 
Could you rebase your PR in order to solve the issue with the test data ? (a PR was merged in the interval and it touched the ironware.json file). 
Thanx

**Comment by martijn-schmidt** [comment]
Hi @PipoCanaja - job's done, should be good to merge again.

**Comment by PipoCanaja** [comment]
@Jellyfrog Good for me, feel free to merge it if it is also OK with you.

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/brocade-bgp-broken/10830/3

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/brocade-bgp-broken/10830/4

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-60-release-changelog-january-2020/10863/1

**Pull request merged**
