### PR TITLE
Add Synology Hardware/Version/Serial detection

### LINKED ISSUE #7957: Synology platform and serial info not shown
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.

- [x ] Please include all of the information between the 
Component | Version
--------- | -------
LibreNMS  | 1.33-274-g27368a2
DB Schema | 226
PHP       | 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
MySQL     | 5.6.38
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

- [x ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
https://p.libren.ms/view/bdde5d7a
https://p.libren.ms/view/b6bf1b90
https://p.libren.ms/view/2a80562a

- [x ] Please provide as much detail as possible.
Synology platform and serial info not showing for DS916+ and DS214+
Both are running version DSM 6.1.4-15217 Update 5

Info is in:
Platform:        .1.3.6.1.4.1.6574.1.5.1.0 = STRING: "DS916+"
Serial:             .1.3.6.1.4.1.6574.1.5.2.0 = STRING: "1760NZN021504"

- [x ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

### PR DESCRIPTION
**Pull request by peelman**
Fixes #7957

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
Would you be willing to add test data for this?

https://docs.librenms.org/Developing/os/Test-Units/

**Comment by peelman** [comment]
@murrant like that?

**Comment by laf** [comment]
Close :)

It's got the data we need but it also needed some json data generating off the back of it. I've done that in this branch for you so you can check the changes and see what's different. Just an FYI, your install is way out of date so didn't include the script to generate this test data anyway - you should upgrade :)

**Comment by peelman** [comment]
Yeah I noticed that after I pushed.  Has since been corrected.

Later today, I will similarly fix #8086 based off of your example here.  Thanks!

**Pull request merged**
