### PR TITLE
Reordering voltage and current sensor items (fixes librenms/librenms#1260)

### PR DESCRIPTION
**Pull request by einhirn**
Changed $index values so "Output phase 1", "Output phase 2" and "Output phase 3" are listed together.

### CODE REVIEW

**Comment by laf** [comment]
@einhirn Do you mean listed together in the WebUI and if so do you mean the order?

**Comment by einhirn** [comment]
Yes, sorry for not referencing #1260 - I pasted a listing from before this patch there. The "$index"-Values for "output phase" are 1,2,3 which gets sorted in between 10x indices for input phases and the 20x-Indices for bypass lines.

**Comment by laf** [comment]
@einhirn If it's just webui then we will be better to sort within that. Changing the index for existing sensors means people lose historic data which we can't really do.

**Comment by einhirn** [comment]
Oh of course - I saw that effect but thought nothing of it.
Changing in WebUI: Hmm - it would suffice to sort indices numerically. Currently it sorts the sensors like
```
1
101
102
103
2
201
202
203
3
500
```
with 1,2,3 being the output lines.
But I don't know where to look for changing the sorting in the webui.
Anyway I'll close this pull request and will change #1260 according to the new info

**Pull request closed without merging**
