### PR TITLE
Fortigate ipv6 ipsec tunnels

### PR DESCRIPTION
**Pull request by fbourqui**
https://docs.fortinet.com/document/fortigate/6.4.0/new-features/32869/snmp-polling-extensions-to-support-new-oids-6-4-2
New OIDs are added in fgVpn to support SNMP query for IPv4 and IPv6 IPsec tunnels
fgVpn2TunTable 1.3.6.1.4.1.12356.101.12.4.2

The old OID used by librenms was only listing IPSec tunnel using ipv4 endpoint, ignoring all ipv6 tunnels:
fgVpnTunEntStatus from fgVpnTunTable 1.3.6.1.4.1.12356.101.12.2.2

This new OID is available since Fortigate version 6.4.2 released on 2020-07-30

need an active support contract to access: https://support.fortinet.com/Information/ProductLifeCycle.aspx
```
FortiOS Release Date (GA)   End of Engineering      End of Support
Version                     Support Date (EOES)     Date (EOS)
5.4     2015-12-21          2018-12-21              2020-06-21
5.6     2017-03-30          2020-03-30              2021-09-30
6.0     2018-03-29          2021-03-29              2022-09-29
6.2     2019-03-28          2022-03-28              2023-09-28
6.4     2020-03-31          2023-03-31              2024-09-30
7.0     2021-03-30          2024-03-30              2025-09-30
7.2     2022-03-31          2025-03-31              2026-09-30
7.4     2023-05-11          2026-05-11              2027-11-11
```

publicly available infos: https://endoflife.date/fortios

here is the output of a walk from my test device (for which I subited test data):

```
librenms@ubuntu:~$ snmpbulkwalk -v2c -c public-m +FORTINET-FORTIGATE-MIB fgt-vm01 fgVpnTunTable
FORTINET-FORTIGATE-MIB::fgVpnTunEntPhase1Name.1.2 = STRING: ipv4tunnel
FORTINET-FORTIGATE-MIB::fgVpnTunEntPhase2Name.1.2 = STRING: ipv4tunnel
FORTINET-FORTIGATE-MIB::fgVpnTunEntRemGwyIp.1.2 = IpAddress: 192.168.199.2
FORTINET-FORTIGATE-MIB::fgVpnTunEntRemGwyPort.1.2 = Gauge32: 0   
FORTINET-FORTIGATE-MIB::fgVpnTunEntLocGwyIp.1.2 = IpAddress: 192.168.199.1
FORTINET-FORTIGATE-MIB::fgVpnTunEntLocGwyPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorSrcBeginIp.1.2 = IpAddress: 10.10.1.0
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorSrcEndIp.1.2 = IpAddress: 10.10.1.255
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorSrcPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorDstBeginIp.1.2 = IpAddress: 10.20.1.0
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorDstEndIp.1.2 = IpAddress: 10.20.1.255
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorDstPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntSelectorProto.1.2 = INTEGER: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntLifeSecs.1.2 = Gauge32: 42901
FORTINET-FORTIGATE-MIB::fgVpnTunEntLifeBytes.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntTimeout.1.2 = Gauge32: 20323
FORTINET-FORTIGATE-MIB::fgVpnTunEntInOctets.1.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntOutOctets.1.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpnTunEntStatus.1.2 = INTEGER: up(2)
FORTINET-FORTIGATE-MIB::fgVpnTunEntVdom.1.2 = INTEGER: 1


librenms@ubuntu:~$ snmpbulkwalk -v2c -c public -m +FORTINET-FORTIGATE-MIB fgt-vm01 fgVpn2TunTable
FORTINET-FORTIGATE-MIB::fgVpn2TunPhase1Name.1.2 = STRING: ipv4tunnel
FORTINET-FORTIGATE-MIB::fgVpn2TunPhase1Name.2.3 = STRING: ipv6tunnel
FORTINET-FORTIGATE-MIB::fgVpn2TunPhase1Name.2.5 = STRING: ipv6tunnel
FORTINET-FORTIGATE-MIB::fgVpn2TunPhase2Name.1.2 = STRING: ipv4tunnel
FORTINET-FORTIGATE-MIB::fgVpn2TunPhase2Name.2.3 = STRING: extraph2
FORTINET-FORTIGATE-MIB::fgVpn2TunPhase2Name.2.5 = STRING: ipv6tunnel
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyIpType.1.2 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyIpType.2.3 = INTEGER: ipv6(2)
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyIpType.2.5 = INTEGER: ipv6(2)
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyIp.1.2 = Hex-STRING: C0 A8 C7 02 
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyIp.2.3 = Hex-STRING: FD A8 CA FE 32 EE 00 00 00 00 00 00 00 00 00 02 
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyIp.2.5 = Hex-STRING: FD A8 CA FE 32 EE 00 00 00 00 00 00 00 00 00 02 
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyPort.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunRemGwyPort.2.5 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyIpType.1.2 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyIpType.2.3 = INTEGER: ipv6(2)
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyIpType.2.5 = INTEGER: ipv6(2)
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyIp.1.2 = Hex-STRING: C0 A8 C7 01 
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyIp.2.3 = Hex-STRING: FD A8 CA FE 32 EE 00 00 00 00 00 00 00 00 00 01 
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyIp.2.5 = Hex-STRING: FD A8 CA FE 32 EE 00 00 00 00 00 00 00 00 00 01 
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyPort.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLocGwyPort.2.5 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcBeginIpType.1.2 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcBeginIpType.2.3 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcBeginIpType.2.5 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcBeginIp.1.2 = Hex-STRING: 0A 0A 01 00 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcBeginIp.2.3 = Hex-STRING: 0A 0A 03 00 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcBeginIp.2.5 = Hex-STRING: 0A 0A 02 00 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcEndIpType.1.2 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcEndIpType.2.3 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcEndIpType.2.5 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcEndIp.1.2 = Hex-STRING: 0A 0A 01 FF 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcEndIp.2.3 = Hex-STRING: 0A 0A 03 FF 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcEndIp.2.5 = Hex-STRING: 0A 0A 02 FF 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcPort.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelSrcPort.2.5 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstBeginIpType.1.2 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstBeginIpType.2.3 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstBeginIpType.2.5 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstBeginIp.1.2 = Hex-STRING: 0A 14 01 00 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstBeginIp.2.3 = Hex-STRING: 0A 14 03 00 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstBeginIp.2.5 = Hex-STRING: 0A 14 02 00 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstEndIpType.1.2 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstEndIpType.2.3 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstEndIpType.2.5 = INTEGER: ipv4(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstEndIp.1.2 = Hex-STRING: 0A 14 01 FF 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstEndIp.2.3 = Hex-STRING: 0A 14 03 FF 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstEndIp.2.5 = Hex-STRING: 0A 14 02 FF 
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstPort.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstPort.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelDstPort.2.5 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelProto.1.2 = INTEGER: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelProto.2.3 = INTEGER: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunSelProto.2.5 = INTEGER: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLifeSecs.1.2 = Gauge32: 42901
FORTINET-FORTIGATE-MIB::fgVpn2TunLifeSecs.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLifeSecs.2.5 = Gauge32: 42897
FORTINET-FORTIGATE-MIB::fgVpn2TunLifeBytes.1.2 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLifeBytes.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunLifeBytes.2.5 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunTimeout.1.2 = Gauge32: 20082
FORTINET-FORTIGATE-MIB::fgVpn2TunTimeout.2.3 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunTimeout.2.5 = Gauge32: 20191
FORTINET-FORTIGATE-MIB::fgVpn2TunInOctets.1.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunInOctets.2.3 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunInOctets.2.5 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunOutOctets.1.2 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunOutOctets.2.3 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunOutOctets.2.5 = Counter64: 0
FORTINET-FORTIGATE-MIB::fgVpn2TunStatus.1.2 = INTEGER: up(2)
FORTINET-FORTIGATE-MIB::fgVpn2TunStatus.2.3 = INTEGER: down(1)
FORTINET-FORTIGATE-MIB::fgVpn2TunStatus.2.5 = INTEGER: up(2)
FORTINET-FORTIGATE-MIB::fgVpn2TunVdom.1.2 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgVpn2TunVdom.2.3 = INTEGER: 1
FORTINET-FORTIGATE-MIB::fgVpn2TunVdom.2.5 = INTEGER: 1
```

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by fbourqui** [comment]
No idea why two DB checks are failing, mariadb 10.11 is ok, older not, seems to be a common issue.
I'm running this change on my prod server monitoring 7 Fortigate clusters, with more than 100 IPSEC tunnels, using a mix of ipv4 and ipv6 endpoints.

Anyone wants to comment, test ?

**Comment by fbourqui** [comment]
Hello,

Could anyone have a look at this pull request ? I've been running it in my production system for a month without any problems,

Thanks

**Comment by electrocret** [comment]
> Hello,
> 
> Could anyone have a look at this pull request ? I've been running it in my production system for a month without any problems,
> 
> Thanks

Can you please address the merge conflicts? Thanks

**Comment by fbourqui** [comment]
> > Hello,
> > Could anyone have a look at this pull request ? I've been running it in my production system for a month without any problems,
> > Thanks
> 
> Can you please address the merge conflicts? Thanks

Hi, not sure how I can resolve the merge conflict:

```
<<<<<<< fortigate-ipv6-ipsec-tunnels
                    // allow parsing of InetAddress hex data representing ipv4 or ipv6
                    // using {{ $InetAddress_varNameContainingHexIpAddrOfTypeInetAddress }}
                    // -Ih flag screew up HEX string that contain only printable chars, use at minimum -Ox, and remove -Ih use for exemple:
                    // snmp_flags: '-OteQUsax'
                    // snmp_no_Ih_flag: ''
                    if (str_starts_with($matches[1], 'InetAddress_')) {
                        $inetaddr = explode('_', $matches[1]);
                        if (count($inetaddr) == 2) {
                            return IP::fromHexString(static::getValueFromData($inetaddr[1], $index, $def, $pre_cache), true);
                        }
                    }
=======
>>>>>>> master
```

As I do not see any conflict, it's just a few lines added to the existing code, I've already added the change done on master on the line just after my change :
\Log::warning('YamlDiscovery: No variable available to replace ' . $matches[1] **. ' index: ' . $index**);

**Pull request closed without merging**
