### PR TITLE
Split PBN os to two different

### PR DESCRIPTION
**Pull request by vitalisator**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ x ] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [ x ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

 Split PBN os poller and discovery

### CODE REVIEW

**Comment by laf** [comment]
I'm not one for more device types but especially CPE as it's not really a type of device but more a term for where a device goes (assuming this is customer premises equipment meaning).

**Comment by vitalisator** [comment]
hmm, in ISP environment I need something to delimit between ISP own and customer premises devices.
I could tried that with groups. Then I would leave the os splitting between them

**Comment by Rosiak** [comment]
I fully understand the need you are trying to address, but I completely agree with @laf.

**Comment by vitalisator** [comment]
ok guys, I agree. 
I removed the extra device type.
Please merge.

**Comment by laf** [comment]
But you've still split PBN into two os definitions. This is the same thing as creating a new device type in essence.

You really need to deal with this via device groups or something else.

**Comment by vitalisator** [comment]
yes, and that is right in the point of view that PBN L3 switch use completely different operating system that a PBN CPE. In fact the products are manufactured from different producer. L3 products are from BDCOM.
So I should have done this from the beginning
Or I have not understood the matter with the os correctly?

**Comment by laf** [comment]
If it's truley a different os then no they should be separate. The os name doesn't seem right though, what do they call it?

**Comment by laf** [comment]
@vitalisator any update?

**Comment by vitalisator** [comment]
the call them:
-----
PBN P2P CP100 Series Platform.
Copyright, 2011 Pacific Broadband Networks.
---
so I could call the os "pbn-cp100" ?

**Comment by laf** [comment]
Looks like they have cp110 and cp120's so possibly not.

I'm only asking the question. pbn-cpe might be fine (pbn-cp maybe). I'll leave it up to you.

**Comment by vitalisator** [comment]
pbn-cp100 make sense, that is the internal term for all CP1xx devices.
please merge.

**Comment by laf** [comment]
I know I said I'll leave it up to you but I don't think a devices model is ideal as the os name - cpe or cp would have been better. @librenms/reviewers thoughts?

**Pull request merged**
