### PR TITLE
Fix Smartoptics skip_values

### PR DESCRIPTION
**Pull request by electrocret**
I got the logic backwards in #16284

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by electrocret** [comment]
Saving test data on my dev box is having issues, I'll regenerate the Test data from the SNMP data whenever I have time to get that fixed.

**Comment by murrant** [comment]
@electrocret can you try `.python_venvs/snmpsim/bin/pip install --upgrade pip`?

**Comment by electrocret** [comment]
> @electrocret can you try `.python_venvs/snmpsim/bin/pip install --upgrade pip`?
@murrant It's not complaining about pip anymore, but still not working.
image

**Comment by murrant** [comment]
Try this `.python_venvs/snmpsim/bin/pip install 'snmpsim>=1.1.7'`

**Review by laf — APPROVED** [review]
I've regenerated the test data. 

LGTM once tests pass

**Comment by electrocret** [comment]
Thank you @laf

**Pull request merged**
