### PR TITLE
Added FibroLAN devices

### PR DESCRIPTION
**Pull request by Jarod2801**
Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jarod2801** [comment]
Hm, stills fails.
Looks like because of a bad character of the SysDesc.
The manufacturer uses the character "µ", which causes the error.
LibreNMS displays it as a "?".
Is there a way to replace such charcters?

**Comment by murrant** [comment]
This is actually net-snmp outputting the binary character. 

LibreNMS has a function called StringHelpers::inferEncoding() but currently it is not called for sysDescr.  Adding that to wherever sysDescr is fetched, might fix the broken encoding.

**Comment by Jarod2801** [comment]
> This is actually net-snmp outputting the binary character.
> 
> LibreNMS has a function called StringHelpers::inferEncoding() but currently it is not called for sysDescr. Adding that to wherever sysDescr is fetched, might fix the broken encoding.

OK.
But sysDescr isn't fetched explicit. I think it comes per default when fetching the basic device information. 
Any way to fetich it "manually" in the yaml file.

Or are there changes needed "deeper" in the code to resolve the problem?

**Comment by Jarod2801** [comment]
Removed the "faulty device" for now, as we need the features on the other devices. Will have a look on the character issue later.

**Review by murrant — APPROVED** [review]

**Pull request merged**
