### PR TITLE
Unbundle javascript language files

### PR DESCRIPTION
**Pull request by murrant**
automatically generated for each install with `php artisan vue-i18n:generate --multi-locales --format=umd`
however, unless `npm run prod` is executed, the cache won't be busted...
This will reduce app.js churn a lot

DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [X] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

**Comment by Jellyfrog** [comment]
Seems like you forgot to run `./lnms vue-i18n:generate --multi-locales --format=umd` :)

**Comment by murrant** [comment]
@Jellyfrog I was thinking of figuring out how mix generates its hashes so we could replicate it in PHP.

**Comment by Jellyfrog** [comment]
> @Jellyfrog I was thinking of figuring out how mix generates its hashes so we could replicate it in PHP.

`return md5(this.read()).substr(0, 20);`
https://github.com/JeffreyWay/laravel-mix/blob/03cbfc7102a58f5d16c95c72b9b76f92c6dba8fd/src/File.js#L173

But I don't think we should do that, I would much rather gitignore these generated files and add a requirement on nodejs and generate these files on the fly also.

**Comment by murrant** [comment]
I could go either way.

I want to merge this PR as is though, we can improve the developer experience in further PRs.

**Comment by Jellyfrog** [comment]
> I want to merge this PR as is though, we can improve the developer experience in further PRs.

Go for it, but there is a conflict now :D

**Comment by SourceDoctor** [comment]
@murrant 
after running daily.sh to get newest state in complete "global settings" section
language files are no more interpreted and only key strings where listed

could you take a look on what's going wrong, please?

**Comment by murrant** [comment]
@SourceDoctor what do you mean?

image

**Comment by SourceDoctor** [comment]
i mean this here:
as i see html/lang/js/  is empty
image

**Comment by murrant** [comment]
Did you run ./daily.sh???

**Comment by SourceDoctor** [comment]
i did,
after #10794 it was fixed :-)

**Comment by murrant** [comment]
Sure :)

**Comment by murrant** [comment]
This pull request has been mentioned on **LibreNMS Community**. There might be relevant details there:

https://community.librenms.org/t/v1-58-release-changelog-november-2019/10224/1

**Pull request merged**
