### PR TITLE
Refactor: Exclude modules from json test data when empty

### PR DESCRIPTION
**Pull request by laf**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

### CODE REVIEW

**Comment by murrant** [comment]
I think you only want to exclude the data when saving the json files.

Some where around line 580

**Comment by murrant** [comment]
But our testing relies on those arrays being present.  So that is why you are getting `null != array()` right now

**Comment by murrant** [comment]
I think this will do it:
```diff
--- LibreNMS/Util/ModuleTestHelper.php	(revision a80e970f064f483d30a753c59e6c76fdea3f56c3)
+++ LibreNMS/Util/ModuleTestHelper.php	(date 1523504631000)
@@ -578,6 +578,11 @@
 
             // insert new data, don't store duplicate data
             foreach ($data as $module => $module_data) {
+                // skip saving modules with no data
+                if (empty($module_data['discovery']) && empty($module_data['poller'])) {
+                    continue;
+                }
+
                 if ($module_data['discovery'] == $module_data['poller']) {
                     $existing_data[$module] = array(
                         'discovery' => $module_data['discovery'],
```

**Comment by murrant** [comment]
I think this does the trick:
```diff
--- LibreNMS/Util/ModuleTestHelper.php	(revision a80e970f064f483d30a753c59e6c76fdea3f56c3)
+++ LibreNMS/Util/ModuleTestHelper.php	(date 1523505867000)
@@ -578,6 +578,11 @@
 
             // insert new data, don't store duplicate data
             foreach ($data as $module => $module_data) {
+                // skip saving modules with no data
+                if ($this->dataIsEmpty($module_data['discovery']) && $this->dataIsEmpty($module_data['poller'])) {
+                    continue;
+                }
+
                 if ($module_data['discovery'] == $module_data['poller']) {
                     $existing_data[$module] = array(
                         'discovery' => $module_data['discovery'],
@@ -779,4 +784,15 @@
         }
         return $this->json_file;
     }
+
+    private function dataIsEmpty($data)
+    {
+        foreach ($data as $table_data) {
+            if (!empty($table_data)) {
+                return false;
+            }
+        }
+
+        return true;
+    }
 }
```

**Comment by laf** [comment]
Thanks @murrant.

I still don't know the testing code enough, never spent any time going through it :(

**Comment by murrant** [comment]
Yeah, also, it is not very readable.  Feel free to refactor it :)

**Pull request merged**
